### PR TITLE
german translation fix

### PR DESCRIPTION
**Pull request by Unterstrichmoepunterstrich**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4036)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[translations/de.ts, line 2476 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_VewPM7melnQfcR2tK:-K_VewPM7melnQfcR2tL:b-8hv4xn) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L2476)):*
> ```XML
>     </message>
>     <message>
>         <source>Size:</source>
> ```

Source string changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by sudden6** [comment]
*[translations/de.ts, line 900 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_a01TapIsPoS8am7vU:-K_a01TapIsPoS8am7vV:by4f2b) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L900)):*
> ```XML
>     <message>
>         <source>To new circle</source>
>         <translation>Zu neuer Gruppe</translation>
> ```

`Circle` zu `Gruppe` zu übersetzen ist in qTox etwas verwirrend, weil es dann zu Verwechslungen mit Gruppenchat kommen kann. mMn die korrekte Übersetzung wäre `Freundeskreis`, die ist aber lang und nicht sehr elegant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[translations/de.ts, line 588 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__wx9-9UnkZNSnheKH:-K__wx90wjEeFeqTqpQA:b-xdk69z) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L588)):*
> ```XML
>     <message>
>         <source>You&apos;re trying to send a sequential file, which is not going to work!</source>
>         <translation>Du versuchst das Senden einer sequentiellen Datei. Dies wird nicht funktionieren.</translation>
> ```

`Du versuchst eine sequenzielle Datei zu senden, dass wird nicht funktionieren!` klingt besser mMn.

---

*[translations/de.ts, line 651 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__xAFcBEwq0VadnTB7:-K__xAFd5d0ARALGQkni:b16ar3) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L651)):*
> ```XML
>     </message>
>     <message>
>         <source>Open all in a new window</source>
> ```

You can't change the source string, this has to be fixed in the code.

---

*[translations/de.ts, line 744 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__xNxjpnEf-Z47BHfY:-K__xNxjpnEf-Z47BHfZ:bt44hna) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L744)):*
> ```XML
>     <message>
>         <source>Filename</source>
>         <translatorcomment>filename</translatorcomment>
> ```

This comment doesn't really make sense, does it?

---

*[translations/de.ts, line 1056 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__xfJoCFtSDodj8QrW:-K__xfJp3K1XuKjHbIJy:b-obo7ao) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1056)):*
> ```XML
>     <message>
>         <source>Autostart</source>
>         <translation>Automatisch mit Betriebssystem starten</translation>
> ```

`Automatisch beim Anmelden starten` ?

---

*[translations/de.ts, line 1324 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__xuebzpXTwSZ39Fca:-K__xuebzpXTwSZ39Fcb:b-nv5pmr) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1324)):*
> ```XML
>     </message>
>     <message>
>         <source>Rename profile</source>
> ```

Again, that has to be fixed in the source.

---

*[translations/de.ts, line 1364 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__y1Q6JAxY3LjP1IKR:-K__y1Q6JAxY3LjP1IKS:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1364)):*
> ```XML
>     </message>
>     <message>
>         <source>Delete profile</source>
> ```

same

---

*[translations/de.ts, line 1426 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__y865nVGxAxrOzX91:-K__y866po26a51P6h8P:b-du1f5f) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1426)):*
> ```XML
>     <message>
>         <source>ToxMe service to register on.</source>
>         <translation>ToxMe Service zum registrieren</translation>
> ```

`ToxMe Dienst, bei dem du dich registrieren willst` ?

---

*[translations/de.ts, line 1488 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__yOwcYdpVISz1XW6C:-K__yOwdLsZ4Ifcfo1tl:b7xdvix) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1488)):*
> ```XML
>     <message>
>         <source>Update ToxMe entry</source>
>         <translation>Update ToxMe-Eintrag</translation>
> ```

`ToxMe Eintrag aktualisieren`

---

*[translations/de.ts, line 1492 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__yWDBiz8NJ2dLorut:-K__yWDBiz8NJ2dLoruu:b3lxpjg) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1492)):*
> ```XML
>     <message>
>         <source>Rename profile.</source>
>         <translation>Profil umbenennen</translation>
> ```

don't change the source string

---

*[translations/de.ts, line 1495 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__y_0_wOFpJcWXPM0J:-K__y_0_wOFpJcWXPM0K:b3lxpjg) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1495)):*
> ```XML
>     </message>
>     <message>
>         <source>Delete profile.</source>
> ```

don't change the source string

---

*[translations/de.ts, line 1674 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__z7I2Dmok7hRsynJ1:-K__z7I2Dmok7hRsynJ2:b-r00hyn) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1674)):*
> ```XML
>     <message>
>         <source>Load automatically checkbox</source>
>         <translation>Lade Auswahl automatisch</translation>
> ```

Die Übersetung passt Kontextmäßig nicht wirklich, sowas in der Art von "Kontrollkästchen um die Auswahl automatisch zu laden".

---

*[translations/de.ts, line 1944 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__zz3PqfvxeOkXqTN5:-K__zz3PqfvxeOkXqTN6:b-m37gsr) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1944)):*
> ```XML
>     <message>
>         <source>Unable to read this image.</source>
>         <translation>Dieses Bild kann nicht lesen werden.</translation>
> ```

`nicht gelesen werden`

---

*[translations/de.ts, line 2394 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_a-6ikZuCXUWsWLzna:-K_a-6ikZuCXUWsWLznb:b-sancn0) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L2394)):*
> ```XML
>     <message>
>         <source>Confirm password</source>
>         <translation>Bestätige Passwort</translation>
> ```

`Passwort bestätigen` ist hier glaube ich üblicher

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by Unterstrichmoepunterstrich** [comment]
*[translations/de.ts, line 900 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_a01TapIsPoS8am7vU:-K_a2h9Tl4OlCevpI9hd:be5xq78) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L900)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`Circle` zu `Gruppe` zu übersetzen ist in qTox etwas verwirrend, weil es dann zu Verwechslungen mit Gruppenchat kommen kann. mMn die korrekte Übersetzung wäre `Freundeskreis`, die ist aber lang und nicht sehr elegant.
</blockquote></details>

das stimmt, deswegen habe ich weiter unten extra Gruppenchat genommen. Jedenfalls klingt die die alte Übersetzung Kreis ziemlich komisch, weil das eher Geometrie erinnert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by Unterstrichmoepunterstrich** [comment]
*[translations/de.ts, line 1426 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__y865nVGxAxrOzX91:-K_a3p8x8CayFGpzIKQD:b-89y4m8) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1426)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`ToxMe Dienst, bei dem du dich registrieren willst` ?
</blockquote></details>

Hatte ich vorher drin stehen, allerdings dachte ich, dass ToxMe Service ein Gattungsbegriff oder ähnliches ist

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[translations/de.ts, line 900 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_a01TapIsPoS8am7vU:-K_aNwRwI6xL5d-hduCA:b3bvr9m) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L900)):*
<details><summary><i>Previously, Unterstrichmoepunterstrich wrote…</i></summary><blockquote>

das stimmt, deswegen habe ich weiter unten extra Gruppenchat genommen. Jedenfalls klingt die die alte Übersetzung Kreis ziemlich komisch, weil das eher Geometrie erinnert.
</blockquote></details>

Jap, ich hab nichts dagegen wenn Kreis nicht mehr vorkommt, aber da muss es doch noch eine andere Übersetzung als "Gruppe" geben...

---

*[translations/de.ts, line 1426 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K__y865nVGxAxrOzX91:-K_aON1Q8xbL8YQrj8dA:b-wthmpm) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L1426)):*
<details><summary><i>Previously, Unterstrichmoepunterstrich wrote…</i></summary><blockquote>

Hatte ich vorher drin stehen, allerdings dachte ich, dass ToxMe Service ein Gattungsbegriff oder ähnliches ist
</blockquote></details>

Eigentlich ist nur `ToxMe` einer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by Unterstrichmoepunterstrich** [comment]
*[translations/de.ts, line 900 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_a01TapIsPoS8am7vU:-K_akh1h6Od-mz_gut-7:bwqvm1s) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L900)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Jap, ich hab nichts dagegen wenn Kreis nicht mehr vorkommt, aber da muss es doch noch eine andere Übersetzung als "Gruppe" geben...
</blockquote></details>

Ich habe mal ein paar Synonyme heraus gesucht für die Bedeutung Gemeinschaft [n]:

Bande {f}, Clique {f}, Reihe {f}, Schar {f}, Team {n}, Trupp {m}, Truppe {f}, Verband {m}, Verein {m}, Gemeinde {f}, Kollektiv (n), Kolonne (f), Block {m}, Clan {m}, Gruppe {f}

Nun stellt sich die Frage, welches am Besten im Deutschen passt.
Wirklich passend ist eigentlich nur Gruppe, aber das wollen wir ja eben nicht nutzen. Gemeine klingt zu kirchlich, Truppe zu militärisch, Bande und Clique sehr salopp. Team beschreibt eher Leute die zusammen arbeiten/Dinge tun. Am ehesten passt dann noch Kollektiv, auch wenn es ggf. einen leicht kommunistischen Anstrich hat. Was denkst du?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[translations/de.ts, line 900 at r1](https://reviewable.io:443/reviews/qtox/qtox/4036#-K_a01TapIsPoS8am7vU:-K_eHvItC1pVzSC_PQ-5:ba91ql6) ([raw file](https://github.com/qtox/qtox/blob/5637658c3c0b3dae2d1f652e6b084b239f27ed27/translations/de.ts#L900)):*
<details><summary><i>Previously, Unterstrichmoepunterstrich wrote…</i></summary><blockquote>

Ich habe mal ein paar Synonyme heraus gesucht für die Bedeutung Gemeinschaft [n]:

Bande {f}, Clique {f}, Reihe {f}, Schar {f}, Team {n}, Trupp {m}, Truppe {f}, Verband {m}, Verein {m}, Gemeinde {f}, Kollektiv (n), Kolonne (f), Block {m}, Clan {m}, Gruppe {f}

Nun stellt sich die Frage, welches am Besten im Deutschen passt.
Wirklich passend ist eigentlich nur Gruppe, aber das wollen wir ja eben nicht nutzen. Gemeine klingt zu kirchlich, Truppe zu militärisch, Bande und Clique sehr salopp. Team beschreibt eher Leute die zusammen arbeiten/Dinge tun. Am ehesten passt dann noch Kollektiv, auch wenn es ggf. einen leicht kommunistischen Anstrich hat. Was denkst du?
</blockquote></details>

Mir ist noch eine andere Idee gekommen, in der Core Bibliothek wird der Gruppenchat" als "Konferenz" bezeichnet, Ich denke das wäre eine elegante Lösung. Dann übersetzen wir "Circle" zu "Gruppe" und "groupchat" zu "Konferenz".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4036)*

**Pull request closed without merging**
