### PR TITLE
Make whole icon change colour to orange when blinking on new event

### LINKED ISSUE #2273: [Proposal] change of blinking icon on new message
hi all,
I've try some Tox client on different OS.
On windows, i cannot see new messages because the icon change (green to orange) is not so easy to notice.
When i look at µTox we have real changes to catch the new message (+notification), the icon become red, and that is easy to see.
sans titre 1

I think It will be better to do the same.

### PR DESCRIPTION
**Pull request by zetok**
Previous ones blinked with only small status dot, which was hardly visible.
Now blinking icon should be a lot more visible.

closes #2273 

https://d.maxfile.ro/wlyrvixwhi.webm

### CODE REVIEW

**Comment by agilob** [comment]
Test it with http://www.color-blindness.com/coblis-color-blindness-simulator/ before introducing potential regression.

**Comment by zetok** [comment]
@agilob I'm not sure how am I supposed to test it - I've saved icon as .png and uploaded there, but when I've tried to change mode from `Normal Color Vision` to something else, only default images showed up.

**Comment by jin-eld** [comment]
Would be great to have a more prominent notification, I keep overseeing it when only the circle inside the lock is blinking, so I'd be happy to see this one merged :)

**Comment by zetok** [comment]
@agilob ok, so, basically, what is the regression here, given that currently even non-colour-blind people can't see the notification?

I.e. is there a reason to not merge it?

**Comment by agilob** [comment]
Could change the commit and add this image as second? taskbar_icon_orange_green.svg (or something like that), I can clearly see current blinking icon. The one from this commit is too aggressive for me. I can add icon setter as setting parameter loaded on startup (but without GUI to change it).

**Comment by zetok** [comment]
@agilob yeah, I guess - although I'm not so sure that adding yet another setting is a good idea.

**Comment by zetok** [comment]
@agilob ok, done.

**Pull request merged**
