### PR TITLE
fix(videoframe): Added buffer alignment between lines

### PR DESCRIPTION
**Pull request by Diadlo**
Fixed warning from #3527. Not sure, that fix issue.

### CODE REVIEW

**Comment by zetok** [comment]
on 824dd56d443c9c0d8b25e3b64017a642a16968f3
- [ ] fixes the crash, but introduces regression; on the receiving side:
  
  dat image
- [ ] even though log says
  
  ```
  [20:15:25.373] src/widget/form/chatform.cpp:324 : Debug: onAvStart
  [20:15:25.374] src/widget/form/chatform.cpp:648 : Debug: creating netcam
  [20:15:25.376] src/video/netcamview.cpp:88 : Debug: SIZER QRect(0,0 0x0)
  Lost packet
  Lost packet
  [20:15:38.078] src/video/camerasource.cpp:219 : Debug: Opening device  "x11grab#:0.0"
  [swscaler @ 0x5555580fcfe0] Warning: data is not aligned! This can lead to a speedloss
  ```
  
  whole screen is being streamed

**Comment by Diadlo** [comment]
@zetok Are you sure, that it's fix crash? It seems that bug reproduce only when exist problem with opening (random)

**Comment by zetok** [comment]
> It seems that bug reproduce only when exist problem with opening (random)

I could reliably reproduce, and now I can't, so it looks fixed to me.

**Comment by Diadlo** [comment]
@zetok Can you test it now?

**Comment by zetok** [comment]
on 075762c011d18b076113534f768ac75c3797ce10 still the same

**Comment by Diadlo** [comment]
Warning fixed

**Comment by zetok** [comment]
on bed1d66 started crashing again

**Comment by Diadlo** [comment]
Some misunderstanding of problem. Closed

**Pull request closed without merging**
