### PR TITLE
fix(threads): Always stop the camera device thread

### PR DESCRIPTION
**Pull request by yurivict**
It was running past the system shutdown.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4527)

### CODE REVIEW

**Comment by Diadlo** [comment]
I'm not understand the reason of this changes?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video/camerasource.h, line 60 at r1](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpjSJ3PKtaQwJMeaSCK:-KpjSJ3PKtaQwJMeaSCL:b-7qxpul) ([raw file](https://github.com/qtox/qtox/blob/0bc2936875503a58bd9a2706deb7021669ff890a/src/video/camerasource.h#L60)):*
> ```objc
>     ~CameraSource();
>     void stream();
>     static QThread* startDeviceThread();
> ```

Not used outside the class => remove from here and use as functions in `cpp` file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527#-:-KpjS7PullKXMiVGhUKV:b-ifxv6l)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/video/camerasource.cpp, line 459 at r1](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpjZPmnbxEsH68YLkeh:-KpjZPmorgjaeICDGDD3:b1veh78) ([raw file](https://github.com/qtox/qtox/blob/0bc2936875503a58bd9a2706deb7021669ff890a/src/video/camerasource.cpp#L459)):*
> ```cpp
> }
> 
> QThread* CameraSource::startDeviceThread() {
> ```

Is there any specific reason to move the code to it's own function? IMO it just introduces more code for no reason and I'd prefer it otherwise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by sudden6** [comment]
~Please don't close Issues before the fix is merged. You can add `fix  #4523` to the commit message and Github will close it automatically when merged.~

Sorry, didn't read new comment on the issue.

**Comment by yurivict** [comment]
> Is there any specific reason to move the code to it's own function? IMO it just introduces more code for no reason and I'd prefer it otherwise.

It makes it more readable, since there are several lines in one logical operation.

**Comment by yurivict** [comment]
Removed functions from the header.

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/video/camerasource.cpp, line 459 at r1](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpjZPmnbxEsH68YLkeh:-KpnabryeV__iKzJB_4m:b-yoa0us) ([raw file](https://github.com/qtox/qtox/blob/0bc2936875503a58bd9a2706deb7021669ff890a/src/video/camerasource.cpp#L459)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Is there any specific reason to move the code to it's own function? IMO it just introduces more code for no reason and I'd prefer it otherwise.
</blockquote></details>

Agree with @sudden6

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by yurivict** [comment]
*[src/video/camerasource.cpp, line 465 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpnbQ0CRDKdD9dDzX4x:-KpnbQ0CRDKdD9dDzX4y:b-ah9v5u) ([raw file](https://github.com/qtox/qtox/blob/28f9ae322f424378dee2d094e263a0da7ee885f2/src/video/camerasource.cpp#L465)):*
> ```cpp
>     auto thread = new QThread;
>     thread->setObjectName("Device thread");
>     thread->start();
> ```

It makes code more readable. One function creates the thread, another one destroys it. Before, this code was among other lines, and the thread destruction was forgotten for the reason of code being unexplicit and unclear. This isn't a goal to absolutely minimize the number of lines. Readability should be maximized.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/video/camerasource.cpp, line 465 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpnbQ0CRDKdD9dDzX4x:-Kpncxd2TwbmOuEl0DWF:bocx9ed) ([raw file](https://github.com/qtox/qtox/blob/28f9ae322f424378dee2d094e263a0da7ee885f2/src/video/camerasource.cpp#L465)):*
> and the thread destruction was forgotten

Hm... I can't see, where it was forgotten? You use the same code inside your functions.
I agree, that goal is maximization of readability, but IMO it doesn't really increase it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by yurivict** [comment]
*[src/video/camerasource.cpp, line 465 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpnbQ0CRDKdD9dDzX4x:-KpneV0gE8AiC5DJ1rfP:b-5ljxgl) ([raw file](https://github.com/qtox/qtox/blob/28f9ae322f424378dee2d094e263a0da7ee885f2/src/video/camerasource.cpp#L465)):*
It names an operation with the function name. This way the reader can easily see what is done. Additionally, this might need to be done in several places.

> I can't see, where it was forgotten?

Thread was left to run past the main function => it was forgotten.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/video/camerasource.cpp, line 465 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpnbQ0CRDKdD9dDzX4x:-Kpo5CVyu-RqBFQ-Dj8C:b-rt2ofe) ([raw file](https://github.com/qtox/qtox/blob/28f9ae322f424378dee2d094e263a0da7ee885f2/src/video/camerasource.cpp#L465)):*
<details><summary><i>Previously, yurivict wrote…</i></summary><blockquote>

It names an operation with the function name. This way the reader can easily see what is done. Additionally, this might need to be done in several places.

> I can't see, where it was forgotten?

Thread was left to run past the main function => it was forgotten.

</blockquote></details>

But it doesn't seems, like you change something

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/video/camerasource.cpp, line 465 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KpnbQ0CRDKdD9dDzX4x:-KppS8ClVnyuDJ-PwHuw:btvxb07) ([raw file](https://github.com/qtox/qtox/blob/28f9ae322f424378dee2d094e263a0da7ee885f2/src/video/camerasource.cpp#L465)):*
I guess this early return was the real problem:
>   if (_isNone) {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by Diadlo** [comment]
I think extracting in functions is overhead in this PR. Make it inline and let's merge

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527#-:-KrqfXHv13Jkn9PZzJwf:b-qnm44y)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/video/camerasource.cpp, line 464 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KrujAEHAJ0UE3JwDGDj:-KrujAEIC-bMAl3EQicq:b-w86snl) ([raw file](https://github.com/qtox/qtox/blob/28f9ae322f424378dee2d094e263a0da7ee885f2/src/video/camerasource.cpp#L464)):*
> ```cpp
> static QThread* startDeviceThread() {
>     auto thread = new QThread;
>     thread->setObjectName("Device thread");
> ```

QStringLiteral("Device thread")

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by Talkless** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by yurivict** [comment]
Updated.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/video/camerasource.cpp, line 464 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KrujAEHAJ0UE3JwDGDj:-KrvWXhC4EMmVXBxxWK2:b-1txzox) ([raw file](https://github.com/qtox/qtox/blob/32995b02b2111ef7c167c62c0b8527bc69265005/src/video/camerasource.cpp#L464)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QStringLiteral("Device thread")
</blockquote></details>

I think, this change is out of the scope of this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527#-:-KrvWX69zE5-FjFVz3LY:b-jbsf8z)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/video/camerasource.cpp, line 464 at r2](https://reviewable.io:443/reviews/qtox/qtox/4527#-KrujAEHAJ0UE3JwDGDj:-KrykydssiUnk7OoZn7T:b6pryxu) ([raw file](https://github.com/qtox/qtox/blob/32995b02b2111ef7c167c62c0b8527bc69265005/src/video/camerasource.cpp#L464)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, this change is out of the scope of this PR
</blockquote></details>

Oh this code is moved from elsewhere, so yes. I thought it's new one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4527)*

**Comment by Diadlo** [comment]
Your PR is failing because of the Commit Guidlines https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Pull request closed without merging**
