### PR TITLE
docs: Add a pull request template file

### PR DESCRIPTION
**Pull request by samcv**
Add a pull request template to tell contributors that their commits
should follow the project's git commit guidelines before submitting
a pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4474)

### CODE REVIEW

**Comment by zetok** [comment]
`s/PULL_REQUEST_TEMPLATE/PR template/`; `scope` is limited to 12 characters.

Could you move template under the `.github/` directory?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4474#-:-KmsEK_Zr7Owt3oZqLhE:b-b93zm4)*

**Comment by zetok** [comment]
Actually, `scope` part isn't even really needed here.

**Comment by samcv** [comment]
I've revised the commit, let me know if it is OK now.

**Comment by Diadlo** [comment]
I'm not sure, that it's good idea. Because by default github take commit message as body of PR. What do you think?

**Comment by zetok** [comment]
>I'm not sure, that it's good idea. Because by default github take commit message as body of PR. What do you think?

Perhaps instead of a sentence, it should be made to be a checkbox (`- [ ]`)

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Later on, more checkboxes could be added, perhaps in a similar manner to [Nixos PR template](https://github.com/NixOS/nixpkgs/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

**Comment by Diadlo** [comment]
@zetok I think, it will drop commit message too

**Comment by samcv** [comment]
Changed it to a checkbox.

**Comment by zetok** [comment]
@Diadlo does it look ok now?

**Comment by Diadlo** [comment]
@zetok As I said, I prefer github PR body autofill. Most of the PR sends by regular contributors who know the rules. (Frequency PR of regular contributers) * (time to set "X" in checkbox) >> (Frequency PR of new contributers) * (time to fix commit message). I think, this PR should be closed

**Comment by samcv** [comment]
You can always just delete it if it's not applicable. `Ctrl + A` then  `Backspace` and then can put anything you want. It's only a suggestion. At another project I added them for, it did not reduce the contributions but instead made new contributors have an easier experience since they did not have to revise their PR as many times.

**Comment by zetok** [comment]
@Diadlo 
>Most of the PR sends by regular contributors who know the rules.

It's normal that most of the commits come from people that are already familiar with the project, and this PR is not really for those people. It's specifically directed towards people who are new to the project. While aiming for newcomers this PR doesn't really aim to increase the frequency of PRs from a new contributor, but rather, it just aims to make contributing as easy and straightforward as possible.

The less friction a new contributor will face when trying to make a PR, the higher chances of them becoming a regular contributor to qTox.

At the same time, there is no actual loss to the information (since github's autofill is based on commit message anyway), and as @samcv said, one doesn't really have to use the template and can easily just delete it.

Overall, I think that increased chance of getting new, and possibly regular contributors outweighs the loss of autofill.

**Comment by sudden6** [comment]
Since a lot of PRs an commits don't follow the formatting, IMO we should merge this. @anthonybilinski @Diadlo @tox-user what do you think?

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/4474#-:-LB7G2Y091R5hWyhaWma:b-jbsf8z)*

**Comment by tox-user** [comment]
I think it's a good idea.

**Pull request merged**
