### PR TITLE
fix: save profile on friend username changes

### LINKED ISSUE #2733: Friend username not saved on qTox crash
Hello,

just noticed the following problem.

Reproduce:
1. Clear your ~/.config/tox directory
2. Create two new Tox profiles (Alice and Bob)
3. Make friends between Alice and Bob
4. Let Bob instance crash (for example with #2727)
5. Start Bob instance again
=> In the contact list the name 'Alice' isn't saved.

### PR DESCRIPTION
**Pull request by sudden6**
@ovalseven8 can you confirm that this is working?

fixes #2733

### CODE REVIEW

**Comment by ovalseven8** [comment]
Seems to work! :+1:

**Comment by alexbakker** [comment]
Wouldn't the same thing as described in #2733 happen with status message changes?

**Comment by sudden6** [comment]
@Impyy yes, but I think the status messages aren't that important. Whereas if you don't have the username of a new friend you basically don't know who it is, until he comes online again.

I'm open to a different opinion tough.

**Comment by alexbakker** [comment]
Fair enough. 
What you could also do is wait for the first time a friend comes online after you've accepted a friend request, wait for the name change callback and save the .tox file then. That way you're not writing to disk on every single name change.

**Comment by sudden6** [comment]
> What you could also do is wait for the first time a friend comes online after you've accepted a friend request, wait for the name change callback and save the .tox file then. That way you're not writing to disk on every single name change.

If we do that, I'm certain we will have another smiliar bug report soon, because the user expects qTox to look the same as it was before. Even after a crash.
Additionally the OS should cache these writes, so hopefully it won't affect performance.

**Comment by zetok** [comment]
> Additionally the OS should cache these writes, so hopefully it won't affect performance.

I wouldn't really count on that, at least not on btrfs. Although if save isn't being done continuously dozens of times per second, then performance hit probably won't be big enough to make users cry.

**Comment by zetok** [comment]
https://gist.github.com/zetok/7da88bcd97553d3c53e3214aa3a047c0 ← instantly crashes on start

note that before testing this PR I've put master qTox into testing on how well does it handle continuously changing random nick.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca3c6e75961af7aa2483ccc21f4cddcb9d34e1d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at
https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format

If this message was triggered by missing `(<scope>)` simply ignore it.

---
This message was auto-generated by https://gitcop.com

**Comment by zetok** [comment]
With 4cef9c95d8d6ae5317619fb4f09ef84335d04ca0 crash on start is fixed.

Also, this fix introduces DoS if name change rate is quick enough.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca3c6e75961af7aa2483ccc21f4cddcb9d34e1d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4cef9c95d8d6ae5317619fb4f09ef84335d04ca0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 809d2f9b400d5483225f8e3f0895703ec083a7a8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at
https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format

If this message was triggered by missing `(<scope>)` simply ignore it.

---
This message was auto-generated by https://gitcop.com

**Comment by zetok** [comment]
DoS is gone on 809d2f9b400d5483225f8e3f0895703ec083a7a8
- [ ] problem with trashing HDD.
- [ ] change makes qTox do a lot of unnecessary writes when profile is loaded: https://gist.github.com/zetok/2099227b87d8fd8539923e19ea041760 , write for each contact.

**Comment by zetok** [comment]
- [x] while contact was changing name repeatedly, I've changed profile name `_3.tox → __3.tox → _3.tox` which resulted in a leftover `__3.tox`; trying to rename again `_3.tox → __3.tox` resulted in an error:
  
  20160323 qtox groupchat names

**Comment by zetok** [comment]
- [ ] on 809d2f9b400d5483225f8e3f0895703ec083a7a8 causes client to disconnect from the DHT, or so it looks:
  
  disconnected

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca3c6e75961af7aa2483ccc21f4cddcb9d34e1d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4cef9c95d8d6ae5317619fb4f09ef84335d04ca0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 809d2f9b400d5483225f8e3f0895703ec083a7a8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: b6f070fb8dfd1ffd09d9214bebd07df8fa742086
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at
https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format

If this message was triggered by missing `(<scope>)` simply ignore it.

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ca3c6e75961af7aa2483ccc21f4cddcb9d34e1d6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4cef9c95d8d6ae5317619fb4f09ef84335d04ca0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 809d2f9b400d5483225f8e3f0895703ec083a7a8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bf15d3c95901d0c7bcb9e51647ca0353f520b49b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at
https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format

If this message was triggered by missing `(<scope>)` simply ignore it.

---
This message was auto-generated by https://gitcop.com

**Comment by zetok** [comment]
- [ ] on bf15d3c95901d0c7bcb9e51647ca0353f520b49b while contact was changing name repeatedly renaming profile was causing client to freeze for some time

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: d2d6fe072a613aceaae174787a478e971f32960c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 4b74217dfd690ee765443f4ad657ccf0e7d3c98c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: de590a0d7fada2d49fc7c3d7612a77a5eeab9002
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 9a565bc91e7c93edc1f7b7f67b70ac9b6913b232
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 54963ebe53fb5067f06eac195127c1a159c9c6f9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at
https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format

If this message was triggered by missing `(<scope>)` simply ignore it.

---
This message was auto-generated by https://gitcop.com

**Comment by sudden6** [comment]
Due to various issues at implementing a save timeout and the Issues @zetok mentioned I will close this PR for now.

**Pull request closed without merging**
