### PR TITLE
Fix url formatting again

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4243)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243#-:-KenbCYELUkgwrTIVVKo:b-jbsf8z)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/chatlog/textformatter.cpp, line 40 at r1](https://reviewable.io:443/reviews/qtox/qtox/4243#-Keo-vXk6x0zo8Vi3Gj0:-Keo-vXls0xirjcC99ez:bky3m8b) ([raw file](https://github.com/qtox/qtox/blob/fc230b23569610d48a0e88f22c372fa3a8a038e6/src/chatlog/textformatter.cpp#L40)):*
> ```cpp
> 
> static const QVector<QPair<QString, QString>> MARKDOWN_SYMBOLS_HTML_CODES {
>     {"*", "&#42"},
> ```

HTML use codes as char analog. I.e. code of '*' is `42` etc.
So better use QSet here and calculate replace string

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243)*

**Comment by sudden6** [comment]
@Diadlo assigned to you to require your LGTM before merge

**Comment by noavarice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 40 at r1](https://reviewable.io:443/reviews/qtox/qtox/4243#-Keo-vXk6x0zo8Vi3Gj0:-KeoppaOZstXPmfwjq7a:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fc230b23569610d48a0e88f22c372fa3a8a038e6/src/chatlog/textformatter.cpp#L40)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

HTML use codes as char analog. I.e. code of '*' is `42` etc.
So better use QSet here and calculate replace string
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 174 at r2](https://reviewable.io:443/reviews/qtox/qtox/4243#-Kf0_q4HakJ6ps13jMBs:-Kf0_q4HakJ6ps13jMBt:btmd4sm) ([raw file](https://github.com/qtox/qtox/blob/5b641a8d0dfd56d239053c491029972d290aab5a/src/chatlog/textformatter.cpp#L174)):*
> ```cpp
>     processUrl(message, [] (QString& str) {
>         for (char c : MARKDOWN_SYMBOLS) {
>             str.replace(c, HTML_CHARACTER_CODE.arg(QString::number(static_cast<int>(c))));
> ```

Can you extract `QString::number(static_cast<int>(c))` in variable?

---

*[src/chatlog/textformatter.cpp, line 204 at r2](https://reviewable.io:443/reviews/qtox/qtox/4243#-Kf0a-8Z1WcG1MBCS6Hy:-Kf0a-8Z1WcG1MBCS6Hz:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/5b641a8d0dfd56d239053c491029972d290aab5a/src/chatlog/textformatter.cpp#L204)):*
> ```cpp
>     }
>     for (char c : MARKDOWN_SYMBOLS) {
>         message.replace(HTML_CHARACTER_CODE.arg(QString::number(static_cast<int>(c))), QString(c));
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243)*

**Comment by noavarice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 174 at r2](https://reviewable.io:443/reviews/qtox/qtox/4243#-Kf0_q4HakJ6ps13jMBs:-Kf13SasxV_n6_pfqRbW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5b641a8d0dfd56d239053c491029972d290aab5a/src/chatlog/textformatter.cpp#L174)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can you extract `QString::number(static_cast<int>(c))` in variable?
</blockquote></details>

Done.

---

*[src/chatlog/textformatter.cpp, line 204 at r2](https://reviewable.io:443/reviews/qtox/qtox/4243#-Kf0a-8Z1WcG1MBCS6Hy:-Kf13T9hGLVZsXVAtgOO:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5b641a8d0dfd56d239053c491029972d290aab5a/src/chatlog/textformatter.cpp#L204)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243)*

**Comment by Diadlo** [comment]
@sudden6 code was changed. Take a look again before merge, please
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243#-:-Kf30YMY4_je10rn2GZs:b-twv4du)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4243#-:-Kf321-h2WzcjTUXkKCY:b-jbsf8z)*

**Pull request merged**
