### PR TITLE
fix: add missed <functional> header

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4745)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4745#-:-KwkXL7W03qa5xfDD3x-:b-jbsf8z)*

**Comment by DX37** [comment]
Errors in Travis caused by issue, which will be fixed in #4746.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4745#-:-KwoD81vLvF6XImnfpyz:b-jbsf8z)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4745#-:-KwzNe4EEWDrJxv72xaK:b-jbsf8z)*

**Pull request merged**
