### PR TITLE
feat(l10n): Update Polish translation from Weblate

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by tux3** [comment]
Why the change to lt.ts?

**Comment by zetok** [comment]
https://github.com/tux3/qTox/blob/master/tools/pull-translations.sh#L50 does it automatically – different versions of lupdate put there different version..

Want me to return it back to `2.1`?

**Comment by tux3** [comment]
No, no, I was just wondering why it only did that to lt.ps in particular, but the difference shouldn't matter.

**Comment by zetok** [comment]
Well, technically, all the .ts were affected when I first ran it on the .ts files.

Then there was a PR with translations to `lt.ts`, which changed it to `2.1`, and here we go again.. :D

**Comment by tux3** [comment]
It'll do.

**Pull request merged**
