### PR TITLE
[WIP] Another URL fixing.

### PR DESCRIPTION
**Pull request by noavarice**
URL regexes reverted to previous state, textformatter refactoring and test updating. Further test adding is in progress

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4510)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 26 at r1](https://reviewable.io:443/reviews/qtox/qtox/4510#-Kob8W9Jw0Mkn1i4dXAe:-Kob8W9Jw0Mkn1i4dXAf:b8jz43h) ([raw file](https://github.com/qtox/qtox/blob/2a50f0e32a255ad2475bea88a1f7e8eac3b88080/src/chatlog/textformatter.cpp#L26)):*
> ```cpp
> // clang-format off
> 
> /* Easy way to get count of markdown symbols - through length of substring, captured by reex group.
> ```

typo `regex`?

---

*[src/chatlog/textformatter.cpp, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4510#-Kob6tKXp4At4934adRo:-Kob6tKY6EbpQgrIowwP:b-j8js31) ([raw file](https://github.com/qtox/qtox/blob/2a50f0e32a255ad2475bea88a1f7e8eac3b88080/src/chatlog/textformatter.cpp#L109)):*
> ```cpp
> }
> 
> // clang-format on
> ```

I think this comment should be above the function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4510)*

**Comment by noavarice** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 26 at r1](https://reviewable.io:443/reviews/qtox/qtox/4510#-Kob8W9Jw0Mkn1i4dXAe:-KobBD1krRiO2yAfoXaq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2a50f0e32a255ad2475bea88a1f7e8eac3b88080/src/chatlog/textformatter.cpp#L26)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `regex`?
</blockquote></details>

Done.

---

*[src/chatlog/textformatter.cpp, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4510#-Kob6tKXp4At4934adRo:-KobBDOQbL05KZx613Ok:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2a50f0e32a255ad2475bea88a1f7e8eac3b88080/src/chatlog/textformatter.cpp#L109)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think this comment should be above the function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4510)*

**Comment by sudden6** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/chatlog/textformatter_test.cpp, line 81 at r1](https://reviewable.io:443/reviews/qtox/qtox/4510#-KocYAAZouDDYbpBEEY0:-KocYAA_vol3r5DFYINg:b-rf3fcx) ([raw file](https://github.com/qtox/qtox/blob/d704f5d21d7b33fbb52f89d9d2a5386015e6a3ce/test/chatlog/textformatter_test.cpp#L81)):*
> ```cpp
>      QStringLiteral("<a href=\"https://github.com/qTox/qTox/issues/4233\">"
>                     "https://github.com/qTox/qTox/issues/4233</a>")},
>     {QStringLiteral("No conflicts with /italic https://github.com/qTox/qTox/issues/4233 font/"),
> ```

Why was this test removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4510)*

**Comment by noavarice** [comment]
I got all wrong. Now i guess that i should write tests so they will show what i expect from  markdown due to incompletness of current information. I will make a PR which will describe a markdown syntax logic along with href highlighting. In response i expect opinion of all people who wants to tell something about it.
Also i am still thinking that using slashes for markdown purposes is *extremely* bad idea as long as it is conflicting with references until they consist from them

**Comment by yurivict** [comment]
Please make sure that URLs enclosed in braces don't eat up the closing brace.
For example URL in this text:
> Tox (https://tox.chat/) is great

should be selected without the closing brace, like in github.

**Comment by Talkless** [comment]
Reviewed 4 of 4 files at r2.
Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 91 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-KrujflRcS90Hxl4BYof:-KrujflRcS90Hxl4BYog:b-elyg3t) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L91)):*
> ```cpp
> 
> static const QRegularExpression URL_PATTERNS[] = {
>         QRegularExpression("\\b(www\\.|((http[s]?)|ftp)://)\\w+\\S+"),
> ```

How about avoiding double-backslashes and using C++11 raw string literals:
R"(\b(www\...
It will make regexp verbatim copy-pastable to some debugging tool.
Also, QStringLiteral()

---

*[src/chatlog/textformatter.cpp, line 106 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-Krukba7YVBYN4Dp43Wz:-Krukba7YVBYN4Dp43X-:b8xg4a4) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L106)):*
> ```cpp
> {
>     QString result = message;
>     for (QRegularExpression exp : URL_PATTERNS) {
> ```

Why not const reference? globalMatch() called later is const.

---

*[src/chatlog/textformatter.cpp, line 107 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-Krukvyosfy-aMSk1qdl:-Krukvyosfy-aMSk1qdm:b-liu8qb) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L107)):*
> ```cpp
>     QString result = message;
>     for (QRegularExpression exp : URL_PATTERNS) {
>         int startLength = result.length();
> ```

const int

---

*[src/chatlog/textformatter.cpp, line 111 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-Krul9OCoDfcMJgqIft6:-Krul9OCoDfcMJgqIft7:b4a4q5p) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L111)):*
> ```cpp
>         QRegularExpressionMatchIterator iter = exp.globalMatch(result);
>         while (iter.hasNext()) {
>             QRegularExpressionMatch match = iter.next();
> ```

const QRegular....

---

*[src/chatlog/textformatter.cpp, line 112 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-KrulC37wqIfoFpMmPXl:-KrulC37wqIfoFpMmPXm:b-liu8qb) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L112)):*
> ```cpp
>         while (iter.hasNext()) {
>             QRegularExpressionMatch match = iter.next();
>             int startPos = match.capturedStart() + offset;
> ```

const int

---

*[src/chatlog/textformatter.cpp, line 113 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-KrulCoiD1UYxYxbRLRN:-KrulCoiD1UYxYxbRLRO:b-liu8qb) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L113)):*
> ```cpp
>             QRegularExpressionMatch match = iter.next();
>             int startPos = match.capturedStart() + offset;
>             int length = match.capturedLength();
> ```

const int

---

*[src/chatlog/textformatter.cpp, line 114 at r2](https://reviewable.io:443/reviews/qtox/qtox/4510#-KrulF24xP3uW-FwVIjo:-KrulF25JXdv725KPYfH:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/d3fef32e2251ff606f8a30af41253ad7610fba5f/src/chatlog/textformatter.cpp#L114)):*
> ```cpp
>             int startPos = match.capturedStart() + offset;
>             int length = match.capturedLength();
>             QString wrappedURL = htmlPatterns[TextStyle::HREF].arg(match.captured());
> ```

const QString

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4510)*

**Comment by noavarice** [comment]
Moved to #4593

**Pull request closed without merging**
