### PR TITLE
Smiley changes

### PR DESCRIPTION
**Pull request by ovalseven8**
- Rename 'cylgom' -> 'Basic'
- Rename 'krepa098' -> 'Classic'
- Rename 'TwitterEmojiSimple' -> 'ASCII-Universe'
- Rename 'TwitterEmojiSVG' -> 'Universe'
- Minor improvements

### CODE REVIEW

**Comment by ovalseven8** [comment]
Of course, the names are not cut in stone.
But for the meantime it's a much better solution than the current names.

**Comment by Schlumpf** [comment]
Why did you remove the unicode glyphs of some emoticons from the XML file?
E.g.:

``` xml
<string>💣</string>
```

**Comment by ovalseven8** [comment]
Because they aren't displayed correctly for most of the people and I wanted that at least in 'Classic' and 'Basic' it is solid.

**Comment by tux3** [comment]
Your "Minor improvements" are a lot of things.
What exactly did you do?

**Comment by ovalseven8** [comment]
Just removed some unicode glyphs that weren't displayed correctly, removed one smiley and fixed one path (smiley wasn't displayed because of that).

**Comment by tux3** [comment]
@ovalseven8 What is that https://github.com/ovalseven8/qTox/commit/d2af778e177ce4bc5ddd29bbecdf6e76fb60dffa ?

**Comment by tux3** [comment]
That's too much unrelated changes, please send separate PRs.

**Comment by Schlumpf** [comment]
Removing the unicode glyphs isn't a good idea. You could change the order in the XML file:

``` xml
<string>:bomb:</string>
<string>💣</string>
```

should solve your problem.

But who are _most_ of people? I thought only older win systems don't support those glyphs...

**Comment by ovalseven8** [comment]
@Schlumpf:
It isn't displayed for Lubuntu 14.04 users as well.

**Pull request closed without merging**
