### PR TITLE
Add colored nicknames in group chats

### PR DESCRIPTION
**Pull request by Monsterovich**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Screenshot:
default

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5404)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
please rename your commits to follow our commit guidelines: https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines or this PR will not pass CI.

> Reviewed 7 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5404#-:-LPXmBJDDCxm9sY1uOyi:b-63qsq2)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatmessage.cpp, line 95 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXlO8D4CgvPJMbCS7Y:-LPXlO8D4CgvPJMbCS7Z:b5nw1or) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/chatlog/chatmessage.cpp#L95)):*
> ```cpp
>     if (colorizeName && Settings::getInstance().getEnableGroupChatsColor())
>     {
>         QByteArray hash = QCryptographicHash::hash((sender.toUtf8()), QCryptographicHash::Md5);
> ```

Can you use a hash function from the SHA256 family? MD5 is not recommended for anything anymore.
___
*[src/chatlog/chatmessage.cpp, line 99 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXlXOs40oDmCROZXgT:-LPXlXOs40oDmCROZXgU:b92q23m) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/chatlog/chatmessage.cpp#L99)):*
> ```cpp
> 
>         if (!authorColor[sender].isValid())
>             authorColor[sender] = QColor(data[0], data[1], data[2]);
> ```

Using RGB color space for this is a bad idea, because there could be colors generated that are hard to read. I would recommend to use HSV color space and only vary the hue coordinate like it's done for identicons.
___
*[src/chatlog/chatmessage.cpp, line 101 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXlu7mC8r_ME3suZr1:-LPXlu7mC8r_ME3suZr2:b-hlii7k) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/chatlog/chatmessage.cpp#L101)):*
> ```cpp
>             authorColor[sender] = QColor(data[0], data[1], data[2]);
> 
>         if (!isMe)
> ```

braces needed
___
*[src/widget/form/settings/userinterfaceform.cpp, line 380 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXm36GAskOZwxnRz7y:-LPXm36GAskOZwxnRz7z:b3mm54x) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/widget/form/settings/userinterfaceform.cpp#L380)):*
> ```cpp
> }
> 
> void UserInterfaceForm::on_useNameColors_stateChanged(int arg1)
> ```

`arg1` is not descriptive, please rename

**Comment by Monsterovich** [comment]
>please rename your commits to follow our commit guidelines: https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines or this PR will not pass CI.

CI processed my commits well but I renamed them anyway. OK.

>Can you use a hash function from the SHA256 family? MD5 is not recommended for anything anymore.

OK.

>arg1 is not descriptive, please rename

I found arg1 stuff in other places. It's insignificant.

>braces needed

Same.

**Comment by Monsterovich** [comment]
Well, I fixed anything. It works well. You can merge.

default

**Review by sudden6 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5404)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatmessage.cpp, line 95 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXlO8D4CgvPJMbCS7Y:-LP_Ds7YDVsdO7ehdRzO:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/chatlog/chatmessage.cpp#L95)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you use a hash function from the SHA256 family? MD5 is not recommended for anything anymore.
</blockquote></details>

ok
___
*[src/chatlog/chatmessage.cpp, line 99 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXlXOs40oDmCROZXgT:-LP_Fc8-0bAP4X8zjKMQ:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/chatlog/chatmessage.cpp#L99)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Using RGB color space for this is a bad idea, because there could be colors generated that are hard to read. I would recommend to use HSV color space and only vary the hue coordinate like it's done for identicons.
</blockquote></details>

ok
___
*[src/chatlog/chatmessage.cpp, line 101 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXlu7mC8r_ME3suZr1:-LP_Farr59wwpggIe2Bt:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/chatlog/chatmessage.cpp#L101)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces needed
</blockquote></details>

ok
___
*[src/widget/form/settings/userinterfaceform.cpp, line 380 at r1](https://reviewable.io/reviews/qtox/qtox/5404#-LPXm36GAskOZwxnRz7y:-LP_E9uV--FIwEp_63xR:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/e6a187a1ae3c17a6649e93760098e3c973eb82fc/src/widget/form/settings/userinterfaceform.cpp#L380)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`arg1` is not descriptive, please rename
</blockquote></details>

ok

**Comment by anthonybilinski** [comment]
@Monsterovich could you please rebase your changes to master tip (or at least past e0bcad21b4424fb6115b1d8b91abd7c1f7bdd45a)? Our CI is broken at 2408e76d0ccd068a461f38d0a08a1648dc57c3bd where your changes start.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5404#-:-LPqtgrF5JRHqrV5cTzf:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
