### PR TITLE
fix(chatform): Hide author on history like on new messages

### PR DESCRIPTION
**Pull request by anthonybilinski**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4620)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/widget/form/genericchatform.cpp, line 383 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt0m3NX3MKFKOgNj-F9:-Kt0m3NY6wLBFZ9C7SRN:b-madnkz) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L383)):*
> ```cpp
>  * @return True if it's needed to hide name, false otherwise
>  */
> bool GenericChatForm::needsToHideName(const ToxPk& messageAuthor, const QDateTime& messageTime) const
> ```

Add documentation entry for `messageTime`

---

*[src/widget/form/genericchatform.cpp, line 414 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt0m9TqzMFq0WJR8bo_:-Kt0m9TqzMFq0WJR8boa:bocxsd4) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L414)):*
> ```cpp
>     } else {
>         msg = ChatMessage::createChatMessage(authorStr, message, ChatMessage::NORMAL, isSelf);
>         QDateTime newMsgDateTime = QDateTime::currentDateTime();
> ```

Optionally make this `const`, it makes code more clear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4620)*

**Comment by noavarice** [comment]
Also, according to travis build log, you should verify that you have added `messageTime` as actual parameter at all `needsToHideName` calls. Just try to compile qTox and you will see where parameter lacks

**Comment by Diadlo** [comment]
Please, add "Fix #4619" to the commit message

**Comment by Talkless** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/widget/form/genericchatform.cpp, line 463 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt24LTBnoFwum_14xH0:-Kt24LTCWw0ylN4NzNBz:b-lfkm22) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L463)):*
> ```cpp
>     bool isSelf = author == Core::getInstance()->getSelfId().getPublicKey();
>     auto chatMsg = ChatMessage::createChatMessage(authorStr, msg, ChatMessage::ALERT, isSelf, dt);
>     QDateTime newMsgDateTime = QDateTime::currentDateTime();
> ```

Could be **const** QDateTime

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4620)*

**Comment by anthonybilinski** [comment]
- Sorry about the broken build, missed a local commit, fixed :(
- Added documentation for param
- Added const on both usages of newMsgDateTime
- added "Fix #4619" to commit message

Reviewable

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4620#-:-KtPuhO4nGwrWwDbcZn7:b-jbsf8z)*

**Comment by noavarice** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 463 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt24LTBnoFwum_14xH0:-KtfN_esLQK297mCiGJH:b7064w7) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L463)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Could be **const** QDateTime
</blockquote></details>

Please, write `Done` if you add mentioned changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4620)*

**Comment by anthonybilinski** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 383 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt0m3NX3MKFKOgNj-F9:-Kth0psC8usVAepsgrD0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L383)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Add documentation entry for `messageTime`
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.cpp, line 414 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt0m9TqzMFq0WJR8bo_:-Kth0qlmQfqkwm2muDVn:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L414)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Optionally make this `const`, it makes code more clear
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.cpp, line 463 at r1](https://reviewable.io:443/reviews/qtox/qtox/4620#-Kt24LTBnoFwum_14xH0:-Kth0sLd2QCHlE5mjXnf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c3de3a706256184b12fdfd2e6911e9ce7111385a/src/widget/form/genericchatform.cpp#L463)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Please, write `Done` if you add mentioned changes
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4620)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4620#-:-Kth6APNdmLWV48rLYA2:b-jbsf8z)*

**Pull request merged**
