### PR TITLE
Fix video freeze

### LINKED ISSUE #2058: Switching to 'Audio/Video' settings tab is blocked on camera initialisation
_Audio/Video_ tab content display is blocked (and waits) on the thread that initialises the camera (and/or microphone) in any situation when that tab is made active. Examples:
- Switching from any other settings tab **to** the _Audio/Video_ tab
- Entering settings (via Gear icon) if the _Audio/Video_ tab was the last active tab

Camera initialisation should be made non-blocking and/or in a separate thread, such that the contents of the _Audio/Video_ tab can be displayed before the camera/microphone device has been enumerated and initialised.

While camera initialisation takes place, the camera preview area could be made:
- Empty (minimum)
- Empty with a user message "Waiting for camera initialisation ..."
- Empty with a progress animation "Initialising ..."

If the progress of initialization is known (definite), then the code could update the progress bar or message accordingly:
1. Searching devices
2. Identifying resolutions
3. Initializing camera

Or whatever the process/steps may be.

Environment:
- **OS Name**: Microsoft Windows 7 Ultimate (x86_64, amd64, 64-bit)
- **OS Version**: 6.1.7601 Service Pack 1 Build 7601
- **Processor**: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz, 3401 Mhz, 4 Core(s) +HT
- **Physical Memory**: 16.0 GB
- **Camera**: Logitech HD Pro Webcam C920
- **Hardware ID**: USB\VID_046D&PID_082D
- **Driver Provider**: Microsoft
- **Driver Version**: 6.1.7601.18208 (12/07/2013) (UVC)
- **qTox Version**: https://github.com/tux3/qTox/commit/f10b4eaee7072bb9fbad5490be016455ba934bcf

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #2058

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4495)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 6 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video/camerasource.h, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4495#-Kn_1IkwmA-XQT3s0oxu:-Kn_1IkxgPSlgphjsnNq:b-pq11sp) ([raw file](https://github.com/qtox/qtox/blob/723c3374dc6ddef387858275e676fe538e7a6162/src/video/camerasource.h#L45)):*
> ```objc
>     void setupDevice(const QString& deviceName);
>     void setupDevice(const QString& deviceName, const VideoMode& mode);
>     bool isNotNone() const;
> ```

I think `isNone()` makes more sense for the name and function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4495)*

**Comment by Diadlo** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video/camerasource.h, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4495#-Kn_1IkwmA-XQT3s0oxu:-Kn_3EtSg0Ow2w9Sylck:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/723c3374dc6ddef387858275e676fe538e7a6162/src/video/camerasource.h#L45)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think `isNone()` makes more sense for the name and function.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4495)*

**Comment by zetok** [comment]
As far as testing goes, :lgtm_strong: , opening & closing the A/V tab no longer is lagging.

I didn't test audio groupchat, since they don't seem to be related to PR.

There was some strange stuff in stdout, no idea if related to PR:

```
[20:54:28.360 UTC] audio/backend/openal.cpp:217 : Debug: Unsubscribed from audio input device [ 1 subscriptions left ]
[20:54:38.403 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 49 , ignoring it
[20:54:39.505 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 72 , ignoring it
[20:54:40.705 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 94 , ignoring it
[20:54:41.804 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 113 , ignoring it
[20:54:42.854 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 141 , ignoring it
[20:54:45.355 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 158 , ignoring it
[20:54:46.657 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 238 , ignoring it
[20:54:47.755 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 272 , ignoring it
[20:54:49.255 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 281 , ignoring it
[20:54:52.455 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 341 , ignoring it
[20:54:54.753 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 409 , ignoring it
[20:54:55.903 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 576 , ignoring it
[20:54:57.904 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 947 , ignoring it
[20:54:59.404 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 1150 , ignoring it
[20:55:00.453 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 1325 , ignoring it
[20:55:01.905 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 1552 , ignoring it
[20:55:03.053 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 1737 , ignoring it
[20:55:04.154 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 1881 , ignoring it
[20:55:05.304 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 2026 , ignoring it
[20:55:06.353 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 2512 , ignoring it
[20:55:07.405 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 3305 , ignoring it
[20:55:08.403 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 3845 , ignoring it
[20:55:09.505 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 4140 , ignoring it
[20:55:10.653 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 4382 , ignoring it
[20:55:11.705 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 4606 , ignoring it
[20:55:12.953 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 4752 , ignoring it
[20:55:14.005 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 4880 , ignoring it
[20:55:15.055 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 5005 , ignoring it
[20:55:16.105 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 5263 , ignoring it
[20:55:17.204 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 5594 , ignoring it
[20:55:18.405 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 5766 , ignoring it
[20:55:19.405 UTC] core/coreav.cpp:776 : Debug: Recommended bitrate with 14  is now  64 / 5843 , ignoring it
```

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxcall.cpp, line 134 at r2](https://reviewable.io:443/reviews/qtox/qtox/4495#-KnpbH0EpA8Bkfisp-1M:-KnpbH0EpA8Bkfisp-1N:bk64xxs) ([raw file](https://github.com/qtox/qtox/blob/2e8daaa5a156f051603820f50dbde8d0c502eaae/src/core/toxcall.cpp#L134)):*
> ```cpp
> 
>         if (source.isNone())
>             source.setupDefault();
> ```

Add newline

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4495#-:-Knpbs4-bmBcRgGVtL-L:bv2owpq)*

**Comment by Diadlo** [comment]
@zetok Do you have this messages on master?

---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxcall.cpp, line 134 at r2](https://reviewable.io:443/reviews/qtox/qtox/4495#-KnpbH0EpA8Bkfisp-1M:-KnpkB8PTuYRrJDG8k1z:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2e8daaa5a156f051603820f50dbde8d0c502eaae/src/core/toxcall.cpp#L134)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Add newline
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4495#-:-KnpkCefhvYNyz5-3GNw:b-1j7piy)*

**Comment by zetok** [comment]
>Do you have this messages on master?

I didn't see it on master.

On 2e8daaa5 there was also a graphical glitch:

spectacle w22192

I haven't seen that on master, and I couldn't reproduce it.

**Comment by Diadlo** [comment]
I had this glitch on master before

**Comment by sudden6** [comment]
:lgtm_strong: had no problems with a short test

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4495#-:-Ko1qYgSxFmooGAsdB4f:bbk3aoq)*

**Pull request merged**
