### PR TITLE
Set window icons on settings window

### PR DESCRIPTION
**Pull request by agilob**
Sets window icon for profile, settings etc when separate windows mode is enabled

### CODE REVIEW

**Comment by ghost** [comment]
> settings

Works

> profile, settings etc

They all show the gear icon. Is that the expected behaviour? The `Add friend` window could display the `+` icon, the `File transfers` one the 2-arrows icon, etc.

> etc

No icon in chat window, unless that wasn't included in the changes.
Edit: probably not, saw #2767 after this comment.

---

Debian testing
Cinnamon 2.6.13
Qt 5.5.1

**Comment by agilob** [comment]
Yes, it's expected. I think it would be "bad" to have 10 different icons for one application, but different windows. 

> No icon in chat window, unless that wasn't included in the changes.

It's in another PR -.-'

**Comment by tux3** [comment]
Well, I think it would make more sense to always display the qTox icon.
Applications typically don't change their icon when you go in the settings, it would make it harder to find qTox in my taskbar if the icon is sometimes just a gear. If all applications did that my taskbar would be a mess!

**Comment by agilob** [comment]
Done.

**Comment by agilob** [comment]
Thanks

**Pull request merged**
