### PR TITLE
fix(group): Show correct count of user on first creation

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4978)

### CODE REVIEW

**Comment by tox-user** [comment]
Why are both `regeneratePeerList()` and `onUserListChanged()` needed? `regeneratePeerList()` already emits a signal that should call `onUserListChanged()`, but when I tried to remove `onUserListChanged()` it didn't work.

**Comment by Diadlo** [comment]
@tox-user `regeneratePeerList()` needed to update peer list when group created (because in real we have one peer). `onUserListChanged()` not called because signal emitet in creation time, when noone connected to group

**Comment by tox-user** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4978#-:-L6ZKMRK0M0xqHidvzl-:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4978#-:-L6rThWF4Qaw9IR0Nkw-:b-jbsf8z)*

**Comment by tox-user** [comment]
This breaks PR https://github.com/qTox/qTox/pull/4923.

**Comment by Diadlo** [comment]
@tox-user You want to say, that #4923 don't work with this PR?)

**Comment by tox-user** [comment]
Yes, #4923 will not work after the changes in this PR.

**Comment by sudden6** [comment]
#4923 is not scheduled for merge in 1.14, so I guess we can live with the breakage for now.

**Pull request merged**
