### PR TITLE
Update NURUPOWILLSUEME

### PR DESCRIPTION
**Pull request by lance0**
Not enough freedom. Fixed.

### CODE REVIEW

**Comment by dubslow** [comment]
That is glorious lol

**Comment by tux3** [comment]
Much better now :)

**Comment by lance0** [comment]
LOOL!L!!!! omfg i love it MUH FREEDOMS!

**Comment by msteinbeck** [comment]
:D

**Comment by ghost** [comment]
I've never felt happier! :')

**Pull request merged**
