### PR TITLE
chore(tools): rewrite C++ tool for generating PK/SK keypair in Rust

### PR DESCRIPTION
**Pull request by zetok**
Also avoid accidentally committing signing keys.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4040)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 8 of 10 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/update-server/qtox-updater-genkeys/src/main.rs, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4040#-K_ZN_-DjTotnKZlDV9J:-K_ZN_-Evk7z2GERLJp2:bmfdjxp) ([raw file](https://github.com/qtox/qtox/blob/0e73ac68e5ccccd44a9f97943b5a115f21c5d9af/tools/update-server/qtox-updater-genkeys/src/main.rs#L37)):*
> ```Rust
> 
>     // make sure to init sodiumoxide for proper entropy
>     sodiumoxide::init();
> ```

check the return value

---

*[tools/update-server/qtox-updater-genkeys/src/main.rs, line 39 at r1](https://reviewable.io:443/reviews/qtox/qtox/4040#-K_ZJ4aJVdbwQeiOR5W5:-K_ZJ4aKKTgH2ZNlpTC4:b-drkzhx) ([raw file](https://github.com/qtox/qtox/blob/0e73ac68e5ccccd44a9f97943b5a115f21c5d9af/tools/update-server/qtox-updater-genkeys/src/main.rs#L39)):*
> ```Rust
>     sodiumoxide::init();
> 
>     let (pk, sk): (PublicKey, SecretKey) = gen_keypair();
> ```

can this method fail to create a "good" keypair? ie when there's not enough entropy available?

---

*[tools/update-server/qtox-updater-genkeys/src/main.rs, line 44 at r1](https://reviewable.io:443/reviews/qtox/qtox/4040#-K_ZJLHp_Nij0XWXuVq_:-K_ZJLHp_Nij0XWXuVqa:bfvgvag) ([raw file](https://github.com/qtox/qtox/blob/0e73ac68e5ccccd44a9f97943b5a115f21c5d9af/tools/update-server/qtox-updater-genkeys/src/main.rs#L44)):*
> ```Rust
>     pkey_file.write_all(&pk.0).expect("Failed to write PublicKey");
> 
>     // SecretKey data should be read-only by owner
> ```

shouldn't the permissions be set before writing the data to the file? IDK if that's possible but, I think the correct approach is: Create file, set permissions to `-rw-------`, write key, set permissions to `-r--------`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4040)*

**Comment by sudden6** [comment]
At this point, I think it would be better to move all the updater stuff + helper tools into a separate repository under the qTox org. Since technically the updater is pretty independent it makes sense IMO.

@Diadlo @tux3 what do you think?

**Comment by zetok** [comment]
Review status: 8 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/update-server/qtox-updater-genkeys/src/main.rs, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4040#-K_ZN_-DjTotnKZlDV9J:-K_ZS1OaGyS_8f_PNthh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0e73ac68e5ccccd44a9f97943b5a115f21c5d9af/tools/update-server/qtox-updater-genkeys/src/main.rs#L37)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

check the return value
</blockquote></details>

Done.

---

*[tools/update-server/qtox-updater-genkeys/src/main.rs, line 39 at r1](https://reviewable.io:443/reviews/qtox/qtox/4040#-K_ZJ4aJVdbwQeiOR5W5:-K_ZNyUWLuAxLTXjriaA:b7rup5q) ([raw file](https://github.com/qtox/qtox/blob/0e73ac68e5ccccd44a9f97943b5a115f21c5d9af/tools/update-server/qtox-updater-genkeys/src/main.rs#L39)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can this method fail to create a "good" keypair? ie when there's not enough entropy available?
</blockquote></details>

Yes. libsodium tries its best to get strong entropy from the system, but if system will provide bad entropy, resulting key can be "weak".

Unless you compile libsodium with an option to use `/dev/random` instead of `urandom`, scenario where there's not enough entropy available doesn't happen. With that in mind, it's still possible for `urandom` to return not-so-good entropy. Making sure that this doesn't happen is outside of scope of this, or libsodium's code though.

---

*[tools/update-server/qtox-updater-genkeys/src/main.rs, line 44 at r1](https://reviewable.io:443/reviews/qtox/qtox/4040#-K_ZJLHp_Nij0XWXuVq_:-K_ZS3LH979Nf5IwB32z:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0e73ac68e5ccccd44a9f97943b5a115f21c5d9af/tools/update-server/qtox-updater-genkeys/src/main.rs#L44)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

shouldn't the permissions be set before writing the data to the file? IDK if that's possible but, I think the correct approach is: Create file, set permissions to `-rw-------`, write key, set permissions to `-r--------`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4040)*

**Comment by sudden6** [comment]
Reviewed 1 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4040)*

**Comment by Diadlo** [comment]
I'm agree with @sudden6 about moving tools in separate repository

**Comment by zetok** [comment]
Is this code good to use it instead of C++ in a separate repo?

**Comment by sudden6** [comment]
Yes

**Comment by zetok** [comment]
Deprecated by #4059, thus closing.

**Pull request closed without merging**
