### PR TITLE
Updates timestamps every second if general settings form is open.

### LINKED ISSUE #1490: qTox cannot into time change
time change
qTox | real time

Please fix.

### PR DESCRIPTION
**Pull request by kushagrasurana**
Updates date stamps when a day passes.
fixes #1490

### CODE REVIEW

**Comment by zetok** [comment]
@kushagrasurana since #1490 is PEBKAC, I'm not sure how it fixes it?

**Comment by kushagrasurana** [comment]
@zetok I thought you were taking about combobox time in general settings not updating.

**Comment by zetok** [comment]
nope

**Comment by tux3** [comment]
This seems to be fixing a non-issue, so I'll close it for now.

**Pull request closed without merging**
