### PR TITLE
refactor: connection to parent method in toxuri.cpp

### PR DESCRIPTION
**Pull request by bodwok**
After that PR - FriendRequestDialog is not currently used in the project

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6182)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6182)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6182#-MBKzzgJ7TJKlvkfdc3X:-MBKzzgJ7TJKlvkfdc3Y:b-y8joo9) (no related file):*
Looks good. Could you also delete friendrequestdialog.{cpp,h}, and remove them from CMakeList.txt?

---
___
*[src/net/toxuri.cpp, line 104 at r1](https://reviewable.io/reviews/qtox/qtox/6182#-MBKzad_1GHVWvTgkpch:-MBKzad_1GHVWvTgkpci:b-mwzmfg) ([raw file](https://github.com/qtox/qtox/blob/431fd7bfa29d17c630c0896b191867a3b9c68dc7/src/net/toxuri.cpp#L104)):*
> ```cpp
> 
>     connect(buttonBox, &QDialogButtonBox::accepted, this, &FriendRequestDialog::accept);
>     connect(buttonBox, &QDialogButtonBox::rejected, this, &FriendRequestDialog::reject);
> ```

what weird existing code, ToxUri doesn't inherit from FriendRequestDialog, I guess it was just connecting to QDialog since it's the base class of both.

**Review by bodwok — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6182)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6182#-MBKzzgJ7TJKlvkfdc3X:-MBQ6nCx43zvB6V01xaj:b-896fix) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Looks good. Could you also delete friendrequestdialog.{cpp,h}, and remove them from CMakeList.txt?
</blockquote></details>

Done.

---

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6182)* status: :shipit: complete! 1 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6182#-MBKzzgJ7TJKlvkfdc3X:-MBRE9b_C_4mI8iJ5zqv:b-uwkowd) (no related file):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:lgtm_strong: 

---

**Review by anthonybilinski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6182)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
