### PR TITLE
fix(video): Disconnect lambda on destruction, refactor

### LINKED ISSUE #3840: Segfault when trying to make a video call after logout & load
##### Brief Description

qTox crashes when one tries to have a video call after logging out & loading profile

OS: Gentoo Linux amd64
qTox version: v1.5.2-218-ge8e946d
Commit hash: e8e946d4c8f21e55680ab7ff8ea0a60026b399e2
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always
##### Steps to reproduce
1. Multiple windows mode
2. Open settings
3. Open Profile
4. Open friend window (chatform)
5. Open About friend window
6. Video call friend (other side autoaccepts)
7. Once call is going on, logout
8. Load same profile
9. Repeat previous steps, that will result in a segfault at accepting video step
##### Observed Behavior

Crash.
##### Expected Behavior

Should just work™.
##### Additional Info

backtrace on c27bb370d2823e1d08aed0e79fe21d37b58182de:

```
[07:20:12.369 UTC] audio/audio.cpp:384 : Debug: Opened audio input "Live! Cam Chat HD [VF0700] Analog Mono"
[07:20:12.369 UTC] audio/audio.cpp:312 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[07:20:12.369 UTC] audio/audio.cpp:401 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fffa2ff4700 (LWP 8281)]
[07:20:12.371 UTC] audio/audio.cpp:416 : Debug: Opened audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fffa30f5700 (LWP 8286)]
[07:20:12.372 UTC] audio/audio.cpp:685 : Debug: Audio source 2 created. Sources active: 1
[07:20:12.372 UTC] video/camerasource.cpp:269 : Debug: Opening device  "/dev/video0"
[mjpeg @ 0x7fffc006de40] Changeing bps to 8
[07:20:13.358 UTC] audio/audio.cpp:312 : Debug: Subscribed to audio input device [ 2 subscriptions ]
[07:20:13.358 UTC] audio/audio.cpp:328 : Debug: Unsubscribed from audio input device [ 1 subscriptions left ]
[07:20:13.362 UTC] widget/form/chatform.cpp:527 : Debug: enableCallButtons
[07:20:13.363 UTC] widget/form/chatform.cpp:540 : Debug: timer started!!
[07:20:13.382 UTC] widget/form/chatform.cpp:341 : Debug: onAvStart
[07:20:13.384 UTC] widget/form/chatform.cpp:672 : Debug: creating netcam
[07:20:13.386 UTC] video/netcamview.cpp:89 : Debug: SIZER QRect(0,0 1280x720)
[07:20:13.477 UTC] video/camerasource.cpp:269 : Debug: Opening device  "/dev/video0"

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff7f4da700 (LWP 6277)]
0x00007ffff7ba8938 in friend_not_valid (m=0x7fffb813a480, friendnumber=10)
    at ../toxcore/Messenger.c:47
47          if (m->friendlist[friendnumber].status != 0) {
(gdb) bt
#0  0x00007ffff7ba8938 in friend_not_valid (m=0x7fffb813a480, friendnumber=10)
    at ../toxcore/Messenger.c:47
#1  0x00007ffff7ba9ae4 in m_friend_exists (m=0x7fffb813a480, friendnumber=10)
    at ../toxcore/Messenger.c:439
#2  0x00007ffff798083a in toxav_video_send_frame (av=0x7fffb8057370, 
    friend_number=10, width=1280, height=720, y=0x7fff701dba40 "", 
    u=0x7fff702bca40 '\200' <repeats 200 times>..., 
    v=0x7fff702f4e40 '\200' <repeats 200 times>..., error=0x7fff7f4d99dc)
    at ../toxav/toxav.c:748
#3  0x00005555555c8aed in CoreAV::sendCallVideo (this=0x7fffb8056120, callId=10, 
    vframe=std::shared_ptr (count 3, weak 1) 0x7fff70007d60)
    at src/core/coreav.cpp:374
#4  0x00005555555d67ea in ToxFriendCall::<lambda(std::shared_ptr<VideoFrame>)>::operator() (frame=..., __closure=<optimized out>) at src/core/toxcall.cpp:127
#5  QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::shared_ptr<VideoFrame> >, void, ToxFriendCall::ToxFriendCall(uint32_t, bool, CoreAV&)::<lambda(std::shared_ptr<VideoFrame>)> >::call (arg=<optimized out>, f=...)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:495
#6  QtPrivate::Functor<ToxFriendCall::ToxFriendCall(uint32_t, bool, CoreAV&)::<lambda(std::shared_ptr<VideoFrame>)>, 1>::call<QtPrivate::List<std::shared_ptr<VideoFrame> >, void> (arg=<optimized out>, f=...)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:552
#7  QtPrivate::QFunctorSlotObject<ToxFriendCall::ToxFriendCall(uint32_t, bool, CoreAV&)::<lambda(std::shared_ptr<VideoFrame>)>, 1, QtPrivate::List<std::shared_ptr<VideoFrame> >, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, 
    a=<optimized out>, ret=<optimized out>)
    at /usr/include/qt5/QtCore/qobject_impl.h:192
#8  0x00007ffff37fef9f in QtPrivate::QSlotObjectBase::call (a=0x7fff7f4d9c00, 
    r=0x5555561190b0, this=0x7fffb0135ab0)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#9  QMetaObject::activate (sender=sender@entry=0x5555561190b0, 
    signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x7fff7f4d9c00) at kernel/qobject.cpp:3715
#10 0x00007ffff37ff3e7 in QMetaObject::activate (
    sender=sender@entry=0x5555561190b0, 
    m=m@entry=0x555555d0f240 <VideoSource::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fff7f4d9c00)
    at kernel/qobject.cpp:3595
#11 0x00005555556d3674 in VideoSource::frameAvailable (
    this=this@entry=0x5555561190b0, 
    _t1=std::shared_ptr (count 3, weak 1) 0x7fff70007d60)
    at moc_videosource.cpp:141
#12 0x000055555563a4fe in CameraSource::<lambda()>::operator() (
    __closure=<synthetic pointer>) at src/video/camerasource.cpp:395
#13 CameraSource::stream (this=0x5555561190b0) at src/video/camerasource.cpp:412
#14 0x00005555555cb6ed in QtConcurrent::RunFunctionTask<void>::run (
    this=0x7fffc013c0a0) at /usr/include/qt5/QtConcurrent/qtconcurrentrunbase.h:130
#15 0x00007ffff35fa17d in QThreadPoolThread::run (this=0x7fffb0135c70)
    at thread/qthreadpool.cpp:93
#16 0x00007ffff35ff28c in QThreadPrivate::start (arg=0x7fffb0135c70)
    at thread/qthread_unix.cpp:341
#17 0x00007ffff30c05f4 in start_thread (arg=0x7fff7f4da700) at pthread_create.c:334
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff25978dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

`t a a bt`: https://gist.github.com/zetok/174b6c23077cc9572ae3405f757be757
other instance `t a a bt f`: https://gist.github.com/zetok/b187f374d55423f9828b3e3e440e3a96

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #3840

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4647)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
I moved video into ToxCall from ToxFriendCall, and added video connection tracking/destruction. ToxFriendCall now just handles friend timeout for calls, and inherits its video functionality from ToxCall. ToxGroupCall also inherits from ToxCall (which it did before), but this means it now contains video. All of it's video is disabled by just passing in a videoDisabled. To me, this seems like a more logical architecture, and allows for more easily integrating video into group calls in the future.

I also am quite sure about the diagnosis of the lambda not being disconnected causing the seg fault, but after fixing and then checking out back to tip, I could no longer reproduce the issue, so I can't with 100% confidence say that it's fixed.

If a reviewer can reproduce the bug, it would be good to test that this does indeed fix it.

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/toxcall.cpp, line 55 at r1](https://reviewable.io:443/reviews/qtox/qtox/4647#-Ku5Ux6_A2C3KlsY6Yfn:-Ku5Ux6_A2C3KlsY6Yfo:b-ctnxj0) ([raw file](https://github.com/qtox/qtox/blob/5fb55c1e011e8d53e1818912f180920083ede2e4/src/core/toxcall.cpp#L55)):*
> // Single line control statements are still required to use braces.

https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by noavarice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxcall.cpp, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4647#-Ku66J8Dexrqd-Cg5gsb:-Ku66J8Dexrqd-Cg5gsc:bcow1m4) ([raw file](https://github.com/qtox/qtox/blob/5fb55c1e011e8d53e1818912f180920083ede2e4/src/core/toxcall.cpp#L52)):*
> ```cpp
> 
>     if (videoEnabled) {
>         videoSource = new CoreVideoSource;
> ```

Does this compile?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxcall.cpp, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4647#-Ku66J8Dexrqd-Cg5gsb:-Ku6WO-VoAQRch5aQNGZ:bo5py2x) ([raw file](https://github.com/qtox/qtox/blob/5fb55c1e011e8d53e1818912f180920083ede2e4/src/core/toxcall.cpp#L52)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Does this compile?
</blockquote></details>

Apparently.. https://stackoverflow.com/questions/620137/do-the-parentheses-after-the-type-name-make-a-difference-with-new
Added parentheses.

---

*[src/core/toxcall.cpp, line 55 at r1](https://reviewable.io:443/reviews/qtox/qtox/4647#-Ku5Ux6_A2C3KlsY6Yfn:-Ku6Wx2tQIoAAF5Vyyls:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5fb55c1e011e8d53e1818912f180920083ede2e4/src/core/toxcall.cpp#L55)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

> // Single line control statements are still required to use braces.

https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by sudden6** [comment]
@noavarice and @Talkless lgtm?

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/toxcall.cpp, line 112 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw0q6auzJNhzv0S91cV:-Kw0q6av6JxIbkrED5iP:bqquby1) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L112)):*
> ```cpp
>         // to poweroff.
>         QtConcurrent::run([]() { CameraSource::getInstance().unsubscribe(); });
>         if (videoSource) {
> ```

I really don't know how all of this actually works, but is there really no possible races here? 

For example, if this thread is suspended for some longer time (to simulate, adding QThread::sleep() for a second  after run(), before if() ), or if QtConcurrent thread is slow (sleep before unsubscribe()).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxcall.cpp, line 111 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw914BCdy0iepwrbUjm:-Kw914BCdy0iepwrbUjn:bih2npv) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L111)):*
> ```cpp
>         // so we unsuscribe asynchronously, it's fine if the webcam takes a couple milliseconds more
>         // to poweroff.
>         QtConcurrent::run([]() { CameraSource::getInstance().unsubscribe(); });
> ```

How there is possible deadlock? `stream()` use only `streamMutex`. Then `unsubscribe()` just will wait for the end of `send_frame`, end of loop iteration and unlock `streamMutex` for us. Then starts unsubscribing. Where I'm wrong?

---

*[src/core/toxcall.cpp, line 112 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw0q6auzJNhzv0S91cV:-Kw90BYu2TlvIxYdprq2:b-xeurgm) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L112)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I really don't know how all of this actually works, but is there really no possible races here? 

For example, if this thread is suspended for some longer time (to simulate, adding QThread::sleep() for a second  after run(), before if() ), or if QtConcurrent thread is slow (sleep before unsubscribe()).
</blockquote></details>

`unsubscribe` doesn't delete `videoSource`. So it still be valid and can be used to delete.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by anthonybilinski** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxcall.cpp, line 111 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw914BCdy0iepwrbUjm:-KwqC_xr1QjDF3BIxCH1:b-4uzpku) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L111)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

How there is possible deadlock? `stream()` use only `streamMutex`. Then `unsubscribe()` just will wait for the end of `send_frame`, end of loop iteration and unlock `streamMutex` for us. Then starts unsubscribing. Where I'm wrong?
</blockquote></details>

I didn't write this code, just moved it FYI. But yes I also can't see how this would cause a deadlock. Should I remove the async call?

---

*[src/core/toxcall.cpp, line 112 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw0q6auzJNhzv0S91cV:-KwqE4feRTiYx23CxxIr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L112)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`unsubscribe` doesn't delete `videoSource`. So it still be valid and can be used to delete.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/toxcall.cpp, line 111 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw914BCdy0iepwrbUjm:-KwqGZAYWyX7YnXnsyX7:bl9x09i) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L111)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I didn't write this code, just moved it FYI. But yes I also can't see how this would cause a deadlock. Should I remove the async call?
</blockquote></details>

Oh.. if it's just moved, let's leave it as is :)
Probably, this hack was created before making CameraSource to work asynchronously. Probably, adding "TODO: check if async is still needed" will be enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647#-:-KwqHgHPZDz38_lTJuFz:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/core/toxcall.cpp, line 111 at r2](https://reviewable.io:443/reviews/qtox/qtox/4647#-Kw914BCdy0iepwrbUjm:-KwqMpoGKTFkOa5hBtPE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c4673bd66945a8f81045bf14d8a5c6f8d772b852/src/core/toxcall.cpp#L111)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Oh.. if it's just moved, let's leave it as is :)
Probably, this hack was created before making CameraSource to work asynchronously. Probably, adding "TODO: check if async is still needed" will be enough
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by Diadlo** [comment]
Please, rebase and fix conflicts

**Comment by anthonybilinski** [comment]
Will push rebase on top of https://github.com/qTox/qTox/pull/4784 once it makes it in, current state of ToxCall on tip doesn't work for friend calls or group calls.

**Comment by Diadlo** [comment]
@anthonybilinski #4784 was merged :)

**Comment by anthonybilinski** [comment]
I rebased to tip a week ago and had everything working, then rebased to tip just now, but calls are already broken before my changes again :P

Will look into a fix for for whatever the problem is now and put my refactor on top of that and update the PR shortly.

EDIT: issue opened https://github.com/qTox/qTox/issues/4799

**Comment by anthonybilinski** [comment]
Rebased to master tip.

**Comment by Talkless** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/core/toxcall.cpp, line 82 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BL1qoBeovV5QrqNam:-L6BL1qoBeovV5QrqNan:b2gbcws) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L82)):*
> ```cpp
> 	Audio& audio = Audio::getInstance();
> 	audio.subscribeInput();
> 	audio.subscribeOutput(alSource);
> ```

Reveiwable shows tabs are here?

---

*[src/core/toxcall.cpp, line 120 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BLF3gjEdQ7W7CgocF:-L6BLF3gjEdQ7W7CgocG:b-80mwec) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L120)):*
> ```cpp
> 	QObject::disconnect(audioInConn);
> 
> 	audioInConn = other.audioInConn;
> ```

Tabs?

---

*[src/core/toxcall.cpp, line 218 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BLLtKCmxLBGraPvpA:-L6BLLtKCmxLBGraPvpB:b2nhp3k) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L218)):*
> ```cpp
>                                                                timeoutTimer{other.timeoutTimer}
> {
> 	other.state = TOXAV_FRIEND_CALL_STATE_NONE;
> ```

Tab

---

*[src/core/toxcall.cpp, line 224 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BNB_NXswO6vkJiP6g:-L6BNB_NXswO6vkJiP6h:b-foz8s5) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L224)):*
> ```cpp
> ToxFriendCall& ToxFriendCall::operator=(ToxFriendCall&& other) noexcept
> {
>     ToxCall::operator=(move(other));
> ```

How does this `move` compiles without std:: ?

---

*[src/core/toxcall.cpp, line 227 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BM3eirT_6LLSH5k5B:-L6BM3eirT_6LLSH5k5C:b-63jk0x) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L227)):*
> ```cpp
>     state = other.state;
>     other.state = TOXAV_FRIEND_CALL_STATE_NONE;
>     timeoutTimer = other.timeoutTimer;
> ```

what if this->timeoutTimer was not nullptr, memory leak possible?

Consider refactoring timeoutTimer into std::unique_ptr, and use swap here to swap uniques.

---

*[src/core/toxcall.cpp, line 269 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BMHpLIpWZB9PFbk5S:-L6BMHpLIpWZB9PFbk5T:b2nhp3k) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L269)):*
> ```cpp
> ToxFriendCall::~ToxFriendCall()
> {
> 	Audio::getInstance().unsubscribeOutput(alSource);
> ```

Tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[src/core/toxcall.cpp, line 82 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BL1qoBeovV5QrqNam:-L6BOqXZ_XkC1cU4Yc1m:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L82)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Reveiwable shows tabs are here?
</blockquote></details>

Done.

---

*[src/core/toxcall.cpp, line 120 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BLF3gjEdQ7W7CgocF:-L6BOqzOJGu7ojliQaju:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L120)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Tabs?
</blockquote></details>

Done.

---

*[src/core/toxcall.cpp, line 218 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BLLtKCmxLBGraPvpA:-L6BOsjcna8Qfjg1ZaCS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L218)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Tab
</blockquote></details>

Done.

---

*[src/core/toxcall.cpp, line 224 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BNB_NXswO6vkJiP6g:-L6BOtQOFpvCXyX6Udhl:b-g2l6rn) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L224)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

How does this `move` compiles without std:: ?
</blockquote></details>

using namespace std; at top of file. The file also manually specifies `std::` in a few places. Do you think removing the `using` would be best, or removing the redundant `std::`'s

---

*[src/core/toxcall.cpp, line 227 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BM3eirT_6LLSH5k5B:-L6BUgu7bPPb8e3l2L-f:bq8p92) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L227)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

what if this->timeoutTimer was not nullptr, memory leak possible?

Consider refactoring timeoutTimer into std::unique_ptr, and use swap here to swap uniques.
</blockquote></details>

Good question. While looking at it I noticed neither the copy constructor nor move constructor are used for either ToxFriendCall or ToxGroupCall, and ToxCall's is only used by these. I had only modified them because they already were defined. What do you think about me just deleting them all?

---

*[src/core/toxcall.cpp, line 269 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BMHpLIpWZB9PFbk5S:-L6BQOp-0n3IyNkuk0oZ:b-h2uosq) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L269)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Tab
</blockquote></details>

Done.
Sorry about the tab spam =/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by Talkless** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/core/toxcall.cpp, line 224 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BNB_NXswO6vkJiP6g:-L6CnRoDW0IGt2IMRzkI:bcs0amk) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L224)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

using namespace std; at top of file. The file also manually specifies `std::` in a few places. Do you think removing the `using` would be best, or removing the redundant `std::`'s
</blockquote></details>

I would suggest to use `std::` (remove using) . In this case, there would be a conflict if class would have `move()` member function for any reason.

---

*[src/core/toxcall.cpp, line 227 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BM3eirT_6LLSH5k5B:-L6Cnm034CCnWZtKYx-6:b8nbl1z) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L227)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Good question. While looking at it I noticed neither the copy constructor nor move constructor are used for either ToxFriendCall or ToxGroupCall, and ToxCall's is only used by these. I had only modified them because they already were defined. What do you think about me just deleting them all?
</blockquote></details>

Well, removing (basically =deleting them all?) would be good option for cleanup if they are really not used. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---

*[src/core/toxcall.cpp, line 224 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BNB_NXswO6vkJiP6g:-L7hCo-H90R1P0_poUKV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L224)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I would suggest to use `std::` (remove using) . In this case, there would be a conflict if class would have `move()` member function for any reason.
</blockquote></details>

Done.

---

*[src/core/toxcall.cpp, line 227 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BM3eirT_6LLSH5k5B:-L7hK_Jzykjke5L_7gv7:b-7j8da6) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L227)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Well, removing (basically =deleting them all?) would be good option for cleanup if they are really not used. 
</blockquote></details>

It actually is used, my indexer just isn't smart enough to see the move constructors inside the containers :P
Migrated to std::unique_ptr. Good suggestion. I prefer this in general, and think we should in general use many more smart pointers instead of raw pointers in qTox.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by anthonybilinski** [comment]
FYI I rebased to master and just reproduced the old issue and verified the fix after this change.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 5 files at r4, 1 of 3 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647#-:-L7h_08lYUS9eQiSLJOI:b-jbsf8z)*

**Comment by Diadlo** [comment]
Still LGTM :)

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[src/core/toxcall.cpp, line 227 at r5](https://reviewable.io:443/reviews/qtox/qtox/4647#-L6BM3eirT_6LLSH5k5B:-L7jb_wJp7eAaf2RGgdi:b-awod9b) ([raw file](https://github.com/qtox/qtox/blob/12be0e0bdd8ed00f0e1b82e68b3c1020d4e57f74/src/core/toxcall.cpp#L227)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

It actually is used, my indexer just isn't smart enough to see the move constructors inside the containers :P
Migrated to std::unique_ptr. Good suggestion. I prefer this in general, and think we should in general use many more smart pointers instead of raw pointers in qTox.
</blockquote></details>

 >and think we should in general use many more smart pointers instead of raw pointers in qTox

Definetly.

Now the new question, is this custom move-assignment operator is now needed at all, if pointer is now handled with move-friendly `unique_ptr`? Maybe `=default` would suffice?

Only "manual" thing left is that enumerator `state`. Quick test shows that moving class instance makes simply a copy of enum, does not zero or swap old one (same as raw pointers, and other scalars probably).

Is is needed for moved-from object to have it set as NONE? 

Moved-from objects must be destructable and assignable. If not setting that `state` member var. makes it have ugly state that makes destruction dangerous (crash), then probably is needed to set `other.state` to NONE. Otherwise, maybe.. not?

Any thoughts?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4647)*

**Comment by anthonybilinski** [comment]
You're right ToxFriendCall move constructor and move assignment operator aren't explicitly needed. `state` being none has no special behaviour on destruction. Removed both and set to `= default;`

Looking into your question I found a bug with ToxCall's move constructor, and also the reason for it still being needed:
alSource is copied in the move of ToxCall, then unsubscribed from on destruction. Zero-ing the moved-from alSource makes the unsubscribe a no-op. My previous move constructor had the alSource copied and zero'd out, then also output re-subscribed which created an always increasing number of output subscriptions. I've changed that to copy alSource and zero the copied-from, and kept the move constructor for that reason.

I also noticed ~ToxFriendCall was unsubscribing alSource, which is already handled by ~ToxCall, so I've removed ~ToxFriendCall's destructor entirely.

Thanks for the very thorough review :)

**Pull request merged**
