### PR TITLE
style: add custom style for QCheckBox for dark theme (#5586)

### PR DESCRIPTION
**Pull request by TriKriSta**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)
Screenshot_20190328_212535

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5593)

### CODE REVIEW

**Comment by sudden6** [comment]
@TriKriSta just a tip for the next time, if you add `fixes #5586` to the PR message it will link to the issue and automatically close it once the PR is merged.

@anthonybilinski assigning to you since you reported the issue.

**Review by anthonybilinski — COMMENTED** [review]
It seems like re-styling the existing assets for dark theme, like we do with most things when changing a theme, instead of having duplicate assets pre-styled in the theme would be better. Is than an option here? Is there a reason to have the duplicate assets instead?

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5593#-:-LbGBTZ32Ph0sUuFe99v:b-86eg2q)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

**Comment by TriKriSta** [comment]
did you mean images (.svg)?  they cannot be changed in the css.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
Ah ok, looks like it's possible on the web and using a QSVGRenderer but not in this case.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5593#-:-LbI4iAwDsoDDFnvMWBa:b-8dly1q)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[themes/dark/settings/mainContent.css, line 37 at r1](https://reviewable.io/reviews/qtox/qtox/5593#-LbI5_Wp11mm9yAA86kq:-LbI5_WqDgXx4NH9DoaH:b7hof7x) ([raw file](https://github.com/qtox/qtox/blob/c778712b135877e1fcda97d1ab03dbd083475819/themes/dark/settings/mainContent.css#L37)):*
> ```CSS
> 
> QCheckBox::indicator:checked:pressed,
> QCheckBox::indicator:unchecked:pressed {
> ```

we don't have a pressed style in the default theme and I think it would be good to keep the two theme's behaviours as consistent as possible. I think I prefer with the pressed animation, could you add one for default as well?

EDIT: my mistake, we do have a pressed animation, just not explicitly defined.

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5593#-:-LbI6kOKDN3pXMNwEHX2:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
