### PR TITLE
Desktop Notifications

### PR DESCRIPTION
**Pull request by TheSpiritXIII**
This pull request comes with an abstract backend class that allows for the creation of desktop notification backeneds. In particular, I have implemented the Snorenotify library as a backend (which supports many backends itself).

You can enable or disable individual notification types including new message, highlighted, friend request, group invite, call invite, file transfer completed, friend online or friend offline.

This pull request has been tested on Linux and Windows. Note, that on Windows the install script does not install Snorenotify for you and on Linux, you have to have cmake with the extra cmake modules installed. For this purpose, Snorenotify notifications are disabled by default and you must enable it yourself by using ENABLE_NOTIFICATION_SNORE_BACKEND=YES while running qmake.

### CODE REVIEW

**Comment by quininer** [comment]
snapshot138

I can't compile this branch, I have installed libappindicator and snorenotify, whether what is missing?

**Comment by TheSpiritXIII** [comment]
@quininer Did you add ENABLE_NOTIFICATION_SNORE_BACKEND=YES as an additional qmake argument?

I rebased before I created a pull request and accidentally broke compiling when you don't have a backend which is what you're seeing now. I just fixed that, so if you only have "None" as an available backend in the settings, then you haven't configured properly (see my comment above).

**Comment by quininer** [comment]
Oh, it seems that because of my typo. Now it's passed. ;)

**Comment by quininer** [comment]
snapshot140

I use KDE5, it does not seem to find `knotifications`?

**Comment by agilob** [comment]
```
➜  qTox git:(notifications) qmake ENABLE_NOTIFICATION_SNORE_BACKEND=YES 
➜  qTox git:(notifications) make -j3
/usr/lib/qt/bin/uic src/android.ui -o ui_android.h
/usr/lib/qt/bin/uic src/loginscreen.ui -o ui_loginscreen.h
...
...
g++ -c -pipe -fno-exceptions -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -std=c++0x -Wall -W -D_REENTRANT -fPIC -DGIT_VERSION="\"9dff3feac72f77819d8d47b5b3b56513dea8fa34\"" -DTIMESTAMP=1439905907 -DLOG_TO_FILE -DQT_MESSAGELOGCONTEXT -DQTOX_PLATFORM_EXT -DQTOX_FILTER_AUDIO -DENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND -DENABLE_SYSTRAY_GTK_BACKEND -DENABLE_NOTIFICATION_SNORE_BACKEND -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I. -Ilibs/include -isystem /usr/include/glib-2.0 -isystem /usr/include/gtk-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/cairo -isystem /usr/include/ffmpeg -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/pango-1.0 -I/usr/lib64/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -isystem /usr/include/glib-2.0 -isystem /usr/include/gtk-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/cairo -isystem /usr/include/pango-1.0 -I/usr/lib64/glib-2.0/include -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/lib64/gtk-2.0/include -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -isystem /usr/local/include/snore/core -I/usr/local/lib64/libsnore-qt5/include -I/usr/local/lib/x86_64-linux-gnu/libsnore-qt5/include -isystem /usr/include/qt -isystem /usr/include/qt/QtOpenGL -isystem /usr/include/qt/QtSvg -isystem /usr/include/qt/QtWidgets -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtNetwork -isystem /usr/include/qt/QtXml -isystem /usr/include/qt/QtSql -isystem /usr/include/qt/QtCore -I. -I. -I/usr/lib/qt/mkspecs/linux-g++ -o snorenotificationbackend.o src/widget/snorenotificationbackend.cpp
In file included from src/widget/snorenotificationbackend.cpp:20:0:
src/widget/snorenotificationbackend.h:24:28: fatal error: libsnore/snore.h: No such file or directory
compilation terminated.
Makefile:2788: recipe for target 'snorenotificationbackend.o' failed
make: *** [snorenotificationbackend.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by quininer** [comment]
@agilob You may need to install new dependencies, `snorenotify` and `libappindicator`.

**Comment by quininer** [comment]
@agilob You may need to install new dependencies, `snorenotify` and `libappindicator`.

**Comment by TheSpiritXIII** [comment]
@quininer Do you have Snorenotify available in that combo box? If so, select it and yo should get Snorenotify settings that you can modify. I don't use KDE myself but Snorenotify likely supports it since the creator of it uses KDE himself.

@agilob Did you make install? Maybe your directories are located elsewhere? Which OS?

**Comment by quininer** [comment]
@TheSpiritXIII No, it only `None`.

**Comment by agilob** [comment]
ok, I did `./simple_make.sh` and it's compiling right now.

```
[  3%] Built target libsnore_lang_translation
[  4%] Automatic moc for target libsnore
[  4%] Built target libsnore_automoc
[ 30%] Built target libsnore
[ 31%] Automatic moc for target snorenotify
[ 31%] Built target snorenotify_automoc
```

Not sure if that's a way how it should work... It downloaded and compiled libsnore from source, it should take it from distro repository. I use arch.

**Comment by agilob** [comment]
qtox2

KDE5 with libsnore compiled from `simple_make.sh`, no backend detected?

**Comment by quininer** [comment]
snapshot141

snorenotify need to manually start. I succeeded. :D

**Comment by cuihaoleo** [comment]
I successfully compiled and ran patched qTox on Archlinux. It's awesome!

A feature request. When I'm chatting, it seems that the notifications of current chat will be sent as well. Could you please change the behaviour so that the chat event currently focused on won't be notified?

**Comment by zetok** [comment]
- [ ] segfault due to random spam: https://gist.github.com/zetok/99a74aa069544b426c13
  
  To reproduce, send 9 times `start` to spambot: C7719C6808C14B77348004956D1D98046CE09A34370E7608150EAD74C3815D30C8BA3AB9BEB9
  (beware that it'll make your qTox hang/crash)

**Comment by towlie** [comment]
@TheSpiritXIII  I should have this idea earlier but setting the status "occupied" should suppress all notifications until you set status "online" or "away" without touching/changing the settings.

**Comment by zetok** [comment]
Sadly, there's only one setting for receiving new messages, which means that incoming messages from friends and groupchats are treated equally, which is simply annoying - i.e. I really want to know when friend writes something, but I don't want to be notified about every single message in very active groupchat..
- [ ] separate options for new messages from friends and groupchats

**Comment by zetok** [comment]
Actually, notification doesn't even notify about all messages from groupchat, just about some, from time to time.
Not sure if that's a desired behaviour?

Edit: using freedesktop backend

**Comment by zetok** [comment]
- [ ] notification about new messages from groupchat doesn't show who sent message (Freedesktop backend)

**Comment by zetok** [comment]
- [ ] there's an issue with not vanishing green "Unread message" notification on this branch - is that a regression, or does that branch simply not contain fixes that are on master qTox?

**Comment by zetok** [comment]
- [ ] some weird issues with qTox freezing after notification has been clicked (Freedesktop backend) - most often happens when there is already qTox window open and then notification appears.
- [ ] **content of message and contact names should not be printed to stdout**, e.g.

```
 14:19:12: SNORE_WARNING void Snore::SnoreCorePrivate::slotNotificationClosed(Snore::Notification) Snore::Notification("Tox chat", "[subliun] zetok: toxcore still references tox.im", id = 1103)was already closed
```

**Comment by zetok** [comment]
- [ ] **missing documentation**

**Comment by albel727** [comment]
So, why was this PR left to rot?

**Comment by agilob** [comment]
Buggy and no one likes it.

**Comment by albel727** [comment]
It's clearly false that nobody likes it. I do, and there were guys above who liked it too. Though I don't exactly like snorenotify because it rate-limits notifications to 3 messages on-screen at all times.

Buggy how? The only bug worthy of mention was the spam crash, apparently in the bowels of snorenotify itself, which I can't reproduce now. Most importantly, this PR set up almost everything that is needed for implementing different notification providers, so one doesn't even need to rely on snorenotify, if its quality is questionable. Basic freedesktop notification backend can be written in 5 minutes and 15 lines, using hooks and GUI settings that this PR provided.

Everything else should only warrant separate issues, **after** this PR is merged. Instead it appears people want it brilliantly polished with ten hundred checkboxes and customizations, whereas basic notification functionality would suffice for now, would be useful immediately, and wouldn't affect those who don't want it at all. I doubt any dev in their right mind would try to see this PR through all the bikeshed without getting at least something merged first.

**Comment by zetok** [comment]
> Instead it appears people want it brilliantly polished with ten hundred checkboxes and customizations

Well, I want it to not break when I, or anyone else would use it.

**Comment by albel727** [comment]
How ten hundred checkboxes with per-friend settings for everything, as people want, are even related to "not breaking"? Not to mention that apparently this PR doesn't break anything.

**Comment by agilob** [comment]
Moved to #2771

**Pull request closed without merging**
