### PR TITLE
fix(UI): remove unnecessary space between a word and colon

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3970)

### CODE REVIEW

**Comment by Diadlo** [comment]
I think it will break all translation of this string. Can you change source string in translation files using `sed`?

**Comment by zetok** [comment]
I could, but it could conflict with translations from weblate.

**Comment by Diadlo** [comment]
:lgtm_strong: :

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3970#-:-KZ5aWPReWKWx_5Q3czs:b-yncq55)*

**Comment by zetok** [comment]
Changed also in translations.

**Comment by Diadlo** [comment]
Come on.. Everybody translated this string with space :/
We should update translation or don't update original string

**Comment by zetok** [comment]
>Come on.. Everybody translated this string with space :/

Not everybody, but yeah, that error should have been found at review of code that introduced the translatable string.

>We should update translation or don't update original string

Feel free to update translations :)

**Comment by Diadlo** [comment]
Done.

---

Reviewed 34 of 34 files at r2.
Review status: 27 of 35 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3970#-:-KZ8laSIbnvglrJl8b5g:b-896fix)*

**Comment by Diadlo** [comment]
¯\_(ツ)_/¯ :lgtm:

---

Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3970#-:-KZ8luzLj7gi2--KVCwq:b2tdjzh)*

**Pull request merged**
