### PR TITLE
fix(windows): workaround docker problem when extracting with tar

### PR DESCRIPTION
**Pull request by sudden6**
@nurupo can you take a look too?

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4571)

### CODE REVIEW

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4571#-:-KrIXtjBcOnl8GthdtPn:b-jbsf8z)*

**Comment by nurupo** [comment]
Not LGTM, fails with

```
Attempting to skip non-existent module qtsql.
```

**Comment by nurupo** [comment]
I guess there is no way to disable building of SQL module, at least in Qt 5.6 (newer versions of Qt added a more configurable exclude/include build options).

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[windows/cross-compile/build.sh, line 273 at r1](https://reviewable.io:443/reviews/qtox/qtox/4571#-KrMFfnIIgemfrleWjPi:-KrMFfnIIgemfrleWjPj:b-239h1b) ([raw file](https://github.com/qtox/qtox/blob/5a3ee31705b066cfda4c599f22c0b4b66438de54/windows/cross-compile/build.sh#L273)):*
> ```Shell
>     -skip webchannel \
>     -skip multimedia \
>     -skip sql \
> ```

This has to be removed, there is no `-skip sql` option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4571)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[windows/cross-compile/build.sh, line 273 at r1](https://reviewable.io:443/reviews/qtox/qtox/4571#-KrMFfnIIgemfrleWjPi:-KrMXGCgxs0UwAoaQ8ln:bxu1kh) ([raw file](https://github.com/qtox/qtox/blob/5a3ee31705b066cfda4c599f22c0b4b66438de54/windows/cross-compile/build.sh#L273)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

This has to be removed, there is no `-skip sql` option.
</blockquote></details>

fixed

For the future you can use `lgtm_cancel` to actually remove a lgtm and block merging

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4571)*

**Comment by nurupo** [comment]
Just tested that it builds fine with that fix.

**Pull request merged**
