### PR TITLE
Add direct link with template for submitting new issues

### PR DESCRIPTION
**Pull request by ghost**
It uses the template in https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md, filling all fields except "OS version".

There could be a more prominent place for that link as long as qTox is alpha.

### CODE REVIEW

**Comment by zetok** [comment]
Could you see whether you can change things to adjust to https://github.com/tux3/qTox/issues/2985#issuecomment-190956974 ?

**Comment by ghost** [comment]
@antis81 this comes from https://github.com/tux3/qTox/issues/2985#issuecomment-191461250, to avoid spamming that issue with questions about this particular commit

The replacement is looking better

``` c++
bodyUI->knownIssues->setText(
      tr("A list of all known issues may be found at our %1 at Github. If you discover a bug or security vulnerability within qTox, please %2 according to the guidelines in our %3 wiki article.")
        .arg(QString::fromUtf8("<a href=\"https://github.com/tux3/qTox/issues\" style=\"text-decoration: underline; color:#0000ff;\">%1</a>")
          .arg(tr("bug-tracker")))
        .arg(QString::fromUtf8("<a href=\"https://github.com/tux3/qTox/issues/new?body=%0A%0A---%0A%0AqTox:+%1%0ACommit+hash:+%2%0Atoxcore:+%3%0AQt:+%4%0AOS+version:\" style=\"text-decoration: underline; color:#0000ff;\">%5</a>")
          .arg(
              //  QString("%0"),  <--- FIXME
              QString(GIT_DESCRIBE),
              QString(GIT_VERSION),
              QString(TOXCORE_VERSION),
              QString(QT_VERSION_STR),
              tr("report it")))
        .arg(QString::fromUtf8("<a href=\"https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports\" style=\"text-decoration: underline; color:#0000ff;\">%1</a>")
          .arg(tr("Writing Useful Bug Reports")))
    );
```

But those `%0A`s in the URL are giving me headaches. `%0` is [not supposed](http://doc.qt.io/qt-5/qstring.html#arg) to be replaced, right? I haven't been able to fix that. Replacing `%0` with `%0` doesn't work. Using the .arg().arg().arg()... variation neither. What am I doing wrong?

**Comment by sudden6** [comment]
@kehugter you could concatenate the two parts of the URL with the `+` operator.
Also https://doc.qt.io/qt-5/qstring.html#toHtmlEscaped might be worth a look.

**Comment by ghost** [comment]
@sudden6 I'd have to make a lot of concatenations, the code will look ugly. Escaping with Qt is perhaps in the right direction, but this probably needs http://doc.qt.io/qt-5/qurl.html#toPercentEncoding and further method nesting, which isn't ideal either.

The workaround I found was to put the replacement with the misbehaving `%0`s at the end, so that the next `.arg()` wouldn't catch them. This hack will fail with more than one string containing URLs with encoded line breaks.

``` c++
bodyUI->knownIssues->setText(
      tr("A list of all known issues may be found at our %1 at Github. If you discover a bug or security vulnerability within qTox, please %3 according to the guidelines in our %2 wiki article.")
        .arg(QString::fromUtf8("<a href=\"https://github.com/tux3/qTox/issues\" style=\"text-decoration: underline; color:#0000ff;\">%1</a>")
          .arg(tr("bug-tracker")))
        .arg(QString::fromUtf8("<a href=\"https://github.com/tux3/qTox/wiki/Writing-Useful-Bug-Reports\" style=\"text-decoration: underline; color:#0000ff;\">%1</a>")
          .arg(tr("Writing Useful Bug Reports")))
        .arg(QString::fromUtf8("<a href=\"https://github.com/tux3/qTox/issues/new?body=%1A%1A---%1A%1AqTox:+%2%1ACommit+hash:+%3%1Atoxcore:+%4%1AQt:+%5%1AOS+version:\" style=\"text-decoration: underline; color:#0000ff;\">%6</a>")
          .arg(
              QString("%0"),
              QString(GIT_DESCRIBE),
              QString(GIT_VERSION),
              QString(TOXCORE_VERSION),
              QString(QT_VERSION_STR),
              tr("report it")))
    );
```

Tell me if it's good enough to (squash and?) push, and whether the form should be changed according to #3010.

**Comment by ghost** [comment]
This should be ready to merge. Replacements are working as they should (as described in the previous comment), so are translations.

**Pull request merged**
