### PR TITLE
style for qlineedit in status panel

### PR DESCRIPTION
**Pull request by agilob**
damn, I'm quick #341 

before:
status

after:
status1

### CODE REVIEW

**Comment by dubslow** [comment]
Er... I don't see the difference? How is this an improvement?

**Comment by agilob** [comment]
I defined background colour for qlineedit, it won't be inherited from system theme, the same with font colour, border was removed.
Build commit to see the different on your config.

**Comment by dubslow** [comment]
Hmm, it works (though I still can't tell the difference between your pics :D)

**Comment by agilob** [comment]
I have dark theme on KDE, Firefox, QtCreator and everything else, so my system theme is extremely similar to the one I defined ;)

**Comment by agilob** [comment]
Modified it a bit. I think it's better now.

indicate

**Comment by ghost** [comment]
Corners are inconsistent :^3

**Comment by agilob** [comment]
Now.
indicate1

**Comment by ghost** [comment]
Better :3

**Comment by agilob** [comment]
:*

**Pull request merged**
