### PR TITLE
feature(exif): Honour exif orientation tag

### LINKED ISSUE #1848: EXIF orientation for image previews
It would be a nice (but for practical purposes irrelevant) feature if qTox could display image previews (inline miniature and zoomed on hover) honouring the EXIF orientation tag.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #1848

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4643)

### CODE REVIEW

**Comment by Diadlo** [comment]
To make Travis works you should edit [`.travis/build-ubuntu-14-04.sh`](https://github.com/qTox/qTox/blob/master/.travis/build-ubuntu-14-04.sh#L28) and [`osx/qTox-Max-Deployer-ULTIMATE.sh`](https://github.com/qTox/qTox/blob/master/osx/qTox-Mac-Deployer-ULTIMATE.sh#L170)

**Comment by anthonybilinski** [comment]
Thanks, fixed

**Comment by sudden6** [comment]
Reviewed 5 of 7 files at r1.
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 329 at r1](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtrpyWujx6P_KS38Y_3:-KtrpyWvcGE-44H4Z926:b-uorwjs) ([raw file](https://github.com/qtox/qtox/blob/d63849cb5fdd1128a51a9ee97c9f704984d9adfd/INSTALL.md#L329)):*
> ```Markdown
> ```bash
> sudo zypper install \
>     libexif-dev \
> ```

it's `libexif-devel`

---

*[src/chatlog/content/filetransferwidget.cpp, line 612 at r1](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtrqDDLgKv3dMTtXgKh:-KtrqDDLgKv3dMTtXgKi:buy9g6j) ([raw file](https://github.com/qtox/qtox/blob/d63849cb5fdd1128a51a9ee97c9f704984d9adfd/src/chatlog/content/filetransferwidget.cpp#L612)):*
> ```cpp
>     ExifByteOrder byteOrder = exif_data_get_byte_order(exifData);
>     ExifEntry *exifEntry = exif_data_get_entry(exifData, EXIF_TAG_ORIENTATION);
>     if (exifEntry)
> ```

coding style, braces required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by anthonybilinski** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 329 at r1](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtrpyWujx6P_KS38Y_3:-KtrxFM5x0H5g_oHMXyJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d63849cb5fdd1128a51a9ee97c9f704984d9adfd/INSTALL.md#L329)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

it's `libexif-devel`
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 612 at r1](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtrqDDLgKv3dMTtXgKh:-KtrxEky0elis393J6A-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d63849cb5fdd1128a51a9ee97c9f704984d9adfd/src/chatlog/content/filetransferwidget.cpp#L612)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

coding style, braces required
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643#-:-Kts5qDy2RUVu4cW0SFh:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-KtwJSsxPlxnjmEofYvp:b9go26) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
> ```QMake
>                 -lv4l1 \
>                 -lv4l2 \
>                 -lavformat \
> ```

are you absolutely sure these can be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643#-:-KtwJWFwSkzdTFhIC1ud:b8b79qu)*

**Comment by anthonybilinski** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-KtwK3tdckYRGKvQQ1xj:b-1kbqoc) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

are you absolutely sure these can be removed?
</blockquote></details>

All four are already included in the LIBS list a little higher up so are duplicate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-KtwNFSauzftdUszR8V9:b-d2hj7k) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

All four are already included in the LIBS list a little higher up so are duplicate.
</blockquote></details>

But the ones above are after `-Bstatic` these ones are after `-Bdynamic`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by anthonybilinski** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-KtwPc1Yy0ExqI3R5R_X:b-8upddn) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

But the ones above are after `-Bstatic` these ones are after `-Bdynamic`
</blockquote></details>

That's a good point, I hadn't noticed. Is there a reason to both statically and dynamically link the same libraries?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-Ktx4ePbtaKyo1J-GQj8:b-3mejh4) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

That's a good point, I hadn't noticed. Is there a reason to both statically and dynamically link the same libraries?
</blockquote></details>

TBH I have no idea, @nurupo do you have any ideas why that could be needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 538 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5QbnK5er3NKA9juFk:-Ku5QbnLScE8Arip4Z7g:b-ogoaxw) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L538)):*
> ```cpp
>             return;
>         }
>         QByteArray imageFileData = imageFile.readAll();
> ```

could be `const QByteArray`

---

*[src/chatlog/content/filetransferwidget.cpp, line 540 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5Qg1cY3w1yYbcUMNi:-Ku5Qg1cY3w1yYbcUMNj:b46b8ol) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L540)):*
> ```cpp
>         QByteArray imageFileData = imageFile.readAll();
>         QImage image = QImage::fromData(imageFileData);
>         int exifOrientation = getExifOrientation(imageFileData.constData(), imageFileData.size());
> ```

could be `const int`

---

*[src/chatlog/content/filetransferwidget.cpp, line 604 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5QqbDR7UGSNB4rIFL:-Ku5QqbDR7UGSNB4rIFM:b-y11tcx) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L604)):*
> ```cpp
> int FileTransferWidget::getExifOrientation(const char* data, const int size)
> {
>     ExifData *exifData = exif_data_new_from_data((unsigned char*)data, size);
> ```

Could be ExifData * **const** exifData or maybe even **const** ExifData * **const** exifData

---

*[src/chatlog/content/filetransferwidget.cpp, line 605 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5R7BGLlo7IEfTcVxG:-Ku5R7BGLlo7IEfTcVxH:bp9wie7) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L605)):*
> ```cpp
> {
>     ExifData *exifData = exif_data_new_from_data((unsigned char*)data, size);
> ```

Also, would be nice to avoid c-style casts. And not to remove constness (I doubt that is needed).

Could be `exif_data_new_from_data(static_cast<const unsigned char*>(data), size);`

---

*[src/chatlog/content/filetransferwidget.cpp, line 610 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5R_2E6bhHEBCgRJZG:-Ku5R_2E6bhHEBCgRJZH:b-f4bl1o) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L610)):*
> ```cpp
> 
>     int orientation = 0;
>     ExifByteOrder byteOrder = exif_data_get_byte_order(exifData);
> ```

const ExifByteOrder

---

*[src/chatlog/content/filetransferwidget.cpp, line 611 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5RcNQyBLctpbjQk68:-Ku5RcNQyBLctpbjQk69:b3aub66) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L611)):*
> ```cpp
>     int orientation = 0;
>     ExifByteOrder byteOrder = exif_data_get_byte_order(exifData);
>     ExifEntry *exifEntry = exif_data_get_entry(exifData, EXIF_TAG_ORIENTATION);
> ```

const ExifEntry * const exifEntry ?

---

*[src/chatlog/content/filetransferwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5S7BT97tNlxh2xtnM:-Ku5S7BT97tNlxh2xtnN:b4tc25x) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L624)):*
> ```cpp
>     switch(orientation)
>     {
>     case 1:
> ```

It would be nice to have `enum class` of these, instead of "magic numbers"

---

*[src/chatlog/content/filetransferwidget.cpp, line 625 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5RuloXy18gSA0ME58:-Ku5RuloXy18gSA0ME59:b-x0sq4r) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L625)):*
> ```cpp
>     {
>     case 1:
>         break;
> ```

maybe just return here, no need to call tranfrom() at all I guess.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by anthonybilinski** [comment]
Review status: 5 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 538 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5QbnK5er3NKA9juFk:-Ku5v53jktFfrk3rCcda:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L538)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

could be `const QByteArray`
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 540 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5Qg1cY3w1yYbcUMNi:-Ku5v4k_y6YwGny5hTw5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L540)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

could be `const int`
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 604 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5QqbDR7UGSNB4rIFL:-Ku5ejsJb3yIWd9H0bGl:beul7wv) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L604)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Could be ExifData * **const** exifData or maybe even **const** ExifData * **const** exifData
</blockquote></details>

exif_data_get_byte_order and exif_data_free both require non-const pointers to non-const data. Not sure why since they shouldn't be modifying, but it's the API..

---

*[src/chatlog/content/filetransferwidget.cpp, line 605 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5R7BGLlo7IEfTcVxG:-Ku5fk_sikpWCM3agPNe:b-veat6v) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L605)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Also, would be nice to avoid c-style casts. And not to remove constness (I doubt that is needed).

Could be `exif_data_new_from_data(static_cast<const unsigned char*>(data), size);`
</blockquote></details>

changed to reinterpret_cast instead of static_cast, kept constness

---

*[src/chatlog/content/filetransferwidget.cpp, line 610 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5R_2E6bhHEBCgRJZG:-Ku5fySX7_5FV6nzMusz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L610)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const ExifByteOrder
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 611 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5RcNQyBLctpbjQk68:-Ku5fyqavFfTp61yoyCu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L611)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const ExifEntry * const exifEntry ?
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5S7BT97tNlxh2xtnM:-Ku5rFl6Zo-lTYxx2FgK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L624)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

It would be nice to have `enum class` of these, instead of "magic numbers"
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 625 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5RuloXy18gSA0ME58:-Ku5rMIiD9X_efb2xX65:b6ukz75) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L625)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

maybe just return here, no need to call tranfrom() at all I guess.
</blockquote></details>

That's true, there are also cases where only mirror is needed and could be mirrored and then returned. I started like that and changed it to just breaking in every case and always applying the transform after changing around transforms and forgetting to change which place returns and which place breaks. This seems simpler and less error prone, and a calling transform with a default-construct QTransform is probably either immediately returned or optimized out completely. Leaving as-is for now, let me know if you feel strongly.

---

*[src/chatlog/content/filetransferwidget.cpp, line 636 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku60K7fYN1bBh_WeHsx:-Ku60K7fYN1bBh_WeHsy:b-bxuerh) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L636)):*
> ```cpp
>         break;
>     case 5:
>         exifTransform.rotate(-90);
> ```

found a bug in case 5-8, fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by sudden6** [comment]
Review status: 5 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-Ku8lWQrUFm4wpZaz3ou:bdmb6lz) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

TBH I have no idea, @nurupo do you have any ideas why that could be needed?
</blockquote></details>

maybe leave it like it is here an open an issue/PR for further discussion?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by anthonybilinski** [comment]
Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-Ku8nUKUpwMnnWEp8vOh:b-de36d6) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

maybe leave it like it is here an open an issue/PR for further discussion?
</blockquote></details>

Created #4653

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by sudden6** [comment]
Reviewed 1 of 3 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[qtox.pro, line 234 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-KtwJSswd0F-FhN5gShH:-Ku8p29Z-UoUiOQSLh2W:b2nhpa7) ([raw file](https://github.com/qtox/qtox/blob/c49959711e6ed7dc6c0c244c34d323ab30fd0170/qtox.pro#L234)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Created #4653
</blockquote></details>

Thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643#-:-KuE9BfCC6cWGa2ZN1Ek:b-jbsf8z)*

**Comment by sudden6** [comment]
@Talkless can you lgtm if you think it's ok?

**Comment by Talkless** [comment]
@sudden6 I can do that? I am not an "maintaner" as such.

**Comment by sudden6** [comment]
Yes and it would be very helpful, review and lgtm isn't limited to maintainers, only merging is. (in case reviewable doesn't allow it, just leave a comment with `lgtm`)

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/chatlog/content/filetransferwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5S7BT97tNlxh2xtnM:-KuPrka-tdir8kW_aS2w:b-pn8vce) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L624)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I did a quick search, and looks like qTox has enums in CamelCase, so it would be nice to have consisten TopLef, TopRight, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by anthonybilinski** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/chatlog/content/filetransferwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku5S7BT97tNlxh2xtnM:-KuQ4kNnSNTg_R43kn0U:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L624)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I did a quick search, and looks like qTox has enums in CamelCase, so it would be nice to have consisten TopLef, TopRight, etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 3 of 7 files at r1, 1 of 2 files at r2, 1 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643#-:-KuQAh_p9sskQ9GeIE-S:b-jbsf8z)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/chatlog/content/filetransferwidget.cpp, line 636 at r2](https://reviewable.io:443/reviews/qtox/qtox/4643#-Ku60K7fYN1bBh_WeHsx:-KuQAp0p3_BuR6epJyoh:b32w0x) ([raw file](https://github.com/qtox/qtox/blob/a52189ea3bb3c608a309b8fb19ac3c4adbd9aff4/src/chatlog/content/filetransferwidget.cpp#L636)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

found a bug in case 5-8, fixed
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4643)*

**Pull request merged**
