### PR TITLE
[Refactor] Add model to FriendWidget (FriendChatroom)

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4977)

### CODE REVIEW

**Comment by Diadlo** [comment]
@nurupo Do you have ideas, why checksum could be changed? Should we update it?
https://travis-ci.org/qTox/qTox/jobs/347462578#L3702

**Comment by nurupo** [comment]
This is very weird, looks like sourceforge or the project maintainer somehow modified the file, which shouldn't happen. I'd email them asking what happened there, as this is fishy.

**Comment by nurupo** [comment]
Try restarting the build, I just wget'ed the tarball and got the correct sha256. SF was under the maintenance around the time this failure has happened, so it's possible that the tabrall URL was redirecting to the "website under maintenance" page. You can notice that the actual tarball is around 1.4MiB, while whatever Travis has downloaded is 652 bytes and of type text/html.

**Comment by Diadlo** [comment]
Still doesn't work. But you are right, it's page with text, that "Sourceforge site is currently in Disaster Recovery mode". Thanks, will wait

**Comment by nurupo** [comment]
Again? This wasn't the case when I wrote my message.

**Comment by nurupo** [comment]
`libexif` has moved away from SF to GitHub for source code hosting, but they still use SF for tarball hosting. You could change the wget URL to point to the git tag tarball from GitHub if you feel that SF is that unreliable https://github.com/libexif/libexif/tags, hopefully the release tarball on SF that we have been using and the git tag tarball don't differ that much. You'd need to update sha256 to that of GitHub's tarball if you would use that.

**Comment by sudden6** [comment]
@nurupo maybe it's also because SF has problems: https://twitter.com/sfnet_ops/status/969017161686626304

**Comment by nurupo** [comment]
Not "also", this is exactly why.

**Comment by sudden6** [comment]
Reviewed 5 of 13 files at r1.
Review status: 5 of 13 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/chatroom/friendchatroom.cpp, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/4977#-L7Qra_IGxoklWQWTxja:-L7Qra_JEKj8on4Er74Q:blovatr) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/model/chatroom/friendchatroom.cpp#L32)):*
> ```cpp
> int FriendChatroom::getCircleId() const
> {
>     return Settings::getInstance().getFriendCircleID(frnd->getPublicKey());
> ```

Using `Settings` like this seems like contrary to the intent of The Plan™, is it inevitable?

---

*[src/widget/widget.h, line 307 at r1](https://reviewable.io:443/reviews/qtox/qtox/4977#-L7Qss1eyCyqI3kevCyY:-L7Qss1fNL_ZPG1lfTqs:bwd88kg) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/widget.h#L307)):*
> ```objc
>     int icon_size;
> 
>     QMap<uint32_t, FriendWidget*> friendWidgets;
> ```

I don't quite get why we need all these collections, storing basically the same stuff. It will only complicate the code to keep them in sync.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4977)*

**Comment by Talkless** [comment]
Review status: 5 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/model/chatroom/friendchatroom.h, line 57 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDR6Sea-Lljl1nmgVVv:-LDR6Sea-Lljl1nmgVVw:b-hxhqc4) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/model/chatroom/friendchatroom.h#L57)):*
> ```objc
> 
> private:
>     bool active = false;
> ```

{false}, {nullptr} ?

---

*[src/widget/friendwidget.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDR6xWGAOXg5whFc70Y:-LDR6xWGAOXg5whFc70Z:btt6jc3) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/friendwidget.h#L69)):*
> ```objc
> 
> public:
>     FriendChatroom* chatroom;
> ```

Could it be `const chatroom`?

---

*[src/widget/friendwidget.cpp, line 321 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDREGL3AWWVHRjl7_wA:-LDREGL3AWWVHRjl7_wB:bv3cbkd) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/friendwidget.cpp#L321)):*
> ```cpp
> void FriendWidget::showDetails()
> {
>     auto iabout = new AboutFriend(frnd, &Settings::getInstance());
> ```

auto const iabout

---

*[src/widget/friendwidget.cpp, line 323 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDREZBU-UGzwJqAqije:-LDREZBU-UGzwJqAqijf:bgque0n) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/friendwidget.cpp#L323)):*
> ```cpp
>     auto iabout = new AboutFriend(frnd, &Settings::getInstance());
>     std::unique_ptr<IAboutFriend> about = std::unique_ptr<IAboutFriend>(iabout);
>     auto aboutUser = new AboutFriendForm(std::move(about), Widget::getInstance());
> ```

auto const

---

*[src/widget/about/aboutfriendform.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDREmXZAhhAw_r8h0Az:-LDREmXZAhhAw_r8h0B-:b3p3pqu) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/about/aboutfriendform.h#L25)):*
> ```objc
> private:
>     Ui::AboutFriendForm* ui;
>     std::unique_ptr<IAboutFriend> about;
> ```

const std::unique_ptr maybe?

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/4977)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/model/chatroom/friendchatroom.h, line 57 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDR6Sea-Lljl1nmgVVv:-LEtDZu52EOkrq2Gy7yP:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/model/chatroom/friendchatroom.h#L57)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

{false}, {nullptr} ?
</blockquote></details>

Done.

---

*[src/model/chatroom/friendchatroom.cpp, line 32 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-L7Qra_IGxoklWQWTxja:-LEtOwwc-QOWAFKtlrrC:b-nayvf1) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/model/chatroom/friendchatroom.cpp#L32)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Using `Settings` like this seems like contrary to the intent of The Plan™, is it inevitable?
</blockquote></details>

Required refactor in settings. I want to avoid it for now. Will be replaced on DI in the future

---

*[src/widget/friendwidget.h, line 69 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDR6xWGAOXg5whFc70Y:-LEtDair6ylMqOSEh7Cp:b7dm21) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/friendwidget.h#L69)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Could it be `const chatroom`?
</blockquote></details>

`chatroom` will used not as cost in future

---

*[src/widget/friendwidget.cpp, line 321 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDREGL3AWWVHRjl7_wA:-LEtDgrJCDTEbBXjTtKg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/friendwidget.cpp#L321)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

auto const iabout
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 323 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDREZBU-UGzwJqAqije:-LEtDh7U71ggMVLapgmr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/friendwidget.cpp#L323)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

auto const
</blockquote></details>

Done.

---

*[src/widget/widget.h, line 307 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-L7Qss1eyCyqI3kevCyY:-LEtNXB0B02qYqaVLXWG:b-gdrb) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/widget.h#L307)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I don't quite get why we need all these collections, storing basically the same stuff. It will only complicate the code to keep them in sync.
</blockquote></details>

What is "the same stuff"? It's models and widgets. Absolutely not the same. When widgets will fully splited on model and view, we can move container with widgets out of `Widget`. Or finally drop, if widget parent will delete it. But until "FriendWidget" provide some logic, we can't drop it

---

*[src/widget/about/aboutfriendform.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-LDREmXZAhhAw_r8h0Az:-LEtOkyf3PicUuBot8P8:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/about/aboutfriendform.h#L25)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const std::unique_ptr maybe?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/4977)*

**Comment by Diadlo** [comment]
@sudden6 ping

**Review by sudden6 — APPROVED** [review]
> Reviewed 1 of 13 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/4977)* status: 0 of 1 LGTMs obtained

___
*[src/model/chatroom/friendchatroom.cpp, line 32 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-L7Qra_IGxoklWQWTxja:-LHDUVEK26Xs_xj0ah4_:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/model/chatroom/friendchatroom.cpp#L32)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Required refactor in settings. I want to avoid it for now. Will be replaced on DI in the future
</blockquote></details>

ok
___
*[src/widget/widget.h, line 307 at r1](https://reviewable.io/reviews/qtox/qtox/4977#-L7Qss1eyCyqI3kevCyY:-LHDVL-_5xpVCKjw7ZMK:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/9ea44ee07e137769d90539243a5a3eef9a727e9a/src/widget/widget.h#L307)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What is "the same stuff"? It's models and widgets. Absolutely not the same. When widgets will fully splited on model and view, we can move container with widgets out of `Widget`. Or finally drop, if widget parent will delete it. But until "FriendWidget" provide some logic, we can't drop it
</blockquote></details>

ok

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: sorry, this went under my radar

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/4977#-:-LHDVYKj9x23X_P6YBnR:bhbxag2)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
