### PR TITLE
feat(core): add send message error handling

### PR DESCRIPTION
**Pull request by anthonybilinski**
remove unused sendMessageResult signal

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5531)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5531)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 663 at r1](https://reviewable.io/reviews/qtox/qtox/5531#-LXEMwM-8hfoNCfOH3GH:-LXEMwM-8hfoNCfOH3GI:b-azgrll) ([raw file](https://github.com/qtox/qtox/blob/25cf1ac2172f619226034b66e1a08d1cdbc5caa1/src/core/core.cpp#L663)):*
> ```cpp
>     int size = message.toUtf8().size();
>     if (size > tox_max_message_length()) {
>         qCritical() << "Core::sendMessageWithType called with message of size:" << size << "when max is:" << maxSize <<". Ignoring.";
> ```

where does `maxSize` come from? why not store the result of `tox_max_message_length()` in a constant in this function and print that?

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5531)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 663 at r1](https://reviewable.io/reviews/qtox/qtox/5531#-LXEMwM-8hfoNCfOH3GH:-LXERBGr-CPuVf548A4Q:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/25cf1ac2172f619226034b66e1a08d1cdbc5caa1/src/core/core.cpp#L663)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

where does `maxSize` come from? why not store the result of `tox_max_message_length()` in a constant in this function and print that?
</blockquote></details>

Done.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5531)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 665 at r2](https://reviewable.io/reviews/qtox/qtox/5531#-LXETHQI4d9O13GBViL1:-LXETHQI4d9O13GBViL2:b-hf339g) ([raw file](https://github.com/qtox/qtox/blob/5289c99962b6be374e92163313bc620eef2cbd58/src/core/core.cpp#L665)):*
> ```cpp
>     if (size > maxSize) {
>         qCritical() << "Core::sendMessageWithType called with message of size:" << size << "when max is:" << maxSize <<". Ignoring.";
>         return 0;
> ```

Can you document (doxygen) that `0` is a special return value? It also seems to clash with the value range of `tox_friend_send_message` where `0` is a valid message receipt. Not sure what to do here.
___
*[src/core/core.cpp, line 672 at r2](https://reviewable.io/reviews/qtox/qtox/5531#-LXEU7Qk7BNZ2zWycyro:-LXEU7Qk7BNZ2zWycyrp:b5h57b2) ([raw file](https://github.com/qtox/qtox/blob/5289c99962b6be374e92163313bc620eef2cbd58/src/core/core.cpp#L672)):*
> ```cpp
>     int receipt = tox_friend_send_message(tox.get(), friendId, type,
>                                           cMessage.data(), cMessage.size(), &error);
>     parseFriendSendMessageError(error);
> ```

shouldn't there be a different return value in case there was an error? see also the comment from above.

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5531)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 665 at r2](https://reviewable.io/reviews/qtox/qtox/5531#-LXETHQI4d9O13GBViL1:-LXEYqW06LqI5BA1eN3N:b-a7ev6z) ([raw file](https://github.com/qtox/qtox/blob/5289c99962b6be374e92163313bc620eef2cbd58/src/core/core.cpp#L665)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you document (doxygen) that `0` is a special return value? It also seems to clash with the value range of `tox_friend_send_message` where `0` is a valid message receipt. Not sure what to do here.
</blockquote></details>

I've got an upcoming PR that will split error handling from the receipt number to not treat 0 specially. This one's intended to be non-functional, so I've retained the 0-receipt number being error from the old behaviour.
___
*[src/core/core.cpp, line 672 at r2](https://reviewable.io/reviews/qtox/qtox/5531#-LXEU7Qk7BNZ2zWycyro:-LXEZf1wDe2GOA27zbFR:bb73xfv) ([raw file](https://github.com/qtox/qtox/blob/5289c99962b6be374e92163313bc620eef2cbd58/src/core/core.cpp#L672)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

shouldn't there be a different return value in case there was an error? see also the comment from above.
</blockquote></details>

Same

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5531)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 665 at r2](https://reviewable.io/reviews/qtox/qtox/5531#-LXETHQI4d9O13GBViL1:-LXEoi-nDfhWtjdk_cOY:bb87tj0) ([raw file](https://github.com/qtox/qtox/blob/5289c99962b6be374e92163313bc620eef2cbd58/src/core/core.cpp#L665)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I've got an upcoming PR that will split error handling from the receipt number to not treat 0 specially. This one's intended to be non-functional, so I've retained the 0-receipt number being error from the old behaviour.
</blockquote></details>

ok then
___
*[src/core/core.cpp, line 672 at r2](https://reviewable.io/reviews/qtox/qtox/5531#-LXEU7Qk7BNZ2zWycyro:-LXEojFM3pMMOMHP5Zik:bb87tj0) ([raw file](https://github.com/qtox/qtox/blob/5289c99962b6be374e92163313bc620eef2cbd58/src/core/core.cpp#L672)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Same
</blockquote></details>

ok then

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5531#-:-LXEooWwBH6FeVR9pvL-:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
