### PR TITLE
fix(exit): delete heap-based QApplication before exit

### LINKED ISSUE #4648: Segfault on exit after activate handled by IPC
##### Brief Description
Commit hash:  c4995971

Reproducible: Rarely

##### Steps to reproduce

1. one qTox instance running
2. start a second qTox instance with no arguments
3. Repeat ~50 times

##### Observed Behavior
```
~/builds/qTox $ ./qtox 
[05:48:53.167 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
[05:48:53.188 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  5260399222953654004
[05:48:53.188 UTC] ipc.cpp:73 : Debug: Attaching to the global shared memory
[05:48:53.188 UTC] main.cpp:249 : Debug: built on:  22:48:13 Sep 13 2017 ( 1505275372 )
[05:48:53.188 UTC] main.cpp:250 : Debug: commit:  00166fe8d625fc383773d12cc1cdc3f69223d3c0 

[05:48:53.188 UTC] ipc.cpp:125 : Debug: postEvent  "activate" to 0
Segmentation fault
```

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4648

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4649)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
I tested this with many iterations before and after the fix, saw occasional seg faults before, zero after.

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4649#-:-Ku69nT_TG2iEZRcJV9U:b-jbsf8z)*

**Comment by noavarice** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4649)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4649#-:-Ku8l2-K34nA-iCfnlaE:b-jbsf8z)*

**Pull request merged**
