### PR TITLE
fix: Fix freez on circle removing

### LINKED ISSUE #4419: Crash when attempting to remove a circle with a user in it
##### Brief Description

OS: Windows 10 64-bit
qTox version: v1.9.0-104-g5d117e6
Commit hash: 5d117e6af854de194dc16575f1fe5c95a43741c8
toxcore: 0.1.8
Qt: 5.5.1
Hardware: 
…

Reproducible: Always 

##### Steps to reproduce
1. Add user to a new circle
2. Attempt to remove circle with a user in it

##### Observed Behavior
Crash when attempting to remove circle with a user in it

##### Expected Behavior
Warning dialog to instruct user to remove all people from the circle before removing it
--or--
Disable the menu item if the circle is not empty

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4419

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4423)

### CODE REVIEW

**Comment by ezavod** [comment]
Great, this works flawless for me.
Tested removing circles with one and more friends, did not experience any problems.

**Comment by Diadlo** [comment]
Please, use `lgtm` button in reviewable

**Comment by ezavod** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4423#-:-KlARkK57IiHoJv7hm0S:b-jbsf8z)*

**Comment by ezavod** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4423)*

**Pull request merged**
