### PR TITLE
Fix resources URI: change double slash to one and add one if missing

### LINKED ISSUE #2541: qTox crashes after clicking the login button
It doesn't crash always but often.
https://gist.github.com/towlie/cf23cfd75fed707e14fe

bt full:
https://gist.github.com/towlie/0394ba0ba93ac1552ebe

### PR DESCRIPTION
**Pull request by agilob**
closes  #2541

### CODE REVIEW

**Comment by tux3** [comment]
No. This doesn't fix #2541

**Comment by agilob** [comment]
It doesnt?

**Comment by agilob** [comment]
ah ok

**Comment by tux3** [comment]
#2541 is a crash because of using uninitialized data. 
Changing a resource's URI can't cause a crash. Worst case, some images will be missing.

Did you test your code before sending it?

**Comment by agilob** [comment]
Ok  I didn't see the comment, sorry.

> Did you test your code before sending it? 

Yes, I did test it, but didn't crash for me. Instead tray icon was not responding to ~~left~~ right click

**Comment by tux3** [comment]
It's not about not seeing the comment, you really need to be more careful. It's not the first time you send obviously broken code without bothering to test.
And then you send a broken fix that doesn't do anything!

I asked you before, please test your code if you're not 100% sure it's correct, that's the bare minimum.

**Comment by agilob** [comment]
I test it now on my arch, ubuntu mint with xfce and windows7 64bit and only regression was on windows, it didn't show tray menu on right click, just nothing happened, but there was no crash.

Sorry about that.

**Comment by tux3** [comment]
On Windows we're connecting to 0xBAADFOOD, this is ought to crash 9 out of 10 times.
I can see how this could not crash on Linux since it doesn't mark uninitialized data the same way windows does, so use valgrind, it'll **very** clearly catch this bug every time. 

The point remains that this is a crash _on startup_, those kind of stupid bugs shouldn't ever get through.

**Comment by agilob** [comment]
I never used valgrind before, I'll give it a try next time :)

Thanks

**Pull request merged**
