### PR TITLE
[WIP] Chore/win deploy

### PR DESCRIPTION
**Pull request by sudden6**
We still need a clever way to only deploy on Stage 3 builds.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5017)

### CODE REVIEW

**Comment by sudden6** [comment]
For nightlies we could also use Bintray as hoster.

**Comment by sudden6** [comment]
anyone has an idea how to test this? @tox-user @anthonybilinski

**Comment by tox-user** [comment]
What exactly needs testing?

**Comment by sudden6** [comment]
I don't know how I can test the deployment to github releases.

**Comment by Diadlo** [comment]
@sudden6 For test replace `tags: true` on `branch: winDeploy` and push your branch in qTox/winDeploy

**Comment by sudden6** [comment]
Working and tested version in #5083

**Pull request closed without merging**
