### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by aaannndddyyy**

### CODE REVIEW

**Comment by zetok** [comment]
cc: @AWeinb , @cebe , @Lednerb , @ovalseven8 , @rubo77 ?

**Comment by Lednerb** [comment]
:+1:

**Comment by ovalseven8** [comment]
One addition:
Please add a space there at the end: https://github.com/aaannndddyyy/qTox/blob/patch-10/translations/de.ts#L1959

**Comment by aaannndddyyy** [comment]
@ovalseven8 Thx for the hint. Fixed.

**Pull request merged**
