### PR TITLE
fix(activity): change last activity time from QDate to QDateTime

### PR DESCRIPTION
**Pull request by anthonybilinski**
* Allows for strict sorting based on last activity in the future

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5667)

### CODE REVIEW

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5667#-:-Lf3_FPU949JNnDPRu6X:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/friendlistwidget.cpp, line 646 at r1](https://reviewable.io/reviews/qtox/qtox/5667#-Lf3ZTCH8Ln_Z4GMQI3J:-Lf3ZTCH8Ln_Z4GMQI3K:b-atxwyq) ([raw file](https://github.com/qtox/qtox/blob/3b18793c2ef28a66a81221ce1b70891ccf6e005d/src/widget/friendlistwidget.cpp#L646)):*
> ```cpp
>     int timeIndex = static_cast<int>(getTimeBucket(time));
>     QWidget* widget = activityLayout->itemAt(timeIndex)->widget();
>     CategoryWidget* categoryWidget = static_cast<CategoryWidget*>(widget);
> ```

I see 4 block with same logic. What about new `getTimeCategoryWidget` method? Feel free to leave as is.
```
const auto activityTime = getActiveTimeFriend(contact);
int timeIndex = static_cast<int>(getTimeBucket(activityTime));
QWidget* widget = activityLayout->itemAt(timeIndex)->widget();
CategoryWidget* categoryWidget = qobject_cast<CategoryWidget*>(widget);
```

**Comment by Diadlo** [comment]
Ups... Travis [failed](https://travis-ci.org/qTox/qTox/jobs/533661487#L2776). Not so LGTM :)

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5667)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/friendlistwidget.cpp, line 646 at r1](https://reviewable.io/reviews/qtox/qtox/5667#-Lf3ZTCH8Ln_Z4GMQI3J:-Lf3jfwD2S6-fE7legGH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3b18793c2ef28a66a81221ce1b70891ccf6e005d/src/widget/friendlistwidget.cpp#L646)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I see 4 block with same logic. What about new `getTimeCategoryWidget` method? Feel free to leave as is.
```
const auto activityTime = getActiveTimeFriend(contact);
int timeIndex = static_cast<int>(getTimeBucket(activityTime));
QWidget* widget = activityLayout->itemAt(timeIndex)->widget();
CategoryWidget* categoryWidget = qobject_cast<CategoryWidget*>(widget);
```

</blockquote></details>

Done.

**Review by Diadlo — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5667)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/friendlistwidget.cpp, line 455 at r2](https://reviewable.io/reviews/qtox/qtox/5667#-Lf3xTYtEoeYPlXz9Iog:-Lf3xTYtEoeYPlXz9Ioh:b5heqk8) ([raw file](https://github.com/qtox/qtox/blob/40f379cd944146ac3e3f0324d59e9d61e82e2b37/src/widget/friendlistwidget.cpp#L455)):*
> ```cpp
>         }
> 
>         CategoryWidget* categoryWidget = getTimeCategoryWidget(friendWidget->getFriend());
> ```

Here and is `index` was used (and used later). I think its removing can have side effects

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5667)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/friendlistwidget.cpp, line 455 at r2](https://reviewable.io/reviews/qtox/qtox/5667#-Lf3xTYtEoeYPlXz9Iog:-Lf4CFJz5FOOncsohn2f:b-kn0usi) ([raw file](https://github.com/qtox/qtox/blob/40f379cd944146ac3e3f0324d59e9d61e82e2b37/src/widget/friendlistwidget.cpp#L455)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Here and is `index` was used (and used later). I think its removing can have side effects
</blockquote></details>

Done. Good catch :)

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5667#-:-Lf4_0Yg9sc9qTyr5uNV:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
