### PR TITLE
docs(INSTALL): updated Windows build instructions

### PR DESCRIPTION
**Pull request by nweyand**
There was some folder mixup, probably due to some parts of the instruction being written out of a 32 bit Windows perspective (where “C:\Program Files” is the default location for installed programs) and other parts written out of 64 bit perspective (where there are two distinct folders for 32 and 64 bit content).

I’ve made sure all paths are compliant with the x64 version now (I’ve left out x86 instructions as I would have no way to test them, x86 is slowly but surely dying out AND people compiling on older systems should be aware anyway that instructions referring to install paths including “C:\Program Files (x86)\” will need some adjustment on their systems).

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4304)

### CODE REVIEW

**Comment by zetok** [comment]
Are windows instructions with fixed paths sufficient to compile qTox?

According to @DX37 current instructions don't work, and so #4291 replaces with working instructions that use MSYS2.

If instructions with fixed path do the job, it would be good to have both ways of compiling listed in INSTALL.md.

**Comment by DX37** [comment]
@zetok As I said in IRC, the current instruction is not that it does not work - it uses very old libraries. And in general, the usual MinGW is pretty old, while the optimized and improved MinGW-w64 is still alive.

**Comment by nweyand** [comment]
> Are windows instructions with fixed paths sufficient to compile qTox?

I am not sure. I have not proceeded so far yet: Due to a problem while downloading something within bootstrap.bat (or rather bootstrap.sh) I haven’t been able to finish compilation. But this fixes everything at least up to the point that one can run the bootstrap shell script without having unused directory entries in the path.

EDIT: As for mingw... Why not switch to clang? It produces better error messages 90% of the time and also generates faster executables. (The only possible drawback is that you might have to compile Qt yourself ATM – but that is supported out of the box.)

**Comment by nweyand** [comment]
This addresses #4303 and adds a small warning about there possibly being false positives on some anti virus software and refers to the appropriate [wiki page](https://github.com/qTox/qTox/wiki/Problematic-antiviruses).

**Comment by DX37** [comment]
@nweyand Instead of using separated programs, with PATH editing, some system changes and etc, can we just use MSYS2, which just installs in one folder, use separated shell that doesn't affect system's PATH and can provide a simple way to install dependencies?

**Comment by DX37** [comment]
Just one new working instruction instead of patching an old and ancient one.

**Comment by nweyand** [comment]
Before reading your comments I wasn’t aware that this was being discussed. Is there already a pull request for your solution?

In any way my suggestion would be to merge my changes as a quick-fix and then start discussing and testing your changes and later use them to overwrite (part of) what I’ve suggested here. The latest addition I made (about possible false positives on some AV SW) stays valid though, even if the process of getting the dependencies is fixed.

**Comment by DX37** [comment]
@nweyand It's #4291.

**Comment by nweyand** [comment]
Ah, your suggestion really looks promising.

I fully support your version over the current instructions provided there is a way to statically build qTox (i.e. take the .exe (and necessary .dll’s), put them into a .7z file and pass them to a friend and be assured that it will work on his PC afterward).
Also if you would like to, I could suggest some grammar and spelling improvements?

**Comment by DX37** [comment]
> Also if you would like to, I could suggest some grammar and spelling improvements?

Sure. I know English, but not very well :smile:

**Comment by nweyand** [comment]
Cool. Would you like me to make a lot of comments in your pull request or may I get access to your repo so that I can modify it directly? Or would you prefer for me to add a pull request to your repo?

EDIT: Maybe we should migrate this discussion to some place that is more appropriate – it has strayed far from the original topic. :)

**Comment by DX37** [comment]
@zetok I think you can close this PR 🤔

**Comment by nweyand** [comment]
> @zetok I think you can close this PR :thinking:

no.

> In any way my suggestion would be to merge my changes as a quick-fix and then start discussing and testing your changes and later use them to overwrite (part of) what I’ve suggested here. The latest addition I made (about possible false positives on some AV SW) stays valid though, even if the process of getting the dependencies is fixed.

As I said: Use this as a quick-fix ;)

**Comment by nweyand** [comment]
Any chance this could be merged? #4304 will take a while still before it is ready for merging and in the meantime there is no working instruction on how to get qTox to compile properly.

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4304#-:-KgSGZeiRfI_cKcovLsd:b-jbsf8z)*

**Pull request merged**
