### PR TITLE
[Refactor] Group widget

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4560)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 2 files at r1, 1 of 2 files at r2.
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1744 at r2](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqnTQQcxReqnnpvVDNx:-KqnTQQdyrud6fPa2CyU:b-hlii7k) ([raw file](https://github.com/qtox/qtox/blob/6b798cda0537333824e0e57f7cf8dd3a63937be4/src/widget/widget.cpp#L1744)):*
> ```cpp
>     g->getChatForm()->setName(title);
> 
>     if (widget->isActive())
> ```

braces needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r2, 4 of 4 files at r3.
Review status: 2 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by sudden6** [comment]
Reviewed 5 of 5 files at r4, 4 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by noavarice** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 5 of 5 files at r4, 4 of 4 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/group.cpp, line 74 at r6](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqsJH5wBb4sk7gTDLa:-KqqsJH5wBb4sk7gTDLb:b-cop00t) ([raw file](https://github.com/qtox/qtox/blob/7b53a35c1b5d6df764f3fa86cb33df857fbd9690/src/group.cpp#L74)):*
> ```cpp
> void Group::setName(const QString& name)
> {
>     if (title != name) {
> ```

I think all title validation checks (like `isEmpty` and etc.) should be stored in one place for consistency

---

*[src/group.cpp, line 75 at r6](https://reviewable.io:443/reviews/qtox/qtox/4560#-Kqqs5ZklLARFDKeBOoc:-Kqqs5ZklLARFDKeBOod:b-iqo8fs) ([raw file](https://github.com/qtox/qtox/blob/7b53a35c1b5d6df764f3fa86cb33df857fbd9690/src/group.cpp#L75)):*
> ```cpp
> {
>     if (title != name) {
>         title = name.left(128);
> ```

Optionally make `128` const

---

*[src/widget/contentdialog.cpp, line 759 at r3](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqlsHtldDeRRcuM8Wg:-KqqlsHuceXVO_ECXDeH:b-v67c0e) ([raw file](https://github.com/qtox/qtox/blob/c5598ed377a1aef1b4acc4e3c6c4a125c490bf05/src/widget/contentdialog.cpp#L759)):*
> ```cpp
>  * @param groupId Id of group to update.
>  */
> void ContentDialog::updateGroupWidget(uint32_t groupId)
> ```

Maybe split this slot for each connected signal (`titleChanged` and `userListChanged`)?

---

*[src/widget/friendlistwidget.cpp, line 28 at r4](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqpKqP02ebWvQMZmt-:-KqqpKqP02ebWvQMZmt0:b-1njkz3) ([raw file](https://github.com/qtox/qtox/blob/d47f596ddf933a42096186968f13752ac53354ff/src/widget/friendlistwidget.cpp#L28)):*
> ```cpp
> #include "src/friend.h"
> #include "src/friendlist.h"
> #include "src/group.h"
> ```

Unnecessary header since `grouplist.h` is included

---

*[src/widget/widget.cpp, line 1741 at r4](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqqUlxO7J0P7Ua-1Bp:-KqqqUlxO7J0P7Ua-1Bq:byp3jzi) ([raw file](https://github.com/qtox/qtox/blob/d47f596ddf933a42096186968f13752ac53354ff/src/widget/widget.cpp#L1741)):*
> ```cpp
> 
>     GroupWidget* widget = g->getGroupWidget();
>     contactListWidget->renameGroupWidget(groupnumber, title);
> ```

`renameGroupWidget` first parameter is `uint32_t` while `groupnumber` has `int` type. May this be dangerous in some way?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/group.cpp, line 74 at r6](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqsJH5wBb4sk7gTDLa:-KqqvV2GuweBvrl38LC2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7b53a35c1b5d6df764f3fa86cb33df857fbd9690/src/group.cpp#L74)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I think all title validation checks (like `isEmpty` and etc.) should be stored in one place for consistency
</blockquote></details>

Done.

---

*[src/group.cpp, line 75 at r6](https://reviewable.io:443/reviews/qtox/qtox/4560#-Kqqs5ZklLARFDKeBOoc:-KqqwIP-MAOS6vxW_NiM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7b53a35c1b5d6df764f3fa86cb33df857fbd9690/src/group.cpp#L75)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Optionally make `128` const
</blockquote></details>

Done.

---

*[src/widget/contentdialog.cpp, line 759 at r3](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqlsHtldDeRRcuM8Wg:-Kqr0C5grBP56KeH1AGC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c5598ed377a1aef1b4acc4e3c6c4a125c490bf05/src/widget/contentdialog.cpp#L759)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Maybe split this slot for each connected signal (`titleChanged` and `userListChanged`)?
</blockquote></details>

Done.

---

*[src/widget/friendlistwidget.cpp, line 28 at r4](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqpKqP02ebWvQMZmt-:-KqqwpPnsKyyi4CiLXOB:bon0579) ([raw file](https://github.com/qtox/qtox/blob/d47f596ddf933a42096186968f13752ac53354ff/src/widget/friendlistwidget.cpp#L28)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Unnecessary header since `grouplist.h` is included
</blockquote></details>

`grouplist.h` doesn't include `group.h`

---

*[src/widget/widget.cpp, line 1744 at r2](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqnTQQcxReqnnpvVDNx:-KqqxYCybppfPOp5ar3X:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b798cda0537333824e0e57f7cf8dd3a63937be4/src/widget/widget.cpp#L1744)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces needed
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 1741 at r4](https://reviewable.io:443/reviews/qtox/qtox/4560#-KqqqUlxO7J0P7Ua-1Bp:-KqqxJInthnqotarVhi2:bz2um1x) ([raw file](https://github.com/qtox/qtox/blob/d47f596ddf933a42096186968f13752ac53354ff/src/widget/widget.cpp#L1741)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`renameGroupWidget` first parameter is `uint32_t` while `groupnumber` has `int` type. May this be dangerous in some way?
</blockquote></details>

It's dangerous in some case. But this cases are very rare on modern systems. I want to avoid replacing `groupnumber` type everywhere in this PR. But plan to do it later

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by noavarice** [comment]
Reviewed 11 of 11 files at r7, 2 of 2 files at r8, 4 of 4 files at r9, 5 of 5 files at r10, 4 of 4 files at r11, 3 of 3 files at r12, 4 of 4 files at r13, 4 of 4 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/group.cpp, line 72 at r12](https://reviewable.io:443/reviews/qtox/qtox/4560#-Kqr4kUzXIJNF7dF5O9x:-Kqr4kUzXIJNF7dF5O9y:b-qkdckw) ([raw file](https://github.com/qtox/qtox/blob/e13b4acf9d1c81d4791546719e1b603d58213f2b/src/group.cpp#L72)):*
> ```cpp
> }
> 
> static const int MAX_GROUP_TITLE_LENGHT = 128;
> ```

`LENGHT` -> `LENGTH`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/group.cpp, line 72 at r12](https://reviewable.io:443/reviews/qtox/qtox/4560#-Kqr4kUzXIJNF7dF5O9x:-KqrHjVc-3t5iEoyGt9W:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e13b4acf9d1c81d4791546719e1b603d58213f2b/src/group.cpp#L72)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`LENGHT` -> `LENGTH`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 5 of 5 files at r15, 4 of 4 files at r16, 4 of 4 files at r17.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560#-:-KqrIOnOQ1IYYAZ2sZMS:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 11 of 11 files at r18, 2 of 2 files at r19, 4 of 4 files at r20, 3 of 3 files at r21, 4 of 4 files at r22, 3 of 3 files at r23, 4 of 4 files at r24, 4 of 4 files at r25.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4560#-:-KqszdlQpGmDR2tWwPny:b-jbsf8z)*

**Pull request merged**
