### PR TITLE
docs: move `Reviews` section – MAINTAINING.md → CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3793)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[MAINTAINING.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2yQe0aD_vKxbBAnpw:-KU2yQe0aD_vKxbBAnpx:brhfpkx) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L57)):_

> ``` Markdown
> - **always** GPG-sign PR that you're merging.
> 
>   Commits that are about to be merged don't have to be signed, but merge-commit
> ```

merge-commits ?

---

_[MAINTAINING.md, line 58 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2yTH793gg8NoyuiAR:-KU2yTH793gg8NoyuiAS:b-lcuo6d) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L58)):_

> ``` Markdown
> 
>   Commits that are about to be merged don't have to be signed, but merge-commit
>   **must** be signed. To simplify process, and ensure that things are done
> ```

`the process`

---

_[MAINTAINING.md, line 59 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2y_-NhLGfsDi7DyKZ:-KU2y_-O--YGOzKoCivh:b-j1fwul) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L59)):_

> ``` Markdown
>   Commits that are about to be merged don't have to be signed, but merge-commit
>   **must** be signed. To simplify process, and ensure that things are done
>   "right", it's preferable to use [`merge-pr.sh`] script, which does that for
> ```

use the [`merge-pr.sh`] script ?

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU2ys-mPm87DVlmi-en:b-9ubm41) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_

> ``` Markdown
>  [**User Manual**](/doc/user_manual_en.md) **|**
>  [**Install**](/INSTALL.md) **|**
>  [**Contribute**](https://github.com/qTox/qTox/wiki#contributing) **|**
> ```

why not link to `CONTRIBUTE.md` here instead of removing it entirely?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[MAINTAINING.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2yQe0aD_vKxbBAnpw:-KU38yR4ebVBb5XtbIym:bswl6v5) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L57)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> merge-commits ?
> </details>
> Nope? There's only a single merge commit for all commits from the PR that is being merged.

---

_[MAINTAINING.md, line 58 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2yTH793gg8NoyuiAR:-KU39_HQpPG79T5pvZpb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L58)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> `the process`
> </details>
> Done.

---

_[MAINTAINING.md, line 59 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2y_-NhLGfsDi7DyKZ:-KU39fKv2ZfdLjRGwCmL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L59)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> use the [`merge-pr.sh`] script ?
> </details>
> Done.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU39kct7YqWudupBkhv:b-bktwa4) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> why not link to `CONTRIBUTE.md` here instead of removing it entirely?
> </details>
> `Contribute` doesn't seem to sounds as catchy, nor does it produce equally "good" emotional response as `Help us`.

Someone who is willing to help qTox will at least look at the points listed below `Help us`, and one of them is redundant with `Contribute` in the header, thus there's no need to keep it in both places.

Someone who's not interested in helping qTox won't be fazed by `Contributing` in the header, but perhaps they could respond to the call for help. Regardless of whether someone would end up helping qTox, there's no point in keeping redundant `Contributing` in the header, since someone who is already or could become interested in helping will look at the list below `Help us`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by sudden6** [comment]
_[MAINTAINING.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2yQe0aD_vKxbBAnpw:-KU3PTmibUX8L462wzmP:bn4jz9e) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L57)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Nope? There's only a single merge commit for all commits from the PR that is being merged.
> </details>
> now I understand what you mean, then it should be "but the merge-commit"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by sudden6** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU3Q6ucabsJvUX1giVt:b-6t3zhb) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `Contribute` doesn't seem to sounds as catchy, nor does it produce equally "good" emotional response as `Help us`.
> 
> Someone who is willing to help qTox will at least look at the points listed below `Help us`, and one of them is redundant with `Contribute` in the header, thus there's no need to keep it in both places.
> 
> Someone who's not interested in helping qTox won't be fazed by `Contributing` in the header, but perhaps they could respond to the call for help. Regardless of whether someone would end up helping qTox, there's no point in keeping redundant `Contributing` in the header, since someone who is already or could become interested in helping will look at the list below `Help us`.
> 
> </details>
> I agree on not naming it Contributing, but I think it still is a good idea to put "Help us" in the header, since that's one of the first things people look at and AFAIK the first and last part of something stays in the mind.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[MAINTAINING.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2yQe0aD_vKxbBAnpw:-KU3bC7aANIRGung3RfJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/797c36a3d77be1927f5676c5347e6a8ac09b65a9/MAINTAINING.md#L57)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> now I understand what you mean, then it should be "but the merge-commit"
> </details>
> Done.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU3bIRqlhOJs64pC_Ox:bwktpf) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_

> (…) but I think it still is a good idea to put "Help us" in the header, since that's one of the first things people look at and AFAIK the first and last part of something stays in the mind.

"Help me, I'm trapped in this alpha software" ~~Lee

↑ stays in mind ;-)

On a more serious note though, people don't look at what's in the header. But yeah, they look at the first and the last (usually) thing in the header, which is why the first item in the header is `User manual`, and the last is IRC channel :-)

What `Help us` in header could do, is link to `Help us` just below downloads, which is clearly visible to anyone who has scrolled even a little bit down in README.md.
I don't really see much point in putting a link in a place that almost no one looks at when the thing link will be pointing to is clearly visible to anyone who's interested in downloading qTox. Which is almost everyone.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU3n4y6ZJrDstNXumYm:b-6kcxe1) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> > (…) but I think it still is a good idea to put "Help us" in the header, since that's one of the first things people look at and AFAIK the first and last part of something stays in the mind.
> 
> "Help me, I'm trapped in this alpha software" ~~Lee
> 
> ↑ stays in mind ;-)
> 
> On a more serious note though, people don't look at what's in the header. But yeah, they look at the first and the last (usually) thing in the header, which is why the first item in the header is `User manual`, and the last is IRC channel :-)
> 
> What `Help us` in header could do, is link to `Help us` just below downloads, which is clearly visible to anyone who has scrolled even a little bit down in README.md.
> I don't really see much point in putting a link in a place that almost no one looks at when the thing link will be pointing to is clearly visible to anyone who's interested in downloading qTox. Which is almost everyone.
> 
> </details>
> For me these headers are a quite important part when trying to evaluate a project on GH. Linking to the section below is a good idea I think.

If you want to reduce the number of entries in the header, maybe remove "Keyboard Shortcuts" or "Jenkins Builds"? Both don't look very important to me.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU3sHLmRjpo7YTep7nl:bm3f1hb) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> For me these headers are a quite important part when trying to evaluate a project on GH. Linking to the section below is a good idea I think.
> 
> If you want to reduce the number of entries in the header, maybe remove "Keyboard Shortcuts" or "Jenkins Builds"? Both don't look very important to me.
> </details>
> I agree that keyboard shortcuts and jenkins don't belong in the header. Keyboard shortcuts should go in the user manual and jenkins should go in Contributing/Help us.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU3yMpNyEn8sdHfJzKU:b8iky06) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> I agree that keyboard shortcuts and jenkins don't belong in the header. Keyboard shortcuts should go in the user manual and jenkins should go in Contributing/Help us.
> </details>
> Oh, right, keyboard shortcuts are also redundant, thanks, removed.

About the "Jenkins Builds" – they are important for some users, so removing it altogether doesn't seem like an option. Perhaps in the future (one can hope).

@AliceGrey jenkins builds don't have anything to do with contributing / helping, so why..?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
@zetok That's my bad I don't know what I was thinking about Jenkins builds.
I say just leave them where they are.

**Comment by AliceGrey** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU600lr-3kLUh9QRYkQ:bcwfqsn) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Oh, right, keyboard shortcuts are also redundant, thanks, removed.
> 
> About the "Jenkins Builds" – they are important for some users, so removing it altogether doesn't seem like an option. Perhaps in the future (one can hope).
> 
> @AliceGrey jenkins builds don't have anything to do with contributing / helping, so why..?
> </details>
> @zetok Ignore what I said about Jenkins, I don't know what I was thinking.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU60HMOAL9JmWaJvbo9:bg7igkv) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> @zetok Ignore what I said about Jenkins, I don't know what I was thinking.
> </details>
> :lgtm: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Reviewed 1 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by sudden6** [comment]
_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU8ppSbqqjhSWKkOfse:biirfpa) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> :lgtm: 
> </details>
> So no "Help us" in header? :(

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU8qizJxod8A_LOEp9s:b43wgib) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> So no "Help us" in header? :(
> </details>
> What would the reason to keep it?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU9DIGsaKcmEFP8Bmqf:b6vj4hn) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> What would the reason to keep it?
> </details>
> To encourage people to bugtest, contribute code, etc...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KU9G086Ps6B9FrjtKLP:buqsq9k) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> To encourage people to bugtest, contribute code, etc...
> </details>
> Right, but what difference does it make when same, bigger text is shown half the page down, in a place that people are more likely to look at than contents of header? And the link in the header would only point to that bigger text..

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by sudden6** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUOWt0Np_80HeqZpFgU:b-62exlv) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Right, but what difference does it make when same, bigger text is shown half the page down, in a place that people are more likely to look at than contents of header? And the link in the header would only point to that bigger text..
> </details>
> Because the Header draws very much attention on the beginning and it's then very easy to overlook the sections in the wall of text.

Why not keep it in the header and in the text? We have enough space there and it won't hurt anyone.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUOjTXdZ3s1wkMAU0P2:bpktf7n) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_

> We have enough space there and it won't hurt anyone.

Actually we don't really have enough of space there. Using up the header space causes "wall of text", which as you've pointed out causes people to overlook information.

Perfect amount of "items" in header would be 2. 3 is already pushing it, and any more than means that lots of people will simply fail to notice the info.

Realistically, we won't get even close to 3, but since we can remove redundant info that is visible anyway, there's no reason to keep it in the header.

> Because the Header draws very much attention on the beginning and it's then very easy to overlook the sections in the wall of text.

Lets not waste the attention it gets :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by Diadlo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUTN3yfPUZ142Qzs1qv:ba2b60c) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_

> Perfect amount of "items" in header would be 2

IMO? Or you have any proof?
Absolutely disagree. Do you ever seen book with ~10 parts and only 2 in book content/header (IDK, what is correct english word to describe it)?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUTPY5TIp3rz1cLKSNY:b-136yp3) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_

> IMO? Or you have any proof?

Average amount of items that one can hold in their short-term memory is 7. With that in mind, deviations from average go both sides, up and down. And design should be aimed at the lower number so that everyone could use it, otherwise you get something like Haskell.

So, with lower number by e.g. 30% you get memory capacity to be ~4.9, so that's basically 5. Still plenty of space, right?

Not really, someone is already holding something in their memory (e.g. "must get qTox"), that's one item, and their cognitive abilities might be temporarily reduced due to external factors (some distraction in the background, whatever), and that can take oh-so-precious memory space. Even if distraction would take only a little bit of space (1 item, very unlikely IMO), you're down to 3 "free" memory "slots".

So you're already pushing it with 3 items in the header in a slightly bad scenario. Not even the worst-case one.

Not a proof per se, just logic. Aside from the number 7, that's a hard scientific data.

> Absolutely disagree. Do you ever seen book with ~10 parts and only 2 in book content/header (IDK, what is correct english word to describe it)?

You mean index?

Well, good thing that it's not a book, since no one reads those ;)

If you are _one of those people_ who do read books, I would recommend http://hpmor.com/ , it's awesome.
http://hpmor.ru/ ← translation, I gotta read it one day :P

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUuPWjv_sbnAJ9J8Q1P:b3g4iep) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> > IMO? Or you have any proof?
> 
> Average amount of items that one can hold in their short-term memory is 7. With that in mind, deviations from average go both sides, up and down. And design should be aimed at the lower number so that everyone could use it, otherwise you get something like Haskell.
> 
> So, with lower number by e.g. 30% you get memory capacity to be ~4.9, so that's basically 5. Still plenty of space, right?
> 
> Not really, someone is already holding something in their memory (e.g. "must get qTox"), that's one item, and their cognitive abilities might be temporarily reduced due to external factors (some distraction in the background, whatever), and that can take oh-so-precious memory space. Even if distraction would take only a little bit of space (1 item, very unlikely IMO), you're down to 3 "free" memory "slots".
> 
> So you're already pushing it with 3 items in the header in a slightly bad scenario. Not even the worst-case one.
> 
> Not a proof per se, just logic. Aside from the number 7, that's a hard scientific data.
> 
> > Absolutely disagree. Do you ever seen book with ~10 parts and only 2 in book content/header (IDK, what is correct english word to describe it)?
> 
> You mean index?
> 
> Well, good thing that it's not a book, since no one reads those ;)
> 
> If you are _one of those people_ who do read books, I would recommend http://hpmor.com/ , it's awesome.
> http://hpmor.ru/ ← translation, I gotta read it one day :P
> </details>
> I think we should rethink our ReadMe. You both have brought up good point @zetok and @diadlo. If you look at some of the most active github projects like https://github.com/yarnpkg/yarn which has a very minimal ReadMe with no header but the ReadMe is short enought and so simple and to the point that it works. I feel we could condense our ReadMe to fit the same style. This is out of the scope of this PR but something we should consider. 

For this PR I think we should have the link in the header. It's something a lot of github users look for when they are looking at projects to contribute to.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUuShLz8HH2dEhUyADy:b-966zhm) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> I think we should rethink our ReadMe. You both have brought up good point @zetok and @diadlo. If you look at some of the most active github projects like https://github.com/yarnpkg/yarn which has a very minimal ReadMe with no header but the ReadMe is short enought and so simple and to the point that it works. I feel we could condense our ReadMe to fit the same style. This is out of the scope of this PR but something we should consider. 
> 
> For this PR I think we should have the link in the header. It's something a lot of github users look for when they are looking at projects to contribute to.
> </details>
> Other good examples: https://github.com/redox-os/redox and https://github.com/vuejs/vue

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by zetok** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUuqkBbIwpIHdKbWQDZ:bx8qu6s) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> Other good examples: https://github.com/redox-os/redox and https://github.com/vuejs/vue
> </details>
> Added `Help us`.

I still think that it's not necessary to have it in header though.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/3793#-KU2ys-lFCND5DNUGjlP:-KUzvEaSpjQTSUagcTwA:bb6ywmx) ([raw file](https://github.com/qtox/qtox/blob/14d3f13722d042ddecbded0973e9a84dc7e495fe/README.md#L6)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> Added `Help us`.
> 
> I still think that it's not necessary to have it in header though.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)*

**Comment by AliceGrey** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793)_

**Comment by AliceGrey** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3793#-:-KUzvYIV56Wo0It6Rc5b:bnfp4nl)_

**Pull request merged**
