### PR TITLE
Refactor call

### PR DESCRIPTION
**Pull request by sudden6**
This mainly makes Toxcall a full class and changes it's usage slightly.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4770)

### CODE REVIEW

**Comment by noavarice** [comment]
Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, 2 of 3 files at r6, 19 of 19 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[src/core/coreav.cpp, line 108 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzVYfQoKGtQSALMf5:-KxWzVYgTqw83yYZ2_u2:b-anshkx) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L108)):*
> ```cpp
> CoreAV::~CoreAV()
> {
>     for (const auto& call : calls)
> ```

Missing braces

---

*[src/core/coreav.cpp, line 339 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzwnlNvQJRdlISywT:-KxWzwnlNvQJRdlISywU:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L339)):*
> ```cpp
>                            uint32_t rate)
> {
>     if (calls.find(callId) == calls.end())
> ```

Same as before

---

*[src/core/coreav.cpp, line 371 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzytA0Bwal03a6fpq:-KxWzytA0Bwal03a6fpr:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L371)):*
> ```cpp
>     // We might be running in the FFmpeg thread and holding the CameraSource lock
>     // So be careful not to deadlock with anything while toxav locks in toxav_video_send_frame
>     if (calls.find(callId) == calls.end())
> ```

Same as before

---

*[src/core/coreav.cpp, line 572 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-QazVWZ8TjeRnlhM:-KxX-QazVWZ8TjeRnlhN:b-42zt93) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L572)):*
> ```cpp
> bool CoreAV::isGroupCallInputMuted(const Group* g) const
> {
>     return g && (groupCalls.find(g->getId()) != groupCalls.end()) ? groupCalls[g->getId()].muteMic : false;
> ```

You can replace ternary with `&& groupCalls[g->getId()].muteMic`. Also consider extracting `g->getId()` into const to not call this twice

---

*[src/core/coreav.cpp, line 582 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-pBe3Rn_GaHuFY9I:-KxX-pBe3Rn_GaHuFY9J:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L582)):*
> ```cpp
> bool CoreAV::isGroupCallOutputMuted(const Group* g) const
> {
>     return g && (groupCalls.find(g->getId()) != groupCalls.end()) ? groupCalls[g->getId()].muteVol : false;
> ```

Same as before

---

*[src/core/coreav.cpp, line 615 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-sJGKGm4Mt48kjQC:-KxX-sJGKGm4Mt48kjQD:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L615)):*
> ```cpp
> bool CoreAV::isCallInputMuted(const Friend* f) const
> {
>     return f && (calls.find(f->getId()) != calls.end()) ? calls[f->getId()].muteMic : false;
> ```

Same as before

---

*[src/core/coreav.cpp, line 625 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-yGJUE-WrgJGEHIJ:-KxX-yGJUE-WrgJGEHIK:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L625)):*
> ```cpp
> bool CoreAV::isCallOutputMuted(const Friend* f) const
> {
>     return f && (calls.find(f->getId()) != calls.end()) ? calls[f->getId()].muteVol : false;
> ```

Same as before

---

*[src/core/coreav.cpp, line 787 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0I8iiYkfoVLp2hI8:-KxX0I8iiYkfoVLp2hI9:brb8op1) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L787)):*
> ```cpp
> {
>     CoreAV* self = static_cast<CoreAV*>(vSelf);
>     if (self->calls.find(friendNum) == self->calls.end())
> ```

Braces

---

*[src/core/coreav.cpp, line 806 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0KCjNo3I2LbOwV4y:-KxX0KCkYkavbyu7iU91:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L806)):*
> ```cpp
>                                 int32_t ystride, int32_t ustride, int32_t vstride, void*)
> {
>     if (calls.find(friendNum) == calls.end())
> ```

Same as before

---

*[src/core/coreav.cpp, line 201 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX4_JPRLOkVxWCNPQt:-KxX4_JPRLOkVxWCNPQu:bz8ewob) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L201)):*
> ```cpp
> bool CoreAV::isCallActive(const Friend* f) const
> {
>     return isCallStarted(f) ? calls[f->getId()].isActive() : false;
> ```

Replace with `&& calls[f->getId().isActive()`

---

*[src/core/coreav.cpp, line 211 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX4l9QouR65UwQCzQD:-KxX4l9QouR65UwQCzQE:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L211)):*
> ```cpp
> bool CoreAV::isCallActive(const Group* g) const
> {
>     return isCallStarted(g) ? groupCalls[g->getId()].isActive() : false;
> ```

Same as before

---

*[src/core/coreav.cpp, line 216 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX4mVs1RV9wLZBOtwg:-KxX4mVs1RV9wLZBOtwh:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L216)):*
> ```cpp
> bool CoreAV::isCallVideoEnabled(const Friend* f) const
> {
>     return isCallStarted(f) ? calls[f->getId()].getVideoEnabled() : false;
> ```

Same as before

---

*[src/core/coreav.cpp, line 278 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX55UO_N9uP_IDo6Jo:-KxX55UO_N9uP_IDo6Jp:b-rn1nxk) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L278)):*
> ```cpp
>         return false;
> 
>     calls.insert(std::make_pair(friendNum, ToxFriendCall(friendNum, video, *this)));
> ```

What is the point of this change?

---

*[src/core/coreav.h, line 121 at r2](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0mz-1akankrOgD-Q:-KxX0mz-1akankrOgD-R:b9h0jum) ([raw file](https://github.com/qtox/qtox/blob/52b7b70b0c40cd09b5bcaffed34b62ffcc945b8c/src/core/coreav.h#L121)):*
> ```objc
>     std::unique_ptr<QTimer> iterateTimer;
>     static std::map<uint32_t, ToxFriendCall> calls;
>     static std::map<uint32_t, ToxGroupCall> groupCalls;
> ```

Why did you change type to `int`?

---

*[src/core/toxcall.cpp, line 57 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX685LM3Y6N8mE_Lbm:-KxX685LM3Y6N8mE_Lbn:b-5ijg72) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/toxcall.cpp#L57)):*
> ```cpp
> 
>     // only free resources if they weren't moved
>     if(valid) {
> ```

Add space

---

*[src/core/toxcall.cpp, line 130 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX6BjwD7VTg5xBg1h6:-KxX6BjwD7VTg5xBg1h7:bcdu1gp) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/toxcall.cpp#L130)):*
> ```cpp
> }
> 
> bool ToxFriendCall::getVideoEnabled() const
> ```

Why not `videoEnabled` or smth like this?

---

*[src/core/toxcall.cpp, line 140 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX6LSK83ifUOXWxKIx:-KxX6LSK83ifUOXWxKIy:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/toxcall.cpp#L140)):*
> ```cpp
> }
> 
> bool ToxFriendCall::getNullVideoBitrate() const
> ```

Same as before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4770)*

**Comment by Diadlo** [comment]
Reviewed 2 of 3 files at r1, 2 of 19 files at r7, 26 of 28 files at r9, 1 of 3 files at r13.
Review status: 1 of 26 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/core/coreav.cpp, line 339 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzwnlNvQJRdlISywT:-KxXdxQUmthSFUaw5nYF:b5o8ewi) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L339)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Probably, because std::map hasn't `contains` method

---

*[src/core/coreav.h, line 121 at r2](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0mz-1akankrOgD-Q:-KxXp-m8dnCAQoKOFRlU:boq1zgi) ([raw file](https://github.com/qtox/qtox/blob/52b7b70b0c40cd09b5bcaffed34b62ffcc945b8c/src/core/coreav.h#L121)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why did you change type to `int`?
</blockquote></details>

Because toxcore use `uint32_t` for friendId

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4770)*

**Comment by Diadlo** [comment]
Exclude noavarice comments :lgtm_strong:

---

Review status: 1 of 26 files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4770#-:-KxXrtKnJBVNg0HFKCnm:b-k1w6pf)*

**Comment by sudden6** [comment]
Review status: 0 of 26 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/core/coreav.cpp, line 108 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzVYfQoKGtQSALMf5:-KxXjxRYQxRQpSril_M5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L108)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Missing braces
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 339 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzwnlNvQJRdlISywT:-KxXkTWy1gR1faQNqd_A:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L339)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 371 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxWzytA0Bwal03a6fpq:-KxXkx8Nc-CUuSauSJOC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L371)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 572 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-QazVWZ8TjeRnlhM:-KxXm2p-6n2-ZjQorPyC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L572)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

You can replace ternary with `&& groupCalls[g->getId()].muteMic`. Also consider extracting `g->getId()` into const to not call this twice
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 582 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-pBe3Rn_GaHuFY9I:-KxXm3TnEUlrTjLkHAMU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L582)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 615 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-sJGKGm4Mt48kjQC:-KxXmSZ2LjoHLQ6ZWIaN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L615)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 625 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-yGJUE-WrgJGEHIJ:-KxXmaZBUkVYN8z9RVxr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L625)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 787 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0I8iiYkfoVLp2hI8:-KxXmoQweeYlqX8pdqGJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L787)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Braces
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 806 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0KCjNo3I2LbOwV4y:-KxXnE7hKiAr2fKYgZhD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L806)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 201 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX4_JPRLOkVxWCNPQt:-KxXk5yjDh9N2dlZLYIv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L201)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Replace with `&& calls[f->getId().isActive()`
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 211 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX4l9QouR65UwQCzQD:-KxXk6_wYxVwAYPc9OzR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L211)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 216 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX4mVs1RV9wLZBOtwg:-KxXkHKiLCXFfng-76cC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L216)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 278 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX55UO_N9uP_IDo6Jo:-KxXM8S0wawAM1FpP6n-:b6xotec) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/coreav.cpp#L278)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

What is the point of this change?
</blockquote></details>

`calls` was an `IndexedList` before, which was some strange custom datatype. I replaced it with `std::map` which needs a different initialization.

---

*[src/core/toxcall.cpp, line 57 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX685LM3Y6N8mE_Lbm:-Kxcb4ktQ9Lvn84DCZAq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/toxcall.cpp#L57)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Add space
</blockquote></details>

Done.

---

*[src/core/toxcall.cpp, line 130 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX6BjwD7VTg5xBg1h6:-KxXMyhcnw-pgZBay5BU:b8w22m6) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/toxcall.cpp#L130)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why not `videoEnabled` or smth like this?
</blockquote></details>

That's what qt-creator automatically generates for getters/setters^^ If I name the function `videoEnabled()` it clashes with the member variable... I'm not sure, do we have a common style for this case?

---

*[src/core/toxcall.cpp, line 140 at r8](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX6LSK83ifUOXWxKIx:-KxXuoaw2RUVg_CECNfL:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/ea9689e066b74915a89e4feb54c546c7ca7017cd/src/core/toxcall.cpp#L140)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

same

---

*[src/core/coreav.h, line 121 at r2](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX0mz-1akankrOgD-Q:-KxXMdTDJXqPWzIax8rY:b-mkaqmh) ([raw file](https://github.com/qtox/qtox/blob/52b7b70b0c40cd09b5bcaffed34b62ffcc945b8c/src/core/coreav.h#L121)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why did you change type to `int`?
</blockquote></details>

Because for some strange reason toxcore uses `int` for groupIds, see https://github.com/TokTok/c-toxcore/issues/606

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4770)*

**Comment by noavarice** [comment]
Reviewed 2 of 19 files at r7, 26 of 28 files at r9.
Review status: 0 of 26 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/core/coreav.cpp, line 572 at r1](https://reviewable.io:443/reviews/qtox/qtox/4770#-KxX-QazVWZ8TjeRnlhM:-KxiHQT-6r0kE0PmEiOd:brwagww) ([raw file](https://github.com/qtox/qtox/blob/4d911f50da5ecc0865ab1aab09a7ec4a1dd54cb4/src/core/coreav.cpp#L572)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, for some reason I do not see any changes, here and any other places

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4770)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 2 of 19 files at r7, 6 of 7 files at r10, 19 of 19 files at r12, 3 of 3 files at r14.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4770#-:-KxiLyw_ESA5E8YQVM50:b-jbsf8z)*

**Pull request merged**
