### PR TITLE
filter_audio (rebased)

### PR DESCRIPTION
**Pull request by ghost**
Added some `#ifdef QTOX_FILTER_AUDIO`s.
Conflicts:
- qtox.pro
- src/coreav.cpp

### CODE REVIEW

**Comment by ghost** [comment]
Here you have one conflict-free rebased, squashed commit.

**Comment by apprb** [comment]
Is there a particular reason to compile irungentoo's filter_audio code as standalone library? 
Probably using `git submodule` is more suitable for this purpose.

**Comment by ghost** [comment]
I don't know how to use `git submodule`.

**Comment by dubslow** [comment]
It's also true that jenkins.libtoxcore.so doesn't use git (at least currently).

**Comment by zetok** [comment]
@apprb isn't that a standalone library though?

**Comment by ghost** [comment]
@apprb I read a little about `git submodule`s. I come to the conclusion that using `git submodule` would be IMHO **inconsistent**, because we also have no _submodule_ for `libtoxcore`. We also have to install `libtoxcore.so` on UNIXes. IMO, treating `filter_audio` as a separate library is here good.
Furthermore, adding the C-sources and C-headers to `qtox.pro` can cause some problems, because `filter_audio` is written in C and qTox is written in  C++. There are some differences between C and C++, so it is IMO correct to separate them using shared objects (`so`s on UNIXes and `dll`s on Windows'es).

**Comment by dubslow** [comment]
@mwuttke97 is there a particular reason for the `unix|win32` in `unix|win32: LIBS += -lfilteraudio` ?

**Pull request merged**
