### PR TITLE
fix: simple_make.sh script

### PR DESCRIPTION
**Pull request by tox-user**
- fix crash when run without parameters
- use cmake instad of automake for building toxcore

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5192)

### CODE REVIEW

**Comment by tox-user** [comment]
I removed the condition that checked for av support in bootstrap.sh. If qTox fails to build without it anyway, it should be ok to remove it.

**Comment by tox-user** [comment]
I've noticed in https://github.com/qTox/qTox/pull/5186 that we still list automake and autoconf as dependencies.

**Comment by sudden6** [comment]
:lgtm_strong: tested successfully

yep, I think we need to clean that file up a bit.

---

Reviewed 2 of 2 files at r1.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5192#-:-LFuoBtgCP8l2KwAcf8a:bsahckw)*

**Comment by sudden6** [comment]
went ahead and merged this one to publish the fix quickly.

**Comment by tox-user** [comment]
Good decision!

**Comment by ghost** [comment]
This commit seems to cause "./bootstrap.sh --local" to fail. See issue https://github.com/qTox/qTox/issues/5199

**Pull request merged**
