### PR TITLE
Update user manual a bit

### PR DESCRIPTION
**Pull request by zetok**
I've made separate commits for stuff to ease review. If it's not needed, or something, I can squash.
Style commit can be yanked if the change is not desired.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3718)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[doc/user_manual_en.md, line 128 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdY7JpCiW3pQcz489g:-KRdY7JpCiW3pQcz489h:bnhyxt9) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L128)):_

> ``` Markdown
> * __Show system tray icon:__ If set, qTox will show its icon in your system
>   tray.
>     * __Start in tray:__ On start, qTox will only show its tray icon and no
> ```

Maybe add `#### Tray` ?

---

_[doc/user_manual_en.md, line 267 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdYVNMueev6hfdxm_B:-KRdYVNMueev6hfdxm_C:b-u8ep1a) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L267)):_

> ``` Markdown
> 
> * __Reset to default settings:__ Use this button to revert any changes you made to
>   the qTox settings.
> ```

Should we write, that it also remove friends alias?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[doc/user_manual_en.md, line 128 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdY7JpCiW3pQcz489g:-KRd_H8TIuq7X9Sn-76d:b-e98830) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L128)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Maybe add `#### Tray` ?
> </details>
> There's no `Tray` "section" in the `General` tab though..?

---

_[doc/user_manual_en.md, line 267 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdYVNMueev6hfdxm_B:-KRdZWZLP2T4H7pAZXSJ:bj0a6ie) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L267)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Should we write, that it also remove friends alias?
> </details>
> We can write that current implementation is buggy and would remove aliases if settings were to be reset.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

_[doc/user_manual_en.md, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeA_0R8Jfcvdt9T8u:-KRdeA_0R8Jfcvdt9T8v:b-mquy5g) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L37)):_

> ``` Markdown
> 
> Can be accessed by right-clicking on a contact or [circle](#circles). When
> right-clicking on a contact appears menu has the following options:
> ```

... contact a menu appears that has ...

---

_[doc/user_manual_en.md, line 41 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeTlIs5fWC2E9uwDi:-KRdeTlJPTMroPViQHoE:b-cgbhz5) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L41)):_

> ``` Markdown
> * __Open chat in a new window:__ opens a new window for the chosen contact.
> * __Invite to group:__ offers an option to create a new groupchat and
>   automatically invite the contact to it, or to invite friend to an already
> ```

invite the friend

---

_[doc/user_manual_en.md, line 43 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeZ0kzK3Kb_a-lKkb:-KRdeZ0kzK3Kb_a-lKkc:b70078n) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L43)):_

> ``` Markdown
>   automatically invite the contact to it, or to invite friend to an already
>   existing groupchat.
> * __Move to circle:__ offers an option to move contact to a new
> ```

move the contact

---

_[doc/user_manual_en.md, line 47 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdefC6bhjYqDxdmF3U:-KRdefC6bhjYqDxdmF3V:b7pv1lw) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L47)):_

> ``` Markdown
> * __Set alias:__ set alias that will be displayed instead of contact's name.
> * __Auto accept files from this friend:__ option to automatically save files
>   from given contact in a chosen directory.
> ```

from the selected contact?

---

_[doc/user_manual_en.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeqdzXnX5FQWPiq9-:-KRdeqdzXnX5FQWPiq90:b-45jqzq) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L48)):_

> ``` Markdown
> * __Auto accept files from this friend:__ option to automatically save files
>   from given contact in a chosen directory.
> * __Remove friend:__ option to remove contact. Confirmation is needed to remove
> ```

remove the contact

---

_[doc/user_manual_en.md, line 54 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdey2K1O7Vo_BfZ1Z_:-KRdey2L5YYwWaOElcQH:b-rzcodq) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L54)):_

> ``` Markdown
> #### Circles
> 
> Circles allow to group contacts together and give the circle a name. Contact
> ```

Circles allow you to group contacts together and give this circle a name. Contacts can be in one or no circle.

---

_[doc/user_manual_en.md, line 152 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdfTjLa5FwLBrgm7Zn:-KRdfTjLa5FwLBrgm7Zo:b-lsn9cc) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L152)):_

> ``` Markdown
> #### Chat
> 
> * __Base font:__ You can set a non-default font and its size for the chat. New
> ```

The new font setting will be used for new messages and all messages after qTox has been restarted.

---

_[doc/user_manual_en.md, line 193 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdfi9NEPS-8EtxgZH5:-KRdfi9NEPS-8EtxgZH6:b-o6mr4x) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L193)):_

> ``` Markdown
> * __Style:__ Changes the appearance of qTox.
> * __Theme color:__ Changes the colors qTox uses.
> * __Timestamp format:__ Change the format in which qTox displays message
> ```

Change -> Changes

---

_[doc/user_manual_en.md, line 267 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdYVNMueev6hfdxm_B:-KRdgFJkvK5sPvEOYasj:b-7b49xx) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L267)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> We can write that current implementation is buggy and would remove aliases if settings were to be reset.
> </details>
> IMHO it's desirable to also remove the aliases, what if the they somehow break qTox?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 10 unresolved discussions.

---

_[doc/user_manual_en.md, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeA_0R8Jfcvdt9T8u:-KRdkWxsxGmgvOqaGRFH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L37)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> ... contact a menu appears that has ...
> </details>
> Done.

---

_[doc/user_manual_en.md, line 41 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeTlIs5fWC2E9uwDi:-KRdkdVHZoMXQULjAdoV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L41)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> invite the friend
> </details>
> Done.

---

_[doc/user_manual_en.md, line 43 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeZ0kzK3Kb_a-lKkb:-KRdki4ZZGj3vxnKZxYB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L43)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> move the contact
> </details>
> Done.

---

_[doc/user_manual_en.md, line 47 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdefC6bhjYqDxdmF3U:-KRdknrRVPqXnupf7gCi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L47)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> from the selected contact?
> </details>
> Done.

---

_[doc/user_manual_en.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeqdzXnX5FQWPiq9-:-KRdksnqQRtQlKblRLlh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L48)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> remove the contact
> </details>
> Done.

---

_[doc/user_manual_en.md, line 54 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdey2K1O7Vo_BfZ1Z_:-KRdl3A_XosCgppsuClZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L54)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Circles allow you to group contacts together and give this circle a name. Contacts can be in one or no circle.
> </details>
> Done.

---

_[doc/user_manual_en.md, line 152 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdfTjLa5FwLBrgm7Zn:-KRdlXrraoRmARIyilpH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L152)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> The new font setting will be used for new messages and all messages after qTox has been restarted.
> </details>
> Done.

---

_[doc/user_manual_en.md, line 193 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdfi9NEPS-8EtxgZH5:-KRdldvS1xkUw7jySVMd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L193)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Change -> Changes
> </details>
> Done.

---

_[doc/user_manual_en.md, line 267 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdYVNMueev6hfdxm_B:-KRdlfHrKDjuNrZ8LiYH:b1ot36s) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L267)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> IMHO it's desirable to also remove the aliases, what if the they somehow break qTox?
> </details>
> Aliases aren't settings, but user data. And if they could break qTox, that would also be a bug that would need to be fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[doc/user_manual_en.md, line 41 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeTlIs5fWC2E9uwDi:-KRdo0PiSTpDOiOVSAa8:bmqwwzr) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L41)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Done.
> </details>
> I think in the English language `,` isn't normally used before `or`. Also second "invite the friend".

---

_[doc/user_manual_en.md, line 152 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdfTjLa5FwLBrgm7Zn:-KRdnfh65EBtgAc5o8WC:bdvuuts) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L152)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Done.
> </details>
> I think in the English language there's normally no `,` before an `and`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[doc/user_manual_en.md, line 41 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdeTlIs5fWC2E9uwDi:-KRdqAaO6Vw8GWfrixqF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L41)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> I think in the English language `,` isn't normally used before `or`. Also second "invite the friend".
> </details>
> Done.

---

_[doc/user_manual_en.md, line 152 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdfTjLa5FwLBrgm7Zn:-KRdqSUAj4j9mw368PvW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L152)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> I think in the English language there's normally no `,` before an `and`
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[doc/user_manual_en.md, line 267 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdYVNMueev6hfdxm_B:-KRdrS6RugTpCjALuIlG:b-lj4ecd) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L267)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Aliases aren't settings, but user data. And if they could break qTox, that would also be a bug that would need to be fixed.
> </details>
> Hmm, yeah I think I can agree with that.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[doc/user_manual_en.md, line 267 at r1](https://reviewable.io:443/reviews/qtox/qtox/3718#-KRdYVNMueev6hfdxm_B:-KRebwJGfPYmCzSjA-Oe:bpnmbxg) ([raw file](https://github.com/qtox/qtox/blob/331105344df0a53599e3fca4354b5b8462887a4a/doc/user_manual_en.md#L267)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Hmm, yeah I think I can agree with that.
> </details>
> Added part about the bug.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718)_

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718#-:-KRgR-Nv4YIUqGfLOwrP:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3718#-:-KRgSvaryied1f9Gh6vX:bnfp4nl)_

**Pull request merged**
