### PR TITLE
fix(build) : correct install script nsis for win64

### LINKED ISSUE #4627: Qtox64 Windows 10 x64 Registry
##### Brief Description

OS: Windows 10 x64
qTox version: 1.11
Commit hash:  66b133c8d4a4d8f60e62475b0b56b509527b1488
toxcore:  0.1.9
Qt:  5.6.2
Hardware:  i7 6820HK, 32 GB Ram, 980M, 512 GB SSD, 2 TB HDD
…

Reproducible: Always 

##### Steps to reproduce

1. Ok, the Windows Qtox x64 uninstall information for the Windows registry (aka Control Panel) is in the wrong place.  The Uninstall Key is located in the following Registry Key for Qtox x64:

- HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\qTox

Additionally, You guys on the install side don't have a EstimateSize REG_SZ which tells the control panel how much size the program is taking up.

2. Seeing as Qtox is installed in the Program Files area for a 64 bit OS as opposed to Program Files (x86) move the Key creation to the following location:

- HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\qTox

### PR DESCRIPTION
**Pull request by PKEv**
fix #4627
https://stackoverflow.com/questions/11150238/writing-registry-value-in-a-64-bit-system

need test!

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5103)

### CODE REVIEW

**Comment by sudden6** [comment]
the space between `build)` and `:` prevents passing our CI

**Comment by sudden6** [comment]
Not tested, but the change :lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5103#-:-LCe3BuJBQczoO847D-B:b-e4lfrb)*

**Comment by Diadlo** [comment]
Lol)

-- need test!
-- Not tested
\<Merge\>

**Comment by sudden6** [comment]
It was open for ~1 month, nobody is going to test it until we release it :P

**Comment by tox-user** [comment]
It's probably the main reason why we add so many bugs with each release :).

**Comment by sudden6** [comment]
So @Diadlo @tox-user do you suggest to revert it?

**Comment by Diadlo** [comment]
@sudden6 No. It just was funny. If we haven't an ability to test it without a release, we can hold it very long time without merge

**Comment by tox-user** [comment]
No need to revert it.

**Pull request merged**
