### PR TITLE
fix(instructions): Improved the FreeBSD instructions.

### PR DESCRIPTION
**Pull request by yurivict**
Recommending in this order:
1. The binary package
2. The port

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4482)

### CODE REVIEW

**Comment by Diadlo** [comment]
Commit scope should be less than 12 characters. Or you can not specify it at all

**Comment by yurivict** [comment]
Made it exactly 12 chars.

**Comment by zetok** [comment]
>fix(instructions): Improved the FreeBSD instructions. 

It should be `docs: Improve FreeBSD install instructions`, could you change it?

Aside from that, :lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4482#-:-KnTfn1kBtXf8UFSmAiP:bmeqml7)*

**Comment by yurivict** [comment]
changed.

**Comment by Diadlo** [comment]
@zetok Are you ok with the current one? (`fix(docs)`)
@yurivict AFAIK, fix should be used for bugs only. IMO better use @zetok example i.e. `docs:`

**Comment by yurivict** [comment]
Changed to docs.

**Pull request merged**
