### PR TITLE
feat(core): set group title for loaded groups

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5448)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5448)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.h, line 194 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpoJnD2QJDEIW1uJK1:-LSpoJnD2QJDEIW1uJK2:bc9up70) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.h#L194)):*
> ```objc
> 
>     void emptyGroupCreated(int groupnumber);
>     void groupLoaded(int groupnumber, const QString& title);
> ```

`groupLoaded` seems to be quite similar to `emptyGroupCreated`, maybe extend it and use a default parameter for `title`?
___
*[src/core/core.cpp, line 1051 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpoptZ8xh8nqV8cCrP:-LSpopt_8Dmnz-746kAb:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1051)):*
> ```cpp
>         size_t titleSize = tox_conference_get_title_size(tox.get(), groupIds[i], &error);
>         if (LogConferenceTitleError(error))
>             continue;
> ```

braces
___
*[src/core/core.cpp, line 1053 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpp43JEbi3YK7HcLQg:-LSpp43JEbi3YK7HcLQh:b-fnvefu) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1053)):*
> ```cpp
>             continue;
> 
>         std::vector<uint8_t> name(titleSize);
> ```

I think `ToxString` would be better here
___
*[src/core/core.cpp, line 1055 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSporP87CPCJgfH1Iz2:-LSporP87CPCJgfH1Iz3:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1055)):*
> ```cpp
>         std::vector<uint8_t> name(titleSize);
>         if (!tox_conference_get_title(tox.get(), groupIds[i], name.data(), &error))
>         if (LogConferenceTitleError(error))
> ```

braces
___
*[src/widget/widget.cpp, line 1923 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSppK63BATEGCBY2RnC:-LSppK63BATEGCBY2RnD:b5kuqgq) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/widget/widget.cpp#L1923)):*
> ```cpp
> }
> 
> void Widget::onGroupLoaded(int groupId, const QString& title)
> ```

same as above, possibly merge with `onEmptyGroupCreated`

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5448)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.h, line 194 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpoJnD2QJDEIW1uJK1:-LSqSZY0-4xCsyMHYo-v:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.h#L194)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`groupLoaded` seems to be quite similar to `emptyGroupCreated`, maybe extend it and use a default parameter for `title`?
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 1051 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpoptZ8xh8nqV8cCrP:-LSqS_ISBfapzgxoKgc2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1051)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 1053 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpp43JEbi3YK7HcLQg:-LSqS_eA-5zunONeeHcD:b-kijqxx) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1053)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think `ToxString` would be better here
</blockquote></details>

Done, constructed ToxString to get QString from byte array. Added constructor for std::vector<uint8_t> instead of using QByteArray with the existing constructor due to my preference of using std types when not interfacing with Qt API.
___
*[src/core/core.cpp, line 1055 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSporP87CPCJgfH1Iz2:-LSqSl3K5D5z2muTtAY9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1055)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/widget/widget.cpp, line 1923 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSppK63BATEGCBY2RnC:-LSqSngQCCq_HxqanciW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/widget/widget.cpp#L1923)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same as above, possibly merge with `onEmptyGroupCreated`
</blockquote></details>

Done.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5448)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1053 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpp43JEbi3YK7HcLQg:-LSq_e0yAq_BA4Fc5jrx:bbbqidx) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1053)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Done, constructed ToxString to get QString from byte array. Added constructor for std::vector<uint8_t> instead of using QByteArray with the existing constructor due to my preference of using std types when not interfacing with Qt API.
</blockquote></details>

I see no advantage of using the std type here, also the rest of the code in this file mostly uses `QByteArray` so IMO it's better to stick to it.
___
*[src/core/toxstring.cpp, line 56 at r2](https://reviewable.io/reviews/qtox/qtox/5448#-LSq_IkT8Rr58RJ3wfU0:-LSq_IkT8Rr58RJ3wfU1:b6y6t6g) ([raw file](https://github.com/qtox/qtox/blob/04fd60695a28c1d3d3ab6367e8ebecbe639dd9a5/src/core/toxstring.cpp#L56)):*
> ```cpp
>  * @param text Input text bytes.
>  */
> ToxString::ToxString(const std::vector<uint8_t>& text)
> ```

If you persist with adding this constructor, please also extend the tests covering this class.

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5448)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1053 at r1](https://reviewable.io/reviews/qtox/qtox/5448#-LSpp43JEbi3YK7HcLQg:-LSqtgKA9qgF4jXTfQJA:bwub2xj) ([raw file](https://github.com/qtox/qtox/blob/404cb84a100600a308eb19bdf6dc0fbbdd5e2bdc/src/core/core.cpp#L1053)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I see no advantage of using the std type here, also the rest of the code in this file mostly uses `QByteArray` so IMO it's better to stick to it.
</blockquote></details>

My logic was that std was a better default and either would function well. You pointed out (in chat) that the conversion from QByteArray -> QString is already handled and tested, plus the addition of a new constructor API adds complexity, which I agree with. Changed to QByteArray. You also made some good counters to my view of defaulting to std where possible which I'll think about some more.
___
*[src/core/core.cpp, line 455 at r3](https://reviewable.io/reviews/qtox/qtox/5448#-LSquDPy7tk8ee5wOVY3:-LSquDPz4n9MXphRh3vj:b9bx597) ([raw file](https://github.com/qtox/qtox/blob/f188409b8ce85515fc3b45a2aedb3af79af2b009/src/core/core.cpp#L455)):*
> ```cpp
>     Core* core = static_cast<Core*>(vCore);
>     // static_cast is used twice to replace using unsafe reinterpret_cast
>     const QByteArray data(static_cast<const char*>(static_cast<const void*>(cookie)), length);
> ```

I don't think this logic makes any sense. Double static cast is as unsafe in that the underlying bytes lose meaning in the new type and accomplishes the same thing. Changed here and across core.cpp where double static cast of pointers was used.
___
*[src/core/toxstring.cpp, line 56 at r2](https://reviewable.io/reviews/qtox/qtox/5448#-LSq_IkT8Rr58RJ3wfU0:-LSqtzgc6LVeDrBTrYxo:b-lhbv3a) ([raw file](https://github.com/qtox/qtox/blob/04fd60695a28c1d3d3ab6367e8ebecbe639dd9a5/src/core/toxstring.cpp#L56)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

If you persist with adding this constructor, please also extend the tests covering this class.
</blockquote></details>

Removed so no longer relevant.

**Comment by Diadlo** [comment]
@anthonybilinski I prefer not to use `reinterpret_cast` because of this:
```
$ cat static_cast.cpp
int main()
{
  unsigned char* uptr = nullptr;
  char* ptr = static_cast<char*>(static_cast<void*>(uptr));
  int i = static_cast<int>(uptr);
}
```
```
$ g++ -m32 static_cast.cpp
static_cast.cpp: In function ‘int main()’:
static_cast.cpp:5:32: error: invalid static_cast from type ‘unsigned char*’ to type ‘int’
   int i = static_cast<int>(uptr);
                                ^
```
```
$ cat reiterpret_cast.cpp 
int main()
{
  unsigned char* uptr = nullptr;
  char* ptr = reinterpret_cast<char*>(uptr);
  int i = reinterpret_cast<int>(uptr);
}
```
```
$ g++ -m32 reiterpret_cast.cpp
# No error
```

**Comment by anthonybilinski** [comment]
casting a pointer to an int is meaningless because the data in incompatible, so you get an error with static_cast (useful, good in normal cases). `reinterpret_cast` is saying to ignore if the data is incomparable and just use the data. This is exactly what we're trying to do when we double `static_cast`. The whole reason we have two is to trick the compiler into not realizing that we're converting `unsigned char` to `char` by first converting to `void*` so that it can't tell what the conversion is. If the data was compatible we would only need a single `static_cast` and that would be preferable, but doing that here causes the same warning that `unsigned char*` and `char*` have incompatible data. Either with `reinterpret_cast` or double `static_cast` we're forcing it to use the data anyway, but `reinterpret_cast` is explicitly saying that that's what we want, but double static_cast is just working around the warning.

**Comment by Diadlo** [comment]
@anthonybilinski You can't cast pointer to non-pointer with two `static_cast`

**Review by sudden6 — COMMENTED** [review]
> Reviewed 1 of 7 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5448)* status: 0 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
@Diadlo true, but the fact remains that we're _trying_ to reinterpret the data here, which is the textbook use case of `reinterpret_cast`, we're not trying to implicitly cast data between compatible types using `static_cast`. The whole reason we need two `static_cast`s in a row is because the data is not implicitly castable.

**Comment by sudden6** [comment]
@Diadlo I think @anthonybilinski is correct here, that we're trying to reinterpret data and we should express that using `reinterpret_cast`.

**Comment by anthonybilinski** [comment]
Is this pending changes, or good the way it is? It would be nice to get this in before v1.17.0.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5448#-:-LTqhBgSDr9twbvmIhTt:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
