### PR TITLE
fix(settings): Change test sound button to checkbox & save to settings

### LINKED ISSUE #3800: Test sound button should be red if disabled
##### Brief Description

OS: Any
qTox version: v1.5.2-73-g894b47a.
Commit hash: 894b47ad7794a808e63f6234bec3a3af26107b12

Reproducible: Always 
##### Steps to reproduce
1. Open AV settings tab
2. Click on green `play a test sound` button
##### Observed Behavior

Appear/disappear shadow around button
##### Expected Behavior

Changing color of button on red/green

### PR DESCRIPTION
**Pull request by AliceGrey**
Fixes #3800 & #3809 

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3808)

### CODE REVIEW

**Comment by zetok** [comment]
checkbox should be set to `on` by default

Edit: perhaps not as a part of this PR

**Comment by AliceGrey** [comment]
@zetok I didn't see the edit. I set it to on by default with an amended push. Let me know if I should change it back.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3808#-:-KTq08Un-MYKbfxKrA83:b-a0ajs6)_

**Comment by zetok** [comment]
> Let me know if I should change it back.

Well, changing back is not really needed, provided that the bug gets fixed.

I.e. with the change checkbox is now `on`, but qTox doesn't produce any sound when changing volume.

**Comment by AliceGrey** [comment]
@zetok Would it be acceptable to just define `mPlayTestSound` as `true` or is that a bit of a kludge?

**Comment by zetok** [comment]
@AliceGrey IMO that would be fine, but I'm not sure if others would agree.

I think that removing the checkbox and just having sound always play when changing volume would be the way to go, but it would be good to make a proposal with it, and if no one will state good reasons to not do that.. :)

**Comment by zetok** [comment]
Actually, nvm, having sound always play wouldn't be a good idea.

**Comment by AliceGrey** [comment]
@zetok I definitely think we should keep the option to turn it off and on.

**Comment by AliceGrey** [comment]
@zetok I think I will rework the function so that it saves mPlayTestSound as a setting and loads it. That should also fix #3809

**Comment by AliceGrey** [comment]
@zetok Ok that amended push should fix #3809 and #3800. Let me know if I should make any style or code location changes.

**Comment by zetok** [comment]
> Let me know if I should make any style or code location changes.

Style seems to look ok, dunno about the code since I don't know C++.

**Comment by sudden6** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3808)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3808#-:-KTsgZUp1AlMavnwr8QR:bnfp4nl)_

**Comment by AliceGrey** [comment]
@zetok Anything else I need to do before merge?

**Comment by zetok** [comment]
@AliceGrey no, things seem to be fine, so, it's going to be merged as soon as @Diadlo / @initramfs / @sudden6 has the time to merge it. Which is probably going to be later today or during the weekend.

Sorry about the delay, there's not enough people with enough time maintaining qTox.

What could lessen maintenance burden, is people other than just the maintainers helping out and reviewing PRs. And if some PRs are reviewed by people other than maintainers, maintainers could spend what little of their time they have on merging PRs instead of going through cycle of reviews. ;)

E.g. there are PRs to the documentation – IMO it would be better if someone who's not a maintainer reviewed them, since docs are usually aimed at people who want to get familiar with the project, and review from such person could help highlight things in PR that aren't good/clear for someone who's not a qTox maintainer.

#3793 ;)

Not sure how to encourage to reviewing PRs :s

**Comment by AliceGrey** [comment]
@zetok I'll put some time into checking out other PR's then :+1:

**Pull request merged**
