### PR TITLE
docs: correct typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by jakieoymj-github**
Deleted the branch,rename the commit,and try PR again.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5258)

### CODE REVIEW

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5258#-:-LHmDwPa6473SMGlTwUs:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by jakieoymj-github** [comment]
@sudden6 What happened? Where am I wrong?

**Comment by sudden6** [comment]
nothing, lgtm=looks good to me and this means I'll merge this PR on the next occasion.

**Comment by jakieoymj-github** [comment]
;P,I know LGTM means.I want to know why must rename PR's title as "docs: correct typo in CONTRIBUTING.md".I follow the instructions in your CONTRIBUTING.md.Why can't pass the checking step?
Thank you :).I keep learning and learning...

**Comment by sudden6** [comment]
Oh, sorry, didn't understand you correctly then^^

MAINTAINING.md says `docs` not `doc` as you wrote and maybe `MAINTAINING` was too long

**Pull request merged**
