### PR TITLE
[Refactor] Remove using Group::getGroupWidget

### PR DESCRIPTION
**Pull request by Diadlo**
Based on #4560

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4563)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/group.cpp, line 53 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwYGDfqkDbDAlX1kwM:-KqwYGDfqkDbDAlX1kwN:b-d27wdv) ([raw file](https://github.com/qtox/qtox/blob/1e90106a08a2eab90218b9e587ad7ce68ed0a4e9/src/model/group.cpp#L53)):*
> ```cpp
> {
>     delete chatForm;
>     widget->deleteLater();
> ```

Group controlled its `GroupWidget` life cycle. Since `GroupWidget` is not a part of `Group` instance anymore, should `groupWidgets` map be deleted manually through `deleteLater()` within `Widget` dtor?

---

*[src/widget/widget.cpp, line 1477 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwXGV7KlSxFAU8aUJ0:-KqwXGV7KlSxFAU8aUJ1:b-v3mui) ([raw file](https://github.com/qtox/qtox/blob/e132227185561537ba60c2cc05cddd2d2a5fdb36/src/widget/widget.cpp#L1477)):*
> ```cpp
>     Nexus::getCore()->removeFriend(f->getId(), fake);
> 
>     friendWidgets.remove(f->getId());
> ```

Replace `f->getId()` with const or make this change as single PR related to `FriendWidget`'s refactoring only

---

*[src/widget/widget.cpp, line 2138 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwWFpGFFlSafzo593G:-KqwWFpGFFlSafzo593H:b-f112ya) ([raw file](https://github.com/qtox/qtox/blob/e132227185561537ba60c2cc05cddd2d2a5fdb36/src/widget/widget.cpp#L2138)):*
> ```cpp
> 
>     for (Friend* f : FriendList::getAllFriends()) {
>         uint32_t friendId = f->getId();
> ```

`friendId` has type `uint32_t` while `friendWidgets` is a `QMap<*int*, FriendWidget>`. I think you can change it within another PR

---

*[src/widget/widget.cpp, line 2143 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwWlDFGtQZHdoQWogl:-KqwWlDFGtQZHdoQWogm:bjqz11y) ([raw file](https://github.com/qtox/qtox/blob/e132227185561537ba60c2cc05cddd2d2a5fdb36/src/widget/widget.cpp#L2143)):*
> ```cpp
> 
>     for (Group* g : GroupList::getAllGroups()) {
>         uint32_t groupId = g->getId();
> ```

Same. Change `groupWidgets` type to `QMap<uint32_t, GroupWidget>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4563)*

**Comment by Diadlo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/model/group.cpp, line 53 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwYGDfqkDbDAlX1kwM:-KrCuE0dD-FBwZGTCW0u:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1e90106a08a2eab90218b9e587ad7ce68ed0a4e9/src/model/group.cpp#L53)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Group controlled its `GroupWidget` life cycle. Since `GroupWidget` is not a part of `Group` instance anymore, should `groupWidgets` map be deleted manually through `deleteLater()` within `Widget` dtor?
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 1477 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwXGV7KlSxFAU8aUJ0:-KrCuZ6_IqSDIOnrZ2EB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e132227185561537ba60c2cc05cddd2d2a5fdb36/src/widget/widget.cpp#L1477)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Replace `f->getId()` with const or make this change as single PR related to `FriendWidget`'s refactoring only
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 2138 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwWFpGFFlSafzo593G:-KrCw7z1_w7dHtU1VR8U:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e132227185561537ba60c2cc05cddd2d2a5fdb36/src/widget/widget.cpp#L2138)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`friendId` has type `uint32_t` while `friendWidgets` is a `QMap<*int*, FriendWidget>`. I think you can change it within another PR
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 2143 at r1](https://reviewable.io:443/reviews/qtox/qtox/4563#-KqwWlDFGtQZHdoQWogl:-KrCw8CITkQj3fEL2Rkf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e132227185561537ba60c2cc05cddd2d2a5fdb36/src/widget/widget.cpp#L2143)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same. Change `groupWidgets` type to `QMap<uint32_t, GroupWidget>`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4563)*

**Comment by noavarice** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1468 at r2](https://reviewable.io:443/reviews/qtox/qtox/4563#-KrFardWZI-IRHHGdf27:-KrFardWZI-IRHHGdf28:b-4oabyb) ([raw file](https://github.com/qtox/qtox/blob/0437536b5cc0c33385ef01badc856ace8f0bdd9e/src/widget/widget.cpp#L1468)):*
> ```cpp
>     }
> 
>     FriendWidget* widget = friendWidgets[friendId];
> ```

Why would not define `friendId` right before this line?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4563)*

**Comment by sudden6** [comment]
with the thing noavarice mentioned fixed, :lgtm_strong: 

---

Reviewed 3 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4563#-:-KrGP4jTKTNaEQPPzRhF:b-n539lf)*

**Comment by Diadlo** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1468 at r2](https://reviewable.io:443/reviews/qtox/qtox/4563#-KrFardWZI-IRHHGdf27:-KrH60LzGHyAjM1Yl9Qz:b881mxo) ([raw file](https://github.com/qtox/qtox/blob/0437536b5cc0c33385ef01badc856ace8f0bdd9e/src/widget/widget.cpp#L1468)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why would not define `friendId` right before this line?
</blockquote></details>

~Because of C89~ Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4563)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4563#-:-KrHebyX39EkzdCRwlBg:b-jbsf8z)*

**Pull request merged**
