### PR TITLE
chore(INSTALL): fix formatting after github changed its markdown parser

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4282)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[INSTALL.md, line 125 at r1](https://reviewable.io:443/reviews/qtox/qtox/4282#-KfwDcZdkgZEF2pmXHMR:-KfwDcZe4EDMpnsJNOAP:baxqxwu) ([raw file](https://github.com/qtox/qtox/blob/4ec5752881d0c38f2b2d355041a4052bca964bae/INSTALL.md#L125)):*
> ```Markdown
> ---
> 
> <a name="arch-easy" />
> ```

What about rename link address and use `#arch`. Same for all `*-easy`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4282)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[INSTALL.md, line 125 at r1](https://reviewable.io:443/reviews/qtox/qtox/4282#-KfwDcZdkgZEF2pmXHMR:-KfwFJF6C4l00fCwQcVu:bbgmbwq) ([raw file](https://github.com/qtox/qtox/blob/4ec5752881d0c38f2b2d355041a4052bca964bae/INSTALL.md#L125)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about rename link address and use `#arch`. Same for all `*-easy`
</blockquote></details>

Somehow that doesn't seem right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4282)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[INSTALL.md, line 125 at r1](https://reviewable.io:443/reviews/qtox/qtox/4282#-KfwDcZdkgZEF2pmXHMR:-Kfx89TWdQadwJNqdSJD:bb76mu4) ([raw file](https://github.com/qtox/qtox/blob/4ec5752881d0c38f2b2d355041a4052bca964bae/INSTALL.md#L125)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Somehow that doesn't seem right.
</blockquote></details>

Why?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4282)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[INSTALL.md, line 125 at r1](https://reviewable.io:443/reviews/qtox/qtox/4282#-KfwDcZdkgZEF2pmXHMR:-Kfzj_JCPW31Xsm3yfA0:bvq9vnh) ([raw file](https://github.com/qtox/qtox/blob/4ec5752881d0c38f2b2d355041a4052bca964bae/INSTALL.md#L125)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Right now links in the index point to `$distro-$specialized_section`. With the suggested change some links would point to `$distro`, and some would point to `$distro-$specialized_section`, with former still being a specialized section, but without an explicit annotation.

Suggested change seems like something that could cause a bit of confusion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4282)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[INSTALL.md, line 125 at r1](https://reviewable.io:443/reviews/qtox/qtox/4282#-KfwDcZdkgZEF2pmXHMR:-Kg05LhbuFvvB91RFUpx:b-ctl6i3) ([raw file](https://github.com/qtox/qtox/blob/9236763865ba3096382bd2cdbff85a540d0f5546/INSTALL.md#L125)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Right now links in the index point to `$distro-$specialized_section`. With the suggested change some links would point to `$distro`, and some would point to `$distro-$specialized_section`, with former still being a specialized section, but without an explicit annotation.

Suggested change seems like something that could cause a bit of confusion.
</blockquote></details>

Just a note: I don't think, that anchor can confuse someone :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4282#-:-Kg05I4-xhJipPChOBe-:b-jbsf8z)*

**Pull request merged**
