### PR TITLE
install icons with `make install` and fix https://bugs.archlinux.org/task/47910

### PR DESCRIPTION
**Pull request by vith**
both changes are for issue #2903 

arch linux was working around a bug with the system tray icons by renaming them (see https://github.com/tux3/qTox/issues/2903#issuecomment-177552029); this PR makes it unnecessary

### CODE REVIEW

**Comment by zetok** [comment]
- [x] `$PREFIX` is not being respected:

```
install -m 644 -p /var/tmp/portage/net-im/qtox-9999/work/qtox-9999/qTox.desktop /var/tmp/portage/net-im/qtox-9999/image//usr/share/applications/
 * ACCESS DENIED:  open_wr:      /usr/share/icons/hicolor/scalable/apps/qtox.svg
/usr/bin/install: cannot create regular file ‘/usr/share/icons/hicolor/scalable/apps/qtox.svg’: Permission denied
Makefile:3991: recipe for target 'install_icon_scalable' failed
make: [install_icon_scalable] Error 1 (ignored)
>>> Completed installing qtox-9999 into /var/tmp/portage/net-im/qtox-9999/image/

 * --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 * LOG FILE: "/var/log/sandbox/sandbox-4795.log"
 * 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/share/icons/hicolor/scalable/apps/qtox.svg
A: /usr/share/icons/hicolor/scalable/apps/qtox.svg
R: /usr/share/icons/hicolor/scalable/apps/qtox.svg
C: /usr/bin/install -m 644 -p /var/tmp/portage/net-im/qtox-9999/work/qtox-9999/img/icons/qtox.svg /usr/share/icons/hicolor/scalable/apps/
```

**Comment by zetok** [comment]
- [ ] ~~double compiling – `make install` makes qTox to be compiled again~~ EDIT: apparently it may happen also on master
  
  reproducible with:

``` bash
#!/bin/bash

# copy qTox, here, removing old version
copy_qtox() {
    [[ -e "qTox" ]] && rm -rf qTox

    echo -n "Copying qTox dir..."
    cp -a --reflink=auto \
        ~/git_zetok/tox/qTox \
        ./
    echo " Done."
}

build_qtox() {
    /usr/lib/qt5/bin/qmake \
        PREFIX="$PWD/usr/" \
        QMAKE_CXX="ccache g++" \
        QMAKE_CXXFLAGS="-O0 -ggdb -fstack-protector-strong" \
        DISABLE_FILTER_AUDIO=YES \
        ENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND=NO \
        ENABLE_SYSTRAY_GTK_BACKEND=NO \
        ENABLE_NOTIFIACATION_SNORE_BACKEND=YES && \
    time make -j$(nproc)
}

install_qtox() {
    make install
}


copy_qtox && \
cd qTox && \
build_qtox && \
install_qtox || echo WTF
```

**Comment by vith** [comment]
Only compiles once for me... https://gist.github.com/vith/fa2ae009da571a8520a348e0faeed28b

**Comment by zetok** [comment]
https://gist.github.com/zetok/31b8c9a6c192afcc374869d6fb7f98ea ← the main difference from log above is that translation files are being updated/generated

I think that it should be tested on some other than Gentoo or Arch distro, to have a 3rd sample.

> <vith> lupdate version 5.6.0

I'm using 5.5.1.

**Comment by vith** [comment]
I can replicate the `make install` recompile on Ubuntu 15.04. I'll investigate further.

**Comment by sudden6** [comment]
I can also confirm the `make install` recompile on openSUSE Leap 42.1.

```
QMake version 3.0                                                                                                                
Using Qt version 5.5.1 in /usr/lib64
```

**Comment by vith** [comment]
I can now reproduce the double build on Arch Linux. It only happens when you switch branches first. The contents of the working tree's files seem to be irrelevant.

Here's an updated version of zetok's test script from above, demonstrating the official master branch double building, and my branch not double building:

``` bash
#!/bin/bash

set -xe

ARG="$1"

# make a bare clone to save bandwidth when repeating this test
if [ ! -d "./vith-qTox" ]; then
    git clone --bare https://github.com/vith/qTox ./vith-qTox
fi

# copy qTox, here, removing old version
copy_qtox() {
    [[ -e "qTox" ]] && rm -rf qTox

    echo -n "Cloning vith's qTox fork..."
    #git clone --mirror ./vith-qTox --origin "vith" --branch "issue-2903" ./qTox
    git clone https://github.com/vith/qTox --reference ./vith-qTox --dissociate --origin vith --branch issue-2903 ./qTox

    if [ "official" = "$ARG" ]; then
        cd ./qTox
        git remote add tux3 https://github.com/tux3/qTox
        git fetch --all
        git checkout tux3/master -b tux3-master
        cd ..
        echo " Done."
    fi
}

build_qtox() {
    qmake-qt5 \
        PREFIX="$PWD/usr/" \
        QMAKE_CXX="ccache g++" \
        QMAKE_CXXFLAGS="-O0 -ggdb -fstack-protector-strong" \
        DISABLE_FILTER_AUDIO=YES \
        ENABLE_SYSTRAY_STATUSNOTIFIER_BACKEND=NO \
        ENABLE_SYSTRAY_GTK_BACKEND=NO \
        ENABLE_NOTIFIACATION_SNORE_BACKEND=YES && \
    time make -j$(nproc)
}

install_qtox() {
    make install
}


copy_qtox
cd qTox
git branch -vv
git status --ignored
echo "built qtox $((build_qtox 2>/dev/null && install_qtox 2>/dev/null || echo WTF) | grep -- '-o qtox' | wc -l) times"
```

### Building my branch:

``` shell-session
~/qtox-double-compile
❯ ./run_test 
+ ARG=
+ '[' '!' -d ./vith-qTox ']'
+ copy_qtox
+ [[ -e qTox ]]
+ rm -rf qTox
+ echo -n 'Cloning vith'\''s qTox fork...'
Cloning vith's qTox fork...+ git clone https://github.com/vith/qTox --reference ./vith-qTox --dissociate --origin vith --branch issue-2903 ./qTox
Cloning into './qTox'...
Checking connectivity... done.
Counting objects: 27470, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7072/7072), done.
Writing objects: 100% (27470/27470), done.
Total 27470 (delta 20304), reused 27470 (delta 20304)
+ '[' official = '' ']'
+ cd qTox
+ git branch -vv
* issue-2903 90874a4 [vith/issue-2903] fix(Widget::updateIcons): fix the way systray icons are loaded
+ git status --ignored
On branch issue-2903
Your branch is up-to-date with 'vith/issue-2903'.
nothing to commit, working directory clean
++ grep -- '-o qtox'
++ build_qtox
++ wc -l
++ install_qtox
+ echo 'built qtox 1 times'
built qtox 1 times
```

### Building official master:

``` shell-session
~/qtox-double-compile
❯ ./run_test official
+ ARG=official
+ '[' '!' -d ./vith-qTox ']'
+ copy_qtox
+ [[ -e qTox ]]
+ rm -rf qTox
+ echo -n 'Cloning vith'\''s qTox fork...'
Cloning vith's qTox fork...+ git clone https://github.com/vith/qTox --reference ./vith-qTox --dissociate --origin vith --branch issue-2903 ./qTox
Cloning into './qTox'...
Checking connectivity... done.
Counting objects: 27470, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (7072/7072), done.
Writing objects: 100% (27470/27470), done.
Total 27470 (delta 20304), reused 27470 (delta 20304)
+ '[' official = official ']'
+ cd ./qTox
+ git remote add tux3 https://github.com/tux3/qTox
+ git fetch --all
Fetching vith
Fetching tux3
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 9 (delta 1), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
From https://github.com/tux3/qTox
 * [new branch]      audio-next -> tux3/audio-next
 * [new branch]      master     -> tux3/master
 * [new branch]      stable     -> tux3/stable
 * [new branch]      testing    -> tux3/testing
+ git checkout tux3/master -b tux3-master
Branch tux3-master set up to track remote branch master from tux3.
Switched to a new branch 'tux3-master'
+ cd ..
+ echo ' Done.'
 Done.
+ cd qTox
+ git branch -vv
  issue-2903  90874a4 [vith/issue-2903] fix(Widget::updateIcons): fix the way systray icons are loaded
* tux3-master 983c4ff [tux3/master] chore: remove not needed binary blobs and script from `tools/`
+ git status --ignored
On branch tux3-master
Your branch is up-to-date with 'tux3/master'.
nothing to commit, working directory clean
++ build_qtox
++ grep -- '-o qtox'
++ wc -l
++ install_qtox
+ echo 'built qtox 2 times'
built qtox 2 times
```

**Comment by sudden6** [comment]
so this seems to be a general problem. I would consider this ready then, @zetok what do you think?

**Comment by zetok** [comment]
> so this seems to be a general problem. I would consider this ready then

I could reproduce too on master, the only difference between master & PR is that with PR it happens a lot more often.

So I guess that there's no reason to not merge PR :)

**Pull request merged**
