### PR TITLE
feat(chatform): Highlight chat history

### LINKED ISSUE #2296: [Request] Highlight chat history
Hello,

for better visibility i would like to have the numbers in the calender view, when you have a chat history, bold.

### PR DESCRIPTION
**Pull request by tWido**
Calendar dates with chat history highlighted with bold
Fixes #2296

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4488)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/persistence/history.cpp, line 296 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT87dun1ZnihV9EGdj:-KnT87dun1ZnihV9EGdk:bwktrc3) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/persistence/history.cpp#L296)):*
> ```cpp
>  * @return List of pairs. First item contains days from start. Second item contains message count.
>  */
> QList<QPair<uint, uint>> History::getChatHistoryCounts(const QString& friendPk, const QDate& from,
> ```

Why do you pass public key as `QString`? `ToxPk` would be more obvious

---

*[src/widget/form/loadhistorydialog.cpp, line 56 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT9JV97FNu-VOoIBpr:-KnT9JV97FNu-VOoIBps:b-ukm9j7) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/widget/form/loadhistorydialog.cpp#L56)):*
> ```cpp
> }
> 
> void LoadHistoryDialog::HighlightDates(int year, int month)
> ```

Function name should start from lowercase character

---

*[src/widget/form/loadhistorydialog.cpp, line 67 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT9UvufmDMepb7MWm1:-KnT9UvufmDMepb7MWm2:b-oqc4c1) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/widget/form/loadhistorydialog.cpp#L67)):*
> ```cpp
>     bold.setFontWeight(QFont::Bold);
> 
>     for (QList<QPair<uint, uint>>::iterator it = counts.begin(); it != counts.end(); it++) {
> ```

You can use iterator like `for (QPair p : counts)`, I guess

---

*[src/widget/form/loadhistorydialog.cpp, line 68 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnTAegXh3HGMt0aNoxi:-KnTAegXh3HGMt0aNoxj:b-k5ap4v) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/widget/form/loadhistorydialog.cpp#L68)):*
> ```cpp
> 
>     for (QList<QPair<uint, uint>>::iterator it = counts.begin(); it != counts.end(); it++) {
>         ui->fromDate->setDateTextFormat(monthStart.addDays((*it).first), bold);
> ```

If you want, you can extract `ui->fromDate` into variable for better reading

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by Diadlo** [comment]
@tWido Please, use Reviewable to mention changes, in order for github to notify users

**Comment by Diadlo** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 291 at r2](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnTc75Vl_e_fTrAyq5H:-KnTc75Vl_e_fTrAyq5I:b-3fxsia) ([raw file](https://github.com/qtox/qtox/blob/8e635826b967698609277e5779f7d2ebc005c17f/src/persistence/history.cpp#L291)):*
> ```cpp
> /**
>  * @brief Fetches chat messages counts for each day from the database.
>  * @param friendPk Friend publick key to fetch.
> ```

*public

---

*[src/persistence/history.cpp, line 312 at r2](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnTcUVDx0PCK_9F_zp-:-KnTcUVEggTHY6rEW7bt:bnd28sb) ([raw file](https://github.com/qtox/qtox/blob/8e635826b967698609277e5779f7d2ebc005c17f/src/persistence/history.cpp#L312)):*
> ```cpp
> 
>     QString queryText =
>         QString("SELECT COUNT(history.id), ((timestamp / 1000  / 60 / 60 / 24)  - %4 ) AS day "
> ```

Few extra spaces in timestamp calculation (`1000<space><space>` and `<space><space>-<space>%4`>)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by Diadlo** [comment]
@tWido Please, use Reviewable to mention changes, in order for github to notify users

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488#-:-KnU-hOV4l0uIdgoafn6:b-jbsf8z)*

**Comment by tWido** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 296 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT87dun1ZnihV9EGdj:-KnU5UZa8DFLu43BYYXp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/persistence/history.cpp#L296)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why do you pass public key as `QString`? `ToxPk` would be more obvious
</blockquote></details>

Done.

---

*[src/persistence/history.cpp, line 291 at r2](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnTc75Vl_e_fTrAyq5H:-KnU5U8CXyw6YOo23JTj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8e635826b967698609277e5779f7d2ebc005c17f/src/persistence/history.cpp#L291)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

*public
</blockquote></details>

Done.

---

*[src/persistence/history.cpp, line 312 at r2](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnTcUVDx0PCK_9F_zp-:-KnU5V1pB1OPdPp3fJR9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8e635826b967698609277e5779f7d2ebc005c17f/src/persistence/history.cpp#L312)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Few extra spaces in timestamp calculation (`1000<space><space>` and `<space><space>-<space>%4`>)
</blockquote></details>

Done.

---

*[src/widget/form/loadhistorydialog.cpp, line 56 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT9JV97FNu-VOoIBpr:-KnU5VT7Ozqug3pi8lur:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/widget/form/loadhistorydialog.cpp#L56)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Function name should start from lowercase character
</blockquote></details>

Done.

---

*[src/widget/form/loadhistorydialog.cpp, line 67 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT9UvufmDMepb7MWm1:-KnU5VpcPCnkdRH6sSgi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/widget/form/loadhistorydialog.cpp#L67)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

You can use iterator like `for (QPair p : counts)`, I guess
</blockquote></details>

Done.

---

*[src/widget/form/loadhistorydialog.cpp, line 68 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnTAegXh3HGMt0aNoxi:-KnU5W4FCHF7phCZie4D:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/widget/form/loadhistorydialog.cpp#L68)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

If you want, you can extract `ui->fromDate` into variable for better reading
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by sudden6** [comment]
Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 314 at r3](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVOHOvcRUvbqyTPSGQ:-KnVOHOwn7J9qArzM4sh:b-axc7gs) ([raw file](https://github.com/qtox/qtox/blob/842789afd333420f45c2992b23b236242636f27a/src/persistence/history.cpp#L314)):*
> ```cpp
>         QString("SELECT COUNT(history.id), ((timestamp / 1000 / 60 / 60 / 24) - %4 ) AS day "
>                 "FROM history "
>                 "LEFT JOIN faux_offline_pending ON history.id = faux_offline_pending.id "
> ```

Why use the faux_offline_pending information?

---

*[src/persistence/history.cpp, line 316 at r3](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVNxUTRtAoBbrRo29N:-KnVNxUUJo8xz4Xcohno:b4fxqk7) ([raw file](https://github.com/qtox/qtox/blob/842789afd333420f45c2992b23b236242636f27a/src/persistence/history.cpp#L316)):*
> ```cpp
>                 "LEFT JOIN faux_offline_pending ON history.id = faux_offline_pending.id "
>                 "JOIN peers chat ON chat_id = chat.id "
>                 "JOIN aliases ON sender_alias = aliases.id "
> ```

Is it necessary to do this join? I don't think aliases are used in this function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 314 at r3](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVOHOvcRUvbqyTPSGQ:-KnVPY_nXtc0wOeaIrMi:b-gmf6mh) ([raw file](https://github.com/qtox/qtox/blob/842789afd333420f45c2992b23b236242636f27a/src/persistence/history.cpp#L314)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Why use the faux_offline_pending information?
</blockquote></details>

I think, it's used to highlight pendings messages too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 296 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT87dun1ZnihV9EGdj:-KnVUI3miEtfZu9QTfqQ:b-nox9b5) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/persistence/history.cpp#L296)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What do you think, avout using `struct DateMessages` instead of QPair? To make content more obvious?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by tWido** [comment]
Review status: 2 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 296 at r1](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnT87dun1ZnihV9EGdj:-KnVce8SexSXLL28aitL:b-ykxlov) ([raw file](https://github.com/qtox/qtox/blob/1978048ae24930f4ccbb2c04db944995f8be3be5/src/persistence/history.cpp#L296)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What do you think, avout using `struct DateMessages` instead of QPair? To make content more obvious?
</blockquote></details>

Used struct as mentioned.  Please, check if variable names are ok.

---

*[src/persistence/history.cpp, line 314 at r3](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVOHOvcRUvbqyTPSGQ:-KnVd2JtPZeV7vLBDgDH:b-airwus) ([raw file](https://github.com/qtox/qtox/blob/842789afd333420f45c2992b23b236242636f27a/src/persistence/history.cpp#L314)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, it's used to highlight pendings messages too
</blockquote></details>

Even without tis particular join, pending messages still show up in calendar.

---

*[src/persistence/history.cpp, line 316 at r3](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVNxUTRtAoBbrRo29N:-KnVcvcOFGt2hVD7EXJ-:bkvy761) ([raw file](https://github.com/qtox/qtox/blob/842789afd333420f45c2992b23b236242636f27a/src/persistence/history.cpp#L316)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Is it necessary to do this join? I don't think aliases are used in this function
</blockquote></details>

Deleted not needed joins. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r4.
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 294 at r4](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVfRkLPhlAgdckHwtw:-KnVfRkM21pB56SeYALs:b-sy2api) ([raw file](https://github.com/qtox/qtox/blob/deada071d762157be63400110da4be9f627a2263/src/persistence/history.cpp#L294)):*
> ```cpp
>  * @param from Start of period to fetch.
>  * @param to End of period to fetch.
>  * @return List of pairs. First item contains days from start. Second item contains message count.
> ```

Please update the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by tWido** [comment]
Review status: 4 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 294 at r4](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVfRkLPhlAgdckHwtw:-KnVhN922IvTSAJH_Tn2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/deada071d762157be63400110da4be9f627a2263/src/persistence/history.cpp#L294)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Please update the comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/history.cpp, line 310 at r5](https://reviewable.io:443/reviews/qtox/qtox/4488#-KnVitEiPnig_CzQ-1A8:-KnVitEiPnig_CzQ-1A9:b-i4p6rb) ([raw file](https://github.com/qtox/qtox/blob/3257770bfa61838ab398a31de28f623f7b28d77a/src/persistence/history.cpp#L310)):*
> ```cpp
>         app.count = row[0].toUInt();
>         app.offsetDays = row[1].toUInt();
>         counts.append(app);
> ```

I'm ok with it, but just a note, you can use bracket initialization. I.e.
`countes.append({ row[0].toUInt(), row[1].toUInt() });`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4488#-:-KnYYbvyi0mbW4AAY-nX:b-jbsf8z)*

**Pull request merged**
