### PR TITLE
feat(camera): add higher resolution camera options

### LINKED ISSUE #5065: qTox should use all camera resolutions
My v4l2 camera allows up to 1920x1080 for H.264 format, and up to 2304x1536 for YUYV 4:2:2 format.

The largest video size qTox offers is 1080. This is probably because 1080 is the largest size for H.264 codec.

qTox shouldn't ignore higher sizes because they allow better picture quality. qTox should use ffmpeg or maybe openh264 library to encode H.264 in CPU when possible.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #5065

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5075)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong: time flies, when creating this these resolutions were not really popular^^

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5075#-:-L9v0Oc85YMBhJ4TS6ex:b-n8fboi)*

**Comment by Diadlo** [comment]
And please, check date of modification in copyright header

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/video/videomode.cpp, line 73 at r2](https://beta.reviewable.io/reviews/qtox/qtox/5075#-L9vPELz9qx1oiwZioR0:-L9vPELz9qx1oiwZioR1:bggh4ml) ([raw file](https://github.com/qtox/qtox/blob/04ecfe3f344c29d9c598d38aaad46f2da8a17728/src/video/videomode.cpp#L73)):*
> ```cpp
> {
>     constexpr uint32_t toleranceFactor = 10; // video mode must be within 10% to be "close enough" to ideal
>     return (width + height)/toleranceFactor;
> ```

Add spaces around `/`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5075#-:-L9vPJE42SfAzRjWh2G1:bt7jk48)*

**Comment by anthonybilinski** [comment]
@Diadlo Does it make more sense to bulk update copyright header of every file at once? I can submit a separate PR to do that, if it's desired.

EDIT: like https://github.com/anthonybilinski/qTox/commit/8dbc77e4b6b06593bcee24cde01d3d365b9192fd

**Comment by Diadlo** [comment]
@anthonybilinski Feel free to do for all files at once

**Pull request merged**
