### PR TITLE
fix(groups): enable AV groups after load

### LINKED ISSUE #5509: Loaded persistent group fails to send audio after joining call
##### Brief Description

OS: Ubuntu 18.04
qTox version: v1.16.3+
Commit hash:  f5aa07f5694a9172bb0bb6c4870cf5486a3460a7
toxcore:  v0.2.9
Qt:  5.11.1
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. A and B join audio group.
2. A and B join audio call.
3. A leaves call, closes qTox. B leaves call.
4. A opens qTox, loads persistent group.
5. A and B join call.

##### Observed Behavior
1. A sends no audio, had non-stop `toxav_group_send_audio` errors:
```
[09:42:14.536 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.576 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.586 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.605 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.636 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.645 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.666 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.696 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.705 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.726 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.735 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.766 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.795 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.806 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
[09:42:14.825 UTC] core/coreav.cpp:594 : Debug: toxav_group_send_audio error
```

### Additional Info

Loaded persistent group that fails to send audio:
```
Thread 8 "qTox Audio" hit Breakpoint 1, CoreAV::sendGroupCallAudio (this=
    0x56123fa2aba0, groupId=2, pcm=0x561245561d50, samples=960, 
    chans=2 '\002', rate=48000)
    at /home/abilinski/builds/qTox/src/core/coreav.cpp:593
593	    if (toxav_group_send_audio(toxav_get_tox(toxav.get()), groupId, pcm, samples, chans, rate) != 0)
```
Newly created group that succeeds in sending audio:
```
Thread 8 "qTox Audio" hit Breakpoint 1, CoreAV::sendGroupCallAudio (
    this=0x56123fa2aba0, groupId=3, pcm=0x5612455678d0, samples=960, 
    chans=2 '\002', rate=48000)
    at /home/abilinski/builds/qTox/src/core/coreav.cpp:593
593	    if (toxav_group_send_audio(toxav_get_tox(toxav.get()), groupId, pcm, samples, chans, rate) != 0)
```

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #5509

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

This uses a new API defined in https://github.com/TokTok/c-toxcore/pull/1305 (and a toxcore release once it is merged).

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5525)

### CODE REVIEW

**Comment by sudden6** [comment]
When this is merged we need to bump the c-toxcore version requirement.

**Comment by sudden6** [comment]
I merged the new API in the c-toxcore repository, do we need to check this still works or can we just merge it once c-toxcore is released?

**Comment by sudden6** [comment]
c-toxcore 2.10 got released so we can update our requirements, use it and then merge this fix

**Comment by anthonybilinski** [comment]
This is now rebased on Toxcore v0.2.10 and should finally be able to go in :D

**Comment by sudden6** [comment]
Do we hard-require v0.2.10 now? because then we should update the version requirements in the README.md too, and eventually add a compile time check.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: for the change itself

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5525#-:-LiPoUjq7-HuWDi4YS1m:b4rvwi6)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
Fixed a return error boolean inversion.

> Do we hard-require v0.2.10 now?

Good point, INSTALL.md updated.

> and eventually add a compile time check.

For now we just have the implicit link time check, but yeah it makes sense to me to check minimum version of all deps in cmake at time of finding them instead of waiting until link time.

**Pull request merged**
