### PR TITLE
fix(ci): fix travis' window build in debian docker by upgrading libseccomp2

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5876)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
This was tested by editing travis' config on my fork of qTox, to make it build windows deps on the branch here: https://travis-ci.org/anthonybilinski/qTox/jobs/597113660. The PR CI here won't hit the Windows build case until the branch is merged, so my fork's CI is the check to look at.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5876)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-windows.sh, line 111 at r1](https://reviewable.io/reviews/qtox/qtox/5876#-Lr48c_v82q9sN-eURfU:-Lr48c_wAIDjKDBlSx5G:bdr4yin) ([raw file](https://github.com/qtox/qtox/blob/3590bc7e814d2a6ceb87c510492d48bb4a5afd19/.travis/build-windows.sh#L111)):*
> ```Shell
> ls -lbh "$PWD"
> 
> sudo apt-get update -qq
> ```

can you add a comment why we need to update libseccomp2?

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5876#-:-Lr48ih88or-M_XPii9N:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5876)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[.travis/build-windows.sh, line 111 at r1](https://reviewable.io/reviews/qtox/qtox/5876#-Lr48c_v82q9sN-eURfU:-Lr63Ppv2ESqy_Sq2e1g:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3590bc7e814d2a6ceb87c510492d48bb4a5afd19/.travis/build-windows.sh#L111)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can you add a comment why we need to update libseccomp2?
</blockquote></details>

Done.

**Pull request merged**
