### PR TITLE
fix(groupinviteform): escape HTML

### PR DESCRIPTION
**Pull request by TheNain38**
Please test it, it's been a while since last time I did some code...

### CODE REVIEW

**Comment by antis81** [comment]
@TheNain38 Code will work.

@zetok I don't like the idea of supporting HTML in the qTox name at all. Plain text should be used. If at all, RichText might be allowed (and not escaped in this case). But the problem is: Escaping HTML results in ugly appearance like e.g.:

`Invited by <b>&lt;font size="36"&gt;Some Body&lt;/font&gt;</b>`

Preventing use of HTML in names resolves all of those problems in one go. Well, users who made use HTML need to adjust their names, but that's it actually!

Agree'd?

**Comment by zetok** [comment]
> Preventing use of HTML in names resolves all of those problems in one go.

No. Users should be allowed to put whatever text they want as their name/whatever. but the text shouldn't be parsed as HTML. Instead it should be displayed exactly the way it is, that is, as a plaintext.

_edited for clarification_

**Comment by antis81** [comment]
> …Instead it should be displayed exactly the way it is, that is, as a plaintext.

That's exactly what I said. :) So the fix is alright by escaping any `<, >, & and "` characters and setting the result as "reduced HTML subset" to the label.

**Comment by zetok** [comment]
> That's exactly what I said. :)

Looks like I've misunderstood.

> Preventing use of HTML in names resolves all of those problems in one go.

In the past some people wanted to actively limit what is allowed as username / etc, which is not going to work well, and only cause problems for users. So I guess I'm a bit touchy about things that sound exactly like those ideas, sorry about that.

**Pull request merged**
