### PR TITLE
Add CTest

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4149)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 8 files at r1.
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/core/toxid_test.cpp, line 27 at r1](https://reviewable.io:443/reviews/qtox/qtox/4149#-KcK0qSbjUAi5qx3F9FF:-KcK0qScrku36lCyV2aH:b-3pc1h2) ([raw file](https://github.com/qtox/qtox/blob/f6f26ecbe66d2f67f779d1f1f5acf60d121c4670/test/core/toxid_test.cpp#L27)):*
> ```cpp
>     bool nequal = toxId1 != toxId2;
>     ck_assert(toxId1 == toxId2);
>     ck_assert(nequal != equal);
> ```

couldn't this be simplified to `ck_assert(!(toxId1 != toxId2));`?

---

*[test/core/toxpk_test.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4149#-KcK1nnLHLgVId1aENB-:-KcK1nnMS-fV-F5Z2AG0:bnj7hl0) ([raw file](https://github.com/qtox/qtox/blob/f6f26ecbe66d2f67f779d1f1f5acf60d121c4670/test/core/toxpk_test.cpp#L37)):*
> ```cpp
>     bool equal = pk1 == pk2;
>     bool nequal = pk1 != pk2;
>     ck_assert(nequal != equal);
> ```

same as above

---

*[test/core/utils.h, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4149#-KcK232SJt_mBqk-eP-9:-KcK232Toh7NfFVYO4mW:b-sfxxqn) ([raw file](https://github.com/qtox/qtox/blob/f6f26ecbe66d2f67f779d1f1f5acf60d121c4670/test/core/utils.h#L1)):*
> ```objc
> #ifndef _TEST_UTILS_H_
> ```

since this file will probably be useful for other things, maybe move it to `test/util/`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4149)*

**Comment by Diadlo** [comment]
Review status: 2 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/core/toxid_test.cpp, line 27 at r1](https://reviewable.io:443/reviews/qtox/qtox/4149#-KcK0qSbjUAi5qx3F9FF:-KcK8XhZZKyqtxAH13nl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f6f26ecbe66d2f67f779d1f1f5acf60d121c4670/test/core/toxid_test.cpp#L27)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

couldn't this be simplified to `ck_assert(!(toxId1 != toxId2));`?
</blockquote></details>

Done.

---

*[test/core/toxpk_test.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4149#-KcK1nnLHLgVId1aENB-:-KcK8Y8zWebNniUQcXFR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f6f26ecbe66d2f67f779d1f1f5acf60d121c4670/test/core/toxpk_test.cpp#L37)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

---

*[test/core/utils.h, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4149#-KcK232SJt_mBqk-eP-9:-KcK8Yf8jJb3oJBG3Z9a:bu7x26r) ([raw file](https://github.com/qtox/qtox/blob/f6f26ecbe66d2f67f779d1f1f5acf60d121c4670/test/core/utils.h#L1)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

since this file will probably be useful for other things, maybe move it to `test/util/`?
</blockquote></details>

Renamed and moved into `test/common.h`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4149)*

**Comment by sudden6** [comment]
Reviewed 2 of 8 files at r1, 4 of 4 files at r2.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4149)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4149#-:-KcNwKro8sDLiWtq1k4e:b-jbsf8z)*

**Pull request merged**
