### PR TITLE
[Refactor] Extract header of GenericChatForm in separate widget

### LINKED ISSUE #2749: qTox (PTT) Push To Talk doesn't work
I was in a call and decided to try the PTT feature.
muted the microphone and then pressed CTRL+P, also tried right control to see if there was any difference. The end result was the other side was simply no able to hear.

the shortcut was obtained from the wiki entry https://github.com/tux3/qTox/wiki/Keyboard-shortcuts

Thank you

### PR DESCRIPTION
**Pull request by Diadlo**
Also fix #2749

----
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4768)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/chatformheader.h, line 93 at r1](https://reviewable.io:443/reviews/qtox/qtox/4768#-KxSHS5SlxZWdtog3JZ4:-KxSHS5TAlJb2TXkUknz:bndwydz) ([raw file](https://github.com/qtox/qtox/blob/9019807074fbd069ac09a7733f4703c259f81b4a/src/widget/chatformheader.h#L93)):*
> ```objc
>     QToolButton* micButton;
> 
>     QPointer<CallConfirmWidget> callConfirm;
> ```

suggestion: use `std::unique_ptr` here, then we never need to worry about a resource leak

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4768)*

**Comment by Diadlo** [comment]
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/chatformheader.h, line 93 at r1](https://reviewable.io:443/reviews/qtox/qtox/4768#-KxSHS5SlxZWdtog3JZ4:-KxTrzDNT_NRKgff3M6f:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9019807074fbd069ac09a7733f4703c259f81b4a/src/widget/chatformheader.h#L93)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

suggestion: use `std::unique_ptr` here, then we never need to worry about a resource leak
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4768)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4768#-:-KxXQxbFrU3KpheNvKA_:b-jbsf8z)*

**Comment by noavarice** [comment]
Reviewed 6 of 9 files at r1, 3 of 3 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4768)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4768#-:-KxXWs_v9Z_aCXLsOaju:b-jbsf8z)*

**Pull request merged**
