### PR TITLE
[WIP] Replace Windows build guide with fresh one

### PR DESCRIPTION
**Pull request by DX37**
Relates to #3372 and partially fixes it (still need to add static build manual).

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4291)

### CODE REVIEW

**Comment by zetok** [comment]
cc @kehugter any opinion?

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[INSTALL.md, line 760 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8UO7QHmQpj6FfwOi5:-Kg8UO7QHmQpj6FfwOi6:b-3kj9w0) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L760)):*
> ```Markdown
> large size of Qt5 package (~800 MB to download and ~5 GB to extract).
> 
> **SECOND WARNING:** The resulting executable isn't static and **will run from
> ```

Perhaps instead of `$# WARNING` use a list?

I.e.

```
**Note:**
  - You need to have…
  - The resulting…
```
?

---

*[INSTALL.md, line 772 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8V9Yg2VODMfd6umVc:-Kg8V9YhEF1IcwFX4lgf:b-im1pej) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L772)):*
> ```Markdown
> ```bash
> pacman -Syu
> ```
> ```

Add a newline before

~~~
```bash```
~~~

 and after closing

~~~
```
~~~

same goes for other occurrences

---

*[INSTALL.md, line 797 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8VFMXX2Y4idmX8w0K:-Kg8VFMXX2Y4idmX8w0L:b-y9b9ez) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L797)):*
> ```Markdown
> ### Compiling toxcore
> 
> Compilation process is similar to [compilation on Linux](#compile-toxcore), but it's more simple.
> ```

<=79 characters per line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291#-:-Kg8UIY3sYgKZ2tK3isN:b-litkc5)*

**Comment by DX37** [comment]
Fixed.

**Comment by DX37** [comment]
Whoa, I forgot to add commands for x64 shell :o

**Comment by DX37** [comment]
> Cool. Would you like me to make a lot of comments in your pull request or may I get access to your repo so that I can modify it directly? Or would you prefer for me to add a pull request to your repo?

@nweyand Create a PR to my repo (and I will practice a little in accepting PRs).

**Comment by DX37** [comment]
Or... I dunno. Is Github's comments more comfortable, @nweyand?

**Comment by sudden6** [comment]
@DX37 and @nweyand for discussion and PR review I suggest to use the "reviewable" button, that's exactly the use case why we included it.

**Comment by nweyand** [comment]
@sudden6 what “reviewable” butten? Where do I find it?

@DX37 pull requests will work fine. I also need more practice with those :D
Could it be that you‘ve added a stash file and a subrepo update in your last commit by mistake?

**Comment by DX37** [comment]
@nweyand Yep, that was a mistake :D

**Comment by DX37** [comment]
Oh, that's not right. We should add only one commit in PR.
I should fix this by myself.

**Comment by DX37** [comment]
Okay, I get it. I need to squash these commits into one.

**Comment by nweyand** [comment]
There in an other possible issue with your build instructions: I am using custom build versions of the Qt libs (for debugging purposes and for unusual target platforms). Is there any way one could use an already build Qt version on HDD instead of downloading everything anew and wasting some additional 6GB of disk space?

**Comment by DX37** [comment]
@nweyand Adding root directory of your Qt to $PATH, I guess.

**Comment by nweyand** [comment]
OK, I will try that later.

**Comment by nweyand** [comment]
BTW, does MYSYS also have the packages for the clang/LLVM toolchain? If that is the case, it might be cool to use clang as it gives better compiler warnings and more readable error messages.

**Comment by DX37** [comment]
@nweyand Yep.

**Comment by nweyand** [comment]
Nice. Maybe we should think about using that instead of GCC. (just my 2c – treat it as a suggestion)

Now there are only three issues left that need resolving IMHO:
1. Static builds. It should be possible to build qTox statically with the default instruction set.
2. IDE integration: If you want to have many contributors, contributing must be made easy. Building with MYSYS is a cool thing, but people want to “just open it in QtCreator” and hit “Run” in there to see whether it’s doing what they want. Therefore the instructions should include what needs to be done to make MYSYS work with QtCreator.
3. Add the instructions to use already installed Qt binaries. People who have several of those already installed (like me^^) won’t want to duplicate all their installed binaries, especially as they require multiple GB of disk space each.


EDIT: BTW, there is no reason why there shouldn’t be several commits included in one pull request. This allows (among other things) to see later who committed to the pull request. If you overwrite the single commit each time, both the development history as well as the different contributors (if there are several) are lost. ;)

**Comment by DX37** [comment]
I just read [this guide](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#pull-request) wrong, I guess.
@zetok @sudden6 What do you think?

**Comment by sudden6** [comment]
@DX37 While you're working on it it is not a problem to have multiple commits. Maybe at the end use interactive rebase to clean up the history before merge.

@nweyand The reviewable button is in the first message of every PR.

**Comment by nweyand** [comment]
@DX37, it would be nice if you could give me the impression of having read what I (and others) said.
> EDIT: BTW, there is no reason why there shouldn’t be several commits included in one pull request. This allows (among other things) to see later who committed to the pull request. If you overwrite the single commit each time, both the development history as well as the different contributors (if there are several) are lost. ;)

> @DX37 While you're working on it it is not a problem to have multiple commits. Maybe at the end use interactive rebase to clean up the history before merge.

This is how it works: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

The idea is not to delete all history and replace it with one single commit – this defeats the purpose of keeping history – but to clean it up so that the essentials remain in there (i.e. who did what).

**Comment by DX37** [comment]
@nweyand I messed up before any thoughts about multiple commits.
You will be mentioned. Don't worry 😉

**Comment by zetok** [comment]
@nweyand 
>@sudden6 what “reviewable” butten? Where do I find it?

https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#reviewing ← do the instructions need to be expanded/clarified?

@DX37 ↑ mind using reviewable to mark things that are done?

Btw, PR needs to be rebased after #4304 got merged.

---

Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[INSTALL.md, line 763 at r2](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgSIicGPrxF5Y0RxvI5:-KgSIicHmpC5DrINZT8t:b-y9qrcb) ([raw file](https://github.com/qtox/qtox/blob/3ca58ed6fe32e649a727391a3a8ff0cd0561fa88/INSTALL.md#L763)):*
> ```Markdown
>  2. The resulting executable isn't a static build and **will run from MSYS2 shell only**!
>  Static build is in progress.
>  ⇒ TODO: Those instructions need to be added before this is merged
> ```

If the PR is still WIP, perhaps add `[WIP]` to PR title?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291#-:-KgSIAedaEWGKe95VBBZ:b-eg8r4s)*

**Comment by DX37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[INSTALL.md, line 760 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8UO7QHmQpj6FfwOi5:-KgSPPUtVTG0H_x_gpiF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L760)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Perhaps instead of `$# WARNING` use a list?

I.e.

```
**Note:**
  - You need to have…
  - The resulting…
```
?
</blockquote></details>

Done.

---

*[INSTALL.md, line 772 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8V9Yg2VODMfd6umVc:-KgSPQclhP_sqqXGCT_r:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L772)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Add a newline before

~~~
```bash```
~~~

 and after closing

~~~
```
~~~

same goes for other occurrences
</blockquote></details>

Done.

---

*[INSTALL.md, line 797 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8VFMXX2Y4idmX8w0K:-KgSPRLax2WMwS6xj-CR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L797)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

<=79 characters per line
</blockquote></details>

Done.

---

*[INSTALL.md, line 763 at r2](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgSIicGPrxF5Y0RxvI5:-KgSPQ4t8NXLaTxycAOf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3ca58ed6fe32e649a727391a3a8ff0cd0561fa88/INSTALL.md#L763)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

If the PR is still WIP, perhaps add `[WIP]` to PR title?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[INSTALL.md, line 797 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8VFMXX2Y4idmX8w0K:-KgSbqlnCEJlCaLPGKqZ:b-3eo4pc) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L797)):*
<details><summary><i>Previously, DX37 (Maxim Kurnosenko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are still new lines that exceed 79 characters.

If you're using vim, this might be of help:

```vim
" Highlight stuff that goes over 79 chars.
augroup vimrc_autocmds
    autocmd BufEnter * highlight OverLength ctermbg=white
    autocmd BufEnter * match OverLength /\%80v.*/
augroup END
" clear highlight
nnoremap <silent> <F9> :highlight OverLength ctermbg=black<CR>
```

---

*[INSTALL.md, line 793 at r2](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgScCAInrJ_CFqRSLEL:-KgScCAInrJ_CFqRSLEM:bfhui92) ([raw file](https://github.com/qtox/qtox/blob/3ca58ed6fe32e649a727391a3a8ff0cd0561fa88/INSTALL.md#L793)):*
> ```Markdown
> mingw-w64-i686-opus mingw-w64-i686-openal mingw-w64-i686-qrencode mingw-w64-i686-libsodium \
> mingw-w64-i686-sqlcipher
> ```
> ```

It would be good to have each dependency on a separate line, so that one could use `sort(1)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291)*

**Comment by DX37** [comment]
Phew... 😅 Rebased. Still WIP.

**Comment by DX37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 797 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8VFMXX2Y4idmX8w0K:-KgTw21nocfD25bt23GN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L797)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

There are still new lines that exceed 79 characters.

If you're using vim, this might be of help:

```vim
" Highlight stuff that goes over 79 chars.
augroup vimrc_autocmds
    autocmd BufEnter * highlight OverLength ctermbg=white
    autocmd BufEnter * match OverLength /\%80v.*/
augroup END
" clear highlight
nnoremap <silent> <F9> :highlight OverLength ctermbg=black<CR>
```
</blockquote></details>

Done.

---

*[INSTALL.md, line 793 at r2](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgScCAInrJ_CFqRSLEL:-KgTw-CynCyL3pUgHOE3:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3ca58ed6fe32e649a727391a3a8ff0cd0561fa88/INSTALL.md#L793)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

It would be good to have each dependency on a separate line, so that one could use `sort(1)`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[INSTALL.md, line 755 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2H6iCB1AnkxGskDo:-KgU2H6jOVhGve2n37Gi:b-fm6kyb) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L755)):*
> ```Markdown
> ## Windows
> 
> This guide will show you modern way to compile qTox on Windows using MSYS2 shell.
> ```

line length

---

*[INSTALL.md, line 797 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8VFMXX2Y4idmX8w0K:-KgU2jmkZgZWrlBdZArQ:b-8nlap4) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L797)):*
<details><summary><i>Previously, DX37 (Maxim Kurnosenko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.

---

*[INSTALL.md, line 761 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2XGJg9VlUB4dnVbd:-KgU2XGKVR8Vb9bgrKQL:b-fm6kyb) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L761)):*
> ```Markdown
>  1. You need to have at least **6 GB** of HDD space because of the large
>  size of of Qt5 (~800 MB to download and ~5 GB to extract).
>  2. The resulting executable isn't a static build and **will run from MSYS2 shell only**!
> ```

line length

---

*[INSTALL.md, line 770 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2b21wwVGkz2mvXkr:-KgU2b22QFgIKCeSESsq:b-fm6kyb) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L770)):*
> ```Markdown
> and install it on your computer. The default location directly on C:\ works just fine.
> 
> After installing open the `MSYS2 MinGW 32-bit` shell for 32 bit building or the `64-bit` one,
> ```

line length

---

*[INSTALL.md, line 780 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2d_Mh6sd1mmdamNK:-KgU2d_Mh6sd1mmdamNL:b-fm6kyb) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L780)):*
> ```Markdown
> 
> If it says something along the lines of `Terminate shell after update`, you should restart
> the console after updating and run the update command above again to make sure it is fully
> ```

line length

---

*[INSTALL.md, line 785 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2efv3201g5bGbgOC:-KgU2efv3201g5bGbgOD:b-fm6kyb) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L785)):*
> ```Markdown
> ### Dependencies
> 
> In order to install the necessary dependencies, run the following command in your
> ```

line length

---

*[INSTALL.md, line 807 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2gh2ZsuaM7SIYJPy:-KgU2gh2ZsuaM7SIYJPz:b-fm6kyb) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L807)):*
> ```Markdown
> ```
> 
> Or, if you want to build for x64, open the `MSYS2 MinGW 64-bit` shell and use this command:
> ```

line length

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291)*

**Comment by DX37** [comment]
Oh god 😄

**Comment by DX37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[INSTALL.md, line 755 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2H6iCB1AnkxGskDo:-KhDP_gN-LLhCMinKA4V:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L755)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---

*[INSTALL.md, line 797 at r1](https://reviewable.io:443/reviews/qtox/qtox/4291#-Kg8VFMXX2Y4idmX8w0K:-KhDPm3aETeMQLu-4k-N:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7634c1e29e17106f6d51c211ed0ca7ad7783fe/INSTALL.md#L797)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.

---

*[INSTALL.md, line 793 at r2](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgScCAInrJ_CFqRSLEL:-KhDPkN3DwUFHsGAlj6A:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3ca58ed6fe32e649a727391a3a8ff0cd0561fa88/INSTALL.md#L793)):*
<details><summary><i>Previously, DX37 (Maxim Kurnosenko) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---

*[INSTALL.md, line 761 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2XGJg9VlUB4dnVbd:-KhDPb7VqNSRYNsu5tJz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L761)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---

*[INSTALL.md, line 770 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2b21wwVGkz2mvXkr:-KhDPgD0ZlJ5crJQnqW3:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L770)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---

*[INSTALL.md, line 780 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2d_Mh6sd1mmdamNK:-KhDPiKp4JspNd2Ln_aL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L780)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---

*[INSTALL.md, line 785 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2efv3201g5bGbgOC:-KhDPjdKfec0L1A0x9Cx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L785)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---

*[INSTALL.md, line 807 at r3](https://reviewable.io:443/reviews/qtox/qtox/4291#-KgU2gh2ZsuaM7SIYJPy:-KhDPl3PfIlZC6SdBjjy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b5d6230f98d4a05efefc98cfc7d1aa836cfe4904/INSTALL.md#L807)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

line length
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4291)*

**Comment by sudden6** [comment]
What's the state of this? Is it already working or still WIP?

**Comment by DX37** [comment]
> What's the state of this? Is it already working or still WIP?

Still WIP. At least static build. I'm a few busy to work with that.

**Comment by Diadlo** [comment]
PR didn't have any activity for over 2 months, and no one seems to be interested in working on it, thus closing.

If that's not the case, please either ask to reopen the pull, or make a new one.

**Pull request closed without merging**
