### PR TITLE
docs: update CHANGELOG.md for v1.5.0 release

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3606)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[CHANGELOG.md, line 13 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOkfm0bncDszDuo_YFZ:-KOkfm0bncDszDuo_YF_:ba6bv9l) ([raw file](https://github.com/qtox/qtox/blob/beaa4ddec2858d0bfb33eb68302661ab07ae3f97/CHANGELOG.md#L13)):_

> ``` Markdown
> #### Breaking Changes
> 
> * **textstyle:**  Change markdown syntax to be more intuitive ([32e48a97](https://github.com/qTox/qTox/commit/32e48a979ca78717a212800547c95ca0f1e67b8f), closes [#3404](https://github.com/qTox/qTox/issues/3404), breaks [#](https://github.com/qTox/qTox/issues/))
> ```

breaks link is useless

---

_[CHANGELOG.md, line 14 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOkfqTAcCher2T1hGN2:-KOkfqTAcCher2T1hGN3:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/beaa4ddec2858d0bfb33eb68302661ab07ae3f97/CHANGELOG.md#L14)):_

> ``` Markdown
> 
> * **textstyle:**  Change markdown syntax to be more intuitive ([32e48a97](https://github.com/qTox/qTox/commit/32e48a979ca78717a212800547c95ca0f1e67b8f), closes [#3404](https://github.com/qTox/qTox/issues/3404), breaks [#](https://github.com/qTox/qTox/issues/))
> * **widget:**  Disable sound notification for `busy` status ([e7785ab4](https://github.com/qTox/qTox/commit/e7785ab4c2790b2c10b33c416bc78ad23a16cc63), breaks [#](https://github.com/qTox/qTox/issues/))
> ```

same

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[CHANGELOG.md, line 13 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOkfm0bncDszDuo_YFZ:-KOkg83HOXiPq6FNseoR:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/beaa4ddec2858d0bfb33eb68302661ab07ae3f97/CHANGELOG.md#L13)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> breaks link is useless
> </details>
> Fixed.

---

_[CHANGELOG.md, line 14 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOkfqTAcCher2T1hGN2:-KOkg8y8TEQxPbkIkEuF:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/beaa4ddec2858d0bfb33eb68302661ab07ae3f97/CHANGELOG.md#L14)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> same
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606#-:-KOkk1LPdLJ_tygRFd3v:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606#-:-KOkumSOTmu_A5d4lWUw:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606#-:-KOkzrIB6JxaMm7IvnnQ:bnfp4nl)_

**Comment by initramfs** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[CHANGELOG.md, line 13 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl-a-FbgvaSpXGqLkk:-KOl-a-GwCEkfJohwm2E:b-h88obv) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L13)):_

> ``` Markdown
> #### Breaking Changes
> 
> * **textstyle:**  Change markdown syntax to be more intuitive ([32e48a97](https://github.com/qTox/qTox/commit/32e48a979ca78717a212800547c95ca0f1e67b8f))
> ```

I know this has been marked as a breaking change in the commit, but from a user's perspective, this doesn't seem to have any affect on functionality, nor does it "break" anything in the repository related to the actual source. This is just for consideration for whether this be moved to another section.

---

_[CHANGELOG.md, line 77 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl10req_ux7d9hj8Cc:-KOl10req_ux7d9hj8Cd:bunjrfj) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L77)):_

> ``` Markdown
> * **status:**:  add ability to copy status messages ([57ce030f](https://github.com/qTox/qTox/commit/57ce030f1d19f4a16f309149addc80bed53b8b2d))
> * **systemtray:**  add "Show" action to context menu ([a851a5b1](https://github.com/qTox/qTox/commit/a851a5b18da8c295fba441c817920cf65db2cdbb))
> * **textstyle:**  Change markdown syntax to be more intuitive ([32e48a97](https://github.com/qTox/qTox/commit/32e48a979ca78717a212800547c95ca0f1e67b8f), closes [#3404](https://github.com/qTox/qTox/issues/3404), breaks [#](https://github.com/qTox/qTox/issues/))
> ```

No issue number is specified here, it just says "breaks #", where the # links to the issues page.

---

_[CHANGELOG.md, line 82 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl1AetFaKto4DFn2yg:-KOl1AeupbYydZfCOiXR:bjtdlsw) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L82)):_

> ``` Markdown
>   *  add setting for 120p very-low-res video ([6045ced3](https://github.com/qTox/qTox/commit/6045ced3f8b538b0c3044370878d4feb76103480))
> * **videomode:**  Added possible video shift ([fd701df1](https://github.com/qTox/qTox/commit/fd701df1012763cba98bbfbbf7bf9ccd898f1c03))
> * **widget:**  Disable sound notification for `busy` status ([e7785ab4](https://github.com/qTox/qTox/commit/e7785ab4c2790b2c10b33c416bc78ad23a16cc63), breaks [#](https://github.com/qTox/qTox/issues/))
> ```

No issue number is specified here, it just says "breaks #", see above.

---

_[CHANGELOG.md, line 121 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl1qBRR08EYcbxfkim:-KOl1qBRR08EYcbxfkin:bfmq7h3) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L121)):_

> ``` Markdown
> * **chattextedit.cpp:**  fix drag-and-drop to be consistent across systems ([70fc247b](https://github.com/qTox/qTox/commit/70fc247b7092b0bd320b3a59bcaf57d896257da8))
> * **contentdialog, widget:**  Remove "new message" bar after reading message ([b2c1f468](https://github.com/qTox/qTox/commit/b2c1f468946aff73b23fb9ac6539331f6c0c7fbe))
> * **corevideosource:**  Partial revert of ef641ce6d3398792c10b30bf24a81c5a6005fe06 ([b1adef2f](https://github.com/qTox/qTox/commit/b1adef2fd0b9aeef58cea34c6637b8cd3f6e16a8), closes [#3527](https://github.com/qTox/qTox/issues/3527))
> ```

Commit hash should be linked.

---

_[CHANGELOG.md, line 164 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl2QU73OoaI_V_xpil:-KOl2QU73OoaI_V_xpim:b-doso82) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L164)):_

> ``` Markdown
> * **ui:**  Prevent suicide crash on logout ([2bdd9824](https://github.com/qTox/qTox/commit/2bdd9824c758a7ce3ff0cb06fa59ed7d8c81455a), closes [#2480](https://github.com/qTox/qTox/issues/2480))
> * **updater:**  Use module path, not working dir ([0a2e96ab](https://github.com/qTox/qTox/commit/0a2e96ab07a9c0427660124a2f1ff45bec0ba0b8))
> * **video:**
> ```

Technically everything under this section is just the development process for the `VideoFrame` refactor, thus can be simplified to a link to the PR, though it doesn't matter that much I guess.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

_[CHANGELOG.md, line 13 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl-a-FbgvaSpXGqLkk:-KOl363e3FgNRy8lg002:b65iibm) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L13)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> I know this has been marked as a breaking change in the commit, but from a user's perspective, this doesn't seem to have any affect on functionality, nor does it "break" anything in the repository related to the actual source. This is just for consideration for whether this be moved to another section.
> </details>
> This does break the formatting of the text, since what was previously rendered as markdown with "formatting" characters not displayed, now may be rendered wrongly, or not rendered at all.

---

_[CHANGELOG.md, line 77 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl10req_ux7d9hj8Cc:-KOl4MDTKojmf1S6AOoj:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L77)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> No issue number is specified here, it just says "breaks #", where the # links to the issues page.
> </details>
> Fixed.

---

_[CHANGELOG.md, line 82 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl1AetFaKto4DFn2yg:-KOl4N-XVi-N9I0wky86:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L82)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> No issue number is specified here, it just says "breaks #", see above.
> </details>
> Fixed.

---

_[CHANGELOG.md, line 121 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl1qBRR08EYcbxfkim:-KOl4PWOh02N-GdLQ7CS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L121)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Commit hash should be linked.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606)_

**Comment by initramfs** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

_[CHANGELOG.md, line 13 [r4]](https://reviewable.io:443/reviews/qtox/qtox/3606#-KOl-a-FbgvaSpXGqLkk:-KOl695fZIyV3xx4EiP_:btm1tff) ([raw file](https://github.com/qtox/qtox/blob/6107d80b8017598ac45fe63080c53a4916fb34fa/CHANGELOG.md#L13)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> This does break the formatting of the text, since what was previously rendered as markdown with "formatting" characters not displayed, now may be rendered wrongly, or not rendered at all.
> </details>
> Ok. Forgive me, I thought this meant markdown syntax for the documentation (e.g. `MAINTAINING.md`, `CONTRIBUTING.md`, etc). My bad :p

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606)_

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3606#-:-KOlCwSb5CZkoQhWxzhQ:bnfp4nl)_

**Pull request merged**
