### PR TITLE
Time format

### PR DESCRIPTION
**Pull request by Diadlo**
Rebased (and fixed?) #2761

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3774)

### CODE REVIEW

**Comment by zetok** [comment]
Input field is buggy, it probably would be the best to split the space it takes into half, and the right half could be used to display current date format – this way user would have an instant preview how date format would look like, and input filed would only need to display formatting string.

**Comment by zetok** [comment]
@Diadlo re: [IRC](https://github.com/qTox/qtox-irc-logs/blob/master/2016/10/%23qtox_20161002.log.txt#L267,L295)

I didn't mean splitting the input field in half, but rather making input field smaller, "squeezing" it to the left, and removing from it part that is not date formatting. The removed part should go to the right of the input field, showing (preferably in real-time) how formatting string in the input field changes date.

**Comment by sudden6** [comment]
@zetok if I understand you correctly, you mean a preview, similar to [this](https://support.content.office.net/en-us/media/2d9513de-9959-4182-8073-7e7fbcf4158c.jpg)?

**Comment by zetok** [comment]
@sudden6 yep.

**Comment by zetok** [comment]
on c417ae599cc6872a0eb9b53ae0d83047872e8274:
- [x] I've set date, and I can't change it back
  
  spectacle sc4192
  
  Steps:
1. `for n in {1..100000}; do echo $n >> nums ; done`
2. copy numbers quickly in vim to clipboard `:%y+`
3. paste in the date format field
4. input field for date change is gone

**Comment by Diadlo** [comment]
@zetok Fixed

**Comment by sudden6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/userinterfaceform.cpp, line 128 at r4](https://reviewable.io:443/reviews/qtox/qtox/3774#-KTQlSgi5SYeDznsrJIr:-KTQlSgi5SYeDznsrJIs:biqhwxu) ([raw file](https://github.com/qtox/qtox/blob/63da8a09758df8268da5dd1e0ac2282a81c7615f/src/widget/form/settings/userinterfaceform.cpp#L128)):_

> ``` cpp
> 
>     QRegularExpression re(QString("[^\\n]{0,%0}").arg(MAX_FORMAT_LENGTH));
>     QRegularExpressionValidator *validator = new QRegularExpressionValidator(re);
> ```

Memory leak?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3774)_

**Comment by Diadlo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/userinterfaceform.cpp, line 128 at r4](https://reviewable.io:443/reviews/qtox/qtox/3774#-KTQlSgi5SYeDznsrJIr:-KTQvL7d6i0U9gyclhE1:b-886gsx) ([raw file](https://github.com/qtox/qtox/blob/63da8a09758df8268da5dd1e0ac2282a81c7615f/src/widget/form/settings/userinterfaceform.cpp#L128)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Memory leak?
> </details>
> Fixed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3774)_

**Comment by sudden6** [comment]
Reviewed 1 of 3 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3774)_

**Comment by sudden6** [comment]
@zetok assinged to you to retest your issue. Please merge if it works :)

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3774#-:-KTQzEp-xBUnX0iSYmg8:bnfp4nl)_

**Comment by zetok** [comment]
on 10186eeba3c6d23beaa067403eb2091be4783a4d there's still no input field with invalid settings

Edit: settings from .ini

**Comment by zetok** [comment]
Seems to work on 7d7daba158b635cb58e6af0ee5de1dec774979c0

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3774)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3774#-:-KTW3BGS89PQvH4Ul-ne:bnfp4nl)_

**Pull request merged**
