### PR TITLE
docs(README): refactor/improve README.md

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3832)

### CODE REVIEW

**Comment by AliceGrey** [comment]
I really like these changes, it's starting to look much cleaner :thumbsup: 

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-KdERSwfsHnYFx_mE:-KV-KdESbKJ37YLfRGja:bup0zqu) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L1)):_

> ``` Markdown
> qTox [![GPLv3+ license][gplv3-badge]][gplv3-link] [![Travis CI][travis-badge]][travis-link] 
> ```

What if we replaced the qTox text with the logo? It seems a bit redundant to have both.

---

_[README.md, line 14 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-KnR7zm8vUDDJaXDD:-KV-KnR7zm8vUDDJaXDE:bu2rp68) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L14)):_

> ``` Markdown
>  **IRC Channel:** [#qtox@freenode]
> 
> **qTox is a powerful Tox client that follows the Tox design guidelines while
> ```

I think this should probable be moved above the header/list of links

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV-KRi2iEFDjpFvAh8h:bq8j108)_

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-LsUJdmueFyWXty8X:-KV-LsUJdmueFyWXty8Y:b-btobmn) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L57)):_

> ``` Markdown
> 
> 
> Screenshot 01
> ```

What if we made the screenshots smaller in the readme? People could click on them to see a larger version? This would also be more mobile device friendly.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-KdERSwfsHnYFx_mE:-KV-OpTBIILKo2qmL4as:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L1)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> What if we replaced the qTox text with the logo? It seems a bit redundant to have both.
> </details>
> Done.

---

_[README.md, line 14 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-KnR7zm8vUDDJaXDD:-KV-Or1LXWYG7DJbHHXq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L14)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> I think this should probable be moved above the header/list of links
> </details>
> Done.

---

_[README.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-LsUJdmueFyWXty8X:-KV-OujIEcq1RHyh1R52:bblm4ky) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L57)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> What if we made the screenshots smaller in the readme? People could click on them to see a larger version? This would also be more mobile device friendly.
> </details>
> Screenshots are already smaller in readme, and clicking on them shows original size.

Not sure how mobile-friendly it is now, and I don't really HTML.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-KdERSwfsHnYFx_mE:-KV-TjsT9aZpy8oMO4JY:bfb9p44) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L1)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Done.
> </details>
> Could you center the logo, badges and short description(qTox is a powerful..)?

---

_[README.md, line 10 at r2](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-TJOiYx4pMV-hNeu4:-KV-TJOiYx4pMV-hNeu5:b-uc32mm) ([raw file](https://github.com/qtox/qtox/blob/7f0ecb7f82daf71dc63ab72ae0aad21da71e0e17/README.md#L10)):_

> ``` Markdown
> 
>  **[User Manual] |**
>  **[Install] |**
> ```

Should Install be renamed to Install/Build? Considering it has instructions on how to compile it from github.

---

_[README.md, line 64 at r2](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-U2NLrtUDhVpcQ48c:-KV-U2NLrtUDhVpcQ48d:b-l3bin7) ([raw file](https://github.com/qtox/qtox/blob/7f0ecb7f82daf71dc63ab72ae0aad21da71e0e17/README.md#L64)):_

> ``` Markdown
> 
> 
> #### Features
> ```

How would you feel about moving this above the screenshots? Maybe above Help Us?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

_[README.md, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-KdERSwfsHnYFx_mE:-KV-UOZ5oXEGQ1qa1MTM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L1)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> Could you center the logo, badges and short description(qTox is a powerful..)?
> </details>
> Done.

---

_[README.md, line 10 at r2](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-TJOiYx4pMV-hNeu4:-KV-YK_jjZF0OUv-9I2O:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7f0ecb7f82daf71dc63ab72ae0aad21da71e0e17/README.md#L10)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> Should Install be renamed to Install/Build? Considering it has instructions on how to compile it from github.
> </details>
> Done.

---

_[README.md, line 64 at r2](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-U2NLrtUDhVpcQ48c:-KV-XzVdo9LexLLdvz_o:b-xr4qwu) ([raw file](https://github.com/qtox/qtox/blob/7f0ecb7f82daf71dc63ab72ae0aad21da71e0e17/README.md#L64)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> How would you feel about moving this above the screenshots? Maybe above Help Us?
> </details>
> I'm not sure if that's a good idea. Visual stuff (screenshots) are kinda way more appealing than long list of features when it comes to evaluating something at first sight.

If not for the need to get more people helping qTox, screenshots should be just below downloads, and rest of stuff below them. Same reason why `Features` are below `Help us`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[README.md, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-LsUJdmueFyWXty8X:-KV-ZluPuTQ3dO-JVWwv:b3sauqx) ([raw file](https://github.com/qtox/qtox/blob/1443d1fa58c37c51fb922fcbfdfd51522d6b932e/README.md#L57)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Screenshots are already smaller in readme, and clicking on them shows original size.
> 
> Not sure how mobile-friendly it is now, and I don't really HTML.
> </details>
> Ok I guess it's ok for now.

---

_[README.md, line 64 at r2](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-U2NLrtUDhVpcQ48c:-KV-ZSjO5ilkGTPzti1k:b32w1t) ([raw file](https://github.com/qtox/qtox/blob/7f0ecb7f82daf71dc63ab72ae0aad21da71e0e17/README.md#L64)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> I'm not sure if that's a good idea. Visual stuff (screenshots) are kinda way more appealing than long list of features when it comes to evaluating something at first sight.
> 
> If not for the need to get more people helping qTox, screenshots should be just below downloads, and rest of stuff below them. Same reason why `Features` are below `Help us`.
> </details>
> Ok

---

_[README.md, line 35 at r3](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-_TobGqc1caE02Di7:-KV-_TobGqc1caE02Di8:bhqvo0p) ([raw file](https://github.com/qtox/qtox/blob/252fdcebef7b2582d551abdbc0f12199b787b527/README.md#L35)):_

> ``` Markdown
> Windows | Linux | OS X | FreeBSD
> --------|-------|------|--------
> **[64 bit installer]**, [signature][sig-64] | **[CentOS, Debian, Fedora, openSUSE, Ubuntu]** | **[Building instructions]** | **[Port]**
> ```

It looks like there is also an Arch build 64bit on the opensuse page. Maybe instead of listing them all you could have two links; Binaries(which takes you to opensuse and Building Instructions(which takes you to the building instructions).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 35 at r3](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV-_TobGqc1caE02Di7:-KV-bAxDM37nCxbIRmbj:b26hwhp) ([raw file](https://github.com/qtox/qtox/blob/252fdcebef7b2582d551abdbc0f12199b787b527/README.md#L35)):_

> It looks like there is also an Arch build 64bit on the opensuse page.

Yeah, it's not listed in readme since it would be more bothersome for user to use it than just following instructions in INSTALL.md, which consist of using the package manager.

> Maybe instead of listing them all you could have two links; Binaries(which takes you to opensuse and Building Instructions(which takes you to the building instructions).

Given the above, not really.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[README.md, line 57 at r4](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV1c-6OKVMwi_aCyOpg:-KV1c-6Ptw4T1BQULuwg:b-yb6024) ([raw file](https://github.com/qtox/qtox/blob/1d4ee66b0091c5f75aaf4caccc1dc803f4bb5cfb/README.md#L57)):_

> ``` Markdown
> * Spread the good word about qTox to make it more popular :smile:
> * Have an opinion? Make sure to [voice it in the issues that need it] :wink:
> * Fixing [easy issues]
> ```

I think you could combine a few lines into this one, something like: Fixing [easy issues] or [issues that need help]  make sure to read [Contributing] first though ;)
You could then delete [Coding] and If you want to contribute.... because they are a redundant.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by Diadlo** [comment]
Wow! It makes readme realy better :)
1. `q` in logo of qTox seems slimsy to me
2. Long header links "overflow" line. Better split it on 2 ~equal lines or remove something
3. `Help us`, `Screenshots`, `Features`, `Organizational stuff` has different font
4. Table hasn't titile. We should add something above `Bold options are recommended`

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV1e2FSdGVmE3P_lnvT:b4ln3b1)_

**Comment by Diadlo** [comment]
3. `Help us`, `Screenshots`, `Features`, `Organizational stuff` has different font
4. Table hasn't titile. We should add something above `Bold options are recommended`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV1hDReLcjCHD0fD1Dc:bsmvnrk)*

**Comment by zetok** [comment]
> Better split it on 2 ~equal lines or remove something

Err, I did want to remove stuff from the header in the other PR >.<

So, time to finally remove `Help us` from it? :D

> `Help us`, `Screenshots`, `Features`, `Organizational stuff` has different font

`Help us` for visibility should IMO have bigger font than other things.. is it bad?

> Table hasn't titile. We should add something above `Bold options are recommended`

Is title really needed, given that it's quite obvious what the table is about?

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 57 at r4](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV1c-6OKVMwi_aCyOpg:-KV1ig9lCoize_spJaVs:bo3vl6y) ([raw file](https://github.com/qtox/qtox/blob/1d4ee66b0091c5f75aaf4caccc1dc803f4bb5cfb/README.md#L57)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> I think you could combine a few lines into this one, something like: Fixing [easy issues] or [issues that need help]  make sure to read [Contributing] first though ;)
> You could then delete [Coding] and If you want to contribute.... because they are a redundant.
> </details>
> Thanks, done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV1gwlagyeRT2oQCegT:bkp8n12)_

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 57 at r4](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV1c-6OKVMwi_aCyOpg:-KV1ndbk7sl1ZRWfBq5m:b-gj4kyk) ([raw file](https://github.com/qtox/qtox/blob/1d4ee66b0091c5f75aaf4caccc1dc803f4bb5cfb/README.md#L57)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Thanks, done.
> </details>
> I'd change the ;) to :wink: just to be consistent. That's my bad.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 57 at r4](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV1c-6OKVMwi_aCyOpg:-KV1oNAm2odfxe4gZlYo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1d4ee66b0091c5f75aaf4caccc1dc803f4bb5cfb/README.md#L57)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> I'd change the ;) to :wink: just to be consistent. That's my bad.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by AliceGrey** [comment]
Yes this PR is now the correct time to remove things from the header :smile: , we could remove Translate since you added the translation badge. 

IMO the header fonts should all be the same regardless of importance. 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV1tMdFS4wlHykSSzvQ:b-wvjqg9)_

**Comment by Diadlo** [comment]
> So, time to finally remove Help us from it? :D

M.... No?)

> Help us for visibility should IMO have bigger font than other things.. is it bad?

I think all titiles should be one size

> Is title really needed, given that it's quite obvious what the table is about?

I think that not enough is strictly heading for visual separation

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV1s9R2IP-Ux2CGxwdv:bmpz5kb)_

**Comment by zetok** [comment]
Made all `###headers` to be equally sized and removed `Translate` from the header.

With added header to the table it looks ~ugly: https://github.com/zetok/qTox/blob/c8baee326411fb876ed76befc9cc96d2bd9e3f1b/README.md

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV1vT__YjlkeBWeWmk1:b3dz0sv)_

**Comment by Diadlo** [comment]
1. Here still not enough place to put all links in one line :(
2. About table header. LGTM, but leave it on your opinion

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV22V_YQjw7jIlyVldS:bs31su)_

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV233wvbLv6v6mEOfs9:bbgbi7g) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_

> ``` Markdown
>  **[Jenkins builds] |**
>  **[Mailing list] |**
>  **IRC Channel:** [#qtox@freenode]
> ```

Maybe change on **[IRC Channel]** ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by zetok** [comment]
> Here still not enough place to put all links in one line :(

We can always remove `Help us` from the header ;P

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV23qz4g-e6ySxRiOO4:b-vtibs6) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Maybe change on **[IRC Channel]** ?
> </details>
> Link opens the `#qtox` channel in freenode's web client, and this is fine for people who don't really IRC, and just want to get onto this thing.

For people who use dedicated IRC clients, having only a "hidden" link is kinda an unpleasant thing – they have to ~manually check where link leads to, and extract that info from the link to join the channel. Painful & slow. For them info `#qtox @ freenode` (without any link) is ~all that they need to join & enjoy. Since they're usually interested in FOSS, it's quite likely that they are already on freenode, which makes joining the channel as easy & fast as `/j #qtox` when they see this clearly visible info.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV25D2eRUsWBCfPoeTR:bi31e7t)_

**Comment by Diadlo** [comment]
If @AliceGrey and @sudden6 don't mind -- remove it

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV2CS52tpURBt8LkcUM:b-lcnbt0)_

**Comment by AliceGrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV2KLiNZrR36nqbBSj3:b-rhqqcg) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Link opens the `#qtox` channel in freenode's web client, and this is fine for people who don't really IRC, and just want to get onto this thing.
> 
> For people who use dedicated IRC clients, having only a "hidden" link is kinda an unpleasant thing – they have to ~manually check where link leads to, and extract that info from the link to join the channel. Painful & slow. For them info `#qtox @ freenode` (without any link) is ~all that they need to join & enjoy. Since they're usually interested in FOSS, it's quite likely that they are already on freenode, which makes joining the channel as easy & fast as `/j #qtox` when they see this clearly visible info.
> </details>
> What if we just had the link? It's pretty self explanitory that it's an irc.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by AliceGrey** [comment]
I'm ok with removing Help Us. I really like the new install link table but I feel it could be smaller or more space concious. There are multiple empty cells that seem useless. Maybe Combine 64bit and 32Bit portable? Have it be one row and put Gentoo (x64) and Other(x32). It would save space and make Help Us more visible by being closer to the top.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV2L4tzqejtg_-BmzNj:bot0hpg)_

**Comment by zetok** [comment]
Removed `Help us` and combined portables "together".

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV3oOArW63WD7_rHEsk:ber0i9r) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> What if we just had the link? It's pretty self explanitory that it's an irc.
> </details>
> I've removed `Channel`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV3pYuigm4Ad54eX3Ut:b-yhc580)_

**Comment by sudden6** [comment]
I'm ok with removing "Help us" with this layout, as the paragraph is now better separated and more on the top.

The thing I don't really like is the table with the installers, maybe we should just put the recommended stuff there and move other builds and compiling to the bottom.

**Comment by zetok** [comment]
> The thing I don't really like is the table with the installers, maybe we should just put the recommended stuff there and move other builds and compiling to the bottom.

Feel free to make that change in a separate PR & enjoy people who are dissatisfied with things they want to get being hidden.

Been there, done ~that (moved to INSTALL.md), wouldn't recommend.

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV6YGs5kOK_HJ7P87uT:b-8zt4k6) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> I've removed `Channel`.
> </details>
> Can you center links? And it will be LGTM

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV6mtVItiJUN-M3DVIf:b-r8m3wf) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Can you center links? And it will be LGTM
> </details>
> I _could_, but it would require rewriting it in ugly HTML, like it's done with the badges.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV6oyILUh4j6z4ZXM_E:bo99m0p) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> I _could_, but it would require rewriting it in ugly HTML, like it's done with the badges.
> </details>
> please no HTML

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832)_

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 30 at r6](https://reviewable.io:443/reviews/qtox/qtox/3832#-KV233wugk-3BreRJJlC:-KV6r4gnA-ThjHN7GpqT:b-816nmq) ([raw file](https://github.com/qtox/qtox/blob/8174c764a2354a18ed379960a728d10d46a821c0/README.md#L30)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> please no HTML
> </details>
> Sadly

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV6r9FK1tjG5CQ_WUwg:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3832#-:-KV6upuuBGE59UuuuNdZ:bnfp4nl)_

**Pull request merged**
