### PR TITLE
fix(chatform): include pressed key(s) when changing focus

### PR DESCRIPTION
**Pull request by anthonybilinski**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5054)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
I noticed this logic is basically identical to `GenericChatForm::eventFilter` which we install on a couple of the child elements of `GenericChatForm`. Could this be deduplicated? I don't really understand when to use ::event vs ::eventFilter..

**Comment by sudden6** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/widget/form/genericchatform.cpp, line 314 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5054#-L9MYEmf-3W0PSR05MnE:-L9MYEmg-UPum2AUCYXD:b-8inc68) ([raw file](https://github.com/qtox/qtox/blob/74c91a203cfcf48bcccdab6104c7244f98c55284/src/widget/form/genericchatform.cpp#L314)):*
> ```cpp
> {
>     // If the user accidentally starts typing outside of the msgEdit, focus it automatically
>     if (e->type() == QEvent::KeyPress) {
> ```

I didn't test, but I think removing `&& !msgEdit->hasFocus()` from the condition could steal all the events when typing a message?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5054)*

**Comment by sudden6** [comment]
According to http://doc.qt.io/archives/qt-4.8/eventsandfilters.html

events seem to be for implementing events that reached a widget and event filters allow you to intercept any event from any widget, IMO the tooltip example is very good.

**Comment by anthonybilinski** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/form/genericchatform.cpp, line 314 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5054#-L9MYEmf-3W0PSR05MnE:-L9Mghgh-WQpzj0X5kzH:barym46) ([raw file](https://github.com/qtox/qtox/blob/74c91a203cfcf48bcccdab6104c7244f98c55284/src/widget/form/genericchatform.cpp#L314)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I didn't test, but I think removing `&& !msgEdit->hasFocus()` from the condition could steal all the events when typing a message?
</blockquote></details>

the only events I saw GeneralChatForm getting when msgEdit has focus was escape key, all other typed keys only were received by msgEdit.
I removed it because I noticed we weren't checking searchForm for focus, so looked into adding that into the check, before realizing neither seems to have an effect.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5054)*

**Comment by sudden6** [comment]
:lgtm_strong: then

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5054#-:-L9Mv2PY2_ALQaKI6Ag9:b1hmrgw)*

**Pull request merged**
