### PR TITLE
chore(tools): replace unsafe signing C++ code with Rust

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4028)

### CODE REVIEW

**Comment by zetok** [comment]
cc @tux3

**Comment by sudden6** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis/build-rust.sh, line 40 at r1](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_EMhtOrzt9Lb4YOFmy:-K_EMhtPA3DeA6td7AI5:b6vw3r3) ([raw file](https://github.com/qtox/qtox/blob/3921a4cc666b612074edfc20f0aee6f89b091461/.travis/build-rust.sh#L40)):*
> ```Shell
> 
>     git clone https://github.com/jedisct1/libsodium.git libsodium
>         --branch 1.0.11 \
> ```

make the version a variable

---

*[.travis/build-rust.sh, line 46 at r1](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_EMp2yO57_YZzrMmic:-K_EMp2zUXr1RdGR-p45:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/3921a4cc666b612074edfc20f0aee6f89b091461/.travis/build-rust.sh#L46)):*
> ```Shell
>     ./autogen.sh
>     ./configure && make -j$(nproc)
>     sudo checkinstall --install --pkgname libsodium --pkgversion 1.0.11 --nodoc -y
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028)*

**Comment by zetok** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis/build-rust.sh, line 40 at r1](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_EMhtOrzt9Lb4YOFmy:-K_EQGzdnwpe1V2oAVr1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3921a4cc666b612074edfc20f0aee6f89b091461/.travis/build-rust.sh#L40)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

make the version a variable
</blockquote></details>

Done.

---

*[.travis/build-rust.sh, line 46 at r1](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_EMp2yO57_YZzrMmic:-K_EQHPYWJl6x9Bn_Gt0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3921a4cc666b612074edfc20f0aee6f89b091461/.travis/build-rust.sh#L46)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028)*

**Comment by sudden6** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/update-server/qtox-updater-sign/src/main.rs, line 55 at r2](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_Ovne_VNblMEkrl0st:-K_Ovneaj0_Vc1HnYKyr:bhrdpzb) ([raw file](https://github.com/qtox/qtox/blob/fa3f0cd44189d4f85a8beb74d49a540aac510bc1/tools/update-server/qtox-updater-sign/src/main.rs#L55)):*
> ```Rust
> 
>     SecretKey::from_slice(&skey_bytes[..SECRETKEYBYTES])
>         .expect("Failed to get right amout of bytes for SecretKey")
> ```

typo: amount

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028)*

**Comment by zetok** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[tools/update-server/qtox-updater-sign/src/main.rs, line 55 at r2](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_Ovne_VNblMEkrl0st:-K_Oy1G_ZiW1JeMac-xK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fa3f0cd44189d4f85a8beb74d49a540aac510bc1/tools/update-server/qtox-updater-sign/src/main.rs#L55)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo: amount
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028)*

**Comment by tux3** [comment]
LGTM

**Comment by sudden6** [comment]
Reviewed 3 of 9 files at r1, 2 of 2 files at r2.
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/update-server/qtox-updater-sign/README.md, line 5 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_QtcJDazoonYLUt5Ey:-K_QtcJEhNg4wD0WR_kO:bemreff) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/README.md#L5)):*
> ```Markdown
> Simple program for signing releases.
> 
> Requires file named `qtox-updater-skey` in workign directory that contains
> ```

`Requires a file`
typo: working

---

*[tools/update-server/qtox-updater-sign/README.md, line 6 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_QtijISOrVXzPzOYSF:-K_QtijJdNmOQohjmVWs:btvd3yj) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/README.md#L6)):*
> ```Markdown
> 
> Requires file named `qtox-updater-skey` in workign directory that contains
> secret key.
> ```

the secret key.

---

*[tools/update-server/qtox-updater-sign/README.md, line 8 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_Qtn7cwGNqsn9ZmYpZ:-K_Qtn7dLTTi_oioguIh:b-fyjnyr) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/README.md#L8)):*
> ```Markdown
> secret key.
> 
> To sign release, either supply name of the data to be signed as an argument,
> ```

`To sign the release`
`supply the name of the file to`

---

*[tools/update-server/qtox-updater-sign/src/main.rs, line 31 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_Qwph3WS_EiWFjIof2:-K_Qwph4zd3EkpMajCDt:b-eygllb) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/src/main.rs#L31)):*
> ```Rust
> const SKEY_FNAME: &'static str = "qtox-updater-skey";
> 
> /// if there is more than just program name in args, treat "1st" arg as a
> ```

`just the program name`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028)*

**Comment by zetok** [comment]
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[tools/update-server/qtox-updater-sign/README.md, line 5 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_QtcJDazoonYLUt5Ey:-K_SgA1LU24LKBAAaGYR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/README.md#L5)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`Requires a file`
typo: working
</blockquote></details>

Done.

---

*[tools/update-server/qtox-updater-sign/README.md, line 6 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_QtijISOrVXzPzOYSF:-K_SgBDOc4eaMEYQcNfG:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/README.md#L6)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

the secret key.
</blockquote></details>

Done.

---

*[tools/update-server/qtox-updater-sign/README.md, line 8 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_Qtn7cwGNqsn9ZmYpZ:-K_SgG8FY2JcpeQUOX24:b-g07ezx) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/README.md#L8)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`To sign the release`
`supply the name of the file to`
</blockquote></details>

~Done.

---

*[tools/update-server/qtox-updater-sign/src/main.rs, line 31 at r3](https://reviewable.io:443/reviews/qtox/qtox/4028#-K_Qwph3WS_EiWFjIof2:-K_SgQCzqNOmUPNEMY2h:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5b207f2b453c4c36b15876f976b5641fc6d77407/tools/update-server/qtox-updater-sign/src/main.rs#L31)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`just the program name`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028)*

**Comment by sudden6** [comment]
:lgtm: 

---

Reviewed 2 of 9 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028#-:-K_U9_e5-WGsqxydXADC:bg7igkv)*

**Comment by zetok** [comment]
@sudden6 changed according to @tux3's feedback.

**Comment by tux3** [comment]
I've tested and can confirm that the current version works correctly.

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4028#-:-K_VIgmQTAVGFrBstb5T:bnfp4nl)*

**Pull request merged**
