### PR TITLE
Rename from toxgui to qtox

### PR DESCRIPTION
**Pull request by Ansa89**

### CODE REVIEW

**Comment by tux3** [comment]
I need to make sure it won't break everything (scripts, etc) and I'll merge it.

**Comment by dubslow** [comment]
It doesn't affect anything in this repository on Linux (and presumably at least OS X if not Windows as well). I don't know how it would effect (e.g.) Jenkins.

**Comment by Ansa89** [comment]
Where can I find jenkins' build script?
I would check it.

**Comment by tux3** [comment]
It did break Jenkins, and I don't think you can access the scripts publicly. Talk to Nikolai Toryzin on IRC.

**Comment by Ansa89** [comment]
@nurupo said he fixed build script on jenkins.

**Comment by tux3** [comment]
That's wonderful.

**Comment by dubslow** [comment]
This and its duplicate #154 can be closed.

**Pull request closed without merging**
