### PR TITLE
Fix incorrect headers order for windows builds

### LINKED ISSUE #4220: Windows nightlies error (again)
On build.tox.chat:
```
In file included from src/platform/camera/directshow.cpp:25:0:
/usr/share/mingw-w64/include/amvideo.h:1518:5: error: ‘REFERENCE_TIME’ does not name a type
     REFERENCE_TIME AvgTimePerFrame;
     ^
/usr/share/mingw-w64/include/amvideo.h:1526:5: error: ‘REFERENCE_TIME’ does not name a type
     REFERENCE_TIME AvgTimePerFrame;
     ^
/usr/share/mingw-w64/include/amvideo.h:1547:5: error: ‘REFERENCE_TIME’ does not name a type
     REFERENCE_TIME AvgTimePerFrame;
     ^
In file included from src/platform/camera/directshow.cpp:28:0:
/usr/share/mingw-w64/include/dvdmedia.h:31:5: error: ‘REFERENCE_TIME’ does not name a type
     REFERENCE_TIME AvgTimePerFrame;
     ^
```

### PR DESCRIPTION
**Pull request by DX37**
Fixes #4220.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4257)

### CODE REVIEW

**Comment by sudden6** [comment]
Interesting does the include order matter for windows?

Can you wrap the parts where the order matters in `// clang-format off` and `// clang-format on` blocks, so they won't get reodered by `clang-format`? Also please add a comment that the order matters there.

**Comment by DX37** [comment]
Updated.

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/autoupdate.cpp, line 38 at r1](https://reviewable.io:443/reviews/qtox/qtox/4257#-KfWayyjMDmCLYdUNqj6:-KfWayyk6PnN_ocUGtDq:br91hgk) ([raw file](https://github.com/qtox/qtox/blob/e70b6ae484a9a3e4a9eb0438516bbffc1530c2ab/src/net/autoupdate.cpp#L38)):*
> ```cpp
> 
> #ifdef Q_OS_WIN
> // Because of replacing to incorrect order, which leads to building failing, this region is ignored for clang-format
> ```

Please reformat to <100 columns like in our Coding Standard https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks

---

*[src/platform/camera/directshow.cpp, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4257#-KfWbEp83bsCzZTjyJEe:-KfWbEp9sU-rF0HofufA:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/e70b6ae484a9a3e4a9eb0438516bbffc1530c2ab/src/platform/camera/directshow.cpp#L24)):*
> ```cpp
> #include "directshow.h"
> 
> // Because of replacing to incorrect order, which leads to building failing, this region is ignored for clang-format
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4257)*

**Comment by DX37** [comment]
Okay, fixed.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4257#-:-KfWhWSq5Va1Fqd2bqt5:b-jbsf8z)*

**Comment by DX37** [comment]
@sudden6 Is there exists an advanced debug for qTox? Like previously successful build №1040, it's not starting on Windows at all... Just loading animation above cursor and that's all.

**Comment by sudden6** [comment]
@DX37 you can run it from the commandline and look at the debug output

**Comment by DX37** [comment]
@sudden6 Well, it did not work. I tried to run the compiled and downloaded client in different consoles - no output. And if I run MSYS2 from the console, from where I built the client, it just freezes, not even launching the login form. And I have to press Ctrl+C.
The last stable version is not affected by this.

**Comment by sudden6** [comment]
If it's not even getting to the login form then there's something very wrong with the build. The best way to solve this is probably to contact `nurupo` or `tux3` in our IRC channel.

**Pull request merged**
