### PR TITLE
Update translations from Weblate

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3923)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, 24 of 24 files at r10.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[translations/ar.ts, line 2223 at r10](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgeOmrduMoPf9U3AVG:-KXgeOmsrrxrzdEGLBas:bfpdort) ([raw file](https://github.com/qtox/qtox/blob/9861b3d1ebd9ab777de4edb3433bf1afece7f14f/translations/ar.ts#L2223)):*
> ```XML
>     <message>
>         <source>Are you sure you want to remove %1 from your contacts list?</source>
>         <translation>هل انت متأكد من ازالة %1 من جهات الاتصال ؟</translation>
> ```

s/1%/%1/

---

*[translations/bg.ts, line 1490 at r10](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgg3Pn-QMwsLlitD9_:-KXgg3Podkhr5bYo5XEC:b-39oxmp) ([raw file](https://github.com/qtox/qtox/blob/9861b3d1ebd9ab777de4edb3433bf1afece7f14f/translations/bg.ts#L1490)):*
> ```XML
>         <source>Change profile password</source>
>         <translation type="unfinished"></translation>
>     </message>
> ```

Also `sed -i -e 's/1%/%1/' translations/bg.ts`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3923)*

**Comment by zetok** [comment]
Review status: 34 of 36 files reviewed at latest revision, 2 unresolved discussions.

---

*[translations/ar.ts, line 2223 at r10](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgeOmrduMoPf9U3AVG:-KXgqNNOM5neyHwBig8K:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9861b3d1ebd9ab777de4edb3433bf1afece7f14f/translations/ar.ts#L2223)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

s/1%/%1/
</blockquote></details>

Done.

---

*[translations/bg.ts, line 1490 at r10](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgg3Pn-QMwsLlitD9_:-KXgqOOg_zdn21m4N3vm:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9861b3d1ebd9ab777de4edb3433bf1afece7f14f/translations/bg.ts#L1490)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Also `sed -i -e 's/1%/%1/' translations/bg.ts`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3923)*

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[translations/ar.ts, line 2223 at r10](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgeOmrduMoPf9U3AVG:-KXgqRuR-IPpp_Iybkgb:b-ogfj3n) ([raw file](https://github.com/qtox/qtox/blob/9861b3d1ebd9ab777de4edb3433bf1afece7f14f/translations/ar.ts#L2223)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hm... Nope?

---

*[translations/ar.ts, line 32 at r11](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgqDnONAGC9R9QKLqc:-KXgqDnONAGC9R9QKLqd:bv78i56) ([raw file](https://github.com/qtox/qtox/blob/50f6c40d0586e2c06ed21949ef14447ea640130d/translations/ar.ts#L32)):*
> ```XML
>     <message>
>         <source>Screen %1</source>
>         <translation>الشاشة %1</translation>
> ```

Nope :)
s/1%/%1/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3923)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[translations/ar.ts, line 32 at r11](https://reviewable.io:443/reviews/qtox/qtox/3923#-KXgqDnONAGC9R9QKLqc:-KXgrvNLyp90t_vy08py:b-lbf3e2) ([raw file](https://github.com/qtox/qtox/blob/50f6c40d0586e2c06ed21949ef14447ea640130d/translations/ar.ts#L32)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Nope :)
s/1%/%1/
</blockquote></details>

That's just how reviewable shows it. `sed` did its job :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3923)*

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3923#-:-KXgsVS0zWMT8zMmrqJf:bnfp4nl)*

**Comment by zetok** [comment]
rebased

**Comment by Diadlo** [comment]
:lgtm_strong: :

---

Reviewed 1 of 1 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3923#-:-KXh1b0kGGVlZl561kqy:b-yncq55)*

**Pull request merged**
