### PR TITLE
Friend widget 4

### PR DESCRIPTION
**Pull request by Diadlo**
Next step of ui/redesign merge (Done 13%)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4050)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/friendlistwidget.cpp, line 707 at r1](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_iCOdM3rxegMzHJbIm:-K_iCOdM3rxegMzHJbIn:bwbm0yg) ([raw file](https://github.com/qtox/qtox/blob/aa3ab019bf4dec79a0fb59df14f94eb56430a392/src/widget/friendlistwidget.cpp#L707)):*
> ```cpp
>         QDate activityDate = getDateFriend(contact);
>         Time time = getTime(activityDate);
>         QWidget *w = activityLayout->itemAt(time)->widget();
> ```

* follows type, same throughout the diff

---

*[src/widget/friendlistwidget.h, line 84 at r1](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_iCLmFNmDCJAmHU5Tx:-K_iCLmFNmDCJAmHU5Ty:bipkshf) ([raw file](https://github.com/qtox/qtox/blob/aa3ab019bf4dec79a0fb59df14f94eb56430a392/src/widget/friendlistwidget.h#L84)):*
> ```objc
>     CircleWidget* createCircleWidget(int id = -1);
>     QLayout* nextLayout(QLayout* layout, bool forward) const;
>     void moveFriends(QLayout *layout);
> ```

* follows type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4050)*

**Comment by Diadlo** [comment]
Review status: 0 of 80 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/friendlistwidget.cpp, line 707 at r1](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_iCOdM3rxegMzHJbIm:-K_nRyqySTwqnpkPhHLe:biylfwa) ([raw file](https://github.com/qtox/qtox/blob/aa3ab019bf4dec79a0fb59df14f94eb56430a392/src/widget/friendlistwidget.cpp#L707)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

* follows type, same throughout the diff
</blockquote></details>

Fixed not only throughout the diff :)

---

*[src/widget/friendlistwidget.h, line 84 at r1](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_iCLmFNmDCJAmHU5Tx:-K_nS3Wt0K7PZlWOEipR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/aa3ab019bf4dec79a0fb59df14f94eb56430a392/src/widget/friendlistwidget.h#L84)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

* follows type
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4050)*

**Comment by sudden6** [comment]
There were not all instances of wrong formatting fixed, but I'll :lgtm_strong: anyway because since it's not worth holding back this PR any longer.

---

Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 78 of 78 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/friendwidget.h, line 46 at r3](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_nkq8cK3r4L04FbCy3:-K_nkq8cK3r4L04FbCy4:b5tp26m) ([raw file](https://github.com/qtox/qtox/blob/44388e202b37d6def02c0cb2286bca2b53775ee0/src/widget/friendwidget.h#L46)):*
> ```objc
>     void removeFriend(int friendId);
>     void copyFriendIdToClipboard(int friendId);
>     void contextMenuCalled(QContextMenuEvent * event);
> ```

strange formatting

---

*[src/widget/gui.cpp, line 279 at r3](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_nl4Bw5JWWSKGeiYze:-K_nl4Bw5JWWSKGeiYzf:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/44388e202b37d6def02c0cb2286bca2b53775ee0/src/widget/gui.cpp#L279)):*
> ```cpp
> QString GUI::itemInputDialog(QWidget*  parent, const QString & title,
>                     const QString & label, const QStringList & items,
>                     int current, bool editable, bool * ok,
> ```

same

---

*[src/widget/gui.cpp, line 400 at r3](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_nl6EluvfycWSWb7iA:-K_nl6EluvfycWSWb7iB:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/44388e202b37d6def02c0cb2286bca2b53775ee0/src/widget/gui.cpp#L400)):*
> ```cpp
> QString GUI::_itemInputDialog(QWidget*  parent, const QString & title,
>                               const QString & label, const QStringList & items,
>                               int current, bool editable, bool * ok,
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4050#-:-K_nmv5RN4LnxVQU4Cbk:b9lpsu0)*

**Comment by Diadlo** [comment]
Review status: 76 of 80 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/widget/friendwidget.h, line 46 at r3](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_nkq8cK3r4L04FbCy3:-K_pB9BRX5-DbvJSVBVZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/44388e202b37d6def02c0cb2286bca2b53775ee0/src/widget/friendwidget.h#L46)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

strange formatting
</blockquote></details>

Done.

---

*[src/widget/gui.cpp, line 279 at r3](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_nl4Bw5JWWSKGeiYze:-K_pAuUEQRRIa9-sFyCH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/44388e202b37d6def02c0cb2286bca2b53775ee0/src/widget/gui.cpp#L279)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[src/widget/gui.cpp, line 400 at r3](https://reviewable.io:443/reviews/qtox/qtox/4050#-K_nl6EluvfycWSWb7iA:-K_pAusq0GdthvNAqG21:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/44388e202b37d6def02c0cb2286bca2b53775ee0/src/widget/gui.cpp#L400)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4050)*

**Pull request merged**
