### PR TITLE
fix(core): Adapt qtox to new conferences state change callback.

### PR DESCRIPTION
**Pull request by Diadlo**
Patch from TokTok/qTox#7
Thanks @iphydf

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4953)

### CODE REVIEW

**Comment by tox-user** [comment]
Last time I tested it, it was broken. Has anything changed?

**Comment by Diadlo** [comment]
@tox-user AFAIK you tested TokTok/qTox
Not sure, that this change itself broke something

**Comment by Diadlo** [comment]
@tox-user AFAIK you tested TokTok/qTox
Not sure, that this change itself broke something

**Comment by tox-user** [comment]
The problem was with this PR + persistent group chats. This PR itself without persistent conferences causes segmentation fault on exit when you are in group chat.

Steps to reproduce:
1. Join group chat.
2. Exit qTox.
3. Notice the segmentation fault in the log.

The problem is either caused by this PR or by toxcore 0.2.0.

**Comment by Diadlo** [comment]
It's strange. I tried it with self created empty group and with group with another person, but haven't segfault (master toxcore was used)

**Pull request closed without merging**
