### PR TITLE
Friend widget 4 (final)

### PR DESCRIPTION
**Pull request by Diadlo**
~It's the final countdown~
Remove FriendWidget from Friend class

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4099)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4099)*

**Comment by sudden6** [comment]
briefly tested it, :lgtm_strong: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4099#-:-KbbZCUm2TA8BMDpuaak:b-sufxk2)*

**Comment by zetok** [comment]
on c6824b1c0cce3ae0629e342e4f0e8da8f614765e

- [x] regression: friend's status message is no longer displayed in the chatform
spectacle sj4225

**Comment by Diadlo** [comment]
@zetok Should be fixed

**Comment by zetok** [comment]
on 0e67393e34237f4b41ab1d4c11201c71b75512a3:

- [x] regression: status message in chatform is truncated in the wrong place
spectacle wrw526
PR
—
old

**Comment by zetok** [comment]
PR needs to be rebased, since there are now some conflicts.

**Comment by Diadlo** [comment]
@zetok Rebased and fixed

**Comment by zetok** [comment]
seems to work on bff25ce, :lgtm_strong:

---

Review status: 2 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4099#-:-KdbmONgsVH0cbCJuIFJ:b-d4dlwe)*

**Pull request merged**
