### PR TITLE
Added a context menu item to copy a friend's public key

### PR DESCRIPTION
**Pull request by alexbakker**
There were some requests for this in #tox. I think this is an important thing to have.

### CODE REVIEW

**Comment by towlie** [comment]
This was removed because it confuses users. So why do you reimplement this? (Publiic key != Tox ID)
Toxcore is not designed to share Tox IDs

**Comment by alexbakker** [comment]
The reason it was confusing before was because it said "Copy tox id" which is why I made it say "Copy public key". If a user wants to know a friend's public key you can't expect them to extract the public key from the save file themselves.

**Comment by ProMcTagonist** [comment]
> If a user wants to know a friend's public key

I can't imagine this ever happening for the vast majority of our target users. This will be even more confusing than before, because everyone will respond to confused users with "That's the public key, not the ID," and make them feel like they should have known that, when they were introduced to Tox with the premise that it's configurationless and crypto for everyone.

It would be better to adopt the protocol extension that @subliun is cooking up for Antox, with an opt out.

**Comment by alexbakker** [comment]
I'm not saying it should be this way forever. But while subliun's protocol extension is still cooking I think we should at least provide this option for now. We can remove it later when someone comes up with a better solution.

**Comment by tux3** [comment]
I don't see the point though, why would someone want to copy the public key? There's not much you can do with it, and it's easy to confuse it with a Tox ID.

**Comment by alexbakker** [comment]
Say you have 2 people in your friend list with the same name, the same status message and the same avatar. How can you tell who's the impostor?

**Comment by TheNain38** [comment]
There should also be a way to know when someone changes it's name, and what name it was before he changes

**Comment by tux3** [comment]
@Impyy 
The simple solution would be to remove both, and re-add your friend. You need to know your friend's Tox ID anyways if you want to confirm its identity.

Technically you could also notice that one of your friend "disappeared", so the attacker would blow its cover immediately, and the order of the friend list corresponds to the order you added people in (unless you move people around) so you would know who's who if you remember what your friend list looked like yesterday.

I suppose that's a valid use case if you have a big friend list full of people you don't trust, but I'm not sure if we should trade real user confusion for a theoretical attack that can be solved by other means.

**Comment by ProMcTagonist** [comment]
> Say you have 2 people in your friend list with the same name, the same status message and the same avatar. How can you tell who's the impostor?

Message history, name change history, status history. The last two are yet to be implemented but are critical for this very reason among others. Right clicking and checking a public key or ID that you've memorized the correct version of is not an acceptable solution.

**Comment by alexbakker** [comment]
Having name history won't help if the contact you added uses the same name as another contact from the get go.

**Comment by agilob** [comment]
> Say you have 2 people in your friend list with the same name, the same status message and the same avatar. How can you tell who's the impostor?

I dont even know what my toxid looks like... how would I know someones else?

This should be added to about windows of a user, not to context menu.

**Comment by ProMcTagonist** [comment]
> Having name history won't help if the contact you added uses the same name as another contact from the get go. 

Which is why I also mentioned status history and message history. Your real friend has probably changed status and/or messaged you. It would also be helpful to have a small identicon for the key on friends' profile pages. Under no circumstances is it desirable for a user to be forced to memorize public keys to identify their friends.

**Comment by alexbakker** [comment]
@agilob

> I dont even know what my toxid looks like... how would I know someones else?

If you notice someone is impersonating a friend on your friend list, the logical next step would be to contact that friend through a different channel and ask for their public key so you can compare. I'm not saying people should memorize each others public keys.

> This should be added to about windows of a user, not to context menu.

I agree, that would be a good way to do it. Like I said before, I don't think that this should be the permanent solution. But as long as there is no about window, we have to provide the option to obtain the public key in a different way.

@ProMcTagonist 

> Which is why I also mentioned status history and message history. Your real friend has probably changed status and/or messaged you.

Not everyone will have history enabled (assuming you want to make status history optional, similarly to message history). This is not a proper solution.

> It would also be helpful to have a small identicon for the key on friends' profile pages.

I agree, this would be nice to have.

> Under no circumstances is it desirable for a user to be forced to memorize public keys to identify their friends.

I agree, see my reply to @agilob.

**Comment by zetok** [comment]
> I don't think that this should be the permanent solution.

You know what they say about temporary solutions.. `;)`

**Comment by agilob** [comment]
I can try implementing today the about window for a user to stop this discussion. The window will be a place for those settings and feature. Do you like the solution @Impyy ?

**Comment by alexbakker** [comment]
@agilob Yes that sounds good!

**Comment by ovalseven8** [comment]
Related issues:
https://github.com/tux3/qTox/issues/1636 | Contact notes
https://github.com/tux3/qTox/issues/1189 | Lookup previous aliases
https://github.com/tux3/qTox/issues/2391 | Profile information
https://github.com/tux3/qTox/issues/2236 | Show friend public key

**Comment by alexbakker** [comment]
Closing in favor of #2547

**Pull request closed without merging**
