### PR TITLE
disable filteraudio, because it makes audio quality worse

### LINKED ISSUE #2942: Remove “Filter audio” option from the settings
Remove “Filter audio” option from the settings or make it inactive.

**Rationale:** At the present time (February 2016) filter_audio is badly broken. The purpose of filter_audio is improving audio quality, that means not only normalization&compression but also echo cancellation. But instead of removing echo it actually _adds_ it. Added echo is so loud, so it even causes a feedback effect with the Echobot. But though the only thing filter_audio does is ruining audio quality, this option still available in the settings.

**Advantages:** UX improvment (no more a confusing option to damage quality)

**Disadvantages:** None.

**Unresolved questions:** Can we have a reasonable alternative to filter_audio?

See also: https://github.com/tux3/qTox/issues/1655, https://github.com/tux3/qTox/issues/2126, https://github.com/tux3/qTox/issues/2756 and many other issues.

### PR DESCRIPTION
**Pull request by sudden6**
Fixes  #2942 until we have a better audio backend

### CODE REVIEW

**Comment by antis81** [comment]
@sudden6
This currently looks like a half-hearted attempt and the code actually introduces bad things…

Please remove the checkbox from the UI file instead of hiding it and make the settings flag always return `false` in `Settings::getFilterAudio()` - you can move the comment there.

**Comment by sudden6** [comment]
@antis81 I didn't remove the checkbox, because I thought we want to reintroduce this at some point?

**Comment by antis81** [comment]
Life is a process of creation and destruction - same with software. :) Right now I don't see anyone, who really cares about implementing this feature and - more important - the concept underneath. Why bother about a dead horse rather than care for the living one?

**Comment by sudden6** [comment]
ok, I removed it. Or did you mean I should eliminate all traces of libfilter_audio?

**Comment by zetok** [comment]
Err.

Wouldn't it be better to simply change `qtox.pro` so that by default filter_audio support won't be compiled?

**Comment by sudden6** [comment]
@zetok without my changes the checkbox would still be displayed, but greyed out. Not user friendly.

**Comment by antis81** [comment]
@zetok This leaves the checkbox as an artifact and is probably not the best solution at all.

**Comment by zetok** [comment]
Right. I just thought that disabling filter_audio is supposed to be ~temporary, until it gets fixed. If that's not the case, nvm what I've said about just disabling it in `qtox.pro`.

**Comment by tux3** [comment]
LGTM.
Although if nobody really wants to fix filteraudio, eventually we can start thinking about removing it entirely.
Even on uTox I haven't noticed a huge improvement with it on, so I wouldn' t be opposed.

**Comment by ovalseven8** [comment]
> eventually we can start thinking about removing it entirely.

:+1:

**Pull request merged**
