### PR TITLE
[Refactor] Lazy smileypack

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4782)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 7 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.cpp, line 291 at r1](https://reviewable.io:443/reviews/qtox/qtox/4782#-Kxrlg4-pgMN2bEiEZDB:-Kxrlg4-pgMN2bEiEZDC:b-e2zyqj) ([raw file](https://github.com/qtox/qtox/blob/3d4785ad9f44a7b12af9ec1c067e5c176049757c/src/persistence/smileypack.cpp#L291)):*
> ```cpp
> {
>     QMutexLocker locker(&loadingMutex);
>     if (emoticonToIcon.find(emoticon) != emoticonToIcon.end())
> ```

braces

Also note you're doing the lookup for `emoticon` twice here, not sure if the compiler will optimize that away or not. Maybe it can be avoided.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782)*

**Comment by Diadlo** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.cpp, line 291 at r1](https://reviewable.io:443/reviews/qtox/qtox/4782#-Kxrlg4-pgMN2bEiEZDB:-KxsdLZxcsiCtgiUmzEl:b-u88ra) ([raw file](https://github.com/qtox/qtox/blob/3d4785ad9f44a7b12af9ec1c067e5c176049757c/src/persistence/smileypack.cpp#L291)):*
>braces

Done.

> you're doing the lookup for emoticon twice

No, it's different lookups. Renamed one of container to avoid misreading.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782)*

**Comment by sudden6** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.cpp, line 291 at r1](https://reviewable.io:443/reviews/qtox/qtox/4782#-Kxrlg4-pgMN2bEiEZDB:-KxsejjweaKRzacFO7mL:bxil3xi) ([raw file](https://github.com/qtox/qtox/blob/3d4785ad9f44a7b12af9ec1c067e5c176049757c/src/persistence/smileypack.cpp#L291)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

>braces

Done.

> you're doing the lookup for emoticon twice

No, it's different lookups. Renamed one of container to avoid misreading.
</blockquote></details>

I actually meant first looking up the element with `find()` then doing another lookup with `operator[]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782)*

**Comment by Diadlo** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.cpp, line 291 at r1](https://reviewable.io:443/reviews/qtox/qtox/4782#-Kxrlg4-pgMN2bEiEZDB:-KxsiUMTM1K8wOy06G96:bixn8sv) ([raw file](https://github.com/qtox/qtox/blob/3d4785ad9f44a7b12af9ec1c067e5c176049757c/src/persistence/smileypack.cpp#L291)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I actually meant first looking up the element with `find()` then doing another lookup with `operator[]`
</blockquote></details>

Oh... Thanks, done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: 7 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782#-:-KxsjnwxCmfzRYWdr4Cc:b-jbsf8z)*

**Comment by noavarice** [comment]
Reviewed 6 of 8 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/persistence/smileypack.cpp, line 62 at r3](https://reviewable.io:443/reviews/qtox/qtox/4782#-KxvmhSx4wC7Rm6OMLo6:-KxvmhSyr-qlk982M4qA:b9zke0z) ([raw file](https://github.com/qtox/qtox/blob/24ac5497d28b85c0a8493b6816281bae9af913db/src/persistence/smileypack.cpp#L62)):*
> ```cpp
> static const QString EMOTICONS_FILE_NAME = QStringLiteral("emoticons.xml");
> 
> static constexpr int CleanupTimeout = 5 * 60 * 1000; // 5 minutes
> ```

Use naming convention for constants

---

*[src/persistence/smileypack.cpp, line 129 at r3](https://reviewable.io:443/reviews/qtox/qtox/4782#-Kxvo2hswEKALYfn_-Rp:-Kxvo2hswEKALYfn_-Rq:b-6hl4xy) ([raw file](https://github.com/qtox/qtox/blob/24ac5497d28b85c0a8493b6816281bae9af913db/src/persistence/smileypack.cpp#L129)):*
> ```cpp
>         std::shared_ptr<QIcon>& icon = it->second;
>         if (icon.use_count() == 1) {
>             cachedIcon.erase(it++);
> ```

I think there is no need for such complicated iterator incrementation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782)*

**Comment by Diadlo** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/persistence/smileypack.cpp, line 62 at r3](https://reviewable.io:443/reviews/qtox/qtox/4782#-KxvmhSx4wC7Rm6OMLo6:-Ky_axYHBO_-BoRxSIK6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/24ac5497d28b85c0a8493b6816281bae9af913db/src/persistence/smileypack.cpp#L62)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Use naming convention for constants
</blockquote></details>

Done.

---

*[src/persistence/smileypack.cpp, line 129 at r3](https://reviewable.io:443/reviews/qtox/qtox/4782#-Kxvo2hswEKALYfn_-Rp:-Ky_ay8BGD7DxHtANb3E:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/24ac5497d28b85c0a8493b6816281bae9af913db/src/persistence/smileypack.cpp#L129)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I think there is no need for such complicated iterator incrementation
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4782)*

**Pull request merged**
