### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by wngr**
Added missing dependencies to build toxcore on fedora.

### CODE REVIEW

**Comment by linux-modder** [comment]
possibly  re-word to indicate that more like @irungentoo's  comment on  /usr/local/   in  .../toxcore/.../INSTALL.md

**Comment by linux-modder** [comment]
@zetok, might wanna show how that is bullshit especially when it builds JUST fine as written in me gist.

**Comment by zetok** [comment]
@linux-modder https://github.com/tux3/qTox/blob/master/INSTALL.md#dependencies ← here you go, read this section in context of my previous comment.

**Comment by linux-modder** [comment]
@ze

**Comment by linux-modder** [comment]
@zetok  do you even use  Fedora, and only part that is even remotely relevant is the qt comment.... which IS valid

**Pull request merged**
