### PR TITLE
docs(README): Fix typo in readme

### PR DESCRIPTION
**Pull request by naxuroqa**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5407)

### CODE REVIEW

**Review by sudden6 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5407)* status: 0 of 1 LGTMs obtained

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5407#-:-LP_obxLBoWHW3ErQjAU:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by sudden6** [comment]
@naxuroqa can you please rebase on master? Travis is trying to run with an old configuration.

**Comment by naxuroqa** [comment]
@sudden6 rebased

**Pull request merged**
