### PR TITLE
add audio group calls

### PR DESCRIPTION
**Pull request by antis81**
Enhances #3084 and fixes the audio data handling. @sudden6 Feel free to either cherry pick the commits or merge this one and rebase on top. I wasn't initially aware you're on it - anyway your changes and the ones here are completely separated and do not interfere. 

Fixes part of #2989 -> (a very important part :smile:).

### CODE REVIEW

**Comment by sudden6** [comment]
I don't understand how this goes together with my changes, am I supposed to merge these on top of my branch?

Edit: I got it now, you probably saved me from doing a lot of ugly hacks :smiley:

**Comment by antis81** [comment]
@sudden6 Welcome! :) Can you check this please and setup a group call - probably with another user or second computer? Would be awesome if that worked out-of-box.

**Comment by sudden6** [comment]
@antis81 Yes it worked!
I have cherry picked your commits into my PR and will close this PR.

**Comment by antis81** [comment]
Ok, thanks! No further changes were pushed by me here, avoiding unnecessary confusion.

**Pull request closed without merging**
