### PR TITLE
Fix/threading

### PR DESCRIPTION
**Pull request by sudden6**
Follow up to #5980

@anthonybilinski Am I correct here with not using `src/model/interface.h` for the signals/slots?

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.h, line 92 at r1](https://reviewable.io/reviews/qtox/qtox/5981#-M2IGszt4MRAabjbUBt-:-M2IGszuDZt6T4u98yO9:bhbiezz) ([raw file](https://github.com/qtox/qtox/blob/08106eb21eebee7e2627623335b35294fc16650a/src/core/coreav.h#L92)):*
> ```objc
>     bool sendCallAudio(uint32_t friendNum, const int16_t* pcm, size_t samples, uint8_t chans,
>                        uint32_t rate) const;
>     void sendCallVideo(uint32_t friendNum, std::shared_ptr<VideoFrame> frame);
> ```

why change these to slots if they're still all being called directly?

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.h, line 92 at r1](https://reviewable.io/reviews/qtox/qtox/5981#-M2IGszt4MRAabjbUBt-:-M2LEagAE0hKFvu41TKu:b-je0d1o) ([raw file](https://github.com/qtox/qtox/blob/08106eb21eebee7e2627623335b35294fc16650a/src/core/coreav.h#L92)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why change these to slots if they're still all being called directly?
</blockquote></details>

Artifact from development, undid this.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 97 at r2](https://reviewable.io/reviews/qtox/qtox/5981#-M2SKAMy7SzXM88sl-z1:-M2SKAMzBuFWOqVbghj6:bm03ult) ([raw file](https://github.com/qtox/qtox/blob/25d0dd6884b7f7090d0dc658cfecc03d4c66b70c/src/nexus.cpp#L97)):*
> ```cpp
>     qRegisterMetaType<int32_t>("int32_t");
>     qRegisterMetaType<int64_t>("int64_t");
>     qRegisterMetaType<size_t>("size_t");
> ```

since slots were reverted, I think this is now unneeded

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 97 at r2](https://reviewable.io/reviews/qtox/qtox/5981#-M2SKAMy7SzXM88sl-z1:-M2VPdcB6WUJQVSfStfG:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/25d0dd6884b7f7090d0dc658cfecc03d4c66b70c/src/nexus.cpp#L97)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

since slots were reverted, I think this is now unneeded
</blockquote></details>

Done.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.h, line 67 at r4](https://reviewable.io/reviews/qtox/qtox/5981#-M2XYahi4304sKqbTJLk:-M2XYahi4304sKqbTJLl:b-smbwdb) ([raw file](https://github.com/qtox/qtox/blob/ed7c4d93bd166b7e2883299dd5a258cef34f1aeb/src/core/coreav.h#L67)):*
> ```objc
>                        uint32_t rate) const;
>     void sendCallVideo(uint32_t friendNum, std::shared_ptr<VideoFrame> frame);
> ```

looking at the diff from start to finish, `sendGroupCallAudio` has moved from last to first from these 3 functions, needless diff
___
*[src/core/toxcall.cpp, line 212 at r2](https://reviewable.io/reviews/qtox/qtox/5981#-M2XY1IjEBU3BMFXhuMf:-M2XY1IjEBU3BMFXhuMg:b-qdyb17) ([raw file](https://github.com/qtox/qtox/blob/25d0dd6884b7f7090d0dc658cfecc03d4c66b70c/src/core/toxcall.cpp#L212)):*
> ```cpp
>                     return;
>                 }
> ```

I think the last two versions both have an issue with your git. e.g. in the last two commits, the braces are used on the single line `if` were removed, which I think was accidental.

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.h, line 67 at r4](https://reviewable.io/reviews/qtox/qtox/5981#-M2XYahi4304sKqbTJLk:-M2Y99UsB17fgYRYMpG_:bm5vxcq) ([raw file](https://github.com/qtox/qtox/blob/ed7c4d93bd166b7e2883299dd5a258cef34f1aeb/src/core/coreav.h#L67)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

looking at the diff from start to finish, `sendGroupCallAudio` has moved from last to first from these 3 functions, needless diff
</blockquote></details>

Done. Sometimes I hate git
___
*[src/core/toxcall.cpp, line 212 at r2](https://reviewable.io/reviews/qtox/qtox/5981#-M2XY1IjEBU3BMFXhuMf:-M2Y9CY_1pd4xFTBDDOL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/25d0dd6884b7f7090d0dc658cfecc03d4c66b70c/src/core/toxcall.cpp#L212)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think the last two versions both have an issue with your git. e.g. in the last two commits, the braces are used on the single line `if` were removed, which I think was accidental.
</blockquote></details>

Done.

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5981#-:-M2brkw08qKd_E-bi2e2:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
