### PR TITLE
fix(ipc): Call processEvent on timer timeout

### LINKED ISSUE #4609: qtox login box appears, even if I am already logged in
##### Brief Description

OS: Linux Kubuntu 17.04
qTox version: v1.11.0-89-g359a42f7
Commit hash: 359a42f78e8edf073d6132bca8954a55094385c5 
toxcore: 0.1.2
Qt: 5.7.1
Hardware: "00:00.0 Host bridge: Intel Corporation Device 590f (rev 06)
00:02.0 VGA compatible controller: Intel Corporation Device 5912 (rev 04)
00:08.0 System peripheral: Intel Corporation Skylake Gaussian Mixture Model
00:14.0 USB controller: Intel Corporation 200 Series PCH USB 3.0 xHCI Controller
00:14.2 Signal processing controller: Intel Corporation 200 Series PCH Thermal Subsystem
00:16.0 Communication controller: Intel Corporation 200 Series PCH CSME HECI #1
00:17.0 SATA controller: Intel Corporation 200 Series PCH SATA controller [AHCI mode]
00:1c.0 PCI bridge: Intel Corporation 200 Series PCH PCI Express Root Port #7 (rev f0)
00:1f.0 ISA bridge: Intel Corporation 200 Series PCH LPC Controller (B250)
00:1f.2 Memory controller: Intel Corporation 200 Series PCH PMC
00:1f.3 Audio device: Intel Corporation 200 Series PCH HD Audio
00:1f.4 SMBus: Intel Corporation 200 Series PCH SMBus Controller
01:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)
 
…

Reproducible: Always 

##### Steps to reproduce

1. start new session
2. a login box appears
3. closing it, the program, qtox, works normally

##### Observed Behavior
strange login box (my profile is without password)

##### Expected Behavior
no login box

##### Additional Info
(links, images, etc go here)
[qtox.txt](https://github.com/qTox/qTox/files/1267171/qtox.txt)

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4609

It's my mistake in IPC refactoring

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4614)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4614#-:-KsxvvUUZ0Fcv7ktFumC:b-jbsf8z)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/ipc.cpp, line 49 at r1](https://reviewable.io:443/reviews/qtox/qtox/4614#-KsyR5b8Qz8rW9j0Nj_i:-KsyR5b8Qz8rW9j0Nj_j:b-i1ehsk) ([raw file](https://github.com/qtox/qtox/blob/32055bd73a12f059fc5efaa17873dbd4d4fb10f5/src/ipc.cpp#L49)):*
> ```cpp
>     timer.setInterval(EVENT_TIMER_MS);
>     timer.setSingleShot(true);
>     connect(&timer, &QTimer::timeout, [=]() {
> ```

I think, you can connect directly to `processEvents`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4614)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/ipc.cpp, line 49 at r1](https://reviewable.io:443/reviews/qtox/qtox/4614#-KsyR5b8Qz8rW9j0Nj_i:-KszNqjkfPEcs_v9Pgqi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/32055bd73a12f059fc5efaa17873dbd4d4fb10f5/src/ipc.cpp#L49)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I think, you can connect directly to `processEvents`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4614)*

**Comment by noavarice** [comment]
:lgtm_strong:

**Pull request merged**
