### PR TITLE
Refactor content dialog

### PR DESCRIPTION
**Pull request by Diadlo**
- [X] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Move all static methods from `ContentDialog` to `ContentDialogManager`. Also fix one bug with group widget drag-and-drop

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5471)

### CODE REVIEW

**Comment by sudden6** [comment]
OSX doesn't like some of your code: https://travis-ci.org/qTox/qTox/jobs/471930078#L2636

**Comment by Diadlo** [comment]
@sudden6 Yes. Should be fixed now. Let's wait for the end of the build

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5471)* status: 0 of 1 LGTMs obtained

___
*[src/widget/contentdialog.cpp, line 760 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwGks9dJJXfyrab46:-LUZwGks9dJJXfyrab47:b8x6hp5) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialog.cpp#L760)):*
> ```cpp
> {
>     return activeChatroomWidget == widget;
> }
> ```

strange EOL
___
*[src/widget/contentdialogmanager.cpp, line 87 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwKsu8LZ7fZUBhKJ2:-LUZwKsu8LZ7fZUBhKJ3:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L87)):*
> ```cpp
>     auto dialog = focusDialog(friendId, friendDialogs);
>     if (dialog != nullptr)
>         dialog->focusFriend(friendId);
> ```

braces
___
*[src/widget/contentdialogmanager.cpp, line 94 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwMB01U-Xpct81yhn:-LUZwMB01U-Xpct81yho:b-skfgnv) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L94)):*
> ```cpp
>     auto dialog = focusDialog(groupId, groupDialogs);
>     if (dialog != nullptr)
>         dialog->focusGroup(groupId);
> ```

braces
___
*[src/widget/contentdialogmanager.cpp, line 179 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwaVQ5_ahGYbWAXKh:-LUZwaVQ5_ahGYbWAXKi:bofims3) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L179)):*
> ```cpp
> }
> 
> ContentDialogManager* ContentDialogManager::getInstance()
> ```

Do you plan to remove the singleton in the future?
___
*[src/widget/contentdialogmanager.cpp, line 210 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwUKhE-UaX3evDkbb:-LUZwUKhE-UaX3evDkbc:b8x6hp5) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L210)):*
> ```cpp
>     removeDialog(dialog, friendDialogs);
>     removeDialog(dialog, groupDialogs);
> }
> ```

strange EOL

**Review by Diadlo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5471)* status: 0 of 1 LGTMs obtained

___
*[src/widget/contentdialog.cpp, line 760 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwGks9dJJXfyrab46:-LU_D204E1rxgC-Ly5aM:bm8v48x) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialog.cpp#L760)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

strange EOL
</blockquote></details>

*EOF
Fixed
___
*[src/widget/contentdialogmanager.cpp, line 87 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwKsu8LZ7fZUBhKJ2:-LU_D4F867qqjfKiEAOt:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L87)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/widget/contentdialogmanager.cpp, line 94 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwMB01U-Xpct81yhn:-LU_D9-Y2L4_ScPKnwLp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L94)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces
</blockquote></details>

Done.
___
*[src/widget/contentdialogmanager.cpp, line 179 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwaVQ5_ahGYbWAXKh:-LU_DA_5DX1QzHo-f01h:bh31985) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L179)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Do you plan to remove the singleton in the future?
</blockquote></details>

Yes. Someday)
___
*[src/widget/contentdialogmanager.cpp, line 210 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwUKhE-UaX3evDkbb:-LU_DGI0A8LJa_GW6gDx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L210)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

strange EOL
</blockquote></details>

Done.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 9 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5471#-:-LUgeJeaDxpOzFbjw4et:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/contentdialogmanager.cpp, line 179 at r1](https://reviewable.io/reviews/qtox/qtox/5471#-LUZwaVQ5_ahGYbWAXKh:-LUgdF-M2M99MOvj740G:buami3a) ([raw file](https://github.com/qtox/qtox/blob/fddb999a91cc929a652129d0916bb94c6ece1738/src/widget/contentdialogmanager.cpp#L179)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Yes. Someday)
</blockquote></details>

Someday™ ;P

**Pull request merged**
