### PR TITLE
Core refactor

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4369)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/nexus.cpp, line 202 at r1](https://reviewable.io:443/reviews/qtox/qtox/4369#-KjSvOl47H6zMpCz1Oz7:-KjSvOl47H6zMpCz1Oz8:b-o5ky80) ([raw file](https://github.com/qtox/qtox/blob/ed4b1d5287082d531dfb9a63baab99bfa65dc896/src/nexus.cpp#L202)):*
> ```cpp
>     // Connections
>     Core* core = profile->getCore();
>     connect(core, &Core::requestSended, profile, &Profile::onRequestSended);
> ```

`send` is an irregular verb, rename to `sent` in the whole PR

---

*[src/persistence/profile.cpp, line 453 at r1](https://reviewable.io:443/reviews/qtox/qtox/4369#-KjSvyE-rvSKJ1TjgjpF:-KjSvyE0e9t1DJWGoSA-:b-9ccjy1) ([raw file](https://github.com/qtox/qtox/blob/ed4b1d5287082d531dfb9a63baab99bfa65dc896/src/persistence/profile.cpp#L453)):*
> ```cpp
>     }
> 
>     QString pkStr = friendPk.toString();
> ```

IMO we should add the whole ToxID under which the friend was added. This allows to add the friend again later with another Tox Client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4369)*

**Comment by Diadlo** [comment]
Review status: 2 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/nexus.cpp, line 202 at r1](https://reviewable.io:443/reviews/qtox/qtox/4369#-KjSvOl47H6zMpCz1Oz7:-KjTFp5bhTI4Cxh5tjdo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed4b1d5287082d531dfb9a63baab99bfa65dc896/src/nexus.cpp#L202)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`send` is an irregular verb, rename to `sent` in the whole PR
</blockquote></details>

Done.

---

*[src/persistence/profile.cpp, line 453 at r1](https://reviewable.io:443/reviews/qtox/qtox/4369#-KjSvyE-rvSKJ1TjgjpF:-KjTEAwWQbNE2H80gpWH:brk94jr) ([raw file](https://github.com/qtox/qtox/blob/ed4b1d5287082d531dfb9a63baab99bfa65dc896/src/persistence/profile.cpp#L453)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IMO we should add the whole ToxID under which the friend was added. This allows to add the friend again later with another Tox Client.
</blockquote></details>

We shouldn't save `ToxId` becouse it's not persistent (see NoSpam)
Also, chat history use TokPk (see `addNewMessage` signature) to store and  display messages

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4369)*

**Comment by sudden6** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/profile.cpp, line 453 at r1](https://reviewable.io:443/reviews/qtox/qtox/4369#-KjSvyE-rvSKJ1TjgjpF:-KjbLTQPnQMdKJ6FMSkD:bhl1by7) ([raw file](https://github.com/qtox/qtox/blob/ed4b1d5287082d531dfb9a63baab99bfa65dc896/src/persistence/profile.cpp#L453)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

We shouldn't save `ToxId` becouse it's not persistent (see NoSpam)
Also, chat history use TokPk (see `addNewMessage` signature) to store and  display messages
</blockquote></details>

ok, I understand the reasoning now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4369)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4369#-:-KjbMZJ26kiqnaMi-dph:b-jbsf8z)*

**Pull request merged**
