### PR TITLE
fix(i18n): Various English fixes

### PR DESCRIPTION
**Pull request by jessica181920**
Consistency, typos, grammatical corrections, capitalization, punctuation,
etc.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5829)

### CODE REVIEW

**Comment by jessica181920** [comment]
whoops, should be fixed now

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 43 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5829)* status: 0 of 1 LGTMs obtained

___
*[src/audio/backend/openal.cpp, line 296 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LoisDVu3TAvBia5lhsF:-LoisDVv9sauayfT31Ot:boes5bz) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/audio/backend/openal.cpp#L296)):*
> ```cpp
> 
>     if (sinksErased == 0 && soundSinksErased == 0) {
>         qWarning() << "Erasing non-existent source";
> ```

"Destroy" has meaning here - classes have constructors and destructors, and this is called from AlSink::~AlSink, a destructor. It's also being used in the function "destroySink" so keeping the "destroy" terminology in the log makes more sense I think.

The log should be a "sink" not a "source" though.
___
*[src/audio/backend/openal.cpp, line 353 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loisg9IDF6-KwKLcfgu:-Loisg9J3Nc8MJxyVA7g:b-7jw80m) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/audio/backend/openal.cpp#L353)):*
> ```cpp
>     const auto s = sources.find(&source);
>     if (s == sources.end()) {
>         qWarning() << "Erased non-existent source";
> ```

same about destroy, though this time it really is a "source"
___
*[src/chatlog/chatmessage.cpp, line 204 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loiw1rDB5ty6ozz-ajF:-Loiw1rDB5ty6ozz-ajG:b4i319i) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/chatlog/chatmessage.cpp#L204)):*
> ```cpp
>     baseFont.setBold(true);
> 
>     msg->addColumn(new Text(QObject::tr("Reformatting text..."), baseFont, false, ""),
> ```

could you add a translation hint here as a second argument to the tr(), in case the "..." meaning isn't obvious in other languages without the "in progress" context?
___
*[src/core/core.cpp, line 179 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loixfiz-XXOe9Acwsha:-Loixfiz-XXOe9Acwshb:b-d9s09a) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/core.cpp#L179)):*
> ```cpp
>     QThread* thread = new QThread();
>     if (thread == nullptr) {
>         qCritical() << "Could not allocate core thread";
> ```

"Core" here is referring to the class Core, classes are capitalised, so uppercase 'C' seems correct.
___
*[src/core/core.cpp, line 186 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loj0VPBA83ouC86-uMs:-Loj0VPBA83ouC86-uMt:bcdseq9) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/core.cpp#L186)):*
> ```cpp
>     auto toxOptions = ToxOptions::makeToxOptions(savedata, settings);
>     if (toxOptions == nullptr) {
>         qCritical() << "Could not allocate Tox options data structure";
> ```

I think this should be "ToxOptions" since it's referring to the class ToxOptions, not just a general options of Tox.
___
*[src/core/core.cpp, line 1308 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojD4FFEhd6Rp6SmT9-:-LojD4FFEhd6Rp6SmT90:bnxdtlo) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/core.cpp#L1308)):*
> ```cpp
>     switch (confType) {
>     case TOX_CONFERENCE_TYPE_TEXT: {
>         qDebug() << QString("Trying to join text group chat invite sent by friend %1").arg(friendId);
> ```

I like the change - but this sentence still seems broken. It sounds like it's joining the invite? Maybe stick a period after "group chat" and before "Invite"?
___
*[src/core/coreav.cpp, line 740 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojFMMmEvxI4JjEL4k-:-LojFMMmEvxI4JjEL4k0:b-3jy59w) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/coreav.cpp#L740)):*
> ```cpp
>         /// we'll always reach this point through a non-blocking queud connection, so not in the
>         /// callback.
>         qWarning() << QString("Rejecting call invite from %1, you're already in that call!").arg(friendNum);
> ```

I kind of like the use of "we" to mean "qTox the program" and "you" to mean "the user" - and it seems like we mostly do this around in other places, `grep -r '".*you.*"'` seems to mostly be UI/prompts, and `grep -r '".*we.*"'` has a decent number of uses to mean "we the qTox program had something go weird" in log messages.

If we follow that pattern, I think "we" makes sense here - because our internal state tells us that we're in a call, but maybe the user doesn't actually see it that way.
___
*[src/net/toxme.cpp, line 100 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojJ11A4JRHMqGL6N3z:-LojJ11A4JRHMqGL6N4-:br8y7d4) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/net/toxme.cpp#L100)):*
> ```cpp
>     QPair<QByteArray, QByteArray> keypair = Core::getInstance()->getKeypair();
>     if (keypair.first.isEmpty() || keypair.second.isEmpty()) {
>         qWarning() << "prepareEncryptedJson: Couldn't get keypair, aborting";
> ```

I think "our" makes sense here, the keypair is from `tox_self_get_public_key`, so it's distinctly our own keypair, instead of just _a_ keypair
___
*[src/persistence/settings.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojJx1qD2tRSaWV8rDQ:-LojJx1qD2tRSaWV8rDR:b-2xcu1j) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/persistence/settings.cpp#L73)):*
> ```cpp
> {
>     settingsThread = new QThread();
>     settingsThread->setObjectName("qTox settings");
> ```

this "Settings" is talking about the class, so I think uppercase makes more sense.
___
*[src/persistence/settingsserializer.cpp, line 333 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojKO_C1vwkB0iZ8lM6:-LojKO_C1vwkB0iZ8lM7:b-obrbd0) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/persistence/settingsserializer.cpp#L333)):*
> ```cpp
>     if (ToxEncrypt::isEncrypted(data)) {
>         if (!passKey) {
>             qCritical() << "The settings file is encrypted, but we don't have a password!";
> ```

"passkey" here is referring to the variable `passkey`, and the term "passkey" comes from toxcore with `Tox_Pass_Key`, where the pass key is derived from the password with `tox_pass_key_derive`. I think this should be left unchanged.

**Comment by jessica181920** [comment]
> could you add a translation hint here as a second argument to the tr(), in case the "..." meaning isn't obvious in other languages without the "in progress" context?

I can but we use ellipsis all over the place in qTox. Look at the chat message box, look at some of the options in context menus, or just search "..." and you'll find a ton

Formatting text (a present tense statement) does not need the "in progress" due to it being in present tense. It is implied that it is in progress. It's like in the statement "I am currently driving a car" you can drop the "currently" because it is implied that you're doing that right now.

> I kind of like the use of "we" to mean "qTox the program" and "you" to mean "the user" - and it seems like we mostly do this around in other places, grep -r '".*you.*"' seems to mostly be UI/prompts, and grep -r '".*we.*"' has a decent number of uses to mean "we the qTox program had something go weird" in log messages.

The "we" and "our" stuff is very infrequent in the strings and I thought I removed it all. It does not sound correct at all and I have never seen software use this pronoun style. I have seen software inform the user with the you form, "you can't do that," or "you already have that file open" or something along those lines, but never "we" or "our." If there are other instances of "we" or "our" then I missed them and I'd like to change them all to the "you" form.

**Comment by jessica181920** [comment]
I don't know why but I left most of the "we" in the debug strings and whatnot. I should have changed this. "We" implies more than one person including the user, which doesn't make sense. The only time "we" makes sense is in comments.

I'm going to change the few instances where I removed "we" pronouns back, but keep in mind that this is pretty much incorrect and should be changed at a future date.

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5829#-:-Lor7NZ66U6bQQ5-JapT:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/audio/backend/openal.cpp, line 296 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LoisDVu3TAvBia5lhsF:-LolL83mDeBNvPEtc3Xy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/audio/backend/openal.cpp#L296)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"Destroy" has meaning here - classes have constructors and destructors, and this is called from AlSink::~AlSink, a destructor. It's also being used in the function "destroySink" so keeping the "destroy" terminology in the log makes more sense I think.

The log should be a "sink" not a "source" though.
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 353 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loisg9IDF6-KwKLcfgu:-LolLA2W-inAdFKzBviO:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/audio/backend/openal.cpp#L353)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same about destroy, though this time it really is a "source"
</blockquote></details>

Done.
___
*[src/chatlog/chatmessage.cpp, line 204 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loiw1rDB5ty6ozz-ajF:-LolLFo4EAWdenamZYeX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/chatlog/chatmessage.cpp#L204)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could you add a translation hint here as a second argument to the tr(), in case the "..." meaning isn't obvious in other languages without the "in progress" context?
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 179 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loixfiz-XXOe9Acwsha:-LolLHib90dZABNFt2UK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/core.cpp#L179)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"Core" here is referring to the class Core, classes are capitalised, so uppercase 'C' seems correct.
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 186 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-Loj0VPBA83ouC86-uMs:-LolLIaG3M_xD-V6b80I:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/core.cpp#L186)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think this should be "ToxOptions" since it's referring to the class ToxOptions, not just a general options of Tox.
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 1308 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojD4FFEhd6Rp6SmT9-:-LolLMH_BtXi01nZaOY4:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/core.cpp#L1308)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I like the change - but this sentence still seems broken. It sounds like it's joining the invite? Maybe stick a period after "group chat" and before "Invite"?
</blockquote></details>

Done.
___
*[src/core/coreav.cpp, line 740 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojFMMmEvxI4JjEL4k-:-Loqx-hc5qi-TXecG4IS:ba5083s) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/core/coreav.cpp#L740)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I kind of like the use of "we" to mean "qTox the program" and "you" to mean "the user" - and it seems like we mostly do this around in other places, `grep -r '".*you.*"'` seems to mostly be UI/prompts, and `grep -r '".*we.*"'` has a decent number of uses to mean "we the qTox program had something go weird" in log messages.

If we follow that pattern, I think "we" makes sense here - because our internal state tells us that we're in a call, but maybe the user doesn't actually see it that way.
</blockquote></details>

Replying to github comment: yeah "we" is kind of weird - but I also feel like "you" isn't right here either since we only expect to hit this state if qTox did something wrong - in which case for all we know maybe the user isn't _really_ in a call. Like you said, just using the implicit I like "Rejecting call invite from %1, already in that call!" seems best. Feel free to change to that later (and all other uses of "we"), but that's not blocking this.
___
*[src/net/toxme.cpp, line 100 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojJ11A4JRHMqGL6N3z:-Lor5mT42Qj2HhGqZDVH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/net/toxme.cpp#L100)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think "our" makes sense here, the keypair is from `tox_self_get_public_key`, so it's distinctly our own keypair, instead of just _a_ keypair
</blockquote></details>

Done.
___
*[src/persistence/settings.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojJx1qD2tRSaWV8rDQ:-Lor6m3A5jwO1WvikHtz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/persistence/settings.cpp#L73)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

this "Settings" is talking about the class, so I think uppercase makes more sense.
</blockquote></details>

Done.
___
*[src/persistence/settingsserializer.cpp, line 333 at r1](https://reviewable.io/reviews/qtox/qtox/5829#-LojKO_C1vwkB0iZ8lM6:-Lor6rDQBbRN9WxLMDAr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3f1cfe240ac68f057660b7c2bf432233a7a0a38c/src/persistence/settingsserializer.cpp#L333)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

"passkey" here is referring to the variable `passkey`, and the term "passkey" comes from toxcore with `Tox_Pass_Key`, where the pass key is derived from the password with `tox_pass_key_derive`. I think this should be left unchanged.
</blockquote></details>

Done.

**Comment by anthonybilinski** [comment]
@sudden6 what are the weblate ramifications for changing a large portion of our source strings at once? I guess this would invalidate a lot of translations in every language?

If that's the case - it seems like we should sync with weblate before merge (which you've done recently), merge this change to master so that v1.17.x don't lose translations, then sync to weblate again so translators can get the new source material. Does that sound right?

**Comment by sudden6** [comment]
Re: the "we" thing

I have seen this quite frequent in debug messages to address the developer (like a note to self), IMO `you` sounds wrong in this case.

Yes I think that will invalidate many strings, but I don't think syncing before makes much sense, because all synced stuff with updated source strings will be invalidated during the update procedure.

**Pull request merged**
