### PR TITLE
Fixes of static analyze warnings

### PR DESCRIPTION
**Pull request by BiTOk**
There is many static analyze warnings for qTox. Fixed most dangerous and several simple.

---

This change is [Reviewable](https://reviewable.io/reviews/tux3/qtox/3573)

### CODE REVIEW

**Comment by tux3** [comment]
LGTM
Edit: Except the commit name is wrong! Please fix that.

**Comment by antis81** [comment]
@BiTOk @tux3 The rest is in #3380 :) - Would you review as well, please?

**Comment by zetok** [comment]
Hi,

As you might be aware, repo has been moved under `qTox` org on github.

What does it have to do with your PR, you might ask.

Well, it doesn't change all that much, except that workflow has been slightly improved – now there are required checks that PR needs to pass in order to be merged.

Those checks are:
- travis (checks whether PR builds & commit message format)
- reviewable (requirement for PR to be reviewed & accepted)

Since osx travis was broken for a bit, you will need to rebase your PR on newest master to get it to pass travis check. Sorry for inconvenience.

Reminder: as always, PR needs to be possible to merge without conflicts. Make sure it does ;)

**Comment by iphydf** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/platform/camera/directshow.cpp, line 83 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3573#-KPOElyKQvaBzuIZyZ6P:-KPOElyKQvaBzuIZyZ6Q:bqzmcmu) ([raw file](https://github.com/qtox/qtox/blob/978d1db923706d7609a39db5e472652b6ac075f5/src/platform/camera/directshow.cpp#L83)):_

> ``` cpp
> 
>         // replace ':' with '_' since FFmpeg uses : to delimitate sources
>         for (size_t i = 0; i < strlen(devIdString); i++)
> ```

@tux3: what's qtox' policy wrt. `std::` on standard library names?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3573)_

**Comment by iphydf** [comment]
@BiTOk which of the fixes is fixing a dangerous bug? In a quick look, I see one fix for undefined behaviour that is in practice working correctly (good to fix, but not dangerous). Which ones were dangerous?

**Comment by BiTOk** [comment]
@iphydf in src/widget/friendlistwidget.cpp fixed potential null pointer dereference.

**Comment by iphydf** [comment]
Ah yes, I see. Can you rebase this branch and fix the conflicts?

**Comment by BiTOk** [comment]
@iphydf now there is no such possibility, and I don't know when will be. Can you do this?

**Comment by iphydf** [comment]
Done: #3741

**Comment by BiTOk** [comment]
@iphydf thank you.

**Pull request closed without merging**
