### PR TITLE
Shift screen region on windows.

### PR DESCRIPTION
**Pull request by Diadlo**
Need tests. Try to fix desktop steam from #3552.

---

This change is [Reviewable](https://reviewable.io/reviews/tux3/qtox/3556)

### CODE REVIEW

**Comment by BiTOk** [comment]
Working fine on win 7 with two monitors in several desktop configurations. LGTM for windows.

**Comment by zetok** [comment]
Hi,

As you might be aware, repo has been moved under `qTox` org on github.

What does it have to do with your PR, you might ask.

Well, it doesn't change all that much, except that workflow has been slightly improved – now there are required checks that PR needs to pass in order to be merged.

Those checks are:
- travis (checks whether PR builds & commit message format)
- reviewable (requirement for PR to be reviewed & accepted)

Since osx travis was broken for a bit, you will need to rebase your PR on newest master to get it to pass travis check. Sorry for inconvenience.

Reminder: as always, PR needs to be possible to merge without conflicts. Make sure it does ;)

**Comment by sudden6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 152 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOnZcvhux_6LQaQTlQ:-KPOnZcvhux_6LQaQTlR:b-psblc1) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L152)):_

> ``` cpp
>     if (index < 0 || index >= videoModes.size())
>     {
>         qWarning() << "Invalid mode index: " << index;
> ```

please remove the space at the end of the string, qt adds it automatically.

---

_[src/widget/form/settings/avform.cpp, line 158 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOndoPOgIZLAvQxx0w:-KPOndoPOgIZLAvQxx0x:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L158)):_

> ``` cpp
>     if (devIndex < 0 || devIndex >= videoDeviceList.size())
>     {
>         qWarning() << "Invalid device index: " << devIndex;
> ```

same

---

_[src/widget/form/settings/avform.cpp, line 182 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOniKdEVvGrJJEJzzz:-KPOniKdEVvGrJJEK---:bvj3dwf) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L182)):_

> ``` cpp
>             mode.height = mode.height / 2 * 2;
> 
>             // Need, if virtual screen origin is top left angle of primary screen
> ```

Needed, if the virtual screen origin is the top left corner of the primary screen

---

_[src/widget/form/settings/avform.cpp, line 184 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOnsf-IgSy1PNqQAS6:-KPOnsf-IgSy1PNqQAS7:b-9e8oi9) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L184)):_

> ``` cpp
>             // Need, if virtual screen origin is top left angle of primary screen
>             QRect screen = QApplication::primaryScreen()->virtualGeometry();
>             qDebug() << "Primary screen: " << screen;
> ```

remove space

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3556)_

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 152 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOnZcvhux_6LQaQTlQ:-KPvNvcvcnvKXF-dzD1F:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L152)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> please remove the space at the end of the string, qt adds it automatically.
> </details>
> ok

---

_[src/widget/form/settings/avform.cpp, line 158 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOndoPOgIZLAvQxx0w:-KPvNydbvPQqx_GJOTjc:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L158)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> same
> </details>
> ok

---

_[src/widget/form/settings/avform.cpp, line 358 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPvO7LuzCYjaFpd8Gur:-KPvO7LuzCYjaFpd8Gus:b-him1u2) ([raw file](https://github.com/qtox/qtox/blob/d82c89f35a1cc29819b984deb201708dd9e87c2a/src/widget/form/settings/avform.cpp#L358)):_

> ``` cpp
>     if (curIndex < 0 || curIndex >= videoDeviceList.size())
>     {
>         qWarning() << "Invalid index: " << curIndex;
> ```

another space to much

---

_[src/widget/form/settings/avform.cpp, line 415 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPvOC-Ve4kWuI1PtW3O:-KPvOC-WOMu-534J-_gR:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/d82c89f35a1cc29819b984deb201708dd9e87c2a/src/widget/form/settings/avform.cpp#L415)):_

> ``` cpp
>     if (index < 0 || index >= videoDeviceList.size())
>     {
>         qWarning() << "Invalid index: " << index;
> ```

same

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3556)_

**Comment by Diadlo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 182 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOniKdEVvGrJJEJzzz:-KPy2-IXwIHSKJfh22pE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L182)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Needed, if the virtual screen origin is the top left corner of the primary screen
> </details>
> Done.

---

_[src/widget/form/settings/avform.cpp, line 184 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPOnsf-IgSy1PNqQAS6:-KPy22IM_JMzVbP-c6Ik:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8f8aa45b430916268246892a78d8e105b3aac93f/src/widget/form/settings/avform.cpp#L184)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> remove space
> </details>
> Done.

---

_[src/widget/form/settings/avform.cpp, line 358 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPvO7LuzCYjaFpd8Gur:-KPy22ucSCsk8DcXGxaN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d82c89f35a1cc29819b984deb201708dd9e87c2a/src/widget/form/settings/avform.cpp#L358)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> another space to much
> </details>
> Done.

---

_[src/widget/form/settings/avform.cpp, line 415 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3556#-KPvOC-Ve4kWuI1PtW3O:-KPy23NaDrf4BJgnCkkL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d82c89f35a1cc29819b984deb201708dd9e87c2a/src/widget/form/settings/avform.cpp#L415)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> same
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3556)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3556#-:-KPyO-n-gAHXVIEeqH9M:bnfp4nl)_

**Comment by antis81** [comment]
@Diadlo Please remove your test code (the qDebug's). Otherwise LGTM -> it doesn't compile though for osx: https://travis-ci.org/qTox/qTox/jobs/154854604

**Comment by Diadlo** [comment]
@antis81 It's not `test code` I added debug messages to make it easier error detection in future

> Done. Your build exited with 0.
> /Users/travis/build.sh: line 109: shell_session_update: command not found

Seems, travis bug

**Comment by antis81** [comment]
> It's not test code I added debug messages to make it easier error detection in future…

Yeah, this is called test code (as you can see by the term "debug" in qDebug), as the code by itself works and wouldn't fail. Thus, we just log irrelevant information. If you want to prevent future mistakes made by other programmers or better falsely implemented concepts build on top of yours, you should go with "assert" (#include <cassert>)… ^^

**Comment by Diadlo** [comment]
@antis81 Ok, I just save one qDebug, which used to make sense to previously existed debug messages. I.e. list of selected modes

**Comment by antis81** [comment]
@Diadlo Thank you! Forgive my bullish (picky) argumentation, but it is important to actually improve situation. Highly appreciate your patience in getting things right. Keep it up! :+1:

**Comment by antis81** [comment]
@abbat @zetok FYI: Looks like Travis OSX build is down. Maybe you want to have a look at it: https://travis-ci.org/qTox/qTox/builds/155008169

**Comment by Diadlo** [comment]
@antis81 But about asserts: what you think about change checking indexes + warning on assert?

**Comment by antis81** [comment]
@Diadlo Good question. Actually the index reported by the combo box is either a valid index or -1, if a) the mode list is empty or b) selection of "no mode" should be allowed. In any other case, the index is valid. So, it might either be an assert, if you like to quickly inform other developers they forgot something or the value is actually valid and should be handled in this case. Conclusion: "The warning is not right and should be removed." :)

**Comment by Diadlo** [comment]
@antis81 List of modes must not be empty. It contains at least "Default mode", which has valid index.

**Comment by zetok** [comment]
@antis81 https://www.traviscistatus.com/incidents/4mvp857qx8bw

**Comment by antis81** [comment]
@zetok Thanks! Looks like they're back with us: Hello Travis! :smile:

**Comment by antis81** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3556#-:-KQ4X5dX240OK7Snq8ap:bnfp4nl)_

**Comment by Diadlo** [comment]
@sudden6 Can you review new commit?

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3556#-:-KQ54RxBwC9JzcSaN0_x:bnfp4nl)_

**Pull request merged**
