### PR TITLE
Multi-window - Separate Window for chats

### PR DESCRIPTION
**Pull request by TheSpiritXIII**
This pull request adds the functionality to detach chats from the main window. You can either detach manually by right clicking on friends or set a setting that detaches all windows by default.

Detached windows still have a friends list! You can chat with multiple friends on a single detached window. Of course, you can also detach friends from detached windows into their own window if you'd like. You're able to drag friends between windows, too!

### CODE REVIEW

**Comment by zetok** [comment]
muh resize
↑ detach, collapse friendlist, make window small, drag & drop some contact → friendlist resizes to its original size, causing visual inconsistencies

**Comment by zetok** [comment]
resize more
↑ After playing more with resizing & collapsing & restoring friendlist

**Comment by zetok** [comment]
size
↑ why there is no minimal size?

Edit: unless someone else confirms that they too suffer from this, it's probably an issue only on i3 / other tiling wms

**Comment by zetok** [comment]
~~By default "separate" windows open themselves with "friendlist" visible, although only one friend is being visible - shouldn't that default to opening new windows without "friendlist" visible?~~

Edit: Actually, after closing window with "friendlist" collapsed, new windows don't have list visible

**Comment by zetok** [comment]
There could be a nice integration with circles:
- [x] when you r-click on circle, you could select an option to open new window with all circle members being present in friendlist (in this case, by default friendlist should be shown?)
- [x] still needs to show by default list when opening a detached window

**Comment by zetok** [comment]
- [x] segfault: https://gist.github.com/zetok/c894041f6fd7247e5b52

**Comment by zetok** [comment]
- [x] windows don't keep set size

**Comment by zetok** [comment]
- [x] when message is received in detached window, notification about new message (double circle) in freindlist doesn't dissapear, unless contact is being clicked on, same goes for groupchats (on 545fb58e8f966f1fe5aca201dc1860a842ea8b50)

**Comment by zetok** [comment]
- [x] segfault when closing groupchat: https://gist.github.com/zetok/873d818c754ee0cf7333

**Comment by zetok** [comment]
- [ ] regression - detached groupchat - when one clicks to show emoticons, and then changes topic, emoticon selector is shown again when topic is changed
  
  https://d.maxfile.ro/yxpkasoptm.webm

**EDIT: ↑ apparently only I can reproduce - can someone else confirm that they're affected too?**

**Comment by zetok** [comment]
- [x] segfault when quitting groupchat with an open window: https://gist.github.com/zetok/ff39d72af148273ad61c

**Comment by zetok** [comment]
- [x] segfault when there is an open detached window when logging out of profile

Steps to reproduce:
1. open detached friend window
2. log out of profile
3. click on detached window

**Comment by zetok** [comment]
- [x] segfault when removed friend: https://gist.github.com/zetok/c90dc5382ad87518b060

**Comment by zetok** [comment]
When there are multiple instances running, only detached windows can be confusing:
all the groupbots

To help with that, title of detached windows should display the name of the qTox instance in titlebar, e.g.
`Zetok - Groupbot (Online)`
- [x] display own name in detached chat titlebar

**Comment by Chiitoo** [comment]
Segfault when removing a chat window: https://gist.github.com/Chiitoo/9d2fd2e09d231846d44d

**Comment by zetok** [comment]
on a16c98d1d4a50a1d55af037d23372cb75efcb6fa
- [x] regression - pressing `Esc`  when changing title of a groupchat closes deteched window – it should just cancel editing title

# 
- [x] detached window is being resized every time it's clicked on in main window - there's nothing really visible about it, until there's enough of content in chatform to trigger visible `Resizing` - https://d.maxfile.ro/ifervafthg.webm
  
  edit: ↑ fixed in new branch

# 
- [x] @Chiitoo's segfault when trying to message friend removed from current detached window: https://gist.github.com/zetok/22ce4548c88788516793

Edit: ↑ dunno whether fixed

**Comment by zetok** [comment]
- [x] segfault when quitting groupchat on 4c040cacfc6b63d17b4c3cc57213a0b510cca707 https://gist.github.com/zetok/25c69544dabe9ab2732f

**Comment by tux3** [comment]
- [x] Adding a friend in a separate window in a circle doesn't show the change in the main window

**Comment by zetok** [comment]
@TheSpiritXIII even with 310f66f9319d2ee4c6bf86dbbfcf83450040525e applied I still got ↓ when leaving groupchat:

```
[19:44:08.551] kernel/qobject.cpp:4753 : Warning: QObject::disconnect: Unexpected null parameter
[19:44:08.551] kernel/qobject.cpp:4753 : Warning: QObject::disconnect: Unexpected null parameter
```
- [ ] some warnings when leaving groupchat

**Comment by tux3** [comment]
- [ ] Going through the friendlist with CTRL+PgUp/PgDown or clicking on a contact won't bring up any minimized chat window, but will still clear new message notifications as if the user looked at it

**Comment by zetok** [comment]
- [x] qTox is not setting an urgency hint on a settings window when it's already open and one clicks on settings button
- [x] also there's a graphical glitch when clicking on it →
  glitch

**Comment by Chiitoo** [comment]
What say you if the window title content were to be flipped?

That is, instead of "$my_name" - "$contact_name" have it "$contact_name" - "$my_name"?

Depending on how long "$my_name" is, as well as on the DE/WM/settings used, the "$contact_name" may not be visible in the task-bar entry.  Of course depending on the length of "$contact_name", it's possible that "$my_name" won't be visible, but at least one would see which contact it is right away.

I guess one option could be making the title scroll, but I'm not sure we want that, nor do I know if it would be easy to implement.

**Comment by zetok** [comment]
@Chiitoo While I personally like `$my_name - $contact_name` more, it's useful only in ~edge cases when someone is running multiple qTox instances. So yeah, `$contact_name - $my_name` should be used.

**Comment by zetok** [comment]
- [x] regression - there is no double circle notification on new messages in groupchat - only with `Group chats always notify` double circle notification appears, but it should appear even without it

**Comment by zetok** [comment]
- [x] regression - there's no blinking icon in tray when message was received

**Comment by Chiitoo** [comment]
The iconic issue can also be seen on Windows builds (yeah, I finally got it built and running!).

**Comment by zetok** [comment]
minimal window size is too small

↑ minimal window size should be big enough to not allow that

**Comment by ovalseven8** [comment]
> regression - detached groupchat - when one clicks to show emoticons, and then changes topic, emoticon selector is shown again when topic is changed
> 
> **EDIT: ↑ apparently only I can reproduce - can someone else confirm that they're affected too?**

Can reproduce it. Tested with latest Lubuntu version. @zetok 

---
- [ ] If I have an extra window for a chat:
  - No Tox icon for the new window in taskbar
  - The qTox-window is blinking if I get a new message. For me it would be better if the Tox icon for the chat is blinking. (Screenshot: http://i.imgur.com/FubQFsl.png | The 'not having blue...' window should blink with a Tox icon)
- [ ] If changing the theme color, it doesn't have an effect for windows that are already in use. At my point of view a small bug, because if I change the Smiley pack it works also for existing windows.

**Comment by agilob** [comment]
@zetok says it's ready to be merged, so if you could fix that conflict, I'll merge it today

**Comment by zetok** [comment]
@agilob that merge conflict is very easy to solve - https://github.com/zetok/qTox/tree/merge1938 ← currently can be `merge --ff` on master.

It's ready functionality-wise, dunno about code.

**Comment by ovalseven8** [comment]
Why not solve the little issues before merging?

**Comment by zetok** [comment]
@ovalseven8 those don't really matter, and can be fixed later on. They are either hard to reproduce by dev, or they affect in minor way functionality related only to new feature this PR introduces.

As such, IMHO it's more beneficial to merge it, and open issues about it, than let it stall and become more problematic to merge, as time will pass and there will be more (more serious) merge conflicts.

**Comment by agilob** [comment]
- [ ] Page up/down to change chat stopped working

**Comment by agilob** [comment]
1. Move splitter max. to left
2. make window smaller
3. open slitter

4.
qtox5

**Comment by agilob** [comment]
1. make window small
2. move splitter max. to left
3. move splitter back to middle
4. move splitter back max. to left
5. column with timestamps is invisible
6. 

qtox6

**Comment by agilob** [comment]
- [ ] whole history is loaded automatically when I open a window, thousands of messages

**Comment by agilob** [comment]
I would say, remove left part of the window and all those issues will be fixed.

**Comment by Chiitoo** [comment]
> whole history is loaded automatically when I open a window, thousands of messages

Does it?  Here it only seems to load one week's worth.

**Comment by tux3** [comment]
I rebased this PR on master, I'm pushing it up for testing in a new multiwindow branch to see if the rebase was successful, and then I'll proceed with merging it into master.

**Comment by zetok** [comment]
@tux3 regressions that aren't ticked off are still present on 2b44161fd685f305381966b5fbbf10e09c4291c7

@agilob I too couldn't reproduce loading whole history - only last 7 days are being loaded.
I know, since I had to manually load history in order to test resizing window on clicking contact.

**Comment by zetok** [comment]
For anyone who would want to test, static builds:
Linux: https://build.tox.chat/view/Clients/job/qTox-testing-qt5.4.2_build_linux_x86-64_release/ ← Qt 5.4.2
https://build.tox.chat/view/Clients/job/qTox-testing_build_linux_x86-64_release/ ← Qt 5.5

windows: https://build.tox.chat/view/Clients/job/qTox-testing_build_windows_x86-64_release/

**Comment by zetok** [comment]
A bit of feedback:
. `[20:45:16] gmscs: so something i notice with the new multi-window qtox is that the settings, add friend and file transfer windows are missing a close button`
. `[20:58:56] gmscs: at least in gtk3*`

**Comment by zetok** [comment]
Since it was rebased and then merged in 7dd66213cbef6d6a6d7d6b2ecc3f89f9d8d8b7b9, closing.

**Pull request closed without merging**
