### PR TITLE
Fix/hide in tray

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4969)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
@Diadlo is the first commit supposed to part of this PR? Your one-line change in the second commit is enough to fix https://github.com/qTox/qTox/issues/4949

**Comment by Diadlo** [comment]
@anthonybilinski Oh.. thanks, was required to compile and test locally with new toktok. Removed

**Comment by anthonybilinski** [comment]
:lgtm_strong:
tested, confirmed works properly now.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4969#-:-L60XQSqeStsSCXzPaDA:bmymy6y)*

**Comment by anthonybilinski** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4969)*

**Pull request merged**
