### PR TITLE
chore: Make building for FreeBSD easier

### PR DESCRIPTION
**Pull request by sudden6**
Add some patches from https://svnweb.freebsd.org/ports/head/net-im/qTox/

@VVD would be nice if you could test this PR

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4013)

### CODE REVIEW

**Comment by VVD** [comment]
FreeBSD 11.0 (without installed net-im/tox) commands to build and run qTox :
```
git clone https://github.com/TokTok/c-toxcore.git c-toxcore
cd c-toxcore
cmake .
gmake
cd -
git clone https://github.com/qTox/qTox
cd qTox
sudo ln -s /usr/local/bin/bash /bin/
./test-pr.sh 4013
mkdir tox
cp -a ../c-toxcore/toxav/*.h ../c-toxcore/toxcore/*.h ../c-toxcore/toxdns/*.h ../c-toxcore/toxencryptsave/*.h tox/
/usr/local/lib/qt5/bin/qmake LIBS+=-L../c-toxcore INCLUDEPATH+=.
gmake
LD_LIBRARY_PATH=../c-toxcore ./qtox
```
Other prerequisites was installed as parts of dependencies for net-im/tox and net-im/qTox.

At least it build, run and open my profile fine.
Audio, video, files and messages didn't tested.

**Comment by Diadlo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[qtox.pro, line 264 at r1](https://reviewable.io:443/reviews/qtox/qtox/4013#-K_6EUowoXa8mk6UdZ8n:-K_6EUowoXa8mk6UdZ8o:bm3ldsu) ([raw file](https://github.com/qtox/qtox/blob/0c81715ad3f781610c234b36958769b878009fbc/qtox.pro#L264)):*
> ```QMake
> 
> unix {
> target.path  = $$PREFIX/bin
> ```

Why without indent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4013)*

**Comment by sudden6** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[qtox.pro, line 264 at r1](https://reviewable.io:443/reviews/qtox/qtox/4013#-K_6EUowoXa8mk6UdZ8n:-K_6H15Y64XWO_SznAkJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0c81715ad3f781610c234b36958769b878009fbc/qtox.pro#L264)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why without indent?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4013)*

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4013#-:-K_6HiNaHGt4hl1p787F:bnfp4nl)*

**Pull request merged**
