### PR TITLE
test(build): check whether code/files have been processed by CMake

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4196)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis/build-ubuntu-14-04.sh, line 189 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMwIdhgmtKCk7tM0s:-KdqMwIdhgmtKCk7tM0t:b-170qu) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L189)):*
> ```Shell
> check_if_differs() {
>     echo "Checking whether files processed by CMake have been committed..."
>     echo ""
> ```

Why we need an empty line?

---

*[.travis/build-ubuntu-14-04.sh, line 190 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMdoLmfufHHYw5mEH:-KdqMdoLmfufHHYw5mEI:b-uwp37p) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L190)):*
> ```Shell
>     echo "Checking whether files processed by CMake have been committed..."
>     echo ""
>     git diff --exit-code
> ```

Can you add comment, that `git diff` return 0 only when there is no changes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4196)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis/build-ubuntu-14-04.sh, line 189 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMwIdhgmtKCk7tM0s:-KdqN81Qz4b0NAZS_qsi:binuyqv) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L189)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why we need an empty line?
</blockquote></details>

To have visual separation between text from `echo` and the output of `git diff`

---

*[.travis/build-ubuntu-14-04.sh, line 190 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMdoLmfufHHYw5mEH:-KdqNkp9fH0L8bDhciM5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L190)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can you add comment, that `git diff` return 0 only when there is no changes?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4196)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis/build-ubuntu-14-04.sh, line 189 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMwIdhgmtKCk7tM0s:-KdqOMZOQND-jp7r9sEa:bhi5o3f) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L189)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

To have visual separation between text from `echo` and the output of `git diff`
</blockquote></details>

What about ` > /dev/null` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4196)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis/build-ubuntu-14-04.sh, line 189 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMwIdhgmtKCk7tM0s:-KdqORjWL0CoN7Xf8ckJ:bx4vim4) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L189)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about ` > /dev/null` ?
</blockquote></details>

For the `git diff --exit-code`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4196)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis/build-ubuntu-14-04.sh, line 189 at r1](https://reviewable.io:443/reviews/qtox/qtox/4196#-KdqMwIdhgmtKCk7tM0s:-KdqOb8Xp3GKZMSUbHBE:bn79gfz) ([raw file](https://github.com/qtox/qtox/blob/df8027e7aad7f858c0c958be6d0a676b896c2b19/.travis/build-ubuntu-14-04.sh#L189)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

For the `git diff --exit-code`
</blockquote></details>

`git diff` is supposed to show what needs to be changed in the PR. With it available, someone can just copy the diff, apply it and update the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4196)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4196#-:-KdqP6FXC9Yl-Oo7R2ms:b-jbsf8z)*

**Pull request merged**
