### PR TITLE
[ui/redesign] Clean group

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3690)

### CODE REVIEW

**Comment by sudden6** [comment]
why is reviewable not required for this PR?

**Comment by zetok** [comment]
reviewable & travis are required only for `master` branch

**Comment by Diadlo** [comment]
@sudden6 #3636

**Comment by sudden6** [comment]
yeah, but https://github.com/qTox/qTox/pull/3692 for example has reviewable required.

**Comment by Diadlo** [comment]
@sudden6 If someone wrote something in reviewable it will have to put "LGTM"

**Comment by antis81** [comment]
@sudden6 @Diadlo @zetok No need to bother "Reviewable" here too much. The **main milestone branch** "ui/redesign" (aka PR #3639) will get the "lgtm" flag, when review is complete and all major tasks there are solved (marked by :ballot_box_with_check:). PR is then merged back into master and cannot be merged into master without "lgtm".

From a political view, you can compare this little team of currently 3 people as a "gremium", which handles a bigger specific (sub-)task.

To visualize the merge strategy a bit better:
sub-PR[1..n] -> ui/redesign -> master

And eventually, to better mark sub-PR's as such, those are prefixed by "[ui/redesign]".

Clear?

**Comment by sudden6** [comment]
I was more interested in the technical detail, why it showed on some PRs but not on this one, didn't know someone disabled it for the branch. thx for the update.

**Comment by antis81** [comment]
It would have actually to be explicitly enabled for branches other than master. :)

**Pull request closed without merging**
