### PR TITLE
fix(UI): Changed tab order to be same with visual order

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3871)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/aboutsettings.ui, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/3871#-KWKES0j78GuBAYOr0S8:-KWKES0k841h1p0Q0mfd:b-qd8ipt) ([raw file](https://github.com/qtox/qtox/blob/2fd07f6a7cb8bdd1cf65bdaad2885c322871e26b/src/widget/form/settings/aboutsettings.ui#L10)):_

> ``` XML
>     <y>0</y>
>     <width>530</width>
>     <height>553</height>
> ```

These changes don't really look relevant, are they?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3871)_

**Comment by Diadlo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/aboutsettings.ui, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/3871#-KWKES0j78GuBAYOr0S8:-KWZtWABi0kKtEif5XDD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2fd07f6a7cb8bdd1cf65bdaad2885c322871e26b/src/widget/form/settings/aboutsettings.ui#L10)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> These changes don't really look relevant, are they?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3871)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3871#-:-KWZvD7Suqq82XWekxto:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3871#-:-KWir8XQ6W6hy6TK1nse:bnfp4nl)_

**Pull request merged**
