### PR TITLE
feat(call): add call end sound

### LINKED ISSUE #4905: [Feature request] Sound on call end
##### Brief Description

A friend suggested to add a sound when a call ends, so you can hear when the connection drops or the other end hangs up even when qTox is in the background.

##### Steps to reproduce

1. let other end hangup audio call

##### Observed Behavior

Call ends silently

##### Expected Behavior

"Bling" sound to indicate the call has ended.

##### Additional Info

The sound has to have an open source license.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #4905

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5056)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Audio is from our outgoing call pcm, reversed, cut, and repeated. I'm not sure how good it is.. couldn't find anything that I liked and fit with out current sound design after searching online for quit a while.

**Comment by tox-user** [comment]
Why does it use `audio.startLoop()`? This sound shouldn't be looped?

**Comment by anthonybilinski** [comment]
Good point, that was a bug. Removed.

**Comment by sudden6** [comment]
Did not test, but code :lgtm_strong: 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5056#-:-L9pw1Zm4_z21gJiPLHF:bxbgycp)*

**Comment by anthonybilinski** [comment]
would be good to get some feedback on the sound used (no technical knowledge needed), here's a bundle of all of our sounds to make it easier, with the new one being "ToxEndCall.pcm". The three can be played with VLC: [sounds.zip](https://github.com/qTox/qTox/files/1949268/sounds.zip)

**Comment by Diadlo** [comment]
@anthonybilinski I think, it's fine. Also, it can be changed later if someone will have better suggestion

**Comment by tox-user** [comment]
@anthonybilinski you should post your sound in a comment in the issue

**Pull request merged**
