### PR TITLE
Undeprecate video

### PR DESCRIPTION
**Pull request by tux3**
This needs testing!
Works On My Machine, but video can be fickle.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4180)

### CODE REVIEW

**Comment by zetok** [comment]
Since travis build fails, probably minimal ffmpeg version needs to be bumped (both in docs and build scripts).

**Comment by tux3** [comment]
It seems the new API was introduced in FFMpeg 3.1, in March 2016.
So it might be a bit early to switch to it, but the code is there.

**Comment by sudden6** [comment]
Can we make this a build time decision and mark the old code as deprecated?

**Comment by tux3** [comment]
We could check LIBAVCODEC_VERSION_INT >= 3747941 at build time, I suppose

**Comment by Diadlo** [comment]
Thanks for PR. Close since #4266 was merged

**Pull request closed without merging**
