### PR TITLE
feat(settings): Export and copy debug log

### LINKED ISSUE #2890: [Idea] Log viewer in settings
Since qTox is a GUI application it would be logical to also have the logfile accessible in the GUI.
I'm thinking about a tab in settings, which shows the content of the logs and allows the user to easily copy them to the clipboard or directly to github.

### PR DESCRIPTION
**Pull request by AliceGrey**
Fixes #2890

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3756)

### CODE REVIEW

**Comment by zetok** [comment]
on c60505fa827e79e12b277eb73c4d3915c89472ec:
- [x] if export file picker gets canceled, log still shows:
  
  ```
  widget/form/settings/advancedform.cpp:111 : Debug: Copied to:  "/qtox.log"
  ```

**Comment by AliceGrey** [comment]
I'll take a look at that

**Comment by AliceGrey** [comment]
*Looks like I messed up my commit with that merge. Fixing it now.

**Comment by AliceGrey** [comment]
Ok sorry about the mess. Commit should be good now and branch should be clean.

**Comment by zetok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/advancedform.cpp, line 105 at r2](https://reviewable.io:443/reviews/qtox/qtox/3756#-KSkK7XPuA_uTXITJvAG:-KSkK7XPuA_uTXITJvAH:b-bioxt7) ([raw file](https://github.com/qtox/qtox/blob/190cbcb897c9bf31a3a9ab0872d884dba1204c9a/src/widget/form/settings/advancedform.cpp#L105)):_

> ``` cpp
> 
>     QFile file(logfile);
>     if(!file.exists())
> ```

Style should be

```
if () // ← space between `if` and parentheses
    1_line;
else
    1_line;

// ↑ newline between last  part of `if` and other code
```

https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#coding-style

Aside from style, `!` is here and in `if`s below unnecessary – just remove it and swap branches.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by zetok** [comment]
on 190cbcb897c9bf31a3a9ab0872d884dba1204c9a
- [x] debug log shows where log is supposed to be saved even though saving was canceled
  
  ```
  Debug: Saving debug log to:  ""
  ```
- [ ] after clicking on `Cancel` interface freezes for a short moment – can something be done about this?
- [x] it should be possible to rename output file

**Comment by AliceGrey** [comment]
I'm not sure what you mean by 

> Aside from style, ! is here and in ifs below unnecessary – just remove it and swap branches.

**Comment by AliceGrey** [comment]
Removed the stray qdebug and made it so the user can name the log. Also added spaces between if statements.

**Comment by AliceGrey** [comment]
I'm not able to reproduce Cancel causing any freezing on linux. I can try the build on Windows if that's where the freezing is occurring.

**Comment by zetok** [comment]
> I'm not sure what you mean by 
> 
> > Aside from style, ! is here and in ifs below unnecessary – just remove it and swap branches.

E.g. 

```
if (!file.exists())
    qDebug() << "No debug file found";
else
    qDebug() << "Found debug log for copying";
```

↓

```
if (file.exists())
    qDebug() << "Found debug log for copying";
else
    qDebug() << "No debug file found";
```

> I'm not able to reproduce Cancel causing any freezing on linux. I can try the build on Windows if that's where the freezing is occurring.

Nah, that happens on Linux.

**Comment by AliceGrey** [comment]
Ah ok I see what you mean now. I'll make those changes. What distro are you having it freeze on? I'm running Arch with QT5 and KDE and I can't get it to freeze so I'm not sure what might be causing it. The dialog window is the built in QT5 dialog function that qtox implements in other functions. So it should function like any other dialog window in qtox.

**Comment by zetok** [comment]
Gentoo, Qt 5.6.1, i3wm.

**Comment by AliceGrey** [comment]
I'm using QT 5.7.0

**Comment by sudden6** [comment]
_[src/widget/form/settings/advancedform.cpp, line 138 at r3](https://reviewable.io:443/reviews/qtox/qtox/3756#-KT0yCXUzBpl9nzUWCl8:-KT0yCXUzBpl9nzUWCl9:b-9c4l9) ([raw file](https://github.com/qtox/qtox/blob/2dbec32c7fe0b497cffe32f9630bf5ba9d14dbf7/src/widget/form/settings/advancedform.cpp#L138)):_

> ``` cpp
>     QClipboard* clipboard = QApplication::clipboard();
> 
>         if (clipboard)
> ```

move the check if the clipboard is accessible to before reading the file and add error handling to the case when the clipboard is inaccessible

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by sudden6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/form/settings/advancedform.cpp, line 98 at r3](https://reviewable.io:443/reviews/qtox/qtox/3756#-KT0zmFmLKzeBkfOZqCX:-KT0zmFoCqfTjAxK1sD3:b-p4guuq) ([raw file](https://github.com/qtox/qtox/blob/2dbec32c7fe0b497cffe32f9630bf5ba9d14dbf7/src/widget/form/settings/advancedform.cpp#L98)):_

> ``` cpp
> void AdvancedForm::on_btnExportLog_clicked()
> {
>     QString savefile = QFileDialog::getSaveFileName(this, tr("Save File"),QDir::homePath(),tr("Logs (*.log)"), 0 ,QFileDialog::DontUseNativeDialog);
> ```

check `savefile` with `isNull()` and `isEmpty()` and exit the function, this could solve the hang @zetok described

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by AliceGrey** [comment]
@sudden6 Ok, taken care of.

**Comment by sudden6** [comment]
_[src/widget/form/settings/advancedform.cpp, line 149 at r4](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTK_gfVXdsPMjAp-qTe:-KTK_gfWnVJrciAB3cl-:b-nfv7d) ([raw file](https://github.com/qtox/qtox/blob/ab910ffa1aed4d2a4006711193020b037064c9d5/src/widget/form/settings/advancedform.cpp#L149)):_

> ``` cpp
>     }
>     else
>         qDebug() << "Unable to access clipboard";
> ```

`else` needs curly brackets if `if` has them.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by sudden6** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/advancedform.cpp, line 120 at r5](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTVqq-MBhpssuxql8Il:-KTVqq-NAfGVLNDT_roH:b-n8pkdd) ([raw file](https://github.com/qtox/qtox/blob/5193706a581222104fb491c2035e4fd44dbbf072/src/widget/form/settings/advancedform.cpp#L120)):_

> ``` cpp
>         qDebug() << "Successfully copied to: " << savefile;
>     else
>         qDebug() << "File was not copied";  
> ```

Found some stray spaces at the end of this line.

Also, please leave a comment if you fix/change something in a PR, because we don't get notifications if you don't.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by AliceGrey** [comment]
@sudden6 Ok I'll make sure to leave comments. I fixed the whitespace and enabled "Visualize whitespace" in my editor so I don't miss that.

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756#-:-KTa1e7NOFpii9xF9CAi:bnfp4nl)_

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

_[src/widget/form/settings/advancedform.cpp, line 113 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa4LLYLYxuCdB5eh_8:-KTa4LLZorDaY7lq5oUg:boxwvk6) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L113)):_

> ``` cpp
>         qDebug() << "Found debug log for copying";
>     else
>         qDebug() << "No debug file found";
> ```

Shouldn't be `return` there or something like that?

---

_[src/widget/form/settings/advancedform.cpp, line 117 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa4um1veISHdcf5Pfl:-KTa4um2oKYG5QFoD91R:bvhgqy) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L117)):_

> ``` cpp
>     QFile::copy(logfile, savefile);
>     QFile copyfile(savefile);
>     if (copyfile.exists())
> ```

Better use result of `QFile::copy` here. Also, if `savefile` already existed before copy,  new file don't overwrite old. [Proof](https://doc.qt.io/qt-4.8/qfile.html#copy)

---

_[src/widget/form/settings/advancedform.cpp, line 136 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa7XuK_7GoKmkf8kg4:-KTa7XuLbuOSLev81FIp:b-8tu8wn) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L136)):_

> ``` cpp
> 
>     QClipboard* clipboard = QApplication::clipboard();
>     if (clipboard)
> ```

IMO, there better will be early break. I.e.

```
if (!succes) 
{ 
printError();
return;
}
// some code
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by AliceGrey** [comment]
@Diadlo Ok those have been taken care of. Hopefully they look good.

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

_[src/widget/form/settings/advancedform.cpp, line 136 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa7XuK_7GoKmkf8kg4:-KTcQRixt_aLeSOp8eGy:b-4jmx99) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L136)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> IMO, there better will be early break. I.e.
> 
> ```
> if (!succes) 
> { 
> printError();
> return;
> }
> // some code
> ```
> 
> </details>
> If you don't agree, say about it (too be sure, that you read it :))

---

_[src/widget/form/settings/advancedform.cpp, line 98 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcOGSWDOJrzIMqGuQD:-KTcOGSXyH7nQ4RXQiWw:b-lkz23j) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L98)):_

> ``` cpp
> void AdvancedForm::on_btnExportLog_clicked()
> {
>     QString savefile = QFileDialog::getSaveFileName(this, tr("Save File"),QDir::homePath(),tr("Logs (*.log)"), 0 ,QFileDialog::DontUseNativeDialog);
> ```

Please, fix problem with spaces and commas: Before comma should not be a space, but should be after comma

---

_[src/widget/form/settings/advancedform.cpp, line 140 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcOkg9yJIkVR8M5Unp:-KTcOkgAPVEsCflHjCu9:b-p971tm) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L140)):_

> ``` cpp
>     else
>     {
>         qDebug() << "Found debug log for copying";
> ```

Remove `else` part of invert `if` like zetok write [above](https://github.com/qTox/qTox/pull/3756#issuecomment-250331166)

---

_[src/widget/form/settings/advancedform.cpp, line 146 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcPR5_yMfu7Jp_fcnt:-KTcPR5aGmrfMEBM7Opr:b-ejk9au) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L146)):_

> ``` cpp
>     if (clipboard)
>     {
>         if (file.open(QIODevice::ReadOnly | QIODevice::Text))
> ```

Seems, `debugtext` didn't used outside this scope. What about move declaration here?
And you don't exist, if can't open file. And don't write anything.

---

_[src/widget/form/settings/advancedform.cpp, line 151 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcQLBqm9YpO3mFZrAd:-KTcQLBqm9YpO3mFZrAe:bmd7e8o) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L151)):_

> ``` cpp
>             debugtext = in.readAll();
>         }
>         file.close();
> ```

Also, IIRC, file should be closed only if it was opened successful, isn't it?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756)_

**Comment by AliceGrey** [comment]
@Diadlo Ok I've got most of them done. I'm not really sure what you mean by 

> Seems, debugtext didn't used outside this scope. What about move declaration here? And you don't exist, if can't open file. And don't write anything.

What I think you mean is changing the if statement from:

```
if (file.open(QIODevice::ReadOnly | QIODevice::Text))
        {
            QTextStream in(&file);
            debugtext = in.readAll();
            file.close();
        }
```

to something like:

```
if (file.open(QIODevice::ReadOnly | QIODevice::Text))
        {
            QTextStream in(&file);
            QString debugtext = in.readAll();
            file.close();
        }
        else
        {
            qDebug() << "Unable to open file for copying to clipboard";
            return;
        }
```

**Comment by Diadlo** [comment]
Sorry, for my unclear explanation. I mean:

```
QString debugtext;
if (file.open(QIODevice::ReadOnly | QIODevice::Text))
{
    QTextStream in(&file);
    debugtext = in.readAll();
    file.close();
}
```

OR

```
if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
{
    qDebug() << "Unable to open file for copying to clipboard";
    return;
}

QTextStream in(&file);
QString debugtext = in.readAll();
file.close();
```

**Comment by AliceGrey** [comment]
@Diadlo Ok Done!

---

Review status: 2 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

_[src/widget/form/settings/advancedform.cpp, line 105 at r2](https://reviewable.io:443/reviews/qtox/qtox/3756#-KSkK7XPuA_uTXITJvAG:-KTd9xbNi434PXvCLPC1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/190cbcb897c9bf31a3a9ab0872d884dba1204c9a/src/widget/form/settings/advancedform.cpp#L105)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Style should be
> 
> ```
> if () // ← space between `if` and parentheses
>     1_line;
> else
>     1_line;
> 
> // ↑ newline between last  part of `if` and other code
> ```
> 
> https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#coding-style
> 
> Aside from style, `!` is here and in `if`s below unnecessary – just remove it and swap branches.
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 98 at r3](https://reviewable.io:443/reviews/qtox/qtox/3756#-KT0zmFmLKzeBkfOZqCX:-KTd9yB72VAUI3ZOgyxK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2dbec32c7fe0b497cffe32f9630bf5ba9d14dbf7/src/widget/form/settings/advancedform.cpp#L98)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> check `savefile` with `isNull()` and `isEmpty()` and exit the function, this could solve the hang @zetok described
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 138 at r3](https://reviewable.io:443/reviews/qtox/qtox/3756#-KT0yCXUzBpl9nzUWCl8:-KTd9pknnilB_u4AfouB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2dbec32c7fe0b497cffe32f9630bf5ba9d14dbf7/src/widget/form/settings/advancedform.cpp#L138)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> move the check if the clipboard is accessible to before reading the file and add error handling to the case when the clipboard is inaccessible
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 149 at r4](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTK_gfVXdsPMjAp-qTe:-KTd9pGjn-W1eYEBZhA6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ab910ffa1aed4d2a4006711193020b037064c9d5/src/widget/form/settings/advancedform.cpp#L149)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> `else` needs curly brackets if `if` has them.
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 120 at r5](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTVqq-MBhpssuxql8Il:-KTd9vTDc4DDkckqXshZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5193706a581222104fb491c2035e4fd44dbbf072/src/widget/form/settings/advancedform.cpp#L120)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Found some stray spaces at the end of this line.
> 
> Also, please leave a comment if you fix/change something in a PR, because we don't get notifications if you don't.
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 113 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa4LLYLYxuCdB5eh_8:-KTd9x3lC7ehPLiYidPR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L113)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Shouldn't be `return` there or something like that?
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 117 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa4um1veISHdcf5Pfl:-KTd9wYxUGxYrEp7jy72:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L117)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Better use result of `QFile::copy` here. Also, if `savefile` already existed before copy,  new file don't overwrite old. [Proof](https://doc.qt.io/qt-4.8/qfile.html#copy)
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 136 at r6](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTa7XuK_7GoKmkf8kg4:-KTd9rdHJzeSojx4a4-r:b-838vte) ([raw file](https://github.com/qtox/qtox/blob/8905a1a070d4e5799e213e84203192fffd1a0942/src/widget/form/settings/advancedform.cpp#L136)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> If you don't agree, say about it (too be sure, that you read it :))
> </details>
> Ok :)

---

_[src/widget/form/settings/advancedform.cpp, line 98 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcOGSWDOJrzIMqGuQD:-KTd9yaxM7p4poGAWSxk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L98)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Please, fix problem with spaces and commas: Before comma should not be a space, but should be after comma
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 140 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcOkg9yJIkVR8M5Unp:-KTd9uku2PBPhNV20imZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L140)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Remove `else` part of invert `if` like zetok write [above](https://github.com/qTox/qTox/pull/3756#issuecomment-250331166)
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 146 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcPR5_yMfu7Jp_fcnt:-KTd9rJ2eJYfjUMDrg5z:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L146)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Seems, `debugtext` didn't used outside this scope. What about move declaration here?
> And you don't exist, if can't open file. And don't write anything.
> </details>
> Done.

---

_[src/widget/form/settings/advancedform.cpp, line 151 at r7](https://reviewable.io:443/reviews/qtox/qtox/3756#-KTcQLBqm9YpO3mFZrAd:-KTd9qUfJVAklyyGfnCy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4bc7d7f19f5ece2e9de6c46f2ab651d82245d190/src/widget/form/settings/advancedform.cpp#L151)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Also, IIRC, file should be closed only if it was opened successful, isn't it?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756#-:-KTdA-pkEJCH9U19ehJN:b-6qlrvk)_

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756#-:-KTdCCYnwuKE0N024VL9:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3756#-:-KTdDPy-X7kEfL-ZSrZg:bnfp4nl)_

**Pull request merged**
