### PR TITLE
make it easier to build on Fedora

### PR DESCRIPTION
**Pull request by quatrox**
Updated some build dependencies for Fedora.  There are more, but they will come later.
Also, make sure the build script uses qmake-qt5 on Fedora. If not, it will use qt4 which will create problems.

### CODE REVIEW

**Comment by zetok** [comment]
@quatrox use spaces instead of tabs

**Comment by quatrox** [comment]
@zetok Thanks for noticing. I have corrected it now.

**Comment by zetok** [comment]
@quatrox mind removing 770c243bdf7df075cb2024520b479b52c8fd198a from this PR and making a new one?

**Comment by quatrox** [comment]
Sure. I just did.  So if I understand the work flow correctly, I should wait for on PR to be completed before starting with the next.

PS!
   Note that when I revert stuff, I use soft reset. I hope that is the correct way to do it.

**Comment by zetok** [comment]
@quatrox 

> Sure. I just did. So if I understand the work flow correctly, I should wait for on PR to be completed before starting with the next.

err, not quite, you can send PRs to unrelated things in parallel - just make sure that PR is about what it says it is `;)`

What you want to do is to make pull requests from branches other than master - e.g. `$ git checkout -b new_pr && git commit && git push origin new_pr`, then just make a PR from that branch
↑ that would be useful only in a case where you have not committed changes yet though, and wouldn't be helpful when you have already committed own stuff on your `master`.

What you would want to do is something like:

``` bash
git fetch upstream  # get latest changes from upstream
git checkout upstream/master -b new_pr  # checkout new branch "new_pr", based on upstream branch "master"
# make some changes
git commit -am "changes"  # commit your changes with commit message "changes"
git push origin new_pr  # push your branch with changes to your fork
```

# 

> Note that when I revert stuff, I use soft reset. I hope that is the correct way to do it.

Looks good to me.

Well, if you'll need further help, feel free to pop on IRC or ask here for it `:)`

**Pull request merged**
