### PR TITLE
feature(paste): Implement pasting images from clipboard

### LINKED ISSUE #1290: Can't past screenshot after hitting print screen key
After hitting print screen key, nothing happen when I try to paste in the message box. In Skype for example, doing it shows the screenshot in the message box and pressing enter sends the image to the contact.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #1290

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4644)

### CODE REVIEW

**Comment by Diadlo** [comment]
s/feature/feat/ in commit message

**Comment by anthonybilinski** [comment]
Done

**Comment by Talkless** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/widget/tool/chattextedit.cpp, line 65 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5SrLTtFQKlaGr8CEg:-Ku5SrLUerAF6qHfBsGA:br23r6l) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L65)):*
qTox coding convetion neds { } for single-statement ifs.

https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks

> // Single line control statements are still required to use braces.

Also, maybe it would be simpler to use `&&` here instead of two if's?

---

*[src/widget/tool/chattextedit.cpp, line 89 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5TkCXr7vNUJQnZoV1:-Ku5TkCXr7vNUJQnZoV2:bhzhqti) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L89)):*
> ```cpp
> bool ChatTextEdit::paste(QKeyEvent* event)
> {
>     QClipboard* clipboard = QApplication::clipboard();
> ```

could be `const QClipboard* const clipboard`

---

*[src/widget/tool/chattextedit.cpp, line 93 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5ToMEdq96lzokKFLz:-Ku5ToMEdq96lzokKFM-:b-r2msiq) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L93)):*
> ```cpp
>         return false;
> 
>     const QMimeData *mimeData = clipboard->mimeData();
> ```

const QMimeData* const mimeData

---

*[src/widget/tool/chattextedit.cpp, line 93 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5U04aJW6k2lTV2h8C:-Ku5U04aJW6k2lTV2h8D:b9b30rh) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L93)):*
> can be NULL if the given mode is not supported by the platform

https://doc.qt.io/qt-5/qclipboard.html#mimeData

---

*[src/widget/tool/chattextedit.cpp, line 97 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5UBCHv3wEjDdXxF5P:-Ku5UBCHv3wEjDdXxF5Q:bpceoa4) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L97)):*
> ```cpp
>         return false;
> 
>     QPixmap pixmap(clipboard->pixmap());
> ```

const QPixmap

---

*[src/widget/tool/chattextedit.h, line 38 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5UHSjBJQ93pbOsuwg:-Ku5UHSjBJQ93pbOsuwh:btkj71e) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.h#L38)):*
> ```objc
>     void tabPressed();
>     void keyPressed();
>     void pasteImage(QPixmap pixmap);
> ```

const QPixmap& pixmap ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644)*

**Comment by noavarice** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 798 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku62W283d5YctCQDezE:-Ku62W283d5YctCQDezF:bgtukch) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/form/chatform.cpp#L798)):*
> ```cpp
> }
> 
> void ChatForm::onImagePasted(QPixmap pixmap)
> ```

Why did you declare another slot instead of using single, since there are equal action are made?

---

*[src/widget/tool/chattextedit.cpp, line 23 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku62qog52NHvMNRLBQv:-Ku62qog52NHvMNRLBQw:b-xng43n) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L23)):*
> ```cpp
> #include "src/widget/translator.h"
> #include <QKeyEvent>
> #include <QApplication>
> ```

Sort headers by name

---

*[src/widget/tool/chattextedit.cpp, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku64IKArGy8IZ_ykpsP:-Ku64IKArGy8IZ_ykpsQ:b-euwbj0) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L45)):*
> ```cpp
> {
>     int key = event->key();
>     if ((key == Qt::Key_Enter || key == Qt::Key_Return) && !(event->modifiers() & Qt::ShiftModifier)) {
> ```

Consider using `switch(key)`. Also there is a block of code which executes every time this function is called -- the last ones. Do you check that adding `return` several times this does not affect key pressing functionality?

---

*[src/widget/tool/chattextedit.cpp, line 90 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku63rKN6KxbyKMyqFuO:-Ku63rKN6KxbyKMyqFuP:by3x8f8) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L90)):*
> ```cpp
> {
>     QClipboard* clipboard = QApplication::clipboard();
>     if (!clipboard)
> ```

Add braces

---

*[src/widget/tool/chattextedit.cpp, line 94 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku63vMW8eXf5JLtBQ2q:-Ku63vMW8eXf5JLtBQ2r:by3x8f8) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L94)):*
> ```cpp
> 
>     const QMimeData *mimeData = clipboard->mimeData();
>     if (!mimeData->hasImage())
> ```

Add braces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 4 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 798 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku62W283d5YctCQDezE:-Ku6_bq8zp1umuucMADn:b-d2mxv) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/form/chatform.cpp#L798)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why did you declare another slot instead of using single, since there are equal action are made?
</blockquote></details>

Removed both slots and slotted into sendImage directly. Changed the directory and filenames from "screenshot" to "image" so that image pasted from clipboard aren't named/stored under "screenshots".

---

*[src/widget/tool/chattextedit.cpp, line 23 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku62qog52NHvMNRLBQv:-Ku6bDYn-ujTPGqzEDJf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L23)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Sort headers by name
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku64IKArGy8IZ_ykpsP:-Ku6bXus-ID6ENXkmIOo:b9eq23v) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L45)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Consider using `switch(key)`. Also there is a block of code which executes every time this function is called -- the last ones. Do you check that adding `return` several times this does not affect key pressing functionality?
</blockquote></details>

The emit keyPressed() and keyPressEvent(event) used to be inside an else. They are only executed outside a branch after I returned from each branch. key presses do still work.

Because most of the if statements are combined with non-key based evaluation, including non constexpr calls, I don't think switch would be better. Would need a case key_val: if(other statement), which seems worse.

---

*[src/widget/tool/chattextedit.cpp, line 65 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5SrLTtFQKlaGr8CEg:-Ku62QZZ8DA2bBJrW_Uu:b-7ni1u4) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L65)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

qTox coding convetion neds { } for single-statement ifs.

https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks

> // Single line control statements are still required to use braces.

Also, maybe it would be simpler to use `&&` here instead of two if's?
</blockquote></details>

changed to &&

---

*[src/widget/tool/chattextedit.cpp, line 89 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5TkCXr7vNUJQnZoV1:-Ku62YHXb0nU3vzNx3bq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L89)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

could be `const QClipboard* const clipboard`
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 90 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku63rKN6KxbyKMyqFuO:-Ku6d7MLgGV9YLH04rBl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L90)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Add braces
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 93 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5ToMEdq96lzokKFLz:-Ku62ak3skhD9kLAMrv6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L93)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QMimeData* const mimeData
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 93 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5U04aJW6k2lTV2h8C:-Ku62lQsCu6pZK1hkxXq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L93)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

> can be NULL if the given mode is not supported by the platform

https://doc.qt.io/qt-5/qclipboard.html#mimeData
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 94 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku63vMW8eXf5JLtBQ2q:-Ku6dHdkVN1vT8bWMkmp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L94)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Add braces
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 97 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5UBCHv3wEjDdXxF5P:-Ku62nPmkbKnqMDxMp89:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L97)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QPixmap
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.h, line 38 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5UHSjBJQ93pbOsuwg:-Ku6dXSHq_znOT5zqhEf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.h#L38)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QPixmap& pixmap ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 793 at r2](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku8l0kLiDKt9tjo4aTA:-Ku8l0kLiDKt9tjo4aTB:b-90hg08) ([raw file](https://github.com/qtox/qtox/blob/f652842bc944b02723c10cab3b81ff124294bf85/src/widget/form/chatform.cpp#L793)):*
> ```cpp
> void ChatForm::sendImage(const QPixmap& pixmap)
> {
>     // Create dir for screenshots
> ```

No need for comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644#-:-Ku8nQ0769CWv_4_LwNI:b-jbsf8z)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[src/widget/tool/chattextedit.cpp, line 97 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5UBCHv3wEjDdXxF5P:-KuPH4RLG85nsau4C-2G:bl9y3ho) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L97)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

is it guaranteed that `QPixmap` can decode the image sucessfully? If not another check would be good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644)*

**Comment by anthonybilinski** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/widget/form/chatform.cpp, line 793 at r2](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku8l0kLiDKt9tjo4aTA:-KuQ3XPq5EGCdJ_FmAhL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f652842bc944b02723c10cab3b81ff124294bf85/src/widget/form/chatform.cpp#L793)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

No need for comment
</blockquote></details>

Done.

---

*[src/widget/tool/chattextedit.cpp, line 97 at r1](https://reviewable.io:443/reviews/qtox/qtox/4644#-Ku5UBCHv3wEjDdXxF5P:-KuQ3WQ7ubwaIyDJJ5ji:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f86b222181d6586c15fd57b0fdb231920fa49976/src/widget/tool/chattextedit.cpp#L97)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

is it guaranteed that `QPixmap` can decode the image sucessfully? If not another check would be good.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4644#-:-KuQAIcvhDYr3l2mWAda:b-jbsf8z)*

**Pull request merged**
