### PR TITLE
revert: "refactor: Added  to include path and exclude it from all includes"

### PR DESCRIPTION
**Pull request by zetok**
Revert needed, since otherwise there is no way to do automatic sorting
of includes.
Also reverted change to the docs, as leaving it would make incorrect
docs.

In case of conflicts, includes were sorted according to the coding
standards from #3839.

This reverts commit b4a9f04f925770b221bf0341fe81b107784d0865.
This reverts commit 592112296012a2159f09571bcff93066b8b6f847.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3986)

### CODE REVIEW

**Comment by Diadlo** [comment]
Standard form #3839 still not approved, so it's time to discuss.
> no way to do automatic sorting

`grep "#include \"" | sort` ?

**Comment by zetok** [comment]
@Diadlo how to use `sort` to separate corresponding to .cpp `.h`, directory-level includes and project-level includes?

**Comment by Diadlo** [comment]
@zetok By module name?
`audio|video|core|...`

**Comment by zetok** [comment]
@Diadlo could you elaborate?

**Comment by Diadlo** [comment]
Detect all wrong local includes
```
MODULES="audio|video|core|widget"
cat file | egrep "#include <($MODULES).+>"
```

**Comment by zetok** [comment]
@Diadlo how does that sort & separate different types of includes?

**Comment by Diadlo** [comment]
```
MODULES="audio|video|core|widget"
WRONG = `cat file | egrep "#include <($MODULES).+>"`
LOCAL_INCLUDES = `cat file | grep "#include \"" | sort`
GLOBAL_INCLUDES = `cat file | grep "#include <" | sort`
```

**Comment by zetok** [comment]
@Diadlo yes, but how to do the sorting of "local" includes correctly & automatically?

**Comment by Diadlo** [comment]
I will think about it

**Comment by zetok** [comment]
@Diadlo the alternative is using clang stuff for the automatic & enforceable include formatting, but it requires having `src/`.

**Comment by zetok** [comment]
@Diadlo , @sudden6 ping?

**Comment by Diadlo** [comment]
:lgtm_strong: 

---

Review status: 0 of 119 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3986#-:-KZtx8mwRFRdp4HaoeP-:b-uwkowd)*

**Comment by sudden6** [comment]
:lgtm: 

---

Review status: 0 of 119 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3986#-:-K_A08lasdNAY0sJ4bpn:bg7igkv)*

**Comment by zetok** [comment]
@sudden6 stale lgtm

**Comment by sudden6** [comment]
:lgtm_strong: 

---

Reviewed 1 of 119 files at r1.
Review status: 1 of 119 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3986#-:-K_AJxVYmTPuZ453a6k3:b-uwkowd)*

**Pull request merged**
