### PR TITLE
Refactor/profile

### PR DESCRIPTION
**Pull request by sudden6**
Something that caught my attention while doing other refactors.

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6226)

### CODE REVIEW

**Review by anthonybilinski — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6226)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
Second commit looks good, will hold off approving until 6225 is updated since this is based on top of it and there are a couple comments there.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6226#-:-MFn0hdh9LTovIlq40IJ:b-az060u)* status: 0 of 1 LGTMs obtained

**Comment by sudden6** [comment]
#6225 is now approved, waiting for lgtm

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 6 files at r1, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6226#-:-MFq01Bc--0H5H7Uzehy:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
