### PR TITLE
Fix #2460

### LINKED ISSUE #2460: "Ligth icon" is grayed out because when qTox is starting I didn't have "Show system tray icon" checked
If I have "Show sytem tray icon" checked, then when qTox would start "Light icon" wouldn't be grayed out

### PR DESCRIPTION
**Pull request by TheNain38**
Fix #2460

### CODE REVIEW

**Comment by agilob** [comment]
Could you make commit message more meaningful?

**Comment by TheNain38** [comment]
Is it better?

**Comment by agilob** [comment]
o/ thanks

Will be merged when we unfreeze master.

**Comment by TheNain38** [comment]
Thanks

**Comment by TheNain38** [comment]
@agilob Btw, Do you know when the new API in toxcore will be pushed?

**Comment by agilob** [comment]
Watch this PR: https://github.com/tux3/qTox/pull/2456 and ask zetok or tux3. No idea.

**Comment by TheNain38** [comment]
Could you merge this please?

**Pull request merged**
