### PR TITLE
Removed uneccessary for loop in markdown and url parsing.

### PR DESCRIPTION
**Pull request by anoadragon453**
We don't need to parse every line, just do one pass over.

Works in my testing, please test before merging.

### CODE REVIEW

**Comment by zetok** [comment]
Could you rebase the PR on newest master?

**Comment by anoadragon453** [comment]
@zetok rebased.

**Comment by PKEv** [comment]
Stopped working local references, if the text is written in a few lines

for example, the message:

```
text 
file:///D:/QtProgects 
text
```

don't work

**Comment by anoadragon453** [comment]
Thanks for the test case, will check it out in a bit.

**Comment by PKEv** [comment]
#3075

**Comment by anoadragon453** [comment]
@PKEv What I've found with your test case is that the lines after the `file://` get included in the file path, i.e.

Instead of navigating to `file:///D:/QtProgects ` we navigate to `file:///D:/QtProgects <br/><br/>text`.

I'll try to fix this ASAP.

**Comment by anoadragon453** [comment]
@PKEv Fixed in #3077. Feel free to test further. Thanks.

**Pull request merged**
