### PR TITLE
docs(INSTALL.md): remove instructions for unsupported by qTox ubuntu

### PR DESCRIPTION
**Pull request by zetok**
Regarding https://github.com/tux3/qTox/issues/390#issuecomment-195701732

### CODE REVIEW

**Comment by NicoHood** [comment]
Maybe you should clearly state that 14.04 is too old to compile the source and not only make it disappear. Thx for clarifying.

**Comment by zetok** [comment]
> Maybe you should clearly state that 14.04 is too old to compile the source and not only make it disappear.

Well, technically, given enough of effort, it's possible to compile qTox on 14.04 - e.g. that's what is being done on travis. The problem that 14.04 has is that some libs are too old, and some are missing, which would make it really hard for someone to compile qTox there, since they would have to compile all missing dependencies first.

Thus, 14.04 is not really "supported" when it comes to compiling, but if someone wanted to, they could compile it there.

I.e. 14.04 is old enough to make compiling qTox there really problematic (thus unsupported), but not too old to completely exclude a possibility of qTox being compiled there.

With that being said, I'm in for removing it since there's crucial part that is needed for compiling not provided in INSTALL.md, and I don't think that anyone is willing to write & maintain one.

**Comment by sudden6** [comment]
@zetok Maybe you could add the above in a shortened form into INSTALL.md? i.e. it is possible, but officially unsupported?

**Comment by zetok** [comment]
@sudden6 I wonder if it's needed – i.e. no instructions for <15.04 should pretty much say that – and it's always possible to compile qTox on $distro, provided that there's enough effort put into compiling deps – and that falls into "unsupported" category by default.

**Comment by sudden6** [comment]
that makes sense, ok then we just remove it

**Pull request merged**
