### PR TITLE
Get basic core encryption funcionality up, still needs to be hooked up to UI and actual usage

### PR DESCRIPTION
**Pull request by dubslow**
Good basis for e.g. the history branch #423 to use (though is independent of that PR)

### CODE REVIEW

**Comment by dubslow** [comment]
It's in a commit note, but this also depends on irungentoo/toxcore#1114 being merged. Should probably wait until then for this.

**Comment by dubslow** [comment]
I'm a bit hesitant about all those memory deep copies with returning raw QByteArrays everywhere, but it might be better than ensuring the caller cleans up memory allocated in the functions... but then again maybe not... thoughts are welcome.

Ooops, misclick trying to comment...

**Comment by krepa098** [comment]
QByteArray is copy-on-write. You can also use QByteArray to allocate memory and pass QByteArray::data() to tox.

> but it might be better than ensuring the caller cleans up memory allocated in the functions

Yes.

**Comment by dubslow** [comment]
Misclicks of the century with this PR

**Comment by dubslow** [comment]
I'm closing this since it's intertwined with and improved in the history branch

**Pull request closed without merging**
