### PR TITLE
Fancy screengraber

### PR DESCRIPTION
**Pull request by Papierkorb**
This PR replaces https://github.com/tux3/qTox/pull/1462 - Removed all traces of previously added binary files from the git history

See the linked PR for earlier discussions on this feature

### CODE REVIEW

**Comment by Papierkorb** [comment]
The merge conflict is auto resolved by git

**Comment by tux3** [comment]
The merge conflict was a bit involved to resolve now due to the accumulated changes, so rebased on master and merged in 426fd7174534757892f79c60f1c02ccabe166438

**Comment by agilob** [comment]
wow this is great!

**Comment by ProMcTagonist** [comment]
I LOVE YOU ALL

**Pull request closed without merging**
