### PR TITLE
docs(CONTRIBUTING): add a guideline to not use dynamic casts/RTTI

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3744)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KSWmwTmywqCvJ_GYFxn:bnfp4nl)_

**Comment by zetok** [comment]
@antis81 , @Diadlo , @initramfs are you fine with the change?

**Comment by initramfs** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[CONTRIBUTING.md, line 316 at r1](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSdWu4nAhc7IV9UQC_f:-KSdWu4oOUkZryh_Jh3r:bc6ypnd) ([raw file](https://github.com/qtox/qtox/blob/691f23962de0dd6b5def24de22046d83fe063397/CONTRIBUTING.md#L316)):_

> ``` Markdown
> ## Dynamic casts / RTTI
> 
> Don't. Instead use `qobject_cast()`.
> ```

This implies you can replace `dynamic_cast` with `qobject_cast` which you can't (this only works when dealing with Qt objects).

Change to:

> qTox is compiled without support for RTTI, as such PRs making use of `dynamic_cast` will fail to compile and may be rejected on these basis. For manipulating Qt-based objects, use `qobject_cast` instead.

---

_[CONTRIBUTING.md, line 320 at r1](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSdWT02_AQjUjDHAgUj:-KSdWT02_AQjUjDHAgUk:b-1tp2w) ([raw file](https://github.com/qtox/qtox/blob/691f23962de0dd6b5def24de22046d83fe063397/CONTRIBUTING.md#L320)):_

> ``` Markdown
> Justification:
> 
> > 5-6% space savings, and "The `qobject_cast()` function behaves similarly to
> ```

Does the "5-6% space savings" refer to the size of the compiled binary or memory usage? That needs to be cleared up. In the case of memory usage, the figure should be removed completely with a generic statement claiming "better memory usage" given that you can't assume the savings are 5-6% across all platforms and machines.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744)_

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[CONTRIBUTING.md, line 316 at r1](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSdWu4nAhc7IV9UQC_f:-KSd_7ujY4L_NmyxBRo-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/691f23962de0dd6b5def24de22046d83fe063397/CONTRIBUTING.md#L316)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> This implies you can replace `dynamic_cast` with `qobject_cast` which you can't (this only works when dealing with Qt objects).
> 
> Change to:
> 
> > qTox is compiled without support for RTTI, as such PRs making use of `dynamic_cast` will fail to compile and may be rejected on these basis. For manipulating Qt-based objects, use `qobject_cast` instead.
> > </details>
> > Done.

---

_[CONTRIBUTING.md, line 320 at r1](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSdWT02_AQjUjDHAgUj:-KSd_8rFCHdzyci-McaY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/691f23962de0dd6b5def24de22046d83fe063397/CONTRIBUTING.md#L320)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Does the "5-6% space savings" refer to the size of the compiled binary or memory usage? That needs to be cleared up. In the case of memory usage, the figure should be removed completely with a generic statement claiming "better memory usage" given that you can't assume the savings are 5-6% across all platforms and machines.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744)_

**Comment by initramfs** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 320 at r1](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSdWT02_AQjUjDHAgUj:-KSddiPhdd8HlJNR6GC9:bsfr9d4) ([raw file](https://github.com/qtox/qtox/blob/691f23962de0dd6b5def24de22046d83fe063397/CONTRIBUTING.md#L320)):_
Rather than having a heading that says justification and listing a reason, perhaps just a paragraph? E.g.

> Compiling qTox without RTTI support gives up to 5~6% size reductions on compiled binary files. The usage of `dynamic_cast` can also be completely mitigated when dealing with Qt objects through use of `qobject_cast` which behaves very much like C++'s `dynamic_cast` but without the RTTI overhead.

I also added "up to" in the paragraph to stress that it's not always 5~6%.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744)_

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 320 at r1](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSdWT02_AQjUjDHAgUj:-KSdizmUcw-hGhABIzY0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/691f23962de0dd6b5def24de22046d83fe063397/CONTRIBUTING.md#L320)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Rather than having a heading that says justification and listing a reason, perhaps just a paragraph? E.g.
> 
> > Compiling qTox without RTTI support gives up to 5~6% size reductions on compiled binary files. The usage of `dynamic_cast` can also be completely mitigated when dealing with Qt objects through use of `qobject_cast` which behaves very much like C++'s `dynamic_cast` but without the RTTI overhead.
> 
> I also added "up to" in the paragraph to stress that it's not always 5~6%.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744)_

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KSdjecGeMTdAZ0YCvII:bnfp4nl)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 317 at r2](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSglADdIYcx-vlMFqBD:-KSglADdIYcx-vlMFqBE:bdy8ify) ([raw file](https://github.com/qtox/qtox/blob/87a4fbecdb2774ae465a82a3f9a82c318a433715/CONTRIBUTING.md#L317)):_

> ``` Markdown
> 
> qTox is compiled without support for RTTI, as such PRs making use of
> `dynamic_cast()` will fail to compile and may be rejected on these basis. For
> ```

this basis?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744)_

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KShkaX86X5YqAj5Q6HD:bnfp4nl)_

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 317 at r2](https://reviewable.io:443/reviews/qtox/qtox/3744#-KSglADdIYcx-vlMFqBD:-KSi_5wMWPqToqyREsi0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/87a4fbecdb2774ae465a82a3f9a82c318a433715/CONTRIBUTING.md#L317)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> this basis?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744)_

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KSiiFpBDvkkpVn5ZG8V:bnfp4nl)_

**Comment by antis81** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KSilSpLVeBdogIZwgiz:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KSjMeoPDxPtrU-1myDz:bnfp4nl)_

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3744#-:-KSpk0mk2kqPltFLsqoG:bnfp4nl)_

**Pull request merged**
