### PR TITLE
chore(build): enable ASLR and DEP protection for windows builds

### LINKED ISSUE #3452: Address space layout randomization
OS: Windows 7 x64
qTox version: qTox version v1.4.1.1-g06d78dc

Reproducible: Always

qTox does not appear to be using ASLR (Address space layout randomization) https://en.wikipedia.org/wiki/Address_space_layout_randomization on Windows. I checked this using Process Explorer.

ASLR helps improve security of a program.

### PR DESCRIPTION
**Pull request by zetok**
Fixes #3452.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3976)

### CODE REVIEW

**Comment by zetok** [comment]
Someone needs to test whether this doesn't break windows builds.

**Comment by Diadlo** [comment]
From IRC
```
[03:32] <nehik> I compiled and tested qTox with this PR https://github.com/qTox/qTox/pull/3976 and everything appears to work.
```

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3976)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3976#-:-K_qMVIljT082dd4QKJq:b-jbsf8z)*

**Comment by towlie** [comment]
My build environment doesn't know these libs. Can you make it optional? Or add a flag so I can disable this.

**Comment by Diadlo** [comment]
@towlie, ~~It isn't lib, it's compilation flags.~~ What compiler do you use?
#4068

**Comment by ghost** [comment]
Whoever said that they tested it must have modified the PR, the correct format of those options is:

QMAKE_LFLAGS += -Wl,--dynamicbase -Wl,--nxcompat

I made PR to fix this https://github.com/qTox/qTox/pull/4069

**Pull request merged**
