### PR TITLE
add mannol translation (NSFW)

### PR DESCRIPTION
**Pull request by dubslow**
Perhaps we should reconsider including this in the repo lol

### CODE REVIEW

**Comment by agilob** [comment]
I don't think this should be in master...

**Comment by ghost** [comment]
@agilob You filthy anti-semite!

**Comment by msteinbeck** [comment]
I totally agree to @agilob.

**Comment by ghost** [comment]
Oy Vey! When is this opression going to stop?! Remember the 5B8D80!

**Comment by tux3** [comment]
I can't merge this, sorry. Let's keep pol inside of pol, or we'll get flamed to death.

**Comment by ghost** [comment]
Literally anotha shoah...

**Pull request closed without merging**
