### PR TITLE
chore(build): fixed library downloading on Windows [WIP]

### PR DESCRIPTION
**Pull request by nweyand**
* This fixes issue #4302

* Changed link to fukuchi.org from http to https.
* wget https://fukuchi.org/works/qrencode/qrencode-3.4.4.tar.gz generates a certificate error. An option has been added to ignore this error and warn appropriately.
* A method for writing debug output messages has been created and is now used across the Windows script. To enable, set ENABLE_DEBUG_OUTPUT to true at the beginning of ./windows/bootstrap.sh

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4309)

### CODE REVIEW

**Comment by nweyand** [comment]
Seems like a lot of shell magic is necessary to get it to run on Windows.

**Comment by nweyand** [comment]
The next step will be to make sure pkg-config is downloaded and installed automatically if not present on the system.

**Comment by nweyand** [comment]
I have a question: Did anyone ever compile qTox on Windows using that build setup???

I am starting to feel like I have been made fun of because that script did not include half of what is necessary to build qTox and by trying to make it run up to this point I have more than tripled its size – and I am still missing some dependencies.

**Comment by Diadlo** [comment]
#3372

**Comment by nweyand** [comment]
No matter whether there will be a MSYS2/MinGW-w64 build in the future (as discussed in #3372), I think it is still worth it to get the ‘old’ MSYS build up and running – especially as there is no static build option with the MSYS2-build ATM.

I agree though that it should be the default if (and only if) the issues [I mentioned here](https://github.com/qTox/qTox/pull/4291#issuecomment-289966834) have been addressed.

**Comment by Diadlo** [comment]
Please. rebase on the master.
Also, do you plan to finish this PR? Or it's already ready to review?

**Comment by Diadlo** [comment]
PR didn't have any activity for over 2 months, and no one seems to be interested in working on it, thus closing.

If that's not the case, please either ask to reopen the pull, or make a new one.

**Pull request closed without merging**
