### PR TITLE
fix(ci): upgrade travis to xcode9.3 to get macos 10.13 with brew support

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5866)

### CODE REVIEW

**Comment by sudden6** [comment]
Seems Travis CI doesn't have enough computation power to build qt5 and ffmpeg in one build O_o

**Comment by anthonybilinski** [comment]
In the latest build, nothing but `brew install ffmpeg` was run, and that still exceeds the 50 minute timeout. Unless we break down ffmpeg's dependency brew installations into more osx serialized jobs, it looks like we _need_ some form of ready-made build environment or precompiled dependencies to have our osx complete in travis.

**Comment by sudden6** [comment]
doesn't brew provide prebuilt binary packages too? maybe we need to update our OSX env to get access to them?

**Comment by anthonybilinski** [comment]
It does for most things, but not for quite a few, like ffmpeg. I'm guessing at least for ffmpeg it's because of licensing.

**Comment by anthonybilinski** [comment]
This is ready to be reviewed :tada: (and high priority)

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5866#-:-LqoMXzD9TwUl7RdEOHm:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 95 at r2](https://reviewable.io/reviews/qtox/qtox/5866#-LqoMLcR5eh4pDCsp_9L:-LqoMLcS5B87uih4jaXm:bb70w76) ([raw file](https://github.com/qtox/qtox/blob/e97b27058463df88a28a366f8573cd2238c8bb9e/osx/qTox-Mac-Deployer-ULTIMATE.sh#L95)):*
> ```Shell
>     fi
> 
>     # osx 10.13 High Sierra doesn't come with a /usr/local/sbin, yet it is needed by some brew packages
> ```

Nice
___
*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 200 at r2](https://reviewable.io/reviews/qtox/qtox/5866#-LqoMT-8CHY3F0gy-baA:-LqoMT-8CHY3F0gy-baB:b2ni78k) ([raw file](https://github.com/qtox/qtox/blob/e97b27058463df88a28a366f8573cd2238c8bb9e/osx/qTox-Mac-Deployer-ULTIMATE.sh#L200)):*
> ```Shell
>         echo "outputting dots to keep travis from killing us..."
>         while true; do
>             echo -n "."
> ```

lol

**Pull request merged**
