### PR TITLE
Fix empty avatar

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5653)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5653)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 94 at r1](https://reviewable.io/reviews/qtox/qtox/5653#-LeRQWcu8LTh1Wos_2H6:-LeRQWcv7XbQ6_QY8vGZ:b-kw8fyz) ([raw file](https://github.com/qtox/qtox/blob/01954427daa69167f7191df373d41e813dc17951/src/core/corefile.cpp#L94)):*
> ```cpp
>     QMutexLocker{coreLoopLock};
> 
>     uint64_t filesize;
> ```

initialize these variables here and invert the `if` below

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5653)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 94 at r1](https://reviewable.io/reviews/qtox/qtox/5653#-LeRQWcu8LTh1Wos_2H6:-LeSEGSa3NV26MCUXfLl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/01954427daa69167f7191df373d41e813dc17951/src/core/corefile.cpp#L94)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

initialize these variables here and invert the `if` below
</blockquote></details>

Done.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5653)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 97 at r2](https://reviewable.io/reviews/qtox/qtox/5653#-LeSJrwiBR9knqM33qkx:-LeSJrwiBR9knqM33qky:b-829fw) ([raw file](https://github.com/qtox/qtox/blob/7f683d612bf5ff2a639af6bf09f01696e43b5e51/src/core/corefile.cpp#L97)):*
> ```cpp
>     uint8_t *file_id = nullptr;
>     uint8_t *file_name = nullptr;
>     int nameLength = 0;
> ```

The type of `nameLength` should be `size_t`

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5653)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 97 at r2](https://reviewable.io/reviews/qtox/qtox/5653#-LeSJrwiBR9knqM33qkx:-LeSlFED0zWdsu9UeeW9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7f683d612bf5ff2a639af6bf09f01696e43b5e51/src/core/corefile.cpp#L97)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The type of `nameLength` should be `size_t`
</blockquote></details>

Done.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5653#-:-LeTTjRD05J8zEfKh3RM:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
