### PR TITLE
Open downloaded image with mouse click on thumbnail

### PR DESCRIPTION
**Pull request by Talkless**
Addresses #2952

### CODE REVIEW

**Comment by antis81** [comment]
LGTM :+1:

**Comment by Talkless** [comment]
Uhm.. so.. how about merging? :-)

**Comment by zetok** [comment]
@antis81 um, if this can be merged, can you merge?

**Comment by antis81** [comment]
Yeah, I'll merge tonight.

**Comment by zetok** [comment]
Great, thanks :)

**Comment by Talkless** [comment]
Thanks @antis81

**Pull request merged**
