### PR TITLE
fix(icon): use Qt tray icon in all cases, remove platform specific backends

### LINKED ISSUE #5599: Major: Tray icon on ubuntu 18.04 flatpak missing
##### Brief Description

OS: Ubuntu 18.04 amd64 flatpak
qTox version: io.github.qtox.qTox/x86_64/stable  v1.16.3
Commit hash: 8eed684c37bd711de2ca4bd863f5f0509edcdc2d
toxcore: 0.2.3
Qt: 5.11.3
Hardware: PC amd64 16gb ram amd cpu
…

Reproducible: Always

##### Steps to reproduce

1. Open qTox
2. Enable show system tray icon

##### Observed Behavior

Nothing happens. Not even after restart

##### Expected Behavior

Tray icon should show up

##### Additional Info
(links, images, etc go here)
screenshot

<details>
<summary>logfile</summary>

```
[12:14:32.291 UTC] :0 : Warning: Qt: Session management error: None of the authentication protocols specified are supported
[12:14:32.309 UTC] persistence/settings.cpp:133 : Debug: "Loading settings from /home/maciej/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[12:14:32.321 UTC] ipc.cpp:61 : Debug: Our global IPC ID is  4054283749330747304
[12:14:32.321 UTC] main.cpp:258 : Debug: commit:  8eed684c37bd711de2ca4bd863f5f0509edcdc2d
[12:14:32.325 UTC] persistence/profile.cpp:117 : Debug: Loading tox save  "/home/maciej/.var/app/io.github.qtox.qTox/config/tox/mkg20001.tox"
[12:14:32.325 UTC] persistence/settings.cpp:335 : Debug: Loading personal settings from "/home/maciej/.var/app/io.github.qtox.qTox/config/tox/mkg20001.ini"
[12:14:32.325 UTC] nexus.cpp:87 : Debug: Starting up
[12:14:32.325 UTC] persistence/settings.cpp:462 : Debug: "Saving global settings at /home/maciej/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[12:14:32.648 UTC] core/core.cpp:202 : Debug: Loading user profile
[12:14:32.648 UTC] core/toxoptions.cpp:63 : Debug: Core starting with IPv6 enabled
[12:14:35.784 UTC] widget/systemtrayicon.cpp:83 : Debug: Using the Qt backend
[12:14:35.792 UTC] :0 : Warning: failed to register service "org.kde.StatusNotifierItem-2-2"
[12:14:37.144 UTC] core/core.cpp:357 : Debug: "Connecting to fe80::f816:3eff:fe61:92e3:33445 (velusip)"
[12:14:37.145 UTC] core/core.cpp:357 : Debug: "Connecting to 2001:1af8:4700:a115:6::b:33445 (Pokemon)"
[12:14:41.645 UTC] core/core.cpp:357 : Debug: "Connecting to 2a00:7a60:0:746b::3:33445 (MAH69K)"
[12:14:41.646 UTC] core/core.cpp:357 : Debug: "Connecting to 185.25.116.107:33445 (MAH69K)"
[12:14:44.533 UTC] widget/systemtrayicon.cpp:92 : Debug: Deleting SystemTrayIcon
[12:14:44.540 UTC] persistence/profile.cpp:329 : Debug: Saving tox save to  "/home/maciej/.var/app/io.github.qtox.qTox/config/tox/mkg20001.tox"
[12:14:44.543 UTC] persistence/settings.cpp:628 : Debug: Saving personal settings at  "/home/maciej/.var/app/io.github.qtox.qTox/config/tox/mkg20001.ini"
[12:14:44.545 UTC] persistence/settings.cpp:462 : Debug: "Saving global settings at /home/maciej/.var/app/io.github.qtox.qTox/config/tox/qtox.ini"
[12:14:44.550 UTC] main.cpp:65 : Debug: Cleanup success
```

</details>

### LINKED ISSUE #5859: Migration from gtk2 to gtk3
I had a problem with building qTox.
I found the problem it is conflict glib2 2.62.1 with gtk2

some errors:

`/usr/include/gtk-2.0/gtk/gtktypeutils.h:236: error: ‘GTypeDebugFlags’ is deprecated
/usr/include/gtk-2.0/gtk/gtktooltips.h:73: error: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead
`
I did downgrading package glib2 2.62.1 to 2.60.7 it fixed the problem.

I think in future qTox need migration to gtk3 to avoid this problem.

### LINKED ISSUE #5881: Tray icon not visible on Ubuntu 19.04 with gnome3
##### Brief Description

OS: Ubuntu 19.04, default theme, gnome3.
qTox version: v1.16.3+
Commit hash:  93c9eef51f8143c3e3e5c1e63e0cc64d1d533f6e
toxcore:  0.2.10
Qt:  5.12.2
Hardware:  Desktop

Possibly related to https://github.com/qTox/qTox/issues/5599 and https://github.com/qTox/qTox/issues/5846.

Reproducible: Always

##### Steps to reproduce

1. Open qTox

##### Observed Behavior
No qTox tray icon appears. When qTox is the active application, it does show up here:
image

but our tray icon menu isn't present, and that entry goes away as soon as a different application is selected.

In logs I see
`[06:34:22.124 UTC] widget/systemtrayicon.cpp:62 : Debug: Using GTK backend`
and
`[06:35:38.182 UTC] widget/systemtrayicon.cpp:92 : Debug: Deleting SystemTrayIcon`

##### Expected Behavior
Tray icon is correctly displayed, and the normal menu is present.

### PR DESCRIPTION
**Pull request by anthonybilinski**
qTox added specialized tray icon backends over time to work around bugs with
the default implementation, since then our GTK+2 backend has stopped working,
our appindicator backend was never selected by default by cmake, and
statusnotifier was never selected at SystemTrayIcon construction, leaving us
only ever using the broken GTK+2 backend, or theoretically the Unity backend,
which I didn't see selected on Ubuntu 16.04 Unity. In all other cases we would
fall back to the Qt backend.

Qt icon has improved over time, and our platform specific icons have become
stale, with GTK+2 becoming deprecated and GTK+3 not having a similar feature,
QSystemTrayIcon has been tested on a variety of DEs and works as well or better
in all cases, as shown in the table at
https://github.com/qTox/qTox/issues/5881#issuecomment-541892457

Fix #5881
Fix #5859

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5888)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Testing completed, results listed at https://github.com/qTox/qTox/issues/5881#issuecomment-541892457. No regression found on all tested OSes.

**Review by sudden6 — APPROVED** [review]
Please also update INSTALL.md where it lists the dependencies and explains the now removed configuration switches

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5888#-:-LrKd10j9MDuhqNJrWvW:bcczb88)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
> Please also update INSTALL.md where it lists the dependencies and explains the now removed configuration switches

Done.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5888#-:-LrLFiPU8o05b_lOB9ck:b-1jzyfc)* status: 0 of 1 LGTMs obtained

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5888#-:-LrLXzso7FWdsaU_5jmB:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
