### PR TITLE
Add ability to cycle through the contacts list.

### PR DESCRIPTION
**Pull request by Jookia**
I've added the ability to cycle through the contacts list with Ctrl+Tab and Ctrl+Shift+Tab. See commits for discussion of the implementation. I haven't tested this on friends lists with just one friend but my calculator says it should work.

The last commit may conflict with #1449 if they fix the shortcuts for the chat system.
This should work with #1371 as it walks the widgets rather than using internal structure.
Improves #997 and #1019 by adding these keybinds.

### CODE REVIEW

**Comment by agilob** [comment]
Ctrl+Tab and Ctrl+Shift+Tab are global/system shortcuts, please set it on CTRL+PG UP/DOWN.

**Comment by Jookia** [comment]
I don't understand. Most applications use the same shortcuts, they don't seem global or system shortcuts?

**Comment by agilob** [comment]
Both used keyboard shortcuts exist in KDE, this commit would override them.
Ctrl+PG up/down already do the same thing in firefox, gajim, piding, clementine, netbeans, ms/libre office...

**Comment by Jookia** [comment]
I see, what do you mean exactly override? Does it steal it from the window manager somehow? Shouldn't it be deciding what its global keys do before applications? This commit also supports Ctrl+Page Up and Ctrl+Page Down since it uses QKeySequence::NextChild and QKeySequence::PreviousChild.

**Comment by zetok** [comment]
@agilob they exist in KDE? from what I remember when I was using KDE I was able to use `CTRL`+`TAB` / `CTRL`+`SHIFT` + `TAB` to switch between tabs in firefox without any problem… (yes, it would seem that TAB does in ff ~same thing `Ctrl+PG up/down` does

**Comment by zetok** [comment]
@Jookia if both ways are supported, then it's the same way ff does it, so IMHO it's as it should be..

**Comment by Jookia** [comment]
@zetok Searching the web seems it may be assigned to switching desktop lists sometimes? Either way if it's overriding global hot keys it's a bug.

**Comment by zetok** [comment]
@Jookia it's not a bug if ff uses it.

**Comment by Jookia** [comment]
@zetok I imagine if you have a key set to globally do something qTox shouldn't affect it or override them, qTox shouldn't get the keys in the first place.

**Comment by zetok** [comment]
@Jookia how do you detect then that there's "global" keybinding, so that qTox could be prevented from grabbing it if it's in use already?

**Comment by Jookia** [comment]
Ideally it shouldn't be getting the keybinding in the first place, so I'm guessing I'm not quite understanding what agilob means, unless there's a bug in KDE.

**Comment by agilob** [comment]
ok, i will provide a way to set such parameters anyway. I'm still saying ctrl+pg up/down is much obvious as more applications use it.

**Comment by Jookia** [comment]
Ah I see. Checking again, I was mistaken- This code does not support Ctrl+Page Up or Ctrl+Page Down, I must've had it working at some point during development and later removed it. I'll have to add this in before any merging happens. Apologies!

**Comment by Jookia** [comment]
I've updated the pull request to use shortcuts and support both key bindings explicitly. This should now actually work since #1457 is merged. In future if there's an option to bind keys, the shortcut parts should be changed as well as other shortcuts across the application.

**Comment by TheLastProject** [comment]
@agilob Err, Ctrl+(Shift+)Tab seems way more common for switching between tabs, because of Firefox and Chrome and the likes doing it, which is basically what you're doing in qTox.

@Jookia supporting both sounds sane, thanks :)

**Comment by zetok** [comment]
@Jookia just a nitpick;
How did you manage to not include info about keybindings in commit messages? Like, they're awesome and stuff, but main point is MIA..

**Comment by Jookia** [comment]
The idea was that it used the existing key bindings, though I should explicitly note that. I'll fix that.

**Comment by Jookia** [comment]
Done. It now mentions the key bindings at the bottom of the last commit. I figure people who want to know more would read the actual commit message.

**Comment by zetok** [comment]
on top of f55fd40ec66e43625b4f206c08c9b511b6934d97

```
* Applying user patches from /etc/portage/patches//net-im/qtox ...
 *   1332-zetok-quoting-fix.patch ...                                                                                                        [ ok ]
 *   1371-zero-one-alphabetized-friend-list.patch ...                                                                                        [ ok ]
 *   1454-Jookia-keybindings-for-cycling-through-contact-list.patch ...

 * Failed Patch: 1454-Jookia-keybindings-for-cycling-through-contact-list.patch !
```

**Comment by Jookia** [comment]
It works fine for me - I've rebased it anyway to make merging easier, perhaps try now? Are you sure you've collected all of the patches and not just the last?

**Comment by zetok** [comment]
Um, it fails to apply on top of other patch, I guess it would work on clean master.

And yep, `wget https://github.com/tux3/qTox/pull/1454.diff -O diff.patch` gets all patches

**Comment by Jookia** [comment]
Oh, it could be that alphabetized friend list patch that's doing things. I'll have a look to see if I can get it to merge cleanly now instead of later.

**Comment by Jookia** [comment]
I'm can't seem to find a compromise to make them merge happily automatically as both branches modify the same areas of code, meaning you have to move some lines around. Try this branch for a patch that includes the friends list code: https://github.com/Jookia/qTox/tree/cyclecontacts_friend_list

**Comment by tux3** [comment]
Rebased on master and merged in 821b01a90b38313d5f1d2ba41308ccdccfaf7f98

**Pull request closed without merging**
