### PR TITLE
Refactor/coreav

### PR DESCRIPTION
**Pull request by sudden6**
The goal is to remove `Audio::getInstance`

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5240)

### CODE REVIEW

**Review by Talkless — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240)* status: 0 of 1 LGTMs obtained

___
*[src/audio/backend/alsource.h, line 30 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSmltH11yMQwNx1dje:-LJSmltH11yMQwNx1djf:b6gye30) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/alsource.h#L30)):*
> ```objc
> private:
>     OpenAL* audio;
>     QMutex* killLock;
> ```

Why QMutex is allocated on heap?
___
*[src/audio/backend/openal.cpp, line 215 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSn7F9A1WR-IEa71SV:-LJSn7F9A1WR-IEa71SW:b-7kq3l8) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L215)):*
> ```cpp
>     // this must happen outside `audioLock`, to avoid a race condition when
>     // AlSink has checked `killLock` already, but not yet locked `audioLock`
>     for(auto& source : sources) {
> ```

space after `for`
___
*[src/audio/backend/openal.cpp, line 229 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSnAP887yzQdM-1E-a:-LJSnAP887yzQdM-1E-b:b-7kq3l8) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L229)):*
> ```cpp
>     // this must happen outside `audioLock`, to avoid a race condition when
>     // AlSink has checked `killLock` already, but not yet locked `audioLock`
>     for(auto& sink : sinks) {
> ```

space after `for`
___
*[src/audio/backend/openal.cpp, line 256 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSnJE8EJb3UWTd1k_g:-LJSnJE8EJb3UWTd1k_h:b-r56pze) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L256)):*
> ```cpp
>     alGenSources(1, &sid);
> 
>     auto sink = new AlSink(*this, sid);
> ```

auto const sink, pointer is not re-assigned.
___
*[src/audio/backend/openal.cpp, line 276 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSo2ph2bfc3iEo_BO4:-LJSo2piExB1EDd9OFal:b-ry5zhr) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L276)):*
> ```cpp
>     QMutexLocker locker(&audioLock);
> 
>     auto s = sinks.find(&sink);
> ```

const auto
___
*[src/audio/backend/openal.cpp, line 277 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSnQWLArNhq30oIYIC:-LJSnQWLArNhq30oIYID:b-2ja7h6) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L277)):*
> ```cpp
> 
>     auto s = sinks.find(&sink);
>     if(s == sinks.end()) {
> ```

space after `if`
___
*[src/audio/backend/openal.cpp, line 314 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSoERL1Ynu0WIrP1At:-LJSoERL1Ynu0WIrP1Au:bgque0n) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L314)):*
> ```cpp
>     }
> 
>     auto source = new AlSource(*this);
> ```

auto const
___
*[src/audio/backend/openal.cpp, line 315 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSo9d937pW4ark7Vyg:-LJSo9d937pW4ark7Vyh:b-tg6n90) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L315)):*
> ```cpp
> 
>     auto source = new AlSource(*this);
>     if (source == nullptr) {
> ```

Do we really care to handle out of memory cases in qTox..?
___
*[src/audio/backend/openal.cpp, line 335 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSoJDbDe8K_NH8t6n2:-LJSoJDbDe8K_NH8t6n3:bs6doqm) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L335)):*
> ```cpp
>     QMutexLocker locker(&audioLock);
> 
>     auto s = sources.find(&source);
> ```

const auto, iterator is not changed
___
*[src/audio/backend/openal.cpp, line 473 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSoePaBzfpVXXxxyMA:-LJSoePaBzfpVXXxxyMB:b-6ot07e) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L473)):*
> ```cpp
> 
>     sndFile.open(QIODevice::ReadOnly);
>     QByteArray data{sndFile.readAll()};
> ```

const could be added too.
___
*[src/core/core.cpp, line 1219 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSp5lL5v9qYC5n30il:-LJSp5lL5v9qYC5n30im:b-do3k2v) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/core/core.cpp#L1219)):*
> ```cpp
> bool Core::getGroupAvEnabled(int groupId) const
> {
>     QMutexLocker ml{coreLoopLock.get()};
> ```

const QMutexLocker, it's not being unlocked manually.
___
*[src/core/coreav.cpp, line 122 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSpHE7B8KUxwTW4OqU:-LJSpHE7B8KUxwTW4OqV:b-rejaj2) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/core/coreav.cpp#L122)):*
> ```cpp
> {
>     TOXAV_ERR_NEW err;
>     ToxAV* toxav = toxav_new(core, &err);
> ```

ToxAV* **const** toxav

**Review by Talkless — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240)* status: 0 of 1 LGTMs obtained

___
*[src/audio/backend/openal.cpp, line 674 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWvanG5p6GyC9FxKA7:-LKWvanG5p6GyC9FxKA8:b-7kq3l8) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/audio/backend/openal.cpp#L674)):*
> ```cpp
> 
>     // TODO(sudden6): these loops don't scale too well
>     for(auto source : sources) {
> ```

space after `for`
___
*[src/audio/backend/openal.cpp, line 682 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWvcJNC0itpPHem7WI:-LKWvcJO18JyiBJmjuyu:b-7kq3l8) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/audio/backend/openal.cpp#L682)):*
> ```cpp
>     }
> 
>     for(auto source : sources) {
> ```

space after `for`
___
*[src/widget/form/settings/avform.cpp, line 535 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWwBo57_XKOrizSOOQ:-LKWwBo57_XKOrizSOOR:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/widget/form/settings/avform.cpp#L535)):*
> ```cpp
>     }
> 
>     QString oldName = audioSettings->getInDev();
> ```

const QString
___
*[src/widget/form/settings/avform.cpp, line 558 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWwFoC-PrTQc2dZpMC:-LKWwFoC-PrTQc2dZpMD:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/widget/form/settings/avform.cpp#L558)):*
> ```cpp
>     }
> 
>     QString oldName = audioSettings->getOutDev();
> ```

const QString

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 2 of 24 files at r1, 5 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 504 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgkbdgAH_9ynd98uZ0:-LNgkbdgAH_9ynd98uZ1:bfrtb7k) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/core/core.cpp#L504)):*
> ```cpp
> 
> #if TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)
> void Core::onGroupPeerListChange(Tox*, uint32_t groupId, void* user)
> ```

I think "void* core" is more clear, "user" makes it seems like the data is a user Could alternatively change to userCbData or something to make it clear it's just qTox defined callback data.
___
*[src/core/coreav.cpp, line 103 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgphCn6F46u3hl8JaX:-LNgphCn6F46u3hl8JaY:b-rmbwng) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/core/coreav.cpp#L103)):*
> ```cpp
> }
> 
> void CoreAV::connectCallbacks(ToxAV& toxav) {
> ```

why dereference `this` then take the address of the reference at each use instead of just passing in this and using it directly?
___
*[src/core/coreav.cpp, line 615 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgt6Hh6FHpedM8hFnD:-LNgt6Hi9KOAzr_OC5lp:b-cz34wp) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/core/coreav.cpp#L615)):*
> ```cpp
>     qDebug() << QString("Joining group call %1").arg(groupId);
> 
>     ToxGroupCallPtr call = ToxGroupCallPtr(new ToxGroupCall{groupId, *this});
> ```

curly braces?
___
*[src/widget/form/settings/avform.cpp, line 99 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgwrTc2bYkOVXA8Vou:-LNgwrTd41uySDWg2MMJ:b-80ircw) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/widget/form/settings/avform.cpp#L99)):*
> ```cpp
> 
>     // TODO(sudden6): connect to audioSrc
>     //connect(audio, &Audio::volumeAvailable, this, &AVForm::setVolume);
> ```

does this need to be connected during construction of it's already managed on show/hide event?

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240)* status: 0 of 1 LGTMs obtained

___
*[src/audio/backend/alsource.h, line 30 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSmltH11yMQwNx1dje:-LKBgNl8CcxrGyoDYRJN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/alsource.h#L30)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Why QMutex is allocated on heap?
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 215 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSn7F9A1WR-IEa71SV:-LKBi8er4q1p0iNDEfzD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L215)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

space after `for`
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 229 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSnAP887yzQdM-1E-a:-LKBi8MGDEue3szoufmI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L229)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

space after `for`
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 256 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSnJE8EJb3UWTd1k_g:-LKBiD4S4Pvr-SviBCcK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L256)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

auto const sink, pointer is not re-assigned.
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 276 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSo2ph2bfc3iEo_BO4:-LKBiITB4OdKNdLYhqkY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L276)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 277 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSnQWLArNhq30oIYIC:-LKBiKio1i_7exavIRZp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L277)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

space after `if`
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 314 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSoERL1Ynu0WIrP1At:-LKBiOKi8KdL72l0egbN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L314)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

auto const
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 315 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSo9d937pW4ark7Vyg:-LKBiOx3Cb6gx9i39CVu:bwt8do2) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L315)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Do we really care to handle out of memory cases in qTox..?
</blockquote></details>

I think it's good practise, do you don't think so?
___
*[src/audio/backend/openal.cpp, line 335 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSoJDbDe8K_NH8t6n2:-LKBi3J3EGp8QnqQB_Jy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L335)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const auto, iterator is not changed
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 473 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSoePaBzfpVXXxxyMA:-LKBivuDDo0fFJGv5aam:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/audio/backend/openal.cpp#L473)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const could be added too.
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 674 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWvanG5p6GyC9FxKA7:-LNjDPoACxHx5qKUXQTV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/audio/backend/openal.cpp#L674)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

space after `for`
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 682 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWvcJNC0itpPHem7WI:-LNjDTUr85JOSfCDgJuM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/audio/backend/openal.cpp#L682)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

space after `for`
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 1219 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSp5lL5v9qYC5n30il:-LKBj6bK1loCdbaK1ziZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/core/core.cpp#L1219)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QMutexLocker, it's not being unlocked manually.
</blockquote></details>

Done.
___
*[src/core/coreav.cpp, line 122 at r1](https://reviewable.io/reviews/qtox/qtox/5240#-LJSpHE7B8KUxwTW4OqU:-LKBjBNJ72HdlIZS4K_2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47f0a21cba1382edccffc7c864f6556749d680f3/src/core/coreav.cpp#L122)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

ToxAV* **const** toxav
</blockquote></details>

Done.
___
*[src/core/coreav.cpp, line 103 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgphCn6F46u3hl8JaX:-LNjBvfiAlbIzGCo0pC0:bwv4wr) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/core/coreav.cpp#L103)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why dereference `this` then take the address of the reference at each use instead of just passing in this and using it directly?
</blockquote></details>

I did it this way to make it impossible for `toxav` to be a `nullptr`
___
*[src/core/coreav.cpp, line 615 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgt6Hh6FHpedM8hFnD:-LNjCKl0AXkRY6d6KhP1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/core/coreav.cpp#L615)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

curly braces?
</blockquote></details>

Done.
___
*[src/widget/form/settings/avform.cpp, line 535 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWwBo57_XKOrizSOOQ:-LNjDDbN4JNCpRN6vU8x:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/widget/form/settings/avform.cpp#L535)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QString
</blockquote></details>

Done.
___
*[src/widget/form/settings/avform.cpp, line 558 at r2](https://reviewable.io/reviews/qtox/qtox/5240#-LKWwFoC-PrTQc2dZpMC:-LNjDEBOEM50WESNZhSl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/052d93e8619c72f183bce5fd01311a4125ad1c44/src/widget/form/settings/avform.cpp#L558)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QString
</blockquote></details>

Done.
___
*[src/widget/form/settings/avform.cpp, line 99 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgwrTc2bYkOVXA8Vou:-LNjD-gl6nmjKAwBqfbY:b-j518i1) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/widget/form/settings/avform.cpp#L99)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

does this need to be connected during construction of it's already managed on show/hide event?
</blockquote></details>

Already done in the show/hide event, removed.

**Comment by sudden6** [comment]
Accidentally force pushed, need to restore the old state tomorrow

**Comment by sudden6** [comment]
@sphaerophoria @anthonybilinski fixed accidental force push, ready for review again.

**Comment by sphaerophoria** [comment]
@sudden6 mind catching me up a little here? I've got a lot of missing context here and a ramp up would be nice. I guess what I'm looking for is

1. Are all of these commits strictly related to removing the call to getInstance?
2. Are there supposed to be functional changes here? Or is there more than that?
3. How does each commit tie into the bigger picture.
4. How have you tested? This is more for me to understand the scope of the changes.

Feel free to just say "nah read it yourself" as I've done very little work on my side yet. Just thought if you could answer some of these it would jumpstart my review.

**Comment by sudden6** [comment]
> Are all of these commits strictly related to removing the call to getInstance?

No, in the process I noticed that the current internal Audio API was very error prone to use (wrong number of register/unregister calls...) and decided to fix that too. Removing the last getInstance calls should now be easier with the cleaned up API.

> Are there supposed to be functional changes here? Or is there more than that?

If by "functional changes" you mean that qTox behaves differently from a user perspective, no.

> How does each commit tie into the bigger picture.

They are more a sequence of development progress, any suggestions on how to clean that up?

> How have you tested? This is more for me to understand the scope of the changes.

Yes, I tested:

- Audio call with echobot
- Switching the audio source and sink during the call to see if the audio continues.

I have no problem with answering question if it helps the review progress :)

**Review by sphaerophoria — COMMENTED** [review]
Alright I'm going to apologize in advance. There are going to be like a million questions coming your way, almost of them are going to be "why". I'm going to be reviewing commit by commit so if there's something that's changed later I won't have seen it. This is going to be the only way I'm going to be able to work my way through this. My apologies if this results in comments that have already been resolved.

If you want to head any of this off basically going through each commit and writing down what you did and why will probably preempt most of my questions.

For now lets look at "refactor(coreav): move CoreAV to the factory pattern too"

Some notes on what this commit looks like it's trying to do (this is a summary of what it does, not whether or not I agree with it. @sudden6 this is the type of info I would love to see in the commit message)

* At a high level this commit looks like it's trying to clean up error cases and simplify handling of pointers
* Due to our inability to throw in constructors the previous instantiation of CoreAV had the ability to create an invalid inner toxav pointer. This case was not handled at all. Moving to a factory method allows us to return a nullptr in the case where something goes wrong.
* Handling of toxav_new errors is significantly improved
* Handling of the raw ToxAV pointer is now cleaner thanks to the unique_ptr deleter
* Addition of Core::getGroupAvEnabled as it is a toxcore concept not a toxav concept

I just left one comment related to this commit. Onto the next!

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240#-:-LPZHL3EBGhI7FTm22fx:bx237a2)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.h, line 74 at r18](https://reviewable.io/reviews/qtox/qtox/5240#-LPZLvRaBR8CKJLI_T8l:-LPZLvRaBR8CKJLI_T8m:bwu5ndp) ([raw file](https://github.com/qtox/qtox/blob/6f86ec9cf5807a71369b0e0baae4d87bfe2b4636/src/core/coreav.h#L74)):*
> ```objc
>     bool isGroupCallInputMuted(const Group* g) const;
>     bool isGroupCallOutputMuted(const Group* g) const;
>     bool isGroupAvEnabled(int groupNum) const;
> ```

Is this function still used? If we are moving to Core::getGroupAvEnabled then we should probably delete this *or* implement Core::getGroupAvEnabled by calling down to this. The Core version is almost a copy paste with a little extra logging. Seems like there's a good chance for divergence and more bugs down the line

**Comment by sphaerophoria** [comment]
___
*[src/core/coreav.cpp, line 103 at r3](https://reviewable.io/reviews/qtox/qtox/5240#-LNgphCn6F46u3hl8JaX:-LPZQfgkB5ePNmom_ZOx:b-6tx6qw) ([raw file](https://github.com/qtox/qtox/blob/08d6ed8f732c54a9ee8ef424afc4fee881978583/src/core/coreav.cpp#L103)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I did it this way to make it impossible for `toxav` to be a `nullptr`
</blockquote></details>

I think I'm okay with that pattern in general. It seems like writing in docs that something can't be null isn't as safe as just forcing it with a reference. Internally we still have to store the pointer as a pointer as it is a heap allocated object that we are responsible for freeing. Storing as a unique_ptr simplifies this for us, but that doesn't mean our APIs have to be this way.

That being said the real question I Have here is why do we pass in this->toxav when this is a member function?

**Review by sphaerophoria — COMMENTED** [review]
In case it wasn't made clear in the last commit, anything I don't comment on I agree with. So just assume a "this is a good change!" on every commit unless I say otherwise :).


**refactor(audio): create objects for each audio sink and source**

* Adds scoped subscription for Audio sources and sinks to avoid errors handling subscription state manually from owners

Review Notes:
* Giving benefit of the doubt that invalidateCallSources will be handled later
* I really like the scoped sink/source. It really cleans stuff up
* I'm not entirely sure I have enough context to understand the changes to ToxCall to their full extent. Looking over the diffs it *looks* reasonable but I'll have to remember to double check that at the end.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240#-:-LPZOJP86_CYtGQGxu_y:b87o8l4)* status: 0 of 1 LGTMs obtained

**Review by sphaerophoria — COMMENTED** [review]
**fix: fix memory leak in CoreAV and missuse of std::uniqe_ptr**

lol. That is all

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240#-:-LPZZPfm4qzWw9Mblq3b:blvpoes)* status: 0 of 1 LGTMs obtained

**Review by sphaerophoria — COMMENTED** [review]
**refactor(audio): move sound playback to AudioSink**

Info I would have liked in commit message

* Playback is now tied to an individual sink instead of the general audio device
* Sink is selected by a sourceId which is managed by AudioSink
** AudioSink gets a sourceId when it registers on construction
** AudioSink passes the sourceId down to the main OpenAL instance which still handles the actual playing, just now it has multiple source options
* Remove the concept of the mainSource and mainBuffer in OpenAL. These are now handled by the audio sinks
** This also allows us to remove some cleanup code as cleanup is handled by the sinks themselves (playMono16Timer)
* Each class who wants to play audio now gets it's own AudioSink instead of fighting over the main audio instance.
* I **believe** this might fix issues with playing multiple sounds at once. Previously we had one output buffer for all files. This caused issues where one audio file could clobber another. For example if your friend is calling you and sends you a message the call sound can be overwritten by the message notification sound resulting in the ringer just playing the notification sound non-stop. Having multiple sinks I assume fixes that problem since each sink gets it's own buffer. @sudden6 please confirm that my understanding is correct

Notes
* I think claiming this is a refactor is unfair. This is a feature addition that required some code rework. Multiple sinks if I understand correctly is a functional change. I would classify refactors more as 
Questions (may be resolved during review)
* What is openAL2?
* I believe this helps us get closer to removal of Audio::getInstance() because other classes own sinks instead of having to directly call into the main audio device, is that true? In the end we still have the issue of creating the sinks so propagating an audio device will be just as hard, but at the very least this is cleaner, better abstracted, and fixes bugs.
* I wanted to test the full PR at this point but didn't get any sound, possibly due to the following log
AL lib: (WW) alGetError: Querying error state on null context (implicitly 0xa004)
so I can't confirm whether or not my suspicions are correct that this fixes multi-sound playback but I'm hopeful. I'll look into the warning once I get through the rest of the review.

I'm going to pause here for a little. I don't think I'll be able to review the rest without a better handle on OpenAL

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5240#-:-LPZh59b6TZqCykWR0cA:b-vrpk8k)* status: 0 of 1 LGTMs obtained

**Comment by sphaerophoria** [comment]
So I just noticed my review edits don't show up in reviewable @sudden6 please review to the review comments on this page above what you see on reviewable.

**Comment by sudden6** [comment]
> Giving benefit of the doubt that invalidateCallSources will be handled later

yes, handled later

> I'm not entirely sure I have enough context to understand the changes to ToxCall to their full extent. Looking over the diffs it looks reasonable but I'll have to remember to double check that at the end.

you probably need to review the squashed version of these changes, I did some stuff and did it differently later

> refactor(audio): move sound playback to AudioSink
Info I would have liked in commit message ...

(shorting this one)

You are correct with all your comments here. `AudioSink/Source` is an abstraction to the OpenAL source/sink concept, so we have the possibility to replace it with something else.

> I think claiming this is a refactor is unfair.

I called it refactor, because it should not change anything from a user point of view.

> What is openAL2?

A audio backend that tries to implement echo cancelling. It's working on some systems but not very reliable.

> ... call into the main audio device, is that true?

Yes, we still have the issue of creating the sources/sinks. I drifted off with the goal, after I saw the state the code is in. I still plan to remove `getInstance` in a later step though.

> I wanted to test the full PR at this point but didn't get any sound

The PR doesn't fully work in the intermediate steps.

**Comment by sudden6** [comment]
This has been merged in parts by the two linked PRs.

**Pull request closed without merging**
