### PR TITLE
fix(tooltip): Set font colour to black for beige tooltip background

### LINKED ISSUE #4641: All tooltips under settings display as blank beige boxes
##### Brief Description

OS: Ubuntu 16.04 Unity
qTox version v1.11.0-117-gedd43b7.
Commit hash:  edd43b7212234b5a2b6e12b2fe5e6cf0294cb398
toxcore:  0.1.10
Qt:  5.5.1

Reproducible: Always

##### Steps to reproduce

1. Open settings menu
2. Hover over any setting

##### Observed Behavior
A beige box of varying size depending on the setting appears, but contains no text.

##### Expected Behavior
The tool tip appears containing text.

#### Additional notes
Not present for my friend, also on Ubuntu 16.04, but on Gnome

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4641

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4642)

### CODE REVIEW

**Comment by Diadlo** [comment]
Unfortunately, this solution does not work if the background color is black

**Comment by anthonybilinski** [comment]
Is the QToolTip background ever black? It doesn't look like it's configured at runtime, unlike say fileTransferWidget where css is selected based on a fontColor variable set in code.

**Comment by sudden6** [comment]
I think Qt can inherit the system design colors of the running desktop environment, at least in KDE it's possible.

**Comment by anthonybilinski** [comment]
Ah, and the reason for this problem is that Ubuntu's theme is bugged: https://bugs.launchpad.net/ubuntu/+source/ubuntu-themes/+bug/1332100

If we want to follow desktop theme forcing beige background and black text might not be the right path.

Should this be closed and let people do ubuntu specific workarounds?

**Comment by Diadlo** [comment]
@sudden6 @anthonybilinski, Since qTox doesn't support system theme, what do you think about forcing tooltip background color to black with white text or white with black?

**Comment by anthonybilinski** [comment]
Here are what the four look like:
white text on beige background, currently what ubuntu sees, obviously broken:
white-on-beige
white text on black background, IMO looks like highlighted text, too strong
white-on-black
black text on white background, IMO blends in too much with background text
black-on-white
black text on beige background, Qt default (which we can force to prevent messing from themes), IMO a good balance of standing out to draw attention but still looking similar to existing text theme:
black-on-beige

**Comment by sudden6** [comment]
Forcing it to black on beige/grey/white would be ok for me.

**Comment by sudden6** [comment]
@Diadlo can you also check? IIRC you run an inverted theme

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4642#-:-Ku8ki80WIrED_06or9O:b-jbsf8z)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4642#-:-Ku9-aiq74z27RvIsEcw:b-jbsf8z)*

**Pull request merged**
