### PR TITLE
refactor/audio chat form

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4363)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 945 at r1](https://reviewable.io:443/reviews/qtox/qtox/4363#-KjPRrWy2DAzDLAzcoR5:-KjPRrWz8eXUpQmYnZe2:b-xk66sz) ([raw file](https://github.com/qtox/qtox/blob/7ccb401a5af1f228faebf1a61436b8aa623b3448/src/widget/widget.cpp#L945)):*
> ```cpp
> }
> 
> void Widget::onCallEnd(uint32_t friendId)
> ```

This seems to be unused?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4363)*

**Comment by Diadlo** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 945 at r1](https://reviewable.io:443/reviews/qtox/qtox/4363#-KjPRrWy2DAzDLAzcoR5:-KjS2ZhZYnW5bHei9RQQ:bew45wy) ([raw file](https://github.com/qtox/qtox/blob/7ccb401a5af1f228faebf1a61436b8aa623b3448/src/widget/widget.cpp#L945)):*
No. It's used in constructor

> connect(av, &CoreAV::avEnd, this, &Widget::onCallEnd);

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4363)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 945 at r1](https://reviewable.io:443/reviews/qtox/qtox/4363#-KjPRrWy2DAzDLAzcoR5:-KjSJ41vduEsW7_rGpGY:buzemf) ([raw file](https://github.com/qtox/qtox/blob/7ccb401a5af1f228faebf1a61436b8aa623b3448/src/widget/widget.cpp#L945)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

No. It's used in constructor

> connect(av, &CoreAV::avEnd, this, &Widget::onCallEnd);
</blockquote></details>

Sorry, my mistake then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4363#-:-KjSJ97oBG3uE7rKH3O5:b-jbsf8z)*

**Comment by sudden6** [comment]
Reviewed 1 of 4 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4363)*

**Pull request merged**
