### PR TITLE
fix(cmake): Add ability to real disable optional dependency

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4103)

### CODE REVIEW

**Comment by zetok** [comment]
Doesn't seem to work, qTox is still linked against those libs.

**Comment by Diadlo** [comment]
cc @zetok

**Comment by zetok** [comment]
Fixed on b4f3015c3b0a0ca7eb7ced48061b39a791f8d60c.

**Comment by zetok** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 467 at r1](https://reviewable.io:443/reviews/qtox/qtox/4103#-KcDkYzVrYnr3ZHi7WWn:-KcDkYzVrYnr3ZHi7WWo:bifawt7) ([raw file](https://github.com/qtox/qtox/blob/b4f3015c3b0a0ca7eb7ced48061b39a791f8d60c/CMakeLists.txt#L467)):*
> ```CMake
> endif()
> 
> if(${ENABLE_APPINDICATOR})
> ```

Doesn't appindicator stuff depend on GTK stuff?

I.e. right now when one disables GTK stuff they still can have appindicator stuff "enabled", and it seems like it would cause compilation to fail?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4103)*

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CMakeLists.txt, line 467 at r1](https://reviewable.io:443/reviews/qtox/qtox/4103#-KcDkYzVrYnr3ZHi7WWn:-KcDnglvNu-oLXtud3tY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b4f3015c3b0a0ca7eb7ced48061b39a791f8d60c/CMakeLists.txt#L467)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Doesn't appindicator stuff depend on GTK stuff?

I.e. right now when one disables GTK stuff they still can have appindicator stuff "enabled", and it seems like it would cause compilation to fail?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4103)*

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4103#-:-KcDsACu_UbhlRJu9mLK:b-jbsf8z)*

**Pull request merged**
