### PR TITLE
Windows cross-compile script: dependency version bumps, NSIS 3 and zip

### PR DESCRIPTION
**Pull request by nurupo**
Should be ready to review, though let's see if it builds on Travis first.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5051)

### CODE REVIEW

**Comment by nurupo** [comment]
Huh, GitHub is being weird and not showing commits in the right order (the last 3 commits). Not that it matters though, Reviewable shows them in the right order and even Travis checks the right commit. Must be some GitHub Web UI bug, as I have force pushed and rebased a lot. Here is the actual order:

```
$ git log --pretty=oneline --abbrev-commit
9525505b (HEAD -> update-windows-crosscompile, fork/update-windows-crosscompile) chore(windows): add architecture to installer's and zip's filenames
0bb35e28 chore(windows): create a zip with qTox to be used in release publishing
6b581021 chore(windows): use NSIS 3 and cache NSIS ShellExecAsUser plugin
2660bea0 chore(windows): bump VPX version to the latest (1.7.0)
57015f42 chore(windows): bump Sodium version to the latest (1.0.16)
ac7cd49d chore(windows): bump QREncode version to the latest (4.0.0)
44febeff chore(windows): bump FFmpeg 3.2 version to the latest (3.2.10)
a25dc427 chore(windows): bump SQLCipher version to the latest (3.4.2)
aa771b26 chore(windows): bump Qt 5.9 version to the latest (5.9.4)
992f66b9 chore(windows): bump OpenSSL version to the latest (1.0.2o)
```

Edit: Looks like GitHub Web UI displays commits sorted the commit time, rather than by the actual order of the commit chain.

**Comment by nurupo** [comment]
Not sure if it's related to this PR, but I noticed that the numbers in the Qt version string (especially the number 9) and the commit hash look a bit weird. It might be because I'm running it in Wine, or it might be some legitimate font rendering issue that also appears on Windows. Can someone test it on Windows?

screenshot

**Comment by nurupo** [comment]
And why does the version string say `v1.11-<hash>`? qTox is long past v1.11.

**Comment by nurupo** [comment]
Oh, nevermind, it looks like v1.11 is the last tag I had fetched, so that explains the version number.

**Comment by tox-user** [comment]
I'm pretty sure the problem with the font is caused by Wine. It happens to me too and not only in qTox, but in a lot of other programs.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5051#-:-L9LeitHAjzdc8B54Z5j:b-jbsf8z)*

**Comment by nurupo** [comment]
Since toxcore 0.2.2 got released, let's use that too.

**Comment by nurupo** [comment]
Huh, apparently it hasn't been released yet. Well, the PR is ready to be merged then.

**Pull request merged**
