### PR TITLE
Add Greek translation

### PR DESCRIPTION
**Pull request by nikolas-n**
I added the translation file in Greek and translated some entries (they're quite a lot).

### CODE REVIEW

**Comment by suhr** [comment]
But there's only `<translation type="unfinished"></translation>` there.

**Comment by nikolas-n** [comment]
Sorry, I forgot to update the file.

**Comment by suhr** [comment]
Good. There's still a lot to translate though.
Also, consider rebasing when you finish translation.

**Comment by zetok** [comment]
@nikolas-n Thanks for the pull request!

Could you squash commits and use the command from https://github.com/tux3/qTox/wiki/Translating#if-youre-just-updating to "cleanup" translation file?
I.e. currently it has lines like `<location filename="../src/widget/form/settings/avform.cpp" line="146"/>`, which aren't needed in it when file is going to be stored in git repo.

**Comment by agilob** [comment]
Merge this?

**Comment by tux3** [comment]
Merged.

**Pull request closed without merging**
