### PR TITLE
Refactor/group

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4990)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Can you describe the functional changes this is supposed to have? Since group is using displayedNameChanged signal, the list of peers in group should update names when alias is set, correct? I don't see this behaviour. Setting an alias for a friend in the group does not update their name in the top group bar, neither does the friend changing their name.

**Comment by sudden6** [comment]
This changes are for the group title, since group and friend share a common base class we can use the common `displayedNameChanged` signal to update all widgets which use group and or friends. `name` here is slightly misleading, because it's actually the title of the group, but it's handled like the friend name.

EDIT: ideally there should be no functional/behaviour changes, just more common code.

**Comment by sudden6** [comment]
lgtm anyone?^^

**Comment by Diadlo** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/model/group.h, line 31 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4990#-LAUgnojBuMkxHbWMRLT:-LAUgnojBuMkxHbWMRLU:b-eagoon) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/model/group.h#L31)):*
> ```objc
> 
> class Friend;
> class GroupChatForm;
> ```

If you removed `chatForm`, remove declaration too

---

*[src/widget/form/chatform.cpp, line 200 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4990#-LAUh_mb2dph0Va4kOX6:-LAUh_mb2dph0Va4kOX7:bonsi3s) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/chatform.cpp#L200)):*
> ```cpp
> 
>     // reflect name changes in the header
>     // TODO(sudden6): check if this creates a cycle when the alias is changed
> ```

Remove `TODO`, right?

---

*[src/widget/form/genericchatform.h, line 25 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4990#-LAUheWMB2h7S2Z1eyF1:-LAUheWMB2h7S2Z1eyF2:b-jin7bw) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/genericchatform.h#L25)):*
> ```objc
> #include "src/chatlog/chatmessage.h"
> #include "src/core/toxpk.h"
> #include "src/model/contact.h"
> ```

You use pointer, I prefer declaration instead of include.

---

*[src/widget/form/genericchatform.cpp, line 242 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4990#-LAUhpBd-ULQWFOGUb-E:-LAUhpBd-ULQWFOGUb-F:bptniwz) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/genericchatform.cpp#L242)):*
> ```cpp
>     fileFlyout->installEventFilter(this);
> 
>     // Translation
> ```

Looks excessive because function name is obvious)

---

*[src/widget/form/groupchatform.cpp, line 184 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4990#-LAUiQ8p2DhHZq52tlU9:-LAUiQ8p2DhHZq52tlUA:brhm8rg) ([raw file](https://github.com/qtox/qtox/blob/3780acffe886799c373f9135789f2fff87a74a46/src/widget/form/groupchatform.cpp#L184)):*
> ```cpp
> {
>     Q_UNUSED(groupId);
>     setName(title);
> ```

Why removed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/4990)*

**Comment by sudden6** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/group.h, line 31 at r1](https://reviewable.io/reviews/qtox/qtox/4990#-LAUgnojBuMkxHbWMRLT:-LBIhlVJCyBUr65cvzU0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/model/group.h#L31)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

If you removed `chatForm`, remove declaration too
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 200 at r1](https://reviewable.io/reviews/qtox/qtox/4990#-LAUh_mb2dph0Va4kOX6:-LBIhqPq3Ledyf3XQogm:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/chatform.cpp#L200)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Remove `TODO`, right?
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/4990#-LAUheWMB2h7S2Z1eyF1:-LBIhrO56IV0rnkeJrOa:bfkztwi) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/genericchatform.h#L25)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

You use pointer, I prefer declaration instead of include.
</blockquote></details>

Done, is this just preference or does it change something?

---

*[src/widget/form/genericchatform.cpp, line 242 at r1](https://reviewable.io/reviews/qtox/qtox/4990#-LAUhpBd-ULQWFOGUb-E:-LBIhyQR10XRJEWA4qRT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/genericchatform.cpp#L242)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Looks excessive because function name is obvious)
</blockquote></details>

Done.

---

*[src/widget/form/groupchatform.cpp, line 184 at r1](https://reviewable.io/reviews/qtox/qtox/4990#-LAUiQ8p2DhHZq52tlU9:-LBIhzc5-F32t5CGEQ56:b4hugse) ([raw file](https://github.com/qtox/qtox/blob/3780acffe886799c373f9135789f2fff87a74a46/src/widget/form/groupchatform.cpp#L184)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why removed?
</blockquote></details>

`group` notified this function that the title changed, no need to set the title again to the same value

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/4990)*

**Comment by sudden6** [comment]
btw, long time no see on Tox, want to talk again sometime?

**Comment by Diadlo** [comment]
Yes. Maybe today :lgtm_strong:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/form/genericchatform.h, line 25 at r1](https://reviewable.io/reviews/qtox/qtox/4990#-LAUheWMB2h7S2Z1eyF1:-LBKYypb8CVie5fPepCv:b-41qdwi) ([raw file](https://github.com/qtox/qtox/blob/8fe3e2013509000af550cc41fa0b82d9ab919223/src/widget/form/genericchatform.h#L25)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done, is this just preference or does it change something?
</blockquote></details>

Avoid recompile files, that include "genericchatform.h" when "content.h" changed

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/4990#-:-LBKZRwE8GyayjSWRnq5:b-keg7bt)*

**Pull request merged**
