### PR TITLE
refactor(id): use toxPk and groupId instead of core numbers

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

~~Based on top of https://github.com/qTox/qTox/pull/5623~~

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5624)

Oops this needs to be combined with #5623 since findGroup isn't callable from the current mime type.

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Reopening since #5623's travis CI check got bugged.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5624)* status: 0 of 1 LGTMs obtained

___
*[src/widget/contentdialog.cpp, line 461 at r1](https://reviewable.io/reviews/qtox/qtox/5624#-Lcat1S60LPgmUQlANTQ:-Lcat1S60LPgmUQlANTR:bl6qegm) ([raw file](https://github.com/qtox/qtox/blob/c0fdc42e3304a5b6b524ec4469e2b154524ca173/src/widget/contentdialog.cpp#L461)):*
> ```cpp
>     GroupWidget* group = qobject_cast<GroupWidget*>(o);
>     if (frnd) {
>         assert(event->mimeData()->hasFormat("toxPk"));
> ```

Couldn't this crash if I drag&drop a file here? or is this filtered in higher layers? same for the other asserts in this file

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5624)* status: 0 of 1 LGTMs obtained

___
*[src/widget/contentdialog.cpp, line 461 at r1](https://reviewable.io/reviews/qtox/qtox/5624#-Lcat1S60LPgmUQlANTQ:-LcbF3Ec6gJK42e5HwGv:bm32yx2) ([raw file](https://github.com/qtox/qtox/blob/c0fdc42e3304a5b6b524ec4469e2b154524ca173/src/widget/contentdialog.cpp#L461)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Couldn't this crash if I drag&drop a file here? or is this filtered in higher layers? same for the other asserts in this file
</blockquote></details>

These branches should only be entered if the dragged or dropped event is a FriendWidget or GroupWidget from the above check, which is why I have an assert that the FriendWidget provides a toxPk, instead of only a check.

Trying to test this branch though, I haven't been able to hit ContentDialog::dropEvent or ContentDialog::dragEnterEvent, maybe because the ContentDialog is always covered?

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5624#-:-LccCmnY6XAVlbTRGlg3:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/contentdialog.cpp, line 461 at r1](https://reviewable.io/reviews/qtox/qtox/5624#-Lcat1S60LPgmUQlANTQ:-LccCaW93aksNvBaAxdV:b-b0whn2) ([raw file](https://github.com/qtox/qtox/blob/c0fdc42e3304a5b6b524ec4469e2b154524ca173/src/widget/contentdialog.cpp#L461)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

These branches should only be entered if the dragged or dropped event is a FriendWidget or GroupWidget from the above check, which is why I have an assert that the FriendWidget provides a toxPk, instead of only a check.

Trying to test this branch though, I haven't been able to it ContentDialog::dropEvent or ContentDialog::dragEnterEvent, maybe because the ContentDialog is always covered?
</blockquote></details>

ok, the reasoning seems fine. As to why the events are not triggered, IDK, I'm not familiar how that works in Qt

**Pull request merged**
