### PR TITLE
feat(login): Add command line argument to open login screen

### LINKED ISSUE #4673: [Feature request]: Command line option to create a new profile
With an instance of qTox running, it's not possible to open a new profile. You can open an existing profile with "qtox -p <profileName>", but if <profileName> doesn't exist, it errors and exits. Running with just "qtox" activates the existing open window.

It seems like the only existing way to create a new profile while logged in is to log out (to get to the login screen), create the profile, then log back in, which is obviously inconvenient.

I think adding a command line option "qtox -l" ('l' for "login") that opens the  login window regardless of running instances, and maybe also making "qtox -p <invalidProfileName>" open the login screen instead of exiting, since then the user gets a dropdown of available profiles, in case they misspelled the profile they wanted.

I don't think actually creating the profile from command line is useful, since then there would be plaintext passwords in history, we'd lose the nice password strength meter etc.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4673

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4675)

### CODE REVIEW

**Comment by sudden6** [comment]
I don't think you should update the translation files, this will create conflicts with weblate IIRC.

---

Review status: 0 of 38 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 313 at r1](https://reviewable.io:443/reviews/qtox/qtox/4675#-KujM0JQIHF0-8zZOF1B:-KujM0JQIHF0-8zZOF1C:b7ohus6) ([raw file](https://github.com/qtox/qtox/blob/befd002895a769baf56b133d48169b1f7418faf1/src/main.cpp#L313)):*
> ```cpp
>             if (eventType == "activate") {
>                 qDebug() << "Another qTox instance is already running. If you want to start a second "
>                         "instance, please open to login screen (qtox -l) or start with a profile (qtox -p <profile name>).";
> ```

`open login screen`? the `to` sounds wrong here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4675#-:-KujM62JSTdrzqV8Hdod:bgf9c0c)*

**Comment by anthonybilinski** [comment]
Removed translation file changes.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 313 at r1](https://reviewable.io:443/reviews/qtox/qtox/4675#-KujM0JQIHF0-8zZOF1B:-KuzvB4qQCphLArPnRrd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/befd002895a769baf56b133d48169b1f7418faf1/src/main.cpp#L313)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`open login screen`? the `to` sounds wrong here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4675#-:-KuzvCSuiaDxDx_bZuBc:b75wwaj)*

**Comment by anthonybilinski** [comment]
I will also update FAQ at https://github.com/qTox/qTox/wiki/FAQ#can-i-run-multiple-instances-of-qtox-at-once if/when this is merged.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 38 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4675#-:-Kuzx2F8HZhJs2luE67U:b-jbsf8z)*

**Pull request merged**
