### PR TITLE
update zh translation.

### PR DESCRIPTION
**Pull request by kitech**
Update zh translation to upstream repo.

### CODE REVIEW

**Comment by zetok** [comment]
Thanks for PR! :)

Recently there has been added commit message format, it would be nice if you could amend your commit to conform to it: https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format

e.g. `feat(l10n): update zh translation`

**Comment by zetok** [comment]
Also, you should run `lupdate -pro qtox.pro -no-obsolete -locations none -ts translations/zh.ts` to remove from translated file not needed parts.

**Comment by kitech** [comment]
OK, I will look at the docs and fix that.

**Comment by zetok** [comment]
Um, ~~translation~~ `.ts` file still has unnecessary parts, have you run `lupdate -pro qtox.pro -no-obsolete -locations none -ts translations/zh.ts && git commit -a --amend` ?

**Comment by kitech** [comment]
I do.

**Comment by kitech** [comment]
Now it's really done.

**Pull request merged**
