### PR TITLE
chore: Use `nullptr` instead of `0` for NULL pointer constants.

### PR DESCRIPTION
**Pull request by iphydf**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5332)

### CODE REVIEW

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5332#-:-LLqJU9Z2utQy6l6kCVi:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5332)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[test/net/toxmedata_test.cpp, line 119 at r1](https://reviewable.io/reviews/qtox/qtox/5332#-LMB-1E5B3YzGP3qMaFV:-LMB-1E6Dnbb0hB6TdFO:b-u1kyw1) ([raw file](https://github.com/qtox/qtox/blob/52a5951d265f0d9b49db5b42aaefced375246ded/test/net/toxmedata_test.cpp#L119)):*
> ```cpp
> {
>     qRegisterMetaType<ToxId>("ToxId");
>     QTest::addColumn<QString>("input", nullptr);
> ```

QTest::addColumn's second parameter already defaults to nullptr. Any reason to re-define it at call point?

**Review by iphydf — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5332)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[test/net/toxmedata_test.cpp, line 119 at r1](https://reviewable.io/reviews/qtox/qtox/5332#-LMB-1E5B3YzGP3qMaFV:-LMBRcScAdH2cM3o2G2b:b-e1975b) ([raw file](https://github.com/qtox/qtox/blob/52a5951d265f0d9b49db5b42aaefced375246ded/test/net/toxmedata_test.cpp#L119)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

QTest::addColumn's second parameter already defaults to nullptr. Any reason to re-define it at call point?
</blockquote></details>

https://github.com/qt/qtbase/blob/5.7/src/testlib/qtestcase.h

It's nullptr as of 5.8. Debian stretch has 5.7.

**Review by anthonybilinski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5332)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[test/net/toxmedata_test.cpp, line 119 at r1](https://reviewable.io/reviews/qtox/qtox/5332#-LMB-1E5B3YzGP3qMaFV:-LMDkzgUAy1qxNdCVsSn:bj1knjo) ([raw file](https://github.com/qtox/qtox/blob/52a5951d265f0d9b49db5b42aaefced375246ded/test/net/toxmedata_test.cpp#L119)):*
<details><summary><i>Previously, iphydf wrote…</i></summary><blockquote>

https://github.com/qt/qtbase/blob/5.7/src/testlib/qtestcase.h

It's nullptr as of 5.8. Debian stretch has 5.7.
</blockquote></details>

Ok sounds good.

**Pull request merged**
