### PR TITLE
chore: remove "Hardware" from issue template

### PR DESCRIPTION
**Pull request by anthonybilinski**
For the grand majority of bug reports, user hardware isn't relevant. Figuring
out what to write isn't always trivial.

@sudden6 thoughts on this change? I don't feel strongly about it, just when I do see the hardware field filled out it's often overly specific and irrelevant.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5972)

### CODE REVIEW

**Comment by Diadlo** [comment]
Another place
https://github.com/qTox/qTox/blob/7b45d7d9e19d9233177c3a2195dc70b55a537ffd/src/widget/form/settings/aboutform.cpp#L119

**Comment by anthonybilinski** [comment]
Thanks, updated.

**Comment by sudden6** [comment]
I agree, it was introduced when we had frequent problems with webcams/mics, but this seems mostly fixed.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5972#-:-LzWYCQT0nxDDV6CWk9n:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
