### PR TITLE
chore(travis): make ccache for OSX work

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4077)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4077#-KaWoxlc5sNTVZjhkzgp:-KaWoxlc5sNTVZjhkzgq:b-3pybco) ([raw file](https://github.com/qtox/qtox/blob/b1bb331403285a9b6236c9b6d1d296638634ae2c/osx/qTox-Mac-Deployer-ULTIMATE.sh#L109)):*
> ```Shell
>         ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
>     fi
>     
> ```

Unnecessary whitespaces

Why does the deploy script install ccache?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4077)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4077#-KaWoxlc5sNTVZjhkzgp:-KaWuFkNgThqRF8Jv9GO:bjs7yn5) ([raw file](https://github.com/qtox/qtox/blob/b1bb331403285a9b6236c9b6d1d296638634ae2c/osx/qTox-Mac-Deployer-ULTIMATE.sh#L109)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Unnecessary whitespaces

Why does the deploy script install ccache?
</blockquote></details>

Done
because that's where all the stuff with brew is installed and it isn't availble before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4077)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4077#-KaWoxlc5sNTVZjhkzgp:-KaWxNxXSIR4YUcGuyP_:b-l0ed2m) ([raw file](https://github.com/qtox/qtox/blob/b1bb331403285a9b6236c9b6d1d296638634ae2c/osx/qTox-Mac-Deployer-ULTIMATE.sh#L109)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done
because that's where all the stuff with brew is installed and it isn't availble before.
</blockquote></details>

`brew` should be available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4077)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[osx/qTox-Mac-Deployer-ULTIMATE.sh, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4077#-KaWoxlc5sNTVZjhkzgp:-KaWz27wNFPvlKRc5YrS:b-9ji04l) ([raw file](https://github.com/qtox/qtox/blob/b1bb331403285a9b6236c9b6d1d296638634ae2c/osx/qTox-Mac-Deployer-ULTIMATE.sh#L109)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`brew` should be available.
</blockquote></details>

moved it to travis specific scripts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4077)*

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4077#-:-KaXCZRhp0GolY06p13A:b-jbsf8z)*

**Pull request merged**
