### PR TITLE
chore(build): slightly refactor bootstrap.sh

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4017)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[bootstrap.sh, line 78 at r1](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_341sGP57rYoqMHxGI:-K_341sGP57rYoqMHxGJ:b-ttusd) ([raw file](https://github.com/qtox/qtox/blob/0aee51a7d3a25fbd49e7c6607e8ab2235d258c70/bootstrap.sh#L78)):*
> ```Shell
>     echo "example usages:"
>     echo "    ${0}    -- install libtoxcore"
>     exit 0
> ```

Maybe not exit here? (it's out of scope `print_help`)

---

*[bootstrap.sh, line 208 at r1](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_34F3dSS1tysWOlqa7:-K_34F3dSS1tysWOlqa8:bue81w) ([raw file](https://github.com/qtox/qtox/blob/0aee51a7d3a25fbd49e7c6607e8ab2235d258c70/bootstrap.sh#L208)):*
> ```Shell
>             then
>                 echo "[ERROR] Unknown parameter \"${1}\""
>                 echo ""
> ```

Maybe add `print_help` here too?

---

*[bootstrap.sh, line 212 at r1](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_34JyChOyYBZZKv_Ji:-K_34JyChOyYBZZKv_Jj:bfnph3a) ([raw file](https://github.com/qtox/qtox/blob/0aee51a7d3a25fbd49e7c6607e8ab2235d258c70/bootstrap.sh#L212)):*
> ```Shell
>             fi
> 
>             print_help
> ```

And if you will remove `exit 0` from `print_help`, then don't forget to add add here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4017)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[bootstrap.sh, line 78 at r1](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_341sGP57rYoqMHxGI:-K_39VrcnehLsAMa1xk8:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0aee51a7d3a25fbd49e7c6607e8ab2235d258c70/bootstrap.sh#L78)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Maybe not exit here? (it's out of scope `print_help`)
</blockquote></details>

Done.

---

*[bootstrap.sh, line 208 at r1](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_34F3dSS1tysWOlqa7:-K_39Xk96x001ZfZRRXB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0aee51a7d3a25fbd49e7c6607e8ab2235d258c70/bootstrap.sh#L208)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Maybe add `print_help` here too?
</blockquote></details>

Done.

---

*[bootstrap.sh, line 212 at r1](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_34JyChOyYBZZKv_Ji:-K_39Z5NQul0LdkBNHr_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0aee51a7d3a25fbd49e7c6607e8ab2235d258c70/bootstrap.sh#L212)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

And if you will remove `exit 0` from `print_help`, then don't forget to add add here
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4017)*

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4017#-:-K_3VTPpXvYML2k8T6Cj:bnfp4nl)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[bootstrap.sh, line 144 at r2](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_3eOXC3HSSkq6LXdjr:-K_3eOXC3HSSkq6LXdjs:b-t9irol) ([raw file](https://github.com/qtox/qtox/blob/9d20bcd57984219e58e26640e20bfbf5dcf84d41/bootstrap.sh#L144)):*
> ```Shell
>             "${BASE_DIR}/${SQLCIPHER_DIR}" \
>             --depth 1 \
>             --branch v3.4.0
> ```

make the version a constant like `TOXCORE_VERSION`

---

*[bootstrap.sh, line 225 at r2](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_3eYKv-JyF929dsGfU:-K_3eYKv-JyF929dsGfV:b-9191s5) ([raw file](https://github.com/qtox/qtox/blob/9d20bcd57984219e58e26640e20bfbf5dcf84d41/bootstrap.sh#L225)):*
> ```Shell
>     # maybe an earlier run of this script failed
>     # thus we should remove the cloned repositories
>     # if exists, otherwise cloning them may fail
> ```

`if they exist,`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4017)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[bootstrap.sh, line 144 at r2](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_3eOXC3HSSkq6LXdjr:-K_3iNepYQ0jSvlr9CHZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9d20bcd57984219e58e26640e20bfbf5dcf84d41/bootstrap.sh#L144)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

make the version a constant like `TOXCORE_VERSION`
</blockquote></details>

Done.

---

*[bootstrap.sh, line 225 at r2](https://reviewable.io:443/reviews/qtox/qtox/4017#-K_3eYKv-JyF929dsGfU:-K_3iPxB4j7pIVsOzE1Q:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9d20bcd57984219e58e26640e20bfbf5dcf84d41/bootstrap.sh#L225)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`if they exist,`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4017)*

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4017#-:-K_4316Kt1v_ExYjxWbF:bnfp4nl)*

**Pull request merged**
