### PR TITLE
 Add an event filter so you can't modify sliders by scrolling, closes #1932

### LINKED ISSUE #1932: Remove mouse scroll ability for sliders (AV settings tab)
As it is now you can accidentally change the sliders when using mouse scroll to move the page.

### PR DESCRIPTION
**Pull request by TheNain38**
closes #1932
Now you can't modify a slider by scrolling on it.
But if you scroll on a slider it will propagate the event to the `AVForm` and it will make it scroll normally

I never worked with that type of stuff before, I would like that someone check if I've done it the right way

### CODE REVIEW

**Comment by TheNain38** [comment]
Could someone review my code? And say to me if there is a better way of doing this?

**Comment by tux3** [comment]
@TheNain38 Instead of creating a FilterScroll class, you can just add `this` as the event filter, and you'll catch the events in `AVForm::eventFilter` (which already exists).
You just need to check in eventFilter that the object `QObject* o` passed in argument is either playbackSlider or microphoneSlider

**Comment by TheNain38** [comment]
@tux3 All done

**Comment by tux3** [comment]
LGTM

**Pull request merged**
