### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by Diadlo**
- [X] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5237)

### CODE REVIEW

**Comment by sudden6** [comment]
Looks interesting, but what is your greater plan with this?

**Comment by Diadlo** [comment]
@sudden6 No greater plan
1. I started with it to test deb building.
2. With it peoples can build qTox inside container without installing development libraries on their machines directly.
3. It add ability to run qTox fresh build in container without installation.

**Review by sudden6 — APPROVED** [review]
maybe we can also use them too speed up our CI? :lgtm_strong: 

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5237#-:-LHMdgaJ6w8qcEdkzaz_:b7h6q7m)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by Diadlo** [comment]
@sudden6 Maybe. But I'm not sure that it will make a speed up. But we can try.

**Pull request merged**
