### PR TITLE
chore(CHANGELOG): add changelog for the v1.10.0 release

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4376)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4376#-:-KjYaHlShsi3fkAspdBh:b-jbsf8z)*

**Comment by sudden6** [comment]
Maybe highlight the tripple-click marks message, auto-groupjoin and new language?

**Comment by zetok** [comment]
@sudden6 done.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4376#-:-KjZAGGz4IdvtMq63FgP:b-jbsf8z)*

**Pull request merged**
