### PR TITLE
Aliases feature

### PR DESCRIPTION
**Pull request by apprb**
relates to #653 and #335.

### CODE REVIEW

**Comment by zetok** [comment]
Finally \o/

I wonder though, is saving aliases per profile, or global?

Edit: r-click.. how hard would it be to make it changeable by clicking on name in chat window?
Also, could it be possible to display contact's own nick in parentheses right to set alias, and in italics? (that's how Venom does it)

**Comment by apprb** [comment]
Globally.
Don't enough energy left after long working week to extract profile related data to separated configure files.
May be later.

**Comment by zetok** [comment]
After setting a lot of text as alias, tooltip showing nick is of enormous size, and from log:

```
QXcbShmImage: shmget() failed (22) for size 151145592 (13093x2886)
```

**Comment by zetok** [comment]
Also after changing alias of selected contact title of window doesn't change until switched to other contact
alias

**Comment by apprb** [comment]
You always help to find problems with big data processing :)

**Comment by apprb** [comment]
Newer look at the window title before, probably because I'm using awesome WM.

**Comment by zetok** [comment]
Contacts that haven't accepted FR/don't have name now don't even show public key:
void

**Pull request merged**
