### PR TITLE
search navigation editing

### PR DESCRIPTION
**Pull request by TriKriSta**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5793)

### CODE REVIEW

**Review by Diadlo — APPROVED** [review]
Otherwise :lgtm_strong:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5793#-:-LmmXvZA0u-iig8X9XWU:b-tbxt33)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.cpp, line 995 at r1](https://reviewable.io/reviews/qtox/qtox/5793#-LmmXjDb1Z2aXnCI3fCm:-LmmXjDh756ZFafzeC-y:b-vaci4p) ([raw file](https://github.com/qtox/qtox/blob/3bac70d67817b62f4f12ec15fc550ba9a91ff8c0/src/widget/form/genericchatform.cpp#L995)):*
> ```cpp
> void GenericChatForm::onSearchDown(const QString& phrase, const ParameterSearch& parameter)
> {
>     auto result = chatLog.searchForward(searchPos, phrase, parameter);    
> ```

Empty spaces at the end of line

**Review by TriKriSta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5793)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/form/genericchatform.cpp, line 995 at r1](https://reviewable.io/reviews/qtox/qtox/5793#-LmmXjDb1Z2aXnCI3fCm:-LmoPCKP4rXlh2DLviOX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3bac70d67817b62f4f12ec15fc550ba9a91ff8c0/src/widget/form/genericchatform.cpp#L995)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Empty spaces at the end of line
</blockquote></details>

Done.

**Comment by sudden6** [comment]
@TriKriSta is this still WIP?

**Comment by TriKriSta** [comment]
@sudden6 yes

**Comment by sudden6** [comment]
with this applied I get:
```
[11:31:46.031 UTC] :0 : Warning: QTextCursor::setPosition: Position '7' out of range
```

When searching for a term and then scrolling down until it's out of view.

**Comment by TriKriSta** [comment]
@sudden6 maybe it is the old bug in class Text and maybe it's better will fix in another pull request

**Pull request merged**
