### PR TITLE
chore: add script for code formatting

### PR DESCRIPTION
**Pull request by zetok**
Part of #4208 without integration with the build system & travis, since it didn't want to work on travis.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4223)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/4223#-KeAM3sROyfnXBT5Pwzu:-KeAM3sSZLozPuxLqtNH:b1vwgn7) ([raw file](https://github.com/qtox/qtox/blob/01a44b7d4dae13001b2821812873ab74f43910b8/doc/coding_standards.md#L10)):*
> ```Markdown
> be applied by simply running clang-format over the source code in question.
> 
> There is [`tools/format-code.sh`] script that one can run to format all C++
> ```

remove `script` from this sentence

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4223)*

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/4223#-KeAM3sROyfnXBT5Pwzu:-KeAnID2IAE20irILLw9:b-g07ezx) ([raw file](https://github.com/qtox/qtox/blob/0c386fcc725b24bcc584a5beaa3181dd4b3d4ff8/doc/coding_standards.md#L10)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

remove `script` from this sentence
</blockquote></details>

~Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4223)*

**Comment by sudden6** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/4223#-KeAM3sROyfnXBT5Pwzu:-KeAtmC5QZEAkzBfE7vp:b-3s74l) ([raw file](https://github.com/qtox/qtox/blob/0c386fcc725b24bcc584a5beaa3181dd4b3d4ff8/doc/coding_standards.md#L10)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

~Done.
</blockquote></details>

ok. Even better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4223)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4223#-:-KeAtrz3TkW8fRzdNcTp:b-jbsf8z)*

**Pull request merged**
