### PR TITLE
Updated Spanish translation. All lines translated/checked.

### PR DESCRIPTION
**Pull request by ghost**
Translated the missing lines and checked the existing ones. Some details:
- Formal "you" everywhere
- Punctuation to Spanish norm
- "Friend" instead of "contact" everywhere
- Other words standardised ("carpeta" to "directorio", "chat de grupo" to "chat grupal", "suprimir" and "borrar" to "eliminar", "mandar" to "enviar", "arrancar" to "iniciar", etc).

A side question: is it possible to have a link/subsection in the wiki to summarise the standards and style used for the translation in each language?

### CODE REVIEW

**Comment by zetok** [comment]
@kehugter 

> A side question: is it possible to have a link/subsection in the wiki to summarise the standards and style used for the translation in each language?

Yep. I've added a few bits: https://github.com/tux3/qTox/wiki/Translating#style

**Comment by ghost** [comment]
@zetok great, thanks. I made a draft of a Spanish styleguide here

https://github.com/kehugter/qTox-spanish-translation-styleguide

Tell me if you prefer to have in qTox's wiki. The benefits of a separate repo is that the issue tracker can be used to discuss the translation (if there's ever some discussion).

**Comment by zetok** [comment]
@kehugter 

> Tell me if you prefer to have in qTox's wiki. The benefits of a separate repo is that the issue tracker can be used to discuss the translation (if there's ever some discussion).

it would be preferable to put it on wiki, so that there would be a central place people could refer to (easier to find). About discussion - if someone will disagree about something translation related there could be an issue made in qTox's issues, and people could talk over it in given issue, on IRC, or on mailing list. I'm not sure whether a separate place to track it for each language would be a good thing..?

Will your translation guidelines fit as subsection of `Language-specific stuff` ?

Awesome work, btw.

**Comment by ghost** [comment]
Sure, is better if everything stays in one place. And the translation-related noise will be minimal probably.

> Will your translation guidelines fit as subsection of Language-specific stuff ?

Yup, I just need to remove some duplicate information. I'll post a gist when it's ready.

---

@zetok - ready to be pasted below French:
https://gist.github.com/kehugter/2387df93f55efa80b6de

**Comment by zetok** [comment]
@kehugter thanks, added. um, you know, you can edit qTox's wiki directly `:)`

**Comment by ghost** [comment]
Oops, now that you mention it I noticed that nice "Edit" button on top!

**Pull request merged**
