### PR TITLE
chore(CI): add build for flatpak image

### LINKED ISSUE #3879: Flatpak support?
Would it be good idea to offer qTox as a flatpak? AFAIK pretty much everyone except Ubuntu, even [Debian](https://packages.debian.org/search?keywords=flatpak), seems to be adopting it as a way to install desktop software.

### PR DESCRIPTION
**Pull request by sudden6**
partially fixes #3879

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5123)

### CODE REVIEW

**Comment by sudden6** [comment]
I consider this ready for review now.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 106 at r1](https://reviewable.io/reviews/qtox/qtox/5123#-LC0l1mx-rbe_04q8Tmt:-LC0l1mx-rbe_04q8Tmu:b-hhs8u0) ([raw file](https://github.com/qtox/qtox/blob/78f47e8e1c920f6c6c1e10886ad03f0e45a825e9/.travis.yml#L106)):*
> ```YAML
>         directories:
>           - /opt/build-windows/x86_64
>     - stage: "macOS, AppImage and Flatpak"
> ```

Why macOS and package builds in one stage?

---

*[flatpak/chat.tox.qTox.json, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/5123#-LC0la3C6l105z5rgIDq:-LC0la3C6l105z5rgIDr:b-1wy8xb) ([raw file](https://github.com/qtox/qtox/blob/78f47e8e1c920f6c6c1e10886ad03f0e45a825e9/flatpak/chat.tox.qTox.json#L2)):*
> ```JSON
> {
> 	"app-id": "chat.tox.qTox",
> ```

I do not really care, but why do you use tabs here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5123#-:-LC0ljqj0oJjzc43zUKL:b-jbsf8z)*

**Comment by sudden6** [comment]
Seems we have to change some stuff for flathub, will update later.

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[.travis.yml, line 106 at r1](https://reviewable.io/reviews/qtox/qtox/5123#-LC0l1mx-rbe_04q8Tmt:-LCFTqbl0CtIxiVUYyHR:bukq0ns) ([raw file](https://github.com/qtox/qtox/blob/78f47e8e1c920f6c6c1e10886ad03f0e45a825e9/.travis.yml#L106)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why macOS and package builds in one stage?
</blockquote></details>

To make the builds more parallel

---

*[flatpak/chat.tox.qTox.json, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/5123#-LC0la3C6l105z5rgIDq:-LCFTt5W68Lmb8syshhq:bi1itpp) ([raw file](https://github.com/qtox/qtox/blob/78f47e8e1c920f6c6c1e10886ad03f0e45a825e9/flatpak/chat.tox.qTox.json#L2)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I do not really care, but why do you use tabs here?
</blockquote></details>

This file will be changed soon, probably also the formatting.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5123)*

**Comment by sudden6** [comment]
I'll probably reference https://github.com/qTox/flathub/tree/qtox for the final solution

**Comment by sudden6** [comment]
Waiting for an answer/update to https://github.com/flatpak/flatpak-builder/issues/13#issuecomment-393330647

**Comment by sudden6** [comment]
I consider this ready now.

**Comment by tox-user** [comment]
Why MIT license? qTox uses GPL3, so why change?

**Comment by sudden6** [comment]
Most of our build scripts are MIT, IDK why though, I just copied another one. Does it make a difference?

**Comment by tox-user** [comment]
We use GPL3 so it would be nice if it applied to all of the code.

**Comment by tox-user** [comment]
I don't like the change in license, don't know anything about how travis and docker work and I haven't tested any of this, but aside from that looks good.

:lgtm_strong:

---

Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
Review status: :shipit: complete! 2 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5123#-:-LFTkKeu0pNgytQ7csKw:b-brr3oj)*

**Pull request merged**
