### PR TITLE
fix(audio): alternate audio fix implementation from #4139

### PR DESCRIPTION
**Pull request by agrecascino**
It all just werks™.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4146)

### CODE REVIEW

**Comment by ghost** [comment]
Beautiful

**Comment by agrecascino** [comment]
^ this man is correct

**Comment by Diadlo** [comment]
Reviewed 4 of 5 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/toxcall.h, line 77 at r2](https://reviewable.io:443/reviews/qtox/qtox/4146#-KcJuwxu-uV7Xdiu46bO:-KcJuwxu-uV7Xdiu46bP:b-k06mer) ([raw file](https://github.com/qtox/qtox/blob/e4eab82acd77cdb8f48f3b411cb2a54d4a90edfd/src/core/toxcall.h#L77)):*
> ```objc
>     ToxGroupCall& operator=(ToxGroupCall&& other) noexcept;
> 
>     QMap<int,quint32> peer;
> ```

Add space after `,`
Also, add [docs](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#documentation)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4146)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/coreav.cpp, line 508 at r2](https://reviewable.io:443/reviews/qtox/qtox/4146#-KcK565qJ1Qlj3HFRHeD:-KcK565qJ1Qlj3HFRHeE:b-2k6cyb) ([raw file](https://github.com/qtox/qtox/blob/e4eab82acd77cdb8f48f3b411cb2a54d4a90edfd/src/core/coreav.cpp#L508)):*
> ```cpp
> 
> /**
>  * @brief Called from a widget call to make sure the source for that peer is invalidated.
> ```

Update docs

---

*[src/core/coreav.cpp, line 512 at r2](https://reviewable.io:443/reviews/qtox/qtox/4146#-KcK54JHOhI0tJG1W34b:-KcK54JHOhI0tJG1W34c:bldk2si) ([raw file](https://github.com/qtox/qtox/blob/e4eab82acd77cdb8f48f3b411cb2a54d4a90edfd/src/core/coreav.cpp#L512)):*
> ```cpp
>  * @param peer Peer Index
>  */
> void CoreAV::groupNameListChanged(int group, int peer) {
> ```

I think, better rename, WHAT do instead WHEN do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4146)*

**Comment by Diadlo** [comment]
Code :lgtm_strong:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4146#-:-KcKBBudEztkG8TgTVuS:bnu8ip0)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/core/toxcall.h, line 77 at r3](https://reviewable.io:443/reviews/qtox/qtox/4146#-KcN71FpKCMkU5UyYtNK:-KcN71FpKCMkU5UyYtNL:bct0cqx) ([raw file](https://github.com/qtox/qtox/blob/48b40b3a566e2b441c013de1d29ad1d6dad413de/src/core/toxcall.h#L77)):*
> ```objc
>     ToxGroupCall& operator=(ToxGroupCall&& other) noexcept;
> 
>     QMap<int, quint32> peer;
> ```

I think this should be renamed to `peers` since it's a collection of multiple.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4146)*

**Comment by sudden6** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/core/toxcall.h, line 77 at r3](https://reviewable.io:443/reviews/qtox/qtox/4146#-KcN71FpKCMkU5UyYtNK:-KcORoOZiLG3FQ8uXvSy:b-tnxvw4) ([raw file](https://github.com/qtox/qtox/blob/48b40b3a566e2b441c013de1d29ad1d6dad413de/src/core/toxcall.h#L77)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think this should be renamed to `peers` since it's a collection of multiple.
</blockquote></details>

You forgot to change the other usages. Also please mark things you fixed as "Done" in Reviewable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4146)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 4 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4146#-:-KcQ11HyE0V64h3O7UnS:b-jbsf8z)*

**Pull request merged**
