### PR TITLE
fix(Widget): Incorrect removing of contacts

### PR DESCRIPTION
**Pull request by bodwok**
Fix: When click on cancel or close the "Remove Friend" dialog, contact will be deleted anyway

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6628)

### CODE REVIEW

**Review by anthonybilinski — COMMENTED** [review]
Oof good catch, introduced when I pulled our this functionality to a new function in cd3c7b392eeed2bfc3bc7e9cd83aaf58a2d384ba, which broke the early return.

I think the flow/naming is a bit weird still, "bool isNeedRemoveChat" isn't just determining if we need to remove the chat like you'd think, it's also determining if we need to remove history, and actually removing history itself.

Maybe instead a function should ask the user about both, and return one of three states, "do nothing", "remove chat but leave history", or "remove chat with history", then Widget::removeGroup / Widget::removeFriend can handle the three states themselves?

i.e.

```
From f34622f5d99bb0ca76d1b1725ce94f919e9b77da Mon Sep 17 00:00:00 2001
From: Anthony Bilinski <me@abilinski.com>
Date: Sun, 8 May 2022 04:22:00 -0700
Subject: [PATCH] fix(Widget): Don't remove friend when removal is cancelled in
 UI

Handle asking separately from friend and history removal logic.
---
 src/widget/widget.cpp | 28 +++++++++++++++++++++++-----
 src/widget/widget.h   |  9 ++++++++-
 2 files changed, 31 insertions(+), 6 deletions(-)

diff --git a/src/widget/widget.cpp b/src/widget/widget.cpp
index 5cfcea5bc..b6483e8e5 100644
--- a/src/widget/widget.cpp
+++ b/src/widget/widget.cpp
@@ -1747,7 +1747,15 @@ void Widget::removeFriend(Friend* f, bool fake)
 {
     assert(f);
     if (!fake) {
-        removeChatHistory(*f);
+        switch (askRemoveChatWithHistory(*f)) {
+        case ChatRemovalType::NoRemove:
+            return;
+        case ChatRemovalType::RemoveWithHistory:
+            profile.getHistory()->removeChatHistory(f->getPersistentId());
+            break;
+        case ChatRemovalType::RemoveJustChat:
+            break;
+        };
     }
 
     const ToxPk friendPk = f->getPublicKey();
@@ -2055,7 +2063,15 @@ void Widget::removeGroup(Group* g, bool fake)
 {
     assert(g);
     if (!fake) {
-        removeChatHistory(*g);
+        switch (askRemoveChatWithHistory(*g)) {
+        case ChatRemovalType::NoRemove:
+            return;
+        case ChatRemovalType::RemoveWithHistory:
+            profile.getHistory()->removeChatHistory(g->getPersistentId());
+            break;
+        case ChatRemovalType::RemoveJustChat:
+            break;
+        };
     }
 
     const auto& groupId = g->getPersistentId();
@@ -2739,16 +2755,18 @@ void Widget::formatWindowTitle(const QString& content)
     }
 }
 
-void Widget::removeChatHistory(Chat& chat)
+Widget::ChatRemovalType Widget::askRemoveChatWithHistory(Chat& chat)
 {
     RemoveChatDialog ask(this, chat);
     ask.exec();
 
     if (!ask.accepted()) {
-        return;
+        return ChatRemovalType::NoRemove;
     }
 
     if (ask.removeHistory()) {
-        profile.getHistory()->removeChatHistory(chat.getPersistentId());
+        return ChatRemovalType::RemoveWithHistory;
+    } else {
+        return ChatRemovalType::RemoveJustChat;
     }
 }
diff --git a/src/widget/widget.h b/src/widget/widget.h
index 6fcf64179..ac02998c9 100644
--- a/src/widget/widget.h
+++ b/src/widget/widget.h
@@ -123,6 +123,13 @@ private:
         Groups
     };
 
+    enum class ChatRemovalType
+    {
+        NoRemove,
+        RemoveJustChat,
+        RemoveWithHistory
+    };
+
 public:
     Widget(Profile& profile_, IAudioControl& audio_, CameraSource& cameraSource,
         Settings& settings, Style& style, QWidget* parent = nullptr);
@@ -287,7 +294,7 @@ private:
     void cleanupNotificationSound();
     void acceptFileTransfer(const ToxFile &file, const QString &path);
     void formatWindowTitle(const QString& content);
-    void removeChatHistory(Chat& chat);
+    ChatRemovalType askRemoveChatWithHistory(Chat& chat);
 
 private:
     Profile& profile;
-- 
2.36.0

```

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6628#-:-N1YN2Z83nsupmd7fdDQ:buqrtj1)* status: 0 of 1 LGTMs obtained

**Review by bodwok — COMMENTED** [review]
Shortened a little, because RemoveChatDialog already contain states from ChatRemovalType. I tried to move the processing of RemoveChatDialog into a separate function, but processing the result still leaves duplicate code.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6628#-:-N1tRIxG9ak-edK8Ita0:b3xzar2)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
Seems reasonable, I think this is cleaner and easier to understand and follow even though there's a couple lines of duplication.

:lgtm_strong: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6628#-:-N22Zir39ElIevAzKj3N:b5421hy)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
Squashed commits and rebased to master branch.

**Pull request merged**
