### PR TITLE
chore(build): allow compilation with custom c-toxcore version

### PR DESCRIPTION
**Pull request by zoff99**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5066)

### CODE REVIEW

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[windows/cross-compile/build.sh, line 877 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9fZqwj1WTL41QpT_bN:-L9fZqwj1WTL41QpT_bO:b-fuhp06) ([raw file](https://github.com/qtox/qtox/blob/a42f112ef3174ee7cb07e633463a8f181363a39b/windows/cross-compile/build.sh#L877)):*
> ```Shell
> 
>   CROSS="$ARCH-w64-mingw32-" CXXLAGS="-O3 -g0" CFLAGS="-O3 -g0" ./configure --target="$VPX_TARGET" \
>                                          --prefix="$VPX_PREFIX_DIR" \
> ```

Indentation.

---

*[windows/cross-compile/build.sh, line 913 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9f_FVp0scqLymtY6Mv:-L9f_FVp0scqLymtY6Mw:b2037f0) ([raw file](https://github.com/qtox/qtox/blob/a42f112ef3174ee7cb07e633463a8f181363a39b/windows/cross-compile/build.sh#L913)):*
> ```Shell
>   mkdir -p "$TOXCORE_PREFIX_DIR"
> 
>   git clone "$TOXCORE_REPO"
> ```

`git clone "$TOXCORE_REPO" c-toxcore`, specify the output directory name, just like we do it in all other git clones commands in here.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066#-:-L9faDrOB4_qJ1mOBc5Z:b-jbsf8z)*

**Comment by nurupo** [comment]
Oh, didn't mean to lgtm before the fixes are made.

:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066#-:-L9faSx7-WAZnoXUIzOQ:b-lxignz)*

**Comment by zoff99** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[windows/cross-compile/build.sh, line 877 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9fZqwj1WTL41QpT_bN:-L9flzks2-y-SVDkgIQF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a42f112ef3174ee7cb07e633463a8f181363a39b/windows/cross-compile/build.sh#L877)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.

---

*[windows/cross-compile/build.sh, line 913 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9f_FVp0scqLymtY6Mv:-L9flyqRBLfMD5ScPEY9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a42f112ef3174ee7cb07e633463a8f181363a39b/windows/cross-compile/build.sh#L913)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

`git clone "$TOXCORE_REPO" c-toxcore`, specify the output directory name, just like we do it in all other git clones commands in here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066)*

**Comment by nurupo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066#-:-L9jVrUh1GM2ICW1-WzC:b-jbsf8z)*

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[windows/cross-compile/build.sh, line 803 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-0Qb9gojrt7i6nvU:-L9q-0Qb9gojrt7i6nvV:b-fec0ll) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L803)):*
> ```Shell
>   cd opus*
> 
>   CFLAGS="-O3 -g0" ./configure --host="$ARCH-w64-mingw32" \
> ```

any reason why you changed the optimization level?

---

*[windows/cross-compile/build.sh, line 876 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-5CY7fp3NMo-B5sP:-L9q-5CY7fp3NMo-B5sQ:b-edpebf) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L876)):*
> ```Shell
>   fi
> 
>   CROSS="$ARCH-w64-mingw32-" CXXLAGS="-O3 -g0" CFLAGS="-O3 -g0" \
> ```

why did you change the compile flags?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066)*

**Comment by zoff99** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[windows/cross-compile/build.sh, line 803 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-0Qb9gojrt7i6nvU:-L9q5L3BDgP7c4l4LXVJ:b-k3ujxv) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L803)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

any reason why you changed the optimization level?
</blockquote></details>

i thought -O3 is ok to use. but sure, if this is an issue please change it back. it's actually another topic.

---

*[windows/cross-compile/build.sh, line 876 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-5CY7fp3NMo-B5sP:-L9q5_cy3_Jzw51Ce_Tt:bfa0hay) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L876)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why did you change the compile flags?
</blockquote></details>

libvpx need CXXFLAGS set, which i now see is actually a typo it should read CXXFLAGS.
what issue do you think this will cause?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[windows/cross-compile/build.sh, line 803 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-0Qb9gojrt7i6nvU:-L9q6CElAOJm8ya19iLn:b-ysil3p) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L803)):*
<details><summary><i>Previously, zoff99 (Zoff) wrote…</i></summary><blockquote>

i thought -O3 is ok to use. but sure, if this is an issue please change it back. it's actually another topic.
</blockquote></details>

generally `-O3` can enable very aggressive optimizations that can cause problems or actually make things slower, usually `-O2 is recommended and I would prefer if you leave it as is if it doesn't solve a particular problem. Another problem is that if you increase the optimization level you automatically loose debug information, since the code is heavily modified.

---

*[windows/cross-compile/build.sh, line 876 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-5CY7fp3NMo-B5sP:-L9q9EY6Ab3Fq7s-CysV:b-otk8lh) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L876)):*
<details><summary><i>Previously, zoff99 (Zoff) wrote…</i></summary><blockquote>

libvpx need CXXFLAGS set, which i now see is actually a typo it should read CXXFLAGS.
what issue do you think this will cause?
</blockquote></details>

same as above, problems with debugging and no problem solved by changing the defaults, if it doesn't fix anything for you I'd prefer to not change the options

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066)*

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[windows/cross-compile/build.sh, line 803 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-0Qb9gojrt7i6nvU:-L9qcvo06wdNnFhz4jkg:b-szenlv) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L803)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

generally `-O3` can enable very aggressive optimizations that can cause problems or actually make things slower, usually `-O2 is recommended and I would prefer if you leave it as is if it doesn't solve a particular problem. Another problem is that if you increase the optimization level you automatically loose debug information, since the code is heavily modified.
</blockquote></details>

The aggressive optimization is true, sometimes it might indeed cause problems. The debugging argument is a bit ridiculous though.

---

*[windows/cross-compile/build.sh, line 876 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-5CY7fp3NMo-B5sP:-L9qfHnaCB14ZAwX5ow-:b-zg2mya) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L876)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same as above, problems with debugging and no problem solved by changing the defaults, if it doesn't fix anything for you I'd prefer to not change the options
</blockquote></details>

`CXXLAGS`. C++ Lags. Hm :thinking: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066)*

**Comment by zoff99** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[windows/cross-compile/build.sh, line 803 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-0Qb9gojrt7i6nvU:-L9xhKkBDsKJIeNxHagL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L803)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

The aggressive optimization is true, sometimes it might indeed cause problems. The debugging argument is a bit ridiculous though.
</blockquote></details>

Done.

---

*[windows/cross-compile/build.sh, line 876 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5066#-L9q-5CY7fp3NMo-B5sP:-L9xhM-i6tt06QDbWSnv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L876)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

`CXXLAGS`. C++ Lags. Hm :thinking: 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066)*

**Comment by nurupo** [comment]
@zoff99 you know, you are not alone in your typo https://github.com/search?q=CXXLAGS&type=Code. Maybe someone should make a bot that would open `sed -i 's/CPPLAGS/CPPFLAGS/g' <file>` PRs to all those repos.

**Comment by zoff99** [comment]
maybe even should patch configure to accept the "typo" name :-)

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5066#-:-L9zPTW83g5GdBdsctGl:b-jbsf8z)*

**Comment by zoff99** [comment]
@sudden6 why was it not merged? now there's conflicts again :-(

**Comment by anthonybilinski** [comment]
@zoff99 the conflict is just that we bumped toxcore version, it's a trivial conflict to resolve. He's a busy guy and we're in the middle of a rushed release, the PR will make it in soon.

**Comment by zoff99** [comment]
it's been waiting since 17th of January.
i know people are busy.

**Comment by sudden6** [comment]
sorry, I forgot an then this toxcore issue appeared

**Comment by tox-user** [comment]
>it's been waiting since 17th of January.
>i know people are busy.

To be honest the lack of activity on the original PR was from you, so you can't blame us for that. You can blame us on the lack of activity on this one though.

**Comment by anthonybilinski** [comment]
@zoff99 can you resolve the conflict with master (just toxcore version bump) and squash the commits? Also it looks like only your original commit was signed, but all review commits were not, it would be good if the final commit could be signed as well.

**Comment by zoff99** [comment]
@sudden6 please squash fix, whatever. merge this thing. i'm not doing this a 5th time.

**Comment by nurupo** [comment]
:lgtm_cancel: 

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[windows/cross-compile/build.sh, line 876 at r3](https://reviewable.io/reviews/qtox/qtox/5066#-L9q-5CY7fp3NMo-B5sP:-LBOLzRA6CBLhQQbEAei:bgrk8uy) ([raw file](https://github.com/qtox/qtox/blob/6c09985256f6df9037dcae9c527a486d76f6ab21/windows/cross-compile/build.sh#L876)):*
<details><summary><i>Previously, zoff99 (Zoff) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

So, are we keeping the flags or not? You undid you change to the opus build but kept it in the vpx build.

---

*[windows/cross-compile/build.sh, line 901 at r6](https://reviewable.io/reviews/qtox/qtox/5066#-LBOLQCV-Q8mVq3vt1lZ:-LBOLQCV-Q8mVq3vt1l_:b-7szqs8) ([raw file](https://github.com/qtox/qtox/blob/7ffa46343f2b1a042d29758f7c3a3229baee4711/windows/cross-compile/build.sh#L901)):*
> ```Shell
> TOXCORE_CUSTOM_VERSION=${TOXCORE_CUSTOM_VERSION:-}
> 
> if [ "$TOXCORE_CUSTOM_VERSION""x" == "x" ]; then
> ```

`then` should be on a new line and there shouldn't be `;`. That's the code format this script uses.

---

*[windows/cross-compile/build.sh, line 918 at r6](https://reviewable.io/reviews/qtox/qtox/5066#-LBOLx8N3UrUugiDefEE:-LBOLx8N3UrUugiDefEF:b-7szqs8) ([raw file](https://github.com/qtox/qtox/blob/7ffa46343f2b1a042d29758f7c3a3229baee4711/windows/cross-compile/build.sh#L918)):*
> ```Shell
>   git checkout "$TOXCORE_VERSION"
>   # do not check hash for a custom version of c-toxcore
>   if [ "$TOXCORE_CUSTOM_VERSION""x" == "x" ]; then
> ```

`then` should be on a new line and there shouldn't be `;`. That's the code format this script uses.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5066#-:-LBOMHiK-YOSnTlbgYAV:b8b79qu)*

**Comment by sudden6** [comment]
Closing since requested changes were not made.

**Pull request closed without merging**
