### PR TITLE
fix(ui): amend QCheckBox background chromatic aberration

### PR DESCRIPTION
**Pull request by jakieoymj-github**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)
#### Before:
checkboxbg1
#### After:
checkboxbg2

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5371)

### CODE REVIEW

**Comment by sudden6** [comment]
I do not really see a difference, can you point it out?

**Comment by jakieoymj-github** [comment]
sorry, I am not on PC, can point it later, there is a light gray stripe between every checkbox.

**Comment by sudden6** [comment]
I think my screen cant visualize that^^

**Comment by jakieoymj-github** [comment]
:), how about on your mobile?

**Comment by Diadlo** [comment]
@sudden6 And now?)
image

**Comment by sudden6** [comment]
@Diadlo thanks, that makes it pretty clear :DD

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5371#-:-LOEjlOQ0i-sjwSbl-Bc:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by jakieoymj-github** [comment]
checkboxbg1-point

**Comment by jakieoymj-github** [comment]
:+1:  OK

**Pull request merged**
