### PR TITLE
v1.15.0 release

### PR DESCRIPTION
**Pull request by anthonybilinski**
Somewhat rushed release due to rushed toxcore v0.2.2. Making it a minor release instead of patch release even though most changes are bug fixes, because we have a couple UI changes and minor features.

ping @sudden6 @Diadlo

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5086)

### CODE REVIEW

**Comment by Diadlo** [comment]
You forgot to add commits with changes itself

**Comment by anthonybilinski** [comment]
@Diadlo sorry I don't understand, what do you mean?

**Comment by Diadlo** [comment]
Sorry, I forgot, that we don't cherry pick commits on minor release :/

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5086#-:-LAM_8iA5Q7Qne8jFnu2:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
Going to look at merging https://github.com/qTox/qTox/pull/5083 before release, by sudden's request.

**Comment by Diadlo** [comment]
Did someone test #4983 after last fix?

**Comment by sudden6** [comment]
Travis PR updated

@Diadlo no I didn't yet, maybe ask around in IRC?

**Comment by anthonybilinski** [comment]
Current pending list of PRs blocking release:
~~https://github.com/qTox/qTox/pull/5089 - translations~~ merged
~~https://github.com/qTox/qTox/pull/5083 - Travis builds, minor review left~~ merged
~~https://github.com/qTox/qTox/pull/4983 - seems to have fairly major problems, should maybe be kicked out of v1.15.0?~~ postponing until after v1.15.0

**Comment by sudden6** [comment]
AFAICT #4983 is for nightlies, if that's right, it wouldn't matter much when merged after the release.

**Pull request merged**
