### PR TITLE
feat(icon): Color-code icons based on the profile.

### PR DESCRIPTION
**Pull request by yurivict**
Allows user to specify the color for a profile,
so that it is easy to distinguish between instances.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4315)

### CODE REVIEW

**Comment by yurivict** [comment]
https://github.com/qTox/qTox/issues/4259

**Comment by noavarice** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/persistence/settings.cpp, line 2068 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-Kgie-0T6F2E7lUnj3kT:-Kgie-0T6F2E7lUnj3kU:b-ct2ydw) ([raw file](https://github.com/qtox/qtox/blob/892bec2e09905f5f8e64506b40579d839207b7c2/src/persistence/settings.cpp#L2068)):*
> ```cpp
> }
> 
> QPair<bool, QColor> Settings::getProfileColor() const
> ```

Returning pair of items from `getProfileColor` method looks a bit weird. Why didn't you declare single getter and setter for each property?

---

*[src/persistence/settings.cpp, line 2074 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KgieSj_D_pbPaWIoBxy:-KgieSj_D_pbPaWIoBxz:bja0nre) ([raw file](https://github.com/qtox/qtox/blob/892bec2e09905f5f8e64506b40579d839207b7c2/src/persistence/settings.cpp#L2074)):*
> ```cpp
> }
> 
> void Settings::setProfileColor(bool enabled, const QColor& color)
> ```

Same as above - even if you just want to disable profile color, you also needs to pass color

---

*[src/widget/icon.h, line 26 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KgigUStMzEzCmU5KWDJ:-KgigUSuz1C_8GwFDKB7:b-7hhwu6) ([raw file](https://github.com/qtox/qtox/blob/892bec2e09905f5f8e64506b40579d839207b7c2/src/widget/icon.h#L26)):*
> ```objc
> class QColor;
> 
> class Icon
> ```

IMO, such class name does not fully represent its meaning. Maybe change it to smth like `IconPainter`? Just make it more clear for comprehension. And add docs for your class and methods which you have described

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4315)*

**Comment by yurivict** [comment]
@noavarice 
> Returning pair of items from getProfileColor method looks a bit weird. Why didn't you declare single getter and setter for each property?

Since there is a mutex in ```Settings```, it is logical to set related values together in one operation. So setting them together is logically sound, though it may look weird. I used QPair to avoid defining a structure for this.

**Comment by Diadlo** [comment]
@yurivict How mutex related with return value?
Added: mutex used to avoid simultaneous code execution by few threads. There is no specific "logic"

**Comment by yurivict** [comment]
> How mutex related with return value?

Assuming that others can change the value any time, mutex will preserve the value consistency and will allow to return the values intact. With separate setters/getters this will not be true. Value x can be changed by A, then returned to B, then value y can be changed by A and returned to B. A meant to change {x,y} together, but due to their separateness B will get the {x,y} combination that was never meant to be set.

I am not implying that this is very relevant to qTox, but that is one of the effects of the mutex.

**Comment by Diadlo** [comment]
What about using invalid color (`QColor()`) for disabled profile color?

**Comment by yurivict** [comment]
> What about using invalid color (QColor()) for disabled profile color?

Then the user will need to select the color again after turning it off and on.

**Comment by Diadlo** [comment]
@yurivict Now I see, that they independently. User can change color independent of enabling/disabling feature

**Comment by yurivict** [comment]
@Diadlo There are actually no changes that are requested. Could you please remove PR-changes-required?

**Comment by zetok** [comment]
@yurivict right now there are merge conflicts, and there's not needed `Merge branch 'master' of github.com:qTox/qTox into icons-color-coded` merge commit.

**Comment by Diadlo** [comment]
No, it's still require changes

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/persistence/settings.cpp, line 2068 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-Kgie-0T6F2E7lUnj3kT:-KmuXpusmlpkAyzs0VGl:bnqfdof) ([raw file](https://github.com/qtox/qtox/blob/d72dddd1233ed83951cb16558b70dd397bbfa0e7/src/persistence/settings.cpp#L2068)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Returning pair of items from `getProfileColor` method looks a bit weird. Why didn't you declare single getter and setter for each property?
</blockquote></details>

What about storing both variables. But here use `return useProfileColor ? profileColor : QColor();` ?

---

*[src/persistence/settings.cpp, line 2074 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KgieSj_D_pbPaWIoBxy:-KmuY11EejF1BCHKIIyO:bkpz7wx) ([raw file](https://github.com/qtox/qtox/blob/d72dddd1233ed83951cb16558b70dd397bbfa0e7/src/persistence/settings.cpp#L2074)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as above - even if you just want to disable profile color, you also needs to pass color
</blockquote></details>

Agree with @noavarice. Should be splitted on 2

---

*[src/persistence/settings.cpp, line 2081 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KmuZHgkpXTMBQn8SQUW:-KmuZHgkpXTMBQn8SQUX:bsblw2x) ([raw file](https://github.com/qtox/qtox/blob/d72dddd1233ed83951cb16558b70dd397bbfa0e7/src/persistence/settings.cpp#L2081)):*
> ```cpp
>         useProfileColor = enabled;
>         profileColor = color;
>         emit profileColorChanged(useProfileColor, profileColor);
> ```

Same with `useProfileColor ? profileColor : QColor();`

---

*[src/widget/icon.cpp, line 2 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KmuJxpA1yJXmWMh-FiO:-KmuJxpA1yJXmWMh-FiP:bla86o2) ([raw file](https://github.com/qtox/qtox/blob/d72dddd1233ed83951cb16558b70dd397bbfa0e7/src/widget/icon.cpp#L2)):*
> ```cpp
> /*
>     Copyright © 2014-2015 by The qTox Project Contributors
> ```

Bump copyright

---

*[src/widget/icon.h, line 2 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KmuK24Yt8FgXeJpaE1s:-KmuK24Yt8FgXeJpaE1t:bla86o2) ([raw file](https://github.com/qtox/qtox/blob/d72dddd1233ed83951cb16558b70dd397bbfa0e7/src/widget/icon.h#L2)):*
> ```objc
> /*
>     Copyright © 2014-2015 by The qTox Project Contributors
> ```

Bump copyright

---

*[src/widget/icon.h, line 26 at r1](https://reviewable.io:443/reviews/qtox/qtox/4315#-KgigUStMzEzCmU5KWDJ:-KmuK6wj_uksbh_LuV-q:b9sjbcq) ([raw file](https://github.com/qtox/qtox/blob/d72dddd1233ed83951cb16558b70dd397bbfa0e7/src/widget/icon.h#L26)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

IMO, such class name does not fully represent its meaning. Maybe change it to smth like `IconPainter`? Just make it more clear for comprehension. And add docs for your class and methods which you have described
</blockquote></details>

Agree with @noavarice
Also, if here just one static method, maybe declare it as function?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4315#-:-KmuXWmoLs4U77GorsHT:b-5bchen)*

**Comment by Diadlo** [comment]
PR didn't have any activity for over 2 months, and no one seems to be interested in working on it, thus closing.

If that's not the case, please either ask to reopen the pull, or make a new one.

**Pull request closed without merging**
