### PR TITLE
microphone mute and volume control buttons. Attempt #2

### PR DESCRIPTION
**Pull request by mdnight**
There was implemented microphone muting for calls. Volume control is not ready yet

### CODE REVIEW

**Comment by tux3** [comment]
Somehow your pr still conflicts with my master branch. I'll try to resolve later if you don't have the time.

**Comment by tux3** [comment]
Conflicts resolved and pr merged manually (5e5bb66409948f7d65d250fee3edfc2660757ba8 ... a75666a072834cab56d94951b310c17eaa0af1d0)

**Comment by ghost** [comment]
Those icons need some work imo.

**Comment by tux3** [comment]
I agree with @mannol1 
They aren't all that bad, but could use some improvement imho. Also the small mic/vol icons aren't aligned with the bigger A/V call buttons.

**Comment by mdnight** [comment]
Like this?

Sorry if my icons aren't so good. This is my first experience in drawing icons.

**Pull request closed without merging**
