### PR TITLE
chore(windows): build installer on Travis

### PR DESCRIPTION
**Pull request by sudden6**
The installer seems to correctly install qTox and qTox seems to work too, tested on wine64

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5016)

### CODE REVIEW

**Comment by Diadlo** [comment]
And how we can download it from travis?

**Comment by sudden6** [comment]
This PR is just about getting the installer to build, for deploying see https://github.com/qTox/qTox/pull/5017

**Comment by sudden6** [comment]
@Diadlo ping

**Comment by Diadlo** [comment]
Otherwise :lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[windows/cross-compile/build.sh, line 1120 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5016#-L8qUJm89LN4eA8s-U2w:-L8qUJm89LN4eA8s-U2x:b30vjkz) ([raw file](https://github.com/qtox/qtox/blob/7305bb3bccf97956b88998ec8a06ed7f6cc24f2f/windows/cross-compile/build.sh#L1120)):*
> ```Shell
>   # the installer creation script expects all the files in qtox/*
>   mkdir qtox
>   cp -R $QTOX_PREFIX_DIR/* ./qtox
> ```

Quotes?

---

*[windows/cross-compile/build.sh, line 1131 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5016#-L8qULZL75MQHbIalyAd:-L8qULZL75MQHbIalyAe:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/7305bb3bccf97956b88998ec8a06ed7f6cc24f2f/windows/cross-compile/build.sh#L1131)):*
> ```Shell
>   fi
> 
>   cp setup-qtox.exe $QTOX_PREFIX_DIR/setup-qtox-"$ARCH".exe
> ```

Same as above

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5016#-:-L8qYPAF5Qre81eRQSp6:b-tbxt33)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[windows/cross-compile/build.sh, line 1120 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5016#-L8qUJm89LN4eA8s-U2w:-L8rKaVh9V9z06MYSXnI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7305bb3bccf97956b88998ec8a06ed7f6cc24f2f/windows/cross-compile/build.sh#L1120)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Quotes?
</blockquote></details>

Done.

---

*[windows/cross-compile/build.sh, line 1131 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5016#-L8qULZL75MQHbIalyAd:-L8rKbBE85dFojzaFHIy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7305bb3bccf97956b88998ec8a06ed7f6cc24f2f/windows/cross-compile/build.sh#L1131)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5016)*

**Comment by nurupo** [comment]
Um, when we setup NSIS on Jenkins we went out of our way to get NSIS 3 because NSIS 2 was lacking something (@tux3 might remember, was it Windows 10 support?). Are you sure you are fine with using NSIS 2?

Also, why not cache the NSIS plugin, like it's done with all of the dependencies, why download it every time?

**Comment by sudden6** [comment]
uh, I thought the recent Debian version already has nsis 3...
I don't know anything about NSIS, so I'm not sure what could be missing, at this stage I'm already happy it produces a working installer.

Caching the plugin should definitely be done, will try to do that after getting the deployment to work.

**Comment by nurupo** [comment]
I will try making some NSIS improvements, e.g. using NSIS 3 and caching the plugin.

Not sure if I will have time for this, but I might also look into the deployment. I see there is already separate PR for this.

**Comment by sudden6** [comment]
That would be very helpful, also with the path to reproducible builds.

The other PR should work™ I just don't know how to test the deployment on GH?

**Comment by nurupo** [comment]
About reproducible builds, I'm pulling NSIS 3 from Debian Experimental, which is not a fixed version, the maintainer often updates it, so today I could install one version of NSIS 3 (e.g. 3.0.2), but on the next day the NSIS package maintainer might push NSIS 3.0.3 into there, which is what you would install, which might result in us having different installers.

I thought of building a fixed version of NSIS 3 manually, [but it seems rather non-trivial](https://salsa.debian.org/debian/nsis/blob/debian/master/debian/rules), which is why I have resorted to pulling it from Debian Experimental.

**Comment by sudden6** [comment]
"rather non-trivial" :DD slight understatement^^

maybe reproducible builds should be 2nd priority then.

**Comment by nurupo** [comment]
>I'm pulling NSIS 3 from Debian Experimental

Okay, I can't pull it from Experimental anymore, NSIS maintainer removed NSIS 3 from Experimental. He moved it into Unstable yesterday, so Unstable now got NSIS 3. Soon Testing will get it too. At this rate  NSIS 3 might get included into the next Debian Stable release! Glad to see this development, NSIS 3 was sitting in Experimental for about a year and a half now, if not longer.

**Comment by nurupo** [comment]
>The other PR should work™ I just don't know how to test the deployment on GH?

Maybe just push a test tag?

**Comment by nurupo** [comment]
Huh, it takes about 15 minutes to build NSIS 3 because it uses mostly 1 job.

**Comment by sudden6** [comment]
I tried to push a test tag, no deployment or even a notice in the logs happened.

**Pull request merged**
