### PR TITLE
feat(core): Disk usage control

### LINKED ISSUE #3946: qTox should inform user that there's no free space on disk to save things
##### Brief Description
Currently qTox doesn't inform user that there is "no space left on the device", instead silently failing to do stuff it is required to do, or creating cryptic errors that have nothing to do with the actual problem.

OS: Gentoo Linux amd64
qTox version: v1.6.0-58-gfeaedee
Commit hash: feaedeed841f419a8eb5b7f40a14e27ef1e104cb
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always

##### Steps to reproduce

1. Mount a small FS: `mkdir fill && sudo mount -t tmpfs -o size=2m,uid=$UID none fill`
2. Start qTox there and make some history `HOME="$PWD/fill" TMPDIR="$PWD/fill" qtox`
3. Close and reopen qTox to make sure that history has been saved (no need to quit it, logout is enough)
4. Fill the mount: `cat /dev/zero > fill/zeros`
5. Try to do things. Sending messages, changing options, whatever, anything that causes writes.

##### Observed Behavior
Some errors in the stdout, little to no errors that user sees, and 0 visible errors that actually inform user what the problem is.

##### Expected Behavior
Visible (GUI) error about no free space on the HDD. Preferably with some instructions for user what to do to free space, perhaps e.g. `You could try to delete some recently downloaded files that take a lot of space`, or something.

##### Additional Info

Some errors:
```
[22:19:45.633 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:19:58.582 UTC] persistence/db/rawdatabase.cpp:651 : Warning: Unknown error 13 executing query "DELETE FROM faux_offline_pending WHERE id=3;"
[22:20:29.343 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:29.344 UTC] widget/systemtrayicon.cpp:99 : Debug: Deleting SystemTrayIcon
[22:20:29.349 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:29.349 UTC] persistence/profile.cpp:408 : Critical: Failed to write, can't save!
[22:20:29.349 UTC] persistence/settings.cpp:656 : Debug: Saving personal settings at  "/home/zetok/working/delete/up/fill/.config/tox/bterased.ini"
[22:20:29.350 UTC] persistence/settingsserializer.cpp:346 : Critical: Failed to write, can't save!
[22:20:40.870 UTC] persistence/profile.cpp:104 : Debug: Loading tox save  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:40.871 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:40.871 UTC] persistence/settings.cpp:358 : Debug: Loading personal settings from "/home/zetok/working/delete/up/fill/.config/tox/bterased.ini"
[22:20:41.133 UTC] core/core.cpp:252 : Debug: Loading user profile
[22:20:41.133 UTC] persistence/profile.cpp:299 : Debug: Loading tox save  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:41.133 UTC] core/core.cpp:136 : Debug: Core starting with IPv6 enabled
[22:20:41.134 UTC] core/core.cpp:321 : Debug: Self avatar not found, will broadcast empty avatar to friends
[22:20:41.163 UTC] core/core.cpp:397 : Debug: Disconnected from the DHT
[22:20:41.925 UTC] widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[22:20:42.633 UTC] core/core.cpp:425 : Debug: "Connecting to 5.135.59.163:33445 (Skey)"
[22:20:42.633 UTC] core/core.cpp:425 : Debug: "Connecting to sorunome.de:33445 (Sorunome)"
[22:20:47.482 UTC] core/core.cpp:425 : Debug: "Connecting to tox.zodiaclabs.org:33445 (stal)"
[22:20:47.783 UTC] core/core.cpp:425 : Debug: "Connecting to v6.tox.zodiaclabs.org:33445 (stal)"
[22:20:48.264 UTC] persistence/db/rawdatabase.cpp:651 : Warning: Unknown error 13 executing query "INSERT INTO history (timestamp, chat_id, message, sender_alias) VALUES (1481062848262, 0, ?, (  CASE WHEN changes() IS 0 THEN (    SELECT id FROM aliases WHERE owner=1 AND display_name=?)  ELSE last_insert_rowid() END));"
[22:20:51.634 UTC] core/core.cpp:389 : Debug: Connected to the DHT
[22:20:51.635 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:51.635 UTC] persistence/profile.cpp:408 : Critical: Failed to write, can't save!
[22:20:54.599 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:54.599 UTC] widget/systemtrayicon.cpp:99 : Debug: Deleting SystemTrayIcon
[22:20:54.604 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:54.604 UTC] persistence/profile.cpp:408 : Critical: Failed to write, can't save!
[22:20:54.605 UTC] persistence/settings.cpp:656 : Debug: Saving personal settings at  "/home/zetok/working/delete/up/fill/.config/tox/bterased.ini"
[22:20:54.605 UTC] persistence/settingsserializer.cpp:346 : Critical: Failed to write, can't save!
[22:20:56.948 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:56.949 UTC] main.cpp:312 : Debug: Clean exit with status 0
```

After the quit ↑ and starting qTox again it's not possible to login, as qTox claims that profile is already in use -.-"

```
[22:20:58.706 UTC] :0 : Debug: using qt5ct plugin
[22:20:58.735 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:58.747 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  11895995666887129815
[22:20:58.748 UTC] main.cpp:210 : Debug: built on:  04:33:24 Dec  6 2016 ( 1480998802 )
[22:20:58.748 UTC] main.cpp:211 : Debug: commit:  feaedeed841f419a8eb5b7f40a14e27ef1e104cb 

[22:20:58.748 UTC] nexus.cpp:85 : Debug: Starting up
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No such file or directory
[22:21:09.553 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:21:09.554 UTC] main.cpp:312 : Debug: Clean exit with status 0
```

### PR DESCRIPTION
**Pull request by tWido**
Fixes #3946

Upon start disk usage is controlled. If usage exceeds threshold user is warned.
If disk is full program notifies user and exits.

On write operation error disk usage is checked.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4500)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main.cpp, line 324 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkTpU4OWvUq7KASulb:-KnkTpU4OWvUq7KASulc:bxnyzvz) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/main.cpp#L324)):*
> ```cpp
> 
>     bool cacheOk = true, dataOk = true, settingsOk = true;
>     bool diskFull = (QFileInfo::exists(cacheDir) && CheckDisk::diskFull(cacheDir, cacheOk))
> ```

I think that it might be a good idea to add a comment above reminding that those files can be located on separate filesystems

---

*[src/main.cpp, line 334 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkSlTeRnZEhXu_HaBL:-KnkSlTeRnZEhXu_HaBM:b-ssr5of) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/main.cpp#L334)):*
> ```cpp
>     if (diskFull) {
>         qCritical() << "Disk full, exiting!";
>         GUI::showError("Disk error", "Disk full. Exiting.");
> ```

Enclose strings that are shown in GUI to user with `tr()`

`s/Disk full/Disk is full/`

---

*[src/persistence/checkdisk.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkRtmtOVBnBBTmzDQR:-KnkRtmtOVBnBBTmzDQS:blx1j5s) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L9)):*
> ```cpp
> 
> // Consider less bytes available as full disk
> #define RESERVE_SIZE 102400
> ```

E.g. my profile is ~375 KiB big.

100 KiB is nowhere near enough. Should be at least 1, if not 10 MiB.

---

*[src/persistence/checkdisk.cpp, line 12 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkSO5EIunBqjNxLKWP:-KnkSO5EIunBqjNxLKWQ:b-2f34oj) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L12)):*
> ```cpp
> 
> /**
>  * @brief Check is disk full.
> ```

It should be: `Check if disk is full`

---

*[src/persistence/checkdisk.cpp, line 17 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkW8prXhO4ki3ei8Du:-KnkW8prXhO4ki3ei8Dv:b-b1q4jt) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L17)):*
> ```cpp
>  * @return True if disk is full or error occured, else false.
>  */
> bool CheckDisk::diskFull(const QString& path, bool& ok)
> ```

Perhaps bool name to `no_err` or `no_error` would be better?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by Diadlo** [comment]
Reviewed 3 of 8 files at r1.
Review status: 3 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/checkdisk.cpp, line 17 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkW8prXhO4ki3ei8Du:-KnkbteSon55YfsUElKn:bjuhuey) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L17)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Perhaps bool name to `no_err` or `no_error` would be better?
</blockquote></details>

@zetok If so `noErr` and `noError` :)

---

*[src/persistence/checkdisk.cpp, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkJhwyMvNdbeEi6gGp:-KnkJhwzDx3nykE6FQbI:b-xht8jc) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L45)):*
> ```cpp
> {
>     QStorageInfo info(path);
>     if (info.bytesAvailable() == -1 || file.size() < info.bytesAvailable()) {
> ```

Use `return info.bytesAvailable() != -1 && file.size() >= info.bytesAvailable();`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by tWido** [comment]
Review status: 2 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main.cpp, line 324 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkTpU4OWvUq7KASulb:-Knooexy6R9Wy6pMrw_J:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/main.cpp#L324)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

I think that it might be a good idea to add a comment above reminding that those files can be located on separate filesystems
</blockquote></details>

Done.

---

*[src/main.cpp, line 334 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkSlTeRnZEhXu_HaBL:-KnoosVoLeqXmlAtMhn-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/main.cpp#L334)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Enclose strings that are shown in GUI to user with `tr()`

`s/Disk full/Disk is full/`
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkRtmtOVBnBBTmzDQR:-KnoovT3Qbn3kE1r3G6-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L9)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

E.g. my profile is ~375 KiB big.

100 KiB is nowhere near enough. Should be at least 1, if not 10 MiB.


</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 12 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkSO5EIunBqjNxLKWP:-KnooxOuWRSag6MOhHkQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L12)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

It should be: `Check if disk is full`
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 17 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkW8prXhO4ki3ei8Du:-Knop0EjwwkQ5ZT762Y9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L17)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

@zetok If so `noErr` and `noError` :)
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkJhwyMvNdbeEi6gGp:-Knop1zKTlwmZER1gK1e:b-ux094) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L45)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Use `return info.bytesAvailable() != -1 && file.size() >= info.bytesAvailable();`
</blockquote></details>

Original was actually a mistake. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by zetok** [comment]
Review status: 2 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/persistence/checkdisk.cpp, line 1 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnpXlIdmUZ5aolrC8Ll:-KnpXlIeyn_phBpNDm4Q:bm2cdxu) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/persistence/checkdisk.cpp#L1)):*
> ```cpp
> 
> ```

Add missing copyright header, also to the new header file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by Diadlo** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/main.cpp, line 335 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnplsorxdgX-bEJrqYO:-KnplsorxdgX-bEJrqYP:b-7ht1tn) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/main.cpp#L335)):*
> ```cpp
>     if (diskFull) {
>         qCritical() << "Disk full, exiting!";
>         GUI::showError(QObject::tr("Disk full"), QObject::tr("Disk is full."));
> ```

Still `Disk full` but in other place :)

---

*[src/persistence/checkdisk.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkRtmtOVBnBBTmzDQR:-KnpmFK0shDRh4U2pEzW:b2u498v) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L9)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you use `1024 * 1024 * 10`?

---

*[src/persistence/settingsserializer.cpp, line 317 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnpoHXv0FG2mRdoYnM2:-KnpoHXv0FG2mRdoYnM3:b70jl09) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/persistence/settingsserializer.cpp#L317)):*
> ```cpp
>         f.cancelWriting();
>         if (!CheckDisk::canWrite(path, f)) {
>             GUI::showError(QObject::tr("Disk full"), QObject::tr("Operation failed due to full disk. Clear some space!"));
> ```

I think we should add `bool` result to this function and do this check on upper level? 
To avoid using GUI here

---

*[src/persistence/db/rawdatabase.cpp, line 637 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-Knpoj1BVTeKy1Z2i2xR:-Knpoj1BVTeKy1Z2i2xS:bxdtc2q) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/persistence/db/rawdatabase.cpp#L637)):*
> ```cpp
>                         QString message = (ok) ? "Disk full error" : "Disk write error";
>                         qCritical() << message << "while executing query" << anonQuery;
>                         GUI::showError(tr("Disk error"), tr(message.toStdString().c_str()));
> ```

Same as above.
To make my position clear: I think we should avoid connection non-GUI part of application with GUI. Currently qTox has a lot of problem with this, but we try to improve the situation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by tWido** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/persistence/checkdisk.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkRtmtOVBnBBTmzDQR:-KntUBcW1nX68R3XoKp7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L9)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can you use `1024 * 1024 * 10`?
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 1 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnpXlIdmUZ5aolrC8Ll:-KntU9aZXjDA5AYxATeT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/persistence/checkdisk.cpp#L1)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Add missing copyright header, also to the new header file.
</blockquote></details>

Done.

---

*[src/persistence/db/rawdatabase.cpp, line 637 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-Knpoj1BVTeKy1Z2i2xR:-KntUKQJG5NT_A66MuCm:b-c12j8h) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/persistence/db/rawdatabase.cpp#L637)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above.
To make my position clear: I think we should avoid connection non-GUI part of application with GUI. Currently qTox has a lot of problem with this, but we try to improve the situation
</blockquote></details>

I got your point and agree. But i think i should start an separate issue and PR for that to avoid mixing new feature and refactoring project functions.  But if you insist i can do it in this issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by zetok** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/persistence/checkdisk.cpp, line 2 at r3](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnttU5xF0US3Pe8gxYB:-KnttU5xF0US3Pe8gxYC:b-910vha) ([raw file](https://github.com/qtox/qtox/blob/9e0f84a6ecf73ea3ee69cdde9510729b23d7834a/src/persistence/checkdisk.cpp#L2)):*
> ```cpp
> /*
>     Copyright © 2015-2016 by The qTox Project Contributors
> ```

This doesn't seem right? If code was written in 2017 (and there's no earlier code), it should be `Copyright © 2017`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by tWido** [comment]
Review status: 6 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/persistence/checkdisk.cpp, line 2 at r3](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnttU5xF0US3Pe8gxYB:-KnxMFlJd1xDx5OZ3IAC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9e0f84a6ecf73ea3ee69cdde9510729b23d7834a/src/persistence/checkdisk.cpp#L2)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This doesn't seem right? If code was written in 2017 (and there's no earlier code), it should be `Copyright © 2017`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/persistence/db/rawdatabase.cpp, line 637 at r2](https://reviewable.io:443/reviews/qtox/qtox/4500#-Knpoj1BVTeKy1Z2i2xR:-Knx_hDCviYDgnpiKPS-:b-jclh16) ([raw file](https://github.com/qtox/qtox/blob/ff65b5089abd466160255ddf916e1630653ddae8/src/persistence/db/rawdatabase.cpp#L637)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

I got your point and agree. But i think i should start an separate issue and PR for that to avoid mixing new feature and refactoring project functions.  But if you insist i can do it in this issue.
</blockquote></details>

We just can't write bad code with reference to the fact that we will correct it later :)
You can do this changes in another commit in this PR to avoid mixing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/main.cpp, line 338 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-Kob5P_Ybi3SSDypPBj9:-Kob5P_Ybi3SSDypPBjA:b-tc3sot) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/main.cpp#L338)):*
> ```cpp
>     }
> 
>     if (!diskFull && (CheckDisk::diskUsage(cacheDir, cacheOk) > DISK_WARN_THRESHOLD
> ```

These conditions are mutually exclusive -- `diskFull` in previous and `!diskFull` here, use `else`

---

*[src/main.cpp, line 340 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-Kob5fJkqeJRDwipyiD6:-Kob5fJkqeJRDwipyiD7:b-y1bqkp) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/main.cpp#L340)):*
> ```cpp
>     if (!diskFull && (CheckDisk::diskUsage(cacheDir, cacheOk) > DISK_WARN_THRESHOLD
>                       || CheckDisk::diskUsage(dataDir, dataOk) > DISK_WARN_THRESHOLD
>                       || CheckDisk::diskUsage(settingsDir, settingsOk) > DISK_WARN_THRESHOLD)) {
> ```

Summarizing these block of code, you can declare array of dir names, single bool variable and process this data the way you need -- this helps to avoid code duplicating. Or move `Settings::getInstance` to `const Settings&` for starting

---

*[src/main.cpp, line 341 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-Kob6YGpMNCTg8TO-GeY:-Kob6YGpMNCTg8TO-GeZ:bjoik08) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/main.cpp#L341)):*
> ```cpp
>                       || CheckDisk::diskUsage(dataDir, dataOk) > DISK_WARN_THRESHOLD
>                       || CheckDisk::diskUsage(settingsDir, settingsOk) > DISK_WARN_THRESHOLD)) {
>         qWarning() << "Disk almost full";
> ```

Disk is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by yurivict** [comment]
Please change: qWarning() << "Disk is almost full";
Even better is you also include how many MB are left.
> qWarning() << "Disk is almost full (free space is only N MB)";

What is holding this?

**Comment by tWido** [comment]
Nothing is holding this. I just have been busy lately.  Hopefully i will have more time in upcoming week.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500#-:-KpkvGEpX_sqTIo7DE2x:bg3cv2s)*

**Comment by Talkless** [comment]
Reviewed 2 of 8 files at r1, 4 of 6 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[src/main.cpp, line 319 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-KrulgD8a17qKWf2FRF2:-KrulgD9LO73QmvYTXxC:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/main.cpp#L319)):*
> ```cpp
> 
> 
>     QString cacheDir = Settings::getInstance().getAppCacheDirPath();
> ```

const QString

---

*[src/main.cpp, line 320 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-KrulhogFUgyXo1LwOrD:-KrulhogFUgyXo1LwOrE:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/main.cpp#L320)):*
> ```cpp
> 
>     QString cacheDir = Settings::getInstance().getAppCacheDirPath();
>     QString dataDir = Settings::getInstance().getAppDataDirPath();
> ```

const QString

---

*[src/main.cpp, line 321 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-KrulnwWS8wSCxmRMyRY:-KrulnwWS8wSCxmRMyRZ:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/main.cpp#L321)):*
> ```cpp
>     QString cacheDir = Settings::getInstance().getAppCacheDirPath();
>     QString dataDir = Settings::getInstance().getAppDataDirPath();
>     QString settingsDir = Settings::getInstance().getSettingsDirPath();
> ```

const QString

---

*[src/persistence/checkdisk.cpp, line 45 at r1](https://reviewable.io:443/reviews/qtox/qtox/4500#-KnkJhwyMvNdbeEi6gGp:-KrumbeCbJTG7Jq6iQYN:b-ytygqd) ([raw file](https://github.com/qtox/qtox/blob/8027d799ef40b1cd672aa60bc5417df5cba0e027/src/persistence/checkdisk.cpp#L45)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Original was actually a mistake. Thanks.
</blockquote></details>

It would suggest to wrap into extra parentheses, because there's lot's going on. ( ( ) && ( ) )

---

*[src/persistence/db/rawdatabase.cpp, line 635 at r4](https://reviewable.io:443/reviews/qtox/qtox/4500#-Krun1cg381a68bKgia0:-Krun1cg381a68bKgia1:bwv9iwf) ([raw file](https://github.com/qtox/qtox/blob/20105dfaaf151dfe129e52564e4da849b913aad6/src/persistence/db/rawdatabase.cpp#L635)):*
> ```cpp
>                     bool ok;
>                     if (CheckDisk::diskFull(this->path, ok)) {
>                         QString message = (ok) ? "Disk full error" : "Disk write error";
> ```

const QString message
QStringLiteral("Disk full....")
See https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#strings

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4500)*

**Comment by sudden6** [comment]
Closing since this one is very outdated.

**Pull request closed without merging**
