### PR TITLE
Desktop sharing on Mac OS X

### LINKED ISSUE #2558: OS X El Capitan — built-in camera isn't detected.
Video Device: none
Commit hash: c568a4db051762c3ec084415194df9335b4b1d55
OS: latest El Capitan
MBP 2015

### PR DESCRIPTION
**Pull request by briskycat**
I have implemented desktop sharing on Mac OS X. This should finally fully resolve https://github.com/tux3/qTox/issues/2558, and (partially at least) https://github.com/tux3/qTox/issues/2487.

### CODE REVIEW

**Comment by RowenStipe** [comment]
Since Travis is broken, I'm chiming in to say it builds properly!

**Comment by agilob** [comment]
Could anyone confirm this?

**Comment by agilob** [comment]
If @RowenStipe confirm this works as expected I can merge it...

**Comment by RowenStipe** [comment]
It looks good to me.

**Comment by RowenStipe** [comment]
After doing a manual rebase for current commit https://github.com/tux3/qTox/commit/b8a0a7d4043e9f0395207d84414ca0e7ba37f28b this pull will work as intended.



This also helps close issues:
https://github.com/tux3/qTox/issues/2470
https://github.com/tux3/qTox/issues/2487

**Comment by agilob** [comment]
OK

**Pull request merged**
