### PR TITLE
Added Kiss smiley shortcut for Universe

### PR DESCRIPTION
**Pull request by NicoHood**
Fix for #4000
Was NOT tested, but the changes are trivial.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4002)

### CODE REVIEW

**Comment by Diadlo** [comment]
@NicoHood Thanks for your PR. Please, update commit message to satisfy [format](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format)

**Comment by NicoHood** [comment]
Force pushed. Better now?

**Comment by Diadlo** [comment]
Yes :lgtm: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4002#-:-KZh2dGCyadlQCXbRL5s:bcyxguu)*

**Comment by Diadlo** [comment]
Can you also update `emoticons` pack? If not, I will merge it

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4002#-:-KZh48gPMjRPfZWwSpls:boyy6gb)*

**Comment by NicoHood** [comment]
The pack you mentioned does not exist. I've updated `emojione` instead. Please merge now if its still okay. Thanks :)

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4002#-:-KZhUfHbrJosbG4HxYNj:bnfp4nl)*

**Comment by zetok** [comment]
@sudden6 ?

**Pull request merged**
