### PR TITLE
fix(preview): only downscale preview images, never upscale

### LINKED ISSUE #4733: [Proposal] Don't upscale image preview, only downscale if necessary
##### Observed Behavior
Hovering over an image in chat causes it to preview. The image is scaled to keep aspect ration and be 50% of screen height and/or 50% of screen width.

Sending a small image i.e. of a piece of text can result in a huge preview of giant blurry grey text that is harder to read than if it was just displayed at the actual size of the capture. I don't think upscaling is generally desirable and it adds blur.

##### Expected Behavior
If the image's width and height are both under 50% of screen, do not scale at all and preview at natural size. If either is larger, then downscale to 50%, like we currently do.

Do people agree that this behaviour should be changed, or do they prefer the way it is, scaling any size image to be 50% of width and 50% of height?

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4733

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4734)

### CODE REVIEW

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 552 at r1](https://reviewable.io:443/reviews/qtox/qtox/4734#-KwQ2CXPBrvmU4vNm0hn:-KwQ2CXQBT7mdExfIIjZ:b-2ufmfi) ([raw file](https://github.com/qtox/qtox/blob/a97acb4afb108846dfc15ec605ea4b67d41cd619/src/chatlog/content/filetransferwidget.cpp#L552)):*
If you'd use uniform call syntax:
```
const int maxPreviewWidth{0.5 * foo()};
```
You would get narrowing warning:
```
/tmp/narrowing/main.cpp:12: warning: narrowing conversion of ‘(5.0e-1 * (double)foo()())’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]
     const int maxPreviewWidth{0.5 * foo()};
                                ~~~~^~~~~~~
```
So the moder way would be:
```
 const int maxPreviewWidth{static_cast<int>(0.5 * foo())};
```
Although it's kinda verbose. On the other hand, it's visible that we are casting...

[ES.23: Prefer the {} initializer syntax](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#es23-prefer-the--initializer-syntax)
> Note {}-initializers do not allow narrowing conversions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 554 at r1](https://reviewable.io:443/reviews/qtox/qtox/4734#-KwQ4Ib5zSs0BlpQst05:-KwQ4Ib5zSs0BlpQst06:b-st7jng) ([raw file](https://github.com/qtox/qtox/blob/a97acb4afb108846dfc15ec605ea4b67d41cd619/src/chatlog/content/filetransferwidget.cpp#L554)):*
> ```cpp
>         const int maxPreviewWidth = 0.5 * desktopSize.width();
>         const int maxPreviewHeight = 0.5 * desktopSize.height();
>         QImage previewImage;
> ```

Default constructor could be avoided in reference to [ES.28: Use lambdas for complex initialization, especially of const variables](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#es28-use-lambdas-for-complex-initialization-especially-of-const-variables), while keeping it const:
```
// psiaudo code
const QImage previewImage = [&image, maxPreviewWidtd, maxPreviewHeight]() {
  if (...)
    return image.scaled(...)
 else 
   return image;
}();
```


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 552 at r1](https://reviewable.io:443/reviews/qtox/qtox/4734#-KwQ2CXPBrvmU4vNm0hn:-Kwq8GpfwArOLbvb1VHv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a97acb4afb108846dfc15ec605ea4b67d41cd619/src/chatlog/content/filetransferwidget.cpp#L552)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

If you'd use uniform call syntax:
```
const int maxPreviewWidth{0.5 * foo()};
```
You would get narrowing warning:
```
/tmp/narrowing/main.cpp:12: warning: narrowing conversion of ‘(5.0e-1 * (double)foo()())’ from ‘double’ to ‘int’ inside { } [-Wnarrowing]
     const int maxPreviewWidth{0.5 * foo()};
                                ~~~~^~~~~~~
```
So the moder way would be:
```
 const int maxPreviewWidth{static_cast<int>(0.5 * foo())};
```
Although it's kinda verbose. On the other hand, it's visible that we are casting...

[ES.23: Prefer the {} initializer syntax](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#es23-prefer-the--initializer-syntax)
> Note {}-initializers do not allow narrowing conversions.
</blockquote></details>

Done.

---

*[src/chatlog/content/filetransferwidget.cpp, line 554 at r1](https://reviewable.io:443/reviews/qtox/qtox/4734#-KwQ4Ib5zSs0BlpQst05:-Kwq8HGFf1ZCEiUwT9Ro:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a97acb4afb108846dfc15ec605ea4b67d41cd619/src/chatlog/content/filetransferwidget.cpp#L554)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Default constructor could be avoided in reference to [ES.28: Use lambdas for complex initialization, especially of const variables](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines.html#es28-use-lambdas-for-complex-initialization-especially-of-const-variables), while keeping it const:
```
// psiaudo code
const QImage previewImage = [&image, maxPreviewWidtd, maxPreviewHeight]() {
  if (...)
    return image.scaled(...)
 else 
   return image;
}();
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 552 at r1](https://reviewable.io:443/reviews/qtox/qtox/4734#-KwQ2CXPBrvmU4vNm0hn:-KwuJBELmTVIzD8SbcPZ:b-i3k4ju) ([raw file](https://github.com/qtox/qtox/blob/a97acb4afb108846dfc15ec605ea4b67d41cd619/src/chatlog/content/filetransferwidget.cpp#L552)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Now I wonder, couldn't it be simpler to use integer division:
```
const int maxPreviewWidth{desktopSize.width() / 2};
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/content/filetransferwidget.cpp, line 552 at r1](https://reviewable.io:443/reviews/qtox/qtox/4734#-KwQ2CXPBrvmU4vNm0hn:-Kwv9XXZxFWP1sYZwITe:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a97acb4afb108846dfc15ec605ea4b67d41cd619/src/chatlog/content/filetransferwidget.cpp#L552)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Now I wonder, couldn't it be simpler to use integer division:
```
const int maxPreviewWidth{desktopSize.width() / 2};
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734)*

**Comment by Talkless** [comment]
Just built, looks good.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734#-:-KwzD08Ht37WMcbbixq5:b-t868m6)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734#-:-KwzD6IJKIuqu6DJIKDD:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4734#-:-Kx2wVnM6vtczXZZlXdw:b-jbsf8z)*

**Pull request merged**
