### PR TITLE
fix: use `qAbs()` instead of `abs()` for better platform compatibility

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3623)

### CODE REVIEW

**Comment by antis81** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/tool/screengrabberchooserrectitem.cpp, line 217 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3623#-KP8w_rKSOMxUPTY1a1_:-KP8w_rLNBR0cfWP7BAY:b-1msjmq) ([raw file](https://github.com/qtox/qtox/blob/254f2b4b3e17c72cec112b65d61f3d67ed9f55a1/src/widget/tool/screengrabberchooserrectitem.cpp#L217)):_

> ``` cpp
>     QPointF delta = event->scenePos() - event->lastScenePos();
>     delta.rx() *= qreal(qAbs(x));
>     delta.ry() *= qreal(qAbs(y));
> ```

Can you remove that c cast here and one line above, please? Like this:

``` c++
delta.rx() *= qAbs(x);
delta.ry() *= qAbs(y);
```

This works, because a `qreal` is the "greater type" and can be safely multiplied by an `int`. Other than that, C casts shouldn't be used at all. So, if you spot one, feel free to change it to `static_cast<TYPE>(VARIABLE)`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3623)_

**Comment by zetok** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/tool/screengrabberchooserrectitem.cpp, line 217 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3623#-KP8w_rKSOMxUPTY1a1_:-KP9-rFci0dRG97lf69K:bo3vl6y) ([raw file](https://github.com/qtox/qtox/blob/254f2b4b3e17c72cec112b65d61f3d67ed9f55a1/src/widget/tool/screengrabberchooserrectitem.cpp#L217)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Can you remove that c cast here and one line above, please? Like this:
> 
> ``` c++
> delta.rx() *= qAbs(x);
> delta.ry() *= qAbs(y);
> ```
> 
> This works, because a `qreal` is the "greater type" and can be safely multiplied by an `int`. Other than that, C casts shouldn't be used at all. So, if you spot one, feel free to change it to `static_cast<TYPE>(VARIABLE)`.
> </details>
> Thanks, done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3623)_

**Comment by antis81** [comment]
@tux3 Are you ok with closing #3624 in favour to this one? I think we get a better cross-platform (and overall) experience with this. Other than that I'm completely with you, that it is a personal preference in this case. I like the QtGlobal functions, because they provide efficient code with less of a hastle (in most cases -> e.g. `qBound`). And it is just as likely as with STL, that those functions ever change. Though by the move to Qt5, some functions got marked deprecated, because STL now provides an equivalent. :)

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3623#-:-KP9uvAIhXowwB2FtsVn:bnfp4nl)_

**Comment by initramfs** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

_[src/widget/tool/screengrabberchooserrectitem.cpp, line 22 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3623#-KPE55JChvKWlcly-r9C:-KPE55JD1OoDfHuzHQgo:b24al89) ([raw file](https://github.com/qtox/qtox/blob/c7371b27534ca43c7957a5541ef450c6aa7a432d/src/widget/tool/screengrabberchooserrectitem.cpp#L22)):_

> ``` cpp
> #include "screengrabberchooserrectitem.h"
> 
> #include <cstdlib>
> ```

If `std::abs()` is changed to `qAbs()` this header include is no longer used.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3623)_

**Comment by zetok** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/widget/tool/screengrabberchooserrectitem.cpp, line 22 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3623#-KPE55JChvKWlcly-r9C:-KPEBv1CSHcxNddiLpxv:bss4a2b) ([raw file](https://github.com/qtox/qtox/blob/c7371b27534ca43c7957a5541ef450c6aa7a432d/src/widget/tool/screengrabberchooserrectitem.cpp#L22)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> If `std::abs()` is changed to `qAbs()` this header include is no longer used.
> </details>
> Removed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3623)_

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3623#-:-KPEQQngiC7XEq-JWSLu:bnfp4nl)_

**Comment by tux3** [comment]
LGTM, I'll close my PR if people prefer the Qt helpers. I think both are roughly equal in this case, so either way is fine by me :)

@antis81 
I think that the cross-platform experience will be the same either way, but maybe it's easier to use the Qt helpers since they are automatically included in pretty much every file that uses Qt.

**Pull request merged**
