### PR TITLE
Refactor/core1

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5408)

### CODE REVIEW

**Comment by sudden6** [comment]
Spinoff of  #5240 @sphaerophoria

I think this should be ok

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5408)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.cpp, line 144 at r1](https://reviewable.io/reviews/qtox/qtox/5408#-LPdPdavB_9x99jb8djH:-LPdPdavB_9x99jb8djI:b-iaylpb) ([raw file](https://github.com/qtox/qtox/blob/916fe78ccc6718529fdbfe983f5f5225ec44812d/src/core/coreav.cpp#L144)):*
> ```cpp
>     assert(toxav != nullptr);
> 
>     return CoreAVPtr(new CoreAV(*toxav));
> ```

After thinking about it I think I've changed my mind on this. It seems like a violation of ownership rules for someone to take in a reference and then assign it to a unique_ptr. I'd prefer that CoreAV takes in a unique_ptr by value or by rvalue reference and assert in the constructor that it's non-null

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5408)* status: 0 of 1 LGTMs obtained

___
*[src/core/coreav.cpp, line 144 at r1](https://reviewable.io/reviews/qtox/qtox/5408#-LPdPdavB_9x99jb8djH:-LPdpTNFDUzvLxhcnjCa:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/916fe78ccc6718529fdbfe983f5f5225ec44812d/src/core/coreav.cpp#L144)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

After thinking about it I think I've changed my mind on this. It seems like a violation of ownership rules for someone to take in a reference and then assign it to a unique_ptr. I'd prefer that CoreAV takes in a unique_ptr by value or by rvalue reference and assert in the constructor that it's non-null
</blockquote></details>

Done.

**Comment by sphaerophoria** [comment]
@sudden6 did you mean to slip this pre-2.0 toxcore removal in?

**Comment by sudden6** [comment]
@sphaerophoria just based this PR on the other one so I don't need to wait for CI once you lgtm it.

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> Reviewed 1 of 6 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5408#-:-LPqfSvO0hbE2vhMIWGB:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
