### PR TITLE
chore(build): bump Qt version to 5.9.3 for Windows

### LINKED ISSUE #4821: Update Qt version for windows builds
According to https://www.phoronix.com/scan.php?page=news_item&px=Qt-5.9.3-Released a new update to Qt is available and we should update the build scripts for Travis.

cc @nurupo for Jenkins.

### PR DESCRIPTION
**Pull request by nurupo**
~~Haven't tested it yet, will let Travis-CI run it and will build and test qTox the binaries locally later.~~

Tested it.

Fixes #4821.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4823)

### CODE REVIEW

**Comment by nurupo** [comment]
Mirrors still don't have Qt 5.9.3, huh. It looks like downloading directly from qt.io redirects to an appropriate mirror, so I'm going to edit the script to always download off qt.io rather than from one particular mirror.

**Comment by nurupo** [comment]
So, it turns out that Qt's own master mirror is dead slow (overloaded perhaps?) and it took over 50 minutes for Travis just to download a few % of the Qt's source code... Let's try again, the source code was mirrored on a few servers since, perhaps qt.io will redirect us to a fast mirror. If now, I might have to undo my last commit.

**Comment by nurupo** [comment]
Tested qTox binaries, seem to work fine. Also updated Jenkins nightlies to Qt 5.9.3.

**Comment by nurupo** [comment]
@sudden6 should be good to go.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4823#-:-KzgmdVmXs0OYd9Q5ZsN:b-jbsf8z)*

**Pull request merged**
