### PR TITLE
remove jenkins deploy step, bump version to v1.17.1

### PR DESCRIPTION
**Pull request by anthonybilinski**
jenkins is no longer used for release builds, and it's causing travis to fail
to deploy

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

This is to fix the issue that our v1.17.0 release tag was causing travis to fail with:
```
Switched to a new branch 'for-jenkins-release'
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/qTox/qTox.git/'
Script failed with status 128
failed to deploy
```
as seen in https://travis-ci.org/github/qTox/qTox/jobs/677058729#L10194.

I'm not sure why we're getting authentication failed, AFAIK the travis token hasn't changed, but since jenkins release builds was removed since last release, it probably doesn't matter.

This will require a v1.17.1 tag to avoid stripping the v1.17.0 tag that was already pushed. @sudden6 I'm not sure how we should clarify this to users during release to avoid confusion over missing v1.17.0 binaries.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6104)

### CODE REVIEW

**Comment by sudden6** [comment]
can you also pull in #6103 ? it's an update for our flatpack builds.

I think we should write in the release text of v1.17.0 something along the lines of `Due to a build error no binaries for this release, see v1.17.1`.

**Comment by sudden6** [comment]
BTW, I'M also concerned about this error: https://travis-ci.org/github/qTox/qTox/jobs/677058728#L212 is that fixed with this change too?

**Comment by anthonybilinski** [comment]
Will update changelog and cherry-pick flatpak change.

RE: other error in logs, it looks like that might come from TRAVIS_COMMIT_RANGE being empty? we pass that down through here:
```
# Verify commit messages
bash ./verify-commit-messages.sh "$TRAVIS_COMMIT_RANGE"
```
to
```
git log --format=format:'%s' "$ARG" \
```
directly. I did change the second part of that, `verify-commit-message.sh` in 40989e54d88fab705c0afb131b9e5826744ee621, but don't see how that could be related. We used the script with our v1.16.3 tag build here https://travis-ci.org/github/qTox/qTox/jobs/406444576#L478 and it had no problems. I wonder if "TRAVIS_COMMIT_RANGE" has changed behaviour for tags since then :thinking:

**Comment by nurupo** [comment]
@anthonybilinski to reply to your IRC message - qtox no longer uses jenkins, so all the scripts and references to jenkins can be removed. It also [looks like](https://github.com/qTox/qTox/commit/412f14558150e4da76acb3d639f5a23dca58b33b#diff-772839f7e87e4ac33eb4bed22ec2f68f) the script is already gone in the master branch.

**Comment by sudden6** [comment]
@anthonybilinski I added the flatpak update and refreshed the changelog

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6104#-:-M5XUX065Dcn8KIGkgff:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
I pushed a test tag and it build on travis. Again the verify commit format step errored, this time with unknown revisions rather than empty revisions: https://travis-ci.org/github/qTox/qTox/jobs/678482472#L215

The hashes are tags, rather than commits like our script expects:
```
$ git describe 4bf579e99b47
travis_test
$ git describe 74d4a81ef188
v1.17.0-2-ga306e23f
```
so we should probably add special tag handling, or just skip the check entirely on tags.

It didn't fail the job, so we can defer the fix until after release. I'll go ahead and delete the test tag, test branch, and merge this PR now.

**Review by anthonybilinski — COMMENTED** [review]
RE: commit message checking having a git error, the job still exits 0.. maybe if it's not blocking the build, maybe we should defer investigation until after release since it has no chance to effec

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6104#-:-M5YGtrI3vwCGeNylwB5:b-fuu6b0)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[CHANGELOG.md, line 21 at r5](https://reviewable.io/reviews/qtox/qtox/6104#-M5_yw8N9o6WkIm_1jlJ:-M5_yw8N9o6WkIm_1jlK:b-35diep) ([raw file](https://github.com/qtox/qtox/blob/c549479c0d3dfdc3c9c3bed4d057cf8173142eb8/CHANGELOG.md#L21)):*
> ```Markdown
> much increased stability of audio and video calls as well as audio group calls.
> 
> For v1.17.0 binaries, see v1.17.1.
> ```

I added a small note and the version numbers to changelog.

**Comment by nurupo** [comment]
FYI Windows builds use OpenSSL 1.1.1d, meanwhile OpenSSL protect has released 1.1.1e, 1.1.1f and 1.1.1g.

**Comment by sudden6** [comment]
@nurupo I updated to 1.1.1.f before the release https://github.com/qTox/qTox/blob/v1.17.0/windows/cross-compile/build.sh#L232

But you're right, g was released this week.

**Comment by nurupo** [comment]
You can cherry-pick https://github.com/nurupo/qTox/commit/89b6e4334c299ec0ad6e51dc344521ed74871524 if you think it needs to be updated before a release.

**Comment by nurupo** [comment]
Wait a second, how come OpenSSL and Qt versions are bumped in v1.17.0 branch but not in master? I have [a work-in-progress PR based on master](https://github.com/nurupo/qTox/commits/update-windows-crosscompile) that bumps OpenSSL to v1.1.1g and Qt to 5.12.8, yet you have already bumped Qt to that in the v1.17.0 branch. For the future reference, which branch should I base PRs on?

**Comment by nurupo** [comment]
Btw, don't wait on my PR, do what you need to make the release.

**Comment by sudden6** [comment]
I bumped the versions on v1.17-dev for the release, but didn't get around to merge the changes back to master.

**Comment by anthonybilinski** [comment]
> For the future reference, which branch should I base PRs on?

Sorry about the confusion and duplicated work. The changes from the `v1.17-dev` branch are merged into `master` periodically, but haven't bee in a while. There's a PR now that will update master with all changes up to v1.17.0: https://github.com/qTox/qTox/pull/6105. In an attempt to stabilize for release, we were targetting bug fixes and dependency updates to `v1.17-dev` which merges into `master`, and then features and refactors directly to `master`. The plan is to do the same for releases going forward so that our attempts to release don't drag on for ages again with regressions getting merged.

P.S. @sudden6 [*I*](https://github.com/qTox/qTox/pull/6071) updated openssl to 1.1.1f :P

**Comment by nurupo** [comment]
Yep, that makes sense.

**Pull request merged**
