### PR TITLE
Update screenshot in README

### PR DESCRIPTION
**Pull request by Doom032**
I think it's more appropriate to have a screenshot without the ex-developer who is featured in the current one. He doesn't exactly bring the best of thoughts.

### CODE REVIEW

**Comment by ghost** [comment]
Doubleplusgood.

But... Windows? It harms the readme's credibility. And the chat content is not really appealing.

**Comment by Doom032** [comment]
That screenshot was available. If you have a better one, it can be used. I'd make one, but I'm not in the position to make a beter one. I don't think Windows is a problem, but the chat content is a bit weird yes.

**Comment by zetok** [comment]
> But... Windows? It harms the readme's credibility.

Dunno about that. I was told that my original screenshot didn't look good enough, so I have adjusted it to the demands, one of them being using windows borders.
Original:
20150630 qtox screenshot for website - initial screenshot

Window borders were generously donated by astonex.

> And the chat content is not really appealing.

Yeah, there's only so much that markov bot  can do.

If someone wants, I can upload somewhere files used for making it, so that they could edit image without problems, and add different chat content.

**Comment by ghost** [comment]
RE Windows: for me at least it inspires the same mistrust as active projects at Sourceforge.

> upload somewhere files used for making it

Sure.

**Comment by zetok** [comment]
https://gist.github.com/zetok/6af729e201a1fae5145a here you go.

Edit: I've used Krita, it might be needed to use .kra files..?

**Comment by sudden6** [comment]
why not just remove the borders completely?

**Comment by zetok** [comment]
> why not just remove the borders completely?

To my understanding (as I was told) borders make it feel "real" – without them screenshot would look like something that was made up in krita/photoshop.. :|

# 

In any case – is anyone working on a better screenshot? Is anyone going to improve this one?
Is this good for merge?

**Comment by ProMcTagonist** [comment]
if this is only getting changed because of a user in it, just gimp them out of the original

**Comment by zetok** [comment]
> if this is only getting changed because of a user in it, just gimp them out of the original

Not only, new screenshot shows new features

**Comment by ProMcTagonist** [comment]
@zetok https://www.zerobin.net/?fa0524c456c5b949#vZSvDVt14BDjA9ugg43VXFtldBe40FfoO5eWBoCtsNU=

**Comment by ghost** [comment]
What do you think of a gif instead of a static screenshot? Is more eye-catching and one can demonstrate file sending, calls, markdown, etc. I can do it, I'd just need the witty chat text...

**Comment by zetok** [comment]
@kehugter 
qtox_screenshot_2016-03-23 18-08-19 339
?

**Comment by ProMcTagonist** [comment]
qtox mockup with zetok

gonna put this in window borders unless we want to gif

**Comment by ghost** [comment]
Merge this if you want, I'll do the gif and PR when ready.

**Comment by Doom032** [comment]
@ProMcTagonist Looks good. Maybe put in a more standard window border style. Non-technical people might think that top bar is part of qTox and think it's weird.

**Comment by ProMcTagonist** [comment]
@Doom032 

qtox mockup with zetok

**Comment by Doom032** [comment]
That one seems good. What do I do now? Close this PR and let @ProMcTagonist make another PR with that picture?

**Comment by sudden6** [comment]
@ProMcTagonist what @Doom032 said would be the way to go. Care to open a PR?

**Pull request closed without merging**
