### PR TITLE
fix(ipc): handle ipc failure gracefully

### PR DESCRIPTION
**Pull request by anthonybilinski**
Allows running qTox inside jails that block IPC.

This is a rework of https://github.com/qTox/qTox/pull/5742.

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5808)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
@yurivict could you try testing this in your FreeBSD jail that originally caused the problem?

**Comment by yurivict** [comment]
IMO this patch needs to be added on top of the other one. The original patch deterministically determines the reason of failure as being in jail, and this patch guesses that this might be the case. There can be many possible reasons of this failure. I suggest that you merge both PRs.

**Comment by anthonybilinski** [comment]
I fully agree that your original implementation determined if a jail was the cause of failure, and that this one doesn't. The benefits of determining this seem very small to me, since even if we fail to init IPC for some other reason, continuing to run without IPC enabled seems best. I'd happily remove "maybe we're in a jail?" from the warning message to not pretend like this determines the cause of the failure.

We don't currently run CI for FreeBSD, just Windows, OSX, and Ubuntu, and we currently have no FreeBSD specific code in our entire code base, plus nothing as low level as reading kernel info. I feel like introducing new platform specific code not covered by CI that queries kernel info is a fairly large maintenance cost, and isn't worth the small benefit of a more descriptive warning message.

**Comment by yurivict** [comment]
Ok, merge it then.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5808#-:-LnRDJqQAq_TDzguLVap:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
Looks like travis CI got stuck, and didn't even receive the request on their side. I'll try force pushing a newline addition and removal to see if that re-triggers it.

**Comment by anthonybilinski** [comment]
Nope, I just forgot to enable travis on dev branches, and earlier today enabled CI checks on dev branches, meaning this PR is now blocked on https://github.com/qTox/qTox/pull/5810.

**Pull request merged**
