### PR TITLE
chore(build): make cmake update version

### PR DESCRIPTION
**Pull request by zetok**
Depends on #4166 to work.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4167)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4167#-:-Kci9NPNdi6YbkppPIJe:b-jbsf8z)*

**Comment by yurivict** [comment]
tools/update-versions.sh appears to be for only OSX and Windows. Why do you call it unconditionally in cmake then?

**Comment by zetok** [comment]
>tools/update-versions.sh appears to be for only OSX and Windows.

It can be used on any system that has GNU sed.

>Why do you call it unconditionally in cmake then?

To update the version.

**Comment by yurivict** [comment]
Could you add cmake variable like NO_VERSION_UPDATE? Because on some systems (BSDs) network connections aren't allowed during build.

**Comment by zetok** [comment]
>Could you add cmake variable like NO_VERSION_UPDATE? Because on some systems (BSDs) network connections aren't allowed during build.

Why would network connection be needed in the first place?

**Comment by yurivict** [comment]
Ok, maybe network connection isn't needed, but git shouldn't be required during build. On FreeBSD for example it isn't installed from the git repository.

```
# tools/update-versions.sh
fatal: Not a git repository (or any parent up to mount point /usr/ports)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
./update-plist-version.sh: line 41: defaults: command not found
```

You shouldn't assume there is a git repository there.

**Comment by yurivict** [comment]
So the problems are 1. this patch adds the unconditional dependency on git executable 2. it assumes the build is done in a git repository directory 3. it functionally duplicates the already existing GIT_DESCRIBE variable that can currently be supplied by the caller.

**Comment by zetok** [comment]
>You shouldn't assume there is a git repository there.

I don't. You're running the old script from master before #4166 was merged. This PR literally depends on #4166 to work.

**Comment by yurivict** [comment]
Now it just fails:
```
# ./tools/update-versions.sh
Not a version: 
```

**Comment by zetok** [comment]
Yep.

**Pull request merged**
