### PR TITLE
remove *.qm files

### PR DESCRIPTION
**Pull request by burunduk**
Propose to remove *.qm files from repository to simplify the translation process

### CODE REVIEW

**Comment by zetok** [comment]
@agilob but .ts aren't removed

**Comment by agilob** [comment]
Commenting from phone :<
Sorry, my bad.

**Comment by dubslow** [comment]
I think I have to ask that this PR be reverted.

My LMDE system is essentially Debian testing snapshotted from several months ago, and the only way I have Qt 5.2+ here is by, a few months ago, adding the jessie archives to my apt sources, installing Qt 5.3, and then removing said line. Unfortunately, when I try the same trick with qttools5-dev-tools, it wants to remove several packages that I don't want to (I believe it would break my system).

I guess an alternative is that I could poke around qtox.pro and make a patch that would disable that step of compilation, and get the old .qm files from somewhere to make it happy. It would make my dev process a bit harder though :P

**Comment by tux3** [comment]
@dubslow Wouldn't qt4-linguist-tools work ?

The .ts and .qm format are probably compatible.

I know that this PR caused quite a lot of trouble, but it does make much more sense to only keep the source in the repo, and build binary blobs at compile time...

**Comment by dubslow** [comment]
Hmm, didn't know that was possible, and apparently I already have that installed.

So based on the error message qmake/sh spat, I ran `sudo ln -s /usr/bin/lrelease /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease` and now am running qmake, it's been running for 30 seconds and counting, with no output...

Edit: I interrupted qmake, got the same error:

```
^CRCC: Error in 'res.qrc': Cannot find file 'translations/fr.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/ru.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/de.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/it.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pl.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/fi.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/mannol.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/uk.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pirate.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/bg.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/sv.qm'
```

Meanwhile I also noticed that I _did_ have a makefile, and so tried running that, which meant I also had to `sudo ln -s /usr/bin/lupdate /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate`. `qmake` still seems to run forever, and interrupting it produces the same errors again, but after interrupting I still at least have a Makefile. On the other hand, `make` also seems to run forever, and interrupting gives me

```
make
/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate qtox.pro
^Cmake: *** [translations/bg.ts] Interrupt
```

**Comment by tux3** [comment]
Try running lupdate and lrelease manually, so you can what's going on ?

**Comment by dubslow** [comment]
Bunch of edits same time, I'll try that now.

Edit: runs for 60+ seconds without stopping, so I interrupted, no output

```
lupdate qtox.pro
^C
```

**Comment by tux3** [comment]
Wait wait wait. Where did you get /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate if you can't install qttools5-dev-tools ?

If you already have the tools installed somehow, then "qtchooser -run-tool=lupdate" and "qtchooser -run-tool=lrelease" are supposed to resolve the correct version

**Comment by dubslow** [comment]
No, I didn't have that, and running qmake gives me the error that it couldn't find it.

So I symlinked it as above.

An older attempt at make before the symlinks:

```
make
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile qtox.pro
sh: 1: /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease: not found
RCC: Error in 'res.qrc': Cannot find file 'translations/fr.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/ru.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/de.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/it.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pl.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/fi.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/mannol.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/uk.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/pirate.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/bg.qm'
RCC: Error in 'res.qrc': Cannot find file 'translations/sv.qm'
/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate qtox.pro
make: /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate: Command not found
make: *** [translations/bg.ts] Error 127
```

**Comment by dubslow** [comment]
Oh, crap.

```
qtchooser -run-tool=lupdate
qtchooser: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate' since it links to qtchooser itself. Check your installation.
bill@Gravemind⌚1705 ~/qtox ∰∂ ls -l `which lupdate`
lrwxrwxrwx 1 root root 9 Jun 20  2013 /usr/bin/lupdate -> qtchooser
```

I guess that explains that.

**Comment by tux3** [comment]
Unlink that and run qtchooser again ?

**Comment by dubslow** [comment]
Yeah lol. Instead I've now done this.

```
sudo ln -s /usr/bin/lupdate-qt4 /usr/lib/x86_64-linux-gnu/qt5/bin/lupdate
sudo ln -s /usr/bin/lrelease-qt4 /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease
```

`qmake` apparently works now, and `make` gives these warnings before continuing to compilation:
https://gist.github.com/dubslow/c4f717f838a00c51387e
They look like normal things to me, that's correct?
Edit: Yep, that's all normal, all is well now, thanks

**Comment by tux3** [comment]
Yep, all is well.

**Comment by dubslow** [comment]
Also compilation modifies the .ts files, meaning I have to reset/stash just to switch branches

**Comment by dubslow** [comment]
Actually it's a bit more serious than that, since it's hard to `git add` everything but the .ts files...

Edit: Not that hard, but still a pain in the butt to even have to think about it.

**Pull request merged**
