### PR TITLE
fix Windows alert by removing focus window setting

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5340)

### CODE REVIEW

**Comment by sudden6** [comment]
AFAICT this does not remove the options from the settings window, can you hide the checkbox on windows?

**Comment by anthonybilinski** [comment]
Agreed, removing it is better than just disabling it. I've updated to remove it altogether across all OSes. I think this is what you meant by

>what do you think about disabling and removing the options from settings in the next release

on the issue, or do you mean remove for only Windows in 1.17.0 then the rest in 1.17.1?

**Comment by sudden6** [comment]
@anthonybilinski no, you understood me correctly.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5340#-:-LMO8gu3-cw4Iw0mP5oV:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
