### PR TITLE
[Refactor] Add IFriendSettings

### PR DESCRIPTION
**Pull request by Diadlo**
Based on #4623

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4624)

### CODE REVIEW

**Comment by noavarice** [comment]
Reviewed 9 of 9 files at r1, 5 of 5 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 5 of 5 files at r6, 4 of 4 files at r7.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/about/aboutfriend.cpp, line 8 at r7](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfFRC_4yo8R1Xxfzv0:-KtfFRC_4yo8R1Xxfzv1:b680ite) ([raw file](https://github.com/qtox/qtox/blob/71727785c597a9d35ac9fa1c612a561531ddd722/src/model/about/aboutfriend.cpp#L8)):*
> ```cpp
> #include "src/persistence/ifriendsettings.h"
> 
> AboutFriend::AboutFriend(const Friend* f, IFriendSettings* settings)
> ```

`IFriendSettings* const`

---

*[src/model/about/aboutfriend.cpp, line 67 at r7](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfFYOer-amtFOLPom1:-KtfFYOer-amtFOLPom2:b-vw0mnl) ([raw file](https://github.com/qtox/qtox/blob/71727785c597a9d35ac9fa1c612a561531ddd722/src/model/about/aboutfriend.cpp#L67)):*
> ```cpp
> {
>     const ToxPk pk = f->getPublicKey();
>     const int value = (int)settings->getAutoAcceptCall(pk);
> ```

I know that point for this PR is to replace explicit `Settings` methods usages, but we must avoid using C-like casts and this will not be a huge change. I really think that you can change it here without filling PR with changes that does not relate to it

---

*[src/model/about/aboutfriend.h, line 16 at r7](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfGLe5TZSz36MOOJio:-KtfGLe5TZSz36MOOJip:b-x0hzd7) ([raw file](https://github.com/qtox/qtox/blob/71727785c597a9d35ac9fa1c612a561531ddd722/src/model/about/aboutfriend.h#L16)):*
> ```objc
> 
> public:
>     explicit AboutFriend(const Friend* f, IFriendSettings* settings);
> ```

No need for `explicit` keyword because there are more than one parameter

---

*[src/persistence/ifriendsettings.h, line 13 at r6](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfEXmFxEZcnzfY5uzh:-KtfEXmFxEZcnzfY5uzi:b-qt3yhz) ([raw file](https://github.com/qtox/qtox/blob/a5710b3a4ac8fe1ef51acf565d223f28611713a7/src/persistence/ifriendsettings.h#L13)):*
> ```objc
>     Q_OBJECT
> public:
>     enum class AutoAcceptCall
> ```

Duplicating `IAboutFriend::AutoAcceptCall`?

---

*[src/persistence/ifriendsettings.h, line 22 at r6](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfEg0vuX1sIilqw2HP:-KtfEg0vuX1sIilqw2HQ:b-4cb86b) ([raw file](https://github.com/qtox/qtox/blob/a5710b3a4ac8fe1ef51acf565d223f28611713a7/src/persistence/ifriendsettings.h#L22)):*
> ```objc
>     Q_DECLARE_FLAGS(AutoAcceptCallFlags, AutoAcceptCall)
> 
>     virtual QString getContactNote(const ToxPk& id) const = 0;
> ```

`pk` name for formal parameter looks more appropriate. This relates also to all other methods

---

*[src/persistence/settings.cpp, line 2035 at r6](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfFB-gJ6n2NJQecKrZ:-KtfFB-gJ6n2NJQecKr_:b-k6rwho) ([raw file](https://github.com/qtox/qtox/blob/a5710b3a4ac8fe1ef51acf565d223f28611713a7/src/persistence/settings.cpp#L2035)):*
> ```cpp
> }
> 
> void Settings::saveFriendSettings(const ToxPk& id)
> ```

What is purpose of this method?

---

*[src/widget/about/aboutfriendform.cpp, line 47 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfCQVZ_htFDZOaeGCB:-KtfCQVZ_htFDZOaeGCC:b7d9qeu) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L47)):*
> ```cpp
> }
> 
> static QString getAutoAcceptDir(const QString& dir)
> ```

Add documentation

---

*[src/widget/about/aboutfriendform.cpp, line 50 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfCWCzY2qRh0hCXh3z:-KtfCWCzY2qRh0hCXh4-:b-mpp9ie) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L50)):*
> ```cpp
> {
>     //: popup title
>     const QString title = AboutFriendForm::tr("Choose an auto accept directory");
> ```

Make it `static`

---

*[src/widget/about/aboutfriendform.cpp, line 56 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfCbK28SxGGHrsnrpc:-KtfCbK28SxGGHrsnrpd:b-dk7mku) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L56)):*
> ```cpp
> void AboutFriendForm::onAutoAcceptDirClicked()
> {
>     const QString dir = [&]{
> ```

I think we should explicitly point which data is captured to closures. For example, neither `ui` nor `about` pointers should be passed by reference since they will not be changed. I mean that this should be changed to `[ui, about]` and not just to `[=]`/ Such notion make clearer what it uses and in which way

---

*[src/widget/about/aboutfriendform.cpp, line 58 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfDL1_aya0tv_CO5rk:-KtfDL1_aya0tv_CO5rl:b-ydu3lq) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L58)):*
> ```cpp
>     const QString dir = [&]{
>         if (!ui->autoacceptfile->isChecked()) {
>             return QString();
> ```

Use`{}` instead

---

*[src/widget/about/aboutfriendform.cpp, line 61 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfE4AwcrFj49fm5C43:-KtfE4AwcrFj49fm5C44:bg5ychp) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L61)):*
> ```cpp
>         }
> 
>         return getAutoAcceptDir(about->getAutoAcceptDir());
> ```

Looks weird. Is there a way to call `getAutoAcceptDir` without parameter?

---

*[src/widget/about/aboutfriendform.cpp, line 93 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfEJiAnVwDpDY5u4s1:-KtfEJiAnVwDpDY5u4s2:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L93)):*
> ```cpp
> void AboutFriendForm::onSelectDirClicked()
> {
>     const QString dir = getAutoAcceptDir(about->getAutoAcceptDir());
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4624)*

**Comment by Diadlo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/about/aboutfriend.cpp, line 8 at r7](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfFRC_4yo8R1Xxfzv0:-Kv-67RsACY8KDGlzHFg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/71727785c597a9d35ac9fa1c612a561531ddd722/src/model/about/aboutfriend.cpp#L8)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`IFriendSettings* const`
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.cpp, line 67 at r7](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfFYOer-amtFOLPom1:-Kv-1F_AjihoJKAlwZP1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/71727785c597a9d35ac9fa1c612a561531ddd722/src/model/about/aboutfriend.cpp#L67)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I know that point for this PR is to replace explicit `Settings` methods usages, but we must avoid using C-like casts and this will not be a huge change. I really think that you can change it here without filling PR with changes that does not relate to it
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.h, line 16 at r7](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfGLe5TZSz36MOOJio:-Kv-1QxuZrT7h4P6A8-U:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/71727785c597a9d35ac9fa1c612a561531ddd722/src/model/about/aboutfriend.h#L16)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

No need for `explicit` keyword because there are more than one parameter
</blockquote></details>

Done.

---

*[src/persistence/ifriendsettings.h, line 13 at r6](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfEXmFxEZcnzfY5uzh:-Kv-1Tcrl1p_CTj4mspD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a5710b3a4ac8fe1ef51acf565d223f28611713a7/src/persistence/ifriendsettings.h#L13)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Duplicating `IAboutFriend::AutoAcceptCall`?
</blockquote></details>

Done.

---

*[src/persistence/ifriendsettings.h, line 22 at r6](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfEg0vuX1sIilqw2HP:-Kv-1kTwUHPYn-xCd3zl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a5710b3a4ac8fe1ef51acf565d223f28611713a7/src/persistence/ifriendsettings.h#L22)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`pk` name for formal parameter looks more appropriate. This relates also to all other methods
</blockquote></details>

Done.

---

*[src/persistence/settings.cpp, line 2035 at r6](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfFB-gJ6n2NJQecKrZ:-Kv-1qGMdDQK2Uljdw8N:b-q95tmv) ([raw file](https://github.com/qtox/qtox/blob/a5710b3a4ac8fe1ef51acf565d223f28611713a7/src/persistence/settings.cpp#L2035)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

What is purpose of this method?
</blockquote></details>

To make possible to save settings having `IFriendSettings*`

---

*[src/widget/about/aboutfriendform.cpp, line 50 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfCWCzY2qRh0hCXh3z:-Kv-3Jk-j5CtP8DBHII6:b-pcmhb1) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L50)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Make it `static`
</blockquote></details>

AFAIK `static` doesn't change anything here

---

*[src/widget/about/aboutfriendform.cpp, line 56 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfCbK28SxGGHrsnrpc:-Kv-4Kw4Ycp3OZzutuRy:bhbx981) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L56)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I think we should explicitly point which data is captured to closures. For example, neither `ui` nor `about` pointers should be passed by reference since they will not be changed
</blockquote></details>

It's just syntax sugar for const initialization. Don't think, that it make sense

---

*[src/widget/about/aboutfriendform.cpp, line 58 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfDL1_aya0tv_CO5rk:-Kv-5BF-dUCIS6oth8xO:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L58)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Use`{}` instead
</blockquote></details>

Done.

---

*[src/widget/about/aboutfriendform.cpp, line 61 at r5](https://reviewable.io:443/reviews/qtox/qtox/4624#-KtfE4AwcrFj49fm5C43:-Kv-5MsFE0nvlV4iFumd:b-hfgncv) ([raw file](https://github.com/qtox/qtox/blob/f48a9dd716d3596511a827af8483b9b754cfa16f/src/widget/about/aboutfriendform.cpp#L61)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Looks weird. Is there a way to call `getAutoAcceptDir` without parameter?
</blockquote></details>

What weird? That function has the same name with method? If so, I can rename it.
Otherwise, I don't understand the problem. We suggest to user last autoaccept directory, when he want to select a new.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4624)*

**Comment by Diadlo** [comment]
@noavarice @sudden6?

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 9 files at r1, 3 of 12 files at r8, 3 of 8 files at r10, 1 of 4 files at r11.
Review status: 5 of 11 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4624#-:-Ky_x5XsABRcQI2Lk2Iv:b-jbsf8z)*

**Comment by Diadlo** [comment]
Rebased

**Pull request merged**
