### PR TITLE
fix(bootstrap): qrencode url

### PR DESCRIPTION
**Pull request by AliceGrey**
Updated qrencode url to https and added error checking if the cert gets in the way.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4463)

### CODE REVIEW

**Comment by AliceGrey** [comment]
@Diadlo PR for #4428

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463#-:-KmVVGlmA1beljXzb2aP:b-jbsf8z)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 42 at r1](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmXsIlYhBtSzvqIfXR2:-KmXsIlZ9AYSMI9YmJ19:b-z838h3) ([raw file](https://github.com/qtox/qtox/blob/c11c96eeee5fa339ebf1db15e3d8c07090ed20aa/windows/bootstrap.sh#L42)):*
> ```Shell
>     echo
>     echo "Would you like to continue without verifying the certificate?"
>     read -p "(yes/No): " input
> ```

Text should be `(yes/No)  y/N` or `y/N` (if it's clear enough), since otherwise user most likely would just type `yes`, which would result in `$input` being `yes`.  This would result in `if` conditional below to be false even when user typed `yes`.

If the script used bash, one could either match string against a regexp, or just limit matching to a single letter from the variable.  `sh` it used though, and I'm not sure what else could be done aside from using better text for `read`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 42 at r1](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmXsIlYhBtSzvqIfXR2:-KmYIQHm8ICrZhkitJIX:b-jliso9) ([raw file](https://github.com/qtox/qtox/blob/c11c96eeee5fa339ebf1db15e3d8c07090ed20aa/windows/bootstrap.sh#L42)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Text should be `(yes/No)  y/N` or `y/N` (if it's clear enough), since otherwise user most likely would just type `yes`, which would result in `$input` being `yes`.  This would result in `if` conditional below to be false even when user typed `yes`.

If the script used bash, one could either match string against a regexp, or just limit matching to a single letter from the variable.  `sh` it used though, and I'm not sure what else could be done aside from using better text for `read`.
</blockquote></details>

Done. Added regexp and changed prompt.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 42 at r1](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmXsIlYhBtSzvqIfXR2:-Kma38Nj-Y7ig5NNUBpz:bmaklb2) ([raw file](https://github.com/qtox/qtox/blob/c11c96eeee5fa339ebf1db15e3d8c07090ed20aa/windows/bootstrap.sh#L42)):*
<details><summary><i>Previously, AliceGrey (Alice) wrote…</i></summary><blockquote>

Done. Added regexp and changed prompt.
</blockquote></details>

With `sh` (dash implementation) that results in `sh: 2: Syntax error: "(" unexpected (expecting "then")`.

`[[ ]]` is a bash keyword, and POSIX `sh` that this script is supposed to use doesn't support it.

Since apparently POSIX shell supports [parameter expansion](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02), the way to do it:

```sh
read -p "(yes/No) y/N: " input
input=$(echo $input | tr "[:upper:]" "[:lower:]")
if [ "${input%es}" == y ]; then
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 42 at r1](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmXsIlYhBtSzvqIfXR2:-Kmcfks6-oz4qiKIrVM3:bfi333d) ([raw file](https://github.com/qtox/qtox/blob/c11c96eeee5fa339ebf1db15e3d8c07090ed20aa/windows/bootstrap.sh#L42)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

With `sh` (dash implementation) that results in `sh: 2: Syntax error: "(" unexpected (expecting "then")`.

`[[ ]]` is a bash keyword, and POSIX `sh` that this script is supposed to use doesn't support it.

Since apparently POSIX shell supports [parameter expansion](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02), the way to do it:

```sh
read -p "(yes/No) y/N: " input
input=$(echo $input | tr "[:upper:]" "[:lower:]")
if [ "${input%es}" == y ]; then
```

</blockquote></details>

Ah I see. I should've been testing using the POSIX shell. Thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 42 at r1](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmXsIlYhBtSzvqIfXR2:-KmchJcyMj7PAQMyEuKD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c11c96eeee5fa339ebf1db15e3d8c07090ed20aa/windows/bootstrap.sh#L42)):*
<details><summary><i>Previously, AliceGrey (Alice) wrote…</i></summary><blockquote>

Ah I see. I should've been testing using the POSIX shell. Thank you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 48 at r2](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmfA4k5hajU6k8uuosL:-KmfA4k6x8VCn9jY0fMg:b-2ldf37) ([raw file](https://github.com/qtox/qtox/blob/f20e14af15e8eb58a1688f6575ededdb743abcc6/windows/bootstrap.sh#L48)):*
> ```Shell
>     else
>         echo "Error: Could not download libqrencode."
>         exit -1
> ```

```sh
sh -c 'exit -1' ; echo $?
sh: 1: exit: Illegal number: -1
2
```

Using bash that "would" work, although in a different way – the exit status would be `255`.

Why not just `exit 1` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 48 at r2](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmfA4k5hajU6k8uuosL:-KmhQ1jHxzTZvwHTNSA9:be99pgs) ([raw file](https://github.com/qtox/qtox/blob/f20e14af15e8eb58a1688f6575ededdb743abcc6/windows/bootstrap.sh#L48)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

```sh
sh -c 'exit -1' ; echo $?
sh: 1: exit: Illegal number: -1
2
```

Using bash that "would" work, although in a different way – the exit status would be `255`.

Why not just `exit 1` ?
</blockquote></details>

Honestly that might have just been a typo on my part. Changing it to exit 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/bootstrap.sh, line 48 at r2](https://reviewable.io:443/reviews/qtox/qtox/4463#-KmfA4k5hajU6k8uuosL:-KmhQTWECUYGrCQuW0en:bpxkyl6) ([raw file](https://github.com/qtox/qtox/blob/f20e14af15e8eb58a1688f6575ededdb743abcc6/windows/bootstrap.sh#L48)):*
<details><summary><i>Previously, AliceGrey (Alice) wrote…</i></summary><blockquote>

Honestly that might have just been a typo on my part. Changing it to exit 1.
</blockquote></details>

Actually after looking back at the code,  on line 11 and line 13 `exit -1` is used as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463)*

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4463#-:-KmhjvYQ1E1EEqbPn53B:b-jbsf8z)*

**Comment by Diadlo** [comment]
@AliceGrey Please, add `Fix #<issue number>` at the commit body in future. See details [here](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#body)

**Pull request merged**
