### PR TITLE
Newsettings is done

### PR DESCRIPTION
**Pull request by dubslow**
1) Cam test doesn't work properly
~~2) the double free still~~ actually I just fixed it!
~~3)~~ 2) It's not very pretty, but it's not very ugly and at least in master it might piss off the people who _can_ pretty-fy it :)

### CODE REVIEW

**Comment by tux3** [comment]
Sorry, but I can't exactly merge that into master ..

Some people actually use qTox (!), and this PR isn't really an improvement for them. 
But it looks like it just needs a bit of polishing/adding content, the actual logic seems to work.

pic31

That said we can pull it into my local newsettings branch, and keep improving it from there on if you want.

**Comment by dubslow** [comment]
Sure, please merge to the branch, the more visible the better. Like I said, at least in master it would annoy enough people to get it fixed. I myself am not learned in the blacke arts of making Qt look pretty -- I call upon the great masters @krepa098 and @apprb to kindly assist me (and by assist I mean I have no idea where to start) :). The two main issues are the images in the top not displaying correctly, and the buttons' location/rendering. (Note that the only content it lacks is the cam preview, and even that is nearly complete. The current privacy thing is also empty.)

I'll see if  I can rustle up that ui guy to make better images for the buttons on bottom.

Edit: tux3 if you're willing I'd appreciate a second opinion on the cam preview issue, but if not I'm reasonably sure I can at least solve that myself.

**Comment by tux3** [comment]
> tux3 if you're willing I'd appreciate a second opinion on the cam preview issue, but if not I'm reasonably sure I can at least solve that myself.

I'd love to but the video preview is completely broken for me in qTox since 18 days ago .. (#285)
Because of that I haven't really followed what happened with the video lately, what's the issue you're having ?

Edit: Branch merged in newsettings

**Comment by dubslow** [comment]
Oh lol, I mostly copied the current code, and it segfaults when I add a widget to a layout... in AVForm.cpp, it's commented. Also note I've edited my previous post, see if you missed something else I added... :P

**Comment by tux3** [comment]
Okay, I'll take a look at that. (Just fixing the scrollbar regression thing first).

**Comment by dubslow** [comment]
Wait a minute, my second look just now spotted a number of issues... I'll do it myself.

**Comment by tux3** [comment]
Okay, then.

**Comment by dubslow** [comment]
Well, now it has functional parity with the current dialog. All that remains is pretty-fying it.

**Comment by krepa098** [comment]
Why don't we use the form-designer? There's actually no need for manual layouting here.

**Comment by dubslow** [comment]
I have no idea what the form-designer is or how to use it.

Like I said, my Qt knowledge is quite slim :/

**Comment by dubslow** [comment]
See newsettings_v2

**Pull request closed without merging**
