### PR TITLE
refactor(MacOSX): switch to Qt 5.13 compliant methods for OSX

### PR DESCRIPTION
**Pull request by Kribylet**
This commit aims to bring Mac OSX specific code into Qt 5.13 compliance.

This PR will be WIP until ready to utilize TravisCI as I am unable to test Mac OSX functionality directly (Apple licenses forbid running OSX VM on non-Apple hardware.)

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5745)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
By the way, you can check this locally for faster iteration time (up to you) by downloading Qt 5.13.0, and configuring qTox to build against that download directory, e.g. `cmake -DCMAKE_PREFIX_PATH=/home/abilinski/deps/Qt/5.13.0/gcc_64/ ..`

Make sure you remove the CMakeCache.txt file when changing Qt version, since its search paths won't be updated otherwise.

Also note that part of this work was done in https://github.com/qTox/qTox/pull/5552, though different choices were made in some cases.

> Reviewed 7 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5745#-:-LjhQHBT2ffFfDlH9O3P:b-jtfzic)* status: 0 of 1 LGTMs obtained

___
*[src/video/genericnetcamview.cpp, line 139 at r2](https://reviewable.io/reviews/qtox/qtox/5745#-LjhxOZG8pQNjsBzA3Xw:-LjhxOZI7ul8846tjLFI:b-cfa48h) ([raw file](https://github.com/qtox/qtox/blob/183a039146c376d78f1c57f23de748532bd72a13/src/video/genericnetcamview.cpp#L139)):*
> ```cpp
>     enterFullScreenButton->hide();
>     toggleMessagesButton->hide();
> #if (QT_VERSION >= QT_VERSION_CHECK(5, 13, 0))
> ```

Introduced in 5.10.0.
___
*[src/widget/tool/croppinglabel.cpp, line 178 at r1](https://reviewable.io/reviews/qtox/qtox/5745#-LjhPv1vEgNDotb41U12:-LjhPv1vEgNDotb41U13:b-2uuoqo) ([raw file](https://github.com/qtox/qtox/blob/9c182c0513a643fe8e3b8e3a67cba5ec9e2a3782/src/widget/tool/croppinglabel.cpp#L178)):*
> ```cpp
>     // Text width + padding. Without padding, we'll have elipses.
> #if (QT_VERSION >= QT_VERSION_CHECK(5, 13, 0))
>     setMaximumWidth(fontMetrics().horizontalAdvance(origText) + fontMetrics().horizontalAdvance("..."));
> ```

horizontalAdvance was added in 5.11.0 - https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance, it would be good to have the check on the exact version so that in the future when we bump minimum supported Qt version, it will be obvious when we can add the compatibility check. i.e. favour the new version instead of the old one for the period where they overlap.

Same with other QT_VERSION checks around
___
*[src/widget/tool/screenshotgrabber.cpp, line 206 at r2](https://reviewable.io/reviews/qtox/qtox/5745#-LjhvZrQ881MDe9o7eOk:-LjhvZrQ881MDe9o7eOl:b-cfa48h) ([raw file](https://github.com/qtox/qtox/blob/183a039146c376d78f1c57f23de748532bd72a13/src/widget/tool/screenshotgrabber.cpp#L206)):*
> ```cpp
> {
>     QRect recGL = QGuiApplication::primaryScreen()->virtualGeometry();
> #if (QT_VERSION >= QT_VERSION_CHECK(5, 13, 0))
> ```

Introduced in 5.10.0.

**Comment by Kribylet** [comment]
@anthonybilinski Thanks for the feedback, I've updated the version checks to adhere to the closest possible version. Other changes that didn't have version checks in place all appear to be entirely based on Qt 5.5 and earlier, which based on install.md is considered required currently. I have been glancing at #5552 a fair bit and it's been helpful, though I've tried to review the required changes on a case by case basis separately as well. My intent is that the code should behave exactly the same as much as possible to avoid introducing anything insidious :suspect: 

Some testing once Travis starts approving should hopefully weed out anything odd.

**Comment by Kribylet** [comment]
Tested:
File transfer from one user to another (5.13.0) (5.9.5)
Offline messages send order (5.13.0) (5.9.5)
Creating/Joining/Messaging in group chat (5.13.0) (5.9.5)
Calling/Answering voice call (5.13.0) (5.9.5)
Video call of desktop user to user, w/ changing desktop resolution (5.13.0) (5.9.5)
***Doesn't automatically update to match properly and causes some strange overlap behavior, but this isn't anything that isn't already in master
Video call of desktop user to user, entering fullscreen mode (5.13.0) (5.9.5)

Untested:
Windowmapper replacement functionality (Mac OSX specific code)
layouts.swapItemsAt functionality/equivalence (Mac OSX specific code)
setAsDockMenu change (Mac OSX specific code)
Adding/removing screen surface during desktop video call (No extra monitor available)

**Review by Kribylet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5745)* status: 0 of 1 LGTMs obtained

___
*[src/video/genericnetcamview.cpp, line 139 at r2](https://reviewable.io/reviews/qtox/qtox/5745#-LjhxOZG8pQNjsBzA3Xw:-Lk-WoY_8gM5iSSHRLah:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/183a039146c376d78f1c57f23de748532bd72a13/src/video/genericnetcamview.cpp#L139)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Introduced in 5.10.0.
</blockquote></details>

Done.
___
*[src/widget/tool/croppinglabel.cpp, line 178 at r1](https://reviewable.io/reviews/qtox/qtox/5745#-LjhPv1vEgNDotb41U12:-Lk-WqumBHAcnVNIYo3_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9c182c0513a643fe8e3b8e3a67cba5ec9e2a3782/src/widget/tool/croppinglabel.cpp#L178)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

horizontalAdvance was added in 5.11.0 - https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance, it would be good to have the check on the exact version so that in the future when we bump minimum supported Qt version, it will be obvious when we can add the compatibility check. i.e. favour the new version instead of the old one for the period where they overlap.

Same with other QT_VERSION checks around
</blockquote></details>

Done.
___
*[src/widget/tool/screenshotgrabber.cpp, line 206 at r2](https://reviewable.io/reviews/qtox/qtox/5745#-LjhvZrQ881MDe9o7eOk:-Lk-WrRa9emZ09NH0uXp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/183a039146c376d78f1c57f23de748532bd72a13/src/widget/tool/screenshotgrabber.cpp#L206)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Introduced in 5.10.0.
</blockquote></details>

Done.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: from my side @anthonybilinski please merge when you also give lgtm

> Reviewed 9 of 10 files at r1, 1 of 3 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5745#-:-Lk4j8fFA9DmVjzcCouV:bgyq1i3)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
Looks good so far - I'm going to try to get an OSX instance running this weekend and see if I can test this, if I don't get time I'll push that burden onto nightly users. Either way I'll merge this within the next couple days.

> Reviewed 1 of 3 files at r3, 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5745#-:-LkBCP-T03347o3SDEYF:b-ne31dt)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
