### PR TITLE
feat(video): Error message on call fail

### PR DESCRIPTION
**Pull request by tWido**
Solves #206 

notifies user if call ended unexpectedly

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4531)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4531)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4531#-:-KplESJxIBipPkRAVxVQ:b-jbsf8z)*

**Comment by Diadlo** [comment]
Please, add `Fix #206` in commit message

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4531#-:-KplGtb5_1HnznOtm4m_:b-jbsf8z)*

**Pull request merged**
