### PR TITLE
added missing dependency to libsqlcipher-dev in simple_make.sh

### PR DESCRIPTION
**Pull request by quatrox**

### CODE REVIEW

**Comment by sudden6** [comment]
Could you add `sqlcipher-devel` for openSUSE also?

**Comment by zetok** [comment]
> But, that fix will come in a separate commit, as I have to figure out the correct dependency first.

Well, fedora doesn't seem to package sqlcipher. That's why INSTALL.md has a section for compiling it.

**Comment by quatrox** [comment]
Please note that I do not have any computers running OpenSUSE at the moment, but a quick search on the Internet indicated that the package name was correct.

**Comment by sudden6** [comment]
I should have added that this comes from my openSUSE system.

**Pull request merged**
