### PR TITLE
chore: actually restrict length the first line of `Merge*` commits

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3617)

### CODE REVIEW

**Comment by initramfs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[verify-commit-messages.sh, line 34 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3617#-KOsFeLtjp2CFbKsOd58:-KOsFeLuormq3pkYBkob:b-uaqnt2) ([raw file](https://github.com/qtox/qtox/blob/21f28fda7f0de84d7a5572999d9700090f4204b5/verify-commit-messages.sh#L34)):_

> ``` Shell
> # Conform, /OR ELSE/.
> if git log --format=format:'%s' "$ARG" | \
>     grep -v -E '^((feat|fix|docs|style|refactor|perf|revert|test|chore)(\(.{,12}\))?:.{1,68})|(Merge .{1,70})$'
> ```

This check checks that any commit follows the given pattern, allowing one to create a false commit called "Merge xxx" and have it be accepted by this script.

Run two checks, the first check executes:

```
git log --no-merges --format=format:'%s' "$ARG"
```

against the `(feat|fix|docs|style|refactor|perf|revert|test|chore)(\(.{,12}\))?:.{1,68}` pattern.

And a second check with:

```
git log --merges --format=format:'%s' "$ARG"
```

against the `(Merge .{1,70}` pattern.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3617)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[verify-commit-messages.sh, line 34 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3617#-KOsFeLtjp2CFbKsOd58:-KOsPCK9ENJBBUo5KLKZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/21f28fda7f0de84d7a5572999d9700090f4204b5/verify-commit-messages.sh#L34)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> This check checks that any commit follows the given pattern, allowing one to create a false commit called "Merge xxx" and have it be accepted by this script.
> 
> Run two checks, the first check executes:
> 
> ```
> git log --no-merges --format=format:'%s' "$ARG"
> ```
> 
> against the `(feat|fix|docs|style|refactor|perf|revert|test|chore)(\(.{,12}\))?:.{1,68}` pattern.
> 
> And a second check with:
> 
> ```
> git log --merges --format=format:'%s' "$ARG"
> ```
> 
> against the `(Merge .{1,70}` pattern.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3617)_

**Comment by initramfs** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[verify-commit-messages.sh, line 51 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3617#-KOsUmmRnM1ok8mKMt21:-KOsUmmRnM1ok8mKMt22:bfj6uhv) ([raw file](https://github.com/qtox/qtox/blob/2ffbdd597b8b35e7c413f4b94a11ddbfe6e7a8b7/verify-commit-messages.sh#L51)):_

> ``` Shell
>     echo "https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format"
>     echo ""
>     echo "Pls fix."
> ```

"Please fix."? Sorry, it's bother me. :)

Apart from that :lgtm: 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3617)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[verify-commit-messages.sh, line 51 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3617#-KOsUmmRnM1ok8mKMt21:-KOy5hLEGwxDF6_jiJDj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/abc00c45277dcde4ddf4f6416beb3fe08f4966eb/verify-commit-messages.sh#L51)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> "Please fix."? Sorry, it's bother me. :)
> 
> Apart from that :lgtm: 
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3617)_

**Comment by initramfs** [comment]
Thnaks :P :lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3617#-:-KOy6K_yFDAzJX0VRXfO:bi50b06)_

**Comment by initramfs** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3617)_

**Pull request merged**
