### PR TITLE
feat(settings): add possibility to change the UDP port range

### PR DESCRIPTION
**Pull request by Neolex-Security**
this commit fix a part of the issue #3334

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3750)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/persistence/settings.cpp, line 2351 at r1](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSeoB8aIEn679fKj0iT:-KSeoB8aIEn679fKj0iU:b-nimxpk) ([raw file](https://github.com/qtox/qtox/blob/5394a89600ea40fe850ba088b1ea73e2474354b4/src/persistence/settings.cpp#L2351)):_

> ``` cpp
> {
>         QMutexLocker locker{&bigLock};
>         if(port>1023 && port<=65535)
> ```

Extra indent in `setStartUDPPort` method. And pleas add spaces around `<` and `>` and after `if` 
i.e. `if (1023 < port && port <= 65535)`

---

_[src/persistence/settings.cpp, line 2367 at r1](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSeob0Nr5xkRB-PuTKL:-KSeob0OuJX8lmx0YVc9:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/5394a89600ea40fe850ba088b1ea73e2474354b4/src/persistence/settings.cpp#L2367)):_

> ``` cpp
> {
>         QMutexLocker locker{&bigLock};
>         if(port>1023 && port<=65535)
> ```

Same as above

---

_[src/widget/form/settings/advancedform.cpp, line 172 at r1](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSepCMRSILFC6jli9NQ:-KSepCMSPloUF1IC3S97:b-n7olv0) ([raw file](https://github.com/qtox/qtox/blob/5394a89600ea40fe850ba088b1ea73e2474354b4/src/widget/form/settings/advancedform.cpp#L172)):_

> ``` cpp
>     if (bodyUI->spinEndUDPPort->value() < bodyUI->spinStartUDPPort->value())
>     {
>         bodyUI->spinEndUDPPort->setValue(bodyUI->spinStartUDPPort->value()+100);
> ```

Please, add spaces around `+`. 
IMO better will be save `bodyUI->spinStartUDPPort->value()` in variable. It will make the code easier to read. Maybe same to EndUDPPort

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Diadlo** [comment]
- Please, add tooltips to port fields (IIRC it's part of accessibility support)
- Maybe add more detailed description what this range does?

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750#-:-KSesT68W0Wcm8X_xGUz:bd9d2hk)_

**Comment by initramfs** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/persistence/settings.cpp, line 2351 at r1](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSeoB8aIEn679fKj0iT:-KSfbWpCQ67hLiYMiBzT:b-olv4da) ([raw file](https://github.com/qtox/qtox/blob/5394a89600ea40fe850ba088b1ea73e2474354b4/src/persistence/settings.cpp#L2351)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Extra indent in `setStartUDPPort` method. And pleas add spaces around `<` and `>` and after `if` 
> i.e. `if (1023 < port && port <= 65535)`
> </details>
> There is also no user feedback if they enter a invalid port number (port number too low), including the default of 0. Instead, the values are simply not saved and upon restarting qTox revert to their old values.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by zetok** [comment]
> feat(settings): add spaces,tooltips,and minimal value of port

Err, no, squash that commit.

**Comment by Neolex-Security** [comment]
Hmm ... why ? 
I'm sorry I make you lost your time ... It's all new for me :/

**Comment by zetok** [comment]
@HascoetKevin there's simply no reason to have multiple commits for 1 change. The change is `option to manually set port range`. Intermediate changes that occur due to review process don't need to introduce unnecessary commits.

Btw, when you have just a single commit that you want to modify, you can just `git commit -a --amend`. _Note that `-a` adds changes to all files, you can just give a path to a single modified file_.

**Comment by initramfs** [comment]
Reviewed 2 of 4 files at r2.
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/form/settings/advancedsettings.ui, line 76 at r2](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSievXRfA4JpBZWooOF:-KSievXSO4sptOJFP8QJ:b-mb7dqf) ([raw file](https://github.com/qtox/qtox/blob/0fbc4f7d369ab8d85e285707963726512bfdf9d9/src/widget/form/settings/advancedsettings.ui#L76)):_

> ``` XML
>            <widget class="QLabel" name="PortRangeLabel">
>             <property name="toolTip">
>              <string>set the UDP port range used by qTox </string>
> ```

Start with a capital letter and remove the space at the end of qTox:

```
<string>Set the UDP port range used by qTox</string>
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by zetok** [comment]
Review status: 4 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/widget/form/settings/advancedsettings.ui, line 79 at r2](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSkOgl3Roct1xo0vcBY:-KSkOgl3Roct1xo0vcBZ:b-gpgrci) ([raw file](https://github.com/qtox/qtox/blob/0fbc4f7d369ab8d85e285707963726512bfdf9d9/src/widget/form/settings/advancedsettings.ui#L79)):_

> ``` XML
>             </property>
>             <property name="text">
>              <string>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Port range ( start port - end port ) :&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</string>
> ```

Move HTML out of translatable text

https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#no-translatable-html-tags

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Neolex-Security** [comment]
up ! 
Do I still have to change something ?

**Comment by zetok** [comment]
Review status: 3 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/persistence/settings.cpp, line 2382 at r3](https://reviewable.io:443/reviews/qtox/qtox/3750#-KT3JBhYrz66CC19Zeey:-KT3JBhZ9ojYyWuKVroe:bki5guq) ([raw file](https://github.com/qtox/qtox/blob/9393c7e6934e3571806403144f04108b009b97e7/src/persistence/settings.cpp#L2382)):_

> ``` cpp
> {
>     QMutexLocker locker{&bigLock};
>     if(port > 1023 && port <= 65535)
> ```

A space is missing between parentheses and `if`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Diadlo** [comment]
Otherwise few mis-style LGTM

---

Reviewed 2 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[src/persistence/settings.cpp, line 2398 at r3](https://reviewable.io:443/reviews/qtox/qtox/3750#-KT3fkTr5Dk-EcX9lAZS:-KT3fkTssONZH7Gojz70:b-7cajzs) ([raw file](https://github.com/qtox/qtox/blob/9393c7e6934e3571806403144f04108b009b97e7/src/persistence/settings.cpp#L2398)):_

> ``` cpp
> {
>     QMutexLocker locker{&bigLock};
>     if(port > 1023 && port <= 65535)
> ```

Same as zetok write above

---

_[src/widget/form/settings/advancedform.cpp, line 173 at r3](https://reviewable.io:443/reviews/qtox/qtox/3750#-KT3d31juSMqnp5fXUym:-KT3d31kyimhzUhatBm4:b-i7x2da) ([raw file](https://github.com/qtox/qtox/blob/9393c7e6934e3571806403144f04108b009b97e7/src/widget/form/settings/advancedform.cpp#L173)):_

> ``` cpp
>     int endPort = bodyUI->spinEndUDPPort->value();
> 
>     if ( endPort < startPort )
> ```

Please remove extra spaces abfter open bracket and before closed :)
i.e. `if (endPort < startPort)`

---

_[src/widget/form/settings/advancedform.cpp, line 186 at r3](https://reviewable.io:443/reviews/qtox/qtox/3750#-KT3fV9mAsIf_FGuY1NN:-KT3fV9nG3OgiqzQjp5z:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/9393c7e6934e3571806403144f04108b009b97e7/src/widget/form/settings/advancedform.cpp#L186)):_

> ``` cpp
>     int endPort = bodyUI->spinEndUDPPort->value();
> 
>     if ( endPort < startPort )
> ```

Same as above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750#-:-KT3fgCzi1yLKG1PxlHA:b4mw236)_

**Comment by Neolex-Security** [comment]
Up ! 
I don't know if it's ok now or if there are more errors ?

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_[src/persistence/settings.cpp, line 2351 at r1](https://reviewable.io:443/reviews/qtox/qtox/3750#-KSeoB8aIEn679fKj0iT:-KTDnrd2wEtaZaV6TuGu:b-7rod7b) ([raw file](https://github.com/qtox/qtox/blob/5394a89600ea40fe850ba088b1ea73e2474354b4/src/persistence/settings.cpp#L2351)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> There is also no user feedback if they enter a invalid port number (port number too low), including the default of 0. Instead, the values are simply not saved and upon restarting qTox revert to their old values.
> </details>
> You forget this ^

---

_[src/persistence/settings.cpp, line 2382 at r3](https://reviewable.io:443/reviews/qtox/qtox/3750#-KT3JBhYrz66CC19Zeey:-KTDiUcY2RbDtBX-keeN:bropvoq) ([raw file](https://github.com/qtox/qtox/blob/9393c7e6934e3571806403144f04108b009b97e7/src/persistence/settings.cpp#L2382)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> A space is missing between parentheses and `if`.
> </details>
> And this ^

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Diadlo** [comment]
And you have 2 commits with same text. Sqash them or rewrite

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750#-:-KTDoDD5f0_GAtJoZcWh:bgze0wh)_

**Comment by Neolex-Security** [comment]
I don't understand ,the number can't be lower than 1024 so how alert the user if it's lower

**Comment by Neolex-Security** [comment]
I think that's ok now ... :)

**Comment by sudden6** [comment]
Review status: 2 of 6 files reviewed at latest revision, 12 unresolved discussions.

---

_[src/widget/form/settings/advancedform.cpp, line 175 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQiV9oTns7-ooHhLmp:-KTQiV9pZcey-AAqbfs_:bcrfbi6) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L175)):_

> ``` cpp
>     if (startPort < 1024)
>     {
>         GUI::showWarning(tr("wrong port"),tr("The start port have to be at least 1024"));
> ```

`The start port has to be 1024 or higher`

---

_[src/widget/form/settings/advancedform.cpp, line 181 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQirSeAAATXX1mrAjp:-KTQirSffsuER56kS-RH:bbubx3a) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L181)):_

> ``` cpp
>     if (endPort < startPort)
>     {
>         bodyUI->spinEndUDPPort->setValue(startPort + 100);
> ```

refactor this and the below line to:

```
endPort = startPort+100;
bodyUI->spinEndUDPPort->setValue(endPort);
```

This way the magic value is only in one place and can't be forgotten to change.

---

_[src/widget/form/settings/advancedform.cpp, line 195 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQjJDkfvzgKGgDycuF:-KTQjJDlbK3IzO5gZgUY:b-rs5i32) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L195)):_

> ``` cpp
>     if (endPort < startPort)
>     {
>         QMessageBox::warning(this, tr("Start port should be lower than end port", "popup title"),
> ```

`The start port should be lower than the end port`

---

_[src/widget/form/settings/advancedform.cpp, line 196 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQjPDlP7lEMN-mYh7c:-KTQjPDlP7lEMN-mYh7d:b-gbeeea) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L196)):_

> ``` cpp
>     {
>         QMessageBox::warning(this, tr("Start port should be lower than end port", "popup title"),
>                         tr("You should swap start and end port.\nThe end port have to be higher than the start port", "popup text"));
> ```

...`end port has to be higher`...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Diadlo** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

_[src/widget/form/settings/advancedform.cpp, line 175 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQiV9oTns7-ooHhLmp:-KTQkLbwJuukrwrpI-eK:bjhnzqr) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L175)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> `The start port has to be 1024 or higher`
> </details>
> Add space after comma

---

_[src/widget/form/settings/advancedform.cpp, line 182 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQySa9VZZ8vPOlH9jh:-KTQySaAWpaVKsGUjKAJ:b-p296sy) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L182)):_

> ``` cpp
>     {
>         bodyUI->spinEndUDPPort->setValue(startPort + 100);
>         endPort = startPort+100;
> ```

Please, add spaces around of `+`

---

_[src/widget/form/settings/advancedform.cpp, line 207 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQxvkDKALWKO8N4oAz:-KTQxvkDKALWKO8N4oB-:b-uahihq) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L207)):_

> ``` cpp
> {
>     int startPort = bodyUI->spinStartUDPPort->value();
>     bodyUI->spinEndUDPPort->setMinimum(startPort+1);
> ```

I think, better use int [valueChanged](https://doc.qt.io/Qt-5/qspinbox.html#valueChanged)
And add spaces around of `+`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

_[src/widget/form/settings/advancedform.cpp, line 207 at r5](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTQxvkDKALWKO8N4oAz:-KTTAbVCt4rYhEyjq1wf:b7nfb88) ([raw file](https://github.com/qtox/qtox/blob/a6c8cea5a40e32ef696006d7f9fe191bc12a7157/src/widget/form/settings/advancedform.cpp#L207)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> I think, better use int [valueChanged](https://doc.qt.io/Qt-5/qspinbox.html#valueChanged)
> And add spaces around of `+`
> </details>
> I mean
> 
> ```
> void AdvancedForm::on_spinStartUDPPort_valueChanged(int startPort)
> {
>     bodyUI->spinEndUDPPort->setMinimum(startPort + 1);
> }
> ```

---

_[src/widget/form/settings/advancedform.cpp, line 181 at r6](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTT93JWopF6_KoboasK:-KTT93JXOCbZtxP7tahi:b-yf4nb8) ([raw file](https://github.com/qtox/qtox/blob/3aa326e07eae3e805c2318be1bb177ee763bf5fb/src/widget/form/settings/advancedform.cpp#L181)):_

> ``` cpp
>     if (endPort < startPort)
>     {
>         endPort = startPort + 100;
> ```

If you whant, you can replace this line and `if` statement below on
`endPort = qMin(startPort + 100, 65535)`.
Also, please, create `MAX_PORT` and `MIN_PORT` constants

---

_[src/widget/form/settings/advancedform.h, line 56 at r6](https://reviewable.io:443/reviews/qtox/qtox/3750#-KTTB13qSvlXVp2uaMKi:-KTTB13rgEKm0WBQY19Q:bw27ghf) ([raw file](https://github.com/qtox/qtox/blob/3aa326e07eae3e805c2318be1bb177ee763bf5fb/src/widget/form/settings/advancedform.h#L56)):_

> ``` objc
>     void on_spinStartUDPPort_editingFinished();
>     void on_spinEndUDPPort_editingFinished();
>     int on_spinStartUDPPort_valueChanged(const QString &arg1);
> ```

`void on_spinStartUDPPort_valueChanged(int startPort);`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750)_

**Comment by Neolex-Security** [comment]
I think I still have to change something but I don't know what^^

**Comment by Diadlo** [comment]
Good work, comrade! :)
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750#-:-KTcVyxDTSSrrbTywwJh:bu5gegq)_

**Comment by Diadlo** [comment]
Loading of port carried only on connect/reconnect. Maybe add tooltip somewhere?

---

Review status: all files reviewed at latest revision, 15 unresolved discussions, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750#-:-KTcWLeodCZZum4JT11t:bw5bzqa)_

**Comment by zetok** [comment]
on 7ee49f32397c31f7f6275759e4073d20c5c6f223:

```
src/persistence/settings.cpp: In member function ‘void Settings::setStartUDPPort(quint16)’:
src/persistence/settings.cpp:2382:29: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     if (port > 1023 && port <= 65535)
                             ^
src/persistence/settings.cpp: In member function ‘void Settings::setEndUDPPort(quint16)’:
src/persistence/settings.cpp:2398:29: warning: comparison is always true due to limited range of data type [-Wtype-limits]
     if (port > 1023 && port <= 65535)
                             ^
```

↑ fix it

spectacle zb6011
- [x] port range by default is set to `0, 1024`, should be `33445, 33545`
- [x] since the option requires toxcore restart, move it under `Connection settings`
- [ ] it's not obvious what the option is for, entry in user manual should be added

**Comment by Diadlo** [comment]
I think better will be move port-range out from `horizontalGroupBox`

---

Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3750#-:-KTeFhmSiYliF4jC9PNm:byxq5vj)_

**Comment by zetok** [comment]
on cfad8a22849be2279d05e727fd45e33805294f72:
- [x] qTox closes its window & tray icon, but doesn't exit even though it claims that it will; situation where it has to exit shouldn't happen at all
  
  spectacle vr2978
  steps:
1. set port range to `33445, 33445`
2. click on `Reconnect`

**Comment by zetok** [comment]
on 389ef58d4d096f4d6d9cb7608e67ad64f7fc2230:
- [ ] qTox claims that it will exit but it just deletes the window & tray, while its process is still exists
  
  Steps to reproduce:
  1. Set port range to ports that are already used by something, e.g. `33445-33446` (used by other qTox instances)
  2. Click on `Reconnect`
  
  Log:
  
  ```
  [09:05:49.662 UTC] persistence/profile.cpp:290 : Debug: Loading tox save  "/home/zetok/.config/tox/d_b.tox"
  [09:05:49.662 UTC] core/core.cpp:133 : Warning: Core starting with IPv6 disabled. LAN discovery may not work properly.
  [09:05:49.662 UTC] core/core.cpp:193 : Critical: can't to bind the port
  [09:05:50.809 UTC] widget/systemtrayicon.cpp:99 : Debug: Deleting SystemTrayIcon
  ```
  
  spectacle vr2978
- [ ] even though there is a warning message, one can still seemingly have ports below `1024` set as range, setting is not being reset to correct value after pressing `Reconnect`. Reset setting is shown only after restarting qTox instance, which is not good enough, since user might be mislead into thinking that port is set to value below `1024` until they restart qTox instance.

**Comment by zetok** [comment]
@HascoetKevin any update on the status of the PR?

**Comment by Neolex-Security** [comment]
I'm kinda lost... I don't know how resolve this problem.
Sorry for the time , I'm really busy theses days

**Pull request closed without merging**
