### PR TITLE
feat(chatform): make magnet links clickable

### PR DESCRIPTION
**Pull request by tvladyslav**
- [X] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5500)

### CODE REVIEW

**Comment by tvladyslav** [comment]
Implemented feature request https://github.com/qTox/qTox/issues/5437

@anthonybilinski there should be no overmatching because of `magnet:?` keyword, which is quite specific, followed by at least one specific argument (xt/mt/kt).

*I would appreciate a double check of this regexp*, because I have poor skills in making them. But to the best of my knowledge and testing, it should work.

**Comment by sudden6** [comment]
Your regex doesn't seem to match:
```
magnet:?xt.1=urn:sha1:YNCKHTQCWBTRNJIV4WNAE52SJUQCZO5C&xt.2=urn:sha1:TXGCZQTH26NL6OUQAJJPFALHG2LTGBC7
```

which is valid according to: https://en.wikipedia.org/wiki/Magnet_URI_scheme

I checked using https://regex101.com

**Comment by tvladyslav** [comment]
@sudden6 good point! Thank you for review. Will fix it today.

**Comment by tvladyslav** [comment]
I didn't find an info if `xt.*` enumeration can start from any number, so I put there `\d` just in case.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5500#-:-LWUewsd1rMvPP1ZINVY:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
