### PR TITLE
fix(simple_make.sh): add a way to make compiling on Fedora work

### LINKED ISSUE #2998: simple_make missing dnf dep qt5-qtsvg-devel
qt5-qtsvg-devel
ffmpeg-devel

### PR DESCRIPTION
**Pull request by zetok**
By installing RPM Fusion repo, which provides required ffmpeg.

Also add missing qt5-qtsvg-devel dependency.

Closes #2998

Someone with Fedora should check whether it works.

### CODE REVIEW

**Comment by linux-modder** [comment]
willing to confirm this change works. but cursory check looks good.   will check with a clean build later today.

**Comment by zetok** [comment]
Note: still has sqlcipher missing in bootstrap.sh

**Comment by linux-modder** [comment]
was not able to add it  here for some reason I have both this commit and the bootstrap as a PR (#3232)

**Comment by zetok** [comment]
I've added required stuff in `bootstrap.sh` in a modular way.

What needs testing beside Fedora part, is whether `bootstrap.sh` after an additional refactoring still correctly works under windows.

**Comment by zetok** [comment]
cc @towlie ?

**Comment by towlie** [comment]
What shall I Test here?

**Comment by zetok** [comment]
Whether windows detection in `bootstrap.sh` still works – by running `boostrap.bat`, which will run `bootstrap.sh`, which is supposed to run `windows/bootstrap.sh`.

So if things will go beyond `./bootstrap.sh` there's no regressions.

Not sure what is needed on windows to make `bootstrap.sh` actually run – it depends on `bash`, so..

**Comment by towlie** [comment]
```
bootstrap.sh: Line 23: Microsoft: Command not found.
```

You broke and changed the detection.
You can compare that part with master. That one works.

**Comment by zetok** [comment]
> `bootstrap.sh: Line 23: Microsoft: Command not found.`

Heh. Funny how old version depended on stuff not working in order to work.

Anyway, thanks for testing, it probably should work now. (that is, I'm assuming that running `cmd.exe` will result in a `0` exit status on windows)

**Comment by towlie** [comment]
It works now.

```
Microsoft Windows [Version 6.1.7601]
--2016-05-07 12:09:10--  https://build.tox.chat/view/libtoxcore/job/libtoxcore_build_windows_x86_shared_release/lastSuccessfulBuild/artifact/libtoxcore_build_windows_x86_shared_release.zip
Auflösen des Hostnamens »build.tox.chat (build.tox.chat)« … 104.236.189.201, 2604:a880:1:20::31:5001
Verbindungsaufbau zu build.tox.chat (build.tox.chat)|104.236.189.201|:443 … verbunden.
HTTP-Anforderung gesendet, auf Antwort wird gewartet … 200 OK
Länge: 1847288 (1,8M) [application/zip]
Wird in »»libtoxcore_build_windows_x86_shared_release.zip«« gespeichert.
```

**Comment by zetok** [comment]
Thanks :)

**Pull request merged**
