### PR TITLE
New video view, v2

### PR DESCRIPTION
**Pull request by zetok**
Replaces #2370, which replaced #2093.

References, to check `[x]` when PR gets merged and issues will be closed:

Fixes:
- [x] #994 
- [x] #1971
- [x] #2037
- [x]  #2046

Most likely fixes / affects:
- [ ] #2351 (needs to be tested)
# 

~~I'm going to "fix"~~ EDIT: Fixed
https://github.com/tux3/qTox/pull/2370#discussion_r41925146
https://github.com/tux3/qTox/pull/2370#discussion_r41923824

rest is up to to you guys `:)`

### CODE REVIEW

**Comment by zetok** [comment]
@antis81 ok, fixed that.

**Comment by antis81** [comment]
Why does travis push fail?

**Comment by zetok** [comment]
@antis81 this branch still uses old `.travis.yml`, which points to PPA which no longer exists, and it fails on getting dependencies.

**Comment by agilob** [comment]
I AM MERGING THIS

STAND BACK

**Comment by antis81** [comment]
@agilob Fixed two minor warnings in master… :) And… I don't see my webcam again. Nevermind though. Together we'll get it going :+1:

**Pull request merged**
