### PR TITLE
Chore/update weblate

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Update qTox translations

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5805)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
I did a trivial rebase of your changes to v1.17-dev tip and changed the base branch over.

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong:

Feel free to push to v1.17-dev, don't worry about any additional merge.

> Reviewed 44 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5805#-:-LnQaGxE4eGLfuFF04Km:b-bryrlr)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
Also don't forget to reset and unlock weblate once done :)

**Comment by sudden6** [comment]
We can only update and unlock Weblate once the changes have been merged back to master, since Weblate operates on master.

**Comment by anthonybilinski** [comment]
v1.17-dev has been merged to master, and I reset and unlocked weblate. This PR should be all wrapped up.

**Pull request merged**
