### PR TITLE
test: Add tests for PosixSignalNotifier

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4701)

### CODE REVIEW

**Comment by Talkless** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/platform/posixsignalnotifier_test.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvMu9SiH-9GoZtETNih:-KvMu9SiH-9GoZtETNii:b-y9knx8) ([raw file](https://github.com/qtox/qtox/blob/efc78fa91eebce14bc1a5d51af894de987997e6a/test/platform/posixsignalnotifier_test.cpp#L37)):*
> ```cpp
> };
> 
> const int TIMEOUT = 10;
> ```

We could advocate to use `constexpr` whenever possible, for ints and std::chorno::miliseconds and other constexpr-friendly types.

---

*[test/platform/posixsignalnotifier_test.cpp, line 83 at r1](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvMtnBXL2tKH5wrY_jw:-KvMtnBYXRx35L6mUETJ:b2ltpv4) ([raw file](https://github.com/qtox/qtox/blob/efc78fa91eebce14bc1a5d51af894de987997e6a/test/platform/posixsignalnotifier_test.cpp#L83)):*
> ```cpp
>     QSignalSpy spy(&psn, &PosixSignalNotifier::activated);
> 
>     const QVector<int> termSignals = {SIGHUP, SIGINT, SIGQUIT, SIGTERM};
> ```

I believe this should work with simply `const auto termSignals = {... `, and loop through that `std::initialize_list<int>` itself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4701)*

**Comment by Talkless** [comment]
Thanks for the test. I should have done it myself.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4701#-:-KvMuYQwFC95AJsFYPGQ:bbqho9t)*

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/platform/posixsignalnotifier_test.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvMu9SiH-9GoZtETNih:-KvNDuspkL4tglKbNqXh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/efc78fa91eebce14bc1a5d51af894de987997e6a/test/platform/posixsignalnotifier_test.cpp#L37)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

We could advocate to use `constexpr` whenever possible, for ints and std::chorno::miliseconds and other constexpr-friendly types.
</blockquote></details>

Done.

---

*[test/platform/posixsignalnotifier_test.cpp, line 83 at r1](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvMtnBXL2tKH5wrY_jw:-KvNDv78xY2DAYupqmgz:bmcbymt) ([raw file](https://github.com/qtox/qtox/blob/efc78fa91eebce14bc1a5d51af894de987997e6a/test/platform/posixsignalnotifier_test.cpp#L83)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I believe this should work with simply `const auto termSignals = {... `, and loop through that `std::initialize_list<int>` itself.
</blockquote></details>

I don't like `auto`, because Qt Creator can't resolve variable type and can't offer me autocompletion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4701)*

**Comment by Talkless** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/platform/posixsignalnotifier_test.cpp, line 83 at r1](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvMtnBXL2tKH5wrY_jw:-KvSj8yqlQ7TeFWnufdG:bocru0v) ([raw file](https://github.com/qtox/qtox/blob/efc78fa91eebce14bc1a5d51af894de987997e6a/test/platform/posixsignalnotifier_test.cpp#L83)):*
> I don't like auto, because Qt Creator can't resolve variable type and can't offer me autocompletion

That's strange, maybe it's older QtCreator?

---

*[test/platform/posixsignalnotifier_test.cpp, line 46 at r2](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvSjdmG3Flp68y1O2Uy:-KvSjdmG3Flp68y1O2Uz:bnfzuqg) ([raw file](https://github.com/qtox/qtox/blob/607873d6401ad126237d2686d204fbfbff9115a2/test/platform/posixsignalnotifier_test.cpp#L46)):*
> ```cpp
>     kill(getpid(), SIGUSR1);
> 
>     for (int i = 0; i < TIMEOUT && spy.count() != 1; i++) {
> ```

All these `i++` could be changed to `++i` for good habit.

---

*[test/platform/posixsignalnotifier_test.cpp, line 53 at r2](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvSkBZvcFUwxFYUTQE-:-KvSkBZvcFUwxFYUTQE0:b-wuxkbc) ([raw file](https://github.com/qtox/qtox/blob/607873d6401ad126237d2686d204fbfbff9115a2/test/platform/posixsignalnotifier_test.cpp#L53)):*
> ```cpp
>     QCOMPARE(spy.count(), 1);
>     QList<QVariant> args = spy.takeFirst();
>     QCOMPARE(args.takeFirst().toInt(), SIGUSR1);
> ```

I doubt `args.takeFirst()` is needed here, non-mutating `.first()` should be enough, also allowing `const QList<QVariant>`.

---

*[test/platform/posixsignalnotifier_test.cpp, line 98 at r2](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvSlhQyiTFXa3n3i0Ib:-KvSlhQyiTFXa3n3i0Ic:b-i84lpv) ([raw file](https://github.com/qtox/qtox/blob/607873d6401ad126237d2686d204fbfbff9115a2/test/platform/posixsignalnotifier_test.cpp#L98)):*
> ```cpp
> 
>     for (int i = 0; i < termSignals.size(); i++) {
>         QList<QVariant> args = spy.at(i);
> ```

const QList,  .takeFirst() -> .first()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4701)*

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/platform/posixsignalnotifier_test.cpp, line 83 at r1](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvMtnBXL2tKH5wrY_jw:-KvYgyQTuv8r2dwigtxH:blylc0w) ([raw file](https://github.com/qtox/qtox/blob/efc78fa91eebce14bc1a5d51af894de987997e6a/test/platform/posixsignalnotifier_test.cpp#L83)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

> I don't like auto, because Qt Creator can't resolve variable type and can't offer me autocompletion

That's strange, maybe it's older QtCreator?
</blockquote></details>

QtCreator 4.4.0

---

*[test/platform/posixsignalnotifier_test.cpp, line 46 at r2](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvSjdmG3Flp68y1O2Uy:-KvYgsMoZd-WS5aQLChI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/607873d6401ad126237d2686d204fbfbff9115a2/test/platform/posixsignalnotifier_test.cpp#L46)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

All these `i++` could be changed to `++i` for good habit.
</blockquote></details>

Done.

---

*[test/platform/posixsignalnotifier_test.cpp, line 53 at r2](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvSkBZvcFUwxFYUTQE-:-KvYgsmfZyqe0fXX389P:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/607873d6401ad126237d2686d204fbfbff9115a2/test/platform/posixsignalnotifier_test.cpp#L53)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I doubt `args.takeFirst()` is needed here, non-mutating `.first()` should be enough, also allowing `const QList<QVariant>`.
</blockquote></details>

Done.

---

*[test/platform/posixsignalnotifier_test.cpp, line 98 at r2](https://reviewable.io:443/reviews/qtox/qtox/4701#-KvSlhQyiTFXa3n3i0Ib:-KvYh8fO3XjEfm7bG-tW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/607873d6401ad126237d2686d204fbfbff9115a2/test/platform/posixsignalnotifier_test.cpp#L98)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QList,  .takeFirst() -> .first()
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4701)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4701#-:-KvcDwelcr2KcpLVbRDo:b-jbsf8z)*

**Pull request merged**
