### PR TITLE
[WIP] Chat: add text search

### PR DESCRIPTION
**Pull request by antis81**
implement #2377

@kehugter @agilob This PR serves as a review basis and is the first extraction of PR #2744 (I will abandon that one soon).

:warning: **Unstable**: Does crash as soon as `CTRL+F` is hit (Thus WIP).

### CODE REVIEW

**Comment by ghost** [comment]
Crashes indeed.

It wasn't the case in #2744. There the search field was opened, you could search (the focus jumped to the chat input area almost immediately each time) and the results were shown. There was no way to close the search area.

**Comment by tux3** [comment]
It's OK to send some WIP PRs that need some testing, but it looks like this doesn't work at all, and it has been inactive for over two weeks.
Please resend when it's a bit more developed, so we don't have too many inactive broken PRs sitting around for weeks.

**Comment by antis81** [comment]
@tux3 Yes, this is good decision. Maybe i'm going to reimplement this in another PR.

**Comment by tux3** [comment]
@antis81 Alright, looking forward to it

**Pull request closed without merging**
