### PR TITLE
Option for tray icon to display user status

### PR DESCRIPTION
**Pull request by ghost**
Setting added for tray icon to be displayed as user status. Default value is **off** (original tox icon as it is now). Useful when user wants to see his current status in tray. Especially handy when auto-away kicks in, we immediately can see if we are away or not without a risk of breaking away status.

### CODE REVIEW

**Comment by dubslow** [comment]
We were waiting to do this until we had proper icons from @ItsDuke, he has these made: https://github.com/tux3/qTox/issues/578#issuecomment-61900064

We're just waiting for the individual files to be uploaded so we can add them.

Additionally, please separate the fixed windowGeometry stuff into a separate commit from updating the tray icon. There's no reason to have them in the same commit.

**Comment by ghost** [comment]
@dubslow This changes were relying on @novist's branch. I improved the UI that @novist implemented.
I'll separate the bug fix and open a new PR.

**Comment by ghost** [comment]
Im not exactly git master so not sure how to go about splitting commit. Obvious way i can think of includes rewriting history and using --force to push but since someone has changes that now depend on this commit i have no idea how to handle it. Some guidance would be appreciated.

P.S. those icons look awesome!

**Comment by dubslow** [comment]
@mwuttke97 Yours is fine, you don't need to open a new PR or anything. I'm talking about novist's first commit should be two.

@novist perhaps just make a new branch with two new commits you manually separate, then cherry pick mwuttke97's commit into the new branch as well?

**Comment by ghost** [comment]
@dubslow In your first comment, you related to @novist's function extraction `saveWindowGeometry()`, didn't you?

@github  Something went wrong with that request

**Comment by dubslow** [comment]
Yeah. He's since removed that code from this PR and said he'd make a separate one. (Note that I only requested those changes in a separate commit, not a separate PR, but it was easier for him to just make a second PR.)

**Comment by ghost** [comment]
Now, writing comments is working again.
@dubslow I requested @novist to cherry pick my first commit https://github.com/mwuttke97/qTox/commit/360cc6422d829a08806c511c73d45e5f5ea5e367, where I refactored the tray-icon-related-settings and also fixed a bug. When he has done so, I think, this PR could be merged. Have you write access to https://github.com/tux3/qTox/ ?

**Comment by ghost** [comment]
It's done now. @tux3 could merge it now.

**To sum up what changed:**
- as the title says:

> Option for tray icon to display user status
- Refactored window dimension and splitter stuff 
- Refactored generalform (new "System tray integration" group box)
  bildschirmfoto vom 2014-11-26 19 49 29
- Fixed this bug (I found this bug but forgot to open an issue):

> The tray-icon-related check boxes were checkable after starting a new instance of qTox, even when "show system tray icon" was unchecked.
- done, undone and finally redone or "un-undone" some things :smile:  :anger:  :sweat:  :confused:  :yum:

**Comment by ghost** [comment]
@novist Why did you remove this connection?

``` xml
- <connection>
- <sender>showSystemTray</sender>
- <signal>toggled(bool)</signal>
- <receiver>trayShowsUserStatus</receiver>
- <slot>setEnabled(bool)</slot>
- <hints>
- <hint type="sourcelabel">
- <x>148</x>
- <y>143</y>
- </hint>
- <hint type="destinationlabel">
- <x>158</x>
- <y>205</y>
- </hint>
- </hints>
- </connection>
```

Please revert your last commit. It makes no sense to me.
Hint: If you reconnect the signals in QtCreator it'll revert your last commit exactly.

**Comment by ghost** [comment]
Yes i noticed one connection being removed. It happened when i removed one checkbox since there were two trayShowsUserStatus checkboxes. One in groupbox and one outside of it, so i removed outside one.

**Comment by ghost** [comment]
Well, I tried it out. (I checked out on your branch and made`make`.) You definitely deleted the correct connection -- which is wrong. I ran the code and it didn't work properly. Then I reconected it (using QtCreator) and `git diff` printed out the same, but  '+' instead of '-' and '-' instead of '+'. Do you understand?

**Comment by ghost** [comment]
Yeah, ill correct it tomorrow. Thanks for pointing it out

**Comment by ghost** [comment]
I suppose someone should fix style of disabled checkboxes too as they look just like enabled ones. It will probably confuse some people.

**Comment by ghost** [comment]
@novist Here's a link: http://qt-project.org/forums/viewthread/27111
If someone added this, please open a new PR. This one has awesome many commits :smile:

**Comment by dubslow** [comment]
Yeah lol, it's quite messy.

**Comment by ghost** [comment]
I cleaned up all this mess and made new PR https://github.com/tux3/qTox/pull/870

**Pull request closed without merging**
