### PR TITLE
I translated into Romanian

### PR DESCRIPTION
**Pull request by remussatala**
https://hosted.weblate.org/projects/tox/qtox/ro/

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4348)

### CODE REVIEW

**Comment by sudden6** [comment]
Please add `chore(translation):` to the front of your commit message.

**Comment by remussatala** [comment]
I'm not a programmer. :)

**Comment by sudden6** [comment]
When using git, just do `git commit --amend` and edit the title on your branch and then push it.

EDIT: fixed instructions

**Comment by zetok** [comment]
Added in 0192e9275f1ceb1cc4caa0b810f87da92d56b75a, thanks!

**Comment by remussatala** [comment]
It should be updated.

**Comment by sudden6** [comment]
What should be updated?

**Comment by remussatala** [comment]
The romanian languaje should be update. I made some changes there.

**Comment by zetok** [comment]
@remussatala using instructions from [MAINTAINING.md](https://github.com/qTox/qTox/blob/master/MAINTAINING.md#translations-from-weblate) anyone can make a PR with updated translations from Weblate.

**Comment by sudden6** [comment]
Additionally we will also update the translations before a release.

**Pull request closed without merging**
