### PR TITLE
[Refactor] Reduce Friend::getChatForm usage

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4542)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/friend.cpp, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4542#-Kq48D83egYG8RgqGgP7:-Kq48D83egYG8RgqGgP8:b-78klhl) ([raw file](https://github.com/qtox/qtox/blob/a993fb5e2d5395e3f5416544cde2ebdadd1f3427/src/friend.cpp#L141)):*
> ```cpp
> ChatForm* Friend::getChatForm() const
> {
>     return chatForm;
> ```

Since this can now theoretically return `nullptr` care must be taken in calling functions

---

*[src/widget/contentdialog.cpp, line 171 at r1](https://reviewable.io:443/reviews/qtox/qtox/4542#-Kq47uMcQXB2uQOi1HXI:-Kq47uMdW8lGGwBGLpUW:b-peu27c) ([raw file](https://github.com/qtox/qtox/blob/a993fb5e2d5395e3f5416544cde2ebdadd1f3427/src/widget/contentdialog.cpp#L171)):*
> ```cpp
>     friendLayout->addFriendWidget(friendWidget, frnd->getStatus());
> 
>     ChatForm* form = frnd->getChatForm();
> ```

I think this line can also be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4542)*

**Comment by Diadlo** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/friend.cpp, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4542#-Kq48D83egYG8RgqGgP7:-Kq7CLbusXEJTFeR89u_:bdbubfr) ([raw file](https://github.com/qtox/qtox/blob/a993fb5e2d5395e3f5416544cde2ebdadd1f3427/src/friend.cpp#L141)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Since this can now theoretically return `nullptr` care must be taken in calling functions
</blockquote></details>

nullptr doesn't really possible, because chatForm settled immediately after friend creation. But added

---

*[src/widget/contentdialog.cpp, line 171 at r1](https://reviewable.io:443/reviews/qtox/qtox/4542#-Kq47uMcQXB2uQOi1HXI:-Kq7BoA86UXY-fyyAEOL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a993fb5e2d5395e3f5416544cde2ebdadd1f3427/src/widget/contentdialog.cpp#L171)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think this line can also be removed
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4542)*

**Comment by sudden6** [comment]
Reviewed 1 of 5 files at r1, 2 of 3 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/widget.cpp, line 1125 at r2](https://reviewable.io:443/reviews/qtox/qtox/4542#-Kq8YpJDYjkdIELEIjf3:-Kq8YpJEGzhYprRvs5qk:b-9axh8t) ([raw file](https://github.com/qtox/qtox/blob/3bbbe3ba0469d2174eb7b3fb928ed24a7315b388/src/widget/widget.cpp#L1125)):*
> ```cpp
>     GenericChatForm* form;
>     Friend* frnd = widget->getFriend();
>     if (widget->getFriend()) {
> ```

reuse frnd

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4542)*

**Comment by Diadlo** [comment]
Review status: 2 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/widget.cpp, line 1125 at r2](https://reviewable.io:443/reviews/qtox/qtox/4542#-Kq8YpJDYjkdIELEIjf3:-KqEakjWwSGEhxS-nTNT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3bbbe3ba0469d2174eb7b3fb928ed24a7315b388/src/widget/widget.cpp#L1125)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

reuse frnd
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4542)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4542#-:-KqHc8IEHfKwujj1BDkW:b-jbsf8z)*

**Pull request merged**
