### PR TITLE
Spanish translation updated

### PR DESCRIPTION
**Pull request by MS-PC**
Spanish translation updated

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4793)

### CODE REVIEW

**Comment by MS-PC** [comment]
Spanish translation updated

**Comment by sudden6** [comment]
change the commit message to fit https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by MS-PC** [comment]
I do not understand much of how to do it, but if you are so kind to add my translations with the corrections.
That you add it manually, thanks.

My goal is only to collaborate.

**Comment by Diadlo** [comment]
Just use this:
```
git commit --amend -m "feat(l10n): update <language> translation"
git push -f
```

**Comment by sudden6** [comment]
@MS-PC If you don't want to learn git but still contribute, you can use Weblate: https://hosted.weblate.org/projects/tox/qtox/

**Comment by MS-PC** [comment]
In case of doubts, and to translate in the page that they proposed, with a temporary account, since for security use a temporary account.
and that I do not like to create accounts with my personal email everywhere.

@sudden6  It is done.

**Pull request closed without merging**
