### PR TITLE
Move Status out of Widget, make asset path not dependent on translation

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5636)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 25 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5636)* status: 0 of 1 LGTMs obtained

___
*[src/model/status.h, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5636#-Ld9FAmF7xJnDK2ZDblc:-Ld9FAmF7xJnDK2ZDbld:b-kqsv05) ([raw file](https://github.com/qtox/qtox/blob/aa172b97ac18d84519c9fa458ddb3bd543ffcb48/src/model/status.h#L29)):*
> ```objc
> {
>     // Status::Status is weird, but Status is a fitting name for both the namespace and enum class..
>     enum class Status
> ```

I think explicitly making the base type `int` would save a lot of casting

**Comment by Diadlo** [comment]
@sudden6 Just my opinion: explicit is better than implicit. There is not so much status casting (just 4 places)

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5636)* status: 0 of 1 LGTMs obtained

___
*[src/model/status.h, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5636#-Ld9FAmF7xJnDK2ZDblc:-LdF343p09VOPKvGPNTE:b7y9cgn) ([raw file](https://github.com/qtox/qtox/blob/aa172b97ac18d84519c9fa458ddb3bd543ffcb48/src/model/status.h#L29)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think explicitly making the base type `int` would save a lot of casting
</blockquote></details>

Changing the underlying type to `int` still fails at converting a QVariant, and doesn't allow for implicit casting. I also think the strong typing of `enum class` is useful for Status in every case but this one, so although changing to `enum` would allow it to implicitly cast during serialization/deserialization, I think it would be less safe as a type in all other cases.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5636#-:-LdFHbOo8mTcKBtUkEYB:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/model/status.h, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5636#-Ld9FAmF7xJnDK2ZDblc:-LdFHVWdBeyvE-ZqisU6:b7g79ah) ([raw file](https://github.com/qtox/qtox/blob/aa172b97ac18d84519c9fa458ddb3bd543ffcb48/src/model/status.h#L29)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Changing the underlying type to `int` still fails at converting a QVariant, and doesn't allow for implicit casting. I also think the strong typing of `enum class` is useful for Status in every case but this one, so although changing to `enum` would allow it to implicitly cast during serialization/deserialization, I think it would be less safe as a type in all other cases.
</blockquote></details>

ok then, since you and @Diadlo seem to agree it's better otherwise.

**Pull request merged**
