### PR TITLE
Removing some unused Core parts

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4598)

### CODE REVIEW

**Comment by Diadlo** [comment]
Add information, that `removeGroup` already used instead of `quitGroupChat` . Otherwise  :lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4598#-:-KsZ1dggxzZK2_kx-bTq:bbt5qm8)*

**Comment by noavarice** [comment]
Where should I add info about it?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4598#-:-Kt0ozSgTG73EEWtRrRk:bn6uqdw)*

**Comment by Diadlo** [comment]
In commit body

**Comment by noavarice** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4598#-:-Kt0rZ6Jy2u7TOcin9kj:b-896fix)*

**Pull request merged**
