### PR TITLE
chore: limit scope of commit messages to dozen characters

### PR DESCRIPTION
**Pull request by zetok**
cc @BiTOk  @Diadlo @antis81 @sudden6 @tux3

---

This change is [Reviewable](https://reviewable.io/reviews/tux3/qtox/3574)

### CODE REVIEW

**Comment by BiTOk** [comment]
So what we should point in scope? For example in this commit: ea0ed69b7aa6b54478138447476e63306b674f68.

**Comment by sudden6** [comment]
IMHO the scope isn't really useful, why not remove it completely?

**Comment by antis81** [comment]
@sudden6 @BiTOk Scope is optional. You can leave out the braces.

**Comment by antis81** [comment]
> So what we should point in scope? For example in this commit: ea0ed69.

You could give something like `(settings,chat)` or nothing at all.

**Comment by Diadlo** [comment]
Why limit is dozen? Now absolutely unreal set some scopes. `genericchatitemlayout`, for example

**Comment by sudden6** [comment]
@antis81 my suggestion about removing the scope part comes from a IRC discussion about the commit message format making things complex for new contributors. I know I can omit it, but do they know? :) Also it doesn't provide a real value in my opinion.

**Comment by zetok** [comment]
> Why limit is dozen? Now absolutely unreal set some scopes. `genericchatitemlayout`, for example

Yes. If you're running into the limit, you're doing it wrong. The example is perfect to show what shouldn't be in the scope.

Besides, dozen is a nice, round number.

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tux3/qtox/3574)*

**Comment by zetok** [comment]
@sudden6 

> I know I can omit it, but do they know?

Well, in CONTRIBUTING.md:

> The scope of the header is also optional.

.

> Also it doesn't provide a real value in my opinion.

It allows to have sections of changelog for given version where stuff that affects particular things is grouped.

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3574#-:-KOLtH5CRihfr1IXTSFG:1417088721)_

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 108 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3574#-KOLwrrNM7LZBYW6zi-I:-KOLwrrNM7LZBYW6zi-J:1381404245) ([raw file](https://github.com/qtox/qtox/blob/b9c3e977659ddd6e4ecdc4b524d32fff50df455e/CONTRIBUTING.md#L108)):_

> ``` Markdown
> `ngView`, etc.
> 
> Since people were abusing legth of the scope, it's limited to 12 characters.
> ```

typo: length

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3574)_

**Comment by zetok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 108 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3574#-KOLwrrNM7LZBYW6zi-I:-KOLzAmB0LhB-W9BlrOs:1758359711) ([raw file](https://github.com/qtox/qtox/blob/b9c3e977659ddd6e4ecdc4b524d32fff50df455e/CONTRIBUTING.md#L108)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> typo: length
> </details>
> Fixed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3574)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3574#-:-KOM-tMO1x2-dCE7Dok0:1417088721)_

**Pull request merged**
