### PR TITLE
Keyboard shortcuts to clear chat area

### PR DESCRIPTION
**Pull request by agilob**
clearing chat area

### CODE REVIEW

**Comment by apprb** [comment]
Potential bug: what happen if you clear chat area with active file transfer?
Since FileTransferAction updates itself by QTextCursor pointed to the certain plaice in ChatAreaWidget.
Probably not a problem, but anyway it is not very good to get rid of active filetransfers.

If you don't against it I'll reimplement this in my history branch (already partially done in apprb@6860790 but without shortcuts for now) on slightly different way.

**Comment by agilob** [comment]
Status of active file transfer reappears.

Bug: paused file transfers don't reappear.

**Comment by tux3** [comment]
I can't merge this just yet if it's still buggy, sorry.

**Comment by agilob** [comment]
No problem, I don't know if I should fix that bug now or wait for fix #266 (last 3 comments)

**Pull request closed without merging**
