### PR TITLE
Fixed build for OS X

### LINKED ISSUE #1: Error compiling qtox with homebrew
https://gist.github.com/3a35560668e2f74e67e5.git

Following directions here:

https://github.com/tux3/qTox#osx-easy-install

### PR DESCRIPTION
**Pull request by ReDetection**
This will also fix ReDetection/homebrew-qtox#1

### CODE REVIEW

**Comment by tux3** [comment]
And bam : Broken jenkins.

**Comment by ReDetection** [comment]
Just found jenkins. :)
I don't understand what you mean. Jenkins os x build is OK now (and was OK when there was include issue o_O ), win builds and linux builds are failing for a long time. o_O 

It seems, Jenkins are working on the OS X too.. I do not know too much about cross-compiling from OS X. I thought it should include AL/al.h when building for them, shouldn't it?

**Comment by tux3** [comment]
> It seems, Jenkins are working on the OS X too.. 

Yeah, I'm surprised it didn't break. But I'm not complaining!

> win builds and linux builds are failing for a long time. o_O 

You can go yell at NikolaiToryzin on #tox-dev @ irc.freenode.net if you want them fixed, I'm sure he'll appreciate it :)

**Comment by ReDetection** [comment]
Oh, I misunderstood :)
And also it seems like I misunderstood tox's jenkins setup. And now I see that `tux3-toxgui` task just downloads sources and triggers build for each platform. Task `ToxGUI OSx X` did break but after some failures it began to build (but with failures in log, seems like there is a bug in the buildscript but I can't see buildscript). I can't see differences between failed and passed build so I think someone just created symlink OpenAL → AL.

**Pull request merged**
