### PR TITLE
chore(tools): make translation updating script amend translation commits

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3854)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[tools/update-translation-files.sh, line 67 at r1](https://reviewable.io:443/reviews/qtox/qtox/3854#-KVlK8N20BPtfUcePiCE:-KVlK8N3hw91CwdGCnlK:bih8vea) ([raw file](https://github.com/qtox/qtox/blob/5a9928774e48d4adb33cbea98fc15ac3817a3681/tools/update-translation-files.sh#L67)):_

> ``` Shell
>     if [[ "$@" = "ALL" ]]
>     then
>         update_translations
> ```

I can't fond `update_translations` function

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3854#-:-KVlLRmGiXcQJ_onSivU:bm6j53k)_

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[tools/update-translation-files.sh, line 72 at r1](https://reviewable.io:443/reviews/qtox/qtox/3854#-KVlOAx092YxGvOQUL44:-KVlOAx16iBZTyVxJIFs:b-5p5741) ([raw file](https://github.com/qtox/qtox/blob/5a9928774e48d4adb33cbea98fc15ac3817a3681/tools/update-translation-files.sh#L72)):_

> ``` Shell
>     fi
> }
> main
> ```

You forget `$@` here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3854)_

**Comment by zetok** [comment]
Right, sorry, I should have actually tested.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[tools/update-translation-files.sh, line 67 at r1](https://reviewable.io:443/reviews/qtox/qtox/3854#-KVlK8N20BPtfUcePiCE:-KVlTCcDA3AIpensLIuH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5a9928774e48d4adb33cbea98fc15ac3817a3681/tools/update-translation-files.sh#L67)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> I can't fond `update_translations` function
> </details>
> Done.

---

_[tools/update-translation-files.sh, line 72 at r1](https://reviewable.io:443/reviews/qtox/qtox/3854#-KVlOAx092YxGvOQUL44:-KVlTFDyjO0f63rntD2l:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5a9928774e48d4adb33cbea98fc15ac3817a3681/tools/update-translation-files.sh#L72)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> You forget `$@` here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3854#-:-KVlT8QKuXuDptvN_IYX:bk1coe8)_

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3854#-:-KVl_XzRZiOBoAfE54Ml:bnfp4nl)_

**Comment by zetok** [comment]
Re: [yesterday's discussion on IRC](https://github.com/qTox/qtox-irc-logs/blob/f04f6f51cec86ee428b45ec406d3d0b49dcd37cb/2016/11/%23qtox_20161104.log.txt#L186,L219); I've added a separate script with the needed behavior.

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3854#-:-KVq4z8H6LtQKkRX8TgR:bnfp4nl)_

**Pull request merged**
