### PR TITLE
feat(offlinemsg): Enable offline messages with no history

### PR DESCRIPTION
**Pull request by sphaerophoria**
Enables faux offline messaging with no history.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5688)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688)* status: 0 of 1 LGTMs obtained

___
*[src/model/message.h, line 28 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LflbpndAqtdzu6rdHzv:-Lflbpne93N3KkYyHMlY:bfdnmqp) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/src/model/message.h#L28)):*
> ```objc
> struct Message
> {
>     bool isAction;
> ```

there's TOX_MESSAGE_TYPE enum tox.h that seems preferable to a isAction bool.
___
*[src/persistence/iofflinemsgssettings.h, line 23 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfljVq31uvyKKUGNiTp:-LfljVq31uvyKKUGNiTq:bjfmhv9) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/src/persistence/iofflinemsgssettings.h#L23)):*
> ```objc
> #define IOFFLINE_MSGS_SETTINGS_H
> 
> class IOfflineMsgsSettings
> ```

now that offline messaging works with or without history enabled, I don't see the value in having a setting for it. With it disabled UI is significantly more confusing (it's impossible to tell if the message has been delivered or not). @sudden6 @diadlo what do you think of removing the "Faux offline messaging" checkbox, and having it always be enabled (but still respect history setting under privacy tab)?
___
*[test/persistence/offlinemsgengine_test.cpp, line 164 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfmBrfKClHkG6mOpsgh:-LfmBrfLCjuxIIbEVgWK:bvcvuor) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/test/persistence/offlinemsgengine_test.cpp#L164)):*
> ```cpp
>     fixture.offlineMsgEngine.addUnsentMessage(msg, completionFn);
>     fixture.offlineMsgEngine.addUnsentMessage(msg, completionFn);
> ```

could verify here that we didn't attempt to send any messages?
___
*[test/persistence/offlinemsgengine_test.cpp, line 206 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfmErl5AWHL_405MGRG:-LfmErl5AWHL_405MGRH:b-sadt68) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/test/persistence/offlinemsgengine_test.cpp#L206)):*
> ```cpp
>     fixture.offlineMsgEngine.addSentMessage(receipt, msg, callback);
>     fixture.offlineMsgEngine.addUnsentMessage(msg, callback);
> ```

verify here that the numCallbacks == 1?

**Comment by sudden6** [comment]
> what do you think of removing the "Faux offline messaging" checkbox, and having it always be enabled (but still respect history setting under privacy tab)?

Seems like a good idea to me.

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688)* status: 0 of 1 LGTMs obtained

___
*[src/model/message.h, line 28 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LflbpndAqtdzu6rdHzv:-LfojX3F53m-7YHnIzvt:bhtbxt3) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/src/model/message.h#L28)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

there's TOX_MESSAGE_TYPE enum tox.h that seems preferable to a isAction bool.
</blockquote></details>

I'm not sure I agree with this. We currently use isAction as a bool in bunch of other places. I'd be in favor of turning it into an enum later if more action types are added, but for now I think moving to an enum would just add a lot of conversions in other places with little benefit.
___
*[src/persistence/iofflinemsgssettings.h, line 23 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfljVq31uvyKKUGNiTp:-Lfojmvi3STnomzDiYcB:b-6nni21) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/src/persistence/iofflinemsgssettings.h#L23)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

now that offline messaging works with or without history enabled, I don't see the value in having a setting for it. With it disabled UI is significantly more confusing (it's impossible to tell if the message has been delivered or not). @sudden6 @diadlo what do you think of removing the "Faux offline messaging" checkbox, and having it always be enabled (but still respect history setting under privacy tab)?
</blockquote></details>

I'm in favor of this. Since @sudden6 gave it the go ahead I've amended my PR with the change
___
*[test/persistence/offlinemsgengine_test.cpp, line 164 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfmBrfKClHkG6mOpsgh:-LfolUisDOJSdsN7qjdZ:bvkegn4) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/test/persistence/offlinemsgengine_test.cpp#L164)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

could verify here that we didn't attempt to send any messages?
</blockquote></details>

I don't really see the benefit. The OfflineMsgEngine doesn't try to send until we tried to deliver messages, but even if it did that would be reasonable behavior. I just care that all of them try to get sent _at somepoint_
___
*[test/persistence/offlinemsgengine_test.cpp, line 206 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfmErl5AWHL_405MGRG:-Lfon5vzDqqeMuslCt6X:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/test/persistence/offlinemsgengine_test.cpp#L206)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

verify here that the numCallbacks == 1?
</blockquote></details>

Done

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688)* status: 0 of 1 LGTMs obtained

___
*[test/persistence/offlinemsgengine_test.cpp, line 206 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfmErl5AWHL_405MGRG:-Lfpbtu-1SwD2QWDsHtU:bhsr8a5) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/test/persistence/offlinemsgengine_test.cpp#L206)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Done
</blockquote></details>

Same logic applies here as to the previous point?

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688)* status: 0 of 1 LGTMs obtained

___
*[test/persistence/offlinemsgengine_test.cpp, line 206 at r1](https://reviewable.io/reviews/qtox/qtox/5688#-LfmErl5AWHL_405MGRG:-Lfpgc1CBM3ebuN4YOzB:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/5efae471b8a89d72b83d7e948eb826a8eb2a6706/test/persistence/offlinemsgengine_test.cpp#L206)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Same logic applies here as to the previous point?
</blockquote></details>

Done

**Review by anthonybilinski — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688#-:-LfphAFZ2tmDwrEATNpd:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by sphaerophoria — COMMENTED** [review]
Whoops had to update the PR. Accidentally forgot to force the spinner to be cleaned up on the main thread and hit a crash when my disk was really slow.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688#-:-LfqBqHd2ZgnjApEKWwB:bcz9ch)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5688#-:-LgvNZSGAipUPJ33HvN8:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
