### PR TITLE
[WIP] Fix Quit/Close actions

### PR DESCRIPTION
**Pull request by antis81**
- [ ] Close qTox sub-windows with CTRL+W instead of CTRL+Q
- [ ] Quit qTox through central (and plattform-independent) CTRL+Q action.

### CODE REVIEW

**Comment by antis81** [comment]
@agilob This is a starting point to fix the duplicate quit actions and `CTRL+Q` behaving like `CTRL+W`. 

Unfortunately still coding this "blind", because I can't get `FFMPEG` stuff to compile. Anyone with Ubuntu 14.04 derivate who can help (@zetok maybe?).

**Comment by agilob** [comment]
I'm strongly against this change `rename quit action from "&Exit" -> "&Quit"`, on my KDE I will have two Quit actions with two different results when clicked.

**Comment by antis81** [comment]
@agilob Done revert of renamed quit action.

**Comment by zetok** [comment]
@antis81 

> fails and tells me GCC cannot compile code.

That's an issue with your gcc install.. Are you sure that you've got the "correct" gcc?

**Comment by antis81** [comment]
@zetok No, it was an issue with ffmpeg… anyway, got it working now. Unfortunately I'm really short on time for qTox currently.

**Pull request closed without merging**
