### PR TITLE
Fix wording for copying friend public key

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by dubslow** [comment]
Technically the key is the ID; the key+ns+chk is called the address.

**Comment by zetok** [comment]
Key is only a part of ID, thus current wording isn't accurate and causes confusion

Edit: https://libtoxcore.so/core_concepts.html#the-tox-id

**Comment by dubslow** [comment]
https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L43

**Comment by tux3** [comment]
We actually try to give back the full Tox ID not just the pubkey (in Core::getFriendAddress(int)) so the wording should be okay.
Plus, I'd rather not confuse the users with too many technical terms if it can be helped. For all intents and purposes the Tox ID is the bunch of letters and numbers you copy paste to add someone, no crypto knowledge required.

**Comment by zetok** [comment]
k, just don't be surprised when users will come screaming that copying ID is broken, as I've highlighted it in #235

**Comment by tux3** [comment]
I haven't had any report of confused users yet, but I remember several people asking for a way to copy their friend's ID, and even making issues on github (three times! #235, #84 and #44).

I know that it's not a very good solution, but I don't have anything better, and if people want this feature I'm not going to hide it from them like I know better.

If you have a good solution I'll gladly consider it, I'm always open to discussion. That said I don't think that changing the wording like this is right, we actually try to return a working friend ID right now, not just the pubkey, so this PR would make it :
- A bit more confusing, this is the only place qTox mentions a public key, eveywhere else we handle Tox IDs
- Wrong most of the time, we normally do return a Tox ID.

**Comment by jbshirk** [comment]
copy friend ID does nothing on OS X, nothing in clipboard. How do I get it?

**Comment by tux3** [comment]
> copy friend ID does nothing on OS X, nothing in clipboard. How do I get it?

If you have absolutely nothing in the clipboard, then that's a bug. 
Does it never work, or just sometimes ?

EDIT: I just tried copying GroupBot's ID on OS X and it worked for me. 
Can you give me more details ? Are you sure you're running the latest version of qTox ?

pic11

**Pull request closed without merging**
