### PR TITLE
Added a bulgarian translation

### PR DESCRIPTION
**Pull request by D3cryptor**
Add Bulgarian Language

### CODE REVIEW

**Comment by suhr** [comment]
Don't forget to add a `.qm` file (click Release in Qt Linguist menu). Also, why close an pull request?

**Comment by tux3** [comment]
Why did you close the PR ? Is the translation not right ?

I can take care of releasing the .qm file this time, if needed.

**Comment by D3cryptor** [comment]
Sorry, i can't make .qm file

**Comment by dubslow** [comment]
Looks like he accidentally the branch which automaccidentally the PR

**Comment by tux3** [comment]
Merged in d315a5fd17f9f29eb5eb7aaccd1ba8e21f89d637, released in 41237a9bbc53915268ee9682ed30af626f7838e0

**Comment by D3cryptor** [comment]
Thanks, if u want change -> "българин" to "Български"

**Comment by tux3** [comment]
Done.

**Comment by D3cryptor** [comment]
Soon I will make some changes

**Pull request closed without merging**
