### PR TITLE
Rewrite cstring

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4237)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxstring.h, line 23 at r1](https://reviewable.io:443/reviews/qtox/qtox/4237#-KeXrgd5q740IUP7n3HZ:-KeXrgd5q740IUP7n3H_:b-dinff0) ([raw file](https://github.com/qtox/qtox/blob/c63c47203e02e707d9c2471ab502986e471ca7f0/src/core/toxstring.h#L23)):*
> ```objc
> #define TOXSTRING_H
> 
> #include <cstdint>
> ```

Don's sure but should these headers be sorted that way? maybe i got it wrong in coding standarts, you can keep as it is

---

*[src/core/toxstring.h, line 33 at r1](https://reviewable.io:443/reviews/qtox/qtox/4237#-KeXxUcNeTrSQ0TZnxCU:-KeXxUcNeTrSQ0TZnxCV:b-v21gip) ([raw file](https://github.com/qtox/qtox/blob/c63c47203e02e707d9c2471ab502986e471ca7f0/src/core/toxstring.h#L33)):*
>  
I guess, "explicit" specifier is redundant here because there are more than one parameter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237)*

**Comment by sudden6** [comment]
Review status: 0 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxstring.h, line 23 at r1](https://reviewable.io:443/reviews/qtox/qtox/4237#-KeXrgd5q740IUP7n3HZ:-KeYLofjH9ljeRTL6guJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c63c47203e02e707d9c2471ab502986e471ca7f0/src/core/toxstring.h#L23)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Don's sure but should these headers be sorted that way? maybe i got it wrong in coding standarts, you can keep as it is
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237)*

**Comment by Diadlo** [comment]
Why not use `QString` instead of `ToxString`?

**Comment by sudden6** [comment]
this would result in a lot of casting, which is avoided with this solution.

**Comment by Diadlo** [comment]
Are talking about `uint8_t` -> `char` casting?

**Comment by sudden6** [comment]
yes

**Comment by Diadlo** [comment]
Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxstring.h, line 33 at r1](https://reviewable.io:443/reviews/qtox/qtox/4237#-KeXxUcNeTrSQ0TZnxCU:-KejdeY0sghH8AvxDWfY:b3kqu) ([raw file](https://github.com/qtox/qtox/blob/c63c47203e02e707d9c2471ab502986e471ca7f0/src/core/toxstring.h#L33)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

>  
I guess, "explicit" specifier is redundant here because there are more than one parameter
</blockquote></details>

+

---

*[src/widget/form/chatform.cpp, line 1015 at r2](https://reviewable.io:443/reviews/qtox/qtox/4237#-KejdPcz0X462wg_0YXK:-KejdPcz0X462wg_0YXL:bg6s4xn) ([raw file](https://github.com/qtox/qtox/blob/5feecd9cb13e1307a927b56de178184418d4aa49/src/widget/form/chatform.cpp#L1015)):*
> ```cpp
>     QDateTime timestamp = QDateTime::currentDateTime();
> 
>     for (QString& qt_msg : splittedMsg) {
> ```

Please, use camel case (i.e. `qtMsg`)

---

*[src/widget/form/chatform.cpp, line 1016 at r2](https://reviewable.io:443/reviews/qtox/qtox/4237#-KejdaNM2sSAgcHIF0_l:-KejdaNM2sSAgcHIF0_m:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/5feecd9cb13e1307a927b56de178184418d4aa49/src/widget/form/chatform.cpp#L1016)):*
> ```cpp
> 
>     for (QString& qt_msg : splittedMsg) {
>         QString qt_msg_hist = qt_msg;
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237)*

**Comment by yurivict** [comment]
CString for some reason also truncates long strings. 1MB string is truncated to ~44k. This probably should be fixed.

**Comment by Diadlo** [comment]
@yurivict It's out of the scope of this PR

**Comment by sudden6** [comment]
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxstring.h, line 33 at r1](https://reviewable.io:443/reviews/qtox/qtox/4237#-KeXxUcNeTrSQ0TZnxCU:-KemWNBPK5VwVCuOe8Ev:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c63c47203e02e707d9c2471ab502986e471ca7f0/src/core/toxstring.h#L33)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

+
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1015 at r2](https://reviewable.io:443/reviews/qtox/qtox/4237#-KejdPcz0X462wg_0YXK:-KemW9jHbYnZLSxyLChA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5feecd9cb13e1307a927b56de178184418d4aa49/src/widget/form/chatform.cpp#L1015)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Please, use camel case (i.e. `qtMsg`)
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1016 at r2](https://reviewable.io:443/reviews/qtox/qtox/4237#-KejdaNM2sSAgcHIF0_l:-KemWAnYhuO05BkJXu8Z:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5feecd9cb13e1307a927b56de178184418d4aa49/src/widget/form/chatform.cpp#L1016)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237)*

**Comment by noavarice** [comment]
Review status: 7 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/core/toxstring.cpp, line 58 at r3](https://reviewable.io:443/reviews/qtox/qtox/4237#-KetGmXRZ_-ohiHOPOOI:-KetGmXRZ_-ohiHOPOOJ:b-mvueqn) ([raw file](https://github.com/qtox/qtox/blob/4e548662d74388281ae072782c09556b17003356/src/core/toxstring.cpp#L58)):*
> ```cpp
> ToxString::ToxString(const uint8_t* text, size_t length)
> {
>     assert(length <= INT_MAX);
> ```

Why just not cut text off?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237#-:-KetnPFef92qhWq7Cjvi:b-jbsf8z)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/core/toxstring.cpp, line 58 at r3](https://reviewable.io:443/reviews/qtox/qtox/4237#-KetGmXRZ_-ohiHOPOOI:-KetrA9QmvJMEK1gASTU:b-5x4o5f) ([raw file](https://github.com/qtox/qtox/blob/4e548662d74388281ae072782c09556b17003356/src/core/toxstring.cpp#L58)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why just not cut text off?
</blockquote></details>

In the current implementation this should never assert, but when something changes I'd rather not alter message contents silently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4237)*

**Comment by Diadlo** [comment]
@sudden6 Merge?

**Pull request merged**
