### PR TITLE
Made clipboard operations work the same on all OSes.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4119)

### CODE REVIEW

**Comment by Diadlo** [comment]
Please, update commit message to satisfy [format](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format)

**Comment by Diadlo** [comment]
IIRC, it's Xorg feature, not Linux or UNIX. May be better add X11_FOUND and use it here?

**Comment by yurivict** [comment]
I think these ifdefs should be deleted. Qt programs are supposed to work the same way on all OSes. Shortcuts, clipboard should all work the same way. All such OS differences are supposed to be handled by Qt.

Would you like me to update the commit and delete these ifdefs?

**Comment by zetok** [comment]
>Would you like me to update the commit and delete these ifdefs?

If you are sure that it will not break things on windows, there's no reason to not delete them.

**Comment by sudden6** [comment]
apparently this is even a default shortcut on windows, didn't know

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4119#-:-Kc5A5JBytydc11IfZp6:b-ayz9ie)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4119#-:-KcCYtrb2r4BfRYjRDcp:b-jbsf8z)*

**Pull request merged**
