### PR TITLE
Rework README.md

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by tux3** [comment]
It looks good! 

Maybe we could emphasize the downloads more, though. They are a bit small compared to the bold links just above and the Screenshots title just below.

ss012

**Comment by zetok** [comment]
**_bold, bold everywhere**_

@tux3 is this how it should look?

**Comment by tux3** [comment]
Lots of bold (too much bold?), but at least the downloads stick out a little.

Looks ok to me.

**Comment by zetok** [comment]
I think that `Screenshots` can be made to be smaller..?

**Comment by tux3** [comment]
But then it's inconsistent with `<h2>Features</h2>`

**Comment by zetok** [comment]
Consistent now :3

**Comment by ghost** [comment]
Repo description says "_Powerful Tox client that follows the Tox design guidelines_". Shouldn't README.md remove the _tries_ from "_tries to follow_"?

**Comment by tux3** [comment]
@kehugter done.

**Pull request merged**
