### PR TITLE
fix(name): Clear alias on name change so that name changes are visible

### PR DESCRIPTION
**Pull request by anthonybilinski**
Temporary work around for #5013

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5015)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
@tox-user does this seem like enough to work-around #5013 for the 1.14.1 release, while a more complete solution remembering if the alias was set by the user or automatically, and possibly having a way to view both the actual username and the alias together for 1.15?

@sudden6 do you think this is reasonable and doesn't hurt your recent alias + name major change?

**Comment by sudden6** [comment]
I'm still not really in favor of permanently deleting the aliases, but I don't have a better solution, so I can live with that. I don't think it will conflict with my other changes.

**Comment by Diadlo** [comment]
Maybe remove alias if it's equal to current username?

**Comment by anthonybilinski** [comment]
I think that's a good idea, updated behaviour. Now the alias will be cleared on name change only if old name is equal to alias. This will fix all the cases of auto-set alias to name changes, so that name changes will remain visible. If a manual alias is set (as long as it never conflicts with the name), it will remain set through name change.

**Comment by sudden6** [comment]
else :lgtm_strong: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/friend.cpp, line 55 at r1](https://reviewable.io:443/reviews/qtox/qtox/5015#-L7vW4bpMKeAC8RMXnsy:-L7vW4bqody0LuV_MhSW:bczityj) ([raw file](https://github.com/qtox/qtox/blob/fa71e6057302bc354ec7adead5a6b5a62e025bb4/src/model/friend.cpp#L55)):*
> ```cpp
>     // save old displayed name to be able to compare for changes
>     const auto oldDisplayed = getDisplayedName();
>     if (userName == userAlias) {
> ```

maybe add a TODO that this is a workaround

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/5015#-:-L7vWAAQZgPfqvDZKdQN:ba3ovo0)*

**Comment by tox-user** [comment]
@anthonybilinski
>This will fix all the cases of auto-set alias to name changes

Not for people using 1.14.0, whose friends changed their name after updating to 1.14.0. Those people will have a different alias set than their friend's name.

**Comment by tox-user** [comment]
This solution is not enough. Most people don't update qTox with every release, so it will not fix the problem for many people, who stayed on 1.14.0 for some amount of time. We should try to fix the problem for everyone. The original solution was better.

With this change the alias will most likely break when:
1. A friend with no alias, with user name XYZ changes their name to XYY.
2. We notice it and set their alias (for the first time) to XYZ, which is their previous name.
3. After some time they change their name back to XYZ.
4. Their alias will reset. This is because their userName is now equal to userAlias.

**Comment by anthonybilinski** [comment]
Toxed with tox-user, going to summarize our chat to explain decision to keep using the current implementation for 1.14.1:
>Not for people using 1.14.0, whose friends changed their name after updating to 1.14.0. Those people will have a different alias set than their friend's name.

Yes, true. These people will have alias set and not see name changes, like the behaviour on 1.14.0
>With this change the alias will most likely break when

Yes, true again. This solution is more of an alternative to resetting on every name change, but it still sometimes does reset when it doesn't need to, since it doesn't add any versioning to alias to know if it was set pre or post 1.14.0.

The way I view it is that here there are corner cases that break aliases for people who updated from 1.13.0 to 1.14.1 (their alias can be wiped by their friend changing name to match their alias) and there are corner cases that break names for people who updated from 1.14.0 to 1.14.1 (their alias could not match the name of their friend if their friend changed names while they were on 1.14.0, in which case their alias will not be cleared). To me, these two rare cases are less bad than the case of always resetting alias on every name change. In @tox-user's view keeping 1.13.0 behaviour of always resetting alias would be better.

In either case, both cases will fixed when we add proper persistent versioning of alias (i.e. was it set automatically or manually set) in 1.15.0, which should cover all cases better.

**Pull request merged**
