### PR TITLE
style: adjust function arg names in header to changes in core.cpp

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3984)

### CODE REVIEW

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3984#-:-KZJTXb9DRx5nzKGXXoh:bnfp4nl)*

**Comment by Diadlo** [comment]
https://github.com/qTox/qTox/blob/master/src/core/corefile.cpp#L306
https://github.com/qTox/qTox/blob/master/src/core/corefile.cpp#L453

**Comment by zetok** [comment]
@Diadlo done.

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3984#-:-KZKhJq0oS3g_lyeCNUH:bnfp4nl)*

**Pull request merged**
