### PR TITLE
Keyboard shortcut to change current chat

### PR DESCRIPTION
**Pull request by agilob**
This feature it no finished as I don't know how to get current/next/previous widget/friend from friendlistwidget and set it as current chat widget. 

If anyone know, please write it here or commit.

### CODE REVIEW

**Comment by zetok** [comment]
Where is documentation?

**Comment by zetok** [comment]
Why are you overriding default keys that already have their use in qTox?

**Comment by agilob** [comment]
Changed to ctrl+page up/down, those keys were set for testing only.

**Comment by dubslow** [comment]
Maybe Ctrl+Tab/Ctrl+Shift+Tab too, à la browsers?

**Comment by agilob** [comment]
@dubslow Discussion here https://github.com/tux3/qTox/issues/1019

**Comment by redsteakraw** [comment]
I am just going to add keyboard shortcuts aid the accessibility of the application so they are important regardless of the finer details.

**Comment by tux3** [comment]
What's the rationale/meaning behind CTRL+SHIFT+L to clear the chat ? Is "L" the start of some word in particular ? Anyways I agree that we should document those shortcuts somewhere.

**Comment by agilob** [comment]
Afair, in gajim and piding you can clear the chat with ctrl+l / ctrl+shift+L

documentation, as @zetok requested is [here](https://github.com/tux3/qTox/wiki/Keyboard-shortcuts), [discussion is here](https://github.com/tux3/qTox/issues/1019)

**Comment by tux3** [comment]
Thanks. I merged it for the clear chat area shortcut, because I think implementing the previous/next contact may take some time, you can send a PR when you think it's ready or for further discussion if you want.

**Comment by TheLastProject** [comment]
Am I correct in thinking Ctrl+PageUp and Ctrl+PageDown should switch contact in my friend list now? Because, well, they don't do anything for me.

**Comment by agilob** [comment]
No, they shouldn't as I didn't get any answer how to get position of current friendwidget from friendwidgetlist. I spent over 3hours trying to get it, no results, it will be easier when the list is sorted. If anyone knows how to get current/next friendwidget from friendwidgetlist, let me know.

**Pull request merged**
