### PR TITLE
Style for comobobox in friendlist panel

### PR DESCRIPTION
**Pull request by agilob**
It looks like qlineedit which is on left side of the combobox.

### CODE REVIEW

**Comment by tux3** [comment]
It looks great, except that "Friends" and "Groups" don't fit in the combobox anymore.

ss024

**Comment by agilob** [comment]
oh

**Comment by SkyzohKey** [comment]
We got this in Micro$hit Windows 8.1
screen

**Comment by agilob** [comment]
qtox
That's better, it should be 50/50 now.

Combobox will have arrow-down there when dark theme branch is merged, the branch has nice arrow down icon.

@FishTFM is that screenshot from my branch? oO
Wow your font rendering is so ugly :<

**Pull request merged**
