### PR TITLE
chore(cmake): Add gzip svg icon on install

### LINKED ISSUE #4582: Icon qtox.svg should be installed in compressed form
It currently installs ```share/icons/hicolor/scalable/apps/qtox.svg```. The FreeBSD port has to run ```gzip -Sz qtox.svg``` to convert it to ```qtox.svgz```. It would be nice if cmake did this automatically during install.

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4582

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4585)

### CODE REVIEW

**Comment by Diadlo** [comment]
@yurivict Can you test it?

**Comment by yurivict** [comment]
@Diadlo It works fine. Thanks!

**Comment by Diadlo** [comment]
@zetok Can you review it?

**Comment by Talkless** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/gzip.sh, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4585#-KuPw6XUKltElPnHHu60:-KuPw6XUKltElPnHHu61:biyqo7v) ([raw file](https://github.com/qtox/qtox/blob/cd8a7ad9c61a9ceee1a71ef3da8c635b56de083a/tools/gzip.sh#L1)):*
> ```Shell
> #!/bin/sh
> ```

Looks like `#!/usr/bin/env bash` is prevalent in other qTox scripts. 

---

*[tools/gzip.sh, line 3 at r1](https://reviewable.io:443/reviews/qtox/qtox/4585#-KuPwO6k954rlq91Z-vG:-KuPwO6ll_dkvmtRYXnJ:b-nhi6dv) ([raw file](https://github.com/qtox/qtox/blob/cd8a7ad9c61a9ceee1a71ef3da8c635b56de083a/tools/gzip.sh#L3)):*
> ```Shell
> #!/bin/sh
> 
> gzip -Sz < $1 > $2
> ```

`"$1"` and `"$2"` (quotes) if `SVG_SRC` and/or `SVG_GZIP` would happen to have spaces in paths.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4585)*

**Comment by Talkless** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4585)*

**Comment by yurivict** [comment]
> Looks like #!/usr/bin/env bash is prevalent in other qTox scripts.

@Talkless /bin/sh should be preferred when possible, Bash scripting shouldn't be used when not needed because bash is an extra dependency on some platform.

Bash should absolutely not be a requirement for qtox to build.

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[tools/gzip.sh, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4585#-KuPw6XUKltElPnHHu60:-KuQE8QRDtlY97vDcjtL:b32w0x) ([raw file](https://github.com/qtox/qtox/blob/cd8a7ad9c61a9ceee1a71ef3da8c635b56de083a/tools/gzip.sh#L1)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Looks like `#!/usr/bin/env bash` is prevalent in other qTox scripts. 
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4585)*

**Comment by zetok** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/Installation.cmake, line 51 at r1](https://reviewable.io:443/reviews/qtox/qtox/4585#-KuR6evMvSRxT7Q7C8Y5:-KuR6evMvSRxT7Q7C8Y6:b-joh74u) ([raw file](https://github.com/qtox/qtox/blob/cd8a7ad9c61a9ceee1a71ef3da8c635b56de083a/cmake/Installation.cmake#L51)):*
> ```CMake
>   set(GZIP_TOOL ${CMAKE_SOURCE_DIR}/tools/gzip.sh)
>   install(CODE "
>   execute_process(COMMAND ${GZIP_TOOL} ${SVG_SRC} ${SVG_GZIP})
> ```

Instead of calling gzip via script, why not just call it directly?

```cmake
execute_process(COMMAND gzip -Sz INPUT_FILE ${SVG_SRC} OUTPUT_FILE ${SVG_GZIP})
```

Dunno if cmake vars need to be put in between quotes.

With cmake calling gzip, you could just install files like before 

```cmake
INSTALL(FILES ${SVG_GZIP} DESTINATION "share/icons/hicolor/scalable/apps")
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4585)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[cmake/Installation.cmake, line 51 at r1](https://reviewable.io:443/reviews/qtox/qtox/4585#-KuR6evMvSRxT7Q7C8Y5:-KuzNkrRseZeAni0YbQX:b-3w9b86) ([raw file](https://github.com/qtox/qtox/blob/cd8a7ad9c61a9ceee1a71ef3da8c635b56de083a/cmake/Installation.cmake#L51)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Instead of calling gzip via script, why not just call it directly?

```cmake
execute_process(COMMAND gzip -Sz INPUT_FILE ${SVG_SRC} OUTPUT_FILE ${SVG_GZIP})
```

Dunno if cmake vars need to be put in between quotes.

With cmake calling gzip, you could just install files like before 

```cmake
INSTALL(FILES ${SVG_GZIP} DESTINATION "share/icons/hicolor/scalable/apps")
```
</blockquote></details>

Thanks, didn't knew about `INPUT_FILE` and `OUTPUT_FILE`
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4585)*

**Comment by Diadlo** [comment]
@zetok ping

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4585#-:-KxTs6QvKxw9wGfdyB5C:b-jbsf8z)*

**Pull request merged**
