### PR TITLE
chore: Make the windows code compatible with TCHAR.

### PR DESCRIPTION
**Pull request by iphydf**
This adds support for non-unicode builds.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3635)

### CODE REVIEW

**Comment by iphydf** [comment]
Note to reviewer: please check this carefully.

**Comment by zetok** [comment]
There's missing info why would it be needed, along with the comment above the code.

**Comment by iphydf** [comment]
Added info in commit message and comment to code.

**Comment by Diadlo** [comment]
Can you use 72-char width of commit message?

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3635#-:-KQNATaTgsmMYlwqZcap:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3635#-:-KQvbw5IGuAV3Am_HYZb:bnfp4nl)_

**Pull request merged**
