### PR TITLE
v1.17.3

### LINKED ISSUE #6252: Not Working on Macos Big Sur 11.0.1 (20B29)
It will stop responding second after i open it.

### PR DESCRIPTION
**Pull request by anthonybilinski**
This includes the fix for MacOS Big Sur, as well as needed fixes for deprecated APIs and build system fixes to build the release, plus all needed release commits. Once this is merged, v1.17.3 will be tagged on the last commit.

Fix #6252

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6257)

### CODE REVIEW

**Comment by sudden6** [comment]
Other important commits:

https://github.com/qTox/qTox/commit/78d132b423a4c76d883189f0a743592078f360a1
https://github.com/qTox/qTox/commit/b0f37063e7703ac87843a2e7f2c662b9bbe0861c
https://github.com/qTox/qTox/commit/2ebf51b5b77184efefe3d02469748d67427c8d63
https://github.com/qTox/qTox/commit/6a21d962141bd6dc7a6b051d20c7dbda471685a9
https://github.com/qTox/qTox/commit/6105af8279b609107f5116b0ac5039b8dbcd17b8
https://github.com/qTox/qTox/commit/82547263f815c2acd1ad5ad4e31019be196d1f2c

I picked those, because they fix something and are self contained. https://github.com/qTox/qTox/commit/b0f37063e7703ac87843a2e7f2c662b9bbe0861c is debatable, since it's not even really tested on master.

The list of your commits seem fine to me.

**Comment by powerjungle** [comment]
>b0f3706 is debatable, since it's not even really tested on master.

Yeah there's no urgent need for that one. My idea for the function is so that it can later be used in the GUI as well to warn the user.

EDIT: Although it would be nice for at least 5a46d3c2 to be included so that the translations work properly.

**Comment by sudden6** [comment]
@powerjungle I'm not 100% sure 5a46d3c can be applied without issues, because the master branch diverged quite a bit from v1.17-dev, but if it's applying cleanly it might be a good idea.

**Comment by anthonybilinski** [comment]
Updated. A couple small cleanups, like using `git cherry-pick -x` for all the backported changes, and reordering all of my changes to after all the backports.

I included:
78d132b
2ebf51b
6a21d96
8254726

From the recommendation, I left out:
b0f3706 - since it's new and not urgent.
6105af8 - since it presents to a user more as a UX change than a bug fix, e.g. now Windows users used to opening multiple profiles would need to use `-l` command line argument.
5a46d3c - didn't apply cleanly.

Including 6a21d96 required pulling in a few other apparmor changes, but those are good to have anyway.

All backports applied with no conflicts. The source of the commits in order (first item is tip):

````
<6 new commits>
0ef8a6f4e1742f1fb0fe338879152e364ac30a53
7d70566853d466dd4b1f4ef3f6d6e01e639914c9
6a9914c233692391dcac9ffadc45b1b0ccc00c1c
958a6e4753789ad1e5a04951dcce34c0b5513ca6
02520a4af6eb42ed588a7be0178eb8e9c27818ed
87c0e8f6388ed5a630ea35ec3b74fb6427077f40
94468b5e277846014d2ba83e3a1156409c347dce
eb2ae9d84d47eb6a5198f308007330e910821485
78d132b423a4c76d883189f0a743592078f360a1
45fb02d9df045ecd4eece6ad17375ddd4f40584e
72646d629cd9cfccc9832cb060d163e7826e970e
d7ed01a9db9c31d5d2da5bab83d1f8e138cd3eac
2944dc6327cdc79d1630756dff314d5ecea6acfd
03092856ffc56db0941179ef78d900a8053a106f
6bc6f5796e654d99d2d49fc8f3db600641b0e971
7edec51a4913431935beef0155ca1da2180d705c
2be144515e33f666712cdd2f6f6a4075bf74846f
7dc7174bd747d1684a8d1de30fba615c89f6bd50
812207782f34cd6cdbc6fc6e5be5503e5abf42dc
dde3ac941658f9b2fba6ff41c79bf90b5a6e3697
f53e9e2a3d2b6943297a12f070a5d1644462a867
9757f4fb82376453bd867d5994fddfbc84246681
e3d25857de90895a9e0769d41c0cb039bf276fc5
6c3a9bb7b896a9ab8278e641eb0895ff312f1974
63b338f269b6180700e685d41f4815a2d7a8e8da
0b1f6dff6ff1281f4717ce68c1189581986157d1
f913aed286ec34526d5df22f83690248635b1b37
886397f57460ba386d94186f6675c0702ad32e76
f9f734c903124245b1d2bdeadbd1155c02d06e83
6a21d962141bd6dc7a6b051d20c7dbda471685a9
2ebf51b5b77184efefe3d02469748d67427c8d63
82547263f815c2acd1ad5ad4e31019be196d1f2c
2d2dfadf2d21ede7c5c6c0286a0fdf2d7eaa9176
fa86413b1b5b72215e7c90002f6e582284bdda6d
a01d31445f403b73ec9a15655e24e0993b0ec097
2d22a76ed32f2faa822a5bc81668e2c0c45f6fe8
684068c9b48eb286596b27aa60f06c5847698eb6

**Comment by powerjungle** [comment]
I did a compile test in anthonybilinski:fix_osx_build and it seems that 5a46d3c wasn't even needed because the translations work well there. The issue I'm having is friends being transparent:

Screenshot 2020-11-23 085249

**Comment by anthonybilinski** [comment]
Hm strange, I can't reproduce that locally while also changing the language: 
image

Do you see the same thing on the last release, v1.17.2? Do you have to do anything special to cause this problem, or is it like this right on start?

**Comment by powerjungle** [comment]
>Do you see the same thing on the last release, v1.17.2?

Yes, but the master doesn't have this problem.

>Do you have to do anything special to cause this problem, or is it like this right on start?

No, nothing special, it just starts like that.

I'm running 5.8.18-1-MANJARO, on Xfce 4.14.

EDIT: When running v1.17.2 on windows it doesn't have this problem, so it seems to be something related to the distro.

EDIT 2: Also on the distro it's using "Qt version: 5.15.1", while on windows it's "Qt версия: 5.12.8", could that be the reason?

**Comment by anthonybilinski** [comment]
I can't think of what would cause that or why it's dependent on a mix of OS + qTox version. Qt would make sense, but I see it working on macOS 11.0 which is using Qt 5.15.1 as well:
image

Since it's not a regression from v1.17.2, I don't think we should delay the release to investigate since MacOS 11.0 currently can't even start qTox without this release. If the issue is fixed on master, it should be resolved in v1.18.0 without further investigation.

**Comment by powerjungle** [comment]
>I don't think we should delay the release to investigate

Yeah, this seems like a weird hiccup from my setup.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: 

> Reviewed 9 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, 7 of 10 files at r4, 3 of 3 files at r5, 3 of 5 files at r7, 2 of 2 files at r8, 1 of 3 files at r9, 12 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6257#-:-MMoe64EA1mSgNJIM2VQ:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
