### PR TITLE
Allow making main window smaller

### LINKED ISSUE #867: Minimum window size is too large
I can't fit qTox into one corner/quarter of my laptop screen...

### PR DESCRIPTION
**Pull request by agilob**
by hiding list of contacts when width of the windows is equal minimum size, set minimum size to 540

somehow fixes #867 @dubslow ?
qtoxmin2

### CODE REVIEW

**Comment by dcharles525** [comment]
could also help out with #1288!

**Comment by agilob** [comment]
I had this in mind ;)

**Comment by zetok** [comment]
> by hiding list of contacts

No.
IMHO it should be done properly, i.e. #383

**Comment by tux3** [comment]
I'm not convinced this is great from a usability PoV. I can already see the confused users wondering where their contact list is gone, or making it disappear by accident. It isn't really a common thing.

**Comment by Zer0-One** [comment]
I agree with @zetok in that this should be implemented as described in #383 . As-is, this might just end up confusing people, and might be annoying for people trying to resize the window to fit a particular desktop layout (could be wrong about this, haven't tested this for myself).

**Pull request closed without merging**
