### PR TITLE
Add open directory option to completed file transfers

### PR DESCRIPTION
**Pull request by TheLastProject**
This adds a button to open the directory a file was saved in on a completed file transfer.
opendirectory

As usual, I understand if this code has imperfections that make you prefer to do it yourself, but it's still useful for me as a learning experience and hopefully to point you to an easy way to add this functionality :)

dir.svg in modified directly from browse.svg.

### CODE REVIEW

**Comment by TheLastProject** [comment]
Oh yeah, this was kinda meant as a fix to #1165, which got closed because a related issue got resolved, but no "Open directory" option was added.

**Comment by dubslow** [comment]
`QString dirPath = QDir(fileInfo.filePath).path();`

**Comment by TheLastProject** [comment]
I just tried that, but that causes it to open the actual file instead of the directory it's in. Are you sure that command is correct?

**Comment by suhr** [comment]
Not sure if it should look so.
cast @ItsDuke

**Comment by ProMcTagonist** [comment]
Preexisting -

open folder

The icon in the original post looks like an inbox to me.

**Comment by TheLastProject** [comment]
I have absolutely no issue with changing the icon if someone can find a nice, sanely-licensed SVG for it. I just felt that editing browse.svg was easier to have something for the time being, and it looked well enough to me to be useable.

**Comment by dubslow** [comment]
What about
`QString dirPath = QString(QFileInfo(fileInfo.filePath).dir());`

**Comment by TheLastProject** [comment]
Sorry, but nope, that doesn't even compile:

```
$ make
g++ -c -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIE -DGIT_VERSION="\"4edb6087775edf18f4f7233d4eed91c759c30c19\"" -DTIMESTAMP=1424206095 -DLOG_TO_FILE -DQTOX_PLATFORM_EXT -DQTOX_FILTER_AUDIO -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SQL_LIB -DQT_CORE_LIB -I/usr/lib64/qt5/mkspecs/linux-g++ -I. -Ilibs/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore -I. -I. -o filetransferwidget.o src/chatlog/content/filetransferwidget.cpp
src/chatlog/content/filetransferwidget.cpp: In member function ‘void FileTransferWidget::handleButton(QPushButton*)’:
src/chatlog/content/filetransferwidget.cpp:437:69: error: no matching function for call to ‘QString::QString(QDir)’
         QString dirPath = QString(QFileInfo(fileInfo.filePath).dir());
                                                                     ^
src/chatlog/content/filetransferwidget.cpp:437:69: note: candidates are:
In file included from /usr/include/qt5/QtCore/qobject.h:41:0,
                 from /usr/include/qt5/QtWidgets/qwidget.h:38,
                 from /usr/include/qt5/QtWidgets/QWidget:1,
                 from src/chatlog/content/filetransferwidget.h:20,
                 from src/chatlog/content/filetransferwidget.cpp:17:
/usr/include/qt5/QtCore/qstring.h:709:29: note: constexpr QString::QString(QStringDataPtr)
     Q_DECL_CONSTEXPR inline QString(QStringDataPtr dd) : d(dd.ptr) {}
                             ^
/usr/include/qt5/QtCore/qstring.h:709:29: note:   no known conversion for argument 1 from ‘QDir’ to ‘QStringDataPtr’
/usr/include/qt5/QtCore/qstring.h:708:5: note: QString::QString(int, Qt::Initialization)
     QString(int size, Qt::Initialization);
     ^
/usr/include/qt5/QtCore/qstring.h:708:5: note:   candidate expects 2 arguments, 1 provided
/usr/include/qt5/QtCore/qstring.h:700:12: note: QString::QString(const QString::Null&)
     inline QString(const Null &): d(Data::sharedNull()) {}
            ^
/usr/include/qt5/QtCore/qstring.h:700:12: note:   no known conversion for argument 1 from ‘QDir’ to ‘const QString::Null&’
/usr/include/qt5/QtCore/qstring.h:603:31: note: QString::QString(const QByteArray&)
     inline QT_ASCII_CAST_WARN QString(const QByteArray &a)
                               ^
/usr/include/qt5/QtCore/qstring.h:603:31: note:   no known conversion for argument 1 from ‘QDir’ to ‘const QByteArray&’
/usr/include/qt5/QtCore/qstring.h:600:31: note: QString::QString(const char*)
     inline QT_ASCII_CAST_WARN QString(const char *ch)
                               ^
/usr/include/qt5/QtCore/qstring.h:600:31: note:   no known conversion for argument 1 from ‘QDir’ to ‘const char*’
/usr/include/qt5/QtCore/qstring.h:220:12: note: QString::QString(QString&&)
     inline QString(QString && other) : d(other.d) { other.d = Data::sharedNull(); }
            ^
/usr/include/qt5/QtCore/qstring.h:220:12: note:   no known conversion for argument 1 from ‘QDir’ to ‘QString&&’
/usr/include/qt5/QtCore/qstring.h:811:8: note: QString::QString(const QString&)
 inline QString::QString(const QString &other) : d(other.d)
        ^
/usr/include/qt5/QtCore/qstring.h:811:8: note:   no known conversion for argument 1 from ‘QDir’ to ‘const QString&’
/usr/include/qt5/QtCore/qstring.h:780:8: note: QString::QString(QLatin1String)
 inline QString::QString(QLatin1String aLatin1) : d(fromLatin1_helper(aLatin1.latin1(), aLatin1.size()))
        ^
/usr/include/qt5/QtCore/qstring.h:780:8: note:   no known conversion for argument 1 from ‘QDir’ to ‘QLatin1String’
/usr/include/qt5/QtCore/qstring.h:212:5: note: QString::QString(int, QChar)
     QString(int size, QChar c);
     ^
/usr/include/qt5/QtCore/qstring.h:212:5: note:   candidate expects 2 arguments, 1 provided
/usr/include/qt5/QtCore/qstring.h:211:5: note: QString::QString(QChar)
     QString(QChar c);
     ^
/usr/include/qt5/QtCore/qstring.h:211:5: note:   no known conversion for argument 1 from ‘QDir’ to ‘QChar’
/usr/include/qt5/QtCore/qstring.h:210:14: note: QString::QString(const QChar*, int)
     explicit QString(const QChar *unicode, int size = -1);
              ^
/usr/include/qt5/QtCore/qstring.h:210:14: note:   no known conversion for argument 1 from ‘QDir’ to ‘const QChar*’
/usr/include/qt5/QtCore/qstring.h:991:8: note: QString::QString()
 inline QString::QString() : d(Data::sharedNull()) {}
        ^
/usr/include/qt5/QtCore/qstring.h:991:8: note:   candidate expects 0 arguments, 1 provided
Makefile:2889: recipe for target 'filetransferwidget.o' failed
make: *** [filetransferwidget.o] Error 1
```

**Comment by TheLastProject** [comment]
@dubslow `QString dirPath = QDir(QFileInfo(fileInfo.filePath).dir()).path();` works. Would you be happy with that?

**Comment by dubslow** [comment]
The `dir()` method returns a QDir object, so you needn't wrap it in a QDir() constructor. QDir objects can't be converted directly to QStrings, which is why the previous didn't compile, but now I'm wondering why `QFileInfo(fileInfo.filePath).dir().path()` works where `QDir(fileInfo.filePath).path()` didn't. Oh well. As long as it's not manual operations on the file path I'm happy.

**Pull request merged**
