### PR TITLE
fix audio device initialization

### LINKED ISSUE #2727: Crash after hitting audiocall or videocall
On Arch Linux.

I get:
[16:40:00.182] ../src/audio/audio.cpp:468 : Debug: Opening audio output "none"
[16:40:04.451] ../src/widget/form/chatform.cpp:468 : Debug: onVideoCallTriggered
[16:40:04.451] ../src/widget/form/chatform.cpp:511 : Debug: disableCallButtons
[16:40:04.454] ../src/core/coreav.cpp:177 : Debug: "Starting call with 0"
[16:40:04.454] ../src/audio/audio.cpp:411 : Debug: Opening audio input "none"
[16:40:04.454] ../src/audio/audio.cpp:388 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[16:40:04.454] ../src/audio/audio.cpp:468 : Debug: Opening audio output "none"
qtox: ../src/audio/audio.cpp:752: void Audio::subscribeOutput(Audio::SID&): Assertion `sid' failed.
[1]    18370 abort (core dumped)  qtox

Solution:
Change the setting in capture devices to another then none it works.

### PR DESCRIPTION
**Pull request by antis81**
If no audio device is selected (specifier == "none"), the initalization routines falsely reported, that initialization was successful.

Closes #2727

@ovalseven8 @zetok Please verify this works.

### CODE REVIEW

**Comment by zetok** [comment]
Fixes #2727 for me.

**Comment by antis81** [comment]
@zetok If it fixes it for you, it's actually fixed. Feel free to merge, I'll remove the _needstest_ label. :)

**Comment by zetok** [comment]
Hmm, actually, while problem is fixed, fix introduces spam in log:

```
[14:59:46.840] src/audio/audio.cpp:437 : Debug: Opening audio output "none"
[14:59:46.840] src/audio/audio.cpp:441 : Warning: No audio output device selected.
[14:59:46.840] src/audio/audio.cpp:694 : Warning: Failed to subscribe to audio output device.
```

↑ those 3 messages are spammed hundreds of times per second when qTox is in "call".

↓ 1 minute long "call" results in:

```
$ ./qTox/qtox -p _3 &>> qTox/testlog
$ du -h qTox/testlog
776K    qTox/testlog
$ wc -l qTox/testlog
9372 qTox/testlog
```

Given that `qtox.log` is being saved in `~/.config/tox/` I think that it should be fixed before merging.

**Comment by antis81** [comment]
@zetok Problem solved. However, it shouldn't be even possible to start an audio call without both in/out devices initialized, don't you think?

**Comment by zetok** [comment]
> However, it shouldn't be even possible to start an audio call without both in/out devices initialized, don't you think?

I think that user should be notified (some warning message) about qTox not using a real device, but should be allowed to make a call. Given how things should work, qTox should be able to start using audio device, or change it in the middle of a call, so that even if user starts a call without valid audio devices, they could select them without ending the call.

**Comment by zetok** [comment]
With 11fccc811ea35ba74f9357b19c086ec812340e0c I still get lots of spam in stdout - not sure if that matters, but I've tested this PR by merging it locally on top of newest master.

**Comment by antis81** [comment]
@tux3 Please do a short review and merge.

**Comment by tux3** [comment]
> However, it shouldn't be even possible to start an audio call without both in/out devices initialized, don't you think?

I think it should be possible! Even if you don't have a mic you want to be able to listen to the call and answer via text, especially in group calls.

I haven't had the time to test this yet, but if there's a lot of spam on stdout it needs to be fixed because that gets written to a log file and we don't currently have limits on its size..

**Comment by zetok** [comment]
> Even if you don't have a mic you want to be able to listen to the call and answer via text, especially in group calls.

Well, the crash didn't happen because there was no input device, but because there was no output device.

**Comment by tux3** [comment]
It might be a bit silly, but I'd rather not have this sort of strange technical restrictions around. Of course it makes little sense for a user to start a call without an output device, so we should at least warn about that, but I'm not convinced it makes sense to outright forbid it.
I could see some (somewhat convoluted) use cases like someone, user or bot, who wants to stream music and doesn't need an output device.

**Comment by antis81** [comment]
> Well, the crash didn't happen because there was no input device, but because there was no output device.

That doesn't matter. To successfully setup a call, you need both a valid input & output device. Otherwise a call is not possible.

@tux3 We (actually I) need a code review for #2768 from somebody, who understands our "Audio" concept, before talking about new features. IOW: From the "audio view point", this currently has highest prio to make audio calls really usable. Btw.: Do we have some kind of (milestone) plan with concepts we like to provide in next release? If not, I think the time has come to establish one, which allows us to lead users and create "trust in stability". Further I think this helps to introduce interested developers, making them chose "their" topic. If you like we can also tox about that (`C52DA9FE98B86AF01178CB605DA2585919B2BA72DF1968B97932DE7155EC354320A65105E357`). :smile:

**Comment by tux3** [comment]
@antis81 

> We (actually I) need a code review for #2768 from somebody, who understands our "Audio" concept, before talking about new features. IOW: From the "audio view point", this currently has highest prio to make audio calls really usable.

I was sort of hoping you would take care of maintaining the audio code since you rewrote a large part of it, but sure I can review it so far. It would be great to get things working reliably at this point, so I'll be happy to review.

> Btw.: Do we have some kind of (milestone) plan with concepts we like to provide in next release? If not, I think the time has come to establish one, which allows us to lead users and create "trust in stability". Further I think this helps to introduce interested developers, making them chose "their" topic

The next point on the roadmap is still stabilizing the "stable" branch, we need to address all outstanding reliability issues before implementing the next big shiny features. 
The new database was merged and has eliminated tons of reliability problems with the chat history, this part I now consider stable. Next would be the audio code, I think it's a harder problem because of all the issues with buggy drivers and libraries (and this is nothing compared to the video drivers!), but it ought to be coming along by now and I hope to have it merged pretty soon.
We should make a release once the new audio code is stable and move on to addressing the next biggest stability issues.

> If you like we can also tox about that (C52DA9FE98B86AF01178CB605DA2585919B2BA72DF1968B97932DE7155EC354320A65105E357). :smile:

Sure, I added you. I'm tux3@toxme.io.

**Comment by agilob** [comment]
@tux3 could we make a version release once this is merged? On some systems like FBSD qtox got stuck on 1.2.2 and there was no update since than. This versions has buggy tray icon, I would suggest doing a "patch release" every ~2weeks? -> 1.2.3 will be next one.

**Comment by antis81** [comment]
This PR is actually ready to merge.

**Comment by zetok** [comment]
@antis81 but spam is still there?

Additionally, there's a segfault when quitting qTox during a call:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff22cff06 in _int_free (av=0x7ffff25f3b80 <main_arena>, p=0x555555fad150, 
    have_lock=0) at malloc.c:3978
3978    malloc.c: No such file or directory.
(gdb) bt
#0  0x00007ffff22cff06 in _int_free (av=0x7ffff25f3b80 <main_arena>, 
    p=0x555555fad150, have_lock=0) at malloc.c:3978
#1  0x00007ffff33e5989 in QHashData::free_helper (this=0x555555da1a00, 
    node_delete=0x7ffff3a96580 <QHash<QString, QPixmapCache::Key>::deleteNode2(QHashData::Node*)>) at tools/qhash.cpp:493
#2  0x00007ffff3a95ed4 in QHash<QString, QPixmapCache::Key>::freeData (
    this=<optimized out>, x=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qhash.h:581
#3  QHash<QString, QPixmapCache::Key>::~QHash (
    this=0x7ffff3e67f48 <(anonymous namespace)::Q_QGS_pm_cache::innerFunction()::holder+72>, __in_chrg=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qhash.h:302
#4  QPMCache::~QPMCache (
    this=0x7ffff3e67f00 <(anonymous namespace)::Q_QGS_pm_cache::innerFunction()::holder>, __in_chrg=<optimized out>) at image/qpixmapcache.cpp:211
#5  0x00007ffff3a9603c in (anonymous namespace)::Q_QGS_pm_cache::innerFunction()::Holder::~Holder() () at image/qpixmapcache.cpp:440
#6  0x00007ffff2289ef0 in __run_exit_handlers (status=0, 
    listp=0x7ffff25f3618 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#7  0x00007ffff2289f50 in __GI_exit (status=<optimized out>) at exit.c:104
#8  0x00007ffff22739eb in __libc_start_main (
    main=0x5555555a56c0 <main(int, char**)>, argc=3, argv=0x7fffffffdd28, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd18) at libc-start.c:331
#9  0x00005555555a6a39 in _start ()
```

Edit: `t a a bt`:

```
(gdb) t a a bt

Thread 18 (Thread 0x7fffa3ffd700 (LWP 8352)):
#0  0x00007ffff2e35610 in __pause_nocancel ()
    at ../sysdeps/unix/syscall-template.S:81
#1  0x00007ffff2e30425 in __pthread_mutex_cond_lock_full (mutex=0x555555fad2f0)
    at ../nptl/pthread_mutex_lock.c:359
#2  0x00007ffff2e31d2f in pthread_cond_wait ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:259
#3  0x00007ffff3386d4b in QWaitConditionPrivate::wait (time=<optimized out>, 
    this=0x555555fad2f0) at thread/qwaitcondition_unix.cpp:136
#4  QWaitCondition::wait (this=<optimized out>, mutex=0x55555753db60, 
    time=time@entry=18446744073709551615) at thread/qwaitcondition_unix.cpp:208
#5  0x0000555555637119 in AudioMeterListener::doListen (this=0x555557551b80)
    at src/audio/audio.cpp:245
#6  0x00007ffff359356d in QtPrivate::QSlotObjectBase::call (a=<optimized out>, 
    r=0x555557551b80, this=0x5555575b7260)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#7  QMetaObject::activate (sender=sender@entry=0x5555575e97d0, 
    signalOffset=<optimized out>, 
    local_signal_index=local_signal_index@entry=32767, argv=0x0, 
    argv@entry=0x5555574da810) at kernel/qobject.cpp:3702
#8  0x00007ffff3594181 in QMetaObject::activate (
    sender=sender@entry=0x5555575e97d0, 
    m=m@entry=0x7ffff37a7d40 <QThread::staticMetaObject>, 
    local_signal_index=32767, local_signal_index@entry=0, argv=0x5555574da810, 
    argv@entry=0x0) at kernel/qobject.cpp:3582
#9  0x00007ffff360cbf5 in QThread::started (this=this@entry=0x5555575e97d0)
    at .moc/moc_qthread.cpp:153
#10 0x00007ffff33864d3 in QThreadPrivate::start (arg=0x5555575e97d0)
    at thread/qthread_unix.cpp:332
#11 0x00007ffff2e2c4bc in start_thread (arg=0x7fffa3ffd700) at pthread_create.c:333
#12 0x00007ffff234520d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 10 (Thread 0x7fffbd757700 (LWP 8019)):
#0  0x00007ffff233b7bd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fffeb6409e5 in g_main_context_poll (priority=2147483647, n_fds=1, 
    fds=0x7fffac002e50, timeout=-1, context=0x7fffac000990)
    at /var/tmp/portage/dev-libs/glib-2.44.1-r1/work/glib-2.44.1/glib/gmain.c:4103
#2  g_main_context_iterate (context=context@entry=0x7fffac000990, 
    block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at /var/tmp/portage/dev-libs/glib-2.44.1-r1/work/glib-2.44.1/glib/gmain.c:3803
#3  0x00007fffeb640b22 in g_main_context_iteration (context=0x7fffac000990, 
    may_block=1)
    at /var/tmp/portage/dev-libs/glib-2.44.1-r1/work/glib-2.44.1/glib/gmain.c:3869
#4  0x00007ffff35bd8ac in QEventDispatcherGlib::processEvents (this=
    0x7fffac0008c0, flags=...) at kernel/qeventdispatcher_glib.cpp:418
#5  0x00007ffff355ea13 in QEventLoop::exec (this=this@entry=0x7fffbd756d60, 
    flags=..., flags@entry=...) at kernel/qeventloop.cpp:204
#6  0x00007ffff33805cc in QThread::exec (this=<optimized out>)
    at thread/qthread.cpp:503
#7  0x00007ffff33864ec in QThreadPrivate::start (arg=0x55555754f140)
    at thread/qthread_unix.cpp:337
#8  0x00007ffff2e2c4bc in start_thread (arg=0x7fffbd757700) at pthread_create.c:333
---Type <return> to continue, or q <return> to quit---
#9  0x00007ffff234520d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7e22840 (LWP 3871)):
#0  0x00007ffff22cff06 in _int_free (av=0x7ffff25f3b80 <main_arena>, 
    p=0x555555fad150, have_lock=0) at malloc.c:3978
#1  0x00007ffff33e5989 in QHashData::free_helper (this=0x555555da1a00, 
    node_delete=0x7ffff3a96580 <QHash<QString, QPixmapCache::Key>::deleteNode2(QHashData::Node*)>) at tools/qhash.cpp:493
#2  0x00007ffff3a95ed4 in QHash<QString, QPixmapCache::Key>::freeData (
    this=<optimized out>, x=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qhash.h:581
#3  QHash<QString, QPixmapCache::Key>::~QHash (
    this=0x7ffff3e67f48 <(anonymous namespace)::Q_QGS_pm_cache::innerFunction()::holder+72>, __in_chrg=<optimized out>)
    at ../../include/QtCore/../../src/corelib/tools/qhash.h:302
#4  QPMCache::~QPMCache (
    this=0x7ffff3e67f00 <(anonymous namespace)::Q_QGS_pm_cache::innerFunction()::holder>, __in_chrg=<optimized out>) at image/qpixmapcache.cpp:211
#5  0x00007ffff3a9603c in (anonymous namespace)::Q_QGS_pm_cache::innerFunction()::Holder::~Holder() () at image/qpixmapcache.cpp:440
#6  0x00007ffff2289ef0 in __run_exit_handlers (status=0, 
    listp=0x7ffff25f3618 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#7  0x00007ffff2289f50 in __GI_exit (status=<optimized out>) at exit.c:104
#8  0x00007ffff22739eb in __libc_start_main (
    main=0x5555555a56c0 <main(int, char**)>, argc=3, argv=0x7fffffffdd28, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffdd18) at libc-start.c:331
#9  0x00005555555a6a39 in _start ()
```

**Comment by antis81** [comment]
@zetok Please recheck :)

**Comment by zetok** [comment]
@antis81 looks like it's fixed :)

**Comment by zetok** [comment]
Hmm, while testing again, I've run into some crash, related to groupchats. Now, qTox (both master & this PR) often hang when playing with audio groupchats, and once on this PR I got this:

```
[14:52:26.191] src/core/coreav.cpp:433 : Debug: toxav_group_send_audio error
[14:52:26.217] src/core/coreav.cpp:433 : Debug: toxav_group_send_audio error
[14:52:26.239] src/persistence/profile.cpp:314 : Debug: Saving tox save to  "/home/zetok/.config/tox/d_b.tox"
[Thread 0x7fffdada3700 (LWP 7499) exited]
[14:52:26.274] src/core/coreav.cpp:433 : Debug: toxav_group_send_audio error
[Thread 0x7fffda441700 (LWP 7500) exited]
[14:52:26.275] src/persistence/settings.cpp:475 : Debug: Saving personal settings at  "/home/zetok/.config/tox/d_b.ini"
[14:52:26.276] src/persistence/settings.cpp:350 : Debug: "Saving global settings at /home/zetok/.config/tox/qtox.ini"
[Thread 0x7fffdbfff700 (LWP 7459) exited]
[14:52:26.307] src/main.cpp:249 : Debug: Clean exit with status 0
[Thread 0x7fffe0a76700 (LWP 7420) exited]
[Thread 0x7fffe14c4700 (LWP 7419) exited]
[Thread 0x7fffb9655700 (LWP 7870) exited]
[Thread 0x7fffdb7fe700 (LWP 7460) exited]
[14:52:26.407] src/audio/audio.cpp:616 : Debug: stopping audio capture
[14:52:26.408] src/audio/audio.cpp:620 : Debug: Closing audio input
[Thread 0x7fffb2532700 (LWP 3587) exited]
[14:52:26.443] global/qglobal.cpp:2868 : Fatal: ASSERT: "!isRecursive()" in file thread/qmutex_linux.cpp, line 202

Program received signal SIGABRT, Aborted.
0x00007ffff22882fb in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
55  ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff22882fb in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff22897d0 in __GI_abort () at abort.c:89
#2  0x00007ffff3371be7 in qt_message_fatal (context=..., message=...)
    at global/qlogging.cpp:1422
#3  QMessageLogger::fatal (this=this@entry=0x7fffffffda90, 
    msg=msg@entry=0x7ffff3614ce8 "ASSERT: \"%s\" in file %s, line %d")
    at global/qlogging.cpp:643
#4  0x00007ffff336bd53 in qt_assert (
    assertion=assertion@entry=0x7ffff361e49f "!isRecursive()", 
    file=file@entry=0x7ffff361e487 "thread/qmutex_linux.cpp", line=line@entry=202)
    at global/qglobal.cpp:2868
#5  0x00007ffff337cd4f in QBasicMutex::lockInternal (this=0x555555d23168)
    at thread/qmutex_linux.cpp:202
#6  0x00007ffff337cdfd in QBasicMutex::lock (this=0x555555d23168)
    at thread/qmutex.h:59
#7  QRecursiveMutexPrivate::lock (timeout=-1, this=0x0) at thread/qmutex.cpp:620
#8  QMutex::lock (this=<optimized out>) at thread/qmutex.cpp:215
#9  0x000055555563813b in QMutexLocker::QMutexLocker (m=<optimized out>, 
    this=<synthetic pointer>) at /usr/include/qt5/QtCore/qmutex.h:128
#10 Audio::unsubscribeInput (this=this@entry=
    0x555555cff5a0 <Audio::getInstance()::instance>) at src/audio/audio.cpp:380
#11 0x000055555569de68 in ToxCall::~ToxCall (this=0x555556faba50, 
    __in_chrg=<optimized out>) at src/core/toxcall.cpp:69
#12 0x000055555566a4ac in ToxGroupCall::~ToxGroupCall (this=0x555556faba50, 
    __in_chrg=<optimized out>) at ./src/core/toxcall.h:70
#13 std::_Destroy<ToxGroupCall> (__pointer=0x555556faba50)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:93
#14 std::_Destroy_aux<false>::__destroy<ToxGroupCall*> (__last=<optimized out>, 
    __first=0x555556faba50)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:103
#15 std::_Destroy<ToxGroupCall*> (__last=<optimized out>, __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:126
#16 std::_Destroy<ToxGroupCall*, ToxGroupCall> (__last=0x555556faba70, 
    __first=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_construct.h:151
#17 std::vector<ToxGroupCall, std::allocator<ToxGroupCall> >::~vector (
    this=0x555555cff710 <CoreAV::groupCalls>, __in_chrg=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/include/g++-v4/bits/stl_vector.h:424
#18 IndexedList<ToxGroupCall>::~IndexedList (
    this=0x555555cff710 <CoreAV::groupCalls>, __in_chrg=<optimized out>)
    at ./src/core/indexedlist.h:10
#19 0x00007ffff228aef0 in __run_exit_handlers (status=0, 
    listp=0x7ffff25f4618 <__exit_funcs>, 
    run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#20 0x00007ffff228af50 in __GI_exit (status=<optimized out>) at exit.c:104
#21 0x00007ffff22749eb in __libc_start_main (
    main=0x5555555a56c0 <main(int, char**)>, argc=3, argv=0x7fffffffdd28, 
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
---Type <return> to continue, or q <return> to quit---
    stack_end=0x7fffffffdd18) at libc-start.c:331
#22 0x00005555555a6a39 in _start ()
```

↑ the crash happened after:
• audio 1v1 & groupchat call with other qTox instance, instance that crashed had no audio output and had audio input set
• other qTox instance hanged, and instance that crashed "saw" other peer go offline
• crashed instance was still in the groupchat
• after that, I've tried to quit crashed qTox instace via tray
• it crashed

No idea whether related to this PR, given that usually qTox instances just hang when playing with groupchats. I mean, in order to reliably reproduce one would need hang fixed first (which exists in both master and PR).

**Comment by tux3** [comment]
@antis81 This conflicts with #2768 unfortunately so I can't merge both unless you rebase one on the other. I think #2768 fixes this though, doesn't it?

**Comment by antis81** [comment]
@tux3 In general you are right, but this PR also fixes a "spam logging" problem in addition. It's easier to merge this one first (it's ready) and rebase #2768 onto master afterwards. I can do that somewhen tonight. :)

**Comment by tux3** [comment]
@antis81 Ok I pulled #2768 in its own branch instead, and I'll be working on fixing it along since there are some bugs and design issues with it that really need to be addressed (like starting a whole new thread for every sound played...).
The other branch will probably diverge a bit, so I'll just fix the spam issue there.

**Comment by antis81** [comment]
Ok.

**Pull request closed without merging**
