### PR TITLE
[ui/redesign] Fix groupchats

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3669)

### CODE REVIEW

**Comment by antis81** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/group.h, line 72 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSDi-jM4iBSlCqni3y:-KQSDi-lERlIxjw_0C-C:b9rottf) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/group.h#L72)):_

> ``` objc
>     QStringList peers;
>     QMap<QString, QString> toxids;
>     bool hasNewMessages, userWasMentioned;
> ```

Maybe split this up to two lines?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by antis81** [comment]
Reviewed 2 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQSEkMHDZUFTJ0iVkIw:b-3litje) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_

> ``` cpp
> }
> 
> void Widget::onChatroomWidgetClicked(GenericChatroomWidget *widget, bool g)
> ```

While not an "official" convention, I saw "g" and "f" used in most places for group and friend. So the above "g" is a bit misleading. Maybe rename it and use "g" for Group instance below.

---

_[src/widget/widget.cpp, line 1046 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSFNksmhNU2scBD7z_:-KQSFNksmhNU2scBD7za:bb6mt9b) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1046)):_

> ``` cpp
>         chatWidget = new ChatForm(frnd);
>     else
>         chatWidget = new GroupChatForm(group);
> ```

:+1:

---

_[src/widget/widget.cpp, line 1050 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSFTYhOJEUndrJTaKZ:-KQSFTYijvK11uOXaU5v:b-b7mfy6) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1050)):_

> ``` cpp
>     activeChat = chatWidget;
>     widget->setAsActiveChatroom();
>     if (frnd)
> ```

I guess, the if block can be merged to the one above, can it?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by Diadlo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/group.h, line 72 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSDi-jM4iBSlCqni3y:-KQSHuE1u96fEysYia9h:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/group.h#L72)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Maybe split this up to two lines?
> </details>
> Done.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQSHkkw4psUrxWdVROB:b2x35ck) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> While not an "official" convention, I saw "g" and "f" used in most places for group and friend. So the above "g" is a bit misleading. Maybe rename it and use "g" for Group instance below.
> </details>
> I am 3 times read context of emits chatroomWidgetClicked. And don't understand, what second parameter means. Second parameter `true` only if user click "open in new window" in context menu. If I am right, we should rename this parameter.

---

_[src/widget/widget.cpp, line 1050 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSFTYhOJEUndrJTaKZ:-KQSIMQKLaCUB7dOODog:b-i21bbo) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1050)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> I guess, the if block can be merged to the one above, can it?
> </details>
> Thanks. Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by antis81** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQSJ6GTG-Dk9uPINgxb:bqgp25h) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> I am 3 times read context of emits chatroomWidgetClicked. And don't understand, what second parameter means. Second parameter `true` only if user click "open in new window" in context menu. If I am right, we should rename this parameter.
> </details>
> To my knowledge, something like "open in new window" doesn't work anyway. Thus I'd say, remove it rather than renaming. If I get this right, it is meant to open chats in tabs, which is controlled by a settings flag (buried somewhere in "UI settings"). But… this requires additonal logic and currently doesn't work. And even if it would, the value should be actually read from Settings::getInstance().getValue().

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by Diadlo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQSKkFhtGirAptozqha:brjwzu1) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> To my knowledge, something like "open in new window" doesn't work anyway. Thus I'd say, remove it rather than renaming. If I get this right, it is meant to open chats in tabs, which is controlled by a settings flag (buried somewhere in "UI settings"). But… this requires additonal logic and currently doesn't work. And even if it would, the value should be actually read from Settings::getInstance().getValue().
> </details>
> This options in context menu provide ability to open chat in new window, independently of settings. I.e. user can disable "open each chat in new window" and open THIS chat in new window.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by antis81** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQSLLc9ZxLPCf9LIZof:blfpj9f) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> This options in context menu provide ability to open chat in new window, independently of settings. I.e. user can disable "open each chat in new window" and open THIS chat in new window.
> </details>
> I just tried it and it is available in current qTox release. In this case, we can simply call "showNormal()" instead of "showContentWidget". Though I must say, I'm not confident with that "feature" at all, because it completely breaks the "single window" mode concept. In single window mode, chats should open in tabs - which requires additional logic and is not part of this PR. In multiple window mode, each chat opens in a new window, so the option is just redundant.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by Diadlo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQSQrBpBsr1x3Fv3ekD:b965xfl) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> I just tried it and it is available in current qTox release. In this case, we can simply call "showNormal()" instead of "showContentWidget". Though I must say, I'm not confident with that "feature" at all, because it completely breaks the "single window" mode concept. In single window mode, chats should open in tabs - which requires additional logic and is not part of this PR. In multiple window mode, each chat opens in a new window, so the option is just redundant.
> </details>
> And as result. Should I change name or leave it?)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by antis81** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQUGOlzjZVle3ZvSIPz:b-equ5nu) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> And as result. Should I change name or leave it?)
> </details>
> Please rename it to what you think fits best.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by Diadlo** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/widget.cpp, line 1031 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3669#-KQSEkMHDZUFTJ0iVkIv:-KQUh4tvDje-qi7HVIeS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5e8d4084e9562833202a52e9a4b505f7e4f057a8/src/widget/widget.cpp#L1031)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Please rename it to what you think fits best.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669)_

**Comment by antis81** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3669#-:-KQX6L36bVyUFrXe8O5-:bnfp4nl)_

**Pull request merged**
