### PR TITLE
Make CoreFile its own class

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5565)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5565)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5565#-LayNvkJBsLndgFDVQMc:-LayNvkK1ywL5gHYolBy:b-6th3vf) (no related file):*
changing the state of any file transfer widgets seems to change the state of all file transfer widgets after this change, e.g.  your friend sending one new transfer after multiple completed and cancelling it makes all your transfers including completed one turn red.

---
___
*[src/core/core.cpp, line 295 at r1](https://reviewable.io/reviews/qtox/qtox/5565#-Lay1JBK1gF16B-CG3-M:-Lay1JBL5MkGUPrev-Vb:b-o3swdr) ([raw file](https://github.com/qtox/qtox/blob/30467555320ba170c9b351c0c533f3e80d42698c/src/core/core.cpp#L295)):*
> ```cpp
>     core->file = CoreFile::makeCoreFile(core.get(), core->tox.get(), core->coreLoopLock);
>     if (!core->file) {
>         qCritical() << "Toxav failed to start";
> ```

corefile, not Toxav
___
*[src/core/corefile.h, line 90 at r1](https://reviewable.io/reviews/qtox/qtox/5565#-LayAFWl1qVl74O9FqxY:-LayAFWn09jjWO6Ck42i:b-j5a3ot) ([raw file](https://github.com/qtox/qtox/blob/30467555320ba170c9b351c0c533f3e80d42698c/src/core/corefile.h#L90)):*
> ```objc
> 
>     static void connectCallbacks(Tox& tox);
>     static void onFileReceiveCallback(Tox*tox, uint32_t friendId, uint32_t fileId, uint32_t kind,
> ```

spec between type and variable
___
*[src/persistence/profile.cpp, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/5565#-LayKdHZ0bYMeXJntq2o:-LayKdHZ0bYMeXJntq2p:bvpu6qd) ([raw file](https://github.com/qtox/qtox/blob/c0f493b6b82433005872246a0aa19aa1053aac30/src/persistence/profile.cpp#L245)):*
> ```cpp
> {
>     if (!isRemoved && core->isReady()) {
>         onSaveToxSave();
> ```

this removal is intentional because toxsave should always be saved after any action requiring it, so by time of destruction there's nothing to change, right?

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5565)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 295 at r1](https://reviewable.io/reviews/qtox/qtox/5565#-Lay1JBK1gF16B-CG3-M:-Lb_AKox-LyP4DNdM4wo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/30467555320ba170c9b351c0c533f3e80d42698c/src/core/core.cpp#L295)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

corefile, not Toxav
</blockquote></details>

Done.
___
*[src/core/corefile.h, line 90 at r1](https://reviewable.io/reviews/qtox/qtox/5565#-LayAFWl1qVl74O9FqxY:-Lb_AZqK8_yPfVi1lHDH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/30467555320ba170c9b351c0c533f3e80d42698c/src/core/corefile.h#L90)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

spec between type and variable
</blockquote></details>

Done.
___
*[src/persistence/profile.cpp, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/5565#-LayKdHZ0bYMeXJntq2o:-Lb_A1B9C5SdauRWdvsm:bnonp43) ([raw file](https://github.com/qtox/qtox/blob/c0f493b6b82433005872246a0aa19aa1053aac30/src/persistence/profile.cpp#L245)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

this removal is intentional because toxsave should always be saved after any action requiring it, so by time of destruction there's nothing to change, right?
</blockquote></details>

done, was a bug

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5565)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5565#-LayNvkJBsLndgFDVQMc:-Lb_Cjk85kYwfkpmJ3dC:b5161qo) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

changing the state of any file transfer widgets seems to change the state of all file transfer widgets after this change, e.g.  your friend sending one new transfer after multiple completed and cancelling it makes all your transfers including completed one turn red.
</blockquote></details>

Done. Took me forever to find that `disconnect` call I missed...

---

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5565#-:-Lc-odM40RV7KTzP0X1N:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
