### PR TITLE
[WORKBRANCH] ui/redesign

### PR DESCRIPTION
**Pull request by antis81**
- [x] fix position of screenshot button (flyout)
- [x] fix call status visualization (the audio/video call buttons)

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3650)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 4 of 14 files at r1.
Review status: 4 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.cpp, line 115 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAaO65oBp6zsusKsPB:-KQAaO65oBp6zsusKsPC:b-6ynwne) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/core/core.cpp#L115)):*
> ```cpp
> }
> 
> CoreAV *Core::getAv() const
> ```

Sould return pointer on const data?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by Diadlo** [comment]
Reviewed 10 of 14 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 214 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAggtpRqgq2_Zbvtkw:-KQAggtqNmi1MhIX5BHa:b-tlrx9f) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L214)):*
> ```cpp
>         return;
> 
>     Core* core = Core::getInstance();
> ```

Maybe move it to place, where it will be used? I.e. end of this method. See below.

---

*[src/widget/form/chatform.cpp, line 239 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAhDrX-RIj1uHRLNeF:-KQAhDrYNSD7zGMRW0LG:b-tl8y5g) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L239)):*
> ```cpp
>         QFileInfo fi(path);
> 
>         core->sendFile(f->getFriendId(), fi.fileName(), path,
> ```

Move `Core* core = Core::getInstance();` before this line

---

*[src/widget/form/chatform.cpp, line 446 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAhbwqFYBzmoZcdF7X:-KQAhbwqFYBzmoZcdF7Y:b2nreh6) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L446)):*
> ```cpp
> void ChatForm::onHangupCallTriggered()
> {
>     CoreAV* av = Core::getInstance()->getAv();
> ```

Same as above.

---

*[src/widget/form/chatform.cpp, line 724 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAhwdmaKRg1EGXaH3g:-KQAhwdnFfN2yacI2yBz:b2nreh6) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L724)):*
> ```cpp
> 
>             if (info.exists())
>                 core->sendFile(f->getFriendId(), info.fileName(),
> ```

Same as above.

---

*[src/widget/form/chatform.cpp, line 870 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAi1Dlu8sGjAVEwZ12:-KQAi1DmKhKowXHhQRit:b-bvi8oe) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L870)):*
> ```cpp
>         QFileInfo fi(file);
> 
>         Core::getInstance()->sendFile(f->getFriendId(), fi.fileName(),
> ```

You already saved instance of core in `core` variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by antis81** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/core/core.cpp, line 115 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAaO65oBp6zsusKsPB:-KQAf2S88IV8lce76yFk:bnas4z2) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/core/core.cpp#L115)):*
<details><summary><i>Previously, Diadlo (Diadlo) wrote…</i></summary>
> Sould return pointer on const data?
</details>
Yes, it's ok and actually it's not possible to make the pointer const.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by antis81** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 239 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAhDrX-RIj1uHRLNeF:-KQApkmFYEu7YzbcNX-0:brpv35m) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L239)):*
<details><summary><i>Previously, Diadlo (Diadlo) wrote…</i></summary>
> Move `Core* core = Core::getInstance();` before this line
</details>
It's a loop. Probably you didn't see.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/core/core.cpp, line 115 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAaO65oBp6zsusKsPB:-KQB7uWArRWFrzzmW3Vo:bdbnrmw) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/core/core.cpp#L115)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> Yes, it's ok and actually it's not possible to make the pointer const.
</details>
So, method shouldn't be const

---

*[src/widget/form/chatform.cpp, line 239 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAhDrX-RIj1uHRLNeF:-KQB81w6U-eUrLm5rNrd:b-nq5j3w) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/widget/form/chatform.cpp#L239)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> It's a loop. Probably you didn't see.
</details>
Oh.. yes, sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by antis81** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/core/core.cpp, line 115 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAaO65oBp6zsusKsPB:-KQCNF_3D-lSS9WAHjEf:bqcx5d7) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/core/core.cpp#L115)):*
<details><summary><i>Previously, Diadlo (Diadlo) wrote…</i></summary>
> So, method shouldn't be const
</details>
What did we learn? Getters are const and there's rare exceptions to that (I don't know in more than 10 years c++ development). Code won't compile either and it is absolutely intentional here. Sorry being a bit straight, but I highly recommend learning about const correctness and how to use it. IOW: "const method" != "const return value". You can also try removing it and see why it doesn't compile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/core/core.cpp, line 115 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3650#-KQAaO65oBp6zsusKsPB:-KQCPoidIgmY0Hc-h9Cy:b-n6ztet) ([raw file](https://github.com/qtox/qtox/blob/d42ea9da13d9fdba73d3be0645ab48436fe81fca/src/core/core.cpp#L115)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> What did we learn? Getters are const and there's rare exceptions to that (I don't know in more than 10 years c++ development). Code won't compile either and it is absolutely intentional here. Sorry being a bit straight, but I highly recommend learning about const correctness and how to use it. IOW: "const method" != "const return value". You can also try removing it and see why it doesn't compile.
</details>
https://github.com/qTox/qTox/pull/3489#discussion_r71072335

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3650)*

**Comment by antis81** [comment]
@Diadlo FYI - If I find the time later, I'm going to pick this PR today. It contains valuable improvements to the AV-Call API and UI. Apart from the logic now working almost perfectly, I've noticed something and if you're in the mood of drawing some SVG's, that's a good point in time to fix microphone and volume (speaker) icons in upper-right corner of the chat area. If this is done, every (status) button can have the same style sheet (now we have four similar, but not equal).

**Edit:** For some reason it also improves situation for #3538, though that was not intentional. :smile:

If everything goes further well, we're done by the end of the week.

**Comment by Diadlo** [comment]
@antis81 Microphone should be only icon or icon + background (like old images)?

**Comment by antis81** [comment]
> Microphone should be only icon or icon + background (like old images)?

Sorry, if that was unclear. Should be icon with **transparent background** - we already have that PNG's and to be polite: "It's suboptimal." ^^

**Comment by Diadlo** [comment]
@antis81 Done
http://diadlo.dyndns.org/owncloud/s/7e4uZOwLqQ92a9J

**Pull request merged**
