### PR TITLE
feat(toxid): Added correct checksum validation.

### LINKED ISSUE #3837: qTox doesn't seem to check the Checksum of ToxId's
In https://github.com/qTox/qTox/blob/master/src/core/toxid.cpp#L141 qTox should also check the checksum of the ToxId and not assume any hex string with the correct length is a valid ToxId.

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #3837

Implementation is taken from the [toxcore](https://github.com/TokTok/c-toxcore/blob/master/toxcore/Messenger.c#L123,L138)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3868)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/core/toxid.cpp, line 137 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7h3BriF_tUxlj9Yyx:-KW7h3Bszs4gVIIUT00t:b-hmg7x7) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L137)):_

> ``` cpp
> 
> /**
>  * @brief Check, that id is a probably valid Tox ID.
> ```

"is probably a"

---

_[src/core/toxid.cpp, line 139 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7h8ammg3zXkApfv-n:-KW7h8ammg3zXkApfv-o:bv4v8m6) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L139)):_

> ``` cpp
>  * @brief Check, that id is a probably valid Tox ID.
>  * @param id Tox ID to check.
>  * @return True if id didn't contains invalid characters, false otherwise.
> ```

Simplify logic, "True if the string can be a ToxID, false otherwise."

---

_[src/core/toxid.cpp, line 142 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7hquUsCv6aMT-wesz:-KW7hquV-Xsh_RVfwKtC:b99q066) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L142)):_

> ``` cpp
>  * @note Doesn't validate checksum.
>  */
> bool ToxId::isValidToxId(const QString &id)
> ```

`&` follows the type, while you're at it fix the other instances too.

---

_[src/core/toxid.cpp, line 164 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7heZbHl8wRBe-b-qD:-KW7heZcT5MOK9zrohne:by45b9i) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L164)):_

> ``` cpp
>     QString checksumStr = id.right(TOX_ID_CHECKSUM_LENGTH);
> 
>     QByteArray publicKey = QByteArray::fromHex(publicKeyStr.toLatin1());
> ```

use `toUtf8()` maybe?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)_

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

_[src/core/toxid.cpp, line 137 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7h3BriF_tUxlj9Yyx:-KX2frlT-2NWlV6cqVq6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L137)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> "is probably a"
> </details>
> Done.

---

_[src/core/toxid.cpp, line 139 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7h8ammg3zXkApfv-n:-KX2fs68PL6CiEvLD2h9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L139)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Simplify logic, "True if the string can be a ToxID, false otherwise."
> </details>
> Done.

---

_[src/core/toxid.cpp, line 142 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7hquUsCv6aMT-wesz:-KX2fsQP7t5B7McvK6P0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L142)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> `&` follows the type, while you're at it fix the other instances too.
> </details>
> Done.

---

_[src/core/toxid.cpp, line 164 at r1](https://reviewable.io:443/reviews/qtox/qtox/3868#-KW7heZbHl8wRBe-b-qD:-KX2fsxJ8UPhNfSycsOs:baxge1b) ([raw file](https://github.com/qtox/qtox/blob/6b3b26e8c49eb0c04405d1664ee85303ec396043/src/core/toxid.cpp#L164)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> use `toUtf8()` maybe?
> </details>
> Here is no reason to use Utf8. All "hex" symbols is in Latin-1

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)_

**Comment by zetok** [comment]
@sudden6 ping?

**Comment by AliceGrey** [comment]
@zetok @Diadlo I believe the naming of the functions is a bit counterintuitive `isValidToxId` is a _probable_ tox ID. `isToxId` checks if it is _truly valid_. I think the functions should be renamed to fit their purpose. One idea is `isValidToxId` -> `isPropableToxID` and `isToxId` -> `isValidToxId`.

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/toxid.h, line 40 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYN_E2N4jXFwgsNj8H7:-KYN_E2N9gvyouJ6lWGV:b-t4ocot) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.h#L40)):*
> ```objc
> 
>     static bool isToxId(const QString& id);
>     static bool isValidToxId(const QString &id);
> ```

`&` follows type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by antis81** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/toxid.cpp, line 142 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNiK4l6fYLHMTCcMH3:-KYNgbqR3qrU7h4ICpY6:b-oqg4go) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L142)):*
> ```cpp
>  * @note Doesn't validate checksum.
>  */
> bool ToxId::isValidToxId(const QString& id)
> ```

Forgive straight language, but:
**This introduces an incomplete and insecure check -> remove this function completely!**

Rather merge the function code into `isToxId()` and rename that function to `isValid()` - thus, the ToxId can be *completely* validated. The order is ok and should not be changed:

1. check length
2. check regular expression
3. calculate checksum & check

---

*[src/core/toxid.cpp, line 153 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNgTNz96eoYXVURFZ2:-KYNgTO-9iAnsapVhmwJ:b7kxthe) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L153)):*
> ```cpp
>  * @return True if id is a valid Tox ID, false otherwise.
>  */
> bool ToxId::isToxId(const QString& id)
> ```

Please change function name to `isValid()` -> see above comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by antis81** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.cpp, line 142 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNiK4l6fYLHMTCcMH3:-KYNqXWUAFTEFxCmBW2H:b-wrj4fh) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L142)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Forgive straight language, but:
**This introduces an incomplete and insecure check -> remove this function completely!**

Rather merge the function code into `isToxId()` and rename that function to `isValid()` - thus, the ToxId can be *completely* validated. The order is ok and should not be changed:

1. check length
2. check regular expression
3. calculate checksum & check

</blockquote></details>

Sorry, just saw the check was incomplete before your change. :innocent: Anyway, please correct that. 

---

*[src/core/toxid.cpp, line 173 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNpxOS2d9L03g0vHTW:-KYNpxOgED52QLHKE_ml:b-51w6ut) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L173)):*
> ```cpp
>     }
> 
>     QByteArray caclulated(reinterpret_cast<char*>(check), 2);
> ```

static_cast

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by sudden6** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.cpp, line 142 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNiK4l6fYLHMTCcMH3:-KYNwp5N3_vB2eiFpd8f:b-5zw10d) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L142)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Sorry, just saw the check was incomplete before your change. :innocent: Anyway, please correct that. 
</blockquote></details>

A check that only tries to match a RegEx could be usefull for in text highlighting of ToxIDs. Renaming it probably won't hurt anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by antis81** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.cpp, line 142 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNiK4l6fYLHMTCcMH3:-KYNzJYe-onTHaUAOFZu:b-63ao1e) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L142)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

A check that only tries to match a RegEx could be usefull for in text highlighting of ToxIDs. Renaming it probably won't hurt anyway.
</blockquote></details>

You shouldn't even think about "…could probably be useful…" in this context! ^^

You'd rather want to write a validator class, that checks, if a string is worth to create a ToxId. As a rough suggestion in "pseudo-code":

```c++
class ToxIdValidator
{
public:
  ToxIdValidator(const QString& s) : mStr(s.toLatin1()) {}

  inline bool isLengthValid() const {
    return mStr.size() == TOX_ID_SIZE;
  }

  inline bool isHexStr() const {
    // do check…
  }

  inline bool isChecksumValid() const {
    // calculate checksum and do check
  }

  inline bool isValid() const {
    return isLengthValid() && isHexStr() && isChecksumValid();
  }

private:
  const QByteArray mStr; 
};
```

This validator can probably be a private static member of ToxId and be used in QString c'tor. And to avoid thread problems, in additon as a short-lived object inside UI.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.cpp, line 142 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNiK4l6fYLHMTCcMH3:-KYT2TyjmVR19jCw4wlj:b-69gu90) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L142)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

You shouldn't even think about "…could probably be useful…" in this context! ^^

You'd rather want to write a validator class, that checks, if a string is worth to create a ToxId. As a rough suggestion in "pseudo-code":

```c++
class ToxIdValidator
{
public:
  ToxIdValidator(const QString& s) : mStr(s.toLatin1()) {}

  inline bool isLengthValid() const {
    return mStr.size() == TOX_ID_SIZE;
  }

  inline bool isHexStr() const {
    // do check…
  }

  inline bool isChecksumValid() const {
    // calculate checksum and do check
  }

  inline bool isValid() const {
    return isLengthValid() && isHexStr() && isChecksumValid();
  }

private:
  const QByteArray mStr; 
};
```

This validator can probably be a private static member of ToxId and be used in QString c'tor. And to avoid thread problems, in additon as a short-lived object inside UI.
</blockquote></details>

I renamed method as @AliceGrey suggest (it seems most correct, IMO)
Validator is not part of this PR.

---

*[src/core/toxid.cpp, line 153 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNgTNz96eoYXVURFZ2:-KYT31n7NmW3tamshe3K:b-lfp680) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L153)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Please change function name to `isValid()` -> see above comment.
</blockquote></details>

Renamed to `isValidToxId`

---

*[src/core/toxid.cpp, line 173 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNpxOS2d9L03g0vHTW:-KYT318etejQ4RKo34oW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L173)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

static_cast
</blockquote></details>

~~Done.~~

---

*[src/core/toxid.h, line 40 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYN_E2N4jXFwgsNj8H7:-KYT394WSUY5gYRKhdtQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.h#L40)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`&` follows type
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.cpp, line 173 at r2](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYNpxOS2d9L03g0vHTW:-KYT47Uwzmbx7ooNlCXi:b-dyxxnw) ([raw file](https://github.com/qtox/qtox/blob/45532e7168354769915760388cfb3b2ac15ada47/src/core/toxid.cpp#L173)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry. It's [impossible](http://stackoverflow.com/questions/10151834/why-cant-i-static-cast-between-char-and-unsigned-char)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by antis81** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.h, line 39 at r3](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYT6_X6Thf_W56Dr8rt:-KYT6_X8lp-uifc8jZOf:b-zbvgws) ([raw file](https://github.com/qtox/qtox/blob/2213dd99e822d9f89ecfb61811b722a7ed1b86d0/src/core/toxid.h#L39)):*
> ```objc
> 
>     static bool isValidToxId(const QString& id);
>     static bool isProbableToxId(const QString& id);
> ```

rename to `isProbablyDoingSomethingOrNotMaybeWhoCares` ^^

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by antis81** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.h, line 39 at r3](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYT6_X6Thf_W56Dr8rt:-KYT7604c42c--rDGWsB:b-l8khnn) ([raw file](https://github.com/qtox/qtox/blob/2213dd99e822d9f89ecfb61811b722a7ed1b86d0/src/core/toxid.h#L39)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

rename to `isProbablyDoingSomethingOrNotMaybeWhoCares` ^^
</blockquote></details>

If you want it this way, then create three static methods:

1. static inline bool ToxId::isLengthValid(const QString& s) {…}
2. static inline bool ToxId::isHexStr(const QString& s) {…}
3. static inline bool ToxId::isChecksumValid(const QString& s) {…}

And then create a fourth, which validates all three like I wrote in the validator class above (which is basically the same thing, but works better across threads):

4. static inline ToxId::isValid(const QString& s)  { return isLengthValid(string) && isHexStr(const QString& s) && isChecksumValid(const QString& s); }

In opposite to a "probably" - this is a safe validation and is clear in any case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by Diadlo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxid.h, line 39 at r3](https://reviewable.io:443/reviews/qtox/qtox/3868#-KYT6_X6Thf_W56Dr8rt:-KYTBGvjrE6iyLkL5Vgi:bmw34wu) ([raw file](https://github.com/qtox/qtox/blob/2213dd99e822d9f89ecfb61811b722a7ed1b86d0/src/core/toxid.h#L39)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

If you want it this way, then create three static methods:

1. static inline bool ToxId::isLengthValid(const QString& s) {…}
2. static inline bool ToxId::isHexStr(const QString& s) {…}
3. static inline bool ToxId::isChecksumValid(const QString& s) {…}

And then create a fourth, which validates all three like I wrote in the validator class above (which is basically the same thing, but works better across threads):

4. static inline ToxId::isValid(const QString& s)  { return isLengthValid(string) && isHexStr(const QString& s) && isChecksumValid(const QString& s); }

In opposite to a "probably" - this is a safe validation and is clear in any case.
</blockquote></details>

I think `isProbablyDoingSomethingOrNotMaybeWhoCares` will be too long, so not :P 
Also, I don't think, that this methods should be a part of `ToxId` class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868)*

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868#-:-KZsJmcnreu_32jwCT1h:bnfp4nl)*

**Comment by Diadlo** [comment]
@sudden6 rebased

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3868#-:-KZuLYfnX5AdPpJ1FFX9:bnfp4nl)*

**Pull request merged**
