### PR TITLE
fix(docs): update toxcore build instructions

### LINKED ISSUE #5133: Build instructions are outdated and simple_make.sh doesn't work on Fedora
The build instructions say to compile toxcore with autoconf instead of cmake, which is not supported anymore.

Additionally `simple_make.sh` misses a dependency on Fedora.

Details here: https://www.reddit.com/r/projecttox/comments/8fschx/help_installing_qtox_on_fedora_26/

### PR DESCRIPTION
**Pull request by tox-user**
Partially fixes #5133

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5134)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[INSTALL.md, line 507 at r1](https://reviewable.io/reviews/qtox/qtox/5134#-LCFSA7pAtxt_2k9yQrq:-LCFSA7pAtxt_2k9yQrr:bqq86nw) ([raw file](https://github.com/qtox/qtox/blob/3751cf7176225701e05b8129396f91b8a8b92b50/INSTALL.md#L507)):*
> ```Markdown
> make -j$(nproc)
> sudo make install
> echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
> ```

IIRC this line was needed for some distro, why remove it?

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5134)*

**Comment by tox-user** [comment]
`echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf`
Didn't seem relevant, but can be kept if it's important.

**Comment by sudden6** [comment]
IIRC some distro (I think Fedora) doesn't look in `/usr/local/lib` for libraries by default, that line fixes that.

**Comment by tox-user** [comment]
I restored the line.

**Comment by sudden6** [comment]
@tox-user also the `ldconfig` line is needed, else the following steps will not find the library.

**Comment by tox-user** [comment]
Done.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5134#-:-LCP-mmEElocl4hwKVm2:b-jbsf8z)*

**Pull request merged**
