### PR TITLE
refactor: Use ToxPk instead of ToxId

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4636)

### CODE REVIEW

**Comment by noavarice** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4636)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/friendlistwidget.cpp, line 556 at r1](https://reviewable.io:443/reviews/qtox/qtox/4636#-Ktc8I5Ssc0VZn9akjqe:-Ktc8I5Ssc0VZn9akjqf:bpi21vh) ([raw file](https://github.com/qtox/qtox/blob/edd00dc40681f5e46410f45c8ddda66e20ae4a7d/src/widget/friendlistwidget.cpp#L556)):*
> ```cpp
> 
>     // Check, that the user has a friend with the same ToxPk
>     ToxPk toxPk{event->mimeData()->text()};
> ```

`QString` from `text()` will be implicitly casted to `QByteArray` that is ~likely~ correct but not expected. I think here should be `text().data()` or something like that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4636#-:-Ktc5vhDA-xpKciU5sll:b-jbsf8z)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/widget/friendlistwidget.cpp, line 556 at r1](https://reviewable.io:443/reviews/qtox/qtox/4636#-Ktc8I5Ssc0VZn9akjqe:-KtcDXiCatn96jvrXokT:b-fr5y39) ([raw file](https://github.com/qtox/qtox/blob/edd00dc40681f5e46410f45c8ddda66e20ae4a7d/src/widget/friendlistwidget.cpp#L556)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`QString` from `text()` will be implicitly casted to `QByteArray` that is ~likely~ correct but not expected. I think here should be `text().data()` or something like that
</blockquote></details>

Thanks. Here was big mistake. Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4636)*

**Comment by noavarice** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4636)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4636#-:-KtkvwsPOVrYUIXuotw8:b-jbsf8z)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4636#-:-KuPzLT8HmLcF9RXZUQl:b-jbsf8z)*

**Comment by sudden6** [comment]
@Diadlo  merge?

**Comment by Diadlo** [comment]
Seems, was github bug. Was merged 12 days ago :)

**Pull request closed without merging**
