### PR TITLE
Friend widget 2

### PR DESCRIPTION
**Pull request by Diadlo**
Round 2 Fight!

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3855)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/contentdialog.cpp, line 518 at r1](https://reviewable.io:443/reviews/qtox/qtox/3855#-KVq6pdiXx10lnZyymya:-KVq6pdjNieqORHsjLOk:b-auhrbw) ([raw file](https://github.com/qtox/qtox/blob/850c4fda30d4cf910b3a839abbccb5a399f3443b/src/widget/contentdialog.cpp#L518)):_

> ``` cpp
>             Group* group = activeChatroomWidget->getGroup();
> 
>             if (frnd)
> ```

Missing curly braces, also in other `if`s in the PR

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3855)_

**Comment by Diadlo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/contentdialog.cpp, line 518 at r1](https://reviewable.io:443/reviews/qtox/qtox/3855#-KVq6pdiXx10lnZyymya:-KVqXvmyplXKQ5BL-r84:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/850c4fda30d4cf910b3a839abbccb5a399f3443b/src/widget/contentdialog.cpp#L518)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Missing curly braces, also in other `if`s in the PR
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3855)_

**Comment by sudden6** [comment]
Reviewed 4 of 7 files at r1, 1 of 2 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/contentdialog.cpp, line 522 at r2](https://reviewable.io:443/reviews/qtox/qtox/3855#-KVtVS4-RfQvKO_IO6sG:-KVtVS40NFhAF0z4TWcd:bevsiia) ([raw file](https://github.com/qtox/qtox/blob/ecdf1249bd8ec873980eb13416ccdfe5bae4057f/src/widget/contentdialog.cpp#L522)):_

> ``` cpp
>                 emit friendDialogShown(frnd);
>             }
>             else
> ```

Should probably be, `else if (group)` to avoid a crash in `void Widget::onDialogShown(GenericChatroomWidget* widget)` if `group` is `nullptr` for whatever reason.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3855)_

**Comment by Diadlo** [comment]
Review status: 5 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/contentdialog.cpp, line 522 at r2](https://reviewable.io:443/reviews/qtox/qtox/3855#-KVtVS4-RfQvKO_IO6sG:-KVtXXjc59HAzFpSc4Vu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ecdf1249bd8ec873980eb13416ccdfe5bae4057f/src/widget/contentdialog.cpp#L522)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Should probably be, `else if (group)` to avoid a crash in `void Widget::onDialogShown(GenericChatroomWidget* widget)` if `group` is `nullptr` for whatever reason.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3855)_

**Comment by sudden6** [comment]
Reviewed 1 of 7 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3855)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3855#-:-KW7gLLy7r87EO8uxlTs:bnfp4nl)_

**Pull request merged**
