### PR TITLE
chore(deploy): publish hashes of windows setup files

### LINKED ISSUE #2670: Publish files and hashes of Windows installers on GitHub
IMO it would be nice if you could publish the Windows installers on GitHub [in the releases part](https://github.com/tux3/qTox/releases). This would allow users to easily switch back to any version they like if they e.g. encounter problems.
To further improve the security I'd suggest you to also add the hashes of these files in the description there. (Recommend hashes: SHA-265 and SHA-512)

### PR DESCRIPTION
**Pull request by sudden6**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

fixes #2670

WIP status, because I will add hashes for the other files too.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5502)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5502)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-osx.sh, line 53 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2cSDNBXxY0ORTLbK9:-LX2cSDNBXxY0ORTLbKA:b8fnflr) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/.travis/build-osx.sh#L53)):*
> ```Shell
> 
> make_hash() {
>     shasum -a 256 "$BIN_NAME" > "$BIN_NAME".sha256
> ```

sha256sum for consistency?
___
*[.travis/build-windows.sh, line 142 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2cUm0BWGVWCdBGOXv:-LX2cUm0BWGVWCdBGOXw:bpnthc5) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/.travis/build-windows.sh#L142)):*
> ```Shell
>   readonly OUT_DIR=./workspace/"$ARCH"/qtox/"$BUILD_TYPE"/
>   readonly NAME=setup-qtox-"$ARCH"-"$BUILD_TYPE".exe
>   sha256sum "$OUT_DIR""$NAME" > "$OUT_DIR""$NAME".sha256
> ```

I think NAME="setup-qtox-${ARCH}-${BUILD_TYPE}.exe"
and "${OUT_DIR}${NAME}"
would better handle either of the variables starting or ending with spaces.
___
*[appimage/build-appimage.sh, line 71 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2dDy-Ahhl-pWbKB65:-LX2dDy-Ahhl-pWbKB66:b4v04es) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/appimage/build-appimage.sh#L71)):*
> ```Shell
>     readonly OUTFILE=./output/qTox-"$TRAVIS_TAG".x86_64.AppImage
>     mv ./output/*.AppImage "$OUTFILE"
>     sha256sum "$OUTFILE" > "$OUTFILE".sha256
> ```

"${OUTFILE}.sha256"
___
*[flatpak/build-flatpak.sh, line 53 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2dKB60d2xg1bfnsau:-LX2dKB7DqFMRJVlB4sQ:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/flatpak/build-flatpak.sh#L53)):*
> ```Shell
>     readonly OUTFILE=./output/qTox-"$TRAVIS_TAG".x86_64.flatpak
>     mv ./output/*.flatpak "$OUTFILE"
>     sha256sum "$OUTFILE" > "$OUTFILE".sha256
> ```

same

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5502)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-osx.sh, line 53 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2cSDNBXxY0ORTLbK9:-LX2hmc12b-BYmSxJTld:b-u5dknh) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/.travis/build-osx.sh#L53)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

sha256sum for consistency?
</blockquote></details>

Not 100% sure it's available on Mac, `shasum` seems to be
___
*[.travis/build-windows.sh, line 142 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2cUm0BWGVWCdBGOXv:-LX3Xc8h9TwhMVdLDwnf:b-vmispk) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/.travis/build-windows.sh#L142)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think NAME="setup-qtox-${ARCH}-${BUILD_TYPE}.exe"
and "${OUT_DIR}${NAME}"
would better handle either of the variables starting or ending with spaces.
</blockquote></details>

After reading https://unix.stackexchange.com/a/421741 I can't really make out a difference and the quotes match the existing styles. I'll change it however if you persist.

**Review by anthonybilinski — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5502)* status: 0 of 1 LGTMs obtained

___
*[.travis/build-osx.sh, line 53 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2cSDNBXxY0ORTLbK9:-LX4twJVCST6WMtyRohc:b-3bggm5) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/.travis/build-osx.sh#L53)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Not 100% sure it's available on Mac, `shasum` seems to be
</blockquote></details>

Good point, forgot this was being run on osx.
___
*[.travis/build-windows.sh, line 142 at r1](https://reviewable.io/reviews/qtox/qtox/5502#-LX2cUm0BWGVWCdBGOXv:-LX4u24X3b_ZrUndvBzn:b-goalhe) ([raw file](https://github.com/qtox/qtox/blob/d6fd9f7524524c539f586251bacfdc84659e39af/.travis/build-windows.sh#L142)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

After reading https://unix.stackexchange.com/a/421741 I can't really make out a difference and the quotes match the existing styles. I'll change it however if you persist.
</blockquote></details>

I was worried that because the whole string was not quoted, only individual variables, if one variable started or ended with a space, the entire string would be split at that point. Testing it seems like that doesn't happen.

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5502#-:-LX4vKJb9vqoxa5FOjpk:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
