### PR TITLE
[Refactor] Add own ChatForm in ContentDialog

### PR DESCRIPTION
**Pull request by Diadlo**
ChatForm should be created only when it's needed => shouldn't be stored in Friend class => anyone who want to use ChatForm should have its own 

----
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4543)

### CODE REVIEW

**Comment by Diadlo** [comment]
@zetok Can you test it, please?
Probably, problems can be with opening/closing chat in different modes (one window, separated windows)

**Comment by zetok** [comment]
failed to compile:

```
[ 56%] Building CXX object CMakeFiles/qtox_static.dir/src/widget/form/settings/aboutform.cpp.o
/home/zetok/working/qtox-test/qTox/src/widget/contentdialog.cpp: In member function ‘FriendWidget* ContentDialog::addFriend(const Friend*)’:
/home/zetok/working/qtox-test/qTox/src/widget/contentdialog.cpp:170:44: error: invalid conversion from ‘const Friend*’ to ‘Friend*’ [-fpermissive]
     chatForms[friendId] = new ChatForm(frnd);
                                            ^
In file included from /home/zetok/working/qtox-test/qTox/src/widget/contentdialog.cpp:41:0:
/home/zetok/working/qtox-test/qTox/src/widget/form/chatform.h:46:14: note:   initializing argument 1 of ‘ChatForm::ChatForm(Friend*)’
     explicit ChatForm(Friend* chatFriend);
              ^
make[2]: *** [CMakeFiles/qtox_static.dir/build.make:1731: CMakeFiles/qtox_static.dir/src/widget/contentdialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:182: CMakeFiles/qtox_static.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

compiling master (ad58c1767b2ab4ff8340076d5ede53aa6e889972) works

**Comment by Diadlo** [comment]
@zetok It's strange that travis past build well. Fixed now

**Comment by zetok** [comment]
on e1dd88c6:

- history is not show for separate chat windows

Either in multiple windows mode, or by r-clicking on contact → `Open chat in new window`

**Comment by Diadlo** [comment]
@zetok Should be fixed

**Comment by Diadlo** [comment]
@zetok Is it LGTM now?

**Comment by zetok** [comment]
on d0118354:

Message is not displayed in single window mode when it was sent via detached window

Steps to reproduce:

1. Set `Multiple windows mode` in settings
2. Send message
3. Close conversation window
4. Unset `Multiple windows mode`
5. Open conversation window, there is no sent message shown

If `Multiple windows mode` is set again, sent message is shown in the detached window.

**Comment by Talkless** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/form/chatform.cpp, line 206 at r3](https://reviewable.io:443/reviews/qtox/qtox/4543#-KruiKgN1u_i4ibVl17v:-KruiKgO_znIzSOZxXMA:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/d011835434f1c7f6cd615c6d61827c9b958e64e6/src/widget/form/chatform.cpp#L206)):*
> ```cpp
> 
>     if (av->isCallStarted(f)) {
>         bool video = av->isCallVideoEnabled(f);
> ```

const bool

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4543)*

**Pull request closed without merging**
