### PR TITLE
chore(warnings): Add -Wall and -Werror flags

### PR DESCRIPTION
**Pull request by Diadlo**
Merge after #4264

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4272)

### CODE REVIEW

**Comment by sudden6** [comment]
I don't think `-Werror` should be enabled by default on non TravisCI builds.

**Comment by zetok** [comment]
>I don't think `-Werror` should be enabled by default on non TravisCI builds. 

Why?

Enabling `-Werror` for all builds would make people report problems with compiling, so that they could be addressed. Without `-Werror` being enabled by default it's very unlikely that someone would report warnings when compiling.

I.e. maintainers of most FOSS(?) projects would just outright ignore compiler warnings in their projects reported by people (e.g. saying that reported warnings aren't relevant), so people tend to follow the "custom" and ignore warnings.

**Comment by Diadlo** [comment]
PR should be fixed now

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4272#-:-KssgRqjSZOT-fAQs_ya:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong: merge?

---

Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4272#-:-KtHzZLl5LPtfd_EzoRc:b7pnnwa)*

**Pull request merged**
