### PR TITLE
fix(build): fix ASLR and DEP protection for windows builds

### PR DESCRIPTION
**Pull request by ghost**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4069)

### CODE REVIEW

**Comment by zetok** [comment]
@lopachecoc 
By having a `Fix #4068` in the commit message the issue would get closed when the commit gets merged.

https://help.github.com/articles/closing-issues-via-commit-messages/

cc @DX37 @towlie could you test and `:lgtm:` on reviewable if it works for you?

**Comment by DX37** [comment]
> cc @DX37 @towlie could you test and :lgtm: on reviewable if it works for you?

I will set up enviroment to build it, but I'm not sure if I can compile it correctly again xD
I'll try...

**Comment by DX37** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4069#-:-KaCHrwj6biaNSkxkYNg:b-jbsf8z)*

**Comment by towlie** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4069#-:-KaDEVLhZawdAcx2YReL:b-jbsf8z)*

**Pull request merged**
