### PR TITLE
chore: Remove qtox.pro and it's mention

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4151)

### CODE REVIEW

**Comment by nurupo** [comment]
@tux3 Uh, I think this is going to break Jenkins builds as the build script uses qmake.

**Comment by Diadlo** [comment]
@nurpo Can you update Jenkins script? I think, it required minimum changes

**Comment by nurupo** [comment]
Usually @tux3 manages qTox jobs and I have nothing to do with them, but I can take a look sometime later this week.

>minimum changes

The .pro file has a whole section for Jenkins [[1]](
https://github.com/qTox/qTox/blob/38cecdc7808d7c87d4a6176338a89802619902b3/qtox.pro#L98-L100)[[2]](https://github.com/qTox/qTox/blob/38cecdc7808d7c87d4a6176338a89802619902b3/qtox.pro#L294-L324), is there something like that in the cmake or we need to do some sustainable changes here?

**Comment by Diadlo** [comment]
@nurupo 
1) IDK why Jenkins should have special build config.
2) Use `-DCMAKE_PREFIX_PATH=./libs` as parameter. Then CMake will search here `include` and `lib`
3) I'm not sure about [this](https://github.com/qTox/qTox/blob/38cecdc7808d7c87d4a6176338a89802619902b3/qtox.pro#L323)

**Comment by nurupo** [comment]
Is there a CMake toolchain file for cross-compiling to Windows somewhere in the repo?

**Comment by Diadlo** [comment]
Unfortunately no

**Comment by nurupo** [comment]
I guess I will leave this for @tux3 to handle.

**Comment by zetok** [comment]
PR needs to be rebased, since there are now some conflicts.

**Comment by DX37** [comment]
> Is there a CMake toolchain file for cross-compiling to Windows somewhere in the repo?

There is mingw-w64-cmake in ArchLinux User Repository. It setup Makefiles to work with MinGW-w64 toolchains in official and user repos.
I have installed almost all mingw'ed dependencies, but (it happens always...) **I can't get sqlcipher compiled!**
How did you even compiled it for Windows? I'm used `--host=i686-w64-mingw32` for configure or `i686-mingw-w64-configure`, but compiling ends with a lot of errors...

**Comment by nurupo** [comment]
@DX37

Firstly, you need to [cross-compile openssl to windows](https://build.tox.chat/job/libopenssl-build-script_src/lastSuccessfulBuild/artifact/libopenssl-build-script_src.sh/*view*/), which is used by sqlcipher.

sqlcipher is a bit special as it doesn't get cross-compiled to windows out of the box, we have even opened an issue about that before https://github.com/sqlcipher/sqlcipher/issues/176. The build script I provided in that issue is the one we still use today.

**Comment by DX37** [comment]
Ok, I will try.

**Comment by nurupo** [comment]
We use openssl 1.0.2 series.

**Comment by DX37** [comment]
> We use openssl 1.0.2 series.

It presents in AUR as `mingw-w64-openssl` package. And I have compiled a fresh version yesterday.

**Comment by DX37** [comment]
I fricking dunno... Which version of GCC in use for cross-compiling?

**Comment by nurupo** [comment]
g++-mingw-w64-x86-64 version 6.2.1-4+19.2, the one in Debian Stretch.

**Comment by DX37** [comment]
WTF? I have mingw-w64-gcc 6.3.1!
Okay, I'm posting [pastebin with errors](http://pastebin.com/qHVNwKgV), which I get through sqlcipher compile.

**Comment by nurupo** [comment]
No idea how to help you, also not sure how you cross-compiling qTox is related to this issue, seems like a giant offtopic to me.

**Comment by DX37** [comment]
> also not sure how you cross-compiling qTox is related to this issue, seems like a giant offtopic to me.

Sorry, my mistake. I just trying to get working compiling of qTox for Windows.

**Comment by yurivict** [comment]
Since you propose to delete qmake build, cmake build failure should be fixed first: https://github.com/qTox/qTox/issues/4175

**Comment by zetok** [comment]
`qtox.pro` is no longer removed?

Aside from that, there are still mentions of `qmake` in:

* INSTALL.md
* simple_make.sh

**Comment by Diadlo** [comment]
@zetok Fixed

**Comment by zetok** [comment]
As far as changes go, :lgtm_strong: .

@sudden6 has jenkins been successfully migrated to cmake?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4151#-:-Kpl4C3gpDqJkQi_56Zs:brjiuvf)*

**Comment by Diadlo** [comment]
@yurivict Does cmake works fine on FreeBDS
@sudden6 Does cmake work fine on Jenkins?

**Comment by sudden6** [comment]
@Diadlo it works with the test build I created, still waiting for an answer of @tux3 on the release builds...

**Comment by yurivict** [comment]
@Diadlo Yes.

**Comment by nurupo** [comment]
@tux3 hasn't ported it to cmake yet. There is a thing that the updater is build-able only with qmake, there is no cmake for the updater.

**Edit:** `s/installer/updater/`

**Comment by zetok** [comment]
>There is a thing that the updater is build-able only with qmake, there is no cmake for the updater.

Well, updater has its own `updater.pro`, so it looks like `qtox.pro` can be removed.

@Diadlo rebase needed.

**Comment by Diadlo** [comment]
@zetok Rebased

**Comment by Diadlo** [comment]
@sudden6 LGTM?

**Comment by Chiitoo** [comment]
One could nit some picks about “it's” which should be “its” in this case.  :]

That is, “chore: Remove qtox.pro and its mention”.

**Comment by Diadlo** [comment]
@Chiitoo Thanks. Fixed

**Pull request merged**
