### PR TITLE
Avatar Choosing Dialog

### PR DESCRIPTION
**Pull request by CosmicToast**
Explicitly filtering out images for the avatar selection dialog.

### CODE REVIEW

**Comment by dubslow** [comment]
I believe this was discussed, and we didn't want to artificially limit what users could choose?

Although your list is explicitly what QPixmap can handle... @tux3 ?

**Comment by zetok** [comment]
Currently it's already impossible to add as image something that isn't an image - there's an error shown that something couldn't be loaded as image. With this PR though, if you have an image that doesn't end in one of formats, you'd have to rename it to one of things that qTox would _require_. IMHO that's not an improvement.

**Comment by CosmicToast** [comment]
A friend of mine (while testing) had his Qt freak out and only be able to select executables.
My theory was that this is because no filters are explicitly up (that and/or memory corruption). Specifying a set of supported images (and making it as extensive as possible) would be idea.
Ideally, the filter should be generated from [QImageReader::supportedImageFormats](http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats), which I'm planning to implement eventually.

**Comment by dubslow** [comment]
I think I'll punt on merging this until someone implements QImageReader, as you suggested you might do.

**Comment by tux3** [comment]
I think the list should also include TIFF and WEBP since Qt support those.

**Comment by CosmicToast** [comment]
Added dynamic generation of the list.
Maybe make it static? Not sure how much the code would actually benefit from that.
Another TODO: move the code into a QString getSupportedFormatsFilter().
Note: while this should work, I'm currently not in a position to test it, if you could add support for travis CI it'd greatly increase (at least my, but hopefully others') productivity.

**Pull request merged**
