### PR TITLE
Fix ACTION messages, status, username HTML parsing

### LINKED ISSUE #1999: When outgoing ACTION messages, nick in the HTML tags will be parse.
snapshot86
snapshot85

I think this and the previous title as parsing HTML is a need to fix the "feature"?

### PR DESCRIPTION
**Pull request by TheNain38**
Normally fixes #1999
Could someone check before merging?

### CODE REVIEW

**Comment by zetok** [comment]
> Could someone check before merging?

@TheNain38 um, what prevents you from checking it?

**Comment by TheNain38** [comment]
@zetok I can't setup a build environnement, I'm trying as hard as possible to setup one

**Comment by zetok** [comment]
@TheNain38 yes, but you still didn't say what is causing you problems

**Comment by antis81** [comment]
Looks good to me :+1:

**Comment by TheNain38** [comment]
@zetok see irungentoo/toxcore#1443

**Comment by TheNain38** [comment]
I've corrected another HTML parsing bug with the typing notification, good to merge.

**Comment by agilob** [comment]
@antis81 pls merge if you tested it and it's ok, I don't want to be the only person who merges :<

**Comment by TheNain38** [comment]
@agilob I've tested it in a VM and it works

**Comment by agilob** [comment]
IT can't be merged because it modifies incoming message. The code is completely stripping HTML from message instead treating message as plaintext. When user with nick `<h1>kotez</h1>` is sending me an action message I should see it as `* <h1>kotez</h1> test` not `* kotez test`. See two examples how the same nickname is displayed in two different ways:
weblate6

weblate5

Another thing, your code introduces regression, nick is displayed in different way in groupchat than in chat. **AFAIR** those changes should be done in chatline.cpp or chatmessage.cpp.

**Comment by TheNain38** [comment]
@agilob Look at your first screenshot, in the groupchat his name hasn't been updated, also I've noticed another place where parsing applies but shouldn't, I will update

**Comment by agilob** [comment]
I was invited to the groupchat by zetok when kotez already had nick with html tags, so there was nothing to be updated.

**Comment by TheNain38** [comment]
@agilob In your screenshot kotez name in groupchat isn't `<h1>kotez</h1>`, it is `kotez`
capture

**Comment by zetok** [comment]
@TheNain38 yes, name was `<h1>kotez</h1>` - this looks like a regression caused by name being assigned as alias.

**Comment by agilob** [comment]
Works for me now. Thanks!

**Pull request merged**
