### PR TITLE
Make markdown strings translatable

### PR DESCRIPTION
**Pull request by agilob**

### CODE REVIEW

**Comment by zetok** [comment]
80a8f2528d631d13d03696452f43f59a110b99ac makes string translatable

```
    <message>
        <source>Plaintext</source>
        <translation type="unfinished">translated :D</translation>
    </message>
```

but it's not translated:
not translated

#3002

**Comment by agilob** [comment]
Force updated that branch, pull --force zetok.

Or just trust me
screenshot_20160510_134112

**Comment by agilob** [comment]
One more... month labels are translated automatically by Qt(?) or operating system
screenshot_20160510_153358

**Comment by zetok** [comment]
Um, could you rename commits to use https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#commit-message-format and move dab3529b390d04029cfddba7610a9a9fedb02d36 to a separate PR based on this branch?

**Comment by agilob** [comment]
what, seriously? I just wanted to help ;_;

**Comment by ovalseven8** [comment]
Yeah, basically you're right.
The new commit message format looks awful, is not beginner friendly for people who just want to help with a single PR, and to create a changelog out of the commit messages is not really the way to go.
But just my opinion. :wink:

**Comment by zetok** [comment]
@ovalseven8 as I've said before – if you're interested in making a changelog in some other way, please do so. Did I perhaps miss your attempt at writing the changelog?

The option is to simply take the commit(s), and change the commit message(s) to fit with CMF – I'm just asking whether someone is willing to do it themselves, or whether PR should be pulled in & edited by someone willing to do it.

**Comment by agilob** [comment]
@zetok this should be told everyone BEFORE even cloning qtox repo, after it's pushed I won't waste time another time to fix commit message format. Sorry.

**Comment by zetok** [comment]
When you open PR/issue:
creating PR
contributing

But yeah, I've added link to it also on https://github.com/tux3/qTox/wiki#contributing.

What more can be done?

**Comment by agilob** [comment]
> When you open PR/issue:

That's after committing.

**Comment by zetok** [comment]
> That's after committing.

Well, yeah. But then again, if someone wants to help, they probably would click on `Contribute` link in `README.md`, which does point to aggregation of links, that now also explicitly points to `CONTRIBUTING.md`.

> (…) after it's pushed I won't waste time another time to fix commit message format. Sorry.

That's kinda weird, given that out of all, fixing the commit message would seem to me to be the easiest thing..? (and doesn't take much time either) 

Especially given that on travis (which fails if commit message doesn't conform) there are helpful links, even to the article that explains in great detail & simple steps how to rewrite history.

**Pull request closed without merging**
