### PR TITLE
refactor(id): make ContactId interface, implement GroupId

### PR DESCRIPTION
**Pull request by anthonybilinski**
Precursor for group history, friend blocking

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5615)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
Do you think it makes sense to add a simple unit test for `GroupId` similar to `ToxPk`?

> Reviewed 21 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5615#-:-LcG5JfW0rOkzt6o7HWw:b-plv1oq)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1099 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG3C_V01wzlFlaGIXm:-LcG3C_W6cxNvC0juX8Z:bpb7p9e) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/core.cpp#L1099)):*
> ```cpp
> }
> 
> GroupId Core::getGroupPersistentId(uint32_t groupNumber) {
> ```

This function is public, so it must lock the coreLoop lock
___
*[src/core/groupid.cpp, line 12 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG3StG-awMLmOSipZN:-LcG3StG-awMLmOSipZO:b-w6ispe) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/groupid.cpp#L12)):*
> ```cpp
> /**
>  * @class GroupId
>  * @brief This class represents a Tox Public id, which is a part of Tox ID.
> ```

I think the term "Tox Public id" doesn't really exist as a term in Tox, maybe explain a bit more here?
___
*[src/core/toxpk.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG45HGDqb2r3OWoDQ3:-LcG45HGDqb2r3OWoDQ4:bliyp4j) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/toxpk.cpp#L40)):*
> ```cpp
>     : ContactId(rawId)
> {
>     assert(rawId.length() == TOX_PUBLIC_KEY_SIZE);
> ```

Is this the correct order? I think `ContactId(rawId)` is executed before the assert, making it kinda useless
___
*[src/widget/widget.cpp, line 1785 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG4iPC7bK0eUeQh_cX:-LcG4iPDEyBJ2GyTRCcZ:bnk4k0d) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/widget/widget.cpp#L1785)):*
> ```cpp
>     if (!g) {
>         qDebug() << "onGroupNamelistChanged: Group " << groupnumber << " not found, creating it";
>         const auto groupId = Nexus::getCore()->getGroupPersistentId(groupnumber);
> ```

shouldn't `Core` be already available in `Widget` I'd prefer not using `getCore()` since we're trying to get rid of it. (whole file)

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5615)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1099 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG3C_V01wzlFlaGIXm:-LcHDyr79ZZc1O19pE9m:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/core.cpp#L1099)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This function is public, so it must lock the coreLoop lock
</blockquote></details>

Done.
___
*[src/core/groupid.cpp, line 12 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG3StG-awMLmOSipZN:-LcHGnJe4AwAElw8b-KQ:b-cxqcvd) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/groupid.cpp#L12)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think the term "Tox Public id" doesn't really exist as a term in Tox, maybe explain a bit more here?
</blockquote></details>

Fixed. Was a mistake from find/replace of Tox ID :S
___
*[src/core/toxpk.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG45HGDqb2r3OWoDQ3:-LcHGtF55eSbQSAecs-B:b-vpnbih) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/toxpk.cpp#L40)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Is this the correct order? I think `ContactId(rawId)` is executed before the assert, making it kinda useless
</blockquote></details>

ContactId(rawid) is executed first, but the assert still stops the ToxPk from finishing construction. I don't think it really matters if the assert is done just before ContactId(rawid) or just after, since either way the construction will be stopped.
___
*[src/widget/widget.cpp, line 1785 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG4iPC7bK0eUeQh_cX:-LcHH5rN78VBLPF3ZKnX:b-eiwjn1) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/widget/widget.cpp#L1785)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

shouldn't `Core` be already available in `Widget` I'd prefer not using `getCore()` since we're trying to get rid of it. (whole file)
</blockquote></details>

I'm not totally sure what you meant by "should be available in Widget", but I've added a Core* member to Widget that's set on init and used in place of Core::getInstance across Widget.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 26 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5615)* status: 0 of 1 LGTMs obtained

___
*[src/core/toxpk.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG45HGDqb2r3OWoDQ3:-LcHYoexCQplfTyN7Oc_:b-pp1z1r) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/toxpk.cpp#L40)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

ContactId(rawid) is executed first, but the assert still stops the ToxPk from finishing construction. I don't think it really matters if the assert is done just before ContactId(rawid) or just after, since either way the construction will be stopped.
</blockquote></details>

Ok, I think with QByteArray it might actually be safe, but I'm still not really happy with this. I'll leave this for you to decide.
___
*[src/widget/widget.cpp, line 1785 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG4iPC7bK0eUeQh_cX:-LcHZOsL7jbVUoyfVmsO:b-wrudao) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/widget/widget.cpp#L1785)):*
I thought there is already a `Core*` in Widget, apparently I was wrong.
> I've added a Core* member to Widget that's set on init and used in place of Core::getInstance across Widget.

It seems this change didn't fully make it into the commit.

**Review by anthonybilinski — COMMENTED** [review]
> Do you think it makes sense to add a simple unit test for GroupId similar to ToxPk?

Since i moved almost all of the functionality of ToxPk to ContactId, leaving the only GroupId-defined function as getSize, I've basically just renamed the ToxPk test to a ContactId test, and checked getSize of both ToxPk and GroupId. Does this seem sufficient?

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5615#-:-LcJ7gqn3OyCzQJFIHyo:b3okpyq)* status: 0 of 1 LGTMs obtained

___
*[src/core/toxpk.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG45HGDqb2r3OWoDQ3:-LcJ74uP9GxTYNkWv71g:bnlr5lb) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/toxpk.cpp#L40)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Ok, I think with QByteArray it might actually be safe, but I'm still not really happy with this. I'll leave this for you to decide.
</blockquote></details>

I think it's roughly functionally equivalent, but yeah I agree it seems conceptually wrong to use the parameter before checking if it's valid. What do you think of this initialization list check?
___
*[src/widget/widget.cpp, line 1785 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG4iPC7bK0eUeQh_cX:-LcHsEaB90fjgbQriNv7:b293x6) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/widget/widget.cpp#L1785)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I thought there is already a `Core*` in Widget, apparently I was wrong.
> I've added a Core* member to Widget that's set on init and used in place of Core::getInstance across Widget.

It seems this change didn't fully make it into the commit.
</blockquote></details>

oops.. replaced Core::getInstance() but not Nexus::getCore(). Fixed.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5615#-:-LcJKDpp8dYy-aimJjx1:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/toxpk.cpp, line 40 at r1](https://reviewable.io/reviews/qtox/qtox/5615#-LcG45HGDqb2r3OWoDQ3:-LcJJkGcDukNyL4RsSgv:bbj3dym) ([raw file](https://github.com/qtox/qtox/blob/e4b6766841a0c692f455190325f26ddf2a9f6688/src/core/toxpk.cpp#L40)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think it's roughly functionally equivalent, but yeah I agree it seems conceptually wrong to use the parameter before checking if it's valid. What do you think of this initialization list check?
</blockquote></details>

ok now, didn't know this was possible

**Pull request merged**
