### PR TITLE
fix: two crashes, uncovered by the persistent groupchat patch

### PR DESCRIPTION
**Pull request by sudden6**
-

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/widget/form/groupchatform.cpp, line 269 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSUuG30NwmoFWGlF3s:-LBSUuG30NwmoFWGlF3t:b-gh1t8a) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/form/groupchatform.cpp#L269)):*
> ```cpp
> 
>     // no need to remove the comma if list is empty
>     if(nickLabelList.isEmpty()) {
> ```

Space after `if`

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113#-:-LBSUzY3BSTfIm7VnTz4:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/widget/widget.cpp, line 1872 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSVZMMEzcVG9YvNGL4:-LBSVZMMEzcVG9YvNGL5:b-1nw46v) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/widget.cpp#L1872)):*
> ```cpp
>         return;
>     }
>     delete groupChatFormIt.value();
> ```

If we delete the `GroupChatForm*` anytime it's removed from `groupChatForms`, it would be a great place to use std::unique_ptr. It would save this ordering issue and also remove the need for looping over the map in ~Widget. This fix is still fine as is.

---

*[src/widget/form/groupchatform.cpp, line 270 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSWJYA9jAuVsYG2P6c:-LBSWJYA9jAuVsYG2P6d:bf1v8jd) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/form/groupchatform.cpp#L270)):*
> ```cpp
>     // no need to remove the comma if list is empty
>     if(nickLabelList.isEmpty()) {
>         return;
> ```

Don't we still need to add the labels back to namesListLayout? returning early skips that part as well, not just removing the comma:
```
    for (QLabel* l : nickLabelList) {
        namesListLayout->addWidget(l);
    }
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113)*

**Comment by tox-user** [comment]
This PR fixes: https://github.com/qTox/qTox/issues/5106.

>Don't we still need to add the labels back to namesListLayout? returning early skips that part as well, not just removing the comma

The list is empty so the for loop will not run. Even if it would, there are no labels to add.

**Comment by tox-user** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113#-:-LBSv4f92v9IZmRM1yPb:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/groupchatform.cpp, line 270 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSWJYA9jAuVsYG2P6c:-LBSvx_G3QnqrGCF2vwz:bq9juvz) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/form/groupchatform.cpp#L270)):*
>The list is empty so the for loop will not run.

Of course, never mind :P

In that case might as well move the check up and not bother sorting the empty list.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113)*

**Comment by tox-user** [comment]
>In that case might as well move the check up and not bother sorting the empty list.

I agree! The comment will have to be updated then.

**Comment by sudden6** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/widget/widget.cpp, line 1872 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSVZMMEzcVG9YvNGL4:-LBX6sNRCQE_E_4F5Y52:b-b8iv2t) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/widget.cpp#L1872)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

If we delete the `GroupChatForm*` anytime it's removed from `groupChatForms`, it would be a great place to use std::unique_ptr. It would save this ordering issue and also remove the need for looping over the map in ~Widget. This fix is still fine as is.
</blockquote></details>

Not changed here, but opened an issue so we don't forget.

---

*[src/widget/form/groupchatform.cpp, line 269 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSUuG30NwmoFWGlF3s:-LBX6zs32sVmMJLJSoP9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/form/groupchatform.cpp#L269)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Space after `if`
</blockquote></details>

Done.

---

*[src/widget/form/groupchatform.cpp, line 270 at r1](https://reviewable.io/reviews/qtox/qtox/5113#-LBSWJYA9jAuVsYG2P6c:-LBX7-_V40Uo0jFGrD4m:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/836191e6f32a556ab59f8f2d318ab6a5447c5ce8/src/widget/form/groupchatform.cpp#L270)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

>The list is empty so the for loop will not run.
Of course, never mind :P

In that case might as well move the check up and not bother sorting the empty list.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113)*

**Comment by anthonybilinski** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113)*

**Comment by anthonybilinski** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5113#-:-LBXaLvYDDSXxHOi4XDr:b-jbsf8z)*

**Pull request merged**
