### PR TITLE
Fix confusing statement, compact instructions

### PR DESCRIPTION
**Pull request by ProMcTagonist**
It sounds like you can press enter to make a new selection.

### CODE REVIEW

**Comment by agilob** [comment]
I think this text is already way too long :<
How about:
`Press space to show or hide qTox, Enter to capture screenshot, Esc to quit`?

**Comment by ProMcTagonist** [comment]
Better?

Should the selection/non-selection tooltips match? One has linedowns and one doesn't, now.

**Comment by agilob** [comment]
Thanks o/

> Should the selection/non-selection tooltips match? One has linedowns and one doesn't, now.

I dont really care...

**Comment by ProMcTagonist** [comment]
It just looks weird for them to be different.

**Pull request merged**
