### PR TITLE
First qTox unit test!

### PR DESCRIPTION
**Pull request by Diadlo**
* `ToxId` test
* `ToxPk` test

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4110)

### CODE REVIEW

**Comment by Diadlo** [comment]
@zetok Can you [take a look](https://travis-ci.org/qTox/qTox/jobs/196850033#L2786)?

**Comment by zetok** [comment]
@Diadlo looks like that files doesn't exist?

**Comment by Diadlo** [comment]
@zetok ~~Do you have any idea, why it's didn't builded?~~

**Comment by sudden6** [comment]
Reviewed 5 of 9 files at r1.
Review status: 5 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4110)*

**Comment by zetok** [comment]
Reviewed 1 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/Testing.cmake, line 16 at r1](https://reviewable.io:443/reviews/qtox/qtox/4110#-Kc1HWgNIVuiJ8Qtzulp:-Kc1HWgNIVuiJ8Qtzulq:b-td257i) ([raw file](https://github.com/qtox/qtox/blob/b61ab81bb49f52402f4aaae246a1e25bd2b38223/cmake/Testing.cmake#L16)):*
> ```CMake
> 
> if (NOT ENABLE_UNIT_TESTS)
>   set(ENABLE_UNIT_TESTS True)
> ```

By default tests probably should be disabled, there's no reason for users who would want to just compile qTox to run tests. If tests are going to be disabled by default, there would be no reason for `simple_make.sh`to install additional deps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4110)*

**Comment by sudden6** [comment]
Reviewed 1 of 9 files at r1.
Review status: 7 of 9 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4110)*

**Pull request closed without merging**
