### PR TITLE
fix(icons): Removed unnecessary icon preparation.

### PR DESCRIPTION
**Pull request by yurivict**
Desktop environments function in largely the same way on UNIXes.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4120)

### CODE REVIEW

**Comment by Diadlo** [comment]
Please, update commit message to satisfy [format](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format)

**Comment by yurivict** [comment]
renamed

**Comment by zetok** [comment]
Does it apply to osx?

**Comment by yurivict** [comment]
The way it's done it picks desktop type from the environment variable and only does something when it is set. So it should be safe. On OSX/Windows it probably will do nothing, because desktop there is different.

I am not sure what happens when no icon preparation is done. Does it still work? No comments in code explaining this.

**Comment by yurivict** [comment]
Without comments explaining why this is needed, I am inclined to think it should either be always done, regardless of desktop, or not done at all. Depending on why this is needed.

**Comment by yurivict** [comment]
Now I think this code is wrong. QtSvg should be used instead. http://doc.qt.io/qt-5/qtsvg-index.html QIcon doesn't work with SVGs, and here qTox passes svgs to QIcon.

**Comment by yurivict** [comment]
I will research it more and update this PR.

**Comment by sudden6** [comment]
@yurivict will this fix a specific bug or is it just cleanup? because if it's the later it should be moved to the 1.9 milestone.

**Comment by yurivict** [comment]
This started as a fix, but turned out to be a cleanup.

**Comment by sudden6** [comment]
Thanks, moved it.

**Comment by Diadlo** [comment]
Please, rebase

**Comment by yurivict** [comment]
rebased

**Comment by sudden6** [comment]
> I will research it more and update this PR.

Is it ready to merge?

**Comment by yurivict** [comment]
Yes, all resolved.

**Comment by sudden6** [comment]
should be tested on linux for one of  xfce, gnome, mate or cinnamon

Edit: preferably on the oldest supported distro

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4120#-:-KcFGDe_VCyDcqluiTqS:b67bkug)*

**Comment by yurivict** [comment]
I tested on cinnamon (Arch), icons work as expected.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4120#-:-Kdc1PpgDTpB_VK95lf9:b-jbsf8z)*

**Comment by Diadlo** [comment]
PR pending 20 days. I think there is no reason to wait longer (anybody who wanted to test, already test it)
I'm planing to merge in the near future

**Comment by noavarice** [comment]
Tested on Gnome, works normally

**Pull request merged**
