### PR TITLE
chore(formatting): run format-code.sh

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4371)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/video/camerasource.cpp, line 98 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUcM_HZkQzIHDazrTv:-KjUcM_HZkQzIHDazrTw:b-7txuw4) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/video/camerasource.cpp#L98)):*
> ```cpp
>     , cctx
> {
>     nullptr
> ```

Here (and a few lines below) have wrong formstting 

---

*[src/widget/contentdialog.cpp, line 510 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUceVTOSRYAxz4o7Ze:-KjUceVTOSRYAxz4o7Zf:bi2h6m8) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/contentdialog.cpp#L510)):*
> ```cpp
>     Status currentStatus = activeChatroomWidget->getFriend()->getStatus();
> 
>     QMap<Status, QIcon> icons{{Status::Online, QIcon(":/img/status/dot_online.svg")},
> ```

This format is a bit strange. What about "clang-format: off" here?

---

*[src/widget/friendlistwidget.cpp, line 60 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUcwir34Y4yhgKe_cK:-KjUcwir34Y4yhgKe_cL:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/friendlistwidget.cpp#L60)):*
> ```cpp
> 
>     QDate today = QDate::currentDate();
>     const QMap<Time, QDate> dates{
> ```

Same as above

---

*[src/widget/friendlistwidget.cpp, line 192 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUd1SU3pN2cNAwxJuJ:-KjUd1SU3pN2cNAwxJuK:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/friendlistwidget.cpp#L192)):*
> ```cpp
>         QDate today = QDate::currentDate();
> #define COMMENT "Category for sorting friends by activity"
>         const QMap<Time, QString> names{
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4371)*

**Comment by sudden6** [comment]
Review status: 12 of 17 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/video/camerasource.cpp, line 98 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUcM_HZkQzIHDazrTv:-KjbR26m2rZ2inoyn3zR:b-xzpylc) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/video/camerasource.cpp#L98)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Here (and a few lines below) have wrong formstting 
</blockquote></details>

Yes, clang format probably got confused by the `#if` should I put `clang-format: off` there?

---

*[src/widget/contentdialog.cpp, line 510 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUceVTOSRYAxz4o7Ze:-KjbRFOjojdkYftF772A:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/contentdialog.cpp#L510)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

This format is a bit strange. What about "clang-format: off" here?
</blockquote></details>

Done.

---

*[src/widget/friendlistwidget.cpp, line 60 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUcwir34Y4yhgKe_cK:-KjbRGKAZhlZ3EGWk-I4:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/friendlistwidget.cpp#L60)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/widget/friendlistwidget.cpp, line 192 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUd1SU3pN2cNAwxJuJ:-KjbRHHd0Fi3Vl3sTrNf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/friendlistwidget.cpp#L192)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4371)*

**Comment by Diadlo** [comment]
Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/video/camerasource.cpp, line 98 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUcM_HZkQzIHDazrTv:-KjbhIlV4lH9wrX3NutP:bjs55jr) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/video/camerasource.cpp#L98)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Yes, clang format probably got confused by the `#if` should I put `clang-format: off` there?
</blockquote></details>

Yes, I think so

---

*[src/widget/contentdialog.cpp, line 510 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUceVTOSRYAxz4o7Ze:-KjbhMvwrEzFzpvFvogv:b-brxt5v) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/contentdialog.cpp#L510)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

And return old format :)

---

*[src/widget/friendlistwidget.cpp, line 60 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUcwir34Y4yhgKe_cK:-KjbhOfLKLhXRlai4wxX:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/friendlistwidget.cpp#L60)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same as above

---

*[src/widget/friendlistwidget.cpp, line 192 at r1](https://reviewable.io:443/reviews/qtox/qtox/4371#-KjUd1SU3pN2cNAwxJuJ:-KjbhPv7fgYGtbqM7Eu-:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/dbde8dcb35f7dec183cbe762a1e72f65266db548/src/widget/friendlistwidget.cpp#L192)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4371)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 41 at r2](https://reviewable.io:443/reviews/qtox/qtox/4371#-Kjw049fZLtxRHzv_EUZ:-Kjw049fZLtxRHzv_EU_:b-zucl5) ([raw file](https://github.com/qtox/qtox/blob/9045d35c99dce624bf1399735eb002adccb9630c/src/chatlog/textformatter.cpp#L41)):*
> ```cpp
> static const QString HTML_CHARACTER_CODE = QStringLiteral("&#%1");
> 
> static const QVector<char> MARKDOWN_SYMBOLS{'*', '/', '_', '~', '`'};
> ```

Perhaps instead of formatting those things in the file use `// clang-format off ` + `// clang-format on` ?

---

*[src/chatlog/content/text.cpp, line 370 at r2](https://reviewable.io:443/reviews/qtox/qtox/4371#-Kjw0YaYZrl2FmrGwHxE:-Kjw0YaYZrl2FmrGwHxF:b-s9ff6b) ([raw file](https://github.com/qtox/qtox/blob/9045d35c99dce624bf1399735eb002adccb9630c/src/chatlog/content/text.cpp#L370)):*
> ```cpp
>         for (QTextBlock::Iterator itr = block.begin(); itr != block.end(); ++itr) {
>             int pos = itr.fragment().position(); // fragment position -> position of the first
>                                                  // character in the fragment
> ```

perhaps move the comment above the code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4371)*

**Comment by sudden6** [comment]
closing in favor of #4434

**Pull request closed without merging**
