### PR TITLE
feat(audio): microphone voice activation

### PR DESCRIPTION
**Pull request by gstark667**
adding volume based voice detection
this addresses issue  #4686

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4790)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/audio/backend/openal.cpp, line 550 at r1](https://reviewable.io:443/reviews/qtox/qtox/4790#-KyFrWwnz0wfSU-7MCEE:-KyFrWwoiXzTmJgwxKe3:bs7k563) ([raw file](https://github.com/qtox/qtox/blob/23624db86a729769b10273becb5059be6761f85d/src/audio/backend/openal.cpp#L550)):*
> ```cpp
>     for (quint32 i = 0; i < samples; i++) {
>         float sample = (float)buf[i] / (float)std::numeric_limits<int16_t>::max();
>         if (sample > 0) {
> ```

You could replace this condition with `sum += abs(sample);`.

Also did you by chance test the square average algorithm ` sum += sample^2;` and how it compares to normal average?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4790)*

**Comment by gstark667** [comment]
*[src/audio/backend/openal.cpp, line 550 at r1](https://reviewable.io:443/reviews/qtox/qtox/4790#-KyFrWwnz0wfSU-7MCEE:-KyIhzoLwPWo6mYNWakI:b-1jm2w) ([raw file](https://github.com/qtox/qtox/blob/23624db86a729769b10273becb5059be6761f85d/src/audio/backend/openal.cpp#L550)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

You could replace this condition with `sum += abs(sample);`.

Also did you by chance test the square average algorithm ` sum += sample^2;` and how it compares to normal average?
</blockquote></details>

I switched it over to std::abs (I tried abs before and the travis build broke for mac because of namespace issues).

I tried out root mean square and didn't notice much of a difference with my usual audio, there were some issues with really quiet or really loud audio though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4790)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/audio/backend/openal.cpp, line 550 at r1](https://reviewable.io:443/reviews/qtox/qtox/4790#-KyFrWwnz0wfSU-7MCEE:-KyKYoackmEjdH2ZwOb0:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/23624db86a729769b10273becb5059be6761f85d/src/audio/backend/openal.cpp#L550)):*
<details><summary><i>Previously, gstark31897 (Gavin Stark) wrote…</i></summary><blockquote>

I switched it over to std::abs (I tried abs before and the travis build broke for mac because of namespace issues).

I tried out root mean square and didn't notice much of a difference with my usual audio, there were some issues with really quiet or really loud audio though.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4790#-:-KyKZ0uRzE9A8MSKs0TG:b-jbsf8z)*

**Comment by sudden6** [comment]
@gstark31897 can you please rebase on master?

**Pull request merged**
