### PR TITLE
feat(chatform): Export chat history to file

### LINKED ISSUE #4143: [enhancement] Export full chat history to plaintext without listing it in the client
As of now, when you want to export chat history, you first have to ask the client to list it, and then either choose to save the chat log from there, or copy and paste it into a text file. Listing it in the client can take a while if you have a lot of chat history since it has to wrap all the lines to fit into the window, and as can be seen in issue #4134 this can lead to qTox crashing.

Therefore, a function to simply export the chat log without having to list it in the client first would be a nice feature.

### PR DESCRIPTION
**Pull request by tWido**
Export chat history to plaintext
Fixes #4143

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4489)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 675 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnT_G61eWTe9DKXG6eL:-KnT_G61eWTe9DKXG6eM:b-hgu8nq) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L675)):*
> ```cpp
> }
> 
> QString ChatForm::getMsgAuthorDispName(const History::HistMessage& msg) const
> ```

Why method, but not static function?
For the future: better do refactoring (extracting function) in separate commit

---

*[src/widget/form/chatform.cpp, line 1024 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnT_eCoEAmj9x8a1e_g:-KnT_eCoEAmj9x8a1e_h:b-6m8ypv) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1024)):*
> ```cpp
>     QString pk = f->getPublicKey().toString();
>     QList<History::HistMessage> msgs =
>         history->getChatHistory(pk, QDateTime::fromMSecsSinceEpoch(0), QDateTime::currentDateTime());
> ```

I think, `QDateTime::fromMSecsSinceEpoch(0)` and/or `QDateTime::currentDateTime()` better extract into variable.
1) It gives logical name to the value
2) It makes the line shorter

---

*[src/widget/form/chatform.cpp, line 1026 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTanmcQ2uCsYloQ_PR:-KnTanmcQ2uCsYloQ_PS:b-ad40em) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1026)):*
> ```cpp
>         history->getChatHistory(pk, QDateTime::fromMSecsSinceEpoch(0), QDateTime::currentDateTime());
> 
>     QString path = QFileDialog::getSaveFileName(0, tr("Save chat log"));
> ```

Becouse of #3436 we should use workaround with `QFileDialog::DontUseNativeDialog`
See example here 881409b91fe133ae53b2e0344a6d764fd0d0a6d7

---

*[src/widget/form/chatform.cpp, line 1036 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTb4eO47wku0DJ1vAL:-KnTb4eO47wku0DJ1vAM:b-sguvg3) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1036)):*
> ```cpp
>     for (const auto& it : msgs) {
>         QString line =
>             QString("%1\t%2\t%3\n").arg(it.timestamp.toString(), getMsgAuthorDispName(it), it.message);
> ```

What about extract `it.timestamp.toString()` and/or `getMsgAuthorDispName(it)` in variable?

---

*[src/widget/form/chatform.cpp, line 1037 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTbCoSUdFAIEpVMeCE:-KnTbCoSUdFAIEpVMeCF:b-rimpw) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1037)):*
> ```cpp
>         QString line =
>             QString("%1\t%2\t%3\n").arg(it.timestamp.toString(), getMsgAuthorDispName(it), it.message);
>         file.write(line.toUtf8());
> ```

To avoid a lot of file writes, better use concat (QStringBuilder?) + one write

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by Diadlo** [comment]
Also, thanks for your PRs ;)

**Comment by tWido** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 1037 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTbCoSUdFAIEpVMeCE:-KnTtBSg9XAfuUiHAMMz:b-2a9my1) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1037)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

To avoid a lot of file writes, better use concat (QStringBuilder?) + one write
</blockquote></details>

Used operator % from QStringBuilder for fast concat

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 675 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnT_G61eWTe9DKXG6eL:-KnTvk1AA5I1qQXWwAOH:bpg5wv4) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L675)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why method, but not static function?
For the future: better do refactoring (extracting function) in separate commit
</blockquote></details>

No, I talk about remove method from `.h` file and make function in `.cpp`

---

*[src/widget/form/chatform.cpp, line 1030 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTv8vmxEHPow4aGb0t:-KnTv8vmxEHPow4aGb0u:b-3l88aq) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1030)):*
> ```cpp
>     QString dir;
>     QString filter;
>     QString path = QFileDialog::getSaveFileName(0, tr("Save chat log"), dir, filter, 0,
> ```

You can pass `QString{}` as parameter directly

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489#-:-KnU-E21mwIH7FBBzDzx:b-jbsf8z)*

**Comment by Diadlo** [comment]
@tWido Please, use Reviewable it make review easier

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 675 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnT_G61eWTe9DKXG6eL:-KnU-ERm2F_lPl4nBbXX:b-retfx4) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L675)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

No, I talk about remove method from `.h` file and make function in `.cpp`
</blockquote></details>

+1. If some function is not supposed to use internal class fields, this function should be placed in `.cpp` without being included to class. Also you can pass only `authorPk` and displayed name from `msg` because `authorPk` will be constructed again right after `getMsgAuthorDispName` call, to avoid action duplicating

---

*[src/widget/form/chatform.cpp, line 1032 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4-1n9_KnQcb1CaSL:-KnU4-1n9_KnQcb1CaSM:b-cxoj0d) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1032)):*
> ```cpp
>     QString path = QFileDialog::getSaveFileName(0, tr("Save chat log"), dir, filter, 0,
>                                                 QFileDialog::DontUseNativeDialog);
>     if (path.isEmpty())
> ```

Please, add brackets for condition code block, even if there's only one line -- see code style

---

*[src/widget/form/chatform.cpp, line 1036 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4XC5yDHZFb5jJCsy:-KnU4XC5yDHZFb5jJCsz:bb73xfv) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1036)):*
> ```cpp
> 
>     QFile file(path);
>     if (!file.open(QIODevice::WriteOnly | QIODevice::Text))
> ```

Same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by tWido** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 675 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnT_G61eWTe9DKXG6eL:-KnU5aoKRgmQJWya1eeq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L675)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

+1. If some function is not supposed to use internal class fields, this function should be placed in `.cpp` without being included to class. Also you can pass only `authorPk` and displayed name from `msg` because `authorPk` will be constructed again right after `getMsgAuthorDispName` call, to avoid action duplicating
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1024 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnT_eCoEAmj9x8a1e_g:-KnU5bDmlA31M1at6zfX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1024)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, `QDateTime::fromMSecsSinceEpoch(0)` and/or `QDateTime::currentDateTime()` better extract into variable.
1) It gives logical name to the value
2) It makes the line shorter
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1026 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTanmcQ2uCsYloQ_PR:-KnU5bxjc4KZEeXRyr10:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1026)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Becouse of #3436 we should use workaround with `QFileDialog::DontUseNativeDialog`
See example here 881409b91fe133ae53b2e0344a6d764fd0d0a6d7
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1036 at r1](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTb4eO47wku0DJ1vAL:-KnU5dBT5muLFvoL2_g4:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/49a4908cd32e1b65d452aea9211038ede76e06e7/src/widget/form/chatform.cpp#L1036)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about extract `it.timestamp.toString()` and/or `getMsgAuthorDispName(it)` in variable?
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1030 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnTv8vmxEHPow4aGb0t:-KnU5bexEdX0Fxp3wXlE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1030)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

You can pass `QString{}` as parameter directly
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1032 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4-1n9_KnQcb1CaSL:-KnU5cP_dv-3sf3y4Amv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1032)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Please, add brackets for condition code block, even if there's only one line -- see code style
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1036 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4XC5yDHZFb5jJCsy:-KnU5cjqn1wWapBBu6CT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1036)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 1032 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4-1n9_KnQcb1CaSL:-KnU69M25UKpEj78Rt5f:b-2edgqz) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1032)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Seems, you forget to push changes? Still no brackers here

---

*[src/widget/form/chatform.cpp, line 1036 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4XC5yDHZFb5jJCsy:-KnU6IvC_bbWmQ2cl1gB:bb73xfv) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1036)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by tWido** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 1032 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4-1n9_KnQcb1CaSL:-KnVIq_KXAVAgmtbaWgA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1032)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems, you forget to push changes? Still no brackers here
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 1036 at r2](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnU4XC5yDHZFb5jJCsy:-KnVIq53btu9rWqSdsoT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed5bcba53a796078dd45a3065f93c64d0c1e7c54/src/widget/form/chatform.cpp#L1036)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489#-:-KnVN9vclcYv78vKwuqh:b-jbsf8z)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/widget/form/chatform.cpp, line 676 at r4](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnVR6W8RDT6NeXxu_Vu:-KnVR6W8RDT6NeXxu_Vv:b-jgsxq3) ([raw file](https://github.com/qtox/qtox/blob/1a0c58f0a25cb503d77ec3d5412b4e538484ce8d/src/widget/form/chatform.cpp#L676)):*
> ```cpp
> }
> 
> QString getMsgAuthorDispName(const ToxPk& authorPk, QString dispName)
> ```

Please pass `QString` by const reference

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by tWido** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[src/widget/form/chatform.cpp, line 676 at r4](https://reviewable.io:443/reviews/qtox/qtox/4489#-KnVR6W8RDT6NeXxu_Vu:-KnVUhNEzsDc2PdRnR_A:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1cfac473784550d4a8961a430a57e878226f8140/src/widget/form/chatform.cpp#L676)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Please pass `QString` by const reference
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4489#-:-KnVVX6psFW4BNWzLMCV:b-jbsf8z)*

**Comment by Diadlo** [comment]
@tWido Good job :+1:

**Pull request merged**
