### PR TITLE
fix(audio): fix error introduced in 67f2605971cf43093c72f811e4df90ab7…

### PR DESCRIPTION
**Pull request by sudden6**
…0544dd6

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5213)

### CODE REVIEW

**Comment by sudden6** [comment]
fixes #5212

**Comment by tox-user** [comment]
I don't get it. What exactly is causing this error and why does it depend on toxcore version?

**Comment by sudden6** [comment]
I forgot to change some code that was grayed out in my IDE because it targets an old toxcore version.

**Comment by tox-user** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5213#-:-LGRikao4YpcETgvxJWU:b-jbsf8z)*

**Pull request merged**
