### PR TITLE
Simplified Chinese translation

### PR DESCRIPTION
**Pull request by broncotc**
This is the zh-CN translation I created today.

### CODE REVIEW

**Comment by dubslow** [comment]
Hmm it looks like you didn't actually run Qt Linguist, since you copied the French file? It's slightly out of date, a lot of file line numbers have changed...

**Comment by broncotc** [comment]
I manully translated it from the <source>s in the french file. When I put it into Linguist, all the ticks are green.

**Comment by broncotc** [comment]
All the translation is finished. lupdate is executed. QT 4.8.6 is used.

**Comment by dubslow** [comment]
I'll merge this, but in the future try to avoid updating all language files, only update the one(s) you're working on.

**Comment by dubslow** [comment]
You also accidentally added a spurious file "null"

**Comment by broncotc** [comment]
Ok, get it~

**Pull request merged**
