### PR TITLE
fix(video): workaround for webcams that provide no fps value

### LINKED ISSUE #5082: USB JPEG webcam fails to open, VIDIOC_ENUM_FRAMEINTERVALS return Invalid Arg
##### Brief Description

OS: Ubuntu 18.04
qTox version: v1.14.1+
Commit hash:  47150f23bf724fb13ca99a5d22d7e5db05c82e75
toxcore:  v0.2.1
Qt:  5.9.4
Hardware:  USB Camera (046d:08da)

Reproducible: Always

##### Steps to reproduce

1. Video preview

##### Observed Behavior
1. No video
```
[05:30:14.148 UTC] widget/form/settings/avform.cpp:389 : Debug: available Modes:
[05:30:14.148 UTC] widget/form/settings/avform.cpp:298 : Debug: selected Modes:
[05:30:14.148 UTC] video/camerasource.cpp:384 : Debug: Closing device  "none"
[05:30:14.149 UTC] video/camerasource.cpp:267 : Debug: Opening device  "/dev/video0"
[05:30:14.149 UTC] video/cameradevice.cpp:160 : Warning: VideoMode could be invalid!
[05:30:14.149 UTC] platform/camera/v4l2.cpp:205 : Warning: Pixel format not found
[V4L2 indev @ 0x7f58140060a0] Unable to parse option value "0x0" as image size
[V4L2 indev @ 0x7f58140060a0] Error setting option video_size to value 0x0.
[05:30:14.149 UTC] video/camerasource.cpp:280 : Warning: Failed to open device!
```
In v4l2::getDeviceModes, VIDIOC_ENUM_FMT and VIDIOC_ENUM_FRAMESIZES are succeeding, but then in getDeviceModeFramerates the first IOCTL of VIDIOC_ENUM_FRAMEINTERVALS for each sets errno 22 "Invalid Argument".

The webcam's pretty old. I'm not sure if this is just a legacy driver issue that isn't worth looking into or if it's indicative of a larger problem, but it does work streaming from ffmpeg. ffmpeg does complain about frame timing, which may be rooted in the same core problem, but they might just handle it better?:
```
$ ffmpeg -i /dev/video0 out.webm
[video4linux2,v4l2 @ 0x56229f0ac8c0] Time per frame unknown
Input #0, video4linux2,v4l2, from '/dev/video0':
  Duration: N/A, start: 67763.945205, bitrate: N/A
    Stream #0:0: Video: mjpeg, yuvj422p(pc, bt470bg/unknown/unknown), 640x480, 31 tbr, 1000k tbn, 1000k tbc
```

`v4l-info`:
```

### v4l2 device info [/dev/video0] ###
general info
    VIDIOC_QUERYCAP
	driver                  : "gspca_zc3xx"
	card                    : "USB Camera (046d:08da)"
	bus_info                : "usb-0000:00:1d.0-1.6"
	version                 : 4.15.10
	capabilities            : 0x85200001 [VIDEO_CAPTURE,?,READWRITE,STREAMING,(null)]

standards

inputs
    VIDIOC_ENUMINPUT(0)
	index                   : 0
	name                    : "gspca_zc3xx"
	type                    : CAMERA
	audioset                : 0
	tuner                   : 0
	std                     : 0x0 []
	status                  : 0x0 []

video capture
    VIDIOC_ENUM_FMT(0,VIDEO_CAPTURE)
	index                   : 0
	type                    : VIDEO_CAPTURE
	flags                   : 1
	description             : "JFIF JPEG"
	pixelformat             : 0x4745504a [JPEG]
    VIDIOC_G_FMT(VIDEO_CAPTURE)
	type                    : VIDEO_CAPTURE
	fmt.pix.width           : 640
	fmt.pix.height          : 480
	fmt.pix.pixelformat     : 0x4745504a [JPEG]
	fmt.pix.field           : NONE
	fmt.pix.bytesperline    : 640
	fmt.pix.sizeimage       : 115790
	fmt.pix.colorspace      : JPEG
	fmt.pix.priv            : 4276996862

controls
    VIDIOC_QUERYCTRL(BASE+0)
	id                      : 9963776
	type                    : INTEGER
	name                    : "Brightness"
	minimum                 : 0
	maximum                 : 255
	step                    : 1
	default_value           : 128
	flags                   : SLIDER
    VIDIOC_QUERYCTRL(BASE+1)
	id                      : 9963777
	type                    : INTEGER
	name                    : "Contrast"
	minimum                 : 0
	maximum                 : 255
	step                    : 1
	default_value           : 128
	flags                   : SLIDER
    VIDIOC_QUERYCTRL(BASE+16)
	id                      : 9963792
	type                    : INTEGER
	name                    : "Gamma"
	minimum                 : 1
	maximum                 : 6
	step                    : 1
	default_value           : 4
	flags                   : SLIDER
    VIDIOC_QUERYCTRL(BASE+17)
	id                      : 9963793
	type                    : INTEGER
	name                    : "Exposure"
	minimum                 : 781
	maximum                 : 18750
	step                    : 1
	default_value           : 2343
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+18)
	id                      : 9963794
	type                    : BOOLEAN
	name                    : "Gain, Automatic"
	minimum                 : 0
	maximum                 : 1
	step                    : 1
	default_value           : 1
	flags                   : UPDATE
    VIDIOC_QUERYCTRL(BASE+24)
	id                      : 9963800
	type                    : MENU
	name                    : "Power Line Frequency"
	minimum                 : 0
	maximum                 : 2
	step                    : 1
	default_value           : 0
	flags                   : unknown
    VIDIOC_QUERYCTRL(BASE+27)
	id                      : 9963803
	type                    : INTEGER
	name                    : "Sharpness"
	minimum                 : 0
	maximum                 : 3
	step                    : 1
	default_value           : 2
	flags                   : SLIDER
```

`v4l2-ctl --all`:
```
Driver Info (not using libv4l2):
	Driver name   : gspca_zc3xx
	Card type     : USB Camera (046d:08da)
	Bus info      : usb-0000:00:1d.0-1.6
	Driver version: 4.15.10
	Capabilities  : 0x85200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps   : 0x05200001
		Video Capture
		Read/Write
		Streaming
		Extended Pix Format
Priority: 2
Video input : 0 (gspca_zc3xx: ok)
Format Video Capture:
	Width/Height      : 640/480
	Pixel Format      : 'JPEG'
	Field             : None
	Bytes per Line    : 640
	Size Image        : 115790
	Colorspace        : JPEG
	Transfer Function : Default (maps to sRGB)
	YCbCr/HSV Encoding: Default (maps to ITU-R 601)
	Quantization      : Default (maps to Full Range)
	Flags             : 
JPEG compression:
	Quality: 75
	Markers: 0x00000018
		Define Huffman Tables
		Define Quantization Tables
Streaming Parameters Video Capture:
	Frames per second: invalid (0/0)
	Read buffers     : 2

User Controls

                     brightness 0x00980900 (int)    : min=0 max=255 step=1 default=128 value=128 flags=slider
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=128 value=128 flags=slider
                          gamma 0x00980910 (int)    : min=1 max=6 step=1 default=4 value=4 flags=slider
                       exposure 0x00980911 (int)    : min=781 max=18750 step=1 default=2343 value=2343 flags=inactive, volatile
                 gain_automatic 0x00980912 (bool)   : default=1 value=1 flags=update
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=0 value=0
                      sharpness 0x0098091b (int)    : min=0 max=3 step=1 default=2 value=2 flags=slider

JPEG Compression Controls

            compression_quality 0x009d0903 (int)    : min=50 max=87 step=1 default=75 value=75
```

### PR DESCRIPTION
**Pull request by sudden6**
fixes #5082

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5355)

### CODE REVIEW

**Review by zetok — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5355)* status: 0 of 1 LGTMs obtained

___
*[src/platform/camera/v4l2.cpp, line 163 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa1onY50flt0jQ-900:-LNa1onZ4aqoohdyPDIl:b-ozg5xp) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/platform/camera/v4l2.cpp#L163)):*
> ```cpp
> 
>             // insert dummy FPS value to have the mode in the list even if we don't know the FPS
>             if(rates.isEmpty()) {
> ```

`if(` insert space between if and parenthesis
___
*[src/video/cameradevice.cpp, line 195 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa1yuZEjwYqbpbWzek:-LNa1yu_A6t-rGZK_Bby:b-ozg5xp) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/video/cameradevice.cpp#L195)):*
> ```cpp
>         const std::string pixelFormatStr = v4l2::getPixelFormatString(mode.pixel_format).toStdString();
>         // don't try to set a format string that doesn't exist
>         if(pixelFormatStr != "unknown" && pixelFormatStr != "invalid") {
> ```

`if(` insert space between if and parenthesis
___
*[src/widget/form/settings/avform.cpp, line 225 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa1zdZCoorNC3-0W9H:-LNa1zdZCoorNC3-0W9I:b-ozg5xp) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/widget/form/settings/avform.cpp#L225)):*
> ```cpp
> void AVForm::selectBestModes(QVector<VideoMode>& allVideoModes)
> {
>     if(allVideoModes.isEmpty()) {
> ```

`if(` insert space between if and parenthesis

**Review by zetok — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5355)* status: 0 of 1 LGTMs obtained

___
*[src/platform/camera/v4l2.cpp, line 162 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa2Ek18Oq6kxRIaOi9:-LNa2Ek18Oq6kxRIaOiA:baesu1d) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/platform/camera/v4l2.cpp#L162)):*
> ```cpp
>                 getDeviceModeFramerates(fd, mode.width, mode.height, vfd.pixelformat);
> 
>             // insert dummy FPS value to have the mode in the list even if we don't know the FPS
> ```

I think that it would be good to add a rationale for this, e.g. something like `some cameras fail to work if we don't provide a dummy FPS value, see #5082`

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5355)* status: 0 of 1 LGTMs obtained

___
*[src/platform/camera/v4l2.cpp, line 162 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa2Ek18Oq6kxRIaOi9:-LNaCdOZ7VChKwY2ePXH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/platform/camera/v4l2.cpp#L162)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

I think that it would be good to add a rationale for this, e.g. something like `some cameras fail to work if we don't provide a dummy FPS value, see #5082`
</blockquote></details>

Done.
___
*[src/platform/camera/v4l2.cpp, line 163 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa1onY50flt0jQ-900:-LNaCdq08tIoeMTxSymM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/platform/camera/v4l2.cpp#L163)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`if(` insert space between if and parenthesis
</blockquote></details>

Done.
___
*[src/video/cameradevice.cpp, line 195 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa1yuZEjwYqbpbWzek:-LNaCedr3qXXNc0HPmbm:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/video/cameradevice.cpp#L195)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`if(` insert space between if and parenthesis
</blockquote></details>

Done.
___
*[src/widget/form/settings/avform.cpp, line 225 at r1](https://reviewable.io/reviews/qtox/qtox/5355#-LNa1zdZCoorNC3-0W9H:-LNaCfMy161Ul5gLtY6r:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5deefc67b5e60f15a1f1687a976170eca788870a/src/widget/form/settings/avform.cpp#L225)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`if(` insert space between if and parenthesis
</blockquote></details>

Done.

**Review by zetok — APPROVED** [review]

**Comment by sudden6** [comment]
@zetok you have to actually `lgtm` this PR, else the reviewable check will not pass.

**Comment by zetok** [comment]
> @zetok you have to actually `lgtm` this PR, else the reviewable check will not pass.

I know, and I explicitly approved changes without `lgtm`. The thing is, I still don't know C++ and qTox's codebase. I do have a faint idea what the code does, but it is not even nearly enough to mark the code as reviewed.

I guess I should have been more clear that I was doing only something like a preliminary screening for obvious things, and a proper review should still be done by someone who knows C++.

**Comment by sudden6** [comment]
Ok, didn't think of that being intentional, and it was a common mistake since GH and reviewable work together.

Maybe a comment like `lgtm from my side, but review from another person needed` would be a good way to convey this?

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5355#-:-LO0JhNBCkYamv5OHjfA:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
