### PR TITLE
refactor(core): use STL random implementation insted of Qt

### LINKED ISSUE #6017: Move to STL <random> over Qt random libs
Qt updated the API for random numbers, so to reduce the version specific code we switch to `<random>` from the C++ STL.

See #6005 for the areas that need changes.

@Chiitoo is working on this

### PR DESCRIPTION
**Pull request by tWido**
use STL <random> libs to reduce version specific code

Closes #6017

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6271)

### CODE REVIEW

**Comment by Chiitoo** [comment]
Thank you for looking into this!

I've still not managed to even start, but it's good to see that the changes needed might be a lot smaller than I had anticipated.

**Comment by sudden6** [comment]
This seems to be against what's done here: https://github.com/qtox/qtox/commit/6105af8279b609107f5116b0ac5039b8dbcd17b8

@anthonybilinski can you comment?

**Comment by tWido** [comment]
> This seems to be against what's done here: [6105af8](https://github.com/qTox/qTox/commit/6105af8279b609107f5116b0ac5039b8dbcd17b8)

Yeah, that seems worrisome, but gcc 9.2 is one and half year old. So it's up to you to decide.

**Comment by sudden6** [comment]
We're even still using GCC 7.0 in our Windows builds, that's what Debian currently ships.

**Comment by tWido** [comment]
Bug doesn't mention first affected version and couldn't find out which GCC version does MinGW use, so rather used pseudorandom generator seeded by time as proposed.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6271#-:-MPcse21-bbBzT8PyAOS:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
