### PR TITLE
Change smiley character order

### PR DESCRIPTION
**Pull request by ovalseven8**
Removed some unicode characters that aren't displayed correctly for many users in the 'Basic' smiley pack. Goal is that at least in the 'Classic' and 'Basic' smiley packs there aren't any display problems.

**Edit:** Now they aren't removed but in another order.

### CODE REVIEW

**Comment by Schlumpf** [comment]
:-1: for removing.
As I said in #2701, changing the order should solve the problem of wrong display in the input field on some systems. If you _remove_ the glyphs, all already written unicode character(e.g. `💣`) will not rendered anymore. Any if you are on a "problematic" system, you won't see them in the chat window, too.

**Comment by ovalseven8** [comment]
@Schlumpf: OK, done. :)

**Comment by ovalseven8** [comment]
@Schlumpf: Thanks, forgot to delete some lines. Should be fixed now.

**Comment by zetok** [comment]
From what I understand, it's not the order that is a problem, but a missing font.

I wonder how feasible would be bundling with qTox font `Symbola`, which has support for all needed glyphs.

**Pull request merged**
