### PR TITLE
refactor: Added  to include path and exclude it from all includes

### PR DESCRIPTION
**Pull request by Diadlo**
We begin each local include with `src/`. It seems redundant.
So, I added `src/` to include path and remove it using from all includes

You can use this script to update your source on Linux:
```
find -type f -print0 | xargs -0 sed -i 's/include "src\//include"/'
```

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3885)

### CODE REVIEW

**Comment by antis81** [comment]
Would you also update docs in [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) please.

**Comment by Diadlo** [comment]
@antis81 Done
Welcome back :)

**Comment by antis81** [comment]
:lgtm:

---

Reviewed 118 of 118 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3885#-:-KWoTZX0fJaT2Ra_1Yav:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3885#-:-KWyunPuin3gxCgrlRxm:bnfp4nl)_

**Comment by sudden6** [comment]
@initramfs doesn't seem very active atm, how long do you want to wait for a LGTM from him?

**Comment by Diadlo** [comment]
Rebased

**Comment by zetok** [comment]
@sudden6 why not use `LGTM_STRONG` ?

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 111 of 119 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3885#-:-KXh-Ax0WSd8DrWhTWSg:bnfp4nl)*

**Pull request merged**
