### PR TITLE
Temporary removal of link to tox.im repository

### PR DESCRIPTION
**Pull request by strixaluco**
As it was stated in recent blog post on https://blog.tox.chat/2015/07/current-situation-3/
"Unfortunately, Sean refuses to take responsibility for what he has done, and seems to carry the attitude that what he did was perfectly acceptable. Despite our having spent a great deal of time and effort trying to engage with him, giving him opportunities to pay us back and redeem himself (which is part of the reason why we have waited this long to make an official post about it), he has shown no remorse for his actions, and continues to hold some of our infrastructure “hostage”. This includes the tox.im, toxme.se, and libtoxcore.so domains. For this reason, we have also been forced to disassociate ourselves with the aforementioned domains and begin again from scratch with a new domain, tox.chat"

### CODE REVIEW

**Comment by Zer0-One** [comment]
@strixaluco there's already a PR for this

**Comment by strixaluco** [comment]
@Zer0-One 
I apologize, but I didn't get your point.

**Comment by Zer0-One** [comment]
@strixaluco https://github.com/tux3/qTox/pull/2035

Your changes are redundant

**Comment by strixaluco** [comment]
@Zer0-One 
Oh, I haven't noticed.

**Pull request closed without merging**
