### PR TITLE
fixes #207

### LINKED ISSUE #207: Command line options
Basically, like Toxic and Venom 

https://img.bi/#/WpzHYKR!BjebnxxQL9NeUXPiNe7bkwUTbgU0IK5Q4pTVPsDd

<blockquote><pre>
~ venom --help
Usage:
venom [OPTION...]
 
Help Options:
-h, --help Show help options
 
Application Options:
-f, --file=<file> Set the location of the tox data file
-l, --loglevel=<loglevel> Set level of messages to log
--offline Start in offline mode
--textview Use textview to display messages
-V, --version Display version number
</pre></blockquote>

### PR DESCRIPTION
**Pull request by Zer0-One**
Adds command-line argument/flag parsing

### CODE REVIEW

**Comment by dubslow** [comment]
Debug logging needs to be on by default, and as far as I can tell the option doesn't actually do anything.

**Comment by tux3** [comment]
Yes, and we're not going to wrap every qDebug in if { } blocks :)

**Comment by dubslow** [comment]
That's what the message handler is for :P

**Comment by Zer0-One** [comment]
I believe it's good now

**Comment by dubslow** [comment]
Better.

The main reason I didn't do this myself is that the docs say that qt options are parsed before this is even constructed, meaning things like "-p" wouldn't be parsed here...

**Pull request merged**
