### PR TITLE
perf(ui): cache stylesheets to reduce memory usage

### PR DESCRIPTION
**Pull request by anthonybilinski**
Issue #5078

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5081)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Running my profile and loading all of my history in one of the chats, then clearing history in that chat. The loading is the increase in memory usage, and the clearing is not visible:
Benchmark off master 55d8922d69f035580dbea92285648d75645bfcf0
[Uploading Anthony_master_massif.log…]()
image

With stylesheet deduplication:
[Anthony_style_massif.log](https://github.com/qTox/qTox/files/1910731/Anthony_style_massif.log)
image

savings are basically 100% of stylesheet allocation, i.e. 80MB in my situation of lots of history loaded.

**Comment by sudden6** [comment]
Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---

*[src/chatlog/content/filetransferwidget.cpp, line 185 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5081#-LA4Vs-5EEaRi0ZK47wx:-LA4Vs-5EEaRi0ZK47wy:bhx9v7a) ([raw file](https://github.com/qtox/qtox/blob/e8928acc37f2b542e34597638f7f8427574c02fa/src/chatlog/content/filetransferwidget.cpp#L185)):*
> ```cpp
> 
>     stylesheet = Style::getStylesheet(":/ui/fileTransferInstance/filetransferWidget.css");
>     setStyleSheet(*stylesheet.get());
> ```

I think you can directly dereference `std::shared_ptr` without having to call `get()` first, or is this considered better style?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081)*

**Comment by sudden6** [comment]
Nice improvement :+1:

**Comment by Talkless** [comment]
Interesting, though I am guessing that caching could work with "plain" QString, as it is implicitly shared data structure, although using shared pointer does provide kinda clear intent. Additionally, maybe worth using std::shared_ptr<*const* QString> to avoid any accidental deep copies? I imagine once it's cached, it's there forever unchanged?

---

Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA4ZjpI59G4khx519_7:b-fclhnu)*

**Comment by Talkless** [comment]
Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/content/filetransferwidget.cpp, line 185 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5081#-LA4Vs-5EEaRi0ZK47wx:-LA4_lFU9FXgMFSL1OoU:bbqg79q) ([raw file](https://github.com/qtox/qtox/blob/e8928acc37f2b542e34597638f7f8427574c02fa/src/chatlog/content/filetransferwidget.cpp#L185)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think you can directly dereference `std::shared_ptr` without having to call `get()` first, or is this considered better style?
</blockquote></details>

Yeah, dereferencing pointer from get() looks kinda too verbose.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/content/filetransferwidget.cpp, line 185 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5081#-LA4Vs-5EEaRi0ZK47wx:-LA4bDGlES-UNtUKR1Ly:bmgzkxb) ([raw file](https://github.com/qtox/qtox/blob/e8928acc37f2b542e34597638f7f8427574c02fa/src/chatlog/content/filetransferwidget.cpp#L185)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Yeah, dereferencing pointer from get() looks kinda too verbose.
</blockquote></details>

Removed. Wasn't style, just a mistake

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081)*

**Comment by anthonybilinski** [comment]
@talkless ah that's a good point. I didn't know about the implicit sharing. If the QString is then held onto by the Widget, I wouldn't have to add all of this lifetime management of the shared_ptr in each class. The cache with shared_ptr has the benefit that it's not there forever, because the cache itself only holds onto the data with a weak_ptr, so once the last user of the stylesheet destructs, it will be removed from cache as well. I don't think this would be handled from using raw QStrings, but that's pretty insignificant in terms of memory usage, maybe less than the thousands of shared_ptrs :P

---

Review status: 0 of 25 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA4cJid0g0_fhxgt-3V:b-55u26p)*

**Comment by Talkless** [comment]
> so once the last user of the stylesheet destructs, it will be removed from cache as well

Yeah makes sense.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA4qoDj30bS5wht2EyY:b-a2di21)*

**Comment by Talkless** [comment]
What's your take on std::shared_ptr<**const** QString> suggestion?

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA4r5_D1iCiQal_49QH:bi4tzbb)*

**Comment by anthonybilinski** [comment]
Switched to const. Do you think the ability to empty the cache is worth the tradeoff of having every class hold onto shared_ptrs? By memory usage its basically the same, but there's lots of new member variables sprinkled around, and it makes it more complex to use the cache, plus we don't normally have every class using a specific stylesheet destruct unless we're quitting. I'm leaning towards just having things that enter the cache stay there forever to simplify.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA4zoyK25cNkXqt2cfd:bmsv8l6)*

**Comment by Talkless** [comment]
> I'm leaning towards just having things that enter the cache stay there forever to simplify.

Uhm, so we go back to the question is shared pointer needed at all? I mean, if cache returns cached QString witch is simply passed into widget without calling any non-const members (and so no detaching, no deep copies performed), Qt's implicit-sharingness should be enough?

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA7YiFI5UfpNfiU86Wq:b-w5ff9p)*

**Comment by anthonybilinski** [comment]
In the case of the cache never emptying, a shared_ptr is not required and the implicit copying of QString is enough. The only benefit we get from the shared_ptr is having the cache be empty-able. So basically we have to choose between 1) raw QString, no new class state, un-emptyable cache; or 2) shared_ptr/weak_ptr, new shared_ptr in every class, emptyable cache.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LA7vLp8-mqTtdrkVW4G:b2t06eb)*

**Comment by Talkless** [comment]
Having cache emptyable looks like too much work and verbosity for a feature that is not sure if really needed in application of this scale and use case.

---

Review status: 0 of 25 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LAEAUxY7WvIEDWWGvol:b-v7mv74)*

**Comment by anthonybilinski** [comment]
Re-benchmarked with change to plain `const QString`, and confirmed memory usage is just about as low as before. Difference could be a slight efficiency of shared_ptr vs QString's sharing implementation, but more likely it's just experimental noise.
[Anthony_QString_massif.log](https://github.com/qTox/qTox/files/1917969/Anthony_QString_massif.log)

image
On a side note I actually see memory going doing quite a lot after clearing history this time. Can't see how it would be related to this change, maybe there was just more time between clear and exit, but either way that investigation is still part of #5078

There's some stuff with `Style` that I want to refactor, but it's not pressing so I won't hold this PR up on it. I'll write it down here so I don't forget..
The behaviour of `dict` was to populates a few items on `setThemeColor` but in `resolve` it populates the map with all the default values only if `dict` is empty. This means that if `setThemeColor` is called before `loadNewStylesheet`, the map would only ever have the couple colour-related items in it. It also means that the first font passed into `loadNewStylesheet` is the only one that matters, since it's used to populate `dict` which only happens the first time. This might be a bug since we actually do pass in a non-default `QFont` in `Text::Text`. I haven't investigated that further. If we do want to just have a default QFont parsed into the `dict`, we can't do that on static init because `QFontInfo` (I think) requires `QGuiApplication` to be init, so the whole `Style` static class might need to be changed into a singleton :(

We might get some slight cache optimization by dropping the `QFont` argument too since it doesn't actually change uniqueness of the stylesheet the way it is now..

**Comment by sudden6** [comment]
code :lgtm_strong: did you test it with switching themes and colors? could be that the cache must be cleared during a switch

---

Reviewed 13 of 25 files at r1, 12 of 12 files at r2, 3 of 25 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/widget/style.cpp, line 105 at r3](https://beta.reviewable.io/reviews/qtox/qtox/5081#-LAJkmZn-KtG_75ztyCm:-LAJkmZpDhTH7M8zkiY6:bb7ozr7) ([raw file](https://github.com/qtox/qtox/blob/13e5006d6ca87953092262bcf71ad6e4e32726f4/src/widget/style.cpp#L105)):*
> ```cpp
>     if (it != stylesheetsCache.end())
>     {
>     	// cache hit
> ```

tabs

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5081#-:-LAJl2op6EzWBpu2OULP:b-mopni1)*

**Comment by tox-user** [comment]
Fonts and colors are defined in many different places, so those Style bugs might not affect anything in the UI. Themes need to be reimplemented and I'm planning to work on that.

**Comment by anthonybilinski** [comment]
>did you test it with switching themes and colors

I hadn't, thanks for the suggestion. Tested now and behaviour looks identical before and after. From code inspection I don't expect risk related to themes/colours, as those don't alias the same stylesheets/fonts that are passed into the function that's caching.

**Comment by anthonybilinski** [comment]
>did you test it with switching themes and colors? could be that the cache must be cleared during a switch

:1st_place_medal: https://github.com/qTox/qTox/issues/5092

**Pull request merged**
