### PR TITLE
Update link for os x binary

### PR DESCRIPTION
**Pull request by zetok**
may be not available ATM, will be when it'll finish building

### CODE REVIEW

**Comment by zetok** [comment]
works now

**Comment by tux3** [comment]
> dist-build.tox.im

I haven't been on IRC for a long time, is there someplace I can get more info ?

**Comment by zetok** [comment]
from https://jenkins.libtoxcore.so/job/qTox%20OS%20X/225/console:
`Publish artifacts to S3 Bucket bucket=dist-build-tox, file=qtox.dmg region=US_EAST_1, upload from slave=false managed=false`

It's hosted on amazon for muh speed

**Comment by tux3** [comment]
Ok, thanks a lot, that makes sense.

**Comment by dubslow** [comment]
> Amazon
> 
> privacy

https://stallman.org/amazon.html

**Comment by stal888** [comment]
epic :^)

**Pull request merged**
