### PR TITLE
refactor(core): Introduce new class ToxEncrypt to interface with toxe…

### PR DESCRIPTION
**Pull request by sudden6**
Introduces a new class for eveything toxencryptsave related.

The switch of the current code to this class will happen in a followup PR. I intend to use this class as some sort of blueprint for the stuff that will follow, so please point out bad style.

cc @antis81 since it could be interesting for your project too.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4060)

### CODE REVIEW

**Comment by Diadlo** [comment]
Do you plan to use error messages out of the debug? If yes -- add `tr()`

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 97 at r1](https://reviewable.io:443/reviews/qtox/qtox/4060#-Ka3u-ZGmmTK7_01yfUt:-Ka3u-ZHpxI2VrxOhfab:b-3ew7il) ([raw file](https://github.com/qtox/qtox/blob/c3dedaff3839dec58093c16205607631e5a2d9a5/src/core/toxencrypt.cpp#L97)):*
> ```cpp
> bool ToxEncrypt::isEncrypted(const QByteArray& ciphertext)
> {
>     if(ciphertext.length() < TOX_PASS_ENCRYPTION_EXTRA_LENGTH)
> ```

`<=` will be more robust and still correct. What do you think?

---

*[src/core/toxencrypt.cpp, line 101 at r1](https://reviewable.io:443/reviews/qtox/qtox/4060#-Ka3scXZYfA5-lC9f7Ow:-Ka3scX_Tz7av20hK4jc:b-kig5hn) ([raw file](https://github.com/qtox/qtox/blob/c3dedaff3839dec58093c16205607631e5a2d9a5/src/core/toxencrypt.cpp#L101)):*
> ```cpp
>         return false;
>     }
>     return tox_is_data_encrypted(reinterpret_cast<const uint8_t*>(ciphertext.constData()));
> ```

Add new line above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060#-:-Ka3uxqAnxc_l27Nsck8:bwmxa2e)*

**Comment by sudden6** [comment]
Nope, they are for debugging only.

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 97 at r1](https://reviewable.io:443/reviews/qtox/qtox/4060#-Ka3u-ZGmmTK7_01yfUt:-Ka4EiaJRYvX7Mw98MtL:b-vjls2s) ([raw file](https://github.com/qtox/qtox/blob/c3dedaff3839dec58093c16205607631e5a2d9a5/src/core/toxencrypt.cpp#L97)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`<=` will be more robust and still correct. What do you think?
</blockquote></details>

The spec says: `The data must be at least TOX_PASS_ENCRYPTION_EXTRA_LENGTH bytes in length.` and that's exactly what this does.

---

*[src/core/toxencrypt.cpp, line 101 at r1](https://reviewable.io:443/reviews/qtox/qtox/4060#-Ka3scXZYfA5-lC9f7Ow:-Ka4GAabYOfvPfmYtbRS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c3dedaff3839dec58093c16205607631e5a2d9a5/src/core/toxencrypt.cpp#L101)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add new line above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060#-:-Ka4EvfpQNa8z5CnLY1Y:b-pwh8cc)*

**Comment by sudden6** [comment]
Do you think it would be possible and beneficial to completely remove the dependency of `<tox/toxencryptsave.h>` from `toxencrypt.h`?

**Comment by Diadlo** [comment]
1) Don't forget to add sources to CMakeList.txt
2) Removing tox header from Core header looks good. If you plan to use `get..Error()` only for debugging -> make it function in `.cpp` file and remove from `.h` with tox header

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060#-:-Ka6QZXYbh6fDKgNpoE3:b-84u90z)*

**Comment by sudden6** [comment]
Both done.
The next question is, if I should switch to the factory method pattern like @nurupo suggested? I mean the idea sounds quite reasonable and nice, but I have no idea or experience if it's good in the long term.

---

Review status: 1 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060#-:-KaERPtRtgN3tUrFR0Av:bgfkfkk)*

**Comment by zetok** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 51 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabjnYPcDexxXttopjK:-KabjnYPcDexxXttopjL:b-de1z37) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L51)):*
> ```cpp
> 
> /**
>  * @brief  Creates a new ToxEncrypt object, with a random salt.
> ```

What is `ToxEncrypt` for?

Also, what is the use case for using derived key? Why not just limit API usage to functions that require only password?

---

*[src/core/toxencrypt.cpp, line 62 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabjjnxByEbvnP-lSCz:-KabjjnxByEbvnP-lSD-:b-reerwz) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L62)):*
> ```cpp
>                         static_cast<size_t>(pass.length()), &error);
> 
>     if(error != TOX_ERR_KEY_DERIVATION_OK)
> ```

missing space – `if(` → `if (`

Same applies to other occurrences.

---

*[src/core/toxencrypt.cpp, line 119 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabiVnNQcvEBpJ66dl7:-KabiVnNQcvEBpJ66dl8:bcim0yf) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L119)):*
> ```cpp
>         return false;
>     }
> ```

Unnecessary space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by sudden6** [comment]
*[src/core/toxencrypt.cpp, line 51 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabjnYPcDexxXttopjK:-KabpaMAJWUuelEOhQjd:bnoksfp) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L51)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

What is `ToxEncrypt` for?

Also, what is the use case for using derived key? Why not just limit API usage to functions that require only password?
</blockquote></details>

You'll find the explaination ~20 lines above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by zetok** [comment]
Review status: 2 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 51 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabjnYPcDexxXttopjK:-Kac0SSP5y4IzfMQp9O6:b-jk9n90) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L51)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

You'll find the explaination ~20 lines above.
</blockquote></details>

There is only generic sentence on `why`, but it says nothing regarding the actual usage and whether the actual usage is a good use-case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by sudden6** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 62 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabjjnxByEbvnP-lSCz:-KacljuIbFenIyxGpgAt:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L62)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

missing space – `if(` → `if (`

Same applies to other occurrences.
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 119 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabiVnNQcvEBpJ66dl7:-KaclkqQDzmWPqk829kn:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L119)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Unnecessary space.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by Diadlo** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/toxencrypt.cpp, line 169 at r5](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbavkY2OrbMKvQ2kh22:-KbavkY3UctZ8noAcuhG:bj74scd) ([raw file](https://github.com/qtox/qtox/blob/c4daf37e0a3b89580c5425037e0267ada736f179/src/core/toxencrypt.cpp#L169)):*
> ```cpp
> /**
>  * @brief  Factory method for the ToxEncrypt object.
>  * @param  password Password to use for encryption.
> ```

Add `@param toxSave`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060#-:-Kbb4vdS7CBWfbatgp8C:b-jbsf8z)*

**Comment by zetok** [comment]
Reviewed 2 of 4 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 65 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-Kbb8-6_42EAcrER_jn5:-Kbb8-6_42EAcrER_jn6:beiti7v) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L65)):*
> ```cpp
> bool ToxEncrypt::isEncrypted(const QByteArray& ciphertext)
> {
>     if(ciphertext.length() < TOX_PASS_ENCRYPTION_EXTRA_LENGTH)
> ```

Space between `if` and `(`, same goes for other occurrences; `s/ if(/ if (/`

---

*[src/core/toxencrypt.cpp, line 84 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbAXBZxfSxQwhjggMT:-KbbAXBZxfSxQwhjggMU:b-or57mm) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L84)):*
> ```cpp
>     if(password.length() == 0)
>     {
>         qWarning() << "Empty password supplied, probably not what you intended.";
> ```

This should fail; I mean, it will fail anyway during `tox_pass_encrypt`, but…

also `qCritical`, since code that uses this functionality should make sure that password of `0` length would not be supplied to it

---

*[src/core/toxencrypt.cpp, line 98 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-Kbb8qbm8bK_tEtpf4bL:-Kbb8qbm8bK_tEtpf4bM:b-jv1z75) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L98)):*
> ```cpp
>     if(error != TOX_ERR_ENCRYPTION_OK)
>     {
>         qWarning() << getEncryptionError(error);
> ```

wouldn't `qCritical` be better? After all, this is not supposed to fail, and if it does, something would be horribly wrong, and that kind of thing should be fixed ASAP

---

*[src/core/toxencrypt.cpp, line 160 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbACH8lCIjPQdIaA69:-KbbACH8lCIjPQdIaA6A:bwgis3u) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L160)):*
> ```cpp
>     { 
>         tox_pass_key_free(passKey);
>         qWarning() << getKeyDerivationError(error);
> ```

`qCritical` ?

---

*[src/core/toxencrypt.cpp, line 178 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBNmRGmJGJ_CGUP4b:-KbbBNmRGmJGJ_CGUP4c:b4z4y8e) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L178)):*
> ```cpp
>     if(!isEncrypted(toxSave))
>     {
>         qWarning() << "The data was not encrypted using this module or it's corrupted.";
> ```

isn't `qInfo` more appropriate?

---

*[src/core/toxencrypt.cpp, line 200 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBe8u_97dC_r18P4h:-KbbBe8u_97dC_r18P4i:b4x47c5) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L200)):*
> ```cpp
>     if(keyError != TOX_ERR_KEY_DERIVATION_OK)
>     {
> ```

unnecessary newline

---

*[src/core/toxencrypt.cpp, line 218 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBWBCNSTiwUvrDnem:-KbbBWBDCmaI0RwTMfii:b-3ygzo5) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L218)):*
> ```cpp
>     if(!passKey)
>     {
>         qWarning() << "The passKey is invalid.";
> ```

`qCritical`

---

*[src/core/toxencrypt.cpp, line 231 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBa9tgQ-quPndxrqk:-KbbBa9tgQ-quPndxrql:b-3ygzo5) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L231)):*
> ```cpp
>     if(error != TOX_ERR_ENCRYPTION_OK)
>     {
>         qWarning() << getEncryptionError(error);
> ```

`qCritical`

---

*[src/core/toxencrypt.cpp, line 267 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBsKXMMkfMLi9DqBw:-KbbBsKXMMkfMLi9DqBx:b1i0a44) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L267)):*
> ```cpp
>     return ciphertext;
> }
> /**
> ```

newline between curly brace and slash?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by sudden6** [comment]
Review status: 3 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 51 at r3](https://reviewable.io:443/reviews/qtox/qtox/4060#-KabjnYPcDexxXttopjK:-KbbKbZzi3PGctnsvFTg:b-wmox01) ([raw file](https://github.com/qtox/qtox/blob/0e5fa1707c6d33a25066f13fe0cc7f0582481883/src/core/toxencrypt.cpp#L51)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

There is only generic sentence on `why`, but it says nothing regarding the actual usage and whether the actual usage is a good use-case.
</blockquote></details>

added a good reason to use the object

---

*[src/core/toxencrypt.cpp, line 169 at r5](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbavkY2OrbMKvQ2kh22:-KbbICSqJkUbYk186Y6_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c4daf37e0a3b89580c5425037e0267ada736f179/src/core/toxencrypt.cpp#L169)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add `@param toxSave`
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 65 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-Kbb8-6_42EAcrER_jn5:-KbbHnJuCHI6qlpv7LoN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L65)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Space between `if` and `(`, same goes for other occurrences; `s/ if(/ if (/`
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 84 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbAXBZxfSxQwhjggMT:-KbbHpCtIDkqbLj7Gxtg:b-iomefd) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L84)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This should fail; I mean, it will fail anyway during `tox_pass_encrypt`, but…

also `qCritical`, since code that uses this functionality should make sure that password of `0` length would not be supplied to it
</blockquote></details>

An empty password is valid for `tox_pass_encrypt` and this layer is not the correct place to enforce password requirements.

---

*[src/core/toxencrypt.cpp, line 98 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-Kbb8qbm8bK_tEtpf4bL:-KbbI8exywb90VGslRKY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L98)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

wouldn't `qCritical` be better? After all, this is not supposed to fail, and if it does, something would be horribly wrong, and that kind of thing should be fixed ASAP
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 160 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbACH8lCIjPQdIaA69:-KbbKtFs-3PaAq-T78Td:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L160)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`qCritical` ?
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 178 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBNmRGmJGJ_CGUP4b:-KbbIDg45_nPXnbpwUVB:b-t3zxve) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L178)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

isn't `qInfo` more appropriate?
</blockquote></details>

I think `qWarning` is appropriate here, because it can also indicate data corruption.

---

*[src/core/toxencrypt.cpp, line 200 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBe8u_97dC_r18P4h:-KbbIKLkcgPYEP9rBL9z:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L200)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

unnecessary newline
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 218 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBWBCNSTiwUvrDnem:-KbbK6wIZjoi8PNpK6wS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L218)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`qCritical`
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 231 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBa9tgQ-quPndxrqk:-KbbINGEpxM040GIqm4Y:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L231)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`qCritical`
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 267 at r6](https://reviewable.io:443/reviews/qtox/qtox/4060#-KbbBsKXMMkfMLi9DqBw:-KbbIOER4MCd_NagybrS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edaff2912cb14948d56c6deff3535a5865d068ce/src/core/toxencrypt.cpp#L267)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

newline between curly brace and slash?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060)*

**Comment by zetok** [comment]
:lgtm_strong:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4060#-:-KbbiWytZVgEx92dyZfc:b-jbsf8z)*

**Pull request merged**
