### PR TITLE
[Refactor] Create ICoreSettings

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4696)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 11 of 15 files at r1.
Review status: 11 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.h, line 229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6axnFs7UmphVhjTvl:-Kv6axnGVEZXoqIz7VQe:byise0z) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/core/core.h#L229)):*
> ```objc
>     QMutex messageSendMutex;
>     bool ready;
>     const ICoreSettings* const s;
> ```

maybe use non raw pointer?

---

*[src/model/interface.h, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6cyk4nQFjEHodMUWH:-Kv6cyk5QwTa8JGiuPK9:b-g86x7z) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/model/interface.h#L6)):*
> ```objc
> #include <functional>
> 
> #define DECLARE_SIGNAL(name, ...) \
> ```

Can you add documentation to these macros?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696)*

**Comment by Diadlo** [comment]
Review status: 7 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.h, line 229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6axnFs7UmphVhjTvl:-Kv9H65LZ5mtGDxT4cwv:b-milzcw) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/core/core.h#L229)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

maybe use non raw pointer?
</blockquote></details>

There is no memory-management related with this pointer. I don't think, that it make sense

---

*[src/model/interface.h, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6cyk4nQFjEHodMUWH:-Kv9GtCwHpe8EHtvKlhw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/model/interface.h#L6)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you add documentation to these macros?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696)*

**Comment by Talkless** [comment]
Review status: 7 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/persistence/settings.h, line 297 at r2](https://reviewable.io:443/reviews/qtox/qtox/4696#-KvDk734nHF0GiH3-qZ4:-KvDk735aWQFm3kPbU80:b8xvyg2) ([raw file](https://github.com/qtox/qtox/blob/76de4d0adf44388879403f3331480997d3ff1f72/src/persistence/settings.h#L297)):*
> ```objc
> 
>     // ICoreSettings
>     virtual const QList<DhtServer>& getDhtServerList() const override;
> ```

There is no need to declare `virtual` *and* `override` together:
[C.128: Virtual functions should specify exactly one of virtual, override, or final](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696)*

**Comment by Diadlo** [comment]
Review status: 7 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/persistence/settings.h, line 297 at r2](https://reviewable.io:443/reviews/qtox/qtox/4696#-KvDk734nHF0GiH3-qZ4:-KvbbxXDlFiDNGXgQ5yT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76de4d0adf44388879403f3331480997d3ff1f72/src/persistence/settings.h#L297)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

There is no need to declare `virtual` *and* `override` together:
[C.128: Virtual functions should specify exactly one of virtual, override, or final](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696)*

**Comment by sudden6** [comment]
Reviewed 1 of 15 files at r1, 6 of 7 files at r2.
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.h, line 229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6axnFs7UmphVhjTvl:-Kv9UMyWb0znrYiDS1P4:b-e11zk9) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/core/core.h#L229)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

There is no memory-management related with this pointer. I don't think, that it make sense
</blockquote></details>

But we could have a dangling pointer if we are not careful

---

*[src/model/interface.h, line 13 at r2](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv9UYY0CBneqKgjuCzZ:-Kv9UYY0CBneqKgjuCz_:bvd3rp0) ([raw file](https://github.com/qtox/qtox/blob/76de4d0adf44388879403f3331480997d3ff1f72/src/model/interface.h#L13)):*
> ```objc
>  * provide some pure virtual methods, which allow to connect to some signal.
>  *
>  * This file provide macroses to make signals declaring easly. With this macros
> ```

`file provides macros`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696)*

**Comment by Diadlo** [comment]
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.h, line 229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6axnFs7UmphVhjTvl:-KvbsmkhW_JUtP7rCrz8:b-h7p81d) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/core/core.h#L229)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

But we could have a dangling pointer if we are not careful
</blockquote></details>

Be careful ;)
I think, it will add unneeded overhead

---

*[src/model/interface.h, line 13 at r2](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv9UYY0CBneqKgjuCzZ:-KvbssdjN4f4mjdUaRhX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76de4d0adf44388879403f3331480997d3ff1f72/src/model/interface.h#L13)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`file provides macros`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 15 files at r1, 2 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.h, line 229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4696#-Kv6axnFs7UmphVhjTvl:-KvsyZGsMMLjItuNZRZ8:btqa09f) ([raw file](https://github.com/qtox/qtox/blob/40fb35f1a0ce8c65d647dad04c1daa8359d550e2/src/core/core.h#L229)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Be careful ;)
I think, it will add unneeded overhead
</blockquote></details>

ok, I don't feel to strong about this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696#-:-KvsyxebnS-Sskz03CD8:b-jbsf8z)*

**Comment by Diadlo** [comment]
@Talkless lgtm?

**Comment by Talkless** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4696#-:-Kw0sD48Xh425EwQIEJH:b-jbsf8z)*

**Pull request merged**
