### PR TITLE
fix: correct log file format

### LINKED ISSUE #4912: "Save chat log" function should save log with dates
Currently there are only timestamps, which is meaningless when the log covers more than one day.

### PR DESCRIPTION
**Pull request by PKEv**
fix #4912

correct log file format + made equals type of windows: export and save chat log

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5094)

### CODE REVIEW

**Comment by sudden6** [comment]
Can you please rename your commits to match our https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format

**Comment by sudden6** [comment]
you have to rename both commits for Travis CI to pass, use interactive rebase `git rebase -i` and the `edit` command.

**Comment by sudden6** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/widget/form/chatform.cpp, line 1045 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5094#-LAZslhwAhseGMLJ99qu:-LAZslhwAhseGMLJ99qv:b-5aror7) ([raw file](https://github.com/qtox/qtox/blob/562fb8075812e5c84e530228d348f3838ee8e5d5/src/widget/form/chatform.cpp#L1045)):*
> ```cpp
>         QString author = getMsgAuthorDispName(authorPk, it.dispName);
> 
>         QString line = QString("%1\t%2\t%3\t%4\n").arg(datestamp, timestamp, author, it.message);
> ```

what do you think about using a standardized date-time format, ie https://en.wikipedia.org/wiki/ISO_8601

---

*[src/widget/form/genericchatform.cpp, line 490 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5094#-LAZtEAs0THHJ8wgV44V:-LAZtEAs0THHJ8wgV44W:bt05wd4) ([raw file](https://github.com/qtox/qtox/blob/b40f8e1fd30c256e733f885c85c0173994188ed3/src/widget/form/genericchatform.cpp#L490)):*
> ```cpp
>         Timestamp* rightCol = qobject_cast<Timestamp*>(l->getContent(2));
> 
>         if (!rightCol)
> ```

couldn't removing this lead to possible nullptr dereference?

---

*[src/widget/form/genericchatform.cpp, line 497 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5094#-LAZt2N970M4lyS1gvcD:-LAZt2N970M4lyS1gvcE:bn4t1ct) ([raw file](https://github.com/qtox/qtox/blob/562fb8075812e5c84e530228d348f3838ee8e5d5/src/widget/form/genericchatform.cpp#L497)):*
> ```cpp
>         QString msg = middleCol->getText();
> 
>         if (msg.isEmpty())
> ```

coding style mandates curly braces at every `if`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5094)*

**Comment by PKEv** [comment]
@sudden6 

> couldn't removing this lead to possible nullptr dereference?

no it can only be empty

I will make a new push

**Pull request closed without merging**
