### PR TITLE
fix(cameradevice): Save string in local variable to avoid errors

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4752)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4752#-:-KwzsXBZiV63ADGe3kzN:b-jbsf8z)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/video/cameradevice.cpp, line 187 at r1](https://reviewable.io:443/reviews/qtox/qtox/4752#-Kx-k52HApey1dQvvbbu:-Kx-k52HApey1dQvvbbv:b9ts0nf) ([raw file](https://github.com/qtox/qtox/blob/6b88ba57cbd82acee1fc50cfaca3d7bbf5e35f27/src/video/cameradevice.cpp#L187)):*
> ```cpp
>         const QString pixelFormat = v4l2::getPixelFormatString(mode.pixel_format);
>         const std::string pixelFormatStr = pixelFormat.toStdString();
>         const char* pixel_format = pixelFormatStr.c_str();
> ```

Too much intermediate steps, don't you think? Why just not to get `pixel_format` directly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4752)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/video/cameradevice.cpp, line 187 at r1](https://reviewable.io:443/reviews/qtox/qtox/4752#-Kx-k52HApey1dQvvbbu:-Kx-ko0sLd70TEg7rt08:bhg2mqn) ([raw file](https://github.com/qtox/qtox/blob/6b88ba57cbd82acee1fc50cfaca3d7bbf5e35f27/src/video/cameradevice.cpp#L187)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Too much intermediate steps, don't you think? Why just not to get `pixel_format` directly?
</blockquote></details>

Because otherwise temporary string will be destroyed and pointer will be incorrect

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4752)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4752)*

**Comment by Diadlo** [comment]
@noavarice LGTM now?

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4752#-:-Kx79mpgHs6UoDeC9XOM:b-jbsf8z)*

**Pull request merged**
