### PR TITLE
docs(CONTRIBUTING): add more info about shape of PRs

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3815)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3815#-:-KU2zvexNAdZ7SZZfYzy:bnfp4nl)_

**Comment by AliceGrey** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

_[CONTRIBUTING.md, line 64 at r1](https://reviewable.io:443/reviews/qtox/qtox/3815#-KU3u7X0qxXqr_TeClZU:-KU3u7X0qxXqr_TeClZV:b-jji55t) ([raw file](https://github.com/qtox/qtox/blob/efa686280244cb1b1a3892da1650084761d9ce56/CONTRIBUTING.md#L64)):_

> ``` Markdown
> 
> * One topic per PR
> * One commit per PR
> ```

I would add something maybe that explains that commits should be amended during the review process instead of creating multiple commits. This might be something users new to git might not know.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3815)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 64 at r1](https://reviewable.io:443/reviews/qtox/qtox/3815#-KU3u7X0qxXqr_TeClZU:-KU4-rZ87vUfujQAIEma:bmfxqew) ([raw file](https://github.com/qtox/qtox/blob/efa686280244cb1b1a3892da1650084761d9ce56/CONTRIBUTING.md#L64)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> I would add something maybe that explains that commits should be amended during the review process instead of creating multiple commits. This might be something users new to git might not know.
> </details>
> Done..?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3815)_

**Comment by AliceGrey** [comment]
LGTM

**Comment by AliceGrey** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3815#-:-KU6-o8B0C804TR6Hb2w:bnfp4nl)_

**Pull request merged**
