### PR TITLE
chore(build): make cmake use ccache when it's available

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4057)

### CODE REVIEW

**Comment by sudden6** [comment]
Could you add a message to indicate when ccache is used?

**Comment by zetok** [comment]
>Could you add a message to indicate when ccache is used?

Is it really needed, given that e.g. `CMakeCache.txt` states whether it's used?

**Comment by sudden6** [comment]
Yes, it'll help finding possible errors because of ccache, since people usually post the output and not CMakeCache.txt.

**Comment by zetok** [comment]
>Yes, it'll help finding possible errors because of ccache, since people usually post the output and not CMakeCache.txt.

What errors?

**Comment by sudden6** [comment]
Build errors for example, everything that could be caused by ccache being enabled.

**Comment by Diadlo** [comment]
I think it will be easier to ask user to clean cache. I'm not sure, that pasting cache files will be realy helpful

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4057#-:-Ka1XasklqEEOmbVrcLC:b-qj6k2h)*

**Comment by zetok** [comment]
@sudden6 done.

**Comment by sudden6** [comment]
:lgtm_strong:  thx

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4057#-:-KaEGWN_HjD9U0lubEHs:b1g5djr)*

**Pull request merged**
