### PR TITLE
Separate UserDb from History class

### PR DESCRIPTION
**Pull request by Diadlo**
Separated common part for all user information in UserDb. It will help
save all user-related information in database (not only history)

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3822)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/persistence/db/userdb.cpp, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/3822#-KUSDc-9e3NYYz2I38in:-KUSDc-AHjyOpndzOUEP:b44rcct) ([raw file](https://github.com/qtox/qtox/blob/0a6e9f605f2c87de1f3f4ec388d6a8c4450f3adb/src/persistence/db/userdb.cpp#L1)):_

> ``` cpp
> #include "userdb.h"
> ```

Missing copyright header; same goes for other files.

If code was introduced e.g. in 2015, and then modified in 2016 header should have `2015-2016` as a copyright date range.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3822)_

**Comment by Diadlo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/persistence/db/userdb.cpp, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/3822#-KUSDc-9e3NYYz2I38in:-KUSR87z95I9efMEsYWf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0a6e9f605f2c87de1f3f4ec388d6a8c4450f3adb/src/persistence/db/userdb.cpp#L1)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Missing copyright header; same goes for other files.
> 
> If code was introduced e.g. in 2015, and then modified in 2016 header should have `2015-2016` as a copyright date range.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3822)_

**Comment by zetok** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/about/aboutuser.cpp, line 1 at r2](https://reviewable.io:443/reviews/qtox/qtox/3822#-KUSWMRDujnlj0eHPJeH:-KUSWMRDujnlj0eHPJeI:b-f76els) ([raw file](https://github.com/qtox/qtox/blob/0a8d3d64198a23bbc137395d2881c0285d2ff549/src/widget/about/aboutuser.cpp#L1)):_

> ``` cpp
> #include "aboutuser.h"
> ```

Could be also added here. `2015-2016`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3822)_

**Comment by Diadlo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/about/aboutuser.cpp, line 1 at r2](https://reviewable.io:443/reviews/qtox/qtox/3822#-KUSWMRDujnlj0eHPJeH:-KUSdeYub7tUIx__UfKb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0a8d3d64198a23bbc137395d2881c0285d2ff549/src/widget/about/aboutuser.cpp#L1)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Could be also added here. `2015-2016`
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3822)_

**Pull request closed without merging**
