### PR TITLE
fixes the tooltip issue #2868

### PR DESCRIPTION
**Pull request by swrdfish**
Closed pull request #2957 and opened a new one after making the changes in a single commit.

### CODE REVIEW

**Comment by zetok** [comment]
This PR doesn't fix it:
not fixed

**Comment by swrdfish** [comment]
@zetok so, I found the problem, actually there are a few more places that require the same fix. I've now made the same fix to all other places I could find, except in the `src/widget/tool/croppinglabel.cpp` file where I'm getting the following error:

```
src/widget/tool/croppinglabel.cpp:129:12: error: ‘mightBeRichText’ is not a member of ‘Qt’
         if(Qt::mightBeRichText(origText))
```

Need some help here.

**Comment by swrdfish** [comment]
@zetok I've found the solution to that problem and have pushed the required changes. Check if this fixes the issue.

**Comment by zetok** [comment]
Yep, seems to be fixed.

Now someone who can into C++ should look at the code & merge it.

**Comment by sudden6** [comment]
I didn't test this, but from reading the docs I think it would be easier to do something like this:

```
statusMessageLabel->setToolTip(convertFromPlainText(newMessage.toHtmlEscaped(), Qt::WhiteSpaceNormal)
```

So first, escape the message and then make it HTML again, so it does wordwrap.

**Comment by swrdfish** [comment]
@sudden6 yes that should work as well, infact my first quick fix was somethng like this:
`statusMessageLabel->setToolTip( "<span>" + newMessage.toHtmlEscaped() + "</span>" )`

But @TheNain38 suggested that I first check if the message has HTML tags or not and then do the conversion.

**Comment by sudden6** [comment]
@ghoshbinayak I think that `mightBeRichText()` isn't a good idea, because

> It mainly checks whether there is something that looks like a tag before the first line break. Although the result may be correct for common cases, there is no guarantee.

As this is a user controlled input, we should not trust it, to prevent possible attacks.

**Comment by swrdfish** [comment]
@sudden6 yes that is true, but I think that this is what Qt uses before rendering a string in RichText. 

Consider the followinig two situations: 

 with only `&quote;`
screenshot from 2016-02-28 03-33-54

with `&quote;` plus `&lt;` and `&gt;`
screenshot from 2016-02-28 03-35-26
`mightBeRichText()` returns true for strings having `&lt;` or `&gt` but not `&quote;` 

One drawback with my method, as you have pointed out earlier, is that there is no text wrapping. And attacks.. I hadn't even thought of that.

I can change it to your proposed method if that is seems more appropriate to you.

**Comment by sudden6** [comment]
@ghoshbinayak yes, please change it, because it displays exactly what the user entered + text wrapping.

**Comment by swrdfish** [comment]
@sudden6 ok, I have made the required changes. See if it's ok. :)

**Comment by zetok** [comment]
@ghoshbinayak could you remove that merge commit?

**Comment by sudden6** [comment]
@ghoshbinayak For me, it's good.

**Comment by swrdfish** [comment]
@zetok I have squashed the commits into one. I hope thats ok.

**Comment by zetok** [comment]
@ghoshbinayak yep, thanks :)

**Comment by tux3** [comment]
LGTM

**Pull request merged**
