### PR TITLE
chore(tools): allow merging PR to whatever branch is checked out

### PR DESCRIPTION
**Pull request by anthonybilinski**
Useful for either dev testing or merging PRs to dev branches.

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5854)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5854)* status: 0 of 1 LGTMs obtained

___
*[merge-pr.sh, line 55 at r1](https://reviewable.io/reviews/qtox/qtox/5854#-Lpwrhy72p_4aldowxH4:-Lpwrhy72p_4aldowxH5:b-uao6gj) ([raw file](https://github.com/qtox/qtox/blob/425e12b2a39d854dccb72e7734fa75534e8ca185/merge-pr.sh#L55)):*
> ```Shell
>     local remote_name="upstream"
>     local merge_branch="merge"
>     local base_branch=$(git branch | grep \* | cut -d ' ' -f2)
> ```

There might be a more reliable way to do this, see https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch

We should also think about the case of being in a detached HEAD state and maybe abort(?)

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5854)* status: 0 of 1 LGTMs obtained

___
*[merge-pr.sh, line 55 at r1](https://reviewable.io/reviews/qtox/qtox/5854#-Lpwrhy72p_4aldowxH4:-LqAs0rD4c0CeRLe0Qiz:b2daz1w) ([raw file](https://github.com/qtox/qtox/blob/425e12b2a39d854dccb72e7734fa75534e8ca185/merge-pr.sh#L55)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

There might be a more reliable way to do this, see https://stackoverflow.com/questions/1593051/how-to-programmatically-determine-the-current-checked-out-git-branch

We should also think about the case of being in a detached HEAD state and maybe abort(?)
</blockquote></details>

Done. Now, `git symbolic-ref HEAD --short` returns 128 in a detached head state and logs `fatal: ref HEAD is not a symbolic ref`, and the error return causes our `set -e` to abort, so no manual error code checking is required.

**Comment by sudden6** [comment]
Would be good to also update https://github.com/qTox/qTox/blob/master/MAINTAINING.md#pull-requests

**Comment by anthonybilinski** [comment]
Updated stating that you should `checkout`, update, and that it can be used on any branch, to make the changes and usage more clear.

**Review by sudden6 — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5854)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
Assuming that "approved changes" means a LGTM, I'll give a :lgtm_strong:  to unblock CI.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5854#-:-LqoJJ-PCcka_3suaCid:b-7bvn7z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
