### PR TITLE
feat(travis): speedup build

### PR DESCRIPTION
**Pull request by sudden6**
Disable a lot of unneeded codecs in ffmpeg to speedup the build + some smaller tweaks.

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3763)

### CODE REVIEW

**Comment by zetok** [comment]
> feat(travis): speedup build

`s/feat/chore/`, also rest of the commit doesn't describe what has changed

Some of those changes could be also used in windows' `bootstrap.sh` – not the codecs, but other stuff.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[.travis/build-ubuntu-14-04.sh, line 156 at r1](https://reviewable.io:443/reviews/qtox/qtox/3763#-KT3CXtHmOeIHlZUhB3j:-KT3CXtHmOeIHlZUhB3k:b-6b4eie) ([raw file](https://github.com/qtox/qtox/blob/9621974b30ce41be08273277d32ed5cfb4dc84bb/.travis/build-ubuntu-14-04.sh#L156)):_

> ``` Shell
> make clean
> echo '*** BUILDING "FULL" VERSION ***'
> qmake qtox.pro QMAKE_CC="$CC" QMAKE_CXX="$CXX" SMILEYS=MIN
> ```

Which part of the **FULL BUILD** fits with disabled emoticons?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3763#-:-KT3COJiGymHdowvqH6R:b-r3wmjp)_

**Comment by sudden6** [comment]
_[.travis/build-ubuntu-14-04.sh, line 156 at r1](https://reviewable.io:443/reviews/qtox/qtox/3763#-KT3CXtHmOeIHlZUhB3j:-KT3q320xDg7p8u8jiyF:b8ks5qs) ([raw file](https://github.com/qtox/qtox/blob/9621974b30ce41be08273277d32ed5cfb4dc84bb/.travis/build-ubuntu-14-04.sh#L156)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Which part of the **FULL BUILD** fits with disabled emoticons?
> </details>
> `SMILEYS=MIN` enables one emoji pack. From the code perspective it doesn't matter if there's one ore more than one enabled. But I can change it regardless, didn't do much speedup.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3763)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[.travis/build-ubuntu-14-04.sh, line 156 at r1](https://reviewable.io:443/reviews/qtox/qtox/3763#-KT3CXtHmOeIHlZUhB3j:-KT4N_gefRJCa5VWfi_S:bh3jsh0) ([raw file](https://github.com/qtox/qtox/blob/9621974b30ce41be08273277d32ed5cfb4dc84bb/.travis/build-ubuntu-14-04.sh#L156)):_

> From the code perspective it doesn't matter if there's one ore more than one enabled.

Bullshit detected, according to this code: https://github.com/qTox/qTox/blob/14c97da7d5e5d9bb14f23d84460c0aa160142d25/qtox.pro#L246,L247

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3763)_

**Comment by sudden6** [comment]
_[.travis/build-ubuntu-14-04.sh, line 156 at r1](https://reviewable.io:443/reviews/qtox/qtox/3763#-KT3CXtHmOeIHlZUhB3j:-KT55sKPvpYqrjmh9gAY:bql9kzv) ([raw file](https://github.com/qtox/qtox/blob/9621974b30ce41be08273277d32ed5cfb4dc84bb/.travis/build-ubuntu-14-04.sh#L156)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> > From the code perspective it doesn't matter if there's one ore more than one enabled.
> 
> Bullshit detected, according to this code: https://github.com/qTox/qTox/blob/14c97da7d5e5d9bb14f23d84460c0aa160142d25/qtox.pro#L246,L247
> </details>
> That's not code, that's the build system (at least how I see it). Also this line doesn't make much difference, besides not including all emoji. Why do you think it's necessary?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3763)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[.travis/build-ubuntu-14-04.sh, line 156 at r1](https://reviewable.io:443/reviews/qtox/qtox/3763#-KT3CXtHmOeIHlZUhB3j:-KT8Uj5SN8EOxhbb7p3b:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9621974b30ce41be08273277d32ed5cfb4dc84bb/.travis/build-ubuntu-14-04.sh#L156)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> That's not code, that's the build system (at least how I see it). Also this line doesn't make much difference, besides not including all emoji. Why do you think it's necessary?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3763)_

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3763#-:-KT8j_RryEky_1LavPbm:bnfp4nl)_

**Pull request merged**
