### PR TITLE
refactor: message text formatting improved

### LINKED ISSUE #3804: text formatting fucks up lists
##### Brief Description

Text formatting in qTox can easily fuck up lists.

qTox version: v1.5.2-144-gbbdd4f0
Commit hash: bbdd4f044c2c6b70fcb8794c8e5f01f1380af168
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always
##### Steps to reproduce
1. Setting `Text Style format: Don't show formatting characters`
2. Send list, e.g. text sample
##### Observed Behavior

List is fucked up
##### Expected Behavior

List shouldn't be affected
##### Additional Info

Text sample:

```
tips:
* use eix
* equery --help → `equery u`
* perhaps don't use a lot of global USE flags
```

spectacle eg4807

### PR DESCRIPTION
**Pull request by noavarice**
Also added simple tests and fix #3804

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4186)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4186#-KdM1sIAWoAdODMDgTNC:-KdM1sIBQlsc6XrTkYJY:bsruq3g) ([raw file](https://github.com/qtox/qtox/blob/d015b61ac33210c6b26b6fbae6db294ff0a48678/src/chatlog/textformatter.cpp#L1)):*
> ```cpp
> #include "textformatter.h"
> ```

Missing copyright notice, same goes for other new files

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4186)*

**Comment by noavarice** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4186#-KdM1sIAWoAdODMDgTNC:-KdMIPOP4LUGgi2-lXFI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d015b61ac33210c6b26b6fbae6db294ff0a48678/src/chatlog/textformatter.cpp#L1)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Missing copyright notice, same goes for other new files
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4186)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 5 of 8 files at r1, 4 of 5 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4186#-:-KdN8wpo-hXGpWdD573o:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4186#-:-KdNGTnSPc2eKZTmu6qJ:b-jbsf8z)*

**Pull request merged**
