### PR TITLE
[Feat] Exit from group with middle mouse click

### PR DESCRIPTION
**Pull request by Diadlo**
* Add ability to quit group with middle mouse click
* Add ability to remove dialog from content dialog with middle mouse click

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4830)

### CODE REVIEW

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4830#-L11tCZQ59mvSfVgQdqq:-L11tCZQ59mvSfVgQdqr:b-ixhwkg) ([raw file](https://github.com/qtox/qtox/blob/b97f56872e02dc701e583d5970b14fc091bd0d40/src/widget/widget.cpp#L1229)):*
> ```cpp
>     friendWidget->setStatusMsg(widget->getStatusMsg());
> 
>     auto widgetRemoveFriend = static_cast<void (Widget::*)(int)>(&Widget::removeFriend);
> ```

maybe adding `TODO: Qt >= 5.7: use qOverload()` would be usefull in cases like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4830)*

**Comment by Diadlo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1229 at r1](https://reviewable.io:443/reviews/qtox/qtox/4830#-L11tCZQ59mvSfVgQdqq:-L16zVKBEPtWRbV3IcFH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b97f56872e02dc701e583d5970b14fc091bd0d40/src/widget/widget.cpp#L1229)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

maybe adding `TODO: Qt >= 5.7: use qOverload()` would be usefull in cases like this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4830)*

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1244 at r2](https://reviewable.io:443/reviews/qtox/qtox/4830#-L2jv_FxHXiOOlU04xab:-L2jv_FylSDCTmnH-DsP:b-jo11w8) ([raw file](https://github.com/qtox/qtox/blob/60aaf6df251220e8ffdbc22fe03896c075842bca/src/widget/widget.cpp#L1244)):*
> ```cpp
> 
> #if (QT_VERSION >= QT_VERSION_CHECK(5, 7, 0))
>     auto widgetRemoveFriend = QOverload<int>::of(&Widget::removeFriend);
> ```

There are two more places below where overload cast is used.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4830)*

**Comment by Diadlo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 1244 at r2](https://reviewable.io:443/reviews/qtox/qtox/4830#-L2jv_FxHXiOOlU04xab:-L2ydyUOjmg_RzVTzv4e:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60aaf6df251220e8ffdbc22fe03896c075842bca/src/widget/widget.cpp#L1244)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

There are two more places below where overload cast is used.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4830)*

**Comment by Diadlo** [comment]
@qTox/core ping?

**Comment by sudden6** [comment]
Seems to cause a build error atm?

**Comment by Diadlo** [comment]
@sudden6 Damn. Was problems with the rebase. Should be fixed now

**Comment by tox-user** [comment]
Why is this change needed? It doesn't seem very intuitive to leave a group by pressing the middle mouse button, but I might be wrong.

**Comment by Diadlo** [comment]
@tox-user Better discuss it in #2605. But removing a friend dialog from a separate dialog window looks intuitive because it's like tabs in a browser

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/4830#-:-LCNrz-uDuNAr5T0Ggyt:b-jbsf8z)*

**Pull request merged**
