### PR TITLE
fix(init): register AV connects and call after AV is ready

### LINKED ISSUE #4406: [Regression] Warning: QObject::connect: invalid null parameter
I am getting an error: `:0 : Warning: QObject::connect: invalid null parameter` on startup.
This is consistently reproducible since 7e3ad7ba873615f4b7a65071d678ac936f7504e7.
As far as I can tell the problem seems to be that `av` is `null` in lines 237-238 in above mentioned commit:
```cpp
    CoreAV* av = core->getAv();
    connect(av, &CoreAV::avEnd, this, &Widget::onCallEnd);
```
I think this is because `Core::getAv` is called **before** `Core::start` initializes the returned `av`.

Full log: [log.txt](https://github.com/qTox/qTox/files/999624/log.txt)

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4406

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4651)

### CODE REVIEW

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/core.cpp, line 248 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5WkX67GahcWujOYjg:-Ku5WkX67GahcWujOYjh:b1njqhb) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L248)):*
> ```cpp
>         emit failedToStart();
>     }
>     for (auto callback : toCallWhenAvReady) {
> ```

`const auto& callback` I believe, not sure why would it need a copy.

---

*[src/core/core.cpp, line 249 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5XfwJKvkiCCbOaKXj:-Ku5XfwJKvkiCCbOaKXk:baxbahf) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L249)):*
> ```cpp
>     }
>     for (auto callback : toCallWhenAvReady) {
>     	callback(av);
> ```

If this >> means tab here in Reviewable? Then it should be replaced to spaces.

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Y83D-J3UVyhMOk_I:-Ku5Y83EhNt9mGOifd7d:b-oilb38) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
> ```cpp
> }
> 
> void Core::callWhenAvReady(std::function<void(CoreAV* av)> toCall)
> ```

Should be `const &`, std::function likely to have dynamic allocations, would be nice to avoid additional copies here. It will be copied into container later once.

Or, you assume that here gonna be two moves? (into callWehnAvReady() and into empalce_back())?

If yes, I am kinda sure that you need `.emplace_back(std::move(toCall))` because `toCall` is a variable with a name (lvalue), so emplace_back() will simply use copy constructor.

---

*[src/core/core.cpp, line 1397 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Xp_AG5g26rU0H1kV:-Ku5Xp_AG5g26rU0H1kW:b20nc9j) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1397)):*
> ```cpp
> void Core::callWhenAvReady(std::function<void(CoreAV* av)> toCall)
> {
> 	toCallWhenAvReady.emplace_back(toCall);
> ```

Spaces, no tabs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by anthonybilinski** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/core.cpp, line 248 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5WkX67GahcWujOYjg:-Ku6U5l1EUR0zJ0xLXPo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L248)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const auto& callback` I believe, not sure why would it need a copy.
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 249 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5XfwJKvkiCCbOaKXj:-Ku6U5fBfZ8YTJiJfru2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L249)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

If this >> means tab here in Reviewable? Then it should be replaced to spaces.
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Y83D-J3UVyhMOk_I:-Ku6UmW3qZrU0oWRtNza:b-ho07pn) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Should be `const &`, std::function likely to have dynamic allocations, would be nice to avoid additional copies here. It will be copied into container later once.

Or, you assume that here gonna be two moves? (into callWehnAvReady() and into empalce_back())?

If yes, I am kinda sure that you need `.emplace_back(std::move(toCall))` because `toCall` is a variable with a name (lvalue), so emplace_back() will simply use copy constructor.
</blockquote></details>

changed to const &, this removes the need for std::move, correct?

---

*[src/core/core.cpp, line 1397 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Xp_AG5g26rU0H1kV:-Ku6UyfeinF3D3BzEGQ7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1397)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Spaces, no tabs.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by sudden6** [comment]
:lgtm_strong: please someone else also take a look

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651#-:-Ku8qPtalJDTTwNsE2VV:bd2wdmc)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Y83D-J3UVyhMOk_I:-Ku8nthtim-1n2fwZ9hd:b-8imfc6) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

changed to const &, this removes the need for std::move, correct?
</blockquote></details>

AFAIC, `std::move(toCall)` must not work here anyway, because `toCall` is a constant object which cannot be moved

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku95kkYXS9_7WYUlmiK:-Ku95kkYXS9_7WYUlmiL:bqft0b9) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
> ```cpp
> }
> 
> void Core::callWhenAvReady(std::function<void(CoreAV* av)> toCall)
> ```

You need to take rvalue reference: `std::function<void(CoreAV* av)>&& toCall)` and still std::move()-it into container. It's strange (welp, it's C++ :-) ), but parameter is rvalue reference for the *callers*, not for the function body itself.

See for sink function example: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f18-for-consume-parameters-pass-by-x-and-stdmove-the-parameter

If it has a name, it's lvalue reference, and not gonna be moved from by default (unless it's in return statement AFAIK, local variable can be moved into function result).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by anthonybilinski** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Y83D-J3UVyhMOk_I:-Ku9EBCTqcxOW454fx6Z:b3tq0fi) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

AFAIC, `std::move(toCall)` must not work here anyway, because `toCall` is a constant object which cannot be moved
</blockquote></details>

It compiles, FYI. Not sure why..

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku95kkYXS9_7WYUlmiK:-Ku9EGQ1088JevavlL1P:bh6xkx7) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

You need to take rvalue reference: `std::function<void(CoreAV* av)>&& toCall)` and still std::move()-it into container. It's strange (welp, it's C++ :-) ), but parameter is rvalue reference for the *callers*, not for the function body itself.

See for sink function example: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#f18-for-consume-parameters-pass-by-x-and-stdmove-the-parameter

If it has a name, it's lvalue reference, and not gonna be moved from by default (unless it's in return statement AFAIK, local variable can be moved into function result).



</blockquote></details>

Changed from const& to rvalue reference, with a std::move into container, as per cpp core guidelines recommendation linked. Thanks for the in-depth feedback :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by noavarice** [comment]
Review status: 1 of 3 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 1395 at r1](https://reviewable.io:443/reviews/qtox/qtox/4651#-Ku5Y83D-J3UVyhMOk_I:-KuBKJs4efLBSP_THJ4k:b8oxhmd) ([raw file](https://github.com/qtox/qtox/blob/186b3a71de9be760ba81637e0f45cf4c7433b911/src/core/core.cpp#L1395)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

It compiles, FYI. Not sure why..
</blockquote></details>

It's not about compiling, this just will do the copy of `toCall` silently

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651#-:-KuPzAJsC8yGeiMZqOVR:b-jbsf8z)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651#-:-Kw8zSohD1BFdIp2fNkP:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
rebased back to tip

**Comment by noavarice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.h, line 230 at r4](https://reviewable.io:443/reviews/qtox/qtox/4651#-KwVAx-ieSIOqh5f1z0D:-KwVAx-ieSIOqh5f1z0E:b-pke3vz) ([raw file](https://github.com/qtox/qtox/blob/7170b48589c88eaa33263ffb0155dbf384b82d56/src/core/core.h#L230)):*
> ```objc
>     bool ready;
>     const ICoreSettings* const s;
>     std::vector<std::function<void(CoreAV* av)>> toCallWhenAvReady;
> ```

Why not `std::list` if we only need to push items back and iterate through them?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by noavarice** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.h, line 230 at r4](https://reviewable.io:443/reviews/qtox/qtox/4651#-KwVAx-ieSIOqh5f1z0D:-KwVJhvVHv00jljpwZrx:bvy6frk) ([raw file](https://github.com/qtox/qtox/blob/7170b48589c88eaa33263ffb0155dbf384b82d56/src/core/core.h#L230)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why not `std::list` if we only need to push items back and iterate through them?
</blockquote></details>

And how `std::list` is better in this case? `std::vector` should be default container by all the C++ Gods recommendations :-) . `std::list` is double-linked list, meaning every node is dynamically allocated, with lot's of indirections through pointers when you "only" iterate.

One should use `std::list` when you do a lot of prepending, inserting into the middle, and need stable references when removing (AFAIK), and probably argued with a benchmark on top of it :-) .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.h, line 230 at r4](https://reviewable.io:443/reviews/qtox/qtox/4651#-KwVAx-ieSIOqh5f1z0D:-KwVSuoPp7oYAlt4bWcr:b-4hvi0r) ([raw file](https://github.com/qtox/qtox/blob/7170b48589c88eaa33263ffb0155dbf384b82d56/src/core/core.h#L230)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

And how `std::list` is better in this case? `std::vector` should be default container by all the C++ Gods recommendations :-) . `std::list` is double-linked list, meaning every node is dynamically allocated, with lot's of indirections through pointers when you "only" iterate.

One should use `std::list` when you do a lot of prepending, inserting into the middle, and need stable references when removing (AFAIK), and probably argued with a benchmark on top of it :-) .
</blockquote></details>

Got it)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4651)*

**Comment by noavarice** [comment]
:lgtm_strong:

**Pull request merged**
