### PR TITLE
feat(toxencrypt): add function to get min length for isEncrypted() to

### PR DESCRIPTION
**Pull request by sudden6**
succeed

Also improve documentation

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4131)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 154 at r1](https://reviewable.io:443/reviews/qtox/qtox/4131#-KcDzi9DLXAlfYM0I-il:-KcDzi9DLXAlfYM0I-im:bbm7zc7) ([raw file](https://github.com/qtox/qtox/blob/6e728b0473af0c116f29472cc96ac8fd8edee92e/src/core/toxencrypt.cpp#L154)):*
> ```cpp
> 
> /**
>  * @brief  Factory method for the ToxEncrypt object. Derives a key from the
> ```

I prefer use only first sentence as brief. The rest should be a function description (without doxygen tag)

---

*[src/core/toxencrypt.cpp, line 179 at r1](https://reviewable.io:443/reviews/qtox/qtox/4131#-KcDzitv-6AVfv5THqpy:-KcDzitv-6AVfv5THqpz:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/6e728b0473af0c116f29472cc96ac8fd8edee92e/src/core/toxencrypt.cpp#L179)):*
> ```cpp
> 
> /**
>  * @brief  Factory method for the ToxEncrypt object. Derives a key from the
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4131)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/toxencrypt.h, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/4131#-KcE-9CVjRKt8hUeIRIv:-KcE-9CVjRKt8hUeIRIw:b-t77zai) ([raw file](https://github.com/qtox/qtox/blob/6e728b0473af0c116f29472cc96ac8fd8edee92e/src/core/toxencrypt.h#L48)):*
> ```objc
> 
> private:
>     ToxEncrypt(Tox_Pass_Key* key);
> ```

Also, while you are still here. Can you make this constructor `explicit`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4131)*

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 154 at r1](https://reviewable.io:443/reviews/qtox/qtox/4131#-KcDzi9DLXAlfYM0I-il:-KcFIe_S9uQyf-qHUo5V:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6e728b0473af0c116f29472cc96ac8fd8edee92e/src/core/toxencrypt.cpp#L154)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I prefer use only first sentence as brief. The rest should be a function description (without doxygen tag)
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 179 at r1](https://reviewable.io:443/reviews/qtox/qtox/4131#-KcDzitv-6AVfv5THqpy:-KcFIfPN9MDzf05wzLLZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6e728b0473af0c116f29472cc96ac8fd8edee92e/src/core/toxencrypt.cpp#L179)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/core/toxencrypt.h, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/4131#-KcE-9CVjRKt8hUeIRIv:-KcFIgsQqjDgiUn-okef:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6e728b0473af0c116f29472cc96ac8fd8edee92e/src/core/toxencrypt.h#L48)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Also, while you are still here. Can you make this constructor `explicit`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4131)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4131#-:-KcGvbRgz2oOzuPSWUB7:b-jbsf8z)*

**Pull request merged**
