### PR TITLE
docs(INSTALL): Remove info about unsupported Debian 8

### LINKED ISSUE #4574: is Debian 8 (Jessie) no logner supported?
Commit https://github.com/qTox/qTox/commit/90910cbfe14f78fd3f03ce6318953967c05ec1c0 upped Qt version to 5.5.

Debian 8 does not have 5.5, only 5.3.

Meanwhile, [INSTALL.md](https://github.com/qTox/qTox/blob/5d159e0203bdd0e72153cce9ca5c0fe8483ba0db/INSTALL.md#debian-1) states that Debian 8 is supported.

So how it is in the end?

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4574

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4576)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4576#-:-KrgLqYdoJF8sD2ZNxGE:b-jbsf8z)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 287 at r1](https://reviewable.io:443/reviews/qtox/qtox/4576#-KrmkU6rX55miLW-XS1q:-KrmkU6rX55miLW-XS1r:b-bwbfx4) ([raw file](https://github.com/qtox/qtox/blob/ee7c7a6be5eaedcdfc4d5d54329fec4e0e996756/INSTALL.md#L287)):*
> ```Markdown
> ```
> 
> **Go to [FFmpeg](#ffmpeg) section to compile it.**
> ```

This line also should be removed.

---

*[INSTALL.md, line 522 at r1](https://reviewable.io:443/reviews/qtox/qtox/4576#-KrmklmrPp0zIAEJZYdG:-KrmklmrPp0zIAEJZYdH:bucn3o6) ([raw file](https://github.com/qtox/qtox/blob/ee7c7a6be5eaedcdfc4d5d54329fec4e0e996756/INSTALL.md#L522)):*
> ```Markdown
> 
> If you had to compile [FFmpeg](#ffmpeg) manually, run this script from qTox
> directory before starting qTox:
> ```

This and relevant stuff below should be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4576)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 287 at r1](https://reviewable.io:443/reviews/qtox/qtox/4576#-KrmkU6rX55miLW-XS1q:-KrnwGzIDDiON7oBPsLw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ee7c7a6be5eaedcdfc4d5d54329fec4e0e996756/INSTALL.md#L287)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This line also should be removed.
</blockquote></details>

Done.

---

*[INSTALL.md, line 522 at r1](https://reviewable.io:443/reviews/qtox/qtox/4576#-KrmklmrPp0zIAEJZYdG:-KrnwHCMUUcKe4pp-VPq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ee7c7a6be5eaedcdfc4d5d54329fec4e0e996756/INSTALL.md#L522)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

This and relevant stuff below should be removed.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4576)*

**Comment by zetok** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4576#-:-Krrv-UyThsqXWy2zhLB:b-jbsf8z)*

**Pull request merged**
