### PR TITLE
fix(build): Fix regression in how cmake finds libraries

### LINKED ISSUE #4680: [Regression] Can't set auto away time
OS: Ubuntu 16.04
Commit hash:  8108bfdc

Reproducible: Always

On commit 8108bfdc and its descendants, my auto away time is greyed out and unselectable.
image

On commit ed634ae0 (it's only parent) it works as expected.

### PR DESCRIPTION
**Pull request by nurupo**
@anthonybilinski can you check if it fixes #4680?

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4688)

### CODE REVIEW

**Comment by nurupo** [comment]
I should probably specify a header file name for `libxss` instead.

**Comment by nurupo** [comment]
Nah, I have changed my mind, this change I have made is good enough, no need to specify the header file name for `libxss`, because then I'd need to specify header file names for all of the libraries, which is really unnecessary.

The whole point of specifying a header file name is for the case when a library is not found using `pkg-config` and doesn't have headers installed system-wide, i.e. when a library is installed in a custom location (e.g. `/hom/nurupo/stuff/libfoo`) and it either 1) doesn't provide `.pc` files or 2) whoever builds qTox didn't set the pkg-config env variables to point to those `*.pc` files. It would be nice to have support for such fallback for every single library that we find using `search_dependency()`, but there are a bit too many of them for me to tackle:

```
$ grep search_dependency CMakeLists.txt 
  search_dependency(GDK_PIXBUF  PACKAGE gdk-pixbuf-2.0   OPTIONAL)
  search_dependency(GLIB        PACKAGE glib-2.0         OPTIONAL)
  search_dependency(GTK         PACKAGE gtk+-2.0         OPTIONAL)
  search_dependency(APPINDICATOR PACKAGE appindicator-0.1)
  search_dependency(GDK_PIXBUF   PACKAGE gdk-pixbuf-2.0)
  search_dependency(GLIB         PACKAGE glib-2.0)
  search_dependency(GTK          PACKAGE gtk+-2.0)
    search_dependency(GTK       PACKAGE gtk+-2.0         OPTIONAL)
    search_dependency(FILTERAUDIO LIBRARY filteraudio HEADER filter_audio.h OPTIONAL)
$ grep search_dependency cmake/Dependencies.cmake 
function(search_dependency pkg)
search_dependency(LIBAVCODEC          PACKAGE libavcodec)
search_dependency(LIBAVDEVICE         PACKAGE libavdevice)
search_dependency(LIBAVFORMAT         PACKAGE libavformat)
search_dependency(LIBAVUTIL           PACKAGE libavutil)
search_dependency(LIBEXIF             PACKAGE libexif)
search_dependency(LIBQRENCODE         PACKAGE libqrencode)
search_dependency(LIBSODIUM           PACKAGE libsodium)
search_dependency(LIBSWSCALE          PACKAGE libswscale)
search_dependency(SQLCIPHER           PACKAGE sqlcipher)
search_dependency(VPX                 PACKAGE vpx)
search_dependency(TOXCORE             PACKAGE toxcore          OPTIONAL)
search_dependency(TOXAV               PACKAGE toxav            OPTIONAL)
search_dependency(TOXENCRYPTSAVE      PACKAGE toxencryptsave   OPTIONAL)
    search_dependency(TOXCORE         PACKAGE libtoxcore)
    search_dependency(TOXAV           PACKAGE libtoxav)
search_dependency(OPENAL              PACKAGE openal)
  search_dependency(X11                 PACKAGE x11 OPTIONAL)
  search_dependency(XSS                 LIBRARY Xss OPTIONAL)
  search_dependency(AVFOUNDATION      FRAMEWORK AVFoundation)
  search_dependency(COREMEDIA         FRAMEWORK CoreMedia   )
  search_dependency(COREGRAPHICS      FRAMEWORK CoreGraphics)
  search_dependency(FOUNDATION        FRAMEWORK Foundation  OPTIONAL)
  search_dependency(IOKIT             FRAMEWORK IOKit       OPTIONAL)
  search_dependency(OPENSSL           PACKAGE openssl)
```

So if someone wants, they can specify header files for all of those libs in a separate PR.

Also, although it would be nice to have support for such fallback, you also might want to question whether it's really necessary to support it. We could just assume that all libraries that we search using `search_dependency(PACKAGE)` must have pkg-config configured correctly or have headers installed system-wide, while the ones we search with `search_dependency(LIBRARY)` (which is just `libfilteraudio`) must either have header installed system-wide or have header filename provided with `HEADER` to search in custom paths. It looks like there is nothing wrong with such assumption, qTox builds without issues on Linux and it also cross-compiles to Windows just fine.

**Comment by sudden6** [comment]
:lgtm_strong:

@anthonybilinski when you give lgtm I'll merge this.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4688#-:-KusjNc_dqEfjs5psAk_:b-2001ah)*

**Comment by sudden6** [comment]
@nurupo I agree with you that specifying the header file optionally is good enough. As for the special case of libXss I think we should switch to pkg-config like in my other PR.

**Comment by nurupo** [comment]
Yeah, both PRs should be merged.

**Comment by anthonybilinski** [comment]
cmake output finds XSS now, and setting works again. :lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4688#-:-Kuu4F2qQlEjpHLKbesr:byxksmg)*

**Pull request merged**
