### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by ovalseven8**
Some translation changes

### CODE REVIEW

**Comment by agilob** [comment]
This can be merged but more texts to translate will be merged soon. Do you want me to merge it now or wait for other PRs?

**Comment by ovalseven8** [comment]
Then I will wait a few days and update the PR. :)

**Comment by agilob** [comment]
I would love to merge PRs from @TheSpiritXIII before Tuesday, I'm working on other small fixes these days.

**Comment by ghost** [comment]
@agilob any news? I'm waiting to push the Spanish translation.

**Comment by agilob** [comment]
I expected some minor PR to be merged quicker...

**Comment by ovalseven8** [comment]
@agilob @antis81 
It's ready for merging now! :)
Changes from #2171 are included.

**Comment by ovalseven8** [comment]
@antis81 
By the way, I didn't use for example a space before '...' because it is common not to use one. Looks better too.

Some original English translations are wrong/buggy, perhaps I will change a few if I have time. But probably it makes sense the most if we do this when qTox is in a more stable status.

**Comment by antis81** [comment]
@ovalseven8 If space before a … is correct German language, we should respect this. I didn't know that either and it doesn't hurt anyway. @aaannndddyyy's PR is ready to merge and cleaned up now.

**Comment by ovalseven8** [comment]
@antis81 
Well, I don't understand your handling. All improvements from #2171 are included here, as arranged, to prevent conflicts/confusions because of too many PRs.
Also, #2171 doesn't actually update the language file at all. The line numbers aren't up-to-date and additional translations not included because https://github.com/tux3/qTox/wiki/Translating was not followed.

**Comment by antis81** [comment]
@ovalseven8 Sorry, I wasn't aware of the [HowTo](https://github.com/tux3/qTox/wiki/Translating). I don't have time now -> reply tomorrow.

@aaannndddyyy FYI

**Comment by aaannndddyyy** [comment]
@ovalseven8 : no, only some of the #2171 changes are included here. Yes I have only updated the strings. But we have fixed quite some errors over there.

**Comment by ovalseven8** [comment]
@aaannndddyyy: Yes, saw that you made some changes recently. I will update this PR tomorrow and then we can look through it together before merging. :)

**Comment by aaannndddyyy** [comment]
sure, no hurry. I was just letting you know in case you missed them. I squashed them for better merging, but if/when this one contains all the improvements, then I need not worry about number of commits of mine anymore and can delete mine.
Now, it's Feuerabend though. 
Good night.

**Pull request closed without merging**
