### PR TITLE
PNG images replaced with SVG

### LINKED ISSUE #1050: Use svg instead of png
I already bumped into this problem even though i am not using HiDPI monitor. Tray icons do not scale good when size of taskbar changes. This is especially true on linux where users have more freedom to change things like this. Changing tray icon format to svg immediately offers perfect solution and on top of that we can get rid of `_2x` icons. I think client should completely migrate to using svg simply because thats the format design is done in anyway and it offers perfect scaling. Someone with HiDPI monitor should comment on this too.

### PR DESCRIPTION
**Pull request by ghost**
Closes #1050
## 

This changeset is **not done** yet. **Do not merge**.
I need several svg images that i was not able to find and they were not simple enough to justify remaking them (hey im not an artist, best i can do is round circles).

```
./img/android/menu.png
./img/android/search.png
./img/settings/general.png
./img/settings/identity.png
./img/settings/privacy.png
./img/settings/av.png
./ui/micButton/micButton.png
./ui/volButton/volButton.png
```

@ItsDuke / @dubslow / @tux3 know anything about these images? Maybe android ones are optional?

I also intend to add a setting for UI scaling (much like in uTox).

### CODE REVIEW

**Comment by dubslow** [comment]
@retuxx I believe is responsible for the /img/settings images, and @Xylemon did the new, prettier mic/volume buttons

**Comment by Xylemon** [comment]
Yeah the Mic and Volume button were done by me. I'd highly recommend using @ItsDuke mic and speaker icons, as they're much better than mine and I also did not make mine scalable since I don't have lot of knowledge regarding the SVG format: https://github.com/notsecure/uTox/issues/666

**Comment by tux3** [comment]
The android ones are, of course, only for android (which is still a prototype).

**Comment by zetok** [comment]
@novist wouldn't just changing font size be better than setting for scaling whole UI?
Also, shouldn't be UI scaled depending on DPI given by OS (or something..) ?

**Comment by ghost** [comment]
According to [docs](https://doc-snapshots.qt.io/qt5-5.4/highdpi.html) only windows and osx are dpi-aware so i think those would not need separate setting. There is no mention of linux though. So im not sure what situation is there. Or maybe this would just require Qt update?

```
Qt 5.4 introduces experimental support for scaling by by device pixel ratio similar to OS X to the platform plugins for Windows and Unix (XCB). This is controlled by the environment variable QT_DEVICE_PIXEL_RATIO.
```

Also we cant really change just font size because if small font is upscaled then it would clip in lots of places in small UI, if big font is downscaled then it would look fine but still in very small and unusable window.

**Comment by zetok** [comment]
> Also we cant really change just font size because if small font is upscaled then it would clip in lots of places in small UI, if big font is downscaled then it would look fine but still in very small and unusable window.

Thing is, for plenty of people current font is already too small. IMHO scaling UI isn't needed when there's only need to make font bigger.

Issue with clipped text.. I don't think that any software handles well oversized text.

> There is no mention of linux though. So im not sure what situation is there.

Dunno really. X has its own thing for DPI scaling that is passed somehow to software running under it, and when it comes to Wayland.. it's job of compositor…

**Comment by ArchangeGabriel** [comment]
I have a HiDPI screen here (3200x1800), running KDE5 on ArchLinux, if you want me to test things.

**Comment by ghost** [comment]
@zetok my friend actually complained that font on windows is indeed too small. I was meaning to add option for that but somehow never did.

@ArchangeGabriel thats great. If you could run qTox in that environment and report us how it works it would be great. I suspect without this patch you should see blurry images if application UI is upscaled automatically. And with this patch blur should go away in 99% of images. Please let us know of test results.

**Comment by ArchangeGabriel** [comment]
Note sure to be able to say if they are blurry or not currently. Joined a snapshot.
snapshot

Since I don’t know what is the expected size of the UI, not sure wether it’s upscaled or not.

Could you export this commit into a patch for me to test it easily? Thanks.

**Comment by ghost** [comment]
@ArchangeGabriel to me it seems that only text was upscaled but not other elements, therefore they look too small and not blurry. Am i correct?

If my assumption is right then testing this patch would yield same results. Anyhow if you still wish to try you can just check out branch on my repo and build it: https://github.com/novist/qTox/tree/svg

**Comment by dubslow** [comment]
Alternately, @ArchangeGabriel GitHubTip:

https://github.com/tux3/qTox/pull/1378 -> https://github.com/tux3/qTox/pull/1378.patch

@novist Mind if I merge it as is, even with a few still missing SVG? It seems that it may take a while to get some of those

**Comment by dubslow** [comment]
Looks like you're missing two svgs:

```
RCC: Error in 'res.qrc': Cannot find file 'ui/acceptCall/acceptCall.svg'
RCC: Error in 'res.qrc': Cannot find file 'ui/rejectCall/rejectCall.svg'
```

They are indeed in your res.qrc but don't exist in the commit.

**Comment by ghost** [comment]
Since @ItsDuke is abducted by aliens i guess you can merge it. I also pushed missing images, sorry about that ;)

**Comment by dubslow** [comment]
Could you amend that into the other commit :P

**Comment by ArchangeGabriel** [comment]
OK, so now it’s even merged I can confirm it doesn’t change anything visually, so the elements might indeed be too small.

**Comment by ItsDuke** [comment]
@novist et al:

Sorry about being incommunicado for awhile, I've just been getting slammed with personal and professional appointments that make it hard to be on here as often as I'd like. So where do we currently stand with this?

**Comment by ghost** [comment]
Still dont have svg images for these:

```
./img/android/menu.png
./img/android/search.png
./img/settings/general.png
./img/settings/identity.png
./img/settings/privacy.png
./img/settings/av.png
./ui/micButton/micButton.png
./ui/volButton/volButton.png
```

Since @Xylemon did not make svg variants of settings images we need volunteer to make those svgs. Also he indicated that mic and volume buttons in your other mockup look better so i would like to get those svgs.

As you can see this got merged already, since very little is missing. And it works great. One thing that does not happen yet is UI scaling on HDPI monitors but i think it is due to used version of Qt not supporting this yet.

So @ItsDuke, do you volunteer to make some more missing svg magic? :)

**Comment by ItsDuke** [comment]
@novist sure thing. Where are these images used, so I can get an idea of how they're being implemented currently?

**Comment by dubslow** [comment]
They are the images for the settings tabs (click on the settings button, and also on your own name/avatar to open your profile settings form with a similar layout and image), and also the mic and volume buttons next to the main audio and video call buttons.

**Comment by ItsDuke** [comment]
@dubslow I don't have a recent version installed, could you take a screenshot of the icons in question?

**Comment by ghost** [comment]
https://github.com/tux3/qTox/tree/master/img/settings
https://github.com/tux3/qTox/blob/master/ui/micButton/micButton.png
https://github.com/tux3/qTox/blob/master/ui/volButton/volButton.png
@Xylemon mentioned your [mockup](https://cloud.githubusercontent.com/assets/7714365/5082114/75ee4f36-6ea8-11e4-8d6a-46752fcc8c28.PNG) with better versions of mic and volume buttons. I just need white mic/volume shapes as button background will be styled by css.

**Comment by ItsDuke** [comment]
@novist sorry about the wait, I just added these to my repository. Hope that helps!

**Comment by ghost** [comment]
Its cool, thanks! Though wth is .eps? We kind of need svg.. :)

**Comment by ItsDuke** [comment]
@novist yeah I just realized that, I'm fixing that :full_moon_with_face:

**Comment by ItsDuke** [comment]
@novist all right, should be fixed!

**Comment by ghost** [comment]
Thank you o/

**Pull request merged**
