### PR TITLE
fix(ui):fix the context menu enabled/disabled behaviors

### PR DESCRIPTION
**Pull request by jakieoymj-github**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Ref: #5253,#5223

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5285)

### CODE REVIEW

**Comment by jakieoymj-github** [comment]
:(
What's wrong?!

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5285#-:-LJYbvpY77Ba_m5S8h8i:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by sudden6** [comment]
Seems to be a Travis CI hiccup, I have restarted the build.

**Comment by jakieoymj-github** [comment]
What shall I do next?

**Pull request closed without merging**
