### PR TITLE
fix(docs): update dependencies for Debian

### PR DESCRIPTION
**Pull request by tox-user**
Add missing libavcodec-dev and remove libglib2.0-dev, which already is a dependency of libgdk-pixbuf2.0-dev.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5031)

### CODE REVIEW

**Comment by sudden6** [comment]
Can you also update https://github.com/qTox/qTox/blob/master/simple_make.sh and check the build scripts for this?

**Comment by tox-user** [comment]
simple_make.sh's apt_install() function installs libavdevice-dev, which has libavcodec-dev as a dependency, so there is no need to add it there. The script works very well on Debian, if you have sudo installed. I'm not sure, if I should remove libglib2.0-dev from apt_install(), because it might be required on other systems.

**Comment by sudden6** [comment]
I think if the dependency is there for Debian it's most probably also there for the other .deb based distros.

**Comment by tox-user** [comment]
Done.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/5031#-:-L8Tx4CyepigWklw27rG:b-jbsf8z)*

**Pull request merged**
