### PR TITLE
test(db): add db schema upgrade test

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5662)

### CODE REVIEW

**Review by Diadlo — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5662)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/history.cpp, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevAfcRCnyvb9V7Vob_:-LevAfcRCnyvb9V7Voba:b-tjrg5m) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/src/persistence/history.cpp#L29)):*
> ```cpp
> 
> namespace {
>     static constexpr int SCHEMA_VERSION = 1;
> ```

I think we don't use the indent inside a `namespace`
___
*[test/persistence/dbschema_test.cpp, line 45 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevAkMSDpsmWSqKKW1V:-LevAkMSDpsmWSqKKW1W:b-r7rk3q) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/test/persistence/dbschema_test.cpp#L45)):*
> ```cpp
> void TestDbSchema::initTestCase()
> {
>     QFile::remove("testCreation.db");
> ```

Just to make sure. Do you understand, that it's not unit-test? What if I have my own file named `testCreation.db` in the current working directory?
___
*[test/persistence/dbschema_test.cpp, line 75 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevBR2d1vRB9m4QQEb3:-LevBR2d1vRB9m4QQEb4:bv67a23) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/test/persistence/dbschema_test.cpp#L75)):*
> ```cpp
>     generateCurrentSchema(queries);
>     QVERIFY(db->execNow(queries));
>     const QMap<QString, QString> expectedSql {
> ```

Why we can't check `queries` with execution?

**Comment by Diadlo** [comment]
*without execution

**Review by Diadlo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5662)* status: 0 of 1 LGTMs obtained

___
*[test/persistence/dbschema_test.cpp, line 75 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevBR2d1vRB9m4QQEb3:-LevC09VCespglyJNmQk:b-9e157h) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/test/persistence/dbschema_test.cpp#L75)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why we can't check `queries` with execution?
</blockquote></details>

*without

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5662)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/history.cpp, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevAfcRCnyvb9V7Vob_:-LewgUXwEHci_pPU-ibh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/src/persistence/history.cpp#L29)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think we don't use the indent inside a `namespace`
</blockquote></details>

Done.
___
*[test/persistence/dbschema_test.cpp, line 45 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevAkMSDpsmWSqKKW1V:-LewgWM7B8VWXe7ysQxb:b-11fbsp) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/test/persistence/dbschema_test.cpp#L45)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Just to make sure. Do you understand, that it's not unit-test? What if I have my own file named `testCreation.db` in the current working directory?
</blockquote></details>

Yes, the use of an actual file is a bit messy. I've updated initTestCase to fail and skip the test if a file name conflict exists. Rationale for using an actual file is in the next comment.
___
*[test/persistence/dbschema_test.cpp, line 75 at r1](https://reviewable.io/reviews/qtox/qtox/5662#-LevBR2d1vRB9m4QQEb3:-Lewgwf5DSeuAFTPOU_Y:b1us76i) ([raw file](https://github.com/qtox/qtox/blob/5335c7ae377f6773b11434fc62a5b029cb438143/test/persistence/dbschema_test.cpp#L75)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

*without
</blockquote></details>

If we have known schemas at each schema version, and a series of commands to update, I don't think it's easy to determine what the schema will be after applying a command, without actually using sqlite.

For example if we want to make sure upgrading from schema 0 to 6 results in the right schema, the returned queries would just be a long list of UPDATE TABLE commands, and it wouldn't be clear if the upgraded db has the right schema. Using sql, it's trivial to check - plus we get the added error checking of sqlite itself.

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5662#-:-Lex9KUlAqkEexGmDwk2:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
