### PR TITLE
docs(coding): add guides about string usage

### PR DESCRIPTION
**Pull request by Talkless**
Add guides about using QStringLiteral, QLatin1String, QLatin1Char and QStringBuilder for more efficient strings.

Qt uses uses these techniques internally and can be considered as good coding practice when working with Qt libraries.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4471)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/coding_standards.md, line 472 at r1](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmsFi6XhquO9Yd_uYnp:-KmsFi6XhquO9Yd_uYnq:b-pxozzv) ([raw file](https://github.com/qtox/qtox/blob/91199dbedfbbe4e3b4e362f82db0293bec7234df/doc/coding_standards.md#L472)):*
> ```Markdown
> ## Strings
> 
> * Use `QStringLiteral` macro when creating string which is not intended to be modified or copied (like appending) into other string:
> ```

Could you format this and other lines to be <=79 characters long wherever possible?

---

*[doc/coding_standards.md, line 511 at r1](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmsFtYDqD4T28ulbz_G:-KmsFtYDqD4T28ulbz_H:bhv83bf) ([raw file](https://github.com/qtox/qtox/blob/91199dbedfbbe4e3b4e362f82db0293bec7234df/doc/coding_standards.md#L511)):*
> ```Markdown
> [QStringLiteral explained]
> 
> [String concatenation with QStringBuilder]
> ```

Perhaps make those 3 links into a list with `*` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
*[doc/coding_standards.md, line 472 at r1](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmsFi6XhquO9Yd_uYnp:-KmvTNvAmsW3ul9Ygy81:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/91199dbedfbbe4e3b4e362f82db0293bec7234df/doc/coding_standards.md#L472)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Could you format this and other lines to be <=79 characters long wherever possible?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/coding_standards.md, line 511 at r1](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmsFtYDqD4T28ulbz_G:-KmvU3iTfosxO5-zOPf8:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/91199dbedfbbe4e3b4e362f82db0293bec7234df/doc/coding_standards.md#L511)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Perhaps make those 3 links into a list with `*` ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 480 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmwmxloS8c2MO8foHbU:-KmwmxloS8c2MO8foHbV:bhpraj8) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L480)):*
> ```Markdown
> ```
> 
> * Use `QLatin1String` when specialized overload exists.
> ```

It should be noted that for translatable strings and maybe paths `QLatin1String` is a bad idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 480 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmwmxloS8c2MO8foHbU:-KmympfuZQ7Xij4TEGNr:b-ywk5ge) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L480)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

It should be noted that for translatable strings and maybe paths `QLatin1String` is a bad idea.
</blockquote></details>

QObject::tr() has no QLatin1Sring() overload, and should produce compile time error if contributor tries that. Or you just mean that we should mention QObject::tr() usage for sake of completeness? Could you elaborate your comment about paths?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471#-:-KmzEbEQAIPycafRy6QZ:b-jbsf8z)*

**Comment by Diadlo** [comment]
Also, it's looks like qt guide. We can't write all qt-specifics hints

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471#-:-KmzExSuMBcKzW1U5Naf:b5mr7f7)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 480 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmwmxloS8c2MO8foHbU:-KmzTe80514u45MocT4S:b-mull2c) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L480)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QObject::tr() has no QLatin1Sring() overload, and should produce compile time error if contributor tries that. Or you just mean that we should mention QObject::tr() usage for sake of completeness? Could you elaborate your comment about paths?
</blockquote></details>

Ok, didn't know that.

Paths can contain Unicode symbols, I'm not sure if it's a good idea to use `QLatin1String` there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 480 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmwmxloS8c2MO8foHbU:-Kmzo609puMpjuiVoc_8:blndjxc) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L480)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Ok, didn't know that.

Paths can contain Unicode symbols, I'm not sure if it's a good idea to use `QLatin1String` there.
</blockquote></details>

Yes, hinting that QLatin1Sring should be used *only* for actually latin-1 strings might be useful,  although name suggest that...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
Yeah I guess so. I could write "Please use QObject::tr(), QStringLiteral, QLatin1String, QLatin1Char and QStringBuilder where appropriate" and leave contributor to figure it out by himself...  In current for it has some educational benefit, especially being open source project.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471#-:-Kmzp7refqK5CQej01Hs:b-gak0mj)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/coding_standards.md, line 473 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-Kmzw985G2C5M8nj8odl:-Kmzw985G2C5M8nj8odm:bolffun) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L473)):*
> ```Markdown
> 
> * Use `QStringLiteral` macro when creating new string.
> In this exampe, string is not intended to be modified or copied (like 
> ```

typo `example`

---

*[doc/coding_standards.md, line 480 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmwmxloS8c2MO8foHbU:-KmzwLXcVVKNAjWSaoT7:b-b42xni) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L480)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Yes, hinting that QLatin1Sring should be used *only* for actually latin-1 strings might be useful,  although name suggest that...
</blockquote></details>

I guess not everybody knows at a glance that `Latin1` equals, `ASCII-only`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[doc/coding_standards.md, line 473 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-Kmzw985G2C5M8nj8odl:-Kn0UYJz8D9efiSzqVTO:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L473)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `example`
</blockquote></details>

Done.

---

*[doc/coding_standards.md, line 480 at r2](https://reviewable.io:443/reviews/qtox/qtox/4471#-KmwmxloS8c2MO8foHbU:-Kn0UZWelqJnHPO7zga-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ad8f66b564a4f8681185596d0456e93ee4d247b9/doc/coding_standards.md#L480)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I guess not everybody knows at a glance that `Latin1` equals, `ASCII-only`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by Talkless** [comment]
I'm thinking, maybe I should separate bullet point sentences and their detailed explanations with empty line..?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471#-:-Kn0UdezFmTFx3F-aZ9o:bjqxuci)*

**Comment by sudden6** [comment]
Yes, I think separating them will make it more readable

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/coding_standards.md, line 497 at r3](https://reviewable.io:443/reviews/qtox/qtox/4471#-Kn0lmUSEeI3Zj0aAsZ5:-Kn0lmUSEeI3Zj0aAsZ6:b-4nocm3) ([raw file](https://github.com/qtox/qtox/blob/44bf00496722bdd95dc58ea7036fbf883260c7ff/doc/coding_standards.md#L497)):*
> ```Markdown
> copying here is unavoidable (and thus `QStringLiteral` loses it's purpose):
> ```
>         if (!dir.rename(logFileDir + QLatin1String("qtox.log"), 
> ```

unnecessary space at the end of line

---

*[doc/coding_standards.md, line 498 at r3](https://reviewable.io:443/reviews/qtox/qtox/4471#-Kn0lsFFh4JKmRaKN0m8:-Kn0lsFFh4JKmRaKN0m9:bwqua9r) ([raw file](https://github.com/qtox/qtox/blob/44bf00496722bdd95dc58ea7036fbf883260c7ff/doc/coding_standards.md#L498)):*
> ```Markdown
> ```
>         if (!dir.rename(logFileDir + QLatin1String("qtox.log"), 
> 	                logFileDir + QLatin1String("qtox.log.1")))
> ```

use spaces instead of tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471#-:-Kn0m-Gr_0L2p1sTZsLh:bmr0jih)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[doc/coding_standards.md, line 497 at r3](https://reviewable.io:443/reviews/qtox/qtox/4471#-Kn0lmUSEeI3Zj0aAsZ5:-Kn5Yg1D3duXnm_yvq2P:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6bd2971b83d38a4c94491aaed3e7ebdc71437d91/doc/coding_standards.md#L497)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

unnecessary space at the end of line
</blockquote></details>

Done.

---

*[doc/coding_standards.md, line 498 at r3](https://reviewable.io:443/reviews/qtox/qtox/4471#-Kn0lsFFh4JKmRaKN0m8:-Kn5YhnCdCzoJsn4ILhv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6bd2971b83d38a4c94491aaed3e7ebdc71437d91/doc/coding_standards.md#L498)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use spaces instead of tab
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4471#-:-Kn5_EHMsvMb9GjAIIds:b-jbsf8z)*

**Comment by Talkless** [comment]
Thanks' for review!

**Pull request merged**
