### PR TITLE
fix(i18n): correct ru translation

### PR DESCRIPTION
**Pull request by PKEv**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3712)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[translations/ru.ts, line 310 at r1](https://reviewable.io:443/reviews/qtox/qtox/3712#-KRY982s9thESSFuHu9T:-KRY982tHC3cvmpXkapW:b-qtfyzu) ([raw file](https://github.com/qtox/qtox/blob/ef9c9d4b48a91a45e72fc48e13267b7320cdd45d/translations/ru.ts#L310)):_

> закладке

Наверное, лучше "вкладке"

---

_[translations/ru.ts, line 318 at r1](https://reviewable.io:443/reviews/qtox/qtox/3712#-KRY96YSAKdkILjIihyL:-KRY96YSAKdkILjIihyM:blppuxb) ([raw file](https://github.com/qtox/qtox/blob/ef9c9d4b48a91a45e72fc48e13267b7320cdd45d/translations/ru.ts#L318)):_

> ``` XML
>     <message>
>         <source>not</source>
>         <translation>не изменяйте</translation>
> ```

`изменяйте` уже есть в строке, куда она будет подставлена. т.е. `%2 изменяйте`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3712)_

**Comment by PKEv** [comment]
correct

**Comment by Diadlo** [comment]
You forget 'n' letter in `i18n` in commit message

**Comment by zetok** [comment]
missing `:` in commit message

**Comment by Diadlo** [comment]
Merged with weblate translation and moved to #3720

**Pull request closed without merging**
