### PR TITLE
feat(audio):OutgoingCallSound

### PR DESCRIPTION
**Pull request by AliceGrey**
Fix for #4244 Adds outgoing call sound when call is started and loops until call is picked up..

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4464)

### CODE REVIEW

**Comment by Diadlo** [comment]
First example sound was better :(
@zetok should we somewhere specify the licence or the author?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[res.qrc, line 102 at r1](https://reviewable.io:443/reviews/qtox/qtox/4464#-Kma-83G8H2CRtW9fbDd:-Kma-83G8H2CRtW9fbDe:b-z9ljj8) ([raw file](https://github.com/qtox/qtox/blob/bc76d5326b960f3452f38a87d3da6438952f0fe2/res.qrc#L102)):*
> ```
>         <file>ui/contentDialog/contentDialog.css</file>
>         <file>ui/tooliconsZone/tooliconsZone.css</file>
>         <file>audio/ToxOutgoingCall.pcm</file>
> ```

Can you move it in `audio` block on the top of the list?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4464#-:-Kma-ycKmVPHqcFDavfF:b-5p3z1p)*

**Comment by zetok** [comment]
@Diadlo according to what is stated, it's licensed under [CC0](https://creativecommons.org/publicdomain/zero/1.0/), so it doesn't require anything like that.

There is a sentence that concerns me though:

>Recorded straight off my iphone.

Does that mean that this is a recording of the dialing sound that iphone makes? If so, it's not licensed under CC0 and can't be included in qTox.

Edit: actually, regardless of whether it's something that is proprietary to iphone, or whether it's a dial sound from an actual call, it would not be under CC0.

**Comment by Diadlo** [comment]
@AliceGrey Can you change the sound?

**Comment by AliceGrey** [comment]
@zetok @Diadlo This PR has a different sound from what I originally proposed. The sound in this PR was made by me. I don't have a lot of experience in using synthesizers but if someone would like to propose another sound I would be happy to change it. I've had a hard time finding a sound under CC.

EDIT: We could use one of the sounds from Tox/Sounds https://github.com/Tox/Sounds/blob/master/Isotoxin/Call%20Sounds/isotoxin_Calltone.flac

**Comment by AliceGrey** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[res.qrc, line 102 at r1](https://reviewable.io:443/reviews/qtox/qtox/4464#-Kma-83G8H2CRtW9fbDd:-KmcgRX2RFMFKiv-udZU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bc76d5326b960f3452f38a87d3da6438952f0fe2/res.qrc#L102)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can you move it in `audio` block on the top of the list?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4464)*

**Comment by Diadlo** [comment]
@zetok So there is no licence problem?

**Comment by Diadlo** [comment]
Code :lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4464#-:-Kmemn47rHVznh0lNsGU:bnu8ip0)*

**Comment by zetok** [comment]
@AliceGrey 
>@zetok @Diadlo This PR has a different sound from what I originally proposed. The sound in this PR was made by me.

That's awesome.

@Diadlo 
>@zetok So there is no licence problem?

Yep, absolutely no problem.

**Comment by Diadlo** [comment]
@AliceGrey God job :+1:

**Pull request merged**
