### PR TITLE
fix(ui): fix the context menu enabled/disabled behaviors

### PR DESCRIPTION
**Pull request by jakieoymj-github**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)
Re-Retry:
fix(ui): fix the context menu enabled/disabled behaviors
refs: #5223 #5253

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5291)

### CODE REVIEW

**Comment by tox-user** [comment]
Why did you create a new PR from a different branch?

**Comment by jakieoymj-github** [comment]
@tox-user  I am also very strange. I have two account, I never use the jakie-github, but it appeared when I create a PR from jakieoymj-github. I don't know how to do with.

**Comment by jakieoymj-github** [comment]
@tox-user It seems I use the jakie-github's primary email as this account's ssh email. I have deleted my jakie-github account. Do I need resubmit this PR?

**Comment by jakieoymj-github** [comment]
@tox-user Another question why my PR failed in Travis CI? I just modified CSS file and deleted a line in src/widget/contentlayout.cpp

**Comment by tox-user** [comment]
We found that the problem was with Travis and there was nothing wrong with your PR. You don't have to resubmit it.

**Review by sudden6 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5291)* status: 0 of 1 LGTMs obtained

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5291#-:-LKXwxhM3bNR744cffGW:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
