### PR TITLE
fix(settings): prevent segfault on wrong proxy settings

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5185)

### CODE REVIEW

**Comment by tox-user** [comment]
With this PR what will happen when proxy settings are wrong?

**Comment by sudden6** [comment]
You can enter the settings page and correct them. Before qTox would segfault after displaying an error message that the proxy is invalid and you would not be able to change it.

**Comment by sudden6** [comment]
This fixes parts of https://github.com/qTox/qTox/issues/5062 namely the crash.

**Comment by tox-user** [comment]
It still crashes for me when I set proxy to HTTP:
```
core/core.cpp:252 : Debug: using proxy "gdrgrghsegesg" : 257
core/core.cpp:313 : Critical: bad proxy, error code: 5
Segmentation fault
```

**Comment by tox-user** [comment]
I was in TCP mode.

**Comment by sudden6** [comment]
I can't reproduce, can you provide a backtrace?

**Comment by tox-user** [comment]
My steps this time:
1. Set proxy to HTTP.
2. Type random text into proxy address field.
3. Press reconnect.
4. A pop up with a warning will show up. Press ok.
5. Change proxy type to SOCKS.
6. Press reconnect.

```
core/core.cpp:252 : Debug: using proxy "fsfseafsefeios" : 257
core/core.cpp:313 : Critical: bad proxy, error code: 5

#0  0x00007ffff4391233 in messenger_size () from /usr/local/lib/libtoxcore.so.2
#1  0x00007ffff439b60c in tox_get_savedata_size () from /usr/local/lib/libtoxcore.so.2
#2  0x000055555580833d in Core::getToxSaveData() ()
#3  0x000055555580a248 in Core::reset() ()
#4  0x00005555557ac0d7 in Core::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#5  0x00007ffff03c5499 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff7664b8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff766c341 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff03989e0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff039b16d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff03ecc43 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff2ac87f7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff2ac8a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff2ac8b0c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff03ed04f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff03969ca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff01c40f3 in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff01c8da8 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007fffef969494 in start_thread (arg=0x7fffc2ffd700) at pthread_create.c:333
#19 0x00007fffef6abacf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

**Comment by sudden6** [comment]
Could reproduce, working on a fix.

**Comment by sudden6** [comment]
Ok so I found out the reason for the crash:

- After the first reconnect toxcore fails to start -> this makes `Core.tox` a `nullptr`
- on the second reconnect in `Core::reset()` we try to get the savedata of the running toxcore instance,
 but since it's not running there's a segfault.

Reproducable using the following steps:

- select proxy type HTTP or SOCKS5 and enter invalid proxy address
- click "reconnect"
- select proxy type HTTP or SOCKS5 and enter invalid proxy address
- click "reconnect"
- crash

I see no way to fix this atm without some major refactoring. I'll add this to our issues.

**Comment by tox-user** [comment]
I see, so it's a separate bug not related to this PR.

**Comment by tox-user** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5185#-:-LFi_rPpD_rORgNQO7JL:b-jbsf8z)*

**Pull request merged**
