### PR TITLE
feat(core): Disk usage control

### LINKED ISSUE #3946: qTox should inform user that there's no free space on disk to save things
##### Brief Description
Currently qTox doesn't inform user that there is "no space left on the device", instead silently failing to do stuff it is required to do, or creating cryptic errors that have nothing to do with the actual problem.

OS: Gentoo Linux amd64
qTox version: v1.6.0-58-gfeaedee
Commit hash: feaedeed841f419a8eb5b7f40a14e27ef1e104cb
toxcore: 0.0.0
Qt: 5.6.1

Reproducible: Always

##### Steps to reproduce

1. Mount a small FS: `mkdir fill && sudo mount -t tmpfs -o size=2m,uid=$UID none fill`
2. Start qTox there and make some history `HOME="$PWD/fill" TMPDIR="$PWD/fill" qtox`
3. Close and reopen qTox to make sure that history has been saved (no need to quit it, logout is enough)
4. Fill the mount: `cat /dev/zero > fill/zeros`
5. Try to do things. Sending messages, changing options, whatever, anything that causes writes.

##### Observed Behavior
Some errors in the stdout, little to no errors that user sees, and 0 visible errors that actually inform user what the problem is.

##### Expected Behavior
Visible (GUI) error about no free space on the HDD. Preferably with some instructions for user what to do to free space, perhaps e.g. `You could try to delete some recently downloaded files that take a lot of space`, or something.

##### Additional Info

Some errors:
```
[22:19:45.633 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:19:58.582 UTC] persistence/db/rawdatabase.cpp:651 : Warning: Unknown error 13 executing query "DELETE FROM faux_offline_pending WHERE id=3;"
[22:20:29.343 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:29.344 UTC] widget/systemtrayicon.cpp:99 : Debug: Deleting SystemTrayIcon
[22:20:29.349 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:29.349 UTC] persistence/profile.cpp:408 : Critical: Failed to write, can't save!
[22:20:29.349 UTC] persistence/settings.cpp:656 : Debug: Saving personal settings at  "/home/zetok/working/delete/up/fill/.config/tox/bterased.ini"
[22:20:29.350 UTC] persistence/settingsserializer.cpp:346 : Critical: Failed to write, can't save!
[22:20:40.870 UTC] persistence/profile.cpp:104 : Debug: Loading tox save  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:40.871 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:40.871 UTC] persistence/settings.cpp:358 : Debug: Loading personal settings from "/home/zetok/working/delete/up/fill/.config/tox/bterased.ini"
[22:20:41.133 UTC] core/core.cpp:252 : Debug: Loading user profile
[22:20:41.133 UTC] persistence/profile.cpp:299 : Debug: Loading tox save  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:41.133 UTC] core/core.cpp:136 : Debug: Core starting with IPv6 enabled
[22:20:41.134 UTC] core/core.cpp:321 : Debug: Self avatar not found, will broadcast empty avatar to friends
[22:20:41.163 UTC] core/core.cpp:397 : Debug: Disconnected from the DHT
[22:20:41.925 UTC] widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[22:20:42.633 UTC] core/core.cpp:425 : Debug: "Connecting to 5.135.59.163:33445 (Skey)"
[22:20:42.633 UTC] core/core.cpp:425 : Debug: "Connecting to sorunome.de:33445 (Sorunome)"
[22:20:47.482 UTC] core/core.cpp:425 : Debug: "Connecting to tox.zodiaclabs.org:33445 (stal)"
[22:20:47.783 UTC] core/core.cpp:425 : Debug: "Connecting to v6.tox.zodiaclabs.org:33445 (stal)"
[22:20:48.264 UTC] persistence/db/rawdatabase.cpp:651 : Warning: Unknown error 13 executing query "INSERT INTO history (timestamp, chat_id, message, sender_alias) VALUES (1481062848262, 0, ?, (  CASE WHEN changes() IS 0 THEN (    SELECT id FROM aliases WHERE owner=1 AND display_name=?)  ELSE last_insert_rowid() END));"
[22:20:51.634 UTC] core/core.cpp:389 : Debug: Connected to the DHT
[22:20:51.635 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:51.635 UTC] persistence/profile.cpp:408 : Critical: Failed to write, can't save!
[22:20:54.599 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:54.599 UTC] widget/systemtrayicon.cpp:99 : Debug: Deleting SystemTrayIcon
[22:20:54.604 UTC] persistence/profile.cpp:377 : Debug: Saving tox save to  "/home/zetok/working/delete/up/fill/.config/tox/bterased.tox"
[22:20:54.604 UTC] persistence/profile.cpp:408 : Critical: Failed to write, can't save!
[22:20:54.605 UTC] persistence/settings.cpp:656 : Debug: Saving personal settings at  "/home/zetok/working/delete/up/fill/.config/tox/bterased.ini"
[22:20:54.605 UTC] persistence/settingsserializer.cpp:346 : Critical: Failed to write, can't save!
[22:20:56.948 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:56.949 UTC] main.cpp:312 : Debug: Clean exit with status 0
```

After the quit ↑ and starting qTox again it's not possible to login, as qTox claims that profile is already in use -.-"

```
[22:20:58.706 UTC] :0 : Debug: using qt5ct plugin
[22:20:58.735 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:20:58.747 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  11895995666887129815
[22:20:58.748 UTC] main.cpp:210 : Debug: built on:  04:33:24 Dec  6 2016 ( 1480998802 )
[22:20:58.748 UTC] main.cpp:211 : Debug: commit:  feaedeed841f419a8eb5b7f40a14e27ef1e104cb 

[22:20:58.748 UTC] nexus.cpp:85 : Debug: Starting up
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No such file or directory
[22:21:09.553 UTC] persistence/settings.cpp:494 : Debug: "Saving global settings at /home/zetok/working/delete/up/fill/.config/tox/qtox.ini"
[22:21:09.554 UTC] main.cpp:312 : Debug: Clean exit with status 0
```

### PR DESCRIPTION
**Pull request by tWido**
Fixes #3946

Needs testing!

Upon start disk usage is controlled. If usage exceeds threshold user is warned.
If disk is full program notifies user and exits.

On write operation error disk usage is checked.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4498)

### CODE REVIEW

**Comment by Diadlo** [comment]
Remove `Needs testing` from commit, please

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[CMakeLists.txt, line 262 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfF3pl0FwJXTwz1Y43:-KnfF3pl0FwJXTwz1Y44:b-hfj05t) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/CMakeLists.txt#L262)):*
> ```CMake
>   src/nexus.cpp
>   src/nexus.h
>   src/persistence/checkdisk.cpp
> ```

We still support `qmake`,  add this files in it too

---

*[src/persistence/checkdisk.cpp, line 39 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf8UwnYS4d1kcO34pJ:-Knf8UwnYS4d1kcO34pK:b-dy9737) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L39)):*
> ```cpp
> #define OK 0
> 
> static int diskInfo(const QString& path, uint64_t* available, uint64_t* total, uint64_t* free)
> ```

Add docs, please

---

*[src/persistence/checkdisk.cpp, line 59 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf88prDIjBGf-XQUio:-Knf88ptTGjjbyJn0vin:bp0shx9) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L59)):*
> ```cpp
>     *total = info.f_blocks;
>     *free = info.f_bfree;
>     return OK;
> ```

`return OK;` van be mover out of `#ifdef`

---

*[src/persistence/checkdisk.cpp, line 64 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf8aGy6LKUQ_IvivAj:-Knf8aGy6LKUQ_IvivAk:boz304w) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L64)):*
> ```cpp
> 
> /**
>  * @brief Checks disk usage.
> ```

I think, better something like "Check is disk full" (not sure in grammar)

---

*[src/persistence/checkdisk.cpp, line 66 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf9TyBJktK2dCAw5Y1:-Knf9TyBJktK2dCAw5Y2:bikzm7i) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L66)):*
> ```cpp
>  * @brief Checks disk usage.
>  * @param path Path to file in filesystem.
>  * @return True if disk is full. Anything else including error is false.
> ```

I think, error should be `true` to stop qTox if here maybe issues with disk.
Or add parameter `bool ok&`

---

*[src/persistence/checkdisk.cpp, line 95 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf9wjA8-uorjL76zqL:-Knf9wjA8-uorjL76zqM:bn2xsoz) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L95)):*
> ```cpp
>  * @param parent Parent widget
>  */
> void DiskCheck::errorDialog(QWidget* parent)
> ```

IMO It will be better, if module is independent of GUI. I don't know how right resolve this situation. Maybe create module `DiskCheckGUI`? What do you think?

---

*[src/persistence/checkdisk.cpp, line 100 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfAU83fV5xnwa23VTx:-KnfAU83fV5xnwa23VTy:bh8vafn) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L100)):*
> ```cpp
>     QMessageBox error(parent);
>     error.critical(0, "Error", "Disk full!");
>     error.setFixedSize(500, 200);
> ```

Not sure about this. Can lead to a problem on display with 4K+?

---

*[src/persistence/checkdisk.h, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfEJNoCjN6q2SXyq5V:-KnfEJNoCjN6q2SXyq5W:bh5tbae) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.h#L6)):*
> ```objc
> #include <cstdint>
> 
> #include <QMessageBox>
> ```

If you will decide to leave `DiskCheck::errorDialog` here, move all this includes in `.cpp` and use forward declaration

---

*[src/persistence/db/rawdatabase.cpp, line 632 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfEzYpGCwMJ5GaaW04:-KnfEzYpGCwMJ5GaaW05:b-3atc03) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/db/rawdatabase.cpp#L632)):*
> ```cpp
>                     goto cleanupStatements;
>                 default:
>                     if (DiskCheck::diskFull(this->path)) {
> ```

Why this check is needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4498#-:-KnfFOTWMTCVltmb5eIO:b-tozvrt)*

**Comment by tWido** [comment]
Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[CMakeLists.txt, line 262 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfF3pl0FwJXTwz1Y43:-KniOAmsq8heivc83DVe:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/CMakeLists.txt#L262)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

We still support `qmake`,  add this files in it too
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 39 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf8UwnYS4d1kcO34pJ:-KniOEkG7tJ6jHLRk2Tc:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L39)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add docs, please
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 59 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf88prDIjBGf-XQUio:-KniOHIYp7pLcLNZbeJ4:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L59)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`return OK;` van be mover out of `#ifdef`
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 64 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf8aGy6LKUQ_IvivAj:-KniOJADoDYVS4hoOT0X:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L64)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, better something like "Check is disk full" (not sure in grammar)
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.cpp, line 66 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf9TyBJktK2dCAw5Y1:-KniOKDfiqaG4JX1twRM:beip90f) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L66)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, error should be `true` to stop qTox if here maybe issues with disk.
Or add parameter `bool ok&`
</blockquote></details>

Error can be a simple thing like non-existing path given or something much worse.  I'm not sure how to handle this.  Maybe path error return not full and other error full? Or add some error info to returned variables? 

---

*[src/persistence/checkdisk.cpp, line 95 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf9wjA8-uorjL76zqL:-KniRqqFHwckmpXClIw_:btwxkel) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L95)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

IMO It will be better, if module is independent of GUI. I don't know how right resolve this situation. Maybe create module `DiskCheckGUI`? What do you think?
</blockquote></details>

I think it should be some function located somewhere in widget file tree, but creating a file for a single function doesn't seem right. Maybe create some file for GUI errors?

For now i removed GUI.  Caused multiple warnings and segfaulted
:0 : Warning: QApplication: Object event filter cannot be in a different thread.

---

*[src/persistence/checkdisk.cpp, line 100 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfAU83fV5xnwa23VTx:-KniSQdYWzJXnEwPtydE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L100)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Not sure about this. Can lead to a problem on display with 4K+?
</blockquote></details>

Done.

---

*[src/persistence/checkdisk.h, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfEJNoCjN6q2SXyq5V:-KniUiSVJQy4SridnbdH:bf986ur) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.h#L6)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

If you will decide to leave `DiskCheck::errorDialog` here, move all this includes in `.cpp` and use forward declaration
</blockquote></details>

Should even QString be moved? 

---

*[src/persistence/db/rawdatabase.cpp, line 632 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfEzYpGCwMJ5GaaW04:-KniU1EDNJUG_fZqpXjL:bvk9c91) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/db/rawdatabase.cpp#L632)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why this check is needed here?
</blockquote></details>

Query commit can fail due to full disk. This check is used to determine  if it failed because of disk space.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4498)*

**Comment by Diadlo** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/main.cpp, line 324 at r2](https://reviewable.io:443/reviews/qtox/qtox/4498#-KniZlXVlmNde3U80GrQ:-KniZlXVlmNde3U80GrR:b-z3xl5q) ([raw file](https://github.com/qtox/qtox/blob/84618162938138b4c559e12bd11f03bb7a468a02/src/main.cpp#L324)):*
> ```cpp
>     bool diskFull = false;
>     if (QFileInfo::exists(cacheDir)) {
>         diskFull = diskFull || CheckDisk::diskFull(cacheDir);
> ```

I think, can be replaced on
`diskFull = diskFull || (QFileInfo::exists(cacheDir) && CheckDisk::diskFull(cacheDir));`
If you think, the current one iss better -- feel free to leave

---

*[src/persistence/checkdisk.cpp, line 66 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf9TyBJktK2dCAw5Y1:-Kni_hP6yTzCu88dtzWt:btq0lia) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L66)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Error can be a simple thing like non-existing path given or something much worse.  I'm not sure how to handle this.  Maybe path error return not full and other error full? Or add some error info to returned variables? 
</blockquote></details>

You can use enum (like `DiskFullError`) reference as parameter and make decision on caller side.

---

*[src/persistence/checkdisk.cpp, line 95 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-Knf9wjA8-uorjL76zqL:-Kniao8-VMnK-mC_z2xN:b-w9r0x0) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L95)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

I think it should be some function located somewhere in widget file tree, but creating a file for a single function doesn't seem right. Maybe create some file for GUI errors?

For now i removed GUI.  Caused multiple warnings and segfaulted
:0 : Warning: QApplication: Object event filter cannot be in a different thread.

</blockquote></details>

I think, [GUI](https://github.com/qTox/qTox/blob/master/src/widget/gui.h) is what you want :)

---

*[src/persistence/checkdisk.cpp, line 100 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfAU83fV5xnwa23VTx:-KnialHjIXPoCUgg_qsA:b-93yu0d) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.cpp#L100)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I talk only about `setFixedSize` :)

---

*[src/persistence/checkdisk.cpp, line 78 at r2](https://reviewable.io:443/reviews/qtox/qtox/4498#-Kni_qjCPtK2pmy7AE8X:-Kni_qjCPtK2pmy7AE8Y:b-aptxu9) ([raw file](https://github.com/qtox/qtox/blob/84618162938138b4c559e12bd11f03bb7a468a02/src/persistence/checkdisk.cpp#L78)):*
> ```cpp
>  * @brief Check is disk full.
>  * @param path Path to file in filesystem.
>  * @param ok Stores success status.
> ```

You add `ok` parameter in docs, but not in code :)

---

*[src/persistence/checkdisk.h, line 6 at r1](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnfEJNoCjN6q2SXyq5V:-KnibKcksVb2bDYb33qm:bb0a0dm) ([raw file](https://github.com/qtox/qtox/blob/ae7c1822d54183a8d11b4b79eb62daee8a85ce86/src/persistence/checkdisk.h#L6)):*
<details><summary><i>Previously, tWido wrote…</i></summary><blockquote>

Should even QString be moved? 
</blockquote></details>

`QWidget` -- yes
`QString` as you want (I prefer to use forward declaration where it's possible)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4498)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/persistence/checkdisk.cpp, line 2 at r2](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnimMQL3wi85cPA4xg1:-KnimMQL3wi85cPA4xg2:b-dd34k4) ([raw file](https://github.com/qtox/qtox/blob/84618162938138b4c559e12bd11f03bb7a468a02/src/persistence/checkdisk.cpp#L2)):*
> ```cpp
> 
> #include "checkdisk.h"
> ```

Does your approach have an advantage over http://doc.qt.io/qt-5/qstorageinfo.html#bytesAvailable ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4498)*

**Comment by tWido** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/persistence/checkdisk.cpp, line 2 at r2](https://reviewable.io:443/reviews/qtox/qtox/4498#-KnimMQL3wi85cPA4xg1:-KninsK8ptqWC6W0Wvue:b43o3du) ([raw file](https://github.com/qtox/qtox/blob/84618162938138b4c559e12bd11f03bb7a468a02/src/persistence/checkdisk.cpp#L2)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Does your approach have an advantage over http://doc.qt.io/qt-5/qstorageinfo.html#bytesAvailable ?
</blockquote></details>

QStorageInfo is since Qt 5.4.  Coding guidelines states support for Qt 5.3. Otherwise i would happily use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4498)*

**Comment by Diadlo** [comment]
Fortunately, recently we bump it in #4493 to Qt 5.5.1

**Comment by Diadlo** [comment]
@tWido Fortunately, recently we bump it in #4493 to Qt 5.5.1

**Comment by tWido** [comment]
@Diadlo Great. It will be much better. Closing this PR and will open a new one with QStorageInfo once it's done.

**Comment by sudden6** [comment]
I'll correct the stuff in `coding_style.md`

**Pull request closed without merging**
