### PR TITLE
Fix segfault on friend id copy, refactor some code

### PR DESCRIPTION
**Pull request by F1ynn**

### CODE REVIEW

**Comment by tux3** [comment]
There are bugs with the resizable friendlist.
If you maximize the windows, resize the friendlist to take half the screen, and shrink the window, the friendlist will disapear to the left, outside of the window!

If you think it's an easy fix, I'll wait for you to resend the PR, if you think that it takes more time, I'll cherry pick some commits and you can resend the resizable friendlist when it's fixed.
But I'd be easier if you had split this into multiple pull requests, this way I don't have to cherry-pick commits when something's wrong :)

**Comment by tux3** [comment]
Pic of the bug :

**Comment by F1ynn** [comment]
Should be a quick fix, sorry about that.

> split this into multiple pull requests
> Sorry about that, I'm still getting used to using git. Will do next time.

**Comment by tux3** [comment]
It's fine, thanks.

**Comment by F1ynn** [comment]
Okay, should be fixed now.

**Comment by tux3** [comment]
I'll merge soon, I'm busy fixing the merge conflicts by hand.
Fixing conflicts in a .ui file is a PAIN !

**Comment by F1ynn** [comment]
Oh man, yikes. Hope it doesn't eat up too much of your time

**Comment by tux3** [comment]
Well, it's more complicated than I anticipated.
Your pull (somehow) breaks the ClickableLabel I use to change the status (I added it today, to change between Online/Away/Busy)
It also looks a bit weird in Qt Designer, but that's not really a problem.

It compiles fine, but my ClickableLabel (a QLabel with a clicked() signal) never received the mouse click.
I have no idea what the problem is, maybe you do ?

**Comment by F1ynn** [comment]
That's odd, I'll take a look at it and get back to you.

**Comment by tux3** [comment]
Thanks

**Comment by F1ynn** [comment]
This is really weird. There's something funky going on with statusHead, I'll let you know when I get it fixed.

**Comment by tux3** [comment]
Okay, I'll see if I can still cherry pick some commits in the meantime.

**Comment by F1ynn** [comment]
Hah NVM, I'm an idiot. This is caused by the line 

ui->statusHead->setAttribute(Qt::WA_TransparentForMouseEvents);

in widget.cpp

I had set that so that I could use its mouse events, but then ended up just handling the events for the entire Widget. It can be removed without issue (I messed something up with git on my end so I can't push out a fix right now)

That was pretty stupid of me, sorry about that.

**Comment by tux3** [comment]
Okay, I'll try to merge again.

**Pull request merged**
