### PR TITLE
Refactor. Use const

### PR DESCRIPTION
**Pull request by Diadlo**
~Based on #4540 and #4539~

----
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4541)

### CODE REVIEW

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/about/aboutuser.cpp, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/4541#-Kpym9xBooXXQTqV4w4Y:-Kpym9xCDYOPd50GUYOp:bn3wg8r) ([raw file](https://github.com/qtox/qtox/blob/8139f99692188ee58ea8127736c332250f93c4d1/src/widget/about/aboutuser.cpp#L10)):*
> ```cpp
> #include <QFileDialog>
> #include <QMessageBox>
> #include <QComboBox>
> ```

Change `include` order

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4541#-:-KpypfiX4OYL-HGlYYLj:b-jbsf8z)*

**Comment by Diadlo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/widget/about/aboutuser.cpp, line 10 at r1](https://reviewable.io:443/reviews/qtox/qtox/4541#-Kpym9xBooXXQTqV4w4Y:-KpzJLTMC_4ZpoHDfA7z:b-9480n1) ([raw file](https://github.com/qtox/qtox/blob/8139f99692188ee58ea8127736c332250f93c4d1/src/widget/about/aboutuser.cpp#L10)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Change `include` order
</blockquote></details>

This was unneeded change. Reverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4541)*

**Comment by sudden6** [comment]
Reviewed 11 of 12 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4541)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4541#-:-Kq8YPeQ5km4O0SutzUA:b-jbsf8z)*

**Pull request merged**
