### PR TITLE
Refactor of ContentDialog

### PR DESCRIPTION
**Pull request by Diadlo**
This PR is part of #4219

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4252)

### CODE REVIEW

**Comment by sudden6** [comment]
nice title :p

**Comment by Diadlo** [comment]
Just used the default one. Renamed

**Comment by sudden6** [comment]
Reviewed 3 of 6 files at r1.
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/contentdialog.cpp, line 545 at r1](https://reviewable.io:443/reviews/qtox/qtox/4252#-Kf81P4U2-QX3oqzbpVY:-Kf81P4U2-QX3oqzbpVZ:b-tsad8k) ([raw file](https://github.com/qtox/qtox/blob/44ca48ee7fa8f9128b591eadc2676dfa796ee1a4/src/widget/contentdialog.cpp#L545)):*
> ```cpp
> }
> 
> void ContentDialog::setUsername(const QString& newName)
> ```

This function should also get docs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4252)*

**Comment by Diadlo** [comment]
Review status: 3 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/contentdialog.cpp, line 545 at r1](https://reviewable.io:443/reviews/qtox/qtox/4252#-Kf81P4U2-QX3oqzbpVY:-KfgsfaTrK0Ps_xHDoLB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/44ca48ee7fa8f9128b591eadc2676dfa796ee1a4/src/widget/contentdialog.cpp#L545)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This function should also get docs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4252)*

**Comment by sudden6** [comment]
:lgtm_strong: 

---

Reviewed 2 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4252#-:-Kfh_jaEvSj9tfeyvAvl:b-uwkowd)*

**Pull request merged**
