### PR TITLE
chore(tools): update translation updater's commit message (s/w/W/)

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3784)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3784#-:-KTLFFM5TEn9HSZn74rR:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3784#-:-KTW1yqz3Oo2D4Gip1EN:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3784#-:-KTW7jcy0LA_E1C4TeNP:bnfp4nl)_

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3784#-:-KTYEsAF6Cu8Dlmz7rCd:bnfp4nl)_

**Pull request merged**
