### PR TITLE
Redesigned VideoFrame class

### PR DESCRIPTION
**Pull request by initramfs**
This PR redesigns the VideoFrame class to be more robust, documented and performant whilst retaining all existing functionality.

Changes in particular to the class:
- modularize functionality: generating a frame has been decoupled from "to" functions (e.g. `toQImage()`).
- better multi-threading performance: updates the mutex to a read-write lock for concurrent reads without blocking.
- more generic: now handles essentially all pixel format types and sizes (instead of hard coding 3 different frame types).
- exposes a new `getAVFrame()` function: allows retrieval of a AVFrame pointer for custom processing by users of the AVFrame object.
- exposes a `isValid()` function: now allows users of VideoFrame to tell if the frame has been released.
- exposes `trackFrame()` and `untrackFrames()` functions that allow the class to perform self-counting weak referencing (allowing mass invalidation of frames as necessary).
- stores dimensional data instead of only size: uses a `QRect` over a `QSize` to store source frame geometry.
- explictly delete move constructor/operator: ensures there is no way to accidentally copy the object without using a smart pointer.

The only functionality changes with this class are that the function `getSize()` has been removed in favor of `getSourceDimensions()` which returns a `QRect` instead of a `QSize` (in which you can call `getSize()` to get the corresponding size and that the reference tracking code in CameraSource has been integrated into the VideoFrame class.

Whilst usage-wise very little has been changed for the class, new functionality introduced with this class will form the basis required for a upcoming PR that I'm working on for a video source compositor (allows for thread-safe composition of different video sources) which will then be used for better desktop video (as well as some other stuff).

---

This change is [Reviewable](https://reviewable.io/reviews/tux3/qtox/3185)

### CODE REVIEW

**Comment by zetok** [comment]
on e151fba76813420359f5e69682f11ebc8232499e
- [x] OOM: 
  
  ```
  galaxor kernel: Out of memory: Kill process 1947 (qtox) score 45 or sacrifice child
  galaxor kernel: Killed process 1947 (qtox) total-vm:3306932kB, anon-rss:1589688kB, file-rss:8188kB
  ```
  
  The instance that wasn't killed by OOM killer uses after ending call 1GB of RAM, and as a video source it used cam (1280x720 resolution)
  The instance that was killed, used desktop streaming as video source, with resolution 1920x1080
- [x] tilted image when desktop-streaming: 
  desktop streaming

**Comment by initramfs** [comment]
@zetok Huh... I ran that through valgrind memchecker with no issues... Back to debugging it is... Thanks for the heads up.

**Comment by initramfs** [comment]
@zetok All issues resolved.

**Comment by zetok** [comment]
on 711eff3f13be6f016e84a3c3252cc56798fd794a
Video overlaps `Hide Messages` button – not sure if it's due to this PR.
overlapping
- [x] not sure why or exactly how, but I got one call participant to "think" that call was finished, while other call participant still got the video from the participating caller(!)
  b-but there's a call
  ↑ `kotez` with an avatar sees that call has ended, but `kotez` without an avatar still receives desktop streaming from `kotez` with an avatar.
  
  Some timing issue that was triggered when I was calling & hanging up calls.

**Comment by initramfs** [comment]
@zetok I don't think the "hide message" overlap is caused by this PR (I didn't touch UI at all). Regarding the timing issue, I too observe some funky behaviour with race conditions from calling. However, I don't think my PR is the source, rather, it uncovered some underlying issue with thread synchronization between CameraSource and ToxAV.

Anyways, I will continue investigating... Might open a separate PR if I find an unrelated issue.

**Comment by initramfs** [comment]
@zetok The "hide message" overlap issue seems to exist before I made this branch.

Screenshot from 6dd1cd0 (which is the merge base between master and this PR's branch):

evidence

**Comment by zetok** [comment]
on 711eff3f13be6f016e84a3c3252cc56798fd794a
CPU usage, dunno if normal, on FX-8370 (@ 4 GHz):
cpu usage
↑ `_3` and `d_b` are in call, `_3` is streaming desktop, `d_b` is sending video from camera

As for hidden streaming, I've managed to reproduce it a few more times. Dunno if that's something that could have been already in there, but I don't remember running into that before.

**Comment by zetok** [comment]
on 711eff3f13be6f016e84a3c3252cc56798fd794a
The instance `_3` after ending call still uses ~100% CPU  (over 12h after the call), and `d_b` segfaulted – sorry, no bt, since I wasn't running it under gdb.

**Comment by initramfs** [comment]
@zetok Based on reports from issue #3237 and #3238 as well as some self testing, it doesn't seem like the excessive CPU usage is caused by this PR though I'm still hellbent on trying to fix it. Profiling seems to be useless because it indicates most of the CPU time comes from libvpx which doesn't seem right if you can attain normal CPU usage.

Anyways, I'm gonna wait on results from yurivict in issue #3238 (after you recommended him to do a bisect). In the meanwhile, I'm gonna work on overhauling the entire video code for qTox...

**Comment by zetok** [comment]
On c8bea03b70d3f4a8c4ead5f5b8c4e003415d47a7 problem with hidden video call still exists (https://github.com/tux3/qTox/pull/3185#issuecomment-214411762)

When pressing button for a/v call in the instance that doesn't have call shown:

```
[11:44:39.388] src/core/coreav.cpp:177 : Debug: "Starting call with 10"
[11:44:39.388] src/core/coreav.cpp:180 : Warning: "Can't start call with 10, we're already in this call!"
```

I think that once this gets fixed PR would be good for merge.

**Comment by initramfs** [comment]
@zetok Is the "phantom call" issue present at both initial call and hang up? Or only hang up?

**Comment by zetok** [comment]
Um? If you're asking about how reproducible it is, then yes, it's ~possible to get it even on the first call after start of the instance.

If the question is about how to reproduce it, then yes, pressing a button to hang up is needed to reproduce (IIRC).

**Comment by initramfs** [comment]
@zetok Sorry I should have clarified, I'm asking about the method to reproduce the issue. In particular, does the issue only present upon attempting to hang up the call (i.e. one party hangs up whilst the other party sees the call as ongoing). Or does the issue present when attempting to make a call as well (the calling party enters the call but the other party does not a see a call).

I ask because I've somewhat located issue to a potential race condition within a file not directly related to this PR (though I'll try to fix it anyway) though this seems to only account for "phantom calls" that occur if one party tries to hang up.

**Comment by zetok** [comment]
> (…) i.e. one party hangs up whilst the other party sees the call as ongoing (…)

Yep, this is pretty much what happens. Although the "hangup" is reflected only in the UI.

**Comment by zetok** [comment]
@initramfs um, any update? Are you still interested in trying to fix that one last remaining issue, and life just got busy for you, or..?

**Comment by initramfs** [comment]
@zetok Hi, terribly sorry for the lack of update, I have indeed been somewhat busy over the last few weeks. Anyhow, I've traced the bug down to pre-existing race conditions within the original video code (and the found plenty more here and there). I have, for the time I've been silent, been working on a complete redesign of the video system with a more sane and clean approach to dealing with multiple video sources (in particular I've been working on a video compositor API that allows arbitary positioning and merging of multiple video streams). I'll probably produce a design doc for it as well. I'll soon continue effort on this particular PR when I get time (doing backend work with some servers atm).

**Comment by zetok** [comment]
build on travis failed, needs to be fixed

**Comment by initramfs** [comment]
@zetok Yep, found the issue, will be fixed with next push (accidentally pushed some stashed WIP code)

**Comment by initramfs** [comment]
@zetok I believe it's done, can you verify that issues are resolved?

**Comment by zetok** [comment]
Hi,

As you might be aware, repo has been moved under `qTox` org on github.

What does it have to do with your PR, you might ask.

Well, it doesn't change all that much, except that workflow has been slightly improved – now there are required checks that PR needs to pass in order to be merged.

Those checks are:
- travis (checks whether PR builds & commit message format)
- reviewable (requirement for PR to be reviewed & accepted)

Since osx travis was broken for a bit, you will need to rebase your PR on newest master to get it to pass travis check. Sorry for inconvenience.

Reminder: as always, PR needs to be possible to merge without conflicts. Make sure it does ;)

**Comment by initramfs** [comment]
@zetok Rebase done :)

**Comment by zetok** [comment]
Similar to other PR, `fix(video): remove old unnecessary comment pretaining to removed code` should actually be `docs(video):`

Also, `s/pretaining/pertaining/` ?

# 

on a2cd234:
- [x]  "spy call" still reproducible no spy pls

**Comment by initramfs** [comment]
@zetok Sorry to bother you but could you try it again now? In all these exchanges I can't seem to reproduce your problem (well, more like I can't stream a webcam and a desktop source without it lagging out and crashing) so I can't exactly check if the issue has been resolved.

Should the same issue persist, would you kindly send me the log files for both clients? Other than that I don't know what other lead I can go on...

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185#-:-KOKPZDsfbhpvFiL3uWb:-2049985686)_

**Comment by zetok** [comment]
yep, still reproducible on 707f7af29ab55d75957cf62fc731797881c018ce

A lot harder to reproduce though.
Most of the times now video call goes on for a split of second before being terminated, but I still managed to reproduce "full spy".

log from the client that was sending video data from camera: https://gist.github.com/zetok/edcf0668b70705bf868f7f01151ce5f8
log from the client that was "spying", and sending video data from part of the screen: https://gist.github.com/zetok/0eae4e958c9d02b9a67ee9f3e26c578f

# 

> well, more like I can't stream a webcam and a desktop source without it lagging out and crashing

An actual crash? Sounds like something that needs to be fixed?

**Comment by initramfs** [comment]
@zetok I like these terminologies you're coming up with ("full spy").

> Most of the times now video call goes on for a split of second before being terminated

That seems to be issues with `CameraSource` and vary as a function of computing power/video size (I get them too on master).

Do you normally get the:

```
deprecated pixel format used, make sure you did set range correctly
```

On master (the line is taken from your logs)?

> An actual crash? Sounds like something that needs to be fixed?

Well no, but the video takes so long to initialize (given that I have a 4K panel) that it just blocks the main thread until the client times out and goes offline, thus terminating the call.

As I'm attempting to fix up the bugs experienced by you I find that I'm increasingly fixing code that's outside the scope of what this PR tries to achieve. I've mentioned a few times now, but I can confirm I am actively working on a proposal to completely redesign the video subsystem. Most of the stuff in this PR will be invalidated by the proposal anyway. Given that you've marked this PR as a milestone for v1.5.0 I've been trying to get all issues ironed out such that the next revision can be released. However, if this PR doesn't really solve any issues but rather causes more, I'd suggest just skipping it in favor of the new proposal and going ahead with the next revision release. I can't give any ETAs for the new proposal since I'm still designing it, but once the design doc is out, I'll immediately submit a "discussion PR" which allows active feedback as I implement the proposal.

With that in mind, it's your judgement call to whether this PR should still be a milestone for the next release. I'll continue to work on it until told otherwise.

**Comment by zetok** [comment]
> Do you normally get the:
>  deprecated pixel format used, make sure you did set range correctly
> On master (the line is taken from your logs)?

I don't see it on 0da1a2fd8b853f4d09bfec4a0c0e8329367a2f04.

Actually, it was the other way around – the one "spying" was sending video from camera, not the desktop. Sorry for the confusion.

# 

> As I'm attempting to fix up the bugs experienced by you I find that I'm increasingly fixing code that's outside the scope of what this PR tries to achieve. I've mentioned a few times now, but I can confirm I am actively working on a proposal to completely redesign the video subsystem. Most of the stuff in this PR will be invalidated by the proposal anyway. Given that you've marked this PR as a milestone for v1.5.0 I've been trying to get all issues ironed out such that the next revision can be released.

What 1.5.0 is supposed to have, is ~fixed/improved video stuff. I've marked this PR for 1.5.0, since it seems to get it ~done in like 95%. The remaining 5% is the "spy call" issue.

> However, if this PR doesn't really solve any issues but rather causes more, I'd suggest just skipping it in favor of the new proposal and going ahead with the next revision release.

It fixes lots of them! It's just that I usually don't focus on the things that "work", since other people do it quite well, and instead I'm focusing on what "doesn't work", so it may sound like I encounter only problems when testing.. ;)

It would be nice to have 1.5.0 released ~soon, but at the same time, if getting this PR into the right shape is not a good option, and instead reworking whole video stuff is better, so be it. It's just that reworking everything seems to be something that will take a lot of time (a lot longer than fixing just this issue)..

Hopefully getting this PR to be merged is a good option?

**Comment by initramfs** [comment]
@zetok I've actually rewritten a bit of `CameraSource` as well now. I've gotten rid of the buggy memfence code and implemented the whole thing using a `QReadWriteLock`. Personally I found quite a substantial performance improvement in switching video devices (and call initialization time), hopefully these changes remove the "spy call" bug as well (I suspected it was a race condition in `CameraSource`).

Should the issue _still_ persist, well, can you check your logs for the:

```
deprecated pixel format used, make sure you did set range correctly
```

lines again, see if they're still there. Not sure exactly how that matter to spy call, but it's a small clue...

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185#-:-KOL8UjMf5q6nkCEKr2b:1861508837)_

**Comment by zetok** [comment]
on de6475f3d362442122b574c6f5b3f84a60b90784 I'm not albe to reproduce spy call any longer.

**Comment by initramfs** [comment]
Finally! :) Damn those race conditions...

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185#-:-KOLCNJz_BPoDH8iZrMb:1759131560)_

**Comment by zetok** [comment]
btw, I'm still getting lots of 

```
[swscaler @ 0x555557e4dbe0] deprecated pixel format used, make sure you did set range correctly
```

spam in stdout

**Comment by initramfs** [comment]
Okay I'm really sorry for the spam now, but can you try it again?

**Comment by zetok** [comment]
Spam is gone on df3345d

**Comment by sudden6** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

_[src/video/videoframe.cpp, line 324 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOM6r8kiIxlEtSrIuRH:-KOM6r8kiIxlEtSrIuRI:-989024475) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.cpp#L324)):_

> ``` cpp
>  * dimension.
>  *
>  * @param frameSize the given frame size of QImage to generate. If frame size is 0, defaults to
> ```

A cosmetic change, I think using QSize() or null for source frame size would be better.

---

_[src/video/videoframe.cpp, line 335 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOM7SLp2KhuhmjA4p0D:-KOM7SLqCRSNspo2V9L8:-293896269) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.cpp#L335)):_

> ``` cpp
>         frameSize = sourceDimensions.size();
>     }
> ```

What happens if `frameSize` is invalid?

---

_[src/video/videoframe.cpp, line 509 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMA0OHjqrBwfjU79Jq:-KOMA0OIsEa8CSsV4EE-:277466799) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.cpp#L509)):_

> ``` cpp
>     FrameBufferKey frameKey = getFrameKey(dimensions, pixelFormat, frame->linesize[0]);
> 
>     // We check the prescence of the frame in case of double-computation
> ```

double-computation?

---

_[src/video/videoframe.h, line 89 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMFOBMxFOaSPtFJre5:-KOMFOBNmKZE7upRdCn_:618698326) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L89)):_

> ``` objc
>      * @return an integer representing the ID of this frame.
>      */
>     inline IDType getFrameID() const
> ```

I think even one line functions should be in the cpp file.

---

_[src/video/videoframe.h, line 114 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMCD4Aqiutjzz8oIvN:-KOMCD4Aqiutjzz8oIvO:1461981161) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L114)):_

> ``` objc
>     /**
>      * @brief Retrieves a copy of the source VideoFormat's pixel format.
>      * @return integer copy represetning the source VideoFrame's pixel format.
> ```

typo: representing

---

_[src/video/videoframe.h, line 177 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMDpXHanyU1dSjAFHA:-KOMDpXI-ciSuy33wrlK:1947383929) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L177)):_

> ``` objc
>             std::hash<bool> boolHasher;
> 
>             // Use java-style hash function to combine fields
> ```

this could use some explanation of the magic values or link to some documentation

---

_[src/video/videoframe.h, line 249 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMFkNdJD4FuxNMYZvK:-KOMFkNdJD4FuxNMYZvL:-1174884445) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L249)):_

> ``` objc
>      */
>     template <typename T>
>     T toGenericObject(const QSize& dimensions, const int pixelFormat, const bool requireAligned,
> ```

I don't know if this is possible with templates, but this should definitely be in the cpp file.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185)_

**Comment by initramfs** [comment]
Review status: 0 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

_[src/video/videoframe.cpp, line 324 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOM6r8kiIxlEtSrIuRH:-KONA9JVC72FOfMkrUwL:-499146009) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.cpp#L324)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> A cosmetic change, I think using QSize() or null for source frame size would be better.
> </details>
> Done.

---

_[src/video/videoframe.cpp, line 335 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOM7SLp2KhuhmjA4p0D:-KONA9mDL6ViIP1WdzBz:779800655) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.cpp#L335)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> What happens if `frameSize` is invalid?
> </details>
> I've added a commit to honour QSize validity (now checks against `isValid()` rather than if the dimensions are zero). Documentation has been updated appropriately to indicate which functions require a valid frame size.

---

_[src/video/videoframe.cpp, line 509 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMA0OHjqrBwfjU79Jq:-KON34F0xdLBdTMobTUV:-1651346647) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.cpp#L509)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> double-computation?
> </details>
> It's hard to explain in the documentation but it's possible (but rare) for two threads to both call this function with the same parameters.

For example, if thread A and B both call `toQImage()` _simultanously_ and the required AVFrame does not exist (no pixel formats match, etc) both threads will end up generating a new `AVFrame` (since there is no contention against a read lock). The actual storage of this `AVFrame` is done whilst a write-lock is being held, resulting in a staggered but double call to `storeAVFrame()`. The if-condition basically says "if this exact frame type already exists in the frame buffer, free the new frame"

Anyhow, I changed the function a bit and added a lot more documentation.

---

_[src/video/videoframe.h, line 89 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMFOBMxFOaSPtFJre5:-KONH_n_6_6XZnfclRUm:-499146009) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L89)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> I think even one line functions should be in the cpp file.
> </details>
> Done.

---

_[src/video/videoframe.h, line 114 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMCD4Aqiutjzz8oIvN:-KONA0C-zSTQfxPnja-A:-499146009) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L114)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> typo: representing
> </details>
> Done.

---

_[src/video/videoframe.h, line 177 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMDpXHanyU1dSjAFHA:-KONHdz4auUmqan7K7TI:2113671447) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L177)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> this could use some explanation of the magic values or link to some documentation
> </details>
> Magic value is just a random prime number, but nevertheless a link in docs has been added.

---

_[src/video/videoframe.h, line 249 [r14]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOMFkNdJD4FuxNMYZvK:-KONHoe1lmPDZhOUvJ7_:-499146009) ([raw file](https://github.com/qtox/qtox/blob/df3345dce5827672a4106b11575728690fcd38f2/src/video/videoframe.h#L249)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> I don't know if this is possible with templates, but this should definitely be in the cpp file.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185)_

**Comment by sudden6** [comment]
Reviewed 1 of 4 files at r1, 1 of 5 files at r7, 1 of 2 files at r10, 2 of 3 files at r13.
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/video/videoframe.cpp, line 210 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUdv8VAv5AEfLEjlfD:-KOUdv8VAv5AEfLEjlfE:b-lzd3l9) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.cpp#L210)):_

> ``` cpp
>     {
>         // We need to add a new source to our reference map, obtain write lock
>         refsLock.unlock();
> ```

doesn't `unlock()` and then `lockForWrite()` open the possibility for a write in between?

---

_[src/video/videoframe.cpp, line 359 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUez4bI-jCIb57qrja:-KOUez4cTcKm8Lfx8nzj:br2895c) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.cpp#L359)):_

> ``` cpp
>  * @param frameSize the given frame size of ToxAVFrame to generate. Defaults to source frame size
>  * if frameSize is invalid.
>  * to source frame size.
> ```

this line doesn't seem to fit in here

---

_[src/video/videoframe.cpp, line 450 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUfV7h1LY5XAEOw0rJ:-KOUfV7h1LY5XAEOw0rK:b182dtw) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.cpp#L450)):_

> ``` cpp
>  */
> bool VideoFrame::FrameBufferKey::operator==(const FrameBufferKey& other) const
> {
> ```

`other == null` check necessary?

---

_[src/video/videoframe.h, line 39 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUb3K84CF_yV0MNY8d:-KOUb3K95_4YKtUnAY2h:bnqu943) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.h#L39)):_

> ``` objc
> #include <unordered_map>
> 
> struct ToxYUVFrame
> ```

It could be handy to provide a `isValid()` function for ToxYUVFrame to make checking for a valid frame easier and more abstracted.

---

_[src/video/videosource.h, line 47 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUjPHjuJkrzl6Q9lDk:-KOUjPHkVAgo6g3X2K0A:b-6lqy3) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videosource.h#L47)):_

> ``` objc
>      * @brief If subscribe sucessfully opens the source, it will start emitting frameAvailable signals.
>      */
>     virtual bool subscribe() = 0;    
> ```

some stray whitespace here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185)_

**Comment by initramfs** [comment]
Review status: 5 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/video/videoframe.cpp, line 210 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUdv8VAv5AEfLEjlfD:-KOUyKUak_X9Qixicu2j:b-qkkgvd) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.cpp#L210)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> doesn't `unlock()` and then `lockForWrite()` open the possibility for a write in between?
> </details>
> No, it only opens the possibility that two threads both pass the `if(refsMap.count(sourceID) == 0)` check.

But this doesn't matter, since the way the elements are accessed are via the [] operator (e.g `mutexMap[sourceID]`). This operator only creates an object if the given object doesn't already exist (it's actually one of the main reasons I used `std::unordered_map` over Qt stuff [I get behavioral guarantees]). The whole structure is a [double-checked locking](https://en.wikipedia.org/wiki/Double-checked_locking) system.

To illustrate:
1. Given that read locks can be concurrently held by two readers, say A and B.
2. Both readers concurrently call `trackFrame()`.
3. Both readers pass the if-condition (`refsMap` doesn't contain the given source).
4. The write lock causes the readers to enter mutual exclusion mode (only single access at a time).
5. Assume A wins the write lock, it calls `mutexMap[sourceID]` creating an object only if it doesn't already exist (as stated by the C++ std library docs).
6. A exits the critical section, B enters.
7. At this point the call to `mutexMap[sourceID]` does **not** create a new object, since it checks again to see if an object already exists.
8. Any further accesses stay in read lock mode, allowing for full concurrency.

---

_[src/video/videoframe.cpp, line 359 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUez4bI-jCIb57qrja:-KOV-hKrGWXBvTt6rPPW:b-p4ybu) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.cpp#L359)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> this line doesn't seem to fit in here
> </details>
> Oops, fixed.

---

_[src/video/videoframe.cpp, line 450 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUfV7h1LY5XAEOw0rJ:-KOV0QRGKehe0Q_thjMd:b-j62zzg) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.cpp#L450)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> `other == null` check necessary?
> </details>
> The function takes `other` via const-reference, you can't have a null reference.

---

_[src/video/videoframe.h, line 39 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUb3K84CF_yV0MNY8d:-KOV2axGVcqpfX01JH8e:b-l0b8g7) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videoframe.h#L39)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> It could be handy to provide a `isValid()` function for ToxYUVFrame to make checking for a valid frame easier and more abstracted.
> </details>
> Done. I've also modified the check in CoreAV to use the new function.

---

_[src/video/videosource.h, line 47 [r15]](https://reviewable.io:443/reviews/qtox/qtox/3185#-KOUjPHjuJkrzl6Q9lDk:-KOV4FXuV86zV5pZa5Mf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5b31b5db723e97daa7404d5c17ee9340d97198e8/src/video/videosource.h#L47)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> some stray whitespace here
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 8 files at r4, 4 of 4 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185#-:-KOVEmqDg9b4HUjmjvIK:bnfp4nl)_

**Comment by sudden6** [comment]
@antis81 could you take a final look?

**Comment by antis81** [comment]
Reviewed 1 of 4 files at r1, 1 of 8 files at r4, 1 of 5 files at r7, 1 of 2 files at r10, 2 of 3 files at r13, 4 of 4 files at r16.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185)_

**Comment by sudden6** [comment]
@antis81 lgtm?

**Comment by antis81** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3185#-:-KOfu5hyB2uhnTDpW55t:bnfp4nl)_

**Pull request merged**
