### PR TITLE
fix(icon): add more size versions to qtox.ico

### LINKED ISSUE #2671: Windows: Icons in file properties displayed incorrectly and too less sizes
Just right-click on `qtox.exe` or `qtox-updater.exe` and choose `Properties`:
propertiesicons

This grey part does not look nice. :smile: 

v1.2.1

### PR DESCRIPTION
**Pull request by Vort**
According to Microsoft's recomendations, icon files should contain images with different sizes and bit depths:
* [Creating Windows XP Icons. Step 5: Creating the .ico Files](https://msdn.microsoft.com/en-us/library/ms997636.aspx#winxpicons_step5)
* [Icons. Size requirements](https://msdn.microsoft.com/en-us/library/windows/desktop/dn742485.aspx#size_requirements)

This pull request adds a script to generate such icons from single .svg file.
Also icon file is updated (without changing logo design).

This script is optimized for current logo and not intended to be embedded to build process.
It is there just for the case if someone will need to update icon file once again.

I have tested this icon with Windows 7 and Windows XP, but more testing is appreciated.
Here is the screenshots with different use cases of new and old icon:
qtox_ico_compare

Fixes #2671

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4127)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4127#-:-Kc3jSpKHZLetCkFIj2q:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_cancel:  On a second pass we found some small issues

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4127#-:-Kc86CZIhbZoPmE_zUUT:bcvkk20)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[windows/generate_icon.sh, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4127#-Kc86TCK5q6Wyby5gOLC:-Kc86TCL2NEvc3Jkm5HG:b-882e6a) ([raw file](https://github.com/qtox/qtox/blob/adefaa09269eada3adf8b07af8c62167a92c4a69/windows/generate_icon.sh#L1)):*
> ```Shell
> # Generates qtox.ico from qtox.svg
> ```

The script is missing a copyright header and `#!/bin/bash`

---

*[windows/generate_icon.sh, line 8 at r1](https://reviewable.io:443/reviews/qtox/qtox/4127#-Kc86JyjVeRQ0Fo5s7ie:-Kc86JyjVeRQ0Fo5s7if:betde92) ([raw file](https://github.com/qtox/qtox/blob/adefaa09269eada3adf8b07af8c62167a92c4a69/windows/generate_icon.sh#L8)):*
> ```Shell
> #   icoutils 0.31.0
> #
> base64 -d <<< R0lGODlhBAABAPEAAAAAAAAAAICAgMDAwCH5BAEAAAAALAAAAAAEAAEAAAIDjAYFADs= > pal.gif
> ```

Could you add a comment what this binary data is and where it comes from?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4127)*

**Comment by Vort** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[windows/generate-icon.sh, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4127#-Kc86TCK5q6Wyby5gOLC:-Kc8DE_HXKDshv8UiOST:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/adefaa09269eada3adf8b07af8c62167a92c4a69/windows/generate-icon.sh#L1)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The script is missing a copyright header and `#!/bin/bash`
</blockquote></details>

Done.

---

*[windows/generate-icon.sh, line 8 at r1](https://reviewable.io:443/reviews/qtox/qtox/4127#-Kc86JyjVeRQ0Fo5s7ie:-Kc8DGvVUeISrBg3nujf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/adefaa09269eada3adf8b07af8c62167a92c4a69/windows/generate-icon.sh#L8)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Could you add a comment what this binary data is and where it comes from?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4127)*

**Comment by Vort** [comment]
Please recheck.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4127#-:-Kc8X7BsDqJIdeo94pAR:bpx0cei)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4127#-:-Kc8Z2XVbq8q3-xKUSgR:b-jbsf8z)*

**Pull request merged**
