### PR TITLE
Friend widget

### PR DESCRIPTION
**Pull request by Diadlo**
Removed `FriendWidget` from `Friend` class

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3838)

### CODE REVIEW

**Comment by zetok** [comment]
on c27bb370d2823e1d08aed0e79fe21d37b58182de:

```
[07:20:12.369 UTC] audio/audio.cpp:384 : Debug: Opened audio input "Live! Cam Chat HD [VF0700] Analog Mono"
[07:20:12.369 UTC] audio/audio.cpp:312 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[07:20:12.369 UTC] audio/audio.cpp:401 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fffa2ff4700 (LWP 8281)]
[07:20:12.371 UTC] audio/audio.cpp:416 : Debug: Opened audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fffa30f5700 (LWP 8286)]
[07:20:12.372 UTC] audio/audio.cpp:685 : Debug: Audio source 2 created. Sources active: 1
[07:20:12.372 UTC] video/camerasource.cpp:269 : Debug: Opening device  "/dev/video0"
[mjpeg @ 0x7fffc006de40] Changeing bps to 8
[07:20:13.358 UTC] audio/audio.cpp:312 : Debug: Subscribed to audio input device [ 2 subscriptions ]
[07:20:13.358 UTC] audio/audio.cpp:328 : Debug: Unsubscribed from audio input device [ 1 subscriptions left ]
[07:20:13.362 UTC] widget/form/chatform.cpp:527 : Debug: enableCallButtons
[07:20:13.363 UTC] widget/form/chatform.cpp:540 : Debug: timer started!!
[07:20:13.382 UTC] widget/form/chatform.cpp:341 : Debug: onAvStart
[07:20:13.384 UTC] widget/form/chatform.cpp:672 : Debug: creating netcam
[07:20:13.386 UTC] video/netcamview.cpp:89 : Debug: SIZER QRect(0,0 1280x720)
[07:20:13.477 UTC] video/camerasource.cpp:269 : Debug: Opening device  "/dev/video0"

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff7f4da700 (LWP 6277)]
0x00007ffff7ba8938 in friend_not_valid (m=0x7fffb813a480, friendnumber=10)
    at ../toxcore/Messenger.c:47
47          if (m->friendlist[friendnumber].status != 0) {
(gdb) bt
#0  0x00007ffff7ba8938 in friend_not_valid (m=0x7fffb813a480, friendnumber=10)
    at ../toxcore/Messenger.c:47
#1  0x00007ffff7ba9ae4 in m_friend_exists (m=0x7fffb813a480, friendnumber=10)
    at ../toxcore/Messenger.c:439
#2  0x00007ffff798083a in toxav_video_send_frame (av=0x7fffb8057370, 
    friend_number=10, width=1280, height=720, y=0x7fff701dba40 "", 
    u=0x7fff702bca40 '\200' <repeats 200 times>..., 
    v=0x7fff702f4e40 '\200' <repeats 200 times>..., error=0x7fff7f4d99dc)
    at ../toxav/toxav.c:748
#3  0x00005555555c8aed in CoreAV::sendCallVideo (this=0x7fffb8056120, callId=10, 
    vframe=std::shared_ptr (count 3, weak 1) 0x7fff70007d60)
    at src/core/coreav.cpp:374
#4  0x00005555555d67ea in ToxFriendCall::<lambda(std::shared_ptr<VideoFrame>)>::operator() (frame=..., __closure=<optimized out>) at src/core/toxcall.cpp:127
#5  QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<std::shared_ptr<VideoFrame> >, void, ToxFriendCall::ToxFriendCall(uint32_t, bool, CoreAV&)::<lambda(std::shared_ptr<VideoFrame>)> >::call (arg=<optimized out>, f=...)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:495
#6  QtPrivate::Functor<ToxFriendCall::ToxFriendCall(uint32_t, bool, CoreAV&)::<lambda(std::shared_ptr<VideoFrame>)>, 1>::call<QtPrivate::List<std::shared_ptr<VideoFrame> >, void> (arg=<optimized out>, f=...)
    at /usr/include/qt5/QtCore/qobjectdefs_impl.h:552
#7  QtPrivate::QFunctorSlotObject<ToxFriendCall::ToxFriendCall(uint32_t, bool, CoreAV&)::<lambda(std::shared_ptr<VideoFrame>)>, 1, QtPrivate::List<std::shared_ptr<VideoFrame> >, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, 
    a=<optimized out>, ret=<optimized out>)
    at /usr/include/qt5/QtCore/qobject_impl.h:192
#8  0x00007ffff37fef9f in QtPrivate::QSlotObjectBase::call (a=0x7fff7f4d9c00, 
    r=0x5555561190b0, this=0x7fffb0135ab0)
    at ../../include/QtCore/../../src/corelib/kernel/qobject_impl.h:124
#9  QMetaObject::activate (sender=sender@entry=0x5555561190b0, 
    signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, 
    argv=argv@entry=0x7fff7f4d9c00) at kernel/qobject.cpp:3715
#10 0x00007ffff37ff3e7 in QMetaObject::activate (
    sender=sender@entry=0x5555561190b0, 
    m=m@entry=0x555555d0f240 <VideoSource::staticMetaObject>, 
    local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fff7f4d9c00)
    at kernel/qobject.cpp:3595
#11 0x00005555556d3674 in VideoSource::frameAvailable (
    this=this@entry=0x5555561190b0, 
    _t1=std::shared_ptr (count 3, weak 1) 0x7fff70007d60)
    at moc_videosource.cpp:141
#12 0x000055555563a4fe in CameraSource::<lambda()>::operator() (
    __closure=<synthetic pointer>) at src/video/camerasource.cpp:395
#13 CameraSource::stream (this=0x5555561190b0) at src/video/camerasource.cpp:412
#14 0x00005555555cb6ed in QtConcurrent::RunFunctionTask<void>::run (
    this=0x7fffc013c0a0) at /usr/include/qt5/QtConcurrent/qtconcurrentrunbase.h:130
#15 0x00007ffff35fa17d in QThreadPoolThread::run (this=0x7fffb0135c70)
    at thread/qthreadpool.cpp:93
#16 0x00007ffff35ff28c in QThreadPrivate::start (arg=0x7fffb0135c70)
    at thread/qthread_unix.cpp:341
#17 0x00007ffff30c05f4 in start_thread (arg=0x7fff7f4da700) at pthread_create.c:334
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff25978dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

`t a a bt`: https://gist.github.com/zetok/174b6c23077cc9572ae3405f757be757

Steps to reproduce (not sure if all are necessary):
1. Multiple windows mode
2. Open settings
3. Open Profile
4. Open friend window (chatform)
5. Open About friend window
6. Video call friend (other side autoaccepts)
7. Once call is going on, logout
8. Load same profile
9. Repeat previous steps, that will result in a segfault at accepting video step

**Comment by Diadlo** [comment]
@zetok Ups.. We have new issue. I can reproduce on current master

**Comment by zetok** [comment]
k, made #3840

**Comment by sudden6** [comment]
Reviewed 1 of 17 files at r3.
Review status: 1 of 20 files reviewed at latest revision, 7 unresolved discussions.

---

_[src/friend.cpp, line 63 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBb2SOnCqGsX-iUl1G:-KVBb2SP7AeqYgY0DZ0j:beo7am2) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friend.cpp#L63)):_

> ``` cpp
>     {
>         userName = name;
>         chatForm->setName(name);
> ```

Isn't this basically redundant with the next line? chatForm could connect to the nameChanged Signal. With the approach here we're mixing the callback and signal approach. In Qt the signal approach is clearly favored.

---

_[src/friend.cpp, line 79 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBbJTg5ayaGoKp67zK:-KVBbJThN4MGwMrSJAn9:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friend.cpp#L79)):_

> ``` cpp
>     {
>         userAlias = alias;
>         chatForm->setName(alias);
> ```

Same as above

---

_[src/friend.cpp, line 96 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBbPSa97mIqg5_4trw:-KVBbPSbofBEgeDtUypf:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friend.cpp#L96)):_

> ``` cpp
>     {
>         statusMessage = message;
>         chatForm->setStatusMessage(message);
> ```

Same as above

---

_[src/friendlist.cpp, line 25 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBlmcawJUDAAlf0MhS:-KVBlmcb8UDzvw4v0MB0:b-yqa2qj) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friendlist.cpp#L25)):_

> ``` cpp
> #include <QMenu>
> #include <QDebug>
> #include <QHash>
> ```

A `containsFriend((const ToxId& userId)` method would be handy, would simplify a lot of code in this PR.

---

_[src/widget/circlewidget.cpp, line 147 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBfE4pSLTrqzkyul6w:-KVBfE4qWHWKOgMV7ih_:b-6rxo6v) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/widget/circlewidget.cpp#L147)):_

> ``` cpp
> void CircleWidget::dragEnterEvent(QDragEnterEvent* event)
> {
>     ToxId toxId(event->mimeData()->text());
> ```

Does this allow any text to enter the circle? If so we should check for a valid ToxId.

---

_[src/widget/friendlistwidget.cpp, line 331 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBhwp4aSZhgvuuU3Sb:-KVBhwp5zdt6k28HD3kq:b8l6hm8) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/widget/friendlistwidget.cpp#L331)):_

> ``` cpp
> }
> 
> void FriendListWidget::moveFriends(QLayout *layout)
> ```

documentation needed here

---

_[src/widget/form/chatform.cpp, line 324 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBl6JqUkYpSSxAdgBs:-KVBl6JrAYVX1x3B8ErP:bxlnids) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/widget/form/chatform.cpp#L324)):_

> ``` cpp
>         connect(callConfirm, &CallConfirmWidget::rejected, this, &ChatForm::onRejectCallTriggered);
> 
>        insertChatMessage(ChatMessage::createChatInfoMessage(
> ```

Are you sure this should be part of this PR?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3838)_

**Comment by Diadlo** [comment]
Review status: 1 of 20 files reviewed at latest revision, 6 unresolved discussions.

---

_[src/friend.cpp, line 63 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBb2SOnCqGsX-iUl1G:-KVByVK8N8sfCF9VD8db:b-3kwfgu) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friend.cpp#L63)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Isn't this basically redundant with the next line? chatForm could connect to the nameChanged Signal. With the approach here we're mixing the callback and signal approach. In Qt the signal approach is clearly favored.
> </details>
> I plan remove chatForm from Friend in next PR. But if you think, that better do it here -- I can.

---

_[src/friend.cpp, line 79 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBbJTg5ayaGoKp67zK:-KVC5_AopdKoNr4SBCxz:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friend.cpp#L79)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Same as above
> </details>
> Same as above

---

_[src/friend.cpp, line 96 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBbPSa97mIqg5_4trw:-KVC5abV7jUmvR887Ceb:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friend.cpp#L96)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Same as above
> </details>
> Same as above

---

_[src/friendlist.cpp, line 25 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBlmcawJUDAAlf0MhS:-KVC0BfNkCbFQaYieohh:b3kqx) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/friendlist.cpp#L25)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> A `containsFriend((const ToxId& userId)` method would be handy, would simplify a lot of code in this PR.
> </details>
> .

---

_[src/widget/circlewidget.cpp, line 147 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBfE4pSLTrqzkyul6w:-KVBzBL5f4UGi3a387Vd:brktcy3) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/widget/circlewidget.cpp#L147)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Does this allow any text to enter the circle? If so we should check for a valid ToxId.
> </details>
> `findFriend` return nullptr, for invalid `toxId`

---

_[src/widget/friendlistwidget.cpp, line 331 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBhwp4aSZhgvuuU3Sb:-KVCGXL3W-5wgbzNSKQi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/widget/friendlistwidget.cpp#L331)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> documentation needed here
> </details>
> Done.

---

_[src/widget/form/chatform.cpp, line 324 at r3](https://reviewable.io:443/reviews/qtox/qtox/3838#-KVBl6JqUkYpSSxAdgBs:-KVC-NV2igBKVCQWByCs:b3yzlfa) ([raw file](https://github.com/qtox/qtox/blob/c27bb370d2823e1d08aed0e79fe21d37b58182de/src/widget/form/chatform.cpp#L324)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Are you sure this should be part of this PR?
> </details>
> It seems that accidentally cherry-picked from source PR
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3838)_

**Comment by HuuThanhHung** [comment]
hello guy i am the newbie, so can i ask where can i find friendlist.ui

**Comment by anthonybilinski** [comment]
@HuuThanhHung I don't think we have Qt designer (.ui) file for friendlist. The friendlist is unfortunately created entirely in code with `FriendListWidget`'s layout being `FriendListLayout`.

**Comment by HuuThanhHung** [comment]
Thank you @anthonybilinski but you can show me the flow of tox when we click on one friend in friendlist and click on call button?

**Comment by Diadlo** [comment]
@HuuThanhHung 

(widget.cpp:1007) `connect(widget, &FriendWidget::chatroomWidgetClicked, friendForm, &ChatForm::focusInput);`
When friend widget in firned list will be clicked `ChatForm` will be focused

(chatform.cpp:164) `connect(headWidget, &ChatFormHeader::callTriggered, this, &ChatForm::onCallTriggered);`
`headWidget` it's part of `ChatForm` with call buttons. When call button pressed `onCallTriggered` called

(chatform.cpp:482) `av->startCall(friendId, false)`

**Comment by HuuThanhHung** [comment]
Thanks so much @Diadlo

**Comment by HuuThanhHung** [comment]
Hi all, 
Can you explain for me how can this function can connect and activate the call button?


(moc_chatfoemheader.cpp:210)
void ChatFormHeader::callTriggered()
{
    QMetaObject::activate(this, &staticMetaObject, 0, nullptr);
}


i want to set when i click on 1 friend in my friendlist it will make the call immediately.
Hope someone can help me! thanks so much!

**Pull request closed without merging**
