### PR TITLE
refactor(toxdns): Removed using of toxdns

### PR DESCRIPTION
**Pull request by Diadlo**
TokTok/toxcore/issues/42

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3648)

### CODE REVIEW

**Comment by sudden6** [comment]
Commit message needs `BREAKING CHANGE:`

**Comment by sudden6** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3648)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3648#-:-KQB-HnIglJe_6xbtA_w:bnfp4nl)_

**Comment by iphydf** [comment]
FYI, there are still mentions to toxdns in translations (hashtag codehealth).

**Comment by Diadlo** [comment]
@iphydf Weblate will remove it automatically with next translation

**Pull request merged**
