### PR TITLE
Don't dereference Tox_Options, use getters instead.

### PR DESCRIPTION
**Pull request by iphydf**
Depending on Tox_Options structure layout is deprecated. We will remove
it from the public API in the future.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4918)

### CODE REVIEW

**Comment by Diadlo** [comment]
Is removing really needed, if it's just a struct with settings? What is the reason?

**Comment by iphydf** [comment]
@Diadlo ABI compatibility. Right now we can't change the struct layout or even add fields to it without breaking the ABI, because people may allocate them in the client code.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4918#-:-L3-bNkzAuGVbEWu_DYn:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4918#-:-L4blpbd6bt9X8vG-LV6:b-jbsf8z)*

**Pull request merged**
