### PR TITLE
refactor: Core refactoring

### PR DESCRIPTION
**Pull request by noavarice**
Brief list of changes:
  - removed unnecessary headers from core.h and core.cpp;
  - added missing brackets and aligned long lists of parameters;
  - some other small changes.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4316)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.cpp, line 357 at r1](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgiIzdQPRkvqJnkXXrt:-KgiIzdRWEWwTuMLD2qd:b-k4sy3o) ([raw file](https://github.com/qtox/qtox/blob/a4a5d29b65d51afae0b8476f44ba0c45fea5c742/src/core/core.cpp#L357)):*
> ```cpp
> bool Core::checkConnection()
> {
>     static bool isConnected = false;
> ```

You changed the logic by removing this part

---

*[src/core/core.cpp, line 412 at r1](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgiHMv-2NyDylVTQxJW:-KgiHMv0b8rrOueinNPr:b6wierj) ([raw file](https://github.com/qtox/qtox/blob/0fdd5d5ce49a7592d107a28a854d6d04d30f1c41/src/core/core.cpp#L412)):*
> ```cpp
> }
> 
> void Core::onFriendRequest(Tox*,
> ```

Did you run `tools/format-source.sh`? I think it will undo these changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by noavarice** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.cpp, line 357 at r1](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgiIzdQPRkvqJnkXXrt:-KgiPBczSStvPLmq9LKX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a4a5d29b65d51afae0b8476f44ba0c45fea5c742/src/core/core.cpp#L357)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

You changed the logic by removing this part
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by sudden6** [comment]
please run `tools/format-source.sh` and commit the changes to the files of this PR.

**Comment by noavarice** [comment]
This made whole bunch of changes, so it is out of this PR

**Comment by sudden6** [comment]
commit only the changes from the three files included in this PR

**Comment by noavarice** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.cpp, line 412 at r1](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgiHMv-2NyDylVTQxJW:-Kgk4EPc-vRRev_-E0Ua:b-4trigu) ([raw file](https://github.com/qtox/qtox/blob/0fdd5d5ce49a7592d107a28a854d6d04d30f1c41/src/core/core.cpp#L412)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Did you run `tools/format-source.sh`? I think it will undo these changes
</blockquote></details>

No, it's not. Only parameters' alignment was affected. Should i commit these changes anyway?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r3.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.cpp, line 412 at r1](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgiHMv-2NyDylVTQxJW:-KgkDd8aVF5r_Tf5_PPx:b-d7qoys) ([raw file](https://github.com/qtox/qtox/blob/0fdd5d5ce49a7592d107a28a854d6d04d30f1c41/src/core/core.cpp#L412)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

No, it's not. Only parameters' alignment was affected. Should i commit these changes anyway?
</blockquote></details>

commit the file with the changes made by the script, all code should be formatted by this script prior to making a PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by noavarice** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/core.cpp, line 412 at r1](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgiHMv-2NyDylVTQxJW:-KgkSYzyzuOIXeiUhGWJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0fdd5d5ce49a7592d107a28a854d6d04d30f1c41/src/core/core.cpp#L412)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

commit the file with the changes made by the script, all code should be formatted by this script prior to making a PR
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316#-:-KgkU7A4uhnajP70PPFs:b-jbsf8z)*

**Comment by Diadlo** [comment]
Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 407 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmPghJcdsaO0QS14cq:-KgmPghJcdsaO0QS14cr:b-91fb4x) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L407)):*
> ```cpp
>         const DhtServer& dhtServer = dhtServerList[j % listSize];
>         qDebug() << QString("Connecting to %1:%2 (%3)")
>                         .arg(QString(dhtServer.address.toLatin1()), QString::number(dhtServer.port),
> ```

Can you extract QStrings in to variable?

---

*[src/core/core.cpp, line 602 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmQk4yzAx-zoq1tKkO:-KgmQk4yzAx-zoq1tKkP:b-q5gfh9) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L602)):*
> ```cpp
> {
>     Profile* profile = Nexus::getProfile();
>     if (profile->isHistoryEnabled()) {
> ```

What about early break?

---

*[src/core/core.cpp, line 615 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRQ0lJDINmgKvcpeo:-KgmRQ0lJDINmgKvcpep:b-5fcek9) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L615)):*
> ```cpp
>     ToxPk friendPk = friendId.getPublicKey();
>     QString errorMessage = getFriendRequestErrorMessage(friendId, message);
>     if (!errorMessage.isNull()) {
> ```

What about early break?

---

*[src/core/core.cpp, line 628 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRY69qnolJnJIQTOj:-KgmRY69qnolJnJIQTOk:b-d6uf0s) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L628)):*
> ```cpp
>             Settings::getInstance().updateFriendAddress(friendId.toString());
> 
>             // TODO: start: this really shouldn't be in Core
> ```

Since block was removed, `start` and `end` can be removed from TODO

---

*[src/core/core.cpp, line 674 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRuRM0K85N68_Fp55:-KgmRuRM0K85N68_Fp56:b-4zxdjk) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L674)):*
> ```cpp
>         ToxString cMsg(part);
>         TOX_ERR_CONFERENCE_SEND_MESSAGE error;
>         bool ok = tox_conference_send_message(tox, groupId, type, cMsg.data(), cMsg.size(), &error);
> ```

Just a note: you forget to change same var in another functions :)

---

*[src/core/core.cpp, line 888 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmSPMjr-aa6njcPlPu:-KgmSPMjr-aa6njcPlPv:b-txxx1) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L888)):*
> ```cpp
>  * @return Self PK
>  */
> ToxPk Core::getSelfPublicKey() const
> ```

We can extract PK from ToxId. Do we really need this method?

---

*[src/core/core.cpp, line 1029 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmT07pbfu51vw-xEdH:-KgmT07pbfu51vw-xEdI:b-fscvfm) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1029)):*
> ```cpp
>     uint8_t friendPk[TOX_PUBLIC_KEY_SIZE] = {0x00};
>     for (uint32_t i = 0; i < friendCount; ++i) {
>         if (!tox_friend_get_public_key(tox, ids[i], friendPk, nullptr)) {
> ```

What do you think about creation `loadFriend` method (load one friend info)?

---

*[src/core/core.cpp, line 1262 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmUX5NokHz-L0bfRMd:-KgmUX5NokHz-L0bfRMe:b-q037mt) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1262)):*
> ```cpp
>         uint32_t groupId = tox_conference_join(tox, friendId, friendGroupPK, length, &error);
>         return parseConferenceJoinError(error) ? groupId : std::numeric_limits<uint32_t>::max();
>     } else if (type == TOX_CONFERENCE_TYPE_AV) {
> ```

You can remove `else` after `return`. Or change it on `switch`?

---

*[src/core/core.cpp, line 1409 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmVImASmoYCguJCh5d:-KgmVImASmoYCguJCh5e:b2bmjf3) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1409)):*
> ```cpp
>             if (ba_message[splitPos] & 0x80) {
>                 do {
>                     splitPos--;
> ```

Forget to change postfix on prefix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by noavarice** [comment]
Review status: 2 of 3 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[src/core/core.cpp, line 407 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmPghJcdsaO0QS14cq:-KgmqDE-036Weo8ZrST7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L407)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can you extract QStrings in to variable?
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 602 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmQk4yzAx-zoq1tKkO:-KgmsCONBL-v3gtsYpab:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L602)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about early break?
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 615 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRQ0lJDINmgKvcpeo:-Kgms9M7WDlSi3q65nsN:bmeo1si) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L615)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about early break?
</blockquote></details>

There is `saveToxSave` call in both branches of condition, how to make early break here?

---

*[src/core/core.cpp, line 628 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRY69qnolJnJIQTOj:-KgmijF78VISGb6fh7Vi:b-yguk9n) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L628)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Since block was removed, `start` and `end` can be removed from TODO
</blockquote></details>

I don't sure that TODO has fixed with this change. Can remove if you want)

---

*[src/core/core.cpp, line 674 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRuRM0K85N68_Fp55:-KgmjSIbfMdXAkwF62K_:bw948me) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L674)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Just a note: you forget to change same var in another functions :)
</blockquote></details>

I change it just to make line length lesser than 100 smb

---

*[src/core/core.cpp, line 888 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmSPMjr-aa6njcPlPu:-KgmiBhdNGsx3A4AxJGI:ba4nqqj) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L888)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

We can extract PK from ToxId. Do we really need this method?
</blockquote></details>

That's the point why I add this method - to get PK directly from `tox_self_get_address` and not from `ToxId`

---

*[src/core/core.cpp, line 1029 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmT07pbfu51vw-xEdH:-Kgmk5zEeyqJIim6ANHF:bo4k5sm) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1029)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What do you think about creation `loadFriend` method (load one friend info)?
</blockquote></details>

Should this method return `Friend` or something else?

---

*[src/core/core.cpp, line 1262 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmUX5NokHz-L0bfRMd:-KgmsYKcn0dcsBa5GWgd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1262)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

You can remove `else` after `return`. Or change it on `switch`?
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 1409 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmVImASmoYCguJCh5d:-KgmsZGQeQaoWjtesQHY:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1409)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Forget to change postfix on prefix
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 615 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRQ0lJDINmgKvcpeo:-Kgnp7yQqjwvoI5hJMoE:b-qkspiq) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L615)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

There is `saveToxSave` call in both branches of condition, how to make early break here?
</blockquote></details>

Add it in both cases

---

*[src/core/core.cpp, line 628 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRY69qnolJnJIQTOj:-KgnpInGXJXdbCzuYdNw:bbo50zi) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L628)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I don't sure that TODO has fixed with this change. Can remove if you want)
</blockquote></details>

Not fully removind. Only `start` and `end`

---

*[src/core/core.cpp, line 888 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmSPMjr-aa6njcPlPu:-Kgnpg5_4902-duEnah-:b-p7cdkm) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L888)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

That's the point why I add this method - to get PK directly from `tox_self_get_address` and not from `ToxId`
</blockquote></details>

IMO, it's code duplication, Feel free to leave

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by noavarice** [comment]
Review status: 2 of 3 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[src/core/core.cpp, line 615 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRQ0lJDINmgKvcpeo:-KgnyFv_ufoPbRQ_Pr3K:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L615)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add it in both cases
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 628 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmRY69qnolJnJIQTOj:-KgnyGwjLPbqDMBxPvqS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L628)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Not fully removind. Only `start` and `end`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 1029 at r4](https://reviewable.io:443/reviews/qtox/qtox/4316#-KgmT07pbfu51vw-xEdH:-KgoxsKkpay6lFD5PWw0:b-qk14xv) ([raw file](https://github.com/qtox/qtox/blob/a9e2ba163e820573903b265520a52b1b2645f65a/src/core/core.cpp#L1029)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Should this method return `Friend` or something else?
</blockquote></details>

Macros looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4316#-:-KgpKp7TwgtaOm2Z41PO:b-jbsf8z)*

**Pull request merged**
