### PR TITLE
Cppcheck

### PR DESCRIPTION
**Pull request by Diadlo**
Fix part of cppcheck warnings and last commit add 'Werror' flag

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4462)

### CODE REVIEW

**Comment by sudden6** [comment]
What exactly is the advantage of passing `std::function` as const reference?

---

Reviewed 14 of 21 files at r2.
Review status: 14 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.cpp, line 992 at r1](https://reviewable.io:443/reviews/qtox/qtox/4462#-KmQaBb6wPJlc8SJpPAz:-KmQaBb6wPJlc8SJpPB-:bwlvnb3) ([raw file](https://github.com/qtox/qtox/blob/9a0632b0cf8bc78d1aae0f2e75b26b73cdb98e52/src/core/core.cpp#L992)):*
> ```cpp
> {
>     const uint32_t friendCount = tox_self_get_friend_list_size(tox);
>     if (friendCount <= 0) {
> ```

Early return on `== 0` would still make sense, but decide for yourself

---

*[src/core/core.cpp, line 1080 at r2](https://reviewable.io:443/reviews/qtox/qtox/4462#-KmQaQ76aCZBjZxLxtZV:-KmQaQ76aCZBjZxLxtZW:bujq29f) ([raw file](https://github.com/qtox/qtox/blob/9a0632b0cf8bc78d1aae0f2e75b26b73cdb98e52/src/core/core.cpp#L1080)):*
> ```cpp
> QString Core::getGroupPeerName(int groupId, int peerId) const
> {
>     uint8_t nameArray[tox_max_name_length()];
> ```

The use of the function was done on purpose, maybe switch to `QByteArray`?

---

*[src/core/core.cpp, line 1141 at r2](https://reviewable.io:443/reviews/qtox/qtox/4462#-KmQacFU0hMuYe7pmknq:-KmQacFU0hMuYe7pmknr:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/9a0632b0cf8bc78d1aae0f2e75b26b73cdb98e52/src/core/core.cpp#L1141)):*
> ```cpp
>     QStringList names;
>     for (uint32_t i = 0; i < nPeers; ++i) {
>         uint8_t name[tox_max_name_length()];
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4462#-:-KmQc6aCpg3MZg7lPr0g:b-yiz6md)*

**Comment by Diadlo** [comment]
std::function isn't function pointer. It's object

---

Review status: 14 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.cpp, line 992 at r1](https://reviewable.io:443/reviews/qtox/qtox/4462#-KmQaBb6wPJlc8SJpPAz:-KmQgVGBLEUCy3LvDEqZ:b-y9r45v) ([raw file](https://github.com/qtox/qtox/blob/9a0632b0cf8bc78d1aae0f2e75b26b73cdb98e52/src/core/core.cpp#L992)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Early return on `== 0` would still make sense, but decide for yourself
</blockquote></details>

Thanks! Forget about this case. Done

---

*[src/core/core.cpp, line 1080 at r2](https://reviewable.io:443/reviews/qtox/qtox/4462#-KmQaQ76aCZBjZxLxtZV:-KmQgZ2uI6mgIW6NMh8P:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9a0632b0cf8bc78d1aae0f2e75b26b73cdb98e52/src/core/core.cpp#L1080)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The use of the function was done on purpose, maybe switch to `QByteArray`?
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 1141 at r2](https://reviewable.io:443/reviews/qtox/qtox/4462#-KmQacFU0hMuYe7pmknq:-KmQgZZOeN9aYnfzGifL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9a0632b0cf8bc78d1aae0f2e75b26b73cdb98e52/src/core/core.cpp#L1141)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4462#-:-KmQgUhQ7tkCYA0iIUg_:b-161cc8)*

**Comment by sudden6** [comment]
Reviewed 6 of 21 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4462)*

**Comment by Diadlo** [comment]
Removed `Werror` flag, because of [this](https://travis-ci.org/qTox/qTox/jobs/241973793#L2266)

**Comment by sudden6** [comment]
maybe we should change that `#warning` to `#message`? Or update Qt on Travis?

**Comment by Diadlo** [comment]
@sudden6 We can't update Qt since Qt 5.3.0 is minimal supported version. We can wait for next debian stable release to update minimal qt version, or replace warning in message. What do you prefer?

**Comment by sudden6** [comment]
I think we can wait for `-Werror` another ~5 days.

**Comment by Diadlo** [comment]
@sudden6 So lgtm?

**Comment by sudden6** [comment]
:lgtm_strong: sorry I forgot

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4462#-:-KmRgiEe84Q7M3_vzpQI:b-bcetxs)*

**Pull request merged**
