### PR TITLE
Update buttons - shows different cursors

### PR DESCRIPTION
**Pull request by proton-byte**
Feat: change some .css files so add the rule "cursor: pointer"

Shows the "pointer" cursor if the user hover over a button. It's then clearer that the user can press the button.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3499)

### CODE REVIEW

**Comment by sudden6** [comment]
Could you please change your commit messages to our format: https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by zetok** [comment]
Also, squash the commits.

**Comment by antis81** [comment]
@Proton-Byte In case you don't know how to do that. Here's how:

``` bash
# make sure you're on the right branch
git checkout patch-1

# start a rebase
git rebase -i master

# now replace the `pick` in first line in the "rebase todo" text file with `r` (reword) and on every subsequent line with `f` (fixup). Finally save and close the file.
# Example:
#     r c6924e5 Update callButton.css
#     f c6924e5 Update ….css
#     f c6924e5 Update ….css
#     …

# save and close the file

# Git will now guide you through the rebasing process and…
# …if everything's alright, force push your changes
git push -f
# First time add '--set-upstream origin master' - Git will tell you in this case.
```

Alright?

**Comment by zetok** [comment]
Hi,

As you might be aware, repo has been moved under `qTox` org on github.

What does it have to do with your PR, you might ask.

Well, it doesn't change all that much, except that workflow has been slightly improved – now there are required checks that PR needs to pass in order to be merged.

Those checks are:
- travis (checks whether PR builds & commit message format)
- reviewable (requirement for PR to be reviewed & accepted)

Since osx travis was broken for a bit, you will need to rebase your PR on newest master to get it to pass travis check. Sorry for inconvenience.

Reminder: as always, PR needs to be possible to merge without conflicts. Make sure it does ;)

**Comment by zetok** [comment]
I've [rebased & squashed](https://github.com/zetok/qTox/commit/c1cd72aa0c660dadef9f21cdb4068c1d07084ebc), but this doesn't change the behaviour of buttons, thus closing.

**Pull request closed without merging**
