### PR TITLE
fix(ui): updating friends list color at runtime

### LINKED ISSUE #5924: Dark theme leaves chatform unchanged until restart
##### Brief Description

OS: Ubuntu 19.10
qTox version: v1.16.3+
Commit hash:  1a726b54cd2e1d72c6cb6f0f9a733e904f5e5371
toxcore:  0.2.10
Qt:  5.12.4
Hardware:  Desktop

Reproducible: Always

##### Steps to reproduce

1. Start qTox with default theme
2. Change theme to "dark"

##### Observed Behavior
Theme is half changed to dark, half kept with default theme, causing an ugly mix:
image

##### Expected Behavior
The entire application is updated to the new theme.

##### Additional Info
Restarting qTox with dark theme selected results in the entire application being correctly styled:
image

### PR DESCRIPTION
**Pull request by bodwok**
Partially fixes [5924](https://github.com/qTox/qTox/issues/5924)

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6079)

### CODE REVIEW

**Comment by TriKriSta** [comment]
it's dark for me
Screenshot_20200409_165156

**Review by TriKriSta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6079)* status: 0 of 1 LGTMs obtained

___
*[src/widget/genericchatroomwidget.cpp, line 142 at r1](https://reviewable.io/reviews/qtox/qtox/6079#-M4UEEAd6EmlTm8vobvQ:-M4UEEAd6EmlTm8vobvR:bgc7m4y) ([raw file](https://github.com/qtox/qtox/blob/d01fed92f08dfaf9ed8a54fdc275b51b22b56ba7/src/widget/genericchatroomwidget.cpp#L142)):*
> ```cpp
> void GenericChatroomWidget::changeStyle()
> {
>     QString wgtStyle = QString("GenericChatroomWidget {"
> ```

I think write style in code it is bad way, better it is write in css files.

**Comment by TriKriSta** [comment]
and updating style doesn't work for separate chat window

**Comment by bodwok** [comment]
> it's dark for me

It seems that when using widget palette, the text color was ignored and filled in with default white. 
Now the color is correctly set from the palette.ini file (groundBase="#201f1f"). It can be replaced with any other color

> I think write style in code it is bad way, better it is write in css files.

Later I will try fix it on css file

> and updating style doesn't work for separate chat window

It’s not clear why this is happening, another bug is most likely

**Comment by bodwok** [comment]
Аdditionally in the dark/genericChatRoomWidget/genericChatRoomWidget.css file the groundBase color was replaced with a lighter GroundExtra color:

`CroppingLabel#nameLabelObj {`
`    color: @groundBase; /* Base color */`
`}`

replaced with:

`CroppingLabel#nameLabelObj {`
`    color: @groundExtra; /* Base color */`
`}`

**Review by TriKriSta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6079)* status: 0 of 1 LGTMs obtained

___
*[res.qrc, line 184 at r2](https://reviewable.io/reviews/qtox/qtox/6079#-M4yVzVlEU182Ib-VKRu:-M4yVzVlEU182Ib-VKRv:b-7q3l31) ([raw file](https://github.com/qtox/qtox/blob/dd9e46def29c80b1825c9ff7ec8fa9010f48849d/res.qrc#L184)):*
> ```
>         <file>themes/default/genericChatRoomWidget/genericChatRoomWidget.css</file>
>         <file>themes/dark/genericChatRoomWidget/genericChatRoomWidget.css</file>
> ```
can you add these files in alphabet order?

**Comment by bodwok** [comment]
> can you add these files in alphabet order?

Done

**Comment by TriKriSta** [comment]
@bodwok maybe You need rewrite comments for last two commits, because travis doesn't like currents comments. (need use types, like feat, fix, refactor and etc, at the beginning of the comment)

**Comment by bodwok** [comment]
> maybe You need rewrite comments for last two commits, because travis doesn't like currents comments. (need use types, like feat, fix, refactor and etc, at the beginning of the comment)

Done

**Comment by TriKriSta** [comment]
:lgtm_strong:

**Review by TriKriSta — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6079#-:-M5HW04s9ZDUdetBGGpB:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
