### PR TITLE
fix(l10n): Correction of the translation into Russian

### PR DESCRIPTION
**Pull request by hkarel**
More natural translation

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4906)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4906#-:-L2_fJDSSkTHcJB6T3Pa:b-jbsf8z)*

**Comment by Diadlo** [comment]
Please, rebase on master

**Comment by hkarel** [comment]
For "Reorganization of the context menu for chat", I intended to make a separate pull request, but he got here ...

**Comment by hkarel** [comment]
Rebase to top of upstream

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 534 at r3](https://reviewable.io:443/reviews/qtox/qtox/4906#-L2pj6kPz4goz0LAAbd9:-L2pj6kQejFu6c-eT_zX:bb3j455) ([raw file](https://github.com/qtox/qtox/blob/8a0d9719644ad3865984b590176f43cb884bfd07/src/widget/form/genericchatform.cpp#L534)):*
> ```cpp
>                               QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
>     if (mboxResult == QMessageBox::No)
>         return;
> ```

coding style, missing brackets

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4906)*

**Comment by hkarel** [comment]
a) Indeed, this requirement is indicated in the code execution rules, therefore, I obeying
b) I consider that applying this rule to one line, to put it mildly, is excessive!
c) The code is full of such constructions - without braces! Really, they were all made before the coding rules were written?!

**Comment by sudden6** [comment]
b) we had a long discussion about the coding style and it was concluded that it's better this way, even if it's a bit more work.

c) Unfortunately the code base is much older than the coding style, so whenever a part with another style is changed, we update it to the new one :) Interestingly this works also quite well to guess how up to date a part of the code is :DD

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4906#-:-L2q-iJYe1KsH3lJEZuL:b-jbsf8z)*

**Comment by hkarel** [comment]
> b) we had a long discussion about the coding style and it was concluded that it's better this way, even if it's a bit more work.

I do not dispute the importance of a single style, but I also understand that a programmer can have his own preferences, trifles, which for a pedant can turn out to be critical. Therefore, in my working projects, I allow some freedom of style. But it so, lyrics...

By the way, if I have to write again a document on the coding style, then probably for the basis I'll take your document. Almost everything in him suits me :)

Now I have again revised the document on the coding style. The mention of brackets even for one line is only for the full IF condition
```
if (...) {
    // Single line control statements are still required to use braces.
} else {
    // Multiline block
    // Multiline block
}
```
But nothing is said about brackets for the short IF condition without the ELSE. So either immediately add it's to the coding style, or I roll back the change ;)

**Comment by Diadlo** [comment]
@hkarel 
> By the way, if I have to write again a document on the coding style, then probably for the basis I'll take your document. Almost everything in him suits me :)

Very nice to hear such comment 

----
> But nothing is said about brackets for the short IF

From coding style: https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks
> Braces should be added for all control structures, even those whose bodies only contain a single line.

**Comment by hkarel** [comment]
>From coding style: https://github.com/qTox/qTox/blob/master/doc/coding_standards.md#braces-and-line-breaks

>>    Braces should be added for all control structures, even those whose bodies only contain a single line.

Indeed, I was inattentive, sorry ...

**Pull request merged**
