### PR TITLE
[Refactor] Add message model

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4589)

### CODE REVIEW

**Comment by sudden6** [comment]
I've not done a complete review yet, but I see almost no comments. Please add documentation to the new models.

**Comment by Talkless** [comment]
Review status: 0 of 16 files reviewed at latest revision, 19 unresolved discussions.

---

*[src/chatlog/chatmessage.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1X5KSjrRoaKb69dFJ:-Kt1X5KSjrRoaKb69dFK:baf0ju7) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L37)):*
> ```cpp
> #include "src/model/group.h"
> #include "src/grouplist.h"
> #include "src/model/message/textmessage.h"
> ```

These new line could be sorted better.

---

*[src/chatlog/chatmessage.cpp, line 50 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1XU14gCMHCi_6bO_V:-Kt1XU14gCMHCi_6bO_W:bqowvof) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L50)):*
> ```cpp
> static QString getMsgAuthorDispName(const ToxPk& authorPk)
> {
>     const Core* core = Core::getInstance();
> ```

could be const Core* _const_ core.

---

*[src/chatlog/chatmessage.cpp, line 51 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1X_4ozMvIpoLuG28u:-Kt1X_4ozMvIpoLuG28v:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L51)):*
> ```cpp
> {
>     const Core* core = Core::getInstance();
>     bool isSelf = authorPk == core->getSelfId().getPublicKey();
> ```

const bool

---

*[src/chatlog/chatmessage.cpp, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1Xfk8vFNLhC9P_pgd:-Kt1Xfk9H_pzCFLsaWLm:bows5ku) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L57)):*
> ```cpp
>     }
> 
>     Friend* f = FriendList::findFriend(authorPk);
> ```

Maybe `const Friend*`? ` getDsiplayedName()` is const.
or maybe even:
`cosnt Friend* const f = ...`
as pointer itself never changes.

---

*[src/chatlog/chatmessage.cpp, line 62 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1YZYhOy97UPTH5F2K:-Kt1YZYhOy97UPTH5F2L:b-ondtbe) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L62)):*
> ```cpp
>     }
> 
>     for (Group* it : GroupList::getAllGroups()) {
> ```

`const Group`, as `resolveToxId()` called later is const.

---

*[src/chatlog/chatmessage.cpp, line 89 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1_il988ZvdSQPnsGF:-Kt1_ilAsj7F1xWtzSmg:b-rvb4cu) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L89)):*
> ```cpp
> 
>     // has to match the color in innerStyle.css (div.action)
>     const QColor actionColor{"#1818FF"};
> ```

Why not QString ovarload, and with QStringLiteral()? const char* should be more pricey.

---

*[src/model/message/message.h, line 31 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1aJ_5ix-5ry3RL4ke:-Kt1aJ_5ix-5ry3RL4kf:b-21xi24) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/message.h#L31)):*
> ```objc
> public:
>     Message(const QDateTime& time);
>     virtual ~Message() = 0;
> ```

QObject has already declared vitual destructor, I would suggest not to clutter child class methods again with "virtual".

Also, why = 0 if there is destructor in message.cpp defined?

I would suggest to remove destructor at all, default one will do it's job it this case.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)

---

*[src/model/message/textmessage.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1coalhIrpVTvMKKoA:-Kt1coalhIrpVTvMKKoB:b-5ohk0q) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.cpp#L9)):*
> ```cpp
>     , id{id}
> {
>     _isAction = text.startsWith(ACTION_PREFIX);
> ```

I believe this could be moved up into initializer list.

---

*[src/model/message/textmessage.cpp, line 44 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1eSg3UlHLA1Ew_xfz:-Kt1eSg3UlHLA1Ew_xg-:bjuu4j2) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.cpp#L44)):*
> ```cpp
> void TextMessage::setText(const QString& text)
> {
>     this->text = text;
> ```

Maye  this simple one-liner (and others below)  could be defined inline inside .h (except makeActionText that needs static constant visible in .cpp) ?

---

*[src/model/message/textmessage.h, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1cBUD0p0sZlXbcrcZ:-Kt1cBUD0p0sZlXbcrc_:b-9klv0v) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L37)):*
> ```objc
>     TextMessage(const TextMessage& message);
>     TextMessage& operator=(const TextMessage& message);
>     ~TextMessage() override;
> ```

No need for empty destructor, I suggest to remove it.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)

---

*[src/model/message/textmessage.h, line 50 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1nSQH5YToUvkS1Xtx:-Kt1nSQI0qSCGt4X-UCh:b40okeb) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L50)):*
> ```objc
> private:
>     // TODO: Remove id (replace on pointer on message itself)
>     int id;
> ```

Also, to be pedantic, I would recommend to sort elements by it's size in descending order to win few bytes due to alignment:
QString, int, bool:
```
#include <QDebug>
#include <QString>

class Foo {
    int x;
    QString y;
    bool z;
};

class Bar {
    QString y;
    int x;
    bool z;
};

int main()
{
    qDebug() << sizeof(Foo) << sizeof(Bar);
}
```
```
24 16
```

---

*[src/model/message/textmessage.h, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1cWnsSc_IVg61nkOw:-Kt1cWnsSc_IVg61nkOx:bsjb82h) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L52)):*
> ```objc
>     int id;
>     QString text;
>     bool _isAction;
> ```

Why inconsistent underscore?

---

*[src/model/message/usermessage.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1f8OA7XtNcxVM0hct:-Kt1f8OA7XtNcxVM0hcu:b-9klv0v) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/usermessage.cpp#L9)):*
> ```cpp
> }
> 
> UserMessage::~UserMessage()
> ```

No need for empty destructor, I suggest to remove it.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)

---

*[src/model/message/usermessage.h, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1f6fWagnkdH0Ke4Ml:-Kt1f6fWagnkdH0Ke4Mm:b-9klv0v) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/usermessage.h#L32)):*
> ```objc
> public:
>     UserMessage(const ToxPk& author, const QDateTime& time);
>     virtual ~UserMessage() = 0;
> ```

No need for empty destructor, I suggest to remove it.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)

---

*[src/widget/form/chatform.cpp, line 736 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1gdtv-QnYjtUQjQmJ:-Kt1gdtv-QnYjtUQjQmK:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L736)):*
> ```cpp
>         // Show each messages
>         const ToxPk& authorPk = m.getAuthor();
>         bool isAction = m.isAction();
> ```

const bool

---

*[src/widget/form/chatform.cpp, line 745 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1gfxRFY1GJBU6cT9f:-Kt1gfxRFY1GJBU6cT9g:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L745)):*
> ```cpp
>         prevMsgDateTime = msgDateTime;
> 
>         bool isSent = msgDateTime != QDateTime();
> ```

const bool

---

*[src/widget/form/chatform.cpp, line 966 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1hmPCf_wBRVPGmhia:-Kt1hmPCf_wBRVPGmhib:buhw1i2) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L966)):*
> ```cpp
>         Core* core = Core::getInstance();
>         uint32_t friendId = f->getId();
>         ToxPk selfPk = Core::getInstance()->getSelfId().getPublicKey();
> ```

const ToxPk.

Also, `QStinng  selfPk` shadows this variable in inner scope some lines below.
Maybe worth renaming ToxPk or QString one?
[ES.12: Do not reuse names in nested scopes](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es12-do-not-reuse-names-in-nested-scopes)

---

*[src/widget/form/chatform.cpp, line 968 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1guBD2UbCa64seQmS:-Kt1guBD2UbCa64seQmT:bz82mnd) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L968)):*
> ```cpp
>         ToxPk selfPk = Core::getInstance()->getSelfId().getPublicKey();
>         TextMessage message { 0, selfPk, part, QDateTime() };
>         int rec = isAction ? core->sendAction(friendId, message.getText())
> ```

`const int`

---

*[src/widget/form/groupchatform.cpp, line 149 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1hLF87qJK0RMhOEFu:-Kt1hLF87qJK0RMhOEFv:btv8ie8) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/groupchatform.cpp#L149)):*
> ```cpp
>         }
>     } else {
>         ToxPk selfPk = Core::getInstance()->getSelfId().getPublicKey();
> ```

`const ToxPk`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4589)*

**Comment by Diadlo** [comment]
@sudden6 Docs added

---

Review status: 0 of 16 files reviewed at latest revision, 19 unresolved discussions.

---

*[src/chatlog/chatmessage.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1X5KSjrRoaKb69dFJ:-Kt6O2e9S9OYzsDCA5Ui:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L37)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

These new line could be sorted better.
</blockquote></details>

Done.

---

*[src/chatlog/chatmessage.cpp, line 50 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1XU14gCMHCi_6bO_V:-Kt6OCwf9BKJ5rzd_HZF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L50)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

could be const Core* _const_ core.
</blockquote></details>

Done.

---

*[src/chatlog/chatmessage.cpp, line 51 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1X_4ozMvIpoLuG28u:-Kt6OEbvza8Gdu9JsilF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L51)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const bool
</blockquote></details>

Done.

---

*[src/chatlog/chatmessage.cpp, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1Xfk8vFNLhC9P_pgd:-Kt6OJ6OWLMuntNX6bsx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L57)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Maybe `const Friend*`? ` getDsiplayedName()` is const.
or maybe even:
`cosnt Friend* const f = ...`
as pointer itself never changes.

</blockquote></details>

Done.

---

*[src/chatlog/chatmessage.cpp, line 62 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1YZYhOy97UPTH5F2K:-Kt6OIhUyhABL3zAPgl-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L62)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const Group`, as `resolveToxId()` called later is const.
</blockquote></details>

Done.

---

*[src/chatlog/chatmessage.cpp, line 89 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1_il988ZvdSQPnsGF:-Kt6OS5uxo3c2x-RC0Ak:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/chatlog/chatmessage.cpp#L89)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Why not QString ovarload, and with QStringLiteral()? const char* should be more pricey.
</blockquote></details>

Done.

---

*[src/model/message/message.h, line 31 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1aJ_5ix-5ry3RL4ke:-Kt6PINzFXoCvthw1ibT:bxrezrj) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/message.h#L31)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QObject has already declared vitual destructor, I would suggest not to clutter child class methods again with "virtual".

Also, why = 0 if there is destructor in message.cpp defined?

I would suggest to remove destructor at all, default one will do it's job it this case.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)
</blockquote></details>

If some of message model will need to custom dtor, it can't be called with `Message` pointer if `Message` will not have the virtual dtor. Let's hope, that we not forget to add it, if it will be requered later.
Done.

---

*[src/model/message/textmessage.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1coalhIrpVTvMKKoA:-Kt6R3-vWjZ5pLKNUuJX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.cpp#L9)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I believe this could be moved up into initializer list.
</blockquote></details>

Done.

---

*[src/model/message/textmessage.cpp, line 44 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1eSg3UlHLA1Ew_xfz:-Kt6SAVluwort-ofapAk:b-2zz2ui) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.cpp#L44)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Maye  this simple one-liner (and others below)  could be defined inline inside .h (except makeActionText that needs static constant visible in .cpp) ?
</blockquote></details>

I prefer to put most part of the code in `cpp`. I don't think, that it's have really performance decrease. Probably compile will optimize this piece of code

---

*[src/model/message/textmessage.h, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1cBUD0p0sZlXbcrcZ:-Kt6SDXZfvOCJnSLaQiH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L37)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

No need for empty destructor, I suggest to remove it.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)
</blockquote></details>

Done.

---

*[src/model/message/textmessage.h, line 50 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1nSQH5YToUvkS1Xtx:-Kt6SL5JmPCqR-GcANwe:brjs19b) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L50)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Also, to be pedantic, I would recommend to sort elements by it's size in descending order to win few bytes due to alignment:
QString, int, bool:
```
#include <QDebug>
#include <QString>

class Foo {
    int x;
    QString y;
    bool z;
};

class Bar {
    QString y;
    int x;
    bool z;
};

int main()
{
    qDebug() << sizeof(Foo) << sizeof(Bar);
}
```
```
24 16
```
</blockquote></details>

Never knew about it. Thanks. Done

---

*[src/model/message/textmessage.h, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1cWnsSc_IVg61nkOw:-Kt6SVux79CCeWtDQrpU:b-266wg2) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L52)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Why inconsistent underscore?
</blockquote></details>

Because the class already has `isAction` method. Replaced on `m` (member) prefix

---

*[src/model/message/usermessage.cpp, line 9 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1f8OA7XtNcxVM0hct:-Kt6SqdlPThCQwVnlN40:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/usermessage.cpp#L9)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

No need for empty destructor, I suggest to remove it.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)
</blockquote></details>

Done.

---

*[src/model/message/usermessage.h, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1f6fWagnkdH0Ke4Ml:-Kt6SrElCHHHMqTJ-2QB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/usermessage.h#L32)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

No need for empty destructor, I suggest to remove it.
[C.30: Define a destructor if a class needs an explicit action at object destruction](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c30-define-a-destructor-if-a-class-needs-an-explicit-action-at-object-destruction)
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 736 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1gdtv-QnYjtUQjQmJ:-Kt6TYw7ajNOtqIwcHg9:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L736)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const bool
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 745 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1gfxRFY1GJBU6cT9f:-Kt6TZLtUkPfXPCzUTZT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L745)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const bool
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 966 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1hmPCf_wBRVPGmhia:-Kt6VIiH_XQjyvU8ljgG:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L966)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const ToxPk.

Also, `QStinng  selfPk` shadows this variable in inner scope some lines below.
Maybe worth renaming ToxPk or QString one?
[ES.12: Do not reuse names in nested scopes](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es12-do-not-reuse-names-in-nested-scopes)
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 968 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1guBD2UbCa64seQmS:-Kt6VJGepey6tufVe_XR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/chatform.cpp#L968)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const int`
</blockquote></details>

Done.

---

*[src/widget/form/groupchatform.cpp, line 149 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1hLF87qJK0RMhOEFu:-Kt6VT2ceETzX5-6qVuR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/widget/form/groupchatform.cpp#L149)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const ToxPk`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4589#-:-Kt6NalaBXPQwzOQuEEm:b-fums39)*

**Comment by Talkless** [comment]
Review status: 0 of 16 files reviewed at latest revision, 18 unresolved discussions.

---

*[src/model/message/message.h, line 31 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1aJ_5ix-5ry3RL4ke:-Kt6rOWVODlT-nYltjVW:bamgdyk) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/message.h#L31)):*
It will be called, because QObject has virtual d-tor, or you are planning to remove QObject from hierarchy? Only one `virtual` is needed, in the base class (QObject in this case). 
[C.128: Virtual functions should specify exactly one of virtual, override, or final](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#c128-virtual-functions-should-specify-exactly-one-of-virtual-override-or-final)
> Use virtual only when declaring a *new* virtual function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4589)*

**Comment by Talkless** [comment]
Review status: 0 of 16 files reviewed at latest revision, 18 unresolved discussions.

---

*[src/model/message/textmessage.h, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt1cWnsSc_IVg61nkOw:-Kt6u7WOK_dYOxMKV5ZZ:b6hgqcd) ([raw file](https://github.com/qtox/qtox/blob/76a4ba70ef550fb463392113651e158da2a7d382/src/model/message/textmessage.h#L52)):*
> isAction
Oh right, a member function, I missed that.

Actually, for off-topic, I would suggest to use `m_` for *all* new code, as does Qt and KDE and boost. It avoids these kind of problems, and increases visibility/distinguishing local vs member variables, etc, etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4589)*

**Comment by noavarice** [comment]
Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 958 at r2](https://reviewable.io:443/reviews/qtox/qtox/4589#-Kt85cZnS__EJ9HFd5p4:-Kt85cZnS__EJ9HFd5p5:b-8i2qkc) ([raw file](https://github.com/qtox/qtox/blob/5b005425c31084d4457f57156ed19f5e03a6fa0e/src/widget/form/chatform.cpp#L958)):*
> ```cpp
>     }
> 
>     bool isAction = msg.startsWith(ACTION_PREFIX, Qt::CaseInsensitive);
> ```

Forgot to use `m.isAction()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4589)*

**Pull request closed without merging**
