### PR TITLE
[Refactor] Remove ChatForm from Group

### PR DESCRIPTION
**Pull request by Diadlo**
Based on #4942

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4943)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4943#-:-L4bj7uuk0M18QfhAP-G:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
Review status: 13 of 16 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/contentdialog.cpp, line 731 at r2](https://reviewable.io:443/reviews/qtox/qtox/4943#-L4mIgnxyC64ifdaMGeu:-L4mIgnxyC64ifdaMGev:b77umwz) ([raw file](https://github.com/qtox/qtox/blob/c52c103db19c474cf199f04f5cc52b80e4de5b1e/src/widget/contentdialog.cpp#L731)):*
> ```cpp
>         groupChatForms[groupId]->show(contentLayout);
>     }
> ```

like we talked about, it seems bad that groupChatForms and friendChatForms are both maps of the same types, and it seems best if groupChatForm and friendChatForm could both be used as generic contactChatForm (or something). This ins't a new change, so no change is needed for this PR.

---

*[src/widget/genericchatroomwidget.cpp, line 184 at r2](https://reviewable.io:443/reviews/qtox/qtox/4943#-L4lunpP69OmGFZenr98:-L4lunpP69OmGFZenr99:b48tc7b) ([raw file](https://github.com/qtox/qtox/blob/c52c103db19c474cf199f04f5cc52b80e4de5b1e/src/widget/genericchatroomwidget.cpp#L184)):*
> ```cpp
> void GenericChatroomWidget::activate()
> {
>     emit chatroomWidgetClicked(this);
> ```

I think it makes more sense for click to be only for actual user mouse clicks, and on click activate is emitted, then for things to connect to activate instead of chatroomWidgetClicked. Having software call activate, which then says the the chatroomWidget was clicked when it wasn't really seems backwards.

---

*[src/widget/widget.cpp, line 1145 at r2](https://reviewable.io:443/reviews/qtox/qtox/4943#-L4lrYiuWcLq1ZDphQhV:-L4lrYiuWcLq1ZDphQhW:b-8h8ey4) ([raw file](https://github.com/qtox/qtox/blob/c52c103db19c474cf199f04f5cc52b80e4de5b1e/src/widget/widget.cpp#L1145)):*
> widget->getGroup
this duplicates first line of else{} which also has `Group* g = widget->getGroup();`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4943)*

**Comment by anthonybilinski** [comment]
Reviewed 13 of 16 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4943)*

**Comment by Diadlo** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/widget/widget.cpp, line 1145 at r2](https://reviewable.io:443/reviews/qtox/qtox/4943#-L4lrYiuWcLq1ZDphQhV:-L4o-F2krWYS22YKzBJg:b-886gsx) ([raw file](https://github.com/qtox/qtox/blob/c52c103db19c474cf199f04f5cc52b80e4de5b1e/src/widget/widget.cpp#L1145)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

> widget->getGroup
this duplicates first line of else{} which also has `Group* g = widget->getGroup();`
</blockquote></details>

Fixed

---

*[src/widget/genericchatroomwidget.cpp, line 184 at r2](https://reviewable.io:443/reviews/qtox/qtox/4943#-L4lunpP69OmGFZenr98:-L4o-HLubMrDuo7oCI9y:b97h017) ([raw file](https://github.com/qtox/qtox/blob/c52c103db19c474cf199f04f5cc52b80e4de5b1e/src/widget/genericchatroomwidget.cpp#L184)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think it makes more sense for click to be only for actual user mouse clicks, and on click activate is emitted, then for things to connect to activate instead of chatroomWidgetClicked. Having software call activate, which then says the the chatroomWidget was clicked when it wasn't really seems backwards.
</blockquote></details>

Will fix in next PRs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4943)*

**Comment by anthonybilinski** [comment]
:lgtm_strong:

---

Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4943#-:-L4o40CCShpFAikdvI0G:b-jbsf8z)*

**Pull request merged**
