### PR TITLE
chore: add a TODO with removal date for deprecated historykeeper

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3665)

### CODE REVIEW

**Comment by Diadlo** [comment]
Why 2018?)
Reference https://github.com/qTox/qTox/issues/3654

**Comment by zetok** [comment]
Since version that deprecated it was released ~8 months ago, there should be sufficiently long period of time to allow users to migrate to new format, and 2 years since deprecation sounds right.

**Comment by Diadlo** [comment]
I think, we should write somewhere (CONTRIBUTING.md?) period of time to removing of deprecated code. 
For example: "deprecated code can be removed after 2 years, after moment, when it was marked deprecated"
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3665#-:-KQIR6fDrglaRjkRBopo:b7ujua7)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3665#-:-KQkdBCESv-O4TdBEVm-:bnfp4nl)_

**Pull request merged**
