### PR TITLE
fix(ui):Revised the context menu enabled/disabled behaviors

### PR DESCRIPTION
**Pull request by jakieoymj-github**
Fixed the issue #5223 and formatted a few codes.
#### BEFORE:
image
#### AFTER:
image
#### BEFORE:
image
#### AFTER:
image

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5247)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
I can't really say something about the CSS changes, maybe @tox-user can?

> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5247#-:-LHhaPrr08DbH7ZaqYDw:bapaoer)* status: 0 of 1 LGTMs obtained

___
*[src/widget/contentlayout.cpp, line 101 at r1](https://reviewable.io/reviews/qtox/qtox/5247#-LHh_Bzb-qFhAwIAeppf:-LHh_Bzb-qFhAwIAeppg:bcibz2u) ([raw file](https://github.com/qtox/qtox/blob/10e85043bf863574ef1db34b25e69d27e3940bcf/src/widget/contentlayout.cpp#L101)):*
> ```cpp
>     QPalette palette = mainHLine.palette();
>     palette.setBrush(QPalette::WindowText, QBrush(QColor(193, 193, 193)));
> //    palette.setBrush(QPalette::WindowText, QBrush(QColor(193, 193, 193))); // Why repeat two times?
> ```

please do not comment out code, just remove it.
___
*[ui/settings/mainContent.css, line 2 at r1](https://reviewable.io/reviews/qtox/qtox/5247#-LHh_SXzB8Yvp1n7CeLt:-LHh_SY-AGbJ5vZsRycp:b-a6ggj5) ([raw file](https://github.com/qtox/qtox/blob/10e85043bf863574ef1db34b25e69d27e3940bcf/ui/settings/mainContent.css#L2)):*
> ```CSS
> /* It makes the context menuitem text black allways
>  * Issue: https://github.com/qTox/qTox/issues/5223
> ```

Same, do not comment out, remove the lines instead and provide the comments in you PR or the commit message.
___
*[ui/settings/mainContent.css, line 82 at r1](https://reviewable.io/reviews/qtox/qtox/5247#-LHh_e7B5sKB6F-nffdO:-LHh_e7B5sKB6F-nffdP:bb73xfv) ([raw file](https://github.com/qtox/qtox/blob/10e85043bf863574ef1db34b25e69d27e3940bcf/ui/settings/mainContent.css#L82)):*
> ```CSS
> }
> 
> /* It makes top border of tabwidget pane intermittent
> ```

Same

**Comment by jakieoymj-github** [comment]
That's OK,I will in the future ;)

**Review by sudden6 — COMMENTED** [review]
please fix it in this Pull Request too and open another Pull Request for the other changes with the spelling mistake, it's not really related to the CSS fixes.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5247#-:-LHi_iX0CIXRkN8AgWTR:b7jq1ds)* status: 0 of 1 LGTMs obtained

**Comment by jakieoymj-github** [comment]
So sorry,it let me be confused too because I'm a github novice.Do I close this PR and re-PR?

**Comment by sudden6** [comment]
That would be one way, yes. But the more elegant way is to force push (`-f`) to the branch from where you opened the PR.

**Review by sudden6 — COMMENTED** [review]
:lgtm_strong: from my side, @tox-user can you take a look at the CSS?

> Reviewed 7 of 11 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5247#-:-LHlLuggCT_VMAXsj6bG:b-pkwbsz)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request closed without merging**
