### PR TITLE
Resize icons. Fixes #1204

### LINKED ISSUE #1204: New message circle is misaligned
When you have one or more unread messages from a contact, their status circle gets pushed slightly to the left due to the "new message" circle around it.
misalign

### PR DESCRIPTION
**Pull request by TheLastProject**
Tested by @urras.

### CODE REVIEW

**Comment by dubslow** [comment]
They're very low quality, some of the new ones

**Comment by TheLastProject** [comment]
They're exactly the same as the old ones. I only resized the canvas to 16px so that they take the same space on the UI.

**Comment by tux3** [comment]
@TheLastProject no, there seems to be a serious loss of quality. The colors are not quite the same, too.

See for example old and new for img/status/dot_groupchat_notification.png:

**Comment by TheLastProject** [comment]
Huh, weird... Seems Pinta isn't really trustworthy for this then :/ Anyway, making sure all images have the same canvas size will fix #1204.

**Comment by tux3** [comment]
Well, I can't merge this as is, please try with GIMP maybe ?

**Pull request closed without merging**
