### PR TITLE
Update fr.ts

### PR DESCRIPTION
**Pull request by aaannndddyyy**

### CODE REVIEW

**Comment by zetok** [comment]
cc: @pwnsdx , @tetraf , @TheNain38 ?

**Comment by TheNain38** [comment]
This is not `défault` but `défaut` in `Retour aux options par défault`.
Otherwise it is good.

**Comment by aaannndddyyy** [comment]
@TheNain38 Right. Thanks. This one was there already, but it escaped my attemtion, even though I changed another letter in that very word.
Fixed
I didn't check everything, just changed what stroke my eye

**Comment by aaannndddyyy** [comment]
this one is ready to be merged

**Pull request merged**
