### PR TITLE
Windows snorenotify dependency

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6212)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
I think this should be working on Windows and _almost_ working on macOS, with the caveat of the build failing on macOS for a confusing reason.. the error from travis is:
```
[ 48%] Building CXX object src/plugins/backends/osxnotificationcenter/CMakeFiles/libsnore_backend_osxnotificationcenter.dir/osxnotificationcenter.mm.o
/Users/travis/build/qTox/qTox/snorenotify/src/plugins/backends/osxnotificationcenter/osxnotificationcenter.mm:74:9: error: use of undeclared identifier 'not'
    if (not m_IdToNotification.contains(notificationId)) {
        ^
```
but the source is:
```
    if (!m_IdToNotification.contains(notificationId)) {
```
so it seems like somehow during build the `!` is getting converted to `not ` and then it's failing because that's undefined? o.O I don't see a mention of this on snore's mailing list or in general on the web, but our current build for snore is dead simple:
```
    git clone https://github.com/KDE/snorenotify "$SNORE_DIR"
    cd "$SNORE_DIR"
    git checkout tags/v0.7.0
    mkdir _build && cd _build
    export CMAKE_PREFIX_PATH=$(brew --prefix qt5)
    cmake -DCMAKE_INSTALL_PREFIX="$LIB_INSTALL_PREFIX" \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_daemon=OFF \
          -DBUILD_settings=OFF \
          -DBUILD_snoresend=OFF \
          ..
    make
```
so I'm not sure how we could be causing it.

**Comment by anthonybilinski** [comment]
Windows notifications now working after including the plugin and a snore exe needed by the plugin to our install :fireworks: 

Verbose version of the macOS build error:
```
[ 48%] Building CXX object src/plugins/backends/osxnotificationcenter/CMakeFiles/libsnore_backend_osxnotificationcenter.dir/osxnotificationcenter.mm.o

cd /Users/travis/build/qTox/qTox/snorenotify/_build/src/plugins/backends/osxnotificationcenter && /Applications/Xcode-9.4.1.app/Contents/Developer/usr/bin/g++ -DKF_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -DQT_GUI_LIB -DQT_MAC_USE_COCOA -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -D_DARWIN_C_SOURCE -D_LARGEFILE64_SOURCE -Dlibsnore_backend_osxnotificationcenter_EXPORTS -I/Users/travis/build/qTox/qTox/snorenotify/_build/src/plugins/backends/osxnotificationcenter -I/Users/travis/build/qTox/qTox/snorenotify/src/plugins/backends/osxnotificationcenter -I/Users/travis/build/qTox/qTox/snorenotify/_build/src/plugins/backends/osxnotificationcenter/libsnore_backend_osxnotificationcenter_autogen/include -I/Users/travis/build/qTox/qTox/snorenotify/src -I/Users/travis/build/qTox/qTox/snorenotify/_build/src -I/Users/travis/build/qTox/qTox/snorenotify/_build/src/libsnore -I/Users/travis/build/qTox/qTox/snorenotify/src/libsnore -iframework /usr/local/opt/qt/lib -isystem /usr/local/opt/qt/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt/./mkspecs/macx-clang -isystem /usr/local/opt/qt/lib/QtGui.framework/Headers -isystem /System/Library/Frameworks/OpenGL.framework/Headers -isystem /usr/local/opt/qt/lib/QtNetwork.framework/Headers -fno-operator-names -fno-exceptions -Wno-gnu-zero-variadic-macro-arguments -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -pedantic -Wzero-as-null-pointer-constant -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -std=gnu++11 -o CMakeFiles/libsnore_backend_osxnotificationcenter.dir/osxnotificationcenter.mm.o -c /Users/travis/build/qTox/qTox/snorenotify/src/plugins/backends/osxnotificationcenter/osxnotificationcenter.mm
/Users/travis/build/qTox/qTox/snorenotify/src/plugins/backends/osxnotificationcenter/osxnotificationcenter.mm:74:9: error: use of undeclared identifier 'not'
    if (not m_IdToNotification.contains(notificationId)) {
        ^
```

**Comment by anthonybilinski** [comment]
macOS build fixed, I was looking at tip locally vs v0.7.0 on the build error, so the code just is actually failing on v0.7.0 but not on tip. I've cherry-picked back the one compile fix commit onto the v0.7.0 release, and it's now building.

qTox is currently failing to find it on macOS though.

**Comment by anthonybilinski** [comment]
image
Working on macOS now :fireworks: 

Just need to clean up git history and test the mac dmg instead of just the local compile.

**Comment by anthonybilinski** [comment]
Neeevermind. A couple snorenotify issues that we worked around are still present on macOS.
1. We don't replace replace notifications with newer ones, which we should. So they just sequentially build up, but still include the text saying that there are multiple messages.
1. After we've displayed 4 notifications, we can't display another one for the length of the process. Even if the initial ones are cleared, no new ones are added.
Both of these problems are shown here: image

Both of those cases work well on Windows, like they do on Linux:
image

The behaviour is I think unusably bad on macOS since we don't even get ongoing new notifications per message like before. I don't think this should be integrated until we can either fix the issue or change the workaround  at least for macOS, maybe by just not attempting to replace messages here.

**Comment by anthonybilinski** [comment]
I've removed the macOS build, but kept the macOS support on my fork at https://github.com/anthonybilinski/qTox/tree/macos_snore. I've updated https://github.com/qTox/qTox/issues/6215 to point towards https://github.com/anthonybilinski/qTox/tree/macos_snore as well.

This PR now just includes Windows support, which works well. Hopefully this can be merged on its own and have the macOS part deferred until the notification issues are addressed.

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6212#-:-MF88c9BAOA0CLlQ8QVi:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
