### PR TITLE
Refactor/cleanup

### PR DESCRIPTION
**Pull request by Diadlo**
Old code is too strange sometimes. Please check logic carefully. Thanks

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4219)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 3 of 5 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeAOx1WoDP3gF3-FDU2:b7b0401) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
> ```cpp
>     index += forward ? 1 : -1;
>     // If goes out of the layout, then go to the next and skip empty
>     while (!(0 <= index && index < currentLayout->count())) {
> ```

yoda conditional and it has a logic change

---

*[src/widget/contentdialog.cpp, line 402 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAPHq7J0T2KsUigAzj:-KeAPHq8ApR-Omgc6t5w:b-frk5ak) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L402)):*
> ```cpp
>     updateStatus(friendId, friendList);
>     ContentDialog* contentDialog = getFriendDialog(friendId);
>     if (contentDialog != nullptr) {
> ```

nullptr checks are done different in the rest of this PR, any reason?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeATB89ivpe6DBx_eyS:b-sozck5) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

yoda conditional and it has a logic change
</blockquote></details>

Yoda condition is easy to read :P 
Becoust it says: 'Not in the interval'. 
Why it has a logic change? 
It's one of the place, where I'm not sure about correctness. But I don't see a mistake

---

*[src/widget/contentdialog.cpp, line 402 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAPHq7J0T2KsUigAzj:-KeAT7K7hHhc1RCgMbqN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L402)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

nullptr checks are done different in the rest of this PR, any reason?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeAW9CeOsdNamQStBj6:b-h7u77t) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Yoda condition is easy to read :P 
Becoust it says: 'Not in the interval'. 
Why it has a logic change? 
It's one of the place, where I'm not sure about correctness. But I don't see a mistake
</blockquote></details>

~yeah, I don't think so and also prefer formulating conditions in the positive way when possible (e.g. 'outside the interval')
the loop is ran at maximum one time, because after the `if` the index is guaranteed to be in range -> convert to `if`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeA_mtgozuz__MBLDXB:b5qr6b8) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

~yeah, I don't think so and also prefer formulating conditions in the positive way when possible (e.g. 'outside the interval')
the loop is ran at maximum one time, because after the `if` the index is guaranteed to be in range -> convert to `if`
</blockquote></details>

You are not right, because `currentLayout` will be changed => `currentLayout->count` will be changed too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeAv-petQSk76nhdLvl:bcdh5g8) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

You are not right, because `currentLayout` will be changed => `currentLayout->count` will be changed too
</blockquote></details>

yes, but then you clamp `index` to the `currentLayout->count() - 1` which makes the while loop stop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeCEnIPCmvbznnpebx8:bu26r2q) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

yes, but then you clamp `index` to the `currentLayout->count() - 1` which makes the while loop stop.
</blockquote></details>

Just take a look on old code
It will skip empty layours.
`not 0 <= index < 0` when count == 0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Reviewed 1 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-KeDW2FUIG2aMVUhk-MU:be76h7b) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Just take a look on old code
It will skip empty layours.
`not 0 <= index < 0` when count == 0
</blockquote></details>

ah, you're right, I assumed `count > 0`
maybe you can add some comments for future me to understand?

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-KeDXrz8jn1bqa-VnW-n:b-y68vh2) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
> ```cpp
> 
>     bool groupchatOnTop = Settings::getInstance().getGroupchatPosition();
>     int next = forward == groupchatOnTop ? index + 1 : index - 1;
> ```

can you explain why `groupchatOnTop` is compared to `forward` to determine the direction?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by noavarice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 316 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDZbaiVBPiebxxykBk:-KeDZbaiVBPiebxxykBl:b-5pjuby) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L316)):*
> ```cpp
> }
> 
> void ContentDialog::cycleContacts(bool forward, bool inverse)
> ```

Add docs for methods with changed signatures or which you've added

---

*[src/widget/contentdialog.cpp, line 760 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeD_YS6CuVN_wxa5uNU:-KeD_YS7J-DXLMF4jXSl:b-6pzpmi) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L760)):*
> ```cpp
>     }
> 
>     return std::get<0>(iter.value())->activeChatroomWidget == std::get<1>(iter.value());
> ```

Maybe join return statement with inversed previous condition? (on your decision)

---

*[src/widget/contentdialog.cpp, line 99 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDMTxLLeiiXloNSM3H:-KeDMTxLLeiiXloNSM3I:buivokf) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L99)):*
> ```cpp
>     boxLayout->addWidget(splitter);
> 
>     setMinimumSize(500, 220);
> ```

Please, add some constants for "magic" literals that are repeated multiple times, for more convenient editing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 1 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 316 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDZbaiVBPiebxxykBk:-Kehh1R76k_ANLT9m0zJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L316)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Add docs for methods with changed signatures or which you've added
</blockquote></details>

Done.

---

*[src/widget/contentdialog.cpp, line 343 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeAOx1WoDP3gF3-FDU1:-Kehh3ummoD495KdIhBL:b9ieoyb) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L343)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ah, you're right, I assumed `count > 0`
maybe you can add some comments for future me to understand?
</blockquote></details>

Comment added. "yoda conditional" removed

---

*[src/widget/contentdialog.cpp, line 760 at r1](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeD_YS6CuVN_wxa5uNU:-Kehht3pp8Gv6vsPlmbX:b-cr4s6j) ([raw file](https://github.com/qtox/qtox/blob/47163c5ac7c31436fb38bf89627a6a94d110179c/src/widget/contentdialog.cpp#L760)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Maybe join return statement with inversed previous condition? (on your decision)
</blockquote></details>

I want to leave validation of find result separated from function logic

---

*[src/widget/contentdialog.cpp, line 99 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDMTxLLeiiXloNSM3H:-Kehh0rXs4MdfQw3cE0D:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L99)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Please, add some constants for "magic" literals that are repeated multiple times, for more convenient editing
</blockquote></details>

Done.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-KehiBz9Mw_728YL7aIO:b7s3fui) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can you explain why `groupchatOnTop` is compared to `forward` to determine the direction?
</blockquote></details>

Comment added

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Reviewed 5 of 6 files at r3.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kei4L4GFzwfyweVajq8:bpjnkpa) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Comment added
</blockquote></details>

My suggestion to make it more clear what the code does:

* make `layouts` a `QList` with {online, group, offline}
* if `groupchatOnTop` call `layouts.swap(0, 1);`
* get `next` depending on `forward`
* handle overflow like it's done now

---

*[src/widget/contentdialog.cpp, line 899 at r3](https://reviewable.io:443/reviews/qtox/qtox/4219#-Kei3xoZvwQM67TceUwV:-Kei3xoZvwQM67TceUwW:b-a57fto) ([raw file](https://github.com/qtox/qtox/blob/a8fcb09f3a5535b002de21cff7258939d550c59f/src/widget/contentdialog.cpp#L899)):*
> ```cpp
> QLayout* ContentDialog::nextLayout(QLayout* layout, bool forward) const
> {
>     // If groupchar on top, order: group, online, offline
> ```

`groupchat`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf0aZ_bRjjXo3SKDAHI:b-sk95cv) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

My suggestion to make it more clear what the code does:

* make `layouts` a `QList` with {online, group, offline}
* if `groupchatOnTop` call `layouts.swap(0, 1);`
* get `next` depending on `forward`
* handle overflow like it's done now
</blockquote></details>

1. It will requered non-const vector
2. (1) => this vector will be inited for every method call

It think it's not optimal. Are you sure, that it's required? If so, I will rewrite it

Also, QVector doesn't provde `swap(int, int)` method. And here should be not swap: (1, 2, 3) -> (2, 3, 1)

---

*[src/widget/contentdialog.cpp, line 899 at r3](https://reviewable.io:443/reviews/qtox/qtox/4219#-Kei3xoZvwQM67TceUwV:-Kf0aWnPg4mMHcejaO0G:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/cb81490d920ac85b8cf44a7c796470c164c2063c/src/widget/contentdialog.cpp#L899)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`groupchat`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf0vDl2kEpLKq2oCYYz:be5g91o) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

1. It will requered non-const vector
2. (1) => this vector will be inited for every method call

It think it's very not optimal. Are you sure, that it's required? If so, I will rewrite it

Also, QVector doesn't provde `swap(int, int)` method. And here should be not swap: (1, 2, 3) -> (2, 3, 1)
</blockquote></details>

I agree it's probably slower, but does it have an impact? -> I don't think so

`QList` provides `swap(int, int)`.

If your comment at the top of the function is correct it would be from `(1,2,3)` to `(2,1,3)` which also would make more sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 899 at r3](https://reviewable.io:443/reviews/qtox/qtox/4219#-Kei3xoZvwQM67TceUwV:-Kf0w7FA6r8tom5mmM-U:bfiqlb6) ([raw file](https://github.com/qtox/qtox/blob/cb81490d920ac85b8cf44a7c796470c164c2063c/src/widget/contentdialog.cpp#L899)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by noavarice** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf1BKnvhjWbXntj7n7C:b-omqz35) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I agree it's probably slower, but does it have an impact? -> I don't think so

`QList` provides `swap(int, int)`.

If your comment at the top of the function is correct it would be from `(1,2,3)` to `(2,1,3)` which also would make more sense.
</blockquote></details>

In previous code layouts are strongly ordered and looped so using of division on QVector size is a very good solution, I guess. Method is supposed just to return next layout in this strong order so why do you want to use swap?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf1KY1hndnCb9ZFAWnA:brfd9f3) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

In previous code layouts are strongly ordered and looped so using of division on QVector size is a very good solution, I guess. Method is supposed just to return next layout in this strong order so why do you want to use swap?
</blockquote></details>

what do you mean by "strong order"?

I don't think the solution to do a modulo operation on the size is a bad thing, my comment is about the switching of the order depending on `groupChatOnTop`. I think it's more clear to handle the order independent of the direction we are going through the list.

I'll leave the decision to @Diadlo but if you stay with your solution, I recommend to modify the comment so that it mentions that the list with `groupChatOnTop == True` is the same as the normal list, just iterated in the reverse order. It makes understanding the code and the rest of the comment much easier.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf1RJZ4Dwdvyzw59nhL:bphf8lj) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

what do you mean by "strong order"?

I don't think the solution to do a modulo operation on the size is a bad thing, my comment is about the switching of the order depending on `groupChatOnTop`. I think it's more clear to handle the order independent of the direction we are going through the list.

I'll leave the decision to @Diadlo but if you stay with your solution, I recommend to modify the comment so that it mentions that the list with `groupChatOnTop == True` is the same as the normal list, just iterated in the reverse order. It makes understanding the code and the rest of the comment much easier.
</blockquote></details>

I plan to move this list/vector in to the class member and change order on settings change. Are you both ok with it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf1VlI8YpiFN3jDRtO8:bgvj44j) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I plan to move this list/vector in to the class member and change order on settings change. Are you both ok with it?
</blockquote></details>

+1 even better than my idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by noavarice** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf1jfwQHkomw1LShaOd:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

+1 even better than my idea.
</blockquote></details>

ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by Diadlo** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/widget/contentdialog.cpp, line 787 at r2](https://reviewable.io:443/reviews/qtox/qtox/4219#-KeDXrz7dNz70QJaaSme:-Kf30L0vnvHLp9s3x8nQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61a04147d5db8a8d8aec9fc0f88f7f58b259b693/src/widget/contentdialog.cpp#L787)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---

*[src/widget/contentdialog.cpp, line 899 at r3](https://reviewable.io:443/reviews/qtox/qtox/4219#-Kei3xoZvwQM67TceUwV:-Kf30Gs55WSptsDpr_Dp:bsj88t8) ([raw file](https://github.com/qtox/qtox/blob/cb81490d920ac85b8cf44a7c796470c164c2063c/src/widget/contentdialog.cpp#L899)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Not fixed
</blockquote></details>

Forget to push. Now removed :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4219#-:-Kf31NlfLawCiJBOg_T3:b-jbsf8z)*

**Comment by Diadlo** [comment]
@zetok Can you test it?

**Comment by zetok** [comment]
on abc91fd49ee2137106ced99cf4b570d2cb4d9dd0:

- [ ] friendlist size got maximized after I've clicked on a contact, no idea why (long status message?)

**Comment by zetok** [comment]
on abc91fd49ee2137106ced99cf4b570d2cb4d9dd0:

- [ ] when clicked on `multiple windows mode` in settings: 
spectacle dj2746

**Comment by Diadlo** [comment]
What is wrong on last screen?

**Comment by zetok** [comment]
Windows got resized, and settings window was moved, that shouldn't have happened.

**Comment by Diadlo** [comment]
This PR splitted on 2:
#4252 and #4251

**Pull request closed without merging**
