### PR TITLE
Edit colors in transfer widget for dark style (#5580)

### PR DESCRIPTION
**Pull request by TriKriSta**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)
Screenshot_20190323_143914

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5584)

### CODE REVIEW

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5584#-:-LalgN2555_0tS4WWnbb:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
FWIW @TriKriSta, my pause/play buttons are grey when in the paused state (like they were before) but are green in your screenshot. Is that a problem?

**Comment by TriKriSta** [comment]
@anthonybilinski, these buttons will turn gray after pressing the pause, probably it was so before, I didn't pay attention

**Comment by anthonybilinski** [comment]
Oh you're right, my mistake. Looks good.

**Pull request merged**
