### PR TITLE
Cleanup core

### PR DESCRIPTION
**Pull request by sudden6**
NOTE: there's some macOS specific code still in Nexus, that needs testing.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4899)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 12 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/main.cpp, line 332 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b6TpUEgCzsLl3_2jZ:-L2b6TpVdSXlJGbX81x5:b-t53iw3) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L332)):*
> ```cpp
>     if (autoLogin && Profile::exists(profileName) &&
>         !Profile::isEncrypted(profileName)) {
>             profile = Profile::loadProfile(profileName);
> ```

Seems, problem with indent

---

*[src/main.cpp, line 335 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b7nTVUZ6HYBj9TS_e:-L2b7nTVUZ6HYBj9TS_f:b-e4etrj) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L335)):*
> ```cpp
>     } else {
>         LoginScreen* loginScreen = new LoginScreen();
>         retCode = loginScreen->exec();
> ```

Seems, `retCode` changed only here. Maybe move declaration + result check + return here?

---

*[src/main.cpp, line 341 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b7NLx3fy6BL4DmDnG:-L2b7NLx3fy6BL4DmDnH:biyh71h) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L341)):*
> ```cpp
>     }
> 
>     if(profile) {
> ```

Add space after `if`

---

*[src/main.cpp, line 346 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b7W6pe19ZONYrFeBG:-L2b7W6pe19ZONYrFeBH:b-48ycih) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L346)):*
> ```cpp
>     } else {
>         // TODO: detect errors with autologin
>         if(retCode == 0) {
> ```

Space after `if`. Not sure, that `profile == nullptr && retCode == 0` is possible, but if you write this part, not sure, that is success

---

*[src/nexus.cpp, line 165 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b8rmvr_eUfqDrlhq_:-L2b8rmvr_eUfqDrlhqa:b-80x5a7) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/nexus.cpp#L165)):*
> ```cpp
>     delete loginScreen;
> 
>     if(profile) {
> ```

Space

---

*[src/nexus.cpp, line 330 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b9XbCLMTu_qOZ7MNU:-L2b9XbCLMTu_qOZ7MNV:b-arxsc) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/nexus.cpp#L330)):*
> ```cpp
> }
> 
> void Nexus::onLastWindowClosed()
> ```

Do nothing. Maybe remove?

---

*[src/core/core.cpp, line 269 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2bBMCql6uonXiaVZvW:-L2bBMCql6uonXiaVZvX:b-efgx2j) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/core/core.cpp#L269)):*
> ```cpp
>     if (!av->getToxAv()) {
>         qCritical() << "Toxav failed to start";
>         emit failedToStart();
> ```

+ `return`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4899)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/widget/loginscreen.h, line 42 at r2](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2joYuQ2LIFJfMeFrfk:-L2joYuRI2D5pAzS3a-z:bkipila) ([raw file](https://github.com/qtox/qtox/blob/e00bf4da99d19dcc6eb14d6d51f22ca362a76c56/src/widget/loginscreen.h#L42)):*
> ```objc
>     ~LoginScreen();
>     void reset();
>     Profile* getProfile();
> ```

getProfile() const; ?

---

*[src/widget/loginscreen.h, line 74 at r2](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2jpAVR4YP38FgIldTR:-L2jpAVR4YP38FgIldTS:bsosjxt) ([raw file](https://github.com/qtox/qtox/blob/e00bf4da99d19dcc6eb14d6d51f22ca362a76c56/src/widget/loginscreen.h#L74)):*
> ```objc
>     Ui::LoginScreen* ui;
>     QShortcut quitShortcut;
>     Profile* profile;
> ```

`profile` is not initialized in constructor?
Consider `Profile* profile{nullptr}`.

---

*[src/widget/widget.cpp, line 966 at r2](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2jofHBlu_C9WZ_PxQZ:-L2jofHBlu_C9WZ_PxQ_:b-maqq97) ([raw file](https://github.com/qtox/qtox/blob/e00bf4da99d19dcc6eb14d6d51f22ca362a76c56/src/widget/widget.cpp#L966)):*
> ```cpp
> void Widget::onRejectCall(uint32_t friendId)
> {
>     CoreAV* av = Core::getInstance()->getAv();
> ```

Could be CoreAV* **const** av

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4899)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/main.cpp, line 332 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b6TpUEgCzsLl3_2jZ:-L3wrXFl1DLT3bC9dSDk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L332)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems, problem with indent
</blockquote></details>

Done.

---

*[src/main.cpp, line 335 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b7nTVUZ6HYBj9TS_e:-L3ws8Fpsw6iqPWBXxwi:byrq2m7) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L335)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems, `retCode` changed only here. Maybe move declaration + result check + return here?
</blockquote></details>

see below

---

*[src/main.cpp, line 341 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b7NLx3fy6BL4DmDnG:-L3wuBtnbAc_4vxMZaLk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L341)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add space after `if`
</blockquote></details>

Done.

---

*[src/main.cpp, line 346 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b7W6pe19ZONYrFeBG:-L3wv20RpcEwdq-sr1LM:b-dsbdjz) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/main.cpp#L346)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Space after `if`. Not sure, that `profile == nullptr && retCode == 0` is possible, but if you write this part, not sure, that is success
</blockquote></details>

Right, removed that part

---

*[src/nexus.cpp, line 165 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b8rmvr_eUfqDrlhq_:-L3wvJsQAFx1HauyIZ8i:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/nexus.cpp#L165)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Space
</blockquote></details>

Done.

---

*[src/nexus.cpp, line 330 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2b9XbCLMTu_qOZ7MNU:-L3wvRPGawVhRRu4-s0e:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/nexus.cpp#L330)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Do nothing. Maybe remove?
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 269 at r1](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2bBMCql6uonXiaVZvW:-L3wqZFrb7FXo11w4Ypa:bb6un1j) ([raw file](https://github.com/qtox/qtox/blob/bae16e53a20903853efe8e9c01cb498466623f1f/src/core/core.cpp#L269)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

+ `return`?
</blockquote></details>

Done

---

*[src/widget/loginscreen.h, line 42 at r2](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2joYuQ2LIFJfMeFrfk:-L3wva328yayhgulPRQg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e00bf4da99d19dcc6eb14d6d51f22ca362a76c56/src/widget/loginscreen.h#L42)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

getProfile() const; ?
</blockquote></details>

Done.

---

*[src/widget/loginscreen.h, line 74 at r2](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2jpAVR4YP38FgIldTR:-L3wvzzpyHr6WTl6D9t4:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e00bf4da99d19dcc6eb14d6d51f22ca362a76c56/src/widget/loginscreen.h#L74)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`profile` is not initialized in constructor?
Consider `Profile* profile{nullptr}`.
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 966 at r2](https://reviewable.io:443/reviews/qtox/qtox/4899#-L2jofHBlu_C9WZ_PxQZ:-L3wvtV_QzUpawIViJXA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e00bf4da99d19dcc6eb14d6d51f22ca362a76c56/src/widget/widget.cpp#L966)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Could be CoreAV* **const** av
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4899)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/main.cpp, line 338 at r3](https://reviewable.io:443/reviews/qtox/qtox/4899#-L4HscaT0xGQeBOEKH2y:-L4HscaT0xGQeBOEKH2z:b-qvv8im) ([raw file](https://github.com/qtox/qtox/blob/a242dc3d19aea475e0038e651fd275415fc83e01/src/main.cpp#L338)):*
> ```cpp
>     }
> 
>     if (profile) {
> ```

Early break?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4899#-:-L4HudFLJ0ifz_pGpXLJ:b-jbsf8z)*

**Pull request merged**
