### PR TITLE
fix write to DB

### LINKED ISSUE #2292: [Regression] qTox lost all my sent messages from few last days
qTox 1673b43e26c853f6446f228fec083af166cbf446 , has happened also on some earlier version.

I don't have any of my sent sent messages in my history after restarting qTox (all received messages are still shown), for past 8 days.

Seems like a recent regression, I'll try to track it down later with bisect.

### PR DESCRIPTION
**Pull request by PKEv**
fix #2292, please test i don't sure

### CODE REVIEW

**Comment by tux3** [comment]
<strike>I'm pretty sure this won't fix the problem. A null byte encoded as UTF8 will still be a null byte...</strike>

So, this has the effect of truncating the message/alias at the first null byte.

**Comment by zetok** [comment]
It improves it a bit - messages are partially saved - if they contain null char, everything after it is truncated.

**Comment by tux3** [comment]
@PKEv Do you know if we can change the column type from TEXT to BLOB?

**Comment by PKEv** [comment]
And there is a real need to support the recording null-char, all messengers support it?
Otherwise probably no other way - just go to BLOB

**Comment by PKEv** [comment]
I think this is to merge the code to improve stability

**Comment by agilob** [comment]
@zetok this is about your issue and you know best how to reproduce it. Please merge if that improves situation.

**Comment by zetok** [comment]
@agilob it improves situation - thus I'm going to merge it.

Also, I'm going to open a new issue, since when message contains NULL, part after NULL doesn't get saved.

**Comment by agilob** [comment]
How about now after e107de1 got merged?

**Pull request merged**
