### PR TITLE
feat: bump font size from undersized

### LINKED ISSUE #2280: Default font is too small
It's just too small for no reason. I can't read any name in my contacts list.

### PR DESCRIPTION
**Pull request by zetok**
Fix #2280.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3806)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3806)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3806#-:-KU2zTALqrZb8GfRPVsx:bnfp4nl)_

**Comment by Diadlo** [comment]
Oh... Why I was not present, when it was merged. It make UI ugly :/

**Comment by zetok** [comment]
Well, it does help people actually see the text. And PR has been open for 4 days before merge.

**Pull request merged**
