### PR TITLE
fix(build): Windows cross-compilation didn't see libfilterudio

### PR DESCRIPTION
**Pull request by nurupo**
Fixed a logic error, we want to add to `CMAKE_FIND_ROOT_PATH` all dependency libs, not only the ones that provide `pkgconfig` files. This prevented `libfilteraudio` being added to `CMAKE_FIND_ROOT_PATH`, as it doesn't provide pkg-config files.

This fix causes the Windows build to error though, because qTox's cmake does even try to look for library headers, so the compilation fails with `#include <filter_audio.h>` not being found. More in https://github.com/qTox/qTox/issues/4587.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4588)

### CODE REVIEW

**Comment by nurupo** [comment]
So this PR can be merged after someone fixes that header issue.

**Comment by Diadlo** [comment]
If I understand correct, it fixes #4587
If so, please, add "Fix #4587" to commit message

**Comment by nurupo** [comment]
No, it doesn't fix https://github.com/qTox/qTox/issues/4587. On the contrary, this PR has revealed an issue in cmake scripts described in https://github.com/qTox/qTox/issues/4587. I need someone to fix https://github.com/qTox/qTox/issues/4587 in order for this PR to work.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4588#-:-KuZS33xbaPhZJHQaleA:b-jbsf8z)*

**Pull request merged**
