### PR TITLE
docs(INSTALL.md): use `$USER` variable instead of dummy `user`

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3739)

### CODE REVIEW

**Comment by Diadlo** [comment]
Any reason of using user home directory? May be `/tmp` will be better?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3739#-:-KSKjQB2-isG8ZR5m5IU:b-uabyzq)_

**Comment by zetok** [comment]
> Any reason of using user home directory? May be /tmp will be better?

`$HOME` is used for persistent storage. Is there a reason why someone wouldn't want to persistently store things that make compiling qTox possible?

**Comment by zetok** [comment]
Oh, and I almost forgot – assuming that `$TMPDIR` has sufficiently large amount of free space and is mounted with executable permissions is **wrong**.

**Comment by antis81** [comment]
@Diadlo This section is about compiling (!) qTox, not about installing.

@zetok Putting the build instructions in the installing manual is misleading. What about placing the build instructions either in "CONTRIBUTING.md" or a new file (e.g. "BUILD.md")?

**Comment by zetok** [comment]
@antis81 sorry, I'm not sure what is misleading? Putting those instructions in the CONTRIBUTING.md would be way more misleading, as they have very little to do with contributing – i.e. there's plenty of things that one could help with in qTox that don't require compiling. INSTALL.md on the other hand is about ways of getting qTox, and compiling is one of ways in which one could get it.

Perhaps it could be split to BUILD.md, though this would IMO require good justification for "hiding away" those rather important instructions.

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3739#-:-KT3imrG-y6DyVRTF2Ee:bnfp4nl)_

**Pull request merged**
