### PR TITLE
chore(circleci): upgrade circleci config file

### PR DESCRIPTION
**Pull request by naxuroqa**
* Upgrade circleci config file to v2.0 format
* See https://circleci.com/docs/2.0/migration/

#### Note
* This probably still needs some more work
* See this as a WIP - As your project settings don't allow any modification to circleci, someone would have to help me out here

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5504)

### CODE REVIEW

**Comment by sudden6** [comment]
I enabled this setting, it seems you must push a new commit to re-trigger the build.

**Comment by naxuroqa** [comment]
Thanks. I still have to re-enable the cache, otherwise builds will take > forever.

**Comment by anthonybilinski** [comment]
@sudden6 could we switch back to 1.0 on master, and develop this on a separate branch so that we can still process PRs in the meantime? I don't seem to have permission to change qTox CircleCI setting:
>To view/edit this page, you must be an organization admin on your VCS-provider (e.g., GitHub).

**Comment by sudden6** [comment]
huh, I though you have permissions, will check.

**Comment by anthonybilinski** [comment]
Disregard, looks like no config was changed, Circle CI just took ended 1.0 builds completely. Good thing we have Travis still running. Developing this in the PR branch seems fine and we can merge directly to master when finished.

**Comment by sudden6** [comment]
I'll close this one as  #5548 finishes it up and is ready to review. Thanks!

**Comment by naxuroqa** [comment]
Thanks for finishing it :+1:

**Pull request closed without merging**
