### PR TITLE
fix(settings): Properly update taskbar on disconnect

### PR DESCRIPTION
**Pull request by AliceGrey**
Fixes: #3795

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3829)

### CODE REVIEW

**Comment by Diadlo** [comment]
@AliceGrey LGTM, but take a look on [my comment](https://github.com/qTox/qTox/issues/3795#issuecomment-255946921) and maybe better change `Core::setStatus`?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3829#-:-KUuT_IAdOtpYt5JdtsS:b-l6byol)_

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3829#-:-KUuVo7nfV2f0REC-8r1:bnfp4nl)_

**Comment by AliceGrey** [comment]
@Diadlo I'll try it with your version and see if I can get it to work. It would probably be best to have core accept it as an option than hacking around it.

**Comment by AliceGrey** [comment]
@Diadlo So it looks like in core there is no TOX_USER_STATUS_OFFLINE so we'd have to change the case statement a bit to get it to work without being called uninitalized. https://github.com/irungentoo/toxcore/blob/master/toxcore/tox.h#L289

**Comment by AliceGrey** [comment]
@Diadlo Ok so it fixes the issue if you add `case Status::Offline: userstatus = TOX_USER_STATUS_NONE;break;` but that's technically incorrect because TOX_USER_STATUS_NONE is supoosed to signify "User is online and available" but it works. It looks like it might be an issue for the new toktok migration.

Edit: As Diadlo mentioned adding `emit statusSet(status);` to the `default`case would also work without having to incorrectly use toxcore.

**Comment by Diadlo** [comment]
I'm not sure, what will be better. Next two points leads to the problem.
1) toxcore doesn't consider `offline` as status. It's just disconnected user.
2) qTox -- consider `offline` as status.

If you whant to change the core, you can add `emit statusSet(status)` in `default` case
@sudden6 @initramfs What you think?

**Comment by initramfs** [comment]
Doesn't toxcore expose a `tox_friend_get_connection_status()` function? This returns an enum:

``` c
/**
 * Protocols that can be used to connect to the network or friends.
 */
typedef enum TOX_CONNECTION {

    /**
     * There is no connection. This instance, or the friend the state change is
     * about, is now offline.
     */
    TOX_CONNECTION_NONE,

    /**
     * A TCP connection has been established. For the own instance, this means it
     * is connected through a TCP relay, only. For a friend, this means that the
     * connection to that particular friend goes through a TCP relay.
     */
    TOX_CONNECTION_TCP,

    /**
     * A UDP connection has been established. For the own instance, this means it
     * is able to send UDP packets to DHT nodes, but may still be connected to
     * a TCP relay. For a friend, this means that the connection to that
     * particular friend was built using direct UDP packets.
     */
    TOX_CONNECTION_UDP,

} TOX_CONNECTION;
```

Can't friends appear to be offline if there is no connection? I feel like the purpose of `tox_friend_get_status()` is to get the state of the friend when there is an active connection, the results being invalid otherwise (since how would we know if a friend is away/busy/available if we have no connection to them.)

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3829#-:-KV-Re-Zx-GF0mW3JIHE:b-ekc0hr)_

**Comment by Diadlo** [comment]
@initramfs So, Are you agree, that the current implementation is right?

**Comment by initramfs** [comment]
@Diadlo Sorry I'm not sure what you mean. Do you the implementation provided by this PR or the existing implementation?

I just had a look at the whole status stuff in qTox and it's an absolute mess. I can't seem to keep track of what signals are connected to which slots and when, especially when you have the same named signals in different classes.

AFAIK, to toxcore "offline" is not a status, it is a state, completely different things. Try to merge the two into "statuses" in general will make it very hard to have it do the right thing without going through hoops of stuff. In this case the PR fixes the behaviour to be correct, but at the cost of emitting a signal from `Core` when it actually came from `Widget`. This solution is also brittle that if this `Widget` function is removed or refactored, you now have broken behaviour from `Core` again. It would also be hard to track down the fact that `Widget` was actually emitting signals `Core` should be.

Whilst this PR can serve as a hotfix, I'd prefer to have separate constructs for a user/friend's status and their connection type (None, TCP, UDP). It seems that `Core::onConnectionStatusChanged()` exists and essentially shoehorns connection type into status (done incorrectly too, forced a friend's status to be either `Online` or `Offline` rather than the spectrum of statuses). In short, any code that checks for the user's status or friend's status must consult both the connection type and the currently set status under the following pseudocode:

```
if(connection is TCP || UDP){
    // Update status as set by user status
}else{
    // Always show offline regardless of user status
}
```

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3829#-:-KV94QgRKtf6GcnNSjTT:bx8z9xj)_

**Comment by Diadlo** [comment]
Ok. It will merge it as hotfix today

**Pull request merged**
