### PR TITLE
Update French translation of "Logout" and "Exit"

### PR DESCRIPTION
**Pull request by TheNain38**

### CODE REVIEW

**Comment by zetok** [comment]
Could you use https://github.com/tux3/qTox/wiki/Translating#remove-obsolete-strings ?

**Comment by TheNain38** [comment]
Could you wait? I will squash the commits together

**Comment by TheNain38** [comment]
Done

**Comment by TheNain38** [comment]
Wait

**Comment by TheNain38** [comment]
@zetok Sorry, I can't squash right now, but in 2 hours and 20 minutes I will be able to.

**Comment by agilob** [comment]
`+8 −630` 

Did you commit everything?

**Comment by TheNain38** [comment]
@agilob Yes

**Comment by TheNain38** [comment]
Done you can merge now

**Pull request merged**
