### PR TITLE
Improve emoji support

### PR DESCRIPTION
**Pull request by sudden6**
- qTox allways compiles all smileys into the binary, this causes an unnecessary large binary and resource consumption during compilation see https://github.com/qTox/qTox/issues/3728 , removing some emoji could also speed up Travis builds
- while digging through the source code I noticed qTox already loads emoji from many paths, they are just undocumented or UNIX only, I choose to add one common path for Windows and Linux so even a qTox binary without any compiled in smileys can load them.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3737)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[doc/user_manual_en.md, line 12 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJ8Ynkav84EyCTADHp:-KSJ8Ynkav84EyCTADHq:bcoklrx) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L12)):_

> ``` Markdown
> * [Multi Window Mode](#multi-window-mode)
> * [Keyboard Shortcuts](#keyboard-shortcuts)
> * [Emoji Packs](#emoji-packs)
> ```

`s/emoji/Emoticons/` ?

---

_[doc/user_manual_en.md, line 365 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJ9AuVJLTp3YJatqQK:-KSJ9AuVJLTp3YJatqQL:b2bc6ta) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L365)):_

> ``` Markdown
> 
> qTox provides support for custom emoji packs. To install a new emoji pack
> put it in `%appdata%/roaming/tox/emoji` for Windows or `~/.config/tox/emoji`
> ```

`~/.config/` is not the place where emoticons should go.  [`XDG_DATA_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) can be used for it.

---

_[doc/user_manual_en.md, line 367 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJAENOG4U7O8gkyQBB:-KSJAENPog-jIipLSz6U:bkkmzs4) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L367)):_

> ``` Markdown
> put it in `%appdata%/roaming/tox/emoji` for Windows or `~/.config/tox/emoji`
> for Linux. The emoji files have to be in a subfolder also containing
> `emoticon.xml`, see the structure of https://github.com/qTox/qTox/tree/4ecbf616dcf2594cf0e65cedeb7ddc7281532c37/smileys
> ```

Can be formatted:

```
`emoticon.xml`, see the structure of
https://github.com/qTox/qTox/tree/4ecbf616dcf2594cf0e65cede/smileys for further
information.
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by Diadlo** [comment]
Maybe add `Fixed #3728` to first commit and `Fixed #3682` to second?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[src/persistence/smileypack.cpp, line 74 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSKb5gkzNHVepXrgTnP:-KSKb5gkzNHVepXrgTnQ:bl4l3y2) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/src/persistence/smileypack.cpp#L74)):_

> ``` cpp
> {
>     QStringList paths = QStringList(pathsParam);
>     paths << Settings::getInstance().getSettingsDirPath() + QDir::separator() + "emoji";
> ```

`getSettingsDirPath()` result already contains separator

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737#-:-KSKbStbXk50Xl9dRfn8:b-aq6ff0)_

**Comment by sudden6** [comment]
_[doc/user_manual_en.md, line 12 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJ8Ynkav84EyCTADHp:-KSQXDrYXjecwMH5pIL6:b-oqy77w) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L12)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `s/emoji/Emoticons/` ?
> </details>
> After reading https://www.theguardian.com/technology/2015/feb/06/difference-between-emoji-and-emoticons-explained I think what we do fits the word "emoji" more

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by sudden6** [comment]
Review status: 3 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

_[doc/user_manual_en.md, line 365 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJ9AuVJLTp3YJatqQK:-KSQd8PflmL6ZI4w1UjQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L365)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `~/.config/` is not the place where emoticons should go.  [`XDG_DATA_HOME`](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) can be used for it.
> </details>
> Done.

---

_[doc/user_manual_en.md, line 367 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJAENOG4U7O8gkyQBB:-KSQdBoF4cRfFG03ts71:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L367)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Can be formatted:
> 
> ```
> `emoticon.xml`, see the structure of
> https://github.com/qTox/qTox/tree/4ecbf616dcf2594cf0e65cede/smileys for further
> information.
> ```
> 
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 74 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSKb5gkzNHVepXrgTnP:-KSQdF2w97UWEqn-q6qu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/src/persistence/smileypack.cpp#L74)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> `getSettingsDirPath()` result already contains separator
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by zetok** [comment]
Review status: 3 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

_[doc/user_manual_en.md, line 12 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJ8Ynkav84EyCTADHp:-KSQde92AMNd1020FKDO:b-5slc4t) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L12)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> After reading https://www.theguardian.com/technology/2015/feb/06/difference-between-emoji-and-emoticons-explained I think what we do fits the word "emoji" more
> </details>
> Err, those all are emoticons.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by initramfs** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

_[doc/user_manual_en.md, line 12 at r1](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSJ8Ynkav84EyCTADHp:-KSQfOrUN0HffcguHWlz:b8ko25x) ([raw file](https://github.com/qtox/qtox/blob/1ba524e4d3763f84275ab066638c51c01824e877/doc/user_manual_en.md#L12)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Err, those all are emoticons.
> </details>
> Based on what I'm reading, I think he's right (emoji ≠ emoticon && emoji ⊄ emoticon).

---

_[doc/user_manual_en.md, line 365 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQgILNZEnDmzFzlBY1:-KSQgILNZEnDmzFzlBY2:b-bgo3ka) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/doc/user_manual_en.md#L365)):_

> ``` Markdown
> 
> qTox provides support for custom emoji packs. To install a new emoji pack
> put it in `%AppData%/Local/emoticons` for Windows or `~/.local/share/emoticons`
> ```

Does `%AppData%/Local/emoticons` or `~/.local/share/emoticons` exist by default? Because I don't have either on my Windows or Linux partition.  Perhaps add a line stating a folder may need to be created.

---

_[src/persistence/smileypack.cpp, line 57 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQiNbMhwMc3ulwP2dC:-KSQiNbMhwMc3ulwP2dD:b-rx0wlt) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L57)):_

> ``` cpp
>  * @brief directory containing the cfg and image files
>  *
>  * @var QStringList SmileyPack::defaultPaths
> ```

I know the existing file already has typenames attached to the variable name, but I suggest stripping them off.

E.g.:

``` c++
/**
 * @class SmileyPack
 * @brief Maps emoticons to smileys.
 *
 * @var SmileyPack::filenameTable
 * @brief Matches an emoticon to its corresponding smiley ie. ":)" -> "happy.png"
 *
 * @var SmileyPack::iconCache
 * @brief representation of a smiley ie. "happy.png" -> data
 *
 * @var SmileyPack::emoticons
 * @brief {{ ":)", ":-)" }, {":(", ...}, ... }
 *
 * @var SmileyPack::path
 * @brief directory containing the cfg and image files
 *
 * @var SmileyPack::defaultPaths
 * @brief Contains all directories where smileys could be found
 */
```

This is to prevent type signature changes from causing documentation to go out of date.

---

_[src/persistence/smileypack.cpp, line 83 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQi011QMLeTLCIpKfM:-KSQi012ix2TSVnjOokT:b-56kn4b) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L83)):_

> ``` cpp
>     QStringList paths = QStringList{":/smileys", "~/.kde4/share/emoticons", "~/.kde/share/emoticons"};
>     // qTox should find emoticons next to the binary
>     paths.append("." + QDir::separator() + EMOTICONS_SUB_DIR);
> ```

Change to:

``` c++
paths.append('.' + QDir::separator() + EMOTICONS_SUB_DIR);
```

to avoid a compiler error on ambiguous use of '+'

---

_[src/persistence/smileypack.cpp, line 108 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQiw9sfL54HOEcQ111:-KSQiw9sfL54HOEcQ112:bbph6rb) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L108)):_

> ``` cpp
> }
> 
> QList<QPair<QString, QString> > SmileyPack::listSmileyPacks()
> ```

Extra space after `<QString, QString>`, change line to:

``` c++
QList<QPair<QString, QString>> SmileyPack::listSmileyPacks()
```

---

_[src/persistence/smileypack.cpp, line 255 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQl00oCJPutSejyM51:-KSQl00oCJPutSejyM52:b-67o9gj) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L255)):_

> ``` cpp
> }
> 
> QString SmileyPack::getAsRichText(const QString &key)
> ```

Not related to the PR, but this can be fixed along with it. Reference operator is binded to the type, e.g:

``` c++
QString SmileyPack::getAsRichText(const QString& key)
```

---

_[src/persistence/smileypack.cpp, line 260 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQlD3pvUNNeRPNkYDx:-KSQlD3qJj04m6ag8L0g:b2nreh6) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L260)):_

> ``` cpp
> }
> 
> QIcon SmileyPack::getAsIcon(const QString &key)
> ```

Same as above.

---

_[src/persistence/smileypack.cpp, line 266 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQlFFlMi9baPpl8lHS:-KSQlFFlMi9baPpl8lHT:b2nreh6) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L266)):_

> ``` cpp
> }
> 
> void SmileyPack::cacheSmiley(const QString &name)
> ```

Same as above.

---

_[src/persistence/smileypack.cpp, line 275 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQlGaM5KDONIHgEFvM:-KSQlGaM5KDONIHgEFvN:b2nreh6) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L275)):_

> ``` cpp
> }
> 
> QIcon SmileyPack::getCachedSmiley(const QString &key)
> ```

Same as above.

---

_[src/persistence/smileypack.h, line 32 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQkIGpLL62lWToSAn3:-KSQkIGpLL62lWToSAn4:b6afxpr) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.h#L32)):_

> ``` objc
> class SmileyPack : public QObject
> {
>     Q_OBJECT
> ```

Perhaps a new line after `Q_OBJECT`? Not important though.

---

_[src/persistence/smileypack.h, line 35 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQjGAPHYj_KnHeq2Ki:-KSQjGAPHYj_KnHeq2Kj:b-eldnjb) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.h#L35)):_

> ``` objc
> public:
>     static SmileyPack& getInstance();
>     static QList<QPair<QString, QString> > listSmileyPacks(const QStringList& paths);
> ```

Same extra space issue as above.

---

_[src/persistence/smileypack.h, line 36 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQjE8fK3WN_a8YsuK6:-KSQjE8gu86E7K3CkRXS:b-eldnjb) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.h#L36)):_

> ``` objc
>     static SmileyPack& getInstance();
>     static QList<QPair<QString, QString> > listSmileyPacks(const QStringList& paths);
>     static QList<QPair<QString, QString> > listSmileyPacks();
> ```

Same extra space issue as above.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by sudden6** [comment]
Review status: 3 of 6 files reviewed at latest revision, 13 unresolved discussions.

---

_[doc/user_manual_en.md, line 365 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQgILNZEnDmzFzlBY1:-KSgwP8804NsWuRZJNdG:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/doc/user_manual_en.md#L365)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Does `%AppData%/Local/emoticons` or `~/.local/share/emoticons` exist by default? Because I don't have either on my Windows or Linux partition.  Perhaps add a line stating a folder may need to be created.
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 57 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQiNbMhwMc3ulwP2dC:-KSgwTLzMzqbIVqCFAbw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L57)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> I know the existing file already has typenames attached to the variable name, but I suggest stripping them off.
> 
> E.g.:
> 
> ``` c++
> /**
>  * @class SmileyPack
>  * @brief Maps emoticons to smileys.
>  *
>  * @var SmileyPack::filenameTable
>  * @brief Matches an emoticon to its corresponding smiley ie. ":)" -> "happy.png"
>  *
>  * @var SmileyPack::iconCache
>  * @brief representation of a smiley ie. "happy.png" -> data
>  *
>  * @var SmileyPack::emoticons
>  * @brief {{ ":)", ":-)" }, {":(", ...}, ... }
>  *
>  * @var SmileyPack::path
>  * @brief directory containing the cfg and image files
>  *
>  * @var SmileyPack::defaultPaths
>  * @brief Contains all directories where smileys could be found
>  */
> ```
> 
> This is to prevent type signature changes from causing documentation to go out of date.
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 83 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQi011QMLeTLCIpKfM:-KSgwRyTDYaMPI9yLeDL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L83)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Change to:
> 
> ``` c++
> paths.append('.' + QDir::separator() + EMOTICONS_SUB_DIR);
> ```
> 
> to avoid a compiler error on ambiguous use of '+'
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 108 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQiw9sfL54HOEcQ111:-KSgwU6ZanOppJi4oNqU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L108)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Extra space after `<QString, QString>`, change line to:
> 
> ``` c++
> QList<QPair<QString, QString>> SmileyPack::listSmileyPacks()
> ```
> 
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 255 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQl00oCJPutSejyM51:-KSgwUrLdXM1K9f4Hdf7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L255)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Not related to the PR, but this can be fixed along with it. Reference operator is binded to the type, e.g:
> 
> ``` c++
> QString SmileyPack::getAsRichText(const QString& key)
> ```
> 
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 260 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQlD3pvUNNeRPNkYDx:-KSgwVQAV-Pc3AGdQ4WR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L260)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Same as above.
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 266 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQlFFlMi9baPpl8lHS:-KSgwW2ltmkwNLvncnj3:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L266)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Same as above.
> </details>
> Done.

---

_[src/persistence/smileypack.cpp, line 275 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQlGaM5KDONIHgEFvM:-KSgwW_eaauzKyeyW7g3:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.cpp#L275)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Same as above.
> </details>
> Done.

---

_[src/persistence/smileypack.h, line 32 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQkIGpLL62lWToSAn3:-KSgwe10fTRZiFiTAC27:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.h#L32)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Perhaps a new line after `Q_OBJECT`? Not important though.
> </details>
> Done.

---

_[src/persistence/smileypack.h, line 35 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQjGAPHYj_KnHeq2Ki:-KSgwfOuKENc1NlB7Ek_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.h#L35)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Same extra space issue as above.
> </details>
> Done.

---

_[src/persistence/smileypack.h, line 36 at r2](https://reviewable.io:443/reviews/qtox/qtox/3737#-KSQjE8fK3WN_a8YsuK6:-KSgwg2uk5Rl8XriAjTI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e739cbb58e2c7ca278cbab4c608075e5a4f66e0d/src/persistence/smileypack.h#L36)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Same extra space issue as above.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by initramfs** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[doc/user_manual_en.md, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/3737#-KT10wEpcWTP3uldwYny:-KT10wEqwEE_aOCcJ7vi:b-83su7r) ([raw file](https://github.com/qtox/qtox/blob/fd6a54969caee8e82e3f37757ef4de37d93615cf/doc/user_manual_en.md#L369)):_

> ``` Markdown
> files have to be in a subfolder also containing `emoticon.xml`, see the
> structure of
> https://github.com/qTox/qTox/tree/4ecbf616dcf2594cf0e65cedeb7ddc7281532c37/smileys
> ```

Is the inclusion of a specific commit version required here as part of the URL? Shouldn't it be better to use a URL like:

```
https://github.com/qTox/qTox/tree/master/smileys
```

?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[doc/user_manual_en.md, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/3737#-KT10wEpcWTP3uldwYny:-KT11RAV9b8-tw2MAK-Y:b70l6kv) ([raw file](https://github.com/qtox/qtox/blob/fd6a54969caee8e82e3f37757ef4de37d93615cf/doc/user_manual_en.md#L369)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Is the inclusion of a specific commit version required here as part of the URL? Shouldn't it be better to use a URL like:
> 
> ```
> https://github.com/qTox/qTox/tree/master/smileys
> ```
> 
> ?
> </details>
> @zetok once suggested always referencing a commit name, because in the future directories could be moved, stuff renamed,...

This way, everything remains valid until the implementation changes, which should be documented anyhow.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by initramfs** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[doc/user_manual_en.md, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/3737#-KT10wEpcWTP3uldwYny:-KT12POz4sa7N4FnZxr5:b36o0ge) ([raw file](https://github.com/qtox/qtox/blob/fd6a54969caee8e82e3f37757ef4de37d93615cf/doc/user_manual_en.md#L369)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> @zetok once suggested always referencing a commit name, because in the future directories could be moved, stuff renamed,...
> 
> This way, everything remains valid until the implementation changes, which should be documented anyhow.
> </details>
> Well, it that case, perhaps change the reference to a tag? So it's immediately obvious which version was last referenced. E.g.

https://github.com/qTox/qTox/tree/v1.5.2/smileys

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by sudden6** [comment]
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

_[doc/user_manual_en.md, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/3737#-KT10wEpcWTP3uldwYny:-KT15A3f5k_GVtEBRrF6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/fd6a54969caee8e82e3f37757ef4de37d93615cf/doc/user_manual_en.md#L369)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Well, it that case, perhaps change the reference to a tag? So it's immediately obvious which version was last referenced. E.g.
> 
> https://github.com/qTox/qTox/tree/v1.5.2/smileys
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737)_

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737#-:-KT15s0CFrbDdNMAMlpM:bnfp4nl)_

**Comment by initramfs** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3737#-:-KT1892OdALv4qZ-wNAN:bnfp4nl)_

**Comment by shinodem** [comment]
add please facepalm emoji 🤦

**Pull request merged**
