### PR TITLE
fix(chattextedit): ChatTextEdit bug fix for issue #5020 Corrected

### PR DESCRIPTION
**Pull request by HoraceBianchon**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5027)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5027#-:-L88UvF62Lz3C4HjZI3X:b-jbsf8z)*

**Comment by sudden6** [comment]
@HoraceBianchon why did you merge `master` back into this branch?

**Comment by HoraceBianchon** [comment]
I just did fetch, pull from upstream.

**Comment by sudden6** [comment]
@HoraceBianchon this unnecessary in a PR branch. If there are merge conflicts, it's better to rebase ontop of upstream/master. I merged only the relevant commit now.

**Comment by HoraceBianchon** [comment]
Thanks.

**Pull request closed without merging**
