### PR TITLE
fix: returned remote links through plain ip address

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4446)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446#-:-KluHnAGlHQX2ZJrR6Cj:b-jbsf8z)*

**Comment by zetok** [comment]
Looks like PR introduces regression for `file://` URI scheme that limits it in qTox to IPv4?

According to [RFC 8089](https://tools.ietf.org/html/rfc8089#section-2) `host` part should match any valid domain name, and not just be limited to IPs.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/chatlog/textformatter.cpp, line 92 at r2](https://reviewable.io:443/reviews/qtox/qtox/4446#-KmC4W_kyJD_TrvnOq9P:-KmC4W_lOAEscvQejikS:b-mo88ss) ([raw file](https://github.com/qtox/qtox/blob/9787be6ad91da8d4cdee1845f0cdb5e0f2c76551/src/chatlog/textformatter.cpp#L92)):*
> ```cpp
>     {QRegularExpression(MULTILINE_CODE), htmlPatterns[CODE]}};
> 
> static const QString IP_PART = "(([01]?\\d{1,2})|(2(([0-4]\\d)|(5[0-5]))))";
> ```

perhaps `s/PART/OCTET` ?

`PART` doesn't really tell how big the part of the IP is, forcing one to parse the regexp.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446#-:-KmC53O1tmo6-Pa1Kob0:b-szv4zp)*

**Comment by sudden6** [comment]
:lgtm_cancel:

It would be nice to also support IPv6

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446#-:-KmJ00sh7wmB4-JgG4Zd:boscrm0)*

**Comment by sudden6** [comment]
@noavarice please leave a comment when you update a PR

:lgtm: 

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446#-:-KmkkUwcpdCLJXnpF52N:bpq1c7v)*

**Comment by noavarice** [comment]
Sorry, will make it further

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 98 at r3](https://reviewable.io:443/reviews/qtox/qtox/4446#-KmkvRJuGInbSjK3Z01h:-KmkvRJv9kB2u4IQwhiw:bj7acf2) ([raw file](https://github.com/qtox/qtox/blob/bcb4eaeeabde38bb1e3ec34ff4dcc452531ff16c/src/chatlog/textformatter.cpp#L98)):*
> ```cpp
> static const QString IPV6_PART = "([\\da-fA-F]{1,4})";
> static const QString IPV6_FULL = QString("(%1(:%1){7})").arg(IPV6_PART);
> static const QString MIXED_IPS = QString("(%1(:%1){5}:%2)").arg(IPV6_PART, IPV4);
> ```

If I'm reading regex right, it doesn't support `::1` and other shortenings of IPv6? (e.g. `0::1`, `000::1`, `0000::1`, `0000:0::1` and so on..)

Aside from that, shortening of IPv4 is also not supported (`127.1` and so on).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446)*

**Comment by noavarice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 98 at r3](https://reviewable.io:443/reviews/qtox/qtox/4446#-KmkvRJuGInbSjK3Z01h:-Kml1L_1YGiG4hKmmVFM:b96cp9n) ([raw file](https://github.com/qtox/qtox/blob/bcb4eaeeabde38bb1e3ec34ff4dcc452531ff16c/src/chatlog/textformatter.cpp#L98)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

If I'm reading regex right, it doesn't support `::1` and other shortenings of IPv6? (e.g. `0::1`, `000::1`, `0000::1`, `0000:0::1` and so on..)

Aside from that, shortening of IPv4 is also not supported (`127.1` and so on).
</blockquote></details>

You are right. It cannot be implemented with regex without auxiliary checks somewhere in the code so I leave it as you can see now. I think, such checks will increase code complexity without necessary reason. It does not mean that I do not want to implement this - just don't know how to make it obvious for everyone who will possibly inspect this code. So maybe there is a reason to handle URL's completely without using of regex?.. This question is for everyone, @diadlo and @sudden6 in particular too

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446)*

**Comment by Diadlo** [comment]
I thought about using [QLabel](https://doc.qt.io/qt-5/qlabel.html#openExternalLinks-prop). But IDK how escape urls for TextFormatter.
1. We can use something like `[^/]+` to a host part
2. Use github markdowm (\*italic\*, \*\*bold\*\*)
3. Require spaces around style-char

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/chatlog/textformatter.cpp, line 98 at r3](https://reviewable.io:443/reviews/qtox/qtox/4446#-KmkvRJuGInbSjK3Z01h:-KmlBXqQCZX7IzBG9cVK:bqi28w6) ([raw file](https://github.com/qtox/qtox/blob/bcb4eaeeabde38bb1e3ec34ff4dcc452531ff16c/src/chatlog/textformatter.cpp#L98)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

You are right. It cannot be implemented with regex without auxiliary checks somewhere in the code so I leave it as you can see now. I think, such checks will increase code complexity without necessary reason. It does not mean that I do not want to implement this - just don't know how make it obvious for everyone who will possibly inspect this code. So maybe there is a reason handle URL's completely without using of regex?.. This question is for everyone, @diadlo and @sudden6 in particular too
</blockquote></details>

I think that it should be done like it was done earlier, before the change: https://github.com/qTox/qTox/commit/3e2bfdd5482daaa21dfa54b0f78125359ca16bad#diff-1036f0c3cc8ef46aef91112d8c6d9d48L242

Although it's not limited to just valid URIs, it works for all valid URIs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4446)*

**Comment by sudden6** [comment]
any update on this?

**Comment by noavarice** [comment]
#4510

**Pull request closed without merging**
