### PR TITLE
fix(chatform): Update member info when group created

### PR DESCRIPTION
**Pull request by kitech**
this should be fix issue https://github.com/qTox/qTox/issues/4503

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4621)

### CODE REVIEW

**Comment by Diadlo** [comment]
@kitech Probably, this method should be called in Group constructor?

**Comment by kitech** [comment]
There are some other calls from widget.cpp, so I put here.
But not very sure.

**Comment by noavarice** [comment]
@Diadlo meant that, since you want to update member info at the moment
group created, it makes sense to do within group constructor

**Comment by kitech** [comment]
if this method called in Group constructor, how about the invited group?

**Comment by Diadlo** [comment]
Implemented in #4978

**Comment by anthonybilinski** [comment]
Closing since fix is merged.

**Pull request closed without merging**
