### PR TITLE
Reword login window: "Login" → "Load Profile"

### PR DESCRIPTION
**Pull request by zetok**
load profile

### CODE REVIEW

**Comment by ovalseven8** [comment]
'Login' is more userfriendly in my mind...

**Comment by zetok** [comment]
@ovalseven8 that depends - "load" implies that something happens locally (like loading save in a game), whereas "login" appears to be used with something in regard to some online service, where you don't have your data locally.

To quote what @LittleVulpix wrote about it in #1898:

> How about "load/use existing" or something that makes it clear the profile is actually on your device, not "somewhere" ? Too often I meet people who say "weird I logged in with the same user and pass but I don't see any of my contacts" when in reality they just created a new tox profile on a different device.

**Comment by TheNain38** [comment]
Yes, I think "load" is better for the same reason. This is also why they changed "Create Account" to "Create Profile".

**Comment by ovalseven8** [comment]
Of course, I can live with @zetok's changes as well. :)

**Comment by ProMcTagonist** [comment]
I like Load. The game save comparison is good.

**Comment by Zer0-One** [comment]
"load" is more appropriate here; was expecting someone to do this at some point. 

+1

**Pull request merged**
