### PR TITLE
Change license of classic smileys to CC BY-SA 4.0 (issue #4954)

### PR DESCRIPTION
**Pull request by krepa098**
The following changes the license of the "Classic" smileys from CC BY-NC to CC BY-SA. 

Notice: The license information is embedded in the EXIF data of the images.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4956)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Confirmed CC is updated to a "free" version as discussed in https://github.com/qTox/qTox/issues/4954:
```
qTox/smileys/Classic$ identify -verbose *.png | grep Copyright
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
    Copyright: CC BY-SA 4.0 https://creativecommons.org/licenses/by-sa/4.0/
```
unlike before (with NonCommercial version):
```
qTox/smileys/Classic$ identify -verbose *.png | grep Copyright
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
    Copyright: CC Attribution-NonCommercial http://creativecommons.org/licenses/by-nc/3.0/
```
@krepa098 It looks like your commit message was truncated, could you format it like this (ref https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit)
```
fix(smiley): change license of classic smileys to CC BY-SA 4.0

Fix #4954
```
Thanks :)

**Comment by nurupo** [comment]
Huh, I'd never think to look for image license in its metadata. Is there a license text file somewhere for smilies, or perhaps a paragraph on licenses of all different things contained in this repo in the top level Readme text file?

**Comment by anthonybilinski** [comment]
@nurupo emojione and Universe smiley packs have license files in their directories, Classic (this one) has metadata copyright info, and Basic smiley pack has no license file and no metadata license info. That's a full list in the project besides the GPLv3 license in the root.

There's no top-level list of licenses used in the project. This should be cleaned up and organized more consistently at some point

**Comment by eclipseo** [comment]
Thank you!

**Comment by krepa098** [comment]
Woops. All good now :)

**Comment by tox-user** [comment]
:lgtm_strong:

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4956#-:-L5Q65j4Tzm6oExwVGkN:b-jbsf8z)*

**Comment by tox-user** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4956)*

**Comment by anthonybilinski** [comment]
:lgtm_strong:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4956#-:-L5Q93qHw0nqzhwD0rhs:b-jbsf8z)*

**Pull request merged**
