### PR TITLE
fix(osx): OSX updater dependency moved.

### PR DESCRIPTION
**Pull request by iphydf**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6093)

### CODE REVIEW

**Comment by sudden6** [comment]
Is this updater even used? A search for `updater.go` in the repository turns up nothing indicating so.

**Comment by iphydf** [comment]
I'd still recommend fixing it before deletion, so that if someone wants to revive it, they are more likely to have a working version of it.

**Review by sudden6 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6093)* status: 0 of 1 LGTMs obtained

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: makes sense, can you then also submit a PR removing this?

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6093#-:-M5HwkC1CIqkWWD8lZNa:b-93f9xo)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
