### PR TITLE
test(FriendListManager): add contact management test

### PR DESCRIPTION
**Pull request by bodwok**
Checks the positions and visibility of contacts after the FriendListManager with a check list

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6437)

### CODE REVIEW

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437)* status: 0 of 1 LGTMs obtained

___
*[src/widget/groupwidget.h, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvUt3EVRZH5H_fX2o:-MvXvUt3EVRZH5H_fX2p:b-bgr5vn) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/src/widget/groupwidget.h#L50)):*
> ```objc
>     QString getNameItem() const final;
>     bool isOnline() const final;
>     bool widgetIsVisible() const;
> ```

lack of `override` or `final` here is causing a warning->error on the macOS CI build
___
*[test/model/friendlistmanager_test.cpp, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvno8-W88XqHdtA-_:-MvXvno8-W88XqHdtA-a:btjv1ek) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L29)):*
> ```cpp
> public:
>     MockFriend()
>         : name("No Name"),          
> ```

trailing whitespace
___
*[test/model/friendlistmanager_test.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvgRUBHWTlB8vPCSe:-MvXvgRV8iOMKEOmDCMz:b-gh8kse) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L73)):*
> ```cpp
>     QString getNameItem() const { return name; }
>     QDateTime getLastActivity() const { return QDateTime::currentDateTime(); }
>     QWidget* getWidget() { return nullptr; }
> ```

all mock overriding mock functions should be marked `override`
___
*[test/model/friendlistmanager_test.cpp, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvre1A3VV85m0Bqbg:-MvXvre1A3VV85m0Bqbh:b-rnynun) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L245)):*
> ```cpp
>         for (auto name : sortedByNameOnlineFriends) {
>             if (sortedByNameOfflineFriends.contains(name, Qt::CaseInsensitive)) {
>                 QWARN("Names in sortedByNameOnlineFriends and sortedByNameOfflineFriends "
> ```

`QWARN` -> `QVERIFY(!"string")`? that way it will fail the test and fail the CI job, while still outputting the warning string. I worry that just a warning log could go missed for a long time since people aren't usually checking CI logs of passed tests
___
*[test/model/friendlistmanager_test.cpp, line 350 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXwIsC0iz-AX9b7d3_:-MvXwIsD4HdKQraeu30l:bwttzrd) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L350)):*
> ```cpp
>             ->addOnlineFriends()->*/addGroups()->buildUnsorted();
>     auto sortedVec = listBuilder./*addOfflineFriends()
>             ->addOnlineFriends()->*/addGroups()->buildSortedByActivity();
> ```

are these `->addOfflineFriends()->addOnlineFriends()`meant to be commented? It seems like a bit of free additional coverage to include them?

**Review by anthonybilinski — APPROVED** [review]
I've pushed a new commit with all the changes I've suggested to your branch. If you agree with the changes, let me know and I can merge like this, you can also squash into your original commit if you want.

If there's something you disagree with feel free to just respond to the comments and updated your original commit with whatever you want ignoring my changes.

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437#-:-MvXyHaf5Z9XRcV_0-Yg:bpo03hd)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
Note that the failing `Build centos docker image` test will be fixed by https://github.com/qTox/qTox/pull/6445 so can be ignored.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437#-:-MvY6fy6-8Nh62Z7EyQL:b-geyg36)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437)* status: 0 of 1 LGTMs obtained

**Review by bodwok — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437)* status: 0 of 1 LGTMs obtained

___
*[src/widget/groupwidget.h, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvUt3EVRZH5H_fX2o:-MvweqQUDB21gRU_YWaN:beein5z) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/src/widget/groupwidget.h#L50)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

lack of `override` or `final` here is causing a warning->error on the macOS CI build
</blockquote></details>

Fixed in [Minor cleanup to contact management test](https://github.com/qTox/qTox/pull/6437/commits/e6dccc476551d15b98f3816f8ce97e8f19d61691)
___
*[test/model/friendlistmanager_test.cpp, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvno8-W88XqHdtA-_:-MvwWFw_7yqxYErpwctd:beein5z) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L29)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

trailing whitespace
</blockquote></details>

Fixed in [Minor cleanup to contact management test](https://github.com/qTox/qTox/pull/6437/commits/e6dccc476551d15b98f3816f8ce97e8f19d61691)
___
*[test/model/friendlistmanager_test.cpp, line 73 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvgRUBHWTlB8vPCSe:-Mvwf2xUBvBgTA8Uu7Oy:beein5z) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L73)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

all mock overriding mock functions should be marked `override`
</blockquote></details>

Fixed in [Minor cleanup to contact management test](https://github.com/qTox/qTox/pull/6437/commits/e6dccc476551d15b98f3816f8ce97e8f19d61691)
___
*[test/model/friendlistmanager_test.cpp, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvre1A3VV85m0Bqbg:-MvwWWGR5wQN_eyXGRLI:bzcuzxk) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L245)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

`QWARN` -> `QVERIFY(!"string")`? that way it will fail the test and fail the CI job, while still outputting the warning string. I worry that just a warning log could go missed for a long time since people aren't usually checking CI logs of passed tests
</blockquote></details>

Good point, failing the test with a description of the error will be more helpful. Looks like we can just use QFAIL("message") to exclude the implicit conversion warning
___
*[test/model/friendlistmanager_test.cpp, line 350 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXwIsC0iz-AX9b7d3_:-MvwecZ5B0qEjDhePg_s:b-osiyvb) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L350)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

are these `->addOfflineFriends()->addOnlineFriends()`meant to be commented? It seems like a bit of free additional coverage to include them?
</blockquote></details>

Checking with online and offline friends will be more complete. Forgot to remove the comments.

**Review by anthonybilinski — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437)* status: 0 of 1 LGTMs obtained

___
*[test/model/friendlistmanager_test.cpp, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/6437#-MvXvre1A3VV85m0Bqbg:-MvwqEOwBqw7bFCVd-qv:b-mcx505) ([raw file](https://github.com/qtox/qtox/blob/400849723d8d25c4b30bd6d862d9c9cfbc3942d9/test/model/friendlistmanager_test.cpp#L245)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

Good point, failing the test with a description of the error will be more helpful. Looks like we can just use QFAIL("message") to exclude the implicit conversion warning
</blockquote></details>

Agreed, `QFAIL` is better. Updated.

**Review by bodwok — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6437#-:-Mvxcmuh55AgqZlh3dpy:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
