### PR TITLE
chore(release): update flatpak and appimage links, update version script

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5271)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
links are still invalid because although we include arch suffix on 1.16.1, it's not included on the binaries on 1.16.3. Will look into it.

**Comment by sudden6** [comment]
@anthonybilinski any progress?

https://github.com/qTox/qTox/issues/5296 seems related to this.

**Comment by anthonybilinski** [comment]
1. Name was changed to append arch in 098482927, after v1.16.1.
2. v1.16.2 and v1.16.3 branched from master and were based on top of v1.16.1 (no name change in build)
3. [problem] 098482927 wasn't committed on or cherry-picked to v1.16.2 or v1.16.3 releases.
4. README.md was updated to include arch in fb6344aee on master.

Together `README.md` on our github landing page from master has links pointing to where the artefacts would be if they were built off master, instead of where they really are based on last release tag.

Possible solutions:
1) revert `README.md` changes to point to last releases artefacts (without suffix). This means the revert will need reverted on next release to re-point to the arch appended files.
2) manually rename the artefacts for the v1.16.3 release, keep `README.md` untouched, and the problem will solve itself next release since the build script will append arch.


solution 2) seems best to me, but has the downside of breaking permanent links to release artefacts.

This wouldn't actually require code changes, but I can make the manual change if approved as part of this PR.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: solution #2 sounds good to me too

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5271#-:-LLjxZMjEU0xxPdab-Yc:b-m2x33n)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
