### PR TITLE
Better right-alignment of timestamps in chatlog

### LINKED ISSUE #3957: [Regression] Timestamps appear in an unintended position.
Not to be confused with 'Timestamp misalignment #2579'.

##### Brief Description

OS: Gentoo Linux (~amd64)
qTox version: v1.6.0-62-g9acacbbf
Commit hash: fb96dd633e55db1f2e030826b939bce841b42af5
toxcore: 0_pre20160904
Qt: 5.8 (qtbase commit [50cb268](http://code.qt.io/cgit/qt/qtbase.git/commit/?id=50cb2687b2864acf66586fab9dd56716ebda4e9d))

Reproducible: Always

##### Steps to reproduce

1. Run qTox.
2. Open a chat.
3. Send some messages to a contact, or have past messages load in the chat window (the 'not sent' animation still appears at the correct spot).
4. Observe the position of the timestamps.

##### Observed Behavior

Timestamps are misplaced to the left from their intended position.

##### Expected Behavior

Timestamps appear at their intended position (closer to the right margin).

##### Additional Info

Running 'git bisect' leads me to suspect the commit c8512fa98461a54f3febc076fa1d7f99eae1d593 as being the culprit.

This is how it makes things look like:

chiitoo_too_ online _-_chiitoo_2016-12-08_23-57-59_379017181

This is how things look with it reverted (one might notice some other changes there as well, but it's the timestamps that we're focusing on here!):

chiitoo_ online _-_chiitoo_too_2016-12-08_23-58-02_046769933

### PR DESCRIPTION
**Pull request by ghost**
Make Text::idealSize() a virtual function and override it in the derived
class Timestamp. The idealSize() function for Timestamps now returns a
tighter size to enable better right-alignment of the timestamps in
chatlog.

Fixes #3957. Note that this change assumes that timestamps do not
contain RTL text.

Chatlog in a separate window **before**:
echotest-master

**after**
echotest-space

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5489)

### CODE REVIEW

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5489#-:-LVx4QtzDlLGrgIq_mjQ:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by sudden6 — CHANGES_REQUESTED** [review]
IIRC there can be RTL text in timestamps with custom date formats, but I think we can ignore that for now.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5489#-:-LVxPv263yO7e42SKfoy:blogxzb)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/chatlog/content/timestamp.cpp, line 35 at r1](https://reviewable.io/reviews/qtox/qtox/5489#-LVxPp2R5K3cpwnn6h-V:-LVxPp2R5K3cpwnn6h-W:bx631le) ([raw file](https://github.com/qtox/qtox/blob/4a89825d856ba7c713e30f849c7d559e364c0ae6/src/chatlog/content/timestamp.cpp#L35)):*
> ```cpp
> QSizeF Timestamp::idealSize()
> {
>     if (doc)
> ```

braces required by our coding style

**Comment by ghost** [comment]
Braces are now fixed.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5489#-:-LW--uuY4WnfPk-dDymq:b-jbsf8z)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
@tmxnst we had some CI failure that are now fixed on master. Could you rebase your PR onto `origin/master` then force push to your PR branch?

I noticed you PRed from `master`, normally you should create a branch for your PR in your repo, then PR from that branch, so that your `master` doesn't diverge from `origin/master`. If it was on a new branch, it also means I could push to your PR branch without risk of messing up your repo in case you've based work on your master.

**Comment by ghost** [comment]
I force-pushed a rebased version.

Don't worry about my master branch, I'll delete it when this PR is merged.

**Pull request merged**
