### PR TITLE
Fixes missing first video mode from video mode selection

### PR DESCRIPTION
**Pull request by initramfs**
The `selectBestModes()` function in `avform.cpp` strips off the first video mode (when the vector `newVideoModes` is empty). This PR resolves the issue by adding the first video mode to the list if the `newVideoModes` vector is empty.

This PR also resolves the issue where video modes aren't truthfully displayed to the user (instead they're rounded to the closest multiple of 120).

This PR fixes issue #3588.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3589)

### CODE REVIEW

**Comment by zetok** [comment]
There is still `360p` and `600p`, but now `720p` is at least back.

**Comment by zetok** [comment]
Btw, 

> This commit fixes issue #3588.

this isn't really needed, simple `Fixes #1234.` would do – https://help.github.com/articles/closing-issues-via-commit-messages/.

**Comment by initramfs** [comment]
@zetok Sorry I only just understood what you meant by that... I've pushed another commit to fix the issue you're experiencing. I've also fixed the first commit's message.

**Comment by initramfs** [comment]
Just as an FYI, as part of the `avform` code, the only "allowed" video resolutions are:

```
Width x Height
--------------
  160 x  120
  460 x  240
  640 x  360
  854 x  480
 1280 x  720
 1920 x 1080
```

Other resolutions are supported if they're within 300 pixels absolute different of any of the modes above. I recall that it's been this way for quite a while now (Git traces that exact list back to June 10th 2016). The code seems to be designed to auto pick resolutions that are closest to the ones on the whitelist. So given your video device reporting resolutions of `640x360` and `640x480`, the latter `640x480` will be eliminated from the list of resolutions presented to the user since `640x360` is an exact match to the whitelisted resolution. Though `640x480` will get matched again against `854x480`, another mechanism ensures that all given resolutions have their height field separated by 120 px, thus once again `640x480` is eliminated in favor of `960x544`.

If that behaviour is to be changed, well, that'll probably need to be in another issue since I don't fully understand the rationale behind the code (perhaps to enforce a certain aspect ratio?) and I don't want to undo other people's work without good reason. From blame it seems like the code was constructed by Diadlo and sudden6.

**Comment by zetok** [comment]
Thanks, that fixes it :)

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589#-:-KOVQNreZvEhtnoq_wg0:bnfp4nl)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/widget/form/settings/avform.cpp, line 284 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOVQxOw0_3VY2_kZfUC:-KOVQxOw0_3VY2_kZfUD:b105tbw) ([raw file](https://github.com/qtox/qtox/blob/a5a4216adfd32d8970fc28fbc99bf517d5af7a50/src/widget/form/settings/avform.cpp#L284)):_

> ``` cpp
> 
>         if (mode.height && mode.width)
>             str += QString("%1p").arg(mode.height);
> ```

wouldn't this cause non multiples of 120p to be displayed to the user? I think this will be confusing to the user.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by initramfs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[src/widget/form/settings/avform.cpp, line 284 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOVQxOw0_3VY2_kZfUC:-KOV_ircSKgNYOWlOlXK:bpei1s) ([raw file](https://github.com/qtox/qtox/blob/a5a4216adfd32d8970fc28fbc99bf517d5af7a50/src/widget/form/settings/avform.cpp#L284)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> wouldn't this cause non multiples of 120p to be displayed to the user? I think this will be confusing to the user.
> </details>
> Yes it would, but forcing it to be a multiple of 120p is deceitful. I wrote this fix primarily in response to @zetok's issues where he sees a non-existent 600p (his camera supports 960x544). I think users wouldn't care too much to see something like `544p`, instead the opposite hurts people that actually care about the video resolution (since it's basically a lie).

Personally, I'm against the whole "pre-defined" video resolutions list (there's just simply too much variety out there to force everyone to a 16:9 video mode) but it's not concerning enough for me to justify against it just yet.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589#-:-KOZnN4nJ_n9ZyRxA6G1:bnfp4nl)_

**Comment by initramfs** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[a discussion](https://reviewable.io:443/reviews/qtox/qtox/3589#-KO_ryGtfbytGnryrAgH:-KO_ryGtfbytGnryrAgI:b-ra0umc) (no related file):_
@zetok I've assigned you for a final check, feel free to merge if all is good.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 251 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaLt4OzYeutdNLiO7q:-KOaLt4PV1Q-ujC9yreP:b-l5dh7v) ([raw file](https://github.com/qtox/qtox/blob/a5a4216adfd32d8970fc28fbc99bf517d5af7a50/src/widget/form/settings/avform.cpp#L251)):_

> ``` cpp
>         VideoMode mode = allVideoModes[it->second];
> 
>         if(newVideoModes.empty())
> ```

There should be space between `if` and `(`

---

_[src/widget/form/settings/avform.cpp, line 261 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaLgYTBd7OI2pMyGwU:-KOaLgYUiN3jP7sHH3Ph:b-l5dh7v) ([raw file](https://github.com/qtox/qtox/blob/a5a4216adfd32d8970fc28fbc99bf517d5af7a50/src/widget/form/settings/avform.cpp#L261)):_

> ``` cpp
>                                        [size](VideoMode mode) { return getModeSize(mode) == size; });
> 
>             if(result == newVideoModes.end())
> ```

There should be space between `if` and `(`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by initramfs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 251 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaLt4OzYeutdNLiO7q:-KOaNEwwzX9mzbCJkppW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a5a4216adfd32d8970fc28fbc99bf517d5af7a50/src/widget/form/settings/avform.cpp#L251)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> There should be space between `if` and `(`
> </details>
> Done.

---

_[src/widget/form/settings/avform.cpp, line 261 [r2]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaLgYTBd7OI2pMyGwU:-KOaNFkTt9hIMm_szBTK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a5a4216adfd32d8970fc28fbc99bf517d5af7a50/src/widget/form/settings/avform.cpp#L261)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> There should be space between `if` and `(`
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 262 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaNebHUeWCOQmI4IQO:-KOaNebHUeWCOQmI4IQP:b-j07abg) ([raw file](https://github.com/qtox/qtox/blob/f987ed7fc60dd46398f34fdb969f577a0834070e/src/widget/form/settings/avform.cpp#L262)):_

> ``` cpp
> 
>             if (result == newVideoModes.end())
>             {
> ```

Also braces aren't needed for a single-line `if` branch

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by initramfs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 262 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaNebHUeWCOQmI4IQO:-KOaOTvE3iktflBz1Qqt:b6z80hh) ([raw file](https://github.com/qtox/qtox/blob/f987ed7fc60dd46398f34fdb969f577a0834070e/src/widget/form/settings/avform.cpp#L262)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Also braces aren't needed for a single-line `if` branch
> </details>
> Is it mandated by the coding style for single line ifs? I personally find them ugly...

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 262 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaNebHUeWCOQmI4IQO:-KOaPG13vhRhlcjzF-4e:b-mh12u4) ([raw file](https://github.com/qtox/qtox/blob/f987ed7fc60dd46398f34fdb969f577a0834070e/src/widget/form/settings/avform.cpp#L262)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Is it mandated by the coding style for single line ifs? I personally find them ugly...
> </details>
> Currently qTox style says that braces aren't needed for single-line `if`s. There's plenty of code in this style, so to be consistent this should follow.

Now, if code style was to change, why not, but it has to be changed first, and code after.

On a side note, there are some things regarding formatting of code that could use some discussion – I'll open an issue for it later, perhaps single-line `if`s will be viewed as a subset of the things that need to be discussed there. If not, a new issue can always be opened :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by initramfs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/form/settings/avform.cpp, line 262 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaNebHUeWCOQmI4IQO:-KOaSXe984kmVYdBz9br:bgpdew7) ([raw file](https://github.com/qtox/qtox/blob/f987ed7fc60dd46398f34fdb969f577a0834070e/src/widget/form/settings/avform.cpp#L262)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Currently qTox style says that braces aren't needed for single-line `if`s. There's plenty of code in this style, so to be consistent this should follow.
> 
> Now, if code style was to change, why not, but it has to be changed first, and code after.
> 
> On a side note, there are some things regarding formatting of code that could use some discussion – I'll open an issue for it later, perhaps single-line `if`s will be viewed as a subset of the things that need to be discussed there. If not, a new issue can always be opened :)
> </details>
> Ok. In that case, I've changed the style to no-brace if. And I agree about code formatting, the current code formatting rules seem very lax (or at least enforcement is very lax). Perhaps a scheme can be created for a source code formatter as well (for example, something like ClangFormat, which can be integrated into QtCreator through a plugin).

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589)_

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/widget/form/settings/avform.cpp, line 262 [r3]](https://reviewable.io:443/reviews/qtox/qtox/3589#-KOaNebHUeWCOQmI4IQO:-KOaUH9FqUuIrJkfHsq-:b-squk3p) ([raw file](https://github.com/qtox/qtox/blob/f987ed7fc60dd46398f34fdb969f577a0834070e/src/widget/form/settings/avform.cpp#L262)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Ok. In that case, I've changed the style to no-brace if. And I agree about code formatting, the current code formatting rules seem very lax (or at least enforcement is very lax). Perhaps a scheme can be created for a source code formatter as well (for example, something like ClangFormat, which can be integrated into QtCreator through a plugin).
> </details>
> Using clang-format is ~exactly part of what I would want to propose :D

And current style being too ~lax is the other part :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3589#-:-KOaUWbtYF6DMAlS4PEx:bnfp4nl)_

**Pull request merged**
