### PR TITLE
docs(README): link to instructions for OSX building

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3819)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 28 at r1](https://reviewable.io:443/reviews/qtox/qtox/3819#-KUOO9fJB5nnw4kBy7nG:-KUOO9fJB5nnw4kBy7nH:b-y04aez) ([raw file](https://github.com/qtox/qtox/blob/67fba561a5721fabe3e60be6f8ee441db140f337/README.md#L28)):_

> ``` Markdown
>   - [other](/INSTALL.md#linux)
> * **Mac**:
>   - __[Building instructions]__
> ```

Why do you use `__text__` instead of `**text**` like in other links?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 28 at r1](https://reviewable.io:443/reviews/qtox/qtox/3819#-KUOO9fJB5nnw4kBy7nG:-KUgqrZjQrn4IBJyYBEB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/67fba561a5721fabe3e60be6f8ee441db140f337/README.md#L28)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Why do you use `__text__` instead of `**text**` like in other links?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819)_

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 28 at r2](https://reviewable.io:443/reviews/qtox/qtox/3819#-KUhqOj1iyhdDdG-Vflb:-KUhqOj1iyhdDdG-Vflc:b1914la) ([raw file](https://github.com/qtox/qtox/blob/8fc7ae2e43f33214a6f16ba8fb768469f33ce45c/README.md#L28)):_

> ``` Markdown
>   - [other](/INSTALL.md#linux)
> * **Mac**:
>   - **[Building instructions]**
> ```

Better, but, please, use `[**Building instructions**]` :)
Now is `**[Building instructions]**`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[README.md, line 28 at r2](https://reviewable.io:443/reviews/qtox/qtox/3819#-KUhqOj1iyhdDdG-Vflb:-KUhqsEOoxClXtYwgHLF:bnvtrum) ([raw file](https://github.com/qtox/qtox/blob/8fc7ae2e43f33214a6f16ba8fb768469f33ce45c/README.md#L28)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Better, but, please, use `[**Building instructions**]` :)
> Now is `**[Building instructions]**`
> </details>
> Why would that be needed?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819)_

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 28 at r2](https://reviewable.io:443/reviews/qtox/qtox/3819#-KUhqOj1iyhdDdG-Vflb:-KUhyolCPD9hDrg6Wf28:bkhm0fc) ([raw file](https://github.com/qtox/qtox/blob/8fc7ae2e43f33214a6f16ba8fb768469f33ce45c/README.md#L28)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Why would that be needed?
> </details>
> To maintain uniformity in design

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 28 at r2](https://reviewable.io:443/reviews/qtox/qtox/3819#-KUhqOj1iyhdDdG-Vflb:-KUi3CVvlfNKpRSaIDzo:b-tw6gj2) ([raw file](https://github.com/qtox/qtox/blob/8fc7ae2e43f33214a6f16ba8fb768469f33ce45c/README.md#L28)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> To maintain uniformity in design
> </details>
> Right. Modified other lines to ensure consistency.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819)_

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3819#-:-KUi6FPZdtn4bOywNpt6:bnfp4nl)_

**Pull request merged**
