### PR TITLE
fix pointer's style

### PR DESCRIPTION
**Pull request by PKEv**

### CODE REVIEW

**Comment by tux3** [comment]
Dynamic casts? Don't you mean static_cast?

**Comment by PKEv** [comment]
sorry...

**Comment by tux3** [comment]
Alright, no problem. Now that's still not going to compile because the syntax is wrong. You forgot parentheses.

And I'd almost argue that safe C++ style casts look a bit strange in the middle of all that faux-OO `void*` heavy C style code riddled with macros, but why not.

**Comment by PKEv** [comment]
you're right

**Pull request closed without merging**
