### PR TITLE
chore(build): Use mingw POSIX threading model for pthreads support

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix build failure saying that std::mutex was not declared

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6399)

### CODE REVIEW

**Review by sphaerophoria — COMMENTED** [review]
It seems weird to me that we don't have to package the winpthreads lib with the output at all. Are we certain that a windows build that uses pthreads will not fail due to missing libraries? 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6399#-:-Mmo2a1n0iAj975WTldv:btev6vd)* status: 0 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
I don't have a good understanding of why it works.. but
1) We run ldd on qTox and check that all DLLs are packaged here: https://github.com/qTox/qTox/blob/d7347773f8b0aa5101db6b1aa15e8f4b503bc90b/windows/cross-compile/build.sh#L1459
2) I ran a locally compiled qTox off this branch merged with #6391, and launched (x86_64) qTox on Windows without issue.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6399#-:-MmoM24B3BnwONQfRTmX:b-bqiom9)* status: 0 of 1 LGTMs obtained

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6399#-:-MmodGAF7TTXTW5nuVDx:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by nurupo** [comment]
FYI, I have hit this exact issue when cross-compiling Qt 6 as it uses C++ threading API, so we would need to do this eventually anyway. I fixed it the same way - via `update-alternatives`.

>It seems weird to me that we don't have to package the winpthreads lib with the output at all.

We have been packaging it for a long time now:

https://github.com/qTox/qTox/blob/a9b7a24fe49213e99b92eb7ffe5e0099eacfba3d/windows/cross-compile/build.sh#L1447

**Pull request merged**
