### PR TITLE
Fix audio not working on 64-bit windows with non-latin audio device names

### LINKED ISSUE #816: Voice chat doesnt work
Windows 7 | sp 1 | ultimate
Trying voice chat with my friend - no sound and every restart reset volume microphone & playback
screenshot 2014-11-19 001
In log:
23:16:08 Audio: Cannot open output audio device
23:16:08 Audio: Cannot open input audio device
in config:
[Audio]
inDev=\x41c\x438\x43a\x440\x43e\x444\x43e\x43d (2- \x423\x441\x442\x440\x43e\x439\x441\x442\x432\x43e \x441 \x43f\x43e\x434\x434\x435\x440\x436\x43a\x43e\x439 High Definition Audio)
outDev=\x414\x438\x43d\x430\x43c\x438\x43a\x438 (2- \x423\x441\x442\x440\x43e\x439\x441\x442\x432\x43e \x441 \x43f\x43e\x434\x434\x435\x440\x436\x43a\x43e\x439 High Definition Audio)

AND 
i cannot enable checkboxes here
screenshot 2014-11-19 001

Using last stable build x64

### PR DESCRIPTION
**Pull request by zetok**
properly fixes #816

### CODE REVIEW

**Comment by zetok** [comment]
For anyone willing to test whether it improves situation on 64-bit windows and doesn't introduce regressions on 32 bit one:
32: https://build.tox.chat/job/qTox-testing_build_windows_x86_release/2/artifact/qTox-testing_build_windows_x86_release.zip
64: https://build.tox.chat/job/qTox-testing_build_windows_x86-64_release/14/artifact/qTox-testing_build_windows_x86-64_release.zip

**Comment by agilob** [comment]
I guess I am going to make myself a Windows setup to test it?

**Comment by antis81** [comment]
> I guess I am going to make myself a Windows setup to test it?

@agilob Maybe ask @PKEv?

**Comment by agilob** [comment]
I just got a laptop with German Windows, I can test it today I think(?)

**Comment by agilob** [comment]
Well, the laptop has audio names in English... @PKEv do you have windows to test it?

**Comment by PKEv** [comment]
no, i have no win 64x

**Comment by zetok** [comment]
@PKEv well, I guess that testing on 32 bits whether PR doesn't introduce regressions will have to do, since apparently no one runs 64 bit windows anyway >.<

So if you could, it would be nice `:)`

**Comment by agilob** [comment]
Maybe we should merge it and revert is we get issues about?

**Comment by zetok** [comment]
> Maybe we should merge it and revert is we get issues about?

Yep.

**Comment by agilob** [comment]
ok...

**Pull request merged**
