### PR TITLE
css styles for mainHead and mainContent in widget.cpp

### PR DESCRIPTION
**Pull request by agilob**
fixes problems with ugly UI on non-standard system theme (KDE example)
before: https://i.imgur.com/XJ0mbpi.png
after: https://imgur.com/a/UbgNz

### CODE REVIEW

**Comment by tux3** [comment]
Could you rebase it on master, please ? If you can't it's okay I'll try to resolve the conflicts later.

**Comment by agilob** [comment]
not sure if I did it right. Sorry, never did `git rebase` before.

**Comment by suhr** [comment]
Why not just use `git merge`? Plus one commit is not a big deal.

**Comment by tux3** [comment]
Hm, nope, it stil conflicts. I'll try to resolve that later.

@suhr I can't merge until all the conflicts are resolved. 
The problem is that this PR adds patches on top of f0a825fd766eedd1063779d6e0fb28281997a07c, but in the meantime my master branch added other patches on top of f0a825fd766eedd1063779d6e0fb28281997a07c, and the two sets of patches try to change the same files at the same time, it's a conflict.
Rebasing this PR on my master or my master on this PR will force someone to fix the conflicts.

**Comment by suhr** [comment]
> I can't merge until all the conflicts are resolved. 

I mean he can do `git merge` instead of rebase. It is usually much simpler to do.

**Comment by tux3** [comment]
> It is usually much simpler to do.

How so ? You still need to fix the conflicts.
(plus it messes the branch visualizations if you merge master into a PR then back into master!)

**Comment by suhr** [comment]
With merge you can usually just resolve conflict by any difftool (meld for example) without messing around dark rebase magic and without the danger to break something by history rewrite.

> it messes the branch visualizations

Again, plus one commit is not a big deal.

**Comment by tux3** [comment]
> With merge you can just resolve conflict by any difftool (meld for example) without messing around dark rebase magic

Same with rebases ! You do "git rebase" and when it fails, you call upon "git mergetool"
Then "git rebase --continue", rinse, repeat.

> without the danger to break something by history rewrite.

Yes, that's actually a very valid point. I probably broke quite a lot of things when cherry picking and rebasing in the past, all of that without signing my changes.

> Again, plus one commit is not a big deal.

Agreed. I'm just saying that it makes for an awkward branch history that merges into itself, not that it matters all that much.
pic3

**Comment by tux3** [comment]
Okay there's a problem with "hiding to tray, tested on linux …" (1ec129f5161acded60f588446b39e69a3d17baaf), it makes qTox always start minimized-to-tray for me.

And only the first commit is mentioned in the PR description, so I'll cherry pick the first commit for now and you can send the rest again if you want, is that okay ?

**Comment by tux3** [comment]
First commit cherry-picked and signed in afc77f63dbd650383e8baad7716c79842f1b278e

**Comment by agilob** [comment]
@tux3 should I make another PRs with preview and hiding to tray?

**Comment by tux3** [comment]
@agilob Yes, please (and thank you!).

(And ideally you should make a branch per new feature, so you can make separate PRs, but it's alright in master if you're careful.)

**Comment by agilob** [comment]
it's my first contribution to open source project. don't bite pls.

**Comment by tux3** [comment]
Sorry :)

**Comment by dubslow** [comment]
Simply call `w->show();` before exec() to start unhidden.

**Comment by agilob** [comment]
@dubslow I'll make it properly today, I'll add another setting 'start in tray' to do that.

**Pull request closed without merging**
