### PR TITLE
Refactor ChatForm

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4288)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 542 at r1](https://reviewable.io:443/reviews/qtox/qtox/4288#-Kg5wzK_cNH-iPhHTnlm:-Kg5wzKaePN55NVoCpVB:b5x6fz7) ([raw file](https://github.com/qtox/qtox/blob/46dfcd4fc62ee6e92fa5492cb88ffcf204fc1ff9/src/widget/form/chatform.cpp#L542)):*
> ```cpp
> 
>     if (Settings::getInstance().getStatusChangeNotificationEnabled()) {
>         QString fStatus = STATUS_TO_STRING[static_cast<int>(status)];
> ```

I'm not a huge fan of replacing those enum to string mappers with qvectors, because you loose the protection of the compiler for unhandled cases and changes of the enum. Maybe extract the switch case into a function?

---

*[src/widget/form/chatform.cpp, line 889 at r1](https://reviewable.io:443/reviews/qtox/qtox/4288#-Kg5ypHDg7bTc6p-efmA:-Kg5ypHERHW9G8UWNjKM:b-srqwvi) ([raw file](https://github.com/qtox/qtox/blob/46dfcd4fc62ee6e92fa5492cb88ffcf204fc1ff9/src/widget/form/chatform.cpp#L889)):*
> ```cpp
> void ChatForm::startCounter()
> {
>     if (callDurationTimer != nullptr) {
> ```

Is there an advantage in comparing with `nullptr`? Because right now the coding style specifies no rule for that and IIRC atleast @Diadlo doesn't do it like this. Please leave these like they are for now, so that we are not changing it back and forth every time :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4288)*

**Comment by noavarice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 542 at r1](https://reviewable.io:443/reviews/qtox/qtox/4288#-Kg5wzK_cNH-iPhHTnlm:-Kg63L1OrMs7gWyqznyY:bs7wumx) ([raw file](https://github.com/qtox/qtox/blob/46dfcd4fc62ee6e92fa5492cb88ffcf204fc1ff9/src/widget/form/chatform.cpp#L542)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I'm not a huge fan of replacing those enum to string mappers with qvectors, because you loose the protection of the compiler for unhandled cases and changes of the enum. Maybe extract the switch case into a function?
</blockquote></details>

Done. 

---

*[src/widget/form/chatform.cpp, line 889 at r1](https://reviewable.io:443/reviews/qtox/qtox/4288#-Kg5ypHDg7bTc6p-efmA:-Kg63WzrYJzLdOVEHfiY:ba9b5ue) ([raw file](https://github.com/qtox/qtox/blob/46dfcd4fc62ee6e92fa5492cb88ffcf204fc1ff9/src/widget/form/chatform.cpp#L889)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Is there an advantage in comparing with `nullptr`? Because right now the coding style specifies no rule for that and IIRC atleast @Diadlo doesn't do it like this. Please leave these like they are for now, so that we are not changing it back and forth every time :)
</blockquote></details>

Done. The only reason i change this is making it a bit more obvious, but it's not so important

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4288)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4288#-:-Kg658ZY6Q7oVYuGYGyo:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_cancel:

I just noticed you removed the call to `getTypingNotification`, this makes it impossible to switch off typing notifications.

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4288#-:-KgAyrsNP747p2hLuk1i:b-hayf0a)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4288#-:-KgTdE6inMeqpNM3vnmF:b-jbsf8z)*

**Pull request merged**
