### PR TITLE
Use GroupInvite instead of set of parameters

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4597)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.cpp, line 499 at r1](https://reviewable.io:443/reviews/qtox/qtox/4597#-KsZ2UD2d83ExkAokqYV:-KsZ2UD3HGB6ERja9DB3:b1q8xoo) ([raw file](https://github.com/qtox/qtox/blob/1d6a062abd4e390558352a88927d57154b06e72e/src/core/core.cpp#L499)):*
> ```cpp
>     Core* core = static_cast<Core*>(vCore);
>     const QByteArray data(static_cast<const char*>(static_cast<const void*>(cookie)), length);
>     const GroupInvite inviteInfo(friendId, type, data);
> ```

Not sure, that using `GroupInvite` in `Core` is good idea: I thought to make Core independent from most other qTox parts. What do you think?

---

*[src/model/groupinvite.cpp, line 28 at r1](https://reviewable.io:443/reviews/qtox/qtox/4597#-KsZ2AlRB59Q-b4TcbCp:-KsZ2AlRB59Q-b4TcbCq:bfh2lnm) ([raw file](https://github.com/qtox/qtox/blob/1d6a062abd4e390558352a88927d57154b06e72e/src/model/groupinvite.cpp#L28)):*
> ```cpp
>  */
> 
> GroupInvite::GroupInvite()
> ```

Add member initialization

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by noavarice** [comment]
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.cpp, line 499 at r1](https://reviewable.io:443/reviews/qtox/qtox/4597#-KsZ2UD2d83ExkAokqYV:-KsyUmHb1LMWdw18h9RI:b-ucisqo) ([raw file](https://github.com/qtox/qtox/blob/1d6a062abd4e390558352a88927d57154b06e72e/src/core/core.cpp#L499)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Not sure, that using `GroupInvite` in `Core` is good idea: I thought to make Core independent from most other qTox parts. What do you think?
</blockquote></details>

I think it's acceptable fot time being

---

*[src/model/groupinvite.cpp, line 28 at r1](https://reviewable.io:443/reviews/qtox/qtox/4597#-KsZ2AlRB59Q-b4TcbCp:-KsyUkO0DaB5adEdZ56n:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1d6a062abd4e390558352a88927d57154b06e72e/src/model/groupinvite.cpp#L28)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add member initialization
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 14 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597#-:-Ksyj0Id6mzVntw5LeNl:b-jbsf8z)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/core/core.cpp, line 1207 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-Kt1oq0HYdVUMMQe5WCm:-Kt1oq0HYdVUMMQe5WCn:b-7qd95i) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L1207)):*
> ```cpp
>     const uint8_t confType = inviteInfo.getType();
>     const QByteArray invite = inviteInfo.getInvite();
>     const uint8_t* cookie = static_cast<const uint8_t*>(static_cast<const void*>(invite.data()));
> ```

`... const cookie`, pointer itself is also not changed.

---

*[src/model/groupinvite.h, line 40 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-Kt1pDPacLYZ0Ow9Fmve:-Kt1pDPacLYZ0Ow9Fmvf:bv42hkp) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/model/groupinvite.h#L40)):*
> ```objc
> 
> private:
>     uint32_t friendId;
> ```

I would suggest use in-class initializers here:
```
uint32_t fridnId{0};
uint8_t type{0};
```
And use `GroupInvite() = default` or remove it completely.

[C.45: Don't define a default constructor that only initializes data members; use in-class member initializers instead](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c45-dont-define-a-default-constructor-that-only-initializes-data-members-use-in-class-member-initializers-instead)


QByteArray and QDateTime does not need {}.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by sudden6** [comment]
Reviewed 8 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.cpp, line 498 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-KtDMVa1EMlKvN25cgGu:-KtDMVa1EMlKvN25cgGv:bcajbka) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L498)):*
> ```cpp
> {
>     Core* core = static_cast<Core*>(vCore);
>     const QByteArray data(static_cast<const char*>(static_cast<const void*>(cookie)), length);
> ```

why do you need to cast twice here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.cpp, line 498 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-KtDMVa1EMlKvN25cgGu:-KtG9Vy6kGxvI4cNn4CE:b-49ta4i) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L498)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why do you need to cast twice here?
</blockquote></details>

Looks like a trick to avoid reinterpret_cast.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/core/core.cpp, line 498 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-KtDMVa1EMlKvN25cgGu:-KtfH_wP98-ckKNxheXd:b-1k7nin) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L498)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Looks like a trick to avoid reinterpret_cast.
</blockquote></details>

And it is

---

*[src/core/core.cpp, line 1207 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-Kt1oq0HYdVUMMQe5WCm:-KtfIwdJPNK-GMC8ljy_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L1207)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`... const cookie`, pointer itself is also not changed.
</blockquote></details>

Done.

---

*[src/model/groupinvite.h, line 40 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-Kt1pDPacLYZ0Ow9Fmve:-KtfJ2is8-hZOaYqA_rz:bej5lmd) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/model/groupinvite.h#L40)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I would suggest use in-class initializers here:
```
uint32_t fridnId{0};
uint8_t type{0};
```
And use `GroupInvite() = default` or remove it completely.

[C.45: Don't define a default constructor that only initializes data members; use in-class member initializers instead](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c45-dont-define-a-default-constructor-that-only-initializes-data-members-use-in-class-member-initializers-instead)


QByteArray and QDateTime does not need {}.


</blockquote></details>

I do not actually like in-class initialization - you are forced to keep in mind that this field may be initialized in header file, or may not. Any way, all changes you mention here were done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by Talkless** [comment]
Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/groupinvite.h, line 40 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-Kt1pDPacLYZ0Ow9Fmve:-KtfT1G6SArIM4DrhzWm:bglnyzo) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/model/groupinvite.h#L40)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I do not actually like in-class initialization - you are forced to keep in mind that this field may be initialized in header file, or may not. Any way, all changes you mention here were done
</blockquote></details>

Well, from other point of view, you can forget initialize var in constructor initializer list after you have adding new variable it into a header. Just write `Foo* m_foo{nullptr};` in one go, and actually forget it. If you add one more constructor overload later, it will still be null-initialized.

Anyway, I have a dream that open source projects would converge into single code style some day, and C++ Core Guidelines is a step into that direction. There are still tabs/spaces and "where do you put { " eternal battle, but at Core Guidelines might help at least with "best practices", so that's why I advocate it. 

It might have rules that I personally don't "like", but I guess it's good trade for *consistency* across projects, making it easier to contribute seeing similar code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by noavarice** [comment]
Review status: 7 of 12 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/model/groupinvite.h, line 40 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-Kt1pDPacLYZ0Ow9Fmve:-KtfWTRJoAzdF0F_WFNS:b-e1uy2l) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/model/groupinvite.h#L40)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Well, from other point of view, you can forget initialize var in constructor initializer list after you have adding new variable it into a header. Just write `Foo* m_foo{nullptr};` in one go, and actually forget it. If you add one more constructor overload later, it will still be null-initialized.

Anyway, I have a dream that open source projects would converge into single code style some day, and C++ Core Guidelines is a step into that direction. There are still tabs/spaces and "where do you put { " eternal battle, but at Core Guidelines might help at least with "best practices", so that's why I advocate it. 

It might have rules that I personally don't "like", but I guess it's good trade for *consistency* across projects, making it easier to contribute seeing similar code.
</blockquote></details>

You are right, consistency is a very important property for code style. So I accept this. You are making valuable contributions to ~at least this project~ whole community, that is more appropriate thing to say

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by sudden6** [comment]
Reviewed 2 of 14 files at r1, 4 of 5 files at r3.
Review status: 11 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.cpp, line 498 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-KtDMVa1EMlKvN25cgGu:-KtktUPsk6P628SwLsfZ:bfbtbey) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L498)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

And it is
</blockquote></details>

Since this looks a bit strange, can you add a comment to document why it's needed here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by noavarice** [comment]
Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/core.cpp, line 498 at r2](https://reviewable.io:443/reviews/qtox/qtox/4597#-KtDMVa1EMlKvN25cgGu:-Ktly3vAlVeTIvCQ4poR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/722e881ee6a5a57661cf2b2bcaea5a79a937eac7/src/core/core.cpp#L498)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Since this looks a bit strange, can you add a comment to document why it's needed here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 9 of 12 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4597#-:-KtmNXjjgL6EZFWH6Fth:b-jbsf8z)*

**Comment by sudden6** [comment]
@noavarice merge?

**Pull request merged**
