### PR TITLE
fix(ui): don't emit filename change windows for every chat

### PR DESCRIPTION
**Pull request by sudden6**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5226)

### CODE REVIEW

**Comment by sudden6** [comment]
fixes #5225

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5226)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 318 at r1](https://reviewable.io/reviews/qtox/qtox/5226#-LHFO2jp2b4gaIiYeXR5:-LHFO2jp2b4gaIiYeXR6:bgetmum) ([raw file](https://github.com/qtox/qtox/blob/0cfa9434b6adc2784a790204d0a13cb3902df862/src/core/corefile.cpp#L318)):*
> ```cpp
>     } else {
>         const auto cleanFileName = CoreFile::getCleanFileName(filename.getQString());
>         if (cleanFileName != filename.getQString()) {
> ```

it turns out getCleanFileName doesn't catch backslashes in filenames despite its intention because the backslash needs multiple levels of escaping (C++, regex). Do you mind including this patch as part of your change to address it?
\-    QRegularExpression regex("[<>:\"/\\|?*]");
\+    QRegularExpression regex{QStringLiteral(R"([<>:"/\\|?*])")};

**Review by anthonybilinski — COMMENTED** [review]
tested and works well. Please apply the small regex patch to catch '\\' in filenames as well.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5226#-:-LHFORSg5M1coKCs_oGi:b5o3h2x)* status: 0 of 1 LGTMs obtained

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5226)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 318 at r1](https://reviewable.io/reviews/qtox/qtox/5226#-LHFO2jp2b4gaIiYeXR5:-LHFWFYj8J0s_XyafueM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0cfa9434b6adc2784a790204d0a13cb3902df862/src/core/corefile.cpp#L318)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

it turns out getCleanFileName doesn't catch backslashes in filenames despite its intention because the backslash needs multiple levels of escaping (C++, regex). Do you mind including this patch as part of your change to address it?
-    QRegularExpression regex("[<>:\"/\\|?*]");
+    QRegularExpression regex{QStringLiteral(R"([<>:"/\\|?*])")};

</blockquote></details>

Done.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5226)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 286 at r2](https://reviewable.io/reviews/qtox/qtox/5226#-LHFZO3Q9siY_vU1GQeQ:-LHFZO3Q9siY_vU1GQeR:b-wayvh5) ([raw file](https://github.com/qtox/qtox/blob/030ef87c6ec20c5dbb52145d6b11c6276982a5d1/src/core/corefile.cpp#L286)):*
> ```cpp
> QString CoreFile::getCleanFileName(QString filename)
> {
>     QRegularExpression regex{QStringLiteral(R"([<>:"/\|?])")};
> ```

Sorry, my comment had its double backslash converted to single backslash by github/reviewable >.<
We still need the double to backslash to escape the backslash from regex. So full thing: QRegularExpression regex{QStringLiteral(R"([<>:"/\\\\|?*])")};

**Review by anthonybilinski — APPROVED** [review]
pending (second) adjustment to add \\\\ instead of \\ in regex, :lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5226#-:-LHG2vIh1jbgMa5br-JU:bbq4vg3)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 286 at r2](https://reviewable.io/reviews/qtox/qtox/5226#-LHFZO3Q9siY_vU1GQeQ:-LHG2noQ00aW-xRsjKoc:be226gt) ([raw file](https://github.com/qtox/qtox/blob/030ef87c6ec20c5dbb52145d6b11c6276982a5d1/src/core/corefile.cpp#L286)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Sorry, my comment had its double backslash converted to single backslash by github/reviewable >.<
We still need the double to backslash to escape the backslash from regex. So full thing: QRegularExpression regex{QStringLiteral(R"([<>:"/\\\\|?*])")};
</blockquote></details>

Going to unblock the PR and give a LGTM so that you can push once this is fixed.

**Pull request merged**
