### PR TITLE
fix(ui): fix typo, make 's' in user(s) conditional

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5630)

### CODE REVIEW

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5630#-:-LczZ85i1jUhelwpC0bM:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by Diadlo** [comment]
https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals

**Review by Diadlo — CHANGES_REQUESTED** [review]
Old way was correct

https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals

**Review by Diadlo — APPROVED** [review]
Old way was correct

https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5630#-:-Lczk0k37WPZRwRnFBUO:b-6q1i2m)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by Diadlo** [comment]
Can't find the way to block merge

**Review by Diadlo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5630)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/groupwidget.cpp, line 164 at r2](https://reviewable.io/reviews/qtox/qtox/5630#-LczkNG79vrOD9LkPvTR:-LczkNG79vrOD9LkPvTS:b-6q1i2m) ([raw file](https://github.com/qtox/qtox/blob/3dd4445626caa42dc754f00ef664a658da3cb3da/src/widget/groupwidget.cpp#L164)):*
> ```cpp
> {
>     int peersCount = chatroom->getGroup()->getPeersCount();
>     if (peersCount == 1) {
> ```

Old way was correct

https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals

**Comment by sudden6** [comment]
@Diadlo To prevent merge you can assign the PR to yourself. I did this now for you.

**Comment by Diadlo** [comment]
@sudden6 Ok. Thanks

**Comment by anthonybilinski** [comment]
Thanks @Diadlo.

There seems to be some other problem making `GroupWidget::updateUserCount` not translate its string then, since that `(s)` is present for me, and the label doesn't update for any language.

~~`GroupWidget::updateUserCount`~~ `GroupChatForm::updateUserCount` on the other hand splits the plural and singular form without including the number in the translation (the wrong way) and it does translate correctly.

**Comment by Diadlo** [comment]
@anthonybilinski Probably it is because noone translate this string until now.  Try to run `./tools/update-translation-files.sh ALL && git diff HEAD~1` and check, that no languages currently have translation for this string

**Comment by anthonybilinski** [comment]
Oops in my previous comment I meant `GroupChatForm::updateUserCount` splits plural/singular and works correctly. But it looks like that's right, there are no translations for it. The source string also can't be found on weblate, since it looks like `GroupWidget::updateUserCount` was added after our last weblate merge. I've updated my PR to instead change `GroupChatForm::updateUserCount` to not split singular/plural forms and include them as part of the translation like `GroupWidget::updateUserCount` already does.

I'll also update sync weblate with our repo after this merge to add the plural string since it looks we haven't done that since 2018-07-01.

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5630)* status: 0 of 1 LGTMs obtained (waiting on @Diadlo)

___
*[src/widget/groupwidget.cpp, line 164 at r2](https://reviewable.io/reviews/qtox/qtox/5630#-LczkNG79vrOD9LkPvTR:-Ld21DhM3Pnq7ki8_OI7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3dd4445626caa42dc754f00ef664a658da3cb3da/src/widget/groupwidget.cpp#L164)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Old way was correct

https://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals
</blockquote></details>

Done.

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5630#-:-Ld2J5fF1HIskyfiNRAc:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
