### PR TITLE
Refactor GenericChatForm

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4343)

### CODE REVIEW

**Comment by Diadlo** [comment]
Seems contentdialog and friendlistwidget have only style change. I think it's out of the scope of the PR

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/genericchatform.cpp, line 76 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6cw9HyAfKlUlqxMmz:-Ki6cw9HyAfKlUlqxMn-:b-awjsqy) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.cpp#L76)):*
> ```cpp
>  * @return Style string
>  */
> QString fontToCss(const QFont& font, const QString& name)
> ```

Make it static

---

*[src/widget/form/genericchatform.cpp, line 92 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6czNbceMhjA9lqMuc:-Ki6czNbceMhjA9lqMud:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.cpp#L92)):*
> ```cpp
>  * @return Name or alias of someone with such public key
>  */
> QString resolveToxId(const ToxPk& pk)
> ```

Same as above

---

*[src/widget/form/genericchatform.cpp, line 176 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6pZXBA8LkDh1pmTtR:-Ki6pZXBA8LkDh1pmTtS:b-kcjudu) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.cpp#L176)):*
> ```cpp
>     msgEdit->setFrameStyle(QFrame::NoFrame);
> 
>     sendButton->setStyleSheet(Style::getStylesheet(":/ui/sendButton/sendButton.css"));
> ```

What about macros here?
```
#define LOAD_STYPE(x) (x)->setStyleSheet(Style::getStylesheet(":/ui/"#x#"/"#x#".css"))
```

---

*[src/widget/form/genericchatform.cpp, line 458 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6rmLSxPkfMepV8uty:-Ki6rmLSxPkfMepV8utz:b-mc10kz) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.cpp#L458)):*
> ```cpp
>     auto chatMsg = ChatMessage::createChatMessage(authorStr, msg, ChatMessage::ALERT, isSelf, dt);
>     qint64 messagesTimeDiff = prevMsgDateTime.secsTo(QDateTime::currentDateTime());
>     if (author == previousId && messagesTimeDiff < chatWidget->repNameAfter) {
> ```

Seems, code used twice. What about extract it to the `nameNeedRepeat` method?

---

*[src/widget/form/genericchatform.h, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6s0EBQJAgvXBSI-W3:-Ki6s0EBQJAgvXBSI-W4:bb6bgxd) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.h#L24)):*
> ```objc
> 
> #include "src/chatlog/chatmessage.h"
> #include "src/core/toxid.h"
> ```

Seems, can be replaced on `ToxPk` forward declaration

---

*[src/widget/form/genericchatform.h, line 35 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6sKUnMuI8ArroNtCu:-Ki6sKUnMuI8ArroNtCv:b-h4l59g) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.h#L35)):*
> ```objc
>  */
> 
> QString resolveToxId(const ToxPk& id);
> ```

I don't think, that it's good idea to place it here. I'm not sure

---

*[src/widget/form/genericchatform.h, line 70 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6sbWEqNuaS0hHI2mU:-Ki6sbWEqNuaS0hHI2mV:b2jixy1) ([raw file](https://github.com/qtox/qtox/blob/146a3dd7330b2645e3b6ded854a66efbc8b337ff/src/widget/form/genericchatform.h#L70)):*
> ```objc
> 
>     void addMessage(const ToxPk& author, const QString& message, const QDateTime& datetime,
>                     bool isAction, bool isSent);
> ```

Seems, isSend always true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343#-:-Ki6sw39IPwkv2do13_U:b-6224x9)*

**Comment by noavarice** [comment]
Reverted to the previous state

---

Review status: 0 of 5 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/genericchatform.cpp, line 76 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6cw9HyAfKlUlqxMmz:-KiA-vrzETwdOTJgf0OA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.cpp#L76)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Make it static
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.cpp, line 92 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6czNbceMhjA9lqMuc:-KiA6lP8JQPX82MJbdr0:b-y0txs) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.cpp#L92)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Can't do this because `resolveToxId` is used in `ChatForm` source code file so static function is not visible from there

---

*[src/widget/form/genericchatform.cpp, line 176 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6pZXBA8LkDh1pmTtR:-KiA77SQSKJL4US4CVaW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.cpp#L176)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about macros here?
```
#define LOAD_STYPE(x) (x)->setStyleSheet(Style::getStylesheet(":/ui/"#x#"/"#x#".css"))
```
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.cpp, line 458 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6rmLSxPkfMepV8uty:-KiA-z2pcDIURnxKta5s:b-24gl3e) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.cpp#L458)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems, code used twice. What about extract it to the `nameNeedRepeat` method?
</blockquote></details>

Done. It was used for three times (in `ChatForm` also) so I made some other changes related to it

---

*[src/widget/form/genericchatform.h, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6s0EBQJAgvXBSI-W3:-KiA0-HaXr2KudursiPt:bo678bt) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L24)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems, can be replaced on `ToxPk` forward declaration
</blockquote></details>

There's a `previousId` class field, so it cannot be replaced

---

*[src/widget/form/genericchatform.h, line 35 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6sKUnMuI8ArroNtCu:-KiA0AcvYr3CKPx4goZY:b8c5sxd) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L35)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I don't think, that it's good idea to place it here. I'm not sure
</blockquote></details>

This function is used in `ChatForm` class too, but it should not be a part of `GenericChatForm` class. I don't see other ways for now

---

*[src/widget/form/genericchatform.h, line 70 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6sbWEqNuaS0hHI2mU:-KiAAVj7AKRr2Nuxa1ss:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L70)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems, isSend always true
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343#-:-KiAEytS755kBcwX1Q8U:baovk04)*

**Comment by Diadlo** [comment]
Reviewed 5 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/genericchatform.h, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6s0EBQJAgvXBSI-W3:-KiAauLYqd7p-Fl5gtxw:bkxr2dg) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L24)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

There's a `previousId` class field, so it cannot be replaced
</blockquote></details>

It's `ToxPk`

---

*[src/widget/form/genericchatform.h, line 35 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6sKUnMuI8ArroNtCu:-KiOlC-lizbQZS4qeZTK:bo30ccd) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L35)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

This function is used in `ChatForm` class too, but it should not be a part of `GenericChatForm` class. I don't see other ways for now
</blockquote></details>

But free function not related with `genericchatform` module is wrong. Move it in ~Core or something like this. You can create `resplove.{h,cpp}` or return in back in the class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by noavarice** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/genericchatform.h, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6s0EBQJAgvXBSI-W3:-KiP15JrwitdRJwL9OjL:bv752kt) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L24)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

It's `ToxPk`
</blockquote></details>

`toxid.h` replaced with `toxpk.h`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by noavarice** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/genericchatform.h, line 35 at r1](https://reviewable.io:443/reviews/qtox/qtox/4343#-Ki6sKUnMuI8ArroNtCu:-KiP1F57dWXaLxxmI7gq:b-l5gfjg) ([raw file](https://github.com/qtox/qtox/blob/1f1b88509555873253a131cea2564d5fbc0193bd/src/widget/form/genericchatform.h#L35)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

But free function not related with `genericchatform` module is wrong. Move it in ~Core or something like this. You can create `resplove.{h,cpp}` or return in back in the class
</blockquote></details>

Returned to `GenericChatForm`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by Diadlo** [comment]
:lgtm_strong:
@sudden6 Can you take a look?

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343#-:-KiP1RFLyKU3RjKwUwVC:bi4wzw1)*

**Comment by sudden6** [comment]
Reviewed 2 of 8 files at r2, 1 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 94 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPWrFTp6oChtMaghqt:-KiPWrFUmkQIDiMHSWL_:b-rwvf2u) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L94)):*
> ```cpp
>  * @return Name or alias of someone with such public key
>  */
> QString GenericChatForm::resolveToxId(const ToxPk& pk)
> ```

should be renamed to `resolveToxPk`

---

*[src/widget/form/genericchatform.cpp, line 108 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPYIcT9lldeSHP3tzd:-KiPYIcT9lldeSHP3tze:b-laxxuz) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L108)):*
> ```cpp
>     }
> 
>     return QString{};
> ```

Maybe `ToxPk.toString()` as fallback?

---

*[src/widget/form/genericchatform.cpp, line 380 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPXQGJ8ATTROMMz8UK:-KiPXQGJ8ATTROMMz8UL:b-lwjpm6) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L380)):*
> ```cpp
>  * @brief Show, is it needed to repeat message author name or not
>  * @param messageAuthor Author of the sent message
>  * @return True if it's needed to repeat name, false otherwise
> ```

I think this comment is inverted

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 108 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPYIcT9lldeSHP3tzd:-KiPYR5E189Amg_ezDxE:bwa5jt5) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L108)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Maybe `ToxPk.toString()` as fallback?
</blockquote></details>

And since this shouldn't happen, probably also a warning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by noavarice** [comment]
Review status: 2 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/widget/form/genericchatform.cpp, line 94 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPWrFTp6oChtMaghqt:-KiZXu3ec_wFGit_eirP:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L94)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

should be renamed to `resolveToxPk`
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.cpp, line 108 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPYIcT9lldeSHP3tzd:-KiZXvk1n3fOAzYMFP-E:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L108)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

And since this shouldn't happen, probably also a warning.
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.cpp, line 380 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPXQGJ8ATTROMMz8UK:-KiZXx0DYCr-4Zfn7rYo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L380)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think this comment is inverted
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by sudden6** [comment]
Reviewed 2 of 3 files at r5.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 380 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPXQGJ8ATTROMMz8UK:-KiaR9T0ydNGEofQlqSp:b-ukbm87) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L380)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Done.
</blockquote></details>

typo in `false`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by noavarice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/widget/form/genericchatform.cpp, line 380 at r3](https://reviewable.io:443/reviews/qtox/qtox/4343#-KiPXQGJ8ATTROMMz8UK:-KiaWMmDhVy8SlcqQ1gK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9da302af74a029dfb87fbda52267d26173cff071/src/widget/form/genericchatform.cpp#L380)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo in `false`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4343#-:-KiacMB6ZBS31AUXjSJj:b-jbsf8z)*

**Pull request merged**
