### PR TITLE
Style sheet and some minor changes

### PR DESCRIPTION
**Pull request by kushagrasurana**
Corrected tab ordering in general settings
Added visual change of disabled settings
Stylesheet changes
faux offline messaging is visible now

### CODE REVIEW

**Comment by agilob** [comment]
Please try using dark system skin to see how it looks now.
Or check this PR to see why I added white background color definitions: https://github.com/tux3/qTox/pull/397

**Comment by kushagrasurana** [comment]
@agilob understood why you used white background and black color for text.
Made changes in stylesheets accordingly.

**Comment by agilob** [comment]
I will try it as soon as I can compile qtox from sources again.

**Comment by AWeinb** [comment]
settings

I don't know but I like the original button bar more and the original box border color looks for me nicer. Also the slightly darker background wasn't bad. (In the old case you would need to set the background of the elements in the boxes to transparent to remove the white background)
Also slightly transparent tooltips arent good to read here.
The centered heading is nice, but it is not good to grasp on the first view. Maybe add some margin at the top?
The inactive button feature is nice.

**Comment by kushagrasurana** [comment]
@AWeinb Thanks for your suggestions.

> I don't know but I like the original button bar more and the original box border color looks for me nicer.
I feel the new style very clean. The button bar matches and changes with qTox's theme.

> Also the slightly darker background wasn't bad. (In the old case you would need to set the background of the elements in the boxes to transparent to remove the white background)
I had previously tried transparent background but as agilob said, the text wont be clear on systems with dark theme.

> Also slightly transparent tooltips arent good to read here.
I will reduce the transparency. The original tooltip was not readable for me.

> The centered heading is nice, but it is not good to grasp on the first view. Maybe add some margin at the top?
I think its better to bring it back to left, as user will need to roll his eyes to view the heading if it is centered.

Once qTox is ported to new api, there will be more people to provide suggestions. lets wait for that.

**Comment by kushagrasurana** [comment]
@AWeinb Thanks for your suggestions.

> I don't know but I like the original button bar more and the original box border color looks for me nicer.

I feel the new style very clean. The button bar matches and changes with qTox's theme.

> Also the slightly darker background wasn't bad. (In the old case you would need to set the background of the elements in the boxes to transparent to remove the white background)

I had previously tried transparent background but as agilob said, the text wont be clear on systems with dark theme.

> Also slightly transparent tooltips arent good to read here.

The original tooltip was not readable for me. So i changed it to this. I will update it with reduced transparency.

> The centered heading is nice, but it is not good to grasp on the first view. Maybe add some margin at the top?

I think its better to bring it back to left, as user will need to roll his eyes to view the heading if it is centered.

Once qTox is ported to new api, there will be more people to provide suggestions. lets wait for that.

**Comment by agilob** [comment]
I will check out your branch when we can compile qTox from sources again. I was working on my own project this month and I have three really good styles, white, dark+blue and dark. I will probably send you a PR with my changes.

**Comment by agilob** [comment]
I have two dark themes nearly prepared

wombat and darkblue, both of them need some polishing and fixes for chatwidget, but 90% is done:

darkblue
wombat

**Comment by kushagrasurana** [comment]
@agilob Both look amazing, way better than the current theme of qTox. Specially the first one (dark+blue).

**Comment by agilob** [comment]
I have some improvements to current light theme too.

**Comment by AWeinb** [comment]
You did a good job with the themes! Especially the first screen looks nice. Am exited for your bright theme improvments because thats what I would use ;)

**Comment by SkyzohKey** [comment]
@agilob Up ! What about new themes ? :)

**Comment by agilob** [comment]
Some previous PRs broke compatibility and I have to start again..

**Comment by agilob** [comment]
@kushagrasurana  I copied your code to my branch. this can be closed.

**Comment by linux-modder** [comment]
@agilob  really like the first dark one

**Pull request closed without merging**
