### PR TITLE
Change smiley color

### LINKED ISSUE #1975: Emoticons/Characters aren't visible
Hello,

some emoticons/characters aren't visible.
Screenshot: 
282e61y jpg

The other issue: Does qTox really need so many emoticons? ;-)

### PR DESCRIPTION
**Pull request by ovalseven8**
This closes #1975.

### CODE REVIEW

**Comment by agilob** [comment]
This PR and #2708 contain two the same commits. This PR has two commits more, do you want me to merge only this one?

**Comment by ovalseven8** [comment]
Well, if you merge this PR, #2708 and #2709 can be closed as well, yes.
Then, everything concerning the smiley packs should be done.

tux3 just wanted that I create multiple PR's for better overview.
The reason why you can see the same commits is basically because the commits depend on each other.

**Comment by agilob** [comment]
> The reason why you can see the same commits is basically because the commits depend on each other.

That's what I thought and wanted to ask :)

**Comment by agilob** [comment]
I don't see any regression and no one opposed, so merging.

**Pull request merged**
