### PR TITLE
Fix experemental audio

### LINKED ISSUE #4904: Echo when chat partner uses loudspeakers
I was faced with the problem of reverse echo. When my interlocutor uses loudspeakers all that I say in my microphone - I also hear in my headphones. And my voice sounds louder than the voice of the interlocutor, which greatly hinders the conversation and ultimately annoying. If the interlocutor changes the loudspeakers to the headphones, then the problem disappears.

OS: Kubuntu 14.04
qTox gitrev: ea6364ae020ead729adffad3073283d63fc98ba0 (and above, I use my own assembly)
toxcore:  0.1.11
Qt:  5.9.3

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4904

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4915)

### CODE REVIEW

**Comment by Diadlo** [comment]
Tested with @hkarel. Echo cancellation works good

**Comment by sudden6** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/audio/backend/openal.cpp, line 589 at r1](https://reviewable.io:443/reviews/qtox/qtox/4915#-L3-dF6vlcLoZvMKfLgI:-L3-dF6wuNv_4bP3s472:b-w37bgu) ([raw file](https://github.com/qtox/qtox/blob/c0327458966ab7b14879dd6838907221c4d854b8/src/audio/backend/openal.cpp#L589)):*
> ```cpp
>     }
> 
>     emit Audio::frameAvailable(inputBuffer, AUDIO_FRAME_SAMPLE_COUNT, 1, AUDIO_SAMPLE_RATE);
> ```

use actual channel count here

---

*[src/audio/backend/openal2.cpp, line 303 at r1](https://reviewable.io:443/reviews/qtox/qtox/4915#-L3-bYfD6YR1vpj41naU:-L3-bYfEuDj70Bc_B2hx:b-o88x67) ([raw file](https://github.com/qtox/qtox/blob/c0327458966ab7b14879dd6838907221c4d854b8/src/audio/backend/openal2.cpp#L303)):*
> ```cpp
>         kill_filter_audio(filterer);
>         filterer = nullptr;
>         return;
> ```

I don't think this is correct. It leads to no audio output at all if echo cancelling is not available.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4915)*

**Comment by Diadlo** [comment]
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/audio/backend/openal.cpp, line 589 at r1](https://reviewable.io:443/reviews/qtox/qtox/4915#-L3-dF6vlcLoZvMKfLgI:-L3-yKGoNW3r3IrQ9PQS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c0327458966ab7b14879dd6838907221c4d854b8/src/audio/backend/openal.cpp#L589)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use actual channel count here
</blockquote></details>

Done.

---

*[src/audio/backend/openal2.cpp, line 303 at r1](https://reviewable.io:443/reviews/qtox/qtox/4915#-L3-bYfD6YR1vpj41naU:-L3-yKlSx9ugeVp8CG-v:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/c0327458966ab7b14879dd6838907221c4d854b8/src/audio/backend/openal2.cpp#L303)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I don't think this is correct. It leads to no audio output at all if echo cancelling is not available.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4915)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4915#-:-L3-yg02hK96M_aPutzQ:b-jbsf8z)*

**Comment by Diadlo** [comment]
@hkarel Said, that qTox starts segfault with this PR
```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000593f2f in OpenAL2::doOutput() ()
#2  0x000000000058f045 in OpenAL::doAudio() ()
#3  0x00007fb150864d71 in QObject::event(QEvent*) () from /opt/qtox/lib/libQt5Core.so.5
#4  0x00007fb14ec9a5bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /opt/qtox/lib/libQt5Widgets.so.5
#5  0x00007fb14eca18c1 in QApplication::notify(QObject*, QEvent*) () from /opt/qtox/lib/libQt5Widgets.so.5
#6  0x00007fb150838a38 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /opt/qtox/lib/libQt5Core.so.5
#7  0x00007fb15083b67d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /opt/qtox/lib/libQt5Core.so.5
#8  0x00007fb15088cd13 in ?? () from /opt/qtox/lib/libQt5Core.so.5
#9  0x00007fb15912ee04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fb15912f048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fb15912f0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fb15088c36f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qtox/lib/libQt5Core.so.5
#13 0x00007fb15083705a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /opt/qtox/lib/libQt5Core.so.5
#14 0x00007fb150662f9b in QThread::exec() () from 
[01:20 PM] hkarel: /opt/qtox/lib/libQt5Core.so.5
#15 0x00007fb150667c3a in ?? () from /opt/qtox/lib/libQt5Core.so.5
#16 0x00007fb1503a7184 in start_thread (arg=0x7fb11c55e700) at pthread_create.c:312
#17 0x00007fb14dda8ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by ElLamparto** [comment]
In AV settings I set Experimental, made a call, the echo was still there.
Then qTox crashed at every startup until I set qtox.ini: enableBackend2=false.

qTox v1.14.0-13-gacea7c3
Win7 32bit

[qtox.log.zip](https://github.com/qTox/qTox/files/1837089/qtox.log.zip)

**Comment by sudden6** [comment]
@ElLamparto The commit hash in this log indicates you built from master and not from this PR, can you verify you actually tested this PR?

**Comment by ElLamparto** [comment]
@sudden6, you are right, I used master. How to build from this PR (on Linux)? Thanks...

**Comment by sudden6** [comment]
@ElLamparto you can use `./test-pr.sh 4915` in the root of this repo to check out this PR.

**Pull request closed without merging**
