### PR TITLE
fix: use only well known categories in the desktop file

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4836)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4836#-:-Kzorhg9IgN9H6TsRQhw:b-jbsf8z)*

**Comment by tox-user** [comment]
Version 1.0? :)
https://github.com/sudden6/qTox/blob/4d36c23c9ba88a350a9b7ae6a7657fda3b8a2af2/qtox.desktop#L2

**Comment by sudden6** [comment]
@tox-user it's not the version of the application but rather the version of the file specification according to https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by tox-user** [comment]
I see. I thought it was the version of the app.

**Comment by sudden6** [comment]
I also had to look that one up very quick ;)

**Pull request merged**
