### PR TITLE
fix(ui): Set tooltip colour and background for all tooltips

### LINKED ISSUE #4667: Ubuntu tooltips for emoji, file attach, and send are solid black
##### Brief Description

OS: Ubuntu 16.04 Unity
Commit hash:  6a5a7564
Qt: 5.5.1

Reproducible: Always

##### Steps to reproduce

1. Hover any of the bottom right buttons

##### Observed Behavior
tooltip

This is probably another CSS issue like #4641. Could be a clash between our custom CSS and theme default CSS. Is the goal to have our CSS follow system theme, or our styling be consistent across themes? Currently it seems like most of our CSS defines absolute colours regardless of theme.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4667

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4748)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 3 of 4 files at r1.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/widget.cpp, line 2152 at r1](https://reviewable.io:443/reviews/qtox/qtox/4748#-Kwy7HlF7q8jzHxzt1PW:-Kwy7HlGvOAL4iHZhn_H:bwqua9r) ([raw file](https://github.com/qtox/qtox/blob/3252d811cef2c92d483fd4765ce8a7bde1dcd665/src/widget/widget.cpp#L2152)):*
> ```cpp
> void Widget::reloadTheme()
> {
> 	this->setStyleSheet(Style::getStylesheet(":/ui/window/general.css"));
> ```

use spaces instead of tab

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4748)*

**Comment by Talkless** [comment]
Could reproduce. No problems with fix on Ubuntu 16.04 or Debian 9 with KDE.

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4748#-:-KwzMoLk3q9vL8CXOime:bssz25b)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4748#-:-KwzMwHX-l3swT8RvyyD:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/widget/widget.cpp, line 2152 at r1](https://reviewable.io:443/reviews/qtox/qtox/4748#-Kwy7HlF7q8jzHxzt1PW:-Kx02z09aXrhi4hG0HSB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3252d811cef2c92d483fd4765ce8a7bde1dcd665/src/widget/widget.cpp#L2152)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use spaces instead of tab
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4748)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4748#-:-Kx2mN8IIug6NB-qV2lB:b-jbsf8z)*

**Pull request merged**
