### PR TITLE
chore(font): update default font and add its license

### LINKED ISSUE #2158: Stress sign (diacritic mark) is stripped in pasted text
I tried to paste the word "коне́чно", but the mark gets stripped.

### PR DESCRIPTION
**Pull request by sudden6**
Besides not violating the license, it may fix https://github.com/qTox/qTox/issues/2158

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4209)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[res/LICENSE, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4209#-KdukoBCIR59gZrxXA3X:-KdukoBCIR59gZrxXA3Y:b-j8no5u) ([raw file](https://github.com/qtox/qtox/blob/f1903fb4cba953ba9cd2698698b28799ed8475ae/res/LICENSE#L1)):*
> ```
> Fonts are (c) Bitstream (see below). DejaVu changes are in public domain.
> ```

Since it applies only to the font, it should be placed in a separate directory along with the font.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209)*

**Comment by sudden6** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[res/font/LICENSE, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4209#-KdukoBCIR59gZrxXA3X:-Kdur528Y8Q5SsDyLm2g:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f1903fb4cba953ba9cd2698698b28799ed8475ae/res/font/LICENSE#L1)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Since it applies only to the font, it should be placed in a separate directory along with the font.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209)*

**Comment by zetok** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 214 at r2](https://reviewable.io:443/reviews/qtox/qtox/4209#-Kdv-k15TX7dQSjxRFJW:-Kdv-k15TX7dQSjxRFJX:bnsls4h) ([raw file](https://github.com/qtox/qtox/blob/f9e233116d01b11da2e36caffc13b908992f4d91/src/main.cpp#L214)):*
> ```cpp
> 
>     // Install Unicode 6.1 supporting font
>     if(QFontDatabase::addApplicationFont("://font/DejaVuSans.ttf") == -1) {
> ```

missing space between `if` and parenthesis

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209)*

**Comment by sudden6** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 214 at r2](https://reviewable.io:443/reviews/qtox/qtox/4209#-Kdv-k15TX7dQSjxRFJW:-Kdv1W1QHqK6EuF4fhW1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f9e233116d01b11da2e36caffc13b908992f4d91/src/main.cpp#L214)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

missing space between `if` and parenthesis
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209)*

**Comment by Diadlo** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 214 at r2](https://reviewable.io:443/reviews/qtox/qtox/4209#-Kdv-k15TX7dQSjxRFJW:-Kdv8idxxyqlyFnSBFwU:b-t6ujl) ([raw file](https://github.com/qtox/qtox/blob/f9e233116d01b11da2e36caffc13b908992f4d91/src/main.cpp#L214)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Are you sure, that path here shouldn't be equal to alias of resource?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209)*

**Comment by zetok** [comment]
#2158 is still not fixed

**Comment by sudden6** [comment]
@zetok if you know the unicode code of that sign you could check if the font has it https://dejavu-fonts.github.io/ or we maybe should provide another default font.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main.cpp, line 214 at r2](https://reviewable.io:443/reviews/qtox/qtox/4209#-Kdv-k15TX7dQSjxRFJW:-KdvGA7O8AaIvfls-okm:b6ksie0) ([raw file](https://github.com/qtox/qtox/blob/f9e233116d01b11da2e36caffc13b908992f4d91/src/main.cpp#L214)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Are you sure, that path here shouldn't be equal to alias of resource?
</blockquote></details>

yes, the alias is only for the filename, and the `font/` path is always added.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209#-:-KdvHymfS3WrDl09GVE8:beqou7o)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4209#-:-KdvL4htCuwjySLHgE1l:b-jbsf8z)*

**Comment by zetok** [comment]
http://graphemica.com/search?q=%D0%B5%CC%81
http://graphemica.com/0301
http://graphemica.com/%D0%B5

**Comment by sudden6** [comment]
@zetok they are both in https://raw.githubusercontent.com/dejavu-fonts/dejavu-fonts/master/status.txt and supported, the problem must be somewhere else then...

**Pull request merged**
