### PR TITLE
Themes - updated

### PR DESCRIPTION
**Pull request by agilob**
WHAT DOES IT HAVE?
EVERYTHING WHAT  https://github.com/tux3/qTox/pull/1640 HAS + MORE:
- fixed css for wombat (tpyos)
- applied css for chat!
- reloading style without restarting app
- code formatting in some places
- CSS formatting
- merging to recent changes in qtox
- compiles now!
  nothing meaningful, just A LOT of small changes sorry about that, I lost track of time. I'm also sorry about those commit messages. first commit `2` includes all commit from old branch, nothing more, nothing less.

WHY?!
I had really bad time merging and updating code after recent changes, so I made .patch from https://github.com/tux3/qTox/pull/1640 and checrry-picked it to this branch, it was just much easier to manage +100 git conflicts! 

Themes:
light

Style is not perfect and I know it. Please keep in mind this is my FIRST EVER experience with CSS. There are shortcomings.

If you know css better than me (you probably do!) please fix it.

@tux3 if you think it's "good enough" please merge it before code conflicts again so I don't have to spend even more hours on solving them, I also won't have much time to fix issues soon.

### CODE REVIEW

**Comment by zetok** [comment]
Could you squash 16fff0642aa28c0358aa7502a639c779f4124666 with previous one?

Aside from that, content of conversation is unreadable, since black letters blend with grey background

**Comment by agilob** [comment]
I cant find any way to change it to value from css, I can change it to system default color, but it doesn't make much sense. I need help from @krepa098.

**Comment by agilob** [comment]
Current problem: background color and dot color of typing notification and spinner are defined in SVG not by palette or css.

**Comment by DanTheBritish** [comment]
Pretty sure that SVG fill colours can be set by external CSS (They can be within HTML, not sure about how QT does it though)

**Comment by agilob** [comment]
@LapFox I really need help with this to polish everything :P If you could give it a try it would help a lot

**Comment by DanTheBritish** [comment]
I've cloned your branch, if I have any success then I'll send you a pull request over there :metal:

**Comment by tritium21** [comment]
Your theme procrastination is blocking progress on accessibility issues.  Make it an ugly blank page so they can put a very much needed FONT SIZE control in, then come back to it.

Basically, anyone with a little bit of vision difficulty cant use your program, and you are sitting here talking about gradients.  Get your priorities straight.

**Comment by tux3** [comment]
@tritium21 

I think we can all agree that accessibility is important, we have to think of color blind people, vision difficulties, people who can't get qTox at all because there hasn't been a working build for their platform in the past month. Those issues all matter to a different set of people, and they will all be addressed eventually.

Now I'm happy to know you have specific priorities, but merely complaining is a very limited contribution. 
Feel free to do the work yourself and send a pull request for review if you think we're procrastinating.

This is a volunteer project, and it moves at volunteer pace.

**Comment by agilob** [comment]
@tritium21 lel, I myself have vision difficulties. Chat area was coded to gain maximum performance and a lot of data is hardcoded to get max. performance while rendering text and columns. It's based on abstract qt classes that do not support CSS or HTML so it's difficult to change it without rewriting 3/4 of that code and losing performance. I don't have much time now, I've been in travel for last 4 days (sleeping on airport and train stations), I've just gratuated and had to move to another city ~300km away, sorry that I don't have time to finish it, but currently I have different priorities.

**Comment by agilob** [comment]
@tux3 I updted my branch, it's ready to merge. Setting to change theme is hidden currently, but all code responsible for it is attached. I think this can be safely merged. A lot of code for styling Windows/OSX was removed so let's see how it behaves now (removed code is commented out). Only light theme is enabled atm, if you want to test wombat/darkblue change it in your .ini.

Feature isn't ready, but it will allow me avoiding gigantic merge conflicts in the future. 

Current problems:
- change font colour in text-area from CSS. 
- change background OR shape colour in SVGs (spinning circle, typing notification dots).

If no one is against this tmp solution, please merge it.

**Comment by tux3** [comment]
@agilob This PR doesn't build for me:

```
src/widget/form/settings/generalform.cpp:20:32: fatal error: ui_generalsettings.h: No such file or directory
```

**Comment by tritium21** [comment]
Do you have benchmarks showing that text rendering speed is an actual problem?  Does text render one character at a time without your performance boosts?  Text rendering performance is sufficient with pretty much everything ever written without optimizing it (caveat: unless the thing you are writing is a GUI framework itself, that's when you put in the effort).  Rip out your performance 'enhancements'.  It does not matter to a human if rendering takes 0.1s or 0.01ms.

**Comment by agilob** [comment]
@tritium21: @zetok did performance testing https://github.com/tux3/qTox/issues/266 https://github.com/tux3/qTox/pull/974

@tux3 `make clean && rm Makefile && qmake && make`? I renamed ui_generalform to ui_generalsettings. This file is automatically generated by qmake.

**Comment by tux3** [comment]
@agilob I did.

I tried `make distclean && qmake && make` in the git tree, I tried `rm -rf * && qmake && make` in a separate empty build folder, but no dice.

**Comment by agilob** [comment]
ok, sorry, my bad. It's fixed now.

Silent build looks like this:

```
➜  Qtox git:(themess) ✗ make
compiling src/platform/autorun_win.cpp
compiling src/platform/autorun_xdg.cpp
compiling src/platform/autorun_osx.cpp
```

**Comment by tux3** [comment]
And of course now it conflicts with master :)

**Comment by agilob** [comment]
Russian translation.

**Comment by tux3** [comment]
I can't take silent builds, though. If a build breaks it really helps to have the full compiler invocation.

**Comment by agilob** [comment]
Silent build cuts successful lines, compilation errors stay the same:

```
compiling src/widget/form/settings/avform.cpp
src/widget/form/settings/avform.cpp: In constructor 'AVForm::AVForm(SettingsWidget*)':
src/widget/form/settings/avform.cpp:47:13: error: 'class Ui::AVSettings' has no member named 'setupi'
     bodyUI->setupi(this);
             ^
src/widget/form/settings/avform.cpp: At global scope:
src/widget/form/settings/avform.cpp:43:34: warning: unused parameter 'parent' [-Wunused-parameter]
   AVForm::AVForm(SettingsWidget *parent) :  GenericForm(QPixmap(":/img/settings/av.png")),
                                  ^
Makefile:2770: recipe for target 'avform.o' failed
```

**Comment by tux3** [comment]
I often need the compiler invocation though. The command line that was used to compile/link.

**Comment by agilob** [comment]
Ok, do you want me to revert it? Can you solve the conflict on your side?

**Comment by tux3** [comment]
Please revert it. I looked at the conflicts, and it seems really messy :

ss016

Did you actually commit merge conflicts in the history without resolving them?

**Comment by agilob** [comment]
on my side only Russian translation conflicted.

**Comment by tux3** [comment]
Okay, thanks.

**Comment by tux3** [comment]
So it seems to mostly work, but there are still some glitches with the default theme.

ss018

ss019

I've only tested quickly on Debian for now, there's a lot of missing borders, some backgrounds turned to dark gray, and the option for changing the Qt style is still there but doesn't seem to do anything anymore.

**Comment by agilob** [comment]
I'll try to fix it today.

**Comment by agilob** [comment]
Not sure if this is better?
snapshot3
snapshot4

Your settings panel should look completely differently oO
snapshot5

**Comment by ProMcTagonist** [comment]
That theme is quite ugly. If that's the new default it needs a makeover by a designer like @itsDuke.

**Comment by agilob** [comment]
Any one who knows css should fix it ;) It's my first try

**Comment by SkyzohKey** [comment]
When i have time, I'll propose mockups for improving the default theme ;)

**Comment by agilob** [comment]
feel free to push directly to my branch.

**Comment by ProMcTagonist** [comment]
Do changes require recompilation?

**Comment by agilob** [comment]
Yes, it takes a few seconds. currently 3 themes: light.css, wombat.css and darkblue.css are hardcoded. I can make it load from file later.

**Comment by ProMcTagonist** [comment]
When hovering over the Language combobox in general settings, the hint is cut off.

broken hovertext

@agilob which one is the default? light?

**Comment by agilob** [comment]
> First try in CSS ;_;

**Comment by ProMcTagonist** [comment]
@agilob Mine too. https://github.com/agilob/qTox/pull/1

**Comment by ProMcTagonist** [comment]
@agilob Mine too. https://github.com/agilob/qTox/pull/1

**Comment by ProMcTagonist** [comment]
Action text isn't blue. Changing group titles appears to be broken too. Are other people experiencing these?

**Comment by agilob** [comment]
Fixed, we can "style" fonts now in chat area :)

**Comment by SkyzohKey** [comment]
Any news about this pr ?

**Comment by agilob** [comment]
I have a full time job now, but I hope to move forward this PR a bit this week.

**Comment by agilob** [comment]
@tux3  I made some changes:
- added original css theme (from current tux3/master) and it's enabled as default
- other themes are included but to change to them user must edit .ini file
- fixed problem with white font on white background in dark system themes (2032) by adding new css file

I think this is safe to merge as all users will user current theme, theme changer is disabled.
I am going to ask my coworker if he could spend some time on CSS.

I would say it's safe to merge now, as there should be no difference before and after this PR is merged (some minor changes like order of checkboxes in general settings and new disabled combobox).

 @SkyzohKeyx  @zetok could you test it on your computers?

**Comment by hexafluoride** [comment]
@tux3 is on a trip @agilob I'm sorry to be the one to tell you

**Comment by stal888** [comment]
I'm sorry for your loss, @agilob.

**Comment by agilob** [comment]
no worries, we all deserve breaks

**Comment by SkyzohKey** [comment]
@agilob, i'll test it when i'll got a little time ;)

**Comment by agilob** [comment]
Will anyone be able to review and merge it once I fix conflict and improve commits?

**Comment by suhr** [comment]
Let @SkyzohKeyx review the CSS and @TheSpiritXIII review the code.

**Comment by ProMcTagonist** [comment]
@itsDuke should review the design, as well, @suhr.

**Comment by suhr** [comment]
He doesn't seem to be active.

**Comment by ItsDuke** [comment]
@suhr I'm here, I just don't have a way of viewing them.

**Comment by SkyzohKey** [comment]
It would be more simple to uses Less or Sass to generate the CSS files. Like that you would just have to modify the variables.less/.sass/.scss to make new themes without having to modify the whole code.

**Comment by antis81** [comment]
@SkyzohKeyx :) - Not too long ago, I wrote a little parser to handle "dynamic" CSS - powerful enough, but not as powerful as less/sass. @scunz remeber? :smile: - maybe we should make this a part of `libHeaven`

**Comment by agilob** [comment]
Any point in trying to implement this 3rd time? Will anyone review and test the code this time?

**Comment by tux3** [comment]
@agilob Unfortunately, it looks like the merge conflicts were never really resolved and now it's getting really unmergeable :/
If you want, feel free to fix the conflicts and send it again. I'll be happy to look at it, but I remember there were quite a lot of places where the CSS style didn't look like the native style, and it looked very weird on some OS/distros. I don't know how easy it is to fix. Maybe it would be easier to use a different approach to changing the color scheme without loosing the native look & feel, because it looks like the current implementation of Themes is pretty complex.

**Comment by agilob** [comment]
Yeah, it's complex mostly because of people hardcoding css in cpp files or .ui ;/

**Pull request closed without merging**
