### PR TITLE
Simplified ifdefs in camera handling: made them USING_V4L to be explicit.

### PR DESCRIPTION
**Pull request by yurivict**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4121)

### CODE REVIEW

**Comment by Diadlo** [comment]
Please, update commit message to satisfy [format](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format)

**Comment by yurivict** [comment]
renamed

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4121#-:-Kc1gxktwsCNUhzAxHGk:b-jbsf8z)*

**Comment by Diadlo** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/video/cameradevice.cpp, line 31 at r1](https://reviewable.io:443/reviews/qtox/qtox/4121#-KcDjBWhEkA9SnFutheW:-KcDjBWhEkA9SnFutheX:b-kljdgb) ([raw file](https://github.com/qtox/qtox/blob/0ec6afa2014e6aaeee759fe5cdbbcadfed3634ee/src/video/cameradevice.cpp#L31)):*
> ```cpp
> #include "src/persistence/settings.h"
> 
> #if defined(Q_OS_LINUX) || defined(Q_OS_FREEBSD)
> ```

I think, better use
`#define USING_V4L defined(Q_OS_LINUX) || defined(Q_OS_FREEBSD)`
Or add `#else`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4121#-:-KcDjJPONXS6Y4dEFXF9:b8b79qu)*

**Comment by yurivict** [comment]
changed

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4121#-:-KcEoWkN9vuvvxFj2WDP:b-jbsf8z)*

**Pull request merged**
