### PR TITLE
fix: Fix problem with unicode symbols on FreeBSD

### LINKED ISSUE #4012: [Regression] Russian letters in profiles names
##### Brief Description

OS: FreeBSD 11.0
qTox version: 1.6.0  
Commit hash:  
toxcore:  0.160924
Qt:  5.6.2
Hardware:  i386 and amd64

Reproducible: Always

##### Steps to reproduce

1. Install qTox 1.5
2. Create profile with russian letters
3. Update qTox to 1.6

1. Install qTox 1.6
2. Create profile with russian letters

##### Observed Behavior
Don't show russian letters in profiles names.
Profiles created in qTox 1.6 look in the file system like "????.db".

##### Expected Behavior
Show russian letters! And create files with correct names in file system like was with qTox 1.5.

##### Additional Info
http://217.26.10.138/vvd/qtox160_russian.png

$ qtox 
[22:32:23.944 UTC] persistence/settings.cpp:137 : Debug: "Loading settings from /home/vvd/.config/tox/qtox.ini"
[22:32:24.051 UTC] widget/translator.cpp:56 : Debug: Loaded translation "ru"
[22:32:24.051 UTC] widget/translator.cpp:69 : Debug: System translation not loaded "ru"
[22:32:24.052 UTC] ipc.cpp:59 : Debug: Our global IPC ID is  16264608118004039845
[22:32:24.055 UTC] main.cpp:210 : Debug: built on:  00:29:57 Dec 26 2016 ( 1482701312 )
[22:32:24.055 UTC] main.cpp:211 : Debug: commit:  n/a 

[22:32:24.055 UTC] nexus.cpp:85 : Debug: Starting up
[22:32:28.006 UTC] persistence/profile.cpp:624 : Warning: Couldn't open tox save  "/home/vvd/.config/tox/��������������1.tox"
[22:32:30.179 UTC] persistence/profile.cpp:117 : Debug: Loading tox save  "/home/vvd/.config/tox/��������������1.tox"
[22:32:30.179 UTC] persistence/profile.cpp:121 : Warning: The tox save file  "/home/vvd/.config/tox/��������������1.tox"  was not found

The name of this profile is "Русский1".

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4012 
@VVD Can you test it?
Also, you can add me in tox: diadlo@toxme.io

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4019)

### CODE REVIEW

**Comment by VVD** [comment]
This patch fixed the issue.

**Review by sudden6 — APPROVED** [review]

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.cpp, line 96 at r2](https://reviewable.io:443/reviews/qtox/qtox/4019#-K_4F70B9T-QiHLsPZYY:-K_4F70CTxcs9OvUkbeB:b-sic8kp) ([raw file](https://github.com/qtox/qtox/blob/047e887a923af80904093db434e0118e314e2763/src/persistence/smileypack.cpp#L96)):*
> ```cpp
>     location = QStandardPaths::AppDataLocation;
> #else
>     location = QStandardPaths::DataLocation;
> ```

can you add a warning here that this could break Unicode on UNIX platforms, so we know where to look the next time? ;)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4019)*

**Comment by Diadlo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.cpp, line 96 at r2](https://reviewable.io:443/reviews/qtox/qtox/4019#-K_4F70B9T-QiHLsPZYY:-K_6HPc2uBs6VxXr3pk-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/047e887a923af80904093db434e0118e314e2763/src/persistence/smileypack.cpp#L96)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can you add a warning here that this could break Unicode on UNIX platforms, so we know where to look the next time? ;)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4019)*

**Comment by sudden6** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4019#-:-K_6IuLt_MLLglQtz7NO:bnfp4nl)*

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4019#-:-K_6OeaY6TVqBBEyV6yP:bnfp4nl)*

**Pull request merged**
