### PR TITLE
Fix incorrect groupname, group invite form refactored and added docs for it

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4194)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/groupinvite.h, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdawhbXmLhPNioIU_R7:-KdawhbYDpzwu-tJctYU:b53d2th) ([raw file](https://github.com/qtox/qtox/blob/757eca70a1a27456d7205f194752fd950eaf0783/src/groupinvite.h#L1)):*
> ```objc
> #ifndef GROUPINVITE_H
> ```

missing copyright header

---

*[src/widget/form/groupinvitewidget.h, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4194#-Kdawniew0GLZTQqjSMs:-KdawnifFagcgxSOniOX:b53d2th) ([raw file](https://github.com/qtox/qtox/blob/757eca70a1a27456d7205f194752fd950eaf0783/src/widget/form/groupinvitewidget.h#L1)):*
> ```objc
> #ifndef GROUPINVITEWIDGET_H
> ```

missing copyright header

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4194)*

**Comment by zetok** [comment]
> `doc: …`

Should be `docs: …`

**Comment by noavarice** [comment]
Done

---

Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/groupinvite.h, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdawhbXmLhPNioIU_R7:-KdaydLu0UjETXcE0EZ6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/757eca70a1a27456d7205f194752fd950eaf0783/src/groupinvite.h#L1)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

missing copyright header
</blockquote></details>

Done.

---

*[src/widget/form/groupinvitewidget.h, line 1 at r1](https://reviewable.io:443/reviews/qtox/qtox/4194#-Kdawniew0GLZTQqjSMs:-KdayhofUcpy_enxbEBy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/757eca70a1a27456d7205f194752fd950eaf0783/src/widget/form/groupinvitewidget.h#L1)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

missing copyright header
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4194#-:-Kdayxfy63QMqkx8il0t:bb6un1j)*

**Comment by Diadlo** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/groupinvite.cpp, line 28 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbQUv3rx0Jd0_IYzzh:-KdbQUv4DXyfS5lnQbde:b-c1i1e8) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/groupinvite.cpp#L28)):*
> ```cpp
>  */
> 
> GroupInvite::GroupInvite(const int32_t FriendId, const uint8_t Type, const QByteArray& Invite)
> ```

1) parameters should start with lowercase letter
2) `const` for parameters sent by value is excessively

---

*[src/groupinvite.cpp, line 29 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbPTNw06oQLcVcxb04:-KdbPTNxwneyzed1-Azn:bpuprlq) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/groupinvite.cpp#L29)):*
> ```cpp
> 
> GroupInvite::GroupInvite(const int32_t FriendId, const uint8_t Type, const QByteArray& Invite)
>     : friendId(FriendId), type(Type), invite(Invite), date(QDateTime::currentDateTime())
> ```

We don't have strict rule about initialize list format, but we use rule: one per line (like with variable declaration)
Also, please, use C++11 feature init by init list (`friendId{friendId}`)

---

*[src/widget/form/groupinviteform.cpp, line 31 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbR7gWU101EI4f8hpY:-KdbR7gWU101EI4f8hpZ:b-9a5pz9) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/widget/form/groupinviteform.cpp#L31)):*
> ```cpp
> 
> #include <algorithm>
> #include <tox/tox.h>
> ```

Non-project and non-qt includes should goes in the end

---

*[src/widget/form/groupinviteform.cpp, line 56 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbRx7WlgP6Du8nw3Zx:-KdbRx7WlgP6Du8nw3Zy:b-8mxnto) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/widget/form/groupinviteform.cpp#L56)):*
> ```cpp
> {
>     QVBoxLayout* layout = new QVBoxLayout(this);
>     connect(createButton, &QPushButton::clicked, [=]()
> ```

Why do you change `this` on `=`?
IDK how compiler implement it, but if it gets all variables from the context it's more expensive

---

*[src/widget/form/groupinviteform.cpp, line 123 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbScy6QleABnKThg5h:-KdbScy6QleABnKThg5i:b5gfwvo) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/widget/form/groupinviteform.cpp#L123)):*
> ```cpp
> void GroupInviteForm::addGroupInvite(int32_t friendId, uint8_t type, QByteArray invite)
> {
>     GroupInviteWidget* addingInviteWidget = new GroupInviteWidget(this, GroupInvite(friendId, type, invite));
> ```

I think, in current context `addingInviteWidget` can be replaced on `widget`. But feel free to leave it
(My rule: long name for wide scope, short name for small scope)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4194)*

**Comment by noavarice** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/groupinvite.cpp, line 28 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbQUv3rx0Jd0_IYzzh:-KdbZ17HyShrSLlX3fmR:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/groupinvite.cpp#L28)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

1) parameters should start with lowercase letter
2) `const` for parameters sent by value is excessively
</blockquote></details>

Done.

---

*[src/groupinvite.cpp, line 29 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbPTNw06oQLcVcxb04:-KdbZ1tAuRV5Znf8kc8v:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/groupinvite.cpp#L29)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

We don't have strict rule about initialize list format, but we use rule: one per line (like with variable declaration)
Also, please, use C++11 feature init by init list (`friendId{friendId}`)
</blockquote></details>

Done.

---

*[src/widget/form/groupinviteform.cpp, line 31 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbR7gWU101EI4f8hpY:-KdbZHQE0DOQloA5DZ-a:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/widget/form/groupinviteform.cpp#L31)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Non-project and non-qt includes should goes in the end
</blockquote></details>

Done.

---

*[src/widget/form/groupinviteform.cpp, line 56 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbRx7WlgP6Du8nw3Zx:-Kdb_O6HHmo91s65MrCn:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/widget/form/groupinviteform.cpp#L56)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why do you change `this` on `=`?
IDK how compiler implement it, but if it gets all variables from the context it's more expensive
</blockquote></details>

Done.

---

*[src/widget/form/groupinviteform.cpp, line 123 at r2](https://reviewable.io:443/reviews/qtox/qtox/4194#-KdbScy6QleABnKThg5h:-Kdb_uOeDWNuJHORdQTi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60fb26ed4bbbb889ecbf17a83ac3ffabe3aac8b1/src/widget/form/groupinviteform.cpp#L123)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, in current context `addingInviteWidget` can be replaced on `widget`. But feel free to leave it
(My rule: long name for wide scope, short name for small scope)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4194)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4194#-:-KdbdPjTy1m8enxaYCou:b-jbsf8z)*

**Pull request merged**
