### PR TITLE
Interface signals without inheriting from QObject

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5545)

### CODE REVIEW

**Comment by Diadlo** [comment]
Why did you remove headers from CMakeLists.txt?

**Comment by anthonybilinski** [comment]
AFAIK the headers listed serve no purpose. The list of sources is only used for the [add_library](https://cmake.org/cmake/help/v3.5/command/add_library.html#id2) call to create our static lib, which "Adds a library target called <name> to be built from the **source** files listed in the command invocation" according to docs. Removing them seems to have no negative effect.

**Comment by sudden6** [comment]
One difference I notice with that PR is, that qtcreator now shows the headers in a different location in the project view. Not sure if that matters (doesn't for me) or changes anything else.

**Comment by Diadlo** [comment]
It isn't true. Some IDEs (at least Visual Studio) show project files only described in CMakeLists.txt. So if you remove it users will not able to open headers with VS

**Comment by anthonybilinski** [comment]
Ok good point. I've updated the PR to not remove headers from the sources list, but the other work I did to enable removing the headers, namely using our `interface.h` macros for interface signals without inheriting from QObject, still seems correct, so I've updated the PR to only contain that part.

This would allow us to compile without the headers in the sources list, if wanted.

**Comment by anthonybilinski** [comment]
Closed and re-opened PR to regenerate merge for travis check, so fixed travis config on the target branch can be used.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5545#-:-M-S5j5G2x1fTuL2uQF4:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by sudden6 — APPROVED** [review]
> Reviewed 12 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5545)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
