### PR TITLE
closes tux3/qtox#988

### PR DESCRIPTION
**Pull request by agilob**
@suhr #752
@TheLastProject #988
groupchat

### CODE REVIEW

**Comment by agilob** [comment]
>  closes tux3/qtox#**988 #989** 

co close :<

**Comment by agilob** [comment]
Ignore this PR, I commited changes in *.ts -.-'

**Comment by suhr** [comment]
> Ignore this PR, I commited changes in *.ts -.-'

You can use rebase to fix such problems without creating a new PR.

**Comment by dubslow** [comment]
Additionally, I have this very useful alias:

`alias tsclear="git checkout -- ~/qtox/translations/*.ts"`

**Pull request closed without merging**
