### PR TITLE
[Refactor] genericchatform css

### PR DESCRIPTION
**Pull request by Diadlo**
It was part of #4768 but I miss it somehow before merge :/

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4804)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 13 of 15 files at r1.
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/chatformheader.cpp, line 79 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KytlLCrh3qOx1pc3SwM:-KytlLCsRRTTnQ3BZW-Y:b-q5w3nq) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L79)):*
> ```cpp
> };
> 
> template <class T, class Fun>
> ```

I'm not 100% sure this is possible, but I think it would be good to limit the `T` class of the template to `QAbstractButton` because it won't work with anything that doesn't implement the interfaces.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4804)*

**Comment by Diadlo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/chatformheader.cpp, line 79 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KytlLCrh3qOx1pc3SwM:-KytwNcdca-o0mk-g-MV:bfl82sj) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L79)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I'm not 100% sure this is possible, but I think it would be good to limit the `T` class of the template to `QAbstractButton` because it won't work with anything that doesn't implement the interfaces.
</blockquote></details>

It's exactly how templates works. If you will try to compile this code with T, which doesn't provide used functions you will have an error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4804)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 15 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/chatformheader.cpp, line 79 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KytlLCrh3qOx1pc3SwM:-KyuHUGlZCyH5kFWn8GH:b-iz2ipe) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L79)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

It's exactly how templates works. If you will try to compile this code with T, which doesn't provide used functions you will have an error.
</blockquote></details>

ok, thank you for the info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4804#-:-KyuH_JxdEfdVj7Q4hDA:b-jbsf8z)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/widget/chatformheader.cpp, line 86 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KyvE8rqDYDD1jTLFVvG:-KyvE8rqDYDD1jTLFVvH:b-v6ok3d) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L86)):*
> ```cpp
>     btn->setAttribute(Qt::WA_LayoutUsesWidgetRect);
>     btn->setObjectName(name);
>     const QString& path = QStringLiteral(":/ui/chatFormHeader/buttons.css");
> ```

Can make it `static` or move out of function

---

*[src/widget/chatformheader.cpp, line 88 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KyvELfRq-ojoNID8J_6:-KyvELfRq-ojoNID8J_7:b-6sm20j) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L88)):*
> ```cpp
>     const QString& path = QStringLiteral(":/ui/chatFormHeader/buttons.css");
>     btn->setStyleSheet(Style::getStylesheet(path));
>     QObject::connect(btn, &QAbstractButton::clicked, self, slot);
> ```

Maybe `onClickSlot`, more clear to read

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4804#-:-KyvG_yndDBWqr5KmPWx:b-jbsf8z)*

**Comment by Diadlo** [comment]
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/widget/chatformheader.cpp, line 86 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KyvE8rqDYDD1jTLFVvG:-Kyvlh-xfaoUKvMv9hGA:by0pdi3) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L86)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Can make it `static` or move out of function
</blockquote></details>

Extracted to namespace

---

*[src/widget/chatformheader.cpp, line 88 at r1](https://reviewable.io:443/reviews/qtox/qtox/4804#-KyvELfRq-ojoNID8J_6:-KyvljUlxHcEiUUc503g:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/31ffdfe81af32c815e899ba142a1b99a3a895d67/src/widget/chatformheader.cpp#L88)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Maybe `onClickSlot`, more clear to read
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4804)*

**Pull request merged**
