### PR TITLE
refactor(audio): introduce IAudioSource interface and use it

### PR DESCRIPTION
**Pull request by sudden6**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

This is the second part of #5240 and finally makes the audio subsystem independent.

I plan to reflect this independence in a future PR by moving it to a cmake subproject.

@Diadlo can you review this since you also reviewed the other PR?

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5641)

### CODE REVIEW

**Review by Diadlo — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5641)* status: 0 of 1 LGTMs obtained

___
*[src/audio/backend/alsource.h, line 15 at r1](https://reviewable.io/reviews/qtox/qtox/5641#-Le2WuF10Yz5h7RsEcRV:-Le2WuF10Yz5h7RsEcRW:b-3qou1f) ([raw file](https://github.com/qtox/qtox/blob/ee6dc2b682e6e7717d8174dac64308d531ebdb53/src/audio/backend/alsource.h#L15)):*
> ```objc
>     AlSource(OpenAL& al);
>     AlSource(AlSource &src) = delete;
>     AlSource & operator=(const AlSource&) = delete;
> ```

Please, reformat
___
*[src/audio/backend/openal.cpp, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5641#-Le2X8bc1dsveT8seY_L:-Le2X8bc1dsveT8seY_M:b-za99im) ([raw file](https://github.com/qtox/qtox/blob/ee6dc2b682e6e7717d8174dac64308d531ebdb53/src/audio/backend/openal.cpp#L330)):*
> ```cpp
> 
>     auto const source = new AlSource(*this);
>     if (source == nullptr) {
> ```

Do we enforce noexcept-way somehow? If no, `new` never returns `nullptr`, it throws the `std::bad_alloc`
___
*[src/audio/backend/openal.cpp, line 351 at r1](https://reviewable.io/reviews/qtox/qtox/5641#-Le2XypTEdPZCk0XLqP8:-Le2XypTEdPZCk0XLqP9:bt62ul8) ([raw file](https://github.com/qtox/qtox/blob/ee6dc2b682e6e7717d8174dac64308d531ebdb53/src/audio/backend/openal.cpp#L351)):*
> ```cpp
> 
>     const auto s = sources.find(&source);
>     if(s == sources.end()) {
> ```

Format

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5641)* status: 0 of 1 LGTMs obtained

___
*[src/audio/backend/alsource.h, line 15 at r1](https://reviewable.io/reviews/qtox/qtox/5641#-Le2WuF10Yz5h7RsEcRV:-Le3_WbH468GX5IkEp_G:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ee6dc2b682e6e7717d8174dac64308d531ebdb53/src/audio/backend/alsource.h#L15)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Please, reformat
</blockquote></details>

Done.
___
*[src/audio/backend/openal.cpp, line 330 at r1](https://reviewable.io/reviews/qtox/qtox/5641#-Le2X8bc1dsveT8seY_L:-Le3ZCcc6Dr9hF_GEAMM:b-6pqflp) ([raw file](https://github.com/qtox/qtox/blob/ee6dc2b682e6e7717d8174dac64308d531ebdb53/src/audio/backend/openal.cpp#L330)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Do we enforce noexcept-way somehow? If no, `new` never returns `nullptr`, it throws the `std::bad_alloc`
</blockquote></details>

yes, we pass ` -fno-exceptions` as compiler flag
___
*[src/audio/backend/openal.cpp, line 351 at r1](https://reviewable.io/reviews/qtox/qtox/5641#-Le2XypTEdPZCk0XLqP8:-Le3_ZYu8mlKW6ktO2gN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ee6dc2b682e6e7717d8174dac64308d531ebdb53/src/audio/backend/openal.cpp#L351)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Format
</blockquote></details>

Done.

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 13 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5641#-:-Le59tST3eHkN95ZiZQm:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/toxcall.cpp, line 108 at r2](https://reviewable.io/reviews/qtox/qtox/5641#-Le59PPACah-NFLct7Gc:-Le59PPACah-NFLct7Gd:b-qgdgwn) ([raw file](https://github.com/qtox/qtox/blob/00c3254f4019916c2769e39efccef29a3803bc06/src/core/toxcall.cpp#L108)):*
> ```cpp
>     , friendId{FriendNum}
> {
>     // TODO(sudden6): move this to audio source
> ```

I'm not sure, that this should be in the audio source. I think the audio source shouldn't know about `ToxAV`

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5641)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/toxcall.cpp, line 108 at r2](https://reviewable.io/reviews/qtox/qtox/5641#-Le59PPACah-NFLct7Gc:-Le6bQtQ9QwPOUxHeqzu:bo8iy86) ([raw file](https://github.com/qtox/qtox/blob/00c3254f4019916c2769e39efccef29a3803bc06/src/core/toxcall.cpp#L108)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I'm not sure, that this should be in the audio source. I think the audio source shouldn't know about `ToxAV`
</blockquote></details>

this was actually a stale comment from the development phase, removed it.

**Pull request merged**
