### PR TITLE
Rejecting call

### PR DESCRIPTION
**Pull request by agilob**
It's not best, looks (very) ugly, but well... it's something. Ideas how to improve it are welcome.

reject button

Technically, it can be merged if you're not disgusted with that.

### CODE REVIEW

**Comment by agilob** [comment]
reject button1

Why are all SLOTs called som many times?
https://gist.github.com/agilob/92ef79f4feed0c0383a4

**Comment by zetok** [comment]
Sorry, but it looks confusing and disgusting.

**Comment by agilob** [comment]
Yup, that's what I wrote ;) How would you make it?

**Comment by zetok** [comment]
I wouldn't since I cannot into coding :P
But rejecting call in the way @ItsDuke [proposed](https://github.com/tux3/qTox/issues/515#issuecomment-61551871) seems to be the best way IMO.

**Comment by agilob** [comment]
I cannot into css and design.

**Comment by tux3** [comment]
I also think that it doesn't look very good :)

Closing for now.

**Pull request closed without merging**
