### PR TITLE
test: Replace check on Qt test

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4438)

### CODE REVIEW

**Comment by Diadlo** [comment]
Qt Test is better, because if tested class use `QMetaObject` and some other Qt stuff then test required started `QApplication`.

**Comment by sudden6** [comment]
Do tests work on Windows? I think we should not run them by default there.

**Comment by Diadlo** [comment]
1) It should work
2) They doesn't runned by default (same as before)

**Comment by sudden6** [comment]
:lgtm_strong: then

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4438#-:-Kljhzvcx8zJUD1aGWEj:b1hmrgw)*

**Pull request merged**
