### PR TITLE
feat: Add spell checking

### LINKED ISSUE #1301: [feature] spell checking
It may be interesting to add spell checking on text input (with suggestions on right click).

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #1301

Spell checking implemented by KF5Sonnet.
Suggest currently don't add official support, because some peoples have troubles with it (and I don't know how to fix it).
But feature is really useful.

image

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149)

### CODE REVIEW

**Comment by tox-user** [comment]
I proposed other ways to implement it:

>Since Sonnet didn't work, we could try to use Enchant for spellchecking (https://en.wikipedia.org/wiki/Enchant_(software)). It can use multiple backends just like Sonnet. Here is a library for Qt that seems to make it very easy to use:
https://github.com/manisandro/qtspell
https://github.com/manisandro/qtspell/tree/master/examples

>If that doesn't work, we could use hunspell (https://en.wikipedia.org/wiki/Hunspell):
https://wiki.qt.io/Spell-Checking-with-Hunspell

**Comment by sudden6** [comment]
Would it be possible to add a runtime setting to disable it in case it's buggy?

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[cmake/Dependencies.cmake, line 35 at r1](https://reviewable.io/reviews/qtox/qtox/5149#-LCnwSSF4e__9vyumY5Q:-LCnwSSF4e__9vyumY5R:b-iq0z4x) ([raw file](https://github.com/qtox/qtox/blob/96301a7714f42a65e3dcd38956079ab11cb943c0/cmake/Dependencies.cmake#L35)):*
> ```CMake
>   Qt5::Xml)
> 
> if(KF5Sonnet_FOUND)
> ```

Can you add an option to the main cmake file to enable (default)/disable spell checking and print a warning here if spell checking is enabled but sonnet isn't found?

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149#-:-LCnwlGBC41wOg8iVZpV:b-xqztn3)*

**Comment by tox-user** [comment]
It would be really nice if it worked, as it's a very useful feature, but why add it if it doesn't? If I remember correctly it only worked well on KDE, because there were some bugs. Maybe they are fixed now?

**Comment by Diadlo** [comment]
@tox-user You write your suggestion 4 month ago. Unfortunately there is still no implementation for any of your suggestion. I think something better than nothing. It can be reimplemented later.

JFY: It works well for me (Arch Linux + i3wm)

**Comment by sudden6** [comment]
I agree with @Diadlo here, even if it didn't work for me last time, it could be very useful for others. Also IIRC there were no regressions.

**Comment by tox-user** [comment]
I remember now that the problem was with Sonnet looking for dictionaries in wrong places. I was able to solve the issue by creating a symlink then. The issue was with the newest available version and with older ones too. It could be fixed in the current version now. We could maybe also use some tricks to make it work?

**Comment by Diadlo** [comment]
@sudden6 Runtime setting added

---

Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/Dependencies.cmake, line 35 at r1](https://reviewable.io/reviews/qtox/qtox/5149#-LCnwSSF4e__9vyumY5Q:-LCo4pST1by3ipunAdsM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/96301a7714f42a65e3dcd38956079ab11cb943c0/cmake/Dependencies.cmake#L35)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Can you add an option to the main cmake file to enable (default)/disable spell checking and print a warning here if spell checking is enabled but sonnet isn't found?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149#-:-LCo4se96nRWyv6pA2bZ:b-gp9dag)*

**Comment by sudden6** [comment]
code :lgtm_strong: also tested it, seems to work for me now without issues. Your last commit name blocks CI though

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149#-:-LCocVDqDUNKJIuXn5LZ:b-rdh15r)*

**Comment by nurupo** [comment]
INSTALL instructions need to be updated to mention Sonnet. CI build scripts need to be updated too, especially the OS X, AppImage and Windows build scripts, binaries of which you use for final release.

**Comment by tox-user** [comment]
>INSTALL instructions need to be updated to mention Sonnet

Specifically version 5.45 that is confirmed by @sudden6 to work. Versions 5.40 and below didn't work when we tested them. That means we need to compile Sonnet on all systems that don't have a version that is new enough.

**Comment by Diadlo** [comment]
@nurupo Didn't plan to add official support

**Comment by tox-user** [comment]
This is only a partial fix then. https://github.com/qTox/qTox/issues/1301 will be still unsolved after this is merged.

**Comment by Diadlo** [comment]
@tox-user Only for windows and macos, right

**Comment by tox-user** [comment]
It will certainly not work on Debian and Ubuntu 16.04 (unless someone compiles new Sonnet). Don't know about Ubuntu 18.04 and other distros.

**Comment by nurupo** [comment]
@tox-user Debian and Ubuntu have package search web interfaces where you can check package versions, which files packages contain (and their fs paths), find a package that contains a filename, etc.

- https://packages.debian.org
- https://packages.ubuntu.com

Very handy tools.

E.g. here are all packages with "sonnet" in the name in all Debian and Ubuntu releases

- https://packages.debian.org/search?suite=all&searchon=names&keywords=sonnet
- https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=sonnet

Looks like only Debian Testing, Debian Sid, and the upcoming Ubuntu 18.10 have Sonnet >= 5.45. It's kind of bad that Ubuntu 18.04 LTS doesn't have it, it has only 5.44 version. Is 5.44 version not good enough?

**Comment by Diadlo** [comment]
@tox-user I don't think, that sonnet doesn't work at all before 5.45

**Comment by sudden6** [comment]
I think we don't know if 5.44 is good enough, I tested 5.45 which worked and tox-user said 5.40 is not working.

**Comment by Talkless** [comment]
Review status: 9 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/persistence/settings.cpp, line 1053 at r4](https://reviewable.io/reviews/qtox/qtox/5149#-LDR-wiL9ntxjGDEbBdK:-LDR-wiL9ntxjGDEbBdL:b-mxihey) ([raw file](https://github.com/qtox/qtox/blob/edcc27b864a1e829cffe1de0ffaee3a0cb7e83f9/src/persistence/settings.cpp#L1053)):*
> ```cpp
> bool Settings::getSpellCheckingEnabled() const
> {
>     QMutexLocker locker{&bigLock};
> ```

Über-pedantic but could be `const QMutexLocker` (same below). :) .

---

*[src/widget/form/genericchatform.h, line 176 at r4](https://reviewable.io/reviews/qtox/qtox/5149#-LDR0AovDf6ZgdUPahRV:-LDR0AovDf6ZgdUPahRW:b-dwvszu) ([raw file](https://github.com/qtox/qtox/blob/edcc27b864a1e829cffe1de0ffaee3a0cb7e83f9/src/widget/form/genericchatform.h#L176)):*
> ```objc
>     ChatTextEdit* msgEdit;
> #ifdef SPELL_CHECKING
>     Sonnet::SpellCheckDecorator* decorator;
> ```

`decorator{nullptr};`

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149)*

**Comment by tox-user** [comment]
I've tested QtSpell library for spell checking. It didn't work for me with ChatTextEdit in qTox, but I'm not sure if the library is broken or if I'm missing something.

**Comment by Diadlo** [comment]
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[src/persistence/settings.cpp, line 1053 at r4](https://reviewable.io/reviews/qtox/qtox/5149#-LDR-wiL9ntxjGDEbBdK:-LErgO_ZCzFt6WCPi7k7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edcc27b864a1e829cffe1de0ffaee3a0cb7e83f9/src/persistence/settings.cpp#L1053)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Über-pedantic but could be `const QMutexLocker` (same below). :) .
</blockquote></details>

Done.

---

*[src/widget/form/genericchatform.h, line 176 at r4](https://reviewable.io/reviews/qtox/qtox/5149#-LDR0AovDf6ZgdUPahRV:-LErgP301HEJHyutnOD1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/edcc27b864a1e829cffe1de0ffaee3a0cb7e83f9/src/widget/form/genericchatform.h#L176)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`decorator{nullptr};`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149)*

**Comment by sudden6** [comment]
Reviewed 2 of 4 files at r4, 4 of 5 files at r5.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---

*[INSTALL.md, line 368 at r5](https://reviewable.io/reviews/qtox/qtox/5149#-LGFE6Mg0LA8tSwE44lJ:-LGFE6Mg0LA8tSwE44lK:b-gng6tx) ([raw file](https://github.com/qtox/qtox/blob/ff0e596f68937376975d4fa2caa67883e3d424cf/INSTALL.md#L368)):*
> ```Markdown
>     qrencode-devel \
>     sqlcipher-devel \
>     sonnet
> ```

it should be `sonnet-devel` to also get the header files

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5149)*

**Comment by sudden6** [comment]
@Diadlo I seem to have more time than you, should I take this over?

**Comment by Diadlo** [comment]
@sudden6 If you have time, I will be very grateful

**Comment by sudden6** [comment]
@Diadlo I think this is ready to merge, I added build support for Linux/AppImage/Flatpak/Mac can you take a look again? I'll merge after you give lgtm

**Comment by Diadlo** [comment]
@sudden6 Do you remember, that it's mine PR?)
LGTM. Rebased on master

**Comment by Diadlo** [comment]
Thank you
LGTM

**Comment by yurivict** [comment]
It's broken, see https://github.com/qTox/qTox/issues/5598

**Pull request merged**
