### PR TITLE
Release v1.12.1

### PR DESCRIPTION
**Pull request by sudden6**
Should fix build on windows and update the version number which we forgot for the v1.12.0 release.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4720)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4720#-:-Kw6WXdqQQ4UDsxk7sWy:b-jbsf8z)*

**Comment by sudden6** [comment]
Hmm, something makes Travis not work, anyone has an idea why?

**Comment by Diadlo** [comment]
@sudden6 Is it right, that you try to merge in master? It already contains this commits

**Comment by sudden6** [comment]
@Diadlo This PR was just to get it reviewed and tested via Travis, i then pushed it to the `v1.12.1` tag. Unfortunately Travis failed in the deploy stage there :/

See https://github.com/qTox/qTox/issues/4723

**Comment by sudden6** [comment]
Working tag pushed

**Pull request closed without merging**
