### PR TITLE
Add audio notifications

### PR DESCRIPTION
**Pull request by F1ynn**

### CODE REVIEW

**Comment by tux3** [comment]
Small bug: It sets the volume to 100% and destroys my ears everytime. But maybe that's just my nondeterministic sound driver, can you reproduce ?

**Comment by F1ynn** [comment]
Yikes! That doesn't happen on either of the two PCs I tested it on. Let me look up the docs for QSound and I'll see what I can do

**Comment by tux3** [comment]
It's probably just my computer then, it's fine.

**Comment by F1ynn** [comment]
Okay, interesting. I checked the docs and tested it on a third computer, didn't hear anything odd.

**Pull request merged**
