### PR TITLE
fix(Widget::updateIcons): workaround QIcon fallback bug

### PR DESCRIPTION
**Pull request by vith**
Some builds of Qt appear to have a bug in icon loading: `QIcon::hasThemeIcon` is sometimes unaware that the icon returned from `QIcon::fromTheme` was a fallback icon, causing `hasThemeIcon` to incorrectly return `true`.

In qTox this leads to the tray and window icons using the static qTox logo icon instead of an icon based on the current presence status.

This workaround checks for an icon that definitely does not exist to determine if `hasThemeIcon` can be trusted.

On systems with the Qt bug, this workaround will always use our included icons but user themes will be unable to override them.

### CODE REVIEW

**Comment by vith** [comment]
If anyone's not a fan of this mitigation, I believe another option would be renaming the static icon to `qtox-logo` or similar, so that there's no `qtox` to fallback to from `qtox-offline` etc.

Downstream worked around it by using a unique capitalization for the installed icon files.

**Comment by vith** [comment]
Related: #3131 #1820

**Comment by sudden6** [comment]
Is this only affecting certain versions of Qt? Because then I think it would be better to limit the workaround to these versions.

Using unique capitalization probably isn't a good idea, because it could be seen as an accident and be renamed in the future, which will break things again.

**Comment by zetok** [comment]
> Is this only affecting certain versions of Qt?

Yep.

> Because then I think it would be better to limit the workaround to these versions.

No, it wouldn't be.
IIRC 5.3 are affected, 5.4 versions are not affected (kinda), 5.5.0 is affected, 5.5.1 is affected, 5.5.1 with some ~~path~~ _patch_ is not affected, 5.6 is affected…

So I'm kinda wondering how you distinguish between 5.5.1 that is affected, and 5.5.1 build that is not affected at compile time.

**Comment by sudden6** [comment]
ok, I thought it would be an easier to distinguish

**Comment by vith** [comment]
I tried to determine which Qt versions are affected, but any that I built myself with `./configure -developer-build` did not have the bug (v5.5.0, v5.5.1, v5.6.0 were the versions I tested). Earlier versions did not have the commit which added the fallback behavior: https://github.com/qtproject/qtbase/commit/a40d390a

I was unable to debug any Qt build without `-developer-build` as I always got an error that the `svg` module didn't exist when trying to build qTox with them. I did skim the patches that Arch Linux was using and it didn't look like they intentionally touched anything icon related.

**Comment by sudden6** [comment]
Seems like your version is already the best solution, I'll merge it later.

**Pull request merged**
