### PR TITLE
Merged master, still highly experimental

### PR DESCRIPTION
**Pull request by dubslow**
I plan a UI revision, as well as some more overhaul of the internals. Also, I might need help clearing the chat list when switching between profiles.

### CODE REVIEW

**Comment by dubslow** [comment]
I have no idea what the conflicts are, I can't find what they are... at any rate, this isn't important yet, functionality is still rather buggy

**Comment by tux3** [comment]
This branch is really really out of date on my end, I tried to rebase on master and fix the conflicts but it's just too much work for now.
If your branch is rebased on master, I'll just pull it and rewrite history.

**Comment by dubslow** [comment]
Errr... something like that.

dubslow:profiles has master merged (not rebased), short of the translation update from a few hours ago. I spent around an hour going through the conflicts. I'm honestly somewhat confused about how this PR isn't merely a fast forward, but... you should be fine to rewrite history in your profiles branch.

**Comment by tux3** [comment]
Ok, I overwrote my branch with yours, but this branch still conflicts with master.

Please try rebasing on master and fixing the conflicts, I'm not sure what part of your branch was added before or after some of the conflicts with master.

**Pull request merged**
