### PR TITLE
Implement clang-format and updated coding style document

### LINKED ISSUE #3601: Code formatting using clang-format & potential switch to established code style
Current qTox code formatting is ~lax, not verified, and not really enforced.

`clang-format` could be used to both format qTox code, and as a checker of whether code has been actually formatted, verified on travis.

If it were to be used as a check, travis would do equivalent of running `clang-format && git diff --exit-code` which would result in travis passing only if code has been formatted & there are no differences after running `clang-format`. If there would be differences, they would be printed, build would fail early & there would be info in travis log about requiring `clang-format` to be run.

As @initramfs said in https://github.com/qTox/qTox/pull/3589#issuecomment-238103043:

> Perhaps a scheme can be created for a source code formatter as well (for example, something like ClangFormat, which can be integrated into QtCreator through a plugin).
# 

The other part is coding style. It's far from being even good, and it seems to reinvent the wheel when there's no need to.

There are already several coding styles out there with guidelines easily available, and they could be used by qTox. Even if not as a perfect drop-in solution, slight adjustments to one of them that is closest to qTox would be less bothersome than reinventing the wheel.

Of course it would be preferable to just use one of styles as drop-in, since it would help assure consistency of the coding style with other projects out there that are already using one of the styles, which most likely would help people to either be already familiar with the style when they want to contribute to qTox, or at least they would have a good reason to get to know coding style, since it's used in other projects as well.

Would be good to use one of those styles:
- [LLVM](http://llvm.org/docs/CodingStandards.html)
- [Google](https://google.github.io/styleguide/cppguide.html)
- [Chromium](http://www.chromium.org/developers/coding-style)
- [Mozilla](https://developer.mozilla.org/en-US/docs/Developer_Guide/Coding_Style)
- [WebKit](https://webkit.org/code-style-guidelines/)

One of those would be nice, since `clang-format` has support for them. And if we decide that none of those is good enough as-is, then even with a slight deviation configuring clang-format would be easier.
# 

Scope of this issue:
- decision whether `clang-format` should be used
  - at all
  - as code style consistency check
    - if check is to be put in place, follow-up on getting it to work on travis
- decision on which coding style among the popular ones would fit qTox needs
  - if none of available ones would be acceptable as-is, specify what needs adjustments in one that is closest to what qTox needs and adjusting it

### PR DESCRIPTION
**Pull request by zetok**
Rebased #3839.

Closes #3601.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4191)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 34 at r2](https://reviewable.io:443/reviews/qtox/qtox/4191#-KdRM9YZL9qPxAUEih0F:-KdRM9YZL9qPxAUEih0G:b4dbj2r) ([raw file](https://github.com/qtox/qtox/blob/d3ecbc74a2189710c841af3d22ed98eba5a04d0b/doc/coding_standards.md#L34)):*
> ```Markdown
> that any code contribution or dependency cannot throw a C++ exception at
> runtime or else the application will crash. For code present in the qTox
> repository, this is enforced by the use of the `exceptions_off` qmake
> ```

we now use cmake instead of qmake

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191)*

**Comment by zetok** [comment]
https://github.com/qTox/qtox-irc-logs/blob/58f6539ea870459e463728ac09920721030c33b5/2017/02/%23qtox_20170220.log.txt#L169,L189

K&R is less annoying to use for me, but Allman with no braces for single-line `if`s would do.

Aside from that, https://github.com/qTox/qTox/pull/3839#issuecomment-257095552 .

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 34 at r2](https://reviewable.io:443/reviews/qtox/qtox/4191#-KdRM9YZL9qPxAUEih0F:-KdV3S_ZYHYPMCZB2wte:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d3ecbc74a2189710c841af3d22ed98eba5a04d0b/doc/coding_standards.md#L34)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

we now use cmake instead of qmake
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191#-:-KdV3T-Z6W99WX7BLBYl:b-91w74b)*

**Comment by Diadlo** [comment]
AFAIK @noavarice (he started contributing to qTox) prefere K&R style too

**Comment by zetok** [comment]
Argument in favor of K&R and against Allman, linked to by @noavarice:

```c++
ChatLineContent* ChatLine::getContent(QPointF scenePos) const
{
    for (ChatLineContent* c: content)
    {
        if (c->sceneBoundingRect().contains(scenePos))
        {
            return c;
        }
    }
    return nullptr;
}
 
void ChatLine::removeFromScene()
{
    for (ChatLineContent* c : content)
    {
        if (c->scene())
        {
            c->scene()->removeItem(c);
        }
    }
}
 
void ChatLine::addToScene(QGraphicsScene* scene)
{
    if (!scene)
    {
        return;
    }
    for (ChatLineContent* c : content)
    {
        scene->addItem(c);
    }
}
 
void ChatLine::setVisible(bool visible)
{
    for (ChatLineContent* c : content)
    {
        c->setVisible(visible);
    }
}
 
void ChatLine::selectionCleared()
{
    for (ChatLineContent* c : content)
    {
        c->selectionCleared();
    }
}
 
void ChatLine::selectionFocusChanged(bool focusIn)
{
    for (ChatLineContent* c : content)
    {
        c->selectionFocusChanged(focusIn);
    }
}
 
void ChatLine::fontChanged(const QFont& font)
{
    for (ChatLineContent* c : content)
    {
        c->fontChanged(font);
    }
}
 
int ChatLine::getColumnCount()
{
    return content.size();
}
```

I've changed the style in `.clang-format` to K&R. Note that currently nothing enforces requirement for braces. It could be done using `clang-tidy`: https://stackoverflow.com/questions/26111162/can-clang-format-add-braces-to-single-line-if-statements-etc

**Comment by sudden6** [comment]
with the changed brace style https://github.com/qTox/qTox/blob/master/tools/configs/qTox-Coding-Style.xml also needs updating

**Comment by zetok** [comment]
@sudden6 no idea how to update that. Feel free to push to this branch.

**Comment by sudden6** [comment]
Interestingly, Qt Creator doesn't seem to have an option for "braces on same line", I guess if everybody wants this style, the file and references to it should be removed.

EDIT: Qt Creator can apparently use clang-format files with a plugin https://stackoverflow.com/questions/22846739/full-customization-of-qt-creator-coding-style#24756329 so the extra file should be dropped.

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r2, 1 of 2 files at r6.
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 80 at r6](https://reviewable.io:443/reviews/qtox/qtox/4191#-KdrqrMG8X3kNu39ie5E:-KdrqrMH5CUD-ZnpNnVV:b-kqmdd5) ([raw file](https://github.com/qtox/qtox/blob/ed7558b6318afacbab6f94f2a46eec23c2d76b44/doc/coding_standards.md#L80)):*
> ```Markdown
> 
>         switch (...) {
>             case 0: {
> ```

case isn't indented, also consider using this example, I think it makes things more clear ```
int foo(int a) {
    switch (a) {
    case 1:
        bar(1);
        break;
    case 2: {
        bar(2);
        break;
    }
    case 3:
    default:
        bar(3);
        break;
    }
    return 0;
}```

It is from qtcreator examples

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191)*

**Comment by zetok** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/coding_standards.md, line 80 at r6](https://reviewable.io:443/reviews/qtox/qtox/4191#-KdrqrMG8X3kNu39ie5E:-KdtpSjv0gLvPF84OMif:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ed7558b6318afacbab6f94f2a46eec23c2d76b44/doc/coding_standards.md#L80)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

case isn't indented, also consider using this example, I think it makes things more clear ```
int foo(int a) {
    switch (a) {
    case 1:
        bar(1);
        break;
    case 2: {
        bar(2);
        break;
    }
    case 3:
    default:
        bar(3);
        break;
    }
    return 0;
}```

It is from qtcreator examples
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191#-:-Kdu8PPoQ53C19yv-PyI:b-jbsf8z)*

**Comment by sudden6** [comment]
Assigned @Diadlo so he can also take a look before merging.

**Comment by Diadlo** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4191#-:-KduFRmeg3pGkH3j_qHd:b-jbsf8z)*

**Pull request merged**
