### PR TITLE
Update Debian 8 dependencies, fix 'Debian 10' mentions

### PR DESCRIPTION
**Pull request by ghost**
Debian 8 is the latest release, fixed mentions and links of Debian >8.

Also, added missing FFmpeg's `libavdevice-dev` dependency to compile qTox in Debian 8.

### CODE REVIEW

**Comment by zetok** [comment]
No. **10** is there for a reason.

Closing, since your PR breaks instructions.

**Comment by agilob** [comment]
what reason?

**Comment by agilob** [comment]
the pr has one more important change. see last changed line

**Comment by ghost** [comment]
I'd like to know the reason too. The only I can think of is ffmpeg, which is available for Debian 8 stable as backport.
https://packages.debian.org/search?keywords=ffmpeg

**Comment by zetok** [comment]
Oh, I see. I didn't know that it's in the backports - on my debian 8 vm `apt-cache search ffmpeg` never presented ffmpeg.

Given that, mind adding instructions on how to add backports for debian? And since ubuntu ≠ debian, those should be split accordingly.

Also, the now `<8` debian part can be simply thrown out, since it's not supported anyway.

**Comment by ghost** [comment]
Sure, I'll edit in a moment.

**Comment by ghost** [comment]
- removed support for Debian <8
- added instructions about backports for Debian
- Debian, Ubuntu <15.04 and Ubuntu >=15.04 have each an independent submenu everywhere for consistency

Also, shouldn't `toxcore dependencies` be listed before `filter_audio`? It needs some of the packages found there.

**Comment by zetok** [comment]
> Also, shouldn't `toxcore dependencies` be listed before `filter_audio`? It needs some of the packages found there.

Right, good catch. Mind doing that too?

**Pull request merged**
