### PR TITLE
chore: Elide text for CallConfirmWidget

### PR DESCRIPTION
**Pull request by hkarel**
In the footsteps #4898

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4900)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/widget/tool/callconfirmwidget.cpp, line 72 at r1](https://reviewable.io:443/reviews/qtox/qtox/4900#-L2MuHS-SsMgOX7ezpJ0:-L2MuHS-SsMgOX7ezpJ1:bu08w15) ([raw file](https://github.com/qtox/qtox/blob/712aa2717ed051db007adc880dd2ada681bd53bf/src/widget/tool/callconfirmwidget.cpp#L72)):*
> ```cpp
>     QLabel* callLabel = new QLabel(QObject::tr("Incoming call..."), this);
>     callLabel->setStyleSheet("QLabel{color: white;} QToolTip{color: black;}");
>     //callLabel->setWordWrap(true);
> ```

don't comment out unused code, this is what git is for :)

---

*[src/widget/tool/callconfirmwidget.cpp, line 78 at r1](https://reviewable.io:443/reviews/qtox/qtox/4900#-L2MvlyGpKdGKI2GcGxU:-L2MvlyGpKdGKI2GcGxV:b-f4re6e) ([raw file](https://github.com/qtox/qtox/blob/712aa2717ed051db007adc880dd2ada681bd53bf/src/widget/tool/callconfirmwidget.cpp#L78)):*
> ```cpp
>     Qt::TextElideMode elideMode = Qt::ElideRight;
> 
>     // At the moment it does not work correctly
> ```

What does not work correctly?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4900)*

**Comment by hkarel** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/widget/tool/callconfirmwidget.cpp, line 72 at r1](https://reviewable.io:443/reviews/qtox/qtox/4900#-L2MuHS-SsMgOX7ezpJ0:-L2PCScSqLsZJ4PsGEu3:b-whp4wr) ([raw file](https://github.com/qtox/qtox/blob/712aa2717ed051db007adc880dd2ada681bd53bf/src/widget/tool/callconfirmwidget.cpp#L72)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

don't comment out unused code, this is what git is for :)
</blockquote></details>

It was a draft version. In the final version, the commented code will be deleted

---

*[src/widget/tool/callconfirmwidget.cpp, line 78 at r1](https://reviewable.io:443/reviews/qtox/qtox/4900#-L2MvlyGpKdGKI2GcGxU:-L2PDbfcHcURy5nUDyPu:b-y85pe1) ([raw file](https://github.com/qtox/qtox/blob/712aa2717ed051db007adc880dd2ada681bd53bf/src/widget/tool/callconfirmwidget.cpp#L78)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

What does not work correctly?
</blockquote></details>

For languages written from right to left, there is no translation for the phrase "Incoming call...".  In any case for languages which I checked.  In this situation, the phrase "Incoming call..." looks bad: "...oming call...".  There are suggestions, what to do about it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4900)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/widget/tool/callconfirmwidget.cpp, line 72 at r1](https://reviewable.io:443/reviews/qtox/qtox/4900#-L2MuHS-SsMgOX7ezpJ0:-L2PPt2Boo_AeBNK7UML:b-hynooq) ([raw file](https://github.com/qtox/qtox/blob/712aa2717ed051db007adc880dd2ada681bd53bf/src/widget/tool/callconfirmwidget.cpp#L72)):*
<details><summary><i>Previously, hkarel (Pavel Karelin) wrote…</i></summary><blockquote>

It was a draft version. In the final version, the commented code will be deleted
</blockquote></details>

OK, I thought it's ready to merge

---

*[src/widget/tool/callconfirmwidget.cpp, line 78 at r1](https://reviewable.io:443/reviews/qtox/qtox/4900#-L2MvlyGpKdGKI2GcGxU:-L2PQ0zCMWTo_dBzYcku:bm3fe1k) ([raw file](https://github.com/qtox/qtox/blob/712aa2717ed051db007adc880dd2ada681bd53bf/src/widget/tool/callconfirmwidget.cpp#L78)):*
<details><summary><i>Previously, hkarel (Pavel Karelin) wrote…</i></summary><blockquote>

For languages written from right to left, there is no translation for the phrase "Incoming call...".  In any case for languages which I checked.  In this situation, the phrase "Incoming call..." looks bad: "...oming call...".  There are suggestions, what to do about it?
</blockquote></details>

I guess it's better to make it correct for the language, missing translations are another problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4900)*

**Comment by hkarel** [comment]
Improvements is made

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4900#-:-L2QDEj49X0Yq3axmNmN:b-jbsf8z)*

**Pull request merged**
