### PR TITLE
refactor(docs): Fix grammer, wording and style in the cross-compile guide

### PR DESCRIPTION
**Pull request by AliceGrey**
Rewrote the cross-compile guide to make it easier to understand. Might need further editing.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5112)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[windows/cross-compile/README.md, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbIx_aBKEpBPtwzVCb:-LBbIx_aBKEpBPtwzVCc:bguxmda) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L1)):*
> ```Markdown
> # Cross-compile from Linux to Windows
> ```

General: remove trailing whitespaces and whitespace in empty lines (Github diff viewer doesn't show them, but reviewable does)

---

*[windows/cross-compile/README.md, line 15 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbKBCiBWNY2jtR_2iO:-LBbKBCiBWNY2jtR_2iP:b-6mc8ee) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L15)):*
> ```Markdown
> 
> 
> **1. [Install Docker](https://docs.docker.com/install).**
> ```

In the rest of our documents we use the `#` syntax for headings like this, is there a reason you used this style?

---

*[windows/cross-compile/README.md, line 28 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJhSq6of11CFX41q6:-LBbJhSq6of11CFX41q7:b-bxkbwn) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L28)):*
> ```Markdown
>   Copy the `build.sh` script to this folder.
>   
>   * `qtox` -- a root directory of a qTox repository. This directory must contain
> ```

`a` -> `the`?

---

*[windows/cross-compile/README.md, line 60 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJugVCvayDJs8XNIJ:-LBbJugXEICDiVdvLi7M:b-tav0wb) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L60)):*
> ```Markdown
> 
> 
> > If you are a qTox developer, you might want to enable tty and leave stdin open by running the following script instead.
> ```

I think this line should not use `>`, it's too easy to miss it IMO

---

*[windows/cross-compile/README.md, line 76 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJKGJBTICrkOGL-9u:-LBbJKGJBTICrkOGL-9v:b-u3btbd) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L76)):*
> ```Markdown
> qTox has a lot of dependencies that need to be cross-compiled.
> <br>
> <br>
> ```

why these line breaks? an empty line should be sufficient to let Markdown create a paragraph

---

*[windows/cross-compile/README.md, line 79 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJXIg3l2t-It1Vn7_:-LBbJXIg3l2t-It1Vn7a:b-ak7odm) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L79)):*
> ```Markdown
> > Note that it takes my Intel Core i7 processor about 125 minutes on average for the cross-compilation
> > to finish on a single core, and about 30 minutes using all 8 hyperthreads. But once you've compiled
> > it once the dependencies will get cached inside the `workspace` directory, and the next time
> ```

`once` one time too much

---

*[windows/cross-compile/README.md, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJU_T475IwvZ9_T7O:-LBbJU_T475IwvZ9_T7P:bhj05ui) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L86)):*
> ```Markdown
> **4. After cross-compiling has finished**
> ***
> The `workspace\i686\qtox` and `workspace\x86_64\qtox\`directories will contain the compiled binaries in their respective debug or release folder depending on the compilation settigns you chose in Step 3.
> ```

typo settings

---

*[windows/cross-compile/README.md, line 95 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJa5w5zNnKghZBKtI:-LBbJa5w5zNnKghZBKtJ:b1a4vb4) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L95)):*
> ```Markdown
> _The `workspace` direcory structure for reference_
> 
> 	workspace
> ```

use spaces not tabs

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5112)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[windows/cross-compile/README.md, line 1 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbIx_aBKEpBPtwzVCb:-LBbw7ow44YM8bJyJl0U:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L1)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

General: remove trailing whitespaces and whitespace in empty lines (Github diff viewer doesn't show them, but reviewable does)
</blockquote></details>

Done.

---

*[windows/cross-compile/README.md, line 15 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbKBCiBWNY2jtR_2iO:-LBbsRd82oNS6V1QutfF:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L15)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

In the rest of our documents we use the `#` syntax for headings like this, is there a reason you used this style?
</blockquote></details>

Done.

---

*[windows/cross-compile/README.md, line 28 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJhSq6of11CFX41q6:-LBbsVWQ6iaafo9EmQJL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L28)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`a` -> `the`?
</blockquote></details>

Done.

---

*[windows/cross-compile/README.md, line 60 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJugVCvayDJs8XNIJ:-LBbwByD5TRmKfbQtpTF:brzez32) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L60)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think this line should not use `>`, it's too easy to miss it IMO
</blockquote></details>

I actually think it brings more atention to it. What would you suggest instead of `>` ?

---

*[windows/cross-compile/README.md, line 76 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJKGJBTICrkOGL-9u:-LBbsY-63v4vzuUxNIZr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L76)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why these line breaks? an empty line should be sufficient to let Markdown create a paragraph
</blockquote></details>

Done.

---

*[windows/cross-compile/README.md, line 79 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJXIg3l2t-It1Vn7_:-LBbsYeCArMDv914AcKH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L79)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`once` one time too much
</blockquote></details>

Done.

---

*[windows/cross-compile/README.md, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJU_T475IwvZ9_T7O:-LBbsZz61P_kdwa6Wgg6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L86)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo settings
</blockquote></details>

Done.

---

*[windows/cross-compile/README.md, line 95 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJa5w5zNnKghZBKtI:-LBbwAoR7HFKERuevIZK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L95)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use spaces not tabs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5112)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/cross-compile/README.md, line 60 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJugVCvayDJs8XNIJ:-LBbyxM75GsLn351U1Mf:b-ac7u5q) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L60)):*
<details><summary><i>Previously, AliceGrey (Alice) wrote…</i></summary><blockquote>

I actually think it brings more atention to it. What would you suggest instead of `>` ?
</blockquote></details>

In the other parts of this document you use `>` for notes, here I would just add empty lines before and after the sentence.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5112)*

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[windows/cross-compile/README.md, line 60 at r1](https://reviewable.io/reviews/qtox/qtox/5112#-LBbJugVCvayDJs8XNIJ:-LBc8xzhCBuMpveqf3Dh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b9c96dad1f90a921a4541de1dfd61e2646ea8e5/windows/cross-compile/README.md#L60)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

In the other parts of this document you use `>` for notes, here I would just add empty lines before and after the sentence.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5112)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5112#-:-LBfBDKr0EuEgn3VMBcv:b-jbsf8z)*

**Pull request merged**
