### PR TITLE
removing border from contact name linedit

### PR DESCRIPTION
**Pull request by agilob**
@TheLastProject  I think it fixes first two points from #864, but I don't understand the third issue. Could you visualise it?

### CODE REVIEW

**Comment by dubslow** [comment]
This only fixes the first point I think. The second two are separate issues about the same line separating the contact info at the top and the main message window.

**Comment by agilob** [comment]
The only difference I can see is different font size. I think I really need some visualisation for that.

**Comment by TheLastProject** [comment]
@agilob
453acfae-7597-11e4-8d85-cafe9c101be1
I've coloured the lines red and blue and drew them a bit further than they really are, to show to difference they have, they are not on the same "height", which is what I meant with not aligning.

**Comment by dubslow** [comment]
Is setting the color necessary? Won't that mess with some themes?

**Comment by zetok** [comment]
@dubslow colour is there to show what needs to be done, not to be used

**Comment by agilob** [comment]
LOL. Volume and microphone buttons have pictures 22x18 what also scales to 25x20. Layout height is limited to 40px so adding a spacing between those two buttons was the problem. Fixed by removing fixed size of buttons, scaling bottom button to 25x18, adding spacing between buttons and aligning them to top/bottom.

The difference in height between lines on my screen was 2px, nice catch @TheLastProject

qtox1
qtox3

**Pull request merged**
