### PR TITLE
Fix/new group api

### PR DESCRIPTION
**Pull request by sudden6**
This should make qTox work with https://github.com/TokTok/c-toxcore/pull/769 without crashing.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4964)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/nexus.cpp, line 210 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tL7X4TvribQo9ZF8_:-L5tL7X4TvribQo9ZF8a:bevel7g) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/nexus.cpp#L210)):*
> ```cpp
>     connect(core, &Core::groupInviteReceived, widget, &Widget::onGroupInviteReceived);
>     connect(core, &Core::groupMessageReceived, widget, &Widget::onGroupMessageReceived);
>     connect(core, &Core::groupNamelistChanged, widget, &Widget::onGroupNamelistChanged);    // TODO(sudden6): toxcore < 0.2.0, remove
> ```

What about `#if !TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)`
On update, you just need to search all `TOX_VERSION_IS_API_COMPATIBLE` calls

---

*[src/core/core.cpp, line 557 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tKgxWvOnig-2oFNiz:-L5tKgxWvOnig-2oFNj-:b-yx1m56) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/core/core.cpp#L557)):*
> ```cpp
> void Core::onGroupPeerListChange(Tox*, uint32_t groupId, void* core)
> {
>     CoreAV* coreAv = static_cast<Core*>(core)->getAv();
> ```

`const auto`?

---

*[src/core/core.cpp, line 569 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tKpbs_4hynB3Fs_oN:-L5tKpbs_4hynB3Fs_oO:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/core/core.cpp#L569)):*
> ```cpp
>                             const uint8_t* name, size_t length, void* core)
> {
>     QString newName = ToxString(name, length).getQString();
> ```

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core/core.cpp, line 534 at r2](https://beta.reviewable.io/reviews/qtox/qtox/4964#-L5tOmrt4MyRcHZrh-h1:-L5tOmrt4MyRcHZrh-h2:b-ekgnna) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/core/core.cpp#L534)):*
> ```cpp
>             // Rejoining existing (persistent) AV conference after disconnect and reconnect.
>             toxav_join_av_groupchat(tox, friendId, cookie, length,
>                                     CoreAV::groupCallCallback, core);
> ```

After TokTok/c-toxcore#800 you need to update `groupCallCallback` signature to use `uint32_t`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/4964)*

**Comment by tox-user** [comment]
Doesn't compile with the newest toxcore master.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/nexus.cpp, line 210 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tQW-Z7F6ClLb1KLAK:-L5tQW-Z7F6ClLb1KLAL:b-cyz55c) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/nexus.cpp#L210)):*
> ```cpp
>     connect(core, &Core::groupNamelistChanged, widget, &Widget::onGroupNamelistChanged);    // TODO(sudden6): toxcore < 0.2.0, remove
> ```

Can we change the name of that method if we want to keep it? `groupNamelistChanged` doesn't look much different from `groupPeerlistChanged`. I get confused just by looking at them

---

*[src/widget/widget.cpp, line 1770 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tPZrFtEC91Mc-ELaK:-L5tPZrFtEC91Mc-ELaL:b-3s38rg) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/widget/widget.cpp#L1770)):*
> g->updatePeer(peernumber, newName);

This will probably not work. In 0.2.0 peernumber is supposed to be always 0. We need to regenerate the whole list instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964#-:-L5tPDrRWd3EFEjmYiMY:b1libuv)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/nexus.cpp, line 210 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tL7X4TvribQo9ZF8_:-L5uckar3DdQgNoDB3Sx:b-6pnomk) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/nexus.cpp#L210)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about `#if !TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)`
On update, you just need to search all `TOX_VERSION_IS_API_COMPATIBLE` calls
</blockquote></details>

I didn't want to pollute nexus with tox.h

---

*[src/nexus.cpp, line 210 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tQW-Z7F6ClLb1KLAK:-L5ucuMAmqoQFGtwvTDd:bg7cvjj) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/nexus.cpp#L210)):*
<details><summary><i>Previously, tox-user wrote…</i></summary><blockquote>

Can we change the name of that method if we want to keep it? `groupNamelistChanged` doesn't look much different from `groupPeerlistChanged`. I get confused just by looking at them
</blockquote></details>

It's not going to stay around long, but what name do you suggest?

---

*[src/core/core.cpp, line 534 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tOmrt4MyRcHZrh-h1:-L5zb5ZaUER-WV-DxwU1:b-mxtuo) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/core/core.cpp#L534)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

After TokTok/c-toxcore#800 you need to update `groupCallCallback` signature to use `uint32_t`
</blockquote></details>

Done. I kept the int types in the rest of the code for now and plan to change them to uint32_t after the next release. This is to keep compatibility for < 0.2.0 toxcore for now.

---

*[src/core/core.cpp, line 557 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tKgxWvOnig-2oFNiz:-L5zbMNczzEbQ8iuDpju:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/core/core.cpp#L557)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`const auto`?
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 569 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tKpbs_4hynB3Fs_oN:-L5zbNM0DKiJx8p_NsxY:b-b1htdz) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/core/core.cpp#L569)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

can't do const, but did auto

---

*[src/widget/widget.cpp, line 1770 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tPZrFtEC91Mc-ELaK:-L5ueIj5fGmKzNZSuylJ:bcf3gw1) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/widget/widget.cpp#L1770)):*
<details><summary><i>Previously, tox-user wrote…</i></summary><blockquote>

> g->updatePeer(peernumber, newName);
This will probably not work. In 0.2.0 peernumber is supposed to be always 0. We need to regenerate the whole list instead.
</blockquote></details>

I can't find any docs saying this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964)*

**Comment by tox-user** [comment]
Nevermind about the peer number. I looked at the wrong function. I don't get any crashes anymore. All of them seem to be fixed.

I often get this warning:
```
core/core.cpp:570 : Debug: "Group 0, Peer 1, name changed to test"
:0 : Warning: QObject::connect: Cannot queue arguments of type 'QString&'
(Make sure 'QString&' is registered using qRegisterMetaType().)
```

It looks like Widget::onGroupPeerNameChanged is never called and that's why names aren't updated in groups after name change.

> It's not going to stay around long, but what name do you suggest?

Maybe groupPeerlistChangedV1?

**Comment by Diadlo** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/widget.cpp, line 1754 at r3](https://beta.reviewable.io/reviews/qtox/qtox/4964#-L63_TF13yzsaGRI3hQP:-L63_TF13yzsaGRI3hQQ:bie3g4b) ([raw file](https://github.com/qtox/qtox/blob/89c3e1cb6d2c8efdf9febc83f93466bf6af3cc45/src/widget/widget.cpp#L1754)):*
> ```cpp
> }
> 
> void Widget::onGroupPeerNameChanged(int groupnumber, int peernumber, QString newName)
> ```

`const QString&`?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/4964)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/core.h, line 150 at r3](https://reviewable.io:443/reviews/qtox/qtox/4964#-L63dsTBdh7cdlPjD3nn:-L63dsTBdh7cdlPjD3no:b-egrrsv) ([raw file](https://github.com/qtox/qtox/blob/89c3e1cb6d2c8efdf9febc83f93466bf6af3cc45/src/core/core.h#L150)):*
> ```objc
>     void groupNamelistChanged(int groupnumber, int peernumber, uint8_t change);
>     void groupPeerlistChanged(int groupnumber);
>     void groupPeerNameChanged(int groupnumber, int peernumber, QString& newName);
> ```

And here `const QString&`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964)*

**Comment by sudden6** [comment]
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/nexus.cpp, line 210 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tQW-Z7F6ClLb1KLAK:-L63i6jZC2gRAV3moojA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/nexus.cpp#L210)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

It's not going to stay around long, but what name do you suggest?
</blockquote></details>

Done.

---

*[src/core/core.h, line 150 at r3](https://reviewable.io:443/reviews/qtox/qtox/4964#-L63dsTBdh7cdlPjD3nn:-L63i8Nwy7sT5Z9abZIw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/89c3e1cb6d2c8efdf9febc83f93466bf6af3cc45/src/core/core.h#L150)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

And here `const QString&`
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 1770 at r2](https://reviewable.io:443/reviews/qtox/qtox/4964#-L5tPZrFtEC91Mc-ELaK:-L63iBHFN4qp7rWPoGEo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e2928ada104db65ff4b86147521ec7bbf862285f/src/widget/widget.cpp#L1770)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I can't find any docs saying this?
</blockquote></details>

Done.

---

*[src/widget/widget.cpp, line 1754 at r3](https://reviewable.io:443/reviews/qtox/qtox/4964#-L63_TF13yzsaGRI3hQP:-L63i9O7Pnesed9gkc8o:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/89c3e1cb6d2c8efdf9febc83f93466bf6af3cc45/src/widget/widget.cpp#L1754)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`const QString&`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964)*

**Comment by Diadlo** [comment]
Reviewed 2 of 5 files at r4.
Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/widget.cpp, line 1754 at r4](https://reviewable.io:443/reviews/qtox/qtox/4964#-L65hpa0FuWjQBvadZBS:-L65hpa0FuWjQBvadZBT:bao08wd) ([raw file](https://github.com/qtox/qtox/blob/34eb21af79619ce44cab9d66f625df88d021940b/src/widget/widget.cpp#L1754)):*
> ```cpp
> }
> 
> void Widget::onGroupPeerNameChanged(int groupnumber, int peernumber, const QString &newName)
> ```

`QString&` but not `QString &`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964)*

**Comment by Diadlo** [comment]
Otherwise :lgtm_strong: 

---

Review status: 4 of 7 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964#-:-L65nJoUGRrCw8bOuMTQ:be4co1r)*

**Comment by sudden6** [comment]
@tox-user lgtm?

**Comment by tox-user** [comment]
Reviewed 2 of 3 files at r3, 3 of 5 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964)*

**Comment by tox-user** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4964#-:-L67tGZXrfCnEwo1xKfQ:b-jbsf8z)*

**Pull request merged**
