### PR TITLE
Allow adding friends using only public key, fixes #2551

### LINKED ISSUE #2551: [Proposal]: Add possibilty to add someone using only the public key
You would need to warn the user that it will not send a friend request.
And you will add the contact using

``` c
uint32_t tox_friend_add_norequest(Tox *tox, const uint8_t *public_key, TOX_ERR_FRIEND_ADD *error);
```

### PR DESCRIPTION
**Pull request by TheNain38**
fix #2551
- [x] Ready

### CODE REVIEW

**Comment by agilob** [comment]
Anyone against?

**Comment by ovalseven8** [comment]
Still don't think that qTox needs that feature.

**Comment by tux3** [comment]
I'm strongly against this, unless you can first show in #2251 that many actual users need this feature. 
So far I haven't seen that _at all_, at best people are cautiously neutral about it.
We can't add an option for every feature. qTox should be the intersection of users' needs, not the union.

**Comment by zoff99** [comment]
i don't think this should be closed

**Pull request closed without merging**
