### PR TITLE
chore: update docs & scripts for getting translations from Weblate

### PR DESCRIPTION
**Pull request by zetok**
Any suggestions how workflow could be improved?

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3726)

### CODE REVIEW

**Comment by zetok** [comment]
Hmm, should I add a vim macro that does the commit renaming?

**Comment by sudden6** [comment]
If you have that macro already written, why not?

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[MAINTAINING.md, line 126 at r1](https://reviewable.io:443/reviews/qtox/qtox/3726#-KS0yf-Kzu0Y71mU9MZR:-KS0yf-Kzu0Y71mU9MZS:b-nc4wpe) ([raw file](https://github.com/qtox/qtox/blob/ac64a1071c007547602d151c253d461de84a2654/MAINTAINING.md#L126)):_

> ``` Markdown
> # Translations from Weblate
> 
> Weblate provides for people an easy way to translate qTox. On one hand, it does
> ```

provides an easy way for people to translate qTox

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3726#-:-KS0z8JI1fXftpjfaYAQ:bnfp4nl)_

**Comment by zetok** [comment]
Added the macro.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

_[MAINTAINING.md, line 126 at r1](https://reviewable.io:443/reviews/qtox/qtox/3726#-KS0yf-Kzu0Y71mU9MZR:-KS2_zn2jflSno28WGwj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ac64a1071c007547602d151c253d461de84a2654/MAINTAINING.md#L126)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> provides an easy way for people to translate qTox
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3726#-:-KS2a-SAL0NeMfVdh5fL:b75r06u)_

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3726)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3726#-:-KS2puraZkv0SYwYRIEn:bnfp4nl)_

**Pull request merged**
