### PR TITLE
docs(INSTALL): inform users about `qtox-alpha` package

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3848)

### CODE REVIEW

**Comment by AliceGrey** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVZTQbSEu0ate8R4cVC:b-33jvty) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_

> ``` Markdown
> Link | Distros | Architecture
> ---- | ------- | ------------
> [OBS] | Arch, CentOS, Debian, Fedora, openSUSE, Ubuntu | x86, x86_64
> ```

You should add a link to the qtox-alpha package here

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVZVnMymYA4lkeg2GTB:b37uce7) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, AliceGrey (Alice) wrote…</i></summary>



> You should add a link to the qtox-alpha package here
> </details>
> It's available in the linked repo..?

```
$ zypper se qtox
Loading repository data...
Reading installed packages...

S | Name                   | Summary                                | Type      
--+------------------------+----------------------------------------+-----------
  | qtox                   | qTox is a powerful Tox client          | package   
  | qtox                   | qTox is a powerful Tox client          | srcpackage
i | qtox-alpha             | qTox is a powerful Tox client          | package   
  | qtox-alpha             | qTox is a powerful Tox client          | srcpackage
  | qtox-alpha-debuginfo   | Debug information for package qtox-a-> | package   
  | qtox-alpha-debugsource | Debug sources for package qtox-alpha   | package   
  | qtox-debuginfo         | Debug information for package qtox     | package   
  | qtox-debugsource       | Debug sources for package qtox         | package
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVjB1roOHQrG1BjaOFH:b-7cy8ku) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> It's available in the linked repo..?
> 
> ```
> $ zypper se qtox
> Loading repository data...
> Reading installed packages...
> 
> S | Name                   | Summary                                | Type      
> --+------------------------+----------------------------------------+-----------
>   | qtox                   | qTox is a powerful Tox client          | package   
>   | qtox                   | qTox is a powerful Tox client          | srcpackage
> i | qtox-alpha             | qTox is a powerful Tox client          | package   
>   | qtox-alpha             | qTox is a powerful Tox client          | srcpackage
>   | qtox-alpha-debuginfo   | Debug information for package qtox-a-> | package   
>   | qtox-alpha-debugsource | Debug sources for package qtox-alpha   | package   
>   | qtox-debuginfo         | Debug information for package qtox     | package   
>   | qtox-debugsource       | Debug sources for package qtox         | package
> ```
> 
> </details>
> I think @AliceGrey means that by clicking on the OBS link you choose `qtox` by default and have no easy way to change it to `qtox-alpha`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVjGHOrmj5TWNzqNl4g:b-mljf38) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> I think @AliceGrey means that by clicking on the OBS link you choose `qtox` by default and have no easy way to change it to `qtox-alpha`.
> </details>
> Well, that's not the case.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVjVCgJ3j12UUNkZ0XC:bvud7fr) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Well, that's not the case.
> </details>
> It is, click on OBS link and choose a distro, there are only install instructions for 'qtox' not for 'qtox-alpha'

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVjWD1dSj9EB2EZZJde:bbi35tf) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> It is, click on OBS link and choose a distro, there are only install instructions for 'qtox' not for 'qtox-alpha'
> </details>
> Um, adding manually `-alpha` to the `$install_command` in the instructions is not an easy change?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVkDZkyjAFwBMm2NddW:bs7h5xi) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Um, adding manually `-alpha` to the `$install_command` in the instructions is not an easy change?
> </details>
> Not if you want maximum visibility, what I thought is the purpose of this PR.

Additionally many SUSE users will use the "OneClick Install" and will never look at the commands.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVkGYxpS47bkg9FHRck:b-55c3g9) ([raw file](https://github.com/qtox/qtox/blob/3ad9364e35afa804aa8874578cf79dbf1317f3d9/INSTALL.md#L69)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Not if you want maximum visibility, what I thought is the purpose of this PR.
> 
> Additionally many SUSE users will use the "OneClick Install" and will never look at the commands.
> </details>
> I thought that it's pretty visible.. As for "maximum" visibility, I'm not sure if that would be beneficial, and that's not really purpose of this PR.

PR aims to provide info that there exists a package `qtox-alpha`, since a lot of people are simply unaware of it, since it's not documented anywhere.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848)_

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[INSTALL.md, line 69 at r1](https://reviewable.io:443/reviews/qtox/qtox/3848#-KVZTQbRFgtNZsEZyOgy:-KVtXWozeUOYLR3hUcfX:b-buyqdg) ([raw file](https://github.com/qtox/qtox/blob/4d82088f1bf70a602e3c1457e9466844a6c10ca2/INSTALL.md#L69)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> I thought that it's pretty visible.. As for "maximum" visibility, I'm not sure if that would be beneficial, and that's not really purpose of this PR.
> 
> PR aims to provide info that there exists a package `qtox-alpha`, since a lot of people are simply unaware of it, since it's not documented anywhere.
> </details>
> ok, then.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3848#-:-KVtXkwHe5MGHfcwz2e-:bnfp4nl)_

**Pull request merged**
