### PR TITLE
closes tux3/qtox#988

### PR DESCRIPTION
**Pull request by agilob**
#752 and #988

### CODE REVIEW

**Comment by dubslow** [comment]
Can someone else (@zetok) confirm this? I can't test myself for another ~36-48 hours.

**Comment by zetok** [comment]
Seems to work, except for regression with truncating shown groupchat title, which is something that at least I don't like (or was it introduced by some other PR? haven't been up to date with "testing" qTox)
gtitile

**Comment by dubslow** [comment]
Merged on the basis that the regression is less evil than the bug fixed

**Comment by agilob** [comment]
I'll fix this in a week, it'll be probably a one line fix.

**Comment by dubslow** [comment]
Any progress on the regression? :)

**Comment by agilob** [comment]
Oh. Sure. 

kkk
kkk1

**Pull request merged**
