### PR TITLE
Svg mic and vol buttons

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3935)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 493 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KY8wuySeeKxYa4wWcYD:-KY8wuySeeKxYa4wWcYE:b-8x7k6f) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L493)):*
> ```cpp
>         {
>             callButton->setObjectName("");
>             callButton->setToolTip("");
> ```

Wouldn't e.g. `Can't start audio call` be better than no tooltip when button is disabled?

Same goes for video call button.

---

*[src/widget/form/chatform.cpp, line 919 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KY8xGpVox7g_IqsiBy7:-KY8xGpVox7g_IqsiBy8:bjbzfnn) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L919)):*
> ```cpp
>     else
>     {
>         micButton->setToolTip("");
> ```

This isn't quite right, since it probably would be preferable to offer an ability to mute microphone even before the call is started.

So either `if` condition is not needed, or tooltip should say `Microphone can be muted only during a call` when it's disabled.

Same goes for the volume button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by antis81** [comment]
Reviewed 1 of 15 files at r1.
Review status: 1 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 919 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KY8xGpVox7g_IqsiBy7:-KYSkIxfZVpHgKi9Y9KC:b-esfrp4) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L919)):*
> …since it probably would be preferable to offer an ability to mute microphone even before the call is started.

Then why did you:

```c++
micButton->setEnabled(false);
updateMuteMicButton();
```

?? :smile:

`updateMuteMicButton()` **reflects** the state in the UI. It **doesn't change** it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by antis81** [comment]
Reviewed 14 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 902 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KYSmiq_uitbFy-csBhR:-KYSmiqaqzVLg9lXDgFv:b-kcnios) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L902)):*
> ```cpp
>     const CoreAV* av = Core::getInstance()->getAv();
> 
>     micButton->setEnabled(av->isCallActive(f));
> ```

@zetok: Uhm… I just saw this. This is wrong! @Diadlo Can you remove the two lines please? Same for the `updateMuteVolButton`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by zetok** [comment]
@antis81 um, the PR's scope is replacing svg icons, and the stuff you're suggesting sounds like something that it better done in another PR?

**Comment by antis81** [comment]
>um, the PR's scope is replacing svg icons, and the stuff you're suggesting sounds like something that it better done in another PR?

In that case, just LGTM, merge and remove the two lines (one for in/out logic) in new pr. And forget the tooltips… ^^

**Comment by antis81** [comment]
:lgtm_strong: 

---

Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935#-:-KYZalgAH11azm6syQeV:b-uwkowd)*

**Comment by Diadlo** [comment]
Review status: 12 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/widget/form/chatform.cpp, line 493 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KY8wuySeeKxYa4wWcYD:-KYlq_yiFpQdOO8ZVgVd:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L493)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Wouldn't e.g. `Can't start audio call` be better than no tooltip when button is disabled?

Same goes for video call button.
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 902 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KYSmiq_uitbFy-csBhR:-KYlq_56pkL1ZBQQ2eJ_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L902)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

@zetok: Uhm… I just saw this. This is wrong! @Diadlo Can you remove the two lines please? Same for the `updateMuteVolButton`.
</blockquote></details>

Done.

---

*[src/widget/form/chatform.cpp, line 919 at r1](https://reviewable.io:443/reviews/qtox/qtox/3935#-KY8xGpVox7g_IqsiBy7:-KYlqZHjqO6D08HBTe5e:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/27a266199b96ced902b89e0fc0b3bf2910ecc25a/src/widget/form/chatform.cpp#L919)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

> …since it probably would be preferable to offer an ability to mute microphone even before the call is started.

Then why did you:

```c++
micButton->setEnabled(false);
updateMuteMicButton();
```

?? :smile:

`updateMuteMicButton()` **reflects** the state in the UI. It **doesn't change** it!

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by zetok** [comment]
on 9d02fce34583148d769e21007491c14979eabf10

Icons are slightly wrongly positioned:
spectacle ti4812

zoomed: 
spectacle yk7044

**Comment by Diadlo** [comment]
@zetok Can't reproduce :(
spectacle m27929

**Comment by zetok** [comment]
on f0926764d1e2d8bd120cf05ba9e0541296c66bec
spectacle sa6958

**Comment by zetok** [comment]
spectacle cf3087
PR @ f0926764d1e2d8bd120cf05ba9e0541296c66bec

————
~master

**Comment by antis81** [comment]
@diadlo How about correcting the svg's and remove the transparent margin?

**Comment by Diadlo** [comment]
@antis81 Sorry, what "correcting"? What "transparent margin"?

**Comment by antis81** [comment]
The svg contains a margin. An icon has to fill the squared area (e.g. 256x256) without borders (when the icon is not squared, it has to touch two borders). This is the first step. Further we should consider to actually set an icon on a QToolButton (this is the easiest way to center it). Setting it as background or a tiled border image leads to incorrect size when the button is not squared and thus "spoils" aspect ratio. Try this:

```css
/* the rule might need to be applied to QToolButton instead */
QAbstractButton { image: 'qrc://path/to/icon.svg'; /* aligment should already be centered and margins have a default, that usually fits best */  }
```

**Comment by Diadlo** [comment]
@antis81 What the problem with current implementation?

**Comment by antis81** [comment]
>What the problem with current implementation?

1. Image is spoiled (faking a margin by placing into the image will falsify any other margin)
2. Margins, spacings and probably size restrictions of the widget are obviously incorrect.

**COMPLETELY OFF-TOPIC**
Apart from that I now really believe, that the qTox application is nothing but a conglomerate of major misconceptions and to fix it, it is absolutely required to fork (rethink) it unless we like to keep breaking major features for presumingly the whole upcoming year. IOW: A non-functional "product" is worth a shit, even if the idea itself might be the "next great thing".

**Comment by zetok** [comment]
>IOW: A non-functional "product" is worth a shit, even if the idea itself might be the "next great thing".

Except that qTox does work for people.

**Comment by antis81** [comment]
@zetok I don't like to discuss it here, but had to "trigger" somewhere… will text you in 1v1 chat… give me a second…

**Comment by Diadlo** [comment]
@antis81 Removin padding seems not good :/
spectacle m22117

**Comment by antis81** [comment]
@diadlo next step, replace `background-image` with `image` in css

**Comment by Diadlo** [comment]
@antis81 Oh.. Sorry. Fixed

**Comment by sudden6** [comment]
Reviewed 8 of 15 files at r1, 1 of 3 files at r2, 5 of 8 files at r4.
Review status: 14 of 17 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 58 at r4](https://reviewable.io:443/reviews/qtox/qtox/3935#-KYxuOhIP_912XQa3I-3:-KYxuOhJbeXqqBekD0I1:bv3nmg6) ([raw file](https://github.com/qtox/qtox/blob/b1ddfe3ce14105b2e485c56a2309e7431a00ef41/src/widget/form/genericchatform.cpp#L58)):*
> ```cpp
>  *
>  * @var GenericChatForm::historyBaselineDate
>  * @brief Used by HistoryKeeper to load messages from t to historyBaselineDate
> ```

this isn't an English sentence and makes no sense, please reword

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by Diadlo** [comment]
Review status: 14 of 17 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 58 at r4](https://reviewable.io:443/reviews/qtox/qtox/3935#-KYxuOhIP_912XQa3I-3:-KYxys1hthmfWie0mmTP:b3ke5bc) ([raw file](https://github.com/qtox/qtox/blob/b1ddfe3ce14105b2e485c56a2309e7431a00ef41/src/widget/form/genericchatform.cpp#L58)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

this isn't an English sentence and makes no sense, please reword
</blockquote></details>

I just copy-pase it from the header. IMO, it's out of the scope this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by sudden6** [comment]
Review status: 14 of 17 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/widget/form/genericchatform.cpp, line 58 at r4](https://reviewable.io:443/reviews/qtox/qtox/3935#-KYxuOhIP_912XQa3I-3:-KYy32UkJBOZRHxSGnFf:b-jqhkvb) ([raw file](https://github.com/qtox/qtox/blob/b1ddfe3ce14105b2e485c56a2309e7431a00ef41/src/widget/form/genericchatform.cpp#L58)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I just copy-pase it from the header. IMO, it's out of the scope this PR
</blockquote></details>

well, then at least add a TODO for it, so we don't forget.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by Diadlo** [comment]
Review status: 14 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/widget/form/genericchatform.cpp, line 58 at r4](https://reviewable.io:443/reviews/qtox/qtox/3935#-KYxuOhIP_912XQa3I-3:-KZ06DQxj47cShymRIPD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b1ddfe3ce14105b2e485c56a2309e7431a00ef41/src/widget/form/genericchatform.cpp#L58)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

well, then at least add a TODO for it, so we don't forget.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3935)*

**Comment by zetok** [comment]
spectacle kp9585
↑ when I picked up audio call

**Comment by Diadlo** [comment]
@zetok @initramfs Can you test it?

**Comment by sudden6** [comment]
@Diadlo mic and vol buttons look as expected: 
spectacle w32579

They work in both, active and inactive state.

**Comment by sudden6** [comment]
IMO the padding between icon and button is to small:
spectacle n32579

#4004 seems fixed for the audio call case, but I don't know if the audio call button should be active while videocalling?

**Comment by Diadlo** [comment]
@antis81 What about icon size? It's `QToolButton` (`setIconSize` didn't help)

**Comment by zetok** [comment]
PR needs to be rebased, since there are now some conflicts.

**Comment by Diadlo** [comment]
cc @antis81

**Comment by antis81** [comment]
@Diadlo Why??

**Comment by sudden6** [comment]
@Diadlo the last commit doesn't seem to have anything to do with this, pleas make another PR

@antis81 probably because he wanted you to look at it again. Also it would be really cool to see you in the IRC sometime :)

**Comment by Diadlo** [comment]
@antis81 You suggested using `QToolButton` but it doesn't work :/

**Comment by antis81** [comment]
@diadlo Why??

**Comment by Diadlo** [comment]
@antis81 https://github.com/qTox/qTox/pull/3935#issuecomment-269120933

**Comment by zetok** [comment]
PR needs to be rebased, since there are now some conflicts.

**Comment by zetok** [comment]
PR needs to be rebased, since there are now some conflicts.

Aside from fixing conflicts, after some rebase PR started to fail to build.

**Pull request closed without merging**
