### PR TITLE
feat(chatlog): Add image preview on paste

### PR DESCRIPTION
**Pull request by sphaerophoria**
Reuse code from the file transfer widget to provide an image preview
on paste/grab. This prevents users from accidentally sending images they
did not mean to when their clipboard is not in the state they thought it
was.

Implementation exposes the genericchatlog vbox to the child classes and
chatform injects the imagepreview into it.

Demo of feature

image preview

**edit**: I forgot to show hover in the gif, but it works just like the file transfer widget does. When you hover over it puts the image into a tooltip at full size.

[x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)

### CODE REVIEW

**Comment by sphaerophoria** [comment]
CI failures look unrelated to my changes. Seems to be some sort of init process in the installer.

**Comment by sudden6** [comment]
@sphaerophoria Seems Qt got updated, I removed the offending code in #6176 if you are interested in reviewing it this will speed up the merge process.

**Comment by sudden6** [comment]
@sphaerophoria CI fail is fixed, can you rebase?

**Comment by anthonybilinski** [comment]
Rebased.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvOwECPKUFLsh5MSO:-MBNvOwECPKUFLsh5MSP:b29a9fb) (no related file):*
The "X" in the top right of the preview being pure white makes it impossible to see if the top right of the image happens to be white. I guess the only way to solve that would be to either have the X be multi colour (e.g. black border on white X) or to have a border to the image with a known background: 


---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvz319sZ4JZn6mNBn:-MBNvz319sZ4JZn6mNBo:b-pupvh4) (no related file):*
It would be nice if ESC cancelled the previewed image, since it already cancels the file picker and the screen selector tools.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBOAnvn-A3kcxGGHtko:-MBOAnvn-A3kcxGGHtkp:b-rxndj6) (no related file):*
Just a note that this allows effectively two messages to be in in progress at once, both the image transfer and the text edit box. Both are sent (separately) when the send message button or enter is pressed.

This is an improvement IMO, I don't think them being separate on the receiving side is that jarring and having them look like they're the same message on the sending side and more importantly be sent at the same time makes it easier to describe an image that you're sending, which was a hassle before.

---
___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MBNykgKBKRUAg8HOhi0:bu1ro6e) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
> ```objc
> #include <QString>
> 
> class ImagePreviewButton : public QPushButton
> ```

why is the image preview a QPushButton? It doesn't seem like needs to be clickable, and clicking it doesn't do anything. This has no real impact on Xorg, but under wayland Qt animates the button click which is confusing.

**Comment by anthonybilinski** [comment]
I forgot to add, overall this is a really nice improvement. It's great to remove the "oh shit" possibility of sending the wrong image and having no way to take it back.

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvz319sZ4JZn6mNBn:-MBQx_mr313W1bQwlIBd:b-p53n1q) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

It would be nice if ESC cancelled the previewed image, since it already cancels the file picker and the screen selector tools.
</blockquote></details>

Reasonable, will add cancel on escape

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvOwECPKUFLsh5MSO:-MBQxd0MArfHiyFmbT2b:b-69raa9) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

The "X" in the top right of the preview being pure white makes it impossible to see if the top right of the image happens to be white. I guess the only way to solve that would be to either have the X be multi colour (e.g. black border on white X) or to have a border to the image with a known background: 


</blockquote></details>

Yeah :(, I should have caught that.

---
___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MBQxhlN40fZ6zfwOfaA:b-54mxez) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

why is the image preview a QPushButton? It doesn't seem like needs to be clickable, and clicking it doesn't do anything. This has no real impact on Xorg, but under wayland Qt animates the button click which is confusing.
</blockquote></details>

I didn't want to change behavior of the existing file preview widget. It was already modeled as a QPushButton so I just left it as is. Is the wayland behavior new with these changes or was it the same on the file transfer widget before?

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)* status: 0 of 1 LGTMs obtained

___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MBlbQ5qA7Ymvu6bw_qV:b-xlfw9j) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I didn't want to change behavior of the existing file preview widget. It was already modeled as a QPushButton so I just left it as is. Is the wayland behavior new with these changes or was it the same on the file transfer widget before?
</blockquote></details>


The chatlog preview is clickable, opening the file in an external image viewer, which is probably why it was a QPushButton. I still don't see the button press animation for it under wayland, but I do on the image preview where the click does nothing, which is a bit confusing:

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)* status: 0 of 1 LGTMs obtained

___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MBmDEsA7Mi00XmJI1P-:b-61qumk) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>


The chatlog preview is clickable, opening the file in an external image viewer, which is probably why it was a QPushButton. I still don't see the button press animation for it under wayland, but I do on the image preview where the click does nothing, which is a bit confusing:



</blockquote></details>

can't upload any video formats, can't upload a gif over 10MB, and a gif under 10MB fails with "Content length exceeded" :rage: 

Here's a mkv with a fake file extension: [preview-qpushbutton.txt](https://github.com/qTox/qTox/files/4894877/preview-qpushbutton.txt)

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvOwECPKUFLsh5MSO:-MCjd0cE3HDSpAom7QxM:b-yrm2dw) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Yeah :(, I should have caught that.
</blockquote></details>

Replaced with the call decline button. A more reasonable person might make their own UI element but I don't really want to do that.

---
*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvz319sZ4JZn6mNBn:-MCjd71B0U1By9V0PsCM:b-896fix) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Reasonable, will add cancel on escape
</blockquote></details>

Done.

---
___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MCjdCMK-mcE60raLPzV:b-4su5az) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

can't upload any video formats, can't upload a gif under 10MB, and a gif under 10MB fails with "Content length exceeded" :rage: 

Here's a mkv with a fake file extension: [preview-qpushbutton.txt](https://github.com/qTox/qTox/files/4894877/preview-qpushbutton.txt)
</blockquote></details>

Please confirm if this fixes the problem. I wasn't seeing the same problem but did notice a difference in behavior if I manually set the flat property to false under X11. I also noticed that when i clicked on X11 I saw a border that I didn't like. I've updated the stylesheet to hide the border completely so it shouldn't appear to be a button in the image preview case at all.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175)* status: 0 of 1 LGTMs obtained

*[a discussion](https://reviewable.io/reviews/qtox/qtox/6175#-MBNvOwECPKUFLsh5MSO:-MCkBtEH5m8hA312oBoz:b8w5mvn) (no related file):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Replaced with the call decline button. A more reasonable person might make their own UI element but I don't really want to do that.
</blockquote></details>

I like the look in general. The call decline button has a white background instead of alpha around the circle, so with a dark image it has: 


Looking at the svg, it looks like the X in the middle is white but the background around the circle is transparent.. so I must be missing something there.

---
___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MCk8Nap8oQ6BC8d98fA:b-77isj0) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Please confirm if this fixes the problem. I wasn't seeing the same problem but did notice a difference in behavior if I manually set the flat property to false under X11. I also noticed that when i clicked on X11 I saw a border that I didn't like. I've updated the stylesheet to hide the border completely so it shouldn't appear to be a button in the image preview case at all.
</blockquote></details>

Unfortunately under wayland with `QT_QPA_PLATFORM=wayland` set, I still see a border and 3D-like movement on click like  before =/

On wayland without `QT_QPA_PLATFORM` set, which uses the default X11  it has no movement and no border which looks good. This is just using Qt's X11 implementation which is default even on wayland.

I'd think this is a Qt wayland bug, but the rest of our QPushButtons, like the "Send message" button from GenericChatForm don't have any 3D behaviour or border even with `QT_QPA_PLATFORM=wayland`. They're using `chatform/button.css` styling which I'd guess is the difference. I'll try setting the same styling here and see if it helps and then try to narrow down the difference.

**Review by anthonybilinski — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175#-:-MmpoVc8Ayilv5izrMV7:bg7igkv)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/widget/imagepreviewwidget.h, line 26 at r1](https://reviewable.io/reviews/qtox/qtox/6175#-MBNykgJ0P5-VV3NOpUu:-MmpoOxz6-BIbd7gPNoC:bld4423) ([raw file](https://github.com/qtox/qtox/blob/d4a8d78f583cbd0ecf52ec9c4f50a6e4482c0cbf/src/widget/imagepreviewwidget.h#L26)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Unfortunately under wayland with `QT_QPA_PLATFORM=wayland` set, I still see a border and 3D-like movement on click like  before =/

On wayland without `QT_QPA_PLATFORM` set, which uses the default X11  it has no movement and no border which looks good. This is just using Qt's X11 implementation which is default even on wayland.

I'd think this is a Qt wayland bug, but the rest of our QPushButtons, like the "Send message" button from GenericChatForm don't have any 3D behaviour or border even with `QT_QPA_PLATFORM=wayland`. They're using `chatform/button.css` styling which I'd guess is the difference. I'll try setting the same styling here and see if it helps and then try to narrow down the difference.
</blockquote></details>

I don't see this even with `QT_QPA_PLATFORM=wayland` anymore, I'm now on arch btw instead of ubuntu like before, so using Qt 5.15.2, so maybe a bug was fixed there?

This is a massive improvement even under Qt Wayland with the old behaviour, and even more so on every other platform.

**Review by anthonybilinski — COMMENTED** [review]
my :lgtm_strong: is stale apparently, so here's another one

> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6175#-:-MmpuOFE2rT73afMsXqv:bsnt48f)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
