### PR TITLE
Darker colors for login buttons

### PR DESCRIPTION
**Pull request by antis81**
@zetok This replaces PR #2367. Feel free to cherry pick the commit and close this PR.

### CODE REVIEW

**Comment by agilob** [comment]
@antis81 please put css in .css files. don't hardcode them in .cpp or .ui :<

**Comment by zetok** [comment]
@agilob I was about to merge it - I take that I shouldn't?

**Comment by antis81** [comment]
Morning :) - Will fix it later today. Btw. do you know how to use the object name selectors? Cause that's what we need here. Is it `QAbstractButton["loginButton"] {}`?

**Comment by agilob** [comment]
I don't like how people put css into .ui files, when you want to change it it hard to find it and edit.

**Comment by agilob** [comment]
pushButton->setObjectName("loginButton");

QAbstractButton#loginButton { ...style... }

**Comment by zetok** [comment]
There's a "bug" here:
1. click on `Create Profile` when `Username` field is empty
2. Error dialog window about missing username appears
3. Now `Create Profile` button has darker colour when login window is focused, independently from whether mouse hovers over it.

On a side note, I'm not quite sure if that kind of dark green should be used when for hover.

**Comment by ovalseven8** [comment]
This PR will also close https://github.com/tux3/qTox/issues/2368, right?

**Comment by zetok** [comment]
@ovalseven8 yep

**Comment by antis81** [comment]
@agilob Think we're more happy with this. I'd say we style the whole thing via CSS. If you agree, I add this here, too.

@zetok Color bug fixed as well.

**Comment by agilob** [comment]
:+1:

**Pull request merged**
