### PR TITLE
Add qTox.appdata.xml for enhance packaging integration.

### PR DESCRIPTION
**Pull request by SkyzohKey**
This pull-request allows qTox to looks better on `gnome-software`, `ubuntu-software` and others applications manager that supports the standard FreeDesktop AppData format.

ie. on gnome-software it should looks something like:
Ricin with the new appdata.xml on gnome-software

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3884)

### CODE REVIEW

**Comment by sudden6** [comment]
@SkyzohKey please format the commit message according to our https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#-git-commit-guidelines

I suggest you squash the two commits into one and prefix the your commit message with `chore(packaging):`

**Comment by SkyzohKey** [comment]
@sudden6 Done. c:

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884#-:-KWe7CW4J7duhBDpk4n-:bnfp4nl)_

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[qTox.appdata.xml, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/3884#-KWhRoA9IxR6_x_a4S1h:-KWhRoA9IxR6_x_a4S1i:b-rlvaco) ([raw file](https://github.com/qtox/qtox/blob/2fdc9cfcae38d5e2ffe8a9fd27b7af5a73899f98/qTox.appdata.xml#L32)):_

> ``` XML
>   </ul>
>   <p>
>     qTox is a free and open source software, built by it's community for it's community.
> ```

s/it's//

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884)_

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[qTox.appdata.xml, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/3884#-KWhRoA9IxR6_x_a4S1h:-KWhh9-c75MM7J5V3kaR:b-t36ow9) ([raw file](https://github.com/qtox/qtox/blob/2fdc9cfcae38d5e2ffe8a9fd27b7af5a73899f98/qTox.appdata.xml#L32)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> s/it's//
> </details>
> That sounds silly in my ears. If you want that changed `s/it's/the`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

_[qTox.appdata.xml, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/3884#-KWhRoA9IxR6_x_a4S1h:-KWhl9bPXyLJUQeI_1vR:b-o8kq93) ([raw file](https://github.com/qtox/qtox/blob/2fdc9cfcae38d5e2ffe8a9fd27b7af5a73899f98/qTox.appdata.xml#L32)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> That sounds silly in my ears. If you want that changed `s/it's/the`.
> </details>
> Yeah, that would be better.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884)_

**Comment by zetok** [comment]
Perhaps move `qTox.appdata.xml` under `res/` ?

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884#-:-KWiHnpXXBkuCEmKfCIX:b-9xm0mx)_

**Comment by zetok** [comment]
Ok, I've moved the file.

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3884#-:-KWnFyZw0RMNdS3oXhDL:bnfp4nl)_

**Pull request merged**
