### PR TITLE
fix(audio): Fix ugly conference audio with 3<= speakers

### LINKED ISSUE #3359: Voice becomes antsy and ragged when making a group voice call
##### Brief Description

When creating group and only two people talks, voices sounds pretty good. But when in voice call talks more than two people (in my case - three humans), voice becomes antsy and ragged.

OS: Windows 10 (my friends have Linux installed and they have this issue too)
qTox version: v1.4.0-117-g792103f
Commit hash: 792103f
Qt: 5.5.1
Hardware: ASUS T200TA

Reproducible: Always
##### Steps to reproduce
1. Create group.
2. Invite three humans.
3. Accept talk for all people in group.
##### Observed Behavior

Crappy voices.
##### Expected Behavior

Pretty good voices.
##### Additional Info

I attached a pretty clean [qtox.log](https://github.com/tux3/qTox/files/300567/qtox.zip) in ZIP.

### PR DESCRIPTION
**Pull request by ghost**
Implement alSource for every conference speaker
Fixes #3359

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4138)

### CODE REVIEW

**Comment by agrecascino** [comment]
SHOW YOURSELF EVIL DEMON!

**Comment by Diadlo** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/audio/audio.cpp, line 689 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2Cc2AIjBY2sSvhbn:-KcK2Cc2AIjBY2sSvhbo:b-meegiw) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/audio/audio.cpp#L689)):*
> ```cpp
> }
> 
> void Audio::subscribeOutput(QVector<ALuint> &sids)
> ```

For me, this function seems useless. You can use `for` +  `Audio::subscribeOutput` call

---

*[src/audio/audio.cpp, line 721 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2UsDmH2Q_Xa6rzZm:-KcK2UsDmH2Q_Xa6rzZn:br29tb2) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/audio/audio.cpp#L721)):*
> ```cpp
> }
> 
> void Audio::unsubscribeOutput(QVector<ALuint> &sids) {
> ```

Move `{` on new line. And same as above

---

*[src/core/coreav.cpp, line 502 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2u4WfK5nSTDKNpnm:-KcK2u4WfK5nSTDKNpnn:b-97ukke) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L502)):*
> ```cpp
> 
>     if (call.alSource.size() <= peer)
>         call.alSource.resize(peer + 1);
> ```

I think, better will be add using [reserve](http://doc.qt.io/qt-4.8/qvector.html#reserve) with `oldSize * 2`

---

*[src/core/coreav.cpp, line 592 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK4Ov75c0zgzTI7tE3:-KcK4Ov75c0zgzTI7tE4:bv9c4zg) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L592)):*
> ```cpp
> 
> /**
>  * @brief Called from core to notify about peer changes
> ```

Better write, what this method do

---

*[src/core/coreav.cpp, line 601 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK5Mra2GAcy0OSC5x4:-KcK5Mra2GAcy0OSC5x5:b-et970y) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L601)):*
> ```cpp
>     Q_UNUSED(peerId);
> 
>     if (change != TOX_CONFERENCE_STATE_CHANGE_PEER_EXIT || !isGroupAvEnabled(groupId))
> ```

I'm a bit confused. Why we unsubscribe, when peer comes?

---

*[src/core/coreav.cpp, line 609 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK4YGTcKG09OB3tW7K:-KcK4YGUbNWno-6ugXd8:b-jtt5ej) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L609)):*
> ```cpp
>     // Unsubscribe from last audio source
>     auto &alSource = groupCalls[groupId].alSource;
>     Audio::getInstance().unsubscribeOutput(alSource.last());
> ```

Why `last()` ?

---

*[src/core/toxcall.h, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK5gCwrk3ZEA6MS71a:-KcK5gCx_bFAs5TmFQ1H:b-goyl76) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/toxcall.h#L32)):*
> ```objc
>      ToxCall& operator=(ToxCall&& other) noexcept;
> 
>      inline void clearAlSource() {alSource = 0;}
> ```

Make multiline
```
{
    alSource = 0;
}
```

---

*[src/core/toxcall.h, line 82 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK5ls40-0Kn08TGJnt:-KcK5ls40-0Kn08TGJnu:b-1gmq3x) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/toxcall.h#L82)):*
> ```objc
>         alSource.erase(alSource.begin(), alSource.end());
>     }
>     QVector<quint32> alSource;
> ```

Add docs in cpp file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4138)*

**Comment by Diadlo** [comment]
Please, use reviewable to mark discussion as done

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/core/coreav.cpp, line 602 at r2](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcOl9uN23-H6WBRDKwt:-KcOl9uN23-H6WBRDKwu:b-v36vzj) ([raw file](https://github.com/qtox/qtox/blob/36e272575aeefb0f8ae8b6d0512dab07a36138f2/src/core/coreav.cpp#L602)):*
> ```cpp
> 
>     // Continue only when peer left group and AV enabled in group
>     if (change != TOX_CONFERENCE_STATE_CHANGE_PEER_EXIT || !isGroupAvEnabled(groupId))
> ```

No. You continute only when peer NOT EXIT the group.

---

*[src/core/coreav.cpp, line 614 at r2](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcOlYkQzaWk2s39CjWR:-KcOlYkQzaWk2s39CjWS:bw3bsx1) ([raw file](https://github.com/qtox/qtox/blob/36e272575aeefb0f8ae8b6d0512dab07a36138f2/src/core/coreav.cpp#L614)):*
> ```cpp
>      */
>     auto &alSource = groupCalls[groupId].alSource;
>     Audio::getInstance().unsubscribeOutput(alSource.last());
> ```

You have peerId, who left group. Why do you unsubscribe exactly last?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4138#-:-KcOl7KdQD-UvbXI8yHs:b-xyytc8)*

**Comment by ghost** [comment]
Review status: 6 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/audio/audio.cpp, line 689 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2Cc2AIjBY2sSvhbn:-KcOtTU2vueteRQUcWkI:bcbjjnr) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/audio/audio.cpp#L689)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

For me, this function seems useless. You can use `for` +  `Audio::subscribeOutput` call
</blockquote></details>

This function required to don't change code in ToxCall::ToxCall(uint32_t CallId) constructor

---

*[src/audio/audio.cpp, line 721 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2UsDmH2Q_Xa6rzZm:-KcOtozB4FSM0J8X8RfG:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/audio/audio.cpp#L721)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Move `{` on new line. And same as above
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 502 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2u4WfK5nSTDKNpnm:-KcOttAqQ43MNI7OYb2C:bg6q46v) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L502)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think, better will be add using [reserve](http://doc.qt.io/qt-4.8/qvector.html#reserve) with `oldSize * 2`
</blockquote></details>

I commited better resize code

---

*[src/core/coreav.cpp, line 592 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK4Ov75c0zgzTI7tE3:-KcOu78WOUqjPJZQ-qyb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L592)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Better write, what this method do
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 602 at r2](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcOl9uN23-H6WBRDKwt:-KcOuHPYYClc1JUlDlJT:b-qgejus) ([raw file](https://github.com/qtox/qtox/blob/36e272575aeefb0f8ae8b6d0512dab07a36138f2/src/core/coreav.cpp#L602)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

No. You continute only when peer NOT EXIT the group.
</blockquote></details>

Note the return after this. So when change equals to TOX_CONFERENCE_STATE_CHANGE_PEER_EXIT, isGroupAvEnabled() condition checked and when it is true, return after this "if" isn't reached and execution continues.

---

*[src/core/coreav.cpp, line 614 at r2](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcOlYkQzaWk2s39CjWR:-KcOv4QC8JFJTRdtLlHL:b-cx62r9) ([raw file](https://github.com/qtox/qtox/blob/36e272575aeefb0f8ae8b6d0512dab07a36138f2/src/core/coreav.cpp#L614)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

You have peerId, who left group. Why do you unsubscribe exactly last?
</blockquote></details>

Last commit should make it more clear. It doesn't associate alSource with individual peer, so we only have to keep enough of alSources allocated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4138)*

**Comment by ghost** [comment]
Review status: 6 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/toxcall.h, line 32 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK5gCwrk3ZEA6MS71a:-KcOy4JneEYDUYavZ9ku:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/toxcall.h#L32)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Make multiline
```
{
    alSource = 0;
}
```
</blockquote></details>

Done.

---

*[src/core/toxcall.h, line 82 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK5ls40-0Kn08TGJnt:-KcOy5D1980UbNrtUfPp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/toxcall.h#L82)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Add docs in cpp file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4138)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/coreav.cpp, line 502 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2u4WfK5nSTDKNpnm:-KcOxsNyhpQcLT5_plY_:b297hlz) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L502)):*
<details><summary><i>Previously, 007-agent wrote…</i></summary><blockquote>

I commited better resize code
</blockquote></details>

Better. But why you don't want to reserve memory?
malloc call is too expensive

---

*[src/core/coreav.cpp, line 602 at r2](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcOl9uN23-H6WBRDKwt:-KcPCkzeU08XkccokUCF:b438g3a) ([raw file](https://github.com/qtox/qtox/blob/36e272575aeefb0f8ae8b6d0512dab07a36138f2/src/core/coreav.cpp#L602)):*
<details><summary><i>Previously, 007-agent wrote…</i></summary><blockquote>

Note the return after this. So when change equals to TOX_CONFERENCE_STATE_CHANGE_PEER_EXIT, isGroupAvEnabled() condition checked and when it is true, return after this "if" isn't reached and execution continues.
</blockquote></details>

Sorry, misread. But what about `TOX_CONFERENCE_STATE_CHANGE_PEER_NAME_CHANGE`? You will unsubscribe on this change

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4138)*

**Comment by ghost** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/coreav.cpp, line 502 at r1](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcK2u4WfK5nSTDKNpnm:-KcPZUAfl3Qmcuqc1GlJ:b-3t0wkm) ([raw file](https://github.com/qtox/qtox/blob/a0c5e491a340f26e1042c882de36eb389c713639/src/core/coreav.cpp#L502)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Better. But why you don't want to reserve memory?
malloc call is too expensive
</blockquote></details>

It shouldn't be too expensive for small allocations. Though if it is required, reserve can happen for example at ToxGroupCall construction, but amount of ints to reserve is up to you.

---

*[src/core/coreav.cpp, line 602 at r2](https://reviewable.io:443/reviews/qtox/qtox/4138#-KcOl9uN23-H6WBRDKwt:-KcPe8ORuP49sRqA3Gg3:b-kfe6p4) ([raw file](https://github.com/qtox/qtox/blob/36e272575aeefb0f8ae8b6d0512dab07a36138f2/src/core/coreav.cpp#L602)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Sorry, misread. But what about `TOX_CONFERENCE_STATE_CHANGE_PEER_NAME_CHANGE`? You will unsubscribe on this change
</blockquote></details>

TOX_CONFERENCE_STATE_CHANGE_PEER_NAME_CHANGE != TOX_CONFERENCE_STATE_CHANGE_PEER_EXIT -> return from function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4138)*

**Comment by zetok** [comment]
Since #4146 got merged, closing.

**Pull request closed without merging**
