### PR TITLE
Invalid memory

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5936)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5936)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 99 at r1](https://reviewable.io/reviews/qtox/qtox/5936#-LugR6D43cPErHjO8N9C:-LugR6D524zOCgrecwnA:b-e6uydd) ([raw file](https://github.com/qtox/qtox/blob/a02c900de9ae4680a22085cc0e4fc65247caf184/src/core/corefile.cpp#L99)):*
> ```cpp
>     size_t nameLength = 0;
>     uint8_t avatarHash[TOX_HASH_LENGTH];
>     if (!data.isEmpty()) {
> ```

AFAICT it is an error to try to call the function with `data.isEmpty() == true` maybe check that first and return an error? At the moment the structure of this function looks quite confusing to me.

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5936)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 99 at r1](https://reviewable.io/reviews/qtox/qtox/5936#-LugR6D43cPErHjO8N9C:-LuhUB-4DWME78LphFeK:b-o1kcob) ([raw file](https://github.com/qtox/qtox/blob/a02c900de9ae4680a22085cc0e4fc65247caf184/src/core/corefile.cpp#L99)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

AFAICT it is an error to try to call the function with `data.isEmpty() == true` maybe check that first and return an error? At the moment the structure of this function looks quite confusing to me.
</blockquote></details>

Calling `CoreFile::sendAvatarFile` with size 0 data is valid, and means "user has no avatar", as mentioned in tox.h:1906. This change just keeps `avatarHash` in scope until its last use.  I agree this function is a bit weird, sending an actual avatar and clearing avatar could be split to different functions to reduce confusion, and the error handling is already split into its own function on `master`, but I'm just going for a minimal bug fix for `v1.17-dev` branch

**Review by sudden6 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5936)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 99 at r1](https://reviewable.io/reviews/qtox/qtox/5936#-LugR6D43cPErHjO8N9C:-LuhartU6R1kWWBgHBln:b-68cj1e) ([raw file](https://github.com/qtox/qtox/blob/a02c900de9ae4680a22085cc0e4fc65247caf184/src/core/corefile.cpp#L99)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Calling `CoreFile::sendAvatarFile` with size 0 data is valid, and means "user has no avatar", as mentioned in tox.h:1906. This change just keeps `avatarHash` in scope until its last use.  I agree this function is a bit weird, sending an actual avatar and clearing avatar could be split to different functions to reduce confusion, and the error handling is already split into its own function on `master`, but I'm just going for a minimal bug fix for `v1.17-dev` branch
</blockquote></details>

ok, then it makes sense for this fix

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5936#-:-Luhawhy6QfWDs_4dI27:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
