### PR TITLE
Update bootstrap.sh, match nodes to wiki.tox.im

### PR DESCRIPTION
**Pull request by dubslow**
This might help #221 or #237, several of the old nodes are probably offline

### CODE REVIEW

**Comment by dubslow** [comment]
Here's my log that caused me to update the node list:

https://gist.github.com/dubslow/3582eba9e42ee6bce3b6

Note that ChauffeR is no longer on the wiki, yet toxcore was apparently able to successfully connect to the node ([otherwise](https://github.com/tux3/qTox/blob/master/core.cpp#L783) the log would have the error message instead).

The same goes for astonex on the retry; his ip and id are different now, yet apparently toxcore was able to connect to the old node.

This suggests that toxcore doesn't sufficiently ensure that nodes are operating properly (i.e., up to date).

**Comment by dubslow** [comment]
Wait, even this won't help, because it doesn't overwrite the old settings file...

**Comment by msteinbeck** [comment]
According to: https://github.com/irungentoo/toxcore/blob/master/INSTALL.md libsodium in version 0.5.0 should be used. Maybe the documentation is outdated or it doesn't matter, but I decided to take this tag, because the instructions do so.

**Comment by dubslow** [comment]
No, several weeks ago (the time of the first commit here, which I proceeded to forget about) I asked irungentoo, and he (and some others) said he used 0.6.1, so I updated bootstrap here. INSTALL.md is just as out of date as bootstrap.sh currently is.

**Comment by tux3** [comment]
Just because qTox doesn't immediatly connect to the DHT doesn't mean that the nodes are offline, as far as I know. It's probably a good idea to match the wiki tho.

**Pull request merged**
