### PR TITLE
[Refactor] Add AboutFriend model

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4622)

### CODE REVIEW

**Comment by Talkless** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/about/aboutfriendform.cpp, line 50 at r2](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtN7KV1jURx0tyQO1Ly:-KtN7KV1jURx0tyQO1Lz:b-gcnk8m) ([raw file](https://github.com/qtox/qtox/blob/60cede36d91bfd774b1d3fea513a1e04c82950ba/src/widget/about/aboutfriendform.cpp#L50)):*
> ```cpp
>     if (!ui->autoacceptfile->isChecked()) {
>         ui->autoacceptfile->setChecked(false);
>         about->setAutoAcceptDir("");
> ```

Better default constructor `{}`.

---

*[src/widget/about/aboutfriendform.cpp, line 54 at r2](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtN7usgshmJKSo6rqlR:-KtN7usgshmJKSo6rqlS:bdcqlli) ([raw file](https://github.com/qtox/qtox/blob/60cede36d91bfd774b1d3fea513a1e04c82950ba/src/widget/about/aboutfriendform.cpp#L54)):*
> ```cpp
>     } else if (ui->autoacceptfile->isChecked()) {
>         QString dir = QFileDialog::getExistingDirectory(
>                     Q_NULLPTR, tr("Choose an auto accept directory", "popup title"), dir);
> ```

`getExistingDirectory()` is getting `dir` as argument, a variable that will be result of `getExistingDirectory()`call itself? Is this defined behavior?

---

*[src/widget/about/aboutfriendform.cpp, line 86 at r2](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtN8MpeFMQDE2u_bYRx:-KtN8MpfHmVdq9IvVYNf:b3otbxl) ([raw file](https://github.com/qtox/qtox/blob/60cede36d91bfd774b1d3fea513a1e04c82950ba/src/widget/about/aboutfriendform.cpp#L86)):*
> ```cpp
> {
>     QString dir = QFileDialog::getExistingDirectory(
>                 Q_NULLPTR, tr("Choose an auto accept directory", "popup title"), dir);
> ```

Same comment as above about `dir`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622)*

**Comment by Diadlo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/about/aboutfriendform.cpp, line 50 at r2](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtN7KV1jURx0tyQO1Ly:-KtNJRd_0LfxeSSwYAGI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/60cede36d91bfd774b1d3fea513a1e04c82950ba/src/widget/about/aboutfriendform.cpp#L50)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Better default constructor `{}`.
</blockquote></details>

Done.

---

*[src/widget/about/aboutfriendform.cpp, line 54 at r2](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtN7usgshmJKSo6rqlR:-KtNIN-zj-nIwtAOAxNA:b-s82zrb) ([raw file](https://github.com/qtox/qtox/blob/60cede36d91bfd774b1d3fea513a1e04c82950ba/src/widget/about/aboutfriendform.cpp#L54)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`getExistingDirectory()` is getting `dir` as argument, a variable that will be result of `getExistingDirectory()`call itself? Is this defined behavior?
</blockquote></details>

Yes, `dir` has uninitialized value, it's the reason of the #4600.
But fix is out of the scope of the refactoring PR. Fixed in #4623

---

*[src/widget/about/aboutfriendform.cpp, line 86 at r2](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtN8MpeFMQDE2u_bYRx:-KtNJSRhmsC7BtJDcxJT:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/60cede36d91bfd774b1d3fea513a1e04c82950ba/src/widget/about/aboutfriendform.cpp#L86)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Same comment as above about `dir`.
</blockquote></details>

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622)*

**Comment by noavarice** [comment]
Review status: 0 of 11 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/about/aboutfriend.cpp, line 60 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcBSow5R8rf4SVLCAi:-KtcBSow5R8rf4SVLCAj:b-v17grj) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L60)):*
> ```cpp
>     Settings::getInstance().setAutoAcceptDir(pk, path);
>     Settings::getInstance().savePersonal();
>     emit autoAcceptDirChanged(path);
> ```

This signal will be emitted even if auto-accept dir was not actually changed. Emitting `autoAcceptDirChanged` should be delegated to `Settings` as an option

---

*[src/model/about/aboutfriend.cpp, line 66 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcB3OeWdgGM1d0-r_F:-KtcB3OeWdgGM1d0-r_G:b-rmiorg) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L66)):*
> ```cpp
> {
>     const ToxPk pk = f->getPublicKey();
>     const int value = static_cast<int>(Settings::getInstance().getAutoAcceptCall(pk));
> ```

Cast to `IAboutFriend::AutoAcceptCall` directly

---

*[src/model/about/aboutfriend.cpp, line 73 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcDGFOt8xy4e8vNAyo:-KtcDGFOt8xy4e8vNAyp:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L73)):*
> ```cpp
> {
>     const ToxPk pk = f->getPublicKey();
>     const int value = static_cast<int>(flag);
> ```

Same as above

---

*[src/model/about/aboutfriend.cpp, line 77 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcDofajVF2rHaK-rWs:-KtcDofajVF2rHaK-rWt:bza008r) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L77)):*
> ```cpp
>     Settings::getInstance().setAutoAcceptCall(pk, sFlag);
>     Settings::getInstance().savePersonal();
>     emit autoAcceptCallChanged(flag);
> ```

`autoAcceptCallChanged` is also emitting from `Settings`

---

*[src/model/about/aboutfriend.cpp, line 91 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcFllmwTgZkGqeSpvO:-KtcFllmwTgZkGqeSpvP:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L91)):*
> ```cpp
>     Settings::getInstance().setAutoGroupInvite(pk, enabled);
>     Settings::getInstance().savePersonal();
>     emit autoGroupInviteChanged(enabled);
> ```

Same as above

---

*[src/widget/about/aboutfriendform.cpp, line 46 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcIRSLMwhivpA8rPJj:-KtcIRSLMwhivpA8rPJk:b-eao7t0) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L46)):*
> ```cpp
> }
> 
> void AboutFriendForm::onAutoAcceptDirClicked()
> ```

Use parameters passing from signals

---

*[src/widget/about/aboutfriendform.cpp, line 69 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcIYoVMwqZKzsan5OC:-KtcIYoVMwqZKzsan5OD:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L69)):*
> ```cpp
> 
> void AboutFriendForm::onAutoAcceptCallClicked()
> {
> ```

Same as above

---

*[src/widget/about/aboutfriendform.cpp, line 78 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcIavkgOecG0CZDxf1:-KtcIavkgOecG0CZDxf2:b47xon6) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L78)):*
> ```cpp
>  * @brief Sets the AutoGroupinvite status and saves the settings.
>  */
> void AboutFriendForm::onAutoGroupInvite()
> ```

`onAutoGroupInvite*Changed*`. Also there must be `bool checked` parameter

---

*[src/widget/about/aboutfriendform.cpp, line 94 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcInOAqbeGxs5SX1H3:-KtcInOAqbeGxs5SX1H4:b-szkn7q) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L94)):*
> ```cpp
>  * @brief Called when user clicks the bottom OK button, save all settings
>  */
> void AboutFriendForm::onAcceptedClicked()
> ```

Same about signal parameters

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622)*

**Comment by noavarice** [comment]
Reviewed 8 of 12 files at r1, 4 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[src/model/about/aboutfriend.cpp, line 60 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcBSow5R8rf4SVLCAi:-Ktf3YJmKA1kPZ_S0_Ep:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L60)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

This signal will be emitted even if auto-accept dir was not actually changed. Emitting `autoAcceptDirChanged` should be delegated to `Settings` as an option
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.cpp, line 66 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcB3OeWdgGM1d0-r_F:-Ktf4O8mw01w_UhOMOR0:bczuo0m) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L66)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Cast to `IAboutFriend::AutoAcceptCall` directly
</blockquote></details>

It can't be casted directly because of different types. Will be fixed in next PR

---

*[src/model/about/aboutfriend.cpp, line 73 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcDGFOt8xy4e8vNAyo:-Ktf4Q2fgBQuEcJ6Eara:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L73)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Same as above

---

*[src/model/about/aboutfriend.cpp, line 77 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcDofajVF2rHaK-rWs:-Ktf4SNaigHxGU0bo7pW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L77)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`autoAcceptCallChanged` is also emitting from `Settings`
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.cpp, line 91 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcFllmwTgZkGqeSpvO:-Ktf4T8rPo8sSRxVHt0P:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/model/about/aboutfriend.cpp#L91)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/widget/about/aboutfriendform.cpp, line 46 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcIRSLMwhivpA8rPJj:-Ktf5oYJGbdvOZCJDb3M:b-3mip5k) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L46)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Use parameters passing from signals
</blockquote></details>

Out of the scope of this PR

---

*[src/widget/about/aboutfriendform.cpp, line 69 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcIYoVMwqZKzsan5OC:-Ktf5qz66Z9aRVi93Trf:b-3mip5k) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L69)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Out of the scope of this PR

---

*[src/widget/about/aboutfriendform.cpp, line 78 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcIavkgOecG0CZDxf1:-Ktf5sQGdbr6C8DtCdck:b-3mip5k) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L78)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`onAutoGroupInvite*Changed*`. Also there must be `bool checked` parameter
</blockquote></details>

Out of the scope of this PR

---

*[src/widget/about/aboutfriendform.cpp, line 94 at r3](https://reviewable.io:443/reviews/qtox/qtox/4622#-KtcInOAqbeGxs5SX1H3:-Ktf7WuRQ7hvrS4NSMmT:b-3mip5k) ([raw file](https://github.com/qtox/qtox/blob/89c9734da475c454b59e5b18c07316272965e1b6/src/widget/about/aboutfriendform.cpp#L94)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same about signal parameters
</blockquote></details>

Out of the scope of this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622)*

**Comment by noavarice** [comment]
Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4622#-:-Ktf8uPhHaKNEfCUQkWp:b-jbsf8z)*

**Pull request merged**
