### PR TITLE
fix(settings): automatically disable UDP when a proxy is set

### LINKED ISSUE #5174: qTox accepts bogus SOCKS5 port and "reconnects" successfully
In the connected qTox enable IPv6 and enable UDP are set. Proxy type is changed from None to SOCKS5, Address is set to localhost, and a bogus port 19059 is selected which has nothing that listens on it. Hitting the Reconnect button "reconnects" successfully, instead of failing.

This is a security bug, because it can lead the user to believe that he is connected through Tor or other proxy when he really isn't.

This port isn't occupied:
```
$ telnet 127.0.0.1 19059
Trying 127.0.0.1...
telnet: connect to address 127.0.0.1: Connection refused
telnet: Unable to connect to remote host
```

qTox-1.15.0
toxcore-0.2.2
FreeBSD 11.1, qTox is installed from the port.

### PR DESCRIPTION
**Pull request by sudden6**
fixes: #5174

- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5189)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Reviewed 2 of 2 files at r1.
Review status: 0 of 1 LGTMs obtained

---

*[src/core/toxoptions.cpp, line 112 at r1](https://reviewable.io/reviews/qtox/qtox/5189#-LGHq1IMBBkmiG1T8ldH:-LGHq1IMBBkmiG1T8ldI:b-ug8042) ([raw file](https://github.com/qtox/qtox/blob/e7c8432f3d80a3e7a323733769e06109d186ce28/src/core/toxoptions.cpp#L112)):*
> ```cpp
>     }
> 
>     tox_options_set_udp_enabled(*toxOptions, !forceTCP);
> ```

would be nice to keep set_udp_enabled with the other network settings like ipv6, either by duplicating the forceTCP check above the proxy block, or by moving all network settings down here with set_udp_enabled.

---

*[src/widget/form/settings/advancedform.cpp, line 181 at r1](https://reviewable.io/reviews/qtox/qtox/5189#-LGHqmugC-4VZLXeuqcb:-LGHqmuh4jG_xp-K0wmj:bm2ldtb) ([raw file](https://github.com/qtox/qtox/blob/e7c8432f3d80a3e7a323733769e06109d186ce28/src/widget/form/settings/advancedform.cpp#L181)):*
> ```cpp
>     Settings::getInstance().setForceTCP(!enableUdp);
>     bodyUI->cbEnableLanDiscovery->setEnabled(enableUdp);
>     bodyUI->cbEnableLanDiscovery->setChecked(false);
> ```

if you have UDP disabled, set a proxy, then disable the proxy, UDP becomes checked.

---

*[src/widget/form/settings/advancedform.cpp, line 212 at r1](https://reviewable.io/reviews/qtox/qtox/5189#-LGHquOL0FrhiP8wv52S:-LGHquOL0FrhiP8wv52T:b8yppgj) ([raw file](https://github.com/qtox/qtox/blob/e7c8432f3d80a3e7a323733769e06109d186ce28/src/widget/form/settings/advancedform.cpp#L212)):*
> ```cpp
>     // enabling UDP and proxy can be a privacy issue
>     bodyUI->cbEnableUDP->setEnabled(!proxyEnabled);
>     bodyUI->cbEnableUDP->setChecked(!proxyEnabled);
> ```

disabling sub-features is inconsistent.
1) with "Show system tray icon", "start in tray" remains checked, but disabled when "Show system tray icon" is disabled.
2) with "Enable UDP", Enabled LAN discovery is disabled and unchecked, and doesn't re-check when Enable LAN discovery is re-checked.
3) With yours, setting proxy un-checks and disables enable UDP, and it IS re-checked when proxy is changed.

We should have the same behaviour instead of 3 different ones. I think probably disabling but leaving checked is best, but if we disable and uncheck I think we should definitely re-check when parent is re-enabled.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5189)*

**Comment by sudden6** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[src/core/toxoptions.cpp, line 112 at r1](https://reviewable.io/reviews/qtox/qtox/5189#-LGHq1IMBBkmiG1T8ldH:-LGKpYcZ3Ei87Rhn3jhi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/e7c8432f3d80a3e7a323733769e06109d186ce28/src/core/toxoptions.cpp#L112)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

would be nice to keep set_udp_enabled with the other network settings like ipv6, either by duplicating the forceTCP check above the proxy block, or by moving all network settings down here with set_udp_enabled.
</blockquote></details>

Done.

---

*[src/widget/form/settings/advancedform.cpp, line 181 at r1](https://reviewable.io/reviews/qtox/qtox/5189#-LGHqmugC-4VZLXeuqcb:-LGKpZvZENMj2od9AN9G:bxpajcn) ([raw file](https://github.com/qtox/qtox/blob/e7c8432f3d80a3e7a323733769e06109d186ce28/src/widget/form/settings/advancedform.cpp#L181)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

if you have UDP disabled, set a proxy, then disable the proxy, UDP becomes checked.
</blockquote></details>

This was actually the intended behaviour from my side, because UDP should be enabled by default and marked clearly as disabled when a proxy is active. There may be better stuff to visualize this, but then I think we should do this in another PR.

---

*[src/widget/form/settings/advancedform.cpp, line 212 at r1](https://reviewable.io/reviews/qtox/qtox/5189#-LGHquOL0FrhiP8wv52S:-LGKqRAH37_JIoKC4pCF:bf2gq54) ([raw file](https://github.com/qtox/qtox/blob/e7c8432f3d80a3e7a323733769e06109d186ce28/src/widget/form/settings/advancedform.cpp#L212)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

disabling sub-features is inconsistent.
1) with "Show system tray icon", "start in tray" remains checked, but disabled when "Show system tray icon" is disabled.
2) with "Enable UDP", Enabled LAN discovery is disabled and unchecked, and doesn't re-check when Enable LAN discovery is re-checked.
3) With yours, setting proxy un-checks and disables enable UDP, and it IS re-checked when proxy is changed.

We should have the same behaviour instead of 3 different ones. I think probably disabling but leaving checked is best, but if we disable and uncheck I think we should definitely re-check when parent is re-enabled.
</blockquote></details>

Changed to 3. here, I think we should rethink these settings at some time.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5189)*

**Comment by tox-user** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5189#-:-LGMj2Ho7qoeyrNT3B8X:b-jbsf8z)*

**Comment by tox-user** [comment]
~~LGTM~~

The UI part has some problems. When you toggle UDP mode it will always set LAN discovery to the opposite. When UDP is disabled LAN will be enabled.

**Comment by sudden6** [comment]
Forgot to push...

**Comment by tox-user** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5189#-:-LGRipg-71Gy3pcqpSV_:b-jbsf8z)*

**Pull request merged**
