### PR TITLE
feat(ui): Add ability to disable LAN discovery

### LINKED ISSUE #4074: Still no option to disable local peer discovery in the settings?
OS: Windows 7 Ultimate, SP1 (64-bit)
qTox: v1.7.0
Commit hash: 12c21b21d2d62a27b0002c1add7e4d7faa0d018d
toxcore: v0.1.3
Qt: v5.5.1

Disabling local peer discovery should have been [possible](/TokTok/c-toxcore/pull/306) since v0.1.1 of c-toxcore, but it seems that qTox still doesn't provide a way to do that via the settings.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #4074

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5059)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 6 files at r1.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---

*[src/core/core.cpp, line 138 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P0eBp6gIvBjipC-oq:-L9P0eBp6gIvBjipC-or:b36dqgl) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/core/core.cpp#L138)):*
> ```cpp
>     bool forceTCP = s->getForceTCP();
>     // LAN requiring UDP is a toxcore limitation, ideally wouldn't be related
>     const bool enabelLanDiscovery = s->getEnableLanDiscovery() && !forceTCP;
> ```

typo `enableLanDiscovery`, make the others const too?

---

*[src/persistence/settings.h, line 300 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P0wCw576EiIhiYefU:-L9P0wCxB8Pb8iYv8dvC:blthju3) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/persistence/settings.h#L300)):*
> ```objc
>     SIGNAL_IMPL(Settings, enableIPv6Changed, bool enabled)
>     SIGNAL_IMPL(Settings, forceTCPChanged, bool enabled)
> 	SIGNAL_IMPL(Settings, enableLanDiscoveryChanged, bool enabled)
> ```

use spaces

---

*[src/persistence/settings.cpp, line 1241 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P1-Vj3Fjoovuw6KXj:-L9P1-Vj3Fjoovuw6KXk:blthju3) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/persistence/settings.cpp#L1241)):*
> ```cpp
> 
>     if (enabled != enableLanDiscovery) {
>     	enableLanDiscovery = enabled;
> ```

use spaces

---

*[src/widget/form/settings/advancedform.cpp, line 178 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P1Lgr3SZQ4-zLnvCY:-L9P1Lgr3SZQ4-zLnvCZ:bb7ozr7) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/widget/form/settings/advancedform.cpp#L178)):*
> ```cpp
> void AdvancedForm::on_cbEnableUDP_stateChanged()
> {
> 	const bool enableUdp = bodyUI->cbEnableUDP->isChecked();
> ```

tabs

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5059)*

**Comment by anthonybilinski** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/core.cpp, line 138 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P0eBp6gIvBjipC-oq:-L9P7bT49KveTpJ9J4nW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/core/core.cpp#L138)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `enableLanDiscovery`, make the others const too?
</blockquote></details>

Done.

---

*[src/persistence/settings.h, line 300 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P0wCw576EiIhiYefU:-L9P7cExC85IQXn1gQhC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/persistence/settings.h#L300)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use spaces
</blockquote></details>

Done.

---

*[src/persistence/settings.cpp, line 1241 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P1-Vj3Fjoovuw6KXj:-L9P7col6v8i7mDCSW4C:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/persistence/settings.cpp#L1241)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use spaces
</blockquote></details>

Done.

---

*[src/widget/form/settings/advancedform.cpp, line 178 at r1](https://beta.reviewable.io/reviews/qtox/qtox/5059#-L9P1Lgr3SZQ4-zLnvCY:-L9P7dPK2T_ZLCJJja2d:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1744da29e46f541af37865832e1bab1484c2da21/src/widget/form/settings/advancedform.cpp#L178)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

tabs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5059)*

**Comment by sudden6** [comment]
TravisCI fails, https://travis-ci.org/qTox/qTox/jobs/363008206#L2628

**Comment by sudden6** [comment]
Reviewed 3 of 4 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5059)*

**Comment by anthonybilinski** [comment]
>TravisCI fails

Fixed

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5059#-:-L9RK08k7HDr61Mu40L6:b-jbsf8z)*

**Pull request merged**
