### PR TITLE
fix(ui): Improved notifications

### PR DESCRIPTION
**Pull request by Monsterovich**
изображение

изображение

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5674)

### CODE REVIEW

**Comment by sudden6** [comment]
Can you please implement a setting that disables printing the message content and sender to the notifications?

**Comment by Monsterovich** [comment]
>Can you please implement a setting that disables printing the message content and sender to the notifications?

Should I hide an avatar too?

**Comment by Monsterovich** [comment]
>Can you please implement a setting that disables printing the message content and sender to the notifications?

Done.

изображение

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, 6 of 8 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5674)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 17 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfY9tt2BILh0hwKdP9R:-LfY9tt2BILh0hwKdP9S:b-jfwqmt) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/CMakeLists.txt#L17)):*
> ```CMake
> option(SVGZ_ICON "Compress the SVG icon of qTox" ON)
> option(ASAN "Compile with AddressSanitizer" OFF)
> option(DESKTOP_NOTIFICATIONS "Use snorenotify for desktop notifications" ON)
> ```

To enable this by default we would need to add libsnorenotify to the CI system, if you really want to do it, make a separate PR for this.
___
*[src/platform/desktop_notifications/desktopnotify.h, line 15 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYATNnEvSQkZkUQBW-:-LfYATNnEvSQkZkUQBW0:b-41pb3u) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/platform/desktop_notifications/desktopnotify.h#L15)):*
> ```objc
>     DesktopNotify();
> 
>     enum MessageType {
> ```

use an `enum class` here for the type safety
___
*[src/widget/widget.cpp, line 1384 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYAzia978IwNimMm2K:-LfYAzia978IwNimMm2L:b-smot2f) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1384)):*
> ```cpp
>         ui->friendList->trackWidget(widget);
> #if DESKTOP_NOTIFICATIONS
>         const Settings& s = Settings::getInstance();
> ```

`Widget` already has a reference to `Settings`, don't use `Settings::getInstance()`
___
*[src/widget/widget.cpp, line 1433 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYB7m05OqEqwCvIHbn:-LfYB7m05OqEqwCvIHbo:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1433)):*
> ```cpp
>     widget->updateStatusLight();
> #if DESKTOP_NOTIFICATIONS
>     const Settings& s = Settings::getInstance();
> ```

same
___
*[src/widget/widget.cpp, line 1520 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYB9d38EgfIGNo2VVp:-LfYB9d38EgfIGNo2VVq:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1520)):*
> ```cpp
>         newMessageAlert(window(), isActiveWindow(), true, true);
> #if DESKTOP_NOTIFICATIONS
>         const Settings& s = Settings::getInstance();
> ```

same
___
*[src/widget/widget.cpp, line 1764 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYBB0m1vNAAJupDFJ_:-LfYBB0m1vNAAJupDFJa:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1764)):*
> ```cpp
>             newMessageAlert(window(), isActiveWindow(), true, true);
> #if DESKTOP_NOTIFICATIONS
>             const Settings& s = Settings::getInstance();
> ```

same

**Comment by Monsterovich** [comment]
done

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5674)* status: 0 of 1 LGTMs obtained

___
*[CMakeLists.txt, line 17 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfY9tt2BILh0hwKdP9R:-Lf_B8ZUE4mkFW4dfURk:b7l0hr4) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/CMakeLists.txt#L17)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

To enable this by default we would need to add libsnorenotify to the CI system, if you really want to do it, make a separate PR for this.
</blockquote></details>

This point is still a problem, I would recommend to leave this as before
___
*[src/platform/desktop_notifications/desktopnotify.h, line 15 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYATNnEvSQkZkUQBW-:-Lf_AxwkCwjM2YrrL79_:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/platform/desktop_notifications/desktopnotify.h#L15)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

use an `enum class` here for the type safety
</blockquote></details>

ok
___
*[src/widget/widget.cpp, line 1384 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYAzia978IwNimMm2K:-Lf_B0z4-AmGnonVVEat:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1384)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`Widget` already has a reference to `Settings`, don't use `Settings::getInstance()`
</blockquote></details>

ok
___
*[src/widget/widget.cpp, line 1433 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYB7m05OqEqwCvIHbn:-Lf_B2Ep--Aecw864AU9:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1433)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

ok
___
*[src/widget/widget.cpp, line 1520 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYB9d38EgfIGNo2VVp:-Lf_B3WY4RPtHrMEMsMU:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1520)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

ok
___
*[src/widget/widget.cpp, line 1764 at r3](https://reviewable.io/reviews/qtox/qtox/5674#-LfYBB0m1vNAAJupDFJ_:-Lf_B4dzEhGHMMGFXdqV:b32wtd) ([raw file](https://github.com/qtox/qtox/blob/84e41303ce6297df68886d4a1615a07286aed794/src/widget/widget.cpp#L1764)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

ok

**Review by Diadlo — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 2 of 8 files at r2, 3 of 3 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5674)* status: 0 of 1 LGTMs obtained

___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 22 at r5](https://reviewable.io/reviews/qtox/qtox/5674#-Lf_hkhXCr9RKfsBhs3M:-Lf_hkhXCr9RKfsBhs3N:b55hsxs) ([raw file](https://github.com/qtox/qtox/blob/821ed5261641043121d0b716d381346ac7502a15/src/platform/desktop_notifications/desktopnotify.cpp#L22)):*
> ```cpp
> }
> 
> void DesktopNotify::createNotification(const QString& title, const QString &text, Snore::Icon &icon)
> ```

Place reference closer to type. I.e. `const QString& text`
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 34 at r5](https://reviewable.io/reviews/qtox/qtox/5674#-Lf_hh471FJ9fB5RVFtz:-Lf_hh471FJ9fB5RVFu-:biyjdj7) ([raw file](https://github.com/qtox/qtox/blob/821ed5261641043121d0b716d381346ac7502a15/src/platform/desktop_notifications/desktopnotify.cpp#L34)):*
> ```cpp
> }
> 
> void DesktopNotify::notifyMessage(const QString title, const QString message)
> ```

Use reference here
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 39 at r5](https://reviewable.io/reviews/qtox/qtox/5674#-Lf_hji36Z6aS-wqfkIQ:-Lf_hji36Z6aS-wqfkIR:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/821ed5261641043121d0b716d381346ac7502a15/src/platform/desktop_notifications/desktopnotify.cpp#L39)):*
> ```cpp
> }
> 
> void DesktopNotify::notifyMessagePixmap(const QString title, const QString message, QPixmap avatar)
> ```

Same as above
___
*[src/platform/desktop_notifications/desktopnotify.cpp, line 49 at r5](https://reviewable.io/reviews/qtox/qtox/5674#-Lf_hr8_4cWAklA4jAGM:-Lf_hr8aCO218eTg2u-C:bod8mbc) ([raw file](https://github.com/qtox/qtox/blob/821ed5261641043121d0b716d381346ac7502a15/src/platform/desktop_notifications/desktopnotify.cpp#L49)):*
> ```cpp
>     QString message;
>     switch (type) {
>     case MessageType::FRIEND: message = tr("New message"); break;
> ```

You maybe interested in using `map` here. I.e.
```
const std::map<MessageType, QString> map = {
    { MessageType, tr("New message") },
    { MessageType, tr("Incoming file transfer") },
    { MessageType, tr("Friend request received") },
    { MessageType, tr("New group message") },
    { MessageType, tr("Group invite received") },
}
return map[type];
```

Feel free to leave as is
___
*[src/widget/widget.h, line 127 at r5](https://reviewable.io/reviews/qtox/qtox/5674#-Lf_iPD99N3hlbBEq2cJ:-Lf_iPDACddEfmgZ4V_F:b-fb17tj) ([raw file](https://github.com/qtox/qtox/blob/821ed5261641043121d0b716d381346ac7502a15/src/widget/widget.h#L127)):*
> ```objc
>     void addGroupDialog(Group* group, ContentDialog* dialog);
>     bool newFriendMessageAlert(const ToxPk& friendId, const QString text, bool sound = true, bool file = false);
>     bool newGroupMessageAlert(const GroupId& groupId, const ToxPk authorPk, const QString message, bool notify);
> ```

const reference

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: from my side

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5674#-:-Lfd_c1AAN-2CueljD_o:bybplqg)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by Diadlo — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 7 files at r1, 2 of 8 files at r2, 1 of 2 files at r3, 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5674#-:-LfdbbGJEFzJqb9hOSSK:b-jbsf8z)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Pull request merged**
