### PR TITLE
autocomplete will work for : also,fixes #1377

### LINKED ISSUE #1377: Groupchat: :[tab] will autocomplete for all nicks, not only for those starting with `:`

### PR DESCRIPTION
**Pull request by kushagrasurana**
added <code>:-</code> in regex.
Works for me

### CODE REVIEW

**Comment by agilob** [comment]
The same bug with `;`
Will autocomplete work with nicks like `:3` with that commit?

**Comment by kushagrasurana** [comment]
so autocomplete should work with ; also ?
yes it will autocomplete nicks like <code>:3</code>

**Comment by agilob** [comment]
http://webmup.com/HmDJQ/vid.webm

**Comment by dubslow** [comment]
The base problem is that each special character needs to be specially added to the regex... what to support can be difficult.
@kushagrasurana What's with the extra `-` character in your commit?

**Comment by kushagrasurana** [comment]
@dubslow without that extra <code>-</code>, autocomplete wont work for <code>-</code>.
At preset, we are whitelisting all characters which should work with autocomplete.
We can do it other way, that is blacklisting all those characters which we dont want to include in autocomplete like <code>whitespace</code>.

**Comment by dubslow** [comment]
That might indeed be the better option....

**Comment by kushagrasurana** [comment]
Can you tell me all the blacklisted characters ( like whitespace )

**Comment by tux3** [comment]
Finally a PR that merges cleanly against master \o/ !

It could maybe be done better, but this is an improvement for now.

**Comment by agilob** [comment]
well only one line changed...

**Comment by tux3** [comment]
@agilob After the horrible things I had to go through for the other 15 PRs, this is paradise.

New rule: From now on all PRs must be 1 line long!

**Pull request merged**
