### PR TITLE
docs(install): link dependencies' missing websites

### LINKED ISSUE #3930: TODO: link to dependencies' websites from `Dependencies` table in INSTALL.md
Each dependency name should be a link to the website of the dependency, to ease finding dependencies for users that might not have them on their distro/OS.

https://github.com/qTox/qTox/blob/master/INSTALL.md#dependencies

### PR DESCRIPTION
**Pull request by ghost**
Link dependency names to the website of the dependency, making them
easier to find for users that might not have them on their distro/OS.

Closes #3930

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3940)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[INSTALL.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3940#-KYGxIuS0op1wfrO0amY:-KYGxIuT6ZKERyda0ZRh:b-h4qd6b) ([raw file](https://github.com/qtox/qtox/blob/767945cd0da152494229c9723e3b9ce3d6c91bd4/INSTALL.md#L48)):*
> ```Markdown
> | [OpenAL Soft]     | >= 1.16.0   |                                                   |
> | [qrencode]        | >= 3.0.3    |                                                   |
> | sqlcipher         | >= 3.2.0    |                                                   |
> ```

Link to https://www.zetetic.net/sqlcipher/ ?

---

*[INSTALL.md, line 49 at r1](https://reviewable.io:443/reviews/qtox/qtox/3940#-KYGxRjSAg3MK9KMAnav:-KYGxRjS2Qd43_uwBWSl:b6jx1lq) ([raw file](https://github.com/qtox/qtox/blob/767945cd0da152494229c9723e3b9ce3d6c91bd4/INSTALL.md#L49)):*
> ```Markdown
> | [qrencode]        | >= 3.0.3    |                                                   |
> | sqlcipher         | >= 3.2.0    |                                                   |
> | [pkg-config]      | >= 0.28     |                                                   |
> ```

1st column could have 4 spaces less

---

*[INSTALL.md, line 615 at r1](https://reviewable.io:443/reviews/qtox/qtox/3940#-KYGxlE4ERmCDcmaWYVU:-KYGxlE4Br3RRcAJtTmX:baq6qsw) ([raw file](https://github.com/qtox/qtox/blob/767945cd0da152494229c9723e3b9ce3d6c91bd4/INSTALL.md#L615)):*
> ```Markdown
> [pkg-config]: https://www.freedesktop.org/wiki/Software/pkg-config/
> [libXScrnSaver]: https://www.x.org/wiki/Releases/ModuleVersions/
> [libX11]: https://www.x.org/wiki/
> ```

Could it be sorted along with the rest of links? `sort(1)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3940)*

**Comment by ghost** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[INSTALL.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3940#-KYGxIuS0op1wfrO0amY:-KYIeaZg8_V0Yj9-0lg4:b-84zfub) ([raw file](https://github.com/qtox/qtox/blob/767945cd0da152494229c9723e3b9ce3d6c91bd4/INSTALL.md#L48)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Link to https://www.zetetic.net/sqlcipher/ ?
</blockquote></details>

Compile instructions are detailed further down, same as toxcore. Really add it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3940)*

**Comment by ghost** [comment]
(it wasn't fun to start using reviewable.io with noscript and refcontrol...)

**Comment by zetok** [comment]
>(it wasn't fun to start using reviewable.io with noscript and refcontrol...)

Sorry about that. Reviewable with its many downsides does allow for better review, and unlike github, it doesn't lose review comment, and does properly track changes across revisions. Well, in any case, if you find it really bothersome to use, you don't have to, since there is "copy" of the text posted on github. If it's not enough to get things going, just say so – github reviews could be used, although that would mean a lot of pain. (the bigger PR is, the worse it gets)

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3940#-KYGxIuS0op1wfrO0amY:-KYInUsO93q3dQk2OgMH:b-idikyh) ([raw file](https://github.com/qtox/qtox/blob/767945cd0da152494229c9723e3b9ce3d6c91bd4/INSTALL.md#L48)):*
<details><summary><i>Previously, kehugter wrote…</i></summary><blockquote>

Compile instructions are detailed further down, same as toxcore. Really add it?
</blockquote></details>

Well, the closest sqlcipher link is half the install.md down, and only in the Linux section.

toxcore also could make use of some link, but given that currently irungentoo's toxcore is used and switch to c-toxcore should be a few days away, adding link to it now to just change it soon doesn't sound really appealing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3940#-:-KYIo3sA3or2Nww6qHEl:b-bsztzk)*

**Comment by ghost** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[INSTALL.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3940#-KYGxIuS0op1wfrO0amY:-KYIuxal4zolYHaxa5Ol:b67vwyd) ([raw file](https://github.com/qtox/qtox/blob/767945cd0da152494229c9723e3b9ce3d6c91bd4/INSTALL.md#L48)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

Well, the closest sqlcipher link is half the install.md down, and only in the Linux section.

toxcore also could make use of some link, but given that currently irungentoo's toxcore is used and switch to c-toxcore should be a few days away, adding link to it now to just change it soon doesn't sound really appealing.
</blockquote></details>

Right. Added the  irungentoo's toxcore link as a placeholder: the repo will have to be grepped and it will show up as a remainder of a change to be made.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3940)*

**Comment by ghost** [comment]
Not your product, no need to be sorry, I was just ranting. Is a nice interface, I like it too, but the GH login is trough appspot.com is very inconvenient.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3940#-:-KYIvNLvAENH8sDSmazK:bmkq7no)*

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3940#-:-KYIyGl46wtoFRrSAmly:bnfp4nl)*

**Pull request merged**
