### PR TITLE
Autoshow

### PR DESCRIPTION
**Pull request by dubslow**
A few minor ui things as well

### CODE REVIEW

**Comment by tux3** [comment]
Hm, it doesn't work when qTox is minimized or just hidden behind another window.

Is that by design? Because the checkbox is a bit confusing then. Otherwise it's good.

**Comment by dubslow** [comment]
I don't know. @darkcoconuts said it worked for him, and... actually it just occurred to me that I think I misinterpreted the minimize to tray code.

**Comment by dubslow** [comment]
fixed

**Comment by tux3** [comment]
Merged manually in f9cb19a157e962f314cb110cad74026e8edcddf4 after a painful rebase.

**Pull request closed without merging**
