### PR TITLE
feat(ui): add event icons for all statuses

### PR DESCRIPTION
**Pull request by anthonybilinski**
Before we would alternate between status icon and online event icon.
Now each status has its own event version, so status doesn't appear to
alternate between online and the correct status.

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5650)

### CODE REVIEW

**Comment by sudden6** [comment]
For at least `taskbar_busy_event.svg` the inner symbol doesn't look centered to me, can you re-check this on all symbols?

**Comment by anthonybilinski** [comment]
All of the event SVGs were created by copying and manually editing the fill colour, e.g.:
```
$ diff light/taskbar_busy_event.svg light/taskbar_busy.svg
45c45
<      style="fill:#ff9600" /><path
---
>      style="fill:#ffffff" /><path
64c64
<      sodipodi:nodetypes="cssscccccc" /></svg>
---
>      sodipodi:nodetypes="cssscccccc" /></svg>
\ No newline at end of file
```
so at least no spacing was changed.

On closer inspection, it looks like you're right:
image

I'm not sure if this is intentional because of the asymmetric speech bubble, or a legacy design flaw. Should this be fixed?

**Comment by sudden6** [comment]
I think it should be fixed (centered), but maybe ask for other opinions too?

**Review by anthonybilinski — COMMENTED** [review]
Icons centred, small event icons removed

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5650#-:-Lf4AeFa6cB-JlPF68IF:b-pdoqmv)* status: 0 of 1 LGTMs obtained

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5650#-:-LfLfCZ09Jl9RCjcs_OK:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
