### PR TITLE
Removes chat history of friend when removed, fixes #1486

### LINKED ISSUE #1486: Delete history message after deleting friend
Info: OS: Win

Reproducible: Always

Steps to reproduce:
1. delete friend
2. add friend back

What happened: history of message loaded

What should happen: chat history must be deleted

### PR DESCRIPTION
**Pull request by kushagrasurana**
works for me.

### CODE REVIEW

**Comment by PKEv** [comment]
Maybe add a confirmation dialog?

**Comment by ProMcTagonist** [comment]
I've found it useful to know if someone I just added is someone that I removed before.

**Comment by kushagrasurana** [comment]
But unnecessary history should be removed, i like the confirmation dialog idea. Or we can but this in settings ( but we already have a lot of settings ).

**Comment by apprb** [comment]
The reasonable alternative to new entry in the settings or history deletion confirmation dialog is a separate history management dialog.

**Comment by PKEv** [comment]
At the moment, I do not really understand the meaning of a large menu control history, on the other hand the removal of stories by default is not the best choice. Not so often remove friends so dialogue confirm the deletion of history will suffice. May be necessary to make one more dialogue - like change the value of nospam after removing other, just in case ...

**Comment by zetok** [comment]
> But unnecessary history should be removed

Why it should be removed?

**Comment by kushagrasurana** [comment]
> Why it should be removed?

Chat data is junk as user cant access the chat history of a removed friend ( untill he adds him back ).

**Comment by linux-modder** [comment]
can confirm this on 1.0.1

Corey W Sheldon
Freelance IT Consultant, Multi-Discipline Tutor
(p) 310.909.7672
G+: https://www.plus.google.com/+CoreySheldon
LinkedIn: https://www.linkedin.com/profile/view?id=70127804
Github: https://www.github.com/linux-modder
Facebook: https://www.facebook.com/corey.sheldon
Several Communities on Stack Exchange https://www.stackexchange.com

http://www.facebook.com/1stclassmobileshine

Tutoring in person or via any of the following platforms:
HackHands https://www.hackhands.com
Wizpert https://www.wizperts.com
FieldNation https://www.fieldnation.com
AirPair https://www.airpair.com
Truelancer http://www.truelancer.com

## {PayPal,Google Wallet/Play store, Apple Pay}

pub  3072D/718BF597
http://pgp.mit.edu/pks/lookup?op=get&search=0xE958C5D6718BF597 2014-12-08
      Key fingerprint = 2930 99EB 083D D332 0752 88C4 E958 C5D6 718B F597

## uid     Corey Sheldon (Fedora Key) sheldon.corey@gmail.com

**Pull request merged**
