### PR TITLE
Zoff99 master3

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4892)

### CODE REVIEW

**Comment by sudden6** [comment]
Continuation of  #4783 since I couldn't push to @zoff99 s branch

**Comment by zoff99** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4892)*

**Comment by zoff99** [comment]
can you register on https://circleci.com/gh/qTox with the github qTox account?
and activate qTox builds. but with circleCI 1.0

and check these:
image

**Comment by zoff99** [comment]
@sudden6 be careful about setting cache dirs in circleCI ! if the size of the cached files is too large, the cache will sort of silently fail. do you know how much MBytes will be in this cache dir?

maybe add to circle.yml at the end:
```
    - du -hs ~/workspace
```

**Comment by zoff99** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4892)*

**Comment by sudden6** [comment]
no problem if it silently fails, if the cached files don't exist, they will be rebuilt

**Comment by zoff99** [comment]
@sudden6 i mean they will silenty be corrupt. be careful, i had bad experiences with cache on circleCI.
only cache small amounts up to 100MByte.

**Comment by zoff99** [comment]
maybe add another dummy commit, here. to see now if caching works ok

**Comment by nurupo** [comment]
>[circle.yml specified cache directories: /home/ubuntu/workspace/i686/dep-cache/*, /home/ubuntu/workspace/x86_64/dep-cache/* but they don't exist](https://circleci.com/gh/qTox/qTox/7)

**Comment by nurupo** [comment]
Looks like the "Save cache" step happens before docker runs. Perhaps Circle-CI does that because the `cache_directories:` is specified before the building part in the .yml file? I'd try moving it after the building part to see if it helps.

**Comment by sudden6** [comment]
@nurupo seems like this is not possible https://circleci.com/docs/1.0/how-cache-works/

I'll later try if we can maybe replicate the Travis CI setting where we're building the deps in extra steps

**Comment by zoff99** [comment]
@sudden6 
https://github.com/zoff99/qTox/blob/zoff99/circleCI_with_cache/circle.yml

image

**Comment by nurupo** [comment]
Oh, I see, with Circle-CI it's dependency caching only.

**Comment by zoff99** [comment]
@sudden6 did you try my solution?
and just a hint: you can ssh into your circleCI build container, that makes it a lot easier. and you don't need to wait so long for each try

**Comment by sudden6** [comment]
yep, I took a look at it, but it doesn't seem to handle changes in the build scripts as well as the one we have for travis.

unfortunately it takes 45min to build qt, so most of the time I'm not around to ssh into the build anymore

@nurupo you seem to know some stuff about docker, I don't know why it doesn't create the directories like `~/workspace/` am I doing something wrong? Since the whole stage 3 build completes without errors, erverything must be somewhere, but where?

**Comment by nurupo** [comment]
Well,

```sh
sudo docker run --rm -v /home/ubuntu/qTox/workspace:/workspace -v /home/ubuntu/qTox/windows/cross-compile:/script -v /home/ubuntu/qTox:/qtox -e TRAVIS_CI_STAGE=stage3 debian:stretch-slim /bin/bash /script/build.sh x86_64 release
```

mounts `/home/ubuntu/qTox/workspace` as `/workspace` inside container, so qTox should be in `/home/ubuntu/qTox/workspace/x86_64/qtox/release` instead of `/home/ubuntu/workspace/x86_64/qtox/release`. No idea why you do `mkdir -p ~/workspace` in `circle.yml` before calling `.travis/build-windows.sh` for 1st stage, it's not used for anything as far I can see.

**Comment by zoff99** [comment]
@sudden6 why dont you use the very first version. and just move the whole docker stuff into the dependency:pre: section? its the easiest way
compile and test can be just dummy

**Comment by sudden6** [comment]
@nurupo thx, now I feel stupid^^ Can you take a look at the changes and give a LGTM if they are ok?

 @zoff99 I want this setup to be as similar to the Travis setup as possible.

**Comment by nurupo** [comment]
It looks good, assuming you want to keep those debugging printouts (don't have anything against them). I don't see any way to download the artifacts in the Circle-CI Web UI though, is that feature disabled? I think that was the entire point of doing all this on Circle-CI -- to allow people to test the qTox built off a PR.

---

Reviewed 1 of 1 files at r2, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4892#-:-L2NAWhK4MtO1xWidt1S:bkmdapz)*

**Comment by sudden6** [comment]
Seems like it's only accessible to people with rights on the repo (https://circleci.com/docs/1.0/build-artifacts/), that makes it quite a bit less usefull :(
I'll merge it anyway since it seems to be working now.

**Pull request merged**
