### PR TITLE
Add AppArmor 2.13.3 profile

### PR DESCRIPTION
**Pull request by Talkless**
- [x ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Ubuntu 19.10 (and current Debian and openSUSE rolling releases) has AppArmor 2.13.3 with updated abstractions. This allows us to create cleaned-up profile, removing rules that are already available in the latest AppArmor release.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5855)

### CODE REVIEW

**Comment by Talkless** [comment]
@setharnold could you review this? You did take a look at original (introducing AppArmor profile) PR. Here, second commit is where you can see actual changes wrt. AppArmor 2.13.3.

**Comment by sudden6** [comment]
@Talkless do you think this should be merged even without some further review?

**Comment by Talkless** [comment]
> @Talkless do you think this should be merged even without some further review?

Ugh, well, I guess so. I believe this is no way critical, as probably I am only user of these AppArmor profiles :-) .

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: it's probably easier for downstream packagers to take these as a basis than to come up with their own rules from scratch, so I think we'll ship it.

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5855#-:-M2wkzBqC3PyTxu6ua07:bp9e457)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — APPROVED** [review]
I'm not very familiar with apparmor, but read through it and nothing seems obviously wrong. I agree with including it - if it's overly restrictive it will be obvious to users of it, and if it's not restrictive enough it's still better than nothing. :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5855#-:-M3-yqBg9iWPuDSCULZm:b3h5e6r)* status: :shipit: complete! 2 of 1 LGTMs obtained

**Pull request merged**
