### PR TITLE
fix(groupinviteform): consider dateTime format in group invites

### LINKED ISSUE #3058: Group invites page doesn't consider date format settings
**Observed Behavior:**  

The date is always formatted like this in the group invites page:
2016-03-26-102429_1366x768_scrot

It doesn't consider the general settings in your Tox profile:
2016-03-26-112106_1366x768_scrot

**Expected Behavior:**

The date is formatted like specified in your settings

### PR DESCRIPTION
**Pull request by a68366**
Now:
after

Closes #3058

### CODE REVIEW

**Comment by sudden6** [comment]
This will probably not update the invite message if the date format is changed.

**Comment by a68366** [comment]
@sudden6 Yes, it won't. Only new invites will have the new format.
Actually, I don't know how to make it updating.
Probably call retranslateUi() somehow. But there is currently no way to know when the format changes.

**Comment by zetok** [comment]
> This will probably not update the invite message if the date format is changed.

Isn't that the same for other stuff that has configurable date/time format?

There's lots of settings that don't really fully take effect until restart.

**Comment by sudden6** [comment]
@a68366 since the groupinviteform is already hooked up to the translator, it would be sufficient to call `Translator::translate()` from the `onDateFormatSelected()` in the generalsettingsform.

No idea if that will help with all date/time issues.

**Comment by a68366** [comment]
@sudden6 Yeah, it will help with group invites log (retranslation should be called in `onTimestampSelected()` too).
Other date/time indicators(e.g. in chatlog, couldn't find them anywhere else) will remain unchanged.
BTW, full client retranslation to just change date format doesn't look good to me.

**Comment by sudden6** [comment]
@a68366 probably yes, I just did a quick skim over the code.

It would still improve things a little bit. Why do you think it's bad? We could probably expand the translator, but I don't think it's worth the work.

**Pull request merged**
