### PR TITLE
feat(audio): don't use dynamic memory allocation and remove resource leak

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4330)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/audio/audio.cpp, line 503 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-Khb-vTvr99L-Aa27_z6:-Khb-vTvr99L-Aa27_z7:b6or1b4) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.cpp#L503)):*
> ```cpp
>         }
>     } else {
>         while(processed > 0) {
> ```

I don't sure that unqueue and remove each single buffer separately is a really good idea. Why just not to replace `bufids + 1` with `bufids + sizeof(ALuint)` for assurance?

---

*[src/audio/audio.cpp, line 689 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhauD0sEpR7uh4AfA_T:-KhauD0sEpR7uh4AfA_U:b-m8633j) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.cpp#L689)):*
> ```cpp
>             // stop playing, marks all buffers as processed
>             alSourceStop(sid);
>             // unque all buffers from the source
> ```

Here should be "unqueue"

---

*[src/audio/audio.h, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhatSCcO9qo5062afcS:-KhatSCdwebDzlUFlpiD:bzbt1zd) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.h#L141)):*
> ```objc
> 
> private:
>     static const unsigned int BUFFER_COUNT = 16;
> ```

Possibly, there is no need to declare this const within the `Audio` class

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330)*

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/audio/audio.cpp, line 503 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-Khb-vTvr99L-Aa27_z6:-Khczx4cE3REFyTHAnRX:bknzhuy) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.cpp#L503)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I don't sure that unqueue and remove each single buffer separately is a really good idea. Why just not to replace `bufids + 1` with `bufids + sizeof(ALuint)` for assurance?
</blockquote></details>

Thanks I thought about this again and came up with a better way to do it. `bufids + 1` should be correct, because pointers are always increased `sizeof(Type)` bytes.

---

*[src/audio/audio.cpp, line 689 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhauD0sEpR7uh4AfA_T:-Khd-Nr3eJCy3G0PDKMy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.cpp#L689)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Here should be "unqueue"
</blockquote></details>

Done.

---

*[src/audio/audio.h, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhatSCcO9qo5062afcS:-Khd-OmqDVd4wLnrYycw:bfwnpx5) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.h#L141)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Possibly, there is no need to declare this const within the `Audio` class
</blockquote></details>

It has to be `const` else the stack smashing protector won't work and the compiler will complain.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330)*

**Comment by noavarice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/audio/audio.h, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhatSCcO9qo5062afcS:-Khd6XvAJI0Evhv921u7:b-7rw39p) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.h#L141)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

It has to be `const` else the stack smashing protector won't work and the compiler will complain.
</blockquote></details>

I mean that it would be better to declare this in cpp file without being included in `Audio` so noone will see such details of implementation, sorry for my english :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/audio/audio.h, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhatSCcO9qo5062afcS:-Khd9yB-AOMvyWgZwxVs:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1ffc8e8c3f8214d3238319f475cca14fb393d437/src/audio/audio.h#L141)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I mean that it would be better to declare this in cpp file without being included in `Audio` so noone will see such details of implementation, sorry for my english :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330)*

**Comment by noavarice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/audio/audio.cpp, line 123 at r2](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhdDkep8-vtF8vLuDQW:-KhdDkep8-vtF8vLuDQX:b-ovf705) ([raw file](https://github.com/qtox/qtox/blob/0e6c59182eae88cc389e80251f95c184a230427e/src/audio/audio.cpp#L123)):*
> ```cpp
>  * @brief Ideally, we'd auto-detect, but that's a sane default
>  *
>  * @var Audio::BUFFER_COUNT
> ```

Please, change docs accordingly by removing `Audio::`

---

*[src/audio/audio.cpp, line 495 at r2](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhdEBe_eXdEzcL1DUkT:-KhdEBeaEGk1jTHgpgHW:b-jxq9tk) ([raw file](https://github.com/qtox/qtox/blob/0e6c59182eae88cc389e80251f95c184a230427e/src/audio/audio.cpp#L495)):*
> ```cpp
> 
>     if(processed == 0) {
>         if(queued < BUFFER_COUNT) {
> ```

You can revert condition and make early `return`, but it's only my own preference. If you will decide to leave it as now - change opening bracket style of `else` statement

---

*[src/audio/audio.cpp, line 505 at r2](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhdEriIVtjTltTp-yDd:-KhdEriIVtjTltTp-yDe:btgm748) ([raw file](https://github.com/qtox/qtox/blob/0e6c59182eae88cc389e80251f95c184a230427e/src/audio/audio.cpp#L505)):*
> ```cpp
>         }
>     } else {
>         // unque all processed buffers
> ```

Also fix "unque" here too :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/audio/audio.cpp, line 123 at r2](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhdDkep8-vtF8vLuDQW:-KhdKChfKdgt6Tl-BEu1:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0e6c59182eae88cc389e80251f95c184a230427e/src/audio/audio.cpp#L123)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Please, change docs accordingly by removing `Audio::`
</blockquote></details>

Done.

---

*[src/audio/audio.cpp, line 495 at r2](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhdEBe_eXdEzcL1DUkT:-KhdKE0R-pZ97hgviFtg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0e6c59182eae88cc389e80251f95c184a230427e/src/audio/audio.cpp#L495)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

You can revert condition and make early `return`, but it's only my own preference. If you will decide to leave it as now - change opening bracket style of `else` statement
</blockquote></details>

Done.

---

*[src/audio/audio.cpp, line 505 at r2](https://reviewable.io:443/reviews/qtox/qtox/4330#-KhdEriIVtjTltTp-yDd:-KhdKHKqd9DdMmtJoXVV:b-966p3h) ([raw file](https://github.com/qtox/qtox/blob/0e6c59182eae88cc389e80251f95c184a230427e/src/audio/audio.cpp#L505)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Also fix "unque" here too :)
</blockquote></details>

Done. I don't like this word :p

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4330#-:-KhdOEjm6ns0WMJVzaow:b-jbsf8z)*

**Pull request merged**
