### PR TITLE
[WIP] Unit tests

### PR DESCRIPTION
**Pull request by Diadlo**
This PR adds basic configuration for test creation. I suggest using google test framework (gtest + gmock). Also, this PR add unit test for `Friend` class and add some simple Mock for `Core`, `Settings` and `Profile` classes. 
We need to solve some organizational issues before merge this PR
- [ ] How test will be started? By additional define to build or split project on 3 subproject (see first commit comment)
- [ ] Travis tests autorun (hope @zetok will help with this?)
- [ ] Add code coverage calculation

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3678)

### CODE REVIEW

**Comment by antis81** [comment]
FYI: Qt Creator has builtin support for unit tests with `gtest`. It sets up a separate project, building the executable completely. I don't know, if the plugin left beta status yet, but it is definitely usable and gets us started, without having to modify application code.

**Comment by Diadlo** [comment]
@antis81 You talk about https://github.com/OneMoreGres/qtc-gtest?

**Comment by antis81** [comment]
Review status: 0 of 10 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

_[src/core/core.h, line 60 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3678#-KQb6HrFhs9MTeeZ38AG:-KQb6HrGxsZ2hI8V3gRL:b6c9y9h) ([raw file](https://github.com/qtox/qtox/blob/e1a2d15359f53a8a422249a38fa6fdd2dbfe138c/src/core/core.h#L60)):_

> ``` objc
>     static QByteArray getSaltFromFile(QString filename);
> 
>     virtual QString getPeerName(const ToxId& id) const;
> ```

Uhm… Core isn't inheritable (Caution: Singleton!) -> remove any virtual method.

---

_[src/persistence/settings.cpp, line 74 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3678#-KQb75yJKtgVFklRyelY:-KQb75yKUdgfStT7fdJ3:b-89q54l) ([raw file](https://github.com/qtox/qtox/blob/fcfac15c785f6cca5a38b9aa4f915fb805aec161/src/persistence/settings.cpp#L74)):_

> ``` cpp
>     settingsThread->start(QThread::LowPriority);
>     moveToThread(settingsThread);
>     loadGlobal();
> ```

Please leave that. Settings is Singleton and auto-loads on first instantiation.

---

_[src/persistence/settings.h, line 150 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3678#-KQb7Nnc9X7JXUzjSMUM:-KQb7Nnc9X7JXUzjSMUN:b-vsuidr) ([raw file](https://github.com/qtox/qtox/blob/e1a2d15359f53a8a422249a38fa6fdd2dbfe138c/src/persistence/settings.h#L150)):_

> ``` objc
>     void loadGlobal();
>     void loadPersonal();
>     virtual void loadPersonal(Profile *profile);
> ```

Same as with core: Not inheritable, due to Singleton -> no virtual methods allowed.

---

_[src/persistence/settings.h, line 643 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3678#-KQb7ZGdDUYTc-RT5pPs:-KQb7ZGdDUYTc-RT5pPt:bezbmye) ([raw file](https://github.com/qtox/qtox/blob/e1a2d15359f53a8a422249a38fa6fdd2dbfe138c/src/persistence/settings.h#L643)):_

> ``` objc
>     static QThread* settingsThread;
> 
> protected:
> ```

Highly private that pointer to self is! Singleton class cannot have protected block.

---

_[tests/mocks/mockCore.h, line 8 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3678#-KQb8Te2TXsFaPMlRLo-:-KQb8Te3ivWUawDCLkFY:b-8of1pv) ([raw file](https://github.com/qtox/qtox/blob/e1a2d15359f53a8a422249a38fa6fdd2dbfe138c/tests/mocks/mockCore.h#L8)):_

> ``` objc
> #include <QThread>
> 
> class MockCore : public Core
> ```

This doesn't work! -> Inheritance of Singleton bites hard!

---

_[tests/mocks/mockSettings.h, line 9 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3678#-KQb8wnfBnaPzT58cgVM:-KQb8wnga5OTuzkXuvQC:b-lx1csl) ([raw file](https://github.com/qtox/qtox/blob/e1a2d15359f53a8a422249a38fa6fdd2dbfe138c/tests/mocks/mockSettings.h#L9)):_

> ``` objc
> #include <gmock/gmock.h>
> 
> class MockSettings : public Settings
> ```

Same here -> Singletons are special. ^^

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3678)_

**Comment by Diadlo** [comment]
@antis81 Without it we can't create mock to this class => can't create unit tests

**Comment by antis81** [comment]
> You talk about https://github.com/OneMoreGres/qtc-gtest?

I talk about this: http://doc.qt.io/qtcreator/creator-autotest.html

**Comment by antis81** [comment]
Have a look here: http://stackoverflow.com/questions/2085953/unit-testing-with-singletons

Especially the first link is interesting. While this is Java/C# code, the same is valid for C++. Btw. the new audio API implementation uses no singleton at all! Guess now the time has come to clean that up. :) Maybe we can finish the ui/redesign thing and do it right after that? What do you think?

**Comment by Diadlo** [comment]
@antis81 Ok

**Pull request closed without merging**
