### PR TITLE
fix: scroll bar stuck to bottom (fix #5755)

### LINKED ISSUE #5755: Problem scrolling up through chat log (scroll bar stuck to bottom)
##### Brief Description
When the chat view is scrolled down all the way to the most recent message (so it’s not possible to scroll down any more), attempting to scroll up in the history with touchpad/scroll wheel doesn't do anything.
 
qTox version: You are using qTox version v1.16.3-570-g174d6ef8
Commit hash: https://github.com/qTox/qTox/commit/174d6ef8ca07f892c4ad329107f03978645bf1ab
toxcore: v0.2.10
Qt: 5.12.4
Hardware: Laptop
 
Reproducible: Always
 
##### Steps to reproduce
- View someone's chat, and be all the way scrolled down (default view, showing newest messages)
- Try to scroll up with touchpad/scroll wheel to view older messages
 
##### Observed Behavior
It doesn't scroll up, it stays at the very bottom. The cursor sometimes appears to quickly change between the pointer and text-cursor as if it's trying to do something but it never scrolls up. However, manually dragging the scrollbar will cause it to scroll up like normal, and touchpad scrolling DOES work if the original position before scrolling isn't at the bottom. The only time scrolling with touchpad doesn't work is when the chat is scrolled all the way down.

Trying to scroll up VERY quickly and with a lot of pressure seems to work as expected, I get this issue when scrolling up at normal or slow speed.

Here’s a video (Scrolling up after clicking on chat area, nothing happens)

https://gfycat.com/acrobaticprestigiousislandcanary
 
##### Expected Behavior
Scrolling to work from any position.
 
I think it's related to these changes - https://github.com/qTox/qTox/commit/be55759555eecc60adf84fd3eb5ae6d993c5edbe -, I can scroll normally if I compile an earlier version

### PR DESCRIPTION
**Pull request by TriKriSta**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5777)

### CODE REVIEW

**Comment by sudden6** [comment]
Testing this now.

**Review by sudden6 — APPROVED** [review]
The problem didn't occur with this fix applied, no regressions detected :lgtm_strong: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5777#-:-Lm6cyDk7pbFn_5uqgsO:b-bjkfqe)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
Running this now for a few hours and I haven't seen the issue pop up. I still noticed https://github.com/qTox/qTox/issues/5755#issuecomment-516576284, but as @TriKriSta mentioned may be fixed by #5693, not this PR.

**Comment by TriKriSta** [comment]
@anthonybilinski these requests fix deferent bugs.

**Comment by anthonybilinski** [comment]
Yes, understood. Just noting some strange behaviour during testing, but not requesting changes for this PR because of it.

**Comment by anthonybilinski** [comment]
a note that I moved your commit to the tip of the v1.17-dev branch, and targeted your PR to this branch. For future updates, please update that commit.

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
From testing this seems to work well - the code is a little confusing to me so just asking for some comments to clarify a couple things before merge.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5777#-:-LnPwZa-Eoesl9SUupQb:b-hulh9t)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[src/widget/form/genericchatform.cpp, line 698 at r2](https://reviewable.io/reviews/qtox/qtox/5777#-LnPvZ95-1buXxEnp6-j:-LnPvZ95-1buXxEnp6-k:b-ei33hg) ([raw file](https://github.com/qtox/qtox/blob/38df897e024393ba15c80017930dac19a92e13b7/src/widget/form/genericchatform.cpp#L698)):*
> ```cpp
> }
> 
> bool GenericChatForm::loadHistoryFrom(const QDateTime &time)
> ```

it's confusing that of the three load functions, 2 are void and one is bool. It's not clear from the API what the returned bool represents. Could you add some doxygen-style comments explaining the return value, like is present on GenericChatForm::needsToHideName?
___
*[src/widget/form/genericchatform.cpp, line 710 at r2](https://reviewable.io/reviews/qtox/qtox/5777#-LnPw8lTAZQBuUQa2csC:-LnPw8lU7KFQeViSRt7y:b5b0tbu) ([raw file](https://github.com/qtox/qtox/blob/38df897e024393ba15c80017930dac19a92e13b7/src/widget/form/genericchatform.cpp#L710)):*
> ```cpp
>     int add = DEF_NUM_MSG_TO_LOAD;
>     if (begin.get() + DEF_NUM_MSG_TO_LOAD > chatLog.getNextIdx().get()) {
>         auto t = chatLog.getNextIdx();
> ```

does this line do anything? isn't `t` unused?
___
*[src/widget/form/genericchatform.cpp, line 714 at r2](https://reviewable.io/reviews/qtox/qtox/5777#-LnPwOnJEoOktnSwG1IE:-LnPwOnJEoOktnSwG1IF:bkf2a10) ([raw file](https://github.com/qtox/qtox/blob/38df897e024393ba15c80017930dac19a92e13b7/src/widget/form/genericchatform.cpp#L714)):*
> ```cpp
>     }
> 
>     if (add  <= 1) {
> ```

maybe comment on what the specialty is about the number of lines added being exactly 1 instead of 2? I don't understand from code why adding one line or adding two lines need to be treated differently.

**Review by TriKriSta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5777)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

___
*[src/widget/form/genericchatform.cpp, line 698 at r2](https://reviewable.io/reviews/qtox/qtox/5777#-LnPvZ95-1buXxEnp6-j:-LnTfBnj4kAAXkuv6ytK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/38df897e024393ba15c80017930dac19a92e13b7/src/widget/form/genericchatform.cpp#L698)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

it's confusing that of the three load functions, 2 are void and one is bool. It's not clear from the API what the returned bool represents. Could you add some doxygen-style comments explaining the return value, like is present on GenericChatForm::needsToHideName?
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 710 at r2](https://reviewable.io/reviews/qtox/qtox/5777#-LnPw8lTAZQBuUQa2csC:-LnTf1Ps7hIAAE6uurVN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/38df897e024393ba15c80017930dac19a92e13b7/src/widget/form/genericchatform.cpp#L710)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

does this line do anything? isn't `t` unused?
</blockquote></details>

Done.
___
*[src/widget/form/genericchatform.cpp, line 714 at r2](https://reviewable.io/reviews/qtox/qtox/5777#-LnPwOnJEoOktnSwG1IE:-LnTf4OtE5809jzBMxYo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/38df897e024393ba15c80017930dac19a92e13b7/src/widget/form/genericchatform.cpp#L714)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

maybe comment on what the specialty is about the number of lines added being exactly 1 instead of 2? I don't understand from code why adding one line or adding two lines need to be treated differently.
</blockquote></details>

Done.

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5777#-:-LnUAgHYDAPbbQ6bZggx:b-uwkowd)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
