### PR TITLE
[Refactor + fix] About friend model

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4606)

### CODE REVIEW

**Comment by sudden6** [comment]
Wouldn't it be less code to merge IFriendSettings and IAboutFriend, and create two different views from this model?

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4606#-:-Ksorv4SuAHHIjquZNHl:b-wu28mn)*

**Comment by Talkless** [comment]
Review status: 0 of 13 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/about/aboutfriend.cpp, line 33 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1t1H4pdaGjj2TzN5q:-Kt1t1H5oidqQzxB89ga:bayhwr2) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L33)):*
> ```cpp
>     const QString pk = f->getPublicKey().toString();
>     const QPixmap avatar = Nexus::getProfile()->loadAvatar(pk);
>     return avatar.isNull() ? QPixmap(":/img/contact_dark.svg")
> ```

QStringLiteral.
Actually maybe better to have some header with these kind of constants, if it may be used in multiple placed, but that's off topic I guess for this PR.

---

*[src/model/about/aboutfriend.cpp, line 67 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1tKQZluqufgmmrHtF:-Kt1tKQZluqufgmmrHtG:b-sp6cki) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L67)):*
> ```cpp
> {
>     const ToxPk pk = f->getPublicKey();
>     const int value = (int)settings->getAutoAcceptCall(pk);
> ```

static_cast?
[ES.49: If you must use a cast, use a named cast](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es49-if-you-must-use-a-cast-use-a-named-cast)

---

*[src/model/about/aboutfriend.cpp, line 74 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1sYW9r4n_S0cU_s-6:-Kt1sYWAIFuBPH30CitF:b-pgn8i2) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L74)):*
> ```cpp
> {
>     const ToxPk pk = f->getPublicKey();
>     const int value = (int)flag;
> ```

static_cast?

---

*[src/model/about/aboutfriend.cpp, line 98 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1tOAoMH8klZI2kW3N:-Kt1tOAoMH8klZI2kW3O:banwc2) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L98)):*
> ```cpp
> {
>     const ToxPk pk = f->getPublicKey();
>     History* history = Nexus::getProfile()->getHistory();
> ```

History* **const** history

---

*[src/model/about/aboutfriend.h, line 16 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1tWggBhTJCOK3lRrU:-Kt1tWggBhTJCOK3lRrV:b-khh9yo) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.h#L16)):*
> ```objc
> 
> public:
>     explicit AboutFriend(const Friend* f, IFriendSettings* settings);
> ```

No need for explicit, it needs more than one argument to construct.

---

*[src/model/about/aboutfriend.h, line 39 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1wHdF7U1z0abSOnK8:-Kt1wHdF7U1z0abSOnK9:b-cdit7y) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.h#L39)):*
> ```objc
> 
> private:
>     const Friend* f;
> ```

pointer initialized and never changed, and AboutFriend is not copyable (QObject), so could be `... * const f;`

---

*[src/model/about/aboutfriend.h, line 40 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1wVzJFDVPj3Uf2Imw:-Kt1wVzJFDVPj3Uf2Imx:bwgbj54) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.h#L40)):*
> ```objc
> private:
>     const Friend* f;
>     IFriendSettings* settings;
> ```

`... * const settings;`

---

*[src/widget/friendwidget.cpp, line 233 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1uLl-ldZ0VDmZ-gDL:-Kt1uLl-ldZ0VDmZ-gDM:bv1udn2) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/friendwidget.cpp#L233)):*
> ```cpp
>     } else if (selectedItem == aboutWindow) {
>         const Friend* f = FriendList::findFriend(friendId);
>         QPointer<IAboutFriend> about = new AboutFriend(f, &Settings::getInstance());
> ```

const QPointer....

---

*[src/widget/about/aboutfriendform.cpp, line 56 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1uly4XI_U3vYlqa7D:-Kt1uly4XI_U3vYlqa7E:b-6nw0wu) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/about/aboutfriendform.cpp#L56)):*
> ```cpp
> void AboutFriendForm::onAutoAcceptDirClicked()
> {
>     QString dir;
> ```

To avoid default constructor and then assignment, lambdas could be used:
[ES.28: Use lambdas for complex initialization, especially of const variables](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es28-use-lambdas-for-complex-initialization-especially-of-const-variables)
```
const QString dir = [ui, &about, this]() {
 // ...
   return  getAutoAcept
// ...
  return QString();
}();
```

---

*[src/widget/about/aboutfriendform.cpp, line 66 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1vppfX7JXRBawE9wn:-Kt1vppgCYUCf0mcmRj-:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/about/aboutfriendform.cpp#L66)):*
> ```cpp
> void AboutFriendForm::onAutoAcceptDirChanged(const QString& path)
> {
>     bool enabled = path.isNull();
> ```

const bool

---

*[src/widget/about/aboutfriendform.cpp, line 90 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1vuJILvKbjgxoMGm4:-Kt1vuJILvKbjgxoMGm5:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/about/aboutfriendform.cpp#L90)):*
> ```cpp
> void AboutFriendForm::onSelectDirClicked()
> {
>     QString dir = getAutoAcceptDir(about->getAutoAcceptDir());
> ```

const QString

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4606)*

**Comment by Diadlo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 11 unresolved discussions.

---

*[src/model/about/aboutfriend.cpp, line 33 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1t1H4pdaGjj2TzN5q:-Kt6CsHFjB01nqTWt-V2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L33)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QStringLiteral.
Actually maybe better to have some header with these kind of constants, if it may be used in multiple placed, but that's off topic I guess for this PR.
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.cpp, line 67 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1tKQZluqufgmmrHtF:-Kt6CsnWtA5-x8IUTE3F:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L67)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

static_cast?
[ES.49: If you must use a cast, use a named cast](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es49-if-you-must-use-a-cast-use-a-named-cast)
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.cpp, line 74 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1sYW9r4n_S0cU_s-6:-Kt6Ct6Q4G40QIBUiDVI:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L74)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

static_cast?
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.cpp, line 98 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1tOAoMH8klZI2kW3N:-Kt6CtOyMO3c8V0twmry:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.cpp#L98)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

History* **const** history
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.h, line 16 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1tWggBhTJCOK3lRrU:-Kt6Czcuqg85edS-Upb8:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.h#L16)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

No need for explicit, it needs more than one argument to construct.
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.h, line 39 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1wHdF7U1z0abSOnK8:-Kt6D6qsdUzEgO17I4iT:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.h#L39)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

pointer initialized and never changed, and AboutFriend is not copyable (QObject), so could be `... * const f;`
</blockquote></details>

Done.

---

*[src/model/about/aboutfriend.h, line 40 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1wVzJFDVPj3Uf2Imw:-Kt6D7AX8_hQxkns99OZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/model/about/aboutfriend.h#L40)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`... * const settings;`
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 233 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1uLl-ldZ0VDmZ-gDL:-Kt6D7gyxCPUPtYV6z4e:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/friendwidget.cpp#L233)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QPointer....
</blockquote></details>

Done.

---

*[src/widget/about/aboutfriendform.cpp, line 56 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1uly4XI_U3vYlqa7D:-Kt6D8Do8q5gcJ873yyA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/about/aboutfriendform.cpp#L56)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

To avoid default constructor and then assignment, lambdas could be used:
[ES.28: Use lambdas for complex initialization, especially of const variables](https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es28-use-lambdas-for-complex-initialization-especially-of-const-variables)
```
const QString dir = [ui, &about, this]() {
 // ...
   return  getAutoAcept
// ...
  return QString();
}();
```
</blockquote></details>

Done.

---

*[src/widget/about/aboutfriendform.cpp, line 66 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1vppfX7JXRBawE9wn:-Kt6D8YESKpmqs-3IqLl:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/about/aboutfriendform.cpp#L66)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const bool
</blockquote></details>

Done.

---

*[src/widget/about/aboutfriendform.cpp, line 90 at r1](https://reviewable.io:443/reviews/qtox/qtox/4606#-Kt1vuJILvKbjgxoMGm4:-Kt6D8udDzLlaKSwI_k-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5f27718943d45d4d15ea37e1d1984c3689a46121/src/widget/about/aboutfriendform.cpp#L90)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QString
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4606)*

**Comment by Diadlo** [comment]
I will split this PR on 3 smaller

**Pull request closed without merging**
