### PR TITLE
chore: fix simple_make.sh to work with cmake

### LINKED ISSUE #4267: simple_make.sh is broken
simple_make.sh is broken
OS:
`uname -a`
Linux client0 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`lsb_release -a`
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah

qTox version: v1.8.1-135-gf72c83a.
Commit hash:  f72c83afb76e4c4f055cb3e5bad9447bd03475e1

Relevant log snippit:

make[1]: Leaving directory '/home/avril/Development/qTox/libs/libtoxcore-v0.1.2'
~/Development/qTox
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'libavcodec'
-- Checking for one of the modules 'libavdevice'
-- Checking for one of the modules 'libavformat'
-- Checking for one of the modules 'libavutil'
-- Checking for one of the modules 'libqrencode'
-- Checking for one of the modules 'libsodium'
-- Checking for one of the modules 'libswscale'
-- Checking for one of the modules 'sqlcipher'
-- Checking for one of the modules 'vpx'
-- Checking for one of the modules 'toxcore'
-- Checking for one of the modules 'toxav'
-- Checking for one of the modules 'toxencryptsave'
-- Checking for one of the modules 'libtoxcore'
-- Checking for one of the modules 'libtoxav'
-- Checking for one of the modules 'openal'
-- Checking for one of the modules 'x11'
-- Checking for one of the modules 'gdk-pixbuf-2.0'
-- Checking for one of the modules 'glib-2.0'
-- Checking for one of the modules 'gtk+-2.0'
-- Checking for one of the modules 'check'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/avril/Development/qTox/_build
make: *** No targets specified and no makefile found.  Stop.

I was able to finish compiling manually by CDing to _build and entering `make`, so it's probably a very simple working directory problem. I reproduced it after cloning the repo again, so I'm pretty sure about this one.

### PR DESCRIPTION
**Pull request by sudden6**
fix #4267

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4268)

### CODE REVIEW

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[simple_make.sh, line 165 at r1](https://reviewable.io:443/reviews/qtox/qtox/4268#-KfbW1dFrkdIJUolkvEB:-KfbW1dFrkdIJUolkvEC:burlfrg) ([raw file](https://github.com/qtox/qtox/blob/aea770f384e689748e2febc65948bcc43e512008/simple_make.sh#L165)):*
> ```Shell
>     ./bootstrap.sh
>     mkdir -p build
>     cd build
> ```

`mkdir` isn't actually needed, you can just pass `_build` to `cd`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4268)*

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[simple_make.sh, line 165 at r1](https://reviewable.io:443/reviews/qtox/qtox/4268#-KfbW1dFrkdIJUolkvEB:-KfbXPB6lKrqGJ18Dzbx:bixcjzv) ([raw file](https://github.com/qtox/qtox/blob/aea770f384e689748e2febc65948bcc43e512008/simple_make.sh#L165)):*
<details><summary><i>Previously, zetok wrote…</i></summary><blockquote>

`mkdir` isn't actually needed, you can just pass `_build` to `cd`
</blockquote></details>

Doesn't work for me, it complains about the directory not existing, which makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4268)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[simple_make.sh, line 165 at r1](https://reviewable.io:443/reviews/qtox/qtox/4268#-KfbW1dFrkdIJUolkvEB:-KfbtJmUS18Rg-Sf4rUY:bpxwwn5) ([raw file](https://github.com/qtox/qtox/blob/aea770f384e689748e2febc65948bcc43e512008/simple_make.sh#L165)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Doesn't work for me, it complains about the directory not existing, which makes sense.
</blockquote></details>

It doesn't really make sense though, given that `cmake` is supposed to create the build dir.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4268)*

**Comment by quatrox** [comment]
Sorry for the messy commit.
I will cancel this and create a new pull request with (hopefully) correct commit message,
fix undocumented cmake parameters as suggested and remove " || exit $?"

**Comment by sudden6** [comment]
closed in favor of #4273

**Pull request closed without merging**
