### PR TITLE
fix: bugs with scroll

### PR DESCRIPTION
**Pull request by TriKriSta**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5889)

### CODE REVIEW

**Comment by Chiitoo** [comment]
This has been working very nicely here for the few days that I've been running with it.

**Comment by anthonybilinski** [comment]
So it looks like the existing behaviour is as follows:
1) a new message is added to the bottom of the chatlog
2) 
```
if (visibleLines.size() > 1) {
    startResizeWorker(visibleLines[1]);
} else {
```
is called, with visible lines being based on the height of your chat, e.g. 11. This causes `startResizeWorker` to be called with the index of one after the old top message, instead of with no argument, which would cause the chatlog to anchor to the bottom.
3) In a case like:
image
visibleLines[0] is the partially covered 8, so visibleLines[1] is the message "9". This would cause the chat to only scroll about 1/4 of a line, while adding a whole new line to the bottom, causing a the chatlog to not scroll all the way to the bottom.
4) Additionally, even if the chatlog is scrolled so that the top line is fully displayed and the newly inserted message at the bottom is fully displayed like this:
image
5) When the friend starts to type, the new typing notification is displayed off screen:
image

I don't think this matches the comment of "user sends one message, but program sometimes sends message with date, and we have 2 messages".

The change still correctly forces chatlog to anchor to the bottom, because there is only one new message:

```
if (newLines.size() > 2 && visibleLines.size() > 1) {
    startResizeWorker(visibleLines[1]);
} else {
    startResizeWorker();
}

```
but the core issue is that we're scrolling to `visibleLines[1]`, which isn't the same thing as anchoring to bottom. We should be calling `startResizeWorker()` even if multiple `newLines` are added.

The scroll to `visibleLines[1]` was added in 0a9e72020e3ec0bcfdca98891466e79cca8c23ec - previously we would always anchor to the bottom (by calling `startResizeWorker()`) when a chatline was added to the bottom. @TriKriSta do you remember why that change was made? If we could change the behaviour back to normally calling `startResizeWorker()` while still accomplishing what was being tried then I think that would be ideal.

**Comment by TriKriSta** [comment]
@anthonybilinski Yes I remember, startResizeWorker(visibleLines[1]) saves your position when you scroll down some messages are downloaded from the history and added to the chat

**Comment by anthonybilinski** [comment]
Got it, thanks, that makes sense. So the behaviour was changed from before scrolling all the way to the bottom on message, to now (supposed to) just shift the chat up by the height of that message, so that if you're scrolled all the way down, you'll stay at the bottom, but if you're not, your view will just shift by one message.

And the issues with the new behaviour are:
1) this mentioned difference between scrolling to visibleLines[1] and scrolling the height of a line, since lines can be partially visible, causing us to become unstuck from the bottom sometimes
2) IMO if the user is scrolled up, their chat view shouldn't change if they send/receive a new message. This was point 2 of my issue here https://github.com/qTox/qTox/issues/5882

IMO the ideal behaviour would be:
1) If scrolled all the way down, stay scrolled all the way when a new message is added to the bottom.
2) If not scrolled down all the way, the view should not move at all when a new message is received (i.e. sticking a new message on the bottom should effectively scroll you up one line.) As as added bonus, it would be nice if there was a UI indication that new messages have been received bellow the current visible chat.

I'll work on updating this PR to match that described behaviour.

**Comment by TriKriSta** [comment]
Oh, I see. But I think this problem will need to fix on another pull request because chat position must be checked before we add messages to it

**Comment by TriKriSta** [comment]
I found another bug
if we scroll up a long time, some messages will remove from the chat. And if someone sends messages, the chat won't load messages which were deleted again.
So, if we check the position chat before adding new messages, we won't have these two problems
And new messages will load from history when we will scroll down.

**Comment by anthonybilinski** [comment]
Yes I've seen that behaviour as well, identified here: https://github.com/qTox/qTox/issues/5824.

**Comment by anthonybilinski** [comment]
Some notes from looking into this some more:
1) for `void ChatLog::insertChatlineAtBottom(const QList<ChatLine::Ptr>& newLines)`, copying `void ChatLog::insertChatlineAtBottom(ChatLine::Ptr l)`'s scroll behaviour of caching `bool stickToBtm = stickToBottom();` then doing the same layout it does after editing `lines` works great for adding new messages.
    1) but! this breaks the scroll down behaviour. If a user is scrolled up in history, and their bottom messages have been removed, when they scroll back down, we want to load historey, add new messages onto the bottom, but not move the scroll location, similar to `insertChatlinesOnTop`. Since the cache of `stickToBottom` is hit, we will get snapped all the way down, which is undesired. I think ChatLog needs to be made aware if it's adding a real new message, in which case it should stay scrolled to bottom, or if it's adding loaded history, in which case it should not snap down. This can maybe be done by renaming and differentiating between `ChatLog::insertChatlineAtBottom(const QList<ChatLine::Ptr>& newLines)` and `ChatLog::insertChatlineAtBottom(ChatLine::Ptr l)`

My changes with the described problems are at https://github.com/anthonybilinski/qTox/tree/message_scroll, feel free to include or work off of them. I'm planning on continuing work on them tomorrow.

**Comment by TriKriSta** [comment]
I think chat will need to scroll down if a user sends messages If a user receives messages chat won't need to scroll down, only send an alarm.

**Comment by TriKriSta** [comment]
Does this pull request have some problems that need to be fixed?

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
Sorry for the delay, I didn't realize that you pushed new commits and that this was ready to be re-reviewed.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5889#-:-LuHOUQxEYRML6Q3LRms:bmxfy7u)* status: 0 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.h, line 70 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHgslU7A9ePPEyMxVq:-LuHgslU7A9ePPEyMxVr:bpvmots) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/chatlog/chatlog.h#L70)):*
> ```objc
>     bool isEmpty() const;
>     bool hasTextToBeCopied() const;
>     bool stickToBottom() const;
> ```

I don't think this visibility change is needed with the architectural changes mentioned below
___
*[src/chatlog/chatlog.cpp, line 411 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHQEEz0Up2STp9h44o:-LuHQEF-8RGpyjGef1Da:bq7txxm) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/chatlog/chatlog.cpp#L411)):*
> ```cpp
> 
>     // user sends one message, but program sometimes sends message with date, and we have 2 messages
>     if (newLines.size() > 2 && visibleLines.size() > 1) {
> ```

like mentioned in https://github.com/qTox/qTox/pull/5889#issuecomment-544200966, I don't think the issue is that multiple lines are coming in at once. I think our scroll behaviour should be independent of how many messages are received, or how many lines are visible. What we want is
1) If we're scrolled to bottom, stay scrolled to bottom
2) If we're not scrolled to bottom, don't shift the scroll pan
___
*[src/model/ichatlog.h, line 142 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHYTSlB3FHhhJrp1gT:-LuHYTSmDSnOwd9pvdZh:b-8kod6q) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/model/ichatlog.h#L142)):*
> ```objc
> 
> signals:
>     void itemUpdated(ChatLogIdx idx, bool isSend = false);
> ```

the itemUpdated signal is a generic signal that's just saying "This index needs to be re-rendered", information of whether a message was sent shouldn't be bundled with a signal just asking for a GUI update. Instead, you could connect a slot that scrolls to bottom with `IMessageDispatcher::messageSent`, in parallel with `SessionChatLog::onMessageSent`.
___
*[src/model/sessionchatlog.cpp, line 378 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHZX5m-yTUmb7gy772:-LuHZX5m-yTUmb7gy773:bj8bld6) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/model/sessionchatlog.cpp#L378)):*
> ```cpp
>     outgoingMessages.insert(id, messageIdx);
> 
>     emit this->itemUpdated(messageIdx, true);
> ```

same as above.
___
*[src/widget/widget.h, line 346 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_05AC9NRQ-S16H8h:-LuH_05AC9NRQ-S16H8i:b-sslmlu) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.h#L346)):*
> ```objc
>     QMap<ToxPk, std::shared_ptr<ChatHistory>> friendChatLogs;
>     QMap<ToxPk, std::shared_ptr<FriendChatroom>> friendChatrooms;
>     QMap<ToxPk, std::shared_ptr<ChatForm>> chatForms;
> ```

it would be nice to leave this cleanup out of the bugfix PR. Not that it's a bad change, but changing as little as possible to fix the bug will reduce the chance of introducing new bugs before release. Cleanup like this could be done as a separate PR and merged to master instead of the release branch.
___
*[src/widget/widget.h, line 358 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_AT7B2WGrI8VS5W7:-LuH_AT7B2WGrI8VS5W8:b-w2sjqf) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.h#L358)):*
> ```objc
>     QMap<GroupId, std::shared_ptr<IChatLog>> groupChatLogs;
>     QMap<GroupId, std::shared_ptr<GroupChatroom>> groupChatrooms;
>     QMap<GroupId, std::shared_ptr<GroupChatForm>> groupChatForms;
> ```

same (out of scope)
___
*[src/widget/widget.cpp, line 585 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_Em_D960d_xt4WVf:-LuH_Em_D960d_xt4WVg:b-w2sjqf) ([raw file](https://github.com/qtox/qtox/blob/7349b44154f22f6ef0be7880a97cb210d55ca982/src/widget/widget.cpp#L585)):*
> ```cpp
>         delete form;
>     }
> ```

same (out of scope)
___
*[src/widget/widget.cpp, line 1151 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_H-8-SR0B6IP_6uD:-LuH_H-8-SR0B6IP_6uE:b-w2sjqf) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1151)):*
> ```cpp
>     friendChatrooms[friendPk] = chatroom;
>     friendWidgets[friendPk] = widget;
>     chatForms[friendPk] = std::shared_ptr<ChatForm>(friendForm);
> ```

same (out of scope)
___
*[src/widget/widget.cpp, line 1330 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_IW_35SaDXNCvp3Z:-LuH_IW_35SaDXNCvp3_:b-w2sjqf) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1330)):*
> ```cpp
>     } else {
>         id = group->getPersistentId();
>         form = groupChatForms[id].get();
> ```

same (out of scope)
___
*[src/widget/widget.cpp, line 1378 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHbobG2-29LMGq4mJN:-LuHbobG2-29LMGq4mJO:b2lsj8m) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1378)):*
> ```cpp
>         }
> 
>         connect(currentForm.get(), &GenericChatForm::stickToBottom, this, &Widget::changeStatusLight);
> ```

Instead of having Widget track the current chat, Widget can use the existing place that we update status light, in `Widget::newFriendMessageAlert`. It knows what friend the notification came from, and which chatform is currently selected already. If a parameter was added to that function of e.g. "isScrolledUp", that could be used with the existing "hasActive" parameter to update the status light even if hasActive is true, if isScrolledUp is also true. This would reduce the state that Widget has to track, and remove the need for this block of code.
___
*[src/widget/widget.cpp, line 1419 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHds7DBrCwtbj63Cjq:-LuHds7DBrCwtbj63Cjr:bqmig9u) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1419)):*
> ```cpp
>     }
> 
>     auto form = chatForms[friendPk].get();
> ```

out of scope
___
*[src/widget/widget.cpp, line 1476 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHdsaGDKY8ZqpZac2Y:-LuHdsaGDKY8ZqpZac2Z:bqmig9u) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1476)):*
> ```cpp
>     }
> 
>     auto chatForm = groupChatForms[groupId].get();
> ```

out of scope
___
*[src/widget/widget.cpp, line 1645 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHdxIE2WvAaQE5rbnz:-LuHdxIE2WvAaQE5rbo-:bnatbl1) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1645)):*
> ```cpp
> {
>     bool inactiveWindow = isMinimized() || !currentWindow->isActiveWindow();
>     bool isNeedAlert = (currentForm != nullptr) && currentForm.get()->isNeedMessageAlert();
> ```

as mentioned, this could be passed in
___
*[src/widget/widget.cpp, line 1762 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHe2Io2LJ8BzXUM54w:-LuHe2Io2LJ8BzXUM54x:bqmig9u) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1762)):*
> ```cpp
> 
>     auto chatForm = chatForms.find(friendPk);
>     chatForms.erase(chatForm);
> ```

out of scope
___
*[src/widget/widget.cpp, line 1842 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHe3RQB-9Thb-YWinl:-LuHe3RQB-9Thb-YWinm:b28ne7n) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1842)):*
> ```cpp
> }
> 
> void Widget::changeStatusLight()
> ```

I don't think this function is needed anymore if integrated into newMessageAlert
___
*[src/widget/widget.cpp, line 2037 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHeapi1KB6AliqeHKh:-LuHeapi1KB6AliqeHKi:bqmig9u) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2037)):*
> ```cpp
>     assert(g);
> 
>     auto form = groupChatForms[groupId].get();
> ```

out of scope
___
*[src/widget/widget.cpp, line 2141 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHebaL0BmCk2_g41zd:-LuHebaL0BmCk2_g41ze:bqmig9u) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2141)):*
> ```cpp
>     groupWidgets[groupId] = widget;
>     groupChatrooms[groupId] = chatroom;
>     groupChatForms[groupId] = std::shared_ptr<GroupChatForm>(form);
> ```

out of scope
___
*[src/widget/widget.cpp, line 2208 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHeclF502Y2rH-kkLD:-LuHeclF502Y2rH-kkLE:bhieqvi) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2208)):*
> ```cpp
>         break;
>     case QEvent::WindowActivate:
>         changeStatusLight();
> ```

I think it can be kept as it was, if scrolled up notification is integrated into existing notification
___
*[src/widget/widget.cpp, line 2337 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHeiO4-qxuWw3tWw8K:-LuHeiO4-qxuWw3tWw8L:bqmig9u) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2337)):*
> ```cpp
>     const auto message = tr("Message failed to send");
>     const auto curTime = QDateTime::currentDateTime();
>     auto form = groupChatForms[groupId].get();
> ```

out of scope
___
*[src/widget/form/genericchatform.h, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHgyuM8Lh4GCD_ZYIZ:-LuHgyuM8Lh4GCD_ZYI_:b-38aghh) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.h#L86)):*
> ```objc
>     QDateTime getLatestTime() const;
>     QDateTime getFirstTime() const;
>     bool isNeedMessageAlert() const;
> ```

I don't think any of these three changes are needed with the mentioned architectural change
___
*[src/widget/form/genericchatform.cpp, line 438 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHgOMgDIiGZ7p2Ewgk:-LuHgOMgDIiGZ7p2Ewgl:b-x3jh7t) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.cpp#L438)):*
> ```cpp
> bool GenericChatForm::isNeedMessageAlert() const
> {
>     return !chatWidget->stickToBottom();
> ```

I don't think this API is needed if the "isScrolledUp" parameter is passed up from `ChatForm::incomingNotification`
___
*[src/widget/form/genericchatform.cpp, line 1108 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHTG6eC8zonRkh1PaC:-LuHTG6eC8zonRkh1PaD:b-h2tb4z) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.cpp#L1108)):*
> ```cpp
> {
>     if (chatWidget->stickToBottom()) {
>         renderMessages(idx, idx + 1);
> ```

skipping the renderMessage call causes messages sent by a friend while scrolled up to not be added to our chatlog. If a friend sends 10 messages, they don't appear in our chatlog until we scroll all the way to the bottom triggering a log load. They should be added to the chatlog even if scrolled up, but just not change the scroll position.
___
*[src/widget/form/genericchatform.cpp, line 1200 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHSgrc0IbQ9sBIylWE:-LuHSgrdEL1AsHp36iUM:b-1z8glp) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.cpp#L1200)):*
> ```cpp
>         chatWidget->scrollToLine(msg);
>     } else {
>         emit stickToBottom();
> ```


same, no longer needed if isScrolledUp" parameter is passed up from `ChatForm::incomingNotification`

**Review by TriKriSta — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5889#-:-LuYG_VoAONefZtZ0jQe:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/chatlog/chatlog.h, line 70 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHgslU7A9ePPEyMxVq:-LuY1nwDEs5FnaPYVllb:bfw8he1) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/chatlog/chatlog.h#L70)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't think this visibility change is needed with the architectural changes mentioned below
</blockquote></details>

but this method is used in other classes
___
*[src/chatlog/chatlog.cpp, line 411 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHQEEz0Up2STp9h44o:-LuY3-8v9gRYAZpRAKPw:b-h0boqe) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/chatlog/chatlog.cpp#L411)):*
> like mentioned in #5889 (comment), I don't think the issue is that multiple lines are coming in at once. I think our scroll behaviour should be independent of how many messages are received, or how many lines are visible. What we want is
> 
> If we're scrolled to bottom, stay scrolled to bottom
> If we're not scrolled to bottom, don't shift the scroll pan

this code check that messages were sent users and weren't sent program (load from history and other) I didn't find another way to check it. Maybe I will find it when I will edit widget scroll bar
___
*[src/model/ichatlog.h, line 142 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHYTSlB3FHhhJrp1gT:-LuY4Hlx88D8lxKCXuhX:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/model/ichatlog.h#L142)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

the itemUpdated signal is a generic signal that's just saying "This index needs to be re-rendered", information of whether a message was sent shouldn't be bundled with a signal just asking for a GUI update. Instead, you could connect a slot that scrolls to bottom with `IMessageDispatcher::messageSent`, in parallel with `SessionChatLog::onMessageSent`.
</blockquote></details>

Done.
___
*[src/model/sessionchatlog.cpp, line 378 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHZX5m-yTUmb7gy772:-LuY4MFODTWgBYW7wema:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/model/sessionchatlog.cpp#L378)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same as above.
</blockquote></details>

Done.
___
*[src/widget/widget.h, line 346 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_05AC9NRQ-S16H8h:-LuY4RH7BWJUdvm0zySd:b5mlf9a) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.h#L346)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

it would be nice to leave this cleanup out of the bugfix PR. Not that it's a bad change, but changing as little as possible to fix the bug will reduce the chance of introducing new bugs before release. Cleanup like this could be done as a separate PR and merged to master instead of the release branch.
</blockquote></details>

I need these a change for turn off a status light
___
*[src/widget/widget.h, line 358 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_AT7B2WGrI8VS5W7:-LuY5LQ64w8ZDLi9rGPA:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.h#L358)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same (out of scope)
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 585 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_Em_D960d_xt4WVf:-LuY5NRY-Rlo2WwXG6vF:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/7349b44154f22f6ef0be7880a97cb210d55ca982/src/widget/widget.cpp#L585)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same (out of scope)
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 1151 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_H-8-SR0B6IP_6uD:-LuY5P2E6dMcPm5447M5:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1151)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same (out of scope)
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 1330 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuH_IW_35SaDXNCvp3Z:-LuY5YBd5mmAXSTz4gMR:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1330)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same (out of scope)
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 1378 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHbobG2-29LMGq4mJN:-LuY5oA-38iuEiMomvLL:blhsvfc) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1378)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Instead of having Widget track the current chat, Widget can use the existing place that we update status light, in `Widget::newFriendMessageAlert`. It knows what friend the notification came from, and which chatform is currently selected already. If a parameter was added to that function of e.g. "isScrolledUp", that could be used with the existing "hasActive" parameter to update the status light even if hasActive is true, if isScrolledUp is also true. This would reduce the state that Widget has to track, and remove the need for this block of code.
</blockquote></details>

Widget::newFriendMessageAlert turn on status light when user send message. And turnOffStatusLight turn off it when user scroll chat down
___
*[src/widget/widget.cpp, line 1419 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHds7DBrCwtbj63Cjq:-LuY6fg84RRMB7H-h_Gt:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1419)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

out of scope
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 1476 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHdsaGDKY8ZqpZac2Y:-LuY6hF22jVwBJmmd0Xj:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1476)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

out of scope
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 1645 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHdxIE2WvAaQE5rbnz:-LuYG8fo5JIHN1Y_PI6D:bl3hn0p) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1645)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

as mentioned, this could be passed in
</blockquote></details>

I didn't understand this message(
___
*[src/widget/widget.cpp, line 1762 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHe2Io2LJ8BzXUM54w:-LuYA7rDAykAnaBSQvU1:b-yd4ya) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1762)):*
> ```
>     auto chatForm = chatForms.find(friendPk);
>     chatForms.erase(chatForm);
> ```
I wrote above
___
*[src/widget/widget.cpp, line 1842 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHe3RQB-9Thb-YWinl:-LuYAONM0N1sswZFMY8B:b6kdn2s) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L1842)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't think this function is needed anymore if integrated into newMessageAlert
</blockquote></details>

newMessageAlert use for turn on Status Light and turnOffStatusLight turn off it
___
*[src/widget/widget.cpp, line 2037 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHeapi1KB6AliqeHKh:-LuYAfW59IVXKHNlBD7r:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2037)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

out of scope
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 2141 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHebaL0BmCk2_g41zd:-LuYAh5j2Z9Rxsvwa_P9:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2141)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

out of scope
</blockquote></details>

I wrote above
___
*[src/widget/widget.cpp, line 2208 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHeclF502Y2rH-kkLD:-LuYAnkYDNhXbZNHiCvM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2208)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I think it can be kept as it was, if scrolled up notification is integrated into existing notification
</blockquote></details>

Done.
___
*[src/widget/widget.cpp, line 2337 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHeiO4-qxuWw3tWw8K:-LuYApOo6aCa5z-AeodU:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/widget.cpp#L2337)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

out of scope
</blockquote></details>

I wrote above
___
*[src/widget/form/genericchatform.h, line 86 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHgyuM8Lh4GCD_ZYIZ:-LuYBC7X4_I8qNBgOi1g:b41j2k9) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.h#L86)):*
> ```
> bool isNeedMessageAlert() const;
> ```
isNeedMessageAlert() is needed for change status light
___
*[src/widget/form/genericchatform.cpp, line 438 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHgOMgDIiGZ7p2Ewgk:-LuYBr0VAkhqSPz_fAQD:b-xyxj73) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.cpp#L438)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't think this API is needed if the "isScrolledUp" parameter is passed up from `ChatForm::incomingNotification`
</blockquote></details>

I didn't find when this signal is sent
___
*[src/widget/form/genericchatform.cpp, line 1108 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHTG6eC8zonRkh1PaC:-LuYF2_S72J8pcagskZS:b-2c1kfs) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.cpp#L1108)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

skipping the renderMessage call causes messages sent by a friend while scrolled up to not be added to our chatlog. If a friend sends 10 messages, they don't appear in our chatlog until we scroll all the way to the bottom triggering a log load. They should be added to the chatlog even if scrolled up, but just not change the scroll position.
</blockquote></details>

If we add messages and save positions sometimes we will have a little jump in chat. I didn't find good way to fix this problem. Maybe I will find it when I will edit scroll bar widget
___
*[src/widget/form/genericchatform.cpp, line 1200 at r1](https://reviewable.io/reviews/qtox/qtox/5889#-LuHSgrc0IbQ9sBIylWE:-LuYETgw91UeXpfw4jHn:b2t24fa) ([raw file](https://github.com/qtox/qtox/blob/6b2119ad29f870350c2c39ccc607f24545ac3a0a/src/widget/form/genericchatform.cpp#L1200)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

same, no longer needed if isScrolledUp" parameter is passed up from `ChatForm::incomingNotification`
</blockquote></details>

I wrote above

**Pull request closed without merging**
