### PR TITLE
fix(chatform): Add ability to cancel call

### LINKED ISSUE #4016: [Regression] unable to cancel audio call before it starts
##### Brief Description
qTox is unable to cancel audio call before it starts (when call button is yellow). It was possible on v1.6.0.

OS: Gentoo Linux amd64
qTox version: v1.7.0-5-gb4c4569
Commit hash: b4c4569299d734d8056e48a6d6dd62f4df2ae86f
toxcore: 0.1.2
Qt: 5.6.2

Reproducible: Always

##### Steps to reproduce

1. Press call button
2. Once it turns yellow, press it again to cancel audio call

##### Observed Behavior
Nothing happens. There's only a warning in the stdout:
```
core/coreav.cpp:257 : Debug: "Starting call with 7"
core/coreav.cpp:260 : Warning: "Can't start call with 7, we're already in this call!"
```

##### Expected Behavior
Audio call should be canceled.

##### Additional Info
`git bisect` with 
git bisect good v1.6.0
git bisect bad f5011cdb2feb2da042e373b4e4094e967bde8120

917812daaabc8b8118526691e67a3f6e2dd8fcb2 is the first bad commit
```
commit 917812daaabc8b8118526691e67a3f6e2dd8fcb2
Author: Nils Fenner <nilsfenner@web.de>
Date:   Mon Aug 29 09:07:23 2016 +0200

    fix: Status reflection for friend calls

:040000 040000 05af1848378a084330cf091d7f7f3218f7ad8f8b adcc966bbb1669a94fbef5cc53c2404f07881abd M	src
:040000 040000 1310dd21e85a5b5472fe35134385857ddc1a2a74 1c92acb8e15a02c40b6f94744e13729213e8e067 M	ui
```

cc @Diadlo @antis81

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4016.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4065)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4065#-:-Ka4HJX-V3H40koJtI1j:b-jbsf8z)*

**Comment by sudden6** [comment]
@zetok can you verify the fix?

**Comment by zetok** [comment]
(580d2df022a429920ece14d03dda01b18f48e5a7)
PR does fix the issue, but it also introduces a regression where call can't be made. I.e. pressing the green call button turns it to a yellow one for a split of second, and then it reverts back to green one.

stdout when clicking on audio call button:

```
[11:13:34.878 UTC] core/coreav.cpp:277 : Debug: "Starting call with 10"
[11:13:34.878 UTC] audio/audio.cpp:359 : Debug: Opening audio input "Live! Cam Chat HD [VF0700] Analog Mono"
[New Thread 0x7fff9bffe700 (LWP 2444)]
[11:13:34.889 UTC] audio/audio.cpp:384 : Debug: Opened audio input "Live! Cam Chat HD [VF0700] Analog Mono"
[11:13:34.889 UTC] audio/audio.cpp:312 : Debug: Subscribed to audio input device [ 1 subscriptions ]
[11:13:34.889 UTC] audio/audio.cpp:401 : Debug: Opening audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fff9b7fd700 (LWP 2450)]
[11:13:34.903 UTC] audio/audio.cpp:416 : Debug: Opened audio output "Built-in Audio Analog Stereo"
[New Thread 0x7fffb8450700 (LWP 2456)]
[11:13:34.905 UTC] audio/audio.cpp:685 : Debug: Audio source 2 created. Sources active: 1
[11:13:34.905 UTC] audio/audio.cpp:312 : Debug: Subscribed to audio input device [ 2 subscriptions ]
[11:13:34.905 UTC] audio/audio.cpp:328 : Debug: Unsubscribed from audio input device [ 1 subscriptions left ]
[11:13:34.999 UTC] core/coreav.cpp:766 : Warning: Call with friend 10 died of unnatural causes!
[11:13:34.999 UTC] audio/audio.cpp:328 : Debug: Unsubscribed from audio input device [ 0 subscriptions left ]
[11:13:34.999 UTC] audio/audio.cpp:531 : Debug: Closing audio input
[11:13:35.000 UTC] audio/audio.cpp:700 : Debug: Audio source 2 deleted. Sources active: 0
[Thread 0x7fff9bffe700 (LWP 2444) exited]
[Thread 0x7fffb8450700 (LWP 2456) exited]
[11:13:35.002 UTC] audio/audio.cpp:564 : Debug: Closing audio output
[Thread 0x7fff9b7fd700 (LWP 2450) exited]
```

Not sure about the exact steps to reproduce; I've been just rapidly clicking on audio/video call buttons. And I've tried to pick up canceled call on the other client.

spectacle mn7881
↑ calling around 7 times per second might be enough to trigger the regression.

**Comment by Diadlo** [comment]
@zetok ~~Are you a StarCraft gamer?~~
I can make only 5 calls click per second. Can't reproduce

**Comment by zetok** [comment]
since it fixes issue, :lgtm_strong: , but a new issue will need to be made about the regression (possibly just uncovers an underlying bug?)

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4065#-:-KbHAyJekN5JJ987n30b:btslr01)*

**Pull request merged**
