### PR TITLE
Have bootstrap fetch toxcore version with old (compatible) API

### PR DESCRIPTION
**Pull request by strk**
See https://lists.tox.im/pipermail/general/2015-April/000028.html

### CODE REVIEW

**Comment by Geremia** [comment]
https://github.com/irungentoo/toxcore/tree/api_old_version

**Comment by strk** [comment]
what about it, @Geremia ?
are you suggesting to send a pull request over there instead ?

**Comment by zetok** [comment]
No. This PR won't be merged anyway.

**Comment by tux3** [comment]
Closing, as we're about to merge the new API qTox.

**Pull request closed without merging**
