### PR TITLE
full support screenshot 2nd monitor

### LINKED ISSUE #1595: White screen when trying to take a screenshot on Windows
I use Windows 8.1 with two 1080p monitors.
If I try to take a screenshot, my second screen turns completely white. If I move qTox to my second screen and try to take a screenshot the same thing happens.

### PR DESCRIPTION
**Pull request by PKEv**
must fix #1595 
I do not have a second monitor please check: @Impyy @blobgo 
Check please in both configurations: the left and right sides of the main display

### CODE REVIEW

**Comment by alexbakker** [comment]
I can't check this because I don't have a Windows setup with 2 monitors anymore, sorry.

**Comment by agilob** [comment]
I assigned @antis81, I remember he said the has a multi-screen setup.

**Comment by antis81** [comment]
Multi-Monitor yes, but no Windows. Is that enough?

**Comment by PKEv** [comment]
I later try in Win
Thank you, @antis81 
please don't merge

**Comment by PKEv** [comment]
in windows, then 2-nd monitor on left side - work wrong

**Comment by zetok** [comment]
Since it affects windows users, perhaps it should be pushed to `testing` branch so that they could test?

**Comment by antis81** [comment]
@PKEv
Here's a nice example from the [Qt documentation](http://doc.qt.io/qt-5/qtwidgets-desktop-screenshot-example.html).

According to this, we can grab all screens regardless of their positioning like this:

``` c++
QPixmap ScreenshotGrabber::grabScreen()
{
    QScreen *screen = QGuiApplication::primaryScreen();
    if (screen)
        return screen->grabWindow(0);

    return QPixmap();
}
```

Wrote a little test application. Works perfectly (on Linux). :)

If this doesn't work on Windows/Mac for whatever reason, we need to do a little more work to find the (virtual) desktop area we actually want to grab.

**Comment by antis81** [comment]
@zetok Pushed my (!) code to `testing`. I think of cleaning it up further. Should I open new PR and close this one? It's invalid in the current form anyway!

**Comment by zetok** [comment]
@antis81 

> Should I open new PR and close this one? It's invalid in the current form anyway! 

yep

> Pushed my (!) code to `testing`. I think of cleaning it up further.

Btw, I think that `testing` branch probably should be deteted & then pushed to, or force pushed to, instead of putting new changes on top of whatever is sitting there.

**Pull request closed without merging**
