### PR TITLE
fix: gcc-7 build

### PR DESCRIPTION
**Pull request by mpxc**
Added missing include for this error: rawdatabase.h:27:20: error: 'std::function' has not been declared

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4404)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4404#-:-Kk2fQKLwB07SbOGV54Y:b-jbsf8z)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/persistence/db/rawdatabase.h, line 14 at r1](https://reviewable.io:443/reviews/qtox/qtox/4404#-Kk5ZCF0JHxY_nzvz_JL:-Kk5ZCF0JHxY_nzvz_JM:bjiukk6) ([raw file](https://github.com/qtox/qtox/blob/d04ad99659bd9f9ca229ac3645c210d16b29a972/src/persistence/db/rawdatabase.h#L14)):*
> ```objc
> #include <atomic>
> #include <memory>
> #include <functional>
> ```

please sort alphabetically

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4404)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4404#-:-Kk7-GqLpO5sHnu09OJe:b-jbsf8z)*

**Comment by Diadlo** [comment]
Please, squash commits

**Pull request merged**
