### PR TITLE
refactor: fixup chat form

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3909)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/widget/form/chatform.cpp, line 79 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KX9uV36X3XKZblwIxnR:-KX9uV36X3XKZblwIxnS:boo1x67) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/widget/form/chatform.cpp#L79)):*
> ```cpp
>     , isTyping(false)
> {
>     avatar->setPixmap(QPixmap(":/img/contact_dark.svg"));
> ```

This line is already executed below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/coreav.cpp, line 180 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXALqh__uOizmBqERyU:-KXALqh__uOizmBqERyV:b-514o12) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/core/coreav.cpp#L180)):*
> ```cpp
>     return f && calls.contains(f->getFriendID())
>             ? !(calls[f->getFriendID()].inactive)
>             : false;
> ```

This is wrong. Please revert.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by Diadlo** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/coreav.cpp, line 180 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXALqh__uOizmBqERyU:-KXCUe0VyZvU7lUy9gvi:bb76mu4) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/core/coreav.cpp#L180)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> This is wrong. Please revert.
</details>
Why?

---

*[src/widget/form/chatform.cpp, line 79 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KX9uV36X3XKZblwIxnR:-KXEv6GrSFeld3OvUx_D:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/widget/form/chatform.cpp#L79)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> This line is already executed below
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/coreav.cpp, line 180 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXALqh__uOizmBqERyU:-KXF6ru_StBVwrBCU-fO:b-9ndf1v) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/core/coreav.cpp#L180)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>
> Why?
</details>
Cause it reflects a false state. You ask for the call's state, not for the friend's state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/coreav.cpp, line 180 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXALqh__uOizmBqERyU:-KXF7Qaabc3AZGyvjjSs:b9bgj80) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/core/coreav.cpp#L180)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> Cause it reflects a false state. You ask for the call's state, not for the friend's state.
</details>
IOW: If a friend picks the phone, lays it besides the base station and walks away, the call is still active! If we want to automagically end the call when a friend does not return after one minute - well, just do that and end the call on the trigger. That would introduce another feature though, so I'd suggest to stick to bug/concept fixing. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/core/coreav.cpp, line 180 at r1](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXALqh__uOizmBqERyU:-KXFKqVJtM_WCeKLHfj-:b9rs278) ([raw file](https://github.com/qtox/qtox/blob/da1aca4b60f3093a44dc2106a749050477ed8a1b/src/core/coreav.cpp#L180)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> IOW: If a friend picks the phone, lays it besides the base station and walks away, the call is still active! If we want to automagically end the call when a friend does not return after one minute - well, just do that and end the call on the trigger. That would introduce another feature though, so I'd suggest to stick to bug/concept fixing. :)
</details>
Sorry, I mixed up friend and call status by myself. So the code looks actually correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
Reviewed 13 of 15 files at r1, 1 of 1 files at r2.
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/widget/tool/callconfirmwidget.h, line 50 at r2](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXFQLOANeYnN4BjqNlI:-KXFQLOB_IUuyeE_MHpz:b-mxufls) ([raw file](https://github.com/qtox/qtox/blob/ee33261364dcc1bf1a0b0bb0219668389e29299a/src/widget/tool/callconfirmwidget.h#L50)):*
> ```objc
>     void showEvent(QShowEvent* event) final override;
>     void hideEvent(QHideEvent* event) final override;
>     bool eventFilter(QObject *, QEvent* event) final override;
> ```

The `final` keyword is enough for final overrides, improving readability a little:

```c++
void paintEvent(QPaintEvent* event) final;
void showEvent(QShowEvent* event) final;
void hideEvent(QHideEvent* event) final;
void eventFilter(QObject* o, QEvent* event) final;
```

Please fix that in turn.

In general, final overrides look like this:

```c++
class BaseClass
{
public:
  virtual void method() = 0;
};

class OverriddenClass : public BaseClass
{
  void method() override;
};

class FinalClass : public OverriddenClass // alternatively inherit from BaseClass
{
  void method() final;
};
```

That's it!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
Please change commit title to something like: "fix: status reflection for friend calls".

**Comment by sudden6** [comment]
Reviewed 2 of 15 files at r1.
Review status: 14 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/widget/form/chatform.cpp, line 116 at r2](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXKoFOIxDYFz5rukG4F:-KXKoFOJcwM9OvoTUdTE:b-666zve) ([raw file](https://github.com/qtox/qtox/blob/ee33261364dcc1bf1a0b0bb0219668389e29299a/src/widget/form/chatform.cpp#L116)):*
> ```cpp
>     connect(core, &Core::fileSendFailed, this, &ChatForm::onFileSendFailed);
>     connect(core, &Core::receiptRecieved, this, &ChatForm::onReceiptReceived);
>     connect(core, &Core::friendMessageReceived,
> ```

IMO it would be better to either leave all `connect` statements as one line or convert everything to two lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by antis81** [comment]
:lgtm:

---

Reviewed 1 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909#-:-KXUiuGyUUjwUJnw51n7:bnfp4nl)*

**Comment by antis81** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/widget/form/chatform.cpp, line 116 at r2](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXKoFOIxDYFz5rukG4F:-KXUj11FjKYIkywSfRZe:b5gha78) ([raw file](https://github.com/qtox/qtox/blob/ee33261364dcc1bf1a0b0bb0219668389e29299a/src/widget/form/chatform.cpp#L116)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary>
> IMO it would be better to either leave all `connect` statements as one line or convert everything to two lines.
</details>
@sudden6 If you ask for a general rule, then it is: "Break at 80 columns.". The reason for this is, that screens are actually optimized for reading. The 80 column rule is given on every single (connect) line here and nothing should be changed about that. When a line reaches 80 columns, I break connects right before the  destination part, but that's only artistic freedom. :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by sudden6** [comment]
uhm, why did you ltgm if it doesn't even pass Travis? Also a rebase will probably invalidate it...

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/widget/form/chatform.cpp, line 116 at r2](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXKoFOIxDYFz5rukG4F:-KXVFaOUVK2T-CFhiR__:b7wpk5l) ([raw file](https://github.com/qtox/qtox/blob/ee33261364dcc1bf1a0b0bb0219668389e29299a/src/widget/form/chatform.cpp#L116)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary>
> @sudden6 If you ask for a general rule, then it is: "Break at 80 columns.". The reason for this is, that screens are actually optimized for reading. The 80 column rule is given on every single (connect) line here and nothing should be changed about that. When a line reaches 80 columns, I break connects right before the  destination part, but that's only artistic freedom. :smile:
</details>
@antis81 For qTox we actually choose 100 columns as soft limit see https://github.com/qTox/qTox/pull/3839 . Anyway I think it's just easier to parse mentally when a huge block follows the same style throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909#-:-KXVHcGb0Ia4TmaNGZ_G:b6cr793)*

**Comment by sudden6** [comment]
Reviewed 5 of 15 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by sudden6** [comment]
I didn't LGTM yet, because I want to get a second review from @antis81

**Comment by antis81** [comment]
@Diadlo I prepared a patch, which I want to send you over later as a file. This cleans up the code dependencies concerning the CallConfirmWidget and opens up the possibility for creating a more or less generic dialog. We can either merge this PR create another one on top, or add the directly on this one. Whatever you prefer.

**Comment by Diadlo** [comment]
@antis81 I prefer to create a new PR. @sudden6, @zetok Do you agree?

**Comment by zetok** [comment]
Yep.

**Comment by sudden6** [comment]
yep

**Comment by antis81** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/widget/form/chatform.cpp, line 424 at r4](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXjbJziHV6wvwsmAuWM:-KXjbJzj3bcYUgp3Y3ch:bnng7ii) ([raw file](https://github.com/qtox/qtox/blob/0bd2036b4d18eda401e36018d98ae4d5ce40b81c/src/widget/form/chatform.cpp#L424)):*
> ```cpp
>     }
> 
>     onAvStart(f->getFriendID(), av->isCallVideoEnabled(f));
> ```

FYI: Hm… I'm a bit confused about this line. It is marked unchanged in the PR, but in master it definitely changed (rebase??)! Can you please check that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909#-:-KXjdAa2gCuTClUosB_S:bnfp4nl)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[src/widget/form/chatform.cpp, line 424 at r4](https://reviewable.io:443/reviews/qtox/qtox/3909#-KXjbJziHV6wvwsmAuWM:-KXk0LYlgp4--YzjIFAA:b-5zanex) ([raw file](https://github.com/qtox/qtox/blob/0bd2036b4d18eda401e36018d98ae4d5ce40b81c/src/widget/form/chatform.cpp#L424)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

FYI: Hm… I'm a bit confused about this line. It is marked unchanged in the PR, but in master it definitely changed (rebase??)! Can you please check that?
</blockquote></details>

http://i.imgur.com/NmJsPo1.png

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909)*

**Comment by Diadlo** [comment]
@antis81 Can you use `:lgtm_stong:`? In order that it is not lost on rebase

**Comment by antis81** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3909#-:-KXo9Yu2VXuIRXx1P_xY:b-uwkowd)*

**Comment by antis81** [comment]
@Diadlo Feel free to merge after the build is ready.

**Pull request merged**
