### PR TITLE
fix(history): don't save own messages when history is disabled

### LINKED ISSUE #5036: qTox writes history file with chat history even when you disable that setting
##### Brief Description

OS: Windows 
Commit hash: 09eee940cdfc2f46b63bad866fac288430f10cb8
toxcore:  toxcore version: 0.2.1
Qt version: 5.10.1
…

Reproducible: Always 

##### Steps to reproduce

Disable all settings that need database features like faux offline message and history. Delete the db files and restart qtox to write something. When you look into the database you will find your chat history.

##### Expected Behavior
There should be no databse created at all.

----
[qtox.log](https://github.com/qTox/qTox/files/1854005/qtox.log)

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #5036

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5038)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5038#-:-L8n4P4QBrllsHP8rFZ2:b-jbsf8z)*

**Comment by tox-user** [comment]
```
qWarning() << "Blocked a message from being added to database while history is disabled";
```
When history is disabled, this warning will be printed on every message. There is no need to fill people's logs with this.

**Comment by anthonybilinski** [comment]
@tox-user when history is disabled, no one should be calling down to History::addNewMessage. The other two places we call down (Profile::onRequestSent and Widget::onFriendMessageReceived) have checks in place to not call down when history is disabled, like the one I added here for ChatForm.

The log just serves as a double-check to prevent something like this from happening again.

**Comment by tox-user** [comment]
I misunderstood, my bad.

**Pull request merged**
