### PR TITLE
feat: UI to import a list of contacts from a file

### LINKED ISSUE #4181: [Enhancement] Import contact list
Hello

I would like to be able to import a centrally managed user list ( essentially a list of Pubkeys, maybe with the current user names as additional information). We are a growing company and I would prefer a simpler alternative to the copy-and-paste-orgy which new users have to endure until all their colleagues are on the contact list. 

Also: Should clicking on tox:toxid - links work in the moment on Linux or Windows? In both cases I get a messages about X being not a proper toxme address and repeated clicking causes multiple client to start up to the profile selector windows.

Is there any guide how to get this working?

Grüße
Stefan

### PR DESCRIPTION
**Pull request by Diadlo**
Resolves #4181

Rebase #4182 + style fix

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4577)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 256 at r1](https://reviewable.io:443/reviews/qtox/qtox/4577#-Krqr2aoBh-hlPPsLQXt:-Krqr2apEl0xa0sRhHwD:b5wrpb3) ([raw file](https://github.com/qtox/qtox/blob/4ae9a324882f87dc1df3ebd6f13e51012a34fb9f/src/widget/form/addfriendform.cpp#L256)):*
> ```cpp
>         QString line = contactsToImport[i].trimmed();
>         qDebug() << line;
>         if (line.isEmpty() || (!ToxId::isToxId(line) && !line.contains(dnsIdExpression)))
> ```

missing braces

---

*[src/widget/form/addfriendform.cpp, line 364 at r1](https://reviewable.io:443/reviews/qtox/qtox/4577#-Krqr5CHiaJ7eu_FSjLE:-Krqr5CHiaJ7eu_FSjLF:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/4ae9a324882f87dc1df3ebd6f13e51012a34fb9f/src/widget/form/addfriendform.cpp#L364)):*
> ```cpp
> 
>     if (contactsToImport.isEmpty())
>         importFileLabel.setText(tr("Import a list of contacts, one Tox ID per line"));
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 256 at r1](https://reviewable.io:443/reviews/qtox/qtox/4577#-Krqr2aoBh-hlPPsLQXt:-KrqtAah7dzTuk26r8AV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4ae9a324882f87dc1df3ebd6f13e51012a34fb9f/src/widget/form/addfriendform.cpp#L256)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

missing braces
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 364 at r1](https://reviewable.io:443/reviews/qtox/qtox/4577#-Krqr5CHiaJ7eu_FSjLE:-KrqtBf03tbMs_WeZwDS:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4ae9a324882f87dc1df3ebd6f13e51012a34fb9f/src/widget/form/addfriendform.cpp#L364)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577#-:-Krr-4IYnnom7pmIYJSw:b-jbsf8z)*

**Comment by noavarice** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 92 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruH7cex_bdTr3Vzgfw:-KruH7cex_bdTr3Vzgfx:b2ftjoe) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L92)):*
> ```cpp
>     connect(&sendButton, &QPushButton::clicked, this, &AddFriendForm::onSendTriggered);
>     connect(&importSendButton, &QPushButton::clicked, this, &AddFriendForm::onImportSendClicked);
>     connect(&importFileButton, &QPushButton::clicked, this, &AddFriendForm::onImportOpenClicked);
> ```

What do you think about re-writing this three `connect`s using macro? :D

---

*[src/widget/form/addfriendform.cpp, line 255 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruKkJjq41aPx-VFn-I:-KruKkJjq41aPx-VFn-J:b-1gb2ha) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L255)):*
> ```cpp
> 
>     QRegularExpression dnsIdExpression("^\\S+@\\S+$");
>     contactsToImport = QString::fromUtf8(contactFile.readAll()).split("\n");
> ```

Use symbol instead of string

---

*[src/widget/form/addfriendform.cpp, line 256 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruCTq0TUvHX7VEEvyQ:-KruCTq0TUvHX7VEEvyR:b4gs3yu) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L256)):*
> ```cpp
>     QRegularExpression dnsIdExpression("^\\S+@\\S+$");
>     contactsToImport = QString::fromUtf8(contactFile.readAll()).split("\n");
>     for (int i = contactsToImport.size() - 1; i >= 0; --i) {
> ```

I do not see any reason for reverse iteration except `qDebug` messages order. If it is not important, use [QMutableListIterator](https://stackoverflow.com/questions/8613737/how-can-i-remove-elements-from-a-qlist-while-iterating-over-it-using-foreach?answertab=votes#tab-top) or any other Qt-supported iteration mechanism

---

*[src/widget/form/addfriendform.cpp, line 259 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruCrqsPC0BLUOTY0EY:-KruCrqsPC0BLUOTY0EZ:b-l2aikm) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L259)):*
> ```cpp
>         QString line = contactsToImport[i].trimmed();
>         qDebug() << line;
>         if (line.isEmpty() || (!ToxId::isToxId(line) && !line.contains(dnsIdExpression))) {
> ```

Too complex condition. I think, reverting it with `!line.isEmpty() && (ToxId::isToxId(line) || line.contains(dnsIdExpression))` will be clearer.

---

*[src/widget/form/addfriendform.cpp, line 356 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruF4tXSQ29MwsaNmp-:-KruF4tXSQ29MwsaNmp0:b-cl5zr1) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L356)):*
> ```cpp
>     headLabel.setText(tr("Add Friends"));
>     messageLabel.setText(tr("Message", "The message you send in friend requests"));
>     importMessageLabel.setText(messageLabel.text());
> ```

Extract message text into const variable

---

*[src/widget/form/addfriendform.cpp, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruL74l8vYt7dMOb36k:-KruL74mbuaNmlmTqiXl:b-o3u89k) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L369)):*
> ```cpp
>         importFileLabel.setText(tr("Import a list of contacts, one Tox ID per line"));
>     } else {
>         importFileLabel.setText(tr("Ready to import %1 contacts, click send to confirm",
> ```

I think, cases when there is 1 contact to import and more than 1 should be distinguished

---

*[src/widget/form/addfriendform.h, line 94 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruFS9CtFmN5XPyAJxP:-KruFS9CtFmN5XPyAJxQ:b-z3v1kd) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.h#L94)):*
> ```objc
>     QTextEdit message, importMessage;
>     QVBoxLayout layout, headLayout, importContactsLayout;
>     QHBoxLayout importFileLine;
> ```

Please, replace only added GUI components with pointers to avoid unnecessary headers importing as much as possible. Also it would be better to declare every single (added?) component by line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Diadlo** [comment]
@sudden6 I add some changes

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 92 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruH7cex_bdTr3Vzgfw:-KrzladcR_tfSz7HAF0b:b-8ejkc0) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L92)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

What do you think about re-writing this three `connect`s using macro? :D
</blockquote></details>

I don't think, that it's good idea

---

*[src/widget/form/addfriendform.cpp, line 255 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruKkJjq41aPx-VFn-I:-KrzlnYC3v4KyVk4SZEz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L255)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Use symbol instead of string
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 256 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruCTq0TUvHX7VEEvyQ:-KrzpZ7OO2y-cVOrYnpv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L256)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I do not see any reason for reverse iteration except `qDebug` messages order. If it is not important, use [QMutableListIterator](https://stackoverflow.com/questions/8613737/how-can-i-remove-elements-from-a-qlist-while-iterating-over-it-using-foreach?answertab=votes#tab-top) or any other Qt-supported iteration mechanism
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 259 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruCrqsPC0BLUOTY0EY:-KrzmL9zbR0P-qb6Ack2:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L259)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Too complex condition. I think, reverting it with `!line.isEmpty() && (ToxId::isToxId(line) || line.contains(dnsIdExpression))` will be clearer.
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 356 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruF4tXSQ29MwsaNmp-:-KrzmdqyrsrpgWG66afU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L356)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Extract message text into const variable
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruL74l8vYt7dMOb36k:-Krzmm-eRz_EDyJuR9xP:bb76mu4) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L369)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I think, cases when there is 1 contact to import and more than 1 should be distinguished
</blockquote></details>

Why?

---

*[src/widget/form/addfriendform.h, line 94 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruFS9CtFmN5XPyAJxP:-KrzrydHmxnY5QB2ndHx:b1mc8rx) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.h#L94)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Please, replace only added GUI components with pointers to avoid unnecessary headers importing as much as possible. Also it would be better to declare every single (added?) component by line
</blockquote></details>

I don't think, that avoid extra `include` is good price to low segmentation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577#-:-KrzwxCZoxa_pNQW_Clo:bnj4oal)*

**Comment by noavarice** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruL74l8vYt7dMOb36k:-Ks-15bzJIef7rQMDtoh:b73ab1z) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L369)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

`Ready to import 1 contacts` does not seem to be reasonable for me

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/form/addfriendform.cpp, line 369 at r3](https://reviewable.io:443/reviews/qtox/qtox/4577#-KruL74l8vYt7dMOb36k:-Ks-3jZRk3yIU4hr5y-e:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/67490260041e0cd8509df72899d7176cb95f47e9/src/widget/form/addfriendform.cpp#L369)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

`Ready to import 1 contacts` does not seem to be reasonable for me
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 155 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-gDdEMrDLBIGHkjfZ:-Ks-gDdEMrDLBIGHkjf_:bpx59yu) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L155)):*
> ```cpp
> {
>     const QString msg = importMessage.toPlainText();
>     return !msg.isEmpty() ? msg : importMessage.placeholderText();
> ```

This could be simplified just a little bit by removing "!" and swapping operands.

---

*[src/widget/form/addfriendform.cpp, line 234 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-h2VWLqnjWjqQSjSD:-Ks-h2VWLqnjWjqQSjSE:bqxhdeo) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L234)):*
> ```cpp
> void AddFriendForm::onImportOpenClicked()
> {
>     QString path = QFileDialog::getOpenFileName(tabWidget, tr("Open contact list"));
> ```

const QString

---

*[src/widget/form/addfriendform.cpp, line 257 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-hQJD4xDW5vicmH9h:-Ks-hQJD4xDW5vicmH9i:b-bur9sl) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L257)):*
> ```cpp
>             it.remove();
>         }
>         qDebug() << it.next();
> ```

Is this debug needed in production? If so, maybe it would be useful to have some prefix or additional info explaining what is it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 247 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-k9dzebWyZMZMzMYW:-Ks-k9dzebWyZMZMzMYX:b-6vf6tf) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L247)):*
> ```cpp
>     }
> 
>     contactsToImport = QString::fromUtf8(contactFile.readAll()).split('\n');
> ```

QString accepts QChar (not simple char), and it's constructor has QLatin1Char-receiving simplified overload, so QLatin1Char('\n').

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 155 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-gDdEMrDLBIGHkjfZ:-Ks0P14We-63Fq4Y7bhW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L155)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

This could be simplified just a little bit by removing "!" and swapping operands.
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 234 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-h2VWLqnjWjqQSjSD:-Ks0P99DBbNE20RW_4Qb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L234)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QString
</blockquote></details>

Done.

---

*[src/widget/form/addfriendform.cpp, line 247 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-k9dzebWyZMZMzMYW:-Ks0PfJbPinRxpfgFaRx:b-sbju2a) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L247)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

QString accepts QChar (not simple char), and it's constructor has QLatin1Char-receiving simplified overload, so QLatin1Char('\n').
</blockquote></details>

`split` has overload which accept `QChar`. `QChar` can be constructed from `char`. Or I miss something?

---

*[src/widget/form/addfriendform.cpp, line 257 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-hQJD4xDW5vicmH9h:-Ks0QC34by88hlsSxviF:b-h9565f) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L257)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Is this debug needed in production? If so, maybe it would be useful to have some prefix or additional info explaining what is it.
</blockquote></details>

Since qTox still not finished, debug messages always needed :)
Have added "header"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/widget/form/addfriendform.cpp, line 247 at r7](https://reviewable.io:443/reviews/qtox/qtox/4577#-Ks-k9dzebWyZMZMzMYW:-Ks-ilCIn5YpKbDpsGDj:b-swphrg) ([raw file](https://github.com/qtox/qtox/blob/43c6d07d8f10de76d15dc0e7cc6c8ced02744bc9/src/widget/form/addfriendform.cpp#L247)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`split` has overload which accept `QChar`. `QChar` can be constructed from `char`. Or I miss something?
</blockquote></details>

Oh your'e right, sorry.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4577)*

**Comment by noavarice** [comment]
:lgtm_strong:

**Pull request merged**
