### PR TITLE
Core cleanup

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5841)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5841)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1106 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZsBNT7v4Hf6QKBRDP:-LpZsBNT7v4Hf6QKBRDQ:bfe954i) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1106)):*
> ```cpp
>     ToxString cTitle(title);
>     Tox_Err_Conference_Title error;
>     bool success = tox_conference_set_title(tox.get(), groupId, cTitle.data(), cTitle.size(), &error);
> ```

checking `success` seems now redundant, no?
___
*[src/core/core.cpp, line 1110 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZsIE157M7UwBc5bmU:-LpZsIE157M7UwBc5bmV:b-m34hy1) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1110)):*
> ```cpp
>         emit saveRequest();
>         emit groupTitleChanged(groupId, getUsername(), title);
>         return;
> ```

this return is now unecessary
___
*[src/core/core.cpp, line 1372 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZto3d7DCRdvj-KnOG:-LpZto3d7DCRdvj-KnOH:b-9usxf1) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1372)):*
> ```cpp
> 
>     for (size_t i = 0; i < groupCount; ++i) {
>         TOX_ERR_CONFERENCE_TITLE error;
> ```

The type of this error variable doesn't seem to fit the others, can you check why?

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5841)* status: 0 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1106 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZsBNT7v4Hf6QKBRDP:-LpubYh_Ao3s9Ww1FGlD:bt01cay) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1106)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

checking `success` seems now redundant, no?
</blockquote></details>

I would think so, but tox.h's comment is:
```
/**
 * Set the conference title and broadcast it to the rest of the conference.
 *
 * Title length cannot be longer than TOX_MAX_NAME_LENGTH.
 *
 * @return true on success.
 */
```
so I figured keeping the check in on return value until the API is updated is a safety measure.
___
*[src/core/core.cpp, line 1110 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZsIE157M7UwBc5bmU:-LpucaMN04v5Vzgv1pe5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1110)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

this return is now unecessary
</blockquote></details>

Done.
___
*[src/core/core.cpp, line 1372 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZto3d7DCRdvj-KnOG:-Lpudhb5-6CZGsUMs4Tw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1372)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The type of this error variable doesn't seem to fit the others, can you check why?
</blockquote></details>

Done.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5841#-:-LpwhuyD1XEE36q_fyyo:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1106 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZsBNT7v4Hf6QKBRDP:-LpwhlS_9TE7oHoHvxWn:b1sb31w) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1106)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I would think so, but tox.h's comment is:
```
/**
 * Set the conference title and broadcast it to the rest of the conference.
 *
 * Title length cannot be longer than TOX_MAX_NAME_LENGTH.
 *
 * @return true on success.
 */
```
so I figured keeping the check in on return value until the API is updated is a safety measure.
</blockquote></details>

ok, but should probably open a ticket on c-toxcore

**Review by anthonybilinski — COMMENTED** [review]
Updated to change parser calls to macro calls that inject the call site into the error logs, so that we don't just get the QDebug line number of the log location, and can actually tell what API  call site errored. Do you mind reviewing the update and the macro usage? Thanks :)

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5841#-:-LqAkceLA2_8oI1mNE4C:btfx0ou)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 1106 at r3](https://reviewable.io/reviews/qtox/qtox/5841#-LpZsBNT7v4Hf6QKBRDP:-Lq5iWnI9RUnyq0_Qcvl:b-fy3ii3) ([raw file](https://github.com/qtox/qtox/blob/f8e3f9e2feb0fc04488988fee6b6dde70eb79578/src/core/core.cpp#L1106)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ok, but should probably open a ticket on c-toxcore
</blockquote></details>

taking a look at tox.h again, at the top of the file they talk about the error enum, and only mention the return error in the case where no error enum is available.. so I'll go ahead and remove the check in our code
```
 * Every error code type has an OK value to which functions will set their error
 * code value on success. Clients can keep their error code uninitialised before
 * passing it to a function. The library guarantees that after returning, the
 * value pointed to by the error code pointer has been initialised.
```

I'll throw updating the individual API comments in toxcore on my list

**Review by sudden6 — COMMENTED** [review]
macros and update :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5841#-:-LqCA7Hc9p4E7eUUrA3Y:b-ey8hg8)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
