### PR TITLE
doc(codingstyle): update min qt version

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4499)

### CODE REVIEW

**Comment by Diadlo** [comment]
Oh, I forgot to change comment in `.travis/build-ubuntu-14-04.sh` Can you change it here too?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4499#-:-Knixi7prgqeoP8SzSLd:bmzc2pe)*

**Comment by Diadlo** [comment]
Amend commit `s/doc/docs/`

**Comment by sudden6** [comment]
Done

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4499#-:-Knjc1eZ5J6Zcze-tilF:bb6un1j)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4499#-:-KnjmQhqiU2gtHcF7ebn:b-jbsf8z)*

**Pull request merged**
