### PR TITLE
translate "aboute page" in Russian

### PR DESCRIPTION
**Pull request by PKEv**

### CODE REVIEW

**Comment by suhr** [comment]
Remove obsolete items, please (`-no-obsolete` option of lupdate).

**Comment by ghost** [comment]
@suhr should all translations use the `-no-obsolete` option? If yes, the command in the wiki should be updated

https://github.com/tux3/qTox/wiki/Translating#if-youre-just-updating

**Comment by suhr** [comment]
It's better to use `-no-obsolete` after translation, but not before.

**Comment by ghost** [comment]
I don't understand when I should use it. My workflow is

`pull` -> `lupdate` -> `linguist` -> `push`

should I `lupdate -no-obsolete` without other arguments after `linguist`?

**Comment by suhr** [comment]
pull → `lupdate` → `linguist` → `lupdate -no-obsolete qtox.pro -ts ‹path to ts file›` → push
This allows you to see (and use) obsolete translations in qt linguist, but get rid of them when everything is translated.

**Pull request merged**
