### PR TITLE
Added support for local links in messages

### PR DESCRIPTION
**Pull request by PKEv**
Added support for local links in messages and correct detect links like "www.123.com"
default

### CODE REVIEW

**Comment by agilob** [comment]
Is this needed? The only case when I can think it's need is when you're chatting with someone in the same (V)LAN  and you want to access common resource on LAN drive.

Anyone for or against this change?

**Comment by PKEv** [comment]
i use this case
And while there is support for such links...
it should not interfere with other users

**Comment by TheNain38** [comment]
I use this to indicate a directory that is common to windows to help others, like:
file:///C:/Windows/System32/drivers/etc/hosts

**Comment by agilob** [comment]
PR introduces regressions:

doesn't detect `tox:user@doman.com` format

First TOX-URI is detected correctly, second not, TOX id have constant length, third ID is invalid as well.

parsin2

First line shouldn't be detected as URI, opening it results in:
parsin1

**Comment by PKEv** [comment]
It does not introduce - saves
in my stable qTox link "tox:agilob@toxme.com" don't detected too
@agilob You sure that link as "www.123.com" should not be detected?
The lack of specified protocol is not so critical, it is strange that this is not happening correctly of association of links (in win i can't reproduce) 
I'll see what can be done..

**Comment by agilob** [comment]
> in my stable qTox link "tox:agilob@toxme.com" don't detected too

But it should ;)

> @agilob You sure that link as "www.123.com" should not be detected?

qTox uses qdesktopservices to open link and if protocol is undefined link is opened as local resource. www without http never works.

**Comment by SkyzohKey** [comment]
So maybe that you could just replace links like `www.example.com` by `http://www.example.com`, It would basically solve the problem without adding a lot of regression to the link system, right ?

**Comment by zetok** [comment]
@SkyzohKeyx no. Messing with user input is a bad idea.

**Comment by agilob** [comment]
> , It would basically solve the problem without adding a lot of regression to the link system, right ?

No, we can't modify user input/output...

**Comment by PKEv** [comment]
I just did not understand, but it actually earlier replace the protocol for the type of links work "www.123.com",

**Comment by PKEv** [comment]
fix all, please look

**Comment by PKEv** [comment]
I restored the substitution of reference because the user does not have to know how to write link
As an example in Google when you copy a link from the address bar is added to the protocol

**Comment by agilob** [comment]
tox:<id> doesnt work

**Comment by PKEv** [comment]
how it should work?
in the stable branch, nothing happens by pressing

**Comment by agilob** [comment]
on my setup it opens 'add contact' window

**Comment by PKEv** [comment]
in my stable qTox it start new process

**Comment by zetok** [comment]
@PKEv  #1926 ?

**Comment by PKEv** [comment]
i create new #2271 , because the title (in  #1926) does not reflect the nature of the problem

**Comment by PKEv** [comment]
then, please merge

**Comment by agilob** [comment]
@PKEv this message:

```
tox:A5CB22B35202E91CE49CD2CE07AF036C1410179D47D2E110A1E1D9D7AD59042FF1C7D6685D57
```

should be clickable `tox:76 hex characters`

**Comment by PKEv** [comment]
fix

**Comment by TheNain38** [comment]
Can this be merged?

**Comment by agilob** [comment]
Sure, I do merges of ready code in evenings.

**Pull request merged**
