### PR TITLE
feat(icons): Icons was updated

### PR DESCRIPTION
**Pull request by Diadlo**
Icon border was added

### CODE REVIEW

**Comment by zetok** [comment]
#3161

**Comment by Diadlo** [comment]
Fix #3161.

**Comment by Diadlo** [comment]
Screenshots. Left is new, right -- old

spectacle bz6510
spectacle mn6723
spectacle dt6723
spectacle lh6723

**Comment by ProMcTagonist** [comment]
@Diadlo The loop of the lock looks very skinny now, and the point of the speech bubble is distorted as well. Could the outline be thinner or further away?

**Comment by Diadlo** [comment]
@ProMcTagonist It is the most tiny outline, which seems normal. I think, that point of the speech bubble is normal. But yes, loop looks skinny. May be I should make circle and body of lock smaller?

**Comment by NoxNoctium** [comment]
Proposals here somewhat related: #2671

**Comment by sudden6** [comment]
The outline definitely makes the icon look smaller, is there a way to put the border on the outsides of the current icon?

**Comment by Diadlo** [comment]
@sudden6 I don't know way. Because size of old icon was equals to size of picture. I must make icon smaller to add border

**Comment by sudden6** [comment]
ok, makes sense, I'm unsure if that's what everybody wants.
@zetok @tux3 opinions?

**Comment by zetok** [comment]
new icon looks kinda weird: weird look
and the white one looks outright broken white broken

**Pull request closed without merging**
