### PR TITLE
[Refactor] Add ProfileInfo

### PR DESCRIPTION
**Pull request by Diadlo**
FYI: I plan to move Toxme in separate model class

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4716)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 7 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/model/profile/profileinfo.cpp, line 140 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvswVjFhxx-ARmjNPW2:-KvswVjGgONswSXVwSwy:biml642) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/model/profile/profileinfo.cpp#L140)):*
> ```cpp
> {
>     QString current = profile->getName() + Core::TOX_EXT;
>     if (path.isEmpty()) {
> ```

success on empty path, are you sure?

---

*[src/model/profile/profileinfo.cpp, line 176 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvswsFWxIDGXdDEkKpk:-KvswsFWxIDGXdDEkKpl:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/model/profile/profileinfo.cpp#L176)):*
> ```cpp
> {
>     QString current = profile->getName() + ".png";
>     if (path.isEmpty()) {
> ```

same

---

*[src/model/profile/profileinfo.cpp, line 205 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvswuGhCpi_yNgKLs7R:-KvswuGhCpi_yNgKLs7S:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/model/profile/profileinfo.cpp#L205)):*
> ```cpp
> IProfileInfo::SetAvatarResult ProfileInfo::setAvatar(const QString &path)
> {
>     if (path.isEmpty()) {
> ```

same

---

*[src/widget/form/profileform.h, line 31 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvsyKbZNphMt65gYpjG:-KvsyKb_Ka72vs8GbIZd:b-kjbsvm) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/widget/form/profileform.h#L31)):*
> ```objc
> 
> class ContentLayout;
> class Core;
> ```

unused now?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by Diadlo** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/model/profile/profileinfo.cpp, line 140 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvswVjFhxx-ARmjNPW2:-KvwU5ejsw49wuihNVhj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/model/profile/profileinfo.cpp#L140)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

success on empty path, are you sure?
</blockquote></details>

Done.

---

*[src/model/profile/profileinfo.cpp, line 176 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvswsFWxIDGXdDEkKpk:-KvwU63BI2SI7wa0tM3x:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/model/profile/profileinfo.cpp#L176)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[src/model/profile/profileinfo.cpp, line 205 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvswuGhCpi_yNgKLs7R:-KvwU6Sm4OIq2hZutnqn:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/model/profile/profileinfo.cpp#L205)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by Diadlo** [comment]
Review status: 6 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/widget/form/profileform.h, line 31 at r1](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvsyKbZNphMt65gYpjG:-KvwUBd3ML-L_tVv_FXf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/109d086408b673caaee9b79ef91011afa5975cc0/src/widget/form/profileform.h#L31)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

unused now?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by sudden6** [comment]
Reviewed 2 of 4 files at r2.
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/model/profile/profileinfo.cpp, line 30 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-Kvwlw6eqOhVBXiWbwcZ:-Kvwlw6f_Cl6QewXQpdQ:b7qe9x9) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L30)):*
> ```cpp
> #include <QFile>
> #include <QBuffer>
> ```

add doxygen documentation to the class and all functions

---

*[src/model/profile/profileinfo.cpp, line 31 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwlfaQRpP17ZfVmEnA:-KvwlfaRH7gqLxuQudc_:b-dqvcyg) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L31)):*
> ```cpp
> #include <QBuffer>
> 
> ProfileInfo::ProfileInfo(Core* core, Profile *profile)
> ```

document that `core` and `profile` must not be `nullptr`

---

*[src/model/profile/profileinfo.cpp, line 61 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-Kvwk_jcmG8y5knMZizh:-Kvwk_jdj0PIBR-JiYli:bcuevk7) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L61)):*
> ```cpp
>     ToxId selfId = profile->getCore()->getSelfId();
>     QString txt = selfId.toString();
>     QClipboard* clip = QApplication::clipboard();
> ```

check for null pointer?

---

*[src/widget/form/profileform.cpp, line 419 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnvGxLuavm107Jgpe:-KvwnvGxLuavm107Jgpf:b-2zqeg6) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L419)):*
> ```cpp
> }
> 
> static const QPair<QString, QString> CAN_NOT_CHANGE_PASSPORD = {
> ```

typo `CAN_NOT_CHANGE_PASSWORD`

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-KvwnbRqpeGqlbID7ixO:b-soc5ks) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
> ```cpp
>     }
> 
>     //: deletion confirmation title
> ```

why did you change the comment style for `tr(...)` here? everywhere else we use `tr(phrase, comment)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by Diadlo** [comment]
Review status: 4 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/profile/profileinfo.cpp, line 30 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-Kvwlw6eqOhVBXiWbwcZ:-Kvzu_le_2hcvHf6p4W7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L30)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

add doxygen documentation to the class and all functions
</blockquote></details>

Done.

---

*[src/model/profile/profileinfo.cpp, line 31 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwlfaQRpP17ZfVmEnA:-Kvzua1WACyPWuLo2vsM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L31)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

document that `core` and `profile` must not be `nullptr`
</blockquote></details>

Done.

---

*[src/model/profile/profileinfo.cpp, line 61 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-Kvwk_jcmG8y5knMZizh:-KvzlRcLFDH8PzfdU7Vn:b5azfmd) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L61)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

check for null pointer?
</blockquote></details>

In docs no information, that it `QApplication::clipboard()` can return `nullptr` if QApplication already constructed.
Add in docs info, that it should be used, only if QApplication constructed

---

*[src/widget/form/profileform.cpp, line 419 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnvGxLuavm107Jgpe:-KvzmY72OgkzRAbyuzKe:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L419)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `CAN_NOT_CHANGE_PASSWORD`
</blockquote></details>

Done.

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-Kvzm3kOiuL-HDXDe4Jm:b-8ie7z9) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why did you change the comment style for `tr(...)` here? everywhere else we use `tr(phrase, comment)`
</blockquote></details>

Reverted.

Exactly here -- no reason. Just to make consistent with the next line.
I change translation comment style to make lines shorter. It helps avoid line breaks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by sudden6** [comment]
Reviewed 6 of 8 files at r3.
Review status: 8 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/model/profile/profileinfo.cpp, line 61 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-Kvwk_jcmG8y5knMZizh:-KwH28c19yQQfOsu2S_C:b32w0x) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/model/profile/profileinfo.cpp#L61)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

In docs no information, that it `QApplication::clipboard()` can return `nullptr` if QApplication already constructed.
Add in docs info, that it should be used, only if QApplication constructed
</blockquote></details>

OK

---

*[src/model/profile/profileinfo.cpp, line 126 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2ILsry10Hzdv0gD1:-KwH2ILsry10Hzdv0gD2:b-fba5b8) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L126)):*
> ```cpp
> /**
>  * @brief Remove characters not supported for profile name from string.
>  * @param src Sorce string.
> ```

typo `Source`

---

*[src/model/profile/profileinfo.cpp, line 176 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2VAtOpRah8GsnjRR:-KwH2VAuUwmyRbYwrRQ1:b-jx47x7) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L176)):*
> ```cpp
> 
> /**
>  * @brief Dangerous way to find out if a path is writable.
> ```

Would be good to add why this operation is dangerous.

---

*[src/model/profile/profileinfo.cpp, line 189 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2ersDWaG9Fb3VG5-:-KwH2ersDWaG9Fb3VG50:b98xwkm) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L189)):*
> ```cpp
> 
> /**
>  * @brief Save profile in cusom place.
> ```

typo `custom`

---

*[src/model/profile/profileinfo.cpp, line 213 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2qeErji2wNImefeJ:-KwH2qeFNh_AOEtSeCYl:bdbgze2) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L213)):*
> ```cpp
> /**
>  * @brief Remove profile.
>  * @return List of files, which can't be removed automaticaly.
> ```

`which couldn't be removed` (past tense) is better here, since we already tried to remove them

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-KwH4CAjlnll_ArauGG0:b-ryk3a) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Reverted.

Exactly here -- no reason. Just to make consistent with the next line.
I change translation comment style to make lines shorter. It helps avoid line breaks.
</blockquote></details>

I think we should prefer the `tr( ... , ... )` style, because it always keeps comment and translation logically grouped in a C++ syntax way. Should we write that into the coding style?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by Diadlo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/model/profile/profileinfo.cpp, line 126 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2ILsry10Hzdv0gD1:-KwH8TLke3vIk8_ubc1v:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L126)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `Source`
</blockquote></details>

Done.

---

*[src/model/profile/profileinfo.cpp, line 176 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2VAtOpRah8GsnjRR:-KwH7JY3QfujT-Q2nGrj:bwc913s) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L176)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Would be good to add why this operation is dangerous.
</blockquote></details>

IDK :(
Just copied from Nexus

---

*[src/model/profile/profileinfo.cpp, line 189 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2ersDWaG9Fb3VG5-:-KwH8_EioLWJlC1kznAv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L189)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `custom`
</blockquote></details>

Done.

---

*[src/model/profile/profileinfo.cpp, line 213 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2qeErji2wNImefeJ:-KwH8gw6uLBRnIp3OWM-:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L213)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`which couldn't be removed` (past tense) is better here, since we already tried to remove them
</blockquote></details>

Done.

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-KwH7PJboqdrl-BP6a65:b-18s1td) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I think we should prefer the `tr( ... , ... )` style, because it always keeps comment and translation logically grouped in a C++ syntax way. Should we write that into the coding style?
</blockquote></details>

["No god, please, no"](https://www.youtube.com/watch?v=umDr0mPuyQc)
Comment in the same line with source string is huge formatting problem. `//:` is good solution. Is still in the same place, just one line above. Why you didn't like it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by sudden6** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/profile/profileinfo.cpp, line 176 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2VAtOpRah8GsnjRR:-KwHB9XKB-b7WeMKzG9K:bie589e) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L176)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

IDK :(
Just copied from Nexus
</blockquote></details>

maybe add a TODO then to find out what's dangerous^^

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-KwHBJPbl2XJBpYSOT7p:bv93jnk) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

["No god, please, no"](https://www.youtube.com/watch?v=umDr0mPuyQc)
Comment in the same line with source string is huge formatting problem. `//:` is good solution. Is still in the same place, just one line above. Why you didn't like it?
</blockquote></details>

~Because a comment and a code line are easily separated by accident, while that generates a syntax error with the other syntax.~

Seems according to http://doc.qt.io/qt-5/i18n-source-translation.html your way is the correct one to comment translations in Qt5, the two argument syntax is used for disambiguation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by Diadlo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/profile/profileinfo.cpp, line 176 at r3](https://reviewable.io:443/reviews/qtox/qtox/4716#-KwH2VAtOpRah8GsnjRR:-KwHJfEsrokPFNgu7hcJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5143ca2d6efca025f60209f30c5ad606451ec65f/src/model/profile/profileinfo.cpp#L176)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

maybe add a TODO then to find out what's dangerous^^
</blockquote></details>

Done.

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-KwHK0Y11JF5Ie3nnjjG:buvg3s4) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

~Because a comment and a code line are easily separated by accident, while that generates a syntax error with the other syntax.~

Seems according to http://doc.qt.io/qt-5/i18n-source-translation.html your way is the correct one to comment translations in Qt5, the two argument syntax is used for disambiguation.
</blockquote></details>

A second parameter has a huge indentation if they separated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by sudden6** [comment]
Reviewed 1 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/widget/form/profileform.cpp, line 432 at r2](https://reviewable.io:443/reviews/qtox/qtox/4716#-KvwnbRqpeGqlbID7ixN:-KwHLZ77SfpC9Iqqb8rl:b-dyz4of) ([raw file](https://github.com/qtox/qtox/blob/53ee0f73b6c560224cd28a3ac64539bfa1569ddf/src/widget/form/profileform.cpp#L432)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

A second parameter has a huge indentation if they separated
</blockquote></details>

While I still don't like it, I think it's better to stick to the convention of Qt, so it's ok for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4716#-:-KwHLlPma-0eH19JT36P:b-jbsf8z)*

**Comment by Diadlo** [comment]
Constants moved on the top of `cpp` file

**Pull request merged**
