### PR TITLE
Remove GUI class, delegate responsibilites to new MessageBoxManager, Widget, Nexus

### PR DESCRIPTION
**Pull request by anthonybilinski**
Based on https://github.com/qTox/qTox/pull/6564

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6566)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 72 of 72 files at r1, 3 of 3 files at r2, 32 of 32 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 112 of 112 files at r6, 49 of 49 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6566)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 71 at r6](https://reviewable.io/reviews/qtox/qtox/6566#-MyWj6uw9n3JwGNbHebX:-MyWj6uw9n3JwGNbHebY:b-m0g8xe) ([raw file](https://github.com/qtox/qtox/blob/76919b2d4ce6edffa918580663eaf4f865a9817d/src/nexus.cpp#L71)):*
> ```cpp
>     , widget{nullptr}
>     , style{new Style()}
>     , messageBoxManager{new MessageBoxManager()}
> ```

Since one `MessageBoxManager` is created in main, why not just inject that one into `Nexus` instead of creating a new one and destroying it?
___
*[src/widget/style.cpp, line 376 at r3](https://reviewable.io/reviews/qtox/qtox/6566#-MyWhOJo2sWokP-Lb02G:-MyWhOJo2sWokP-Lb02H:b5xffur) ([raw file](https://github.com/qtox/qtox/blob/cebc6e0fbfab3ca44c6f5e6b10b85ab2382fcc5b/src/widget/style.cpp#L376)):*
> ```cpp
> void Style::applyTheme()
> {
>     emit themeReload();
> ```

I wonder if there's a Qt mechanism to update the style of the whole application. Not blocking this review on that though.

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6566)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 71 at r6](https://reviewable.io/reviews/qtox/qtox/6566#-MyWj6uw9n3JwGNbHebX:-My_bJZAEibqAOsye6et:bn91u5f) ([raw file](https://github.com/qtox/qtox/blob/76919b2d4ce6edffa918580663eaf4f865a9817d/src/nexus.cpp#L71)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Since one `MessageBoxManager` is created in main, why not just inject that one into `Nexus` instead of creating a new one and destroying it?
</blockquote></details>

Ah, bug. Yeah I was initially constructing in Nexus, then later constructed in main and passed it in through `setMessageBoxManager` because I realized profile needed it from main. Removed the duplicate construction Nexus' constructor.
___
*[src/widget/style.cpp, line 376 at r3](https://reviewable.io/reviews/qtox/qtox/6566#-MyWhOJo2sWokP-Lb02G:-My_bYeQ0W-uqpq_W0Ix:b-37nhrm) ([raw file](https://github.com/qtox/qtox/blob/cebc6e0fbfab3ca44c6f5e6b10b85ab2382fcc5b/src/widget/style.cpp#L376)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I wonder if there's a Qt mechanism to update the style of the whole application. Not blocking this review on that though.
</blockquote></details>

Yeah this does seem like an awful lot of boilerplate code for something that seems like pretty generic behaviour :thinking:

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 150 of 150 files at r8, 22 of 87 files at r9, 49 of 141 files at r12, 29 of 78 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6566)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 71 at r6](https://reviewable.io/reviews/qtox/qtox/6566#-MyWj6uw9n3JwGNbHebX:-MycI8AFDNrJrSPlpg_j:b7qotbb) ([raw file](https://github.com/qtox/qtox/blob/76919b2d4ce6edffa918580663eaf4f865a9817d/src/nexus.cpp#L71)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Ah, bug. Yeah I was initially constructing in Nexus, then later constructed in main and passed it in through `setMessageBoxManager` because I realized profile needed it from main. Removed the duplicate construction Nexus' constructor.
</blockquote></details>

Please initialize `messageBoxManager` with `nullptr`
___
*[src/widget/tool/imessageboxmanager.cpp, line 22 at r13](https://reviewable.io/reviews/qtox/qtox/6566#-MycJ9X30KV17MHNMo8Y:-MycJ9X30KV17MHNMo8Z:b-zbby1h) ([raw file](https://github.com/qtox/qtox/blob/5c912f8a92f01326b7441ebd618f015097fa886d/src/widget/tool/imessageboxmanager.cpp#L22)):*
> ```cpp
> #include "src/widget/tool/imessageboxmanager.h"
> 
> IMessageBoxManager::~IMessageBoxManager() = default;
> ```

Can't you put this into the header?

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6566)* status: 0 of 1 LGTMs obtained

___
*[src/nexus.cpp, line 71 at r6](https://reviewable.io/reviews/qtox/qtox/6566#-MyWj6uw9n3JwGNbHebX:-MyvAthv-GtqLYdfwQ4h:bfbq99i) ([raw file](https://github.com/qtox/qtox/blob/76919b2d4ce6edffa918580663eaf4f865a9817d/src/nexus.cpp#L71)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Please initialize `messageBoxManager` with `nullptr`
</blockquote></details>

Good point, done.
___
*[src/widget/tool/imessageboxmanager.cpp, line 22 at r13](https://reviewable.io/reviews/qtox/qtox/6566#-MycJ9X30KV17MHNMo8Y:-MyvBEd62UDkaKWm8DjJ:b-4x7box) ([raw file](https://github.com/qtox/qtox/blob/5c912f8a92f01326b7441ebd618f015097fa886d/src/widget/tool/imessageboxmanager.cpp#L22)):*
Intentional to due -Wweak-vtables: https://releases.llvm.org/13.0.0/tools/clang/docs/DiagnosticsReference.html#wweak-vtables

> warning: A has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit

This avoid some linking bloat, apparently. This was originally added to qTox in https://github.com/qTox/qTox/pull/6394.

**Review by sudden6 — APPROVED** [review]
> Reviewed 1 of 141 files at r12, 121 of 121 files at r16, 32 of 32 files at r17, 4 of 4 files at r18, 1 of 1 files at r19, 112 of 112 files at r20, 49 of 49 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6566)* status: 0 of 1 LGTMs obtained

___
*[src/widget/tool/imessageboxmanager.cpp, line 22 at r13](https://reviewable.io/reviews/qtox/qtox/6566#-MycJ9X30KV17MHNMo8Y:-MyvF5wQ6iwnhm7ufrsG:b-b3rck0) ([raw file](https://github.com/qtox/qtox/blob/5c912f8a92f01326b7441ebd618f015097fa886d/src/widget/tool/imessageboxmanager.cpp#L22)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Intentional to due -Wweak-vtables: https://releases.llvm.org/13.0.0/tools/clang/docs/DiagnosticsReference.html#wweak-vtables

> warning: A has no out-of-line virtual method definitions; its vtable will be emitted in every translation unit

This avoid some linking bloat, apparently. This was originally added to qTox in https://github.com/qTox/qTox/pull/6394.
</blockquote></details>

ok, already forgot about that :D

**Pull request merged**
