### PR TITLE
translate to russian "contacts groups"

### PR DESCRIPTION
**Pull request by PKEv**

### CODE REVIEW

**Comment by PKEv** [comment]
after load i see that names of tab not translated...
but in "ru.ts" all was translated... 
What could be the problem?
default

**Comment by tux3** [comment]
They aren't translated properly. I opened the ru.ts and none of them are validated.

ss013

Did you forget to click the validate translation button (green check mark) ?

**Comment by PKEv** [comment]
correct, but this don't help... 
default
perhaps this is due to #1861

**Comment by tux3** [comment]
That's interesting, since it still works in every other language.
Have you tried removing the "final" specifiers in the "class XXX final : public GenericForm" lines?

**Comment by PKEv** [comment]
yes, removing the "final" specifiers  is help

**Pull request merged**
