### PR TITLE
add local conferrence black list feature.

### PR DESCRIPTION
**Pull request by tetsaicn**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4610)

### CODE REVIEW

**Comment by kitech** [comment]
[this is the demo shot](https://img.vim-cn.com/63/23754ece50c1f6e5094bea5c3d8828d945bbed.png)

**Comment by sudden6** [comment]
This PR doesn't pass Travis CI, because of https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#commit-message-format

Also, please add a short description of this feature to https://github.com/qTox/qTox/blob/master/doc/user_manual_en.md

---

Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/widget/widget.cpp, line 1694 at r1](https://reviewable.io:443/reviews/qtox/qtox/4610#-KstcQLkhLktiRMjtLs5:-KstcQLlDMYw-jYPCmr9:b-u2etyx) ([raw file](https://github.com/qtox/qtox/blob/8efe7253f2e0fdbad07671ed333c12721e5ecb97/src/widget/widget.cpp#L1694)):*
> ```cpp
>     const Settings& s = Settings::getInstance();
>     if (s.getBlackList().contains(author.toString())) {
>         qDebug()<<"filtered:"<<author.toString();
> ```

please add some spaces here

---

*[src/widget/form/settings/privacysettings.ui, line 123 at r1](https://reviewable.io:443/reviews/qtox/qtox/4610#-KstcmfLKNb7OsRdRT6D:-KstcmfLKNb7OsRdRT6E:bu4lqca) ([raw file](https://github.com/qtox/qtox/blob/8efe7253f2e0fdbad07671ed333c12721e5ecb97/src/widget/form/settings/privacysettings.ui#L123)):*
> ```XML
>         <widget class="QGroupBox" name="groupBox">
>          <property name="title">
>           <string>BlackList</string>
> ```

Please add a description what this feature does as a tooltip

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610#-:-KstdIn-GjGzvtWvH3Iu:bfhwp9g)*

**Comment by kitech** [comment]
thanks. got that commit style.

**Comment by sudden6** [comment]
You can use only one word inside the braces, e.g. `feat(chatform):`

**Comment by Diadlo** [comment]
And length of the scope (text in the braces) should be less or equal 12

**Comment by sudden6** [comment]
Code looks good now, can you please add one or two sentences to the user manual, to document this feature?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610#-:-Kt7h59hfW4fkUpl2FmI:b-nlo81g)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/settings.cpp, line 339 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN1bi_V99zWDRj9CmB:-KtN1biajQ2gMFxT8hbq:bqucy1z) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/persistence/settings.cpp#L339)):*
> ```cpp
>         typingNotification = ps.value("typingNotification", true).toBool();
>         enableLogging = ps.value("enableLogging", true).toBool();
>         blackList = ps.value("blackList", "").toString().split("\n");
> ```

Do not use "" for creating empty QString, it calls copy constructor. Better using default constructor  with `QString{}`.

Actually, there is no need to put second argument at all in this case, default QVariant() will work OK.

Also, there is no need to create QString `"\n"`, char `'\n'` is quite enough.

---

*[src/persistence/settings.cpp, line 1744 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN3fkuPswtxSHq7ESw:-KtN3fkuPswtxSHq7ESx:b-cr92i2) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/persistence/settings.cpp#L1744)):*
> ```cpp
> }
> 
> void Settings::setBlackList(QStringList& blist) {
> ```

Brace should be after newline:
```
void Settings::setBlackList(QStringList& blist) 
{
``
```


---

*[src/persistence/settings.cpp, line 1749 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN406rVGAmPVfarPgm:-KtN406rVGAmPVfarPgn:b-oyqke) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/persistence/settings.cpp#L1749)):*
> ```cpp
>     if (blist != blackList) {
>         blackList = blist;
>         emit blackListChanged(blackList);
> ```

emitting signal under mutex, coulnd't this produce deadlock in some situation?

Maybe unlocking and emitting `blist` local variable would work?

---

*[src/persistence/settings.h, line 442 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN4S35JUuiyVXuOIDk:-KtN4S35JUuiyVXuOIDl:bb83anl) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/persistence/settings.h#L442)):*
> ```objc
>     void setTypingNotification(bool enabled);
>     QStringList getBlackList() const;
>     void setBlackList(QStringList& blist);
> ```

I guess it could be **const** QStringList& blist

---

*[src/widget/form/settings/privacyform.cpp, line 95 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN5JpdSXl7ufl5OLOu:-KtN5JpdSXl7ufl5OLOv:b-unua89) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/widget/form/settings/privacyform.cpp#L95)):*
> ```cpp
>     bodyUI->cbTypingNotification->setChecked(s.getTypingNotification());
>     bodyUI->cbKeepHistory->setChecked(Settings::getInstance().getEnableLogging());
>     bodyUI->blackListTextEdit->setText(s.getBlackList().join("\n"));
> ```

`'\n'`

---

*[src/widget/form/settings/privacyform.cpp, line 124 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN5PNbq7jPJu40MTPe:-KtN5PNcY2CP6IFUVUbQ:bggmdko) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/widget/form/settings/privacyform.cpp#L124)):*
> ```cpp
> void PrivacyForm::on_blackListTextEdit_textChanged()
> {
>     QStringList strlist = bodyUI->blackListTextEdit->toPlainText().split("\n");
> ```

`'\n'`,
also,`const QStringList`, if `setBlackList` will be updated to take const reference (it should).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610)*

**Comment by kitech** [comment]
@Talkless nice code style
the locker problem, there has some other code like this. need more fix if has deadlock

**Comment by sudden6** [comment]
Review status: 3 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[doc/user_manual_en.md, line 273 at r3](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtkwRn9Hm422efdWt8o:-KtkwRnAwS-FaWZLrrDi:b1mmfzx) ([raw file](https://github.com/qtox/qtox/blob/ba36ce0a52aab52c157b637bf7b99d88eb333a52/doc/user_manual_en.md#L273)):*
> ```Markdown
> #### BlackList
> 
> BlackList is a feature of Tox that locally block group member's messages across all you joined groups who spam these groups. You need put member's public key one perline into the BlackList text edit. Since now qTox has no method to get group member's, for now you can't directly get the member's public key. I think this will some more work for easy use.
> ```

suggestion for more "english" text:

`BlackList is a feature of qTox that locally blocks a group member's messages across all your joined groups, in case someone spams a group. You need to put a members public key into the BlackList text box one per line to activate it. Currently qTox doesn't have a method to get the public key from a group member, this will be added in the future.`

Please open an issue on Github about not being able to get the public key from a group member.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610)*

**Comment by sudden6** [comment]
@kitech don't forget to make a comment, else nobody will get notifications

**Comment by sudden6** [comment]
Reviewed 2 of 4 files at r3, 1 of 1 files at r4.
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610)*

**Comment by sudden6** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/settings.cpp, line 1749 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN406rVGAmPVfarPgm:-KuFzr9F7pVurPGmwUxH:b-v0ua0i) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/persistence/settings.cpp#L1749)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

emitting signal under mutex, coulnd't this produce deadlock in some situation?

Maybe unlocking and emitting `blist` local variable would work?
</blockquote></details>

Only when the SLOT function also changes the blacklist, so I see no problem here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610)*

**Comment by kitech** [comment]
I think so, no problem here. but the SLOT need use the variable without change it.
How about emit a const variable here?

**Comment by sudden6** [comment]
IIRC variables in SLOTs are passed by value anyway, so that also shouldn't be a problem.

**Comment by Talkless** [comment]
Review status: 6 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/persistence/settings.cpp, line 1749 at r2](https://reviewable.io:443/reviews/qtox/qtox/4610#-KtN406rVGAmPVfarPgm:-KuKjmbi5mJE93pH8D0u:bycxah2) ([raw file](https://github.com/qtox/qtox/blob/c3a8a22ec220b961962e240e27af32535598d582/src/persistence/settings.cpp#L1749)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Only when the SLOT function also changes the blacklist, so I see no problem here.
</blockquote></details>

`bigLock` is used not only for blaclists. What if SLOT calls getBlackList(), getWhatver that again locks `bigLock`?

Maybe in *current* implementation qTox does not introduces factual deadlock, but who knows how what code do in the future.

[CP.22: Never call unknown code while holding a lock (e.g., a callback)](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cp22-never-call-unknown-code-while-holding-a-lock-eg-a-callback)

UDPATE: Oh I see that bigLock is recursive, OK then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610)*

**Comment by Talkless** [comment]
Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 4 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4610#-:-KuQamRdMjs0mmWkFgRw:b-jbsf8z)*

**Pull request merged**
