### PR TITLE
German translation updates

### PR DESCRIPTION
**Pull request by sudden6**

### CODE REVIEW

**Comment by ghost** [comment]
I'm guessing that this will be rejected. You should make a PR that only includes `de.ts`

**Comment by sudden6** [comment]
yeah I wasn't sure if I should run lupdate for all languages and since it produced such a huge diff I thought it hasn't been run for a long time.

**Comment by zetok** [comment]
@sudden6 https://github.com/tux3/qTox/wiki/Translating#if-youre-just-updating `:)`

**Comment by tux3** [comment]
Sorry, I can't take this as is. Please send a new PR with only the de.ts.

**Comment by sudden6** [comment]
Ok I'm made a new one, hopefully right now ;)

**Pull request closed without merging**
