### PR TITLE
fix: Fixed crash on profile import

### LINKED ISSUE #3660: Crash on Profile Import: Assertion `Nexus::getDesktopGUI()' failed.
##### Brief Description

OS: Arch Linux, 64bit
qTox version: v1.5.1-63-gfcfac15
Commit hash: fcfac15c785f6cca5a38b9aa4f915fb805aec161
toxcore: 0.0.0
Qt: 5.7.0

Reproducible: Always
##### Steps to reproduce
1. Try to import .tox profile
##### Observed Behavior

Immediate crash with this console output:

qtox: ../src/widget/gui.cpp:50: GUI::GUI(QObject*): Assertion `Nexus::getDesktopGUI()' failed.
[1]    3590 abort (core dumped)  qtox
##### Expected Behavior

Import profile data and not crash.

[qtox.txt](https://github.com/qTox/qTox/files/440408/qtox.txt)

### PR DESCRIPTION
**Pull request by Diadlo**
Fixed #3660.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3668)

### CODE REVIEW

**Comment by antis81** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/widget/tool/profileimporter.cpp, line 25 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3668#-KQUNoeCKuElX2lBeXSd:-KQUNoeDdYdtHwhqpawv:bho5mze) ([raw file](https://github.com/qtox/qtox/blob/51f3ba4343f1c127495d36945a0af9e8f8ee4684/src/widget/tool/profileimporter.cpp#L25)):_

> ``` cpp
> #include <QMessageBox>
> #include <QApplication>
> #include <QPushButton>
> ```

Mind about alphabetical order? I know it's Latin and not Cyrillic alphabet, but it probably helps to keep conflicts at a minimum with our "ui feature branch". I'd love to learn that some day - maybe you can teach… :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3668)_

**Comment by antis81** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/tool/profileimporter.cpp, line 33 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3668#-KQUPgv1XIT3ZmYgUnte:-KQUPgv2ffCG4zGc2FKS:b-7mo7f4) ([raw file](https://github.com/qtox/qtox/blob/51f3ba4343f1c127495d36945a0af9e8f8ee4684/src/widget/tool/profileimporter.cpp#L33)):_

> ``` cpp
>  * @class ProfileImporter
>  * @brief This class provides the ability to import profile.
>  *
> ```

Remove empty line.

---

_[src/widget/tool/profileimporter.cpp, line 36 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3668#-KQUOaI6CL77jVX_yRHT:-KQUOaI7sL36iUYPhEWo:bagvwn5) ([raw file](https://github.com/qtox/qtox/blob/51f3ba4343f1c127495d36945a0af9e8f8ee4684/src/widget/tool/profileimporter.cpp#L36)):_

> ``` cpp
>  * @note This class can be used before @a Nexus instance will be created.
>  * Therefore it can't use @a GUI class
>  */
> ```

Doxygen usually adds a documentation to the following function (which is the c'tor in this case). I'm not sure about this one, because we explicitly gave the `@class` context. Just to be safe, I tend to also add a block above c'tor (or first function/method in general) to avoid confusion.

The @note block reads:
"An instance of this class has to be created before the @a Nexus instance."

From this it is clear, that it cannot be used in any code **after** Nexus singleton instance was once created. And it raises the question: "Why is that? Does it kill any cats?" -- Could you add that please? :)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3668)_

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/tool/profileimporter.cpp, line 25 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3668#-KQUNoeCKuElX2lBeXSd:-KQUkvXw5P41XfF2g_0v:b-el33dl) ([raw file](https://github.com/qtox/qtox/blob/51f3ba4343f1c127495d36945a0af9e8f8ee4684/src/widget/tool/profileimporter.cpp#L25)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Mind about alphabetical order? I know it's Latin and not Cyrillic alphabet, but it probably helps to keep conflicts at a minimum with our "ui feature branch". I'd love to learn that some day - maybe you can teach… :)
> </details>
> Done. ;)

---

_[src/widget/tool/profileimporter.cpp, line 33 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3668#-KQUPgv1XIT3ZmYgUnte:-KQUl4IW4Mnl9MOH_Dsp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/51f3ba4343f1c127495d36945a0af9e8f8ee4684/src/widget/tool/profileimporter.cpp#L33)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Remove empty line.
> </details>
> Done.

---

_[src/widget/tool/profileimporter.cpp, line 36 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3668#-KQUOaI6CL77jVX_yRHT:-KQUl4hVq4aiM6JxH4bh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/51f3ba4343f1c127495d36945a0af9e8f8ee4684/src/widget/tool/profileimporter.cpp#L36)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Doxygen usually adds a documentation to the following function (which is the c'tor in this case). I'm not sure about this one, because we explicitly gave the `@class` context. Just to be safe, I tend to also add a block above c'tor (or first function/method in general) to avoid confusion.
> 
> The @note block reads:
> "An instance of this class has to be created before the @a Nexus instance."
> 
> From this it is clear, that it cannot be used in any code **after** Nexus singleton instance was once created. And it raises the question: "Why is that? Does it kill any cats?" -- Could you add that please? :)
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3668)_

**Comment by antis81** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3668)_

**Comment by antis81** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3668#-:-KQUzXvbeYVMp48nTC23:bnfp4nl)_

**Pull request merged**
