### PR TITLE
chore: Fix OSX build

### PR DESCRIPTION
**Pull request by iphydf**
Also fix a typo in the verify-commit-messages.sh script.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3)

### CODE REVIEW

**Comment by zetok** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis/travis.sh, line 19 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3#-KO1VWr8GsIPL5FgsudE:-KO1VWr8GsIPL5FgsudF:-2049679147) ([raw file](https://github.com/qtox/qtox/blob/ca8bdad14302a88bc83068514e64aca55f0561be/.travis/travis.sh#L19)):*
> ```Shell
>     bash ./osx/qTox-Mac-Deployer-ULTIMATE.sh -b
>     bash ./osx/qTox-Mac-Deployer-ULTIMATE.sh -d
> #    bash ./osx/qTox-Mac-Deployer-ULTIMATE.sh -dmg
> ```

Perhaps a comment could be added that it was commented out since travis failed due to `hdiutil: create failed - Resource busy` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3)*

**Comment by iphydf** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis/travis.sh, line 19 \[r1\]](https://reviewable.io:443/reviews/qtox/qtox/3#-KO1VWr8GsIPL5FgsudE:-KO1bBlGfII6GDHCSs9k:-499146009) ([raw file](https://github.com/qtox/qtox/blob/ca8bdad14302a88bc83068514e64aca55f0561be/.travis/travis.sh#L19)):*
<details><summary><i>Previously, zetok wrote…</i></summary>
> Perhaps a comment could be added that it was commented out since travis failed due to `hdiutil: create failed - Resource busy` ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3)*

**Comment by zetok** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3)*

**Comment by zetok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3#-:-KO1c3WielODqRZpJDYR:1417088721)*

**Comment by iphydf** [comment]
@tux3 will you have time to review?

**Comment by iphydf** [comment]
Apparently not.

**Pull request merged**
