### PR TITLE
fix: Now cannot send party invite to a friend which has "Offline" status

### LINKED ISSUE #4018: Can't invite friend to a conference
##### Brief Description
Inviting friend to a conference doesn't work if they have been invited to it already when they were offline.

OS: Gentoo Linux amd64
qTox version: v1.7.0-5-gb4c4569
Commit hash: b4c4569299d734d8056e48a6d6dd62f4df2ae86f
toxcore: 0.1.2
Qt: 5.6.2

Reproducible: Always

##### Steps to reproduce

1. Create a conference by inviting an offline friend to it
2. Once friend comes online drag & drop them to the created conference

##### Observed Behavior
Friend doesn't receive the invitation.
There are messages in stdout about critical problems.

##### Expected Behavior
Friend should receive an invitation when they're dragged & dropped on to the conference.
There should be no misleading errors in stdout.

##### Additional Info
stdout errors:
```
[11:30:05.184 UTC] core/core.cpp:1271 : Critical: Conference invite failed to send
[11:30:06.235 UTC] core/core.cpp:705 : Critical: Fail of tox_conference_set_title
[11:30:06.235 UTC] core/core.cpp:709 : Critical: Conference not found

[11:30:12.241 UTC] core/core.cpp:1268 : Critical: Conference not found
[11:30:17.908 UTC] core/core.cpp:1268 : Critical: Conference not found
```

### PR DESCRIPTION
**Pull request by noavarice**
Fix #4018

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4115)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4115#-:-KbvqLJ4o-aDeTCk5Ugh:b-jbsf8z)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[src/widget/groupwidget.cpp, line 261 at r1](https://reviewable.io:443/reviews/qtox/qtox/4115#-Kc4F4HT1XNwdeGYsQTA:-Kc4F4HT1XNwdeGYsQTB:bkdi2al) ([raw file](https://github.com/qtox/qtox/blob/3e715a257ba8bf32a5c4f66b008fd8ba01f1946b/src/widget/groupwidget.cpp#L261)):*
> ```cpp
> 
>     int friendId = frnd->getFriendId();
>     if(frnd->getStatus() != Status::Offline) {
> ```

please add a space between `(` according to our coding style.  You can use the qtcreator configuration file in https://github.com/qTox/qTox/tree/master/tools/configs to let qtcreator do this for you.

---

*[src/widget/form/groupchatform.cpp, line 301 at r1](https://reviewable.io:443/reviews/qtox/qtox/4115#-Kc4Fa-iQdVoGE7WAQwc:-Kc4Fa-jrIGEfqEZ1mTt:bb7od0r) ([raw file](https://github.com/qtox/qtox/blob/3e715a257ba8bf32a5c4f66b008fd8ba01f1946b/src/widget/form/groupchatform.cpp#L301)):*
> ```cpp
>     int friendId = frnd->getFriendId();
>     int groupId = group->getGroupId();
>     if(frnd->getStatus() != Status::Offline) {
> ```

same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4115)*

**Comment by noavarice** [comment]
*[src/widget/groupwidget.cpp, line 261 at r1](https://reviewable.io:443/reviews/qtox/qtox/4115#-Kc4F4HT1XNwdeGYsQTA:-Kc4qNHXrA_2ToLJ9EVq:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3e715a257ba8bf32a5c4f66b008fd8ba01f1946b/src/widget/groupwidget.cpp#L261)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

please add a space between `(` according to our coding style.  You can use the qtcreator configuration file in https://github.com/qTox/qTox/tree/master/tools/configs to let qtcreator do this for you.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4115)*

**Comment by noavarice** [comment]
*[src/widget/form/groupchatform.cpp, line 301 at r1](https://reviewable.io:443/reviews/qtox/qtox/4115#-Kc4Fa-iQdVoGE7WAQwc:-Kc4qxRI79u2TGSY8toD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3e715a257ba8bf32a5c4f66b008fd8ba01f1946b/src/widget/form/groupchatform.cpp#L301)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4115)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4115#-:-Kc56Kd1I19bs-7Cpo6p:b-jbsf8z)*

**Pull request merged**
