### PR TITLE
chore(cmake): Lookup toxcore's static dependencies

### LINKED ISSUE #4935: Nightly version are outdated
##### Brief Description

OS: Window 32/68
qTox version: nightly
Commit hash:  n/a
toxcore:  n/a
Qt:  n/a
Hardware:  n/a

Reproducible: Always

##### Steps to reproduce
1. goto https://github.com/qTox/qTox
2. download windows nightly build
3. open archive

##### Observed Behavior
files modification date == 2017-12-28 21:33

##### Expected Behavior
today - files modification date < 1 week

##### Additional Info
On the https://tox.chat/download.html page nightly links following to 404 error

### PR DESCRIPTION
**Pull request by nurupo**
Toxcore has changed the way it generates pkg-config `.pc` files. [It now uses `.private` fields](https://github.com/TokTok/c-toxcore/pull/667), which define things for static-linking only (they appear when you pass an additional `--static` flag to `pkg-config`). This is the proper use of `.private` variables, the way toxcore has previously generated `.pc` files wasn't very proper. For qTox this change means that qTox needs to use [the static versions of variables](https://cmake.org/cmake/help/v3.10/module/FindPkgConfig.html) to get those `.private` fields defined in toxcore's `.pc` file.

This fixes #4935, the qTox nightly build on Jenkins (qTox master building against toxcore master).

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4944)

### CODE REVIEW

**Comment by Diadlo** [comment]
So toxcore doesn't support dynamic linkage anymore?

**Comment by nurupo** [comment]
It does. Why are you asking?

**Comment by nurupo** [comment]
Should I wrap the static toxcore lookups in `if(WIN32)`, since we want to link statically to toxcore only on Windows?

**Comment by Diadlo** [comment]
@nurupo Oh.. sorry, forget, that this problem only on windows

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/Dependencies.cmake, line 117 at r1](https://reviewable.io:443/reviews/qtox/qtox/4944#-L4Kq6UNYGa7s0UmyPpw:-L4Kq6UNYGa7s0UmyPpx:b-ce1uxk) ([raw file](https://github.com/qtox/qtox/blob/3f0372b2c50162e5f0580b49ace77e87a7bfa108/cmake/Dependencies.cmake#L117)):*
> ```CMake
> # Try to find cmake toxcore libraries
> if(WIN32)
>   search_dependency(TOXCORE             PACKAGE toxcore          OPTIONAL STATIC_PACKAGE)
> ```

Out of the scope of PR, but does someone know, why toxcore is optional?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4944#-:-L4KqNMyy5ScFWwUQhol:b-jbsf8z)*

**Comment by nurupo** [comment]
qTox master can't link statically to toxcore 2.0.0 on any platform, not just Windows. This change makes it able to link statically on Windows.

**Comment by nurupo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[cmake/Dependencies.cmake, line 117 at r1](https://reviewable.io:443/reviews/qtox/qtox/4944#-L4Kq6UNYGa7s0UmyPpw:-L4Kr0PNBnW8sy307_ea:bx9ohqm) ([raw file](https://github.com/qtox/qtox/blob/3f0372b2c50162e5f0580b49ace77e87a7bfa108/cmake/Dependencies.cmake#L117)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Out of the scope of PR, but does someone know, why toxcore is optional?
</blockquote></details>

Because there is another `search_dependency()` for toxcore below, which is not optional. This one is for cmake buildd of toxcore, the one below is for autotools build of toxcore.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4944)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4944#-:-L4SEnpE_lGdJHeV30O0:b-jbsf8z)*

**Pull request merged**
