### PR TITLE
Adds button to enable camera preview when user order it

### PR DESCRIPTION
**Pull request by agilob**
adds a button in av settings tab which blocks automatic start
of camera preview in the tab. The camera/desktop preview will be
loaded after user explicitly ordered it.

Hopefully this will help with debugging freezing qtox. at least we will
know if camera or audio is broken.

snapshot2

Won't close, but will help with #2438 debugging.

### CODE REVIEW

**Comment by ovalseven8** [comment]
Please change 'Enable camera' to 'Preview'.
Because some people could think they first have to click 'Enable camera' to do a video call, what's wrong.

**Comment by ProMcTagonist** [comment]
The whole thing is a button? Can you toggle it back off?

**Comment by agilob** [comment]
How about,'start video preview'?

you can by changing tab. give it a try

**Comment by ghost** [comment]
Will this new behaviour be removed at some point?

**Comment by agilob** [comment]
I don't see a reason why it should be removed. I was supposed to be implemented since beginning.

**Comment by BiTOk** [comment]
@agilob Can we open camera in separate thread without this button? This can resolve problem with qTox freezing.

**Comment by agilob** [comment]
We can, but it's not the problem. The issue is not to start a camera when user wants to change audio settings or video settings.

**Comment by ovalseven8** [comment]
Of course, qTox should solve the problem with freezing but additionally I like @agilob's solution.

**Comment by agilob** [comment]
Feel free to merge ;)

**Comment by tux3** [comment]
If this is just to help debugging, then it shouldn't go into master. Unless people actually want to have to click that button.

**Comment by zetok** [comment]
> If this is just to help debugging, then it shouldn't go into master. Unless people actually want to have to click that button.

It's not really, at least IMHO. Letting qTox use webcam causes **huge** cpu usage, and I don't see why e.g. laptop users would want that to happen when they have limited battery time, and when they just go to the settings power consumption dramatically jumps up.

I mean, yes, this is a ~workaround, but if something can't really be ~fixed, then workaround is still better than nothing - at least in this particular case.

**Comment by ghost** [comment]
What about enabling the button if started as `qtox --debug`? And throwing into that option any future debugging tweak.

**Comment by koobs** [comment]
I agree with others, the preview functionality just shouldn't block on the main thread (See: #2058). 

Once the preview is enabled, does the state persist (preview remains enabled) between program launches and tab switches, or does it have to be turned on _every time_ ?

If the latter and not the former, I'm heavily -1 on this as a solution in production releases. 

Preview functionality (by default) is great, its the blocking that needs solving.

**Comment by agilob** [comment]
This is a new functionality, not only for debugging purpose, I don't want my camera to start when I want to change audio device.

**Comment by rugk** [comment]
I think this is unnecessary. When you click on "audio/video" it's quite clear that you expect something with audio/video to happen. A preview screen is nothing surprising.
And laptop user really won't always look at the tab "audio/video" the whole time just to drain their battery. :grin:

> and when they just go to the settings power consumption dramatically jumps up.

and half their battery is drain immediately... :wink: 
No, a few seconds access to the webcam won't be such bad. If laptop users would really be cared about this they would just quickly switch away and next time they'll remember what's there.
Additionally this settings tab is not something whcih is accessed regularly. And if it is accessed it is very likely the user wants to change something regarding audio or video settings and at least the latter one already makes clear that the user already is in a video conversion.

So I'm in favour of this:

> What about enabling the button if started as qtox --debug? And throwing into that option any future debugging tweak.

Alternatively you should not merge it into master - maybe a development branch would fit.

**Comment by TheNain38** [comment]
I'm with @rugk's opinion on this. The user expect that something with audio/video will happen if they go on this tab.

**Comment by ovalseven8** [comment]
> I don't want my camera to start when I want to change audio device.

Agree. What's wrong with that PR?

**Comment by agilob** [comment]
Someone doesn't like it...

**Comment by rugk** [comment]
> I don't want my camera to start when I want to change audio device.

Just: Why?

**Comment by agilob** [comment]
> Why 
> 
> > I want to change audio device.

Why would I want to change oil every time I tank up a car?

**Comment by rugk** [comment]
> Why would I want to change oil every time I tank up a car?

You do not change the oil. You just have a look on it.
Because when changing oil you have to do something, for looking at your camera picture you do not.

Additionally when driving to the gas station the chances are also high that you want to change your oil - and you do not have to press a button before you get to the oil can.

So expect of "What you want" (UX) arguments - are there any technical arguments for such an additional button?

**Comment by TheNain38** [comment]
e.g skype does have a separate audio and a separate video tab, but you do not have to press a button to see the video

**Comment by ghost** [comment]
I also think it's inconvenient to add steps to such trivial tasks. It makes the software feel less "friendly" for the non geeks. Takes away the _great-it-just-works_ factor.

If knowing _if camera or audio is broken_ is the main goal, then the logs should be more verbose or, as TheNain38 says, there should be separate audio/video tabs (which is worse than having to activate the camera, IMO).

**Comment by TheNain38** [comment]
@kehugter In fact, I don't like to have separate tabs, I would prefer it to stay the same as it is right now

**Comment by ProMcTagonist** [comment]
What if: If the user enables the camera by clicking the button, then leaves the settings/tab, then comes back within one minute, they shouldn't have to click to turn it on again?

**Pull request closed without merging**
