### PR TITLE
fix videosurface (missing buffer flip) and some glitches in av settings

### PR DESCRIPTION
**Pull request by derMart**
Hello,

this PR addresses three issues:
1. Opengl buffers are not flipped during paintGL. At least on Windows this prevents video from working. Enabling setAutoBufferSwap solves the problem.
2. Audio devices using special characters are not displayed correctly and cannot be opened.
According: http://openal.org/pipermail/openal/2014-August/000202.html at least on Windows the strings are UTF8 rather than any local encoding. I'm not sure about other platforms, so I just applied the change on windows.
3. Video is not correctly initialized in the av settings form (resolution not set). Furthermore the 0x0 resolution is removed and audio initialization code tries to avoid opening audio devices twice.

cheers
Martin

### CODE REVIEW

**Comment by dubslow** [comment]
Excellent stuff, neat and tidy separate commits to boot :)

**Comment by derMart** [comment]
thank you very much :)

**Comment by derMart** [comment]
Video in settings screen hangs after waking from tray icon. Seems the showEvent in AFForm was missing -> I was so free to add a commit therefore too ;)

**Comment by dubslow** [comment]
@suhr At least the sound works now. I'll close the old related issues, and you can make a new one regarding the clipped name.

**Pull request merged**
