### PR TITLE
custom compile qTox for Testing

### PR DESCRIPTION
**Pull request by zoff99**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4920)

### CODE REVIEW

**Comment by zoff99** [comment]
@sudden6 can you review this one, if you have some time please?

**Comment by zoff99** [comment]
@sudden6 @Diadlo this is been sitting around for a long time. do you have time to review please? it would help to have this in the repo

**Comment by Diadlo** [comment]
Your PR is failing because of the Commit Guidlines https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by zoff99** [comment]
Dialo can you help me? "Allow edits from maintainers." is on

**Comment by sudden6** [comment]
@zoff99 use `git commit --amend` to fix the title of the commits

**Comment by zoff99** [comment]
see #5066

**Pull request closed without merging**
