### PR TITLE
chore(legal): update copyright date to 2018 for all source files

### PR DESCRIPTION
**Pull request by anthonybilinski**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5079)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
github does not like regenerating diffs when the target branch has updated o.o

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 132 of 132 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5079#-:-LA7gNI6DtaNwXaKj4sv:b-jbsf8z)*

**Comment by tox-user** [comment]
:lgtm_strong:

---

Reviewed 132 of 132 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5079#-:-LACo-fv-OZUOe1JfgqQ:b-jbsf8z)*

**Comment by anthonybilinski** [comment]
updated to add end date to copyright notices, instead of just updating currently present end dates.
i.e. instead of just 2015-2016 -> 2015-2018, also 2015 -> 2015-2018.

**Pull request merged**
