### PR TITLE
Style

### PR DESCRIPTION
**Pull request by krepa098**
- background of MaskablePixmapWidget now depends on the average color of the pixmap (the goal is not to please everyone's flavor!)
- issue #334 a)
- extended Style to allow symbols like @mediumGrey -> #c1c1c1
- removed some cases where QPalette was used for styling (styling should only be done in .css files, some platform-styles don't even use palettes)
- some changes to the chatlog
- updated .css files (more to go)

Hopefully this doesn't cause any regressions :smile:

### CODE REVIEW

**Comment by tux3** [comment]
> Hopefully this doesn't cause any regressions :smile:

pic32
Speak of the devil ... now the background color is broke!

Edit: Also the average color doesn't seem to make a lot of sense, Impyy doesn't have a single blue pixel in his avatar, and he gets a blue background. Maybe the median color would make more sense ? 
(or just transparency, really ..)

**Comment by krepa098** [comment]
Hmm... did you do a clean rebuild?
snapshot13

**Comment by tux3** [comment]
Well, I'll try again.

**Comment by tux3** [comment]
I'm still having the light grey background after a make clean && qmake && make

pic33

I can git bisect it if you want, since you don't seem to be affected.

**Comment by tux3** [comment]
I bisected it back to 214e428b7ea8efb6e40b3df5c6ed7fbb924bd611

**Comment by krepa098** [comment]
Does activating/hovering change the color? I just tried a fresh git clone & make from my repo and it worked just fine.

Could be due to the removal of setAutoFillBackground(true); in widget/groupwidget.cpp:34 although it shouldn't be needed using css.

**Comment by tux3** [comment]
If I hover or click in/out the background doesn't change at all.

**Comment by tux3** [comment]
Nope setAutoFillBackground doesn't help.

I'm trying to fix it on my end, by nothing seems to work. It's like the CSS background-color just doesn't apply to the parent's bg for some reason.

**Comment by tux3** [comment]
Wait, something's weird. It looks like my local copy of the PR doesn't have the same style.cpp as your branch.
EDIT: Nope, still doesn't work.

**Comment by tux3** [comment]
It looks like background-color just doesn't work.

With the changes I made it should be completely red, but the background stays undefined no matter what.
pic34

**Comment by krepa098** [comment]
Seems like Oxygen (the widget style) is the problem :anguished: I'm using Qt Cruve. Well at least I can reproduce it now...

**Comment by tux3** [comment]
Maybe there's a workaround, surely we're not the first project using a background color on KDE/Oxygen ?

**Comment by krepa098** [comment]
It's fixed now, I think.

**Comment by tux3** [comment]
Compiling right now.
Edit: Alright, it works for me, thanks !

**Comment by dubslow** [comment]
This causes the ChatArea to not have bold nicknames, instead they look the same as text. Previously the other nick was bold black, my nick bold gray, and chat nonbold. Now all three are nonbold.

**Pull request merged**
