### PR TITLE
fix(video): allow not integer framerates

### LINKED ISSUE #4866: Webcam OSX Sierra
OS X Sierra 10.12.65
qTox version: v1.13.0
Commit hash:  a66af1b128f7293bc08718ce2cc064f
toxcore:  0.1.0
Qt:  5.9.3

Hi, im using qTox v1.13.0 on OSX Sierra and the Webcam in qTox is not detect as you can see in the screenshot below.

33979210-3c79ae7c-e09b-11e7-98e2-7db73e4093ed

### PR DESCRIPTION
**Pull request by sudden6**
Fix #4866 and #4764

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4871)

### CODE REVIEW

**Comment by Diadlo** [comment]
Good guess :lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4871#-:-L0un-nzOiNSSxo3WEhB:bjc4dij)*

**Comment by sudden6** [comment]
@Diadlo plese do the review again, I found some other bugs and stuff

**Comment by Diadlo** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/widget/form/settings/avform.cpp, line 328 at r2](https://reviewable.io:443/reviews/qtox/qtox/4871#-L0zqp_1hqqsn5Uu4EC9:-L0zqp_1hqqsn5Uu4ECA:bgqib8p) ([raw file](https://github.com/qtox/qtox/blob/b4b975cd75abf725b3f4502ace5e361682603efe/src/widget/form/settings/avform.cpp#L328)):*
> ```cpp
>         VideoMode mode = videoModes[i];
>         if (mode.width == prefRes.width() && mode.height == prefRes.height()
>             && static_cast<quint16>(mode.FPS) == prefFPS)
> ```

Maybe better compare floats without truncating?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4871)*

**Comment by sudden6** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/widget/form/settings/avform.cpp, line 328 at r2](https://reviewable.io:443/reviews/qtox/qtox/4871#-L0zqp_1hqqsn5Uu4EC9:-L0zwWqRPQ_YU_t6o2iz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/b4b975cd75abf725b3f4502ace5e361682603efe/src/widget/form/settings/avform.cpp#L328)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Maybe better compare floats without truncating?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4871)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4871#-:-L0zyqoxWlRUD226Ce3Y:b-jbsf8z)*

**Pull request merged**
