### PR TITLE
Message formatting refactoring & bad url highlighting fix

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4236)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 154 at r1](https://reviewable.io:443/reviews/qtox/qtox/4236#-KeUkbh0hrM3FckbZVdn:-KeUkbh1RJHm3mMkexgp:buvge8v) ([raw file](https://github.com/qtox/qtox/blob/0de2817e6aec68b7188ccc7b4821354efaa9492c/src/chatlog/textformatter.cpp#L154)):*
> ```cpp
>  * @param showFormattingSymbols True, if it is supposed to include formatting symbols into resulting
>  * string
>  * @return Source text with styled font
> ```

update function documentation, there is no return value anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by noavarice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 154 at r1](https://reviewable.io:443/reviews/qtox/qtox/4236#-KeUkbh0hrM3FckbZVdn:-KeUqAIFsuuXvuqeOXTx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/0de2817e6aec68b7188ccc7b4821354efaa9492c/src/chatlog/textformatter.cpp#L154)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

update function documentation, there is no return value anymore
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by sudden6** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 134 at r2](https://reviewable.io:443/reviews/qtox/qtox/4236#-Ke_-sXyIzvylAUqnilw:-Ke_-sXyIzvylAUqnilx:bcnsrfc) ([raw file](https://github.com/qtox/qtox/blob/d94ba6e5ba548ffe1796d757205c04bccc4d23b5/src/chatlog/textformatter.cpp#L134)):*
> ```cpp
>  * @brief Applies a function for URL's which can be extracted from passed string
>  * @param str String in which we are looking for URL's
>  * @param func Function which is applying to URL
> ```

`applied to the URL`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by noavarice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 134 at r2](https://reviewable.io:443/reviews/qtox/qtox/4236#-Ke_-sXyIzvylAUqnilw:-Ke_8IFnURyGpuXwniFl:b-dm1etk) ([raw file](https://github.com/qtox/qtox/blob/d94ba6e5ba548ffe1796d757205c04bccc4d23b5/src/chatlog/textformatter.cpp#L134)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`applied to the URL`?
</blockquote></details>

Maybe :) Are you sure? Because I'm not)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by sudden6** [comment]
*[src/chatlog/textformatter.cpp, line 134 at r2](https://reviewable.io:443/reviews/qtox/qtox/4236#-Ke_-sXyIzvylAUqnilw:-Ke_jozNhSuYdaGSvpMa:b-u6w8ji) ([raw file](https://github.com/qtox/qtox/blob/d94ba6e5ba548ffe1796d757205c04bccc4d23b5/src/chatlog/textformatter.cpp#L134)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Maybe :) Are you sure? Because I'm not)
</blockquote></details>

I'm pretty sure, but no native speaker either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by noavarice** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/chatlog/textformatter.cpp, line 134 at r2](https://reviewable.io:443/reviews/qtox/qtox/4236#-Ke_-sXyIzvylAUqnilw:-KeclAjODEhE0if2j9iC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d94ba6e5ba548ffe1796d757205c04bccc4d23b5/src/chatlog/textformatter.cpp#L134)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I'm pretty sure, but no native speaker either.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4236#-:-KecoNwjgUSC5kMEFlrV:b-jbsf8z)*

**Pull request merged**
