### PR TITLE
Implemented search of contacts

### PR DESCRIPTION
**Pull request by kushagrasurana**
All friends/groups not matching the criteria set by search text and combo box are made hidden.
search1
search2

### CODE REVIEW

**Comment by zetok** [comment]
lines

↑ I've launched qTox, "searched" for `bot`, and left it overnight → I guess contacts' state changed `online` → `offline` → `online`, or something like that

**Comment by ProMcTagonist** [comment]
Thanks for this!

There should be a clear field button so people can return to their contacts easily.

**Comment by agilob** [comment]
http://doc.qt.digia.com/qtquick-components-symbian-1.1/qml-textfield.html#textfield-with-clear-button

**Comment by kushagrasurana** [comment]
@zetok you are right. The status changes causes this bug.
@ProMcTagonist nice idea
A simple method is [this](http://doc.qt.io/qt-5/qlineedit.html#clearButtonEnabled-prop) . But its ugly
So either i will extend lineEdit class or use the css method
But i am having end semester exams which will end on 2nd of May. So it will tough for me to work on it.

**Comment by SkyzohKey** [comment]
@kushagrasurana ClearButtons are nice! :)
Awesome job for searchbox ^^

**Comment by agilob** [comment]
@kushagrasurana in ui/friendlist/frienlist.css QVBoxLayout doesn't have any style, hidden widget have reserved spacing - 6 (in qtcreator->mainwindow->designer) so it shows background of qboxlayout. remove spacing, set stretch to 0 and set background transparent, should work.

**Comment by tux3** [comment]
Rebased on master and merged in 19bf083b41c455c5d369fd8183b2546a3d21ca6c

**Pull request closed without merging**
