### PR TITLE
Update de.ts

### PR DESCRIPTION
**Pull request by ghost**
Translation revised.
Some lines inserted, which were not in the online file, but in the cloned one.

### CODE REVIEW

**Comment by zetok** [comment]
How does this relate to #917, which in comparison has rather a lot of changes?

**Comment by ghost** [comment]
Am 22.12.2014 um 12:01 schrieb zetok:

> How does this relate to #917 https://github.com/tux3/qTox/pull/917,
> which in comparison has rather a lot of changes?

May be.
As I see they are rather old and not integrated.
I looked in them roughly and mean that you can forgot them and they are
missing the two sections, which are in the cloned file but not online .

I made the changes online in the browser.

## 

PGP-Schlüssel:
0xD2A804E4

**Comment by zetok** [comment]
If you make changes through browser, you most likely don't have newest `de.ts` to translate, but an outdated and incomplete one…
Currently translating qTox requires from the one translating to update `*.ts` file before starting to translate it using `lupdate` tool. If you haven't used it, you've translated/corrected outdated file, which may contain things that are no longer needed, or not contain what is needed.

**Comment by ghost** [comment]
Am 22.12.2014 um 15:08 schrieb zetok:

> If you make changes through browser, you most likely don't have newest
> |de.ts| to translate, but an outdated and incomplete one…
> Currently translating qTox requires from the one translating to update
> |*.ts| file before starting to translate it using |lupdate| tool. If you
> haven't used it, you've translated/corrected outdated file, which may
> contain things that are no longer needed, or not contain what is needed.

That means, doing a new translation after using the update tool?
And if necessary how to delete the made pull request through browser?

Is this proceeding right:
- translate with QtLinguist after lupdate
- save the file and open it with gedit
- copy the content and paste it (overwrite) into my fork
- switch to preview and commit it
- and finally the pull request

Thanks

## 

PGP-Schlüssel:
0xD2A804E4

**Comment by zetok** [comment]
I personally think that doing it with git rather than interface github provides would be less problematic, but the way you've described should work too..

in case where you could use `git`:

``` bash
git clone https://github.com/Toxicop/qTox.git    # fresh clone, less problematic than going through resetting
cd qTox
git checkout -b translation   # creates translation branch and switches you to it
lupdate -no-obsolete -pro qtox.pro -ts translations/de.ts   # update de.ts
## after ↑ translate, when done ↓ ##
git commit -am "Update Deutsch translation"   # creates a commit with a commit message in ""
git push origin translation    # pushes to origin (your github repo) branch translation
```

After that you'd have to go to github and click `Create pull request`.

Then this PR can be then closed. Since you seem to be a bit struggling with PRs, it will be simpler to just create new PR rather than going through something that isn't just basics to make changes properly in this PR.

Feel free to ask questions, and if you'll encounter something that's hard to get through, you can always go on #tox channel on freenode IRC network :)

**Pull request closed without merging**
