### PR TITLE
change picture

### PR DESCRIPTION
**Pull request by ProMcTagonist**
#3020

### CODE REVIEW

**Comment by zetok** [comment]
There's no `Unread messages` that screen in #3020 had, and no groupchat shown.

Additionally, with recent merge that changed how groupchat invites are treated, groupchat invite also got "notification".

I think that it would be good to add both to screenshot?

And remove that `null` from my nick, since usually users won't get to ever see that? I.e. even when talking with me..
no null

Edit: and when file transfer widget will be fixed, screenshot will have to be fixed again, but that'll happen some time later.

**Comment by ProMcTagonist** [comment]
gimme screenshots of both  in your same-sized qtox window and I'll gimp them in

**Comment by zetok** [comment]
> gimme screenshots of both in your same-sized qtox window and I'll gimp them in

Er, I don't have the same size of the window anymore.. and AFAIK it can done without that by just copypasting (at least in krita).

**Comment by ProMcTagonist** [comment]
I just prefer not having to resize because it's cleaner. But it'll be fine. 

Post some screenshots of the features you want featured. I can't compile latest qTox at the moment.

**Comment by zetok** [comment]
> I just prefer not having to resize because it's cleaner.

No idea about that, when I was doing stuff in krita copypasting was identical to the pixel.

Anyway;

groupchat invite
and the rest of "features" (groupchat, 2 types of a new message notification (etc?)) are in https://gist.github.com/zetok/6af729e201a1fae5145a

**Comment by ProMcTagonist** [comment]
qtox zetok mockup

**Comment by ProMcTagonist** [comment]
qtox zetok mockup

**Pull request merged**
