### PR TITLE
Refactor/remove filteraudio

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5912)

### CODE REVIEW

**Comment by sudden6** [comment]
The audio filtering/echo compensation didn't ever work reliably, so just remove it.

**Comment by anthonybilinski** [comment]
I've never noticed it doing anything when I quickly tried it in the past, but I'll try putting it through a more rigorous test to make sure it's really not effective. If it even has a moderate benefit in some use cases, there might be users benefiting from it. Assigning to myself to do that testing.

**Comment by anthonybilinski** [comment]
Trying to test the filtering, compiling with libfilteraudio and enabling "experimental audio backend" then restarting qTox, my audio is completely mute. Calls, rings, and the test sound from clicking the volume bar are all silent. Is our implementation just too broken to use the library?

**Comment by sudden6** [comment]
Rings and the test sound don't go through ´libfilteraudio`, could be something else that's broken?

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5912)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5912#-M30j9FR9ukjIN8i4H5W:-M30j9FR9ukjIN8i4H5X:bcub6d1) (no related file):*
I tried testing again, but again on my Ubuntu 19.10 desktop the entire application is entirely mute when I enable filter audio and restart qTox. I tried on my ARM chromebook running arch linux, which has newer version of all libs and is all around as different as machines get from my desktop, but it had the same thing, where all of qTox is mute after restarting with experimental backend checked.

I verified both had filter audio installed and cmake found it, verified capture and output devices selected were correct, and restarting qTox after unchecking experimental backend made each have normal sound again.

Can you use this feature? If not there must be a bug in qTox stopping it from working at all, and I can really validate how well it works if we aren't using it.

---

**Review by anthonybilinski — APPROVED** [review]
I rebased the change forward which removed 3 of the 4 commits (appimage update bridge, debian sqlcipher) which were already present upstream. I also changed the base branch to `v1.17-dev`.

> Reviewed 9 of 14 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5912#-:-M330J6O6EvpT_NT7Uvf:bgerghn)* status: 0 of 1 LGTMs obtained (waiting on @anthonybilinski)

*[a discussion](https://reviewable.io/reviews/qtox/qtox/5912#-M30j9FR9ukjIN8i4H5W:-M30vw1n53azB0Di2atR:b-c8q2k1) (no related file):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I tried testing again, but again on my Ubuntu 19.10 desktop the entire application is entirely mute when I enable filter audio and restart qTox. I tried on my ARM chromebook running arch linux, which has newer version of all libs and is all around as different as machines get from my desktop, but it had the same thing, where all of qTox is mute after restarting with experimental backend checked.

I verified both had filter audio installed and cmake found it, verified capture and output devices selected were correct, and restarting qTox after unchecking experimental backend made each have normal sound again.

Can you use this feature? If not there must be a bug in qTox stopping it from working at all, and I can really validate how well it works if we aren't using it.
</blockquote></details>

Chatted with @sudden6 and he saw the same thing where it caused it to be mute. Regardless my previous experience with it was that qTox crashed on open when experimental was enabled, and more recently it's mute. @sudden6 had it working previously, but found it didn't work well and needed manual tuning to actually get results from, which isn't ideal. That in combination with it being unmaintained and an internal tox project, makes me think we should still remove it. Hopefully it can be replaced with a better implementation for echo cancellation in the future.

---

**Review by anthonybilinski — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5912#-:-M3353J8BkjZZfQMtD-Z:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by anthonybilinski** [comment]
Github status checks is stuck waiting on travis, even though travis completed. Details link is totally missing. I'll try closing and re-opening the PR to see if that kicks off the check or changing base branch, or pushing a dummy commit, or whatever it takes o.o

**Pull request merged**
