### PR TITLE
docs(MAINTAINING): add info about pull request "expiration date"

### PR DESCRIPTION
**Pull request by zetok**
Also removed obsolete info regarding PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4091)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:
cc @sudden6

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[MAINTAINING.md, line 76 at r1](https://reviewable.io:443/reviews/qtox/qtox/4091#-KbHAqejhDOxZlkLdADb:-KbHAqejhDOxZlkLdADc:b-12l4u4) ([raw file](https://github.com/qtox/qtox/blob/a5d2c573ddca775567024ee9e64fe735146b1807/MAINTAINING.md#L76)):*
> ```Markdown
>     feel free to merge right away.
> - if you're about to merge PR, assign yourself to it.
> - if you decide that PR actually isn't to be (yet) merged, de-assign yourself.
> ```

Why this removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4091#-:-KbHAt9wyypHBXvOm5oe:brc5z7y)*

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[MAINTAINING.md, line 76 at r1](https://reviewable.io:443/reviews/qtox/qtox/4091#-KbHAqejhDOxZlkLdADb:-KbHBWbIQSVYupVRDwYn:b-i1sajh) ([raw file](https://github.com/qtox/qtox/blob/a5d2c573ddca775567024ee9e64fe735146b1807/MAINTAINING.md#L76)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why this removed?
</blockquote></details>

It adds unnecessary complexity, and it slightly conflicts with reviewable workflow, in which assigned people are required to LGTM PR to pass review.

Aside from that, no one was doing that anyway; having dead guideline points doesn't help.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4091)*

**Comment by sudden6** [comment]
*[MAINTAINING.md, line 80 at r1](https://reviewable.io:443/reviews/qtox/qtox/4091#-KbHUt-Aj-GJt3slr1GE:-KbHUt-B-Yne6GBoJvz9:bhv86ha) ([raw file](https://github.com/qtox/qtox/blob/74dc3fc57bd3e3d2c3d813e900f63dbcf49625f2/MAINTAINING.md#L80)):*
> ```Markdown
> - if PR doesn't apply properly on top of current master (when using
>   [`merge-pr.sh`] script), request a rebase and tag PR with `PR-needs-rebase`.
> - if PR requires changes but there has been no activity from PR submitter for
> ```

just language improvements: "if a PR requires", "from the PR submitter"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4091)*

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[MAINTAINING.md, line 80 at r1](https://reviewable.io:443/reviews/qtox/qtox/4091#-KbHUt-Aj-GJt3slr1GE:-KbHXLodphJNE54nEw-n:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/74dc3fc57bd3e3d2c3d813e900f63dbcf49625f2/MAINTAINING.md#L80)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

just language improvements: "if a PR requires", "from the PR submitter"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4091)*

**Comment by sudden6** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4091#-:-KbHamnlM6wEVI8d6Rhq:b-uwkowd)*

**Pull request merged**
