### PR TITLE
fix: use currentDateTime for get num messages for friend (fix #5714)

### LINKED ISSUE #5714: history doesn't load
##### Brief Description

OS: Arch Linux
qTox version: v1.16.3-476-g033f28e6
Commit hash: 033f28e67ecd61cd0fdb6cc0e8de8a2bc920e1d7
toxcore: 0.2.9
Qt: 5.12.4

Reproducible: Always

##### Steps to reproduce

1. start the program
2. go to friend chat and see empty chat without history

### PR DESCRIPTION
**Pull request by TriKriSta**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5715)

### CODE REVIEW

**Review by Diadlo — APPROVED** [review]

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5715)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/history.cpp, line 526 at r1](https://reviewable.io/reviews/qtox/qtox/5715#-LiEHZ612Gk0yToVshvO:-LiEHZ612Gk0yToVshvP:bgya8to) ([raw file](https://github.com/qtox/qtox/blob/1c42efeebbe377792e0b857048241366bef7ae3a/src/persistence/history.cpp#L526)):*
> ```cpp
> size_t History::getNumMessagesForFriend(const ToxPk& friendPk)
> {
>     return getNumMessagesForFriendBeforeDate(friendPk, QDateTime::currentDateTime());
> ```

I think this is incorrect. If the timezone changes we may miss some messages. I think what I want to do here is use QDateTime() and then in getNumMessagesForFriendBeforeDate only add the timestamp restriction when !date.isNull()

**Comment by TriKriSta** [comment]
for example, I can create a function getFinishDateChatHistory which will take the date of the last message. And this date use for load history

**Comment by sphaerophoria** [comment]
keep in mind database access can have significant user noticable latency. If youre going to make a new call I'd prefer one that just does what we want, but I think its fairly easy to allow invalid dates. I dont mind doing the change if you dont want to btw. I introduced the bug 🤷

**Comment by sphaerophoria** [comment]
Just for completeness the root cause of the bug is that QDateTime has undefined behavior if the stored time goes out of range. I couldn't find docs on what the valid range is, just that it can change based on timezone and timespec


From the Qt docs

The range of valid values able to be stored in QDateTime is dependent on the internal storage implementation. QDateTime is currently stored in a qint64 as a serial msecs value encoding the date and time. This restricts the date range to about +/- 292 million years, compared to the QDate range of +/- 2 billion years. Care must be taken when creating a QDateTime with extreme values that you do not overflow the storage. The exact range of supported values varies depending on the Qt::TimeSpec and time zone.

**Comment by TriKriSta** [comment]
And if use it QDateTime::currentDateTime().addDays(1) ?

**Comment by sphaerophoria** [comment]
What happens if someone changes their system time? I think it's fundamentally incorrect to include the timestamp filter when we don't want a timestamp filter. I think it's better to remove the filter by dynamically adding it based on a valid QDateTime.

**Comment by TriKriSta** [comment]
> I think this is incorrect. If the timezone changes we may miss some messages. I think what I want to do here is use QDateTime() and then in getNumMessagesForFriendBeforeDate only add the timestamp restriction when !date.isNull()

Did you mean, If getNumMessagesForFriendBeforeDate gets QDateTime.isNull this function will return all num messages?

**Comment by TriKriSta** [comment]
this decision breaks search, but search breaks anyway. So search can fix on another pull request

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5715#-:-LiF5YGzEYlZ6zpHk8p2:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
