### PR TITLE
fix(ui):Revised the context menu enabled/disabled behaviors

### PR DESCRIPTION
**Pull request by jakieoymj-github**
Re-PR:Fixed the issue #5223 and formatted a few codes.
#### BEFORE:
image
#### AFTER:
image
#### BEFORE:
image
#### AFTER:
image

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5253)

### CODE REVIEW

**Comment by sudden6** [comment]
lgtm from my side, @tox-user can you maybe take a look at the CSS changes? If you're ok with them, just merge it.

**Comment by tox-user** [comment]
Unfortunately I don't have time to read all of the changes currently. I can take a look in a few days.

**Comment by jakieoymj-github** [comment]
Not big changed,most is formatted the codes.

**Comment by jakieoymj-github** [comment]
The reason is seted some .QWidget , QTabBar attributes in
ui/settings/mainContent.css

**Review by tox-user — APPROVED** [review]
Looks good

**Comment by tox-user** [comment]
I can't use Reviewable because of some error: "Unable to create review: There's already a review for this pull request in another instance of Reviewable: https://reviewable.io/reviews/qtox/qtox/5253".

**Comment by sudden6** [comment]
I can not use reviewable too, @jakieoymj-github could you move this to a new PR so we can merge it? Somehow we broke reviewable^^

**Comment by jakieoymj-github** [comment]
Okay,I'll do it later.Thanks for your reviewing.

**Pull request closed without merging**
