### PR TITLE
docs(INSTALL): Combine toxcore and qtox dependencies together

### PR DESCRIPTION
**Pull request by Mestake**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

This changes work for 18.04 too.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5186)

### CODE REVIEW

**Comment by sudden6** [comment]
Thanks for your PR, but as far as I can tell that are the same dependencies as for 16.04?

It might however make sense to combine the dependencies for qTox and toxcore into one listing like you did. What do you think about this?

**Comment by Mestake** [comment]
@sudden6 Yeah, it seems I just didn't look at the `toxcore` section. 

But I think this dependencies should be merged anyway because even with `--without-tox` flag passed to `bootstrap.sh` cmake is still trying to find these libs:

> CMake Error at cmake/Dependencies.cmake:74 (message):
  LIBSODIUM package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:110 (search_dependency)
  CMakeLists.txt:89 (include)

> CMake Error at cmake/Dependencies.cmake:74 (message):
  VPX package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:113 (search_dependency)
  CMakeLists.txt:89 (include)

Also it's trying to find TOXCORE package and it's not aware about `--without-tox` flag too.

> CMake Error at cmake/Dependencies.cmake:74 (message):
  TOXCORE package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:129 (search_dependency)
  CMakeLists.txt:89 (include)

So as far as I get it this flag has not much sense (on Ubuntu at least).

I see two ways:

1. Combine this lists as I did in the PR (for all the Ubuntu sections).
2. Explicitly note that on Ubuntu it must be build with `toxcore` (place a bold warning at the beginning of the Ubuntu section) and maybe place `Toxcore dependencies` section above Ubuntu sections.

What do you think?

**Comment by sudden6** [comment]
> But I think this dependencies should be merged anyway because even with --without-tox flag passed to bootstrap.sh cmake is still trying to find these libs:

This is probably a slight misunderstanding. qTox can not work without toxcore, the flag is just there for the case where it's already installed in the system via a repository or manually.

> Combine this lists as I did in the PR (for all the Ubuntu sections)

I think this is the way to go, maybe also for the other distributions if you have enough time.

**Comment by Mestake** [comment]
> qTox can not work without toxcore, the flag is just there for the case where it's already installed in the system via a repository or manually.

Yes, I understand. Well, Ubuntu has no package containing `libtoxcore.a` or `libtoxcore.so` so manual installation is the only case.

> I think this is the way to go, maybe also for the other distributions if you have enough time.

Sure, I think i should rename this PR and amend the commit. Should I also delete `Toxcore dependencies` section?

**Comment by sudden6** [comment]
Btw, there's also `simple_make.sh`, which should work for a lot of distros to build.

> Should I also delete Toxcore dependencies section?

Yes, it's not needed if it has no content.

**Comment by Mestake** [comment]
Done.

**Comment by sudden6** [comment]
Review status: 0 of 1 LGTMs obtained

---

*[INSTALL.md, line 298 at r1](https://reviewable.io/reviews/qtox/qtox/5186#-LFn6NSJ06bIHEbz7BnX:-LFn6NSJ06bIHEbz7BnY:b-u16x33) ([raw file](https://github.com/qtox/qtox/blob/b547efa9516fd04dca42c06717ba66ae68ec567d/INSTALL.md#L298)):*
> ```Markdown
>     qttools5-dev \
>     qttools5-dev-tools \
>     yasm \
> ```

This seems to be a stray `\` here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5186)*

**Comment by Mestake** [comment]
Oops, what a shame

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5186#-:-LFnD8i46axAy7oi26hS:b-jbsf8z)*

**Pull request merged**
