### PR TITLE
fix(IPC): don't double lock shared memory

### LINKED ISSUE #4678: IPC logs "Warning: QSharedMemory::lock: already locked" on activate
##### Brief Description

OS: Linux
Commit hash:  b7921ef2

Reproducible: Always

##### Steps to reproduce

1. Open qTox
2. Open a second instance with no command line options

##### Observed Behavior

First instance logs:
```
[22:40:45.251 UTC] :0 : Warning: QSharedMemory::lock: already locked
[22:40:45.251 UTC] ipc.cpp:265 : Debug: Processing event:  "activate" : 1506120045 = false
```

##### Expected Behavior
```
[22:40:45.251 UTC] ipc.cpp:265 : Debug: Processing event:  "activate" : 1506120045 = false
```

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4678

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4679)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
isCurrentOwner locked the global memory mutex, which is required because it's called directly from main, but it's also called from within fetchEvent which is called by processEvents, which locks the mutex. This caused the double lock error log.

I split isCurrentOwner into isCurrentOwner and (private) isCurrentOwnerNoLock, with isCurrentOwner just calling isCurrentOwnerNoLock after locking the global mem mutex, and then used isCurrentOwnerNoLock for internal methods that already lock the global memory mutex.

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4679#-:-KuiWmSNg0UJaf8Fm1Fd:b-jbsf8z)*

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[src/ipc.cpp, line 140 at r1](https://reviewable.io:443/reviews/qtox/qtox/4679#-KujVUj2iNHUBdglo3gs:-KujVUj3-HIZXBHgdE8X:b-cqdnam) ([raw file](https://github.com/qtox/qtox/blob/57a070081f9be8e58ff7b23a01c97a399ce62139/src/ipc.cpp#L140)):*
> ```cpp
> {
>     if (globalMemory.lock()) {
>         bool isOwner = isCurrentOwnerNoLock();
> ```

could be `const bool`

---

*[src/ipc.cpp, line 286 at r1](https://reviewable.io:443/reviews/qtox/qtox/4679#-KujVlCQtF28US_8OJSy:-KujVlCQtF28US_8OJSz:bdw3mj) ([raw file](https://github.com/qtox/qtox/blob/57a070081f9be8e58ff7b23a01c97a399ce62139/src/ipc.cpp#L286)):*
> ```cpp
> bool IPC::isCurrentOwnerNoLock()
> {
>     void* data = globalMemory.data();
> ```

Since there is only a comparison, and pointer itself is not changed, it could be const:
`const void* const data`

---

*[src/ipc.cpp, line 291 at r1](https://reviewable.io:443/reviews/qtox/qtox/4679#-KujVuo9dR-AAHMDVYSx:-KujVuo9dR-AAHMDVYSy:b-dunrbn) ([raw file](https://github.com/qtox/qtox/blob/57a070081f9be8e58ff7b23a01c97a399ce62139/src/ipc.cpp#L291)):*
> ```cpp
>         return false;
>     }
>     return ((*(uint64_t*)data) == globalId);
> ```

Please no C-style casts. 
I believe `static_cast<const uint64_t*>(deta)` should work here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4679)*

**Comment by anthonybilinski** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[src/ipc.cpp, line 140 at r1](https://reviewable.io:443/reviews/qtox/qtox/4679#-KujVUj2iNHUBdglo3gs:-Kuu6OeTNkoi0fR1tC4_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/57a070081f9be8e58ff7b23a01c97a399ce62139/src/ipc.cpp#L140)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

could be `const bool`
</blockquote></details>

Done.

---

*[src/ipc.cpp, line 286 at r1](https://reviewable.io:443/reviews/qtox/qtox/4679#-KujVlCQtF28US_8OJSy:-Kuu6O6eLat-Seq8l_3P:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/57a070081f9be8e58ff7b23a01c97a399ce62139/src/ipc.cpp#L286)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Since there is only a comparison, and pointer itself is not changed, it could be const:
`const void* const data`
</blockquote></details>

Done.

---

*[src/ipc.cpp, line 291 at r1](https://reviewable.io:443/reviews/qtox/qtox/4679#-KujVuo9dR-AAHMDVYSx:-Kuu6NsRR-ZZZREsMeUL:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/57a070081f9be8e58ff7b23a01c97a399ce62139/src/ipc.cpp#L291)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Please no C-style casts. 
I believe `static_cast<const uint64_t*>(deta)` should work here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4679)*

**Comment by sudden6** [comment]
@Talkless lgtm?

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4679#-:-Kv8HkeMlKpMddlPDFlw:b-jbsf8z)*

**Pull request merged**
