### PR TITLE
[WIP] qTox Audio API reimplementation based on RtAudio

### LINKED ISSUE #3625: Audio stream remains open after leaving Audio/Video settings
qTox leaves audio playback stream open after leaving Audio/Video settings

OS: Debian GNU/Linux Sid
qTox version:  v1.4.0-245-g99ce719
Commit hash:  99ce719b800b5fedeb47eb848268976dcbf96fc7
toxcore:  0.0.0
Qt:  5.5.1
…

Reproducible: Always 
##### Steps to reproduce
1. Go to Settings
2. Select Audio/Video settings tab
3. Go back to chat or to another settings tab
##### Observed Behavior

qTox leaves pulseaudio playback stream open forever
##### Expected Behavior

qTox should close playback stream just after leaving Audio/Video settings tab

### PR DESCRIPTION
**Pull request by antis81**
**Important note:** Library bindings are kept in parallel to OpenAL until it can be replaced completely.
- [x] add RtAudio library dependency
- [ ] update build scripts and maintenace
- [ ] update docs
- [ ] **(last step)** remove OpenAL code and dependency
# Concept

The goal of the qTox audio API is to create a flexible management mechanism for the use of audio resources within qTox. Access to audio resources is encapsulated in a special audio context, which defines the audio devices, that should be used to stream and/or monitor audio. Here are some examples for audio contexts:
- qTox call
- qTox group-call
- audio preview (aka monitor)

**qTox code won't be aware of the underlying API in use - namely RtAudio. Direct access to RtAudio from outside the API is strictly forbidden.**
## Namespaces & Classes

Each method, that belongs to the qTox audio API is wrapped by the `qTox::Audio` namespace. Within the namespace, there exist the following classes:
- Obsolete: ~~Devices -> Controls access to audio devices and manages the devices, which are in use.~~
- Device -> Represents an single input or output device, including an `RtAudio::DeviceInfo`, describing the device's capabilities.
- StreamContext -> A streaming context configures the required input and/or output device and parameters.
# TODO: Implementation
- [x] implement a ~~"context"~~ "stream" class, that is used as a binding object for each audio ~~context~~ stream. Streams are e.g. a "qTox call receiver", a "qTox call sender" or the "settings preview"), which connects the required input/output devices.
- [ ] Implement audio resource self-management.
- [ ] settings for volume and gain (gain algorithm can be probably used from OpenAL implementation), if there's no prepared one.
- [ ] Use `Opus` codec for audio filtering, compression and the like.
## Want to help?

This PR will get merged into `master`, if implementation of audio API is complete or at least in a state, that provides feature parity to the current implementation. If you want to help with implementation or have ideas, please contact me and I'll do my best to answer your questions (@antis81 --> Tox-ID: `C52DA9FE98B86AF01178CB605DA2585919B2BA72DF1968B97932DE7155EC354320A65105E357`).
# Solves issues

Closes #3625, #3626

---

This change is [Reviewable](https://reviewable.io/reviews/tux3/qtox/3524)

### CODE REVIEW

**Comment by antis81** [comment]
@sudden6 If you like to help, please setup a PR, that merges into this one (not on master!).

@zetok, @abbat Can you help to set up the build dependencies on Jenkins/Travis? The build scripts should also install the packages (or compile).

For xUbuntu the required package is `librtaudio-dev`.

**Comment by antis81** [comment]
@tux3 FYI -> Started implementation of new RtAudio based API.

**Comment by zetok** [comment]
> Can you help to set up the build dependencies on Jenkins/Travis?

Linux traivs done in #3526, osx one still needs to be done, and depends on #3520.
As for jenkins, @tux3 will take care of settings up stuff there for windows when time comes.

**Comment by antis81** [comment]
@sudden6 @tux3 I had to rewrite most audio stuff I pushed here and need to push a few more times, until there is a stable basis, that is actually usable by qTox and extensible. Assume this will take not too long. So please stay tuned. If this basis is ready, I won't push in the `audio/api` branch and setup PR's on this one to add features (like e.g. volume and gain control). We also should consider implementing some unit tests to actually make the new audio API rock solid right from the start.

Here's in short how it is going to work:
Each qTox `call` or `group-call` and also the `sound notifications` is going to run in a separate context (the `StreamContext`), which is completely "self-managed". Each stream context closes and destroys itself, when it gets "out of scope" -> e.g. a call finishes. This also closes the device, if no other context uses it, this is very resource efficient. Changing the device during a call is also possible, but not implemented yet - requires a reopen.

I will write the description of major changes in the upcoming commit(s), as the code design completely changed compared to yesterday (no more singleton - yay! :smile:).

I also wrote with one of the RtAudio developers and cleared some questions out.

**Comment by towlie** [comment]
@antis81 Does rtaudio manage opened devices? So we don't have this opened closed device thing again? 
It caused cpu usage through audio services.

**Comment by antis81** [comment]
@towlie Yes! :) RtAudio is stream based. Each `StreamContext` opens the in-/output resources as needed. So when the last `StreamContext` is destroyed, the devices' resources are also freed. However I don't know, if that all works as expected yet. Contrary to what my first thought was, the RtAudio class only handles a single stream object, which brought me to current design. I'll need to talk with the developers / and [RTFM](https://www.music.mcgill.ca/~gary/rtaudio/classRtAudio.html) to figure that out completely. :)

However, the `StreamContext` concept is also usable on our OpenAL sources and we can reuse it, if the RtAudio approach does not work for whatever reason… :)

**Comment by Diadlo** [comment]
Is RTAudio compatible with [GPLv3](https://www.gnu.org/licenses/gpl-3.0.html)?

[Wikipedia](https://ru.wikipedia.org/wiki/RTAudio) says: 

> RTAudio is a proprietary CODEC. Like RTVideo, this protocol can also be licensed from Microsoft.

**Comment by zetok** [comment]
@Diadlo RtAudio ≠ RTAudio.

**Comment by alexeysvrv** [comment]
@antis81 Are there any progress with the implementation?

**Comment by antis81** [comment]
> Are there any progress with the implementation?

Don't get confused by the PR's red :x:'es, lying about the actual state. :) The state of this API is actually: It "kinda works", but there's serious issues with it, that need to be solved before we can even think about replacing OpenAL. But…
1. I have local code available, which is able to actually place a successful call to echo bot (Tox-ID: `76518406F6A9F2217E8DC487CC783C25CC16A15EB36FF32E335A235342C48A39`) and can playback our "incoming" sound (2x speed due to mixed mono/stereo channels, but works in general). If you expect understandable language in a call though - well, I have to disappoint you… :stuck_out_tongue:
2. There's some unanswered questions and we need to discuss that with the guys from RtAudio, before we put too much effort in an API, that might not work out well with qTox. This is the main reason I paused this -> will be a time consuming task! If you're interested in solving this, let me know. 

I think it is time to push my code, which completely replaces OpenAL code in any means, but leaves the library dependencies intact, so we can fall-back any time.

@initramfs Could we talk this through maybe on qTox? I'll put my ID in the PR's description for contact. Though I cannot promise to be online regularly. If you feel for urgent discussion, please drop me a mail.

**Comment by initramfs** [comment]
@antis81 Your ToxID is not complete, that's only your public key. :)

And no problem, I'm free to discuss stuff with you.

**Comment by antis81** [comment]
>Sorry, is your tox ID: 

Ooopsi, was ID from a test profile. Nevermind, too. Corrected in description. :)

**Comment by antis81** [comment]
@initramfs @sudden6 FYI -> I started implementation of audio resource "auto-management" and basically have an idea how to do it. As discussed few hours ago, reopening an audio device, which is in use, throws up. RtAudio does a pretty lousy job here by not correctly managing devices, but hey - we're getting more and more to the state of our own powerful API. And don't worry about exceptions: Though we cannot implement "exception safety" due to qTox build rules, they will simply vanish in the end. We don't want or need them actually.

Btw. quality during call is not due to "performance issues" or something, but a single buffer is used. To keep things simple in the beginning, the active stream is being "aborted" and reinitialized, which causes "audio gaps" in the local output stream. I was actually surprised, that I was able to get it quickly into that current quite stable state. :smile:

**Comment by akhilman** [comment]
I hope new stream contexts also will resolve #2459

**Comment by antis81** [comment]
> I hope new stream contexts also will resolve #2459

Actually this is one of our new API's features, yes! While the settings and UI requires a small "upgrade" to reflect the additional output device, the code is already prepared to bind separate in/out devices for the desired context. The current implementation state actually makes it a hard requirement to stream calls and notifications to separate output devices. For this and some other open TODO's, it is still marked WIP. So I wouldn't exactly say it is "ready for qTox" yet :innocent:, but it is quite stable and makes good progress.

**Comment by alexeysvrv** [comment]
@antis81 What news?

**Comment by alexeysvrv** [comment]
@antis81 Any progress?

**Comment by alexeysvrv** [comment]
@antis81

**Comment by zetok** [comment]
PR needs to be rebased, since there are now some conflicts.

**Comment by Diadlo** [comment]
PR didn't have any activity for over 2 months, and no one seems to be interested in working on it, thus closing.

If that's not the case, please either ask to reopen the pull, or make a new one.

**Pull request closed without merging**
