### PR TITLE
fix(core): remove pgc code

### PR DESCRIPTION
**Pull request by sudden6**
This code was needed for the pgc implementation, but is not needed for
minipgc

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5401)

### CODE REVIEW

**Comment by sphaerophoria** [comment]
Mind flushing out the rational here a little? I currently don't have enough context to review because I don't know the difference between pgc and minipgc and why their specs are different. I can't verify that this isn't needed anymore with the amount of information I currently have.

**Comment by sudden6** [comment]
PGC was the first implementation for making persistent group chats in c-toxcore. It never made it into master. minipgc is the second implementation for making persistent group chats, this time it was merged. We had the code for PGC already in qTox because it doesn't interfere with the c-toxcore/master code, but for minipgc the API changed slightly compared to PGC and we need to adapt to this changes.

**Comment by sphaerophoria** [comment]
Alright had an offline discussion with @sudden6 and figured out what's going on here.

A good start point to read on this would be https://github.com/TokTok/c-toxcore/blob/master/docs/minpgc.md

Basically there was an implementation of persistent group chats that never made it into master. As part of this PR (826) this change was made to tox.h

```
 *  if friend_number == UINT32_MAX then conference automatically joined.
 *  On auto-join client must call tox_conference_join or toxav_join_av_groupchat
 *  immediately in callback. For api compatibility reason, if client don't
 *  call one these functions, conference will be deleted and toxcore
 *  totally forget this conference.
 *
```

We preemptively accepted this change into qTox thinking that the PR would get merged. This was not the case. We can back out the change since it's unlikely persistent group chats will ever get merged in that form.

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5401#-:-LPMxOmC3prLilUB6tou:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
