### PR TITLE
feat(settings): Add audio quality setting

### LINKED ISSUE #4693: Feature request: audio quality settings
It would be very useful to be able to change audio quality. I assume that means changing bitrate. It would enable people to use qTox even when they are on a poor internet connection. There should probably be a few predefined values for the user to choose from, for example: high, medium, low, very low. Currently if someone is on a bad internet connection they might not be able to use qTox so they would have to switch to another messaging app that has lower internet usage.

### PR DESCRIPTION
**Pull request by tox-user**
Fixes #4693

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4697)

### CODE REVIEW

**Comment by tox-user** [comment]
screenshot from 2017-09-28 16-38-47

Testing:
1. Start a call with someone.
2. Go to Settings > Audio/Video and change Audio Quality.
3. Restart the call.
4. Your caller will notice the difference in audio quality.

Issues:
Audio Quality combo box doesn't show which value is active. The setting isn't persistent.

It would be great if someone with experience could finish this feature or tell me what to do next.

**Comment by sudden6** [comment]
Great PR, to make the settings persistent you have to hook it up to our [settings infrastructure ](https://github.com/qTox/qTox/blob/master/src/persistence/settings.cpp).

**Comment by Diadlo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/core/coreav.cpp, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8yiuLXCjMahmseamK:-Kv8yiuLXCjMahmseamL:b-d5v7qs) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/core/coreav.cpp#L52)):*
> ```cpp
>  *
>  * @var CoreAV::audioBitrate
>  * @brief In kb/s. More than enough for Opus.
> ```

Brief needs updating. At least, remove "More than enough for Opus"

---

*[src/core/coreav.cpp, line 239 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8yTtKth40oLBr27F7:-Kv8yTtKth40oLBr27F8:b8s2i0r) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/core/coreav.cpp#L239)):*
> ```cpp
>     assert(calls.contains(friendNum));
>     TOXAV_ERR_ANSWER err;
>     if (toxav_answer(toxav, friendNum, audioBitrate, VIDEO_DEFAULT_BITRATE, &err)) {
> ```

Probably, you should move `audioBitrate` in `Settings` and use `Settings::getInstance().getAudioBitrate()` here

---

*[src/widget/form/settings/avform.cpp, line 344 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8xRd2TJp8ujTdxc5d:-Kv8xRd35kWnJwWADOte:bkvc9nr) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/widget/form/settings/avform.cpp#L344)):*
> ```cpp
>     QString name;
>     name = tr("High (64 kbps)");
>     audioQualityComboBox->addItem(name);
> ```

Probably [`addItems`](http://doc.qt.io/qt-4.8/qcombobox.html#addItems) will be better here

---

*[src/widget/form/settings/avform.cpp, line 433 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8xb-_zYNKJ9l6oy4w:-Kv8xb-_zYNKJ9l6oy4x:btrzyur) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/widget/form/settings/avform.cpp#L433)):*
> ```cpp
> {
>     uint32_t bitrate;
>     switch (index) {
> ```

Suggest to use array here
```
int bitrates[] = { 64, 32, 16, 8 };
// If you want, you can add asset here
int bitrate = bitrates[index];
```

---

*[src/widget/form/settings/avform.cpp, line 448 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8yXi7NztoLLOYW6XS:-Kv8yXi7NztoLLOYW6XT:b-pbvjxq) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/widget/form/settings/avform.cpp#L448)):*
> ```cpp
>     }
>    
>     Core::getInstance()->getAv()->audioBitrate = bitrate;
> ```

And here `Settings::getInstance().setAudioBitrate(bitrate)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by tox-user** [comment]
Thank you for help :). The setting is now persistent. Now I only need someone to test it in a conversation, because I couldn't find anyone that I could call at the moment.

**Comment by sudden6** [comment]
@tox-user for testing `echobot@toxme.io` is very handy

**Comment by tox-user** [comment]
Good to know! It looks like everything is working fine.

**Comment by Diadlo** [comment]
Reviewed 3 of 6 files at r2.
Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/widget/form/settings/avform.cpp, line 343 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD0YfJNdtZGka1_nEG:-KvD0YfKwP6fK9DTr6qR:bkk0e3h) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L343)):*
> Low (16 kbps

You forgot the bracket

---

*[src/widget/form/settings/avform.cpp, line 347 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD1i4otlMJQuFOrPM3:-KvD1i4otlMJQuFOrPM4:b8n5v9h) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L347)):*
> ```cpp
>     audioQualityComboBox->addItems(names);
> 
>     int currentBitrate = Settings::getInstance().getAudioBitrate();
> ```

Seems,  `currentBitrate` is not modified here. Use const then

---

*[src/widget/form/settings/avform.cpp, line 351 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD11FJnT5ui4D_TBCA:-KvD11FJnT5ui4D_TBCB:bwg3t4y) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L351)):*
> ```cpp
>     int index = 0;
> 
>     for (int i = 0; i < names.length(); i++) {
> ```

Better use array here.
```
QVector<int> bitrates = { 64, 32, 16, 8 }
index = bitrates.indexOf(currentBitrate)
```

---

*[src/widget/form/settings/avform.cpp, line 440 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD1XkboKFlzrJeIusl:-KvD1XkboKFlzrJeIusm:b-7s4sqq) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L440)):*
> ```cpp
> void AVForm::on_audioQualityComboBox_currentIndexChanged(int index)
> {
>     int bitrates[] = { 64, 32, 16, 8 };
> ```

const

---

*[src/widget/form/settings/avform.cpp, line 441 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD1bZcoGZYFpv7xtBl:-KvD1bZcoGZYFpv7xtBm:b-7s4sqq) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L441)):*
> ```cpp
> {
>     int bitrates[] = { 64, 32, 16, 8 };
>     int bitrate = bitrates[index];
> ```

const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by Talkless** [comment]
Review status: 4 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/persistence/settings.cpp, line 1889 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDlsSfqFQywAhBS_hR:-KvDlsSgGhzqEdQ1VJWB:b2tqnuc) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/persistence/settings.cpp#L1889)):*
> ```cpp
> int Settings::getAudioBitrate() const
> {
>     QMutexLocker locker{&bigLock};
> ```

uber pedantic but that could be **const** QMutextLocker. There are no manual `.unlock()`. Same elsewere.

---

*[src/widget/form/settings/avform.cpp, line 340 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDmNdpJxjFXqFV0Y15:-KvDmNdpJxjFXqFV0Y16:b-ry5h2s) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L340)):*
> ```cpp
> void AVForm::fillAudioQualityComboBox()
> {
>     bool previouslyBlocked = audioQualityComboBox->blockSignals(true);
> ```

const bool

---

*[src/widget/form/settings/avform.cpp, line 342 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDmV1xuWPStgdL_3W6:-KvDmV1xuWPStgdL_3W7:b-q4x4z9) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L342)):*
> ```cpp
>     bool previouslyBlocked = audioQualityComboBox->blockSignals(true);
> 
>     QStringList names;
> ```

`const QStringList names{tr(...) , tr(...), ... };`, if my suggestion below is not applied.

---

*[src/widget/form/settings/avform.cpp, line 351 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD11FJnT5ui4D_TBCA:-KvDpUMIIgBIRbWTlQzB:b-51mpl7) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L351)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Better use array here.
```
QVector<int> bitrates = { 64, 32, 16, 8 }
index = bitrates.indexOf(currentBitrate)
```
</blockquote></details>

Alternatively, there could be something like that (not actually tested pseudocode):
```
// there are only so few items, no need for arrays or loops IMHO
audioQualityComboBox->addItem(tr(..), 64);
audioQualityComboBox->addItem(tr(..), 32);

const int index = audioQualityComboBox.findData(currentBitrate);
audioQualityComboBox->setCurrrentIndex(index);
```

and in other place:
```
Settings::getInstance().setAudioBitrate(audioQualityComboBox->currentData().toInt());
```
so we don't need to duplicate these { 64, 32, .. }, they will be inside combobox itself.

Although maybe I am missing something.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by tox-user** [comment]
@Talkless, my current code does something similar. It extracts the bitrate from combobox. I did it to not have to repeat the same array, but I will do what @Diadlo says if he thinks it's better.

**Comment by Diadlo** [comment]
If `addItem(tr(..), 64);` works, it's much better

**Comment by tox-user** [comment]
I can see now why this is a better solution. It works!

**Comment by Talkless** [comment]
Review status: 2 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/widget/form/settings/avform.cpp, line 340 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDmNdpJxjFXqFV0Y15:-KvI3urKG7z9j64kdGqM:bqhnqg) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L340)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const bool
</blockquote></details>

Why all-caps local variables? It's global constants that are usually all-caps.

Actually, all-caps should be reserverd for macros *only*, but that's offtopic.
[NL.9: Use ALL_CAPS for macro names only](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl9-use-all_caps-for-macro-names-only)
[Enum.5: Don’t use ALL_CAPS for enumerators](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#enum5-dont-use-all_caps-for-enumerators)
[ES.9: Avoid ALL_CAPS names](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es9-avoid-all_caps-names).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by tox-user** [comment]
I thought caps names were always used for constants in most programming languages. Should only global constants names be written in uppercase?

**Comment by Talkless** [comment]
Review status: 2 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/persistence/settings.cpp, line 1889 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDlsSfqFQywAhBS_hR:-KvIOIukfM65HkClTg1x:b-7vswps) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/persistence/settings.cpp#L1889)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

uber pedantic but that could be **const** QMutextLocker. There are no manual `.unlock()`. Same elsewere.
</blockquote></details>

Please click "Done" button in Reviweable for comments that has a fix (such as this).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by tox-user** [comment]
:lgtm_strong:

---

Review status: 2 of 7 files reviewed at latest revision, 13 unresolved discussions.

---

*[src/core/coreav.cpp, line 52 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8yiuLXCjMahmseamK:-KvInDvqLIiR6RcaiEeM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/core/coreav.cpp#L52)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Brief needs updating. At least, remove "More than enough for Opus"
</blockquote></details>

Done.

---

*[src/core/coreav.cpp, line 239 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8yTtKth40oLBr27F7:-KvInRv9NK0zbiEK9KWy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/core/coreav.cpp#L239)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Probably, you should move `audioBitrate` in `Settings` and use `Settings::getInstance().getAudioBitrate()` here
</blockquote></details>

Done.

---

*[src/persistence/settings.cpp, line 1889 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDlsSfqFQywAhBS_hR:-KvInBheflqkYxzWHqZu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/persistence/settings.cpp#L1889)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Please click "Done" button in Reviweable for comments that has a fix (such as this).
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 344 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8xRd2TJp8ujTdxc5d:-KvIn2nLWotRjKYLdOcf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/widget/form/settings/avform.cpp#L344)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Probably [`addItems`](http://doc.qt.io/qt-4.8/qcombobox.html#addItems) will be better here
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 433 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8xb-_zYNKJ9l6oy4w:-KvInUVmwv0RpxXsBfcW:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/widget/form/settings/avform.cpp#L433)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Suggest to use array here
```
int bitrates[] = { 64, 32, 16, 8 };
// If you want, you can add asset here
int bitrate = bitrates[index];
```
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 448 at r1](https://reviewable.io:443/reviews/qtox/qtox/4697#-Kv8yXi7NztoLLOYW6XS:-KvIRnmvBIvc5Z-XfRhN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/61eddc1f6b76f2da1a6d180426a2b7f53c757e2a/src/widget/form/settings/avform.cpp#L448)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

And here `Settings::getInstance().setAudioBitrate(bitrate)`
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 340 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDmNdpJxjFXqFV0Y15:-KvIn9_i961t04Y-hJTx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L340)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Why all-caps local variables? It's global constants that are usually all-caps.

Actually, all-caps should be reserverd for macros *only*, but that's offtopic.
[NL.9: Use ALL_CAPS for macro names only](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#nl9-use-all_caps-for-macro-names-only)
[Enum.5: Don’t use ALL_CAPS for enumerators](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#enum5-dont-use-all_caps-for-enumerators)
[ES.9: Avoid ALL_CAPS names](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es9-avoid-all_caps-names).
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 342 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvDmV1xuWPStgdL_3W6:-KvIn7_aXATHpfKqCahk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L342)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

`const QStringList names{tr(...) , tr(...), ... };`, if my suggestion below is not applied.
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 343 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD0YfJNdtZGka1_nEG:-KvIn82H9uZFTSj-K6Qa:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L343)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

> Low (16 kbps

You forgot the bracket
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 347 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD1i4otlMJQuFOrPM3:-KvIn4YqjCytx_LL35hO:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L347)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Seems,  `currentBitrate` is not modified here. Use const then
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 351 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD11FJnT5ui4D_TBCA:-KvIRuSUY2_JIYsCaJVv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L351)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Alternatively, there could be something like that (not actually tested pseudocode):
```
// there are only so few items, no need for arrays or loops IMHO
audioQualityComboBox->addItem(tr(..), 64);
audioQualityComboBox->addItem(tr(..), 32);

const int index = audioQualityComboBox.findData(currentBitrate);
audioQualityComboBox->setCurrrentIndex(index);
```

and in other place:
```
Settings::getInstance().setAudioBitrate(audioQualityComboBox->currentData().toInt());
```
so we don't need to duplicate these { 64, 32, .. }, they will be inside combobox itself.

Although maybe I am missing something.
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 440 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD1XkboKFlzrJeIusl:-KvIRplUh80vMgK0A5Ei:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L440)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.

---

*[src/widget/form/settings/avform.cpp, line 441 at r2](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvD1bZcoGZYFpv7xtBl:-KvIRoTfUCKUKIFxGDV8:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7ed2d97aadab8aa0acb39e54aafaea06c0ebe57c/src/widget/form/settings/avform.cpp#L441)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697#-:-KvInGTLO_ULn5WT-P0I:b-jbsf8z)*

**Comment by Talkless** [comment]
Review status: 2 of 7 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[src/widget/form/settings/avform.ui, line 127 at r5](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvSmtt-LbTiMjtJo21a:-KvSmtt0D40vBeJcqx6o:b-5zo4au) ([raw file](https://github.com/qtox/qtox/blob/78c6869e4c11c24fc3f9c61e194839479729b7bc/src/widget/form/settings/avform.ui#L127)):*
Second sentence could be simplified to, though feel free to ignore.
> Lower settings reduces network bandwidth usage.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by tox-user** [comment]
Review status: 2 of 7 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[src/widget/form/settings/avform.ui, line 127 at r5](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvSmtt-LbTiMjtJo21a:-KvWXU_PI09d48sOkU2c:b-woa8rt) ([raw file](https://github.com/qtox/qtox/blob/78c6869e4c11c24fc3f9c61e194839479729b7bc/src/widget/form/settings/avform.ui#L127)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Second sentence could be simplified to, though feel free to ignore.
> Lower settings reduces network bandwidth usage.
</blockquote></details>

It's a good idea but I feel like it might not be a good enough explanation for an average user.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by sudden6** [comment]
Reviewed 2 of 6 files at r2, 1 of 2 files at r3.
Review status: 4 of 7 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

*[src/widget/form/settings/avform.ui, line 127 at r5](https://reviewable.io:443/reviews/qtox/qtox/4697#-KvSmtt-LbTiMjtJo21a:-KvX3sDJi9XCHuSy34Mq:bkx9by4) ([raw file](https://github.com/qtox/qtox/blob/78c6869e4c11c24fc3f9c61e194839479729b7bc/src/widget/form/settings/avform.ui#L127)):*
<details><summary><i>Previously, tox-user wrote…</i></summary><blockquote>

It's a good idea but I feel like it might not be a good enough explanation for an average user.
</blockquote></details>

I agree, the longer one seems better to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Reviewed 1 of 5 files at r1, 4 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697#-:-KvcFwgFf5hS2QCANPXw:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 5 files at r1, 2 of 6 files at r2, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697#-:-KvnTrPLXZT8aQsalHL8:b-jbsf8z)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 3 of 6 files at r2, 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4697#-:-Kvnd3rqZC-PTRyaMyoH:b-jbsf8z)*

**Comment by Diadlo** [comment]
@tox-user Good job

**Pull request merged**
