### PR TITLE
Select password field when it is wrong, Fixes #2584 using sudden6's idea

### LINKED ISSUE #2584: When entering a wrong password, the password field doesn't get emptied

### PR DESCRIPTION
**Pull request by TheNain38**
Fixes #2584 using @sudden6's idea

### CODE REVIEW

**Comment by ghost** [comment]
Works as expected, thanks!

**Comment by zetok** [comment]
So, under i3 it works only when I use keyboard to load profile (enter) - if I use mouse, it doesn't work. I guess that's a thing specific to tiling window manager(s?). In any case, it seems like an upstream problem - is anyone else who doesn't use tiling wm able to reproduce that?

Edit: if it's not reproducible outside of tiling wm, IMHO it should be merged.

**Comment by ghost** [comment]
As you said, is not reproducible. I tested keyboard and mouse in Plasma and Cinnamon.

**Comment by zetok** [comment]
I see, thanks for testing :)

**Pull request merged**
