### PR TITLE
feat(smileys): add emojione emoji-pack and make it the default

### LINKED ISSUE #3315: [change icon suggestion] Turn :) from the red cheeks into a :grinning: closed mouth smile
Let's face it, the current : ) or : - ) smiley icon in qTox looks almost embarrassed with those red cheeks and closed eyes. 

Even the ^ _ ^ icon has that 'joyful in frosty weather' type look with all that red.

I'd prefer to see the : ) smiley be made into a "more standard" looking smileyface _without_ the red cheeks. Something like the :grinning: icon for example, but with a closed mouth smile. 

Thank you.

+1 if you concur. :beer:

### PR DESCRIPTION
**Pull request by sudden6**
Thanks to @ProMcTagonist who suggested to use emojis from emojione.com

Fixes #3315

### CODE REVIEW

**Comment by zetok** [comment]
- [x] not available not available

**Comment by sudden6** [comment]
@zetok should be fixed

**Comment by zetok** [comment]
- [x] `®` and `©` don't work, even though they're "shown" in the list – i.e. instead of signs, there are 2 empty places in the list
  muh ©®

**Comment by sudden6** [comment]
Also fixed, please note, that not every emoji in the pack is currently available in the emoji picker, because I didn't yet find a way to convert an emoji.json file to an emoticon.xml file.

**Comment by zetok** [comment]
```
zetok@galaxor ~/git_zetok/tox/qTox/smileys $ ls Universe/ | wc -l
877
zetok@galaxor ~/git_zetok/tox/qTox/smileys $ ls emojione/ | wc -l
1836
```

IMO it would be good to add all of them.

**Comment by sudden6** [comment]
I don't know if it would be a good idea, because our emoji picker isn't exactly useful when choosing between that many emoji and these are probably the most used ones.

**Comment by zetok** [comment]
> I don't know if it would be a good idea, because our emoji picker isn't exactly useful when choosing between that many emoji.

Yep, it needs to be fixed :)
Issue:  #992
Proposal: #1294

**Comment by sudden6** [comment]
So, display all when the new picker is done?

**Comment by zetok** [comment]
I'd prefer to display all, and if that breaks current emoticon picker, fix the picker.

**Comment by sudden6** [comment]
I'd prefer to use the current state of this PR, then fix the emoji picker (won't probably happen very soon), then upgrade to the full set.

**Comment by zetok** [comment]
About using current set – I've been wondering whether including that in qTox repo is really the best choice.

I.e. given that emojine is being actively developed, and what's more, it's using git, I was wondering whether using it as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) wouldn't be better.

**Comment by sudden6** [comment]
I also thought about this, but I don't know if this is a good idea here. I'm not sure if our user will appreciate if the emojis change between releases.

Also there's the problem of generating an appropriate emoticons.xml but I think we could change the qTox code to  support the emoji.json format.

**Pull request merged**
