### PR TITLE
Close camera after call

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5121)

### CODE REVIEW

**Comment by tox-user** [comment]
The camera also activates when we are video calling someone, before they even pick up.

**Comment by sudden6** [comment]
@tox-user that's probably a different issue.

**Comment by Diadlo** [comment]
I see only one functional change: `unsubscribe()` call was removed. Why it will close camera after call?

**Comment by sudden6** [comment]
before it was unsubscribed twice, which is wrong. For me it fixed the webcam staying on after a call.

**Comment by Diadlo** [comment]
Ok. Seems understand

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5121#-:-LCVNKqm7qnyfyHx3Vww:b-jbsf8z)*

**Pull request merged**
