### PR TITLE
fix(appimage): Use external binary path when enabling autorun from appimage

### LINKED ISSUE #6241: Appimage does not start at user logon
##### Brief Description

OS: Ubuntu 20.04
qTox version: v1.17.2 
Commit hash:  465d82606813439ee14425f7462903bb39f2da30
toxcore: 0.2.11
Qt:  5.7.1

Reproducible: Always

##### Steps to reproduce

1.  Run Appimage
2. Set Autostart
3. Logout and log back in

##### Observed Behavior

qTox does not start
##### Expected Behavior

qTox started automatically

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #6241

- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6382)

### CODE REVIEW

**Review by sphaerophoria — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6382#-:-MkKlAhj8wkdoDhbwouH:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/platform/autorun_xdg.cpp, line 53 at r1](https://reviewable.io/reviews/qtox/qtox/6382#-MkKkRK-Bl2_pjdYqg9t:-MkKkRK-Bl2_pjdYqg9u:b5bapq) ([raw file](https://github.com/qtox/qtox/blob/acc87fc8882db075d37e60b8fc41109be94df510/src/platform/autorun_xdg.cpp#L53)):*
> ```cpp
> }
> 
> inline QString currentCommandLine()
> ```

nit: I'd argue that this is generally named incorrectly. If I launch qtox without the `-p` argument is this _really_ the current command line? I think this is _a_ comamndline that will launch qtox into the same state, but I don't think it's correct.

Feel free to ignore and merge anyways, it's not _more_ wrong now
___
*[src/platform/autorun_xdg.cpp, line 55 at r1](https://reviewable.io/reviews/qtox/qtox/6382#-MkKkhGsAjVBW_YGvj7T:-MkKkhGsAjVBW_YGvj7U:b-to1x0x) ([raw file](https://github.com/qtox/qtox/blob/acc87fc8882db075d37e60b8fc41109be94df510/src/platform/autorun_xdg.cpp#L55)):*
> ```cpp
> inline QString currentCommandLine()
> {
>     return "\"" + currentBinPath() + "\" -p \""
> ```

Not blocking review on this... but isn't this wrong when you have multiple profiles? 

Profile A: Sets auto run, writes a qtox commandline to to the autorun dir
Profile B: Checks autorun by seeing if the file exists, yup! it does!

Potential fix. Desktop files should be named as qtox-<profile>.desktop and multiple can be launched on startup

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6382)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/platform/autorun_xdg.cpp, line 55 at r1](https://reviewable.io/reviews/qtox/qtox/6382#-MkKkhGsAjVBW_YGvj7T:-MkKohbz8zNLG78uW_xf:b-s3moxx) ([raw file](https://github.com/qtox/qtox/blob/acc87fc8882db075d37e60b8fc41109be94df510/src/platform/autorun_xdg.cpp#L55)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

Not blocking review on this... but isn't this wrong when you have multiple profiles? 

Profile A: Sets auto run, writes a qtox commandline to to the autorun dir
Profile B: Checks autorun by seeing if the file exists, yup! it does!

Potential fix. Desktop files should be named as qtox-<profile>.desktop and multiple can be launched on startup
</blockquote></details>

reviewable ate some letters I think. qtox-profile.desktop

**Review by anthonybilinski — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6382)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/platform/autorun_xdg.cpp, line 53 at r1](https://reviewable.io/reviews/qtox/qtox/6382#-MkKkRK-Bl2_pjdYqg9t:-MkKtH-lBBUJZlNvaAlA:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/acc87fc8882db075d37e60b8fc41109be94df510/src/platform/autorun_xdg.cpp#L53)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

nit: I'd argue that this is generally named incorrectly. If I launch qtox without the `-p` argument is this _really_ the current command line? I think this is _a_ comamndline that will launch qtox into the same state, but I don't think it's correct.

Feel free to ignore and merge anyways, it's not _more_ wrong now
</blockquote></details>

Done.
___
*[src/platform/autorun_xdg.cpp, line 55 at r1](https://reviewable.io/reviews/qtox/qtox/6382#-MkKkhGsAjVBW_YGvj7T:-MkKrvLfBQNnn-QcxlDG:b-tm6v7c) ([raw file](https://github.com/qtox/qtox/blob/acc87fc8882db075d37e60b8fc41109be94df510/src/platform/autorun_xdg.cpp#L55)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

reviewable ate some letters I think. qtox-profile.desktop
</blockquote></details>

The autostart file path already includes the profile name, see `getAutostartFilePath()`

**Review by sphaerophoria — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6382)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/platform/autorun_xdg.cpp, line 55 at r1](https://reviewable.io/reviews/qtox/qtox/6382#-MkKkhGsAjVBW_YGvj7T:-MkKutxa2sjmWjS_RtQl:b-l59z9i) ([raw file](https://github.com/qtox/qtox/blob/acc87fc8882db075d37e60b8fc41109be94df510/src/platform/autorun_xdg.cpp#L55)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

The autostart file path already includes the profile name, see `getAutostartFilePath()`
</blockquote></details>

I don't know how I managed to miss that. I looked _explicitly_ for that and just didn't see it.

**Pull request merged**
