### PR TITLE
issue 960

### PR DESCRIPTION
**Pull request by kushagrasurana**
Video setting sliders works on mouse scroll.

### CODE REVIEW

**Comment by Brottweiler** [comment]
I'd imagine this would be intended.

**Comment by kushagrasurana** [comment]
The slider works now on mouse scroll, after my fix.

**Comment by Brottweiler** [comment]
They currently work for me with mouse scroll without your fix.

**Comment by zetok** [comment]
@Brottweiler so you don't experience any symptoms of #960 ?

EDIT: I for one experience those issues…

**Comment by zetok** [comment]
And this fix works for me.

**Comment by Brottweiler** [comment]
@zetok Oh, maybe it's a different issue. I can manipulate the slider using my mouse wheel, but I don't know what happens when i save the settings.

**Comment by dubslow** [comment]
@krepa098 

If I don't see any response to this by the time I get proper access to my own computers again (i.e. not just ssh, probably no more than two weeks ish?), I'll see about testing and merging this and 920 @lumirayz

**Comment by krepa098** [comment]
Seems to work fine.
@kushagrasurana please remove the _sliderMoved slots as they are now redundant.

**Comment by agilob** [comment]
+1, I have the same problem as described by @kushagrasurana 
scrolling on sliders doesn't change camera settings until clicked on sliders.

**Comment by dubslow** [comment]
@krepa098 @kushagrasurana This is probably something really stupid, but how does this actually help? As far as I can tell, the new slots aren't connected to any signals (just like the old, non-functioning slots)...?

**Comment by krepa098** [comment]
They are connected (http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html#automatic-connections). And the old slots had been connected too.

Anyway, changing theses properties produces garbage results on Windows and I think we should disable them (on Windows, they work fine on linux and OSX(?)).

**Comment by tux3** [comment]
Rebased and merged in 64bd3b7b47661bbdbbacca11a3aa190f72e41954

**Pull request closed without merging**
