### PR TITLE
Add deb package building

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4983)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 2 of 4 files at r1.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 134 at r1](https://reviewable.io:443/reviews/qtox/qtox/4983#-L6fNg1wJpHTUmJ3TmUU:-L6fNg1xS-MVrtOQJuPv:bj8xsex) ([raw file](https://github.com/qtox/qtox/blob/85cf0b11fba39520a0f90233a6b3389257d67efc/.travis.yml#L134)):*
> ```YAML
>       tags: true
>     skip_cleanup: true
>   - protider: releases
> ```

typo `provider`?

---

*[cmake/Packing.cmake, line 3 at r1](https://reviewable.io:443/reviews/qtox/qtox/4983#-L6fO1zCEdrK9KIAIaHz:-L6fO1zDD_g_CC6wF0RD:b-vmr5aq) ([raw file](https://github.com/qtox/qtox/blob/85cf0b11fba39520a0f90233a6b3389257d67efc/cmake/Packing.cmake#L3)):*
> ```CMake
> execute_process(COMMAND
>             git describe
> 		WORKING_DIRECTORY
> ```

mixed tabs and spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4983)*

**Comment by Diadlo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 134 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4983#-L6fNg1wJpHTUmJ3TmUU:-L6x8jya3Si9grC7P7r5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/85cf0b11fba39520a0f90233a6b3389257d67efc/.travis.yml#L134)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

typo `provider`?
</blockquote></details>

Done.

---

*[cmake/Packing.cmake, line 3 at r1](https://beta.reviewable.io/reviews/qtox/qtox/4983#-L6fO1zCEdrK9KIAIaHz:-L6x8lX_1Me-0b-AEQMe:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/85cf0b11fba39520a0f90233a6b3389257d67efc/cmake/Packing.cmake#L3)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

mixed tabs and spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/4983)*

**Comment by Diadlo** [comment]
Will try to merge before release?

**Comment by sudden6** [comment]
Since this can't really break our existing release channels, I think it's safe.

EDIT: Does it already work?

**Comment by Diadlo** [comment]
@sudden6 ~Since uploading package works only on release, I don't know, but I can upload one package in build time to test. Let's try~
No, it doesn't work

**Comment by Diadlo** [comment]
Seems ready. Can someone with debian/ubuntu try this repo?
https://bintray.com/qtox/qTox/
Package: qtox-nightly

**Comment by sudden6** [comment]
Installation works on Ubuntu 17.10, but running fails:
screenshot_20180318_152115

EDIT: I think the package doesn't specify the needed dependencies correctly or it's only working on Debian. I also think the package could be missing c-toxcore.

**Comment by sudden6** [comment]
I found Travis CI supports bintray deployment, https://docs.travis-ci.com/user/deployment/bintray/

**Comment by Diadlo** [comment]
@sudden6 Thanks for the link, not sure, that it's possible to use it here, because filename contains version. Depends list updated

**Comment by anthonybilinski** [comment]
Tested on Ubuntu 16.04:
during install, it failed when there was already "qtox" present from a different package. It should maybe remove other qtox packages if installed:
```
abilinski@:/tmp$ sudo dpkg -i qtox-nightly-1.14.0.351-Linux.deb 
(Reading database ... 340362 files and directories currently installed.)
Preparing to unpack qtox-nightly-1.14.0.351-Linux.deb ...
Unpacking qtox-nightly (1.14.0.351) ...
dpkg: error processing archive qtox-nightly-1.14.0.351-Linux.deb (--install):
 trying to overwrite '/usr/bin/qtox', which is also in package qtox 201708291918~v1.6.0
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Errors were encountered while processing:
 qtox-nightly-1.14.0.351-Linux.deb
```
when running, I got a crash, missing dependencies:
```
abilinski@:/tmp$ sudo dpkg -i qtox-nightly-1.14.0.351-Linux.deb 
abilinski@:/tmp$ /usr/bin/qtox
/usr/bin/qtox: error while loading shared libraries: libavcodec.so.56: cannot open shared object file: No such file or directory
```

**Comment by alexeysvrv** [comment]
Any progress? I want to install deb. package on my Ubunru 14.04)))

**Comment by Diadlo** [comment]
New version: https://dl.bintray.com/qtox/qTox/_build/qtox-nightly-1.14.0.355-Linux.deb
@alexeysvrv can you try?

**Comment by alexeysvrv** [comment]
@Diadlo ERROR insoluble dependence libavdevice-ffmpeg56(>=7:2.4)

**Comment by Diadlo** [comment]
@alexeysvrv Another try
https://dl.bintray.com/qtox/qTox/_build/qtox-nightly-1.14.0.356-Linux.deb

**Comment by piddubnyi** [comment]
@Diadlo I tried latest link, still does not work:
igor@pc:~/Downloads$ sudo dpkg -i qtox-nightly-1.14.0.356-Linux.deb 
[sudo] password for igor: 
dpkg: error processing archive qtox-nightly-1.14.0.356-Linux.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 6 package 'qtox-nightly':
 'Depends' field, missing package name, or garbage where package name expected
Errors were encountered while processing:
 qtox-nightly-1.14.0.356-Linux.deb

I'd like to install via deb package also.

**Comment by sudden6** [comment]
@Diadlo now that we have an AppImage and a Flatpak build do you want to continue with this?

**Comment by Diadlo** [comment]
@sudden6 I think that most of the users prefer to use a native package manager. So I think we should finish it. But currently I have not enough time

**Comment by sudden6** [comment]
Ok :+1:

**Comment by anthonybilinski** [comment]
Given that we have support on most major distros now including Debian and derivatives, and that this is quite stale, I'm going to close.

I still think there would be some value in being able to build our own packages with cpack, so that debug/nightly builds can be managed by the package manager, but it seems quite minor since regular users can just use their distro packages.

**Pull request closed without merging**
