### PR TITLE
[Refactor] ToxmeData

### PR DESCRIPTION
**Pull request by Diadlo**
Based on #4718

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4729)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 4 of 8 files at r1.
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 27 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZheF1Ufd34DzYdht:-KwHZheF1Ufd34DzYdhu:b7zoyif) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L27)):*
> ```cpp
> #include <QString>
> 
> QByteArray ToxmeData::parsePublicKey(const QString& text) const
> ```

function documentation

---

*[src/net/toxmedata.cpp, line 30 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZZoAu6Tlhv75EfzB:-KwHZZoBrOeNIzXRzVQW:by8xm77) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L30)):*
> ```cpp
> {
>     const QJsonObject json = QJsonDocument::fromJson(text.toLatin1()).object();
>     const QString& key = json["key"].toString();
> ```

Do we need to check if the key exists? http://doc.qt.io/qt-5/qjsonobject.html#operator-5b-5d says the `[]` operator may return `QJsonValue::Undefined`

---

*[src/net/toxmedata.cpp, line 60 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZys4NK-o-qJGzocJ:-KwHZys5Av1uxV471KYV:b-gqg704) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L60)):*
> ```cpp
> {
>     const QJsonObject json = QJsonDocument::fromJson(inText.toLatin1()).object();
>     const QString& text = json["tox_id"].toString();
> ```

check if "tox_id" exists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Diadlo** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 27 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZheF1Ufd34DzYdht:-KwHadEaS0N1MZ-b2dKu:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L27)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

function documentation
</blockquote></details>

Done.

---

*[src/net/toxmedata.cpp, line 30 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZZoAu6Tlhv75EfzB:-KwHadfDrVWjXdPQMAOL:bomqgig) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L30)):*
http://doc.qt.io/qt-5/qjsonvalue.html#toString

> If type() is not String, a null QString will be returned.

null QString -> empty QByteArray.

---

*[src/net/toxmedata.cpp, line 60 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZys4NK-o-qJGzocJ:-KwHanVQ7SGXKTXxJgFH:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L60)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

check if "tox_id" exists?
</blockquote></details>

Same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by sudden6** [comment]
I'll review again when the other PR is merged, so I can focus on the important parts here.

**Comment by Diadlo** [comment]
@sudden6 Done :)

**Comment by sudden6** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 30 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZZoAu6Tlhv75EfzB:-KwHkhBchHGf8wdWPWpH:b32w0x) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L30)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

http://doc.qt.io/qt-5/qjsonvalue.html#toString

> If type() is not String, a null QString will be returned.

null QString -> empty QByteArray.
</blockquote></details>

OK

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-KwKjpbWzxWxOhnO_Hxk:buyeh4z) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
> ```cpp
> {
>     const QJsonObject json = {
>         { "action", action },
> ```

can we use `QStringLiteral` here and in the other places? Maybe even extract the keywords into `constexpr QStringLiteral` on the file level?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 30 at r1](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwHZZoAu6Tlhv75EfzB:-KwMJD_DV8PCBG_5pSOk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/18d7d74bbec51f97c285f28d1ba2b5f6b84a632a/src/net/toxmedata.cpp#L30)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-KwMJEfL6yL7dPeLFh7m:b7tqrhl) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

can we use `QStringLiteral` here and in the other places? Maybe even extract the keywords into `constexpr QStringLiteral` on the file level?
</blockquote></details>

`QStringLiteral` done.
Don't understand what do you mean by "file level"? Scope?
If so, I don't know, is it make sense? Most of string are unique.
But if I understond right and you think, that it will make code better - say and I will do it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-KwQATlJKN177A5S0mvZ:b-ltf2dc) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`QStringLiteral` done.
Don't understand what do you mean by "file level"? Scope?
If so, I don't know, is it make sense? Most of string are unique.
But if I understond right and you think, that it will make code better - say and I will do it.
</blockquote></details>

If there are duplicates, QStringLiteral bloats the code, because their string literal is not shared.

It could be:
```
namespace { // everything is with internal linkage by default (vars, helper funcs and class definitions)
namespace consts {
namespace keys {
const QStiring Action{QStringLiteral("action")}; // hinting NL.9: Use ALL_CAPS for macro names only
} } }
```
(P.S. QStringLiteral is not a type, it's a macro with lambda call, so no constexpr, as QString constructor is not constexpr).

---

*[src/net/toxmedata.cpp, line 37 at r3](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwQ9ISArRJYqUFPGOOf:-KwQ9ISArRJYqUFPGOOg:bfo1e9c) ([raw file](https://github.com/qtox/qtox/blob/cff44bcb7f98ea07f64bf17d0373eb1b64cb3d76/src/net/toxmedata.cpp#L37)):*
> ```cpp
> {
>     const QJsonObject json = QJsonDocument::fromJson(text.toLatin1()).object();
>     const QString& key = json[QStringLiteral("key")].toString();
> ```

Is this temporary-lifetime-extension-by-const-reference really needed here? Looks kinda too smart :-), and not often used...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by sudden6** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-KwRj0SretUy21iO7RXR:b-bomfw5) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

If there are duplicates, QStringLiteral bloats the code, because their string literal is not shared.

It could be:
```
namespace { // everything is with internal linkage by default (vars, helper funcs and class definitions)
namespace consts {
namespace keys {
const QStiring Action{QStringLiteral("action")}; // hinting NL.9: Use ALL_CAPS for macro names only
} } }
```
(P.S. QStringLiteral is not a type, it's a macro with lambda call, so no constexpr, as QString constructor is not constexpr).
</blockquote></details>

I meant it in a similar way what @Talkless wrote down, though I would have made the keys private `static const` class members. IDK if that's better or worse.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-KwUCCgK4fcZ6HYsHnFh:b-y8vxtm) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I meant it in a similar way what @Talkless wrote down, though I would have made the keys private `static const` class members. IDK if that's better or worse.
</blockquote></details>

Not sure, probably matter of taste. Though maybe cosmetic argument would be that there is no need for "others" to see these `private static const` declarations in header (definitions will of course be in .cpp). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-KwUIhzoJGclvOp8EFYZ:bqtt1t0) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Not sure, probably matter of taste. Though maybe cosmetic argument would be that there is no need for "others" to see these `private static const` declarations in header (definitions will of course be in .cpp). 
</blockquote></details>

Another argument would be that namespaces helps to organize constants (globals) into groups (consts, detail, ...).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by noavarice** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 36 at r3](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwVNuYVzP_uYo5DfhL9:-KwVNuYVzP_uYo5DfhLA:bgfktlv) ([raw file](https://github.com/qtox/qtox/blob/cff44bcb7f98ea07f64bf17d0373eb1b64cb3d76/src/net/toxmedata.cpp#L36)):*
> ```cpp
> QByteArray ToxmeData::parsePublicKey(const QString& text) const
> {
>     const QJsonObject json = QJsonDocument::fromJson(text.toLatin1()).object();
> ```

Hmm, why Latin1?

---

*[src/net/toxmedata.cpp, line 37 at r3](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwQ9ISArRJYqUFPGOOf:-KwVOimMXe1TASIXmsDH:b-imbgqm) ([raw file](https://github.com/qtox/qtox/blob/cff44bcb7f98ea07f64bf17d0373eb1b64cb3d76/src/net/toxmedata.cpp#L37)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Is this temporary-lifetime-extension-by-const-reference really needed here? Looks kinda too smart :-), and not often used...
</blockquote></details>

I think this is not necessary, compiler can even `move` result of expression

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by noavarice** [comment]
Reviewed 1 of 8 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 51 at r2](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwKjpbWzxWxOhnO_Hxj:-Kx1uGzAK4UUVZFKn6dN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ecf516b4c0f068d446b6029f5d089ccc1b66f1c8/src/net/toxmedata.cpp#L51)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Another argument would be that namespaces helps to organize constants (globals) into groups (consts, detail, ...).
</blockquote></details>

Done.

---

*[src/net/toxmedata.cpp, line 36 at r3](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwVNuYVzP_uYo5DfhL9:-Kx1px3v63MKCcZL1jAZ:b-9v8vpg) ([raw file](https://github.com/qtox/qtox/blob/cff44bcb7f98ea07f64bf17d0373eb1b64cb3d76/src/net/toxmedata.cpp#L36)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Hmm, why Latin1?
</blockquote></details>

Because `fromJson` requires `QByteArray` as parameter

---

*[src/net/toxmedata.cpp, line 37 at r3](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwQ9ISArRJYqUFPGOOf:-Kx1qauJmn3NBHFvUhpc:btd6pzj) ([raw file](https://github.com/qtox/qtox/blob/cff44bcb7f98ea07f64bf17d0373eb1b64cb3d76/src/net/toxmedata.cpp#L37)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

I think this is not necessary, compiler can even `move` result of expression
</blockquote></details>

It used at least to make code easier to read

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 185 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx1z7kWT6Lw0KDqpWr6:-Kx1z7kWT6Lw0KDqpWr7:b-urljqi) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L185)):*
> ```cpp
> QString ToxmeData::deleteAddressRequest(const ToxPk& pk)
> {
>     QJsonObject json = {
> ```

const QJsonObject

---

*[src/net/toxmedata.cpp, line 187 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx2-sxjgzrR8v4yTAaT:-Kx2-sxjgzrR8v4yTAaU:b1k8bbk) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L187)):*
> ```cpp
>     QJsonObject json = {
>         { consts::keys::PublicKey, pk.toString() },
>         { consts::keys::Timestamp, static_cast<int>(time(nullptr)) },
> ```

Using `QDateTime::currentDateTimeUtc().toSecsSinceEpoch()` could avoid that cast (although kinda verbose...), as `QJsonValue` accepts `qint64`, and that `<ctime>` include could be replaced with more.. C++'ish one, if anyone cares :-) .

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 120 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx23SWPxElImS8oLsfY:-Kx23SWPxElImS8oLsfZ:bw6cz87) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L120)):*
> ```cpp
>     }
> 
>     const int code = json[consts::keys::Code].toInt(INT32_MAX);
> ```

Can we be sure that tox will never use INT32_MAX as error code?

Alternative could be something like:
```
const QJsonValue code = json[const::keys::Code];
if (!code.isDouble()) {
    return IncorrectResponse;
}
return code.toInt();
```

---

*[src/net/toxmedata.cpp, line 161 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx21xuZzUswwT4yPQjU:-Kx21xu_Yo1YGykDN_MJ:bsh5rec) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L161)):*
> ```cpp
>     if (json.isEmpty()) {
>         code = ToxmeData::NoPassword;
>         return QString{};
> ```

These could be simply `return {}` (same below).

---

*[src/net/toxmedata.cpp, line 189 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx24OpCI9zj4ST-K_fK:-Kx24OpCI9zj4ST-K_fL:bq3j3ej) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L189)):*
> ```cpp
>         { consts::keys::Timestamp, static_cast<int>(time(nullptr)) },
>     };
>     return QJsonDocument{json}.toJson();
> ```

toJson() does not use Compact, as above. Is this as planned?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 120 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx23SWPxElImS8oLsfY:-Kx3K84J0mHVHK6Ia_VW:bczgm2s) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L120)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Can we be sure that tox will never use INT32_MAX as error code?

Alternative could be something like:
```
const QJsonValue code = json[const::keys::Code];
if (!code.isDouble()) {
    return IncorrectResponse;
}
return code.toInt();
```
</blockquote></details>

Then `{ "c": 1.2 }` will be parsed as correct, which isn't true. Any other suggestions?

---

*[src/net/toxmedata.cpp, line 161 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx21xuZzUswwT4yPQjU:-Kx3K_TnIYU61-FI7sSw:bttsiiy) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L161)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

These could be simply `return {}` (same below).
</blockquote></details>

I prefer to specify type

---

*[src/net/toxmedata.cpp, line 185 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx1z7kWT6Lw0KDqpWr6:-Kx3Kbi3Hgner5U0FY1j:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L185)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

const QJsonObject
</blockquote></details>

Done.

---

*[src/net/toxmedata.cpp, line 187 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx2-sxjgzrR8v4yTAaT:-Kx3NZL1EnvvbFoXw_ue:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L187)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Using `QDateTime::currentDateTimeUtc().toSecsSinceEpoch()` could avoid that cast (although kinda verbose...), as `QJsonValue` accepts `qint64`, and that `<ctime>` include could be replaced with more.. C++'ish one, if anyone cares :-) .
</blockquote></details>

Done.

---

*[src/net/toxmedata.cpp, line 189 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx24OpCI9zj4ST-K_fK:-Kx3Nwfe1-h3UWahWyOF:b-4efcby) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L189)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

toJson() does not use Compact, as above. Is this as planned?
</blockquote></details>

Forget here. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Diadlo** [comment]
Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/net/toxmedata.cpp, line 187 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx2-sxjgzrR8v4yTAaT:-Kx3fd9-ZH4tqYlxfyld:b-qfgzgo) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L187)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`toSecsSinceEpoch` was introduced in Qt 5.8. `toMSecsSinceEpoch / 1000` used

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 161 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx21xuZzUswwT4yPQjU:-KxSQsEcdWH5VK5b6N6n:b-xd161u) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L161)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I prefer to specify type
</blockquote></details>

It has a *tiny* advantage in case of refactoring errors, but feel free to ignore, I don't want to push this too much:
```
QVariant foo() { // changed into QVariant
   // ...
   return QString{}; // forgot,  now this calls QVariant(const QString&) instead of simpler  QVariant()
}   
```

---

*[src/net/toxmedata.cpp, line 47 at r5](https://reviewable.io:443/reviews/qtox/qtox/4729#-KxSOQHITvRPWm5zd6f8:-KxSOQHJvzUWenBxqy7c:bqaqe9t) ([raw file](https://github.com/qtox/qtox/blob/2b974f6982a70cbaf53760815f3f6535db942550/src/net/toxmedata.cpp#L47)):*
> ```cpp
> }
> 
> static qint64 getCurrentTime()
> ```

Since you added use of  namespaces, this could live inside some sort of `helpers` or `detail` namespace, within anonymous namespace, so it will never clash even with ToxmeData member functions. `static` will be no longer needed, as it will live within anonymous ns. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 37 at r3](https://reviewable.io:443/reviews/qtox/qtox/4729#-KwQ9ISArRJYqUFPGOOf:-KxSS9fk2qokL9ZhMnna:b-eidhnm) ([raw file](https://github.com/qtox/qtox/blob/cff44bcb7f98ea07f64bf17d0373eb1b64cb3d76/src/net/toxmedata.cpp#L37)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

It used at least to make code easier to read
</blockquote></details>

I am talking about that reference const QString **&** key only, using variable to make easier to read is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by Talkless** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 120 at r4](https://reviewable.io:443/reviews/qtox/qtox/4729#-Kx23SWPxElImS8oLsfY:-KxST7xNoWr2lj-gbi9I:b2srnns) ([raw file](https://github.com/qtox/qtox/blob/2d35f9301e006de826b735bf5d06817b96380336/src/net/toxmedata.cpp#L120)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Then `{ "c": 1.2 }` will be parsed as correct, which isn't true. Any other suggestions?
</blockquote></details>

Hm true. No suggestions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4729#-:-KxgqNUtQtWASIIzyYnG:b-jbsf8z)*

**Pull request merged**
