### PR TITLE
Firend widget dnd

### PR DESCRIPTION
**Pull request by Diadlo**
First part of #3838

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3841)

### CODE REVIEW

**Comment by zetok** [comment]
on c9af2a582a3ddc0f22a66dcfd988fc008841b636:
- [x] regression with number of friends in the circle (note even the empty circles that claim that they have friends in them)
  
  spectacle aq9361
  
  Steps to reproduce:
  1. Add friends to circle A
  2. Drag & drop friends from circle A to circle B

**Comment by Diadlo** [comment]
@zetok Fixed

**Comment by sudden6** [comment]
Reviewed 1 of 7 files at r2.
Review status: 1 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/widget/circlewidget.cpp, line 170 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKtydprIxCPPmgBjyP:-KVKtydprIxCPPmgBjyQ:b-i51lkj) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L170)):_

> ``` cpp
>     setExpanded(true, false);
> 
>     // Check, that element dropped from qTox
> ```

... that the element is dropped ...

---

_[src/widget/circlewidget.cpp, line 176 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKu7bOiOOIMkvrwCEE:-KVKu7bOiOOIMkvrwCEF:b-wvburt) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L176)):_

> ``` cpp
>         return;
> 
>     // Check, that user have friend with same toxid
> ```

... that the user has a friend with this ToxId

---

_[src/widget/circlewidget.cpp, line 182 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKuMoBcUn0apcOPONa:-KVKuMoBcUn0apcOPONb:b-r2pdpk) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L182)):_

> ``` cpp
>         return;
> 
>     // Saved to update old circle after moved.
> ```

I can't really make sense of this comment

---

_[src/widget/friendlistwidget.cpp, line 618 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKuZ11KgsJBIIzyl9g:-KVKuZ12-EeirnK6KvTr:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/friendlistwidget.cpp#L618)):_

> ``` cpp
> void FriendListWidget::dropEvent(QDropEvent* event)
> {
>     // Check, that element dropped from qTox
> ```

Same as above

---

_[src/widget/friendlistwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKua8ilz1dl0XC90M1:-KVKua8ilz1dl0XC90M2:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/friendlistwidget.cpp#L624)):_

> ``` cpp
>         return;
> 
>     // Check, that user have friend with same toxid
> ```

Same as above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3841)_

**Comment by Diadlo** [comment]
Review status: 1 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[src/widget/circlewidget.cpp, line 170 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKtydprIxCPPmgBjyP:-KVif_Pt8T8pIlWYhvu0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L170)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> ... that the element is dropped ...
> </details>
> Done.

---

_[src/widget/circlewidget.cpp, line 176 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKu7bOiOOIMkvrwCEE:-KVifLum9aCQ7aJGZhST:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L176)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> ... that the user has a friend with this ToxId
> </details>
> Done.

---

_[src/widget/circlewidget.cpp, line 182 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKuMoBcUn0apcOPONa:-KVifMGCXFjCXFmC7t6j:b-jc95i8) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L182)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> I can't really make sense of this comment
> </details>
> It means, that we should find `CircleWidget*` before `circleId` will be changed

---

_[src/widget/friendlistwidget.cpp, line 618 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKuZ11KgsJBIIzyl9g:-KVifZhJ8Us6TW-iekQP:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/friendlistwidget.cpp#L618)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Same as above
> </details>
> Done.

---

_[src/widget/friendlistwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKua8ilz1dl0XC90M1:-KVifajM5SZLWOMvkxb5:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/friendlistwidget.cpp#L624)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Same as above
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3841)_

**Comment by sudden6** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/circlewidget.cpp, line 176 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKu7bOiOOIMkvrwCEE:-KVj9dk6T-4UtuP2gL6u:b-knip3n) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L176)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Done.
> </details>
> "with this ToxId" or "with the same ToxId" is more correct I think.

---

_[src/widget/circlewidget.cpp, line 182 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKuMoBcUn0apcOPONa:-KVjA8BYMM9loL4NaBwk:bvys5ef) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L182)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> It means, that we should find `CircleWidget*` before `circleId` will be changed
> </details>
> "Save CircleWidget before changing the Id" maybe?

---

_[src/widget/friendlistwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKua8ilz1dl0XC90M1:-KVjAQwx2r7lzI3arxT9:b-npoufo) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/friendlistwidget.cpp#L624)):_
<details><summary>

<i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary>



> Done.
> </details>
> Still same as above

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3841)_

**Comment by Diadlo** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/widget/circlewidget.cpp, line 176 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKu7bOiOOIMkvrwCEE:-KVjEBizlEzu4vepokiD:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L176)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> "with this ToxId" or "with the same ToxId" is more correct I think.
> </details>
> Done.

---

_[src/widget/circlewidget.cpp, line 182 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKuMoBcUn0apcOPONa:-KVjEC7gtL_S-6gM_4MQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/circlewidget.cpp#L182)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> "Save CircleWidget before changing the Id" maybe?
> </details>
> Done.

---

_[src/widget/friendlistwidget.cpp, line 624 at r2](https://reviewable.io:443/reviews/qtox/qtox/3841#-KVKua8ilz1dl0XC90M1:-KVjECiqjXOqnsFXqNUx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/41d245baa4cb0dd6072d50945b078eb98c67c68f/src/widget/friendlistwidget.cpp#L624)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Still same as above
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3841)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 4 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3841#-:-KVllNikce7_aQ5P7Fd_:bnfp4nl)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3841#-:-KVoA2y2rwCof_ImbU2P:bnfp4nl)_

**Pull request merged**
