### PR TITLE
Stop emoji window disappearing upon emoji selection.

### LINKED ISSUE #3043: [Feature Request] Keep emoticon option open until manually deselect
Brief description: I and some of the people I chat with enjoy fooling around with streams of emoticons/emojis in lieu of actual text. To make this fun more easy, it would be nice to have the dialog remain open so I can spam a whole bunch to my buddy instead of having to open the dialog and find the page I was on again.

Operating System: Arch Linux (Linux 4.4.5-1)  
toxcore (pacman package) version: 3747-1 
qTox (pacman package) version: 1.3.0-1
Qt version: 5.5.1
Hardware: HP G61 laptop
AMD Athlon(tm) II Dual-Core M300 × 2 
Gallium 0.4 on AMD RS880 (DRM 2.43.0, LLVM 3.7.1)

Reproducible: Always

**Steps to reproduce:**  
1.  Click smiley face beside the text window to open emoticon dialog
2.  Click any icon

**Observed Behavior:**  
Emoticon dialog closes and emoticon is pasted into the text window 

**Expected (Desired) Behavior:**  
Emoticon dialog remains open, and the selected emoticon is pasted into the text window

**Additional info:**  
This is the default functionality in Skype, and makes it quite fun to play around with the emoticons. Currently, the emoticon dialog can be deselected by clicking outside of it, so there is already an escape from the potential "problem" posed by keeping the dialog open implemented.

### PR DESCRIPTION
**Pull request by anoadragon453**
Fixes #3043.

### CODE REVIEW

**Comment by zetok** [comment]
While it does close the issue, I'm not sure if "clicking away" should be the only way in which emoticon selector can be closed.

I think that being able to select some emoticons and press "enter" to close selector & send message would be better.

**Comment by anoadragon453** [comment]
Indeed, as the cursor in the chat window is still blinking.

**Comment by anoadragon453** [comment]
@zetok That could be another issue though.

**Comment by zetok** [comment]
> @zetok That could be another issue though.

Not really, given that it's about modifying current workflow, and not adding a new yet-to-be-extended functionality.

**Comment by zetok** [comment]
Actually, I wonder if it shouldn't disappear if any key is being pressed, without catching they key - i.e. whatever key would be pressed, emoticon selector would close, and the key press would be forwarded to the input field.

**Comment by anoadragon453** [comment]
Since the cursor is still blinking I believe users would expect that behavior, yes.

**Comment by sudden6** [comment]
@anoadragon453 can you implement the behavior @zetok described?

**Comment by anoadragon453** [comment]
@sudden6 KeyEvents passed to the emoji window, other than key_ESC, should be passed to the text entry widget. I've been pretty busy lately, so if someone else wants to implement the rest of this PR don't hesitate to, otherwise I'll finish it up eventually™

**Comment by zetok** [comment]
Note: required changes were done in #3182

**Comment by zetok** [comment]
Closing, since #3182 was merged.

**Pull request closed without merging**
