### PR TITLE
feat(l10n): update Russian translation from Weblate

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3723)

### CODE REVIEW

**Comment by initramfs** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[translations/ru.ts, line 3 at r1](https://reviewable.io:443/reviews/qtox/qtox/3723#-KRtNZlQsxmLyn3wVurk:-KRtNZlRlWaB0Su_anXm:b-26e255) ([raw file](https://github.com/qtox/qtox/blob/628cfd23222df3406ef0b39580565b75d94ae352/translations/ru.ts#L3)):_

> ``` XML
> <?xml version="1.0" encoding="utf-8"?>
> <!DOCTYPE TS>
> <TS version="2.0" language="ru_RU">
> ```

I have no idea what this `TS version` tag means, but should it be going down? From 2.1 -> 2.0?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3723)_

**Comment by initramfs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3723)_

**Comment by zetok** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[translations/ru.ts, line 3 at r1](https://reviewable.io:443/reviews/qtox/qtox/3723#-KRtNZlQsxmLyn3wVurk:-KRtPKujIgaXhaoXG7XP:bfb7llw) ([raw file](https://github.com/qtox/qtox/blob/628cfd23222df3406ef0b39580565b75d94ae352/translations/ru.ts#L3)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> I have no idea what this `TS version` tag means, but should it be going down? From 2.1 -> 2.0?
> </details>
> ~Kinda. 
> `lupdate` tool on my system points to qt4 version (2.0), while earlier update done by @Diadlo used qt5 version (2.1).

That doesn't seem to matter though.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3723)_

**Comment by initramfs** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[translations/ru.ts, line 3 at r1](https://reviewable.io:443/reviews/qtox/qtox/3723#-KRtNZlQsxmLyn3wVurk:-KRtQZ8tgUZhy-cnbSPD:b2nhll9) ([raw file](https://github.com/qtox/qtox/blob/628cfd23222df3406ef0b39580565b75d94ae352/translations/ru.ts#L3)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> ~Kinda. 
> `lupdate` tool on my system points to qt4 version (2.0), while earlier update done by @Diadlo used qt5 version (2.1).
> 
> That doesn't seem to matter though.
> </details>
> Ok.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3723#-:-KRtQaD7jbUb5K8Pw5Oo:bnfp4nl)_

**Pull request merged**
