### PR TITLE
Fix quoting; everything after '>' is a quote

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by ghost** [comment]
+1

**Comment by stqism** [comment]
This is a regression.

**Comment by suhr** [comment]
@stqism Indeed it is.

**Comment by ghost** [comment]
No it's not.

**Comment by tux3** [comment]
This PR is pointless if I'm going to get another PR two days from now to revert it. Let's try to find an actual solution instead, like adding an option in the settings, or maybe making a plugin system so you can have all sorts of crazy formatting only yourself can see.

**Comment by zetok** [comment]
@tux3 This is an actual solution. At this point, qTox not only is inconsistent with its own behaviour, but also with what other Tox clients do.

**Comment by tux3** [comment]
@zetok Consistency by itself is not enough. Removing quoting support entirely would be just as if not more consistent than considering everything after '>' a quote.
Obviously, not everyone agrees that everything after '>' should be a quote (emoticons are an issue in particular), but many people still want quoting support. I would rather not just ignore either half of the problem, but instead try to find a solution that addresses the issue in its entirety.
A simple option in the settings might be a solution, this is something we could discuss.

**Comment by optimumtact** [comment]
Stop letting the core team push you around and grow a spine.

**Comment by tux3** [comment]
@optimumtact would you care to expand on that ?

**Comment by zetok** [comment]
> Removing quoting support entirely would be just as if not more consistent than considering everything after '>' a quote.

Nope, it would be inconsistent with other Tox clients.

> try to find a solution that addresses the issue in its entirety.

Issue here is that people disagree. So.. how are you going to solve it?

**Comment by ProMcTagonist** [comment]
+1

**Comment by mindcombatant** [comment]
actual solution would be to have an option in the settings finally, no one will complain once there's

<> quote greentexting ON
<> quote greentexting OFF
<> quote greentexting CUSTOM [type in your own regex]

or something similar in the settings

**Comment by tsdko** [comment]
With ON as the default, obviously.

**Comment by dcharles525** [comment]
Awesome, more settings to bloat up qTox. No one uses greentext, Tox is being written to be simple and easy for the common person, not to have a million settings.

**Comment by 4DA** [comment]
Option would be fine, just hide it under "Advanced settings".

**Comment by ayyyy** [comment]
Keep greentext, dcharles525 can %*#$ off with his generalizations.

**Comment by dubslow** [comment]
Language please :)

**Comment by zetok** [comment]
@dubslow just saying; "language" wouldn't be needed if problem was solved..

**Comment by TheLastProject** [comment]
Honestly, I think greentext is pretty okay, but if we can't agree on what should be green and what not, let's just get rid of greentexting completely. Nobody seems to be happy with any solution, and not using greentexting at all is the most consistent and most professional looking choice.

**Comment by zetok** [comment]
@TheLastProject 

> Nobody seems to be happy with any solution

Not "nobody". Also, you're not being specific when it comes to what you mean by "solution"…

**Comment by ProMcTagonist** [comment]
> Nobody seems to be happy with any solution

What? Everyone is happy with some solution.

> not using greentexting at all is the most consistent and most professional looking choice.

A completely unrelated and baseless statement, pushing your own personal preference, sprinkled with random feel-good words.

**Comment by kushagrasurana** [comment]
How about quoting only from context menu. User selects some text, right-click then click on "Quote".
We can have shortcut for the action.

**Comment by ProMcTagonist** [comment]
That sounds terrible to use and also very far removed from what we're talking about here.

**Comment by dcharles525** [comment]
@ayyyy Didn't mean to piss in your coffee mate! I guess make it a setting in advanced settings so everyone is happy?

**Comment by stal888** [comment]
Tox will make greentexting popular (again).

This could be our quirky killer feature, but only if all clients support greentext.

**Comment by optimumtact** [comment]
Yes agreed, all clients support by default, on by default
lame ass weeb emoticons can go jump

**Comment by JFreegman** [comment]
> Not supporting greentext

Into the trash it goes

**Comment by Zer0-One** [comment]
@JFreegman 
trash

**Comment by stal888** [comment]
@Zer0-One 
no

**Comment by ayyyyyyyyyyy** [comment]
Could you please merge PR?

**Comment by zetok** [comment]
still broken

↑ qTox users without this patch still have to suffer broken quoting

Edit: it still applies cleanly against master qTox..

**Comment by ProMcTagonist** [comment]
Please patch this bug

**Comment by zetok** [comment]
Since it doesn't apply cleanly on master any longer, I've created new PR: #1732

**Pull request closed without merging**
