### PR TITLE
Fix desktop stream crash

### PR DESCRIPTION
**Pull request by Diadlo**

### CODE REVIEW

**Comment by sudden6** [comment]
If I read this correctly the qDebug() statements will be called for every frame and create massive logspam. Is this PR intended only for testing?

**Comment by Diadlo** [comment]
This PR for tests, now

**Comment by sudden6** [comment]
ok, please put this information in the comment in the future.

**Comment by zetok** [comment]
03c50764d6d0cc8acd8e319715ccd2d423e0bf2c fixes #3527 for me.

Add to commit message info "why", i.e. that it fixes an issue where stuff crashed because $reasons

Generally, commits should explain what their purpose is, not only what is done, but also why.

\+ `Fixes #3527`

**Pull request merged**
