### PR TITLE
chore(i18n): translate INSTALL.md to persian

### PR DESCRIPTION
**Pull request by dev0p0**
Translating INSTALL.md to Persian language.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5046)

### CODE REVIEW

**Comment by anthonybilinski** [comment]
Not a big deal, but in the future you can create a new branch on your fork and PR from there, then to fix problems you can force push new commits to that branch and the PR will automatically see them, this way you won't have to create multiple PRs :)

As for the content, it would be great if a native Persian speaker could review the contents, I don't think we have any on the main team. If you could maybe pull in a friend, ideally bilingual, to review it and check for any mistakes that would be great.

For translations, we normally translate UI contents using weblate, more info at https://github.com/qTox/qTox/blob/master/translations/README.md. We should maybe add project docs like this in there as well to manage the translations, if that's possible with a markdown doc that can't dynamically parse translation files like qTox does. @sudden6 what do you think? Is having manual translation maintainable?

dev0p0 if you're interested in translation more Persian, our Persian translation coverage for qTox itself is pretty low (currently at 57%) so feel free to head over to weblate :D

**Comment by dev0p0** [comment]
@anthonybilinski Thanks for the hint about the PR, I will keep that in mind. 

I certainly have friends that are able to review the content, that have good knowledge of both the languages and Git. I have a few buddies that are not programmers but have very good knowledge of English and Persian literature and language, but are not used to computers and Git. So I don't know what to do. :(

I am actively working on the Persian part of the weblate, I feel kind of lonely cause no one else seems to contribute over there, and it would be great if I could ask some persian translators to join in. Most of the people I know are busy with their daily jobs or their boyfriend and girlfriends :) Also to be honest @sudden6 among some other friends over #tox and #toktok were the ones who suggested translating the INSTALL.md, the weblate, and that I update the user guide and translate it as well.

So, should I change the INSTALL.fa.md? or should I only bring in some folks for the review? And can you please tell me how this reviewing process by a friend of mine that is also good at Git, should be done? Thank you.

**Comment by sudden6** [comment]
@anthonybilinski I think the only documents to translate that make sense are README.md and the user manual. Not sure about weblate for them, but it could be possible. Maybe we should extend our website to cover that? It's already setup with weblate and multiple languages. <- @tox-user IIRC you wanted more content for the website, that sort of content?

@dev0p0 If your friends can use Github the easiest would be for them to leave some comments here. If not maybe someone can review it via email and you merge the corrections? Maybe you can also give qTox to them when we next pull in translations so they can see where the translations are applied?

**Comment by dev0p0** [comment]
Great @sudden6  I will leave em a hint so they can come over here and check it out. Thank you. I might ask a few people to check this thing, so you might want to wait a day or two so they can check the translation. Thank you.

**Comment by tox-user** [comment]
@sudden6 a user guide wouldn't hurt, but I'm not sure if it makes sense to maintain it in both places (unless it's not required).

**Comment by sudden6** [comment]
You're right, it could be either on the website or in the repo.

**Comment by jupiter69** [comment]
the translation that was written by dev0p0 was superb. thumbs up bro. keep it up..

**Comment by sudden6** [comment]
I think we can count this as :lgtm_strong: then

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/qtox/qtox/5046#-:-L9MUtP234-FfH1ClSud:bwbw8ww)*

**Comment by dev0p0** [comment]
Thank you guys! @anthonybilinski @sudden6 @jupiter69 I am awaiting one of my other friends commit though, they have made some suggestions as well.

**Comment by sudden6** [comment]
@dev0p0 what's the state of this? also your translations have been merged and you should be able to test them in the next release

**Comment by dev0p0** [comment]
Hi there @sudden6, I have had a rough week. My system is having all sorts of problems. I have tried to get hold of my friend regarding the translation, unfortunately she/he is not able to find the time to make a commit. So you probably just wanna go ahead and accept just my one friend's comment about the correctness of the translation. Thank you about the merge, I will check em right now.

**Pull request merged**
