### PR TITLE
Update translations from Weblate

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3767)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1, 29 of 29 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[translations/ar.ts, line 132 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT3yaC1sDoIjWCv7J5h:-KT3yaC1sDoIjWCv7J5i:b-vm9sg8) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/ar.ts#L132)):_

> ``` XML
>     <message>
>         <source>You are using qTox version %1.</source>
>         <translation type="unfinished">حالياً تستخدم الإصدار كيوتوكسqTox %1</translation>
> ```

Maybe add `.` in the end of sentence?

---

_[translations/et.ts, line 132 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT4-XwAxZeiQyiY9SW8:-KT4-XwBHvYBCY6vJua6:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/et.ts#L132)):_

> ``` XML
>     <message>
>         <source>You are using qTox version %1.</source>
>         <translation type="unfinished">Kasutad qToxi versiooni %1</translation>
> ```

Same as above

---

_[translations/et.ts, line 140 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT40ytiQ6uEDanY3ZQS:-KT40ytjf8bQRN97Xy0i:b-ab953h) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/et.ts#L140)):_

> ``` XML
>     <message>
>         <source>toxcore version: %1</source>
>         <translation type="unfinished">TOXcore'i versioon: %1</translation>
> ```

Why here `TOX` is uppercase?

---

_[translations/lt.ts, line 132 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT43G-RtHAGV-vAlpsE:-KT43G-ShSUXUrVoiYuq:b-vm9sg8) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/lt.ts#L132)):_

> ``` XML
>     <message>
>         <source>You are using qTox version %1.</source>
>         <translation type="unfinished">Naudojate qTox versiją: %1</translation>
> ```

Maybe add `.` in the end of sentence?

---

_[translations/nl.ts, line 8 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT43nYe47fFxQRVjrAy:-KT43nYfADjFajeC7mLV:bw4g6sc) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/nl.ts#L8)):_

> ``` XML
>     <message>
>         <source>Audio/Video</source>
>         <translation>Audio/video</translation>
> ```

Why lowercase? Anyway, does not correspond to the original

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3767)_

**Comment by zetok** [comment]
Review status: 27 of 30 files reviewed at latest revision, 5 unresolved discussions.

---

_[translations/ar.ts, line 132 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT3yaC1sDoIjWCv7J5h:-KT47FLv-TMjETgIpQdz:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/ar.ts#L132)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Maybe add `.` in the end of sentence?
> </details>
> Done.

---

_[translations/et.ts, line 132 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT4-XwAxZeiQyiY9SW8:-KT47PpMzMkS1IZ0ASwv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/et.ts#L132)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Same as above
> </details>
> Done.

---

_[translations/et.ts, line 140 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT40ytiQ6uEDanY3ZQS:-KT47R8vgdtt1kngHAnh:b4wnxtm) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/et.ts#L140)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Why here `TOX` is uppercase?
> </details>
> Dunno, I've just copypasted that from the original translation

---

_[translations/lt.ts, line 132 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT43G-RtHAGV-vAlpsE:-KT47aZ_G3d-uIDFCeRE:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/lt.ts#L132)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Maybe add `.` in the end of sentence?
> </details>
> Done.

---

_[translations/nl.ts, line 8 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT43nYe47fFxQRVjrAy:-KT47chx-pXwyYNKrclT:bz4m5rj) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/nl.ts#L8)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Why lowercase? Anyway, does not correspond to the original
> </details>
> Dunno, that's what comes from weblate, perhaps some grammar rules or something.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3767)_

**Comment by Diadlo** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[translations/et.ts, line 140 at r2](https://reviewable.io:443/reviews/qtox/qtox/3767#-KT40ytiQ6uEDanY3ZQS:-KT4E8BBOROvrUCC--a7:b32w1t) ([raw file](https://github.com/qtox/qtox/blob/4d77216f28acd939807c1562d3e513f6d4e2c41d/translations/et.ts#L140)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Dunno, I've just copypasted that from the original translation
> </details>
> Ok

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3767)_

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3767#-:-KT4EHVS2DeJ3SP5Yj7Y:bnfp4nl)_

**Pull request merged**
