### PR TITLE
Rewrite all links to the qTox repository from tux3 to qTox

### PR DESCRIPTION
**Pull request by initramfs**
This PR rewrites all links within the repository from https://github.com/tux3/qTox to https://github.com/qTox/qTox as per the changes introduced in issue #3578.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3585)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3585)_

**Comment by zetok** [comment]
Reviewed 47 of 49 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[INSTALL.md, line 447 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3585#-KOHaWAvx4LmNd_f78lk:-KOHaWAwyApuOUMVJV0A:-1207983462) ([raw file](https://github.com/qtox/qtox/blob/b7aa982a57de1e2d54a6150732e370b44af89525/INSTALL.md#L447)):_

> `````` Markdown
> Then, clone qTox:
> ```bash
> git clone https://github.com/qTox/qTox``
> ``````

Change itself is Ok, but since line is already being changed those trailing backticks should be removed

---

_[src/widget/form/settings/aboutform.cpp, line 96 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3585#-KOJSnuhzZ6uyZETVsUt:-KOJSnuiOHpgnZHqWMmK:1379199408) ([raw file](https://github.com/qtox/qtox/blob/b7aa982a57de1e2d54a6150732e370b44af89525/src/widget/form/settings/aboutform.cpp#L96)):_

> ``` cpp
>                                     "----%0A%0AMore+information+on+how+to+"
>                                     "write+good+bug+reports+in+the+wiki%3A+"
>                                     "https%3A%2F%2Fgithub.com%2Ftux3%2FqTox%2F"
> ```

This too needs to be changed

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3585)_

**Comment by initramfs** [comment]
@zetok Damn... You're good... (at finding dem links). Issues resolved. :)

**Comment by zetok** [comment]
>   fix(INSTALL.md): remove unnecessary backticks in qTox URL

This isn't a fix, since it doesn't fix anything in qTox itself (i.e. the application, from user PoV).

Edit: `docs(INSTALL.md): ...` would do

**Comment by zetok** [comment]
BTW, it would seem that PR submitter needs to acknowledge each discussion in reviewable as resolved too.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[INSTALL.md, line 447 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3585#-KOHaWAvx4LmNd_f78lk:-KOJeNIv6sVrTjjWzxgy:5173665) ([raw file](https://github.com/qtox/qtox/blob/b7aa982a57de1e2d54a6150732e370b44af89525/INSTALL.md#L447)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Change itself is Ok, but since line is already being changed those trailing backticks should be removed
> </details>
> OK

---

_[src/widget/form/settings/aboutform.cpp, line 96 [r1]](https://reviewable.io:443/reviews/qtox/qtox/3585#-KOJSnuhzZ6uyZETVsUt:-KOJePtk_dhgjknuC2Xq:5173665) ([raw file](https://github.com/qtox/qtox/blob/b7aa982a57de1e2d54a6150732e370b44af89525/src/widget/form/settings/aboutform.cpp#L96)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> This too needs to be changed
> </details>
> OK

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3585#-:-KOJegG_80pAhqgvwnO3:2048868560)_

**Comment by initramfs** [comment]
@zetok I've aknowledged all comments.

**Comment by zetok** [comment]
@initramfs right, reviewable's UI isn't really intuitive – after you comment/acknowledge/etc you need to push the "Publish" button – until that, "changes" aren't shown.

**Comment by zetok** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3585#-:-KOK39-raVHAK73tBfzb:1417088721)_

**Comment by zetok** [comment]
nvm, looks like I cannot into reviewable's UI -.-"

**Pull request merged**
