### PR TITLE
add dark style

### PR DESCRIPTION
**Pull request by TriKriSta**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)
screenshot_20190221_155103
screenshot_20190219_162027
screenshot_20190223_194323
screenshot_20190223_194404
screenshot_20190223_194458

I started to create dark style.
What colors would be preferable?

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5558)

### CODE REVIEW

**Comment by 2635599** [comment]
i like this

**Comment by naxuroqa** [comment]
This looks nice, but it seems this will need quite some work maintaining it in the future. Is qtox overwriting the default qt theme this much?

**Comment by TriKriSta** [comment]
@naxuroqa, Need to edit a lot of css files yet. But in the future will need to edit these files if will add new widgets in program

**Comment by sudden6** [comment]
Nice!

**Comment by Monsterovich** [comment]
I want white theme too.

**Comment by sudden6** [comment]
@TriKriSta Is this ready for review already?

**Comment by TriKriSta** [comment]
@sudden6 not yet, I need to edit some styles.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 58 of 82 files at r1, 34 of 50 files at r2, 21 of 21 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5558)* status: 0 of 1 LGTMs obtained

___
*[src/widget/style.cpp, line 407 at r3](https://reviewable.io/reviews/qtox/qtox/5558#-LZQiMG38CLpQNqPe70j:-LZQiMG38CLpQNqPe70k:b-ksrkwg) ([raw file](https://github.com/qtox/qtox/blob/d35dbcc870d3f35c9ba075736f85ec27d7c84b42/src/widget/style.cpp#L407)):*
> ```cpp
> QString Style::getThemePath()
> {
>     if (Settings::getInstance().getThemeColor() > 4) {
> ```

Hardcoding `4` as constant here seems quite dangerous, can you rewrite this to e.g. use the theme name to decide on the path?

**Review by TriKriSta — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5558)* status: 0 of 1 LGTMs obtained

___
*[src/widget/style.cpp, line 407 at r3](https://reviewable.io/reviews/qtox/qtox/5558#-LZQiMG38CLpQNqPe70j:-LZUtp4687n6wz6tp3CZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d35dbcc870d3f35c9ba075736f85ec27d7c84b42/src/widget/style.cpp#L407)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Hardcoding `4` as constant here seems quite dangerous, can you rewrite this to e.g. use the theme name to decide on the path?
</blockquote></details>

Done.

**Review by sudden6 — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5558)* status: 0 of 1 LGTMs obtained

**Comment by sudden6** [comment]
The code looks good to me now, but this PR makes qTox segfault with the following backtrace:

```
1 QWidget::setStyleSheet(QString const&)                        0x7ffff0e4f9e0 
2 ContentLayout::reloadTheme             contentlayout.cpp 72   0x78c83d       
3 Widget::reloadTheme                    widget.cpp        2181 0x691780       
4 Widget::init                           widget.cpp        223  0x685f35       
5 Nexus::showMainGUI                     nexus.cpp         176  0x61ce6a       
6 Nexus::start                           nexus.cpp         140  0x61cc47       
7 main                                   main.cpp          353  0x611be2       
```

Where in `ContentLayout::reloadTheme()` `mainContent` and `mainHead` are both `nullptr`.

**Comment by TriKriSta** [comment]
@sudden6, I don't have this problem, but I tried to fix it.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong: your latest commit fixes this problem for me too

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5558#-:-LZaFKJGEgr179upsGJJ:bhiehsv)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by envsh** [comment]
Cool!

**Comment by sudden6** [comment]
@TriKriSta Thank you very much for this work!

**Comment by whoizit** [comment]
@TriKriSta I'm rly apreciate it, rly nice work!

**Comment by quantumpacket** [comment]
Could we get a new release pushed out sometime soon? :)

**Comment by fcore117** [comment]
Daily builds seems broken.

**Comment by MEGAMASTER4000** [comment]
I'm sorry for probably asking a somewhat stupid quesstion, but how do we install this? Have used x64 install package.

**Comment by sudden6** [comment]
You can install a nightly build, but make sure to back up your profile: https://github.com/qTox/qTox-nightly-releases/releases/tag/ci-master-latest

**Comment by MEGAMASTER4000** [comment]
@sudden6 Thank you for your response. It might be I'm just new to github and haven't figured it out yet, but the link you provided only provides LICENSE and RREADME.MD. I can't install anything with that - right?

**Comment by anthonybilinski** [comment]
Check here: https://github.com/qTox/qTox-nightly-releases/releases which is under the "releases" tab at the top of that page. You can just expand the "assets" from the releases and choose the installer for your platform. Our latest nightly is a bit stale.. I'm working on that now.

I think I broke @sudden6's link while trying to get our nightlies running again.. that should be fixed once I succeed.

**Comment by ghost** [comment]
Hey, this is great! 
Could I suggest a gray theme? This works great with Breeze Dark in Plasma.
79163561-9a696980-7ddf-11ea-8c43-49e515af9201
Are there any plans to release this any time soon?

**Pull request merged**
