### PR TITLE
fix(appimage): build sqlcipher form source

### PR DESCRIPTION
**Pull request by sudden6**
Needed since Debian version is broken https://bugs.debian.org/850421

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109)

### CODE REVIEW

**Comment by tox-user** [comment]
Related issue: https://github.com/qTox/qTox/issues/4054

**Comment by tox-user** [comment]
It works!

**Comment by anthonybilinski** [comment]
haven't tested, but code changes :lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109#-:-LBE2OnrC9oZEkovAGbQ:bgmxeoo)*

**Comment by anthonybilinski** [comment]
tested with this change and still segfault on encrypted profiles :lgtm_cancel:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109#-:-LBE6EMZ8LxOoBi6gO9i:b-wt4p32)*

**Comment by nurupo** [comment]
@sudden6 Are you sure that qTox is linking using libsqlcipher that you have manually built, not the libsqlcipher installed from Debian's package repository? Looking at the diff, it seems like there are two different libsqlciphers now. The one you have built is probably installed into `/usr/local`, and it's likely that qTox's cmake finds Debian's libsqlcipher before it gets to search `/usr/local`.

**Comment by sudden6** [comment]
@nurupo that's why I modified `simple_make.sh` to not install sqlcipher.

Also the qtox build process seems to use the sqlcipher from `/usr/local/`
```
-- Checking for one of the modules 'sqlcipher'
-- SQLCIPHER LIBRARY_DIRS: /usr/local/lib
-- SQLCIPHER INCLUDE_DIRS: /usr/local/include/sqlcipher
-- SQLCIPHER CFLAGS_OTHER: 
-- SQLCIPHER LIBRARIES:    sqlcipher
-- SQLCIPHER found
```

@anthonybilinski can you check that's also the case for you?

I've uploaded my build [here](https://a.uguu.se/MQCf1JFLjizf.appimage), maybe that one works, then we have a strange problem.

**Comment by nurupo** [comment]
Looking at the PR diff, I don't see `simple_make.sh` being modified at all.

**Comment by nurupo** [comment]
Hm, despite having Debian sqlcipher installed, qTox's cmake does indeed say that it uses sqlcipher from `/usr/local`, so I guess everything is fine.

**Comment by sudden6** [comment]
@nurupo thanks, I'm an idiot, forgot to push the changes *facedesk*

**Comment by anthonybilinski** [comment]
Tested, no more seg fault on encrypted profiles :lgtm_strong:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[appimage/build.sh, line 83 at r2](https://reviewable.io/reviews/qtox/qtox/5109#-LBcDfUADU-daEydPHD_:-LBcDfUADU-daEydPHDa:b-hfqosi) ([raw file](https://github.com/qtox/qtox/blob/51366b60ef5b4389542b78606c42c091e73d8b1c/appimage/build.sh#L83)):*
> ```Shell
> # APT_FLAGS for automatic install
> # True to not install sqlcipher
> ./simple_make.sh "$APT_FLAGS" True
> ```

maybe rename the arg to something more meaningful than "True", i.e. "WITHOUT_SQLCIPHER" so that it's clear from the caller's perspective what it's for and so it's harder to mix up with future args.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109#-:-LBcDr2G03Q_LdyovQ8k:bjo2xju)*

**Comment by nurupo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[simple_make.sh, line 37 at r2](https://reviewable.io/reviews/qtox/qtox/5109#-LBeX8fD2RDW11AgWE37:-LBeX8fD2RDW11AgWE38:b-tupejx) ([raw file](https://github.com/qtox/qtox/blob/51366b60ef5b4389542b78606c42c091e73d8b1c/simple_make.sh#L37)):*
> ```Shell
>     )
> 
>     if [ "$WITHOUT_SQLCIPHER" != "True" ]; then
> ```

having `then` o na new line and `;` removed would make it consistent with the rest of the script.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109)*

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[simple_make.sh, line 37 at r2](https://reviewable.io/reviews/qtox/qtox/5109#-LBeX8fD2RDW11AgWE37:-LBfJ6No5aQvQ00DqRZN:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/51366b60ef5b4389542b78606c42c091e73d8b1c/simple_make.sh#L37)):*
<details><summary><i>Previously, nurupo wrote…</i></summary><blockquote>

having `then` o na new line and `;` removed would make it consistent with the rest of the script.
</blockquote></details>

Done.

---

*[appimage/build.sh, line 83 at r2](https://reviewable.io/reviews/qtox/qtox/5109#-LBcDfUADU-daEydPHD_:-LBfJ8ky3ojyE0U0KS1N:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/51366b60ef5b4389542b78606c42c091e73d8b1c/appimage/build.sh#L83)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

maybe rename the arg to something more meaningful than "True", i.e. "WITHOUT_SQLCIPHER" so that it's clear from the caller's perspective what it's for and so it's harder to mix up with future args.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109)*

**Comment by nurupo** [comment]
Did not test, but the PR looks okay. :lgtm_strong:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5109#-:-LBhKyfr1CY4OZ_iGOs5:btsguo9)*

**Pull request merged**
