### PR TITLE
docs(CONTRIBUTING): add section about include styles

### PR DESCRIPTION
**Pull request by sudden6**
@iphydf please comment if that's what you meant ;)

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3729)

### CODE REVIEW

**Comment by iphydf** [comment]
I like enforceable rules. This is not an easily enforceable set of rules. An easily enforceable rule would be "only use relative include paths for internal includes". You can enforce this rule by not passing `-I$TOPLEVEL_SOURCE_DIR` to the compiler. Currently, that will break compilation, because the code does not follow this rule. If you fix the current code (aided by the compiler telling you where to fix it), you'll then be able to enforce the rule on future code.

**Comment by sudden6** [comment]
Updated after a clarifying discussion on IRC. @initramfs @antis81 what do you think about it?

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 273 at r1](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8EDSJ2pn10i7sS_I2:-KS8EDSJ2pn10i7sS_I3:b-18w4om) ([raw file](https://github.com/qtox/qtox/blob/a46a3f633ac15eafa8c5beb86aae0e5eb75e60aa/CONTRIBUTING.md#L273)):_

> ``` Markdown
> ## Includes
> 
> On the project level, include files starting with the root directory of the repository, e.g.
> ```

<80 chars per line, also applies to the other line

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[CONTRIBUTING.md, line 273 at r1](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8EDSJ2pn10i7sS_I2:-KS8EtEgyOf8UtAwi4bJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/a46a3f633ac15eafa8c5beb86aae0e5eb75e60aa/CONTRIBUTING.md#L273)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> <80 chars per line, also applies to the other line
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by initramfs** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[CONTRIBUTING.md, line 273 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8qFTO4cUNuOb2LFC4:-KS8qFTPdn9uEWl1q9nt:b2n1ads) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L273)):_

> ``` Markdown
> ## Includes
> 
> On the project level, include files starting with the root directory of the
> ```

Change to:

"...include files **should** start with the root directory of the repository..."

Also, this is not always true. Including a file in the same directory should be free of any directory specifier. E.g. under the directory `src/video/` files including each other should **not** prefix their includes with `src/video/`.

---

_[CONTRIBUTING.md, line 277 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8rOdECZfHfj-k6U-s:-KS8rOdECZfHfj-k6U-t:b-uwl7hi) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L277)):_

> `````` Markdown
> 
> ```C++
> "src/core/core.h"
> ``````

Might want to make the example:

``` c++
#include "src/core/core.h"
```

---

_[CONTRIBUTING.md, line 280 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8qqhUhIwkBe8-0xS3:-KS8qqhVJIDYnLBbMwlv:bmy9aj8) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L280)):_

> ``` Markdown
> ```
> 
> If including files from the operating systems libraries or framework use `<>`
> 
> ```
> ```

Change to:

"...from ~~the~~ operating system libraries or **frameworks** use `<>`..."

If this is to be mentioned, you should also mention that Qt library headers must be included using the `<>` operations too.

---

_[CONTRIBUTING.md, line 281 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8rgdH_qSzfgWi1xPj:-KS8rgdH_qSzfgWi1xPk:b-ryd8fq) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L281)):_

> ``` Markdown
> 
> If including files from the operating systems libraries or framework use `<>`
> tags, e.g. `stdio.h` from `src/main.cpp`:
> ```

We're using C++ here, we include `cstdio` instead of `stdio.h`.

---

_[CONTRIBUTING.md, line 284 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8rVVtMNQezR0EqqZy:-KS8rVVtMNQezR0EqqZz:bjo4dd) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L284)):_

> `````` Markdown
> 
> ```C++
> <stdio.h>
> ``````

Same as above, might want to make the example:

``` c++
#include <cstdio>
```

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by sudden6** [comment]
_[CONTRIBUTING.md, line 273 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8qFTO4cUNuOb2LFC4:-KSCtZtU47HgTki9am3g:bn1bvuo) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L273)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Change to:
> 
> "...include files **should** start with the root directory of the repository..."
> 
> Also, this is not always true. Including a file in the same directory should be free of any directory specifier. E.g. under the directory `src/video/` files including each other should **not** prefix their includes with `src/video/`.
> </details>
> In the discussion on IRC just before you joined yesterday there was the idea that local includes should always start with `src/` because it makes the rule easier to enforce.
> https://github.com/qTox/qtox-irc-logs/blob/master/2016/09/%23qtox_20160920.log.txt#L89

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[CONTRIBUTING.md, line 280 at r3](https://reviewable.io:443/reviews/qtox/qtox/3729#-KSLT5-TjcOnl8QyGrKY:-KSLT5-U9KtkLjwhMAbT:b1omf4c) ([raw file](https://github.com/qtox/qtox/blob/8437fdfafcb78a0fe7856b1cc3631ca5019c54d6/CONTRIBUTING.md#L280)):_

> operating systems

system ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[CONTRIBUTING.md, line 277 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8rOdECZfHfj-k6U-s:-KSMxC37kewSDAVS8OvV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L277)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Might want to make the example:
> 
> ``` c++
> #include "src/core/core.h"
> ```
> 
> </details>
> Done.

---

_[CONTRIBUTING.md, line 280 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8qqhUhIwkBe8-0xS3:-KSMx8TW93WYfkj_pihx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L280)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Change to:
> 
> "...from ~~the~~ operating system libraries or **frameworks** use `<>`..."
> 
> If this is to be mentioned, you should also mention that Qt library headers must be included using the `<>` operations too.
> </details>
> Done.

---

_[CONTRIBUTING.md, line 281 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8rgdH_qSzfgWi1xPj:-KSMvN1x64ud0nea4Rgb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L281)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> We're using C++ here, we include `cstdio` instead of `stdio.h`.
> </details>
> Done.

---

_[CONTRIBUTING.md, line 284 at r2](https://reviewable.io:443/reviews/qtox/qtox/3729#-KS8rVVtMNQezR0EqqZy:-KSMvOIyBL98ue8PwIzo:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/748a2a0eefab8a66a2ce6f970213b1cc01532f21/CONTRIBUTING.md#L284)):_
<details><summary>

<i>Previously, initramfs wrote…</i></summary>



> Same as above, might want to make the example:
> 
> ``` c++
> #include <cstdio>
> ```
> 
> </details>
> Done.

---

_[CONTRIBUTING.md, line 280 at r3](https://reviewable.io:443/reviews/qtox/qtox/3729#-KSLT5-TjcOnl8QyGrKY:-KSMvKi0_pkYZJyffYEc:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8437fdfafcb78a0fe7856b1cc3631ca5019c54d6/CONTRIBUTING.md#L280)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> > operating systems
> 
> system ?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

_[CONTRIBUTING.md, line 274 at r3](https://reviewable.io:443/reviews/qtox/qtox/3729#-KSNrzwmdFI6ncVNB1W6:-KSNrzwmdFI6ncVNB1W7:b-zi94ej) ([raw file](https://github.com/qtox/qtox/blob/8437fdfafcb78a0fe7856b1cc3631ca5019c54d6/CONTRIBUTING.md#L274)):_

> ``` Markdown
> 
> On the project level, include files starting with the root directory of the
> repository, e.g. `src/core/core.h` from `src/widget/widget.cpp`:
> ```

There's missing part that other kinds of includes from project (relative) are banned – i.e. currently it looks like an example of what should be used, without specifying that something else shouldn't be used.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by sudden6** [comment]
sorry accidentally deleted the branch...

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[CONTRIBUTING.md, line 274 at r3](https://reviewable.io:443/reviews/qtox/qtox/3729#-KSNrzwmdFI6ncVNB1W6:-KTsh8rYe5iNES252QDU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8437fdfafcb78a0fe7856b1cc3631ca5019c54d6/CONTRIBUTING.md#L274)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> There's missing part that other kinds of includes from project (relative) are banned – i.e. currently it looks like an example of what should be used, without specifying that something else shouldn't be used.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729)_

**Comment by zetok** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3729#-:-KTsmGdVtEOp-n3j8iBu:bnfp4nl)_

**Pull request merged**
