### PR TITLE
chore: update download links for Windows

### LINKED ISSUE #4901: Download Site is Offline
I was trying to download the windows version but the site is offline.

### PR DESCRIPTION
**Pull request by sudden6**
fixes  #4901

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4902)

### CODE REVIEW

**Comment by nurupo** [comment]
I think you meant to link the installers instead of zips? Because that's what the `qtox-win.pkg.tox.chat` URLs redirected to before -- installers.

**Comment by sudden6** [comment]
are the installers still autmatically built on every release?

**Comment by nurupo** [comment]
That would be those pkg jobs

- https://build.tox.chat/view/qtox/job/qTox_pkg_windows_x86-64_stable_release/lastSuccessfulBuild/artifact/setup-qtox.exe
- https://build.tox.chat/view/qtox/job/qTox_pkg_windows_x86_stable_release/lastSuccessfulBuild/artifact/setup-qtox.exe

**Comment by nurupo** [comment]
Remember there was an issue with verifying qTox signatures? After that I have disabled those ^ pkg projects so that they won't be updated by anything until someone re-enabled them on a release and disables again.

**Comment by nurupo** [comment]
Now that I think, since the update server is down, we don't even have sigs anymore, huh.

**Comment by sudden6** [comment]
yep, that's probably the case. Also the updater is disabled in the next builds since it was pretty broken.

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 141 at r1](https://reviewable.io:443/reviews/qtox/qtox/4902#-L2RXd-6LCV81OgikBjz:-L2RXd-6LCV81OgikBk-:b-genhjm) ([raw file](https://github.com/qtox/qtox/blob/bb8bc53790c3a89bc5427435082405ca5fdd8fc1/README.md#L141)):*
> ```Markdown
> 
> [#qtox@freenode]: https://webchat.freenode.net/?channels=qtox
> [64 bit release]: https://build.tox.chat/view/qtox/job/qTox_pkg_windows_x86-64_stable_release/lastSuccessfulBuild/artifact/setup-qtox.exe
> ```

Why installer renamed to release?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4902)*

**Comment by sudden6** [comment]
@Diadlo because they are all built from the release tag, I thought it's better fitting.

**Comment by nurupo** [comment]
While at it, change "portable" to "nightly".

**Comment by nurupo** [comment]
Oh, there is no "portable" anymore. Good, no need to change anything then.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4902#-:-L2Uhfy0YIrUJ2CCLuDV:b-jbsf8z)*

**Pull request merged**
