### PR TITLE
Merge v1.16.3

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [ ] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Since all the changes in v1.16.2 and v1.16.3 were backported from master tip (except flatpak KDE SDK version pump), the only diffs generated from the merge are version updates on master.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5262)

### CODE REVIEW

**Comment by sudden6** [comment]
Can you cherry pick the KDE SDK update into master?

**Comment by anthonybilinski** [comment]
The KDE SDK update will be merged into master as is. Is there a reason to cherry-pick the commit as well?

**Comment by sudden6** [comment]
no, i just meant to put it into master

**Comment by anthonybilinski** [comment]
The SDK update is in e5234cefc16461818bf03174c5ebbd293d6e89d2, which was in v1.16.3 release, and is part of this PR. This merge puts it in master. So isn't no action required?

**Review by sudden6 — APPROVED** [review]
Sorry, I mistook this for a test PR and only now realized that it's the PR to update our README and  versions :lgtm_strong: 

> Reviewed 5 of 6 files at r4, 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5262#-:-LI2uVAN4qR5oA8F0AV-:b-sd0k93)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
