### PR TITLE
refactor: remove getInstance from toxuri.cpp

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Need to test if I didn't break any functionality with this.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6178)

### CODE REVIEW

**Comment by bodwok** [comment]
In the main.cpp file:
``` 
    if (profile) {
          nexus.bootstrapWithProfile(profile);
      } else {
         nexus.setParser(&parser); 
         int returnval = nexus.showLogin(profileName); 
         if (returnval == QDialog::Rejected) { 
             return -1; 
         } 
    }

    uriDialog = std::unique_ptr<ToxURIDialog>(new ToxURIDialog(nullptr, profile->getCore())); // profile can be nullptr
```
I changed to:
```
    if (profile) {
        nexus.bootstrapWithProfile(profile);
    } else {
        nexus.setParser(&parser);
        int returnval = nexus.showLogin(profileName);
        if (returnval == QDialog::Rejected) {
            return -1;
        }
	profile = nexus.getProfile();
    }

    uriDialog = std::unique_ptr<ToxURIDialog>(new ToxURIDialog(nullptr, profile->getCore()));
```
and it started without errors for me

**Comment by sudden6** [comment]
Thank you very much for the review. Your fix is correct and I updated the PR. If you open Reviewable and give the `ltgm_strong` I'll merge it as soon as I'm online again.

**Review by bodwok — COMMENTED** [review]
I tested that and now it seems to be working.
One question:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6178#-:-MAwFohV59HtTIbPW1Lq:bg08wlk)* status: 0 of 1 LGTMs obtained

___
*[src/net/toxuri.h, line 38 at r1](https://reviewable.io/reviews/qtox/qtox/6178#-MAwB8-h5bQYFCI7GfJL:-MAwB8-h5bQYFCI7GfJM:b3pcod0) ([raw file](https://github.com/qtox/qtox/blob/673ab08347ae551aab06da6e1afd9e5a49be25d0/src/net/toxuri.h#L38)):*
> ```objc
>     QString getRequestMessage();
>     bool handleToxURI(const QString& toxURI);
>     bool toxURIEventHandler(const QByteArray& eventData);
> ```

this method is declared but not defined?

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6178)* status: 0 of 1 LGTMs obtained

___
*[src/net/toxuri.h, line 38 at r1](https://reviewable.io/reviews/qtox/qtox/6178#-MAwB8-h5bQYFCI7GfJL:-MB5qZ9vEZv2fFxthdJZ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/673ab08347ae551aab06da6e1afd9e5a49be25d0/src/net/toxuri.h#L38)):*
<details><summary><i>Previously, bodwok wrote…</i></summary><blockquote>

this method is declared but not defined?
</blockquote></details>

Done.

**Review by bodwok — COMMENTED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6178#-:-MB67xpE8wCS9MDnmtdW:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Comment by sudden6** [comment]
@bodwok thank you for your review!

**Comment by bodwok** [comment]
You’re welcome)

**Pull request merged**
