### PR TITLE
fix: Deadlock while rotating logs

### LINKED ISSUE #2920: qTox "Not responding" after update on OS X version 10.11.3
Application cannot start after Mac was updated to OS 10.11.3

qTox was installed from `qTox-OSX-1.2.4.307.dmg`

### PR DESCRIPTION
**Pull request by sudden6**
based on #2974
fixes #2920

### CODE REVIEW

**Comment by zetok** [comment]
No idea whether it's due to this PR, but logs are malformed:

```
[New LWP 7889]
[17:29:07.566] src/persistence/settings.cpp:121 : Debug: [17:29:07.566] src/ipc.cpp:46 : Debug: Ou[17:29:07.566] src/ipc.cpp:64 : Debug: [17:29:07.567] src/main.cpp:159 : Debug: bui[17:29:07.567] src/main.cpp:160 : Debug: commit[17:29:07.567] src/ipc.cpp:125 : Debug[17:29:09.001] src/persistence/profile.cpp:86 : Debug[17:29:09.001] src/persistence/settings.cpp:371 : Debug: "S[New LWP 7939]
[New LWP 7940]
[17:29:09.045] src/persistence/settings.cpp:296 : Debug: Load[17:29:09.045] src/nexus.cp[New LWP 7941]
[New LWP 7987]
[17:29:09.689] src/core/core.cpp:2[17:29:09.689] src/persistence/profile.cpp:249 : Debug[17:29:09.689] src/core/core.cpp:132 : [New LWP 7988]
[17:29:11.365] src/widget/systemtrayico[New LWP 8039]
[17:29:12.731] src/core/core.cpp:407 : Debug: "[17:29:12.731] src/core/core.cpp:407 : Debug: [17:29:17.231] src/core/core.cpp:407 : Debug: [17:29:17.232] src/core/core.cpp:407 : Debug: "[17:29:21.731] src/core/core.cpp:407 : Debug: "Con[17:29:21.731] src/core/core.cpp:407 : Debug: "C[17:29:23.494] src/core/core.cpp:3[17:29:23.494] src/persistence/profile.cpp:314 : Debug:[LWP 7941 exited]
```

**Comment by sudden6** [comment]
@zetok I hope this fixes all deadlocks and segfaults in the logging code once and for all.
I may have gone overboard with using QAtomicPointer, but I had no idea how to solve this differently.

**Comment by zetok** [comment]
on 525d865b13ae6e5523078dc399507a479a56f1f5 logs seem to be ok

**Comment by sudden6** [comment]
in master now, thus closing

**Pull request closed without merging**
