### PR TITLE
feat(l10n): update Bulgarian translation

### PR DESCRIPTION
**Pull request by wDraw**

### CODE REVIEW

**Comment by zetok** [comment]
Could you clean up translation file according to the instructions on wiki & amend?

Thanks for translating qTox btw :)

**Comment by wDraw** [comment]
Forgot, sorry.

**Comment by zetok** [comment]
Oh, wait, it's not squashed?

**Comment by wDraw** [comment]
Is it a big problem?

**Comment by zetok** [comment]
Not a big problem per se – it's a matter of not including in PR stuff that is not needed, and only inflates repo size.

Unnecessary inflation is not a good thing :)

**Comment by wDraw** [comment]
Okay, I'll try to squash them.

**Comment by wDraw** [comment]
Done.

**Pull request merged**
