### PR TITLE
Change '.com' to '.tld'

### PR DESCRIPTION
**Pull request by ovalseven8**

### CODE REVIEW

**Comment by tux3** [comment]
I don't know, does this make it any clearer to the user what we mean?

**Comment by ProMcTagonist** [comment]
No.

**Comment by ovalseven8** [comment]
The PR makes the string more general. At the moment at first view it seems like you can only use .com domains.

**Comment by zetok** [comment]
> The PR makes the string more general.

If the users knew what `.tld` means, that would be true. Check, it doesn't even make more sense to me.

On the other hand, `.com` is something that is an ~equivalent for the users to `.tld`…

**Comment by ProMcTagonist** [comment]
Most users will not know what .tld means, whereas .com is obvious to everyone. No one is going to think it's somehow restricted to .com.

Zero gain, active damage, PR is harmful, close.

**Comment by subliun** [comment]
it should be changed to example.com as per http://www.iana.org/domains/reserved

**Comment by zetok** [comment]
> it should be changed to example.com as per http://www.iana.org/domains/reserved

Yeah - @ovalseven8 mind making PR with that change? `:)`

**Pull request closed without merging**
