### PR TITLE
Refactor toxencrypt2

### PR DESCRIPTION
**Pull request by sudden6**
This PR builds on #4131 and #4130 to switch all code parts from coreencryption.cpp to ToxEncrypt.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4132)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/persistence/profile.cpp, line 172 at r1](https://reviewable.io:443/reviews/qtox/qtox/4132#-KcK9915b3m8kTTUp6ij:-KcK9915b3m8kTTUp6ik:b-8ze7hy) ([raw file](https://github.com/qtox/qtox/blob/ca024951d56ec62fce047ecd5255a544f28ebe4c/src/persistence/profile.cpp#L172)):*
> ```cpp
> {
>     std::unique_ptr<ToxEncrypt> tmpKey;
>     if(!password.isEmpty())
> ```

Use early break.

---

*[src/persistence/profile.cpp, line 200 at r1](https://reviewable.io:443/reviews/qtox/qtox/4132#-KcK96PS8n8rkwfGjdGs:-KcK96PS8n8rkwfGjdGt:b-qhlwyf) ([raw file](https://github.com/qtox/qtox/blob/ca024951d56ec62fce047ecd5255a544f28ebe4c/src/persistence/profile.cpp#L200)):*
> ```cpp
>     }
> ```

Extra new line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4132#-:-KcK9t_BMhjHeS_N0FNE:b-jbsf8z)*

**Comment by Diadlo** [comment]
:lgtm_cancel: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4132#-:-KcK9yy_JIZNl_ZGNpN6:b8b79qu)*

**Comment by sudden6** [comment]
Review status: 5 of 21 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/persistence/profile.cpp, line 172 at r1](https://reviewable.io:443/reviews/qtox/qtox/4132#-KcK9915b3m8kTTUp6ij:-KcOwfQ4ksb52XMYFDbl:blgl12v) ([raw file](https://github.com/qtox/qtox/blob/ca024951d56ec62fce047ecd5255a544f28ebe4c/src/persistence/profile.cpp#L172)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Use early break.
</blockquote></details>

I don't know what you mean here.

---

*[src/persistence/profile.cpp, line 200 at r1](https://reviewable.io:443/reviews/qtox/qtox/4132#-KcK96PS8n8rkwfGjdGs:-KcOwi6n_UuB04H68oKf:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/ca024951d56ec62fce047ecd5255a544f28ebe4c/src/persistence/profile.cpp#L200)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Extra new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4132)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 16 of 16 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4132#-:-KcPCfVWVBlTuJ9Jm8a9:b-jbsf8z)*

**Pull request merged**
