### PR TITLE
refactor(messages): don't use receipt 0 as unsent, simplify class state

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5539)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5539)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/offlinemsgengine.cpp, line 39 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV3c3tBHZ7YP3T8kRh:-LXV3c3tBHZ7YP3T8kRi:b-2qyohq) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L39)):*
> ```cpp
> {
>     QMutexLocker ml(&mutex);
>     assert(!receivedReceipts.contains(receipt));
> ```

Do you know that it's guaranteed to receive a receipt exactly once? If not, I think we should replace this with a warning message and return.
___
*[src/persistence/offlinemsgengine.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV4AWxE2bsGM71Df1A:-LXV4AWxE2bsGM71Df1B:b-x0b5d6) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L50)):*
> ```cpp
> }
> 
> void OfflineMsgEngine::addSentSavedMessage(ReceiptNum receipt, RowId messageID, ChatMessage::Ptr chatMessage)
> ```

doxygen? I don't really understand the purpose from just the name of the method
___
*[src/persistence/offlinemsgengine.cpp, line 62 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV5HFN8bo7tCwVwwrz:-LXV5HFN8bo7tCwVwws-:b-qldhs6) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L62)):*
> ```cpp
>     QMutexLocker ml(&mutex);
> 
>     if (!Settings::getInstance().getFauxOfflineMessaging())
> ```

braces for the following iffs
___
*[src/persistence/offlinemsgengine.cpp, line 71 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV5XVu91ezUD1IH6Rm:-LXV5XVu91ezUD1IH6Rn:b-gao8yf) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L71)):*
> ```cpp
>         return;
> 
>     QVector<Message> messages = sentSavedMessages.values().toVector() + unsentSavedMessages;
> ```

will `toVector()` somehow preserver the order of the messages? or how is the correct order ensured?

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5539)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/offlinemsgengine.cpp, line 39 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV3c3tBHZ7YP3T8kRh:-LaX5fAn1DLuiH9PWmXX:b6aljtr) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L39)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Do you know that it's guaranteed to receive a receipt exactly once? If not, I think we should replace this with a warning message and return.
</blockquote></details>

I don't see an API restriction that receipt callback is only called once, changed to warning.
___
*[src/persistence/offlinemsgengine.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV4AWxE2bsGM71Df1A:-LaXIVkYC0CSBn3gsrrq:bbbmsco) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L50)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

doxygen? I don't really understand the purpose from just the name of the method
</blockquote></details>

Added doxygen to all public API.
___
*[src/persistence/offlinemsgengine.cpp, line 62 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV5HFN8bo7tCwVwwrz:-LaXIeno8TE7LRBwlW33:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L62)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

braces for the following iffs
</blockquote></details>

Done.
___
*[src/persistence/offlinemsgengine.cpp, line 71 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV5XVu91ezUD1IH6Rm:-LaXIkBu2pi-Psp_x9VL:bjm5nbt) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L71)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

will `toVector()` somehow preserver the order of the messages? or how is the correct order ensured?
</blockquote></details>

Bug, good catch. Sorting by rel time of authorship seems easier and more clear than trying to send both sent and unsent messages in the same structure and still have them quickly randomly accessible by receipt number.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5539)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/offlinemsgengine.cpp, line 39 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV3c3tBHZ7YP3T8kRh:-Law0zNX04sgXuIr4y96:b-3lwkp6) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L39)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

I don't see an API restriction that receipt callback is only called once, changed to warning.
</blockquote></details>

Did you also mean to return from the function?
___
*[src/persistence/offlinemsgengine.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV4AWxE2bsGM71Df1A:-Law1aA_CO6yXd0eVQHL:bjk371o) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L50)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Added doxygen to all public API.
</blockquote></details>

The rest of the qTox doc is directly in the source file, I'd ask you to do the same.

**Comment by sudden6** [comment]
There seems to be a mistake in the code: https://travis-ci.org/qTox/qTox/jobs/511709414#L2710

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5539)* status: 0 of 1 LGTMs obtained

___
*[src/persistence/offlinemsgengine.cpp, line 39 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV3c3tBHZ7YP3T8kRh:-Lax--gq936blcNnwPg0:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L39)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Did you also mean to return from the function?
</blockquote></details>

Done.
___
*[src/persistence/offlinemsgengine.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV4AWxE2bsGM71Df1A:-Lax-FJi0f-H_qDPWITg:b-92yq82) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L50)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

The rest of the qTox doc is directly in the source file, I'd ask you to do the same.
</blockquote></details>

FWIW I think documenting the params and purpose of the function in the header where the API of the class is declared instead of in the source file where the implementation is defined makes more sense, but for the purpose of consistency, done.

**Comment by sudden6** [comment]
___
*[src/persistence/offlinemsgengine.cpp, line 50 at r1](https://reviewable.io/reviews/qtox/qtox/5539#-LXV4AWxE2bsGM71Df1A:-LaxqUTFBqQK53c_dClr:b-v4mm44) ([raw file](https://github.com/qtox/qtox/blob/1069a04093719f3473096ab281606e2ea6bc04f4/src/persistence/offlinemsgengine.cpp#L50)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

FWIW I think documenting the params and purpose of the function in the header where the API of the class is declared instead of in the source file where the implementation is defined makes more sense, but for the purpose of consistency, done.
</blockquote></details>

I agree with that, but a more coordinated effort to change that is better. Needs also a coding style change.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5539#-:-Laxr5AJ2IFZ0JyOtPf1:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
