### PR TITLE
Smileys

### PR DESCRIPTION
**Pull request by krepa098**
A default set of smileys. This should fix issue #172.

### CODE REVIEW

**Comment by tux3** [comment]
Are you sure it's okay to overwrite the copyright ?
Did you ask nurupo ? He might sue us.
Note that I don't know the first thing about licenses and copyrights.

**Comment by dubslow** [comment]
Those two files were written exclusively by him; he merely copied the wrong header from other files. Here he corrected it to the right header.

(That is to say, nurupo never had anything to do with these particular files.)

**Comment by krepa098** [comment]
Exactly. I just copied the wrong header by mistake.

**Comment by tux3** [comment]
My bad !
All is well.

**Pull request merged**
