### PR TITLE
"Green text" sucks

### PR DESCRIPTION
**Pull request by stqism**
please merge

### CODE REVIEW

**Comment by mindcombatant** [comment]
yes, please remove greentext. or at least make it a setting that defaults to "off" for new users.

**Comment by stqism** [comment]
So so much, the majority of our users do not know what "green text" is and only get frustrated when they attempt to legitimately use > for other normal reasons like emoticons and are prevented from doing so.

**Comment by mindcombatant** [comment]
agreed with stqism, some people may be scared off by it even.

**Comment by ProMcTagonist** [comment]
> are prevented from doing so.

What?

**Comment by DanTheBritish** [comment]
f7feb8ecbb621511a36cb909e4e0bad9f847dfb7 is a good middle ground, means that emoticons are not affected and a leading space will not greentext.

**Comment by zetok** [comment]
this PR should be closed

**Comment by tux3** [comment]
I also think it should be closed, https://github.com/tux3/qTox/commit/f7feb8ecbb621511a36cb909e4e0bad9f847dfb7 solves most of the problems. And it's not that unusual for >quotes to be colored.

@dubslow you wanted to close it too, iirc ?

**Comment by stqism** [comment]
@dubslow Reopen it please, "green text" doesn't actually suck any less even if it's not annoying anymore.

**Comment by dubslow** [comment]
Well it's not getting merged

**Comment by zetok** [comment]
why then re-opening it?

**Comment by tux3** [comment]
@zetok To keep discussion open and visible, at least.
But at this point I don't think this PR is going anywhere.

**Comment by stqism** [comment]
@zetok because censoring opinions that disagree with your own speaks poorly on the project.

**Comment by dubslow** [comment]
Closing it would hardly be censoring :P

**Comment by ProMcTagonist** [comment]
Greentext doesn't affect emoticons. It doesn't affect the position or layout or behavior of anything. It just makes things green. What are you talking about, @stqism? 

You were in favor of shitposting issues being ignored a few days ago.

**Comment by tux3** [comment]
There doesn't seem to be any progress, and this PR doesn't merge cleanly against master. Closing for now.

**Pull request closed without merging**
