### PR TITLE
Friend request form: Fix crashes by rejecting multiple requests from same person

### PR DESCRIPTION
**Pull request by TheSpiritXIII**

### CODE REVIEW

**Comment by zetok** [comment]
Segfaults.
- [ ] regression - segfault when copying ID
  
  Steps to reproduce:
  1. Reject received FR
  2. Go to profile and click on ID to copy it
  3. segfault: https://gist.github.com/zetok/4ee1fe94ea005f33c687

**Comment by zetok** [comment]
- [ ] regression - segfault when trying to log out of profile after rejecting FR: https://gist.github.com/zetok/9ff0ab61c4098b535bb8

**Comment by zetok** [comment]
Note: when this gets fixed, it will require 06611d618e4306b2402717bc4a62d505b0a77200 to be reverted before merging.

**Comment by agilob** [comment]
I know how to fix the crash, had the same problem yesterday in about window.Will you have time to test it with me @zetok ?

**Comment by zetok** [comment]
@agilob I most likely will have time in the next 3 days (and what is left out of this one), unless something unexpected pops up :)

**Comment by zetok** [comment]
#2978 renders this PR obsolete, thus closing.

**Pull request closed without merging**
