### PR TITLE
Add libexif to the Windows cross-compilation

### LINKED ISSUE #4672: Windows cross-compilation fails due to missing libexif
Probably related to https://github.com/qTox/qTox/pull/4643. Will work on fixing it a bit later.

Also, It might be worth figuring out how to make Travis run the cross-compilation build, this issue should ideally have been fixed in the PR that introduceed it.

```
-- Checking for one of the modules 'libexif'
CMake Error at cmake/Dependencies.cmake:71 (message):
  LIBEXIF package, library or framework not found
Call Stack (most recent call first):
  cmake/Dependencies.cmake:99 (search_dependency)
  CMakeLists.txt:80 (include)
```

### PR DESCRIPTION
**Pull request by nurupo**
Fixes #4672.

I have also added some sha256 checking, was a bit lazy to open a separate PR for it.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4676)

### CODE REVIEW

**Comment by nurupo** [comment]
Want to add one more offtopic commit (update toxcore and Qt versions), so don't merge yet.

**Comment by nurupo** [comment]
That's it, the PR should be good to go.

**Comment by sudden6** [comment]
The commit message `feat(build): Check sha256 of all tarballs we download for Windows cross-compilation` is probably too long and fails the check

**Comment by sudden6** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4676)*

**Comment by nurupo** [comment]
How about now?

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4676#-:-KudV1hLZ5-ZH_6wOZtW:b-jbsf8z)*

**Pull request merged**
