### PR TITLE
Anonymize query

### LINKED ISSUE #3399: Confidential info from database is printed in stdout
##### Brief Description

OS: PC-BSD
qTox version: 1.4 (installed with `pkg` not from sources this time)
Commit hash:  NA
toxcore:  0.0.0
Qt:  5.5.1
Hardware:  
…

Reproducible: Always
##### Steps to reproduce
1. I just turn on qTox from terminal
##### Observed Behavior

I get this log on each start of qtox for each of my contacts:

```
[20:11:15.865] src/persistence/db/rawdatabase.cpp:374 : Warning: Failed to prepare statement 
"SELECT history.id, faux_offline_pending.id, timestamp, chat.public_key, aliases.display_name, 
sender.public_key, message FROM history LEFT JOIN faux_offline_pending ON history.id = 
faux_offline_pending.id JOIN peers chat ON chat_id = chat.id JOIN aliases ON sender_alias = 
aliases.id JOIN peers sender ON aliases.owner = sender.id WHERE timestamp BETWEEN 
146541300000 AND 14660000000 AND 
chat.public_key='PUBLIC KEY WAS HERE';" with error 26

...
a bit later:
...
[20:13:07.881] src/persistence/db/rawdatabase.cpp:374 : Warning: Failed to prepare statement "INSERT INTO peers (id, public_key) VALUES (1, 'PUBLIC KEY WAS HERE');" with error 26

```
##### Expected Behavior

public_key and time stamps should not be exposed in log.

### PR DESCRIPTION
**Pull request by Diadlo**
Added anonymizing SQL query in logs

Fixed #3399.

---

This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3704)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

_[src/persistence/db/rawdatabase.cpp, line 543 at r1](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRWzfwH4dKG0xhC8Opy:-KRWzfwIiMg_NtHAtwMl:b-yw8xky) ([raw file](https://github.com/qtox/qtox/blob/9d653129395c9d9e330339fe735b616546e2cbff/src/persistence/db/rawdatabase.cpp#L543)):_

> ``` cpp
>                     continue;
> 
>                 QString query = anonymizeQuery(query.query);
> ```

Compile fails here, probably because of the duplicate variable name `query`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/persistence/db/rawdatabase.cpp, line 543 at r1](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRWzfwH4dKG0xhC8Opy:-KRXUhA8V3IQqQxEm_49:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/9d653129395c9d9e330339fe735b616546e2cbff/src/persistence/db/rawdatabase.cpp#L543)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Compile fails here, probably because of the duplicate variable name `query`.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by zetok** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/persistence/db/rawdatabase.cpp, line 591 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYWQdNVf4IBdPA0__G:-KRYWQdNVf4IBdPA0__H:b-a2ofql) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L591)):_

> ``` cpp
> {
>     QString queryString(query);
>     queryString.replace(QRegExp("chat.public_key='[A-Z0-9]{64}'"),
> ```

`s/A-Z/A-F/`

---

_[src/persistence/db/rawdatabase.cpp, line 593 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYW_8sX75cMndxR_qf:-KRYW_8sX75cMndxR_qg:by7pt9a) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L593)):_

> ``` cpp
>     queryString.replace(QRegExp("chat.public_key='[A-Z0-9]{64}'"),
>                         "char.public_key='<HERE IS PUBLIC KEY>'");
>     queryString.replace(QRegExp("timestamp BETWEEN [0-9]{1,} AND [0-9]{1,}"),
> ```

Can timestamp really have only one digit?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/persistence/db/rawdatabase.cpp, line 591 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYWQdNVf4IBdPA0__G:-KRYbglVH5JR7d_YITFF:bmhvsjg) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L591)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `s/A-Z/A-F/`
> </details>
> Does it really matter?

---

_[src/persistence/db/rawdatabase.cpp, line 593 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYW_8sX75cMndxR_qf:-KRYbikSdO0r5XC-NSLX:b5aaqq) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L593)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Can timestamp really have only one digit?
> </details>
> I don't know. But 1+ symbols is correct solution

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

_[src/persistence/db/rawdatabase.cpp, line 591 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYWQdNVf4IBdPA0__G:-KRYzfgXC47sXqZLFNPp:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L591)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Does it really matter?
> </details>
> Done.

---

_[src/persistence/db/rawdatabase.cpp, line 593 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYW_8sX75cMndxR_qf:-KRYzfU0bK3XJjyuIVUk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L593)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> I don't know. But 1+ symbols is correct solution
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by antis81** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/persistence/db/rawdatabase.cpp, line 591 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYWQdNVf4IBdPA0__G:-KRZGDEK1RJje2ic-dFz:bmvqqe7) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L591)):_
<details><summary>

<i>Previously, Diadlo (Diadlo) wrote…</i></summary>



> Done.
> </details>
> Please stop using QRegExp and use QRegularExpression instead. We could probably ad a "RegEx" typedef somewhere (e.g. Core header) to make it a little more attractive.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by Diadlo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

_[src/persistence/db/rawdatabase.cpp, line 591 at r2](https://reviewable.io:443/reviews/qtox/qtox/3704#-KRYWQdNVf4IBdPA0__G:-KRZtxXhdGnVSL2et3OX:b-fxmlqn) ([raw file](https://github.com/qtox/qtox/blob/7258eec0862b04e23560c0a88a2a1aa5d2a69b50/src/persistence/db/rawdatabase.cpp#L591)):_
<details><summary>

<i>Previously, antis81 (Nils Fenner) wrote…</i></summary>



> Please stop using QRegExp and use QRegularExpression instead. We could probably ad a "RegEx" typedef somewhere (e.g. Core header) to make it a little more attractive.
> </details>
> Thanks, I will know :)
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by Diadlo** [comment]
@sudden6 @antis81 Anybody LGTM?

**Comment by antis81** [comment]
To be honest, these code changes are introducing no value nor do they fix/improve something. So… i cannot give a lgtm.

If you ask for opinion, rather remove those log entries completely or probably just log the line in code, stating `qWarning("Query failed in %s:L%d", __FILE__, __LINE__");` without exposing the query at all. This is already done in logging anyway. And why those changes to the `if … else if… else" blocks instead of "switch" statement? Those have nothing to do with this PR and produce a static analyzer warning. In general don't use "default" in a switch statement and either a) handle all possible values or b) use  "if … else if … else".

**Comment by Diadlo** [comment]
@antis81 If you think, that hide PK and timestamp it's not problem, which should be fixed write about it in #3399
Why you think, that undetailed message better than anonymize query?
What problem with `default` case? It exist before like `result != SQLITE_DONE`

> produce a static analyzer warning

What warning it produce?

**Comment by antis81** [comment]
> Why you think, that undetailed message better than anonymize query?

Because it carries redundant and misleading information when analyzing a possible bug. What you want to know, when something fails is: revision, file and line.

There's two possible reasons:
1. The query always fails -> coding error -> does not happen in a stable release!
2. The parameters are wrong by user, in which case we get the details immediately.

> What warning it produce?

--> `covered-switch-default`

**Comment by Diadlo** [comment]
@antis81 It maybe problem with database file or something else. I think reason of errors in agilob's log it's not one of your two reason

**Comment by sudden6** [comment]
@antis81 I agree with @Diadlo that it helps debugging problems. qTox has grown big enough that errors are only reproducible by some users and in these cases a detailed enough log file helps enormously.

@Diadlo I didn't LGTM, because antis81 seemed like he was still in a discussion with you and I wanted to avoid the PR being closed before he could voice his opinion.

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704)_

**Comment by antis81** [comment]
I really don't care about debuggers or log files, not using those -> go ahead.

**Comment by Diadlo** [comment]
@antis81 So lgtm?

**Comment by sudden6** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3704#-:-KSCmYMpJwkmmUIf7o8c:bnfp4nl)_

**Pull request merged**
