### PR TITLE
docs: update MAINTAINING.md with new rules for taggin issues

### PR DESCRIPTION
**Pull request by sudden6**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5780)

### CODE REVIEW

**Review by Kribylet — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5780)* status: 0 of 1 LGTMs obtained

**Review by Kribylet — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5780#-:-LmELJjEEFYY2RjDYRG2:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5780)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[MAINTAINING.md, line 106 at r2](https://reviewable.io/reviews/qtox/qtox/5780#-LmHSHUt-_NpaiKHAyJ4:-LmHSHUt-_NpaiKHAyJ5:box5p4j) ([raw file](https://github.com/qtox/qtox/blob/02361093a9cebd1427a11f541f61e0166ca915d7/MAINTAINING.md#L106)):*
> ```Markdown
> ### User impact
> 
> We have two labels to rate user impact `U-high` and `U-low`.
> ```

we currently still have 3 levels of both U and D. Are you intending to change that to just 2 of each - or are we keeping the "medium" level of each as well?

**Comment by sudden6** [comment]
I intended it to change to only two levels.

**Pull request merged**
