### PR TITLE
Refactor SmileyPack

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4322)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/persistence/smileypack.cpp, line 140 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhETYegl_IY3QugFJfO:-KhETYegl_IY3QugFJfP:b-nexk59) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L140)):*
> ```cpp
> QVector<QPair<QString, QString>> SmileyPack::listSmileyPacks(const QStringList& paths)
> {
>     QVector<QPair<QString, QString>> smileyPacks;
> ```

I think `QList` is better here

---

*[src/persistence/smileypack.cpp, line 141 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhES3S7jsIudgYVHwh3:-KhES3S7jsIudgYVHwh4:b7olx7s) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L141)):*
> ```cpp
> {
>     QVector<QPair<QString, QString>> smileyPacks;
>     const QString fileName = QStringLiteral("emoticons.xml");
> ```

What about move it out of the method?

---

*[src/persistence/smileypack.cpp, line 210 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhESR1VtXc27yfxilGx:-KhESR1VtXc27yfxilGy:b-yl5ymo) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L210)):*
> ```cpp
>     emoticonToIcon.clear();
>     icons.clear();
>     const int iconsCount = emoticonElements.size();
> ```

Can you place this line after `const QString ...` ? (just to group consts)

---

*[src/persistence/smileypack.cpp, line 213 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhESfjlZ2DFP8YGpzC3:-KhESfjlZ2DFP8YGpzC4:b-6eyj5o) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L213)):*
> ```cpp
>     icons.reserve(iconsCount);
>     for (int i = 0; i < iconsCount; ++i) {
>         QString iconName = emoticonElements.at(i).attributes().namedItem(itemName).nodeValue();
> ```

What about extract `emoticonElements.at(i)`? It used twise

---

*[src/persistence/smileypack.h, line 51 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhEVVmeAWVqOnbr7zZW:-KhEVVmeAWVqOnbr7zZX:bay1gsj) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.h#L51)):*
> ```objc
> 
>     QVector<QIcon> icons;
>     QMap<QString, QIcon const*> emoticonToIcon;
> ```

What about `const QIcon const *`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4322)*

**Comment by noavarice** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/persistence/smileypack.cpp, line 140 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhETYegl_IY3QugFJfO:-Khfil6AsQ1FZPLCw7qB:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L140)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

I think `QList` is better here
</blockquote></details>

Done.

---

*[src/persistence/smileypack.cpp, line 141 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhES3S7jsIudgYVHwh3:-KhfilZaHIy7YNzQl6rJ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L141)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about move it out of the method?
</blockquote></details>

Done.

---

*[src/persistence/smileypack.cpp, line 210 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhESR1VtXc27yfxilGx:-Khfim_jPupob3gnXJBU:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L210)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Can you place this line after `const QString ...` ? (just to group consts)
</blockquote></details>

Done.

---

*[src/persistence/smileypack.cpp, line 213 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhESfjlZ2DFP8YGpzC3:-KhfinYV8Bn-QsVNut0B:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.cpp#L213)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about extract `emoticonElements.at(i)`? It used twise
</blockquote></details>

Done.

---

*[src/persistence/smileypack.h, line 51 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhEVVmeAWVqOnbr7zZW:-KhfiohvVpt2ZJetU16a:boxbj2j) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.h#L51)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about `const QIcon const *`?
</blockquote></details>

Compiler complains so I leave it as now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4322)*

**Comment by Diadlo** [comment]
Reviewed 1 of 3 files at r6, 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.h, line 51 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhEVVmeAWVqOnbr7zZW:-Khg4z32_0WBijO-In2v:b1gbt9z) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.h#L51)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Compiler complains so I leave it as now
</blockquote></details>

Сomplains on what?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4322)*

**Comment by Diadlo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/persistence/smileypack.h, line 51 at r4](https://reviewable.io:443/reviews/qtox/qtox/4322#-KhEVVmeAWVqOnbr7zZW:-Khg7rfv99Ih672rwvh9:b-9ne3h0) ([raw file](https://github.com/qtox/qtox/blob/8ecab407d335b77e941f1f039c295a8a0f99cd09/src/persistence/smileypack.h#L51)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Сomplains on what?
</blockquote></details>

Sorry, `const QIcon* const`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4322)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4322#-:-KhxvS9ucZ7BZUE-EOY3:b-jbsf8z)*

**Pull request merged**
