### PR TITLE
chore(release): Update release instructions to reflect current procedure

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6264)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6264)* status: 0 of 1 LGTMs obtained

___
*[MAINTAINING.md, line 239 at r1](https://reviewable.io/reviews/qtox/qtox/6264#-MN02gF72UjS4HYTuN-C:-MN02gF72UjS4HYTuN-D:bt6dmbo) ([raw file](https://github.com/qtox/qtox/blob/3661cb1a3321913082d0a7bd115f0859ff5b5a2d/MAINTAINING.md#L239)):*
> ```Markdown
>   release job.
> - Download the binaries that are part of the draft release, sign them in
>   in detached and ascii armored mode, i.e. `-a -b`, and upload the signatures to
> ```

If you already give the example switches, the full command ready for copy&past would be good.
___
*[MAINTAINING.md, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/6264#-MN02tQA34-qZf8d1m2q:-MN02tQB1aVg12qz1seC:b71d1w8) ([raw file](https://github.com/qtox/qtox/blob/3661cb1a3321913082d0a7bd115f0859ff5b5a2d/MAINTAINING.md#L245)):*
> ```Markdown
> - Write a short blog post for https://github.com/qTox/blog/ and advertise the
>   post on Tox IRC channels, popular Tox groups, reddit, or whatever other platforms.
> - Modify the flatpak manifest created before tag to replace the qTox path back
> ```

I don't understand what you want to tell with this point. I think you want to say something like "merge  [`./flatpak/io.github.qtox.qTox.json`] back into the upstream flatpak manifest"?

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6264)* status: 0 of 1 LGTMs obtained

___
*[MAINTAINING.md, line 239 at r1](https://reviewable.io/reviews/qtox/qtox/6264#-MN02gF72UjS4HYTuN-C:-MN27ivn4L6lEFeOGeT7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/3661cb1a3321913082d0a7bd115f0859ff5b5a2d/MAINTAINING.md#L239)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

If you already give the example switches, the full command ready for copy&past would be good.
</blockquote></details>

Done.
___
*[MAINTAINING.md, line 245 at r1](https://reviewable.io/reviews/qtox/qtox/6264#-MN02tQA34-qZf8d1m2q:-MN27jVG1DqbyOCA8fyO:b-896fig) ([raw file](https://github.com/qtox/qtox/blob/3661cb1a3321913082d0a7bd115f0859ff5b5a2d/MAINTAINING.md#L245)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I don't understand what you want to tell with this point. I think you want to say something like "merge  [`./flatpak/io.github.qtox.qTox.json`] back into the upstream flatpak manifest"?
</blockquote></details>

Done?

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6264#-:-MN2yFMt7aNqRyWbPli7:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
Updated again even though it was approved. Changes:
* manifest in qTox repo always just uses path. It never needs to specify a tag or a branch, because if it's being read at that tag or branch in the repo, the directory will also have that tag or branch checked out.
* flathub just always has latest tag like before.
* this removes the need to update qTox's manifest again after releasing.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6264#-:-MN36dk38ybPLwyC1okh:bucpuyr)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6264)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[MAINTAINING.md, line 248 at r3](https://reviewable.io/reviews/qtox/qtox/6264#-MN3Ca6Y4rod8fLQT4y1:-MN3Ca6Z89PkQi2qWWun:b-85dux4) ([raw file](https://github.com/qtox/qtox/blob/10d2e9603b1066616585e076f94b40904dc535ae/MAINTAINING.md#L248)):*
> ```Markdown
>   [Flathub repository]. Keep the [Flathub repository]'s version of "sources" for
>   qTox.
> - Comment to the PR with `bot, build` to execute a test build
> ```

Removed because my latest PR automatically started a build both when opened, and when updated. Commenting `bot, build` cause a double-build by the bot.

**Review by sudden6 — APPROVED** [review]
now it's 100% clear :lgtm_strong: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6264#-:-MN3zubZ7n3H1qE57KK3:b-q4ysp9)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
