### PR TITLE
feat(audio): split the audio interface from the backend library

### PR DESCRIPTION
**Pull request by sudden6**
This paves the way to support multiple audio backends

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4332)

### CODE REVIEW

**Comment by sudden6** [comment]
I just noticed that this breaks audio because no signals are emitted an received from the backend, any ideas why this happens?

**Comment by sudden6** [comment]
Found the problem thanks to Diadlo

**Comment by sudden6** [comment]
@Diadlo ping

**Comment by Diadlo** [comment]
@sudden6 Pong. As I said before. I think we should start with replacing singleton on DI
But because lately I haven't time, I will paste `LGTM`. If you think that it's "the right way". Feel free to merge. 
@zetok Can you test?
@noavarice Can you review it?

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4332#-:-Kj9cEt1I8qAQbOOKm6M:b-jbsf8z)*

**Pull request merged**
