### PR TITLE
Local bootstrap list

### LINKED ISSUE #5767: Have user editable bootstrap nodelist
When the bootstrap nodes list was stored in the .ini file, it was easily visible and editable by users. Now that it's stored in the json file as provided by nodes.tox.chat, it's still in an easy to edit json format, but is packaged inside the binary, making it near impossible for users to manually edit.

It would be good for the bootstrap list to stay as an external editable config file, so that users can easily create custom private DHTs, view the list, and quickly adds nodes in case of outages / blocks without having to wait for a release.

### PR DESCRIPTION
**Pull request by anthonybilinski**
- [x] Commits follow our [git commit guidelines](https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#git-commit-guidelines)

Fix #5767

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/6126)

### CODE REVIEW

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126)* status: 0 of 1 LGTMs obtained

___
*[src/core/dhtserver.cpp, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/6126#-M6LcGt6-OSRiY04kXMd:-M6LcGt6-OSRiY04kXMe:b-2e7ukt) ([raw file](https://github.com/qtox/qtox/blob/045f289ca50f98072404231646789f8f2000e07d/src/core/dhtserver.cpp#L29)):*
> ```cpp
> bool DhtServer::operator==(const DhtServer& other) const
> {
>     bool statusUdp;
> ```

This comparison operator now doesn't really make sense to me. Now you're comparing default initialized variables to the other Object?
___
*[src/net/bootstrapnodeupdater.h, line 10 at r1](https://reviewable.io/reviews/qtox/qtox/6126#-M6LcetD3R6gCliMWj0G:-M6LcetD3R6gCliMWj0H:b-w9tsfh) ([raw file](https://github.com/qtox/qtox/blob/045f289ca50f98072404231646789f8f2000e07d/src/net/bootstrapnodeupdater.h#L10)):*
> ```objc
> 
> #include "src/core/dhtserver.h"
> #include "src/net/ibootstraplistgenerator.h"
> ```

IMO that interface should be in `src/core` since `Core needs this`

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126)* status: 0 of 1 LGTMs obtained

___
*[src/core/dhtserver.cpp, line 29 at r1](https://reviewable.io/reviews/qtox/qtox/6126#-M6LcGt6-OSRiY04kXMd:-M6Lwfj31T8gwr-OePAn:b-nko7tu) ([raw file](https://github.com/qtox/qtox/blob/045f289ca50f98072404231646789f8f2000e07d/src/core/dhtserver.cpp#L29)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This comparison operator now doesn't really make sense to me. Now you're comparing default initialized variables to the other Object?
</blockquote></details>

Bug, I just copy pasted the members in to list them all :facepalm: Removed.
___
*[src/net/bootstrapnodeupdater.h, line 10 at r1](https://reviewable.io/reviews/qtox/qtox/6126#-M6LcetD3R6gCliMWj0G:-M6M0uIB0pu7yBbeRo95:b-t31xns) ([raw file](https://github.com/qtox/qtox/blob/045f289ca50f98072404231646789f8f2000e07d/src/net/bootstrapnodeupdater.h#L10)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

IMO that interface should be in `src/core` since `Core needs this`
</blockquote></details>

I agreed `net` doesn't make sense, I've moved it to `model` rather than `core`

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 5 of 24 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126#-:-M6MBOqIDpP8BhwPARet:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by sphaerophoria — COMMENTED** [review]
I might be misusing the feature, but something doesn't seem right to me? If I change ~/.config/tox/bootstrapNodes.json to

```
{
    "nodes": [
        {
            "ipv4": "127.0.0.1",
            "ipv6": "",
            "maintainer": "sphaerophoria",
            "port": 33445,
            "public_key": "41076B90F4C0869D98F126C551D411C6176CCEC68A7CEF97D55A8C5C63885244",
            "status_tcp": true,
            "status_udp": true
        }
    ]
}
```

I still see the following logs
```
[20:07:38.770 UTC] core/core.cpp:807 : Debug: Connecting to bootstrap node 13
[20:07:38.772 UTC] core/core.cpp:807 : Debug: Connecting to bootstrap node 14
[20:07:43.270 UTC] core/core.cpp:807 : Debug: Connecting to bootstrap node 15
[20:07:43.273 UTC] core/core.cpp:807 : Debug: Connecting to bootstrap node 16
```

but shouldn't there only be one bootstrap node in the list?

Also if I remove some of the required fields from the list I see no indication that anything has failed. Am I using it wrong?

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126#-:-M6R8SnsADcxFTD4fup6:b-jxyyp1)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 810 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R4wsQD0FJn_6NSNWS:-M6R4wsQD0FJn_6NSNWT:bd18p6i) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/core/core.cpp#L810)):*
> ```cpp
> 
>         QByteArray address;
>         if (dhtServer.ipv4.isEmpty() && !dhtServer.ipv6.isEmpty()) {
> ```

Should we ensure that only one of these is set in the bootstrap loader? That way we could just use ipv6 if it's valid, otherwise use ipv4.

Also that would ensure we don't try to pass in an empty address to tox_bootstrap
___
*[src/net/bootstrapnodeupdater.cpp, line 67 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R4Qp_2JtcErlAy3W1:-M6R4Qp_2JtcErlAy3W2:b7wnjq9) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L67)):*
> ```cpp
> 
>     // only use nodes that provide at least UDP connection
>     if (!node[NodeFields::status_udp].toBool(false)) {
> ```

What is the point in all of these checks if we already check the needed fields at the top?
___
*[src/net/bootstrapnodeupdater.cpp, line 115 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R604b5zqj3TcEg8Eq:-M6R604b5zqj3TcEg8Er:bg1hnp8) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L115)):*
> ```cpp
> 
>     if (!nodeList.isObject()) {
>         return result;
> ```

We should add warn logs for users since the nodes list is user editable now.
___
*[src/net/bootstrapnodeupdater.cpp, line 120 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R5u1qBgwTFuRZ8-aP:-M6R5u1qBgwTFuRZ8-aQ:bg1hnp8) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L120)):*
> ```cpp
>     QJsonObject rootObj = nodeList.object();
>     if (!(rootObj.contains(jsonNodeArrayName) && rootObj[jsonNodeArrayName].isArray())) {
>         return result;
> ```

We should add warn logs for users since the nodes list is user editable now.
___
*[src/net/bootstrapnodeupdater.cpp, line 142 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R6Ef37c1c2vRhp1le:-M6R6Ef48tvulClvCSHZ:b-fhlf2y) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L142)):*
> ```cpp
>     QString nodesJson = nodesFile.readAll();
>     nodesFile.close();
>     QJsonDocument d = QJsonDocument::fromJson(nodesJson.toUtf8());
> ```

I don't see any reason to use single letter variable names instead of something a little more descriptive
___
*[src/net/bootstrapnodeupdater.cpp, line 261 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R6Sqj3kvZ9kfKl9cJ:-M6R6Sqj3kvZ9kfKl9cK:b4lybs3) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L261)):*
> ```cpp
> }
> 
> QString BootstrapNodeUpdater::getUserNodesFilePath()
> ```

If we're moving to getting paths from the Paths class doesn't it make more sense for this to go there?
___
*[src/persistence/paths.h, line 46 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R0UdZCDaJt2N8d04A:-M6R0Ud_3otA1DXySzHz:b-acgll4) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/persistence/paths.h#L46)):*
> ```objc
>     QString getScreenshotsDir() const;
>     // to be removed when paths migration is complete.
>     QString getLegacySettingsDirPath() const;
> ```

I'm not sure how I feel about these names. If they are the only paths available why are they legacy? If I were trying to retrieve the settings path I would look at this and say "where is the non-legacy settings dir" which seems to not exist.

I'd maybe just note in the doxygen comments that these paths are intended to be moved?

@anthonybilinski indicated that the other paths in here are currently unused as well, which makes things extra confusing since someone would look for the screenshots dir and be pointed to the wrong location. If these paths are a work in progress maybe it's better to feature guard them with an ifdef or something so people know not to use them? 
___
*[src/persistence/paths.cpp, line 263 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R0ts6A5XhFkHgL45d:-M6R0ts6A5XhFkHgL45e:byoc8gj) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/persistence/paths.cpp#L263)):*
> ```cpp
>  * @note To be removed when path migration is complete.
>  */
> QString Paths::getLegacySettingsDirPath() const
> ```

I'm assuming these are straight copy pastes from the old settings functions. I try to note that type of change in the commit message to ease reviewer load, but that's just me being selfish :P

**Review by anthonybilinski — COMMENTED** [review]
> I might be misusing the feature, but something doesn't seem right to me

Fixed, `loadNodesFile` was still always using the built-in file rather than the passed in file. It'll now log warnings with invalid config.

> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126#-:-M6Rrwlm0z_vvTC5mLxf:b-wvjbll)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/core/core.cpp, line 810 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R4wsQD0FJn_6NSNWS:-M6Rsv5aEZF5Y9BOJsZj:b-d50vqc) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/core/core.cpp#L810)):*
Yeah this part seems iffy. The source, https://nodes.tox.chat/ has ipv4 and ipv6 addresses whenever a node supports both, so setting both in `DhtServer` mirrors that info. I favoured using ipv4 if both are present because the user of qTox might not have an ipv6 connection. I think ideally we would just try to bootstrap from each address, but since our bootstrapping is (questionably) throttled to just trying a couple nodes per bootstrap, and (questionably) says that adding more nodes slows down connecting, I skipped doing that since I figured that would just lead to a slower connection.

If/when our Core bootstrapping is updated, I think it could handle dual-protocol nodes better.

> Also that would ensure we don't try to pass in an empty address to tox_bootstrap

I added a check to `jsonNodeToDhtServer` that will reject nodes that have neither an ipv4 nor ipv6 address.
___
*[src/net/bootstrapnodeupdater.cpp, line 67 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R4Qp_2JtcErlAy3W1:-M6RuMxH330ScQPaPRnJ:bkwb21) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L67)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

What is the point in all of these checks if we already check the needed fields at the top?
</blockquote></details>

The check at the top is just checking that the keys are present, all the subsequent ones are checking the values of each config.
___
*[src/net/bootstrapnodeupdater.cpp, line 115 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R604b5zqj3TcEg8Eq:-M6RumkP7_d_Fj8tRx0w:b-886gsx) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L115)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

We should add warn logs for users since the nodes list is user editable now.
</blockquote></details>

Fixed
___
*[src/net/bootstrapnodeupdater.cpp, line 120 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R5u1qBgwTFuRZ8-aP:-M6Runhs1szQbzVh8_UE:b-886gsx) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L120)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

We should add warn logs for users since the nodes list is user editable now.
</blockquote></details>

Fixed
___
*[src/net/bootstrapnodeupdater.cpp, line 142 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R6Ef37c1c2vRhp1le:-M6RvJOD5YjXtvVPOP_M:bt2vr1b) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L142)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I don't see any reason to use single letter variable names instead of something a little more descriptive
</blockquote></details>

Fixed.
___
*[src/net/bootstrapnodeupdater.cpp, line 261 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R6Sqj3kvZ9kfKl9cJ:-M6RwDhc60N5eOuWBHNA:b-rhcrhu) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L261)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

If we're moving to getting paths from the Paths class doesn't it make more sense for this to go there?
</blockquote></details>

Seems dependent on where Paths goes. The "old"/current way was that we have 3 dirs and every class knows its own path within whichever dir, the "new"/unused way is that `Paths` provides each file path. If we do end up removing all the unused/inaccurate API from `Paths` then I'd be happy to move this in, but if `Paths` is going to stay split between the 3 "old" directories and the many "new"/unused/inaccurate paths, I'd rather not add `getUserNodesFilePath` to it so that it doesn't get mixed in with the other API :S
___
*[src/persistence/paths.h, line 46 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R0UdZCDaJt2N8d04A:-M6RwmQQ0O0FWd5YoOBR:b-1qzyst) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/persistence/paths.h#L46)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I'm not sure how I feel about these names. If they are the only paths available why are they legacy? If I were trying to retrieve the settings path I would look at this and say "where is the non-legacy settings dir" which seems to not exist.

I'd maybe just note in the doxygen comments that these paths are intended to be moved?

@anthonybilinski indicated that the other paths in here are currently unused as well, which makes things extra confusing since someone would look for the screenshots dir and be pointed to the wrong location. If these paths are a work in progress maybe it's better to feature guard them with an ifdef or something so people know not to use them? 
</blockquote></details>

Yeah the more I think about Paths, the more this API is extremely confusing. @sudden6 would you be ok with me just deleting all of the current unused API from `Paths` in a single commit? When the paths reword is finished, that commit could be backed out, but in the meantime it would leave `Paths` with an accurate and reasonable API, where each function gives the correct path.
___
*[src/persistence/paths.cpp, line 263 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R0ts6A5XhFkHgL45d:-M6Rx99Q7T0nVUCf5G-3:b-jcqilk) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/persistence/paths.cpp#L263)):*
<details><summary><i>Previously, sphaerophoria wrote…</i></summary><blockquote>

I'm assuming these are straight copy pastes from the old settings functions. I try to note that type of change in the commit message to ease reviewer load, but that's just me being selfish :P 
</blockquote></details>

That's fair, I could have split it into a commit along with the code moving in `BootstrapNodeUpdate`r. I'll keep that in mind going forward.

**Review by sudden6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/persistence/paths.h, line 46 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R0UdZCDaJt2N8d04A:-M6TuEX7AwKDRwy3am3o:bhh41dl) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/persistence/paths.h#L46)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Yeah the more I think about Paths, the more this API is extremely confusing. @sudden6 would you be ok with me just deleting all of the current unused API from `Paths` in a single commit? When the paths reword is finished, that commit could be backed out, but in the meantime it would leave `Paths` with an accurate and reasonable API, where each function gives the correct path.
</blockquote></details>

I'm a bit against completely removing the API, because then we'll forget about it, but ifdef out the problematic parts seems fine.

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/6126)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[src/net/bootstrapnodeupdater.cpp, line 261 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R6Sqj3kvZ9kfKl9cJ:-M6WDK5KDi94R6Iz1D9j:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/net/bootstrapnodeupdater.cpp#L261)):*
<details><summary><i>Previously, anthonybilinski (Anthony Bilinski) wrote…</i></summary><blockquote>

Seems dependent on where Paths goes. The "old"/current way was that we have 3 dirs and every class knows its own path within whichever dir, the "new"/unused way is that `Paths` provides each file path. If we do end up removing all the unused/inaccurate API from `Paths` then I'd be happy to move this in, but if `Paths` is going to stay split between the 3 "old" directories and the many "new"/unused/inaccurate paths, I'd rather not add `getUserNodesFilePath` to it so that it doesn't get mixed in with the other API :S
</blockquote></details>

Done.
___
*[src/persistence/paths.h, line 46 at r3](https://reviewable.io/reviews/qtox/qtox/6126#-M6R0UdZCDaJt2N8d04A:-M6WDBoh3c8Fze6DzEDx:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/d1553f45482e78b795da32f010bbdd91a08d7d8b/src/persistence/paths.h#L46)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I'm a bit against completely removing the API, because then we'll forget about it, but ifdef out the problematic parts seems fine.
</blockquote></details>

Done.

**Pull request merged**
