### PR TITLE
refactor(toxid): use left instead of mid

### PR DESCRIPTION
**Pull request by noavarice**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4638)

### CODE REVIEW

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4638#-:-Ktc8HzSVswAQYLVAu3L:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4638#-:-Ktkw4pOue8EvAJE0KJM:b-jbsf8z)*

**Comment by Talkless** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4638#-:-KuPzR754xnsDSO63fc1:b-jbsf8z)*

**Comment by Diadlo** [comment]
@noavarice Merge?

**Comment by sudden6** [comment]
I merged it since noavarice doesn't seem to have time for this.

**Pull request merged**
