### PR TITLE
fix: Update to immutable TES API and one-big-lib change.

### PR DESCRIPTION
**Pull request by iphydf**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4894)

### CODE REVIEW

**Comment by sudden6** [comment]
I guess this needs `#ifdef` based on the toxcore version to work?

**Comment by iphydf** [comment]
Done.

**Comment by Diadlo** [comment]
Please, rebase on master

**Comment by iphydf** [comment]
Rebased.

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[src/core/toxencrypt.cpp, line 162 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jpoBYI-wwZruTrvNq:-L2jpoBYI-wwZruTrvNr:bmbg027) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/core/toxencrypt.cpp#L162)):*
> ```cpp
>     TOX_ERR_KEY_DERIVATION error;
> #if TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)
>     Tox_Pass_Key* passKey = tox_pass_key_derive(
> ```

I believe could be `Tox_Pass_Key* const passKey`
Same below.

---

*[src/persistence/db/rawdatabase.cpp, line 488 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jqB1m14mY79bW5bHf:-L2jqB1m14mY79bW5bHg:b-dv1y6l) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/persistence/db/rawdatabase.cpp#L488)):*
> ```cpp
>         "L'ignorance est le pire des maux";
> #if TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)
>     std::unique_ptr<Tox_Pass_Key, PassKeyDeleter> key(tox_pass_key_derive_with_salt(
> ```

**const** std::unique_ptr<...

---

*[src/persistence/db/rawdatabase.cpp, line 492 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jqGMFNXDd99Z470hB:-L2jqGMFNXDd99Z470hC:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/persistence/db/rawdatabase.cpp#L492)):*
> ```cpp
>         static_cast<std::size_t>(passData.size()), expandConstant, nullptr));
> #else
>     std::unique_ptr<Tox_Pass_Key, PassKeyDeleter> key(tox_pass_key_new());
> ```

Same as above

---

*[src/persistence/db/rawdatabase.cpp, line 521 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jqIXEVOA_cTS6ke1u:-L2jqIXFI2XnbUxPn_pv:b-rmtty4) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/persistence/db/rawdatabase.cpp#L521)):*
> ```cpp
> 
> #if TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)
>     std::unique_ptr<Tox_Pass_Key, PassKeyDeleter> key(tox_pass_key_derive_with_salt(
> ```

same, const

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4894)*

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 162 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jpoBYI-wwZruTrvNq:-L2lU3Lk09StaFxwSJPQ:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/core/toxencrypt.cpp#L162)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

I believe could be `Tox_Pass_Key* const passKey`
Same below.
</blockquote></details>

Done.

---

*[src/persistence/db/rawdatabase.cpp, line 488 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jqB1m14mY79bW5bHf:-L2lU3yfFcQHXvS3estM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/persistence/db/rawdatabase.cpp#L488)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

**const** std::unique_ptr<...
</blockquote></details>

Done.

---

*[src/persistence/db/rawdatabase.cpp, line 492 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jqGMFNXDd99Z470hB:-L2lU4LSMPB0ixmACvLy:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/persistence/db/rawdatabase.cpp#L492)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.

---

*[src/persistence/db/rawdatabase.cpp, line 521 at r1](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2jqIXEVOA_cTS6ke1u:-L2lU50c5a3PGru52nFH:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/34c8a72f13acefc9cd65fb50f5d276b8d98c092a/src/persistence/db/rawdatabase.cpp#L521)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

same, const
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4894)*

**Comment by Talkless** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 208 at r2](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2p3jZVjlKhtbVT27T-:-L2p3jZW3gqXr3S0IfF_:bt3j6xv) ([raw file](https://github.com/qtox/qtox/blob/5dcd97202a1e55f6723ed56474d4e268eba6ea24/src/core/toxencrypt.cpp#L208)):*
> ```cpp
>     TOX_ERR_KEY_DERIVATION keyError;
> #if TOX_VERSION_IS_API_COMPATIBLE(0, 2, 0)
>     Tox_Pass_Key* passKey = tox_pass_key_derive_with_salt(
> ```

Tox_Pass_Key* const passKey

---

*[src/core/toxencrypt.cpp, line 212 at r2](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2p3mKsz7ipL2VxWBSz:-L2p3mKsz7ipL2VxWBT-:bt3j6xv) ([raw file](https://github.com/qtox/qtox/blob/5dcd97202a1e55f6723ed56474d4e268eba6ea24/src/core/toxencrypt.cpp#L212)):*
> ```cpp
>         static_cast<size_t>(pass.length()), salt, &keyError);
> #else
>     Tox_Pass_Key* passKey = tox_pass_key_new();
> ```

Tox_Pass_Key* const passKey

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4894)*

**Comment by iphydf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core/toxencrypt.cpp, line 208 at r2](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2p3jZVjlKhtbVT27T-:-L2pLUNkTK3BgRWNNHJ_:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/5dcd97202a1e55f6723ed56474d4e268eba6ea24/src/core/toxencrypt.cpp#L208)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Tox_Pass_Key* const passKey
</blockquote></details>

Done.

---

*[src/core/toxencrypt.cpp, line 212 at r2](https://reviewable.io:443/reviews/qtox/qtox/4894#-L2p3mKsz7ipL2VxWBSz:-L2pL_OnQ21TtMQiuSow:bdycovi) ([raw file](https://github.com/qtox/qtox/blob/5dcd97202a1e55f6723ed56474d4e268eba6ea24/src/core/toxencrypt.cpp#L212)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Tox_Pass_Key* const passKey
</blockquote></details>

Done, but this code was moved from a few lines above. I'm not sure which rules you're enforcing here, but not the "should look like surrounding code" one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4894)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4894#-:-L2tZm2SavrCeTlcH95_:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4894#-:-L2tmuWydZ-e1yTd_kiF:b-jbsf8z)*

**Pull request merged**
