### PR TITLE
Add nightly build links to README.md

### PR DESCRIPTION
**Pull request by tobeaver**
This might be useful when some bugfixes are merged. Currently I mean #4801.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4812)

### CODE REVIEW

**Comment by Diadlo** [comment]
Your PR is failing because of the Commit Guidlines https://github.com/qTox/qTox/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by tobeaver** [comment]
Travis failed to `JOB=build-ubuntu-14-04`. And I don't know what to do with that.

**Comment by Diadlo** [comment]
@tobeaver Seems Travis bug. Fixed now

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4812#-:-KzKUhfP3bfwPQ9vcahl:b-jbsf8z)*

**Comment by Diadlo** [comment]
@sudden6 @zetok

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4812#-:-KzSuJE1kNjQ6fvE4mjb:b-jbsf8z)*

**Pull request merged**
