### PR TITLE
Show toxcore version

### LINKED ISSUE #2086: Display toxcore version
Additionally to your own version number (or hash) you should also display the toxcore version in the About window as i suggested in https://github.com/irungentoo/toxcore/issues/1395 for the core.

### PR DESCRIPTION
**Pull request by zetok**
Even though currently it's listed as 0.0.0, it sill should be shown.

Closes #2086

### CODE REVIEW

**Comment by tux3** [comment]
Isn't it too soon, since it's probably going to stay at 0.0.0 for a long time?

**Comment by agilob** [comment]
There is new toxcore version "released", we're the only client that didn't implement new a/v api. I can do it over the weekend in 2-3 weeks.

**Comment by zetok** [comment]
Beside what @agilob said, there's no reason to hide it, since later on this functionality could be easily forgotten about.

**Comment by tux3** [comment]
Alright.

**Pull request merged**
