### PR TITLE
[Refactor] Add Contact class

### PR DESCRIPTION
**Pull request by Diadlo**
Add parent of the Friend and Group

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4550)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/friend.cpp, line 119 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxAIFinFHW-kWCuYV:-KqHxAIGyx7-F1a3U4b2:b5uyhnx) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/friend.cpp#L119)):*
> ```cpp
> uint32_t Friend::getId() const
> {
>     return getFriendId() * 2;
> ```

What's that?

---

*[src/model/group.cpp, line 133 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxI6F1OvABIz7w1pd:-KqHxI6F1OvABIz7w1pe:bb73xfv) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/group.cpp#L133)):*
> ```cpp
> uint32_t Group::getId() const
> {
>     return getGroupId() * 2 + 1;
> ```

Same

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550)*

**Comment by Diadlo** [comment]
Review status: 0 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/friend.cpp, line 119 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxAIFinFHW-kWCuYV:-KqOZnTXMD7rmgzoeNXZ:b499q7j) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/friend.cpp#L119)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

What's that?
</blockquote></details>

Changed

---

*[src/model/group.cpp, line 133 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxI6F1OvABIz7w1pd:-KqOaf8PjYBxnQSu_oOT:b499q7j) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/group.cpp#L133)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Same
</blockquote></details>

Changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550)*

**Comment by sudden6** [comment]
I'm still confused what that is, care to provide the reasons for this change?

---

Review status: 0 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/group.cpp, line 133 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxI6F1OvABIz7w1pd:-KqP_ied7z8F9uWqDbwS:b58pl45) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/group.cpp#L133)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Changed
</blockquote></details>

Is `getGroupId()` only there for backward compatibility? Or why do both functions exist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550#-:-KqP_Um9fD5VFEKJSJY6:b-a6ha57)*

**Comment by Diadlo** [comment]
To remove code like [this](https://github.com/qTox/qTox/blob/master/src/widget/genericchatroomwidget.h#L45:L52)

---

Review status: 0 of 29 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/model/group.cpp, line 133 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxI6F1OvABIz7w1pd:-KqRHI00ojEunePVVdTv:b-4rcu7b) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/group.cpp#L133)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Is `getGroupId()` only there for backward compatibility? Or why do both functions exist?
</blockquote></details>

For backward compatibility. Do you think, that it should be removed in this PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550#-:-KqRHOH-Mkm-0caQ3TRO:b-tamerv)*

**Comment by sudden6** [comment]
Reviewed 26 of 33 files at r1, 5 of 6 files at r2.
Review status: 28 of 29 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/model/group.cpp, line 133 at r1](https://reviewable.io:443/reviews/qtox/qtox/4550#-KqHxI6F1OvABIz7w1pd:-KqUa7sMpFPTcNrBRirt:beudzg5) ([raw file](https://github.com/qtox/qtox/blob/267173075ba2625eef1855061e737e39ae7426d5/src/model/group.cpp#L133)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

For backward compatibility. Do you think, that it should be removed in this PR?
</blockquote></details>

You can leave it for later if you want, but mark it as deprecated.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 4 of 33 files at r1, 12 of 12 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550#-:-KqmOunTulasX6EKgXYq:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4550#-:-KqnNuA-7AhMQPmjDlkN:b-jbsf8z)*

**Pull request merged**
