### PR TITLE
Code style improvements

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by agilob** [comment]
I think you're spamming with those commits with inconsistent syntax:

wat

**Comment by tux3** [comment]
@agilob 
It's not really inconsistent.
Having either no braces twice or braces twice is ok, mixing both not so much.

You could argue that it's just a matter of personal tastes, but I'll take it :)

**Comment by zetok** [comment]
@agilob it's all according to https://github.com/tux3/qTox/wiki/Coding#coding-style `;)`

**Comment by agilob** [comment]
I don't want to be a jerk, but those commit make only mess in branches, don't introduce anything new, codestyle between 137-160 is inconsistent. 

@zetok  The wiki page gives example of code-style

> E.g. https://github.com/tux3/qTox/blob/master/src/misc/flowlayout.cpp

When you visit the file you see two different code styles for single-line-if-statements:

```
    if (m_hSpace >= 0) {
        return m_hSpace;
    } else {
        return smartSpacing(QStyle::PM_LayoutHorizontalSpacing);
    }
```

```
    if (index >= 0 && index < itemList.size())
        return itemList.takeAt(index);
    else
        return 0;
```

If you really want to follow allmans style then use [astyle for that](http://astyle.sourceforge.net/astyle.html#_style=allman):
astyle src/_.(h||cpp) src/chatlog/_.(h||cpp) src/platform/_.(h||cpp) src/chatlog/content/_.(h||cpp) src/misc/_.(h||cpp) src/misc/db/_.(h||cpp) src/widget/_.(h||cpp) src/widget/form/_.(h||cpp) src/widget/tool/*.(h||cpp) -A1

Changes made by converting all above files:
[back_in_the_game 1267162] commitmessage
 147 files changed, 6716 insertions(+), 5130 deletions(-)
 rewrite src/audio.h (70%)
 rewrite src/autoupdate.h (77%)
 rewrite src/chatlog/chatlog.h (76%)
 rewrite src/chatlog/content/text.h (72%)
 rewrite src/core.h (92%)
 rewrite src/historykeeper.h (73%)
 rewrite src/ipc.h (62%)
 rewrite src/misc/settings.h (90%)
 rewrite src/misc/style.h (62%)
 rewrite src/nexus.h (66%)
 rewrite src/toxme.h (73%)
 rewrite src/widget/androidgui.h (82%)
 rewrite src/widget/callconfirmwidget.h (62%)
 rewrite src/widget/form/chatform.h (73%)
 rewrite src/widget/gui.h (92%)
 rewrite src/widget/systemtrayicon.h (62%)
 rewrite src/widget/widget.h (80%)

**Comment by agilob** [comment]
If you think codestyle is very important, than just create bash script that will be invoked as pre-commit `git hook` and format every file before signing changes.
I don't think it' so important...

**Pull request closed without merging**
