### PR TITLE
Add test for Toxme

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4718)

### CODE REVIEW

**Comment by sudden6** [comment]
Reviewed 3 of 8 files at r1.
Review status: 3 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/net/toxmedata.cpp, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF8qxVVwEWfpDJJi8C:-KwF8qxWp6E_HI4REnmI:b4rzi9h) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L24)):*
> ```cpp
> 
> #include <QString>
> ```

add function documentation for all functions here

---

*[src/net/toxmedata.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF9IUyrTOqPeyWgftW:-KwF9IUyrTOqPeyWgftX:b-czprai) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L37)):*
> ```cpp
> 
>     QByteArray key;
>     // I think, exist more easy way to convert key to ByteArray
> ```

There's `QByteArray::fromHex` see http://doc.qt.io/qt-5/qbytearray.html#fromHex

---

*[src/net/toxmedata.cpp, line 63 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF9UrZD9RW043tbEXK:-KwF9UrZD9RW043tbEXL:bfcojcm) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L63)):*
> ```cpp
> {
>     QString text = inText;
>     static const QByteArray pattern{"tox_id\""};
> ```

consider using `constexpr` for compile time constants

---

*[src/net/toxmedata.cpp, line 65 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF9_u6Aaa-ruJrpR-j:-KwF9_u6Aaa-ruJrpR-k:bca6nfo) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L65)):*
> ```cpp
>     static const QByteArray pattern{"tox_id\""};
>     const int index = text.indexOf(pattern);
>     if (index == -1)
> ```

missing braces in this file

---

*[test/net/toxmedata_test.cpp, line 59 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHE0fEi132jUi3X1Bd:-KwHE0fEi132jUi3X1Be:b1dyouh) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L59)):*
> ```cpp
> };
> 
> void TestToxmeData::parsePublicKeyTest()
> ```

Maybe short comments what each test does and why it's needed?

---

*[test/net/toxmedata_test.cpp, line 184 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHEdpzuyN3QJ_NKdS6:-KwHEdpzuyN3QJ_NKdS7:b-qc20ss) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L184)):*
> ```cpp
> 
>     int timeRes = json["timestamp"].toInt();
>     QVERIFY(qAbs(timeRes - timestamp) < 100);
> ```

Am I right in that this test will fail if the actions take more than 100ms? If so, this should be noted, although it's unlikely to ever happen in practice.

---

*[test/net/toxmedata_test.cpp, line 248 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHF79JZgWNsOiqURhg:-KwHF79K84nKzU5EBpSO:bnj7hl0) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L248)):*
> ```cpp
> 
>     int timeRes = json["timestamp"].toInt();
>     QVERIFY(qAbs(timeRes - timestamp) < 100);
> ```

same as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4718)*

**Comment by Diadlo** [comment]
Review status: 3 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[src/net/toxmedata.cpp, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF8qxVVwEWfpDJJi8C:-KwHFuCx-Z4zS_bNT_j-:bxbvkw1) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L24)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

add function documentation for all functions here
</blockquote></details>

Please, skip toxmedata review for now. It's just moved from `toxme.cpp`. I plan to fully refactor it after test merge, it's the reason of test creation :)

---

*[src/net/toxmedata.cpp, line 37 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF9IUyrTOqPeyWgftW:-KwHG0_YCDkz_bUIeEZN:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L37)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

There's `QByteArray::fromHex` see http://doc.qt.io/qt-5/qbytearray.html#fromHex
</blockquote></details>

Same as above

---

*[src/net/toxmedata.cpp, line 63 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF9UrZD9RW043tbEXK:-KwHG1mFK8WfIWjheOWD:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L63)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

consider using `constexpr` for compile time constants
</blockquote></details>

Same as above

---

*[src/net/toxmedata.cpp, line 65 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF9_u6Aaa-ruJrpR-j:-KwHG29qp_8_cQL2HgxE:b-ya81ng) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L65)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

missing braces in this file
</blockquote></details>

Same as above

---

*[test/net/toxmedata_test.cpp, line 59 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHE0fEi132jUi3X1Bd:-KwHJ14PZjAUHqEWs8qb:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L59)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Maybe short comments what each test does and why it's needed?
</blockquote></details>

Done.

---

*[test/net/toxmedata_test.cpp, line 184 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHEdpzuyN3QJ_NKdS6:-KwHGM8YWCEK4IITM0Lr:bnnixat) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L184)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

Am I right in that this test will fail if the actions take more than 100ms? If so, this should be noted, although it's unlikely to ever happen in practice.
</blockquote></details>

Ok. But is this a comment for the sake of comment?

---

*[test/net/toxmedata_test.cpp, line 248 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHF79JZgWNsOiqURhg:-KwHGSvWNCC4xr24nalK:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L248)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4718)*

**Comment by sudden6** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF8qxVVwEWfpDJJi8C:-KwHJJI0PuF1J5UkTnge:bqpvg2m) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L24)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Please, skip toxmedata review for now. It's just moved from `toxme.cpp`. I plan to fully refactor it after test merge, it's the reason of test creation :)
</blockquote></details>

ok, pls state that in the PR the next time, will save time for both of us^^

---

*[test/net/toxmedata_test.cpp, line 184 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHEdpzuyN3QJ_NKdS6:-KwHJj9CtUrentQgrlud:bk6g90z) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L184)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Ok. But is this a comment for the sake of comment?
</blockquote></details>

`take more than 100 seconds`, no, it's just very strange for a test like this to depend on the time, so better document it.

---

*[test/net/toxmedata_test.cpp, line 248 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHF79JZgWNsOiqURhg:-KwHKDEl5Cli2dItJnhc:b-2gm9bb) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L248)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4718)*

**Comment by Diadlo** [comment]
Review status: 1 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/net/toxmedata.cpp, line 24 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwF8qxVVwEWfpDJJi8C:-KwHMlIM1I_Q9SY5ISDC:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/src/net/toxmedata.cpp#L24)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

ok, pls state that in the PR the next time, will save time for both of us^^
</blockquote></details>

Done.

---

*[test/net/toxmedata_test.cpp, line 184 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHEdpzuyN3QJ_NKdS6:-KwHMnDkhfH_-1aJOvnC:b-a17b6t) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L184)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

`take more than 100 seconds`, no, it's just very strange for a test like this to depend on the time, so better document it.
</blockquote></details>

Many tests (test for every module, which works with time) depends on time.
Done.

---

*[test/net/toxmedata_test.cpp, line 248 at r1](https://reviewable.io:443/reviews/qtox/qtox/4718#-KwHF79JZgWNsOiqURhg:-KwHMmpjIk1xuZRdQAuk:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6f7c11cd1e7456bbf08543d12c2e79203fcd3a71/test/net/toxmedata_test.cpp#L248)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

same typo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4718)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 4 of 8 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4718#-:-KwHORXnuyVCQwf2CdLS:b-jbsf8z)*

**Comment by Diadlo** [comment]
@sudden6 Probably, you are interested in #4729 :)

**Pull request merged**
