### PR TITLE
chore(cmake): Add icons, desktop, appdata installation

### LINKED ISSUE #4100: [Regression] qtox compiled with cmake doesn't install icon or desktop files
##### Brief Description

OS: Gentoo Linux amd64
qTox version: v1.7.0-104-gf0467ab
Commit hash:  f0467abc34f3dc2308b9cd4473550e8f1d4ce787
toxcore:  v0.1.6
Qt:  5.6.2

Reproducible: Always

##### Steps to reproduce

1. generate makefile with cmake
2. `make install`

##### Observed Behavior
There are no icon, desktop, etc files installed

##### Expected Behavior
Files should be installed just like with qmake

##### Additional Info
qmake installing icons: https://github.com/qTox/qTox/blob/f0467abc34f3dc2308b9cd4473550e8f1d4ce787/qtox.pro#L221,L230
desktop: https://github.com/qTox/qTox/blob/f0467abc34f3dc2308b9cd4473550e8f1d4ce787/qtox.pro#L215,L216
appdata: https://github.com/qTox/qTox/blob/f0467abc34f3dc2308b9cd4473550e8f1d4ce787/qtox.pro#L217,L218

cc @Diadlo ?

### PR DESCRIPTION
**Pull request by Diadlo**
Fix #4100

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4102)

### CODE REVIEW

**Comment by zetok** [comment]
92723c6d83b68dfe9b0271040083172fd298af25 doesn't fix it, files are placed in the wrong place;

should be:
```
/usr/bin/qtox
/usr/share/appdata/qTox.appdata.xml
/usr/share/applications/qTox.desktop
/usr/share/doc/qtox-1.7.0/README.md.bz2
/usr/share/icons/hicolor/128x128/apps/qtox.png
/usr/share/icons/hicolor/14x14/apps/qtox.png
/usr/share/icons/hicolor/16x16/apps/qtox.png
/usr/share/icons/hicolor/192x192/apps/qtox.png
/usr/share/icons/hicolor/22x22/apps/qtox.png
/usr/share/icons/hicolor/24x24/apps/qtox.png
/usr/share/icons/hicolor/256x256/apps/qtox.png
/usr/share/icons/hicolor/32x32/apps/qtox.png
/usr/share/icons/hicolor/36x36/apps/qtox.png
/usr/share/icons/hicolor/48x48/apps/qtox.png
/usr/share/icons/hicolor/512x512/apps/qtox.png
/usr/share/icons/hicolor/64x64/apps/qtox.png
/usr/share/icons/hicolor/72x72/apps/qtox.png
/usr/share/icons/hicolor/96x96/apps/qtox.png
/usr/share/icons/hicolor/scalable/apps/qtox.svg
```

is:

```
/usr/appdata/qTox.appdata.xml
/usr/applications/qTox.desktop
/usr/bin/qtox
/usr/share/doc/qtox-9999/README.md.bz2
/usr/share/hicolor/128x128/app/qtox.png
/usr/share/hicolor/14x14/app/qtox.png
/usr/share/hicolor/16x16/app/qtox.png
/usr/share/hicolor/192x192/app/qtox.png
/usr/share/hicolor/22x22/app/qtox.png
/usr/share/hicolor/24x24/app/qtox.png
/usr/share/hicolor/256x256/app/qtox.png
/usr/share/hicolor/32x32/app/qtox.png
/usr/share/hicolor/36x36/app/qtox.png
/usr/share/hicolor/48x48/app/qtox.png
/usr/share/hicolor/512x512/app/qtox.png
/usr/share/hicolor/64x64/app/qtox.png
/usr/share/hicolor/72x72/app/qtox.png
/usr/share/hicolor/96x96/app/qtox.png
```

**Comment by Diadlo** [comment]
Should be fixed now. Exclude `/usr/share/doc/qtox-9999/README.md.bz2`
CMake on my PC didn't install it

**Comment by zetok** [comment]
`qTox.appdata.xml` and `qTox.desktop` still aren't in the right place on 86dd707b70608f30cba44fccb6bd5db7198ccfc6

**Comment by Diadlo** [comment]
Fixed

**Comment by zetok** [comment]
works for me :lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmake/Installation.cmake, line 8 at r1](https://reviewable.io:443/reviews/qtox/qtox/4102#-Kbdx06du5Pzppi_XQIA:-Kbdx06enF6IQmEHV73t:b-ra0ju) ([raw file](https://github.com/qtox/qtox/blob/f054210a03dc23f3e088052d4e78ad1ad9aa84eb/cmake/Installation.cmake#L8)):*
> ```CMake
> 
> if(APPLE)
>   set(MACOSX_BUNDLE_SHORT_VERSION_STRING 1.4.1)
> ```

Version doesn't seem to be right..?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4102#-:-Kbdwcr-D7FHfEGsVs5L:b8bb22s)*

**Pull request merged**
