### PR TITLE
Make 'None' and 'Desktop' camera device names translatable

### LINKED ISSUE #2252: "None" in Video device not translated and "Desktop" isn't translatable
capture

And also Desktop isn't translatable at all.

### PR DESCRIPTION
**Pull request by zetok**
fixes #2252

### CODE REVIEW

**Comment by TheNain38** [comment]
Could you also make 'Desktop' camera device name translatable?

**Comment by zetok** [comment]
@TheNain38 ok, done.

**Comment by TheNain38** [comment]
@zetok Thanks.

**Comment by TheNain38** [comment]
When this get merged I will update the French translation.

**Comment by TheNain38** [comment]
Could you merge it please?

**Comment by tux3** [comment]
Looks good to me.

**Comment by zetok** [comment]
Ok, rebased and pushed on master in 6998c2c757828e20f9125969f364e81f5938b22d

**Pull request closed without merging**
