### PR TITLE
Add tooltip in filetransferwidget

### PR DESCRIPTION
**Pull request by PKEv**
It is not clear what they are doing buttons

### CODE REVIEW

**Comment by yurivict** [comment]
You have typo: transmite -> transmit

**Comment by PKEv** [comment]
Has corrected my English

**Comment by tux3** [comment]
"transmit" should be "transfer" in this case, but I'll just fix that in the merge commit.

**Comment by tux3** [comment]
Merged in https://github.com/tux3/qTox/commit/262fc7059dc82140a58344e9c7e9d3d15827a65a

Will reach master on Sunday night if all goes well.

**Pull request closed without merging**
