### PR TITLE
Remove cdata

### PR DESCRIPTION
**Pull request by sudden6**
improves the ToxId class so that the cData helper is obsolete.

A further step could be to stop passing ToxIds an PKs as QString and use the ToxId class for that.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4011)

### CODE REVIEW

**Comment by Diadlo** [comment]
If you don't mind, make the review #3868 and add `isValidToxId` method

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/friendlist.cpp, line 38 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsEo1qvgcA1cdoTvI-:-KZsEo1r_E7pj95GdNPi:b-kwd11n) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/friendlist.cpp#L38)):*
> ```cpp
>     Friend* newfriend = new Friend(friendId, userId);
>     friendList[friendId] = newfriend;
>     tox2id[userId.getPublicKey()] = friendId;
> ```

Maybe add TODO? Something like `replace QString key on QByteArray`?

---

*[src/core/core.cpp, line 859 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsAsHw8UNHcC7EqnfA:-KZsAsHxVHvcl81C3hOa:b-ofblx8) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/core.cpp#L859)):*
> ```cpp
> ToxId Core::getSelfId() const
> {
>     QByteArray friendAddress(TOX_ADDRESS_SIZE, 0x00);
> ```

Why do you use `0x00` instead of `0`?

---

*[src/core/toxid.cpp, line 96 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsBx62_hvmo_9n75Ei:-KZsBx63bB3a-ijyzDGg:b2903b) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/toxid.cpp#L96)):*
> ```cpp
>  * @brief Create a Tox ID from a QByteArray.
>  *
>  * If the given id is not a valid Tox ID, then:
> ```

`s/ID/ID, but can be a public key/`
And if it can't, than publicKey == noSpam == checkSum = 0

---

*[src/core/toxid.cpp, line 103 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsCN6JZV3cSqkQj7b5:-KZsCN6JZV3cSqkQj7b6:b-1isa05) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/toxid.cpp#L103)):*
> ```cpp
> ToxId::ToxId(const QByteArray &rawId)
> {
>     if(rawId.length() == TOX_SECRET_KEY_SIZE)
> ```

Why validation is skipped?

---

*[src/core/toxid.cpp, line 107 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsCd_dVfq_MssYCXmf:-KZsCd_dVfq_MssYCXmg:b-3sgu48) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/toxid.cpp#L107)):*
> ```cpp
>         toxId = rawId;                              // construct from PK only
>     }
>     else if (rawId.length() == TOX_ADDRESS_SIZE)
> ```

```
else if (rawId.length() == TOX_ADDRESS_SIZE 
          && isToxId(rawId.toHex().toUpper()))  
{
    toxId = rawId
} 
else 
{
    toxId = QByteArray(TOX_ADDRESS_SIZE, 0x00); // invalid id string
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011#-:-KZsEBH2dNx5IN9dc4X9:bglc1fx)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[src/friendlist.cpp, line 38 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsEo1qvgcA1cdoTvI-:-KZsJrIxUacJaWmZXTb4:b-pr4i51) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/friendlist.cpp#L38)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Maybe add TODO? Something like `replace QString key on QByteArray`?
</blockquote></details>

This already replaces the `QString` key with a `QByteArray`

---

*[src/core/core.cpp, line 859 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsAsHw8UNHcC7EqnfA:-KZsK2nVIv56AHnSvc1N:bts2bn) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/core.cpp#L859)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why do you use `0x00` instead of `0`?
</blockquote></details>

Just a habit, to make it more clear that it's initializing it with zero bytes and not an unused function parameter

---

*[src/core/toxid.cpp, line 103 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsCN6JZV3cSqkQj7b5:-KZsKUWtdguZtFut-2kz:b-bsjvxh) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/toxid.cpp#L103)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why validation is skipped?
</blockquote></details>

you can't really validate a public key, they are basically random bytes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/friendlist.cpp, line 38 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsEo1qvgcA1cdoTvI-:-KZtcB5uZuUk_9nRW1SG:b-lz29np) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/friendlist.cpp#L38)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

This already replaces the `QString` key with a `QByteArray`
</blockquote></details>

Oh.. Sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011#-:-KZtcRjM-JUoVTb0lbcf:bnfp4nl)*

**Comment by zetok** [comment]
There are now some conflicts, rebase is needed.

**Comment by antis81** [comment]
Reviewed 14 of 17 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/core/core.cpp, line 426 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-nWw6TB-Fun-KJBTi:-K_-nWw6TB-Fun-KJBTj:b3uqbs9) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L426)):*
> ```cpp
>                     +':'+QString().setNum(dhtServer.port)+" ("+dhtServer.name+')';
> 
>         const char* address = dhtServer.address.toLatin1().constData();
> ```

Crash! -> Store the created array.

---

*[src/core/core.cpp, line 861 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-p5PEp6yEvc-rmMg-:-K_-p5PEp6yEvc-rmMg0:b-hn2lbg) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L861)):*
> ```cpp
>     QByteArray friendAddress(TOX_ADDRESS_SIZE, 0x00);
>     tox_self_get_address(tox, reinterpret_cast<uint8_t*>(friendAddress.data()));
>     return ToxId(friendAddress);
> ```

```c++
uint8_t friendAddress[TOX_ADDRESS_SIZE] = {0};
tox_self_get_address(tox, friendAddress);
return ToxId(QString::fromLatin1(reinterpret_cast<char*>(friendAddress)));
// TODO: Add ToxId c'tor for char* and get rid of that uchar bullshit
```

---

*[src/core/core.cpp, line 989 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-rY1nnHyQCSSGyo-8:-K_-rY1oGLOSMLnFpUL5:b-v42ulb) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L989)):*
> ```cpp
>             if (tox_friend_get_public_key(tox, ids[i], reinterpret_cast<uint8_t*>(friendPk.data()), nullptr))
>             {
>                 emit friendAdded(ids[i], ToxId(friendPk).getPublicKeyString());
> ```

Same here: Use QString::fromLatin1(reinterpret_cast<char*>(friendPk)) to emit the signal.

---

*[src/core/core.cpp, line 1105 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-rsIN_meEAph1bSXI:-K_-rsIO83mAui40K9BL:bp1gc15) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L1105)):*
> ```cpp
>     TOX_ERR_CONFERENCE_PEER_QUERY error;
>     bool success = tox_conference_peer_get_public_key(tox, groupId, peerId,
>                                                       reinterpret_cast<uint8_t*> (friendPk.data()), &error);
> ```

Yep… here as well.

---

*[src/core/toxid.cpp, line 27 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-sAacBC8rIhvZRf7o:-K_-sAadF8r2E0C99diI:b-3ds3d9) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.cpp#L27)):*
> ```cpp
> #include <tox/tox.h>
> #include <qregularexpression.h>
> #include <cstdint>
> ```

Correct include order.

---

*[src/core/toxid.cpp, line 175 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-tAK-JtRbPzMV1i9c:-K_-tAK0Np9UaWejmTzx:b-l9n9kf) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.cpp#L175)):*
> ```cpp
> const uint8_t* ToxId::getBytes() const
> {
>     return reinterpret_cast<const uint8_t*> (toxId.constData());
> ```

extra space

---

*[src/core/toxid.h, line 32 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-tO03Ycrh6FIgf2yu:-K_-tO04dIPT1m6ekSyU:b-45xp4) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.h#L32)):*
> ```objc
>     ToxId(const ToxId& other);
>     explicit ToxId(const QString& id);
>     explicit ToxId(const QByteArray& rawId);
> ```

```c++
explicit ToxId(const char* rawId);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by antis81** [comment]
If Tox defines some struct (e.g. tox_id), this should be stored/copied in ToxId.

**Comment by sudden6** [comment]
@Diadlo please review again, I changed many things

---

Review status: 11 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/core/core.cpp, line 426 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-nWw6TB-Fun-KJBTi:-K_40rAuW9iL5q-SPtZi:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L426)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Crash! -> Store the created array.
</blockquote></details>

Done.

---

*[src/core/core.cpp, line 861 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-p5PEp6yEvc-rmMg-:-K_40vLKdYVAzE7u8WLi:b-osejdj) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L861)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

```c++
uint8_t friendAddress[TOX_ADDRESS_SIZE] = {0};
tox_self_get_address(tox, friendAddress);
return ToxId(QString::fromLatin1(reinterpret_cast<char*>(friendAddress)));
// TODO: Add ToxId c'tor for char* and get rid of that uchar bullshit
```
</blockquote></details>

I've changed it like you suggested, but I still think using a `QByteArray` and then casting is less error prone, because you only have to specify the size once.

---

*[src/core/core.cpp, line 989 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-rY1nnHyQCSSGyo-8:-K_3nUPfJ4ucWLhoKuF6:bd3jtz4) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L989)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Same here: Use QString::fromLatin1(reinterpret_cast<char*>(friendPk)) to emit the signal.
</blockquote></details>

That would be wrong, because it converts raw bytes directly to `QString`.

---

*[src/core/core.cpp, line 1105 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-rsIN_meEAph1bSXI:-K_41K9YSwq4VeAsIYdO:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L1105)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Yep… here as well.
</blockquote></details>

Done.

---

*[src/core/toxid.cpp, line 96 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsBx62_hvmo_9n75Ei:-K_41caVXltDNvbEKqt7:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/toxid.cpp#L96)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`s/ID/ID, but can be a public key/`
And if it can't, than publicKey == noSpam == checkSum = 0
</blockquote></details>

Done.

---

*[src/core/toxid.cpp, line 107 at r1](https://reviewable.io:443/reviews/qtox/qtox/4011#-KZsCd_dVfq_MssYCXmf:-K_41fjeALa9ZmCzhLPw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/70a7fdc6794b5b617acd15c54756fecaf509b355/src/core/toxid.cpp#L107)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

```
else if (rawId.length() == TOX_ADDRESS_SIZE 
          && isToxId(rawId.toHex().toUpper()))  
{
    toxId = rawId
} 
else 
{
    toxId = QByteArray(TOX_ADDRESS_SIZE, 0x00); // invalid id string
}
```
</blockquote></details>

Done.

---

*[src/core/toxid.cpp, line 27 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-sAacBC8rIhvZRf7o:-K_41ZuVscoF4RrmMGZe:b-xv7yiw) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.cpp#L27)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Correct include order.
</blockquote></details>

what's wrong with it?

---

*[src/core/toxid.h, line 32 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-tO03Ycrh6FIgf2yu:-K_4t8wbmpU2wRdD0-Nb:b-ouailc) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.h#L32)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

```c++
explicit ToxId(const char* rawId);
```
</blockquote></details>

I made it `const uint8_t*` because this doesn't cause a warning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011#-:-K_4tQOAQVnFBOFcsQyG:b-g2210l)*

**Comment by sudden6** [comment]
I'm also thinking about splitting ToxID and Public Key handling into two classes, because they really aren't the same. Opinions or suggestions on how to do this with minimal work in C++?

**Comment by Diadlo** [comment]
Reviewed 2 of 5 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/core/toxid.cpp, line 27 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-sAacBC8rIhvZRf7o:-K_64KiSh5qRqGroGTDd:b-kipiob) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.cpp#L27)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

what's wrong with it?
</blockquote></details>

#include <Qt*>
Should be after C/C++ includes

---

*[src/core/toxid.cpp, line 129 at r4](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_62QhgWiq_y5orJJbD:-K_62QhgWiq_y5orJJbE:b-i47hon) ([raw file](https://github.com/qtox/qtox/blob/f5ec5cfe0bfb7160cc49b25c94ca92969dd0c18d/src/core/toxid.cpp#L129)):*
> ```cpp
> 
> 
> void ToxId::checkToxId(const QByteArray& rawId)
> ```

`check` should be `const`. You are check and set toxId. Rename method, please.

---

*[src/core/toxid.cpp, line 242 at r4](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_64WpGje2M1fM106Ug:-K_64WpHCxpXROJ39-oo:b-90b5cg) ([raw file](https://github.com/qtox/qtox/blob/f5ec5cfe0bfb7160cc49b25c94ca92969dd0c18d/src/core/toxid.cpp#L242)):*
> ```cpp
> bool ToxId::isValidToxId(const QString& id)
> {
>     if (!isToxId(id))
> ```

Are you sure, that this `if` realy needed?
If yes, it can be replaced on `isToxId(id) && ToxId(id).isValid()`

---

*[src/core/toxid.cpp, line 264 at r4](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_639MMHbSLzyhiw7VK:-K_639MNaaKvx0j1nKWj:bhrvpoz) ([raw file](https://github.com/qtox/qtox/blob/f5ec5cfe0bfb7160cc49b25c94ca92969dd0c18d/src/core/toxid.cpp#L264)):*
> ```cpp
>  * @return True if it is a valid Tox ID, false otherwise.
>  */
> bool ToxId::isValid()
> ```

Make it `const`, please

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by sudden6** [comment]
*[src/core/toxid.cpp, line 242 at r4](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_64WpGje2M1fM106Ug:-K_69g8iT_ZWMjQRxUR3:b-ga3ufk) ([raw file](https://github.com/qtox/qtox/blob/f5ec5cfe0bfb7160cc49b25c94ca92969dd0c18d/src/core/toxid.cpp#L242)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Are you sure, that this `if` realy needed?
If yes, it can be replaced on `isToxId(id) && ToxId(id).isValid()`
</blockquote></details>

Done. Yes it's needed to make sure it's hex digits and and the length matches

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by sudden6** [comment]
Review status: 15 of 17 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/core/toxid.cpp, line 27 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-sAacBC8rIhvZRf7o:-K_69akfr19hfR-HJMpt:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.cpp#L27)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

#include <Qt*>
Should be after C/C++ includes
</blockquote></details>

Done.

---

*[src/core/toxid.cpp, line 175 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-tAK-JtRbPzMV1i9c:-K_69efiG7NAHZqo8-9Z:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/toxid.cpp#L175)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

extra space
</blockquote></details>

Done.

---

*[src/core/toxid.cpp, line 129 at r4](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_62QhgWiq_y5orJJbD:-K_69cdjCtPwTT2VBvgh:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f5ec5cfe0bfb7160cc49b25c94ca92969dd0c18d/src/core/toxid.cpp#L129)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`check` should be `const`. You are check and set toxId. Rename method, please.
</blockquote></details>

Done.

---

*[src/core/toxid.cpp, line 264 at r4](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_639MMHbSLzyhiw7VK:-K_69s6yVII6U7etsr_c:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/f5ec5cfe0bfb7160cc49b25c94ca92969dd0c18d/src/core/toxid.cpp#L264)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Make it `const`, please
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by Diadlo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011#-:-K_6Cc5Irb4TM7ukIByx:bnfp4nl)*

**Comment by antis81** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/core.cpp, line 861 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-p5PEp6yEvc-rmMg-:-K_6i0CHkl9AtIIDmVAr:bv2doc1) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L861)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I've changed it like you suggested, but I still think using a `QByteArray` and then casting is less error prone, because you only have to specify the size once.
</blockquote></details>

In general Core abstracts Tox from the UI and should not use any Qt objects "internally". Instead it has to "wrap" the C API. Means, it talks directly "toxcore language" and delivers Qt objects only to the "outer world". If implemented correctly, this is not error prone at all. ToxId c'tor has to validate the string however, so it will correctly return an invalid ID object in case the returned array is a nullptr or an empty array.

---

*[src/core/core.cpp, line 989 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-rY1nnHyQCSSGyo-8:-K_6gO1_TNRg2JeFjGy7:bnvkzpz) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L989)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

That would be wrong, because it converts raw bytes directly to `QString`.
</blockquote></details>

Neat… create an object, convert to string, throw away this object, create another object by that converted string and finally assign it to a copy of friend… qTox is so funny! :smile:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by antis81** [comment]
Reviewed 2 of 5 files at r3, 2 of 4 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by antis81** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011#-:-K_6lD_bFrbj84CbgOze:b-jbsf8z)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[src/core/core.cpp, line 861 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-p5PEp6yEvc-rmMg-:-K_6xifj1h-gRy9aYdXC:bendp1n) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L861)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

In general Core abstracts Tox from the UI and should not use any Qt objects "internally". Instead it has to "wrap" the C API. Means, it talks directly "toxcore language" and delivers Qt objects only to the "outer world". If implemented correctly, this is not error prone at all. ToxId c'tor has to validate the string however, so it will correctly return an invalid ID object in case the returned array is a nullptr or an empty array.
</blockquote></details>

Yep, I think the same, no other class besides `Core` should have to deal with C stuff. This is why I would have preferred to keep ToxId without a constructor from `uint8_t*`, but I'll leave it like this for now.

---

*[src/core/core.cpp, line 989 at r2](https://reviewable.io:443/reviews/qtox/qtox/4011#-K_-rY1nnHyQCSSGyo-8:-K_6xWTkPf080njlLRRm:b-p0uarm) ([raw file](https://github.com/qtox/qtox/blob/28535b1e8e08151816d383c35cdee7ff988879a9/src/core/core.cpp#L989)):*
<details><summary><i>Previously, antis81 (Nils Fenner) wrote…</i></summary><blockquote>

Neat… create an object, convert to string, throw away this object, create another object by that converted string and finally assign it to a copy of friend… qTox is so funny! :smile:
</blockquote></details>

Well, the next step I'm planning to do is, remove all the PKs and Id's being passed around a QString

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011)*

**Comment by Diadlo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4011#-:-K_88QPdqpCUUfmYOCDi:bnfp4nl)*

**Comment by sudden6** [comment]
Removing initramfs since already two people have reviewed.

**Pull request merged**
