### PR TITLE
 fix(core, global): add mutex for guard Core::start 

### PR DESCRIPTION
**Pull request by ghost**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4472)

### CODE REVIEW

**Comment by ghost** [comment]
This fixed #4406 .

**Comment by ezavod** [comment]
@QweEwq2016 
Sorry, but this does not seem to work right.
Startup of qTox is lot longer than normal (~3sec before, ~15sec with your changes).

As far as I can tell this is because in `Core::start()` you lock `initializeMutex` and then call `Core::getAv()` (on my system this happens 19 times, at least one of them is triggered via `Core::makeAv()`).
Obviously your lock is set at this point and one waits for timeout in `Core::getAv()`.
Within your lock you call `GUI::setEnabled()` -> `QMetaObject::invokeMethod()` which blocks until all tries to lock in `Core::getAv()` resume.

After a brief glance at the code, the lock does not seem to have a use anyway (please correct me, if i miss something). Issue #4406 is fixed by your reordering in nexus.

**Comment by ghost** [comment]
@ezavod 
Hello.
"Issue #4406 is fixed by your reordering in nexus." - maybe, not only reordering? startCore() call in other thread, and getAv() in Widget::init() maybe return nullptr, because startCore() maybe not finished. I do not quite understand how to solve this problem without a mutex. Any ideas?

**Comment by ezavod** [comment]
@QweEwq2016 
Sorry for my delayed answer.
I do not know any good solution either.

Maybe one could test if the reordering fixes #4406 reliably.
It seems so to me, but maybe someone else should do proper testing.
This would not prevent other possible nullpointers, but would at least get rid of this occurring always at startup.

**Comment by Diadlo** [comment]
@zetok As I said, I prefer github PR body autofill. Most of the PR sends by regular contributors who know the rules. (Frequency PR of regular contributers) * (time to set "X" in checkbox) >> (Frequency PR of new contributers) * (time to fix commit message)
I think this PR should be closed

**Comment by anthonybilinski** [comment]
The referenced issue https://github.com/qTox/qTox/issues/4406 was fixed by https://github.com/qTox/qTox/pull/4651 which has been merged.

**Pull request closed without merging**
