### PR TITLE
Set status icon on separate chat window

### LINKED ISSUE #2210: Detached windows should have qTox icon in taskbar
Description:
Detached windows don't have qTox icon shown in taskbar.

OS: Lubuntu (15.04?)

Reproducible: Always

Additional info:
fubqfsl

First reported by @ovalseven8 in https://github.com/tux3/qTox/pull/1938#issuecomment-134951140

### PR DESCRIPTION
**Pull request by agilob**
closes #2210 
screenshot_20160103_122950

### CODE REVIEW

**Comment by agilob** [comment]
@zetok could you test and merge?

**Comment by antis81** [comment]
Other than some minor style corrections -> LGTM

**Comment by ghost** [comment]
Works fine on Cinnamon too.

**Comment by agilob** [comment]
Please merge, this issue is annoying.

**Comment by antis81** [comment]
@agilob Merged!

**Pull request closed without merging**
