### PR TITLE
chore: fix some compiler warnings

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4856)

### CODE REVIEW

**Comment by Diadlo** [comment]
Mostly :lgtm_strong: 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video/videomode.cpp, line 77 at r1](https://reviewable.io:443/reviews/qtox/qtox/4856#-L01PzrNj85de5tBQZyP:-L01PzrNj85de5tBQZyQ:b-29gric) ([raw file](https://github.com/qtox/qtox/blob/628ad31a06249d8bb6e3affbcc9a42e45463c79a/src/video/videomode.cpp#L77)):*
> ```cpp
> VideoMode::operator bool() const
> {
>     return width || height || static_cast<int>(FPS);
> ```

Probably, better to use `FPS < 0.001f`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4856#-:-L01Q5cR6TtiIy2vS9hA:b-24013b)*

**Comment by sudden6** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[src/video/videomode.cpp, line 77 at r1](https://reviewable.io:443/reviews/qtox/qtox/4856#-L01PzrNj85de5tBQZyP:-L01RS-RvwXdFb3pGKCc:bdp5h4u) ([raw file](https://github.com/qtox/qtox/blob/628ad31a06249d8bb6e3affbcc9a42e45463c79a/src/video/videomode.cpp#L77)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Probably, better to use `FPS < 0.001f`
</blockquote></details>

I thought about this too, but it's also true for negative values of `FPS` so this seemed simpler and more correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4856)*

**Comment by Diadlo** [comment]
Oh, yes, and `qAbs`

**Comment by Talkless** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/video/videomode.cpp, line 64 at r1](https://reviewable.io:443/reviews/qtox/qtox/4856#-L11p8STypj6J8rM-iVk:-L11p8STypj6J8rM-iVl:bn3qwm0) ([raw file](https://github.com/qtox/qtox/blob/628ad31a06249d8bb6e3affbcc9a42e45463c79a/src/video/videomode.cpp#L64)):*
> ```cpp
> {
>     return width == other.width && height == other.height && x == other.x && y == other.y
>            && qAbs(FPS - other.FPS) < 0.001f && pixel_format == other.pixel_format;
> ```

Maybe `qFuzzyCompare(FPS, other.FPS)` would be more "Qt-standard" way of doing this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4856)*

**Comment by sudden6** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[src/video/videomode.cpp, line 64 at r1](https://reviewable.io:443/reviews/qtox/qtox/4856#-L11p8STypj6J8rM-iVk:-L3woPzGrPTNLKA9KGpV:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/628ad31a06249d8bb6e3affbcc9a42e45463c79a/src/video/videomode.cpp#L64)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Maybe `qFuzzyCompare(FPS, other.FPS)` would be more "Qt-standard" way of doing this?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4856)*

**Pull request merged**
