### PR TITLE
Added buggy new profiles feature; see last commit for details

### PR DESCRIPTION
**Pull request by dubslow**

### CODE REVIEW

**Comment by tux3** [comment]
I'm just a bit reluctant to merge a PR with buggy in the title ..
I can't test it right now but I will ASAP.

**Comment by dubslow** [comment]
I made this in a separate (non-master) branch in my repo, but I have no idea how to create a PR that opens a new branch in yours, and I forgot the mention it in the PR lol.

I do think it is worth pulling into your repo in a separate branch; that will encourage more testing (and hopefully generate some feedback as far as the UI goes), which it certainly needs.

**Comment by tux3** [comment]
I pulled it into https://github.com/tux3/qTox/tree/profiles

**Comment by dubslow** [comment]
As it turns out, the large majority of the buginess was me not realizing that tox_load is a network function and should only be called once for each tox_new. Whoops.

**Pull request closed without merging**
