### PR TITLE
Undeprecate video

### PR DESCRIPTION
**Pull request by Diadlo**
Rebase #4180
Also add `#if LIBAVCODEC_VERSION_INT < 3747941` instead of removing

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4266)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4266#-:-KfbIi23l9FZNrvjdolb:b-jbsf8z)*

**Comment by Diadlo** [comment]
@zetok Can you test it?

**Comment by zetok** [comment]
I no longer have ffmpeg 2.8 installed on my box

**Comment by sudden6** [comment]
I'll test it in a VM

**Comment by sudden6** [comment]
hmm, in the VM where ffmpeg 2.8 is used, compilation fails with an unrelated error, so I can't test...

**Pull request merged**
