### PR TITLE
UI for autoaway

### PR DESCRIPTION
**Pull request by agilob**
addition to https://github.com/tux3/qTox/pull/441

autoaway

### CODE REVIEW

**Comment by tux3** [comment]
It doesn't actually reset the timer, does it ?

So if I set the auto-away to 2376 minutes by mistake then back to 1 minutes, it'll stay locked at 2376 until the next restart (or after 2376 minutes of inactivity!)

**Comment by agilob** [comment]
Should do the job now, @dubslow, would you like to add anything?

And.. I set maxmimum value to 600 minutes, I can change it to INT_MAX if you want, this artificial limit is useless I think but qtcreator made me to set anything there.

**Comment by dubslow** [comment]
FWIW, one day is a... _plausible_ auto away time, and that's somewhat more than 600, but I won't be miffed unless someone complains about it.

I'd be more likely to complain about the checkbox and int box not being on the same line, wasting oh-so-precious vertical space.

@tux3, there's at least one old issue about this that can be closed.

**Comment by tux3** [comment]
@dubslow thanks for the heads up, I closed #107

**Comment by dubslow** [comment]
Wait what? There isn't even a checkbox, I'm nuts.

Also, the minimum should be zero so it can be disabled. (The code already handles it.)

**Pull request merged**
