### PR TITLE
fix(platform): use result to remove -Wunused-result warning

### LINKED ISSUE #4699: -Werror with -Wstrict-overflow causes multiple build errors on release builds
##### Brief Description
Commit hash:  ab12555935fe5a39f1cb3470fb2daaed5b68ffc8

Reproducible: Always

##### Steps to reproduce

1. cmake -DCMAKE_BUILD_TYPE=Release .
2. make

##### Observed Behavior
The O2 optimization causes some assumptions by the compiler that then causes warnings. I see multiple warnings like "assuming signed overflow does not occur when assuming that ..." generated from -Werror=strict-overflow, stopping the build.

Some of the errors seem extremely minor, like looping on the size of a QVector which is of signed int type.

A couple examples:
```
[  9%] Building CXX object CMakeFiles/qtox_static.dir/src/core/coreav.cpp.o
/home/abilinski/build/qTox/src/chatlog/documentcache.cpp: In member function ‘QTextDocument* DocumentCache::pop()’:
/home/abilinski/build/qTox/src/chatlog/documentcache.cpp:29:16: error: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Werror=strict-overflow]
 QTextDocument* DocumentCache::pop()
                ^
/home/abilinski/build/qTox/src/chatlog/documentcache.cpp: In destructor ‘DocumentCache::~DocumentCache()’:
/home/abilinski/build/qTox/src/chatlog/documentcache.cpp:23:1: error: assuming signed overflow does not occur when assuming that (X - c) <= X is always true [-Werror=strict-overflow]
 DocumentCache::~DocumentCache()
 ^
cc1plus: all warnings being treated as errors
CMakeFiles/qtox_static.dir/build.make:602: recipe for target 'CMakeFiles/qtox_static.dir/src/chatlog/documentcache.cpp.o' failed
```

### LINKED ISSUE #4710: Unused fn return values in posixsignalnotifier.cpp
##### Brief Description
qTox build with `-pedantic` flag errors on unused results.

OS: Gentoo Linux
qTox version: v1.12.0
Commit hash:  8bc1fe7ee9f5b32ced0851c330b03efd14a090b4 + #4709
toxcore:  0.1.10
Qt:  5.7.1
GCC: 5.4.0

Reproducible: Always

##### Steps to reproduce

1. Run `cmake` with arg: `-DCMAKE_CXX_FLAGS="-Og -ggdb -fstack-protector-strong -pedantic"`

##### Observed Behavior
Build errors on unused result

##### Expected Behavior
There should be no unused results

##### Additional Info
Error:

```
/home/zetok/working/qtox-test/qTox/src/platform/posixsignalnotifier.cpp: In function ‘void detail::signalHandler(int)’:
/home/zetok/working/qtox-test/qTox/src/platform/posixsignalnotifier.cpp:56:60: error: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
     ::write(g_signalSocketPair[0], &signum, sizeof(signum));
                                                            ^
/home/zetok/working/qtox-test/qTox/src/platform/posixsignalnotifier.cpp: In member function ‘void PosixSignalNotifier::onSignalReceived()’:
/home/zetok/working/qtox-test/qTox/src/platform/posixsignalnotifier.cpp:112:67: error: ignoring return value of ‘ssize_t read(int, void*, size_t)’, declared with attribute warn_unused_result [-Werror=unused-result]
     ::read(detail::g_signalSocketPair[1], &signum, sizeof(signum));
                                                                   ^
cc1plus: all warnings being treated as errors
```

### PR DESCRIPTION
**Pull request by Talkless**
Check for write() and read() results and abort in case of unexpected
failure.

Without these checks, -Wunused-result is emitted on specific compiler configurations, after introducing #4581.

Fixes #4710
Partially fixes #4699

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4711)

### CODE REVIEW

**Comment by sudden6** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/platform/posixsignalnotifier.cpp, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/4711#-KvYdMOwEk1UBvV6X10o:-KvYdMOwEk1UBvV6X10p:b1z1zop) ([raw file](https://github.com/qtox/qtox/blob/beeb95a9e2125b6aeb1e487e761d7c8ebe5b5e17/src/platform/posixsignalnotifier.cpp#L57)):*
> ```cpp
> 
>     if(::write(g_signalSocketPair[0], &signum, sizeof(signum)) == -1) {
>         qFatal("Failed to write to signal socket, error = %d", errno);
> ```

I found no documentation about `qFatal` being safe in a signal handler, if you did please add a link as comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4711)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/platform/posixsignalnotifier.cpp, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/4711#-KvYdMOwEk1UBvV6X10o:-Kvc6L3QVpZVDcRVIIV7:b-zhlbkn) ([raw file](https://github.com/qtox/qtox/blob/beeb95a9e2125b6aeb1e487e761d7c8ebe5b5e17/src/platform/posixsignalnotifier.cpp#L57)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

I found no documentation about `qFatal` being safe in a signal handler, if you did please add a link as comment.
</blockquote></details>

Uhg, totally forgot about that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4711)*

**Comment by Talkless** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/platform/posixsignalnotifier.cpp, line 57 at r1](https://reviewable.io:443/reviews/qtox/qtox/4711#-KvYdMOwEk1UBvV6X10o:-Kvc9Kt_vMWdy1G9NRjM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/beeb95a9e2125b6aeb1e487e761d7c8ebe5b5e17/src/platform/posixsignalnotifier.cpp#L57)):*
<details><summary><i>Previously, Talkless (Vincas Dargis) wrote…</i></summary><blockquote>

Uhg, totally forgot about that.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4711)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4711#-:-KvnTbq7AbCXAgq8v4gA:b-jbsf8z)*

**Pull request merged**
