### PR TITLE
Added dynamic translation to status and username

### PR DESCRIPTION
**Pull request by TheNain38**
Could someone check before merging?

### CODE REVIEW

**Comment by agilob** [comment]
Thanks for your contribution!

**Comment by TheNain38** [comment]
qTox crashes on windows 7 after my PR got merged on 33418346256532231a72fcc859c922233aed020a

**Comment by tux3** [comment]
@agilob You didn't try building it before merging?
There's a blatant nullptr dereference, it would have crashed on startup on any platform.

If it's not a trivial fix, please test it before merging, just so you don't break the live build next time.

**Comment by agilob** [comment]
Sorry about that, I just checked source code changes and saw it builds on travis and I merged it. Might be worth adding [GUI started to travis](http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-GUI-%28e.g.-a-Web-browser%29) so we add:

```
sleep 10 && killall qtox & # delay kill tox by 10sec in background
./qTox
```

so travis will test if application starts correctly.

**Pull request merged**
