### PR TITLE
docs(README): list some of the ways to help qTox

### PR DESCRIPTION
**Pull request by zetok**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/3785)

### CODE REVIEW

**Comment by sudden6** [comment]
_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTKaZ-4pT_Ah3HxLSek:btalpc2) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_

> ``` Markdown
> * Fixing [easy issues]
> * [Testing] and [reporting bugs]
> * [Easy] translating
> ```

Maybe we can find something better than "Easy translating", I don't think that makes sense or is proper English.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTKcbS77ePzQbFuqEkZ:b8qecvf) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> Maybe we can find something better than "Easy translating", I don't think that makes sense or is proper English.
> </details>
> I think that it is correct, although it doesn't sound good. Any ideas with what it should be replaced?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by sudden6** [comment]
_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTKdSq1GFWxpY__u5AU:b25w95e) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> I think that it is correct, although it doesn't sound good. Any ideas with what it should be replaced?
> </details>
> For me it sounds kinda weird. Sadly I don't have a better idea, could you describe with some words what you mean with "easy translating"? Maybe that will help me find something.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTKfoDUZBlFOIEeYJNv:b6idqzm) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> For me it sounds kinda weird. Sadly I don't have a better idea, could you describe with some words what you mean with "easy translating"? Maybe that will help me find something.
> </details>
> Easy, as in, literally easy. I.e. translating & submitting the translation without using weblate is simply hard, and with weblate it's easy.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTKy4BVdZOEcGHm1ofj:b-gv1q06) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Easy, as in, literally easy. I.e. translating & submitting the translation without using weblate is simply hard, and with weblate it's easy.
> </details>
> `Translate with ease` / `Translate easily` ?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by sudden6** [comment]
_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTLEWn8hpt1MMPpQH2n:b4iw0j7) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> `Translate with ease` / `Translate easily` ?
> </details>
> `Translating is also easy`, `Translating is simple` ? with links on `easy`/`simple`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTLIiwDsHWpvkI8Jh84:bpj3pl4) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> `Translating is also easy`, `Translating is simple` ? with links on `easy`/`simple`?
> </details>
> Hmm, that doesn't really fit in with the sentence `Some of them are:`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by sudden6** [comment]
_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTLLLIfXmGeSi46Qvjw:b-f764pg) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, zetok wrote…</i></summary>



> Hmm, that doesn't really fit in with the sentence `Some of them are:`
> </details>
> True, but the first two don't fit the scheme too. Anyway then a possibility would be `Translating, it's easy`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by zetok** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

_[README.md, line 48 at r1](https://reviewable.io:443/reviews/qtox/qtox/3785#-KTKaZ-4pT_Ah3HxLSej:-KTLQ3y3GzdxuY4MdeUg:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6e5bfd35cdcaacb62cab731a8daa77cb7a536b6d/README.md#L48)):_
<details><summary>

<i>Previously, sudden6 wrote…</i></summary>



> True, but the first two don't fit the scheme too. Anyway then a possibility would be `Translating, it's easy`.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785)_

**Comment by sudden6** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/3785#-:-KTLWHy66e8j3aoqbEg2:bnfp4nl)_

**Pull request merged**
