### PR TITLE
fix(audio): Moved volume and gain defaults from OpenAL to the calling code

### PR DESCRIPTION
**Pull request by yurivict**
There is no need for all backends to reset their default volume and gain.

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4545)

### CODE REVIEW

**Comment by yurivict** [comment]
All uses of Settings and some other code should also be moved to the caller. For this PR I just picked the most visible and easy part.

**Comment by Diadlo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/audio/backend/openal.cpp, line 310 at r1](https://reviewable.io:443/reviews/qtox/qtox/4545#-Kq6vBHkrrR6Jd9awViw:-Kq6vBHkrrR6Jd9awVix:b-9elig8) ([raw file](https://github.com/qtox/qtox/blob/d59c7223895b9cca09fd98081657541976d09efb/src/audio/backend/openal.cpp#L310)):*
> ```cpp
> 
>     alGenSources(1, &alMainSource);
>     checkAlError();
> ```

Why `checkAlError()` removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4545)*

**Comment by yurivict** [comment]
*[src/audio/backend/openal.cpp, line 310 at r1](https://reviewable.io:443/reviews/qtox/qtox/4545#-Kq6vBHkrrR6Jd9awViw:-Kq6zYaVRkkDIvEx7B0W:b8ktm4m) ([raw file](https://github.com/qtox/qtox/blob/d59c7223895b9cca09fd98081657541976d09efb/src/audio/backend/openal.cpp#L310)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Why `checkAlError()` removed?
</blockquote></details>

It is OpenAL-specific error check after the operation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4545)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/audio/backend/openal.cpp, line 310 at r1](https://reviewable.io:443/reviews/qtox/qtox/4545#-Kq6vBHkrrR6Jd9awViw:-Kq74Es4rhVSAz3wrL2U:bj3zjw4) ([raw file](https://github.com/qtox/qtox/blob/d59c7223895b9cca09fd98081657541976d09efb/src/audio/backend/openal.cpp#L310)):*
<details><summary><i>Previously, yurivict wrote…</i></summary><blockquote>

It is OpenAL-specific error check after the operation.
</blockquote></details>

Sorry, diff shows, that error check removed before operation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4545#-:-Kq74iPE1nR0ajf4D7-y:b-jbsf8z)*

**Comment by yurivict** [comment]
*[src/audio/backend/openal.cpp, line 310 at r1](https://reviewable.io:443/reviews/qtox/qtox/4545#-Kq6vBHkrrR6Jd9awViw:-Kq8RbGq9qRmCXUdVOgW:bb534eh) ([raw file](https://github.com/qtox/qtox/blob/d59c7223895b9cca09fd98081657541976d09efb/src/audio/backend/openal.cpp#L310)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Sorry, diff shows, that error check removed before operation
</blockquote></details>

No, it's after the operation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4545)*

**Comment by sudden6** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/widget/form/settings/avform.cpp, line 474 at r1](https://reviewable.io:443/reviews/qtox/qtox/4545#-Kq8ZQQ-zKjP--wwJXd1:-Kq8ZQQ-zKjP--wwJXd2:b-l2yymu) ([raw file](https://github.com/qtox/qtox/blob/eabdf123f3e09344d972900d5b89f6a62dbaafb9/src/widget/form/settings/avform.cpp#L474)):*
> ```cpp
>     Audio& audio = Audio::getInstance();
>     audio.reinitInput(deviceName);
>     audio.setInputGain(Settings::getInstance().getAudioInGainDecibel());
> ```

`avform.cpp` isn't the correct place to restore volume, what if the user opens a call before looking at the settings?

Better place would be `Audio.getInstance()` to restore all audio settings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4545)*

**Comment by yurivict** [comment]
Yes, this has to do with problems in how audio devices are initialized in general.

```getInstance()``` is a wrong place. Initialization should be called once when the client is initialized, and once when the user changes the audio device.

I will modify the PR.

**Comment by yurivict** [comment]
I will submit a new PR.
Will change Audio interface, will move initialization into one place, and will fix the problem with the changed device set (https://github.com/qTox/qTox/issues/4537)

**Pull request closed without merging**
