### PR TITLE
chore(release): Update README download links and MAINTAINING.md

### PR DESCRIPTION
**Pull request by anthonybilinski**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5095)

### CODE REVIEW

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5095#-:-LAsa5qT9mO-oNKluX_6:b-jbsf8z)*

**Comment by Diadlo** [comment]
Maybe add it to `update-version.sh` script?

**Comment by anthonybilinski** [comment]
Added to `update-version.sh` script and removed the `instructions` to update README links from `MAINTAINING`

**Comment by Diadlo** [comment]
@anthonybilinski Seems changes of `MAINTAINING.md` still here

**Comment by anthonybilinski** [comment]
@Diadlo it now mentions to update tox.chat only, instead of both README.md and tox.chat.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5095#-:-LAvPXRPBuIsWK-6BM_N:b-jbsf8z)*

**Comment by Diadlo** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[tools/update-versions.sh, line 52 at r2](https://reviewable.io/reviews/qtox/qtox/5095#-LAvPggs7TvdDVMDUV7r:-LAvPgguAsl5bNufO_iP:bwgpm5o) ([raw file](https://github.com/qtox/qtox/blob/65d66576f98635fe8453381e8627ca16efa740d8/tools/update-versions.sh#L52)):*
> ```Shell
> update_readme() {
>     cd "$BASE_DIR"
>     sed -ri "s|(github.com/qTox/qTox/releases/download/v)[0-9]+\.[0-9]+\.[0-9]+|\1$@|g" README.md
> ```

What about versions with `patch=0`? AFAIK it will be `v1.2` instead of `v1.2.0` if so, make last (and middle?) part optional

---


*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5095)*

**Comment by anthonybilinski** [comment]
I think with [semantic versioning](https://semver.org/), which I think we're following, we always have a patch version present, even if 0. This has been the case for us from v1.3.0 to v1.15.0, so I'm going to leave with the check for patch version. I also made the version checking pattern common between regex and input checking, so it won't allow setting the version to i.e. `1.6`, only `1.6.0`.

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io/reviews/qtox/qtox/5095#-:-LAy_H2UC-ujsSVyczyd:b-jbsf8z)*

**Pull request merged**
