### PR TITLE
QFormLayout for Public Information

### PR DESCRIPTION
**Pull request by saneki**
Current:
qtox-old-crop

New:
qtox-new-crop

### CODE REVIEW

**Comment by tux3** [comment]
I have no objections, but I'd like more opinions on the design change because I have no tastes.

**Comment by agilob** [comment]
If you could make avatar be the same size as the form it would be great! Just fit it to height of the form.

**Comment by TheLastProject** [comment]
When aligned correctly, it's surely fine. I'd like the colon to be removed though. So not "Name:" but simply "Name".

**Comment by saneki** [comment]
Update (vertically aligned, avatar size is the same):
qtox-new-2-crop

@TheLastProject I added colons after the fieldnames for consistency, as they're used in the options forms.

**Pull request merged**
