### PR TITLE
refactor(video): rework video mode handling

### PR DESCRIPTION
**Pull request by sudden6**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4880)

### CODE REVIEW

**Comment by Talkless** [comment]
Review status: 0 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/platform/camera/avfoundation.mm, line 72 at r1](https://reviewable.io:443/reviews/qtox/qtox/4880#-L2jqqBECWY6HYCrrOhM:-L2jqqBECWY6HYCrrOhN:b-rw3xco) ([raw file](https://github.com/qtox/qtox/blob/167bb6384b32ea3899ca2080203efc8a2dd1cc83/src/platform/camera/avfoundation.mm#L72)):*
> ```XML
>             mode.height = dimensions.height;
> 
>             for (AVFrameRateRange* range in format.videoSupportedFrameRateRanges) {
> ```

maybe **const** AVFrameRateRange* range

---

*[src/widget/form/settings/avform.cpp, line 300 at r1](https://reviewable.io:443/reviews/qtox/qtox/4880#-L2jtohqpigrXJKgjN3p:-L2jtohqpigrXJKgjN3q:b-ow0g4o) ([raw file](https://github.com/qtox/qtox/blob/167bb6384b32ea3899ca2080203efc8a2dd1cc83/src/widget/form/settings/avform.cpp#L300)):*
> ```cpp
> 
>     // select FPS near target
>     for(auto& mode : allVideoModes) {
> ```

spaces after for, for, and if

---

*[src/widget/form/settings/avform.cpp, line 351 at r1](https://reviewable.io:443/reviews/qtox/qtox/4880#-L2jttzxaJdlvy4b3f7F:-L2jttzxaJdlvy4b3f7G:b-dz7sg6) ([raw file](https://github.com/qtox/qtox/blob/167bb6384b32ea3899ca2080203efc8a2dd1cc83/src/widget/form/settings/avform.cpp#L351)):*
> ```cpp
>         VideoMode mode = videoModes[i];
>         // INFINITY is used to ensure the float comparison is false
>         float modeFPS = mode ? mode.availableFPS.at(mode.selectedFPSIdx) : +INFINITY;
> ```

const float

---

*[src/widget/form/settings/avform.cpp, line 368 at r1](https://reviewable.io:443/reviews/qtox/qtox/4880#-L2jtysEs7flYoPRnsoE:-L2jtysEs7flYoPRnsoF:b-dz7sg6) ([raw file](https://github.com/qtox/qtox/blob/167bb6384b32ea3899ca2080203efc8a2dd1cc83/src/widget/form/settings/avform.cpp#L368)):*
> ```cpp
>     for (int i = 0; i < videoModes.size(); ++i) {
>         VideoMode mode = videoModes[i];
>         float fps = mode.selectedFPSIdx >= 0 ? mode.availableFPS.at(mode.selectedFPSIdx) : -1.0f;
> ```

const float

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4880)*

**Comment by Talkless** [comment]
Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---

*[src/video/cameradevice.cpp, line 156 at r1](https://reviewable.io:443/reviews/qtox/qtox/4880#-L2p56myEM7cqo0Myn2K:-L2p56mz43hX6GhSQsa5:basj9xz) ([raw file](https://github.com/qtox/qtox/blob/167bb6384b32ea3899ca2080203efc8a2dd1cc83/src/video/cameradevice.cpp#L156)):*
> ```cpp
>     }
> 
>     float FPS = 15;
> ```

This could be updated to use [ES.28: Use lambdas for complex initialization, especially of const variables](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es28-use-lambdas-for-complex-initialization-especially-of-const-variables) if you care enought:

const float FPS  = [&mode]() {
if (mode.selectedFPSIdx >= 0) {
        return mode.availableFPS.at(mode.selectedFPSIdx);
    } else if (mode.defaultFPS > 0){
        return mode.defaultFPS;
    } else {       
        qWarning() << "VideoMode could be invalid!";
        return 15;
}

And it would be nice to have this `15` a named constant instead of magic value.

---

*[src/video/videomode.h, line 34 at r1](https://reviewable.io:443/reviews/qtox/qtox/4880#-L2p6ED0ytUUGccGL_rs:-L2p6ED0ytUUGccGL_rt:blce5gy) ([raw file](https://github.com/qtox/qtox/blob/167bb6384b32ea3899ca2080203efc8a2dd1cc83/src/video/videomode.h#L34)):*
> ```objc
>     float defaultFPS = -1.0f;
>     int selectedFPSIdx = -1;
>     QVector<float> availableFPS{};
> ```

`{}` is redundant here, it will be default-constructer correctly.. by default :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4880)*

**Comment by sudden6** [comment]
@Talkless Thx, will include the changes before merging.

Btw, do you want to join any of our Teams https://github.com/orgs/qTox/teams ?

**Comment by Talkless** [comment]
> Btw, do you want to join any of our Teams https://github.com/orgs/qTox/teams ?

What does joining a team means?

P.S. that page is not accessible for me:
> You’re not a member of any teams in this organization.

**Comment by sudden6** [comment]
> What does joining a team means?

It provides a common chat and one can @ mention a whole group of people. For example, currently 
it's quite hard to reach anyone involved with qTox without opening an issue and and mentioning their username.

> P.S. that page is not accessible for me:

Sorry didn't know that. Currently there is a team for Linux/Windows/Mac/Website and the Core devs who have commit rights to the repo. This isn't fully fleshed out yet and I'm just starting to invite active people so I can find them in one place.

**Comment by Talkless** [comment]
> It provides a common chat and one can @ mention a whole group of people.

That's useful.

> This isn't fully fleshed out yet and I'm just starting to invite active people so I can find them in one place.

Cool, You could add me into Linux team then.

**Pull request closed without merging**
