### PR TITLE
fix(video): don't use pointers to temporary objects

### LINKED ISSUE #4764: qTox video-calls issue
##### Brief Description

OS: Windows 7 Ultimate SP1
qTox version: v1.12.1
toxcore: 0.1.10
Qt: 5.6.3

After the update video-calls are not working. There is no image from the camera on the screen.

That's what we can see.

Camera itself is working, I've checked it. So, there is something with qTox. I think.

### PR DESCRIPTION
**Pull request by sudden6**
fixes #4764

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4796)

### CODE REVIEW

**Comment by Diadlo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/video/cameradevice.cpp, line 152 at r1](https://reviewable.io:443/reviews/qtox/qtox/4796#-Kyc86evqWcGRhkBlNc4:-Kyc86ewLQgsOoU52jQz:b-fc1kwz) ([raw file](https://github.com/qtox/qtox/blob/112b1bd544874ce14cd0b662464eac1e92db7688/src/video/cameradevice.cpp#L152)):*
> ```cpp
>     }
> 
>     std::string videoSize = QString("%1x%2").arg(screen.width()).arg(screen.height()).toStdString();
> ```

What about `QStringLiteral`

---

*[src/video/cameradevice.cpp, line 153 at r1](https://reviewable.io:443/reviews/qtox/qtox/4796#-Kyc83NIV3KshfEBCQss:-Kyc83NJi4jGpfGRvaMP:bjh7hbr) ([raw file](https://github.com/qtox/qtox/blob/112b1bd544874ce14cd0b662464eac1e92db7688/src/video/cameradevice.cpp#L153)):*
> ```cpp
> 
>     std::string videoSize = QString("%1x%2").arg(screen.width()).arg(screen.height()).toStdString();
>     std::string framerate = QString().setNum(FPS).toStdString();
> ```

`QString{}`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4796)*

**Comment by Diadlo** [comment]
And fix [travis](https://travis-ci.org/qTox/qTox/jobs/300399579#L2729)

**Comment by sudden6** [comment]
found some more of the same mistakes

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/video/cameradevice.cpp, line 152 at r1](https://reviewable.io:443/reviews/qtox/qtox/4796#-Kyc86evqWcGRhkBlNc4:-KycIJQmoxgdP8xmSqEP:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/112b1bd544874ce14cd0b662464eac1e92db7688/src/video/cameradevice.cpp#L152)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

What about `QStringLiteral`
</blockquote></details>

Done.

---

*[src/video/cameradevice.cpp, line 153 at r1](https://reviewable.io:443/reviews/qtox/qtox/4796#-Kyc83NIV3KshfEBCQss:-KycIK0eYAZchwIRZZjv:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/112b1bd544874ce14cd0b662464eac1e92db7688/src/video/cameradevice.cpp#L153)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

`QString{}`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4796#-:-KycIMDNwkZ1FpekW2w3:b-qhpbwn)*

**Comment by Diadlo** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video/cameradevice.cpp, line 101 at r2](https://reviewable.io:443/reviews/qtox/qtox/4796#-KydgumjSqKXVHjnFgJQ:-KydgumjSqKXVHjnFgJR:b-lrco5l) ([raw file](https://github.com/qtox/qtox/blob/bbf72705b5936a40e054b57c2e4ad17d46d9bcce/src/video/cameradevice.cpp#L101)):*
> ```cpp
>     }
> 
>     if (avformat_open_input(&fctx, devName.toStdString().c_str(), format, options) < 0)
> ```

Forget one :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4796)*

**Comment by sudden6** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/video/cameradevice.cpp, line 101 at r2](https://reviewable.io:443/reviews/qtox/qtox/4796#-KydgumjSqKXVHjnFgJQ:-KyeQ7IO1hqvUE70Tasw:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/bbf72705b5936a40e054b57c2e4ad17d46d9bcce/src/video/cameradevice.cpp#L101)):*
<details><summary><i>Previously, Diadlo (Polshakov Dmitry) wrote…</i></summary><blockquote>

Forget one :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4796)*

**Comment by Diadlo** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4796#-:-KyeSulAk3rhiHxg4TET:b-jbsf8z)*

**Pull request merged**
