### PR TITLE
fix(avatar): set friend to identicon on empty avatar receipt

### LINKED ISSUE #4724: Identicon does not display in contact list for friends running older client
##### Brief Description

OS: Ubuntu 16.04
Commit hash:  42c4a748268ecbf53f0c882d0db4bd9de2e90ed5

Reproducible: Always

##### Steps to reproduce

1. Run client past identicon addition
2. Have contact come online running client before identicon addition

##### Observed Behavior
Before friend comes online, their avatar is shown as their identicon. Once they come online, in group list, they have the old default avatar. Selecting and de-selecting does not change it. Clicking "show details" on the friend shows the identicon, not the default avatar.

##### Expected Behavior
Identicon is showed in all places for the friend.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fixes #4724

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4769)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core/corefile.cpp, line 290 at r1](https://reviewable.io:443/reviews/qtox/qtox/4769#-KxXXnA7tozeF_S_Wrrt:-KxXXnA8KkDA2alE1yTJ:bfi4bg3) ([raw file](https://github.com/qtox/qtox/blob/46e715a1cffe12f4b0fa50f07917e8b2113dc38f/src/core/corefile.cpp#L290)):*
> ```cpp
>             QByteArray identiconData{(char*)identiconImage.bits(),identiconImage.byteCount()};
>             QByteArray identiconHash{TOX_HASH_LENGTH, 0};
>             tox_hash((uint8_t*)identiconHash.data(), (uint8_t*)identiconData.data(), identiconData.size());
> ```

Why do you cast `identiconImage` byte data back and forth? Extract `identiconImage.bits()` into separate const (but if you do not have to change this data, use `constBits()`). And use `reinterpret_cast` instead of C-style or even better `static_cast` twice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4769)*

**Comment by noavarice** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4769)*

**Comment by sudden6** [comment]
I think this is a bad idea to introduce a dependency on `Identicon` into `CoreFile`, better find a way to modify `Profile` to achieve the same thing.

**Comment by sudden6** [comment]
I'm closing this, since the implementation is a bad way and no activity since more than two weeks.

**Comment by anthonybilinski** [comment]
Second go at fixing this a year later, less half-assed this time.

* Removed CoreFile's friendAvatarChangedDeprecated in passing.
* All friend avatar changes and removals go through Profile, so that Profile can manage identicons.
* Split the concept of "changed" and "removed" into "changed", "set", and "removed", so that those who care only what the avatar is can connect to "changed", but those who care if it's default so they can change the avatar on active can connect to "set" and "removed" instead.
* Change to "changed" means that each user of avatar doens't need to re-create default avatar from path. Also means that classes that forgot to create default from path like groupnetcamview and netcamview will now see default avatar when avatar is removed and identicons are disabled.

**Review by sudden6 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/4769)* status: 0 of 1 LGTMs obtained

___
*[src/widget/friendwidget.cpp, line 28 at r2](https://reviewable.io/reviews/qtox/qtox/4769#-LMaoqI98W_cs_Jzfu5O:-LMaoqI98W_cs_Jzfu5P:b-hn9slx) ([raw file](https://github.com/qtox/qtox/blob/79cfca09688d8398bd83804e0008c9e2978e3b50/src/widget/friendwidget.cpp#L28)):*
> ```cpp
> #include "src/core/core.h"
> #include "src/friendlist.h"
> #include "src/nexus.h"
> ```

why those additional includes?

**Review by anthonybilinski — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/4769)* status: 0 of 1 LGTMs obtained

___
*[src/core/corefile.cpp, line 290 at r1](https://reviewable.io/reviews/qtox/qtox/4769#-KxXXnA7tozeF_S_Wrrt:-LMarwfV8LYbxvmKMhPr:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/46e715a1cffe12f4b0fa50f07917e8b2113dc38f/src/core/corefile.cpp#L290)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why do you cast `identiconImage` byte data back and forth? Extract `identiconImage.bits()` into separate const (but if you do not have to change this data, use `constBits()`). And use `reinterpret_cast` instead of C-style or even better `static_cast` twice
</blockquote></details>

Done.
___
*[src/widget/friendwidget.cpp, line 28 at r2](https://reviewable.io/reviews/qtox/qtox/4769#-LMaoqI98W_cs_Jzfu5O:-LMarxjq-o7RbeOExfEN:b-my8yg5) ([raw file](https://github.com/qtox/qtox/blob/79cfca09688d8398bd83804e0008c9e2978e3b50/src/widget/friendwidget.cpp#L28)):*
<details><summary><i>Previously, sudden6 wrote…</i></summary><blockquote>

why those additional includes?
</blockquote></details>

Whoops, removed.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 2 of 17 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/4769#-:-LMaw7xt0bkz1nP0S-ca:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
