### PR TITLE
Fixed translation errors.

### PR DESCRIPTION
**Pull request by Lednerb**
Added / Fixed Strings in the German translation.

### CODE REVIEW

**Comment by Lednerb** [comment]
How can i translate the NO-Button?

no-button

Should be nearby the tox1-protocol prompt.

**Comment by tux3** [comment]
You can't change the text on the button if that's what you're asking, not without some code changes anyway. What would you put instead ?

**Comment by Lednerb** [comment]
Yes, this was what i wanted to ask.
I wanted to change "No" to the German  "Nein".

Edit: Can be merged, so at least the text is translated.

**Comment by tux3** [comment]
Note: There is a way to translate message box buttons using Qt's official translation files as well as our own.

**Pull request merged**
