### PR TITLE
refactor(friendwidget): FriendWidget refactoring

### PR DESCRIPTION
**Pull request by Diadlo**
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/4540)

### CODE REVIEW

**Comment by noavarice** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/widget/friendwidget.cpp, line 105 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyWm48kanApQYYdXkS:-KpyWm48kanApQYYdXkT:b-gsztxm) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L105)):*
> ```cpp
>     QAction* removeChatWindow = nullptr;
> 
>     uint32_t friendId = frnd->getFriendId();
> ```

Is it the same ID as `friendId` class field?

---

*[src/widget/friendwidget.cpp, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyYAIws6NK7-r7lpjJ:-KpyYAIws6NK7-r7lpjK:bs04mkj) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L109)):*
> ```cpp
> 
>     bool notAlone = contentDialog != nullptr && contentDialog->chatroomWidgetCount() > 1;
>     if (!contentDialog || notAlone) {
> ```

Maybe make `bool nullContentDialog = contentDialog == nullptr;` and use it over again? Also this condition guard actually looks like `if (contentDialog == nullptr || contentDialog != nullptr &&  contentDialog->chatroomWidgetCount() > 1` so you can replace it with `if (nullContentDialog ||  contentDialog->chatroomWidgetCount() > 1)`

---

*[src/widget/friendwidget.cpp, line 113 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyXnuKa3uNvCoBBrxL:-KpyXnuLwI_IeNWuhRr5:b-8yjnq) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L113)):*
> ```cpp
>     }
> 
>     bool hasFriendWidget = contentDialog->hasFriendWidget(friendId, this);
> ```

Potential `nullptr` dereferencing since `contentDialog != nullptr` is not checked anymore

---

*[src/widget/friendwidget.cpp, line 149 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyZxX7bxfSYyd-IU5m:-KpyZxX7bxfSYyd-IU5n:b-fvwb0s) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L149)):*
> ```cpp
>     QAction* removeCircleAction = nullptr;
>     if (circleId != -1) {
>         const QString circleName = Settings::getInstance().getCircleName(circleId);
> ```

Move `Settings::getInstance()` to `const Settings[&*]`

---

*[src/widget/friendwidget.cpp, line 158 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-Kpy_PpfgtlHbQKhjMth:-Kpy_PpfgtlHbQKhjMti:b-q5cl7) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L158)):*
> ```cpp
>     QMap<QAction*, int> circleActions;
> 
>     for (int i = 0; i < Settings::getInstance().getCircleCount(); ++i) {
> ```

Same about `Settings`

---

*[src/widget/friendwidget.cpp, line 303 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyaNlsFYBHCmtYc4k7:-KpyaNlsFYBHCmtYc4k8:b62zdtf) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L303)):*
> ```cpp
> void FriendWidget::updateStatusLight()
> {
>     const QString statuses[] = {
> ```

Why does not make it `static`?

---

*[src/widget/friendwidget.cpp, line 337 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpybEI9UeJS_9Tq90XF:-KpybEI9UeJS_9Tq90XG:b-ii33a8) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L337)):*
> ```cpp
>     const bool event = frnd->getEventFlag();
> 
>     const QMap<Status, QString> names = {
> ```

Same as previous. Maybe even make it array, decide on your own

---

*[src/widget/friendwidget.cpp, line 375 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpybrAwIcIHaL5PL32_:-KpybrAwIcIHaL5PL32a:bl3qvhj) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L375)):*
> ```cpp
> void FriendWidget::onAvatarChange(int friendId, const QPixmap& pic)
> {
>     if (friendId != frnd->getFriendId()) {
> ```

Same about `frnd->getFriendId()` and `friendId` class field

---

*[src/widget/friendwidget.cpp, line 385 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-Kpyc-6BEA2Hr58mfAy0:-Kpyc-6BEA2Hr58mfAy1:b36aixk) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L385)):*
> ```cpp
> void FriendWidget::onAvatarRemoved(int friendId)
> {
>     if (friendId != frnd->getFriendId()) {
> ```

Same as before

---

*[src/widget/friendwidget.cpp, line 426 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyewUmCP14lqBLgmA0:-KpyewUmCP14lqBLgmA1:b-8lncyt) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L426)):*
> ```cpp
>     QString alias = _alias.left(tox_max_name_length());
>     frnd->setAlias(alias);
>     Settings::getInstance().setFriendAlias(frnd->getPublicKey(), alias);
> ```

Replace `Settings::getInstance` if you want

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4540)*

**Comment by Diadlo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/widget/friendwidget.cpp, line 105 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyWm48kanApQYYdXkS:-KpzK8-Q6RxTokiJtEPH:bdoffpp) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L105)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Is it the same ID as `friendId` class field?
</blockquote></details>

Class field removed

---

*[src/widget/friendwidget.cpp, line 109 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyYAIws6NK7-r7lpjJ:-Kq1ZN2zstNOWdoln_t9:bybyn55) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L109)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Maybe make `bool nullContentDialog = contentDialog == nullptr;` and use it over again? Also this condition guard actually looks like `if (contentDialog == nullptr || contentDialog != nullptr &&  contentDialog->chatroomWidgetCount() > 1` so you can replace it with `if (nullContentDialog ||  contentDialog->chatroomWidgetCount() > 1)`
</blockquote></details>

Now using pointer as a bool

---

*[src/widget/friendwidget.cpp, line 113 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyXnuKa3uNvCoBBrxL:-Kq1ZVa4AftosFI74KDj:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L113)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Potential `nullptr` dereferencing since `contentDialog != nullptr` is not checked anymore
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 149 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyZxX7bxfSYyd-IU5m:-Kq1Zo_eSxdv3WlZcF-k:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L149)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Move `Settings::getInstance()` to `const Settings[&*]`
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 158 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-Kpy_PpfgtlHbQKhjMth:-Kq1Zp_4RNXMS5Robf6V:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L158)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same about `Settings`
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 303 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyaNlsFYBHCmtYc4k7:-Kq1_-HlcMDevfYIvr9Q:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L303)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Why does not make it `static`?
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 337 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpybEI9UeJS_9Tq90XF:-Kq1_1T7SbEf9MwMFGEM:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L337)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as previous. Maybe even make it array, decide on your own
</blockquote></details>

Done.

---

*[src/widget/friendwidget.cpp, line 375 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpybrAwIcIHaL5PL32_:-Kq1_HtsbtRGq5tT4-cF:b-4iikej) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L375)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same about `frnd->getFriendId()` and `friendId` class field
</blockquote></details>

Field removed

---

*[src/widget/friendwidget.cpp, line 385 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-Kpyc-6BEA2Hr58mfAy0:-Kq1_JJABFzzbLC8rQ3F:b-4iikej) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L385)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Same as before
</blockquote></details>

Field removed

---

*[src/widget/friendwidget.cpp, line 426 at r1](https://reviewable.io:443/reviews/qtox/qtox/4540#-KpyewUmCP14lqBLgmA0:-Kq1_S9c1V9D9QFMz5M6:b-896fix) ([raw file](https://github.com/qtox/qtox/blob/6ff85090650ca68db9e5347b6298b4ee201e9bd1/src/widget/friendwidget.cpp#L426)):*
<details><summary><i>Previously, noavarice wrote…</i></summary><blockquote>

Replace `Settings::getInstance` if you want
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4540)*

**Comment by noavarice** [comment]
:lgtm_strong:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4540#-:-Kq2KDI0qCD3tTT-zn80:b-jbsf8z)*

**Comment by sudden6** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/4540#-:-Kq8Xp9FqDf3yIOEOA4e:b-jbsf8z)*

**Comment by Diadlo** [comment]
Closes #4547

**Pull request merged**
